### PR TITLE
Fix #3786: Fix regex checks for translated strings

### LINKED ISSUE #3786: Regex checks fail for translations
The new regex checks introduced in #3754 are incorrectly failing for translatewiki (the pattern is set up incorrectly). See: #3687

### PR DESCRIPTION
**Pull request by BenHenning**
## Explanation

Fixes #3786

#3754 introduced new regex checks to make sure translated strings go into the correct XML files, but the check didn't quite work for translated versions of strings.xml. However, the existing regex check didn't have support for matching against file patterns when exempting files (which is needed in this case since the check should exclude translated values directories).

The changes to the check include:
- Adding support for exempting files by one or more patterns
- Rearranging the logic to cache regex pattern compilation & file reading to avoid repeating these. This should be a nice performance improvement, but one drawback is the current implementation requires reading whole files into memory. Given we don't have any super large files in the codebase, this is probably fine. A future improvement would be to parallelize the file searching.

Note that one behavior change with the changes above is that failures will now be organized by file rather than by check (i.e. all failures for a particular file will be printed in order of that file's lines rather than in order of the checks).

See #3764 for a passing demonstration of the check (since the check is currently passing on develop; this is only an issue when trying to merge #3687--the test branch combines this & that branch). Also, new tests were added (one specifically for validating this case). See this test fail/pass without/with the regex change:

regex_test_failing
_Test failing with the old pattern_

regex_test_passing
_Test passing with the new pattern_

Finally, per the review an additional check was added to prohibited nested resource directories to simplify the set of potential matches for strings.xml (i.e. to ensure strings.xml must live immediately under a 'values-<lang>-r<region>/' directory structure).

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only
N/A

### CODE REVIEW

File: scripts/src/javatests/org/oppia/android/scripts/regex/RegexPatternValidationCheckTest.kt [hunk 1]
```diff
@@ -828,6 +828,30 @@ class RegexPatternValidationCheckTest {
...
+
+    runScript()
+
+    assertThat(outContent.toString().trim()).isEqualTo(REGEX_CHECK_PASSED_OUTPUT_INDICATOR)
+  }
+
+  @Test
+  fun testFileContent_translatableString_inTranslatedPrimaryStringsFile_fileContentIsCorrect() {
+    val prohibitedContent = "<string name=\"test\">Translatable</string>"
+    tempFolder.newFolder("testfiles", "app", "src", "main", "res", "values-ar")
```
Comment (FareesHussain) [inline scripts/src/javatests/org/oppia/android/scripts/regex/RegexPatternValidationCheckTest.kt:901]: can we have a test case for 

`app/src/main/res/values-ar/<str>/strings.xml` too

**Review by FareesHussain — CHANGES_REQUESTED** [review]
LGTM, 
I guess some test cases are needed
since we don't have a test case for the paths where there is a package between 
`values` and `strings.xml`

File: scripts/src/javatests/org/oppia/android/scripts/regex/RegexPatternValidationCheckTest.kt (hunk 1 above)
Comment (BenHenning) [reply scripts/src/javatests/org/oppia/android/scripts/regex/RegexPatternValidationCheckTest.kt:901]: Is this actually allowed by Android resources? I was under the impression that value files should generally live directly under their respective values folders?

**Comment by BenHenning** [comment]
Hmm https://stackoverflow.com/questions/4930398/can-the-android-layout-folder-contain-subfolders lays out contradictory information. I'm actually thinking that maybe we need a check to prohibit subdirectories instead of supporting subdirectories in these types of patterns.

File: scripts/src/javatests/org/oppia/android/scripts/regex/RegexPatternValidationCheckTest.kt (hunk 1 above)
Comment (BenHenning) [reply scripts/src/javatests/org/oppia/android/scripts/regex/RegexPatternValidationCheckTest.kt:901]: Hmm https://stackoverflow.com/questions/4930398/can-the-android-layout-folder-contain-subfolders lays out contradictory information. I'm actually thinking that maybe we need a check to prohibit subdirectories instead of supporting subdirectories in these types of patterns.

Comment (FareesHussain) [reply scripts/src/javatests/org/oppia/android/scripts/regex/RegexPatternValidationCheckTest.kt:901]: image
This is the new android studio template for new projects 
I guess it is allowed

Comment (BenHenning) [reply scripts/src/javatests/org/oppia/android/scripts/regex/RegexPatternValidationCheckTest.kt:901]: @FareesHussain is that representing directory structure? That doesn't seem right at face value since themes.xml (night) means values-night/themes.xml. What's the directory structure for that folder ('project view' not 'Android view')?

Comment (FareesHussain) [reply scripts/src/javatests/org/oppia/android/scripts/regex/RegexPatternValidationCheckTest.kt:901]: Ah my bad, it is values-night/themes.xml

Comment (BenHenning) [reply scripts/src/javatests/org/oppia/android/scripts/regex/RegexPatternValidationCheckTest.kt:901]: New check added.

**Comment by BenHenning** [comment]
New check has been added. Thanks @FareesHussain! PTAL.

**Review by FareesHussain — APPROVED** [review]
LGTM, thanks

**Comment by BenHenning** [comment]
Thanks again @FareesHussain!
