### PR TITLE
Fixes # 1223: Add DragAndDropSortInputViewModel

### LINKED ISSUE #1223: Add DragDropSort item view
Add DragDropSort item view in exploration and it's corresponding ViewModel to handle all the things related to drag-drop sort

**Target PR date**: 30 May 2020
**Target completion date**: 4 June 2020

### PR DESCRIPTION
**Pull request by aggarwalpulkit596**
## Explanation

Fixes #1223 

In this PR I've added support for drag-drop interaction which you can play out using the prototype exploration.
Steps to try out drag-drop interaction

1. Select the first topic, go to lessons.
2. Open the first story, first topic -> Prototype Exploration
3. Play out the entire question it will in the last of the topic.
4. Long press item to drag items

Mocks -> https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/45195f06-0c1e-487e-9d86-918b9bf6d76f/PM-Q7-Drag-Drop-No-Answer-13
## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

File: app/src/main/java/org/oppia/app/player/state/itemviewmodel/DragDropInteractionContentViewModel.kt [hunk 1]
```diff
@@ -0,0 +1,10 @@
+package org.oppia.app.player.state.itemviewmodel
+
+import org.oppia.app.viewmodel.ObservableViewModel
+
+/** [ObservableViewModel] for MultipleChoiceInput values or ItemSelectionInput values. */
```
Comment (aggarwalpulkit596) [inline app/src/main/java/org/oppia/app/player/state/itemviewmodel/DragDropInteractionContentViewModel.kt]: Will fix all docs

File: .idea/gradle.xml [hunk 2]
```diff
@@ -20,7 +20,8 @@
           </set>
         </option>
         <option name="resolveModulePerSourceSet" value="false" />
+        <option name="useQualifiedModuleNames" value="true" />
```
Comment (aggarwalpulkit596) [inline .idea/gradle.xml]: I'll remove this change

File: domain/src/main/assets/ratios_exploration1.json [hunk 3]
```diff
@@ -406,7 +406,7 @@
           "param_changes": [],
           "feedback": {
             "content_id": "default_outcome",
-            "html": "<p>No, that is not correct. If you don't know how to solve this question, try playing the <oppia-noninteractive-link text-with-value=\"&amp;quot;\\&amp;quot;What is a Ratio?\\&amp;quot; lesson&amp;quot;\" url-with-value=\"&amp;quot;https://www.oppia.org/explore/2mzzFVDLuAj8&amp;quot;\"></oppia-noninteractive-link>.</p>"
+            "html": "<p>No, that is not correct. If you don't know how to solve this question, try playing the <oppia-noninteractive-link text-with-value=\"&amp;quot;\\&amp;quot;What is a Ratio?\\&amp;quot; lesson&amp;quot;\" url-with-value=\"&amp;quot;https://www.oppia.org/explore/drag_and_drop_test_exploration&amp;quot;\"></oppia-noninteractive-link>.</p>"
```
Comment (aggarwalpulkit596) [inline domain/src/main/assets/ratios_exploration1.json]: I'll remove this change

**Comment by vinitamurthi** [comment]
Why are we skipping CI here?

**Comment by aggarwalpulkit596** [comment]
Untill the PR is ready for review i thought it's better to skip CI😅

**Comment by BenHenning** [comment]
PR looks good at a high-level; feel free to start adding tests.

**Comment by BenHenning** [comment]
@rt4914 could you take a first pass on this?

File: app/src/main/java/org/oppia/app/player/state/DragDropSortInteractionView.kt [hunk 4]
```diff
@@ -0,0 +1,94 @@
...
+
+/**
+ * A custom [RecyclerView] for displaying a list of items that can be re-ordered using
+ * [DragItemTouchHelperCallback].
+ */
+class DragDropSortInteractionView @JvmOverloads constructor(
+  context: Context, attrs: AttributeSet? = null, defStyleAttr: Int = 0
+) : RecyclerView(context, attrs, defStyleAttr) {
+
+  @Inject lateinit var htmlParserFactory: HtmlParser.Factory
```
Comment (rt4914) [inline app/src/main/java/org/oppia/app/player/state/DragDropSortInteractionView.kt]: Convert this to multiple lines as the ktlint does formatting like this:
```
@Inject 
lateinit var htmlParserFactory: HtmlParser.Factory
```

File: app/src/main/java/org/oppia/app/player/state/DragDropSortInteractionView.kt [hunk 5]
```diff
@@ -0,0 +1,94 @@
...
+            htmlParserFactory.create(resourceBucketName, entityType, entityId, /* imageCenterAlign= */ false)
+              .parseOppiaHtml(
+                viewModel.htmlContent.htmlList.joinToString(separator = "<br>"), binding.dragDropContentTextView
+              )
+          binding.viewModel = viewModel
+        }
+      )
+      .build()
+  }
+
```
Comment (rt4914) [inline app/src/main/java/org/oppia/app/player/state/DragDropSortInteractionView.kt]: Remove this extra blank line.

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

File: app/src/main/res/layout/drag_drop_interaction_items.xml [hunk 6]
```diff
@@ -0,0 +1,39 @@
...
+
+  <LinearLayout
+    android:id="@+id/drag_drop_item_container"
+    android:layout_width="match_parent"
+    android:layout_height="wrap_content"
+    android:layout_margin="4dp"
+    android:gravity="center_vertical">
+
+    <TextView
+      android:id="@+id/drag_drop_content_text_view"
```
Comment (BenHenning) [inline app/src/main/res/layout/drag_drop_interaction_items.xml:24]: Per our discussion, are you planning to introduce the recycler view version of this in a follow up PR? If so, please add a TODO here to track that.

File: app/src/main/res/layout/drag_drop_interaction_items.xml [hunk 7]
```diff
@@ -0,0 +1,39 @@
...
+  xmlns:tools="http://schemas.android.com/tools">
+
+  <data>
+
+    <variable
+      name="htmlContent"
+      type="CharSequence" />
+
+    <variable
+      name="viewModel"
```
Comment (BenHenning) [inline app/src/main/res/layout/drag_drop_interaction_items.xml:12]: This doesn't appear to be used--do we need it?

File: app/src/main/java/org/oppia/app/player/state/itemviewmodel/DragDropInteractionContentViewModel.kt [hunk 8]
```diff
@@ -0,0 +1,9 @@
+package org.oppia.app.player.state.itemviewmodel
+
+import org.oppia.app.model.StringList
+import org.oppia.app.viewmodel.ObservableViewModel
+
+/** [ObservableViewModel] for DragDropSortInput values. */
+class DragDropInteractionContentViewModel(
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/app/player/state/itemviewmodel/DragDropInteractionContentViewModel.kt:7]: Is this class actually used/needed? It seems like we're binding HTML content directly.

**Review by BenHenning — APPROVED** [review]
Thanks @aggarwalpulkit596--this LGTM! Feel free to resolve my comments if they are uncontroversial, otherwise feel free to follow up with me.

File: app/src/main/res/layout/drag_drop_interaction_items.xml (hunk 6 above)
Comment (aggarwalpulkit596) [reply app/src/main/res/layout/drag_drop_interaction_items.xml:24]: recyclerview will be part of the nest PR in which we are adding support for grouping because that's the reason we need a recyclerview.

File: app/src/main/java/org/oppia/app/player/state/itemviewmodel/DragDropInteractionContentViewModel.kt (hunk 8 above)
Comment (aggarwalpulkit596) [reply app/src/main/java/org/oppia/app/player/state/itemviewmodel/DragDropInteractionContentViewModel.kt:7]: This is being used inside the custom view

File: app/src/main/java/org/oppia/app/player/state/DragDropSortInteractionView.kt (hunk 5 above)
Comment (aggarwalpulkit596) [reply app/src/main/java/org/oppia/app/player/state/DragDropSortInteractionView.kt]: done

File: app/src/main/java/org/oppia/app/player/state/DragDropSortInteractionView.kt (hunk 4 above)
Comment (aggarwalpulkit596) [reply app/src/main/java/org/oppia/app/player/state/DragDropSortInteractionView.kt]: done

File: app/src/main/res/layout/drag_drop_interaction_items.xml (hunk 7 above)
Comment (aggarwalpulkit596) [reply app/src/main/res/layout/drag_drop_interaction_items.xml:12]: yes this is being used for binding/saving the content of html
