### PR TITLE
Fix #989: Crash on Profile edit page landscape.

### LINKED ISSUE #989: Crash on Profile edit page landscape.
Change profile image in portrait mode, now change orientation and click on edit image.

Error

```
2020-06-30 14:07:46.658 10505-10505/org.oppia.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.oppia.app, PID: 10505
    java.lang.IllegalStateException: FragmentManager has been destroyed
        at androidx.fragment.app.FragmentManager.ensureExecReady(FragmentManager.java:1911)
        at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1942)
        at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:297)
        at androidx.fragment.app.DialogFragment.showNow(DialogFragment.java:212)
        at org.oppia.app.profileprogress.ProfileProgressActivityPresenter.showPictureEditDialog(ProfileProgressActivityPresenter.kt:63)
        at org.oppia.app.profileprogress.ProfileProgressActivity.onProfilePictureClicked(ProfileProgressActivity.kt:72)
        at org.oppia.app.profileprogress.ProfileProgressHeaderViewModel.clickOnProfilePicture(ProfileProgressHeaderViewModel.kt:44)
        at org.oppia.app.databinding.ProfileProgressHeaderBindingLandImpl._internalCallbackOnClick(ProfileProgressHeaderBindingLandImpl.java:412)
        at org.oppia.app.generated.callback.OnClickListener.onClick(OnClickListener.java:11)
```

### PR DESCRIPTION
**Pull request by anandwana001**
## Explanation

In my earlier PR https://github.com/oppia/oppia-android/pull/1446, I had solved this issue using `retainInstance` which after discussing with the team I get to know it create memory leaks issue and it's better to solve through Injecting ViewModel directly to the presenter.  

Screenshot 2020-09-02 at 17 24 42
Screenshot 2020-09-02 at 17 22 19

## Checklist

- [ ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [ ] The PR is made from a branch that's **not** called "develop".
- [ ] The PR is made from a branch that is up-to-date with "develop".
- [ ] The PR's branch is based on "develop" and not on any other branch.
- [ ] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

File: app/src/main/java/org/oppia/app/profileprogress/ProfileProgressViewModel.kt [hunk 1]
```diff
@@ -34,7 +34,7 @@ class ProfileProgressViewModel @Inject constructor(
   private val topicListController: TopicListController,
   private val logger: ConsoleLogger,
   @StoryHtmlParserEntityType private val entityType: String
-) : ObservableViewModel() {
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/app/profileprogress/ProfileProgressViewModel.kt:37]: Does it just not need to be observable?

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @anandwana001. Can you confirm there's already a test to verify that the crash isn't occurring?

File: app/src/main/java/org/oppia/app/profileprogress/ProfileProgressViewModel.kt (hunk 1 above)
Comment (rt4914) [reply app/src/main/java/org/oppia/app/profileprogress/ProfileProgressViewModel.kt:37]: @BenHenning Though it is assigned to Akshay, I am actually not able to understand what do you mean by this comment?

**Review by rt4914 — CHANGES_REQUESTED** [review]
Just add a test case which follows the same steps mentioned in the issue:
`Change profile image in portrait mode, now change orientation and click on edit image.`

**Review by rt4914 — APPROVED** [review]
LGTM

File: app/src/main/java/org/oppia/app/profileprogress/ProfileProgressViewModel.kt (hunk 1 above)
Comment (BenHenning) [reply app/src/main/java/org/oppia/app/profileprogress/ProfileProgressViewModel.kt:37]: Ah. I was confused about why this was removed, but it makes sense now.

File: app/src/sharedTest/java/org/oppia/app/profileprogress/ProfileProgressFragmentTest.kt [hunk 2]
```diff
@@ -218,6 +218,42 @@ class ProfileProgressFragmentTest {
...
+      onView(isRoot()).perform(orientationLandscape())
+      intended(expectedIntent)
+      onView(
+        atPositionOnView(
+          R.id.profile_progress_list,
+          0,
+          R.id.profile_edit_image
+        )
+      ).perform(click())
+      onView(withText(R.string.profile_progress_edit_dialog_title)).inRoot(isDialog())
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/app/profileprogress/ProfileProgressFragmentTest.kt:288]: Please add a comment to the effect: “dialog should still be open after configuration change”

**Review by BenHenning — APPROVED** [review]
Thanks! Lgtm—feel free to resolve my comment after addressing.

File: app/src/sharedTest/java/org/oppia/app/profileprogress/ProfileProgressFragmentTest.kt (hunk 2 above)
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/app/profileprogress/ProfileProgressFragmentTest.kt:288]:
```suggestion
      // The dialog should still be open after a configuration change.
      onView(withText(R.string.profile_progress_edit_dialog_title)).inRoot(isDialog())
```

Comment (BenHenning) [reply app/src/sharedTest/java/org/oppia/app/profileprogress/ProfileProgressFragmentTest.kt:288]: Committed directly.

**Comment by BenHenning** [comment]
@rt4914 can you verify the latest changes I made to the branch?

File: app/src/sharedTest/java/org/oppia/app/profileprogress/ProfileProgressFragmentTest.kt [hunk 3]
```diff
@@ -248,6 +248,43 @@ class ProfileProgressFragmentTest {
...
+        atPositionOnView(
+          R.id.profile_progress_list,
+          0,
+          R.id.profile_edit_image
+        )
+      ).perform(click())
+      // The dialog should still be open after a configuration change.
+      onView(withText(R.string.profile_progress_edit_dialog_title)).inRoot(isDialog())
+        .check(matches(isDisplayed()))
+    }
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/app/profileprogress/ProfileProgressFragmentTest.kt]:
```suggestion
    launch<ProfileProgressActivity>(createProfileProgressActivityIntent(internalProfileId)).use {
      testCoroutineDispatchers.runCurrent()
      waitForTheView(withText("Admin"))
      onView(
        atPositionOnView(
          R.id.profile_progress_list,
          0,
          R.id.profile_edit_image
        )
      ).perform(click())
      testCoroutineDispatchers.runCurrent()
      onView(withText(R.string.profile_progress_edit_dialog_title)).inRoot(isDialog())
        .check(matches(isDisplayed()))
      onView(withText(R.string.profile_picture_edit_alert_dialog_choose_from_library))
        .perform(click())
      testCoroutineDispatchers.runCurrent()
      intended(expectedIntent)
      onView(isRoot()).perform(orientationLandscape())
      testCoroutineDispatchers.runCurrent()
      intended(expectedIntent)
      onView(
        atPositionOnView(
          R.id.profile_progress_list,
          0,
          R.id.profile_edit_image
        )
      ).perform(click())
      testCoroutineDispatchers.runCurrent()
      // The dialog should still be open after a configuration change.
      onView(withText(R.string.profile_progress_edit_dialog_title)).inRoot(isDialog())
        .check(matches(isDisplayed()))
    }
```

Comment (BenHenning) [reply app/src/sharedTest/java/org/oppia/app/profileprogress/ProfileProgressFragmentTest.kt]: Added runCurrent calls since merging with develop broke the test.

**Comment by BenHenning** [comment]
@rt4914 please take a look at the newest commit as well since I needed to fix the new test being added.

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Comment by BenHenning** [comment]
Thanks for checking!

**Comment by BenHenning** [comment]
Requesting a CP on this since it's a straightforward fix and it's nice to include it in alpha.
