### PR TITLE
Fix #5818: Robolectric edittext input action

### LINKED ISSUE #5818: [BUG]: Fix Robolectric append/replaceText handling in EditTextInputAction and add corresponding tests.
### Describe the bug

This issue tracks the bug fix and upcoming tests related to `EditTextInputAction` used in test infrastructure for EditText input.

### 1. The Issue

- [x]  There was a bug in the `EditTextInputAction` class where appending or replacing text didn’t behave correctly in Robolectric environments. Specifically: (addressed in [PR #5617 ](https://github.com/oppia/oppia-android/pull/5617)) 
- `appendText` does not work correctly as it replaces the text rather than appending it.

- Both actions incorrectly called `EditText.setText(text)`, meaning that even when `appendText()` was used, it replaced the entire content instead of appending to it.
- This issue was masked by passing transitive test cases, but broke the intended behavior of append vs. replace differentiation.
- The logic for handling `appendText()` and `replaceText()` needed to differentiate between Robolectric and Espresso environments.

---

### 2. Adding Corresponding Tests

- [ ] Tests still need to be added to ensure the behavior of `EditTextInputAction` remains correct across test environments.

To achieve this, we should:
- Add a dedicated test class (similar to the one for [TextInputAction](https://github.com/oppia/oppia-android/blob/d25fe1f0f29688f5ed485503bc0a9c4bfff2d73f/testing/src/main/java/org/oppia/android/testing/espresso/TextInputAction.kt))
- Write Robolectric-based tests verifying `appendText()` and `replaceText()` apply the correct text values
- Validate that the logic paths in the updated `updateText()` method execute correctly for both `isAppend=true` and `isAppend=false`

### Steps To Reproduce

1. Write a Robolectric test using `EditTextInputAction.appendText()` to input text into an `EditText`.
2. Set initial text in the `EditText` (e.g., "123").
3. Use `appendText("45")` and expect the final text to be "12345".
4. Run the test in Robolectric.
5. Observe that the text becomes "45" instead of "12345", indicating that `appendText()` is replacing rather than appending the text.

Concered file: [testing/src/main/java/org/oppia/android/testing/espresso/EditTextInputAction.kt](https://github.com/oppia/oppia-android/blob/d25fe1f0f29688f5ed485503bc0a9c4bfff2d73f/testing/src/main/java/org/oppia/android/testing/espresso/EditTextInputAction.kt#L22)

### Expected Behavior

When using `EditTextInputAction.appendText()` in Robolectric-based tests, the provided text should be appended to the existing contents of the `EditText`, preserving the original text.

Similarly, when using `replaceText()`, the original text in the `EditText` should be completely replaced with the new input.

These behaviors should match how Espresso handles `typeText()` and `replaceText()` on physical/emulated devices.

### Screenshots/Videos

_No response_

### What device/emulator are you using?

_No response_

### Which Android version is your device/emulator running?

_No response_

### Which version of the Oppia Android app are you using?

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Sandesh282**
Fixes #5818

## Explanation

Fixes #5818: Refactors `EditTextInputAction` to remove its dependency on constructor injection of `TestCoroutineDispatchers`, which caused Robolectric edit text input actions to be difficult to invoke reliably in tests.

This change introduces `TestCoroutineDispatchersInjector`, which provides a static access point for test coroutine dispatchers. `EditTextInputAction` is updated to retrieve dispatchers through this injector instead of relying on injected fields.

As a result, `EditTextInputAction` methods can now be invoked directly from tests without requiring `@Inject` setup, resolving the existing TODO in the file and simplifying test usage across Robolectric-based tests.

### Key changes
- Added `TestCoroutineDispatchersInjector` to hold a static reference to
  `TestCoroutineDispatchers`.
- Updated `TestDispatcherModule` to initialize the injector.
- Refactored `EditTextInputAction` to access dispatchers via the static injector.
- Updated test usages to call `EditTextInputAction` methods directly.
- Removed `EditTextInputAction` injection from test classes.

This is a duplicate of https://github.com/oppia/oppia-android/pull/6082, which contains previous reviews but was closed due to force-pushing.

## Essential Checklist

- [x] The PR title starts with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The explanation section above starts with "Fixes #bugnum: " (If this PR fixes part of an issue, use instead: "Fixes part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

This PR does not introduce any UI-related changes. It only affects test infrastructure and
Robolectric-based test utilities. As a result, no UI verification, screenshots, or accessibility
checks are required.

### CODE REVIEW

**Comment by Sandesh282** [comment]
@adhiamboperes This is a clean re-submission replacing #6082. All previous review feedback has been addressed:

- Fully imported `appendText` and `replaceText` instead of using `EditTextInputAction.Companion.` prefix (Ben's and your feedback)
- Verified Ben's comment on `TestCoroutineDispatchersInjector.kt`, the static injector was simplified but retained as Ben concluded it's the pragmatic approach before Hilt migration
- Removed all unrelated changes 
PTAL when you get a chance. Thanks!

File: scripts/assets/test_file_exemptions.textproto
Comment (adhiamboperes) [inline scripts/assets/test_file_exemptions.textproto:1]: This looks out of place @Sandesh282, PTAL.

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @Sandesh282! All the test files look good to me now.

I am handing over the final reviews to @BenHenning to look at the TestCoroutineDispatchersInjector changes and the EditTextInputActionRobolectricTest.kt, specifically.

File: scripts/assets/test_file_exemptions.textproto
Comment (adhiamboperes) [reply scripts/assets/test_file_exemptions.textproto:1]: Always check the files changed tab of your PR to confirm that the files there are all relevant. This is required by the PR checklist.

Comment (Sandesh282) [reply scripts/assets/test_file_exemptions.textproto:1]: Done, reverted the unrelated changes. PTAL @adhiamboperes when you get a chance!

**Comment by BenHenning** [comment]
Apologies--hoping to look at this tomorrow.

File: testing/src/main/java/org/oppia/android/testing/espresso/EditTextInputAction.kt [hunk 1]
```diff
@@ -19,50 +18,47 @@ import javax.inject.Inject
...
-  // the TestCoroutineDispatchers so that the outer class doesn't need to be injected.
-  /**
-   * Returns a [ViewAction] that appends the specified string into the view targeted by the
-   * [ViewAction].
-   */
-  fun appendText(text: String): ViewAction = updateText(
-    text, baseAction = typeText(text), isAppend = true
-  )
+class EditTextInputAction @Inject constructor() {
+  companion object {
```
Comment (BenHenning) [inline testing/src/main/java/org/oppia/android/testing/espresso/EditTextInputAction.kt]: This can just be a top-level object, no need for companion. Plus, the class is never injected so it doesn't make sense to have an `@Inject` constructor.

File: testing/src/main/java/org/oppia/android/testing/espresso/EditTextInputAction.kt [hunk 2]
```diff
@@ -19,50 +18,47 @@ import javax.inject.Inject
...
+        override fun perform(uiController: UiController?, view: View?) {
+          // Appending text only works on Robolectric, whereas Espresso needs to use typeText().
+          if (Build.FINGERPRINT.contains("robolectric", ignoreCase = true)) {
+            val editText = view as? EditText
+            if (isAppend) {
+              editText?.append(text)
+            } else {
+              editText?.setText(text)
+            }
+            TestCoroutineDispatchersInjector.getDispatcher().runCurrent()
```
Comment (BenHenning) [inline testing/src/main/java/org/oppia/android/testing/espresso/EditTextInputAction.kt]: The correct way to do this is to introduce an injector interface and provider, then implement them in test applications throughout the codebase. I was hesitant to suggest this because it will require changing a lot of files, and since the rest of the PR is done, I am fine with you checking in the current solution provided:
1. You file an issue to migrate `TestCoroutineDispatchersInjector` to the correct pattern.
2. You add a code TODO pointing to that issue in `TestCoroutineDispatchersInjector` and mention that the class should not be used in any new locations.
3. You restrict Bazel access to the injector specifically to this class (which, since it isn't modularized, means you'll need to restrict it to `//testing/src/main/java/org/oppia/android/testing:__subpackages__` I think).

For a reference on a correctly set up injector provider, see: https://github.com/oppia/oppia-android/blob/develop/utility/src/main/java/org/oppia/android/util/system/OppiaClockInjector.kt and https://github.com/oppia/oppia-android/blob/develop/utility/src/main/java/org/oppia/android/util/system/OppiaClockInjectorProvider.kt.

With the injector pattern properly in place, you can get access to the underlying object using the following approach:

```kotlin
val context = ApplicationProvider.getApplicationContext<Application>()
val provider = context as TestCoroutineDispatchersInjectorProvider
val injector = provider.getTestCoroutineDispatchersInjector()
val testCoroutineDispatchers = injector.getTestCoroutinDispatchers()
```

(You could also use the `View`'s `Context` but it's a few extra steps and the above should work for both Robolectric & Espresso).

I will note that I was wrong in my earlier comment. I thought that this couldn't be done cleanly without Hilt because I assumed that the production application classes would need to implement the provider, but that isn't actually true since we almost always have a custom test application (and basically always should).

You may actually want to consider implementing this in this PR. It may not be as bad as it sounds because technically only the tests that use the action will need to implement the provider interfaces, and there aren't too many. I also suggest adding error checking to the sample code above (you can use optional casting via `as?` and then check that they cast correctly--failure error messages can inform developers that their test's test application class needs to implement the injector provider in order to use the action). The action's KDoc should also be updated to reflect this.

File: testing/src/main/java/org/oppia/android/testing/threading/BUILD.bazel [hunk 3]
```diff
@@ -40,6 +40,7 @@ kt_android_library(
     testonly = True,
     srcs = [
         "TestCoroutineDispatchers.kt",
+        "TestCoroutineDispatchersInjector.kt",
```
Comment (BenHenning) [inline testing/src/main/java/org/oppia/android/testing/threading/BUILD.bazel]: This will need to be in its own package per my comment above.

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @Sandesh282 and apologies for the delayed review. I made a mistake in my earlier review--there is a clean way to solve this. However, with the delays I think it's fine if you want to defer that to a different task (though you need to make sure it's captured correctly before we can merge this). However, I suspect that it might not actually be that much more work and is probably worth just going ahead and addressing directly in this PR.

PTAL at my comments and let me know if you have any questions.

File: testing/src/main/java/org/oppia/android/testing/espresso/EditTextInputAction.kt (hunk 1 above)
Comment (Sandesh282) [reply testing/src/main/java/org/oppia/android/testing/espresso/EditTextInputAction.kt]: Alright. I have
- Removed `class @Inject constructor()` + `companion object`
- Now just `object EditTextInputAction { ... }`
- Removed `javax.inject.Inject` import

File: testing/src/main/java/org/oppia/android/testing/espresso/EditTextInputAction.kt (hunk 2 above)
Comment (Sandesh282) [reply testing/src/main/java/org/oppia/android/testing/espresso/EditTextInputAction.kt]: Done.
- Added TODO: #6160
- Expanded KDoc explaining the correct approach (referencing `OppiaClockInjector/OppiaClockInjectorProvider`)
- Added note that "this class should not be used in any new locations"

File: testing/src/main/java/org/oppia/android/testing/threading/BUILD.bazel (hunk 3 above)
Comment (Sandesh282) [reply testing/src/main/java/org/oppia/android/testing/threading/BUILD.bazel]: Done. Moved `TestCoroutineDispatchersInjector` into its own Bazel target (`test_coroutine_dispatchers_injector`) with restricted visibility to `//testing:__pkg__` and `//testing/src/main/java/org/oppia/android/testing:__subpackages__`. This ensures it can't be used from new locations outside testing infrastructure.

**Comment by Sandesh282** [comment]
PTAL @BenHenning.

**Review by BenHenning — APPROVED** [review]
Thanks @Sandesh282! This LGTM!

**Comment by BenHenning** [comment]
FYI @Sandesh282 I think you need to remove a line from the test file exemption (per the failing check). Otherwise @adhiamboperes will need to take a review pass yet.

File: testing/src/test/java/org/oppia/android/testing/espresso/EditTextInputActionTest.kt
Comment (adhiamboperes) [inline testing/src/test/java/org/oppia/android/testing/espresso/EditTextInputActionTest.kt:1]: The reason why this test is causing issues with the coverage script is because it does not follow the expected naming pattern.

It should be `EditTextInputActionTest`.

File: scripts/assets/test_file_exemptions.textproto [hunk 4]
```diff
@@ -4279,6 +4279,10 @@ test_file_exemption {
   exempted_file_path: "testing/src/main/java/org/oppia/android/testing/espresso/EditTextInputAction.kt"
   test_file_not_required: true
 }
```
Comment (adhiamboperes) [inline scripts/assets/test_file_exemptions.textproto]: If you name the test file correctly you can remove this exemption.

File: scripts/assets/test_file_exemptions.textproto [hunk 5]
```diff
@@ -4279,6 +4279,10 @@ test_file_exemption {
...
+test_file_exemption {
+  exempted_file_path: "testing/src/test/java/org/oppia/android/testing/espresso/EditTextInputActionRobolectricTest.kt"
+  is_extra_test_file: true
+}
```
Comment (adhiamboperes) [inline scripts/assets/test_file_exemptions.textproto]: It is not correct that this is an extra test file, because no other test file exists for `EditTextInputAction`, hence its exemption above.

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @Sandesh282! Just had some cleanup suggestions, PTAL.

File: testing/src/test/java/org/oppia/android/testing/espresso/EditTextInputActionTest.kt
Comment (Sandesh282) [reply testing/src/test/java/org/oppia/android/testing/espresso/EditTextInputActionTest.kt:1]: Done.

File: scripts/assets/test_file_exemptions.textproto (hunk 5 above)
Comment (Sandesh282) [reply scripts/assets/test_file_exemptions.textproto]: Done.

File: scripts/assets/test_file_exemptions.textproto (hunk 4 above)
Comment (Sandesh282) [reply scripts/assets/test_file_exemptions.textproto]: Done.

**Comment by Sandesh282** [comment]
PTAL @adhiamboperes.

File: scripts/assets/test_file_exemptions.textproto
Comment (adhiamboperes) [inline scripts/assets/test_file_exemptions.textproto]: This exemption is still there, and likely why you have a failing static check. The newly renamed `EditTextInputActionTest` is the test file for `EditTextInputAction`, so the exemption is no longer valid. You should remove it.

Comment (Sandesh282) [reply scripts/assets/test_file_exemptions.textproto]: Done.

**Review by adhiamboperes — COMMENTED** [review]
The changes LGTM, I am waiting for CI results before sending to merge queue.

**Review by adhiamboperes — APPROVED** [review]
Approving, thanks!
