### PR TITLE
Fix #1710 & #1749: Hint dialog reveal bug fix

### LINKED ISSUE #1710: Hint Dialog showing one extra hint but not revealable
**Describe the bug**
After revealing a hint, when we again open the hint dialog hint list will show the next hint item but it is not clickable.

**To Reproduce**
1. Play what is fraction
2. Play till the question `what fraction is shown by the shaped part of this drawing?` hexagonal one
3. submit 2 wrong answer
4. reveal the hint
5. close the hint dialog
6. open hint dialog and 2 items will be visible

**Expected behavior**
It should not show the next item until it is revealable

### LINKED ISSUE #1749: StateFragmentLocalTest tests are failing on develop
Following test cases are failing on current develop

```
testStateFragment_nextState_viewSolution_noNewHintIsAvailable
testStateFragment_nextState_viewFourHints_submitWrongAnswer_wait10s_newHintIsAvailable
testStateFragment_nextState_viewSolution_submitWrongAnswer_wait10s_noNewHintIsAvailable
testStateFragment_nextState_viewFourHints_submitWrongAnswer_noNewHintIsAvailable
testStateFragment_nextState_viewFourHints_wait30seconds_newHintIsAvailable
testStateFragment_nextState_viewFourHints_wait10seconds_noNewHintIsAvailable
testStateFragment_nextState_viewFourHints_submitWrongAnswer_wait10s_canViewSolution
testStateFragment_nextState_submitThreeWrongAnswers_canViewOneHint
testStateFragment_nextState_viewFourHints_wait30seconds_canViewSolution
testStateFragment_nextState_viewSolution_wait30seconds_noNewHintIsAvailable
```

Needs more details and solution

### PR DESCRIPTION
**Pull request by rt4914**
## Explanation

Fixes #1710 
Fixes #1749

Along with the issue mentioned in #1710 this PR also adds a test which will fail if this implementation is not working.

NOTE: Before checking this branch, run test cases on current develop and see that 10 test cases are failing in `StateFragmentLocalTest`. Mostly because of #1576 
Filed an issue for the same: https://github.com/oppia/oppia-android/issues/1749 

UPDATE: The test cases have been fixed now.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

File: app/src/main/java/org/oppia/app/hintsandsolution/HintsAndSolutionAdapter.kt [hunk 1]
```diff
@@ -140,7 +140,7 @@ class HintsAndSolutionAdapter(
         binding.revealHintButton.setOnClickListener {
           hintsViewModel.isHintRevealed.set(true)
           expandedHintListIndexListener.onRevealHintClicked(position, /* isHintRevealed= */ true)
-          (fragment.requireActivity() as? RevealHintListener)?.revealHint(true, position / 2)
+          (fragment.requireActivity() as? RevealHintListener)?.revealHint(true, ((position / 2)))
```
Comment (anandwana001) [inline app/src/main/java/org/oppia/app/hintsandsolution/HintsAndSolutionAdapter.kt]: can we add argument name comment for **true**?

Comment (anandwana001) [inline app/src/main/java/org/oppia/app/hintsandsolution/HintsAndSolutionAdapter.kt]: Do we need this extra brackets around position/2?

File: app/src/main/java/org/oppia/app/hintsandsolution/HintsAndSolutionDialogFragmentPresenter.kt [hunk 2]
```diff
@@ -75,7 +75,7 @@ class HintsAndSolutionDialogFragmentPresenter @Inject constructor(
     }
 
     this.state = state
-    viewModel.newAvailableHintIndex.set(newAvailableHintIndex)
+    viewModel.newAvailableHintIndex.set((newAvailableHintIndex * 2))
```
Comment (anandwana001) [inline app/src/main/java/org/oppia/app/hintsandsolution/HintsAndSolutionDialogFragmentPresenter.kt]: Should we add a comment above this line that why are we doing this ***2**?
This makes this more understandable

File: app/src/main/java/org/oppia/app/hintsandsolution/HintsViewModel.kt [hunk 3]
```diff
@@ -36,25 +36,23 @@ class HintsViewModel @Inject constructor() : HintsAndSolutionItemViewModel() {
...
-
-    val isLastHintRevealed = (itemList[itemList.size - 1] as HintsViewModel).isHintRevealed.get()!!
-    if (solution.hasExplanation() && hintList.size == itemList.size && isLastHintRevealed) {
+    val isLastHintRevealed = (itemList[itemList.size - 2] as HintsViewModel).isHintRevealed.get()!!
+    if (solution.hasExplanation() &&
+      hintList.size * 2 == itemList.size &&
+      isLastHintRevealed &&
+      allHintsExhausted.get()!!
+    ) {
       val solutionViewModel = SolutionViewModel()
```
Comment (anandwana001) [inline app/src/main/java/org/oppia/app/hintsandsolution/HintsViewModel.kt]: Just like `addHintToList` can we create another method for this `addSolutionToList`?
This might makes `processHintList` looks clean and separable.

**Review by anandwana001 — CHANGES_REQUESTED** [review]
NIt changes 

Checked all the test cases. The new test case is passing but 10 other test cases are failing as mentioned in the issue also. 
### This PR
Screenshot 2020-08-31 at 10 18 41

### Failing in Develop too
Screenshot 2020-08-31 at 10 24 24

File: app/src/main/java/org/oppia/app/hintsandsolution/HintsAndSolutionAdapter.kt (hunk 1 above)
Comment (rt4914) [reply app/src/main/java/org/oppia/app/hintsandsolution/HintsAndSolutionAdapter.kt]: Done.
```
          (fragment.requireActivity() as? RevealHintListener)?.revealHint(
            /* saveUserChoice = */ true,
            /* hintIndex = */ position / 2
          )
```

Comment (rt4914) [reply app/src/main/java/org/oppia/app/hintsandsolution/HintsAndSolutionAdapter.kt]: Removed brackets.

File: app/src/main/java/org/oppia/app/hintsandsolution/HintsAndSolutionDialogFragmentPresenter.kt (hunk 2 above)
Comment (rt4914) [reply app/src/main/java/org/oppia/app/hintsandsolution/HintsAndSolutionDialogFragmentPresenter.kt]: Added:
```
    // The newAvailableHintIndex received here is coming from state player but in this implementation
    // hints/solutions are shown on every even index and on every odd index we show a divider.
    // Therefore multiplying the original index by 2.
```

File: app/src/main/java/org/oppia/app/hintsandsolution/HintsViewModel.kt (hunk 3 above)
Comment (rt4914) [reply app/src/main/java/org/oppia/app/hintsandsolution/HintsViewModel.kt]: Done.

**Comment by rt4914** [comment]
@anandwana001 The tests which are failing are result of #1576 . I have fixed those test cases in this PR itself.

File: app/src/main/java/org/oppia/app/hintsandsolution/HintsAndSolutionAdapter.kt [hunk 4]
```diff
@@ -140,7 +140,10 @@ class HintsAndSolutionAdapter(
         binding.revealHintButton.setOnClickListener {
           hintsViewModel.isHintRevealed.set(true)
           expandedHintListIndexListener.onRevealHintClicked(position, /* isHintRevealed= */ true)
-          (fragment.requireActivity() as? RevealHintListener)?.revealHint(true, position / 2)
+          (fragment.requireActivity() as? RevealHintListener)?.revealHint(
+            /* saveUserChoice = */ true,
```
Comment (anandwana001) [inline app/src/main/java/org/oppia/app/hintsandsolution/HintsAndSolutionAdapter.kt]: Just one more update on format
`/* isHintRevealed= */` 
diff
`/* saveUserChoice = */`

File: app/hs_err_pid44135.log [hunk 5]
```diff
@@ -0,0 +1,857 @@
+#
```
Comment (anandwana001) [inline app/hs_err_pid44135.log]: Is this file something related to test?

Comment (anandwana001) [reply app/hs_err_pid44135.log]: and the other one too

**Review by anandwana001 — CHANGES_REQUESTED** [review]
There are 3 unknown files get added in this PR.

**Review by anandwana001 — APPROVED** [review]
LGTM, Thanks @rt4914 
NIt changes in earlier points
Screenshot 2020-08-31 at 11 32 05

File: app/src/main/java/org/oppia/app/hintsandsolution/HintsAndSolutionAdapter.kt (hunk 4 above)
Comment (aggarwalpulkit596) [reply app/src/main/java/org/oppia/app/hintsandsolution/HintsAndSolutionAdapter.kt]: Why not use named arguments here ?

Comment (rt4914) [reply app/src/main/java/org/oppia/app/hintsandsolution/HintsAndSolutionAdapter.kt]: @aggarwalpulkit596 What do you mean by named arguments? Can you mention an example?

**Comment by rt4914** [comment]
> LGTM, Thanks @rt4914
> NIt changes in earlier points

Removed files.

File: app/hs_err_pid44135.log (hunk 5 above)
Comment (rt4914) [reply app/hs_err_pid44135.log]: Removed

**Comment by anandwana001** [comment]
> > LGTM, Thanks @rt4914
> > NIt changes in earlier points
> 
> Removed files.

In files changed section `sreenshots/org.oppia.app.onboarding.OnboardingActivity.png` this one is showing

File: app/src/main/java/org/oppia/app/hintsandsolution/HintsAndSolutionAdapter.kt (hunk 4 above)
Comment (aggarwalpulkit596) [reply app/src/main/java/org/oppia/app/hintsandsolution/HintsAndSolutionAdapter.kt]: instead of manually writing the argument name as an inline comment, use named arguments of the function itself.

Comment (rt4914) [reply app/src/main/java/org/oppia/app/hintsandsolution/HintsAndSolutionAdapter.kt]: Not sure if this is what you meant or not? Can you please confirm?
```
            saveUserChoice = true,
            hintIndex = position / 2
```

**Comment by rt4914** [comment]
> > > LGTM, Thanks @rt4914
> > > NIt changes in earlier points
> > 
> > 
> > Removed files.
> 
> In files changed section `sreenshots/org.oppia.app.onboarding.OnboardingActivity.png` this one is showing

Actually it was in local commit, was waiting for Pulkit's reply on the comment.

File: app/src/main/java/org/oppia/app/hintsandsolution/HintsAndSolutionAdapter.kt (hunk 4 above)
Comment (aggarwalpulkit596) [reply app/src/main/java/org/oppia/app/hintsandsolution/HintsAndSolutionAdapter.kt]: yes that's correct this is exactly what I mean

Comment (rt4914) [reply app/src/main/java/org/oppia/app/hintsandsolution/HintsAndSolutionAdapter.kt]: Okay. Thanks.

**Comment by rt4914** [comment]
@anandwana001 You can now resolve the comments.

File: app/src/main/java/org/oppia/app/hintsandsolution/HintsAndSolutionDialogFragmentPresenter.kt [hunk 6]
```diff
@@ -75,7 +75,10 @@ class HintsAndSolutionDialogFragmentPresenter @Inject constructor(
     }
 
     this.state = state
-    viewModel.newAvailableHintIndex.set(newAvailableHintIndex)
+    // The newAvailableHintIndex received here is coming from state player but in this implementation
+    // hints/solutions are shown on every even index and on every odd index we show a divider.
+    // Therefore multiplying the original index by 2.
+    viewModel.newAvailableHintIndex.set((newAvailableHintIndex * 2))
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/app/hintsandsolution/HintsAndSolutionDialogFragmentPresenter.kt]: Nit: remove extra parentheses

File: app/src/main/java/org/oppia/app/hintsandsolution/HintsViewModel.kt [hunk 7]
```diff
@@ -36,36 +36,52 @@ class HintsViewModel @Inject constructor() : HintsAndSolutionItemViewModel() {
...
-        if (isLastHintRevealed) {
-          val hintsAndSolutionViewModel = HintsViewModel()
-          hintsAndSolutionViewModel.title.set(hintList[index].hintContent.contentId)
-          hintsAndSolutionViewModel.hintsAndSolutionSummary.set(hintList[index].hintContent.html)
-          hintsAndSolutionViewModel.isHintRevealed.set(hintList[index].hintIsRevealed)
-          itemList.add(hintsAndSolutionViewModel as HintsAndSolutionItemViewModel)
+        addHintToList(hintList[index])
+      } else {
+        val isLastHintRevealed =
+          (itemList[itemList.size - 2] as HintsViewModel).isHintRevealed.get()!!
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/app/hintsandsolution/HintsViewModel.kt]: Do we guarantee at this point that the list size is > 1?

Comment (BenHenning) [inline app/src/main/java/org/oppia/app/hintsandsolution/HintsViewModel.kt]: Here and elsewhere: can we avoid the !! operator by handling the null cases?

File: app/src/main/java/org/oppia/app/hintsandsolution/HintsViewModel.kt [hunk 8]
```diff
@@ -36,36 +36,52 @@ class HintsViewModel @Inject constructor() : HintsAndSolutionItemViewModel() {
...
     }
     return itemList
   }
+
+  private fun addHintToList(hint: Hint) {
+    val hintsAndSolutionViewModel = HintsViewModel()
+    hintsAndSolutionViewModel.title.set(hint.hintContent.contentId)
+    hintsAndSolutionViewModel.hintsAndSolutionSummary.set(hint.hintContent.html)
+    hintsAndSolutionViewModel.isHintRevealed.set(hint.hintIsRevealed)
+    itemList.add(hintsAndSolutionViewModel as HintsAndSolutionItemViewModel)
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/app/hintsandsolution/HintsViewModel.kt]: This cast is a bit weird. Why is this needed?

**Review by BenHenning — APPROVED** [review]
Thanks @rt4914! Is the reference to #1576 in the title correct? Please fix. 

Had a few comments, otherwise the solution looks good to me.

File: app/src/main/java/org/oppia/app/hintsandsolution/HintsAndSolutionDialogFragmentPresenter.kt (hunk 6 above)
Comment (rt4914) [reply app/src/main/java/org/oppia/app/hintsandsolution/HintsAndSolutionDialogFragmentPresenter.kt]: Removed.

File: app/src/main/java/org/oppia/app/hintsandsolution/HintsViewModel.kt (hunk 7 above)
Comment (rt4914) [reply app/src/main/java/org/oppia/app/hintsandsolution/HintsViewModel.kt]: Added this condition in else part.
`} else if (itemList.size > 1) {`

And also below.

Comment (rt4914) [reply app/src/main/java/org/oppia/app/hintsandsolution/HintsViewModel.kt]: Done. By making this change:
`(itemList[itemList.size - 2] as HintsViewModel).isHintRevealed.get() ?: false`

File: app/src/main/java/org/oppia/app/hintsandsolution/HintsViewModel.kt (hunk 8 above)
Comment (rt4914) [reply app/src/main/java/org/oppia/app/hintsandsolution/HintsViewModel.kt]: Removed this cast.
Also, renamed `hintsAndSolutionViewModel` to `hintsViewModel`

**Comment by rt4914** [comment]
@BenHenning You can check the last commit and the comments to your replies. That should suffice. Thanks.

File: app/src/main/java/org/oppia/app/hintsandsolution/HintsViewModel.kt [hunk 9]
```diff
@@ -37,33 +37,36 @@ class HintsViewModel @Inject constructor() : HintsAndSolutionItemViewModel() {
...
-      allHintsExhausted.get()!!
-    ) {
-      addSolutionToList(solution)
+    if (itemList.size > 1) {
+      val isLastHintRevealed =
+        (itemList[itemList.size - 2] as HintsViewModel).isHintRevealed.get() ?: false
+      if (solution.hasExplanation() &&
+        hintList.size * 2 == itemList.size &&
+        isLastHintRevealed &&
+        allHintsExhausted.get()!!
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/app/hintsandsolution/HintsViewModel.kt]: Ditto for these observables (prefer not using !! operator). I suggest doing a pass on this file to remove all such cases (local vals can help reduce the logical complexity increase that can come from adding these checks in a bunch of places).

**Review by BenHenning — APPROVED** [review]
Thanks @rt4914. Still LGTM. @anandwana001 feel free to verify my latest comment for @rt4914 if that speeds things up.

File: app/src/main/java/org/oppia/app/hintsandsolution/HintsViewModel.kt (hunk 9 above)
Comment (rt4914) [reply app/src/main/java/org/oppia/app/hintsandsolution/HintsViewModel.kt]: Solved.

**Review by BenHenning — APPROVED** [review]

**Comment by BenHenning** [comment]
Thanks @rt4914!

**Comment by BenHenning** [comment]
(de-assigning Akshay since I assume you assigned him to verify the comment I just resolved).
