### PR TITLE
Fix #426: Topic size fix

### LINKED ISSUE #426: Use KB instead of MB for smaller topic sizes

### PR DESCRIPTION
**Pull request by rt4914**
## Explanation

Screenshot 2019-11-20 at 11 48 04 AM
Screenshot 2019-11-20 at 11 48 10 AM
Screenshot 2019-11-20 at 11 48 16 AM

Check code.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

File: app/src/main/java/org/oppia/app/topic/overview/TopicOverviewViewModel.kt [hunk 1]
```diff
@@ -20,9 +20,22 @@ class TopicOverviewViewModel @Inject constructor() : ObservableViewModel() {
...
+    val size: Double = topic.get()?.diskSizeBytes!!.toDouble()
+    if (size == 0.0) {
+      return "0 KB"
+    }
+    val sizeInKB = size / 1024.0
+    val sizeInMB = size / 1024.0 / 1024.0
+    val sizeInGB = size / 1024.0 / 1024.0 / 1024.0
+    val sizeInTB = size / 1024.0 / 1024.0 / 1024.0 / 1024.0
+    return when {
+      sizeInTB >= 1 -> decimalFormat.format(sizeInTB) + " TB"
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/app/topic/overview/TopicOverviewViewModel.kt]: Let's default to KB for now since otherwise we need strings for each of these for localization.

Comment (rt4914) [reply app/src/main/java/org/oppia/app/topic/overview/TopicOverviewViewModel.kt]: okay, then KB will be the only unit for now.

Comment (rt4914) [reply app/src/main/java/org/oppia/app/topic/overview/TopicOverviewViewModel.kt]: As per the conversation, we are keeping this code and we should shift the units to `strings.xml`

**Review by veena14cs — APPROVED** [review]
Looks good.

**Comment by nikitamarysolomanpvt** [comment]
LGTM
