### PR TITLE
Fix #5781, #5808, #5796: Handle null imageRetriever Case in CustomHtmlContentHandler

### LINKED ISSUE #5781: [BUG]: The app breaks in the first chapter of division
### Describe the bug

 When the learner is playing the first chapter in Topic Division, the app stops working and the learner goes back to the "Stories you can play" page. If the learner tries to start again clicking on the continue button a message " Oppia keeps stopping"  is showing and the learner is redirected to the Home seccion. 

Note:  In the last version I could play all chapters in topic Division

### Steps To Reproduce

1. Go to Division
2. Go to What is Division
3. Play the lesson
4. Observe 
6. Play again clicking on continue button
7. Observe

### Expected Behavior

It is expected play the chapter completly.

### Screenshots/Videos

https://github.com/user-attachments/assets/dcc83b22-bfd4-4d63-98bf-31b57043b10e

### What device/emulator are you using?

OPPO A79 5G

### Which Android version is your device/emulator running?

Android 14

### Which version of the Oppia Android app are you using?

0.15-beta-9404ea41d9

### Additional Context

_No response_

### LINKED ISSUE #5796: [BUG]: The app redirects or breaks in the first chapter of Fraction
### Describe the bug

When the learner is playing the first chapter in Topic Fraction, the app stops working and the learner goes back to the "Stories you can play" page. If the learner tries to start again by clicking on the continue button the message " Oppia keeps stopping" is showing and the learner is redirected to the Home section.

### Steps To Reproduce

1. Go to Fraction
2. Go to What is a Fraction?
3. Play the lesson
4. Observe
5. Play again by clicking on the continue button
6. Observe

### Expected Behavior

It is expected to play the chapter entirely.

### Screenshots/Videos

https://github.com/user-attachments/assets/fb9b02c0-0a99-4931-b40e-ed1f90233b21

### What device/emulator are you using?

_No response_

### Which Android version is your device/emulator running?

_No response_

### Which version of the Oppia Android app are you using?

_No response_

### Additional Context

_No response_

### LINKED ISSUE #5808: [BUG]:  The app breaks in the Writing Ratios in Simplest Form lesson
### Describe the bug

When the learner is playing "Writing Ratios in simplest form" Lesson, the app stops working and the learner goes back to the "Stories you can play" page. If the learner tries to start again clicking on the continue button a message " Oppia keeps stopping" is shown.

### Steps To Reproduce

1. Go to Ratios and Proportional Reasoning
2. Go to Writing Ratios in Simplest Form
3. Play the lesson
4. Observe -  the app redirects to the "Stories you can play" page.
5. Go to Writing Ratios in Simplest Form
6. Play again clicking on continue button
7. Observe

### Expected Behavior

It is expected play the lesson completly.

### Screenshots/Videos

Image

https://github.com/user-attachments/assets/c50c2a2b-e401-489c-9713-596e84049f7c

### What device/emulator are you using?

OPPO A79 5G

### Which Android version is your device/emulator running?

Android 14

### Which version of the Oppia Android app are you using?

0.15-beta-9404ea41d9

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by manas-yu**
## Explanation

Fix #5781 
Fix #5808 
Fix #5796 

To prevent passing a null `imageRetriever` to the `handleTag` method during content description generation, this PR introduces the following changes:

- Removes the `imageRetriever` parameter from `getContentDescription()`, as image retrieval is unnecessary during content description generation.
- Introduces `handleTagForContentDescription()` method, following [this comment](https://github.com/oppia/oppia-android/issues/5781#issuecomment-2806775271), to handle tag parsing specifically during content description generation.

### Before

https://github.com/user-attachments/assets/7b3065c1-e485-4ce3-867d-e8f0c37a12cf

### After

https://github.com/user-attachments/assets/5b880bf6-ad2c-42e7-a16e-f48db2c7f8b9

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

### CODE REVIEW

**Comment by manas-yu** [comment]
Hi @adhiamboperes PTAL, Thanks!

File: utility/src/main/java/org/oppia/android/util/parser/html/CustomHtmlContentHandler.kt [hunk 1]
```diff
@@ -145,8 +145,14 @@ class CustomHtmlContentHandler private constructor(
           }
         }
         customTagHandlers.getValue(tag).handleClosingTag(output, indentation = 0, tag)
-        customTagHandlers.getValue(tag)
-          .handleTag(attributes, openTagIndex, output.length, output, imageRetriever)
+
+        if (imageRetriever == null) {
```
Comment (adhiamboperes) [inline utility/src/main/java/org/oppia/android/util/parser/html/CustomHtmlContentHandler.kt:149]: This check here reads like we are only handling content description when `imageRetriever == null`. What if there is another reason for the `imageRetriever` to be null?

**Review by adhiamboperes — COMMENTED** [review]
Thanks @manas-yu! I have one comment regarding the implementation, PTAL.

File: utility/src/main/java/org/oppia/android/util/parser/html/CustomHtmlContentHandler.kt (hunk 1 above)
Comment (manas-yu) [reply utility/src/main/java/org/oppia/android/util/parser/html/CustomHtmlContentHandler.kt:149]: Actually, the reason I initially introduced the `isContentDescriptionMode` Boolean was to explicitly allow the null `imageRetriever` case only during content description generation and avoid the cases you mentioned. However, based on what Ben mentioned during the CLaM meeting, my understanding is that it would be better architecturally to rely on `imageRetriever == null` check directly. This way, we can handle such cases more cleanly within the respective TagHandlers, similar to how `PolicyPageTagHandler` operates when it's passed a null `urlImageParserFactory` in the `HtmlParser`.
Please let me know if I’ve misunderstood anything or if the current implementation needs to be revised. 

My initial approach: [here](https://github.com/oppia/oppia-android/blob/12322e5621d670408269abb40a6da26cd5df16a6/utility/src/main/java/org/oppia/android/util/parser/html/CustomHtmlContentHandler.kt#L150-L153)

**Comment by manas-yu** [comment]
Hi @adhiamboperes PTAL, Thanks!

File: utility/src/main/java/org/oppia/android/util/parser/html/CustomHtmlContentHandler.kt (hunk 1 above)
Comment (manas-yu) [reply utility/src/main/java/org/oppia/android/util/parser/html/CustomHtmlContentHandler.kt:149]: Hi @adhiamboperes, just wanted a confirmation if I should follow the initial approach, since that would resolve this comment.

Comment (adhiamboperes) [reply utility/src/main/java/org/oppia/android/util/parser/html/CustomHtmlContentHandler.kt:149]: Is the assumption here that if the image retriever is null, then we won't be able to provide content descriptions?

Comment (adhiamboperes) [reply utility/src/main/java/org/oppia/android/util/parser/html/CustomHtmlContentHandler.kt:149]: Actually, never mind, I think I get it now.

File: utility/src/main/java/org/oppia/android/util/parser/html/CustomHtmlContentHandler.kt [hunk 2]
```diff
@@ -204,6 +210,22 @@ class CustomHtmlContentHandler private constructor(
...
 
+    /**
+     * Called when a custom tag is encountered during content description generation.
+     *
+     * @param attributes the tag's attributes
+     * @param openIndex the index in the output [Editable] at which this tag begins
+     * @param closeIndex the index in the output [Editable] at which this tag ends
+     * @param output the destination [Editable] to which content can be added
+     */
+    fun handleTagForContentDescription(
```
Comment (adhiamboperes) [inline utility/src/main/java/org/oppia/android/util/parser/html/CustomHtmlContentHandler.kt:221]: So far, only `PolicyPageTagHandler` overrides this function. Ben suggests  in https://github.com/oppia/oppia-android/issues/5781#issuecomment-2806775271 that [MathTagHandler.kt#L41](https://github.com/oppia/oppia-android/blame/develop/utility/src/main/java/org/oppia/android/util/parser/html/MathTagHandler.kt#L41) can also be changed. Is there any other possible usage?

File: utility/src/test/java/org/oppia/android/util/parser/html/CustomHtmlContentHandlerTest.kt
Comment (adhiamboperes) [inline utility/src/test/java/org/oppia/android/util/parser/html/CustomHtmlContentHandlerTest.kt:1]: It appears that we could add tests for the which handleTage method has been called by modifying the `FakeTagHandler` to include a fake `handleTagForContentDescription` and following the example of a test like `testParseHtml_withOneCustomTag_handlerIsCalledWithAttributes`

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @manas-yu! Did a full pass here and left some comments. 

Apologies for the delayed review!

File: utility/src/test/java/org/oppia/android/util/parser/html/CustomHtmlContentHandlerTest.kt
Comment (manas-yu) [reply utility/src/test/java/org/oppia/android/util/parser/html/CustomHtmlContentHandlerTest.kt:1]: Added Tests for `handleTagForContentDescription`.

File: utility/src/main/java/org/oppia/android/util/parser/html/CustomHtmlContentHandler.kt (hunk 2 above)
Comment (manas-yu) [reply utility/src/main/java/org/oppia/android/util/parser/html/CustomHtmlContentHandler.kt:221]: Updated `MathTagHandler` to implement the `handleTagForContentDescription`.

**Comment by manas-yu** [comment]
Hi @adhiamboperes PTAL, Thanks!

**Review by adhiamboperes — APPROVED** [review]
Thanks @manas-yu. This LGTM!
