### PR TITLE
Fix #379: Collapse past wrong answers

### LINKED ISSUE #379: Past answers should be collapsed
We should only show the most recently submitted answer, and otherwise collapse the list of N-1 prior answer & feedbacks that can be expanded by the user to see the whole conversation.

### PR DESCRIPTION
**Pull request by BenHenning**
Fix #379.

This change collapses past submitted answers to an expandable bar similar to Oppia web, and tracks the number of wrong answers currently submitted, minus the most recent one (which may be correct). I tried mimicking the exact behavior around when the list re-expands/collapses based on navigating to/from states, and submitting new answers. It's probably worth checking out the branch and playing with it.

There is no mock for this, but I followed @mschanteltc's guidance via chat on text type, size, and color. Otherwise, I tried mimicking the Oppia web version with some small tweaks to make it a bit more Android-esque.

There are no new tests for this, but those should be done as part of #388.

### CODE REVIEW

File: app/src/main/java/org/oppia/app/viewmodel/ObservableArrayList.kt [hunk 1]
```diff
@@ -0,0 +1,81 @@
...
+  }
+
+  private fun notifyAdd(start: Int, count: Int) {
+    listeners.notifyInserted(this, start, count)
+  }
+
+  private fun notifyRemove(start: Int, count: Int) {
+    listeners.notifyRemoved(this, start, count)
+  }
+}
```
Comment (rt4914) [inline app/src/main/java/org/oppia/app/viewmodel/ObservableArrayList.kt]: Missing EOF

File: app/src/main/java/org/oppia/app/viewmodel/ObservableArrayList.kt [hunk 2]
```diff
@@ -0,0 +1,81 @@
+package org.oppia.app.viewmodel
+
+import androidx.databinding.ListChangeRegistry
+import androidx.databinding.ObservableList
+
+/** A version of Android's ObservableArrayList, except with correct Kotlin overrides. */
+class ObservableArrayList<T>: ArrayList<T>(), ObservableList<T> {
```
Comment (rt4914) [inline app/src/main/java/org/oppia/app/viewmodel/ObservableArrayList.kt]: Nit spacing issue: `ObservableArrayList<T> : ArrayList<T>()`

File: app/src/main/java/org/oppia/app/player/state/itemviewmodel/PreviousResponsesHeaderViewModel.kt [hunk 3]
```diff
@@ -0,0 +1,13 @@
+package org.oppia.app.player.state.itemviewmodel
+
+import androidx.databinding.ObservableBoolean
+import org.oppia.app.player.state.listener.PreviousResponsesHeaderClickListener
+
+/** [ViewModel] for the header of the section of previously submitted answers. */
+class PreviousResponsesHeaderViewModel(
+  val previousAnswerCount: Int, var isExpanded: ObservableBoolean,
+  private val previousResponsesHeaderClickListener: PreviousResponsesHeaderClickListener
+): StateItemViewModel(ViewType.PREVIOUS_RESPONSES_HEADER) {
```
Comment (rt4914) [inline app/src/main/java/org/oppia/app/player/state/itemviewmodel/PreviousResponsesHeaderViewModel.kt]: Nit spacing: `) : StateItemViewModel`

**Review by rt4914 — APPROVED** [review]
This new implementation looks really good and improves the UX a lot. Awesome work.

**Review by jamesxu0 — APPROVED** [review]
LGTM. Good UI improvements!

File: app/src/main/java/org/oppia/app/viewmodel/ObservableArrayList.kt (hunk 1 above)
Comment (BenHenning) [reply app/src/main/java/org/oppia/app/viewmodel/ObservableArrayList.kt]: Done.

File: app/src/main/java/org/oppia/app/viewmodel/ObservableArrayList.kt (hunk 2 above)
Comment (BenHenning) [reply app/src/main/java/org/oppia/app/viewmodel/ObservableArrayList.kt]: Done.

File: app/src/main/java/org/oppia/app/player/state/itemviewmodel/PreviousResponsesHeaderViewModel.kt (hunk 3 above)
Comment (BenHenning) [reply app/src/main/java/org/oppia/app/player/state/itemviewmodel/PreviousResponsesHeaderViewModel.kt]: Done.

**Comment by BenHenning** [comment]
Thanks!
