### PR TITLE
Fix #1769: Re-enable previously failing skipped tests (Espresso only)

### LINKED ISSUE #1769: Inputting TextInput answers in landscape auto-closes keyboard
This is the same bug as #1767 except after its cause PR is reverted, this still repros but only for the TextInput interaction which indicates it may have a different root cause.

### PR DESCRIPTION
**Pull request by yurilev**
## Explanation

Fixes #1769: Re-enable previously failing skipped tests (Espresso only):

* `testStateFragment_loadExp_continueToEndExploration_hasReturnToTopicButton()`
* `testStateFragment_loadExp_changeConfiguration_continueToEnd_hasReturnToTopicButton()`

Tested on emulators locally.

Leaving TODOs for #1612 to fix them for Robolectric - similar TODOs are present for the parallel portrait tests.

## Checklist
- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

File: app/src/sharedTest/java/org/oppia/android/app/player/state/StateFragmentTest.kt [hunk 1]
```diff
@@ -809,7 +808,7 @@ class StateFragmentTest {
   }
 
   @Test
-  @Ignore("Currently failing due to a regression") // TODO(#1769): Re-enable.
+  @RunOn(TestPlatform.ESPRESSO) // TODO(#1612): Enable for Robolectric.
```
Comment (yurilev) [inline app/src/sharedTest/java/org/oppia/android/app/player/state/StateFragmentTest.kt:811]: Note there are identical preexisting TODOs for adjacent tests, portrait versions of these two.

**Review by BenHenning — APPROVED** [review]
Thanks @yurilev. This LGTM.

**Comment by BenHenning** [comment]
Though before merging, @yurilev can you confirm which parts of #1769 that this doesn't address?

**Comment by yurilev** [comment]
I titled it "fix part of" because at the time I thought the discussion might lead to more action items. Renamed the pull request to not say "part of".

The tests are still disabled for Robolectric, but that is covered by the TODOs for #1612.

**Comment by BenHenning** [comment]
Thanks @yurilev. SGTM.
