### PR TITLE
Fix #2667: Wrong Tab selected on configuration change in TopicFragment

### LINKED ISSUE #2667: Wrong Tab selected on configuration change in TopicFragment
**Describe the bug**
Lesson Tab is selected on configuration change without changing the fragment of the viewpager

**To Reproduce**

1.Select First Test Topic from Home Carousel.
2. Select the practice tab
3. change the orientation
4. See the error

**Expected behavior**
The fragment should remain what it was before orientation change

**Screenshots**

https://user-images.githubusercontent.com/53645584/107349593-68ec2800-6aee-11eb-8276-a43e564bef55.mp4

**Device**
- Device/emulator being used: Real device Oneplus 7
- SDK version 29

### PR DESCRIPTION
**Pull request by MaskedCarrot**
## Explanation
Fixes #2667 

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

## gif
https://user-images.githubusercontent.com/53645584/107369398-c0e35880-6b07-11eb-835f-4bd0e0034613.mp4

## Espresso Tests
without fix | with fix
--- | ---
Screenshot from 2021-02-15 11-24-48 | Screenshot from 2021-02-15 11-26-49

## Tests after the changes made in this PR.
Espresso | Robolectric
--- | ---
Screenshot from 2021-02-24 14-35-05 | Screenshot from 2021-02-24 14-37-17

### CODE REVIEW

**Comment by anandwana001** [comment]
Few points: 
1. Can we check why do we have this issue at first place? What's causing this issue?
2. If we are solving this, can we have test case related to it?

Currently, we do have a test to test this issue `testTopicFragment_clickOnPracticeTab_configurationChange_showsSameTabAndItsContent` and it's passing for me. 

Could you please confirm!!.

**Comment by FareesHussain** [comment]
@anandwana001 the bug only occurs when navigated through Promoted stories. I guess we need to test it using `HomeActivityTest`

@MaskedCarrot Your implementation does fix this. But you need to track down what might be causing this issue before fixing this, to avoid further bugs related to this. This is also weird that it is only reproduced when navigated through Promoted stories.

**Comment by MaskedCarrot** [comment]
This issue is caused because in the `handleOnCreate` of TopicFragmentPresenter we are setting the viewpager to lessons/info fragment every time the activity is recreated.

**Review by rt4914 — CHANGES_REQUESTED** [review]
@MaskedCarrot Please add a test case for this specific case. The test should be added in `TopicFragmentTest`.

**Comment by anandwana001** [comment]
@rt4914 before going for the test case, could you confirm if the approach looks good to you? Also, what is the root cause of this issue before fixing it? As we are landing on the same topic page but from two different places, what's the difference here?

File: app/src/main/java/org/oppia/android/app/topic/TopicFragment.kt [hunk 1]
```diff
@@ -27,13 +27,15 @@ class TopicFragment : InjectableFragment() {
     val internalProfileId = arguments?.getInt(PROFILE_ID_ARGUMENT_KEY) ?: -1
     val topicId = arguments?.getString(TOPIC_ID_ARGUMENT_KEY) ?: TEST_TOPIC_ID_0
     val storyId = arguments?.getString(STORY_ID_ARGUMENT_KEY) ?: ""
+    val isConfigChanged = savedInstanceState == null
```
Comment (rt4914) [inline app/src/main/java/org/oppia/android/app/topic/TopicFragment.kt]: The naming is incorrect.
It should be once of these:

`val isConfigChanged = savedInstanceState != null`
or
`val isConfigNotChanged = savedInstanceState == null`

File: app/src/main/java/org/oppia/android/app/topic/TopicFragmentPresenter.kt [hunk 2]
```diff
@@ -105,10 +106,12 @@ class TopicFragmentPresenter @Inject constructor(
         }
       }
     }.attach()
-    if (topicId.isNotEmpty() && storyId.isNotEmpty())
-      setCurrentTab(TopicTab.LESSONS)
-    else if (topicId.isNotEmpty() && storyId.isEmpty())
-      setCurrentTab(TopicTab.INFO)
+    if (isConfigChanged) {
```
Comment (rt4914) [inline app/src/main/java/org/oppia/android/app/topic/TopicFragmentPresenter.kt]: Negate this condition based on above suggestion:

Either: `if (!isConfigChanged) {` or `if (isConfigNotChanged) {`

**Review by rt4914 — CHANGES_REQUESTED** [review]
@MaskedCarrot PTAL

**Comment by rt4914** [comment]
> @rt4914 before going for the test case, could you confirm if the approach looks good to you? Also, what is the root cause of this issue before fixing it? As we are landing on the same topic page but from two different places, what's the difference here?

@anandwana001 Yeah the approach is correct. Only the naming is just opposite.

**Cause**: The code is incorrect. It should be like this: if we are on same screen and do orientation change than nothing should change.

From promoted story we show Topic-Lessons in expanded form and from `All topics` section we should `Topic Info`.

File: app/src/main/java/org/oppia/android/app/topic/TopicFragment.kt (hunk 1 above)
Comment (MaskedCarrot) [reply app/src/main/java/org/oppia/android/app/topic/TopicFragment.kt]: done

File: app/src/main/java/org/oppia/android/app/topic/TopicFragmentPresenter.kt (hunk 2 above)
Comment (MaskedCarrot) [reply app/src/main/java/org/oppia/android/app/topic/TopicFragmentPresenter.kt]: done

File: app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt [hunk 3]
```diff
@@ -103,6 +103,8 @@ class TopicFragmentTest {
 
   private val TOPIC_NAME = "Fractions"
 
+  private val FRACTIONS_STORY_ID = "wANbh4oOClga"
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt]: Don't create a new variable for this id, import it from `StoryProgressController`

```kotlin
import org.oppia.android.domain.topic.FRACTIONS_STORY_ID_0
```

File: app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt [hunk 4]
```diff
@@ -343,7 +345,7 @@ class TopicFragmentTest {
   }
 
   @Test
-  fun testTopicFragment_configurationChange_showsDefaultTabAndItsContent() {
+  fun testTopicFragment_configChange_showsDefaultTabAndItsContent() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt:347]: Thanks for fixing this `configChange`.
Could you please check if there is an issue filled to fix this, if yes, include that issue in this PR.

File: app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt [hunk 5]
```diff
@@ -358,19 +360,65 @@ class TopicFragmentTest {
     }
   }
 
+  @Test
+  fun testTopicFragment_withStoryId_clickOnPracticeTab_configChange_showsSameTabAndItsContent() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt:363]: why we are saying `withStoryId`? I think we can skip this.

File: app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt [hunk 6]
```diff
@@ -358,19 +360,65 @@ class TopicFragmentTest {
...
+    launchTopicPlayStoryActivityIntent(
+      internalProfileId,
+      FRACTIONS_TOPIC_ID,
+      FRACTIONS_STORY_ID
+    ).use {
+      testCoroutineDispatchers.runCurrent()
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt:369]: Does this test case fail without this fix?
If yes, please add before/after screenshot of test result showing failure before and passing in after. 

Also, please add 2 more screenshots showing all the tests are passing on Espresso and Robolectric.

File: app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt [hunk 7]
```diff
@@ -358,19 +360,65 @@ class TopicFragmentTest {
...
+  }
+
   private fun launchTopicActivityIntent(
     internalProfileId: Int,
     topicId: String
   ): ActivityScenario<TopicActivity> {
     return launch(createTopicActivityIntent(internalProfileId, topicId))
   }
 
+  private fun launchTopicPlayStoryActivityIntent(
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt:429]: Can we add `kdocs` for this method and the method above to help understand other developers, when to use which function?

Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt:429]: Same with `createTopicPlayStoryActivityIntent` and `createTopicActivityIntent`.

**Review by anandwana001 — CHANGES_REQUESTED** [review]
Nit changes on the Test file.

File: app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt (hunk 4 above)
Comment (MaskedCarrot) [reply app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt:348]: There is no issue open related to topicFragmentTest.

File: app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt (hunk 5 above)
Comment (MaskedCarrot) [reply app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt:363]: we are using `withStoryId` because in all other test cases we are not using`storyid` as an argument to create an intent to launch `TopicActivity` and without passing `storyId` we can't go to lessons tab.

File: app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt (hunk 6 above)
Comment (MaskedCarrot) [reply app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt:370]: yes, this test fails without the fix.
Added screenshots in the description.

File: app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt (hunk 4 above)
Comment (MaskedCarrot) [reply app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt:347]: I found no issue to fix this.

File: app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt (hunk 6 above)
Comment (MaskedCarrot) [reply app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt:369]: Without the fix this test is failing only on espresso. Test on roboelectric passes with or without the fix.

Comment (MaskedCarrot) [reply app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt:369]: added screenshots for espresso tests in the description.

File: app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt (hunk 7 above)
Comment (MaskedCarrot) [reply app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt:429]: done

File: app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt (hunk 3 above)
Comment (MaskedCarrot) [reply app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt]: done

File: app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt (hunk 6 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt:369]: Please add robolectric screenshot too showing all the tests are passing.

**Comment by anandwana001** [comment]
@MaskedCarrot please update the branch

File: app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt (hunk 5 above)
Comment (rt4914) [reply app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt:363]: I think keeping `withStoryId` is correct here because based on that flow of the tabs is decided.

**Review by rt4914 — CHANGES_REQUESTED** [review]
PTAL

1. Update title to this format: `Fix #2667: Wrong Tab selected on configuration change in TopicFragment`. Missing the `:` in current title.
2. Update your branch with develop

File: app/src/main/java/org/oppia/android/app/topic/TopicFragmentPresenter.kt [hunk 8]
```diff
@@ -105,10 +106,12 @@ class TopicFragmentPresenter @Inject constructor(
...
-    if (topicId.isNotEmpty() && storyId.isNotEmpty())
-      setCurrentTab(TopicTab.LESSONS)
-    else if (topicId.isNotEmpty() && storyId.isEmpty())
-      setCurrentTab(TopicTab.INFO)
+    if (!isConfigChanged) {
+      if (topicId.isNotEmpty() && storyId.isNotEmpty())
+        setCurrentTab(TopicTab.LESSONS)
+      else if (topicId.isNotEmpty() && storyId.isEmpty())
+        setCurrentTab(TopicTab.INFO)
+    }
```
Comment (FareesHussain) [inline app/src/main/java/org/oppia/android/app/topic/TopicFragmentPresenter.kt]: I think we can directly use a variable like `previousActiveTab` and use the TopicTab instead.
`isConfigChanged` doesn't look good to me.

**Review by FareesHussain — CHANGES_REQUESTED** [review]
@MaskedCarrot PTAL

File: app/src/main/java/org/oppia/android/app/topic/TopicFragmentPresenter.kt (hunk 8 above)
Comment (MaskedCarrot) [reply app/src/main/java/org/oppia/android/app/topic/TopicFragmentPresenter.kt]: @FareesHussain can you please explain your approach a bit more.

Comment (FareesHussain) [reply app/src/main/java/org/oppia/android/app/topic/TopicFragmentPresenter.kt]: Instead of saving the boolean save the current `TopicTab` and use it in the onSavedInstance(using `addProto`)

Comment (MaskedCarrot) [reply app/src/main/java/org/oppia/android/app/topic/TopicFragmentPresenter.kt]: I think viewpager retains the tab on config change. The problem here was caused because we were changing the tab to the lessons tab every time the activity is created. So I think saving the tab is not be necessary. WDYT

Comment (rt4914) [reply app/src/main/java/org/oppia/android/app/topic/TopicFragmentPresenter.kt]: @MaskedCarrot Your explanation is correct in my opinion.

Comment (rt4914) [reply app/src/main/java/org/oppia/android/app/topic/TopicFragmentPresenter.kt]: @BenHenning I discussed about the first comment that @FareesHussain has mentioned. He informed me that you have suggested to use `savedInstance` to save the values instead of using `configChanged` [Reference](https://docs.google.com/document/d/17mjInnMroI17jlSkn0GhDo-iVw9heF1z8FtjY_saUl0/edit#bookmark=id.vhiko680hbqf). Can you mention the reason why we prefer that over the solution done in this PR.

File: app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt [hunk 9]
```diff
@@ -358,19 +359,79 @@ class TopicFragmentTest {
...
+   * Creates TopicActivity Intent without a storyId
+   */
   private fun createTopicActivityIntent(internalProfileId: Int, topicId: String): Intent {
     return TopicActivity.createTopicActivityIntent(
       ApplicationProvider.getApplicationContext(), internalProfileId, topicId
     )
   }
 
+  /**
+   * Creates TopicActivity Intent with a storyId
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt]: Could you please add a bit more detail something like when to use this and how it will be helpful?

File: app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt [hunk 10]
```diff
@@ -358,19 +359,79 @@ class TopicFragmentTest {
...
+    storyId: String
+  ): Intent {
+    return TopicActivity.createTopicPlayStoryActivityIntent(
+      ApplicationProvider.getApplicationContext(), internalProfileId, topicId, storyId
+    )
+  }
+
+  /**
+   * Launches TopicActivity without a storyId.
+   * This simulates opening a topic from All topics list.
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt:416]: is it correct this simulates All Topics, as I think we have multiple things like Promoted stories, Recently Played, Coming Soon, View All.

@rt4914 please correct me if I am missing something here.

**Review by anandwana001 — CHANGES_REQUESTED** [review]

File: app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt (hunk 10 above)
Comment (rt4914) [reply app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt:416]: This is correct.

For explanation:
1. Click on any item present in `Home Carousel` -> Opens `Topic-Lessons tab`
2. Click on any item present inside `RecentlyPlayedActivity` -> Opens exploration directly
3. Click on any item present on home screen in `All topics` section -> Opens `Topic Info Tab`.

**Comment by rt4914** [comment]
For @BenHenning 's reference: https://github.com/oppia/oppia-android/pull/2670#discussion_r576313799

File: app/src/main/java/org/oppia/android/app/topic/TopicFragmentPresenter.kt (hunk 8 above)
Comment (BenHenning) [reply app/src/main/java/org/oppia/android/app/topic/TopicFragmentPresenter.kt]: We have to be careful when restoring state & make sure that everything we're restoring is ultimately stored in Android's activity-tied Bundle class (otherwise in low memory cases we'll lose all state-- #2571 is tracking fixing this broadly & especially for domain ephemeral state). In this case the current solution is fine since we're relying on arguments to restore state, and that should be stored in the activity-bound Bundle upon configuration change or low memory situations.

File: app/src/main/java/org/oppia/android/app/topic/TopicFragmentPresenter.kt [hunk 11]
```diff
@@ -105,10 +106,12 @@ class TopicFragmentPresenter @Inject constructor(
...
     }.attach()
-    if (topicId.isNotEmpty() && storyId.isNotEmpty())
-      setCurrentTab(TopicTab.LESSONS)
-    else if (topicId.isNotEmpty() && storyId.isEmpty())
-      setCurrentTab(TopicTab.INFO)
+    if (!isConfigChanged) {
+      if (topicId.isNotEmpty() && storyId.isNotEmpty())
+        setCurrentTab(TopicTab.LESSONS)
+      else if (topicId.isNotEmpty() && storyId.isEmpty())
+        setCurrentTab(TopicTab.INFO)
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/topic/TopicFragmentPresenter.kt]: Suggest using a ``when`` instead. Also, be aware that per https://developer.android.com/kotlin/style-guide#formatting we should always add braces if any statements span multiple lines.

File: app/src/main/java/org/oppia/android/app/topic/TopicFragmentPresenter.kt (hunk 8 above)
Comment (rt4914) [reply app/src/main/java/org/oppia/android/app/topic/TopicFragmentPresenter.kt]: @BenHenning Thanks.

@FareesHussain WDYT?

Comment (FareesHussain) [reply app/src/main/java/org/oppia/android/app/topic/TopicFragmentPresenter.kt]: Sounds good to me

**Comment by rt4914** [comment]
@MaskedCarrot You will need to update your branch again. Currently CI checks are failing.

@anandwana001 and @FareesHussain Can you review this again? Thanks.

**Review by FareesHussain — APPROVED** [review]
LGTM

File: app/src/main/java/org/oppia/android/app/topic/TopicFragmentPresenter.kt (hunk 11 above)
Comment (MaskedCarrot) [reply app/src/main/java/org/oppia/android/app/topic/TopicFragmentPresenter.kt]: Should i change these lines to 
```
    when(isConfigChanged) {
      false -> {
        if(topicId.isNotEmpty() && storyId.isNotEmpty()) {
          setCurrentTab(TopicTab.LESSONS)
        }
      }
    }
```
because  by default the viewpager opens topic info fragment in the viewpager.

File: app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt (hunk 9 above)
Comment (MaskedCarrot) [reply app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt]: done

File: app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt [hunk 12]
```diff
@@ -358,19 +359,81 @@ class TopicFragmentTest {
...
+      testCoroutineDispatchers.runCurrent()
+      clickTabAtPosition(position = PRACTICE_TAB_POSITION)
+      testCoroutineDispatchers.runCurrent()
+      matchStringOnListItem(
+        recyclerView = R.id.topic_practice_skill_list,
+        itemPosition = 0,
+        targetViewId = R.id.master_skills_text_view,
+        stringToMatch = "Master These Skills"
+      )
+      onView(isRoot()).perform(orientationLandscape())
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt:378]: could you please confirm one more thing?
When running this test on espresso, is it changing the orientation or it's just passing?

**Review by anandwana001 — CHANGES_REQUESTED** [review]

File: app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt (hunk 12 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt:378]: If it is not changing orientation try running `testTopicFragment_clickOnReviewTab_configChange_showsSameTabAndItsContent` and see if this is changing the orientation. 

I think this is possible because of time delays, but let's just confirm to prevent any other cause.

Comment (MaskedCarrot) [reply app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt:378]: Yes this test is changing the orientation and then passing

Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt:378]: @FareesHussain Could you please this behaviour?

Comment (FareesHussain) [reply app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt:378]: @anandwana001 @MaskedCarrot Sorry for the delay. I've tested this and I was unable to see the orientation change.
```suggestion
      testCoroutineDispatchers.runCurrent()
      onView(isRoot()).perform(orientationLandscape())
```
Using this I was able to see the orientation change

Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt:378]: Thanks, @FareesHussain for confirming. 
@MaskedCarrot Please check the above comment.

Comment (MaskedCarrot) [reply app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt:378]: I checked and found that  I was able to see the orientation change on my real device but i did not see it when I ran it on an emulator 
Thanks @anandwana001 @FareesHussain

File: app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt [hunk 13]
```diff
@@ -375,6 +375,7 @@ class TopicFragmentTest {
         targetViewId = R.id.master_skills_text_view,
         stringToMatch = "Master These Skills"
       )
+      testCoroutineDispatchers.runCurrent()
       onView(isRoot()).perform(orientationLandscape())
       testCoroutineDispatchers.runCurrent()
```
Comment (FareesHussain) [inline app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt:379]: Should we remove this?

**Review by FareesHussain — APPROVED** [review]
LGTM. Added a commet please check

File: app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt (hunk 13 above)
Comment (MaskedCarrot) [reply app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt:380]: I think removing this may cause the orientation to change without switching to the practice tab. WDYT?

Comment (MaskedCarrot) [reply app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt:379]: I think we can remove this because after clicking on the tab we have a `runCurrent()` which will  provide the delay to switch the tab.

File: app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt (hunk 12 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt:378]: This is a good one as you are able to run the test on a real device. 
Could you tell is there any specific configuration you had to do before running espresso test on a real device?

File: app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt (hunk 13 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt:379]: Check if Robolectric passing or not with/without this stabilizing.

File: app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt (hunk 12 above)
Comment (MaskedCarrot) [reply app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt:378]: no, I didn't do any changes to my device for these tests in particular. Though to enable my device to run espresso tests I had to disable battery optimization for oppia app.

File: app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt (hunk 13 above)
Comment (MaskedCarrot) [reply app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt:379]: The robolectric test are passing with or without `testCoroutineDispatchers.runCurrent()`

Comment (MaskedCarrot) [reply app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt:379]: removed unnecessary `testCoroutineDispatchers.runCurrent()` and checked that the tests are still correctly passing on espresso (real device and emulator) and robolectric.

Comment (MaskedCarrot) [reply app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt:379]: added screenshots for the same in description.

**Review by FareesHussain — APPROVED** [review]
LGTM, 
Can you confirm that you are able to see the screen rotation while running the espresso tests.

**Comment by MaskedCarrot** [comment]
yes I can see the orientation change

**Comment by anandwana001** [comment]
I will take a look at this tomorrow.

**Review by anandwana001 — APPROVED** [review]
LGTM

File: app/src/main/java/org/oppia/android/app/topic/TopicFragment.kt [hunk 14]
```diff
@@ -27,13 +27,15 @@ class TopicFragment : InjectableFragment() {
...
+    val isConfigChanged = savedInstanceState != null
 
     return topicFragmentPresenter.handleCreateView(
       inflater,
       container,
       internalProfileId,
       topicId,
-      storyId
+      storyId,
+      isConfigChanged
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/topic/TopicFragment.kt]: Optional, or: ``isConfigChanged = savedInstanceState != null`` which is just as readable without needing a variable.

File: app/src/main/java/org/oppia/android/app/topic/TopicFragmentPresenter.kt (hunk 11 above)
Comment (BenHenning) [reply app/src/main/java/org/oppia/android/app/topic/TopicFragmentPresenter.kt]: I was actually thinking this:

```kotlin
    if (!isConfigChanged) {
      when {
        topicId.isNotEmpty() && storyId.isNotEmpty() -> setCurrentTab(TopicTab.LESSONS)
        topicId.isNotEmpty() && storyId.isEmpty() -> setCurrentTab(TopicTab.INFO)
      }
    }
```

However, that made me then realize this whole thing can be simplified a bit more:

```kotlin
    if (!isConfigChanged && topicId.isNotEmpty()) {
      setCurrentTab(if (storyId.isNotEmpty()) TopicTab.LESSONS else TopicTab.INFO)
    }
```

I'm fine with any of these options (the two above or the current implementation).

**Review by BenHenning — APPROVED** [review]
Thanks @MaskedCarrot! I had a couple thoughts, but feel free to resolve those conversations. The PR LGTM. Please re-assign me if you have any follow-up questions that you'd like my thoughts on.

File: app/src/main/java/org/oppia/android/app/topic/TopicFragment.kt (hunk 14 above)
Comment (MaskedCarrot) [reply app/src/main/java/org/oppia/android/app/topic/TopicFragment.kt]: done

File: app/src/main/java/org/oppia/android/app/topic/TopicFragmentPresenter.kt (hunk 11 above)
Comment (MaskedCarrot) [reply app/src/main/java/org/oppia/android/app/topic/TopicFragmentPresenter.kt]: The above approach makes the code look much cleaner. changed the code with as the above approach

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.
