### PR TITLE
Fix Part #565: Domain on-boarding flag

### LINKED ISSUE #565: Onboarding flow need domain layer controller
Onboarding flow should be visible only once irrespective of learner profile. Introduce domain layer code to control this feature.

### PR DESCRIPTION
**Pull request by nikitamarysolomanpvt**
## Explanation
Duplicate of #574
Onboarding flow should be visible only once irrespective of learner profile. Introduced domain layer code to control this feature.
Oppia app now showing On-boarding on initial app open, and directly to choose profile page upon returning to the app. Both of these states are also properly retained across configuration changes due to Dagger not leading to activities trying to recreate their dependent controllers.

From a testing side, testcase for OnboardingFlowControllerTest is introduced to test OnboardingFlowController.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

File: domain/src/test/java/org/oppia/domain/OnboardingFlowControllerTest.kt [hunk 1]
```diff
@@ -0,0 +1,233 @@
...
+import org.robolectric.annotation.Config
+import javax.inject.Inject
+import javax.inject.Qualifier
+import javax.inject.Singleton
+import kotlin.coroutines.EmptyCoroutineContext
+
+/** Tests for [OnBoardingFlowController]. */
+@RunWith(AndroidJUnit4::class)
+@Config(manifest = Config.NONE)
+class OnBoardingFlowControllerTest {
```
Comment (veena14cs) [inline domain/src/test/java/org/oppia/domain/OnboardingFlowControllerTest.kt]: Please take a look at the class name and file name.

File: model/src/main/proto/example.proto [hunk 2]
```diff
@@ -9,6 +9,10 @@ message UserAppHistory {
   bool already_opened_app = 1;
 }
 
+message OnBoardingFlow {
+  bool already_on_boarded_app = 1;
+  }
```
Comment (veena14cs) [inline model/src/main/proto/example.proto]: Correct indentation.  And can we rename this file to something contextual.

**Review by veena14cs — CHANGES_REQUESTED** [review]
Test cases are passing but it gives some errors.

Screenshot 2020-01-22 at 11 22 54 AM

**Review by rt4914 — APPROVED** [review]
LGTM, Thanks

**Comment by rt4914** [comment]
> Test cases are passing but it gives some errors.
> 
> Screenshot 2020-01-22 at 11 22 54 AM

+1

File: model/src/main/proto/example.proto (hunk 2 above)
Comment (nikitamarysolomanpvt) [reply model/src/main/proto/example.proto]: Corrected indentation.

File: domain/src/test/java/org/oppia/domain/OnboardingFlowControllerTest.kt (hunk 1 above)
Comment (nikitamarysolomanpvt) [reply domain/src/test/java/org/oppia/domain/OnboardingFlowControllerTest.kt]: Done.

**Comment by nikitamarysolomanpvt** [comment]
> > Test cases are passing but it gives some errors.
> > Screenshot 2020-01-22 at 11 22 54 AM
> 
> +1

PTAL on #599. This was discussed in meeting and was told to raise as an issue.

**Review by veena14cs — APPROVED** [review]
LGTM.

File: domain/src/main/java/org/oppia/domain/OnBoardingFlowController.kt [hunk 3]
```diff
@@ -0,0 +1,61 @@
+package org.oppia.domain
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/domain/OnBoardingFlowController.kt]: This doesn't seem like the right package. This ought to go under a subpackage, e.g. ``onboarding``.

File: domain/src/main/java/org/oppia/domain/OnBoardingFlowController.kt [hunk 4]
```diff
@@ -0,0 +1,61 @@
...
+      it.toBuilder().setAlreadyOnBoardedApp(true).build()
+    }.invokeOnCompletion {
+      it?.let {
+        logger.e("DOMAIN", "Failed when storing that the user already on-boarded the app.", it)
+      }
+    }
+  }
+
+  /** Clears any indication that the user has previously completed on-boarding the application. */
+  fun clearOnBoardingFlow() {
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/domain/OnBoardingFlowController.kt]: When will we clear the onboarding flow?

File: model/src/main/proto/example.proto [hunk 5]
```diff
@@ -9,6 +9,10 @@ message UserAppHistory {
   bool already_opened_app = 1;
 }
 
+message OnBoardingFlow {
```
Comment (BenHenning) [inline model/src/main/proto/example.proto]: Is this an example proto? It seems like we want to surface to the UI, so it should go in a final location. Also, please add documentation for this proto & its field.

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @nikitamarysolomanpvt! This generally looks canonical to me. I have some questions about the API & proto that I'd like addressed before I approve. Also, please put the controller/test/proto in final locations.

File: domain/src/main/java/org/oppia/domain/OnBoardingFlowController.kt (hunk 4 above)
Comment (nikitamarysolomanpvt) [reply domain/src/main/java/org/oppia/domain/OnBoardingFlowController.kt]: In test cases we are using...

File: domain/src/main/java/org/oppia/domain/OnBoardingFlowController.kt (hunk 3 above)
Comment (nikitamarysolomanpvt) [reply domain/src/main/java/org/oppia/domain/OnBoardingFlowController.kt]: added subpackage onboarding

File: model/src/main/proto/example.proto (hunk 5 above)
Comment (nikitamarysolomanpvt) [reply model/src/main/proto/example.proto]: onboarding proto is created.

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

File: model/src/main/proto/onboarding.proto [hunk 6]
```diff
@@ -0,0 +1,12 @@
+syntax = "proto3";
+
+package model;
+
+option java_package = "org.oppia.app.model";
+option java_multiple_files = true;
+
+// Structure for user onboarding flow.
+message OnboardingFlow {
+// Determines whether user already onboarded
```
Comment (rt4914) [inline model/src/main/proto/onboarding.proto]: Indentation issue, fix this. Also, full stop at the end.

File: model/src/main/proto/onboarding.proto [hunk 7]
```diff
@@ -0,0 +1,12 @@
+syntax = "proto3";
+
+package model;
+
+option java_package = "org.oppia.app.model";
+option java_multiple_files = true;
```
Comment (rt4914) [inline model/src/main/proto/onboarding.proto:6]: why do we need this here?

**Review by rt4914 — COMMENTED** [review]
Nit changes

File: model/src/main/proto/onboarding.proto (hunk 6 above)
Comment (nikitamarysolomanpvt) [reply model/src/main/proto/onboarding.proto]: Done.

File: model/src/main/proto/onboarding.proto (hunk 7 above)
Comment (nikitamarysolomanpvt) [reply model/src/main/proto/onboarding.proto:6]: Removed.

File: domain/src/main/java/org/oppia/domain/OnBoardingFlowController.kt (hunk 4 above)
Comment (BenHenning) [reply domain/src/main/java/org/oppia/domain/OnBoardingFlowController.kt]: Ah. That's not ideal, I think. We ought to not create test-only backdoors in classes. Instead, we should only define the public API that we need for the production surface area, and test that directly. Do we actually need to clear the state, or can we create a new singleton component to simulate a new app starting? Note that if we need to, we can always delete the file directly via test to simulate a new device.

Note that in this case, tests that include a clear call aren't simulating real production behavior and may actually pass/fail in cases when the user-facing behavior isn't wrong. That may impact our maintenance of this code in the long-term, and could introduce confusion or wrong assumptions by other engineers interacting with this.

File: domain/src/test/java/org/oppia/domain/OnboardingFlowControllerTest.kt [hunk 8]
```diff
@@ -0,0 +1,236 @@
...
+
+  @Test
+  @ExperimentalCoroutinesApi
+  fun testController_onboardedApp_cleared_observeNewController_userDidNotOnboardApp() =
+    runBlockingTest(coroutineContext) {
+      onboardingFlowController.markOnboardingFlowCompleted()
+      advanceUntilIdle()
+
+      // Clear, then recreate another controller.
+      onboardingFlowController.clearOnboardingFlow()
```
Comment (BenHenning) [inline domain/src/test/java/org/oppia/domain/OnboardingFlowControllerTest.kt]: As discussed in the other thread, you can instead simulate this by deleting the cache file that's on disk to avoid needing a clear function.

**Review by BenHenning — APPROVED** [review]
Thanks @nikitamarysolomanpvt! Thanks for cleaning up the location & proto. Please remove the test-only clear function, and then this LGTM for submission. Feel free to follow up with me via chat if you have any questions about removing that function.

File: model/src/main/proto/onboarding.proto (hunk 7 above)
Comment (rt4914) [reply model/src/main/proto/onboarding.proto:6]: @nikitamarysolomanpvt Actually, I was working on app module and remove this line was creating issues. Please undo this change and add this line again.

Comment (nikitamarysolomanpvt) [reply model/src/main/proto/onboarding.proto:6]: Done.

File: domain/src/main/java/org/oppia/domain/OnBoardingFlowController.kt (hunk 4 above)
Comment (nikitamarysolomanpvt) [reply domain/src/main/java/org/oppia/domain/OnBoardingFlowController.kt]: Removed and added in test class

File: domain/src/test/java/org/oppia/domain/OnboardingFlowControllerTest.kt (hunk 8 above)
Comment (nikitamarysolomanpvt) [reply domain/src/test/java/org/oppia/domain/OnboardingFlowControllerTest.kt]: Removed

**Comment by nikitamarysolomanpvt** [comment]
> Thanks @nikitamarysolomanpvt! Thanks for cleaning up the location & proto. Please remove the test-only clear function, and then this LGTM for submission. Feel free to follow up with me via chat if you have any questions about removing that function.

PTAL i removed it from controller and added in test class

File: domain/src/test/java/org/oppia/domain/OnboardingFlowControllerTest.kt [hunk 9]
```diff
@@ -0,0 +1,247 @@
...
+
+  private val coroutineContext by lazy {
+    EmptyCoroutineContext + testDispatcher
+  }
+
+  @Mock
+  lateinit var mockOnboardingObserver: Observer<AsyncResult<OnboardingFlow>>
+
+  @Captor
+  lateinit var onboardinggResultCaptor: ArgumentCaptor<AsyncResult<OnboardingFlow>>
```
Comment (rt4914) [inline domain/src/test/java/org/oppia/domain/OnboardingFlowControllerTest.kt]: This can be written in a single line:
`@Captor  lateinit var onboardinggResultCaptor: ArgumentCaptor<AsyncResult<OnboardingFlow>>`

Ditto for above line.

File: domain/src/test/java/org/oppia/domain/OnboardingFlowControllerTest.kt [hunk 10]
```diff
@@ -0,0 +1,247 @@
...
+  interface TestApplicationComponent {
+    @Component.Builder
+    interface Builder {
+      @BindsInstance
+      fun setApplication(application: Application): Builder
+
+      fun build(): TestApplicationComponent
+    }
+
+    fun inject(onboardinggFlowControllerTest: OnboardingFlowControllerTest)
```
Comment (rt4914) [inline domain/src/test/java/org/oppia/domain/OnboardingFlowControllerTest.kt]: Typo update:
`fun inject(onboardingFlowControllerTest: OnboardingFlowControllerTest)`

File: domain/src/test/java/org/oppia/domain/OnboardingFlowControllerTest.kt [hunk 11]
```diff
@@ -0,0 +1,247 @@
...
+      .setApplication(ApplicationProvider.getApplicationContext())
+      .build()
+      .inject(this)
+  }
+
+  @Test
+  @ExperimentalCoroutinesApi
+  fun testController_providesInitialLiveData_thatIndicatesUserHasNotOnboardedTheApp() =
+    runBlockingTest(coroutineContext) {
+      val onboardingg = onboardingFlowController.getOnboardingFlow()
```
Comment (rt4914) [inline domain/src/test/java/org/oppia/domain/OnboardingFlowControllerTest.kt]: Typo:
onboardingg -> onboarding
Ditto everywhere else.

File: domain/src/test/java/org/oppia/domain/OnboardingFlowControllerTest.kt [hunk 12]
```diff
@@ -0,0 +1,247 @@
...
+  private fun setUpTestApplicationComponent() {
+    DaggerOnboardingFlowControllerTest_TestApplicationComponent.builder()
+      .setApplication(ApplicationProvider.getApplicationContext())
+      .build()
+      .inject(this)
+  }
+
+  @Test
+  @ExperimentalCoroutinesApi
+  fun testController_providesInitialLiveData_thatIndicatesUserHasNotOnboardedTheApp() =
```
Comment (rt4914) [inline domain/src/test/java/org/oppia/domain/OnboardingFlowControllerTest.kt]: Update:
`testController_providesInitialLiveData_indicatesUserHasNotOnboardedTheApp`

File: domain/src/test/java/org/oppia/domain/OnboardingFlowControllerTest.kt [hunk 13]
```diff
@@ -0,0 +1,247 @@
...
+      // The app should be considered not yet onboarded since the previous history was cleared.
+      verify(mockOnboardingObserver, atLeastOnce()).onChanged(onboardinggResultCaptor.capture())
+      assertThat(onboardinggResultCaptor.value.isSuccess()).isTrue()
+      assertThat(onboardinggResultCaptor.value.getOrThrow().alreadyOnboardedApp).isFalse()
+    }
+
+  /** Clears any indication that the user has previously completed onboarding the application. */
+  private fun clearOnboardingFlow(onboardingFlowStore: PersistentCacheStore<OnboardingFlow>) {
+    onboardingFlowStore.clearCacheAsync().invokeOnCompletion {
+      it?.let {
```
Comment (rt4914) [inline domain/src/test/java/org/oppia/domain/OnboardingFlowControllerTest.kt]: This can actually be removed as we are not anything inside this.
`onboardingFlowStore.clearCacheAsync()` this is enough.

File: domain/src/test/java/org/oppia/domain/OnboardingFlowControllerTest.kt [hunk 14]
```diff
@@ -0,0 +1,247 @@
...
+      }
+    }
+  }
+
+  @Qualifier
+  annotation class TestDispatcher
```
Comment (rt4914) [inline domain/src/test/java/org/oppia/domain/OnboardingFlowControllerTest.kt]: Nit: Single line
`@Qualifier  annotation class TestDispatcher`

**Review by rt4914 — APPROVED** [review]
Nit changes suggested.

File: domain/src/test/java/org/oppia/domain/OnboardingFlowControllerTest.kt (hunk 9 above)
Comment (nikitamarysolomanpvt) [reply domain/src/test/java/org/oppia/domain/OnboardingFlowControllerTest.kt]: Done

File: domain/src/test/java/org/oppia/domain/OnboardingFlowControllerTest.kt (hunk 10 above)
Comment (nikitamarysolomanpvt) [reply domain/src/test/java/org/oppia/domain/OnboardingFlowControllerTest.kt]: Done

File: domain/src/test/java/org/oppia/domain/OnboardingFlowControllerTest.kt (hunk 11 above)
Comment (nikitamarysolomanpvt) [reply domain/src/test/java/org/oppia/domain/OnboardingFlowControllerTest.kt]: Done

File: domain/src/test/java/org/oppia/domain/OnboardingFlowControllerTest.kt (hunk 12 above)
Comment (nikitamarysolomanpvt) [reply domain/src/test/java/org/oppia/domain/OnboardingFlowControllerTest.kt]: Done

File: domain/src/test/java/org/oppia/domain/OnboardingFlowControllerTest.kt (hunk 13 above)
Comment (nikitamarysolomanpvt) [reply domain/src/test/java/org/oppia/domain/OnboardingFlowControllerTest.kt]: Done

File: domain/src/test/java/org/oppia/domain/OnboardingFlowControllerTest.kt (hunk 14 above)
Comment (nikitamarysolomanpvt) [reply domain/src/test/java/org/oppia/domain/OnboardingFlowControllerTest.kt]: Done.
