### PR TITLE
Fixes part of #2627: Pin Verification screen A11y

### LINKED ISSUE #2256: Changes needed in Pin Password Activity [A11y] [BLOCKED]
**Describe the bug**

Pin Password Activity is not fully compatible with some users from the Accessibility point of view.

Issue 1 - The pinView inside the pin_password_activity.xml does not have any content label (inactive state)
Issue 2 - The reset pin dialog box has a profile input view which also misses a label.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start the Accessibility Scanner App on your device
2. Open the Oppia Android App and try to login as a user. 
3. Scan the screenshots with the Accessibility Scanner
4. You will see the tests that are not passed by that screen
5. Repeat this for other screens

**Expected behaviour**
All the tests must be passed by scanning the screenshots for both Tablet and Mobile Devices in every orientation.

**Screenshots**

| Issue 1  |    Issue 2    |
|:--------:|:-------------:|
|Screenshot_2020-12-06-23-55-11-56_80a9469f53bfe75dbc6e8989be28e2f0|  Screenshot_2020-12-06-23-54-15-94_80a9469f53bfe75dbc6e8989be28e2f0 | 
|Screenshot_2020-12-06-23-53-09-67_80a9469f53bfe75dbc6e8989be28e2f0| |

**Device**
- Real Device - RealMe3
- SDK version - 29

**Additional context**
The Screenshots are descriptive enough for understanding the issues but still, if there is a need of clarification then you can comment here. Multiple Pull Requests can also be made for solving these issues.

Reference - [https://github.com/oppia/oppia-android/wiki/Working-on-UI#accessibility-scanner](https://github.com/oppia/oppia-android/wiki/Working-on-UI#accessibility-scanner)

### PR DESCRIPTION
**Pull request by rt4914**
## Explanation

Fixes part of #2627 (part 2 & 3)

Fixes part of #2256 (part 1)

This PR mainly focuses on two things:
1. The icons have been reversed. It was mentioned by Chantel [here](https://github.com/oppia/oppia-android/issues/2627#issuecomment-781659348) but it still needs to be reflected in the mocks.
2. Introduces strings which will be used by screen readers.
3. Thr flow for `show/hide password` selection has been fixed.

**Output**
https://user-images.githubusercontent.com/9396084/114103894-891a4680-98e7-11eb-8a5c-8b433cc73445.mp4

**Known Issue**
1. The current output mentions "Oppia" string in between but that is getting solved in #3028 PR.
2. And Part 1 or original issue is pending.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Review by FareesHussain — APPROVED** [review]
LGTM, Thanks

**Review by Arjupta — APPROVED** [review]
@rt4914 this PR only solves Issue -1 of the #2256 , also there are only two sub-issues for it. May be you wanted to reference part 2 & 3 of any other Issue. Rest LGTM

**Comment by rt4914** [comment]
> @rt4914 this PR only solves Issue -1 of the #2256 , also there are only two sub-issues for it. May be you wanted to reference part 2 & 3 of any other Issue. Rest LGTM

@ARJUPTA Incorrect issue was mentioned. Can you recheck this?

**Comment by Arjupta** [comment]
> > @rt4914 this PR only solves Issue -1 of the #2256 , also there are only two sub-issues for it. May be you wanted to reference part 2 & 3 of any other Issue. Rest LGTM
> 
> @ARJUPTA Incorrect issue was mentioned. Can you recheck this?

Yes it looks correct now. Also this PR solves Part-1 of previously mentioned issue (#2256) as both issues are related to pin verification activity. I suggest to include the changes for Part-2 of previously mentioned issue as it just needs a label to be added for the dialog fragment for password reset. Then we can close both of these issues simultaneously.

File: app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt [hunk 1]
```diff
@@ -719,7 +761,29 @@ class PinPasswordActivityTest {
...
+  fun testPinPassword_withAdmin_clickShowHideIcon_hasPasswordShownContentDescription() {
+    ActivityScenario.launch<PinPasswordActivity>(
+      PinPasswordActivity.createPinPasswordActivityIntent(
+        context = context,
+        adminPin = adminPin,
+        profileId = adminId
+      )
+    ).use {
+      closeSoftKeyboard()
+      onView(withId(R.id.show_pin)).perform(click())
```
Comment (MaskedCarrot) [inline app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt:820]:
```suggestion
      testCoroutineDispatchers.runCurrent()
      onView(withId(R.id.show_pin)).perform(click())
```
test is failing because less than 90 percent of the view is visible.

**Review by MaskedCarrot — COMMENTED** [review]
@rt4914 the test  `testPinPassword_withAdmin_showHidePassword_imageChangesToHide` is failing.

**Comment by anandwana001** [comment]
Will review this today.

File: app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt (hunk 1 above)
Comment (rt4914) [reply app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt:820]: Tests are passing now. Thanks.

**Review by MaskedCarrot — APPROVED** [review]
LGTM, thanks

File: app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt [hunk 2]
```diff
@@ -147,6 +148,27 @@ class PinPasswordActivityTest {
     }
   }
 
+  @Test
+  fun testPinPassword_pinView_hasContentDescription() {
+    ActivityScenario.launch<PinPasswordActivity>(
+      PinPasswordActivity.createPinPasswordActivityIntent(
+        context = context,
+        adminPin = adminPin,
+        profileId = adminId
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt:157]: `profileId = adminId` this doesn't sounds good. Can we have a good first issue for this?

File: app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt [hunk 3]
```diff
@@ -147,6 +148,27 @@ class PinPasswordActivityTest {
     }
   }
 
+  @Test
+  fun testPinPassword_pinView_hasContentDescription() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt:152]: can we have a landscape version of this test? as we are setting content description in the land version of XML so it's different from the regular one.

**Review by anandwana001 — APPROVED** [review]
LGTM, nit questions.

File: app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt (hunk 2 above)
Comment (rt4914) [reply app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt:157]: I think this is correct. What do you suggest instead?

File: app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt (hunk 3 above)
Comment (rt4914) [reply app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt:152]: Added another test.

File: app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt (hunk 2 above)
Comment (rt4914) [reply app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt:157]: All tests passed. Resolving this.

File: app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt (hunk 3 above)
Comment (rt4914) [reply app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt:152]: All tests passed. Resolving this.
