### PR TITLE
Fixes #5972: Profile name accepts invalid inputs like single dot (.) or single space ( )

### LINKED ISSUE #5972: [Validation Issue]: Profile name accepts invalid inputs like single dot (.) or single space ( )
### Describe the bug

The profile name field incorrectly allows a single dot (.) or a single space ( ). These are not valid names. 
Double dots (..) and double spaces ( ) are rejected correctly.

### Steps To Reproduce

- After App starts up
- Go to Admin Control and enter the Admin pin
- Select Edit Profiles
- Click and Rename any profile(New/Admin) with  single dot (.) or a single space ( )

### Expected Behavior

- Profile names should require at least one valid letter
- Inputs that are only special characters or spaces should not be accepted

### Screenshots/Videos

https://github.com/user-attachments/assets/a6f34375-6427-4ccf-b302-42d98c59b637

Image

### What device/emulator are you using?

Vivo v21e

### Which Android version is your device/emulator running?

Android 13

### Which version of the Oppia Android app are you using?

0.16-beta-5f3e75afa7

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by ShankhanilSaha**
## Explanation

Fixes #5972 

- Updates `utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt` to only allow names which have only alphabets and spaces.
- Now names with single dots(.) and single spaces( ) are not allowed anymore which previously were.
- Creates function `createDefaultProfile()` in `domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt` to create a default profile during onboarding with no checks other than checking no accounts are already present to prevent create a invalid account.
- Create exception type `PROFILES_ALREADY_EXIST` for function to return if condition not met.
- Replace `addProfile()` with  `createDefaultProfile()` in `createDefaultAdminProfile()` and `createDefaultProfile()`.
- Add tests for new profile name verification logic.
- Add tests for `createDefaultProfile()` function ensuring it works as intended.

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

### CODE REVIEW

File: utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt [hunk 1]
```diff
@@ -18,21 +15,27 @@ class ProfileNameValidator @Inject constructor() {
...
-  private fun containsNoRepeatedUseOfAllowedSymbols(name: String): Boolean {
-    return !name.contains(noRepeatedAllowedSymbolsRegex)
+  /** Ensures that name does not contains only spaces. */
+  private fun notOnlySpaces(name: String): Boolean {
+    name.forEach {
+      if (it.isAlphabetic()) {
+        return true
+      }
+    }
+    return false
```
Comment (adhiamboperes) [inline utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt]: This function is not needed -- Kotlin has an in-built `isBlank()` extension function that checks whethera char sequence is empty or consists solely of whitespace characters.

File: utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt [hunk 2]
```diff
@@ -18,21 +15,27 @@ class ProfileNameValidator @Inject constructor() {
...
+    return containsOnlyLettersAndSpaces(name) && notOnlySpaces(name)
   }
 
-  /** Validates if the character in the name is an alphabet or an allowed symbol or not. */
-  private fun containsOnlyLettersAndAllowedSymbols(name: String): Boolean {
+  /** Validates if the character in the name is an alphabet or a space. */
+  private fun containsOnlyLettersAndSpaces(name: String): Boolean {
     name.forEach {
-      if (!(it.isAlphabetic() || it in repeatableSymbols)) {
+      if (!(it.isAlphabetic() || it == space)) {
```
Comment (adhiamboperes) [inline utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt]: This could probably be simplified to:
```suggestion
      if (!(it.trim().isAlphabetic())) {
```

Comment (adhiamboperes) [reply utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt]: Could you please look into  why `forEach ` is used here? s it really needed?

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @ShankhanilSaha! I have reviewed the PR and left some comments. Also, please take a look at the CI results -- tests in `ProfileManagementControllerTest` are failing due to the changed logic. Please locate the failing tests and either fix them, or verify whether the new logic is working correctly. 

Please also reach out if you have any questions.

File: utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt (hunk 2 above)
Comment (ShankhanilSaha) [reply utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt]: > This could probably be simplified to:

@adhiamboperes The `Char.isAlphabetic()` function is not designed to give `true` output to spaces(' ') which fall in category `CharCategory.SPACE_SEPARATOR`. 
in `if (!(it.trim().isAlphabetic())) {` `.trim()` would only remove leading and trailing spaces thus names with spaces in between would return false thus `|| it == space is necessary`
It can be simplified to your suggestion but for that we have to include `CharCategory.SPACE_SEPARATOR` in `Char.isAlphabetic()` function and rename it to `Char.isAlphabeticOrSpace()` i can do that if you need.

Comment (ShankhanilSaha) [reply utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt]: About `.forEach{` it checks and returns false even if one letter is not of the categories in `.isAlphabetic()` or a space(' ') this can be removed and written in a more simple manner without hampering code efficiency by replacing it with `name.any { !(it.isAlphabetic() && it == space) }`.

File: utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt (hunk 1 above)
Comment (ShankhanilSaha) [reply utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt]: alright i will remove this function and update
`return containsOnlyLettersAndSpaces(name) && notOnlySpaces(name)` to `return containsOnlyLettersAndSpaces(name) && !name.isBlank()`.

**Comment by ShankhanilSaha** [comment]
Hi @adhiamboperes, the tests are primarily failing because of the tests in `utility/src/test/java/org/oppia/android/util/profile/ProfileNameValidatorTest.kt`
should i completely remove the tests which are verifying names which were formerly allowed? or should i update them to something like the code in the attatchment which will expect false to formerly allowed names.
Screenshot_20251105_230528

**Comment by ShankhanilSaha** [comment]
@adhiamboperes could you please check the error logs once, some tests were failing previously so i fixed them by changing the functions to `addAdminProfileAndWait()` which fixed the issue of the test looking for a profile before it was even created. 
But now it seems like there is some maven related dependency downloading issue which i believe has not arrived from my code, could be wrong.

**Comment by theMr17** [comment]
@ShankhanilSaha I've re-run the tests, they should work fine now.

**Comment by ShankhanilSaha** [comment]
@adhiamboperes upon making the file changes in this PR a few tests fail in `app/src/sharedTest/java/org/oppia/android/app/onboarding/CreateProfileFragmentTest.kt`
and 
`testing/src/test/java/org/oppia/android/testing/profile/ProfileTestHelperTest.kt` even tho tests are unrelated to the changes since they don't use any name which passed previously but gets rejected with the changes. I could use some help with this one.

**Comment by adhiamboperes** [comment]
Hi @ShankhanilSaha, those tests are failing because they rely on the `ProfileManagementController`, which relies on the `ProfileNameValidator`

**Comment by adhiamboperes** [comment]
Looking at the traces, it appears that the failing functions rely on an exception that has changed, so there are changes needed downstream as well. I need to review the code first.

File: utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt [hunk 3]
```diff
@@ -35,6 +37,16 @@ class ProfileNameValidator @Inject constructor() {
...
 
+  /** Checks if name contains only symbols */
+  private fun doesNotContainOnlyAllowedSymbolsAndSpaces(name: String): Boolean {
+    name.forEach {
+      if (it.isAlphabetic()) {
+        return true
+      }
+    }
+    return false
+  }
```
Comment (adhiamboperes) [inline utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt:42]: Can be simplified to:
```suggestion
 private fun doesNotContainOnlyAllowedSymbolsAndSpaces(name: String): Boolean {
    return name.any { it.isAlphabetic() }
  }
```

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @ShankhanilSaha. Left a suggestion, PTAL.

**Comment by adhiamboperes** [comment]
> CreateProfileFragmentTest

@ShankhanilSaha, the failing tests in `CreateProfileFragmentTest` and  `ProfileTestHelperTest` are most likely due to the fact that we are no longer allowing empty names, but in the `OnboardingFragmentPresenter`, we have a `createDefaultProfile` function which is meant to create a dummy profile, to be filled later. This lead to the creation of `fun createDefaultAdminProfile()` in  `ProfileTestHelper` as a helper functions for the scenarios where we need a default empty profile.

The failing tests are probably usages of `ProfileTestHelper.createDefaultAdminProfile()`. Please review each of the failing tests and see if any usage of `createDefaultAdminProfile` can be replaced by `addOnlyAdminProfile`, and in cases where the function cannot be replaced(because it is the functionality under test), or you are unsure, please raise these in the group chat for resolution.

File: utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt (hunk 3 above)
Comment (ShankhanilSaha) [reply utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt:42]: Thanks @adhiamboperes , will change it. I used `.forEach` because it was previously used in the same file and I just used that as a reference.
While I am at it 
```
  private fun containsOnlyLettersAndAllowedSymbols(name: String): Boolean {
    name.forEach {
      if (!(it.isAlphabetic() || it in repeatableSymbols)) {
        return false
      }
    }
    return true
  }
```
can also be simplified to 
```
 private fun containsOnlyLettersAndAllowedSymbols(name: String): Boolean {
    return name.all{ it.isAlphabetic() || it in repeatableSymbols }
}
```
should i change that aswell?

Comment (adhiamboperes) [reply utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt:42]: Yes, that would be fine.

Comment (ShankhanilSaha) [reply utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt:42]: done

**Comment by ShankhanilSaha** [comment]
Hi @adhiamboperes , in `CreateProfileFragmentTest` and `ProfileTestHelperTest`, the appropriate files are not loaded for the `addAdminProfileAndWait()` function.

However, `profileTestHelper` has another function `addOnlyAdminProfile()`. Unlike `createDefaultAdminProfile()`, this starts the setup fresh and ensures there is initially only a single admin profile. I believe this is more suitable for tests, and it fixes the failures (verified locally).

That said, since this doesn't relate directly to the name validation logic, I am not sure why `createDefaultAdminProfile() `causes the failures. I noticed in previous tests I fixed that `createDefaultAdminProfile()` was often the root cause. It may not be suitable for tests due to slow execution (I tried using `addAdminProfileAndWait()` because the logs showed the test checking for a profile before the function had finished creating it).

**Comment by adhiamboperes** [comment]
Hi @ShankhanilSaha,
 
> That said, since this doesn't relate directly to the name validation logic, I am not sure why `createDefaultAdminProfile() `causes the failures. I noticed in previous tests I fixed that `createDefaultAdminProfile()` was often the root cause. It may not be suitable for tests due to slow execution (I tried using `addAdminProfileAndWait()` because the logs showed the test checking for a profile before the function had finished creating it).

`createDefaultAdminProfile()` fails because if you look at the implementation of the function, it creates a profile with an empty name. The new validation logic prohibits empty names. So the function should be updated to have a profile name, e.g. John.

**Comment by adhiamboperes** [comment]
Please also remember to update the default profile in `OnboardingFragmentPresenter` to have a default name, "Admin" while keeping the rest of the fields blank as they are. Refer to my previous explanation quoted below.

> @ShankhanilSaha, the failing tests in `CreateProfileFragmentTest` and `ProfileTestHelperTest` are most likely due to the fact that we are no longer allowing empty names, but in the `OnboardingFragmentPresenter`, we have a `createDefaultProfile` function which is meant to create a dummy profile, to be filled later. This lead to the creation of `fun createDefaultAdminProfile()` in `ProfileTestHelper` as a helper functions for the scenarios where we need a default empty profile.

**Comment by ShankhanilSaha** [comment]
Hi @adhiamboperes could you please let me know about the new function replacing the `createDefaultAdminProfile()` in brief.

**Comment by adhiamboperes** [comment]
Hi Shankhanil,
Please create a new function in the `ProfileManagementController` for creating a default profile. It would have no validations(such as the name validation) and all fields would have default values. It should however check that there are no existing profiles(to avoid misuse).

This function should only be used on the onboarding fargment presenter(where the default profile is currently being created) and the test helper(also as a replacement of the create default profile helper).

Please let me know if you need any further support.

**Comment by ShankhanilSaha** [comment]
Hi @adhiamboperes , i am primarily referring to the `addProfile()` fucntion in the `ProfileManagementController` [file](https://github.com/oppia/oppia-android/blob/develop/domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt) as it is somewhat similar to the function I need to make. Had some questions about the default profile being created, the parameters being passed  `name: String,
    pin: String,
    avatarImagePath: Uri?,
    allowDownloadAccess: Boolean,
    colorRgb: Int,
    isAdmin: Boolean` you said should all be default values. Should I just hard code the default values in the function definition or can just make the `newProfileBuilder` without any parameters and it somehow automatically handles them. If not the later what should the default values be such as name, etc. Also should the profile be admin?

**Comment by adhiamboperes** [comment]
> Hi @adhiamboperes , i am primarily referring to the `addProfile()` fucntion in the `ProfileManagementController` [file](https://github.com/oppia/oppia-android/blob/develop/domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt) as it is somewhat similar to the function I need to make. Had some questions about the default profile being created, the parameters being passed `name: String, pin: String, avatarImagePath: Uri?, allowDownloadAccess: Boolean, colorRgb: Int, isAdmin: Boolean` you said should all be default values. Should I just hard code the default values in the function definition or can just make the `newProfileBuilder` without any parameters and it somehow automatically handles them. If not the later what should the default values be such as name, etc. Also should the profile be admin?


You should hard code them in the arguments, similar to what is passed in the `createDefaultAdminProfile()`

**Comment by ShankhanilSaha** [comment]
Hi @adhiamboperes , for checking if there are no existing profile 
```
if (it.profilesCount > 0) {
    //Returns in case profiles 
    return@storeDataWithCustomChannelAsync Pair(it, ProfileActionStatus.PROFILES_EXIST) do exist in the db
}
```
what  should I pair in the return statement? Shall I add a attribute in `ProfileActionStatus` called `PROFILES_EXIST`?
Also should the default profile have admin access?

**Comment by ShankhanilSaha** [comment]
Also this is my proposed function, i just took `addProfile()` as a reference. Could you please take a look and let me know the changes needed?
```
    fun createDefaultProfile(): DataProvider<Any?> {
    val deferred = profileDataStore.storeDataWithCustomChannelAsync(
      updateInMemoryCache = true
    ) {
      if (it.profilesCount > 0) {
        return@storeDataWithCustomChannelAsync Pair(it, ProfileActionStatus.PROFILES_EXIST)
      }

      val nextProfileId = it.nextProfileId
      val profileDir = directoryManagementUtil.getOrCreateDir(nextProfileId.toString())

      val newProfile = Profile.newBuilder().apply {
        this.name = ""
        this.pin = ""
        this.allowDownloadAccess = false
        this.allowInLessonQuickLanguageSwitching = false
        this.id = ProfileId.newBuilder().setInternalId(nextProfileId).build()
        dateCreatedTimestampMs = oppiaClock.getCurrentTimeMs()
        this.isAdmin = false
        readingTextSize = ReadingTextSize.MEDIUM_TEXT_SIZE
        numberOfLogins = 0

        avatar = ProfileAvatar.newBuilder().apply {
          avatarColorRgb = -10710042
        }.build()
      }.build()

      val wasProfileEverAdded = it.profilesCount > 0

      val profileDatabaseBuilder =
        it.toBuilder()
          .putProfiles(nextProfileId, newProfile)
          .setWasProfileEverAdded(wasProfileEverAdded)
          .setNextProfileId(nextProfileId + 1)
      Pair(profileDatabaseBuilder.build(), ProfileActionStatus.SUCCESS)
    }
    return dataProviders.createInMemoryDataProviderAsync(ADD_PROFILE_PROVIDER_ID) {
      return@createInMemoryDataProviderAsync getDeferredResult(null, name, deferred)
    }
  }
```

**Comment by ShankhanilSaha** [comment]
@adhiamboperes The function is created and applied in the necessary places, Please take a look. Also the tests seem to be failing again for those dependencies download issue.

File: domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt [hunk 4]
```diff
@@ -1199,6 +1246,9 @@ class ProfileManagementController @Inject constructor(
         )
       ProfileActionStatus.PROFILE_TYPE_UNKNOWN ->
         AsyncResult.Failure(UnknownProfileTypeException("ProfileType must be set."))
+
+      ProfileActionStatus.PROFILES_ALREADY_EXIST ->
+        AsyncResult.Failure(ProfilesAlreadyExistException("Profiles already exist."))
```
Comment (adhiamboperes) [inline domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt]: Suggest making the error message more descriptive.

```suggestion
        AsyncResult.Failure(ProfilesAlreadyExistException("Failed to create a default profile because profiles already exist."))
```

File: utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt [hunk 5]
```diff
@@ -18,23 +18,26 @@ class ProfileNameValidator @Inject constructor() {
...
-    return true
+    return name.all { it.isAlphabetic() || it in repeatableSymbols }
   }
 
+  /** Makes sure that there are no repeated symbols in the name. */
   private fun containsNoRepeatedUseOfAllowedSymbols(name: String): Boolean {
     return !name.contains(noRepeatedAllowedSymbolsRegex)
   }
 
+  /** Checks if name contains only symbols */
```
[the remark this answers is not in the document]
Comment (adhiamboperes) [reply utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt]: Not sure why Copilot is configured for this PR, but the review comment is valid -- the KDoc is confusing.

```suggestion
 /**
   * Ensures the name is not made up exclusively of allowed symbols
   * (i.e. it must contain at least one alphabetic character).
   */
```

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @ShankhanilSaha! The implementation now follows the suggested fix. What is missing is tests for the changes.

[ProfileNameValidatorTest.kt](https://github.com/oppia/oppia-android/blob/release-0.17/utility/src/test/java/org/oppia/android/util/profile/ProfileNameValidatorTest.kt.) needs tests to verify that names that are single dot (.) or single space ( ) fail validation(this verifies that the reported bug is fixed).

[ProfileManagementControllerTest.kt](https://github.com/oppia/oppia-android/blob/release-0.17/domain/src/test/java/org/oppia/android/domain/profile/ProfileManagementControllerTest.kt) needs tests for the  new `createDefaultProfile`API, verifying the conditions added, e.g. an error is returned if profiles already exist, the default profile is created successfully with all the expected defaults. You will be able to find similar tests for the `addProfile` function to use as examples.

Another validation is to launch the app wth the onboardingv2 feature flag enabled, and verify that onboarding works correctly. In https://github.com/oppia/oppia-android/blob/92346c369d7cde3593b8bedd576254e75295ef8b/config/src/java/org/oppia/android/config/platform/feature_flags.textproto#L59

File: domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt (hunk 4 above)
Comment (ShankhanilSaha) [reply domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt]: Done

**Comment by ShankhanilSaha** [comment]
@adhiamboperes I have added the mentioned tests and addressed the requested changes. Please take a look.

File: domain/src/test/java/org/oppia/android/domain/profile/ProfileManagementControllerTest.kt [hunk 6]
```diff
@@ -123,6 +123,68 @@ class ProfileManagementControllerTest {
     TestPlatformParameterModule.reset()
   }
 
+  @Test
+  fun testCreateDefaultProfile_createDefaultProfile_checkResultIsFailure() {
```
Comment (adhiamboperes) [inline domain/src/test/java/org/oppia/android/domain/profile/ProfileManagementControllerTest.kt]:
```suggestion
  fun testCreateDefaultProfile_whileProfileAlreadyExists_checkResultIsFailure() {
```

File: domain/src/test/java/org/oppia/android/domain/profile/ProfileManagementControllerTest.kt [hunk 7]
```diff
@@ -123,6 +123,68 @@ class ProfileManagementControllerTest {
...
+    setUpTestApplicationComponent()
+    createDefaultProfile()
+    val dataProvider = createDefaultProfile()
```
Comment (adhiamboperes) [inline domain/src/test/java/org/oppia/android/domain/profile/ProfileManagementControllerTest.kt:132]:
```suggestion
// Ensure a profile already exists.
    createDefaultProfile()
    // Attempt to create another default profile.
    val dataProvider = createDefaultProfile()
```

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Left a suggestion.

File: domain/src/test/java/org/oppia/android/domain/profile/ProfileManagementControllerTest.kt (hunk 6 above)
Comment (ShankhanilSaha) [reply domain/src/test/java/org/oppia/android/domain/profile/ProfileManagementControllerTest.kt]: @adhiamboperes 
``` 
fun testCreateDefaultProfile_whileProfileAlreadyExists_onBoardingV2Enabled_checkResultIsFauilure() {
```
exceeds the 100 characters a line lint limit .
so i renamed the function to 
``` 
fun testCreateDefaultProfile_ifProfileAExists_onBoardingV2Enabled_checkResultIsFauilure() {
```
is that name fine?

File: domain/src/test/java/org/oppia/android/domain/profile/ProfileManagementControllerTest.kt [hunk 8]
```diff
@@ -136,9 +138,11 @@ class ProfileManagementControllerTest {
   }
 
   @Test
-  fun testCreateDefaultProfile_createDefaultProfile_onBoardingV2Enabled_checkProfileIsFauilure() {
+  fun testCreateDefaultProfile_ifProfileExists_onBoardingV2Enabled_checkResultIsFauilure() {
```
Comment (adhiamboperes) [inline domain/src/test/java/org/oppia/android/domain/profile/ProfileManagementControllerTest.kt]: Nit on spelling.
```suggestion
  fun testCreateDefaultProfile_ifProfileExists_onBoardingV2Enabled_checkResultIsFailure() {
```

**Review by adhiamboperes — APPROVED** [review]
Thanks @ShankhanilSaha! Great job on this task.

I am approving the PR but left a nit comment. Let me know when that is fixed so that I can merge the PR.

File: domain/src/test/java/org/oppia/android/domain/profile/ProfileManagementControllerTest.kt (hunk 6 above)
Comment (adhiamboperes) [reply domain/src/test/java/org/oppia/android/domain/profile/ProfileManagementControllerTest.kt]: sounds good.

File: domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt [hunk 9]
```diff
@@ -143,6 +143,9 @@ class ProfileManagementController @Inject constructor(
   /** Indicates that the there is not device settings currently. */
   class DeviceSettingsNotFoundException(msg: String) : Exception(msg)
 
+  /** Indicates  that profiles already exist in the app. */
```
[the remark this answers is not in the document]
Comment (adhiamboperes) [reply domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt]: Also PTAL.

**Comment by ShankhanilSaha** [comment]
@adhiamboperes Missed the typo during code review, thanks! I Have pushed the change requested.
