### PR TITLE
Fix #4121: Added tests for TokenSubject

### LINKED ISSUE #4121: Add tests for TokenSubject
#4051 introduces a new custom Truth test subject: TokenSubject. It would be advantageous to add thorough tests for this to ensure that:
- Each of the subject methods correctly allow users to test specific properties of the protos each subject helps verify
- Each of the subject methods are verified to fail when expected (i.e. when used with an incompatible proto property) with the correct failure reason being verified

See #4097 for a similar issue.

### PR DESCRIPTION
**Pull request by theayushyadav11**
Fixes #4121
This pull request introduces a new test class `TokenSubjectTest` to the `oppia_android_test` suite, focusing on validating various aspects of the `Token` class from the `MathTokenizer` utility. The primary changes include the addition of the test class itself and the corresponding Bazel build rule.

#### Addition of Test Class:
* [`testing/src/test/java/org/oppia/android/testing/math/TokenSubjectTest.kt`](diffhunk://#diff-aeecd58bdeac384c551e2a73a6debca08e2bdfb0492eb84007773ed78af057d0R1-R180): Added a new test class `TokenSubjectTest` with multiple test methods to verify the correctness of different `Token` types and their properties.

#### Bazel Build Rule:
* [`testing/src/test/java/org/oppia/android/testing/math/BUILD.bazel`](diffhunk://#diff-8a86bceb0e654069d42dcb4e76a52f65aeea3bc7d76a9cdff53f5e4bdde93f08R70-R85): Added a new `oppia_android_test` target for `TokenSubjectTest`, specifying its dependencies and configuration.

#### Screenshot of the passing tests.
image

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section))

### CODE REVIEW

**Comment by theayushyadav11** [comment]
Hi @adhiamboperes PTAL, and suggest me if there are any changes to make.

File: scripts/assets/test_file_exemptions.textproto [hunk 1]
```diff
@@ -4111,7 +4111,7 @@ test_file_exemption {
   test_file_not_required: true
 }
 test_file_exemption {
-  exempted_file_path: "testing/src/main/java/org/oppia/android/testing/math/TokenSubject.kt"
+  exempted_file_path: "testing/src/main/java/org/oppia/android/testing/math/RealSubject.kt"
```
Comment (adhiamboperes) [inline scripts/assets/test_file_exemptions.textproto]: Remove exemption.

File: testing/src/test/java/org/oppia/android/testing/math/TokenSubjectTest.kt [hunk 2]
```diff
@@ -0,0 +1,198 @@
...
+  }
+
+  @Test
+  fun testTokenSubject_isVariableWhoseName_correctName_passes() {
+    val token = Token.VariableName("x", 10, 15)
+    TokenSubject.assertThat(token).isVariableWhoseName().isEqualTo("x")
+  }
+
+  @Test
+  fun testTokenSubject_isVariableWhoseName_incorrectType_fails() {
```
Comment (adhiamboperes) [inline testing/src/test/java/org/oppia/android/testing/math/TokenSubjectTest.kt]:
```suggestion
  fun testTokenSubject_isVariableWhoseName_incorrectName_fails() {
```

File: testing/src/test/java/org/oppia/android/testing/math/TokenSubjectTest.kt [hunk 3]
```diff
@@ -0,0 +1,198 @@
...
+    val token = Token.PositiveInteger(42, 10, 15)
```
Comment (adhiamboperes) [inline testing/src/test/java/org/oppia/android/testing/math/TokenSubjectTest.kt]: Should this be `val token = Token.VariableName("x", 10, 15)`? I assumed that it is the failure case for the previous test.

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @theayushyadav11! I have just a few comments.

**Comment by theayushyadav11** [comment]
Hi @adhiamboperes  , this PR is ready for review PTAL.

File: testing/src/test/java/org/oppia/android/testing/math/TokenSubjectTest.kt (hunk 3 above)
Comment (adhiamboperes) [reply testing/src/test/java/org/oppia/android/testing/math/TokenSubjectTest.kt]: It’s not clear to me if this was addressed. Please confirm whether my assumption was right or wrong.

File: testing/src/test/java/org/oppia/android/testing/math/TokenSubjectTest.kt [hunk 4]
```diff
@@ -0,0 +1,217 @@
...
+
+  @Test
+  fun testTokenSubject_passesWithCorrectVariableName() {
+    val token = Token.VariableName("x", 10, 15)
+    TokenSubject.assertThat(token).isVariableWhoseName().isEqualTo("x")
+  }
+
+  @Test
+  fun testTokenSubject_isVariableWhoseName_incorrectName_fails() {
+    val token = Token.VariableName("x", 10, 15)
```
Comment (theayushyadav11) [inline testing/src/test/java/org/oppia/android/testing/math/TokenSubjectTest.kt:76]: Hi I have updated the code and the comment was addressed, PTAL.

**Comment by theayushyadav11** [comment]
Hi @adhiamboperes, PTAL.

**Review by adhiamboperes — APPROVED** [review]
LGTM, Thanks @theayushyadav11.
