### PR TITLE
Fix #3708: Content Description Generation For ImageRegionSelectionInteraction

### LINKED ISSUE #3708: Add content description for each image region in ImageRegionSelectionInteraction
**Description**
`ImageRegionSelectionInteraction` does not contain `contentDescription` and therefore fails on accessibility scanner

**Steps to reproduce**
1. Open `First Test Topic`
2. Open `Image Region Selection Exploration`
3. Using [accessibility scanner](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide#using-a11y-scanner-in-android) take screenshot of the screen which shows all planets.
4. Notice that the scanner fails with various errors

**Expected solution**
The scanner should should 0 errors.

For each image region we should add content description. Follow files can help you get started:
- app/src/main/java/org/oppia/android/app/player/state/ImageRegionSelectionInteractionView.kt
- app/src/main/res/layout/image_region_selection_interaction_item.xml

### PR DESCRIPTION
**Pull request by manas-yu**
## Explanation

Fix #3708

This PR adds logic for dynamic content descriptions in **ImageRegionSelectionInteraction**, i.e. generating distinct descriptions for selected and not selected regions. For example:  
- **Selected:** "Image showing Region 3." 
- **Not Selected:** "Select Region 3 image."

## Before
image
image

## After
image
image

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

### CODE REVIEW

**Comment by manas-yu** [comment]
Hi @adhiamboperes PTAL, Thanks!
"After" video for reference on talkback: https://drive.google.com/file/d/1iAb58nEw0aB4SnspkGl_cSyh8R3fBf1w/view?usp=sharing

File: app/src/main/java/org/oppia/android/app/utility/ClickableAreasImage.kt [hunk 1]
```diff
@@ -172,4 +191,22 @@ class ClickableAreasImage(
...
   }
+
+  private fun generateContentDescription(
+    clickableArea: LabeledRegion,
+    isSelected: Boolean
+  ): String {
+    if (isSelected) {
+      return "This is a ${clickableArea.label} image."
+    }
+    return "Select ${clickableArea.label} image."
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/utility/ClickableAreasImage.kt]: Did you mean for this to be an if/else condition?

Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/utility/ClickableAreasImage.kt]: These could be a string template, so that they are translatable. Seperately, how did you come up with the structure of the content description?

**Review by adhiamboperes — COMMENTED** [review]
Thanks @manas-yu! I have some questions about the implementation

File: app/src/main/java/org/oppia/android/app/utility/ClickableAreasImage.kt (hunk 1 above)
Comment (manas-yu) [reply app/src/main/java/org/oppia/android/app/utility/ClickableAreasImage.kt]: For the content description of the `ImageRegionSelection`, I aimed to create a dynamic content description where the currently selected region has a distinct and descriptive label than unselected ones. This improves accessibility by ensuring that users relying on TalkBack can clearly differentiate between selected and unselected regions.   

- In `addRegionViews`, the content description is set based on whether the region is initially selected.  

- In `resetRegionSelectionViews`, if a region matches the `imageLabel`, it retains the selected description; otherwise, it is updated with the unselected description.  

- `updateRegionContentDescription` assigns the content description generated by `generateContentDescription` to the region’s view.  

- The `if (clickableArea.label != imageLabel)` check in `showOrHideRegion` prevents redundant function calls.  

- Avoided unnecessary words like "Selected" or "Tap" in content descriptions to avoid redundant text warnings("content description might contain unnecessary text").  

Let me know if this approach is acceptable or if further refinements are needed.

Comment (manas-yu) [reply app/src/main/java/org/oppia/android/app/utility/ClickableAreasImage.kt]: The function `generateContentDescription` returns an appropriate TalkBack description for a given region. If the region is selected, TalkBack announces:
"This is a ${clickableArea.label} image."
Otherwise, it prompts the user with:
"Select ${clickableArea.label} image."

The function now uses string templates for translatable text instead of hardcoded strings.

**Comment by manas-yu** [comment]
@adhiamboperes PTAL, Thanks!

File: app/src/main/java/org/oppia/android/app/utility/ClickableAreasImage.kt (hunk 1 above)
Comment (adhiamboperes) [reply app/src/main/java/org/oppia/android/app/utility/ClickableAreasImage.kt]: Sounds good.

Comment (adhiamboperes) [reply app/src/main/java/org/oppia/android/app/utility/ClickableAreasImage.kt]: This sounds good, thanks.

File: app/src/sharedTest/java/org/oppia/android/app/testing/ImageRegionSelectionInteractionViewTest.kt [hunk 2]
```diff
@@ -177,7 +178,7 @@ class ImageRegionSelectionInteractionViewTest {
       assertThat(regionClickedEvent.value)
         .isEqualTo(
           NamedRegionClickedEvent(
-            regionLabel = "Region 3", contentDescription = "You have selected Region 3"
+            regionLabel = "Region 3", contentDescription = "This is a Region 3 image."
```
Comment (adhiamboperes) [inline app/src/sharedTest/java/org/oppia/android/app/testing/ImageRegionSelectionInteractionViewTest.kt]: Compared to the original string, I am not sure if the new string will read smoothy for non-planet images. E.g. numberlines in the Fractions Topic. In fractions, some regions selected could be 1 and 3 quaters, for example.

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @manas-yu. Implementation details look good, but I'd like you to review te format of the content description thinking about other scenarios it may be used.

**Comment by manas-yu** [comment]
@adhiamboperes PTAL, Thanks.

File: app/src/sharedTest/java/org/oppia/android/app/testing/ImageRegionSelectionInteractionViewTest.kt (hunk 2 above)
Comment (manas-yu) [reply app/src/sharedTest/java/org/oppia/android/app/testing/ImageRegionSelectionInteractionViewTest.kt]: Replaced the string with "Image showing %1$s."

**Review by adhiamboperes — APPROVED** [review]
LGTM, Thanks @manas-yu!
