### PR TITLE
Fix #5455: Resolve crash in AudioViewModel by initializing state variables

### LINKED ISSUE #2652: Splash Screen Stretched
**Describe the bug**
 Splash screen is displayed when a user opens the app, on small screen devices the splash screen is working as expected, but on large screen devices, the splash screen is getting stretched and doesn't work as expected.

**To Reproduce**
1. Go to the Oppia app
2. Click on the icon
3. If your device screen is more than 6 inch
4. See  splash screen getting stretched

**Expected behavior**
 The splash screen should be displayed in the same aspect ratio as needed.

**Screenshots**

[Note: Also reported in #3193 -- see additional videos in that issue.]

Expected Behaviour
Expected Behaviour
Actual Behaviour
SplashScreen

**Device**
- OnePlus 7 Pro
- Android 10.0

The logo should be fixed as per device width:
- Mobile ([Portrait](https://xd.adobe.com/view/dfe8ccd4-39eb-414d-a0b2-b5674357f966-8abb/screen/ddc5589e-10d1-48e4-b551-5487801233e1), [Landscape](https://xd.adobe.com/view/dfe8ccd4-39eb-414d-a0b2-b5674357f966-8abb/screen/375d3300-f70d-44ed-a48a-269a58ecc854))
- Tablet ([Portrait](https://xd.adobe.com/view/dfe8ccd4-39eb-414d-a0b2-b5674357f966-8abb/screen/d39fdc8a-2bee-4867-a1a6-ce4280671c2b), [Landscape](https://xd.adobe.com/view/dfe8ccd4-39eb-414d-a0b2-b5674357f966-8abb/screen/d69bb715-1aea-4815-8401-6e7fde167ed4))

### LINKED ISSUE #5455: [BUG]:  The app crashes occasionally when the device is rotated during exploration.
### Describe the bug

 The app crashes occasionally when the device is rotated during exploration.
 
The attached video shows the app crashing when the user rotates the device after selecting input. However, I later found that it crashes even without selecting input.

### Steps To Reproduce
Open any lesson and rotate device.

### Expected Behavior
The crash should not happen.

### Screenshots/Videos

https://github.com/oppia/oppia-android/assets/76042077/8fb94b8a-447d-4b63-ab5d-02c2db1b513c

Screenshot 2024-07-01 102916

### Device:
Android 10
Realme 3
<details>
  <summary>Full stacktrace</summary>

```

   --------- beginning of crash
2024-07-01 12:33:04.441 20689-20689/org.oppia.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.oppia.android, PID: 20689
    kotlin.UninitializedPropertyAccessException: lateinit property state has not been initialized
        at org.oppia.android.app.player.audio.AudioViewModel.loadAudio(AudioViewModel.kt:91)
        at org.oppia.android.app.player.audio.AudioViewModel.loadMainContentAudio(AudioViewModel.kt:76)
        at org.oppia.android.app.player.audio.AudioFragmentPresenter.subscribeToAudioLanguageLiveData$lambda-3(AudioFragmentPresenter.kt:162)
        at org.oppia.android.app.player.audio.AudioFragmentPresenter.lambda$fdov4KnYyyWXrE4vXcM8K07F1xI(Unknown Source:0)
        at org.oppia.android.app.player.audio.-$$Lambda$AudioFragmentPresenter$fdov4KnYyyWXrE4vXcM8K07F1xI.onChanged(Unknown Source:4)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:307)
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
        at androidx.lifecycle.Transformations$1.onChanged(Transformations.java:76)
        at androidx.lifecycle.MediatorLiveData$Source.onChanged(MediatorLiveData.java:152)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:307)
        at org.oppia.android.util.data.DataProviders$NotifiableAsyncLiveData.setValue(DataProviders.kt:405)
        at org.oppia.android.util.data.DataProviders$NotifiableAsyncLiveData.setValue(DataProviders.kt:354)
        at androidx.lifecycle.LiveData$1.run(LiveData.java:91)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:227)
        at android.app.ActivityThread.main(ActivityThread.java:7822)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
2024-07-01 12:33:04.447 1463-3711/? D/OppoDisplayPolicy: com.android.systemui, change system app cutoutMode: color always
2024-07-01 12:33:04.450 20689-21508/org.oppia.android D/FA: Event not sent since app measurement is disabled
2024-07-01 12:33:04.452 1816-16507/? D/Launcher.TouchInteractionService: onActiveNavBarRegionChanges: region = SkRegion((452,1432,612,1520)(618,1432,720,1520))
2024-07-01 12:33:04.454 1463-1485/? V/WindowManager: adjustNotShowWallpaperByOppo: false
2024-07-01 12:33:04.456 1463-1485/? I/WindowManager: Screen frozen for +414ms due to Window{73c7261 u0 org.oppia.android/org.oppia.android.app.player.exploration.ExplorationActivity}
2024-07-01 12:33:04.477 6823-6823/? E/SubscriptionManagerWrapper: java.lang.NoSuchMethodException: android.telephony.SubscriptionManager.getActiveDataSubscriptionId []
2024-07-01 12:33:04.482 1463-8237/? I/Process: ydh getFreeMemory tag = MemFree:
2024-07-01 12:33:04.482 1463-8237/? I/Process: ydh getFreeMemory tag = Buffers:
2024-07-01 12:33:04.482 1463-8237/? I/Process: ydh getFreeMemory tag = Cached:
2024-07-01 12:33:04.482 1463-8237/? I/Process: ydh getFreeMemory tag = IonTotalCache:
2024-07-01 12:33:04.482 1463-8237/? I/Process: ydh getFreeMemory val = 94000
2024-07-01 12:33:04.483 1463-8237/? I/Process: ydh getFreeMemory val = 47568
2024-07-01 12:33:04.483 1463-8237/? I/Process: ydh getFreeMemory val = 1262656
2024-07-01 12:33:04.483 1463-8237/? I/Process: ydh getFreeMemory val = 4716
2024-07-01 12:33:04.483 1463-8237/? E/Process: get_ion_cache_memory: Unable to open /d/ion/system_stats
2024-07-01 12:33:04.486 6823-6823/? I/Choreographer: Skipped 1 frames!  The application may be doing too much work on its main thread.
2024-07-01 12:33:04.507 641-781/? I/hwcomposer: [OVL] (0) Overlay input(0) was used with queue previously  
2024-07-01 12:33:04.507 641-781/? I/hwcomposer: [DBQ] (q2:0x726b66d300) Buffer queue is destroyed  
2024-07-01 12:33:04.507 641-781/? I/hwcomposer: [DBQ] (q2:0x726b66d300) Free Slot(0), handle=0x726b651000, 4377600 -> 0  
2024-07-01 12:33:04.514 1463-8237/? I/Process: ydh getFreeMemory tag = MemFree:
2024-07-01 12:33:04.514 1463-8237/? I/Process: ydh getFreeMemory tag = Buffers:
2024-07-01 12:33:04.514 1463-8237/? I/Process: ydh getFreeMemory tag = Cached:
2024-07-01 12:33:04.514 1463-8237/? I/Process: ydh getFreeMemory tag = IonTotalCache:
2024-07-01 12:33:04.514 1463-8237/? I/Process: ydh getFreeMemory val = 93376
2024-07-01 12:33:04.514 1463-8237/? I/Process: ydh getFreeMemory val = 47568
2024-07-01 12:33:04.514 1463-8237/? I/Process: ydh getFreeMemory val = 1262700
2024-07-01 12:33:04.514 1463-8237/? I/Process: ydh getFreeMemory val = 4536
2024-07-01 12:33:04.514 1463-8237/? E/Process: get_ion_cache_memory: Unable to open /d/ion/system_stats
2024-07-01 12:33:04.650 1463-8237/? W/ActivityTaskManager:   Force finishing activity org.oppia.android/.app.player.exploration.ExplorationActivity
2024-07-01 12:33:04.650 1463-8237/? V/ColorZoomWindowManagerService: prepareZoomTransition: curStack=ActivityStack{68858ed stackId=864 type=standard mode=fullscreen visible=true translucent=true, 1 tasks}   nextStackActivityStack{68858ed stackId=864 type=standard mode=fullscreen visible=true translucent=true, 1 tasks}
2024-07-01 12:33:04.650 1463-8236/? I/Process: ydh getFreeMemory tag = MemFree:
2024-07-01 12:33:04.650 1463-8236/? I/Process: ydh getFreeMemory tag = Buffers:
2024-07-01 12:33:04.650 1463-8236/? I/Process: ydh getFreeMemory tag = Cached:
2024-07-01 12:33:04.650 1463-8236/? I/Process: ydh getFreeMemory tag = IonTotalCache:
2024-07-01 12:33:04.650 1463-8236/? I/Process: ydh getFreeMemory val = 88988
2024-07-01 12:33:04.650 1463-8236/? I/Process: ydh getFreeMemory val = 47580
2024-07-01 12:33:04.650 1463-8236/? I/Process: ydh getFreeMemory val = 1263152
2024-07-01 12:33:04.650 1463-8236/? I/Process: ydh getFreeMemory val = 9440
2024-07-01 12:33:04.651 1463-8236/? E/Process: get_ion_cache_memory: Unable to open /d/ion/system_stats
2024-07-01 12:33:04.651 1463-8237/? D/PowerHalWrapper: <amsBoostResume> last:org.oppia.android, next:org.oppia.android 
2024-07-01 12:33:04.652 1463-8236/? I/Process: ydh getFreeMemory tag = MemFree:
2024-07-01 12:33:04.652 1463-8236/? I/Process: ydh getFreeMemory tag = Buffers:
2024-07-01 12:33:04.652 1463-8236/? I/Process: ydh getFreeMemory tag = Cached:
2024-07-01 12:33:04.652 1463-8236/? I/Process: ydh getFreeMemory tag = IonTotalCache:
2024-07-01 12:33:04.652 1463-8236/? I/Process: ydh getFreeMemory val = 88988
2024-07-01 12:33:04.652 1463-8236/? I/Process: ydh getFreeMemory val = 47580
2024-07-01 12:33:04.652 1463-8236/? I/Process: ydh getFreeMemory val = 1263152
2024-07-01 12:33:04.652 1463-8236/? I/Process: ydh getFreeMemory val = 9440
2024-07-01 12:33:04.652 1463-8236/? E/Process: get_ion_cache_memory: Unable to open /d/ion/system_stats
2024-07-01 12:33:04.654 1463-8236/? I/Process: ydh getFreeMemory tag = MemFree:
2024-07-01 12:33:04.654 1463-8236/? I/Process: ydh getFreeMemory tag = Buffers:
2024-07-01 12:33:04.654 1463-8236/? I/Process: ydh getFreeMemory tag = Cached:
2024-07-01 12:33:04.654 1463-8236/? I/Process: ydh getFreeMemory tag = IonTotalCache:
2024-07-01 12:33:04.654 1463-8236/? I/Process: ydh getFreeMemory val = 88988
2024-07-01 12:33:04.654 1463-8236/? I/Process: ydh getFreeMemory val = 47580
2024-07-01 12:33:04.654 1463-8236/? I/Process: ydh getFreeMemory val = 1263152
2024-07-01 12:33:04.654 1463-8236/? I/Process: ydh getFreeMemory val = 9440
2024-07-01 12:33:04.654 1463-8236/? E/Process: get_ion_cache_memory: Unable to open /d/ion/system_stats
2024-07-01 12:33:04.655 20689-20689/org.oppia.android I/Process: Sending signal. PID: 20689 SIG: 9
2024-07-01 12:33:04.659 1829-3741/? W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.startService:1609 android.content.ContextWrapper.startService:680 com.coloros.performance.service.FrameCollectService.startQualityProtect:288 com.coloros.performance.service.FrameCollectService.recordAppErrorEvent:339 com.coloros.performance.service.FrameCollectService.access$000:58 
2024-07-01 12:33:04.661 1463-8237/? D/OppoDetectOidt: detectExceptionsForOIDT type:0
2024-07-01 12:33:04.661 1829-1829/? I/QualityProtectService: MemoryMallocDebug is closed
2024-07-01 12:33:04.665 1829-21744/? I/QualityProtectService: EAP_LOG:eap_log_crash
2024-07-01 12:33:04.665 1829-21744/? I/QualityProtectService: keep service alive
2024-07-01 12:33:04.671 1829-2895/? W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.startService:1609 android.content.ContextWrapper.startService:680 com.oppo.statistics.record.RecordHandler.startDcsService:210 com.oppo.statistics.record.RecordHandler.addTask:137 com.oppo.statistics.agent.CommonAgent.recordCommon:23 
2024-07-01 12:33:04.676 3832-7905/? W/DCS: Record event failed. DCS reject event: [appId=20089,logTag=20089,eventId=performance_crash] . Pls check server config.
2024-07-01 12:33:04.699 1463-21743/? D/OppoThermalStats: SimpleTopProcesses: {system_server=20, lastSamepleWallTime=2024-07-01 12:27:50.995, usap64=2, surfaceflinger=3.6, com.android.phone=3.6}
2024-07-01 12:33:04.700 1463-21743/? D/OppoThermalStats: reset mHaveCaptured:false
2024-07-01 12:33:04.703 1463-21743/? I/DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
2024-07-01 12:33:04.708 1463-21743/? W/DropBoxManagerService: Dropping: data_app_crash (10 > 0 bytes)
2024-07-01 12:33:04.709 1463-21743/? I/ColorEapManager: UserId of entry: 0
2024-07-01 12:33:04.709 1463-1588/? W/InputDispatcher: channel 'f42ff98 org.oppia.android/org.oppia.android.app.home.HomeActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
2024-07-01 12:33:04.709 1463-1588/? E/InputDispatcher: channel 'f42ff98 org.oppia.android/org.oppia.android.app.home.HomeActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2024-07-01 12:33:04.709 1463-1588/? W/InputDispatcher: channel 'ccd332f org.oppia.android/org.oppia.android.app.topic.TopicActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
2024-07-01 12:33:04.709 1463-1588/? E/InputDispatcher: channel 'ccd332f org.oppia.android/org.oppia.android.app.topic.TopicActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2024-07-01 12:33:04.709 1463-1588/? W/InputDispatcher: channel '9493973 org.oppia.android/org.oppia.android.app.profile.ProfileChooserActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
2024-07-01 12:33:04.709 1463-1588/? E/InputDispatcher: channel '9493973 org.oppia.android/org.oppia.android.app.profile.ProfileChooserActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2024-07-01 12:33:04.709 1463-1588/? W/InputDispatcher: channel '73c7261 org.oppia.android/org.oppia.android.app.player.exploration.ExplorationActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
2024-07-01 12:33:04.709 1463-1588/? E/InputDispatcher: channel '73c7261 org.oppia.android/org.oppia.android.app.player.exploration.ExplorationActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2024-07-01 12:33:04.711 1463-21743/? D/ColorEapUtils: diffDay: 0
2024-07-01 12:33:04.711 1463-21743/? D/ColorEapUtils: over crash limit, stop collect file
2024-07-01 12:33:04.712 1463-21743/? D/DropBoxManagerService: file :: /data/system/dropbox/data_app_crash@1719817384708.lost
2024-07-01 12:33:04.713 1463-1722/? W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.startService:1609 oppo.util.OppoStatistics.startDcsService:400 oppo.util.OppoStatistics.access$100:41 oppo.util.OppoStatistics$1.run:152 java.util.concurrent.ThreadPoolExecutor.runWorker:1167 
2024-07-01 12:33:04.714 1463-21743/? W/AES: Exception Log handling...
2024-07-01 12:33:04.714 1463-21743/? W/AES: Skipped - do not care third party apk
2024-07-01 12:33:04.714 1463-1503/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
2024-07-01 12:33:04.716 16442-16442/? I/ADB_SERVICES: for fd 18, revents = 2011
2024-07-01 12:33:04.716 1463-3711/? I/WindowManager: WIN DEATH: Window{73c7261 u0 org.oppia.android/org.oppia.android.app.player.exploration.ExplorationActivity}
2024-07-01 12:33:04.716 16442-16442/? I/ADB_SERVICES: for fd 18, revents = 2011
2024-07-01 12:33:04.716 1463-3711/? W/InputDispatcher: Attempted to unregister already unregistered input channel '73c7261 org.oppia.android/org.oppia.android.app.player.exploration.ExplorationActivity (server)'
2024-07-01 12:33:04.716 1463-2139/? V/ActivityManager: Death received in com.android.server.am.ActivityManagerService$AppDeathRecipient@182eb17 for thread android.os.BinderProxy@3294b04, mPid:20689,mApp:ProcessRecord{7744322 20689:org.oppia.android/u0a462}
2024-07-01 12:33:04.717 677-1703/? I/BufferQueueProducer: [org.oppia.android/org.oppia.android.app.player.exploration.ExplorationActivity#0](this:0x7056f1c800,id:11734,api:1,p:20689,c:677) disconnect(P): api 1
2024-07-01 12:33:04.717 16442-16442/? I/ADB_SERVICES: for fd 16, revents = 2011
2024-07-01 12:33:04.718 623-623/? I/Zygote: Process 20689 exited due to signal 9 (Killed)
2024-07-01 12:33:04.718 1463-3711/? V/WindowManager: Changing focus from Window{73c7261 u0 org.oppia.android/org.oppia.android.app.player.exploration.ExplorationActivity EXITING} to null
2024-07-01 12:33:04.719 7864-7864/? I/InputTransport: Destroy ARC handle: 0xdbc97c90
2024-07-01 12:33:04.720 18155-18155/? I/InputTransport: Destroy ARC handle: 0x7947540920
2024-07-01 12:33:04.721 3832-7905/? W/DCS: Record event failed. DCS reject event: [appId=20120,logTag=20120,eventId=eap_log_create] . Pls check server config.
2024-07-01 12:33:04.723 1463-8236/? I/WindowManager: WIN DEATH: Window{ccd332f u0 org.oppia.android/org.oppia.android.app.topic.TopicActivity}
2024-07-01 12:33:04.723 1463-8236/? W/InputDispatcher: Attempted to unregister already unregistered input channel 'ccd332f org.oppia.android/org.oppia.android.app.topic.TopicActivity (server)'
2024-07-01 12:33:04.727 1463-2343/? I/WindowManager: WIN DEATH: Window{f42ff98 u0 org.oppia.android/org.oppia.android.app.home.HomeActivity}
2024-07-01 12:33:04.727 1463-2343/? W/InputDispatcher: Attempted to unregister already unregistered input channel 'f42ff98 org.oppia.android/org.oppia.android.app.home.HomeActivity (server)'
2024-07-01 12:33:04.729 1463-1477/? I/WindowManager: WIN DEATH: Window{9493973 u0 org.oppia.android/org.oppia.android.app.profile.ProfileChooserActivity}
2024-07-01 12:33:04.730 1463-1477/? W/InputDispatcher: Attempted to unregister already unregistered input channel '9493973 org.oppia.android/org.oppia.android.app.profile.ProfileChooserActivity (server)'
2024-07-01 12:33:04.734 677-677/? D/SurfaceFlinger: Client::detachLayer this 0x7056f2e0c0, layer sequence 48793 9493973 org.oppia.android/org.oppia.android.app.profile.ProfileChooserActivity#0
2024-07-01 12:33:04.734 677-677/? D/SurfaceFlinger: Client::detachLayer this 0x7056f2e0c0, layer sequence 48800 f42ff98 org.oppia.android/org.oppia.android.app.home.HomeActivity#0
2024-07-01 12:33:04.734 677-677/? D/SurfaceFlinger: Client::detachLayer this 0x7056f2e0c0, layer sequence 48807 ccd332f org.oppia.android/org.oppia.android.app.topic.TopicActivity#0
2024-07-01 12:33:04.737 1463-2139/? I/ActivityManager: Process org.oppia.android (pid 20689) has died: fore TOP 
2024-07-01 12:33:04.737 1463-2139/? W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1073 com.android.server.am.OppoExtraActivityManagerService.setKeyLockModeNormal:56 com.android.server.am.ActivityManagerService.appDiedLocked:4240 com.android.server.am.ActivityManagerService$AppDeathRecipient.binderDied:1679 android.os.BinderProxy.sendDeathNotice:633 
2024-07-01 12:33:04.737 1463-1500/? I/libprocessgroup: Successfully killed process cgroup uid 10462 pid 20689 in 0ms
2024-07-01 12:33:04.739 1037-1037/? D/BoundBrokerSvc: onUnbind: Intent { act=com.google.android.gms.measurement.START pkg=com.google.android.gms }
2024-07-01 12:33:04.742 1037-1037/? D/BoundBrokerSvc: onUnbind: Intent { act=com.google.firebase.auth.api.gms.service.START pkg=com.google.android.gms }
2024-07-01 12:33:04.744 3832-7949/? I/DCS-BackgroundAppData: sendAppBgEvent: has no pkgName=org.oppia.android
2024-07-01 12:33:04.746 1463-2139/? V/ColorZoomWindowManagerService: onAnimationFinished:  r=ActivityRecord{b77461f u0 org.oppia.android/.app.player.exploration.ExplorationActivity t756 f}
2024-07-01 12:33:04.747 6823-25169/? D/KeyguardService: requestKeyguard FocusedAppChanged
2024-07-01 12:33:04.747 1463-2139/? I/InputTransport: Destroy ARC handle: 0x78296a14c0
2024-07-01 12:33:04.747 1463-2139/? I/InputTransport: Destroy ARC handle: 0x78296a18a0
2024-07-01 12:33:04.748 1463-2139/? I/InputTransport: Destroy ARC handle: 0x78296a1b20
2024-07-01 12:33:04.748 1463-2139/? I/InputTransport: Destroy ARC handle: 0x78296a1f00
2024-07-01 12:33:04.750 1463-2139/? D/DEBUG_VISIBILITY: mOccluded:false lastOccluded:false
2024-07-01 12:33:04.751 677-677/? D/SurfaceFlinger: Client::detachLayer this 0x709fa8f780, layer sequence 48821 Letterbox - left#0
2024-07-01 12:33:04.752 677-677/? I/BufferQueue: [org.oppia.android/org.oppia.android.app.player.exploration.ExplorationActivity#0](this:0x7056f1c800,id:11734,api:1,p:-1,c:-1) ~BufferQueueCore
2024-07-01 12:33:04.758 1463-1485/? D/OppoPhoneWindowManager: handleStartingWindow spend time =: 0
2024-07-01 12:33:04.758 1463-1485/? E/system_server: Invalid ID 0x00000000.
2024-07-01 12:33:04.760 1463-1463/? I/OppoPhoneWindowManager: KeyLockModeReceiver KeyLockMode: 0 ProcessName: org.oppia.android
2024-07-01 12:33:04.760 1463-1484/? W/ActivityManager: setHasOverlayUi called on unknown pid: 20689
2024-07-01 12:33:04.761 1816-1816/? D/Launcher.RecentTasksList: onTaskStackChanged: 
2024-07-01 12:33:04.763 666-26667/? D/AudioPolicyService: UidPolicy::onUidStateChanged() UID=10161 procState=3
2024-07-01 12:33:04.764 1463-1485/? D/WindowManager: Add to mViews: DecorView@de6f03c[android], this = android.view.WindowManagerGlobal@7e2d009,pkg= org.oppia.android
2024-07-01 12:33:04.764 1463-1485/? D/ViewRootImpl[android]: hardware acceleration = false , fakeHwAccelerated = true, sRendererDisabled = false, forceHwAccelerated = false, sSystemRendererDisabled = false
2024-07-01 12:33:04.765 1463-1485/? D/OppoDisplayPolicy: org.oppia.android, no change cutoutMode: 0
2024-07-01 12:33:04.765 1463-2135/? V/AlarmManager: set(PendingIntent{d50d428: PendingIntentRecord{afeb541 com.google.android.gms startService}}) : type=3 when=315828757454whenElapsed315828757454maxWhen =552348757454 win=236520000000 interval=0 flags=0x8 pkg = com.google.android.gms
2024-07-01 12:33:04.767 1463-1485/? I/InputTransport: Create ARC handle: 0x78a14331a0
2024-07-01 12:33:04.768 677-677/? D/SurfaceFlinger: Client::detachLayer this 0x709fa8f780, layer sequence 48813 AppWindowToken{5947f35 token=Token{4207d6c ActivityRecord{b77461f u0 org.oppia.android/.app.player.exploration.ExplorationActivity t756}}}#0
2024-07-01 12:33:04.770 1463-1485/? D/OppoDisplayPolicy: org.oppia.android, no change cutoutMode: 0
2024-07-01 12:33:04.772 20698-20698/? I/g.oppia.androi: Late-enabling -Xcheck:jni
2024-07-01 12:33:04.773 677-2844/? I/BufferQueue: [unnamed-677-11735](this:0x7071dec000,id:11735,api:0,p:-1,c:-1) BufferQueue core=(677:/system/bin/surfaceflinger)
2024-07-01 12:33:04.774 677-2844/? I/BufferQueueConsumer: [unnamed-677-11735](this:0x7071dec000,id:11735,api:0,p:-1,c:677) connect(C): consumer=(677:/system/bin/surfaceflinger) controlledByApp=false
2024-07-01 12:33:04.774 677-2844/? I/BufferQueueConsumer: [unnamed-677-11735](this:0x7071dec000,id:11735,api:0,p:-1,c:677) setConsumerName: unnamed-677-11735
2024-07-01 12:33:04.774 677-2844/? I/BufferQueueConsumer: [Splash Screen org.oppia.android#0](this:0x7071dec000,id:11735,api:0,p:-1,c:677) setConsumerName: Splash Screen org.oppia.android#0
2024-07-01 12:33:04.775 1463-1499/? I/ActivityManager: Start proc 20698:org.oppia.android/u0a462 for activity {org.oppia.android/org.oppia.android.app.topic.TopicActivity}
2024-07-01 12:33:04.775 1463-31930/? D/OppoSapScanCoexistManager: SceneMode = 2PreSceneMode = 2
2024-07-01 12:33:04.775 677-2844/? D/DispPerfService: get proc=Splash Screen org.oppia.android#0 none
2024-07-01 12:33:04.775 677-2844/? I/BufferQueueConsumer: [Splash Screen org.oppia.android#0](this:0x7071dec000,id:11735,api:0,p:-1,c:677) setDefaultBufferSize: width=720 height=1520
2024-07-01 12:33:04.778 1463-1485/? D/Surface: lockCanvas
2024-07-01 12:33:04.779 1463-1485/? D/Surface: Surface::connect(this=0x782908e000,api=2)
2024-07-01 12:33:04.779 677-2844/? I/BufferQueueProducer: [Splash Screen org.oppia.android#0](this:0x7071dec000,id:11735,api:2,p:1463,c:677) connect(P): api=2 producer=(1463:system_server) producerControlledByApp=false
2024-07-01 12:33:04.788 677-2844/? D/DispPerfService: onframeavailable pid=1463, slot=0, seq=48894, ret=0, name=system_server:Splash Screen org.oppia.android#0
2024-07-01 12:33:04.789 666-26667/? D/AudioPolicyService: UidPolicy::onUidStateChanged() UID=10462 procState=20
2024-07-01 12:33:04.799 20698-20698/? E/g.oppia.androi: Unknown bits set in runtime_flags: 0x8000
2024-07-01 12:33:04.804 1444-21748/? E/DropBoxUtil: [AppErrors] null InputStream [CONTEXT service_id=254 ]
    java.io.IOException: null InputStream
        at csqu.b(:com.google.android.gms@242213022@24.22.13 (100400-638740827):184)
        at cspc.m(:com.google.android.gms@242213022@24.22.13 (100400-638740827):7)
        at csow.apply(:com.google.android.gms@242213022@24.22.13 (100400-638740827):37)
        at tfi.apply(:com.google.android.gms@242213022@24.22.13 (100400-638740827):5)
        at tfu.apply(:com.google.android.gms@242213022@24.22.13 (100400-638740827):45)
        at dnbf.a(:com.google.android.gms@242213022@24.22.13 (100400-638740827):3)
        at dvsx.a(:com.google.android.gms@242213022@24.22.13 (100400-638740827):13)
        at ecse.d(:com.google.android.gms@242213022@24.22.13 (100400-638740827):3)
        at ecsg.run(:com.google.android.gms@242213022@24.22.13 (100400-638740827):42)
        at ectr.execute(:com.google.android.gms@242213022@24.22.13 (100400-638740827):1)
        at ecsa.h(:com.google.android.gms@242213022@24.22.13 (100400-638740827):1)
        at ecsa.jf(:com.google.android.gms@242213022@24.22.13 (100400-638740827):40)
        at ecsg.g(:com.google.android.gms@242213022@24.22.13 (100400-638740827):13)
        at dnaw.a(:com.google.android.gms@242213022@24.22.13 (100400-638740827):20)
        at dvsw.a(:com.google.android.gms@242213022@24.22.13 (100400-638740827):13)
        at ecty.a(:com.google.android.gms@242213022@24.22.13 (100400-638740827):20)
        at ecwb.a(:com.google.android.gms@242213022@24.22.13 (100400-638740827):3)
        at ecvc.run(:com.google.android.gms@242213022@24.22.13 (100400-638740827):21)
        at ecwd.run(:com.google.android.gms@242213022@24.22.13 (100400-638740827):5)
        at ecua.run(:com.google.android.gms@242213022@24.22.13 (100400-638740827):53)
        at ectr.execute(:com.google.android.gms@242213022@24.22.13 (100400-638740827):1)
        at ecua.execute(:com.google.android.gms@242213022@24.22.13 (100400-638740827):76)
        at ecsa.h(:com.google.android.gms@242213022@24.22.13 (100400-638740827):1)
        at ecsa.jf(:com.google.android.gms@242213022@24.22.13 (100400-638740827):40)
        at ecuc.c(:com.google.android.gms@242213022@24.22.13 (100400-638740827):31)
        at dnba.i(:com.google.android.gms@242213022@24.22.13 (100400-638740827):18)
        at dnbe.a(:com.google.android.gms@242213022@24.22.13 (100400-638740827):10)
        at dvsx.a(:com.google.android.gms@242213022@24.22.13 (100400-638740827):13)
        at ecse.d(:com.google.android.gms@242213022@24.22.13 (100400-638740827):3)
        at ecsg.run(:com.google.android.gms@242213022@24.22.13 (100400-638740827):42)
        at ectr.execute(:com.google.android.gms@242213022@24.22.13 (100400-638740827):1)
        at ecsa.h(:com.google.android.gms@242213022@24.22.13 (100400-638740827):1)
        at ecsa.jf(:com.google.android.gms@242213022@24.22.13 (100400-638740827):40)
        at ecsg.g(:com.google.android.gms@242213022@24.22.13 (100400-638740827):13)
        at dnbh.a(:com.google.android.gms@242213022@24.22.13 (100400-638740827):20)
        at dvsw.a(:com.google.android.gms@242213022@24.22.13 (100400-638740827):13)
        at ecty.a(:com.google.android.gms@242213022@24.22.13 (100400-638740827):20)
        at ecwb.a(:com.google.android.gms@242213022@24.22.13 (100400-638740827):3)
        at ecvc.run(:com.google.android.gms@242213022@24.22.13 (100400-638740827):21)
        at ecwd.run(:com.google.android.gms@242213022@24.22.13 (100400-638740827):5)
        at ecua.run(:com.google.android.gms@242213022@24.22.13 (100400-638740827):53)
        at ectr.execute(:com.google.android.gms@242213022@24.22.13 (100400-638740827):1)
        at ecua.execute(:com.google.android.gms@242213022@24.22.13 (100400-638740827):76)
        at ecsa.h(:com.google.android.gms@242213022@24.22.13 (100400-638740827):1)
        at ecsa.jf(:com.google.android.gms@242213022@24.22.13 (100400-638740827):40)
        at ecuc.c(:com.google.android.gms@242213022@24.22.13 (100400-638740827):31)
        at dnbo.c(:com.google.android.gms@242213022@24.22.13 (100400-638740827):56)
        at dnbo.b(:com.google.android.gms@242213022@24.22.13 (100400-638740827):10)
        at com.google.android.gms.stats.service.DropBoxEntryAddedChimeraService.a(:com.google.android.gms@242213022@24.22.13 (100400-638740827):376)
2024-07-01 12:33:04.804 1444-21748/? E/DropBoxUtil:     at com.google.android.gms.framework.tracing.wrapper.TracingIntentService.onHandleIntent(:com.google.android.gms@242213022@24.22.13 (100400-638740827):13)
        at pac.handleMessage(:com.google.android.gms@242213022@24.22.13 (100400-638740827):7)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:227)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2024-07-01 12:33:04.811 1444-21748/? E/DropBoxUtil: [AppDoctor] null InputStream [CONTEXT service_id=254 ]
    java.io.IOException: null InputStream
        at csqu.b(:com.google.android.gms@242213022@24.22.13 (100400-638740827):184)
        at cspc.m(:com.google.android.gms@242213022@24.22.13 (100400-638740827):7)
        at csot.apply(:com.google.android.gms@242213022@24.22.13 (100400-638740827):35)
        at com.google.android.gms.stats.service.DropBoxEntryAddedChimeraService.a(:com.google.android.gms@242213022@24.22.13 (100400-638740827):476)
        at com.google.android.gms.framework.tracing.wrapper.TracingIntentService.onHandleIntent(:com.google.android.gms@242213022@24.22.13 (100400-638740827):13)
        at pac.handleMessage(:com.google.android.gms@242213022@24.22.13 (100400-638740827):7)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:227)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2024-07-01 12:33:04.814 1463-2135/? V/ActivityManager: New death recipient com.android.server.am.ActivityManagerService$AppDeathRecipient@762243b for thread android.os.BinderProxy@c759758, pid:20698,mApp:null
2024-07-01 12:33:04.816 1463-2135/? D/DEBUG_VISIBILITY: mOccluded:false lastOccluded:false
2024-07-01 12:33:04.812 1444-21748/? E/DropBoxUtil: [AppDoctor] null InputStream [CONTEXT service_id=254 ]
    java.io.IOException: null InputStream
        at csqu.b(:com.google.android.gms@242213022@24.22.13 (100400-638740827):184)
        at cspc.m(:com.google.android.gms@242213022@24.22.13 (100400-638740827):7)
        at csot.apply(:com.google.android.gms@242213022@24.22.13 (100400-638740827):35)
        at com.google.android.gms.stats.service.DropBoxEntryAddedChimeraService.a(:com.google.android.gms@242213022@24.22.13 (100400-638740827):476)
        at com.google.android.gms.framework.tracing.wrapper.TracingIntentService.onHandleIntent(:com.google.android.gms@242213022@24.22.13 (100400-638740827):13)
        at pac.handleMessage(:com.google.android.gms@242213022@24.22.13 (100400-638740827):7)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:227)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2024-07-01 12:33:04.823 6823-25169/? D/KeyguardService: requestKeyguard FocusedAppChanged
2024-07-01 12:33:04.823 641-781/? W/hwcomposer: [OVL] (0) No overlay input queue(3)  
2024-07-01 12:33:04.823 641-781/? I/hwcomposer: [DBQ] (q2:0x726b66d300) Buffer queue is created with size(3)  
2024-07-01 12:33:04.823 641-781/? I/hwcomposer: [DBQ] (q2:0x726b66d300) setConsumerListener  
2024-07-01 12:33:04.823 641-781/? I/hwcomposer: [DBQ] (q2:0x726b66d300) Reallocate Slot(0), pool(0 -> 0) size(0 -> 4377600) 

```

</details>

### PR DESCRIPTION
**Pull request by TanishMoral11**
**Explanation:**
Fixes #5455:
- This PR addresses issue #5455, which involves a crash caused by `kotlin.UninitializedPropertyAccessException` in `AudioViewModel` when the device is rotated during exploration.
- The fix ensures proper initialization of state variables in the `loadAudio()` function, which prevents the app from crashing due to uninitialized properties.

**Essential Checklist:**
- [x] The PR title and explanation each start with "Fix #5455: ".
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

**Before Changes Video :** 
https://github.com/user-attachments/assets/649c9869-3ce6-4e0c-bafa-9769ff6d655f

**After Changes Video :** 
https://github.com/user-attachments/assets/6ded81c1-4846-4328-bd2e-b5c25420808b

**Screenshot of Passing Tests on Espresso:**
Screenshot 2024-12-10 185043

### CODE REVIEW

File: app/src/main/java/org/oppia/android/app/player/audio/AudioViewModel.kt [hunk 1]
```diff
@@ -88,6 +90,8 @@ class AudioViewModel @Inject constructor(
    * @param allowAutoPlay If false, audio is guaranteed not to be autoPlayed.
    */
   private fun loadAudio(contentId: String?, allowAutoPlay: Boolean, reloadingMainContent: Boolean) {
+    // Check if 'state' is initialized before proceeding.
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/player/audio/AudioViewModel.kt]: This comment is not needed as the code is self explanatory

File: app/src/main/java/org/oppia/android/app/player/audio/AudioViewModel.kt [hunk 2]
```diff
@@ -66,9 +66,11 @@ class AudioViewModel @Inject constructor(
...
   }
 
-  fun setStateAndExplorationId(newState: State, id: String) {
-    state = newState
-    explorationId = id
+  fun setStateAndExplorationId(newState: State?, id: String?) {
+    if (newState != null && id != null) {
+      state = newState
+      explorationId = id
+    }
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/player/audio/AudioViewModel.kt]: I have traced the usage of this function to: https://github.com/oppia/oppia-android/blob/f7e46519f54ef37871cefce27de1812bf4510493/app/src/main/java/org/oppia/android/app/player/state/StatePlayerRecyclerViewAssembler.kt#L276-L283. Here, I can see that we perform a nullcheck for `id`, but not for `state`. As state is the variable throwing the uninitialized property exception, it might be worth finding a more indpeth reason why it is not being initialized on time. Or perharbs both values are not being initialized on time.

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @TanishMoral11!

I feel like this solution is not robust because it provides no explanation why the variable is not being initialized. It also does not provide an actual fallback. What should happen if the state and id are null?

File: app/src/main/java/org/oppia/android/app/player/audio/AudioViewModel.kt (hunk 1 above)
Comment (TanishMoral11) [reply app/src/main/java/org/oppia/android/app/player/audio/AudioViewModel.kt]: Thanks @adhiamboperes , I'll remove that comment to maintain a clean codebase.

File: app/src/main/java/org/oppia/android/app/player/audio/AudioViewModel.kt (hunk 2 above)
Comment (TanishMoral11) [reply app/src/main/java/org/oppia/android/app/player/audio/AudioViewModel.kt]: Hey @adhiamboperes, 
Thanks for the insight! I will also ensure to add null checks for both state and id to prevent the issue. 
I'll keep you updated on my progress!

**Comment by TanishMoral11** [comment]
@adhiamboperes PTAL

**Comment by TanishMoral11** [comment]
Hi @adhiamboperes , could you take a look at this PR ?
Let me know if there's anything more I should adjust. 
Thanks!

File: app/src/main/java/org/oppia/android/app/player/audio/AudioViewModel.kt [hunk 3]
```diff
@@ -66,11 +67,16 @@ class AudioViewModel @Inject constructor(
     processPlayStatusLiveData()
   }
 
-  fun setStateAndExplorationId(newState: State, id: String) {
+  fun setStateAndExplorationId(newState: State?, id: String?) {
+    if (newState == null || id == null) {
+      Log.e("AudioViewModel", "Failed to set state or id - parameters are null")
+      return
+    }
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/player/audio/AudioViewModel.kt]: This is not needed. These values are passed in from the presenter, and we make an assumption that they are not null by the time they are passed in here.

Side note, we use our own logger, `oppiaLogger` for printing messages. It has w, i, and e just like `Log`.

File: app/src/main/java/org/oppia/android/app/player/audio/AudioViewModel.kt [hunk 4]
```diff
@@ -66,11 +67,16 @@ class AudioViewModel @Inject constructor(
...
     state = newState
     explorationId = id
   }
 
+
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/player/audio/AudioViewModel.kt]: Remove double newline.

File: app/src/main/java/org/oppia/android/app/player/audio/AudioViewModel.kt [hunk 5]
```diff
@@ -88,6 +94,11 @@ class AudioViewModel @Inject constructor(
    * @param allowAutoPlay If false, audio is guaranteed not to be autoPlayed.
    */
   private fun loadAudio(contentId: String?, allowAutoPlay: Boolean, reloadingMainContent: Boolean) {
+    if (!::state.isInitialized || !::explorationId.isInitialized) {
+      Log.w("AudioViewModel", "Cannot load audio: state or explorationId is not initialized.")
+      return
+    }
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/player/audio/AudioViewModel.kt]: Refactor this to:
```suggestion
     val targetContentId = when {
      !contentId.isNullOrEmpty() -> contentId
      ::state.isInitialized -> state.content.contentId
      else -> ""
    }
```

which is more robust, adds a check for `state.isInitialized` and provides a final fallback (`""`) if neither `contentId` nor `state.content.contentId` is available. This version helps avoid potential crashes if `state` or `contentId` is unavailable.

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @TanishMoral11! PTAL at my suggestions. 

Do not resolve reviewer comments, so that the reviewer can verify that they have been addressed.

**Comment by TanishMoral11** [comment]
Hey @adhiamboperes,

I've successfully addressed all the required changes as per the feedback. Could you kindly take a look at the updates when you get a chance?
Thanks!!

File: app/src/main/java/org/oppia/android/app/player/audio/AudioViewModel.kt [hunk 6]
```diff
@@ -1,5 +1,6 @@
 package org.oppia.android.app.player.audio
 
+import android.util.Log
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/player/audio/AudioViewModel.kt]: I think this can be removed. Please confirm. Ktlint should have caught this.

**Comment by TanishMoral11** [comment]
Hey @adhiamboperes PTAL 
Thanks !!

**Comment by TanishMoral11** [comment]
Hey @adhiamboperes PTAL, 

Could you kindly review this PR . I’ve addressed all the issues, and there are no further changes required from my side. However, if you need any modifications, please let me know, and I’d be happy to make them.

Additionally, I have two other open PRs (#5563 and #5573) where I need to address some changes or modifications. Due to my upcoming college exams, I will be less active until December 6. I will be available to work on them after that.

Please let me know how I should proceed.
Because The Oppia bot automatically closes PRs if there is no activity, so I would like to understand how I can prevent my PR from being closed in such cases.

Thanks !!

**Comment by adhiamboperes** [comment]
@TanishMoral11, regularly updating your PR from develop should keep it open. You only need to do this at least once a week(using the update button at the bottom of the PR)

**Comment by TanishMoral11** [comment]
Hey @adhiamboperes PTAL

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @TanishMoral11. Code changes like this always need to be tested to verify that they work.

The function under investigation is:
```kt
/**
   * Load audio based on the contentId.
   *
   * @param contentId If contentId is null, then state.content.contentId is used as default.
   * @param allowAutoPlay If false, audio is guaranteed not to be autoPlayed.
   */
  private fun loadAudio(contentId: String?, allowAutoPlay: Boolean, reloadingMainContent: Boolean) {
   val targetContentId = contentId ?: state.content.contentId
    val voiceoverMapping =
      state.recordedVoiceoversMap[targetContentId] ?: VoiceoverMapping.getDefaultInstance()

 ....
  }
```
Given that the error stack is:
```kt
2024-07-01 12:33:04.441 20689-20689/org.oppia.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.oppia.android, PID: 20689
    kotlin.UninitializedPropertyAccessException: lateinit property state has not been initialized
```

We know that state is not being initialized before use. So we made this change, per current PR:

```kt
    val targetContentId = when {
      !contentId.isNullOrEmpty() -> contentId
      ::state.isInitialized -> state.content.contentId
      else -> ""
    }
```

In order to test if this solution correctly fixes the issue, I wrote a test aimed at verifying that audio will still be playable on orientation change. The test is as follows:
```kt
@Test
  fun testAudioFragment_playAudio_configurationChange_checkAudioPaused() {
    addMediaInfo()
    launch<AudioFragmentTestActivity>(
      createAudioFragmentTestIntent(
        internalProfileId
      )
    ).use {
      testCoroutineDispatchers.runCurrent()

      waitForTheView(allOf(withId(R.id.play_pause_audio_icon), WithNonZeroDimensionsMatcher()))
        .perform(click())
      testCoroutineDispatchers.runCurrent()
      
      onView(withId(R.id.audio_progress_seek_bar)).perform(setProgress(100))
     
      onView(isRoot()).perform(orientationLandscape())
      testCoroutineDispatchers.runCurrent()
      onView(withId(R.id.play_pause_audio_icon))
        .check(matches(withContentDescription(context.getString(R.string.audio_play_description))))
    }
  }
  ```

However, this test still fails with the exception: 
```
kotlin.UninitializedPropertyAccessException: lateinit property state has not been initialized
at org.oppia.android.app.player.audio.AudioViewModel.loadAudio(AudioViewModel.kt:99)
at org.oppia.android.app.player.audio.AudioViewModel.loadMainContentAudio(AudioViewModel.kt:76)
at org.oppia.android.app.player.audio.AudioFragmentPresenter.subscribeToAudioLanguageLiveData$lambda-3(AudioFragmentPresenter.kt:158)
```

When I checked my code at `AudioViewModel.kt:99`, I discovered that it is  ` val voiceoverMapping =
      state.recordedVoiceoversMap[targetContentId] ?: VoiceoverMapping.getDefaultInstance()`. The state object here has not been initialized.

Your task is to find out why state has not been initialized, and run the test above against the fix until it passes. The test may need some modification, please use your discretion.

I created a [gist](https://gist.github.com/adhiamboperes/058764b5afdc2a4d50a24fc9790cce36) that shows you where `waitForTheView` and `WithNonZeroDimensionsMatcher()` come from.

**Comment by TanishMoral11** [comment]
Hey @adhiamboperes PTAL, 

So, The Issue Was Caused By State Not Being Initialized On Time Due To Missing Or Delayed Checks In The Lifecycle Flow. I Have Investigated And Addressed The Initialization Process, Ensuring Null Checks Are Implemented For Both State And Id.

Additionally, I Refined The Test To Validate The Fix And Confirm The Code Now Behaves As Expected.

**Comment by TanishMoral11** [comment]
Hey @adhiamboperes PTAL !!

File: .idea/codeStyles/Project.xml
Comment (adhiamboperes) [inline .idea/codeStyles/Project.xml:1]: This file should not be part of PR changes.

File: app/src/sharedTest/java/org/oppia/android/app/player/audio/AudioFragmentTest.kt [hunk 7]
```diff
@@ -208,14 +211,95 @@ class AudioFragmentTest {
...
+            context.getString(
+              R.string.audio_play_description
             )
           )
         )
+      )
+    }
+  }
+
+  /** Returns a matcher that matches view based on non-zero width and height. */
```
Comment (adhiamboperes) [inline app/src/sharedTest/java/org/oppia/android/app/player/audio/AudioFragmentTest.kt]: These helper classes should be moved after the last test in this file, to maintain readability of the class.

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @TanishMoral11. While your latest test cases seem to be passing on Robolectric, it fails when I test it on Espresso on my emulator. Can you post a screenshot showing that the tests pass on espresso? Could you also show a video demo that this bug does not recurr with the kates code changes?

**Comment by TanishMoral11** [comment]
Hey @adhiamboperes PTAL !!

Thank you for your feedback.

Before Changes Video : 
https://github.com/user-attachments/assets/649c9869-3ce6-4e0c-bafa-9769ff6d655f

After Changes Video : 
https://github.com/user-attachments/assets/6ded81c1-4846-4328-bd2e-b5c25420808b

Screenshot of Passing Tests :
Screenshot 2024-12-10 185043

File: .idea/codeStyles/Project.xml
Comment (TanishMoral11) [reply .idea/codeStyles/Project.xml:1]: Done.

File: app/src/sharedTest/java/org/oppia/android/app/player/audio/AudioFragmentTest.kt (hunk 7 above)
Comment (TanishMoral11) [reply app/src/sharedTest/java/org/oppia/android/app/player/audio/AudioFragmentTest.kt]: Done.

File: .idea/codeStyles/Project.xml
Comment (adhiamboperes) [inline .idea/codeStyles/Project.xml:1]: This is a project file, but should not be modified(not sure why this happens on windows). You can fix this by pulling `git pull upstream develop`. If there are conflicts, choose upstream so that the file is restored to it's original state. This PR should only have 2 changed files, the  viewmodel and the test file.

**Review by adhiamboperes — APPROVED** [review]
Thanks @TanishMoral11, this LGTM.

Just one last comment. PTAL.

File: .idea/codeStyles/Project.xml
Comment (TanishMoral11) [reply .idea/codeStyles/Project.xml:1]: Done.

**Comment by TanishMoral11** [comment]
Hey @adhiamboperes , Could You PTAL
