### PR TITLE
Fixes #239: fixed audio related test cases that interact with StateFragment

### LINKED ISSUE #239: Fix audio test cases in StateFragmentTest, AudioFragmentTest and CellularDataFragmentTest
@jamesxu0 @BenHenning 

@veena14cs has updated the implementation of AudioFragment. Earlier, we were controlling the visibility of audio fragment inside StateFragment but practically the AudioFragment was always created.

So we have updated this implementation to creating or removing the AudioFragment only when needed.

Because of these changes test cases related to AudioFragment are failing.
@jamesxu0 can you have a look at them and update accordingly?

### PR DESCRIPTION
**Pull request by jamesxu0**
## Explanation

Fixes #239: Fixed audio related tests cases that interact with StateFragment which was recently changed in PR #238.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is **assigned** to an appropriate reviewer.

### CODE REVIEW

**Review by rt4914 — CHANGES_REQUESTED** [review]
@jamesxu0 

Though all the libraries are added properly, I am getting error in AudioFragmentTest:

Mainly in line 18: `import kotlinx.coroutines.test.TestCoroutineDispatcher`

It maybe some Android Studio issue but not sure yet, can you check this on your machine?

Screenshot 2019-10-17 at 10 41 46 PM

**Comment by jamesxu0** [comment]
@rt4914 I spoke with @BenHenning earlier today about this. This test should be built with Robolectric and use the dependencies in testImplementation. For some reason, gradle tries to build this test when running other espresso tests. Ben said this won't be a problem when we switch to Bazel. I guess for now commenting out the test will work.

File: app/src/main/java/org/oppia/app/player/state/StateFragment.kt [hunk 1]
```diff
@@ -7,11 +7,27 @@ import android.view.View
...
+import org.oppia.app.player.exploration.EXPLORATION_ACTIVITY_TOPIC_ID_ARGUMENT_KEY
 import javax.inject.Inject
 
 /** Fragment that represents the current state of an exploration. */
 class StateFragment : InjectableFragment(), CellularDataInterface {
 
+  companion object {
+    /**
+     * Creates a new instance of a StateFragment
+     * @param topicId
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/app/player/state/StateFragment.kt]: Please finish this documentation.

File: app/src/main/java/org/oppia/app/player/state/StateFragment.kt [hunk 2]
```diff
@@ -7,11 +7,27 @@ import android.view.View
...
+     * @return [StateFragment]: Fragment
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/app/player/state/StateFragment.kt]: Nit: ``:`` not needed. Also, please finish this documentation (e.g. ``@return a new instance of [StateFragment]``)

Comment (BenHenning) [reply app/src/main/java/org/oppia/app/player/state/StateFragment.kt]: See: https://kotlinlang.org/docs/reference/kotlin-doc.html.

File: app/src/main/java/org/oppia/app/player/state/StateFragment.kt [hunk 3]
```diff
@@ -7,11 +7,27 @@ import android.view.View
...
+     */
+    fun newInstance(topicId: String): StateFragment {
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/app/player/state/StateFragment.kt]: Why would we need the topic ID for creating new state fragments? Shouldn't the exploration ID be sufficient?

File: app/src/main/java/org/oppia/app/player/state/StateFragment.kt [hunk 4]
```diff
@@ -7,11 +7,27 @@ import android.view.View
 import android.view.ViewGroup
 import org.oppia.app.fragment.InjectableFragment
 import org.oppia.app.player.audio.CellularDataInterface
+import org.oppia.app.player.exploration.EXPLORATION_ACTIVITY_TOPIC_ID_ARGUMENT_KEY
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/app/player/state/StateFragment.kt]: It feels a bit weird reusing this. Fragments and activities ought to define their own keys that are used specifically for their purposes to avoid reusing bundle keys, and to keep things specific to that fragment/activity.

File: app/src/main/java/org/oppia/app/player/state/StateFragment.kt (hunk 3 above)
Comment (BenHenning) [inline app/src/main/java/org/oppia/app/player/state/StateFragment.kt]: Is this topicId actually used anywhere? If not, prefer to remove.

File: app/src/sharedTest/java/org/oppia/app/player/audio/AudioFragmentTest.kt [hunk 5]
```diff
@@ -50,7 +50,7 @@ import org.robolectric.shadows.util.DataSource
 import javax.inject.Inject
 import javax.inject.Qualifier
 
-/** Tests for [AudioFragment]. */
+/** Tests for [AudioFragment]. Have to run test with Robolectric */
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/app/player/audio/AudioFragmentTest.kt]: Suggest wording this as a TODO on #59, e.g.:

``// TODO(#59): Make this test work with Espresso. NOTE TO DEVELOPERS: This test will not build for Espresso, and may prevent other tests from being built or running.``

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @jamesxu0. I'm slightly confused about the new argument being introduced in ``StateFragment``, but otherwise the PR LGTM!

File: app/src/main/java/org/oppia/app/player/state/StateFragment.kt (hunk 3 above)
Comment (jamesxu0) [reply app/src/main/java/org/oppia/app/player/state/StateFragment.kt]: changed to explorationId

File: app/src/main/java/org/oppia/app/player/state/StateFragment.kt (hunk 4 above)
Comment (jamesxu0) [reply app/src/main/java/org/oppia/app/player/state/StateFragment.kt]: changed so that StateFragment has its own key

File: app/src/main/java/org/oppia/app/player/state/StateFragment.kt (hunk 3 above)
Comment (jamesxu0) [reply app/src/main/java/org/oppia/app/player/state/StateFragment.kt]: the explorationId is retrieved in StateFragmentPresenter https://github.com/oppia/oppia-android/blob/324d493a49b4bd137ba3a028737545dd65d2ebb2/app/src/main/java/org/oppia/app/player/state/StateFragmentPresenter.kt#L58

Comment (BenHenning) [reply app/src/main/java/org/oppia/app/player/state/StateFragment.kt]: Please also rename the variable here to be ``explorationId`` to match the KDoc & the key name.

File: app/src/main/java/org/oppia/app/player/state/StateFragmentPresenter.kt [hunk 6]
```diff
@@ -107,8 +108,9 @@ class StateFragmentPresenter @Inject constructor(
   private fun showHideAudioFragment(isVisible: Boolean) {
     if (isVisible) {
       if (getAudioFragment() == null) {
+        val audioFragment = AudioFragment.newInstance(TEST_EXPLORATION_ID_5, "END")
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/app/player/state/StateFragmentPresenter.kt]: Shouldn't we pass the explorationId in here rather than referencing the text exploration ID?

**Review by BenHenning — APPROVED** [review]
Thanks @jamesxu0!

**Review by veena14cs — APPROVED** [review]

**Review by rt4914 — APPROVED** [review]
