### PR TITLE
Fix #1656: Profile progress click fix

### LINKED ISSUE #1656: Marquee effect in toolbar title
We need this implementation in toolbars:
https://drive.google.com/file/d/1vkDZxO0EamgTxkiXOrXV3qc3ti-42lws/view?usp=sharing

This implementation is needed in `TopicActivity`, `ExplorationActivity`, `StoryActivity` and `RevisionCard`

### LINKED ISSUE #1659: Stories in ProfileProgressActivity aren't clickable
**Describe the bug**
`RecentlyPlayedStorySummaryViewModel` doesn't have `onClick` function so that the stories aren't clickable.

**To Reproduce**
1. Go to Home
2. Click on Hamburger icon (navigation drawer)
3. Click on profile picture
4. Scroll to "Recently-Played Stories" 
5. Click on a story
6. Notice that nothing happens

**Expected behavior**
The story should open and the user should be able to play the story normally.

**Screenshots**
This is the screen where the problem exists
Screenshot_2020-08-15-13-14-29

### PR DESCRIPTION
**Pull request by rt4914**
## Explanation

Fix #1659 
As per this comment https://github.com/oppia/oppia-android/issues/1659#issuecomment-675080309

The profile-progress item should be clickable and should route to `Topic-Lessons` page.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Review by anandwana001 — APPROVED** [review]
LGTM, Thanks @rt4914

File: app/src/main/java/org/oppia/app/profileprogress/RecentlyPlayedStorySummaryViewModel.kt [hunk 1]
```diff
@@ -1,9 +1,29 @@
...
+  val activity: AppCompatActivity,
+  val internalProfileId: Int,
   val promotedStory: PromotedStory,
-  val entityType: String
-) : ProfileProgressItemViewModel()
+  val entityType: String,
+  private val IntentFactoryShim: IntentFactoryShim
+) : ProfileProgressItemViewModel(), RouteToTopicPlayStoryListener {
+  fun onStoryItemClicked() {
+    routeToTopicPlayStory(internalProfileId, promotedStory.topicId, promotedStory.storyId)
```
Comment (MohamedMedhat1998) [inline app/src/main/java/org/oppia/app/profileprogress/RecentlyPlayedStorySummaryViewModel.kt:17]: Can't we just remove the interface `RouteToTopicPlayStoryListener` and its overridden function and copy its implementation here?  
```
  fun onStoryItemClicked() {
    val intent = IntentFactoryShim.createTopicPlayStoryActivityIntent(
      activity.applicationContext,
      internalProfileId,
      topicId,
      storyId
    )
    activity.startActivity(intent)
  }
```

**Review by MohamedMedhat1998 — APPROVED** [review]
LGTM  
Just 1 question in the comments.

File: app/src/main/java/org/oppia/app/profileprogress/RecentlyPlayedStorySummaryViewModel.kt (hunk 1 above)
Comment (rt4914) [reply app/src/main/java/org/oppia/app/profileprogress/RecentlyPlayedStorySummaryViewModel.kt:17]: No actually this is an interm solution later on all these routes will be used once `IntentFactoryShim` is removed. So its better to keep it here so that we can easily track and update code wherever needed.
