### PR TITLE
Fix #4002: Profiles cant have internationalised names

### LINKED ISSUE #4002: Profiles can't have internationalized names
**Describe the bug**
Profiles can't have internationalized names.

**To Reproduce**
1. Open the create profile flow
2. In the name box for the profile, type non-English characters
3. Attempt to create the profile
4. Observe that an error appears indicating that the profile can't be created

**Expected behavior**
Now that Oppia supports non-English languages, profile names should be able to also be internationalized.

**Demonstration**
image

**Environment**
- Device/emulator being used: Nexus 5X
- Android or SDK version (e.g. Android 5 or SDK 21): Android 8.1.0
- App version (you can get this through system app settings or via the admin controls menu in-app): Develop build on 04b8e0381e3d49a4a4a0f17e111386385bf4ffbb.

**Additional context**
None

### PR DESCRIPTION
**Pull request by JishnuGoyal**
## Explanation

Fixes #4002

This PR introduces a new injectable class into the codebase called `ProfileNameValidator`.

This class uses Kotlin functions to verify input, instead of Regex patterns which were used earlier. 

In addition to what functionalities the regex patterns supported, this solution will now accept all International characters(English + non-English letters), and these characters: `.` , `'`, `-`

It will also reject the following:

Numbers (0, 1, 2, ... 9)
Symbols (!@#$%^&*... etc.)
Parentheses and Brackets ( (, [, { )

These built-in Kotlin methods function do not interfere with the RTL markers.

#### Hindi and Arabic profiles successfully created:
image

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

### CODE REVIEW

**Comment by JishnuGoyal** [comment]
Note that this regex pattern _will_ allow mixing of English and non English characters as some languages use of combination of those, for ex, Spanish, German, etc.

Kindly let me know if any further changes are required in the logic part @srushtirk

**Comment by JishnuGoyal** [comment]
PTAL @BenHenning @bkaur-bkj Thanks!

File: domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt [hunk 1]
```diff
@@ -722,7 +722,7 @@ class ProfileManagementController @Inject constructor(
   }
 
   private fun onlyLetters(name: String): Boolean {
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt]: This name no longer matches--please update.

File: domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt [hunk 2]
```diff
@@ -722,7 +722,7 @@ class ProfileManagementController @Inject constructor(
...
-    return name.matches(Regex("^[ A-Za-z]+\$"))
+    return name.matches(Regex("^(?!.*^[-.'])^(?!.*[.'-]\$).*^(?!.*[0-9!@#\$%^&*()_+={}\\[\\]|\\\\;\",?/<>`~]).*[\\w\\u00BF-\\u1FFF\\u2C00-\\uD7FF.'-]"))
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt]: This pattern has grown to an unmanageable size, I think. :) Can you instead split this into multiple, more specific patterns and check them one-at-a-time? I suggest moving them to fields to provide semantic meaning (such as having one for verifying that disallowed symbols are absent)l.

File: domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt [hunk 3]
```diff
@@ -722,7 +722,7 @@ class ProfileManagementController @Inject constructor(
...
   }
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt]: Please add tests for various names that should be prohibited/allowed to ensure the pattern is working as expected.

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @JishnuGoyal! Left some initial comments--PTAL.

File: domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt (hunk 3 above)
Comment (JishnuGoyal) [reply domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt:726]: Hello, @srushtirk , could you give some test cases/ examples of what names are acceptable and which ones are not acceptable?
What I want to make sure is that:
Although you have allowed `.`, `-` and `'` in the name, can the name start/end with one of these symbols?(For ex, is `-jishnu..` allowed?)

This is one of the constraints I found, but I want to know if there are any more of such constraints that are needed to be taken care of. 
PTAL @srushtirk Thanks!

**Comment by JishnuGoyal** [comment]
Hello, @srushtirk  , could you give some test cases/ examples of what names are acceptable and which ones are not acceptable?
What I want to make sure is that:
Although you have allowed `.`, `-` and `'` in the name, can the name start/end with one of these symbols?
(For ex, is `-jishnu..` allowed?)

This is one of the constraints I found, but I want to know if there are any more of such constraints that are needed to be taken care of.
PTAL @srushtirk Thanks!

**Comment by srushtirk** [comment]
Hi @JishnuGoyal let's allow any order for the symbols . , ', -, English and non English characters. As it is difficult to predict where exactly in the user's name would these symbols be. This causes some edge cases where users can create profiles with random names starting or ending with these symbols, which is fine to trade off with. 

We can put the following restrictions though:
1) No two symbols next to each other. Eg: --, '-, .', ..
2) Avoid spaces in profile names

**Comment by JishnuGoyal** [comment]
PTAL @BenHenning , Thanks!

File: domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt [hunk 4]
```diff
@@ -721,8 +721,29 @@ class ProfileManagementController @Inject constructor(
     return imageFile.absolutePath
   }
 
-  private fun onlyLetters(name: String): Boolean {
-    return name.matches(Regex("^[ A-Za-z]+\$"))
+  private fun nameAllowed(name: String): Boolean {
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt]: Given that we're considering also adding a bad word filter in the future, it might be prudent to create a new NameValidator class in the utility module and have name logic added there (along with dedicated tests so that you can more easily cover edge cases vs. having to test those through the profile management controller).

File: domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt [hunk 5]
```diff
@@ -721,8 +721,29 @@ class ProfileManagementController @Inject constructor(
...
+        noRepeatedUseOfAllowedSymbols(name)
+      )
+  }
+
+  private fun notEmptyNoSpacesAndContainsLetters(name: String): Boolean {
+    return name.matches(Regex("^.[\\w\\u00BF-\\u1FFF\\u2C00-\\uD7FF.'\\-]+\$"))
+  }
+
+  private fun noNumbers(name: String): Boolean {
+    return name.matches(Regex("^[^0-9]*\$"))
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt]: You could also do: ``name.none { it.isDigit() }`` which might actually be more performant than the regex check.

File: domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt [hunk 6]
```diff
@@ -721,8 +721,29 @@ class ProfileManagementController @Inject constructor(
...
+  }
+
+  private fun noSymbols(name: String): Boolean {
+    return name.matches(Regex("^[^#*!@\$%^&()_+=\\\\|\\]\\[\":;?/><,`~{}]*\$"))
+  }
+
+  private fun noRepeatedUseOfAllowedSymbols(name: String): Boolean {
+    return name.matches(Regex("^(?!.*([.'-]{2})).*"))
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt]: Could you use a containsMatch here and just check again ``[\.'-]{2}``?

File: domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt [hunk 7]
```diff
@@ -721,8 +721,29 @@ class ProfileManagementController @Inject constructor(
...
+    return (
+      notEmptyNoSpacesAndContainsLetters(name) &&
+        noNumbers(name) &&
+        noSymbols(name) &&
+        noRepeatedUseOfAllowedSymbols(name)
+      )
+  }
+
+  private fun notEmptyNoSpacesAndContainsLetters(name: String): Boolean {
+    return name.matches(Regex("^.[\\w\\u00BF-\\u1FFF\\u2C00-\\uD7FF.'\\-]+\$"))
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt]: Similarly to below, you could have a separate check that uses ``isWhitespace`` to simplify this just to checking for letters. That being said, would ``isLetter`` also work instead of using the pattern?

File: domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt [hunk 8]
```diff
@@ -721,8 +721,29 @@ class ProfileManagementController @Inject constructor(
...
+  }
+
+  private fun noNumbers(name: String): Boolean {
+    return name.matches(Regex("^[^0-9]*\$"))
+  }
+
+  private fun noSymbols(name: String): Boolean {
+    return name.matches(Regex("^[^#*!@\$%^&()_+=\\\\|\\]\\[\":;?/><,`~{}]*\$"))
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt]: Nit: you ought to define regex patterns as vals so that they don't need to be recompiled each time.

Also, why doesn't the letter check above cover the symbols case?

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @JishnuGoyal! Added some more comments for ways I think this could be simplified, and made more future-proof.

File: domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt (hunk 7 above)
Comment (JishnuGoyal) [reply domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt]: This method ensures that the name isn't empty (doesn't allow blank space, next line), but at the same time it matches letters of "any language" -> so isLetters() can't be used. Please Note that this regex pattern doesn't reject any symbols, it merely returns `true` when it there is a `letter` (of any language) is present in the name.

File: domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt (hunk 8 above)
Comment (JishnuGoyal) [reply domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt]: > Also, why doesn't the letter check above cover the symbols case?

Since the regex pattern mentioned here https://github.com/oppia/oppia-android/pull/4081#discussion_r787941521 doesn't reject symbols, this function was added.

File: domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt (hunk 4 above)
Comment (JishnuGoyal) [reply domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt]: > along with dedicated tests so that you can more easily cover edge cases vs. having to test those through the profile management controller

Interesting! Should I also move the tests related to allowed and unallowed names from profile management controller's test to name validator class's test or keep duplicate tests as well?

**Comment by JishnuGoyal** [comment]
This was my first time creating a new class in this project. PTAL @BenHenning

**Comment by BenHenning** [comment]
Thanks @JishnuGoyal. Apologies, I'll need to take another pass on this tomorrow.

File: utility/src/main/java/org/oppia/android/util/namevalidator/NameValidator.kt [hunk 9]
```diff
@@ -0,0 +1,39 @@
+package org.oppia.android.util.namevalidator
```
Comment (BenHenning) [inline utility/src/main/java/org/oppia/android/util/namevalidator/NameValidator.kt]: I suggest putting this under the profile subpackage since it's still relevant to profiles. You'll also need to update the BUILD.bazel file in that package to include a new android_library for this validator.

File: utility/src/main/java/org/oppia/android/util/namevalidator/NameValidator.kt [hunk 10]
```diff
@@ -0,0 +1,39 @@
...
+
+class NameValidator {
```
Comment (BenHenning) [inline utility/src/main/java/org/oppia/android/util/namevalidator/NameValidator.kt]: I suggest making this an ``@Inject``-able class (see https://github.com/oppia/oppia-android/blob/develop/utility/src/main/java/org/oppia/android/util/profile/DirectoryManagementUtil.kt for a reference, and its usages) since that'll allow for better test & dependency management.

File: utility/src/main/java/org/oppia/android/util/namevalidator/NameValidator.kt [hunk 11]
```diff
@@ -0,0 +1,39 @@
...
+  companion object {
+    private const val MATCH_INTERNATIONAL_LETTERS_REJECT_SPACES =
+      "^.[\\w\\u00BF-\\u1FFF\\u2C00-\\uD7FF.'\\-]+\$"
```
Comment (BenHenning) [inline utility/src/main/java/org/oppia/android/util/namevalidator/NameValidator.kt]: How did you determine this range? Is there any documentation that you can point to?

File: utility/src/main/java/org/oppia/android/util/namevalidator/NameValidator.kt [hunk 12]
```diff
@@ -0,0 +1,39 @@
...
+
+    private const val REJECT_SYMBOLS = "^[^#*!@\$%^&()_+=\\\\|\\]\\[\":;?/><,`~{}]*\$"
```
Comment (BenHenning) [inline utility/src/main/java/org/oppia/android/util/namevalidator/NameValidator.kt]: Ditto here--why reject these specific symbols?

File: utility/src/main/java/org/oppia/android/util/namevalidator/NameValidator.kt [hunk 13]
```diff
@@ -0,0 +1,39 @@
...
+
+    private const val REJECT_REPEATED_USE_OF_ALLOWED_SYMBOLS = "[\\.'-]{2}"
+
+    fun validate(name: String): Boolean {
```
Comment (BenHenning) [inline utility/src/main/java/org/oppia/android/util/namevalidator/NameValidator.kt]: Suggest instead: isNameValid.

File: utility/src/main/java/org/oppia/android/util/namevalidator/NameValidator.kt [hunk 14]
```diff
@@ -0,0 +1,39 @@
...
+    }
+
+    private fun notEmptyNoSpacesAndContainsLetters(name: String): Boolean {
+      return name.matches(Regex(MATCH_INTERNATIONAL_LETTERS_REJECT_SPACES))
+    }
+
+    private fun noNumbers(name: String): Boolean {
+      return name.none {
+        it.isDigit()
+      }
```
Comment (BenHenning) [inline utility/src/main/java/org/oppia/android/util/namevalidator/NameValidator.kt]: This can fit on one line--please update.

File: utility/src/main/java/org/oppia/android/util/namevalidator/NameValidator.kt [hunk 15]
```diff
@@ -0,0 +1,39 @@
...
+    fun validate(name: String): Boolean {
+      return (
+        notEmptyNoSpacesAndContainsLetters(name) &&
+          noNumbers(name) &&
+          noSymbols(name) &&
+          noRepeatedUseOfAllowedSymbols(name)
+        )
+    }
+
+    private fun notEmptyNoSpacesAndContainsLetters(name: String): Boolean {
```
Comment (BenHenning) [inline utility/src/main/java/org/oppia/android/util/namevalidator/NameValidator.kt]: Method names should be verb phrases, e.g.: ``containsLettersAndNoSpaces``.

Ditto for the others.

You could also consider making these string extension function, e.g.:

```kotlin
private fun String.containsLettersAndNoSpaces(): Boolean =
  matches(Regex(MATCH_INTERNATIONAL_LETTERS_REJECT_SPACES))
```

File: utility/src/main/java/org/oppia/android/util/namevalidator/NameValidator.kt [hunk 16]
```diff
@@ -0,0 +1,39 @@
...
+      return name.matches(Regex(MATCH_INTERNATIONAL_LETTERS_REJECT_SPACES))
```
Comment (BenHenning) [inline utility/src/main/java/org/oppia/android/util/namevalidator/NameValidator.kt]: Suggest saving these ``Regex`` objects in lazy-initialized ``val``s at the companion object level.

File: utility/src/test/java/org/oppia/android/util/namevalidator/NameValidatorTest.kt [hunk 17]
```diff
@@ -0,0 +1,27 @@
+package org.oppia.android.util.namevalidator
+
+import org.junit.Assert.assertFalse
+import org.junit.Assert.assertTrue
```
Comment (BenHenning) [inline utility/src/test/java/org/oppia/android/util/namevalidator/NameValidatorTest.kt]: Please use Truth assertions, instead (see uses of ``assertThat`` elsewhere in the codebase).

File: domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt (hunk 7 above)
Comment (BenHenning) [reply domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt]: Why wouldn't ``isLetter`` work? It's my understanding that it should be checking for letters in roughly the same range that you're using here.

Also, ``isWhitespace`` should be the same as ``\\w`` (and you could specifically verify this by adding tests to cover various whitespace).

File: domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt (hunk 4 above)
Comment (BenHenning) [reply domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt]: I think you should focus on adding new test cases that are separate from the ProfileManagementController's tests (you also get redundancy this way).

File: domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt (hunk 8 above)
Comment (BenHenning) [reply domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt]: I'm actually wondering if we could just check that it only contains letters and no repeated allowed symbols. Wouldn't the "else" case there be all other symbols (including whitespace, digits, and these symbols)?

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @JishnuGoyal! Took a first pass. I think this is definitely on the right track, but I have a bunch of suggestions. I'll take a more thorough pass on tests in my next review pass, but in the meantime please also:
- Add KDocs for all non-private classes and methods
- Add tests to more thoroughly cover the various cases that the regex patterns can handle
- Fix the broken tests & CI checks

File: utility/src/main/java/org/oppia/android/util/namevalidator/NameValidator.kt (hunk 9 above)
Comment (JishnuGoyal) [reply utility/src/main/java/org/oppia/android/util/namevalidator/NameValidator.kt]: Please have a look at the new android_library and suggest if deps [ ] field is to be added

File: utility/src/main/java/org/oppia/android/util/namevalidator/NameValidator.kt (hunk 11 above)
Comment (JishnuGoyal) [reply utility/src/main/java/org/oppia/android/util/namevalidator/NameValidator.kt]: I found a new in-built way of determining if the input is a letter or not. This implementation is essentially a contraction of that range. It is much more clear now :)

File: utility/src/main/java/org/oppia/android/util/namevalidator/NameValidator.kt (hunk 16 above)
Comment (JishnuGoyal) [reply utility/src/main/java/org/oppia/android/util/namevalidator/NameValidator.kt]: i'm not sure about this one... Is there a reference in the codebase I could use?

File: utility/src/main/java/org/oppia/android/util/namevalidator/NameValidator.kt (hunk 10 above)
Comment (JishnuGoyal) [reply utility/src/main/java/org/oppia/android/util/namevalidator/NameValidator.kt]: Awesome! But what should I `inject` via the constructor as a parameter?

**Comment by JishnuGoyal** [comment]
PTAL @BenHenning 
I will be adding more-tests to check edge cases after the following pass :)
Thanks!

File: domain/src/test/java/org/oppia/android/domain/profile/ProfileManagementControllerTest.kt [hunk 18]
```diff
@@ -167,23 +171,43 @@ class ProfileManagementControllerTest {
   }
 
   @Test
-  fun testAddProfile_addProfileWithNumberInName_checkResultIsFailure() {
+  fun testAddProfile_addProfilesWithUnAllowedNames_checkResultIsFailure() {
```
Comment (BenHenning) [inline domain/src/test/java/org/oppia/android/domain/profile/ProfileManagementControllerTest.kt]:
```suggestion
  fun testAddProfile_addProfilesWithDisallowedNames_checkResultIsFailure() {
```

File: domain/src/test/java/org/oppia/android/domain/profile/ProfileManagementControllerTest.kt [hunk 19]
```diff
@@ -111,6 +111,10 @@ class ProfileManagementControllerTest {
     Profile.newBuilder().setName("Veena").setPin("567").setAllowDownloadAccess(true).build()
   )
 
+  private val allowedNamesList = listOf<String>("जिष्णु", "Ben-Henning", "Rajat.T", "جيشنو")
+
+  private val unAllowedNamesList = listOf<String>("जिष्णु7", "Ben_Henning", "Rajat..T", "جيشنو^&&")
```
Comment (BenHenning) [inline domain/src/test/java/org/oppia/android/domain/profile/ProfileManagementControllerTest.kt]: Nit: suggest disallowedNames

(strike 'List' from both, and switch 'unAllowed' with 'disallowed').

File: utility/src/main/java/org/oppia/android/util/profile/NameValidator.kt [hunk 20]
```diff
@@ -0,0 +1,33 @@
...
+      return (onlyLettersAndAllowedSymbols(name) && noRepeatedUseOfAllowedSymbols(name))
+    }
+
+    private fun onlyLettersAndAllowedSymbols(name: String): Boolean {
+      return name.matches(Regex(MATCH_LETTERS_AND_ALLOWED_SYMBOLS))
+    }
+
+    private fun noRepeatedUseOfAllowedSymbols(name: String): Boolean {
+      return !name.contains(Regex(REJECT_REPEATED_USE_OF_ALLOWED_SYMBOLS))
+    }
```
Comment (BenHenning) [inline utility/src/main/java/org/oppia/android/util/profile/NameValidator.kt]: These should be member functions, instead, and the validator should be injected.

File: utility/src/test/java/org/oppia/android/util/profile/NameValidatorTest.kt [hunk 21]
```diff
@@ -0,0 +1,26 @@
...
+  private val allowedNamesList = listOf<String>("जिष्णु", "Ben-Henning", "Rajat.T", "جيشنو")
+
+  private val unAllowedNamesList =
+    listOf<String>("जिष्णु7", "Ben_Henning", "Rajat..T", "جيشنو^&&", " ", ".", "Ben Henning")
+
+  @Test
+  fun testNameValidator_addUnAllowedName_returnFalse() {
+    unAllowedNamesList.forEach {
+      Truth.assertThat(!NameValidator.isNameValid(it))
+    }
```
Comment (BenHenning) [inline utility/src/test/java/org/oppia/android/util/profile/NameValidatorTest.kt]: Each of the names should be a distinct test for each case being tested (such as English characters, Hindi characters, Portuguese characters, etc., allowed symbols, and failing cases such as disallowed symbols or characters).

File: utility/src/test/java/org/oppia/android/util/profile/NameValidatorTest.kt [hunk 22]
```diff
@@ -0,0 +1,26 @@
...
+  }
+
+  @Test
+  fun testNameValidator_addAllowedName_returnTrue() {
+    allowedNamesList.forEach {
+      Truth.assertThat(NameValidator.isNameValid(it))
```
Comment (BenHenning) [inline utility/src/test/java/org/oppia/android/util/profile/NameValidatorTest.kt]: You're not asserting anything. This should be: assertThat(value).isEqualTo(expectedValue), though because you're testing a boolean you can just use 'isTrue/isFalse'. See  other assertThat() calls in the codebase for reference.

You should also directly import assertThat (per convention & best practices).

File: utility/src/main/java/org/oppia/android/util/namevalidator/NameValidator.kt (hunk 16 above)
Comment (BenHenning) [reply utility/src/main/java/org/oppia/android/util/namevalidator/NameValidator.kt]: It would look something like:

```kotlin
private val letterRegex by lazy { Regex("...") }
```

Then you would use ``letterRegex`` when needed.

File: utility/src/main/java/org/oppia/android/util/namevalidator/NameValidator.kt (hunk 10 above)
Comment (BenHenning) [reply utility/src/main/java/org/oppia/android/util/namevalidator/NameValidator.kt]: You don't need to inject anything into the validator class, but you do need to inject the validator.

File: utility/src/main/java/org/oppia/android/util/namevalidator/NameValidator.kt (hunk 9 above)
Comment (BenHenning) [reply utility/src/main/java/org/oppia/android/util/namevalidator/NameValidator.kt]: I suggest setting up Bazel locally per the wiki and trying to build the app locally (since there are other BUILD files that will need to be updated here).

File: domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt (hunk 7 above)
Comment (BenHenning) [reply domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt]: Reminder to respond to this--isLetter would be a large simplification.

**Review by BenHenning — COMMENTED** [review]
Thanks @JishnuGoyal. Took another pass.

**Comment by JishnuGoyal** [comment]
I'm migrating from Windows environment to Linux Ubuntu, and have been facing some conflicts with the IDE and the new OS. Apologies for the conflicting commits, I'll revert these asap..

File: utility/src/test/java/org/oppia/android/util/profile/NameValidatorTest.kt (hunk 21 above)
Comment (JishnuGoyal) [reply utility/src/test/java/org/oppia/android/util/profile/NameValidatorTest.kt]: > English characters, Hindi characters, Portuguese characters

Could you please clarify which all language characters should I add tests for?

**Comment by JishnuGoyal** [comment]
>  I suggest setting up Bazel locally per the wiki and trying to build the app locally (since there are other BUILD files that will need to be updated here).


It took me a while to set up Bazel and linux environment properly. I think the Bazel build on my current branch is failing because I either haven't properly set up Build.Bazel rules for the new NameValidator class correctly, or injected it incorrectly inside `ProfileManagementController`...
 A little push into the right direction would be very helpful!
image
###### it complains that name validator is unresolved at `ProfileManagmentController`

PTAL @BenHenning

**Comment by JishnuGoyal** [comment]
> Reminder to respond to this--isLetter would be a large simplification.

isLetter() recognizes only english letters --> Every other symbol is "not a letter" to it, including letters from other languages...
Hence it will return false in case anything is input other than the English Alphabet.

PTAL @BenHenning

File: domain/src/test/java/org/oppia/android/domain/profile/ProfileManagementControllerTest.kt [hunk 23]
```diff
@@ -167,23 +171,43 @@ class ProfileManagementControllerTest {
...
+        avatarImagePath = null,
+        allowDownloadAccess = false,
+        colorRgb = -10710042,
+        isAdmin = true
+      ).toLiveData().observeForever(mockUpdateResultObserver)
+      testCoroutineDispatchers.runCurrent()
+
+      verifyUpdateFailed()
+      assertThat(updateResultCaptor.value.getErrorOrNull()).hasMessageThat()
+        .contains("$it does not contain only letters")
```
Comment (BenHenning) [inline domain/src/test/java/org/oppia/android/domain/profile/ProfileManagementControllerTest.kt]: This error seems no longer correct--we should update it.

@srushtirk do you have suggestions on what the new error message should be?

File: utility/src/main/java/org/oppia/android/util/profile/BUILD.bazel [hunk 24]
```diff
@@ -14,3 +14,11 @@ kt_android_library(
         "//third_party:javax_inject_javax_inject",
     ],
 )
+
+kt_android_library(
+    name = "name_validator",
+    srcs = [
+        "NameValidator.kt",
+    ],
+    visibility = ["//domain:__subpackages__","//utility:__subpackages__"],
```
Comment (BenHenning) [inline utility/src/main/java/org/oppia/android/util/profile/BUILD.bazel]: I suggest just making this API visibility (i.e. ``//:oppia_api_visibility``) since we don't specify more granular visibility unless it's a relative sub-package, test-only, or a module.

File: utility/src/main/java/org/oppia/android/util/profile/NameValidatorUtil.kt [hunk 25]
```diff
@@ -0,0 +1,20 @@
+package org.oppia.android.util.profile
+
+/** Utility class for [NameValidator]. */
+object NameValidatorUtil {
```
Comment (BenHenning) [inline utility/src/main/java/org/oppia/android/util/profile/NameValidatorUtil.kt]: I'm not sure I see the point of this class--why not include these properties within NameValidator itself?

File: utility/src/main/java/org/oppia/android/util/profile/NameValidator.kt [hunk 26]
```diff
@@ -0,0 +1,32 @@
+package org.oppia.android.util.profile
+
+import javax.inject.Inject
+import javax.inject.Singleton
+
+/** Utility to validate profile names */
+@Singleton
+class NameValidator @Inject constructor() {
```
Comment (BenHenning) [inline utility/src/main/java/org/oppia/android/util/profile/NameValidator.kt]: Nit: ProfileNameValidator would probably be clearer since 'name' is a bit generic in itself.

File: utility/src/main/java/org/oppia/android/util/profile/NameValidator.kt [hunk 27]
```diff
@@ -0,0 +1,32 @@
+package org.oppia.android.util.profile
+
+import javax.inject.Inject
+import javax.inject.Singleton
+
+/** Utility to validate profile names */
```
Comment (BenHenning) [inline utility/src/main/java/org/oppia/android/util/profile/NameValidator.kt]:
```suggestion
/** Utility to validate that profile names are correctly formatted. */
```

File: utility/src/main/java/org/oppia/android/util/profile/NameValidator.kt [hunk 28]
```diff
@@ -0,0 +1,32 @@
...
+@Singleton
+class NameValidator @Inject constructor() {
+  private val letterAndSymbolsRegex by lazy {
+    Regex("^.[${NameValidatorUtil.lettersAndSymbolsRegexString}]+\$")
+  }
+
+  private val noRepeatedAllowedSymbolsRegex by lazy { Regex("[.'-]{2}") }
+
+  /**
+   * Validates names for a profile
```
Comment (BenHenning) [inline utility/src/main/java/org/oppia/android/util/profile/NameValidator.kt]:
```suggestion
   * Validates a profile name to ensure that it isn't confusingly formatted or contains invalid characters.
```

(May require line wrapping).

File: utility/src/test/java/org/oppia/android/util/profile/NameValidatorTest.kt [hunk 29]
```diff
@@ -0,0 +1,36 @@
...
+
+  @Test
+  fun testNameValidator_addDisallowedName_returnFalse() {
+    disallowedNames.forEach {
+      assertThat(nameValidator.isNameValid(it)).isEqualTo(false)
+    }
+  }
+
+  @Test
+  fun testNameValidator_addAllowedName_returnTrue() {
```
Comment (BenHenning) [inline utility/src/test/java/org/oppia/android/util/profile/NameValidatorTest.kt]: Rather than organizing these tests as pass/fail, you should structure them based on the specific behavior that's being tested, the condition that triggers that behavior, and subsequent outcome. Each behavior should be in its own test. For example:

``testIsNameValid_nameWithSpaces_returnsFalse``

or

```testNameIsValid_nameHasOneDash_returnsTrue``

etc.

File: utility/src/test/java/org/oppia/android/util/profile/NameValidatorTest.kt [hunk 30]
```diff
@@ -0,0 +1,36 @@
...
+    allowedNames.forEach {
+      assertThat(nameValidator.isNameValid(it)).isEqualTo(true)
```
Comment (BenHenning) [inline utility/src/test/java/org/oppia/android/util/profile/NameValidatorTest.kt]: The more Truthy way to do this is:

```suggestion
      assertThat(nameValidator.isNameValid(it)).isTrue()
```

**Review by BenHenning — CHANGES_REQUESTED** [review]
> > Reminder to respond to this--isLetter would be a large simplification.
> 
> isLetter() recognizes only english letters --> Every other symbol is "not a letter" to it, including letters from other languages... Hence it will return false in case anything is input other than the English Alphabet.
> 
> PTAL @BenHenning

Out of curiosity, where did you obverse this behavior @JishnuGoyal? Per https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/is-letter.html and the corresponding JVM implementation (https://github.com/JetBrains/kotlin/blob/6a670dc5f38fc73eb01d754d8f7c158ae0176ceb/libraries/stdlib/jvm/src/kotlin/text/CharCategoryJVM.kt#L22) isLetter should be conforming to the category "Ll" of the Unicode specification which means every character listed in https://www.compart.com/en/unicode/category/Ll should return true. https://www.compart.com/en/unicode/category/Lu and https://www.compart.com/en/unicode/category/Lo are also matched. Per [this Kotlin](https://play.kotlinlang.org/#eyJ2ZXJzaW9uIjoiMS42LjEwIiwicGxhdGZvcm0iOiJqYXZhIiwiYXJncyI6IiIsIm5vbmVNYXJrZXJzIjp0cnVlLCJ0aGVtZSI6ImlkZWEiLCJjb2RlIjoiLyoqXG4gKiBZb3UgY2FuIGVkaXQsIHJ1biwgYW5kIHNoYXJlIHRoaXMgY29kZS4gXG4gKiBwbGF5LmtvdGxpbmxhbmcub3JnIFxuICovXG5cbmZ1biBtYWluKCkge1xuICAgIHByaW50bG4oJ2EnLmlzTGV0dGVyKCkpXG4gICAgcHJpbnRsbignw78nLmlzTGV0dGVyKCkpXG4gICAgcHJpbnRsbignxJEnLmlzTGV0dGVyKCkpXG4gICAgcHJpbnRsbignxaknLmlzTGV0dGVyKCkpXG4gICAgcHJpbnRsbignxbMnLmlzTGV0dGVyKCkpXG4gICAgcHJpbnRsbignxr4nLmlzTGV0dGVyKCkpXG4gICAgcHJpbnRsbignyKEnLmlzTGV0dGVyKCkpXG4gICAgcHJpbnRsbign0bEnLmlzTGV0dGVyKCkpXG4gICAgcHJpbnRsbignzrYnLmlzTGV0dGVyKCkpXG4gICAgcHJpbnRsbign0asnLmlzTGV0dGVyKCkpXG4gICAgcHJpbnRsbign4YOTJy5pc0xldHRlcigpKVxuICAgIHByaW50bG4oJ+CkhScuaXNMZXR0ZXIoKSlcbn0ifQ==) code, all of the tested characters across multiple scripts (including on Devanagari at the end) all return true for 'isLetter'. Am I maybe missing something?

Beyond the above, I took another pass on the PR--PTAL.

**Comment by JishnuGoyal** [comment]
> Out of curiosity, where did you obverse this behavior @JishnuGoyal? 

@BenHenning, have a look at <a href = "https://pl.kotl.in/KHcwbnFzy">this code sample</a>. This is a manual test I did using isLetter(). Please feel free to press the `run` option and check the implementation.

> all of the tested characters across multiple scripts (including on Devanagari at the end) all return true for 'isLetter'. Am I maybe missing something?

The first test case, `जिष्णु` [  `Jishnu` in Hindi ] in the above code sample fails only due to using isLetter() , as it cannot recognize complex usage of [HINDI, devnagri] literals, such as in names. 
This is because the formation of `letters` in hindi (and probably some other languages too) changes according to the `word`. 

Although isLetter() works fine for _individual letters_, in case of some words, it returns false when it actually should return true due to complex usage of the letters.
#### Another way of saying is that we are using letters which are beyond the set of letters conforming to the category "Ll" of the Unicode specification.

_Another problem is that isLetter() will also `reject` allowed symbols._ [This is why all the other test cases fail in the code sample]

<a href = "https://pl.kotl.in/3ZFRtuPWQ">Here is a code sample</a> using regex which passes the same tests.

File: utility/src/test/java/org/oppia/android/util/profile/NameValidatorTest.kt (hunk 29 above)
Comment (JishnuGoyal) [reply utility/src/test/java/org/oppia/android/util/profile/NameValidatorTest.kt]: Added. PTAL and let me know if more tests are needed

**Comment by JishnuGoyal** [comment]
PTAL @BenHenning

**Comment by BenHenning** [comment]
Apologies; will  need to look at this tomorrow.

File: utility/src/main/java/org/oppia/android/util/profile/BUILD.bazel [hunk 31]
```diff
@@ -20,5 +20,5 @@ kt_android_library(
     srcs = [
         "NameValidator.kt",
```
Comment (BenHenning) [inline utility/src/main/java/org/oppia/android/util/profile/BUILD.bazel]: Looks like this also needs to be renamed.

File: utility/src/test/java/org/oppia/android/util/profile/ProfileNameValidatorTest.kt [hunk 32]
```diff
@@ -0,0 +1,71 @@
...
+  @Test
+  fun testIsNameValid_nameWithAllowedSymbols_returnsTrue() {
+    val namesWithAllowedSymbol = listOf<String>("Ben-Henning", "Rajat.T", "G'Jishnu")
+    namesWithAllowedSymbol.forEach {
+      assertThat(profileNameValidator.isNameValid(it)).isTrue()
+    }
+  }
+
+  @Test
+  fun testIsNameValid_nameWithRepeatedAllowedSymbols_returnsFalse() {
```
Comment (BenHenning) [inline utility/src/test/java/org/oppia/android/util/profile/ProfileNameValidatorTest.kt:79]: I think this will be a good candidate for parameterized tests, though that'll need to wait for my chain of math expressions PRs to be merged (which might take another week or so). Are you okay with waiting for that?

**Review by BenHenning — COMMENTED** [review]
> > Out of curiosity, where did you obverse this behavior @JishnuGoyal?
> 
> @BenHenning, have a look at [this code sample](https://pl.kotl.in/KHcwbnFzy). This is a manual test I did using isLetter(). Please feel free to press the `run` option and check the implementation.
> 
> > all of the tested characters across multiple scripts (including on Devanagari at the end) all return true for 'isLetter'. Am I maybe missing something?
> 
> The first test case, `जिष्णु` [ `Jishnu` in Hindi ] in the above code sample fails only due to using isLetter() , as it cannot recognize complex usage of [HINDI, devnagri] literals, such as in names. This is because the formation of `letters` in hindi (and probably some other languages too) changes according to the `word`.
> 
> Although isLetter() works fine for _individual letters_, in case of some words, it returns false when it actually should return true due to complex usage of the letters.
> 
> #### Another way of saying is that we are using letters which are beyond the set of letters conforming to the category "Ll" of the Unicode specification.
> _Another problem is that isLetter() will also `reject` allowed symbols._ [This is why all the other test cases fail in the code sample]
> 
> [Here is a code sample](https://pl.kotl.in/3ZFRtuPWQ) using regex which passes the same tests.

@JishnuGoyal thanks for the example. Might https://developer.android.com/reference/kotlin/java/lang/Character#isAlphabetic(kotlin.Int) work instead? I think the issue is making sure that modifier and control characters are also considered (since we need to make sure RTL markers also aren't ignored since they can appear).

Besides the above, I took another pass on the PR but didn't focus as much on the util impl and tests since a lot is in-flux at the moment. Please also make sure that the CI checks are passing before sending this back.

File: utility/src/main/java/org/oppia/android/util/profile/BUILD.bazel (hunk 31 above)
Comment (JishnuGoyal) [reply utility/src/main/java/org/oppia/android/util/profile/BUILD.bazel]: done

File: utility/src/test/java/org/oppia/android/util/profile/ProfileNameValidatorTest.kt (hunk 32 above)
Comment (JishnuGoyal) [reply utility/src/test/java/org/oppia/android/util/profile/ProfileNameValidatorTest.kt:79]: Sure @BenHenning . Is it ready yet?

**Comment by JishnuGoyal** [comment]
> @JishnuGoyal thanks for the example. Might https://developer.android.com/reference/kotlin/java/lang/Character#isAlphabetic(kotlin.Int) work instead? I think the issue is making sure that modifier and control characters are also considered (since we need to make sure RTL markers also aren't ignored since they can appear).

Thank you so much @BenHenning for this suggestion. 
I must bring into notice that although isAlphabet() handles all the cases well, some hindi characters as mentioned before will not be recognised (I ran tests and verified). [the current impl handles it correctly though]

Also, isAlphabet is only available in Java, so an additional Java class will be introduced to use it. If we are ready to continue with this, may i push the required code?

**Comment by JishnuGoyal** [comment]
PTAL @BenHenning , looking to confirm if im on the right track, i believe making a Java file wouldnt be such a good idea..

File: utility/src/main/java/org/oppia/android/util/profile/BUILD.bazel [hunk 33]
```diff
@@ -16,9 +17,34 @@ kt_android_library(
...
+        "ProfileNameValidatorModule.kt",
+    ],
+    visibility = ["//:oppia_prod_module_visibility"],
+    deps = [
+        ":dagger",
+        ":profile_name_validator_impl",
+    ],
+)
+
+dagger_rules()
```
Comment (BenHenning) [inline utility/src/main/java/org/oppia/android/util/profile/BUILD.bazel]: Please add missing EOF newline.

**Comment by BenHenning** [comment]
Apologies @JishnuGoyal. I'll need to delay my review on this due to being a bit slammed this week due to a release we're preparing for later in the week.

**Comment by JishnuGoyal** [comment]
@seanlip Could you please reopen this as well? 
Thanks!

**Comment by JishnuGoyal** [comment]
PTAL @BenHenning

**Comment by BenHenning** [comment]
Hi. Really sorry for the review delay--I was still really slammed the last few weeks.

I'll take a pass on Monday.In the meantime, you should update to the latest develop branch @JishnuGoyal and address any conflicts.

File: utility/src/test/java/org/oppia/android/util/profile/ProfileNameValidatorTest.kt (hunk 32 above)
Comment (BenHenning) [reply utility/src/test/java/org/oppia/android/util/profile/ProfileNameValidatorTest.kt:79]: Yep! You can look at the following for an example: https://github.com/oppia/oppia-android/blob/develop/domain/src/test/java/org/oppia/android/domain/classify/rules/numericexpressioninput/NumericExpressionInputIsEquivalentToRuleClassifierProviderTest.kt.

**Comment by BenHenning** [comment]
Hi @JishnuGoyal. Sorry for the long review. I spent a while looking into different options, and I think the best option is just to implement our own character-based alphabetic check. This ensures proper Unicode compatibility (which is difficult with Regex), but accounts for the mark characters used in Hindi. See my implementation for reference: https://pl.kotl.in/V7hAJ9lsh. This seems to work correctly for the characters in your name, and it avoids needing to depend on the Android Character.isAlphabetic function so it can be done completely in Kotlin without any warnings. Let me know what you think.

Once we finalize the checking approach, I'll take a full pass on the PR.

**Comment by JishnuGoyal** [comment]
> Hi @JishnuGoyal. Sorry for the long review. I spent a while looking into different options, and I think the best option is just to implement our own character-based alphabetic check. This ensures proper Unicode compatibility (which is difficult with Regex), but accounts for the mark characters used in Hindi. See my implementation for reference: https://pl.kotl.in/V7hAJ9lsh. This seems to work correctly for the characters in your name, and it avoids needing to depend on the Android Character.isAlphabetic function so it can be done completely in Kotlin without any warnings. Let me know what you think.

Thank you so much @BenHenning for this awesome suggestion. CharCategory class actually solves the problem in Kotlin itself. I have added the required necessary changes and pushed them.

**Comment by JishnuGoyal** [comment]
Talking about the CI checks, I do need a little push in the right direction here --
I have gone through the logs but I don't understand why the ProfileNameValidator class is not being recognised properly --
I have injected this class just the way other classes are being injected -- 
For reference, I saw how OppiaClock has been injected and did the same with ProfileNameValidator.

**Comment by JishnuGoyal** [comment]
I have also set up the bazel configuration for `ProfileNameValidator.`
Why is it failing?

Also while we are at it, would it be okay to not _Inject_ `ProfileNameValidator` and simply use an object of it in `ProfileManagementController` ?

PTAL @BenHenning 
I feel its been a while this PR has been open and I hope this could be resolved soon, Thanks!

**Comment by BenHenning** [comment]
@JishnuGoyal I think you don't need a module here (specifically ``ProfileNameValidatorModule``). Modules are only needed when we want to provide different implementations. We can forego the interface and just provide an injectable implementation class.

The error is coming from the fact that the module needs to be included in every suite that depends on ``ProfileManagementControllerTest`` (which is, to say, almost every test in the codebase). Not having a new module avoids all of this and should simplify things quite a bit.

**Comment by JishnuGoyal** [comment]
> @JishnuGoyal I think you don't need a module here (specifically ProfileNameValidatorModule). Modules are only needed when we want to provide different implementations. We can forego the interface and just provide an injectable implementation class.
The error is coming from the fact that the module needs to be included in every suite that depends on ProfileManagementControllerTest (which is, to say, almost every test in the codebase). Not having a new module avoids all of this and should simplify things quite a bit.

Thank you so much for this tip! I have added these changes :)

Other than the lint test, all the tests are failing due to an unrelated class, ProfileEditActivityTest --
Could you please tell how should i proceed with this? 

PTAL @BenHenning

File: app/src/main/java/org/oppia/android/app/application/ApplicationComponent.kt [hunk 34]
```diff
@@ -99,6 +99,7 @@ import javax.inject.Singleton
     LocaleProdModule::class, ActivityRecreatorProdModule::class,
     NumericExpressionInputModule::class, AlgebraicExpressionInputModule::class,
     MathEquationInputModule::class, SplitScreenInteractionModule::class,
+    LocaleProdModule::class, ActivityRecreatorProdModule::class,
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/application/ApplicationComponent.kt]: This appears duplicated with a few lines above. Please remove.

File: utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt [hunk 35]
```diff
@@ -0,0 +1,55 @@
+package org.oppia.android.util.profile
+
+import javax.inject.Inject
+import javax.inject.Singleton
+
+/** Utility to validate that profile names are correctly formatted. */
+@Singleton
```
Comment (BenHenning) [inline utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt]: This can be omitted--scopes are only needed if there's state (otherwise it's fine for the Dagger provider to recreate the class).

File: utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt [hunk 36]
```diff
@@ -0,0 +1,55 @@
...
+class ProfileNameValidator @Inject constructor() {
+  private val noRepeatedAllowedSymbolsRegex by lazy { Regex("[.'-]{2}") }
+
+  /**
+   * Validates a profile name to ensure that it isn't confusingly formatted
+   * or contains invalid characters.
```
Comment (BenHenning) [inline utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt]: Two nits:
1. Please make sure documentation lines take up as much horizontal space as possible before line-wrapping (i.e. up to 100 characters which is our line limit).
2. Perhaps add some clarifying details about what 'invalid' means (e.g. non-letter characters, per the Unicode standard for letter categories, plus apostrophes and dashes).

File: utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt [hunk 37]
```diff
@@ -0,0 +1,55 @@
...
+   *
+   * @param name name of the profile
+   * @return if the profile name is allowed or not
+   */
+  fun isNameValid(name: String): Boolean {
+    return (onlyLettersAndAllowedSymbols(name) && noRepeatedUseOfAllowedSymbols(name))
```
Comment (BenHenning) [inline utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt]:
```suggestion
    return onlyLettersAndAllowedSymbols(name) && noRepeatedUseOfAllowedSymbols(name)
```

Small nit, but we don't typically add redundant parentheses.

File: utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt [hunk 38]
```diff
@@ -0,0 +1,55 @@
...
+  }
+
+  /** Validates if the character in the name is an alphabet or an allowed symbol or not. */
+  private fun onlyLettersAndAllowedSymbols(name: String): Boolean {
```
Comment (BenHenning) [inline utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt]: We generally keep method names as verbs or verb phrases. Suggest renaming to something like: ``containsOnlyLettersAndAllowedSymbols``.

Ditto for other methods in this class.

File: utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt [hunk 39]
```diff
@@ -0,0 +1,55 @@
...
+@Singleton
+class ProfileNameValidator @Inject constructor() {
+  private val noRepeatedAllowedSymbolsRegex by lazy { Regex("[.'-]{2}") }
+
+  /**
+   * Validates a profile name to ensure that it isn't confusingly formatted
+   * or contains invalid characters.
+   *
+   * @param name name of the profile
+   * @return if the profile name is allowed or not
```
Comment (BenHenning) [inline utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt]: Perhaps instead: whether it's a valid, acceptable name?

File: utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt [hunk 40]
```diff
@@ -0,0 +1,55 @@
...
+  }
+
+  /** Validates if the character in the name is an alphabet or an allowed symbol or not. */
+  private fun onlyLettersAndAllowedSymbols(name: String): Boolean {
+    name.forEach {
+      if (!(it.isAlphabetic() || isSymbolAllowed(it))) {
+        return false
+      }
+    }
+    return true
```
Comment (BenHenning) [inline utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt]: Can be simplified and made more Kotlin-idiomatic:

```kotlin
return name.all { it.isAlphabetic() || isSymbolAllowed(it) }
```

Also given the above, perhaps rename the latter helper to ``isAllowedSymbol`` since I think it'll be less confusion ('symbol' could be construed to mean any written symbol which then puts it a bit at odds with allowed alphabetic characters).

File: utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt [hunk 41]
```diff
@@ -0,0 +1,55 @@
+package org.oppia.android.util.profile
+
+import javax.inject.Inject
+import javax.inject.Singleton
+
+/** Utility to validate that profile names are correctly formatted. */
+@Singleton
+class ProfileNameValidator @Inject constructor() {
+  private val noRepeatedAllowedSymbolsRegex by lazy { Regex("[.'-]{2}") }
```
Comment (BenHenning) [inline utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt]: Does the '.' need to be escaped? I'm assuming that names like "Jerry" would fail right now (would be nice to add a test case for that scenario to verify a fix).

File: utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt [hunk 42]
```diff
@@ -0,0 +1,55 @@
...
+  private fun noRepeatedUseOfAllowedSymbols(name: String): Boolean {
+    return !name.contains(noRepeatedAllowedSymbolsRegex)
+  }
+
+  private fun isSymbolAllowed(symbol: Char): Boolean {
+    return symbol == '.' || symbol == '-' || symbol == '\''
+  }
+
+  private fun Char.isAlphabetic(): Boolean {
+    /**
```
Comment (BenHenning) [inline utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt]: Should be a block comment, or multiple line comments. KDocs should only be reserved for top-level members like classes, objects, functions, and values.

File: utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt (hunk 38 above)
Comment (BenHenning) [inline utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt]: Optional: you could instead make the name a receiver, e.g. ``String.containsOnlyLettersAndAllowedSymbols``. Ditto for the other check method, below.

File: utility/src/test/java/org/oppia/android/util/profile/ProfileNameValidatorTest.kt [hunk 43]
```diff
@@ -0,0 +1,71 @@
...
+import org.junit.Test
+import javax.inject.Inject
+
+class ProfileNameValidatorTest {
+  @Inject
+  lateinit var profileNameValidator: ProfileNameValidator
+
+  @Before
+  fun setup() {
+    profileNameValidator = ProfileNameValidator()
```
Comment (BenHenning) [inline utility/src/test/java/org/oppia/android/util/profile/ProfileNameValidatorTest.kt]: This should be injected as I mentioned earlier. Are you running into any issues with setting this up as a Robolectric test? I suggest referencing other utility and domain tests for a reference (you probably won't need any modules nor a custom component, so it should be a relatively simple setup).

File: utility/src/test/java/org/oppia/android/util/profile/ProfileNameValidatorTest.kt [hunk 44]
```diff
@@ -0,0 +1,71 @@
...
+  }
+
+  @Test
+  fun testIsNameValid_nameWithNumber_returnsFalse() {
+    val nameWithNumber = "Jishnu7"
+    assertThat(profileNameValidator.isNameValid(nameWithNumber)).isFalse()
+  }
+
+  @Test
+  fun testIsNameValid_nameWithDisallowedSymbol_returnsFalse() {
```
Comment (BenHenning) [inline utility/src/test/java/org/oppia/android/util/profile/ProfileNameValidatorTest.kt:59]: Since we were waiting for parameterized tests, I suggest using that here, instead, to avoid the for-loop/control flow below. See https://github.com/oppia/oppia-android/blob/develop/utility/src/test/java/org/oppia/android/util/math/MathExpressionParserTest.kt for an example test that uses parameterization.

Ditto for other tests that are verifying multiple things.

**Review by BenHenning — COMMENTED** [review]
Thanks @JishnuGoyal! Nice tests & overall implementation. I find this much cleaner and easier to understand!

I had a bunch of comments, but most of them are just nits. PTAL and let me know if you have any follow-up questions. I think after the latest batch of comments this PR will probably be more or less LGTM.

File: utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt (hunk 35 above)
Comment (JishnuGoyal) [reply utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt]: done

File: app/src/main/java/org/oppia/android/app/application/ApplicationComponent.kt (hunk 34 above)
Comment (JishnuGoyal) [reply app/src/main/java/org/oppia/android/app/application/ApplicationComponent.kt]: done

File: utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt (hunk 42 above)
Comment (JishnuGoyal) [reply utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt]: Noted. Done.

File: utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt (hunk 36 above)
Comment (JishnuGoyal) [reply utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt]: done

File: utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt (hunk 37 above)
Comment (JishnuGoyal) [reply utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt]: done

File: utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt (hunk 38 above)
Comment (JishnuGoyal) [reply utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt]: done!

File: utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt (hunk 39 above)
Comment (JishnuGoyal) [reply utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt]: Yep, done :)

File: utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt (hunk 40 above)
Comment (JishnuGoyal) [reply utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt]: noted, thanks. Done.

File: utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt (hunk 38 above)
Comment (JishnuGoyal) [reply utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt]: I feel the implementation would be cleaner this way because  otherwise, inside the method, "it" keyword will have to be used twice which will have two different meanings each time (String and char).

File: utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt (hunk 41 above)
Comment (JishnuGoyal) [reply utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt]: No, the '.' doesn't need to be escaped -- Kotlin actually complains an redundant escape when I tried doing it. Also, "Jerry" passes the test, and I'm adding a test case just in case.

File: utility/src/test/java/org/oppia/android/util/profile/ProfileNameValidatorTest.kt (hunk 43 above)
Comment (JishnuGoyal) [reply utility/src/test/java/org/oppia/android/util/profile/ProfileNameValidatorTest.kt]: done :)

File: utility/src/test/java/org/oppia/android/util/profile/ProfileNameValidatorTest.kt (hunk 44 above)
Comment (JishnuGoyal) [reply utility/src/test/java/org/oppia/android/util/profile/ProfileNameValidatorTest.kt:59]: done :)

File: utility/src/main/java/org/oppia/android/util/profile/BUILD.bazel (hunk 33 above)
Comment (JishnuGoyal) [reply utility/src/main/java/org/oppia/android/util/profile/BUILD.bazel]: done

**Comment by JishnuGoyal** [comment]
PTAL @BenHenning is it correct way to write tests? 
Also, are any additional changes required to make parameterised tests work with Build.Bazel ?

File: utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt (hunk 41 above)
Comment (BenHenning) [reply utility/src/main/java/org/oppia/android/util/profile/ProfileNameValidator.kt]: Ah, did you escape it with ``\\.``? Though, if it is actually being treated as '.' correctly, then this is probably a moot point.

File: domain/src/test/java/org/oppia/android/domain/profile/ProfileManagementControllerTest.kt (hunk 23 above)
Comment (BenHenning) [reply domain/src/test/java/org/oppia/android/domain/profile/ProfileManagementControllerTest.kt]: Is this still unresolved @JishnuGoyal?

Also, I think we should make sure that there are at least a few tests for name validation in ProfileManagementControllerTest, too, such as:
- One valid name with Latin characters
- One valid name with Devanagari characters (which would fail without the new validator)
- One invalid name (with the correct presented)

What do you think?

File: utility/src/test/java/org/oppia/android/util/profile/NameValidatorTest.kt (hunk 21 above)
Comment (BenHenning) [reply utility/src/test/java/org/oppia/android/util/profile/NameValidatorTest.kt]: I think the latest tests are sufficient.

File: utility/src/test/java/org/oppia/android/util/profile/ProfileNameValidatorTest.kt [hunk 45]
```diff
@@ -0,0 +1,119 @@
...
+    val nameWithNumber = "Jishnu7"
+    assertThat(profileNameValidator.isNameValid(nameWithNumber)).isFalse()
+  }
+
+  @Test
+  @RunParameterized(
+    Iteration("Ben#Henning", "name=Ben#Henning"),
+    Iteration("Rajay@T", "name=Rajay@T"),
+    Iteration("جيشنو^&&", "name=جيشنو^&&"),
+    Iteration("_Jishnu", "name=_Jishnu"),
```
Comment (BenHenning) [inline utility/src/test/java/org/oppia/android/util/profile/ProfileNameValidatorTest.kt]: Nit: Please remove the trailing comma for here & other parameterized tests below.

**Review by BenHenning — COMMENTED** [review]
Thanks @JishnuGoyal! Just had a few remaining comments, otherwise this PR looks really close to being done.

> PTAL @BenHenning is it correct way to write tests? Also, are any additional changes required to make parameterised tests work with Build.Bazel ?

They look correct--did they pass for you when run?

For Bazel, you may need to update the test's dependencies here: https://github.com/oppia/oppia-android/blob/develop/utility/BUILD.bazel#L90. For the needed dependencies, see the referenced parameterized tests for which libraries need to be included. You should be able to verify locally if it works by running the following in a terminal (from the repository root):

```sh
bazel test //utility:src/main/java/org/oppia/android/util/profile/ProfileNameValidatorTest
```

File: utility/src/test/java/org/oppia/android/util/profile/ProfileNameValidatorTest.kt (hunk 45 above)
Comment (JishnuGoyal) [reply utility/src/test/java/org/oppia/android/util/profile/ProfileNameValidatorTest.kt]: done

**Comment by JishnuGoyal** [comment]
I have added Build.bazel file for ProfileNameValidatorTest but I'm facing some problems -  This mentioned test is failing even after adding the bazel files.
>bazel test //utility:src/main/java/org/oppia/android/util/profile/ProfileNameValidatorTest

PTAL @BenHenning . Which all places do the bazel files need to be added?

**Comment by JishnuGoyal** [comment]
> Is this still unresolved @JishnuGoyal?

Yes, haven't heard back from @srushtirk yet.

>Also, I think we should make sure that there are at least a few tests for name validation in ProfileManagementControllerTest, too, such as:

    One valid name with Latin characters
    One valid name with Devanagari characters (which would fail without the new validator)
    One invalid name (with the correct presented)

What do you think?

Sure.

File: domain/src/test/java/org/oppia/android/domain/profile/ProfileManagementControllerTest.kt (hunk 23 above)
Comment (seanlip) [reply domain/src/test/java/org/oppia/android/domain/profile/ProfileManagementControllerTest.kt]: I will take over answering this one, since @srushtirk is away.

Let's go with this error message: "Please choose a profile name that doesn't include numbers or symbols."

(Also, @JishnuGoyal, in the future, if you don't hear back from someone within 2 days and it's blocking you, please escalate. Thanks.)

**Comment by seanlip** [comment]
Just a note -- for the first point, I have responded to @JishnuGoyal's comment.

**Comment by JishnuGoyal** [comment]
> Just a note -- for the first point, I have responded to @JishnuGoyal's comment.

@seanlip , I'm not sure what this message is in reference to, could you please provide some more detail?

**Comment by seanlip** [comment]
It refers to: "Is this still unresolved @JishnuGoyal? / Yes, haven't heard back from @srushtirk yet."

**Comment by BenHenning** [comment]
Reopened since this was closed due to my late review.

File: utility/src/test/java/org/oppia/android/util/profile/BUILD.bazel [hunk 46]
```diff
@@ -0,0 +1,31 @@
...
+        "//third_party:com_google_truth_truth",
+        "//third_party:junit_junit",
+        "//third_party:org_robolectric_robolectric",
+        "//third_party:robolectric_android-all",
+        "//utility/src/main/java/org/oppia/android/util/locale:prod_module",
+        "//utility/src/main/java/org/oppia/android/util/logging:prod_module",
+    ],
+)
+
+dagger_rules()
```
Comment (BenHenning) [inline utility/src/test/java/org/oppia/android/util/profile/BUILD.bazel]: Please add a missing EOF line to this file.

File: utility/src/test/java/org/oppia/android/util/profile/ProfileNameValidatorTest.kt [hunk 47]
```diff
@@ -0,0 +1,119 @@
...
+@Config(manifest = Config.NONE)
+class ProfileNameValidatorTest {
+  @Inject
+  lateinit var profileNameValidator: ProfileNameValidator
+
+  @Parameter
+  lateinit var name: String
+
+  @Before
+  fun setup() {
```
Comment (BenHenning) [inline utility/src/test/java/org/oppia/android/util/profile/ProfileNameValidatorTest.kt:36]: Nit: ``setUp`` for consistency with other test suites.

File: domain/src/test/java/org/oppia/android/domain/profile/ProfileManagementControllerTest.kt (hunk 23 above)
Comment (BenHenning) [reply domain/src/test/java/org/oppia/android/domain/profile/ProfileManagementControllerTest.kt]: @JishnuGoyal reminder to please address this comment.

**Review by BenHenning — CHANGES_REQUESTED** [review]
Apologies for the really late review here.

Thanks @JishnuGoyal. I just had a few nits, plus a comment on an existing thread that hasn't yet been resolved. Other than those comments, I think the PR is very close to 'LGTM'. PTAL.

**Comment by BenHenning** [comment]
@JishnuGoyal this would be value to get in, especially since it's so close to being finished up. Do you have a plan for completing this?

**Comment by BenHenning** [comment]
This is actually on my backlog to investigate, but I haven't been able to make the time for it quite yet.

**Comment by BenHenning** [comment]
I'm now taking a look at this (since it's functionality that we'd like to include in the upcoming beta release).

**Comment by BenHenning** [comment]
Created https://github.com/JishnuGoyal/oppia-android/pull/1 to address the conflicts & broken tests. PTAL @JishnuGoyal.

File: domain/src/test/java/org/oppia/android/domain/profile/ProfileManagementControllerTest.kt (hunk 23 above)
Comment (BenHenning) [reply domain/src/test/java/org/oppia/android/domain/profile/ProfileManagementControllerTest.kt]: add_profile_error_name_only_letters still needs to be updated to have a clearer error.

File: utility/src/test/java/org/oppia/android/util/profile/BUILD.bazel (hunk 46 above)
Comment (BenHenning) [reply utility/src/test/java/org/oppia/android/util/profile/BUILD.bazel]: This has been resolved.

File: utility/src/test/java/org/oppia/android/util/profile/ProfileNameValidatorTest.kt (hunk 47 above)
Comment (BenHenning) [reply utility/src/test/java/org/oppia/android/util/profile/ProfileNameValidatorTest.kt:36]: Still unresolved.

**Review by BenHenning — APPROVED** [review]
Latest changes look good and CI is now passing. There are two comments that still need resolution before this can be fixed, though I think I'm going to go ahead and merge this and then address them in a separate PR (to avoid needing another day of iteration).

**Comment by BenHenning** [comment]
Since this PR is part of broader urgent work for the Beta MR1 release, I'm force-merging this without @rt4914's review. I've self-reviewed it and found no major issues. Furthermore, https://github.com/oppia/oppia-android/issues/4567 is tracking ensuring that this does get reviewed by someone else later after it's been merged.

File: utility/src/test/java/org/oppia/android/util/profile/ProfileNameValidatorTest.kt (hunk 47 above)
Comment (BenHenning) [reply utility/src/test/java/org/oppia/android/util/profile/ProfileNameValidatorTest.kt:36]: Resolved in #4565.

File: domain/src/test/java/org/oppia/android/domain/profile/ProfileManagementControllerTest.kt (hunk 23 above)
Comment (BenHenning) [reply domain/src/test/java/org/oppia/android/domain/profile/ProfileManagementControllerTest.kt]: Resolved in #4565.
