### PR TITLE
Fix #5959: Profile colors and positions change when selecting a profile in the Profile screen

### LINKED ISSUE #5959: [BUG]: Profile colors and positions change when selecting a profile in the Profile screen
### Describe the bug

When selecting a profile from the "Select your profile" screen, the profile list slightly shifts and some profile colors change unexpectedly.

### Steps To Reproduce

- Open the Oppia app.
- Go to the "Select your profile" screen.
- Set up multiple profiles (more than 5).
- Scroll down and click on any profile near the bottom of the list.
- Observe that the profiles slightly shift from their original position and profile colors change.

### Expected Behavior

Profile positions and colors should remain consistent when selecting a profile.

### Screenshots/Videos

https://github.com/user-attachments/assets/5b91a4b7-1a96-4f34-ac61-7fe639506d2e

### What device/emulator are you using?

Oppo reno 2f

### Which Android version is your device/emulator running?

Android 11

### Which version of the Oppia Android app are you using?

_No response_

### Additional Context

**Cause:**
When a profile is clicked, `onProfileClick() `updates the learner ID if it is absent. This causes the `LiveData` holding the profile list to emit a new list. Since the current adapter uses `notifyDataSetChanged()`, the entire RecyclerView reloads all items. As a result, the list briefly shows flickering, incorrect colors, and temporary item shifts.

**Proposed Solution:**
Introduce `DiffUtil`in `RecyclerViewBindingAdapter` for the `profile_recycler_view`. Since each profile has a unique id, we can use it to efficiently calculate differences and update only the changed items. This will eliminate flickering and keep profile colors stable during list updates.

**Files to Check:**
- [ProfileChooserFragmentPresenter](https://github.com/oppia/oppia-android/blob/fcb87dc79074450f90a658c9dddb186a12ab75f3/app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenter.kt#L70C7-L70C38) -> funs `onProfileClick()`, `updateLearnerIdIfAbsent()`, `computeLoginRoute()`
- [ProfilemanagementController](https://github.com/oppia/oppia-android/blob/fcb87dc79074450f90a658c9dddb186a12ab75f3/domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt#L94) -> funs `initializeLearnerId()`
- [ProfileChooserViewModel](https://github.com/oppia/oppia-android/blob/fcb87dc79074450f90a658c9dddb186a12ab75f3/app/src/main/java/org/oppia/android/app/profile/ProfileChooserViewModel.kt#L22) -> fun `retrieveProfiles()`
- [RecyclerViewBindingAdapter](https://github.com/oppia/oppia-android/blob/3ffeedf7e90795ae9b23ec600a19d7cff72f1ca4/app/src/main/java/org/oppia/android/app/recyclerview/RecyclerViewBindingAdapter.java#L20)
- [BindableAdapter](https://github.com/oppia/oppia-android/blob/3ffeedf7e90795ae9b23ec600a19d7cff72f1ca4/app/src/main/java/org/oppia/android/app/recyclerview/BindableAdapter.kt#L42)

**Personal Note:**
I personally tried using `DiffUtil` for the `profile_recycler_view`, and it solved the problem. After applying it, the list updates smoothly without shifts or temporary wrong colors.

Output:

https://github.com/user-attachments/assets/64d1048c-fe56-44b8-9786-a3279350640d

### PR DESCRIPTION
**Pull request by itsadityaaaaa**
## Explanation

  - Explain what your PR does. If this PR fixes an existing bug, please include
  - "Fixes #5959 " in the explanation so that GitHub can auto-close the issue
  - when this PR is merged there will be no flickering while choosing the profile and user can navigate smoothly.
 

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only
- Mobile (Without Loaded Avatar Image)

https://github.com/user-attachments/assets/480e7a61-9831-468d-84b4-4742cb3b48ba

- Mobile (With Loaded Avatar Image)

https://github.com/user-attachments/assets/84c576b0-ea33-494a-90e4-488b0884f43d
 
- Tablet

https://github.com/user-attachments/assets/d5d61275-b487-4a99-aac5-329c11d2e4ab

 - Failing tests (without Fix)
 
Screenshot from 2026-03-09 17-48-21

Screenshot from 2026-03-09 17-48-31

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- For PRs introducing new UI elements or color changes, both light and dark mode screenshots must be included
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### CODE REVIEW

**Comment by itsadityaaaaa** [comment]
@BenHenning Thanks for your guidance and feedback.

I am Sorry that I had to close my previous PR due to merge conflicts with the branch. This PR will continue the work and discussion from the previous one [https://github.com/oppia/oppia-android/pull/6063](https://github.com/oppia/oppia-android/pull/6063)

I am also attaching my debug doc here [https://docs.google.com/document/d/1CkVmUMNSJeCQ0mXIPxIedZRqGKKeBSwx3FERdsn2iy0/edit?usp=sharing](https://docs.google.com/document/d/1CkVmUMNSJeCQ0mXIPxIedZRqGKKeBSwx3FERdsn2iy0/edit?usp=sharing)

Root Cause Analysis:
The flicker (specifically the color swap between profile avatars) is caused by two layers of deferred/async rendering during notifyDataSetChanged():

1. Data-binding defers updates to the next frame
2. Glide's async pipeline for local drawables

Additionally, I am including links to all the open review threads from the previous PR for reference.
1. Thread 1 - [https://github.com/oppia/oppia-android/pull/6063#discussion_r2881278256](https://github.com/oppia/oppia-android/pull/6063#discussion_r2881278256)
2. Thread 2 - [https://github.com/oppia/oppia-android/pull/6063#discussion_r2881279053](https://github.com/oppia/oppia-android/pull/6063#discussion_r2881279053)
3. Thread 3 - [https://github.com/oppia/oppia-android/pull/6063#discussion_r2881280703](https://github.com/oppia/oppia-android/pull/6063#discussion_r2881280703)
4. Thread 4 - [https://github.com/oppia/oppia-android/pull/6063#discussion_r2881281819](https://github.com/oppia/oppia-android/pull/6063#discussion_r2881281819)
5. Thread 5 - [https://github.com/oppia/oppia-android/pull/6063#discussion_r2881284299](https://github.com/oppia/oppia-android/pull/6063#discussion_r2881284299)
6. Thread 6 - [https://github.com/oppia/oppia-android/pull/6063#discussion_r2881284914](https://github.com/oppia/oppia-android/pull/6063#discussion_r2881284914)

Other than that, please re-run the CI build. If it fails, please note that I have built the app locally and did not encounter any errors.

File: app/src/sharedTest/java/org/oppia/android/app/databinding/ImageViewBindingAdaptersTest.kt [hunk 1]
```diff
@@ -194,6 +258,23 @@ class ImageViewBindingAdaptersTest {
     }
   }
 
+  private fun withColorFilter(
+    color: Int,
+    mode: PorterDuff.Mode
+  ): TypeSafeMatcher<View> {
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/databinding/ImageViewBindingAdaptersTest.kt]: Is it possible to do the check without a matcher? They're a bit heavy-handed since they require specific setup that ought to be tested directly, so if it's possible to somewhat easily just pull the properties to check directly from the view then that's probably cleaner in this case.

File: app/src/sharedTest/java/org/oppia/android/app/databinding/ImageViewBindingAdaptersTest.kt [hunk 2]
```diff
@@ -174,6 +181,63 @@ class ImageViewBindingAdaptersTest {
     }
   }
 
+  @Test
+  fun testSetProfileImage_nullAvatar_doesNotCrash() {
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/databinding/ImageViewBindingAdaptersTest.kt:183]: Do any of these tests fail without the fixes in place? It seems worth adding a screenshot showing that there are tests which for sure fail without the fix (as proof that they can catch the issue if it recurs in this way).

**Review by BenHenning — COMMENTED** [review]
Thanks @itsadityaaaaa. Took another pass.

File: app/src/sharedTest/java/org/oppia/android/app/databinding/ImageViewBindingAdaptersTest.kt (hunk 1 above)
Comment (itsadityaaaaa) [reply app/src/sharedTest/java/org/oppia/android/app/databinding/ImageViewBindingAdaptersTest.kt]: @BenHenning  I have updated the tests, Please take a look

File: app/src/sharedTest/java/org/oppia/android/app/databinding/ImageViewBindingAdaptersTest.kt (hunk 2 above)
Comment (itsadityaaaaa) [reply app/src/sharedTest/java/org/oppia/android/app/databinding/ImageViewBindingAdaptersTest.kt:183]: @BenHenning There were 3 tests that were failing without the fix, I have added the screenshot please take a look.

**Comment by itsadityaaaaa** [comment]
Ready for review (Commenting to remove the stale tag)

**Comment by BenHenning** [comment]
Apologies--hoping to look at this tomorrow.

File: app/src/main/java/org/oppia/android/app/recyclerview/BindableAdapter.kt [hunk 3]
```diff
@@ -211,6 +211,7 @@ class BindableAdapter<T : Any> internal constructor(
             // Attaching lifecycleOwner before view model initialization can sometimes cause a
             // NullPointerException because data might not be attached to the views yet.
             binding.lifecycleOwner = lifecycleOwner
+            binding.executePendingBindings()
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/recyclerview/BindableAdapter.kt]: Unfortunately this is blocked on #6126 getting merged--we need to be careful not to overlap the two since there's additional testing and broader considerations needed before this change can be made (which are being done in #6126).

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @itsadityaaaaa! The PR LGTM, but we need to wait for #6126 to be merged, then this PR will need to be updated with its `BindableAdapter` changes reverted and the fixed issue double checked before it can be merged.

File: app/src/main/java/org/oppia/android/app/recyclerview/BindableAdapter.kt (hunk 3 above)
Comment (itsadityaaaaa) [reply app/src/main/java/org/oppia/android/app/recyclerview/BindableAdapter.kt]: @BenHenning Thanks for the review. Waiting for any further response on #6126

**Comment by itsadityaaaaa** [comment]
@BenHenning #6126 is merged, after pulling the changes I found out the issue still exists without fixing (ImageViewBindingAdapters.java) , I tested it without `binding.executePendingBindings() `  and its working as well as the test is also failing without my fix in (ImageViewBindingAdapters.java). Please take a look.

**Review by BenHenning — APPROVED** [review]
Thanks @itsadityaaaaa for waiting and double checking after #6126 was merged. It's great that this fix is still needed as it stands. Approving and enabling auto-merge. I've restarted the build workflows since they should pass (I think they failed due to some CI flakiness).
