### PR TITLE
Fix #2940: Fix chapter lesson blurring for SVG thumbnails

### LINKED ISSUE #2940: Locked lesson thumbnails don't blur when loaded as SVGs
It seems that when loading real SVG thumbnails, the lock icon appears correct for chapters that can't yet be played, but the blur doesn't work (presumably because the blur transformation is a BitmapTransformation).

### PR DESCRIPTION
**Pull request by BenHenning**
Fix #2940

Adds support for blurring SVG images. The main issue is that our previous transformation is a ``BitmapTransformation``, and those don't apply to SVGs. This actually took me some time to figure out (https://github.com/bumptech/glide/issues/2631#issuecomment-803228591 was one of my braindumps). Glide does have support for attaching custom transformations to custom types (such as our ``ScalableVectorGraphic`` class). Beyond that, I couldn't find a good way to blur the SVG, so I added a pathway to prerender the SVG to a bitmap and then blur that. Not only does this consolidate our blurring to one routine (which adds consistency), it also is likely more performant to render bitmaps than SVGs. I might add bitmap pre-rendering for all SVGs since sometimes the picture rendering fails, and bitmap rendering seems more reliable.

Testing is tricky here. We ideally need Glide testing to verify upstream that the drawable is created & arranged correctly (tracked by #1523), and we need screenshot testing to verify visual correctness especially for blurring (#1815). I'm not clear on what else I can test--if anyone has ideas, please let me know.

In order to test this locally, you'll need to download the alpha assets locally. This is a bit tricky to do, so please follow up with me if you want to verify locally. Otherwise, you can verify this is correct via the alpha test binary after all of the alpha PRs are merged in.

One side change: I updated the bitmap transformation to correctly use a message digest/equals/hashCode as recommended by Glide documentation: https://bumptech.github.io/glide/doc/transformations.html#required-methods. From my understanding, the previous implementation is unlikely to run into any issues but the changes make the transformation more correct per documentation.

Screenshot of blurring with SVG:

image

### CODE REVIEW

**Comment by rt4914** [comment]
@BenHenning For this can you mention the steps to load the alpha content so that I can check on that.

**Comment by BenHenning** [comment]
A bug I found while testing with production alpha: sometimes images won't load in the list (& will either white out or just be the filled color). This seems to only affect the story list, and sometimes they appear after scrolling & waiting and other times they don't (even with app restart). It seems like something is failing when converting to bitmap & it never recovers.

**Comment by rt4914** [comment]
@BenHenning Does this PR still needs a review?

**Comment by BenHenning** [comment]
Yup @rt4914, but it looks like no codeowners reviews are necessary. I'll ask @viktoriias to review since she introduced the original blurring code, and you since you're reviewing #2981 and that's introducing most of the SVG stuff used here.

**Comment by BenHenning** [comment]
@rt4914 & @viktoriias PTAL.

File: utility/src/main/java/org/oppia/android/util/parser/BitmapBlurrer.kt [hunk 1]
```diff
@@ -6,52 +6,48 @@ import android.renderscript.Allocation
...
- * The following [tutorial](https://futurestud.io/tutorials/glide-custom-transformation)
- * was used as a reference, as well as this [article](https://stackoverflow.com/a/23119957).
+ * The radius of the blur, a float between 0 and 25. It defines the value of the standard deviation
+ * to the Gaussian function.
  */
-class BlurTransformation(private val context: Context) : BitmapTransformation() {
+private const val BLUR_RADIUS = 20f
 
+/** Utility used to blur [Bitmap]s. */
+internal class BitmapBlurrer(private val context: Context) {
```
Comment (rt4914) [inline utility/src/main/java/org/oppia/android/util/parser/BitmapBlurrer.kt:17]: Though this class name makes sense to me but reading it sounds a bit awkward.

**Review by rt4914 — APPROVED** [review]
LGTM.

**Comment by viktoriias** [comment]
LGTM

**Review by viktoriias — APPROVED** [review]

File: utility/src/main/java/org/oppia/android/util/parser/BitmapBlurrer.kt (hunk 1 above)
Comment (BenHenning) [reply utility/src/main/java/org/oppia/android/util/parser/BitmapBlurrer.kt:17]: Might be because 'blurrer' isn't a word. :) Any suggestions for alternative names?

Comment (rt4914) [reply utility/src/main/java/org/oppia/android/util/parser/BitmapBlurrer.kt:17]: `BitmapBlurEffect` , `BitmapBlurImpl` ?

Comment (BenHenning) [reply utility/src/main/java/org/oppia/android/util/parser/BitmapBlurrer.kt:17]: 'Impl' doesn't really fit since it's not implementing an interface/API. 'BlurEffect' is a bit off, too, since 'effect' actually means something in Android and this isn't that (https://developer.android.com/reference/android/media/effect/Effect).

I think I'll keep this now (for time), but if you have additional thoughts I'm happy to discuss.

**Comment by BenHenning** [comment]
Looks like the Gradle failure is due to the uncommon LogUploadWorkerTest flake being tracked by #2032.

**Comment by BenHenning** [comment]
Thanks for the reviews!

See https://github.com/oppia/oppia-android/pull/2980#issuecomment-825478246 for context on why I'm both enabling auto-merge and cancelling the Bazel test CI run.

Note also that the code reviewer request above isn't right--it was a temporary request due to the base branch changing without the branch itself being updated to be properly based on develop post the squash merge of #2983.

**Comment by BenHenning** [comment]
Hmm. CI isn't triggering for some reason. Closing & reopening PR to see if that triggers it.

**Comment by BenHenning** [comment]
Note that I do plan on letting the full CI checks run on develop now that this & the previous 4 PRs have been merged.
