### PR TITLE
Fix #1930: "Tick icon" disappears on configuration change in QuestionPlayer 

### LINKED ISSUE #1930: "Tick icon" disappears on configuration change in QuestionPlayer
**Describe the bug**
"Tick icon" disappears on configuration change in QuestionPlayer

**To Reproduce**
1. Go to 'HomeScreen'
2. Scroll to 'Fractions Topic' and click on it
3. Go to 'Practice'
4. Check any checkbox and click start
5. Choose the correct answer for any question
6. Rotate the screen and notice that the "tick icon" disappeared

**Expected behavior**
The "tick icon" should stay visible for the correct answer

### PR DESCRIPTION
**Pull request by MaskedCarrot**
## Explanation

Fixes #1930 
## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

https://user-images.githubusercontent.com/53645584/103134815-f3f99600-46d9-11eb-9ba4-a0d2701f4cd8.mp4

## Tests
Roboelectric | Espresso
-- | --
Screenshot from 2021-01-16 20-30-14 | Screenshot from 2021-01-16 20-27-18

### CODE REVIEW

**Comment by MaskedCarrot** [comment]
@BenHenning Please take a look. I have tried to use the approach you suggested.

**Comment by MaskedCarrot** [comment]
> 
> 
> ## Explanation
> 
> Fixes #1930 
> ## Checklist
> 
> - [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
> - [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
> - [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
> - [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
> - [x] The PR is made from a branch that's **not** called "develop".
> - [x] The PR is made from a branch that is up-to-date with "develop".
> - [x] The PR's branch is based on "develop" and not on any other branch.
> - [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.
> 
> 
>
video
> 
> 
> ## Tests
> Roboelectric | Espresso
> -- | --
> Screenshot from 2021-01-16 20-30-14 | Screenshot from 2021-01-16 20-27-18
> 
> 
> 
> 
>

**Review by rt4914 — APPROVED** [review]
LGTM, all the tests are passing.
Screenshot 2021-01-19 at 2 00 56 PM

File: app/src/main/java/org/oppia/android/app/player/state/StatePlayerRecyclerViewAssembler.kt [hunk 1]
```diff
@@ -228,6 +228,7 @@ class StatePlayerRecyclerViewAssembler private constructor(
         )
       }
     } else if (ephemeralState.stateTypeCase == EphemeralState.StateTypeCase.COMPLETED_STATE) {
+      isCorrectAnswer.set(true)
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/player/state/StatePlayerRecyclerViewAssembler.kt:233]: Please add a brief comment here explaining this for future readers (e.g. something like "Ensure the answer is marked in situations where that's guaranteed (e.g. completed state) so that the UI always has the correct answer indication, even after configuration changes." or similar).

This helps provide context for others since otherwise this seems almost random despite it having very specific intention.

**Review by BenHenning — COMMENTED** [review]
Thanks @MaskedCarrot! I like how simple the PR got in the end. Just had one comment--PTAL.

File: app/src/main/java/org/oppia/android/app/player/state/StatePlayerRecyclerViewAssembler.kt (hunk 1 above)
Comment (MaskedCarrot) [reply app/src/main/java/org/oppia/android/app/player/state/StatePlayerRecyclerViewAssembler.kt:233]: done

**Review by BenHenning — APPROVED** [review]
Thanks @MaskedCarrot! LGTM!
