### PR TITLE
Fix #2967 Refactor packages for services

### LINKED ISSUE #2967: Refactor package structure for service tests & mocked services
**Describe the bug**
Mock services cannot be used in other tests since they are created in a testing package in the data module. Additionally, the tests for the services are improperly named without "service".
For example, the test for the topic service `MockTopicTest` uses the `MockTopicService` in the same module. It should  instead be named `TopicServiceTest` using the `MockTopicService` provided in our testing module.

**Expected behavior**
We want to be able to use the mocked services in other module (e.g. the domain module).

**Additional context**
The mock services will be moved to the testing module in a non-test package. The tests will be renamed `Mock_____Service` to reflect what it's testing: remote service, using a mocked service.

### PR DESCRIPTION
**Pull request by jcqli**
## Explanation
Fix #2967
Refactors the package structure so that the mock services are in the testing module, enabling them to be used in other modules -- all mocked services are now in a `testing.network` package.
Renames the affiliated tests form `Mock___Test` to `___ServiceTest` to better reflect that they test the service using the mock services.

This PR also makes changes to the feedback reporting JSON so that the service tests pass.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [ ] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [ ] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by jcqli** [comment]
FYI -- this is currently blocked due to [this bazel error](https://gist.github.com/jcqli/ccd99ac5c655c98de1f8b174dd1bcbb4) that I can also repro on the develop branch (just running `bazel build //:oppia`)

EDIT: This was a local error :) Resolved!

File: testing/src/main/java/org/oppia/android/testing/ApiUtils.kt [hunk 1]
```diff
@@ -1,4 +1,4 @@
-package org.oppia.android.data.backends
+package org.oppia.android.testing
```
Comment (BenHenning) [inline testing/src/main/java/org/oppia/android/testing/ApiUtils.kt]: Hmm maybe something like ``testing/network`` would be a clearer place for this--WDYT?

**Review by BenHenning — COMMENTED** [review]
Nice cleanup--thanks @jcqli! Just had one comment. PTAL.

File: testing/src/main/java/org/oppia/android/testing/ApiUtils.kt (hunk 1 above)
Comment (jcqli) [reply testing/src/main/java/org/oppia/android/testing/ApiUtils.kt]: Makes sense -- I wasn't sure if this would be limited to the network services or if it could be used elsewhere but that change be made if we ever end up doing that.

Done

**Review by BenHenning — APPROVED** [review]
Thanks @jcqli! LGTM.

**Comment by BenHenning** [comment]
FYI this broke Bazel tests: #3018.
