### PR TITLE
Fix #5431 :  Todo Checks Should Check Exclusively Against Issues

### LINKED ISSUE #5431: [BUG]: Todo Checks Should Check Exclusively Against Issues
### Describe the bug

Currently, when to-do open checks run on CI, they check for both open issues and open PRs. This behaviour should be improved to limit the checks to issues only. 

### Steps To Reproduce

Run the to-do open checks with a TODO comment that points to a PR. The check will pass incorrectly.

### Expected Behavior

I expect the to-do checks to fail if a todo points to a PR instead of an open issue.

### Screenshots/Videos

N/A

### What device/emulator are you using?

_No response_

### Which Android version is your device/emulator running?

_No response_

### Which version of the Oppia Android app are you using?

_No response_

### Additional Context

This issue was discovered when [#5240](https://github.com/oppia/oppia-android/pull/5240) was merged. The PR had a TODO that pointed to the PR's number(5240) instead of an issue number. While the PR was open, all checks were passing. However, once the PR was merged and closed, the checks could not pass since the PR was no longer open and could not be referenced against the check.

### PR DESCRIPTION
**Pull request by subhajitxyz**
## Explanation

Fix #5431
This pull request fixes issue by implementing the following changes:

Filters out pull requests from the "open issues" list.
Ensures all "To-Do" checks will pass only for open issues (not for prs).

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- For PRs introducing new UI elements or color changes, both light and dark mode screenshots must be included
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### CODE REVIEW

**Comment by subhajitxyz** [comment]
PTAL , @adhiamboperes .

File: scripts/src/java/org/oppia/android/scripts/common/remote/GitHubService.kt [hunk 1]
```diff
@@ -29,7 +29,7 @@ interface GitHubService {
    * @return the list of [GitHubIssue]s read from the remote repository (as a [Call])
    */
   @Headers("Accept: application/vnd.github+json", "X-GitHub-Api-Version: 2022-11-28")
-  @GET("repos/{repo_owner}/{repo_name}/issues?direction=asc")
+  @GET("repos/{repo_owner}/{repo_name}/issues?direction=asc&pulls=false")
```
Comment (adhiamboperes) [inline scripts/src/java/org/oppia/android/scripts/common/remote/GitHubService.kt]: Why not add the `pulls` as a query parameter? I think it is cleaner that way and will allow you to add tests in the corresponding test files. 

API ref: https://docs.github.com/en/rest/issues/issues?apiVersion=2022-11-28

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @subhajitxyz! PTAL at my comment inline.

File: scripts/src/java/org/oppia/android/scripts/common/remote/GitHubService.kt (hunk 1 above)
Comment (subhajitxyz) [reply scripts/src/java/org/oppia/android/scripts/common/remote/GitHubService.kt]: As per doc , pulls  as Parameters work  for "List organization issues assigned to the authenticated user"

So, i have added new code , where i have filtered out pulls using pull_request key.

**Comment by subhajitxyz** [comment]
PTAL, @adhiamboperes .

File: scripts/src/java/org/oppia/android/scripts/common/GitHubClient.kt [hunk 2]
```diff
@@ -68,13 +68,14 @@ class GitHubClient(
...
       val response = withContext(Dispatchers.IO) { call.execute() }
+
       check(response.isSuccessful()) {
         "Failed to fetch issues at page $pageNumber: ${response.code()}\n${call.request()}" +
           "\n${response.errorBody()}."
       }
       return@async checkNotNull(response.body()) {
         "No issues response from GitHub for page: $pageNumber."
-      }
+      }.filter { it.pullRequest == null }
```
Comment (adhiamboperes) [inline scripts/src/java/org/oppia/android/scripts/common/GitHubClient.kt:78]: What does this mean?

**Review by adhiamboperes — COMMENTED** [review]
@subhajitxyz, just had one clarification. PTAL.

File: scripts/src/java/org/oppia/android/scripts/common/GitHubClient.kt (hunk 2 above)
Comment (subhajitxyz) [reply scripts/src/java/org/oppia/android/scripts/common/GitHubClient.kt:78]: The line .filter { it.pullRequest == null } is applying a filter to the list of issues returned in the response.body() so that only issues that are not pull requests are included in the final list.

**Comment by subhajitxyz** [comment]
@adhiamboperes , PTAL.

File: scripts/src/java/org/oppia/android/scripts/common/GitHubClient.kt (hunk 2 above)
Comment (adhiamboperes) [reply scripts/src/java/org/oppia/android/scripts/common/GitHubClient.kt:78]: Sounds good.

**Review by adhiamboperes — APPROVED** [review]
Thanks @subhajitxyz. This generally looks good to me.

**Comment by adhiamboperes** [comment]
@subhajitxyz, could you please update the PR description with an overview of your fix, then sync with develop.

**Comment by subhajitxyz** [comment]
Done.
