### PR TITLE
Fixes #4272: Added remaining tests for EventLogSubject.

### LINKED ISSUE #4272: Add tests for EventLogSubject
#4267 introduces a new custom Truth test subject: EventLogSubject. It would be advantageous to add thorough tests for this to ensure that:
- Each of the subject & comparator methods correctly allow users to test specific properties of the protos each subject helps verify
- Each of the subject & comparator methods are verified to fail when expected (i.e. when used with an incompatible proto property) with the correct failure reason being verified

See #4097 for a similar issue.

## Pending testcases:

For context tests, we should test for 4 outcomes:
1. The context being present and matching
 `testEventLog_whenContextIsInfoTab_passes` using `EventLogSubject.assertThat(eventLog).hasOpenInfoTabContext()`

2. Subject has context with ceratin properties
`_returnsTopicContextSubject`  

```kotlin
 val eventLog = EventLog.newBuilder()
    .setContext(
      EventLog.Context.newBuilder()
        .setOpenInfoTab(
          TopicContext.newBuilder().setTopicId("info_tab_topic")
        )
    )
    .build()

  val subject = EventLogSubject.assertThat(eventLog)
    .hasOpenInfoTabContextThat()

subject.hasTopicIdThat().isEqualTo("info_tab_topic")
```

3. Subject has context with ceratin properties, and executes a block.
`_executesBlockWithCorrectSubject`

  ```kotlin
val eventLog = EventLog.newBuilder()
    .setContext(
      EventLog.Context.newBuilder()
        .setOpenInfoTab(TopicContext.newBuilder().setTopicId("test_topic"))
    )
    .build()

  EventLogSubject.assertThat(eventLog)
    .hasOpenInfoTabContextThat {
      hasTopicIdThat().isEqualTo("test_topic")
    }
```
4. A failure case when  the subject under test does not match the input.

These are necessary because every context subject has these 3 functions, and this will increase the code coverage of the class. 

(1) and (4) have already been covered in #5678

### PR DESCRIPTION
**Pull request by theayushyadav11**
Fixes #4272.
This PR contains all the remaining tests for the the file EventLogSubject in [testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt](testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt) which resulted in 100% code coverage.

### Screenshot of the passing tests:
Screenshot from 2025-04-20 17-00-31

### Code Coverage 100%
Screenshot from 2025-04-20 17-00-17

 
## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

### CODE REVIEW

**Comment by theayushyadav11** [comment]
PTAL @adhiamboperes .

**Comment by theayushyadav11** [comment]
Hi @adhiamboperes , this pr is ready for review PTAL whenever you get a moment.
Thanks

File: testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt [hunk 1]
```diff
@@ -332,6 +515,44 @@ class EventLogSubjectTest {
...
+      .setContext(
+        EventLog.Context.newBuilder()
+          .setOpenRevisionTab(topicContext)
+      )
+      .build()
+
+    val subject = EventLogSubject.assertThat(eventLog)
+      .hasOpenRevisionTabContextThat()
+
+    subject.hasTopicIdThat().isEqualTo("topicId")
```
Comment (adhiamboperes) [inline testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt]: The test outcome here is different from what the test name says it should be, PTAL.

File: testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt [hunk 2]
```diff
@@ -309,6 +454,44 @@ class EventLogSubjectTest {
...
+      .setContext(
+        EventLog.Context.newBuilder()
+          .setOpenPracticeTab(topicContext)
+      )
+      .build()
+
+    val subject = EventLogSubject.assertThat(eventLog)
+      .hasOpenPracticeTabContextThat()
+
+    subject.hasTopicIdThat().isEqualTo("topicId")
```
Comment (adhiamboperes) [inline testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt]: Why is this not:
```suggestion
    assertThat(eventLog)
      .hasOpenPracticeTabContextThat()
```
?

Either way, pleas update the test name to match the assertion.

File: testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt [hunk 3]
```diff
@@ -270,6 +292,43 @@ class EventLogSubjectTest {
...
+    val eventLog = EventLog.newBuilder()
+      .setContext(
+        EventLog.Context.newBuilder()
+          .setOpenExplorationActivity(explorationContext)
+      )
+      .build()
+
+    val subject = EventLogSubject.assertThat(eventLog)
+      .hasOpenExplorationActivityContextThat()
+    subject.hasExplorationIdThat().isEqualTo("explorationId")
```
Comment (adhiamboperes) [inline testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt]:
```suggestion
  assertThat(eventLog).hasOpenExplorationActivityContextThat().hasExplorationIdThat().isEqualTo("explorationId")
```

File: testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt [hunk 4]
```diff
@@ -283,6 +342,54 @@ class EventLogSubjectTest {
...
+      .setContext(
+        EventLog.Context.newBuilder()
+          .setOpenInfoTab(topicContext)
+      )
+      .build()
+
+    val subject = EventLogSubject.assertThat(eventLog)
+      .hasOpenInfoTabContextThat()
+
+    subject.hasTopicIdThat().isEqualTo("topicId")
```
Comment (adhiamboperes) [inline testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt]: For every test, make sure that the last statement is the assertion block, per my suggestion above.

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @theayushyadav11! It is really nice to see such a huge file reach 100% coverage.

I have however left some suggestions on fixing the test assertions. Please apply them to all the tests in this PR.

File: testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt (hunk 1 above)
Comment (theayushyadav11) [reply testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt]: There is a just extra check that after returning verifies some properties.

File: testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt (hunk 4 above)
Comment (theayushyadav11) [reply testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt]: Updated.

File: testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt (hunk 3 above)
Comment (theayushyadav11) [reply testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt]: updated.

File: testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt (hunk 2 above)
Comment (theayushyadav11) [reply testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt]: updated.

**Comment by theayushyadav11** [comment]
PTAL @adhiamboperes .

**Review by adhiamboperes — APPROVED** [review]
This LGTM, thanks @theayushyadav11!

**Comment by adhiamboperes** [comment]
Updating branch and enabling auto-merge
