### PR TITLE
Fix #6042 Drawer highlight issue

### LINKED ISSUE #6042: [BUG]: Drawer menu higllights do not update on back navigation
### Describe the bug

When a drawer menu item like the "Administrator Controls" option is selected, it gets higlighted. Unfortunately, when the back button is pressed(such that the user goes to a different screen, e.g. home), the highlight is not removed.

### Steps To Reproduce

1. Open the app and navigate to any screen containing the drawer menu, e.g. Home.
2. Open the drawer.
3. Tap a menu item that navigates to a new screen (e.g., Administrator Controls).
4. Observe that the selected menu item becomes highlighted.
5. Press the device back button to return to a different screen (e.g., Home).
6. See that the previously selected drawer item remains highlighted instead of clearing when leaving that screen.

### Expected Behavior

The menu item should no longer be highlighted when the associated screen has been navigated away from.

### Screenshots/Videos

_No response_

### What device/emulator are you using?

_No response_

### Which Android version is your device/emulator running?

_No response_

### Which version of the Oppia Android app are you using?

0.17-beta

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by itsadityaaaaa**
## Explanation
 - "Fixes #6042 " in the explanation so that GitHub can auto-close the issue
  - Fix menu item should no longer be highlighted when the associated screen has been navigated away from.
 

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #6042 " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only
- Tablet

https://github.com/user-attachments/assets/c2fd671c-bd5c-48ff-a928-4c1224a8ff15

- Mobile 

https://github.com/user-attachments/assets/bc97c496-644d-487f-ae54-7cdae2b47937

- Affected Espresso Tests Result
Screenshot from 2025-12-28 21-45-52

Screenshot from 2025-12-28 21-44-13

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- For PRs introducing new UI elements or color changes, both light and dark mode screenshots must be included
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### CODE REVIEW

**Comment by itsadityaaaaa** [comment]
@adhiamboperes I  think this CI failure appears unrelated to this PR.
Build is failing during Bazel dependency fetch before tests execute.
This looks like an  CI/dependency issue.

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @itsadityaaaaa!

There are a few things to clarify/improve:
1. Part of the PR description reads: "Removed dependency on menu ordering, preventing issues when menu structure changes." However, I see no code that points to this. Could you please elaborate?
2. The [NavigationDrawerFragment.kt](https://github.com/oppia/oppia-android/pull/6045/files#diff-3c9086737f2c3702808a5178337cf02d02dbccc3d718caafcac291449f0aa181) is covered via `NavigationDrawerActivityDebugTest` and `NavigationDrawerActivityProdTest`.  Please add tests for verifying the changes introduced. If you need support on a way forward, please let us know.
3. The video demos show menu highlight for the options items, but it is important to show that this is fixed for the footer items as weel, i.e. the admin controls and developer options items.
4. The PR title and the start of the explanation are missing a reference to "fix #issueNumber", which are used to automate closing the issue once the PR is merged. Please add these.

**Comment by itsadityaaaaa** [comment]
@adhiamboperes Thank You! for your suggestions, will work on it and get back to you if need any help

**Comment by itsadityaaaaa** [comment]
@adhiamboperes I did changes according to the suggestion, please review the modification and tell me any other modifications are required.

**Comment by itsadityaaaaa** [comment]
PR is ready for review (Commenting to remove the Stale tag.)

**Comment by itsadityaaaaa** [comment]
@adhiamboperes Please review the PR, is anything else required ?

File: app/src/main/java/org/oppia/android/app/drawer/NavigationDrawerFragmentPresenter.kt [hunk 1]
```diff
@@ -473,7 +473,24 @@ class NavigationDrawerFragmentPresenter @Inject constructor(
       }
     }
   }
-
+  fun updateDrawerHighlights() {
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/drawer/NavigationDrawerFragmentPresenter.kt:477]: Please insert a new line between functions for formatting consistency.

File: app/src/main/java/org/oppia/android/app/drawer/NavigationDrawerFragmentPresenter.kt [hunk 2]
```diff
@@ -473,7 +473,24 @@ class NavigationDrawerFragmentPresenter @Inject constructor(
...
+        binding.fragmentDrawerNavView.menu
+          .findItem(itemId)
+          ?.isChecked = true
+      } else if (itemId == 0) {
+        footerViewModel.isAdministratorControlsSelected.set(true)
+        uncheckAllMenuItemsWhenAdministratorControlsOrDeveloperOptionsIsSelected()
+      } else if (itemId == -1) {
+        footerViewModel.isDeveloperOptionsSelected.set(true)
+        uncheckAllMenuItemsWhenAdministratorControlsOrDeveloperOptionsIsSelected()
+      }
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/drawer/NavigationDrawerFragmentPresenter.kt]: In Kotlin, the standard is to use a when block as opposed to a nested if. But the rest of the logic looks good.

File: app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerActivityDebugTest.kt [hunk 3]
```diff
@@ -231,7 +231,37 @@ class NavigationDrawerActivityDebugTest {
       )
     }
   }
+  @RunOn(TestPlatform.ESPRESSO)
```
Comment (adhiamboperes) [inline app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerActivityDebugTest.kt:236]: Please add the "// TODO(#2535): Unable to open NavigationDrawer multiple times on Robolectric" instructions so these new tests are not missed during a future refactor.


Also, please add a newline before this test.

File: app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerActivityProdTest.kt [hunk 4]
```diff
@@ -728,7 +728,37 @@ class NavigationDrawerActivityProdTest {
...
+    ).use {
+      it.openNavigationDrawer()
+      onView(withText(R.string.menu_options)).perform(click())
+      onView(isRoot()).perform(pressBack())
+      it.openNavigationDrawer()
+      onView(isRoot()).perform(orientationLandscape())
+      onView(withId(R.id.fragment_drawer_nav_view))
+        .check(matches(checkNavigationViewItemStatus(NavigationDrawerItem.HOME)))
+    }
+  }
```
Comment (adhiamboperes) [inline app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerActivityProdTest.kt:764]: Please add newlines between tests for formatting consistency.

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @itsadityaaaaa for this PR! The solution looks good, but I have suggested some improvements. PTAL.

Apologies for the delay in review!

**Comment by itsadityaaaaa** [comment]
@adhiamboperes I have implemented the suggested changes, please take a look. Looking forward for your review

**Review by adhiamboperes — APPROVED** [review]
LGTM, thanks @itsadityaaaaa!

**Comment by adhiamboperes** [comment]
@itsadityaaaaa, have you had the chance to fill the form above?

**Comment by itsadityaaaaa** [comment]
@adhiamboperes I had already fill the form, If the team didn't got the response should I have to fill it again?

**Comment by adhiamboperes** [comment]
@itsadityaaaaa, something might have happened and we didn't receive your submission. Could you please ensure that when you click the link, the form title is "Becoming an Oppia collaborator".

**Comment by adhiamboperes** [comment]
@itsadityaaaaa, apologies, I have seen your response -- no need to fill the form again. Thanks!

**Comment by itsadityaaaaa** [comment]
@adhiamboperes Thanks!  for the update.
