### PR TITLE
Fix #1106: Addition of Work Manager for uploading logs

### LINKED ISSUE #1106: Addition of Work Manager [GSoC'20][Milestone 3]
Addition of Work manager (and tests) will enable us to upload the stored crash reports and event logs [for analytics] when there is presence of network connectivity.

### PR DESCRIPTION
**Pull request by Sarthak2601**
## Explanation

Fixes #1106 - Implements work manager for uploading events and exceptions to Firebase in presence of network connection. 

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

File: domain/src/main/java/org/oppia/domain/oppialogger/OppiaLogUploadWorker.kt [hunk 1]
```diff
@@ -0,0 +1,81 @@
...
+      val exceptionLogs = exceptionStore.value?.getOrThrow()?.exceptionLogList
+      exceptionLogs?.let {
+        for (exceptionLog in it) {
+          exceptionLogger.logException(exceptionLog.toException())
+          it.remove(exceptionLog)
+        }
+      }
+      Result.success()
+    } catch (e: Exception) {
+      e.printStackTrace()
```
Comment (vinitamurthi) [inline domain/src/main/java/org/oppia/domain/oppialogger/OppiaLogUploadWorker.kt]: Please use the console logger here

File: domain/src/main/java/org/oppia/domain/oppialogger/OppiaLogUploadWorker.kt [hunk 2]
```diff
@@ -0,0 +1,81 @@
...
+      val eventLogs = eventStore.value?.getOrThrow()?.eventLogList
+      eventLogs?.let {
+        for (eventLog in it) {
+          eventLogger.logEvent(eventLog)
+          it.remove(eventLog)
+        }
+      }
+      Result.success()
+    } catch (e: Exception) {
+      e.printStackTrace()
```
Comment (vinitamurthi) [inline domain/src/main/java/org/oppia/domain/oppialogger/OppiaLogUploadWorker.kt]: Ditto

File: domain/src/main/java/org/oppia/domain/oppialogger/OppiaLogUploader.kt [hunk 3]
```diff
@@ -0,0 +1,66 @@
...
+import androidx.work.ExistingPeriodicWorkPolicy
+import androidx.work.NetworkType
+import androidx.work.PeriodicWorkRequest
+import androidx.work.WorkManager
+import java.util.concurrent.TimeUnit
+
+private const val OPPIA_EXCEPTION_WORK = "OPPIA_EXCEPTION_WORK_REQUEST"
+private const val OPPIA_EVENT_WORK = "OPPIA_EVENT_WORK_REQUEST"
+
+class OppiaLogUploader() {
```
Comment (vinitamurthi) [inline domain/src/main/java/org/oppia/domain/oppialogger/OppiaLogUploader.kt]: I am a bit unsure what the purpose of this class is. This is not an uploader since its not doing any uploading. It looks like its only creating the worker requests right? Can we rename this class accordingly?

**Review by vinitamurthi — CHANGES_REQUESTED** [review]
I think you can add tests now

File: domain/src/main/java/org/oppia/domain/oppialogger/OppiaLogUploadWorker.kt (hunk 1 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/OppiaLogUploadWorker.kt]: Done.

File: domain/src/main/java/org/oppia/domain/oppialogger/OppiaLogUploadWorker.kt (hunk 2 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/OppiaLogUploadWorker.kt]: Done.

File: domain/src/main/java/org/oppia/domain/oppialogger/OppiaLogUploader.kt (hunk 3 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/OppiaLogUploader.kt]: Aah, I named it so because the work requests are after all the ones that will start the process of uploading. Changed it to `OppiaLogUploadWorkRequest`, is that fine now ?

**Comment by BenHenning** [comment]
Haven't looked at this in depth yet, but @Sarthak2601 I believe you'll need to add new dependencies to BUILD.bazel files as needed to fix the broken Bazel build. In general, if you need to change a gradle file you'll almost certainly also need to change the corresponding Bazel file for that module. See also: https://docs.google.com/document/d/1V0RMehfi3GLVsZ6dyin1nTo4_TO28LACp4wPlEnvnM0/edit#bookmark=id.lt3lnonhm4zo.

File: app/src/main/java/org/oppia/app/application/OppiaApplication.kt [hunk 4]
```diff
@@ -30,4 +32,8 @@ class OppiaApplication :
     FirebaseApp.initializeApp(applicationContext)
     component.getApplicationStartupListeners().forEach(ApplicationStartupListener::onCreate)
   }
+
+  override fun getWorkManagerConfiguration(): Configuration {
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/app/application/OppiaApplication.kt:38]: This should be done via modules not directly in components.

File: domain/build.gradle [hunk 5]
```diff
@@ -68,6 +70,9 @@ dependencies {
       'org.robolectric:robolectric:4.3',
       project(":testing"),
   )
+  androidTestImplementation(
```
Comment (BenHenning) [inline domain/build.gradle]: We don’t use instrumentation tests for domain layer tests.

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkRequest.kt [hunk 6]
```diff
@@ -0,0 +1,80 @@
...
+/** Enqueues unique periodic work requests for uploading events and exceptions to the remote service on application creation. */
+@Singleton
+class LogUploadWorkRequest @Inject constructor(
+  private val context: Context
+) : ApplicationStartupListener {
+
+  private val workerConstraints = Constraints.Builder()
+    .setRequiredNetworkType(NetworkType.CONNECTED)
+    .setRequiresBatteryNotLow(true)
+    .setRequiresStorageNotLow(true)
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkRequest.kt]: Why this constraint? Won’t this prevent uploading logs in cases when storage is low and could be freed by uploading logs?

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkRequest.kt [hunk 7]
```diff
@@ -0,0 +1,80 @@
...
+private const val OPPIA_EXCEPTION_WORK = "OPPIA_EXCEPTION_WORK_REQUEST"
+private const val OPPIA_EVENT_WORK = "OPPIA_EVENT_WORK_REQUEST"
+
+/** Enqueues unique periodic work requests for uploading events and exceptions to the remote service on application creation. */
+@Singleton
+class LogUploadWorkRequest @Inject constructor(
+  private val context: Context
+) : ApplicationStartupListener {
+
+  private val workerConstraints = Constraints.Builder()
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkRequest.kt]: Please add tests to ensure these constraints don’t change accidentally.

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt [hunk 8]
```diff
@@ -0,0 +1,112 @@
...
+import org.oppia.util.logging.ConsoleLogger
+import org.oppia.util.logging.EventLogger
+import org.oppia.util.logging.ExceptionLogger
+import javax.inject.Inject
+import javax.inject.Singleton
+
+const val LOG_UPLOAD_WORKER = "log_upload_worker"
+
+/** [Worker] class that extracts log reports from the cache store and logs them to the remote service. */
+@Singleton
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt]: I wouldn’t expect to be using a singleton injectable class with a factory pattern. Shouldn’t the factory return a new instance for each call?

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkRequest.kt [hunk 9]
```diff
@@ -0,0 +1,80 @@
...
+    enqueueWorkRequestForEvents(workManager)
+    enqueueWorkRequestForExceptions(workManager)
+  }
+
+  /** Enqueues a unique periodic work request for uploading events to the remote service. */
+  private fun enqueueWorkRequestForEvents(workManager: WorkManager) {
+    val workerCase =
+      Data.Builder()
+        .putString(
+          LogUploadWorker.WORKER_CASE_KEY,
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkRequest.kt]: What purpose does this enum to string conversion serve? In general that’s not a great practice since we can’t rely on enum constants to be a particular value (at least in Java).

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt [hunk 10]
```diff
@@ -0,0 +1,112 @@
...
+      }
+      WorkerCase.EXCEPTION_WORKER.toString() -> {
+        exceptionWork()
+      }
+      else -> Result.failure()
+    }
+  }
+
+  /** Extracts exception logs from the cache store and logs them to the remote service. */
+  private fun exceptionWork(): Result {
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt]: Name: method names should be verbs or verb phrases. Please revise. Ditto below.

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt [hunk 11]
```diff
@@ -0,0 +1,112 @@
...
+      consoleLogger.e(LOG_UPLOAD_WORKER, e.toString(), e)
+      Result.failure()
+    }
+  }
+
+  /** Extracts event logs from the cache store and logs them to the remote service. */
+  private fun eventWork(): Result {
+    return try {
+      val eventStore = analyticsController.getEventLogs()
+      val eventLogs = eventStore.value?.getOrThrow()?.eventLogList
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt]: Is this being called on the main thread? If not, we shouldn’t be interacting directly with LiveData like this.

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerModule.kt [hunk 12]
```diff
@@ -0,0 +1,36 @@
...
+@MapKey
+annotation class WorkerKey(val value: KClass<out Worker>)
+
+/** Provides [LogUploadWorker] related dependencies. */
+@Module
+interface LogUploadWorkerModule {
+
+  @Binds
+  @WorkerKey(LogUploadWorker::class)
+  @IntoMap
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerModule.kt]: Why use a map if it only has one element?

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkRequest.kt [hunk 13]
```diff
@@ -0,0 +1,80 @@
...
+import java.util.concurrent.TimeUnit
+import javax.inject.Inject
+import javax.inject.Singleton
+
+private const val OPPIA_EXCEPTION_WORK = "OPPIA_EXCEPTION_WORK_REQUEST"
+private const val OPPIA_EVENT_WORK = "OPPIA_EVENT_WORK_REQUEST"
+
+/** Enqueues unique periodic work requests for uploading events and exceptions to the remote service on application creation. */
+@Singleton
+class LogUploadWorkRequest @Inject constructor(
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkRequest.kt]: Suggest: LogUploadWorkManagerInitializer

The current name confused me slightly—this class isn’t representing a request.

File: domain/src/test/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkRequestTest.kt [hunk 14]
```diff
@@ -0,0 +1,210 @@
...
+    )
+    networkConnectionUtil.setCurrentConnectionStatus(NetworkConnectionUtil.ConnectionStatus.LOCAL)
+
+    logUploadWorkRequest.onCreate()
+    val eventLog = fakeEventLogger.getMostRecentEvent()
+    assertThat(eventLog).isEqualTo(eventLogTopicContext)
+  }
+
+  @Test
+  fun testWorkRequest_logExcepton_withoutNetwork_callOnCreate_verifyLogToRemoteService() {
```
Comment (BenHenning) [inline domain/src/test/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkRequestTest.kt]: This and the above test can’t happen in prod: onCreate will always be called before we can actually log anything. Please update both tests to match.

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @Sarthak2601. Took a first pass.

**Comment by BenHenning** [comment]
Also, I didn’t see any Bazel files updated, just the workspace. Note that the workspace change enables using a dependency, but doesn’t actually use that dependency. You’ll need to update the domain/BUILD.bazel file.

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt (hunk 10 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt]: Done.

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerModule.kt (hunk 12 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerModule.kt]: I did this because in the future we might want to add other workers as well. Like in Sajal's original project, there was a situation where he had to sync the profiles to the Oppia backend.

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkRequest.kt (hunk 13 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkRequest.kt]: Done.

File: domain/src/test/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkRequestTest.kt (hunk 14 above)
Comment (Sarthak2601) [reply domain/src/test/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkRequestTest.kt]: But then there will be previous logs right? Like across different app sessions.

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt (hunk 11 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt]: Okay, was the way of interaction correct in case of the exceptions ? I've modified this to make the two implementations similar. PTAL.

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt (hunk 8 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt]: Yes, you're right. Modified.

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkRequest.kt (hunk 6 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkRequest.kt]: Okay, done.

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkRequest.kt (hunk 7 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkRequest.kt]: Done.

File: app/src/main/java/org/oppia/app/application/OppiaApplication.kt (hunk 4 above)
Comment (Sarthak2601) [reply app/src/main/java/org/oppia/app/application/OppiaApplication.kt:38]: Done.

File: domain/build.gradle (hunk 5 above)
Comment (Sarthak2601) [reply domain/build.gradle]: Removed.

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkRequest.kt (hunk 9 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkRequest.kt]: Okay so the input data for the worker works as a bundle. It only deals in int, string, float, double, etc. values. Now I need  to handle two cases(event and exception) inside the doWork() of the worker. So to handle both these things I'm doing this way. Should I go for something else?

**Comment by Sarthak2601** [comment]
> Also, I didn’t see any Bazel files updated, just the workspace. Note that the workspace change enables using a dependency, but doesn’t actually use that dependency. You’ll need to update the domain/BUILD.bazel file.

Yep, done.

File: app/src/main/java/org/oppia/app/application/OppiaApplication.kt (hunk 4 above)
Comment (Sarthak2601) [reply app/src/main/java/org/oppia/app/application/OppiaApplication.kt:38]: I tried implementing this via the module and here's what I did - 
Implemented the `Configuration.Provider` in the WorkManagerInitialiser and then initialised the work manager in its on create and then bound them in the module. I had to remove the default work manager initialisation using a content provider in the manifest. All of this worked perfectly in production but didn't seem to work in tests as the work manager was getting initialised again and again. 

So I changed the implementation to just providing the configuration via module and then returning that configuration in the `getWorkManagerConfiguration()`. This way production worked, tests worked and we didn't need to alter the default initialisation of the work manager. Is this fine ?

**Comment by vinitamurthi** [comment]
I'm approving just to unblock the PR but please wait for Rajat and Ben's reviews

**Review by vinitamurthi — APPROVED** [review]

**Comment by Sarthak2601** [comment]
> I'm approving just to unblock the PR but please wait for Rajat and Ben's reviews

Yes, thanks :)

File: domain/BUILD.bazel [hunk 15]
```diff
@@ -34,6 +35,7 @@ TEST_DEPS = [
         artifact("com.google.truth:truth"),
         artifact("org.jetbrains.kotlin:kotlin-test-junit"),
         artifact("org.jetbrains.kotlin:kotlin-reflect"),
+        artifact("androidx.work:work-testing:2.4.0"),
```
Comment (rt4914) [inline domain/BUILD.bazel]: Nit: I think we can follow the alphabetical order here too.

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt [hunk 16]
```diff
@@ -0,0 +1,110 @@
...
+import org.oppia.domain.oppialogger.analytics.AnalyticsController
+import org.oppia.domain.oppialogger.exceptions.ExceptionsController
+import org.oppia.domain.oppialogger.exceptions.toException
+import org.oppia.util.data.DataProviders
+import org.oppia.util.logging.ConsoleLogger
+import org.oppia.util.logging.EventLogger
+import org.oppia.util.logging.ExceptionLogger
+import javax.inject.Inject
+
+const val LOG_UPLOAD_WORKER = "log_upload_worker"
```
Comment (rt4914) [inline domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt]: Suggestion: 
`const val TAG = "LogUploadWorker.tag"`

Shift this to companion object and use it like this:
`LogUploadWorker.TAG ` everywhere outside this file.

**Review by rt4914 — APPROVED** [review]
LGTM, just a couple of nits.

File: domain/BUILD.bazel (hunk 15 above)
Comment (Sarthak2601) [reply domain/BUILD.bazel]: Done.

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt (hunk 16 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt]: I don't actually need it anywhere outside this file as of now but moved it to companion object as we may use it in the future while logging work requests.

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkRequest.kt (hunk 9 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkRequest.kt]: Modified, PTAL.

File: app/src/main/java/org/oppia/app/application/OppiaApplication.kt (hunk 4 above)
Comment (BenHenning) [reply app/src/main/java/org/oppia/app/application/OppiaApplication.kt:38]: I'm slightly confused. I actually would expect the work manager to be initialized repeatedly in tests since each test recreates the test application.

With this solution, don't we need to update all test applications to also be a Configuration.Provider? How does it actually get hooked up?

File: domain/src/main/java/org/oppia/domain/oppialogger/analytics/AnalyticsController.kt [hunk 17]
```diff
@@ -154,11 +154,8 @@ class AnalyticsController @Inject constructor(
     oppiaEventLogs.eventLogList.withIndex()
       .minBy { it.value.timestamp }?.index
 
-  /**
-   * Returns a [LiveData] result which can be used to get [OppiaEventLogs]
-   * for the purpose of uploading in the presence of network connectivity.
-   */
-  fun getEventLogs(): LiveData<AsyncResult<OppiaEventLogs>> {
-    return dataProviders.convertToLiveData(eventLogStore)
+  /** Returns [eventLogStore] which can be later converted to [LiveData] to extract log reports from the store. */
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/domain/oppialogger/analytics/AnalyticsController.kt]:
```suggestion
  /** Returns a data provider for log reports that have been recorded for upload. */
```

Previous wording caused some confusion for me:
1) Readers don't know what eventLogStore is--that's an implementation detail
2) It's implied DataProviders can be turned into LiveData since that's more or less its purpose

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt (hunk 11 above)
Comment (BenHenning) [reply domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt]: Sorry, this wasn't a comment about consistency. If this function is not being called on the main thread, we cannot retrieve LiveData's value: it's designed to be used only on the main thread. How does AndroidX's WorkManager behave when doWork() is called?

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt (hunk 8 above)
Comment (BenHenning) [reply domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt]: I see that you removed the scope, but the class is still injectable. As mentioned, constructed classes do not need injection constructors.

Also, this constructor should be private since it's only called from its factory.

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerModule.kt (hunk 12 above)
Comment (BenHenning) [reply domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerModule.kt]: I see. I actually suggest not generalizing this right now because it's not clear if the constraints the system is currently run under will also work for other applications of WorkManager. Generalizing may take a bit more thought based on the exact needs of the different workers, and possibly more abstraction since the current solution is heavily dependent on WorkManager, making any future work to be able to switch to another delivery work manager API difficult.

File: domain/src/test/java/org/oppia/domain/oppialogger/LogUploadWorkerTest.kt [hunk 18]
```diff
@@ -0,0 +1,223 @@
...
+import org.oppia.util.logging.GlobalLogLevel
+import org.oppia.util.logging.LogLevel
+import org.oppia.util.networking.NetworkConnectionUtil
+import org.robolectric.annotation.Config
+import javax.inject.Inject
+import javax.inject.Singleton
+
+@RunWith(AndroidJUnit4::class)
+@Config(manifest = Config.NONE)
+class LogUploadWorkerTest {
```
Comment (BenHenning) [inline domain/src/test/java/org/oppia/domain/oppialogger/LogUploadWorkerTest.kt]: Here & elsewhere: rename tests & suites to match their production counterparts.

File: domain/src/test/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkRequestTest.kt (hunk 14 above)
Comment (BenHenning) [reply domain/src/test/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkRequestTest.kt]: That's a good point. In that case, we should fully simulate the situation & the test names should reflect it. To simulate app restart, you need to recreate the test component since the actual objects will be different in the new application.

Please update this & other tests that are testing "pre-app" behavior.

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @Sarthak2601! The Bazel changes LGTM for codeowners, but I have some other concerns about the current implementation. PTAL.

**Comment by BenHenning** [comment]
Also from our Hangouts chat where you mentioned doWork() is executed on a background thread: have you tested this manually with the actual app yet? I'm fairly sure this won't work as-is because:
1) In doWork() you're not blocking on the main thread which means that LiveData won't ever have the values from the data provider since that takes at least 2 thread hops
2) In doWork() you aren't observing the LiveData, so it never becomes active. Our LiveData bridge only calls into the data provider if it's active to prevent unnecessary work.

File: domain/src/test/java/org/oppia/domain/oppialogger/LogUploadWorkerTest.kt (hunk 18 above)
Comment (Sarthak2601) [reply domain/src/test/java/org/oppia/domain/oppialogger/LogUploadWorkerTest.kt]: Modified, PTAL.

File: domain/src/main/java/org/oppia/domain/oppialogger/analytics/AnalyticsController.kt (hunk 17 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/analytics/AnalyticsController.kt]: Done.

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerModule.kt (hunk 12 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerModule.kt]: Okay, done.

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt (hunk 8 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt]: Done.

File: app/src/main/java/org/oppia/app/application/OppiaApplication.kt (hunk 4 above)
Comment (Sarthak2601) [reply app/src/main/java/org/oppia/app/application/OppiaApplication.kt:38]: I also expected the same but once it's initialised, it gives error when we re-initialise it again. Also, it got hooked up to the tests as is. Whenever we want to use their functionality, we can initialise the testWorkManager via the api provided by the testing dependency.

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt (hunk 11 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt]: Changed the implementation to a coroutine worker and handled cache retrieval via the original controller. PTAL.

File: domain/src/test/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkRequestTest.kt (hunk 14 above)
Comment (Sarthak2601) [reply domain/src/test/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkRequestTest.kt]: Due to work manager testing issue, couldn't apply these test cases. However, tests verifying the call of this function and its contents have been put. PTAL.

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt [hunk 19]
```diff
@@ -0,0 +1,105 @@
...
+  }
+
+  /** Extracts event logs from the cache store and logs them to the remote service. */
+  private suspend fun uploadEvents(): Result {
+    return try {
+      val eventLogs = analyticsController.getEventLogStoreList()
+      eventLogs.let {
+        for (eventLog in it) {
+          eventLogger.logEvent(eventLog)
+          analyticsController.removeFirstEventLogFromStore()
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt:72]: This seems a bit odd to me--why don't we just ask the controller to remove all of the events that were successfully logged? Ditto for removeFirstExceptionLogFromStore above.

File: domain/src/main/java/org/oppia/domain/oppialogger/exceptions/ExceptionsController.kt [hunk 20]
```diff
@@ -159,13 +158,30 @@ class ExceptionsController @Inject constructor(
...
   }
+
+  /** Returns a list of [ExceptionLog] after reading from [exceptionLogStore]. */
+  suspend fun getExceptionLogStoreList(): MutableList<ExceptionLog> {
+    return exceptionLogStore.readDataAsync().await().exceptionLogList
+  }
+
+  /** Removes the first [ExceptionLog] from the [exceptionLogStore]. */
+  fun removeFirstExceptionLogFromStore() {
+    exceptionLogStore.storeDataAsync(true) { oppiaExceptionLogs ->
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/domain/oppialogger/exceptions/ExceptionsController.kt]: For this & AnalyticsController, please qualify the ``true`` by using a named argument to provide context to readers.

File: domain/src/main/java/org/oppia/domain/oppialogger/analytics/AnalyticsController.kt [hunk 21]
```diff
@@ -154,11 +151,28 @@ class AnalyticsController @Inject constructor(
...
-   * for the purpose of uploading in the presence of network connectivity.
-   */
-  fun getEventLogs(): LiveData<AsyncResult<OppiaEventLogs>> {
-    return dataProviders.convertToLiveData(eventLogStore)
+  /** Returns a data provider for log reports that have been recorded for upload. */
+  fun getEventLogStore(): DataProvider<OppiaEventLogs> {
+    return eventLogStore
+  }
+
+  /** Returns a list of [EventLog] after reading from [eventLogStore]. */
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/domain/oppialogger/analytics/AnalyticsController.kt]: Readers don't know what ``eventLogStore`` is. Try phrasing this based on the public API, not the implementation. Ditto for ``ExceptionsController``.

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploaderModule.kt [hunk 22]
```diff
@@ -0,0 +1,11 @@
+package org.oppia.domain.oppialogger.loguploader
+
+import dagger.Binds
+import dagger.Module
+
+/** Provides Log Uploader related dependencies. */
+@Module
+interface LogUploaderModule {
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploaderModule.kt]: Perhaps: FirebaseLogUploaderModule

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploaderModule.kt [hunk 23]
```diff
@@ -0,0 +1,11 @@
+package org.oppia.domain.oppialogger.loguploader
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploaderModule.kt]: Suggest putting this with the other Firebase impls to keep them together.

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/FirebaseLogUploader.kt [hunk 24]
```diff
@@ -0,0 +1,39 @@
+package org.oppia.domain.oppialogger.loguploader
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/domain/oppialogger/loguploader/FirebaseLogUploader.kt]: Suggest putting this with the other Firebase deps to keep them together.

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/FirebaseLogUploader.kt [hunk 25]
```diff
@@ -0,0 +1,39 @@
...
+import androidx.work.PeriodicWorkRequest
+import androidx.work.WorkManager
+import javax.inject.Inject
+import javax.inject.Singleton
+
+private const val OPPIA_EVENT_WORK = "OPPIA_EVENT_WORK_REQUEST"
+private const val OPPIA_EXCEPTION_WORK = "OPPIA_EXCEPTION_WORK_REQUEST"
+
+/** Enqueues work requests for uploading stored event/exception logs to the remote service. */
+@Singleton
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/domain/oppialogger/loguploader/FirebaseLogUploader.kt]: This is overscoping--we don't actually have any state to scope. I suggest removing this.

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/FirebaseLogUploader.kt [hunk 26]
```diff
@@ -0,0 +1,39 @@
...
+class FirebaseLogUploader @Inject constructor() : LogUploader {
+
+  /** Enqueues a unique periodic work request for uploading exceptions to the remote service. */
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/domain/oppialogger/loguploader/FirebaseLogUploader.kt]: Documentation doesn't seem needed here & below since it's overriding behavior defined in ``LogUploader``.

File: domain/src/test/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkManagerInitializerTest.kt [hunk 27]
```diff
@@ -0,0 +1,264 @@
...
+  // TODO(#89): Move this to a common test application component.
+  @Singleton
+  @Component(
+    modules = [
+      TestModule::class,
+      TestLogReportingModule::class,
+      TestLogStorageModule::class,
+      TestDispatcherModule::class,
+      LogUploadWorkerModule::class,
+      TestLogUploaderModule::class
```
Comment (BenHenning) [inline domain/src/test/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkManagerInitializerTest.kt]:
```suggestion
      TestModule::class, TestLogReportingModule::class, TestLogStorageModule::class, TestDispatcherModule::class, LogUploadWorkerModule::class, TestLogUploaderModule::class
```

Prefer tightly packing these (my suggested edit probably will need to be slightly broken up, though).

File: domain/src/test/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkManagerInitializerTest.kt [hunk 28]
```diff
@@ -0,0 +1,264 @@
...
+
+    fun inject(logUploadWorkRequestTest: LogUploadWorkManagerInitializerTest)
+  }
+}
+
+/**  A test specific fake for the log uploader. */
+@Singleton
+class FakeLogUploader @Inject constructor() : LogUploader {
+
+  private val eventRequestIdList = ArrayList<UUID>()
```
Comment (BenHenning) [inline domain/src/test/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkManagerInitializerTest.kt]:
```suggestion
  private val eventRequestIdList = mutableListOf<UUID>()
```

Prefer ``mutableListOf``. Ditto below.

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt [hunk 29]
```diff
@@ -0,0 +1,105 @@
...
+      }
+      Result.success()
+    } catch (e: Exception) {
+      consoleLogger.e(TAG, e.toString(), e)
+      Result.failure()
+    }
+  }
+
+  /** Creates an instance of [LogUploadWorker] by properly injecting dependencies. */
+  class FactoryLogUpload @Inject constructor(
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt]: Prefer just ``Factory``. Then you can inject ``LogUploadWorker.Factory`` where needed.

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt [hunk 30]
```diff
@@ -0,0 +1,105 @@
...
+  private suspend fun uploadExceptions(): Result {
+    return try {
+      val exceptionLogs = exceptionsController.getExceptionLogStoreList()
+      exceptionLogs.let {
+        for (exceptionLog in it) {
+          exceptionLogger.logException(exceptionLog.toException())
+          exceptionsController.removeFirstExceptionLogFromStore()
+        }
+      }
+      Result.success()
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt:58]: What if the log operation fails? Should we track it & return a failure in that case, then retry later?

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt [hunk 31]
```diff
@@ -0,0 +1,105 @@
...
+      val eventLogs = analyticsController.getEventLogStoreList()
+      eventLogs.let {
+        for (eventLog in it) {
+          eventLogger.logEvent(eventLog)
+          analyticsController.removeFirstEventLogFromStore()
+        }
+      }
+      Result.success()
+    } catch (e: Exception) {
+      consoleLogger.e(TAG, e.toString(), e)
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt]: Here & above: prefer logging context. Adding the exception will provide sufficient context to the exception, e,g:

```kotlin
consoleLogger.e(TAG, "Failed to upload events", e)
```

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerModule.kt [hunk 32]
```diff
@@ -0,0 +1,26 @@
...
+@Module
+interface LogUploadWorkerModule {
+
+  @Binds
+  fun bindLogUploadWorkerFactory(
+    worker: LogUploadWorker.FactoryLogUpload
+  ): LogUploadChildWorkerFactory
+
+  @Binds
+  fun bindWorkerFactory(logUploadWorkerFactory: LogUploadWorkerFactory): WorkerFactory
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerModule.kt]: Why is this needed? Can't we just inject the factory where we need to?

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerFactory.kt [hunk 33]
```diff
@@ -0,0 +1,22 @@
...
+import androidx.work.WorkerFactory
+import androidx.work.WorkerParameters
+import javax.inject.Inject
+
+/** Custom [WorkerFactory] for the [LogUploadWorker]. */
+class LogUploadWorkerFactory @Inject constructor(
+  private val workerFactory: LogUploadChildWorkerFactory
+) : WorkerFactory() {
+
+  /** Returns a [LogUploadWorker] after injecting [appContext] and [workerParameters] into [LogUploadChildWorkerFactory]. */
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerFactory.kt]: Or perhaps: ``Returns a new [LogUploadWorker] for the given context and parameters.``

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerFactory.kt [hunk 34]
```diff
@@ -0,0 +1,22 @@
...
+  override fun createWorker(
+    appContext: Context,
+    workerClassName: String,
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerFactory.kt:17]: Is it okay to ignore this?

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadChildWorkerFactory.kt [hunk 35]
```diff
@@ -0,0 +1,10 @@
+package org.oppia.domain.oppialogger.loguploader
+
+import android.content.Context
+import androidx.work.CoroutineWorker
+import androidx.work.WorkerParameters
+
+/** Returns an instance of the worker class after injecting the needed dependencies. */
+interface LogUploadChildWorkerFactory {
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadChildWorkerFactory.kt]: Why do we need this? Why not just inject LogUploadWorker.Factory directly where needed?

File: domain/src/test/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerTest.kt [hunk 36]
```diff
@@ -0,0 +1,245 @@
...
+  // TODO(#89): Move this to a common test application component.
+  @Singleton
+  @Component(
+    modules = [
+      TestModule::class,
+      TestLogReportingModule::class,
+      TestLogStorageModule::class,
+      TestDispatcherModule::class,
+      LogUploadWorkerModule::class,
+      TestLogUploaderModule::class
```
Comment (BenHenning) [inline domain/src/test/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerTest.kt]: Ditto for these modules (prefer tightly formatting them).

File: domain/src/test/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerTest.kt [hunk 37]
```diff
@@ -0,0 +1,245 @@
...
+import javax.inject.Singleton
+
+@RunWith(AndroidJUnit4::class)
+@LooperMode(LooperMode.Mode.PAUSED)
+@Config(manifest = Config.NONE)
+class LogUploadWorkerTest {
+
+  @Rule
+  @JvmField
+  val mockitoRule: MockitoRule = MockitoJUnit.rule()
```
Comment (BenHenning) [inline domain/src/test/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerTest.kt]: Doesn't seem needed--you're not using captors or mocks. Ditto for LogUploadWorkManagerInitializerTest.

File: domain/src/test/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerTest.kt [hunk 38]
```diff
@@ -0,0 +1,245 @@
...
+    workManager.enqueue(request)
+    testCoroutineDispatchers.runCurrent()
+    val workInfo = workManager.getWorkInfoById(request.id)
+
+    assertThat(workInfo.get().state).isEqualTo(WorkInfo.State.SUCCEEDED)
+    assertThat(fakeEventLogger.getMostRecentEvent()).isEqualTo(eventLogTopicContext)
+  }
+
+  @Test
+  fun testWorker_logException_withoutNetwork_enqueueRequest_verifySuccess() {
```
Comment (BenHenning) [inline domain/src/test/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerTest.kt:142]: It seems also worthwhile to test that when there is network that it doesn't enqueue the request (since it should log it directly).

**Review by BenHenning — APPROVED** [review]
Thanks @Sarthak2601! Overall, I think this looks really good. Nearly all of my comments are just nits that I noticed. I think the structure of this PR is great.

**Review by BenHenning — CHANGES_REQUESTED** [review]
Meant to request changes.

File: app/src/main/java/org/oppia/app/application/OppiaApplication.kt (hunk 4 above)
Comment (BenHenning) [reply app/src/main/java/org/oppia/app/application/OppiaApplication.kt:38]: Looks like this is resolved now.

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt (hunk 11 above)
Comment (BenHenning) [reply domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt]: Looks good--thanks!

File: domain/src/test/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkRequestTest.kt (hunk 14 above)
Comment (BenHenning) [reply domain/src/test/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkRequestTest.kt]: This seems reasonable--thanks!

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploaderModule.kt (hunk 22 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploaderModule.kt]: Done.

File: domain/src/main/java/org/oppia/domain/oppialogger/analytics/AnalyticsController.kt (hunk 21 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/analytics/AnalyticsController.kt]: Done.

File: domain/src/main/java/org/oppia/domain/oppialogger/exceptions/ExceptionsController.kt (hunk 20 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/exceptions/ExceptionsController.kt]: Done.

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt (hunk 19 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt:72]: I've basically done a one by one transaction here so that none of the logs get misplaced in the interim. This seemed reasonable to me. We can keep track of exceptions in a better way here I think.

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/FirebaseLogUploader.kt (hunk 25 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/loguploader/FirebaseLogUploader.kt]: Done.

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/FirebaseLogUploader.kt (hunk 26 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/loguploader/FirebaseLogUploader.kt]: Done.

File: domain/src/test/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkManagerInitializerTest.kt (hunk 27 above)
Comment (Sarthak2601) [reply domain/src/test/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkManagerInitializerTest.kt]: I've done it in a 2-2 configuration.

File: domain/src/test/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkManagerInitializerTest.kt (hunk 28 above)
Comment (Sarthak2601) [reply domain/src/test/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkManagerInitializerTest.kt]: Done.

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt (hunk 30 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt:58]: If any of the operation fails, it'll throw an error which will be caught and the result will be failed. All of the un-uploaded logs will then be taken up in the next work manager cycle. Does that make sense?

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt (hunk 31 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt]: Done.

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt (hunk 29 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt]: Done.

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerModule.kt (hunk 32 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerModule.kt]: Actually that's worker factory that provides context and worker params to the child factory which then injects the other dependencies and clubs all these together to make the worker class. This is done because we can't inject the worker params directly.

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerFactory.kt (hunk 33 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerFactory.kt]: Done.

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerFactory.kt (hunk 34 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerFactory.kt:17]: Yes, it's okay. I've verified.

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadChildWorkerFactory.kt (hunk 35 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadChildWorkerFactory.kt]: LogUploadWorker.Factory is an implementation of this interface. This interface's instance is then used by the worker factory to inject the context and worker params into.

File: domain/src/test/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerTest.kt (hunk 36 above)
Comment (Sarthak2601) [reply domain/src/test/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerTest.kt]: Done.

File: domain/src/test/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerTest.kt (hunk 37 above)
Comment (Sarthak2601) [reply domain/src/test/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerTest.kt]: Done.

File: domain/src/test/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerTest.kt (hunk 38 above)
Comment (Sarthak2601) [reply domain/src/test/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerTest.kt:142]: Actually that `withoutNetwork` is basically for putting the exceptions inside the store and the work request will perform its function in presence of network only (in background, when the app instance is closed).

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploaderModule.kt (hunk 23 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploaderModule.kt]: Won't that mean adding additional dependencies (work manager) in the utility module of both gradle and bazel just for the sake of this file ?

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/FirebaseLogUploader.kt (hunk 24 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/loguploader/FirebaseLogUploader.kt]: Ditto as above.

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploaderModule.kt (hunk 23 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploaderModule.kt]: Done.

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/FirebaseLogUploader.kt (hunk 24 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/loguploader/FirebaseLogUploader.kt]: Done.

File: domain/src/main/java/org/oppia/domain/oppialogger/analytics/AnalyticsController.kt [hunk 39]
```diff
@@ -156,14 +156,14 @@ class AnalyticsController @Inject constructor(
...
+  /** Returns a list of event log reports that have been recorded for upload. */
   suspend fun getEventLogStoreList(): MutableList<EventLog> {
     return eventLogStore.readDataAsync().await().eventLogList
   }
 
-  /** Removes the first [EventLog] from the [eventLogStore]. */
+  /** Removes the first event log report that had been recorded for upload. */
   fun removeFirstEventLogFromStore() {
-    eventLogStore.storeDataAsync(true) { oppiaEventLogs ->
+    eventLogStore.storeDataAsync(/* updateInMemoryCache= */true) { oppiaEventLogs ->
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/domain/oppialogger/analytics/AnalyticsController.kt]:
```suggestion
    eventLogStore.storeDataAsync(updateInMemoryCache = true) { oppiaEventLogs ->
```

Optional. Yours is completely acceptable (though you should add a space after the ``/``), though Kotlin gives us this syntax for Kotlin APIs for free & it includes automatic validation.

File: domain/src/main/java/org/oppia/domain/oppialogger/exceptions/ExceptionsController.kt [hunk 40]
```diff
@@ -163,14 +163,14 @@ class ExceptionsController @Inject constructor(
...
+  /** Returns a list of exception log reports which have been recorded for upload. */
   suspend fun getExceptionLogStoreList(): MutableList<ExceptionLog> {
     return exceptionLogStore.readDataAsync().await().exceptionLogList
   }
 
-  /** Removes the first [ExceptionLog] from the [exceptionLogStore]. */
+  /** Removes the first exception log report that had been recorded for upload. */
   fun removeFirstExceptionLogFromStore() {
-    exceptionLogStore.storeDataAsync(true) { oppiaExceptionLogs ->
+    exceptionLogStore.storeDataAsync(/* updateInMemoryCache = */true) { oppiaExceptionLogs ->
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/domain/oppialogger/exceptions/ExceptionsController.kt]: Ditto here.

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploaderModule.kt (hunk 23 above)
Comment (BenHenning) [reply domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploaderModule.kt]: You're correct, but one advantage of keeping all "Firebase" things together is that it lets us easily switch out implementations in the future (if we ever moved off Firebase).

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt (hunk 30 above)
Comment (BenHenning) [reply domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt:58]: I don't think that's quite right, unless I'm missing something. The suspend function you're calling on the DataProvider (retrieveData()) won't throw an exception, it'll return an AsyncResult with the failure. Don't we need to check all of these results for potential failures?

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerModule.kt (hunk 32 above)
Comment (BenHenning) [reply domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerModule.kt]: I understand why the factory is needed, but I don't quite understand why we can't inject LogUploadWorkerFactory where we're currently injecting WorkerFactory (though I don't actually see this injected anywhere--are you sure this binding is being used?)

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadChildWorkerFactory.kt (hunk 35 above)
Comment (BenHenning) [reply domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadChildWorkerFactory.kt]: That part is clear to me, but what isn't clear to me is why can't we inject LogUploadWorker.Factory where we are currently injecting this factory? Why do we need this interface & why can't we use the only implementation of it directly?

File: domain/src/test/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerTest.kt (hunk 37 above)
Comment (BenHenning) [reply domain/src/test/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerTest.kt]: Doesn't seem removed in the latest changes--am I missing something?

File: domain/src/test/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerTest.kt (hunk 38 above)
Comment (BenHenning) [reply domain/src/test/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerTest.kt:142]: To be clear: I'm actually suggesting that we verify that we _don't_ enqueue the request if we log with internet connectivity on (since it should just log as normal). Am I maybe misunderstanding why we shouldn't do that?

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @Sarthak2601! PTAL at my comments & reply before I approve. Also, I think you'll need to make Bazel changes and that will require my approval per code owners.

File: domain/src/main/java/org/oppia/domain/oppialogger/analytics/AnalyticsController.kt (hunk 39 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/analytics/AnalyticsController.kt]: Done.

File: domain/src/main/java/org/oppia/domain/oppialogger/exceptions/ExceptionsController.kt (hunk 40 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/exceptions/ExceptionsController.kt]: Done.

File: domain/src/test/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerTest.kt (hunk 38 above)
Comment (Sarthak2601) [reply domain/src/test/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerTest.kt:142]: Okay, so work manager will work in the background only. It'll get enqueued at its specified time interval only and will fetch logs from the cache store. Now when the app is running and there is network, it'll not store in the cache store and will log directly itself. If there are no cached log reports in the store, it'll just complete the process of the request. Does that help ?

File: domain/src/test/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerTest.kt (hunk 37 above)
Comment (Sarthak2601) [reply domain/src/test/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerTest.kt]: Have you refreshed ? I think it's removed.

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadChildWorkerFactory.kt (hunk 35 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadChildWorkerFactory.kt]: The interface is basically to link the appContext and workParams that we receive from the WorkerFactory and relay it in such a form so that we can inject other dependencies as well. 
Note - WorkerFactory gets the `appContext` and `workParams` from the `WorkManagerConfiguration` at application start.

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt (hunk 30 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt:58]: Umm..I'm actually using the readDataAsync from the Analytics/Exceptions Controller. Will that not throw an error ? I believe I faced an error while testing.

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerModule.kt (hunk 32 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerModule.kt]: Yes, it's getting set up as the default worker factory using the WorkManagerConfiguration at app start up.

**Comment by Sarthak2601** [comment]
@BenHenning for the code owners, I've added artifacts in Bazel and it's building perfectly. PTAL. Also, I used [this](https://android.jlelse.eu/injecting-into-workers-android-workmanager-and-dagger-948193c17684) article for work manager - dagger integration.

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt (hunk 30 above)
Comment (BenHenning) [reply domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt:58]: No, it won't. See the implementation: https://github.com/oppia/oppia-android/blob/2ca2397/data/src/main/java/org/oppia/data/persistence/PersistentCacheStore.kt#L75. Or, at least, it won't under normal operations. Normal failures will be propagated via AsyncResult--that's actually why we have it.

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerModule.kt (hunk 32 above)
Comment (BenHenning) [reply domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerModule.kt]: That's injecting LogUploadWorkerFactory, not WorkerFactory (which is what this binding is providing). This still seems unnecessary--you should be able to remove it.

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadChildWorkerFactory.kt (hunk 35 above)
Comment (BenHenning) [reply domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadChildWorkerFactory.kt]: I don't think I'm being really clear here: I'm not suggesting that you stop passing those things. I'm suggesting you delete this interface and in ``LogUploadWorkerFactory`` inject ``LogUploadWorker.Factory``, instead. It still does all of the things you mentioned above, but it avoids needing this class (you should move the documentation to the Factory class, though).

File: utility/BUILD.bazel [hunk 41]
```diff
@@ -23,6 +23,7 @@ kt_android_library(
         "//app:crashlytics_deps",
         artifact("org.jetbrains.kotlinx:kotlinx-coroutines-core"),
         artifact("androidx.appcompat:appcompat"),
+        artifact("androidx.work:work-runtime-ktx:2.4.0"),
```
Comment (BenHenning) [inline utility/BUILD.bazel]: Remove the version--having it defined in WORKSPACE should be sufficient.

File: domain/src/test/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerTest.kt (hunk 37 above)
Comment (BenHenning) [reply domain/src/test/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerTest.kt]: I still see this in LogUploadWorkManagerInitializerTest. Please make sure to keep an eye on 'ditto' in comments since it means it applies broadly.

File: domain/src/test/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerTest.kt (hunk 38 above)
Comment (BenHenning) [reply domain/src/test/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerTest.kt:142]: Yep, I'm actually asking that you verify everything you just said actually works like we expect it to via tests here.

**Comment by BenHenning** [comment]
@Sarthak2601 left 1 new comment & replies to most existing threads. PTAL.

**Review by BenHenning — APPROVED** [review]
Approving to unblock, but submission is conditioned on my comment threads being resolved. @rt4914 & @anandwana001 please verify these.

File: domain/src/test/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkManagerInitializerTest.kt (hunk 28 above)
Comment (Sarthak2601) [reply domain/src/test/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkManagerInitializerTest.kt]: To be clear on this : The enqueuing of work requests doesn't depend on if we have network connectivity or not. Even if we have internet connection, work requests will be enqueued and the worker will work as is. However, during that time no logs will be saved as all of them will be uploaded directly to the remote service.

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/FirebaseLogUploader.kt (hunk 26 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/loguploader/FirebaseLogUploader.kt]: Done.

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerModule.kt (hunk 32 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerModule.kt]: Done.

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt (hunk 30 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt:58]: Done.

File: utility/BUILD.bazel (hunk 41 above)
Comment (Sarthak2601) [reply utility/BUILD.bazel]: Done.

File: domain/src/test/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerTest.kt (hunk 37 above)
Comment (Sarthak2601) [reply domain/src/test/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerTest.kt]: Done.

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadChildWorkerFactory.kt (hunk 35 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadChildWorkerFactory.kt]: Yes, done.

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt (hunk 30 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt:58]: It seems like there's a misunderstanding here. I am not using retrieveData function anymore as the implementation has been shifted to readDataAsync which returns a deferrable instead of an asyncResult. According to already existing implementations of readDataAsync, we don't need to check for failure cases here. Please correct me if I am wrong here.

File: domain/src/test/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerTest.kt (hunk 38 above)
Comment (Sarthak2601) [reply domain/src/test/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerTest.kt:142]: Work manager and event logging are completely separate things here. Request enqueue and dequeue will work regardless of how we are logging our events. The work manager's task is to enqueue a request, fetch the logs from the store and upload them on Firebase. Even if there is network connection, work request will get enqueued to fetch data from the cache store. Logging of an event/exception is a part of the Analytics/Exception controller and not the work manager.

File: domain/src/main/java/org/oppia/domain/oppialogger/OppiaLogUploadWorker.kt (hunk 1 above)
Comment (rt4914) [reply domain/src/main/java/org/oppia/domain/oppialogger/OppiaLogUploadWorker.kt]: Resolving this now.

File: domain/src/main/java/org/oppia/domain/oppialogger/OppiaLogUploadWorker.kt (hunk 2 above)
Comment (rt4914) [reply domain/src/main/java/org/oppia/domain/oppialogger/OppiaLogUploadWorker.kt]: Resolving this now.

File: domain/src/main/java/org/oppia/domain/oppialogger/OppiaLogUploader.kt (hunk 3 above)
Comment (rt4914) [reply domain/src/main/java/org/oppia/domain/oppialogger/OppiaLogUploader.kt]: Keeping this open, for further communication in future.

File: domain/BUILD.bazel (hunk 15 above)
Comment (rt4914) [reply domain/BUILD.bazel]: Resolving this now

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt (hunk 16 above)
Comment (rt4914) [reply domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt]: Okat

File: domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt (hunk 30 above)
Comment (rt4914) [reply domain/src/main/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorker.kt:58]: Resolving this now.

File: domain/src/test/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerTest.kt (hunk 38 above)
Comment (rt4914) [reply domain/src/test/java/org/oppia/domain/oppialogger/loguploader/LogUploadWorkerTest.kt:142]: Keeping this open, for further communication in future.

File: utility/BUILD.bazel (hunk 41 above)
Comment (rt4914) [reply utility/BUILD.bazel]: Resolving this now.

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.
