### PR TITLE
Fix #2409: Resolve ktlint max line in walkthrough test package

### LINKED ISSUE #2409: Resolve ktlint max line in walkthrough test package
**Describe the bug**
We are preventing the 100 char length at some places like test case fun name. 
`// ktlint-disable max-line-length`

**Expected behavior**
We need to remove this prevention and fix the function name under 100 char length.

### PR DESCRIPTION
**Pull request by MaskedCarrot**
## Explanation
Fixes #2409 

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

File: app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughActivityTest.kt [hunk 1]
```diff
@@ -71,14 +71,14 @@ import javax.inject.Singleton
...
-  fun testWalkthroughFragment_defaultProgress_worksCorrectly() {
+  fun testWalkthroughActivity_defaultProgress_worksCorrectly() {
     launch(WalkthroughActivity::class.java).use {
       onView(withId(R.id.walkthrough_progress_bar)).check(matches(withProgress(1)))
     }
   }
 
   @Test
-  fun testWalkthroughFragment_checkFrameLayout_backButton_progressBar_IsVisible() {
+  fun testWalkthroughActivity_checkFrameLayout_backButton_progressBar_IsVisible() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughActivityTest.kt]: testWalkthroughActivity_checkFrameLayout_backButton_progressBarIsVisible

File: app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughActivityTest.kt [hunk 2]
```diff
@@ -105,7 +105,7 @@ class WalkthroughActivityTest {
   }
 
   @Test
-  fun testWalkthroughFragment_nextBtn_configurationChanged_backBtn_worksCorrectly() {
+  fun testWalkthroughActivity_nextBtn_configChange_backBtn_worksCorrectly() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughActivityTest.kt]: either use `btn` or `button` everywhere.

Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughActivityTest.kt]: same with `inc` and `dec`

File: app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughFinalFragmentTest.kt [hunk 3]
```diff
@@ -107,7 +107,7 @@ class WalkthroughFinalFragmentTest {
   }
 
   @Test
-  fun testWalkthroughWelcomeFragment_recyclerViewIndex1_topicSelected_topicTitleIsCorrect() {
+  fun testWalkthroughFinalFragment_topicSelected_topicTitle_firstTestTopic_isDisplayed() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughFinalFragmentTest.kt]: testWalkthroughFinalFragment_topicSelected_topicTitle_firstTestTopicIsDisplayed

File: app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughTopicListFragmentTest.kt [hunk 4]
```diff
@@ -152,7 +152,7 @@ class WalkthroughTopicListFragmentTest {
   }
 
   @Test
-  fun testWalkthroughWelcomeFragment_rVIndex1_topicCard_configChanged_topicNameIsCorrect() {
+  fun testWalkthroughTopicListFragment_topicCard_configChanged_topicNameIsCorrect() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughTopicListFragmentTest.kt]: `configChange` keep consistency.

**Review by anandwana001 — CHANGES_REQUESTED** [review]
@MaskedCarrot left few points, applies to all other parts.

File: app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughActivityTest.kt (hunk 2 above)
Comment (MaskedCarrot) [reply app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughActivityTest.kt]: done

File: app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughTopicListFragmentTest.kt (hunk 4 above)
Comment (MaskedCarrot) [reply app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughTopicListFragmentTest.kt]: Done

File: app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughFinalFragmentTest.kt (hunk 3 above)
Comment (MaskedCarrot) [reply app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughFinalFragmentTest.kt]: Done

File: app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughActivityTest.kt (hunk 1 above)
Comment (MaskedCarrot) [reply app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughActivityTest.kt]: Done

File: app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughFinalFragmentTest.kt [hunk 5]
```diff
@@ -189,7 +189,7 @@ class WalkthroughFinalFragmentTest {
   }
 
   @Test
-  fun testWalkthroughFinalFragment_yesNoButton_isDisplayed() {
+  fun testWalkthroughFinalFragment_yesNoBtn_isDisplayed() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughFinalFragmentTest.kt]: Is displayed should be together with yes no button as suggested in last comment.

**Review by anandwana001 — CHANGES_REQUESTED** [review]

File: app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughFinalFragmentTest.kt (hunk 5 above)
Comment (MaskedCarrot) [reply app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughFinalFragmentTest.kt]: done

File: app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughActivityTest.kt [hunk 6]
```diff
@@ -71,14 +71,14 @@ import javax.inject.Singleton
 )
 class WalkthroughActivityTest {
   @Test
-  fun testWalkthroughFragment_defaultProgress_worksCorrectly() {
+  fun testWalkthroughActivity_defaultProgress_worksCorrectly() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughActivityTest.kt]: please keep the result and what is being checked together. 

testWalkthroughActivity_defaultProgressWorksCorrectly

Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughActivityTest.kt]: ditto for all

**Review by anandwana001 — CHANGES_REQUESTED** [review]
Also confirm, `configChange` should be consistent everywhere.

**Comment by rt4914** [comment]
Un-assigning until the suggested changes are done.

File: app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughActivityTest.kt (hunk 6 above)
Comment (MaskedCarrot) [reply app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughActivityTest.kt]: @anandwana001 this test checks three things in it 
```
  @Test
  fun testWalkthroughActivity_checkFrameLayout_backBtn_progressBar_isVisible() {
    launch(WalkthroughActivity::class.java).use {
      onView(withId(R.id.walkthrough_fragment_placeholder)).check(matches(isDisplayed()))
      onView(withId(R.id.back_button)).check(matches(isDisplayed()))
      onView(withId(R.id.walkthrough_progress_bar)).check(matches(isDisplayed()))
    }
  }
```
WDYT should i separate it to separate tests or change the funchtion name such that this is correctly implied.

**Comment by MaskedCarrot** [comment]
> Also confirm, `configChange` should be consistent everywhere.

`configChange` is consistent throughout walkthrough package

File: app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughActivityTest.kt (hunk 6 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughActivityTest.kt]: Separate them

Comment (MaskedCarrot) [reply app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughActivityTest.kt]: done

File: app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughActivityTest.kt [hunk 7]
```diff
@@ -70,32 +70,45 @@ import javax.inject.Singleton
   qualifiers = "port-xxhdpi"
 )
 class WalkthroughActivityTest {
+
   @Test
-  fun testWalkthroughFragment_defaultProgress_worksCorrectly() {
+  fun testWalkthroughActivity_checkDefaultProgressWorksCorrectly() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughActivityTest.kt]: testWalkthroughActivity_defaultProgressWorksCorrectly

File: app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughActivityTest.kt [hunk 8]
```diff
@@ -70,32 +70,45 @@ import javax.inject.Singleton
...
     launch(WalkthroughActivity::class.java).use {
       onView(withId(R.id.walkthrough_progress_bar)).check(matches(withProgress(1)))
     }
   }
 
   @Test
-  fun testWalkthroughFragment_checkFrameLayout_backButton_progressBar_IsVisible() {
+  fun testWalkthroughActivity_checkFrameLayoutIsVisible() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughActivityTest.kt]: testWalkthroughActivity_frameLayoutIsVisible

File: app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughActivityTest.kt [hunk 9]
```diff
@@ -70,32 +70,45 @@ import javax.inject.Singleton
...
     launch(WalkthroughActivity::class.java).use {
       onView(withId(R.id.walkthrough_fragment_placeholder)).check(matches(isDisplayed()))
+    }
+  }
+
+  @Test
+  fun testWalkthroughActivity__checkBackBtnIsVisible() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughActivityTest.kt]: testWalkthroughActivity_backBtnIsVisible

**Review by anandwana001 — CHANGES_REQUESTED** [review]
@MaskedCarrot 
- no need of using a check, if we are saying isShown, or isVisible or something like that. 
- only use `_` single to separate

Applies to all files.

File: app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughActivityTest.kt (hunk 7 above)
Comment (MaskedCarrot) [reply app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughActivityTest.kt]: done

File: app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughActivityTest.kt (hunk 8 above)
Comment (MaskedCarrot) [reply app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughActivityTest.kt]: done

File: app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughActivityTest.kt (hunk 9 above)
Comment (MaskedCarrot) [reply app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughActivityTest.kt]: done

File: app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughFinalFragmentTest.kt [hunk 10]
```diff
@@ -107,7 +107,7 @@ class WalkthroughFinalFragmentTest {
   }
 
   @Test
-  fun testWalkthroughWelcomeFragment_recyclerViewIndex1_topicSelected_topicTitleIsCorrect() {
+  fun testWalkthroughFinalFragment_topicSelected_topicTitleFirstTestTopicIsDisplayed() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughFinalFragmentTest.kt]: testWalkthroughFinalFragment_topicSelected_firstTestTopicIsDisplayed

File: app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughFinalFragmentTest.kt [hunk 11]
```diff
@@ -157,7 +157,7 @@ class WalkthroughFinalFragmentTest {
   }
 
   @Test
-  fun testWalkthroughWelcomeFragment_recyclerViewIndex2_topicSelected_configurationChanged_topicTitleIsCorrect() { // ktlint-disable max-line-length
+  fun testWalkthroughFinalFragment_topicSelected_configChange_topicTitleIsCorrect() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughFinalFragmentTest.kt]: testWalkthroughFinalFragment_topicSelected_configChange_secondTestTopicIsDisplayed

File: app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughFinalFragmentTest.kt [hunk 12]
```diff
@@ -132,7 +132,7 @@ class WalkthroughFinalFragmentTest {
   }
 
   @Test
-  fun testWalkthroughWelcomeFragment_recyclerViewIndex2_topicSelected_topicTitleIsCorrect() {
+  fun testWalkthroughFinalFragment_topicSelected_topicTitleSecondTestTopicIsDisplayed() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughFinalFragmentTest.kt]: testWalkthroughFinalFragment_topicSelected_secondTestTopicIsDisplayed

File: app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughFinalFragmentTest.kt [hunk 13]
```diff
@@ -189,7 +189,7 @@ class WalkthroughFinalFragmentTest {
   }
 
   @Test
-  fun testWalkthroughWelcomeFragment_recyclerViewIndex1_topicSelected_yesNoButton_isDisplayedCorrectly() { // ktlint-disable max-line-length
+  fun testWalkthroughFinalFragment_yesNoBtnIsDisplayed() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughFinalFragmentTest.kt]: testWalkthroughFinalFragment_topicSelected_yesNoBtnIsDisplayed

File: app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughFinalFragmentTest.kt [hunk 14]
```diff
@@ -212,7 +212,7 @@ class WalkthroughFinalFragmentTest {
   }
 
   @Test
-  fun testWalkthroughWelcomeFragment_recyclerViewIndex1_topicSelected_clickNoButton_worksCorrectly() { // ktlint-disable max-line-length
+  fun testWalkthroughFinalFragment_clickNoBtn_noBtnWorksCorrectly() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughFinalFragmentTest.kt]: testWalkthroughFinalFragment_topicSelected_clickNoBtn_noBtnWorksCorrectly

**Review by anandwana001 — CHANGES_REQUESTED** [review]
nit changes

File: app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughTopicListFragmentTest.kt [hunk 15]
```diff
@@ -179,7 +179,7 @@ class WalkthroughTopicListFragmentTest {
   }
 
   @Test
-  fun testWalkthroughWelcomeFragment_recyclerViewIndex4_lessonThumbnailIsCorrect() {
+  fun testWalkthroughTopicListFragment_topicCard_lessonThumbnailIsCorrect() {
```
Comment (MaskedCarrot) [inline app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughTopicListFragmentTest.kt:182]: @anandwana001 should i make this ` testWalkthroughTopicListFragment_topicCardSelected_lessonThumbnailIsCorrect()`

File: app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughTopicListFragmentTest.kt [hunk 16]
```diff
@@ -106,7 +106,7 @@ class WalkthroughTopicListFragmentTest {
   }
 
   @Test
-  fun testWalkthroughWelcomeFragment_recyclerViewIndex0_topicHeader_topicHeaderIsCorrect() {
+  fun testWalkthroughTopicListFragment_topicHeader_whatDoYouWantToLearnIsDisplayed() {
```
Comment (MaskedCarrot) [inline app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughTopicListFragmentTest.kt:109]: will changing the name to `testWalkthroughTopicListFragment_topicHeaderSelected_whatDoYouWantToLearnIsDisplayed()` be meaningful?

Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughTopicListFragmentTest.kt:109]: keeping `testWalkthroughTopicListFragment_topicHeader_whatDoYouWantToLearnIsDisplayed` is also sounds good.
Is there anything blocking in this?

File: app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughFinalFragmentTest.kt (hunk 14 above)
Comment (MaskedCarrot) [reply app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughFinalFragmentTest.kt]: done

File: app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughFinalFragmentTest.kt (hunk 13 above)
Comment (MaskedCarrot) [reply app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughFinalFragmentTest.kt]: done

File: app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughFinalFragmentTest.kt (hunk 12 above)
Comment (MaskedCarrot) [reply app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughFinalFragmentTest.kt]: done

File: app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughFinalFragmentTest.kt (hunk 11 above)
Comment (MaskedCarrot) [reply app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughFinalFragmentTest.kt]: done

File: app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughFinalFragmentTest.kt (hunk 10 above)
Comment (MaskedCarrot) [reply app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughFinalFragmentTest.kt]: done

File: app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughTopicListFragmentTest.kt (hunk 16 above)
Comment (MaskedCarrot) [reply app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughTopicListFragmentTest.kt:109]: no there is nothing blocking this but since we are checking the topic header on recycler view index 0 I thought it would be better to use topicHeaderSelected

File: app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughTopicListFragmentTest.kt (hunk 15 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughTopicListFragmentTest.kt:182]: that way we have to make all `topicCardSelected` which might get repetitive. Going with the current one.

**Review by anandwana001 — APPROVED** [review]
LGTM, Thanks @MaskedCarrot

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.
