### PR TITLE
Fix #2947: Test cases are flaking in the FakeOppiaClockTest

### LINKED ISSUE #2947: Test cases are flaking in the FakeOppiaClockTest
**Describe the bug**
The test cases `testGetCurrentCalendar_wallClockMode_returnsCalendarWithCurrentTimeMillis()` and `testGetCurrentTimeMs_wallClockMode_returnsCurrentTimeMillis ` are flaky.

Failure error - 
```
expected to be in range: (1616173019436..1616173019440)
but was                : 1616173019440

	at org.oppia.android.testing.time.FakeOppiaClockTest.isWithin(FakeOppiaClockTest.kt:262)
	at org.oppia.android.testing.time.FakeOppiaClockTest.testGetCurrentCalendar_wallClockMode_returnsCalendarWithCurrentTimeMillis(FakeOppiaClockTest.kt:194)
```

**Expected behavior**
The test cases should always pass.

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.
When run 100 times, the test case failed 1 time - 
Screenshot from 2021-03-19 20-43-41

Sometimes failing on CI checks -
Screenshot from 2021-03-19 20-47-03

### PR DESCRIPTION
**Pull request by Karanjot-singh**
## Explanation
Fixes #2947: Delay between reported time and current time increased to 100m/s

## Screenshots of Tests
1. ``` testGetCurrentCalendar_wallClockMode_returnsCalendarWithCurrentTimeMillis()``` run 100 times

image

``` testGetCurrentCalendar_wallClockMode_returnsCalendarWithCurrentTimeMillis()``` run 1000 times

image

2. ```testGetCurrentTimeMs_wallClockMode_returnsCurrentTimeMillis()``` run 100 times

image

```testGetCurrentTimeMs_wallClockMode_returnsCurrentTimeMillis()``` run 1000 times

image

3. Complete Test File ```FakeOppiaClockTest.kt``` run 100 times

image

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by Karanjot-singh** [comment]
PTAL @anandwana001 @BenHenning

**Comment by anandwana001** [comment]
Assigning @prayutsu as he is the Issue author to take a loot initially, before the code owners.

File: testing/src/test/java/org/oppia/android/testing/time/FakeOppiaClockTest.kt [hunk 1]
```diff
@@ -136,7 +136,7 @@ class FakeOppiaClockTest {
 
     // Verify that the reported time is within 4ms of actual time (to provide some guard against
     // flakiness since this is testing real clock time).
```
Comment (prayutsu) [inline testing/src/test/java/org/oppia/android/testing/time/FakeOppiaClockTest.kt]: Replace 4 ms with 100 ms.

File: testing/src/test/java/org/oppia/android/testing/time/FakeOppiaClockTest.kt [hunk 2]
```diff
@@ -136,7 +136,7 @@ class FakeOppiaClockTest {
...
-    assertThat(reportedTimeMs).isWithin((currentTimeMs - 2)..(currentTimeMs + 2))
+    assertThat(reportedTimeMs).isWithin((currentTimeMs - 50)..(currentTimeMs + 50))
     // Sanity check that the fake is, indeed, using real clock time
     assertThat(reportedTimeMs).isNotEqualTo(0)
```
Comment (prayutsu) [inline testing/src/test/java/org/oppia/android/testing/time/FakeOppiaClockTest.kt:141]: Please add a '.' after the comment.

File: testing/src/test/java/org/oppia/android/testing/time/FakeOppiaClockTest.kt [hunk 3]
```diff
@@ -191,7 +191,7 @@ class FakeOppiaClockTest {
     val calendar = fakeOppiaClock.getCurrentCalendar()
 
     // The calendar should be inited to a value close to the clock time at the time it was created.
-    assertThat(calendar.timeInMillis).isWithin((currentTimeMs - 2)..(currentTimeMs + 2))
```
Comment (prayutsu) [inline testing/src/test/java/org/oppia/android/testing/time/FakeOppiaClockTest.kt:194]: Correct typo `inited` --> `initiated`.

**Review by prayutsu — CHANGES_REQUESTED** [review]
Left some comments. PTAL @Karanjot-singh

**Comment by prayutsu** [comment]
@anandwana001 @BenHenning I tested it locally and the flakes seem to be fixed now.

@Karanjot-singh Can you also add some screenshots where - 
1. The whole test file is run 100 times
2. flaky test 1 is run 1000 times in isolation.
3. flaky test 2 is run 1000 times in isolation.

**Comment by Karanjot-singh** [comment]
> @anandwana001 @BenHenning I tested it locally and the flakes seem to be fixed now.
> 
> @Karanjot-singh Can you also add some screenshots where - 
> 1. The whole test file is run 100 times
> 2. flaky test 1 is run 1000 times in isolation.
> 3. flaky test 2 is run 1000 times in isolation.

Sure, I will make these changes and add the extra screenshots in a few minutes.

**Comment by Karanjot-singh** [comment]
I have made the changes and added the screenshots. PTAL @prayutsu

**Review by prayutsu — APPROVED** [review]
LGTM, Thanks @Karanjot-singh

**Comment by prayutsu** [comment]
@Karanjot-singh The reviewed comments should only be resolved by one who initiated it (or if they explicitly ask you to resolve them) and if you made the suggested changes, you can reply - "Done" to the comments rather than resolving it.
Unresolved comments help the reviewers to keep the track of the suggested changes as the reviewers don't go through the resolved conversations.

Thanks!

**Comment by Karanjot-singh** [comment]
> @Karanjot-singh The reviewed comments should only be resolved by one who initiated it (or if they explicitly ask you to resolve them) and if you made the suggested changes, you can reply - "Done" to the comments rather than resolving it.
> Unresolved comments help the reviewers to keep the track of the suggested changes as the reviewers don't go through the resolved conversations.
> 
> Thanks!

Noted! Will definitely take care of that.

**Review by BenHenning — APPROVED** [review]
Thanks @Karanjot-singh!
