### PR TITLE
Fix #5615 : Scroll Position For Policies Screen On Orientation Change

### LINKED ISSUE #5615: [BUG]: Privacy Policy Scroll Resets on Orientation Change
### Describe the bug

When Viewing The Privacy Policy Page, If I Scroll Down The Content And Then Change The Screen Orientation (E.g., From Portrait To Landscape Or Vice Versa), The Scroll Position Resets, And The Page Jumps Back To The Top Of The Screen.

### Steps To Reproduce

1. Open The Oppia Android App.
2. Navigate To The Privacy Policy Page.
3. Scroll Down The Content Of The Privacy Policy.
4. Change The Device's Orientation (Portrait To Landscape Or Landscape To Portrait).
5. Observe That The Page Scroll Position Resets To The Top, Rather Than Maintaining The Previously Scrolled Position.

### Expected Behavior

The Page Should Retain Its Scroll Position Even After Changing The Device's Orientation. The User Should Not Be Forced To Scroll Back Down To Their Previous Position.

### Screenshots/Videos

[Screen_recording_20241222_231207.webm](https://github.com/user-attachments/assets/11a3b285-749e-4def-9358-eb5662f5dadc)

### What device/emulator are you using?

Pixel 8 Pro

### Which Android version is your device/emulator running?

Android 11

### Which version of the Oppia Android app are you using?

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by TanishMoral11**
## Explanation
This PR fixes #5615   the issue where the scroll position in the policies screen (Privacy Policy/Terms of Service) would reset after an orientation change.

### **Changes Made:**
1. **Updated `PoliciesFragmentPresenter`:**
   - Added a `scrollPosition` property to save and restore the scroll state.
   - Implemented `onSaveInstanceState` and `onRestoreInstanceState` handling using a constant key.
   - Ensured the scroll position is retained using `ScrollView.viewTreeObserver` in `onGlobalLayoutListener`.

2. **Modified `PoliciesFragment`:**
   - Delegated `onSaveInstanceState` calls to the presenter.
   - Passed the saved instance state to the presenter during fragment view creation.

### **Testing Performed:**
- Verified that scroll position is correctly retained:
  - Across orientation changes (portrait ↔️ landscape).
  - On both Privacy Policy and Terms of Service screens
---

## Essential Checklist
- [x] The PR title and explanation each start with "Fix #bugnum: ".
- [x] No unnecessary code changes or Android Studio formatting changes are included.
- [x] The branch is **not** called "develop" and is up-to-date with "develop".
- [x] Appropriate reviewers are assigned.

---

After Changes :
[Screen_recording_20241223_010758.webm](https://github.com/user-attachments/assets/f9648b03-5b27-4090-9eaa-82946214cd62)

### CODE REVIEW

**Comment by TanishMoral11** [comment]
Hey @adhiamboperes , PTAL

**Comment by TanishMoral11** [comment]
Hey @adhiamboperes , This PR is Ready For Review , PTAL.

**Comment by TanishMoral11** [comment]
Hey @adhiamboperes PTAL !!

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @TanishMoral11! 
While this implementation looks good, these kind of UI changes require UI tests. While I am not exactly sure the exact way to test this, I would suggest a test that replicates the bug e.g. launch screen > scroll to a specific test > perform orientation change> assert that that specific text or position is displayed.

**Comment by TanishMoral11** [comment]
Hey @adhiamboperes , PTAL !! 

Image

File: app/src/main/java/org/oppia/android/app/policies/PoliciesFragmentPresenter.kt [hunk 1]
```diff
@@ -22,22 +24,39 @@ class PoliciesFragmentPresenter @Inject constructor(
...
     setUpContentForTextViews(policiesFragmentArguments.policyPage, binding)
 
+    (binding.root as ScrollView).viewTreeObserver.addOnGlobalLayoutListener {
+      binding.root.scrollTo(0, scrollPosition)
+    }
+
     return binding.root
   }
 
+  fun handleSaveInstanceState(outState: Bundle) {
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/policies/PoliciesFragmentPresenter.kt:59]: This public function needs a kdoc.

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @TanishMoral11! Just one comment left to wrap this up

**Comment by TanishMoral11** [comment]
Hey @adhiamboperes, PTAL !!

File: app/src/main/java/org/oppia/android/app/policies/PoliciesFragmentPresenter.kt (hunk 1 above)
Comment (TanishMoral11) [reply app/src/main/java/org/oppia/android/app/policies/PoliciesFragmentPresenter.kt:59]: Done .

**Review by adhiamboperes — APPROVED** [review]
Thanks @TanishMoral11! LGTM.
