### PR TITLE
Fix part of #1824: Add chapter dash line

### LINKED ISSUE #1824: Lowfi: Tablet: StoryActivity Landscape + Portrait
This issue is tracking the full low-fi work of `StoryActivity` Tablet (Landscape + Portrait)

Mock: https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/screen/64ef596d-f0ee-48fe-afc2-2ae40367e382/
https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/screen/d70a3ade-826a-4ac6-95e6-907a24d7b896/

Major work items:
- [ ] Vertical dash line with progress
- [x] Inactive card - lock/blur effect.
- [ ] RTL Supportive
**Note : Please test UI for RTL support, prior to merging this fix.**

### PR DESCRIPTION
**Pull request by viktoriias**
## Explanation

Fix #1824.
This is the updated copy of https://github.com/oppia/oppia-android/pull/3066

#### What's new:
- Minor UI adjustments
- Added a separate activity and layout for `ImageViewBindingAdaptersTest`. 
- Introduce a dedicated BUILD.bazel file for the new test suite, and then set up a genrule to replace the import of the adapters with the _updated variant.

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### CODE REVIEW

**Comment by viktoriias** [comment]
@rt4914 @BenHenning Please review.

**Comment by BenHenning** [comment]
Thanks @viktoriias. Sorry for not following up on Friday. I'll need one more day before I can take a look at this. In the mean time, could you resolve the conflicts & merge in the latest develop changes?

**Review by rt4914 — APPROVED** [review]
Looks really nice. Please make following changes:
1. Add `Fix part of #1824` in description
2. Add mobile/tablet scrrenshots in various configurations.

Otherwise LGTM

**Comment by viktoriias** [comment]
Phone (no change):

**Comment by viktoriias** [comment]
Tablet:

**Comment by viktoriias** [comment]
> Looks really nice. Please make following changes:
> 
> 1. Add `Fix part of #1824` in description
> 2. Add mobile/tablet scrrenshots in various configurations.
> 
> Otherwise LGTM

Done and done. Thanks!

File: app/src/main/java/org/oppia/android/app/customview/VerticalDashedLineView.kt [hunk 1]
```diff
@@ -0,0 +1,63 @@
...
+    val dashLength: Float = dpToPx(DASH_LENGTH_IN_DP)
+    val dashThickness: Float = dpToPx(DASH_THICKNESS_IN_DP)
+
+    paint = Paint()
+    paint.isAntiAlias = true
+    paint.color = ContextCompat.getColor(context, R.color.colorPrimary)
+    paint.style = Paint.Style.STROKE
+    paint.strokeCap = Paint.Cap.ROUND
+    paint.strokeWidth = dashThickness
+    paint.pathEffect = DashPathEffect(floatArrayOf(dashLength, dashGap), /* phase= */ 0F)
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/customview/VerticalDashedLineView.kt]:
```suggestion
    paint = Paint().apply {
      isAntiAlias = true
      color = ContextCompat.getColor(context, R.color.colorPrimary)
      style = Paint.Style.STROKE
      strokeCap = Paint.Cap.ROUND
      strokeWidth = dashThickness
      pathEffect = DashPathEffect(floatArrayOf(dashLength, dashGap), /* phase= */ 0F)
    }
```

Bit more Kotlin idiomatic.

File: app/src/main/java/org/oppia/android/app/databinding/ImageViewBindingAdapters.java [hunk 2]
```diff
@@ -43,6 +44,29 @@ public static void setImageDrawable(
     imageView.setImageResource(drawableResourceId);
   }
 
+  /**
+   * Binds a drawable indicated by {@link ChapterPlayState} to an {@link ImageView} via
+   * "android:src".
+   * Reference: https://stackoverflow.com/a/35809319/3689782.
+   */
+  @BindingAdapter("android:src")
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/databinding/ImageViewBindingAdapters.java]: Could you maybe customize this so that it's not overloading android:src? I actually have a PR coming that's prohibiting using android:src for drawables, and this isn't really the same meaning of android:src, anyway. Suggest instead: playState:image (see profile:src for an example on how to use a custom namespace).

Also, please update the binding method name, too (e.g. to setPlayStateDrawable or similar).

File: app/src/main/java/org/oppia/android/app/databinding/ImageViewBindingAdapters.java [hunk 3]
```diff
@@ -43,6 +44,29 @@ public static void setImageDrawable(
     imageView.setImageResource(drawableResourceId);
   }
 
+  /**
+   * Binds a drawable indicated by {@link ChapterPlayState} to an {@link ImageView} via
+   * "android:src".
+   * Reference: https://stackoverflow.com/a/35809319/3689782.
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/databinding/ImageViewBindingAdapters.java]: Nit: blank doc line before this.

File: app/src/sharedTest/java/org/oppia/android/app/databinding/ImageViewBindingAdaptersTest.kt [hunk 4]
```diff
@@ -0,0 +1,245 @@
...
+/** Tests for [ImageViewBindingAdaptersTest]. */
+@RunWith(AndroidJUnit4::class)
+@LooperMode(LooperMode.Mode.PAUSED)
+@Config(
+  application = ImageViewBindingAdaptersTest.TestApplication::class,
+  qualifiers = "port-xxhdpi"
+)
+class ImageViewBindingAdaptersTest {
+
+  // TODO(#3059): Add more tests for other BindableAdapters present in [ImageViewBindingAdapters].
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/databinding/ImageViewBindingAdaptersTest.kt:96]: Thanks for adding this TODO.

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @viktoriias! This does look quite nice.

Had a couple of comments, plus a few additional questions:
1. Can you please update the PR description to explain what's left in #1824 after this is merged?
2. Follow-up from (1), do we still need to implement the empty circles & later dashed lines per the mocks for not-yet-completed chapters, or should that be completed in this PR? I'm asking because per your screenshots it seems that the line doesn't go to the bottom of the chapter list yet,
3. Follow-up from (3), if this isn't complete yet, we should hide it behind a platform parameter flag until it's ready to be enabled (just to avoid a half-complete thing being merged)
4. Was https://github.com/oppia/oppia-android/issues/1824#issuecomment-874868992 accounted for in this PR, or would that happen in a follow-up?
5. Could you please update this PR with the latest develop & resolve the conflict?

File: app/src/main/java/org/oppia/android/app/databinding/ImageViewBindingAdapters.java (hunk 3 above)
Comment (viktoriias) [reply app/src/main/java/org/oppia/android/app/databinding/ImageViewBindingAdapters.java]: Done

File: app/src/main/java/org/oppia/android/app/databinding/ImageViewBindingAdapters.java (hunk 2 above)
Comment (viktoriias) [reply app/src/main/java/org/oppia/android/app/databinding/ImageViewBindingAdapters.java]: Done.

**Comment by viktoriias** [comment]
> 1. Can you please update the PR description to explain what's left in #1824 after this is merged?

Done

> 2 Follow-up from (1), do we still need to implement the empty circles & later dashed lines per the mocks for not-yet-completed chapters, or should that be completed in this PR? I'm asking because per your screenshots it seems that the line doesn't go to the bottom of the chapter list yet.

Mocks have 3 chapters, so the line looks longer. It ends at the beginning of the last chapter.

> 3 Follow-up from (3), if this isn't complete yet, we should hide it behind a platform parameter flag until it's ready to be enabled (just to avoid a half-complete thing being merged)

I believe it's lowfi complete.

> 4 Was [#1824 (comment)](https://github.com/oppia/oppia-android/issues/1824#issuecomment-874868992) accounted for in this PR, or would that happen in a follow-up?

RTL support was listed as a separate item in #1824, but I'll add RTL screenshots

> 5 Could you please update this PR with the latest develop & resolve the conflict?

Done

**Comment by viktoriias** [comment]
RTL Tablet:

**Comment by BenHenning** [comment]
> > 1. Can you please update the PR description to explain what's left in [Lowfi: Tablet: StoryActivity Landscape + Portrait #1824](https://github.com/oppia/oppia-android/issues/1824) after this is merged?
> 
> Done
> 
> > 2 Follow-up from (1), do we still need to implement the empty circles & later dashed lines per the mocks for not-yet-completed chapters, or should that be completed in this PR? I'm asking because per your screenshots it seems that the line doesn't go to the bottom of the chapter list yet.
> 
> Mocks have 3 chapters, so the line looks longer. It ends at the beginning of the last chapter.
> 
> > 3 Follow-up from (3), if this isn't complete yet, we should hide it behind a platform parameter flag until it's ready to be enabled (just to avoid a half-complete thing being merged)
> 
> I believe it's lowfi complete.
> 
> > 4 Was [#1824 (comment)](https://github.com/oppia/oppia-android/issues/1824#issuecomment-874868992) accounted for in this PR, or would that happen in a follow-up?
> 
> RTL support was listed as a separate item in #1824, but I'll add RTL screenshots
> 
> > 5 Could you please update this PR with the latest develop & resolve the conflict?
> 
> Done

Thanks for clarifying. A couple of points:
- ImageViewBindingAdaptersTest will need to be passing on both Gradle & Robolectric before we can merge this PR, so that's probably not actually a "what's left" in the PR description since it's a prerequisite to merging
- I was actually interested in what other UI work is needed here. It seems as though the UI implementation is incomplete since there's no empty circle on the last card. Can you clarify the remaining work needed at the UI level in the PR description?
- Should there be an open circle at the top of the line for the initial card before it's started?
- Can you upload a screenshot demonstrating progress for more than 2 cards since there's supposed to be a circle for each card per the mocks

**Comment by viktoriias** [comment]
> * ImageViewBindingAdaptersTest will need to be passing on both Gradle & Robolectric before we can merge this PR, so that's probably not actually a "what's left" in the PR description since it's a prerequisite to merging

I was referring to this paragraph:

"Once that's working, I can take an attempt on trying to make this work for Bazel as well (which will require additional work since at the moment we don't support databinding in tests, but I think this will be possible since we'll need to introduce new test-only layouts to make the above work)."

https://github.com/oppia/oppia-android/pull/3066#issuecomment-819879523

> * I was actually interested in what other UI work is needed here. It seems as though the UI implementation is incomplete since there's no empty circle on the last card. Can you clarify the remaining work needed at the UI level in the PR description?
> * Should there be an open circle at the top of the line for the initial card before it's started?
> * Can you upload a screenshot demonstrating progress for more than 2 cards since there's supposed to be a circle for each card per the mocks

I don't have a story with more than 2 chapters.. @rt4914 Could you confirm the UI part?

File: app/src/main/res/layout/test_image_view_bindable_adapter_activity.xml [hunk 5]
```diff
@@ -0,0 +1,9 @@
+<?xml version="1.0" encoding="utf-8"?>
+<layout xmlns:android="http://schemas.android.com/apk/res/android">
```
Comment (anandwana001) [inline app/src/main/res/layout/test_image_view_bindable_adapter_activity.xml]: Do we need to wrap this UI in layout tag or we can simply go with ImageView as a parent layout?
Wrapping the layout tag internally creates its corresponding BindingAdapter class which affects building time.

File: app/src/sharedTest/java/org/oppia/android/app/databinding/ImageViewBindingAdaptersTest.kt [hunk 6]
```diff
@@ -0,0 +1,245 @@
...
+  }
+
+  @After
+  fun tearDown() {
+    Intents.release()
+  }
+
+  @Test
+  fun testSetPlayStateDrawableWithChapterPlayState_completedState_hasCorrectDrawable() {
+    activityRule.scenario.runWithActivity {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/databinding/ImageViewBindingAdaptersTest.kt:123]: Could you please add a screenshot showing that these tests are passing on espresso?

File: app/src/sharedTest/java/org/oppia/android/app/databinding/ImageViewBindingAdaptersTest.kt [hunk 7]
```diff
@@ -0,0 +1,245 @@
...
+      onView(withId(R.id.image_view_for_data_binding)).check(
+        matches(withDrawable(R.drawable.circular_solid_color_primary_32dp))
+      )
+    }
+  }
+
+  @Test
+  fun testSetPlayStateDrawableWithChapterPlayState_notStartedState_hasCorrectDrawable() {
+    activityRule.scenario.runWithActivity {
+      val imageView: ImageView = it.findViewById(R.id.image_view_for_data_binding)
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/databinding/ImageViewBindingAdaptersTest.kt]: As we will be using this image view for this whole test suite, we can create a helper function which will return the image view. 

```kt
  private fun getImageView(
    imageViewBindingAdaptersTestActivity: ImageViewBindingAdaptersTestActivity
  ): ImageView {
    return imageViewBindingAdaptersTestActivity.findViewById(R.id.image_view_for_data_binding)
  }
```

**Review by anandwana001 — CHANGES_REQUESTED** [review]
Could you try building APK using bazel and check if this feature is working or not? 
Run these bazel commands and 
Steps:
1. Run - `bazel build //:oppia_dev`
2.  Either start an emulator or attach the device. 
3. Run - `bazel run //:install_oppia_dev`

**Comment by viktoriias** [comment]
Passing tests:
Screen Shot 2021-10-07 at 10 17 45 AM

File: app/src/sharedTest/java/org/oppia/android/app/databinding/ImageViewBindingAdaptersTest.kt (hunk 6 above)
Comment (viktoriias) [reply app/src/sharedTest/java/org/oppia/android/app/databinding/ImageViewBindingAdaptersTest.kt:123]: Done

File: app/src/main/res/layout/test_image_view_bindable_adapter_activity.xml (hunk 5 above)
Comment (viktoriias) [reply app/src/main/res/layout/test_image_view_bindable_adapter_activity.xml]: Made a change, PTAL.
I also added a TODO comment that I saw in similar files.

File: app/src/sharedTest/java/org/oppia/android/app/databinding/ImageViewBindingAdaptersTest.kt (hunk 7 above)
Comment (viktoriias) [reply app/src/sharedTest/java/org/oppia/android/app/databinding/ImageViewBindingAdaptersTest.kt]: Done

**Comment by BenHenning** [comment]
Some from meeting, I think there are a few other things to complete here:
1. The incomplete circle seems a lot fainter than the mocks (I didn't even realize it was there until I saw it on another screen because it is almost invisible on some screens due to low contrast)
2. We should double check the accessibility scenario here (i.e. running a11y scanner, and using TalkBack to verify that the elements are either ignored or announced properly; I'm assuming they should be ignored in this case). See: https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide#setting-up-accessibility-scanner-and-talkback.
3. I suggest implementing the high-fidelity version right away so that we aren't just pushing that work back (& that might also mean that we can mark #1824 as fully fixed -- @rt4914 can you confirm?). It seems preferable now that the app is getting released to people on a semi-regular basis that all UI changes are effectively high fidelity from initial implementation at this point.
4. For the test failure, I think an easier route might be to introduce a dedicated BUILD.bazel file for the new test suite, and then set up a genrule to replace the import of the adapters with the _updated variant. See https://github.com/oppia/oppia-android/blob/f9eb3cdcba174fdd78690af33ffe3c7a8b547a10/app/test_with_resources.bzl and https://github.com/oppia/oppia-android/blob/3a0afb4eb8222d4ff3acd2e2e660b85911d35229/app/src/main/java/org/oppia/android/app/utility/datetime/BUILD.bazel for an idea on how genrules are setup.

Some other resources that might be helpful
- Bazel setup instructions: https://github.com/oppia/oppia-android/wiki/Oppia-Bazel-Setup-Instructions#installation
- Another non-glob defined test that you effectively copy & paste to get started on introducing a new target for the new test: https://github.com/oppia/oppia-android/blob/3a0afb4eb8222d4ff3acd2e2e660b85911d35229/app/src/test/java/org/oppia/android/app/activity/BUILD.bazel

**Comment by rt4914** [comment]
@BenHenning @viktoriias 

For testing the UI for more than 2 explorations I updated `test_story_id_0.json` file in `domain/assets` to [following](https://gist.github.com/rt4914/10f4f6af435de26ea615116f73c1af2e).

The results were as follows:
   
   


For `A11Y` I will need some time for check that correctly.

**Comment by rt4914** [comment]
@viktoriias Using[ these steps](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide#setup-play-store-in-tablet-emulator) I was able to start the  `A11y Scanner` and `Talkback` but it consumes a lot of memory because of which the emulator goes into ANR state.
To make it work I copied the UI from `sw600dp` file and used it for mobile-portrait. The output was following:
1. A11Y scanner is passing for this PR. (Basically it is failing for dummy content only which is not part of this PR)
2. Talkback is not selecting is the `vertical-dashed` line which is actually correct for our case. FYI the output is not correct but that's not because of this PR. There is already an issue filed for this: https://github.com/oppia/oppia-android/issues/3898

**Accessibility Scanner Output**


**Talkback Output**
https://user-images.githubusercontent.com/9396084/136610137-514859fb-b603-4eda-9a72-b62e5f9739f1.mp4

**Comment by viktoriias** [comment]
I lowered the circles and made a grey circle a little more visible. Latest screenshot:

Screenshot_1633743773

**Comment by BenHenning** [comment]
Sorry, I'll need to review this on Monday.

File: app/src/main/res/layout-sw600dp/story_fragment.xml [hunk 8]
```diff
@@ -67,11 +67,14 @@
 
       <androidx.recyclerview.widget.RecyclerView
         android:id="@+id/story_chapter_list"
-        android:layout_width="match_parent"
+        android:layout_width="528dp"
```
Comment (BenHenning) [inline app/src/main/res/layout-sw600dp/story_fragment.xml:70]: This seems a bit awkward. All we know is that the smallest width is 600dp, do we actually want to fix this to 528dp?

File: app/src/main/res/values/dimens.xml [hunk 9]
```diff
@@ -517,6 +517,9 @@
   <!-- Topic Lessons Fragment -->
   <dimen name="topic_lessons_fragment_layout_padding_bottom">128dp</dimen>
 
+  <!-- Story Chapter View Tablet -->
+  <dimen name="story_chapter_view_tablet_margin_top_first_item">20dp</dimen>
```
Comment (BenHenning) [inline app/src/main/res/values/dimens.xml]: @rt4914 should we be defining tablet-specific dimensions like this (vs. having a variant in values-sw600dp/dimens.xml)?

File: app/src/main/res/layout-sw600dp/story_chapter_view.xml [hunk 10]
```diff
@@ -1,12 +1,13 @@
 <?xml version="1.0" encoding="utf-8"?>
 <layout xmlns:android="http://schemas.android.com/apk/res/android"
-  xmlns:app="http://schemas.android.com/apk/res-auto">
+  xmlns:app="http://schemas.android.com/apk/res-auto"
```
Comment (BenHenning) [inline app/src/main/res/layout-sw600dp/story_chapter_view.xml:3]: Why does only this file need to change vs. the other story_chapter_view layouts?

File: app/src/sharedTest/java/org/oppia/android/app/databinding/BUILD.bazel [hunk 11]
```diff
@@ -0,0 +1,50 @@
...
+load("//:oppia_android_test.bzl", "oppia_android_test")
+
+# Resource shim needed so that tests can build in both Gradle & Bazel.
+genrule(
+    name = "update_ImageViewBindingAdaptersTest",
+    srcs = ["ImageViewBindingAdaptersTest.kt"],
+    outs = ["ImageViewBindingAdaptersTest_updated.kt"],
+    cmd = """
+    cat $(SRCS) |
+    sed 's/import org.oppia.android.R/import org.oppia.android.app.test.R/g' |
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/databinding/BUILD.bazel]: The new R import should be ``org.oppia.android.app.databinding`` per the custom_package being set below.

File: app/src/sharedTest/java/org/oppia/android/app/databinding/BUILD.bazel [hunk 12]
```diff
@@ -0,0 +1,50 @@
+"""
+Tests for databinding.
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/databinding/BUILD.bazel]:
```suggestion
Tests for UI databinding utilities and adapters.
```

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @viktoriias. The StateFragmentLocalTest CI failure is a known flake.

Otherwise, left some comments. The approach generally LGTM, at this point I'm mainly interested in seeing CI pass.

File: app/src/sharedTest/java/org/oppia/android/app/databinding/BUILD.bazel (hunk 11 above)
Comment (viktoriias) [reply app/src/sharedTest/java/org/oppia/android/app/databinding/BUILD.bazel]: Done.

File: app/src/main/res/layout-sw600dp/story_chapter_view.xml (hunk 10 above)
Comment (viktoriias) [reply app/src/main/res/layout-sw600dp/story_chapter_view.xml:3]: Because this UI only applies to the tablet.

File: app/src/main/res/layout-sw600dp/story_fragment.xml (hunk 8 above)
Comment (viktoriias) [reply app/src/main/res/layout-sw600dp/story_fragment.xml:70]: This change came from the original https://github.com/oppia/oppia-android/pull/3066. @rt4914 Do you remember why you chose 528dp?

**Comment by anandwana001** [comment]
> Passing tests: Screen Shot 2021-10-07 at 10 17 45 AM

Could you please also add for `app/src/sharedTest/java/org/oppia/android/app/story/StoryFragmentTest.kt` test file as there are new tests introduced.

**Comment by viktoriias** [comment]
> Could you please also add for app/src/sharedTest/java/org/oppia/android/app/story/StoryFragmentTest.kt test file as there are new tests introduced.

Oh right:
Screen Shot 2021-10-14 at 7 38 12 PM

**Review by anandwana001 — APPROVED** [review]
Codeowner file LGTM

File: app/src/main/res/layout-sw600dp/story_fragment.xml (hunk 8 above)
Comment (rt4914) [reply app/src/main/res/layout-sw600dp/story_fragment.xml:70]: Actually there are two ways to work on such an UIs
1. Make margins fixed and content width variable.
2. Make content width fixed and margins variable.

From the mocks that we have it is clear that irrespective of screen size the content width is fixed and margins are variable. And therefore we fixed it to 528dp. 
Also it's actually nice as it guarantees that UI will looks consistent across all tablet devices.

 If we make margins fixed then on smallest tablet devices it does look really bad which is one issue that we are facing currently on various activities.

File: app/src/main/res/values/dimens.xml (hunk 9 above)
Comment (viktoriias) [reply app/src/main/res/values/dimens.xml]: Changed this to variant in dimens.xml

**Comment by BenHenning** [comment]
Sorry @viktoriias will need to review this on Monday.

File: app/src/main/res/layout-sw600dp/story_chapter_view.xml (hunk 10 above)
Comment (BenHenning) [reply app/src/main/res/layout-sw600dp/story_chapter_view.xml:3]: Ah, I didn't realize this was only meant to be for tablets.

File: app/src/sharedTest/java/org/oppia/android/app/databinding/BUILD.bazel [hunk 13]
```diff
@@ -0,0 +1,51 @@
+"""
+Tests for UI databinding utilities and adapters.
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/databinding/BUILD.bazel:2]: Ah, there's unfortunately one more thing that we'll need to do.

Now that this file is being introduced, we need to add oppia_android_test targets for each of the other tests in this package (otherwise they won't be included in the Bazel test run anymore). Can you please add those? Per https://github.com/oppia/oppia-android/tree/develop/app/src/sharedTest/java/org/oppia/android/app/databinding I think there are more 4 test targets that need to be added.

File: app/src/main/res/layout-sw600dp/story_fragment.xml (hunk 8 above)
Comment (BenHenning) [reply app/src/main/res/layout-sw600dp/story_fragment.xml:70]: Got it, thanks for the explanation.

**Review by BenHenning — COMMENTED** [review]
Thanks @viktoriias. This looks good to me, but we do have one more Bazel change that needs to be made before it can be merged. PTAL at my new comment.

File: app/src/sharedTest/java/org/oppia/android/app/databinding/BUILD.bazel (hunk 13 above)
Comment (viktoriias) [reply app/src/sharedTest/java/org/oppia/android/app/databinding/BUILD.bazel:2]: Done, added 4 more test targets with genrule.
StateFragmentLocalTest is failing now, not sure why..

**Comment by BenHenning** [comment]
Sorry, will need to review this tomorrow.

**Comment by BenHenning** [comment]
Also @viktoriias there are failing CI checks--are they related to the latest changes?

**Comment by viktoriias** [comment]
> Also @viktoriias there are failing CI checks--are they related to the latest changes?

`StateFragmentLocalTest` is failing and it doesn't seem related.

File: app/src/sharedTest/java/org/oppia/android/app/databinding/BUILD.bazel [hunk 14]
```diff
@@ -24,28 +69,43 @@ oppia_android_test(
...
+    deps = TEST_DEPS,
+)
+
+oppia_android_test(
+    name = "MarginBindingAdaptersTest",
+    srcs = ["MarginBindingAdaptersTest_updated.kt"],
+    custom_package = "org.oppia.android.app.databinding",
+    test_class = "org.oppia.android.app.databinding.MarginBindingAdaptersTest",
+    test_manifest = "//app:test_manifest",
+    deps = TEST_DEPS,
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/databinding/BUILD.bazel]: Prefer not sharing test deps, actually. It's easier to manage dependencies when they're unique across tests, especially during migrations. We share deps for top-level tests because we have to.

File: app/src/sharedTest/java/org/oppia/android/app/databinding/BUILD.bazel [hunk 15]
```diff
@@ -5,7 +5,52 @@ Tests for UI databinding utilities and adapters.
...
+    "//third_party:org_robolectric_robolectric",
+    "//third_party:robolectric_android-all",
+    "//utility/src/main/java/org/oppia/android/util/accessibility:test_module",
+    "//utility/src/main/java/org/oppia/android/util/caching/testing:caching_test_module",
+    "//utility/src/main/java/org/oppia/android/util/data:data_providers",
+    "//utility/src/main/java/org/oppia/android/util/logging:prod_module",
+]
+
 # Resource shim needed so that tests can build in both Gradle & Bazel.
+TEST_FILES = [
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/databinding/BUILD.bazel]: Nit: ``_TEST_FILES`` (it's conventional to prefix 'private' Bazel members using a '_' prefix).

File: app/src/sharedTest/java/org/oppia/android/app/databinding/BUILD.bazel (hunk 13 above)
Comment (BenHenning) [reply app/src/sharedTest/java/org/oppia/android/app/databinding/BUILD.bazel:2]: Thanks! I'll take a look and follow up with a PR comment reply.

**Review by BenHenning — COMMENTED** [review]
Thanks @viktoriias. Just had a few follow-up comments, otherwise this is looking really good.

Re: the failure, it's probably #2844 and unrelated to this PR. Just to be sure, though, I re-ran the workflow to see if it will now pass.

**Comment by BenHenning** [comment]
Hmm it failed again, interesting. @viktoriias does it pass for you locally without issue? If possible, could you try running the same set of tests as the failing shard to see if that also passes for you? Specifically:

```
bazel test --keep_going -- //app:src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileListFragmentTest //app:src/sharedTest/java/org/oppia/android/app/profileprogress/ProfileProgressActivityTest //app:src/sharedTest/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragmentTest //app:src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughActivityTest //app:src/sharedTest/java/org/oppia/android/app/player/audio/AudioFragmentTest //app:src/sharedTest/java/org/oppia/android/app/customview/LessonThumbnailImageViewTest //app:src/sharedTest/java/org/oppia/android/app/thirdparty/LicenseTextViewerActivityTest //app:src/sharedTest/java/org/oppia/android/app/devoptions/MarkChaptersCompletedActivityTest //app:src/sharedTest/java/org/oppia/android/app/home/RecentlyPlayedFragmentTest //app:src/sharedTest/java/org/oppia/android/app/devoptions/DeveloperOptionsActivityTest //app/src/test/java/org/oppia/android/app/activity:ActivityIntentFactoriesTest //app:src/sharedTest/java/org/oppia/android/app/topic/lessons/TopicLessonsFragmentTest //app:src/sharedTest/java/org/oppia/android/app/options/AudioLanguageFragmentTest //app:src/test/java/org/oppia/android/app/player/state/StateFragmentLocalTest //app:src/sharedTest/java/org/oppia/android/app/thirdparty/ThirdPartyDependencyListFragmentTest
```

If this is CI-specific, we may need to introduce a retry mechanism also on the run step (which I've been considering to work around this specific flake). I can do that in a separate PR, but I first want to see if this is specific to CI.

File: app/src/sharedTest/java/org/oppia/android/app/databinding/BUILD.bazel (hunk 15 above)
Comment (viktoriias) [reply app/src/sharedTest/java/org/oppia/android/app/databinding/BUILD.bazel]: Done

File: app/src/sharedTest/java/org/oppia/android/app/databinding/BUILD.bazel (hunk 14 above)
Comment (viktoriias) [reply app/src/sharedTest/java/org/oppia/android/app/databinding/BUILD.bazel]: Done

**Comment by viktoriias** [comment]
> Hmm it failed again, interesting. @viktoriias does it pass for you locally without issue? If possible, could you try running the same set of tests as the failing shard to see if that also passes for you? Specifically:
> 
> ```
> bazel test --keep_going -- //app:src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileListFragmentTest //app:src/sharedTest/java/org/oppia/android/app/profileprogress/ProfileProgressActivityTest //app:src/sharedTest/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragmentTest //app:src/sharedTest/java/org/oppia/android/app/walkthrough/WalkthroughActivityTest //app:src/sharedTest/java/org/oppia/android/app/player/audio/AudioFragmentTest //app:src/sharedTest/java/org/oppia/android/app/customview/LessonThumbnailImageViewTest //app:src/sharedTest/java/org/oppia/android/app/thirdparty/LicenseTextViewerActivityTest //app:src/sharedTest/java/org/oppia/android/app/devoptions/MarkChaptersCompletedActivityTest //app:src/sharedTest/java/org/oppia/android/app/home/RecentlyPlayedFragmentTest //app:src/sharedTest/java/org/oppia/android/app/devoptions/DeveloperOptionsActivityTest //app/src/test/java/org/oppia/android/app/activity:ActivityIntentFactoriesTest //app:src/sharedTest/java/org/oppia/android/app/topic/lessons/TopicLessonsFragmentTest //app:src/sharedTest/java/org/oppia/android/app/options/AudioLanguageFragmentTest //app:src/test/java/org/oppia/android/app/player/state/StateFragmentLocalTest //app:src/sharedTest/java/org/oppia/android/app/thirdparty/ThirdPartyDependencyListFragmentTest
> ```
> 
> If this is CI-specific, we may need to introduce a retry mechanism also on the run step (which I've been considering to work around this specific flake). I can do that in a separate PR, but I first want to see if this is specific to CI.

Checks are passing now

**Review by BenHenning — APPROVED** [review]
Thanks @viktoriias. This looks really good!

**Comment by BenHenning** [comment]
Merging since approvals seem complete & CI is passing.
