### PR TITLE
Fix #3410: Merged Switch click with TextViews in ProfileEditActivity

### LINKED ISSUE #3130: Administrator controls toggle radio buttons by clicking on the complete item
**Describe the bug**
Toggle Radio button by clicking on the `topic_update_on_wifi_constraint_layout` and `auto_update_topic_constraint_layout`

**To Reproduce**
1. Go to 'Administrator Controls'
2. Click on 'Download and update only on Wifi'
3. The radio button is not changed

**Expected behavior**
To be able to toggle the radio button by clicking anywhere on the view.

**Screenshots**
image

### LINKED ISSUE #3410: ProfileEdit toggle radio buttons by clicking on the complete item
**Describe the bug**
Make the radio button with text a clickable to toggle the radio button (Allow Download Access) in the ProfileEdit 

**To Reproduce**
1. Go to 'ProfileEdit '
2. Click on Text on the left of radio button
3. See that the radio button is not changed

**Expected behavior**
Toggle radio button by clicking on its corresponding text.

Similar to #3131

### PR DESCRIPTION
**Pull request by rt4914**
## Explanation

Fix #3410: Merged Switch click with TextViews in ProfileEditActivity

Similar to https://github.com/oppia/oppia-android/pull/3191 , this PR also merged the textviews with switch to make the entire area clickable. So basically `Switch + 2 Texts` are clickable.

## Tests
Screenshot 2021-07-05 at 8 46 24 PM

## Accessibility Output

Earlier the screen reader would first read the title, then subtext and then finally the switch, i.e. it took 3 steps.

Now it merges all of that into 1 single step:
  

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

File: app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt [hunk 1]
```diff
@@ -427,6 +429,105 @@ class ProfileEditActivityTest {
...
+    }
+  }
+
+  @Test
+  fun testProfileEdit_startWithUserHasDownloadAccess_switchIsNotClickable() {
+    profileManagementController.addProfile(
+      name = "James",
+      pin = "123",
+      avatarImagePath = null,
+      allowDownloadAccess = true,
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt:461]: having download access but not able to click? is this correct?

**Review by anandwana001 — CHANGES_REQUESTED** [review]

File: app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt (hunk 1 above)
Comment (rt4914) [reply app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt:461]: Yes, we are just checking that `Switch` is not clickable instead the entire container is clickable which is written as test in above `testProfileEdit_startWithUserHasDownloadAccess_clickAllowDownloadContainer_checkChanged `

The aim is to make `Switch` non-clickable and `Switch + 2 TextViews` as clickable.

Comment (rt4914) [reply app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt:461]: @anandwana001 PTAL

Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt:461]: my question was more of logic one, when we provide `allowDownloadAccess ` to true then is it correct that it is not clickable?

Comment (rt4914) [reply app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt:461]: `allowDownloadAccess` has nothing to do with `clickable`. If its true, it means that while creating the profile user has given the download access to user and therefore show the switch as `ON` by default which the admin can further change on click in this screen.

`allowDownloadAccess` is just the state of the permission to user and not related to click.

The click will simply change this state.

**Review by anandwana001 — APPROVED** [review]
