### PR TITLE
Fix #5612 Talk back is not reading Arabic language in Preferred Audio Language

### LINKED ISSUE #5612: Talk back is not reading Arabic language in Preferred Audio Language
### Describe the bug

Talk back is not reading Arabic language in Preferred Audio Language

### Steps To Reproduce

1.  Go to 'Fractions'.
2.  Tap on 'what is Fraction?'.
3.  Start the lesson.
4.  Tap on Three dot on top right corner.
5.  Tap on 'Options'.
6.  Tap on 'Preferred Audio Language'.
7.  Swipe across the various languages.

### Expected Behavior

Talk back to read all the language names including Arabic.

### Screenshots/Videos

https://github.com/user-attachments/assets/a21a5cc8-9111-4dab-ae23-3037985f12e2

### What device/emulator are you using?

Device name : OPPO Reno2 F

### Which Android version is your device/emulator running?

Android Version : Andorid 11

### Which version of the Oppia Android app are you using?

App Version : version 0.13-oppia-f73057826f

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by subhajitxyz**
## Explanation
Fix #5612

This PR includes adding a function languageContentDescription(), which return content description for audioLangueDisplayname Finally, it is set into the content description of the TextView.

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- For PRs introducing new UI elements or color changes, both light and dark mode screenshots must be included
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### CODE REVIEW

**Comment by subhajitxyz** [comment]
PTAL @adhiamboperes .

File: app/src/main/java/org/oppia/android/app/options/AudioLanguageItemViewModel.kt [hunk 1]
```diff
@@ -29,4 +29,14 @@ class AudioLanguageItemViewModel(
   val isLanguageSelected: LiveData<Boolean> by lazy {
     Transformations.map(currentSelectedLanguage) { it == language }
   }
+  /**
+   * Returns the content description for the current language. This is used for accessibility
+   * purposes to provide a readable description of the language in the UI.
+   */
+  fun languageContentDescription(): String {
+    return when (language) {
+      AudioLanguage.ARABIC_LANGUAGE -> "Arabic"
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/options/AudioLanguageItemViewModel.kt]: Could you please move this to strings.xml with a descriptive name?

File: app/src/sharedTest/java/org/oppia/android/app/options/AudioLanguageFragmentTest.kt [hunk 2]
```diff
@@ -499,6 +500,30 @@ class AudioLanguageFragmentTest {
     }
   }
 
+  @Test
+  fun testOpenFragment_withEnglish_verifyContentDescriptionOfArabicLanguage() {
```
Comment (adhiamboperes) [inline app/src/sharedTest/java/org/oppia/android/app/options/AudioLanguageFragmentTest.kt]:
```suggestion
  fun testFragment_withEnglish_verifyContentDescriptionReadsArabicLanguage() {
```

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @subhajitxyz! Just some minor changes suggested.

File: app/src/sharedTest/java/org/oppia/android/app/options/AudioLanguageFragmentTest.kt (hunk 2 above)
Comment (subhajitxyz) [reply app/src/sharedTest/java/org/oppia/android/app/options/AudioLanguageFragmentTest.kt]: Done.

File: app/src/main/java/org/oppia/android/app/options/AudioLanguageItemViewModel.kt (hunk 1 above)
Comment (subhajitxyz) [reply app/src/main/java/org/oppia/android/app/options/AudioLanguageItemViewModel.kt]: @adhiamboperes , I have added this to strings.xml. Please check if it is okay.

Comment (subhajitxyz) [reply app/src/main/java/org/oppia/android/app/options/AudioLanguageItemViewModel.kt]: Done.

**Comment by subhajitxyz** [comment]
PTAL, @adhiamboperes .

File: app/src/main/java/org/oppia/android/app/options/AudioLanguageItemViewModel.kt (hunk 1 above)
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/options/AudioLanguageItemViewModel.kt]:
```suggestion
      AudioLanguage.ARABIC_LANGUAGE -> appLanguageResourceHandler.getStringInLocaleWithWrapping(
        R.string.arabic_language_display_name_content_description
      )
```

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @subhajitxyz, just one more suggestion. PTAL. Also, please add a screen recording of the solution.

File: app/src/main/java/org/oppia/android/app/options/AudioLanguageItemViewModel.kt (hunk 1 above)
Comment (subhajitxyz) [reply app/src/main/java/org/oppia/android/app/options/AudioLanguageItemViewModel.kt]: Done

**Comment by subhajitxyz** [comment]
PTAL @adhiamboperes

**Review by adhiamboperes — APPROVED** [review]
Thanks @subhajitxyz! This LGTM.

**Comment by adhiamboperes** [comment]
This PR is temporarily blocked on merging because there is one already queued up for merging. Should be updated and merged in a couple of hours.

**Comment by subhajitxyz** [comment]
Thanks @adhiamboperes .
