### PR TITLE
Fix #2994: Update data objects for feedback reporting

### LINKED ISSUE #2994: Update data objects structure to sync with backend storage
**Describe the bug**
The data objects must be updated to include a GAE object for entry point as well as the report schema version for backend storage compatibility.

### PR DESCRIPTION
**Pull request by jcqli**
## Explanation
Fix #2994 to update the data objects so they match the backend storage model structure
- Adds a schema number to the GAE object sent in the network request
- Add a data object for the entry point
- Specify language **code**, remove device brand attribute, change timestamp from msec to sec to match backend datetime property
- Updates the testing JSON to match changes

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [ ] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

File: data/src/main/java/org/oppia/android/data/backends/gae/model/GaeFeedbackReportingEntryPoint.kt [hunk 1]
```diff
@@ -0,0 +1,24 @@
+package org.oppia.android.data.backends.gae.model
+
+import com.squareup.moshi.Json
+import com.squareup.moshi.JsonClass
+
+/**
+ * Data class for feedback reporting entry point represented in the backend domain model
+ * TODO(#2801): Link backend domain model
```
Comment (BenHenning) [inline data/src/main/java/org/oppia/android/data/backends/gae/model/GaeFeedbackReportingEntryPoint.kt]: Nit: TODOs shouldn't be in KDocs since they're not actually part of the class's documentation.

File: data/src/main/java/org/oppia/android/data/backends/gae/model/GaeFeedbackReportingSystemContext.kt [hunk 2]
```diff
@@ -11,12 +11,12 @@ import com.squareup.moshi.JsonClass
...
+  @Json(name = "platform_version") val packageVersionName: String,
   /** The package version code for the user's instance of the app. */
   @Json(name = "package_version_code") val packageVersionCode: Int,
-  /** The ISO-639 code for the country locale set on the user's device. */
-  @Json(name = "country_locale") val countryLocale: String,
-  /** The IDO-3166 code for the language locale set on the user's device. */
-  @Json(name = "language_locale") val languageLocale: String
+  /** The ISO-3166 code for the country locale set on the user's device. */
+  @Json(name = "country_locale_code") val countryLocaleCode: String,
+  /** The IDO-639 code for the language locale set on the user's device. */
```
Comment (BenHenning) [inline data/src/main/java/org/oppia/android/data/backends/gae/model/GaeFeedbackReportingSystemContext.kt:17]: Were these ISO codes reversed before?

File: data/src/test/assets/api_mocks/feedback_reporting.json [hunk 3]
```diff
@@ -1,36 +1,46 @@
...
+    "network_type": "wifi"
   },
-  "report_creation_timestamp": 1610519337000,
+  "report_submission_timestamp_sec": 1610519337,
   "system_context": {
-    "package_name": "example.package.name",
-    "package_code": "example_version_code",
-    "country_locale": "IN",
-    "language_locale": "EN"
+    "platform_version": "1.0-example_version",
```
Comment (BenHenning) [inline data/src/test/assets/api_mocks/feedback_reporting.json]: Prefer the format used in your other PR since that's closer to what versions will look like.

**Review by BenHenning — COMMENTED** [review]
Thanks @jcqli! Left a few comments.

File: data/src/main/java/org/oppia/android/data/backends/gae/model/GaeFeedbackReportingSystemContext.kt (hunk 2 above)
Comment (jcqli) [reply data/src/main/java/org/oppia/android/data/backends/gae/model/GaeFeedbackReportingSystemContext.kt:17]: Yup, accidentally switched them earlier. [Language codes](https://developer.android.com/reference/java/util/Locale#getISOLanguages()) are ISO-639 and [country codes](https://developer.android.com/reference/java/util/Locale#getISO3Country()) are ISO 3166.

File: data/src/main/java/org/oppia/android/data/backends/gae/model/GaeFeedbackReportingEntryPoint.kt (hunk 1 above)
Comment (jcqli) [reply data/src/main/java/org/oppia/android/data/backends/gae/model/GaeFeedbackReportingEntryPoint.kt]: Done

File: data/src/test/assets/api_mocks/feedback_reporting.json (hunk 3 above)
Comment (jcqli) [reply data/src/test/assets/api_mocks/feedback_reporting.json]: Done

**Review by BenHenning — APPROVED** [review]
Thanks @jcqli! LGTM.
