### PR TITLE
Fix #3890 Break *Required into 2 parts.

### LINKED ISSUE #3788: Break AddProfileActivity string "*Required" into two parts.
`“*Required”` string in `Add Profile` should be broken down into two parts because “*” does not need a translation.

### PR DESCRIPTION
**Pull request by rishidyno**
Fix #3788 
## Explanation
| LTR  |
|-------- | 

| Before | After |
| ----- | -----|
|Screenshot_20211214-184046|Screenshot_20211214-184048|
|Screenshot_20211214-184128|Screenshot_20211214-184188|
|Screenshot_20211214_133939| Screenshot_20211214_133939|
|Screenshot_20211214_133935| Screenshot_20211214_133955|

| RTL |
|-------- | 

| Before | After |
| ----- | -----|
|Screenshot_20211214-173009 | Screenshot_20211214-afterlpng|
|Screenshot_20211214-173024| Screenshot_20211214-173459|
|Screenshot_20211214_183328|Screenshot_20211214_183337|
|Screenshot_20211214_183338|Screenshot_20211214_183340|

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### CODE REVIEW

**Comment by rishidyno** [comment]
@BenHenning I am getting this error. I tried adding app_language_resource_handler dependency in the app BUILD.bazel file. 

This is the error log

Starting local Bazel server and connecting to it...
INFO: Analyzed target //:oppia (280 packages loaded, 5615 targets configured).
INFO: Found 1 target...
ERROR: /home/rishi/opensource/oppia-android/app/BUILD.bazel:628:19: KotlinCompile //app:view_models_kt { kt: 156, java: 0, srcjars: 0 } for armeabi-v7a failed: (Exit 1): builder failed: error executing command bazel-out/host/bin/external/io_bazel_rules_kotlin/src/main/kotlin/builder '--flagfile=bazel-out/android-armeabi-v7a-fastbuild/bin/app/view_models_kt-kt-java.jar-0.params'
warning: runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/external/com_github_jetbrains_kotlin/lib/kotlin-stdlib.jar (version 1.4)
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/external/com_github_jetbrains_kotlin/lib/kotlin-stdlib-jdk7.jar (version 1.4)
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/external/com_github_jetbrains_kotlin/lib/kotlin-stdlib-jdk8.jar (version 1.4)
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/bazel-out/android-armeabi-v7a-fastbuild/bin/external/maven/v1/https/repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-stdlib/1.5.0/header_kotlin-stdlib-1.5.0.jar (version 1.5)
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/bazel-out/android-armeabi-v7a-fastbuild/bin/external/maven/v1/https/repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-common/1.5.0/header_kotlin-stdlib-common-1.5.0.jar (version 1.5)
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/bazel-out/android-armeabi-v7a-fastbuild/bin/external/maven/v1/https/repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-reflect/1.5.0/header_kotlin-reflect-1.5.0.jar (version 1.5)
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/bazel-out/android-armeabi-v7a-fastbuild/bin/external/maven/v1/https/repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.4.10/header_kotlin-stdlib-jdk8-1.4.10.jar (version 1.4)
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/bazel-out/android-armeabi-v7a-fastbuild/bin/external/maven/v1/https/repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk7/1.4.10/header_kotlin-stdlib-jdk7-1.4.10.jar (version 1.4)
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/external/com_github_jetbrains_kotlin/lib/kotlin-script-runtime.jar (version 1.4)
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/external/com_github_jetbrains_kotlin/lib/kotlin-reflect.jar (version 1.4)
warning: some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath
warning: runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/external/com_github_jetbrains_kotlin/lib/kotlin-stdlib.jar (version 1.4)
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/external/com_github_jetbrains_kotlin/lib/kotlin-stdlib-jdk7.jar (version 1.4)
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/external/com_github_jetbrains_kotlin/lib/kotlin-stdlib-jdk8.jar (version 1.4)
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/bazel-out/android-armeabi-v7a-fastbuild/bin/external/maven/v1/https/repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-stdlib/1.5.0/header_kotlin-stdlib-1.5.0.jar (version 1.5)
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/bazel-out/android-armeabi-v7a-fastbuild/bin/external/maven/v1/https/repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-common/1.5.0/header_kotlin-stdlib-common-1.5.0.jar (version 1.5)
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/bazel-out/android-armeabi-v7a-fastbuild/bin/external/maven/v1/https/repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-reflect/1.5.0/header_kotlin-reflect-1.5.0.jar (version 1.5)
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/bazel-out/android-armeabi-v7a-fastbuild/bin/external/maven/v1/https/repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.4.10/header_kotlin-stdlib-jdk8-1.4.10.jar (version 1.4)
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/bazel-out/android-armeabi-v7a-fastbuild/bin/external/maven/v1/https/repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk7/1.4.10/header_kotlin-stdlib-jdk7-1.4.10.jar (version 1.4)
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/external/com_github_jetbrains_kotlin/lib/kotlin-script-runtime.jar (version 1.4)
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/external/com_github_jetbrains_kotlin/lib/kotlin-reflect.jar (version 1.4)
warning: some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath
app/src/main/java/org/oppia/android/app/profile/AddProfileViewModel.kt:25:79: error: unresolved reference: add_profile_required
  val starRequired: String = "*" + resourceHandler.getStringInLocale(R.string.add_profile_required)
                                                                              ^
Compilation failure: compile phase failed:
warning: runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/external/com_github_jetbrains_kotlin/lib/kotlin-stdlib.jar (version 1.4)
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/external/com_github_jetbrains_kotlin/lib/kotlin-stdlib-jdk7.jar (version 1.4)
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/external/com_github_jetbrains_kotlin/lib/kotlin-stdlib-jdk8.jar (version 1.4)
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/bazel-out/android-armeabi-v7a-fastbuild/bin/external/maven/v1/https/repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-stdlib/1.5.0/header_kotlin-stdlib-1.5.0.jar (version 1.5)
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/bazel-out/android-armeabi-v7a-fastbuild/bin/external/maven/v1/https/repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-common/1.5.0/header_kotlin-stdlib-common-1.5.0.jar (version 1.5)
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/bazel-out/android-armeabi-v7a-fastbuild/bin/external/maven/v1/https/repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-reflect/1.5.0/header_kotlin-reflect-1.5.0.jar (version 1.5)
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/bazel-out/android-armeabi-v7a-fastbuild/bin/external/maven/v1/https/repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.4.10/header_kotlin-stdlib-jdk8-1.4.10.jar (version 1.4)
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/bazel-out/android-armeabi-v7a-fastbuild/bin/external/maven/v1/https/repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk7/1.4.10/header_kotlin-stdlib-jdk7-1.4.10.jar (version 1.4)
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/external/com_github_jetbrains_kotlin/lib/kotlin-script-runtime.jar (version 1.4)
    /home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/external/com_github_jetbrains_kotlin/lib/kotlin-reflect.jar (version 1.4)
warning: some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath
/home/rishi/.cache/bazel/_bazel_rishi/2d9bbf034eeaafac68b4112f599a43d0/execroot/__main__/app/src/main/java/org/oppia/android/app/profile/AddProfileViewModel.kt:25:79: error: unresolved reference: add_profile_required
  val starRequired: String = "*" + resourceHandler.getStringInLocale(R.string.add_profile_required)
                                                                              ^
Target //:oppia failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 33.654s, Critical Path: 23.36s
INFO: 3 processes: 2 internal, 1 linux-sandbox.
FAILED: Build did NOT complete successfully
rishi@r:~/opensource/oppia-android$

**Comment by BenHenning** [comment]
@rishidyno it looks like you addressed that problem by moving the view model to the VIEW_MODELS_WITH_RESOURCES list. However, you're also using a kotlinx import which shouldn't be used per https://developer.android.com/topic/libraries/view-binding/migration. You should use a direct resource reference, instead, and retrieve the view using findViewById.

**Comment by rishidyno** [comment]
@BenHenning @rt4914  All tests have passed PTAL.

File: app/src/main/java/org/oppia/android/app/profile/AddProfileViewModel.kt [hunk 1]
```diff
@@ -18,6 +22,7 @@ class AddProfileViewModel @Inject constructor() : ObservableViewModel() {
   val createPin = ObservableField(false)
   val isButtonActive = ObservableField(false)
   val showInfoAlertPopup = ObservableField<Boolean>(false)
+  val starRequired: String = "*" + resourceHandler.getStringInLocale(R.string.add_profile_required)
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/profile/AddProfileViewModel.kt]: Suggest instead: ``requiredTextWithStar``

File: app/src/sharedTest/java/org/oppia/android/app/profile/AddProfileActivityTest.kt [hunk 2]
```diff
@@ -171,6 +171,17 @@ class AddProfileActivityTest {
     assertThat(label).isEqualTo(context.getString(R.string.add_profile_activity_label))
   }
 
+  @Test
+  fun testAddProfileActivity_required_heading_text_view_hasCorrectRequiredString() {
+    launch(
+      AddProfileActivity::class.java
+    ).use {
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/profile/AddProfileActivityTest.kt]:
```suggestion
    launch(AddProfileActivity::class.java).use {
```

Nit: this can fit on one line.

File: app/src/sharedTest/java/org/oppia/android/app/profile/AddProfileActivityTest.kt [hunk 3]
```diff
@@ -171,6 +171,17 @@ class AddProfileActivityTest {
     assertThat(label).isEqualTo(context.getString(R.string.add_profile_activity_label))
   }
 
+  @Test
+  fun testAddProfileActivity_required_heading_text_view_hasCorrectRequiredString() {
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/profile/AddProfileActivityTest.kt]: This isn't really a heading, it's just a label. Perhaps instead:

```
testAddProfileActivity_hasRequiredTextPrefixedWithStar
```

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @rishidyno! Took a full pass on the PR. Besides the comments I left in code, could you also please update your PR description to:

1. Include an explanation for what this PR is doing, and some context on the approach you're taking
2. To include a filled-in "For UI-specific PRs only" section (you should follow all the instructions list)
3. Under the 'For UI-specific PRs only' please also include at least one screenshot with Arabic to demonstrate the RTL behavior for this string (I want to make sure it reverses correctly)

**Comment by rishidyno** [comment]
@BenHenning  I have added the SS and have addressed the changes PTAL.

**Review by BenHenning — APPROVED** [review]
Thanks @rishidyno. This LGTM--nothing else to add!

**Comment by BenHenning** [comment]
I'm force merging this since @rt4914 is out & I'm more or less covering his codeowners this week. I reviewed the whole PR & everything LGTM, plus tests are passing.

**Comment by rishidyno** [comment]
Thanks @BenHenning
