### PR TITLE
Fix #1441: Fixes in current event logging scenario

### LINKED ISSUE #1441: Fixes in Current Event Logging scenario
This issue tracks the problems in the current event logging scenario - 
- Removal of context as a parameter. 
- Errors in event reporting of Question Player.

### PR DESCRIPTION
**Pull request by Sarthak2601**
## Explanation

Fix #1441 
- Removal of Context parameter from everywhere. 
- Fixes in Question Player event logging. 

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

File: app/src/main/java/org/oppia/app/home/HomeFragmentPresenter.kt [hunk 1]
```diff
@@ -205,10 +205,9 @@ class HomeFragmentPresenter @Inject constructor(
 
   private fun logHomeActivityEvent() {
     analyticsController.logTransitionEvent(
-      activity.applicationContext,
       oppiaClock.getCurrentCalendar().timeInMillis,
       EventLog.EventAction.OPEN_HOME,
-      null
+      /* Event Context */ null
```
Comment (vinitamurthi) [inline app/src/main/java/org/oppia/app/home/HomeFragmentPresenter.kt]: This should be /* eventContext= */

File: utility/src/main/java/org/oppia/util/logging/EventBundleCreator.kt [hunk 2]
```diff
@@ -55,12 +54,12 @@ class EventBundleCreator {
...
     val bundle = Bundle()
+    val skillIdList = eventLog.context.questionContext.skillIdList
     bundle.putLong(TIMESTAMP_KEY, eventLog.timestamp)
     bundle.putString(QUESTION_ID_KEY, eventLog.context.questionContext.questionId)
-    bundle.putStringArray(
-      SKILL_LIST_ID_KEY,
-      eventLog.context.questionContext.skillIdList.toTypedArray()
-    )
+    for (skillId in skillIdList) {
+      bundle.putString(SKILL_ID_KEY + skillIdList.indexOf(skillId), skillId)
```
Comment (vinitamurthi) [inline utility/src/main/java/org/oppia/util/logging/EventBundleCreator.kt]: I thought we discussed that we would convert the array to a string and put it once, instead of keeping separate keys..
i.e. 
```
bundle.putString(SKILL_ID_KEY, skillIdList.joinToString())
```

**Review by vinitamurthi — CHANGES_REQUESTED** [review]

File: app/src/main/java/org/oppia/app/home/HomeFragmentPresenter.kt (hunk 1 above)
Comment (Sarthak2601) [reply app/src/main/java/org/oppia/app/home/HomeFragmentPresenter.kt]: Done.

File: utility/src/main/java/org/oppia/util/logging/EventBundleCreator.kt (hunk 2 above)
Comment (Sarthak2601) [reply utility/src/main/java/org/oppia/util/logging/EventBundleCreator.kt]: Done.

File: app/src/main/java/org/oppia/app/home/HomeFragmentPresenter.kt [hunk 3]
```diff
@@ -205,10 +205,9 @@ class HomeFragmentPresenter @Inject constructor(
 
   private fun logHomeActivityEvent() {
     analyticsController.logTransitionEvent(
-      activity.applicationContext,
       oppiaClock.getCurrentCalendar().timeInMillis,
       EventLog.EventAction.OPEN_HOME,
-      null
+      /* eventContext */ null
```
Comment (vinitamurthi) [inline app/src/main/java/org/oppia/app/home/HomeFragmentPresenter.kt]: Add an '=' , i.e. `/* eventContext= */ null`

**Review by vinitamurthi — APPROVED** [review]
Just one nit

**Comment by vinitamurthi** [comment]
Feel free to resolve once you add the = in the comment and merge the PR

File: app/src/main/java/org/oppia/app/home/HomeFragmentPresenter.kt (hunk 3 above)
Comment (Sarthak2601) [reply app/src/main/java/org/oppia/app/home/HomeFragmentPresenter.kt]: Done.

**Comment by Sarthak2601** [comment]
Comments resolved, merging !
