### PR TITLE
Fix part of #134: Home fragment low fi with TopicList

### LINKED ISSUE #134: UI structure: Introduce topic list on home screen
This is tracking introducing the activity/fragment/view structures to hook up #117 to prepare for #10.

Two things needs to done in this:

- [x] Make promoted story a caraousel https://xd.adobe.com/spec/e2239cf4-9cde-4c08-5296-25316c1f0a14-9412/screen/d47aa8de-a7a8-4d25-b011-5baefc7b7098/HP-Home-Page-
(Filed a issue #389 )
- [x] Currently "All Topics" text is not visible below promoted stories - add that as an item. (@rt4914 Check #311 )

### PR DESCRIPTION
**Pull request by rt4914**
## Explanation

This PR includes implementation of HomeFragment and next PR on this will include ContinuePlayingActivity

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is **assigned** to an appropriate reviewer.

### CODE REVIEW

**Comment by rt4914** [comment]
@BenHenning PTAL

File: app/src/main/java/org/oppia/app/home/topiclist/TopicListAdapter.kt [hunk 1]
```diff
@@ -0,0 +1,126 @@
...
+    return when (viewType) {
+      // TODO(#249): Generalize this binding to make adding future items easier.
+      VIEW_TYPE_WELCOME_MESSAGE -> {
+        val inflater = LayoutInflater.from(parent.context)
+        val binding =
+          DataBindingUtil.inflate<WelcomeBinding>(
+            inflater,
+            R.layout.welcome,
+            parent,
+            /* attachToParent= */false
```
Comment (veena14cs) [inline app/src/main/java/org/oppia/app/home/topiclist/TopicListAdapter.kt]: space after `*/` here and elsewhere.

File: app/src/main/java/org/oppia/app/home/RouteToTopicPlayStoryListener.kt [hunk 2]
```diff
@@ -0,0 +1,6 @@
+package org.oppia.app.home
+
+/** Listener for when an activity should route to a topic. */
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/app/home/RouteToTopicPlayStoryListener.kt]: Should this say ``route to a story``?

File: app/src/main/java/org/oppia/app/home/HomeFragmentPresenter.kt [hunk 3]
```diff
@@ -64,4 +107,48 @@ class HomeFragmentPresenter @Inject constructor(
...
+
+  private fun subscribeToUserAppHistory() {
+    getUserAppHistory()!!.observe(fragment, Observer<UserAppHistory> { result ->
+      getUserAppHistoryViewModel().setAlreadyAppOpened(result.alreadyOpenedApp)
+      itemList.add(0, getUserAppHistoryViewModel())
+      topicListAdapter.notifyDataSetChanged()
+    })
+  }
+
+  private fun getUserAppHistory(): LiveData<UserAppHistory>? {
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/app/home/HomeFragmentPresenter.kt]: Why the nullable return value? Doesn't Transformations.map() guarantee a non-null return if the LiveData passed in is non-null?

File: app/src/main/java/org/oppia/app/home/HomeFragmentPresenter.kt [hunk 4]
```diff
@@ -21,35 +31,68 @@ private const val EXPLORATION_ID = TEST_EXPLORATION_ID_5
...
+
     return binding.root
   }
 
   private fun getUserAppHistoryViewModel(): UserAppHistoryViewModel {
     return viewModelProvider.getForFragment(fragment, UserAppHistoryViewModel::class.java)
   }
 
+  private fun getPromotedStoryViewModel(): PromotedStoryViewModel? {
+    return promotedStoryViewModel.getForFragment(fragment, PromotedStoryViewModel::class.java)
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/app/home/HomeFragmentPresenter.kt]: Won't this always be non-null?

File: app/src/main/java/org/oppia/app/home/topiclist/PromotedStoryViewModel.kt [hunk 5]
```diff
@@ -0,0 +1,43 @@
...
+@FragmentScope
+class PromotedStoryViewModel @Inject constructor(
+  private val activity: AppCompatActivity
+) : ObservableViewModel() {
+  /**
+   * The retrieved [LiveData] for retrieving topic summaries. This model should ensure only one
+   * [LiveData] is used for all subsequent processed data to ensure the transformed [LiveData]s are
+   * always in sync.
+   */
+
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/app/home/topiclist/PromotedStoryViewModel.kt]: Nit: remove blank newline here. KDocs should always be directly next to the class member that they are documenting.

File: app/src/main/res/layout/promoted_story_card.xml [hunk 6]
```diff
@@ -0,0 +1,119 @@
...
+      android:layout_marginEnd="8dp"
+      android:text="@string/recently_played_stories"
+      android:textColor="@color/oppiaPrimaryText"
+      android:textStyle="bold"
+      app:layout_constraintEnd_toStartOf="@+id/view_all"
+      app:layout_constraintStart_toStartOf="parent"
+      app:layout_constraintTop_toTopOf="parent" />
+
+    <TextView
+      android:id="@+id/view_all"
```
Comment (veena14cs) [inline app/src/main/res/layout/promoted_story_card.xml]: You can rename it to `view_all_text_view` for differentiating the between views.

File: app/src/main/java/org/oppia/app/home/topiclist/PromotedStoryViewModel.kt [hunk 7]
```diff
@@ -0,0 +1,43 @@
...
+import org.oppia.app.home.HomeActivity
+import org.oppia.app.model.PromotedStory
+import org.oppia.app.viewmodel.ObservableViewModel
+import javax.inject.Inject
+
+// TODO(#283): Add download status information to promoted-story-card.
+
+/** [ViewModel] for displaying a promoted story. */
+@FragmentScope
+class PromotedStoryViewModel @Inject constructor(
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/app/home/topiclist/PromotedStoryViewModel.kt]: I suggest not making this injectable. I ran into a similar situation when rearranging the state fragment's recyclerview adapter, and I came to the conclusion that view models which are stored in recycler view adapter lists shouldn't be injected (since they ought to be constructed, instead). That will solve the need to depend on HomeActivity directly because you can pass in RouteToContinuePlayingListener in the view model's constructor to call into. That keeps the UI dependencies clean (members of the UI hierarchy should only directly call into children and children should indirectly call into parents).

File: app/src/main/res/layout/promoted_story_card.xml [hunk 8]
```diff
@@ -0,0 +1,119 @@
...
+        android:layout_height="wrap_content"
+        android:background="@color/white"
+        android:orientation="vertical"
+        app:layout_constraintBottom_toBottomOf="parent"
+        app:layout_constraintEnd_toEndOf="parent"
+        app:layout_constraintStart_toStartOf="parent"
+        app:layout_constraintTop_toBottomOf="@id/lesson_thumbnail">
+
+        <TextView
+          android:id="@+id/chapter_name"
```
Comment (veena14cs) [inline app/src/main/res/layout/promoted_story_card.xml]: Ditto elsewhere.

File: app/src/main/java/org/oppia/app/home/topiclist/PromotedStoryViewModel.kt [hunk 9]
```diff
@@ -0,0 +1,43 @@
...
+  private val activity: AppCompatActivity
+) : ObservableViewModel() {
+  /**
+   * The retrieved [LiveData] for retrieving topic summaries. This model should ensure only one
+   * [LiveData] is used for all subsequent processed data to ensure the transformed [LiveData]s are
+   * always in sync.
+   */
+
+  var promotedStoryObservable = ObservableField<PromotedStory>()
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/app/home/topiclist/PromotedStoryViewModel.kt]: Should this be a ``val`` given that the reference itself won't be overwritten, only the value it contains?

File: app/src/main/java/org/oppia/app/home/topiclist/TopicListAdapter.kt [hunk 10]
```diff
@@ -0,0 +1,126 @@
...
+) :
+  RecyclerView.Adapter<RecyclerView.ViewHolder>() {
+
+  override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): RecyclerView.ViewHolder {
+    return when (viewType) {
+      // TODO(#249): Generalize this binding to make adding future items easier.
+      VIEW_TYPE_WELCOME_MESSAGE -> {
+        val inflater = LayoutInflater.from(parent.context)
+        val binding =
+          DataBindingUtil.inflate<WelcomeBinding>(
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/app/home/topiclist/TopicListAdapter.kt]: Suggest using WelcomeBinding directly:

```kotlin
val binding = WelcomeBinding.inflate(inflater, parent, /* attachToParent= */ false)
```

Ditto for the others.

File: app/src/main/java/org/oppia/app/home/topiclist/TopicListAdapter.kt [hunk 11]
```diff
@@ -0,0 +1,126 @@
...
+/** Adapter to inflate different items/views inside [RecyclerView]. The itemList consists of various ViewModels. */
+class TopicListAdapter(
+  private val itemList: MutableList<Any>,
+  private val topicSummaryClickListener: TopicSummaryClickListener
+) :
+  RecyclerView.Adapter<RecyclerView.ViewHolder>() {
+
+  override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): RecyclerView.ViewHolder {
+    return when (viewType) {
+      // TODO(#249): Generalize this binding to make adding future items easier.
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/app/home/topiclist/TopicListAdapter.kt]: I think this falls more under #216 since using the bindable adapter makes things pretty generic, especially when combined with an enum (see #270 in StateFragmentPresenter for how this looks when it's all composed).

File: app/src/main/java/org/oppia/app/home/topiclist/TopicListAdapter.kt [hunk 12]
```diff
@@ -0,0 +1,126 @@
...
+        val binding =
+          DataBindingUtil.inflate<TopicSummaryViewBinding>(
+            inflater,
+            R.layout.topic_summary_view,
+            parent,
+            /* attachToParent= */false
+          )
+        TopicListViewHolder(binding)
+      }
+      else -> throw IllegalArgumentException("Invalid view type") as Throwable
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/app/home/topiclist/TopicListAdapter.kt]: Would be nice to include the view type designated as invalid in the error string to provide context if it's ever thrown.

File: app/src/main/java/org/oppia/app/home/topiclist/TopicListAdapter.kt [hunk 13]
```diff
@@ -0,0 +1,126 @@
...
+      is UserAppHistoryViewModel -> {
+        VIEW_TYPE_WELCOME_MESSAGE
+      }
+      is PromotedStoryViewModel -> {
+        VIEW_TYPE_PROMOTED_STORY
+      }
+      is TopicSummary -> {
+        VIEW_TYPE_TOPIC_LIST
+      }
+      else -> throw IllegalArgumentException("Invalid type of data $position")
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/app/home/topiclist/TopicListAdapter.kt]: Suggest also including ``itemList[position]`` in the error message since the current error message doesn't provide the specific data that was determined as invalid.

File: app/src/main/java/org/oppia/app/home/topiclist/TopicListAdapter.kt [hunk 14]
```diff
@@ -0,0 +1,126 @@
...
+
+  override fun getItemCount(): Int {
+    return itemList.size
+  }
+
+  private class WelcomeViewHolder(
+    val binding: ViewDataBinding
+  ) : RecyclerView.ViewHolder(binding.root) {
+    internal fun bind(userAppHistoryViewModel: UserAppHistoryViewModel) {
+      binding.setVariable(BR.viewModel, userAppHistoryViewModel)
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/app/home/topiclist/TopicListAdapter.kt]: If you make ``binding`` of type ``WelcomeBinding`` then you can access the view model directly:

```kotlin
private class WelcomeViewHolder(
  val binding: WelcomeBinding
): RecyclerView.ViewHolder(binding.root) {
  internal fun bind(userAppHistoryViewModel: UserAppHistoryViewModel) {
    binding.viewModel = userAppHistoryViewModel
  }
}
```

Ditto below.

File: app/src/main/java/org/oppia/app/home/topiclist/TopicListAdapter.kt [hunk 15]
```diff
@@ -0,0 +1,126 @@
...
+      binding.setVariable(BR.viewModel, promotedStoryViewModel)
+    }
+  }
+
+  private class TopicListViewHolder(
+    val binding: ViewDataBinding
+  ) : RecyclerView.ViewHolder(binding.root) {
+    internal fun bind(topicSummary: TopicSummary, topicSummaryClickListener: TopicSummaryClickListener) {
+
+      val topicSummaryViewModel = TopicSummaryViewModel(topicSummary, topicSummaryClickListener)
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/app/home/topiclist/TopicListAdapter.kt]: I suggest binding TopicSummaryViewModel in the item list instead of TopicSummary. That makes this cleaner and more consistent with the other view holders (which consequentially makes the migration to the bindable adapter trivial).

File: app/src/main/java/org/oppia/app/home/topiclist/TopicListAdapter.kt [hunk 16]
```diff
@@ -0,0 +1,126 @@
...
+import org.oppia.app.home.UserAppHistoryViewModel
+import org.oppia.app.model.TopicSummary
+
+private const val VIEW_TYPE_WELCOME_MESSAGE = 1
+private const val VIEW_TYPE_PROMOTED_STORY = 2
+private const val VIEW_TYPE_TOPIC_LIST = 3
+
+/** Adapter to inflate different items/views inside [RecyclerView]. The itemList consists of various ViewModels. */
+class TopicListAdapter(
+  private val itemList: MutableList<Any>,
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/app/home/topiclist/TopicListAdapter.kt]: Let's avoid ``Any``. I suggest introducing an abstract ``HomeItemViewModel`` supertype for each of the three view models contained in this adapter, and using downcasting as necessary to convert to more specific types. This provides better type safety than ``Any``, and makes it possible to convert this adapter to a generic bindable adapter in the future. See #270 in StateFragmentPresenter how that adapter was set up with a common supertype, and similarly in #195.

File: app/src/main/java/org/oppia/app/home/topiclist/TopicSummaryViewModel.kt [hunk 17]
```diff
@@ -0,0 +1,42 @@
...
+// These values were roughly computed based on the mocks. They won't produce the same colors since darker colors in the
+// mocks were not consistently darker. An alternative would be to specify both background colors together to ensure
+// proper contrast with readable elements.
+const val DARKEN_VALUE_MULTIPLIER: Float = 0.9f
+const val DARKEN_SATURATION_MULTIPLIER: Float = 1.2f
+
+/** The view model corresponding to topic summaries in the topic summary RecyclerView. */
+class TopicSummaryViewModel(
+  val topicSummary: TopicSummary, private val topicSummaryClickListener: TopicSummaryClickListener
+) {
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/app/home/topiclist/TopicSummaryViewModel.kt]: Shouldn't this extend ``ViewModel``?

File: app/src/main/res/layout/home_fragment.xml [hunk 18]
```diff
@@ -1,37 +1,42 @@
...
       app:layout_constraintBottom_toBottomOf="parent"
-      app:layout_constraintLeft_toLeftOf="parent"
-      app:layout_constraintRight_toRightOf="parent"
-      app:layout_constraintTop_toTopOf="parent"/>
+      app:layout_constraintEnd_toEndOf="parent"
+      app:layout_constraintStart_toStartOf="parent"
+      app:layout_constraintTop_toBottomOf="parent" />
+
     <Button
       android:id="@+id/play_exploration_button"
```
Comment (BenHenning) [inline app/src/main/res/layout/home_fragment.xml:31]: When are we going to remove this? Prefer not keeping around buttons that shouldn't be on the home screen.

File: app/src/main/res/layout/promoted_story_card.xml [hunk 19]
```diff
@@ -0,0 +1,119 @@
+<?xml version="1.0" encoding="utf-8"?>
```
Comment (BenHenning) [inline app/src/main/res/layout/promoted_story_card.xml:1]: Can you confirm as part of #134 with Chantel whether this layout matches the case where we show a suggested lesson instead of a recently completed? I'm guessing it does, but I'm having difficulty tracking that down in the mocks.

I don't think this question should block this PR, but it's good to clarify.

File: app/src/main/res/values/strings.xml [hunk 20]
```diff
@@ -26,6 +26,13 @@
   <string name="topic_overview_see_more">See More</string>
   <string name="topic_download_text">(%s MB)</string>
   <string name="topic_story_progress_percentage">%s\%%</string>
+  <string name="continue_lesson">Continue with your Lesson</string>
+  <string name="more">MORE</string>
```
Comment (BenHenning) [inline app/src/main/res/values/strings.xml]: We should capitalize using textAllCaps and not here.

File: app/src/main/res/values/strings.xml [hunk 21]
```diff
@@ -26,6 +26,13 @@
...
+  <string name="loading_topics_list_text">Loading topics list…</string>
+  <string name="error_loading_topics_list_text">Error loading topics list</string>
```
Comment (BenHenning) [inline app/src/main/res/values/strings.xml]: Are this & the above string used? I think I integrated them originally to have a pending state while the topic controller provided a pending value.

File: app/src/sharedTest/java/org/oppia/app/home/ContinuePlayingActivityTest.kt [hunk 22]
```diff
@@ -0,0 +1,66 @@
...
+
+  @Test
+  fun testContinuePlayingActivity_loadContinuePlayingFragment_hasDummyString() {
+    ActivityScenario.launch(ContinuePlayingActivity::class.java).use {
+      onView(withId(R.id.dummy_text_view)).check(matches(withText(containsString("Dummy Continue Playing Activity"))))
+    }
+  }
+
+  @Module
+  class TestModule {
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/app/home/ContinuePlayingActivityTest.kt]: Nit: we actually don't need this module or the component since they aren't being initialized in this test. Suggest removing for now.

File: app/src/sharedTest/java/org/oppia/app/home/HomeActivityTest.kt [hunk 23]
```diff
@@ -89,10 +99,185 @@ class HomeActivityTest {
...
+      }
+      onView(atPositionOnView(R.id.home_recycler_view, 1, R.id.story_name)).check(
+        matches(
+          withText(containsString("Second Story"))
+        )
+      )
+    }
+  }
+
+  // TODO(#135): Update this test case to check that topic-play tab is opened.
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/app/home/HomeActivityTest.kt]: @nikitamarysolomanpvt FYI.

Comment (BenHenning) [reply app/src/sharedTest/java/org/oppia/app/home/HomeActivityTest.kt]: Also @rt4914, shouldn't we test this within the topic activity/fragment test, instead? Here it makes sense to me to verify we're using the correct API (sending a topic & story ID), and have another test for topic activity to verify that starting the activity with both parameters properly auto opens the tab & scrolls.

If you agree, let's finish the home fragment test side here and move this TODO to a checkbox within #135 that can be satisfied with a test in TopicActivityTest.

File: app/src/sharedTest/java/org/oppia/app/home/HomeActivityTest.kt [hunk 24]
```diff
@@ -89,10 +99,185 @@ class HomeActivityTest {
...
+  @Test
+  fun testHomeActivity_recyclerViewIndex1_clickPromotedStory_opensTopicActivity() {
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/app/home/HomeActivityTest.kt:200]: Is it worth verifying that we are also sending the story ID? See my above comment--we should verify we're using the correct API here.

**Review by BenHenning — APPROVED** [review]
Thanks @rt4914! This generally LGTM (& really nice tests for the topic list). Feel free to re-assign to me if you want me to do one more pass, but once all my comments are resolved I'm completely fine with this being merged.

File: app/src/main/java/org/oppia/app/home/HomeFragmentPresenter.kt (hunk 4 above)
Comment (rt4914) [reply app/src/main/java/org/oppia/app/home/HomeFragmentPresenter.kt]: @BenHenning I was thinking of the case when the learner has just started using the app, in that case what there won't be any promoted story, right? Or the domain layer is making sure that there is a promoted story every time?

File: app/src/main/java/org/oppia/app/home/topiclist/TopicListAdapter.kt (hunk 1 above)
Comment (rt4914) [reply app/src/main/java/org/oppia/app/home/topiclist/TopicListAdapter.kt]: done.

File: app/src/main/res/layout/promoted_story_card.xml (hunk 6 above)
Comment (rt4914) [reply app/src/main/res/layout/promoted_story_card.xml]: Done.

File: app/src/main/res/layout/promoted_story_card.xml (hunk 8 above)
Comment (rt4914) [reply app/src/main/res/layout/promoted_story_card.xml]: Done.

File: app/src/main/java/org/oppia/app/home/RouteToTopicPlayStoryListener.kt (hunk 2 above)
Comment (rt4914) [reply app/src/main/java/org/oppia/app/home/RouteToTopicPlayStoryListener.kt]: It will route to `Topic-Play-Tab` to a specific story item.

Comment (rt4914) [reply app/src/main/java/org/oppia/app/home/RouteToTopicPlayStoryListener.kt]: Updated doc accordingly.

File: app/src/main/java/org/oppia/app/home/HomeFragmentPresenter.kt (hunk 3 above)
Comment (rt4914) [reply app/src/main/java/org/oppia/app/home/HomeFragmentPresenter.kt]: Removed nullable.

File: app/src/main/java/org/oppia/app/home/HomeFragmentPresenter.kt (hunk 4 above)
Comment (rt4914) [reply app/src/main/java/org/oppia/app/home/HomeFragmentPresenter.kt]: For now I am making this non-null based on your comment.

File: app/src/main/java/org/oppia/app/home/topiclist/PromotedStoryViewModel.kt (hunk 5 above)
Comment (rt4914) [reply app/src/main/java/org/oppia/app/home/topiclist/PromotedStoryViewModel.kt]: Done.

File: app/src/main/res/values/strings.xml (hunk 20 above)
Comment (rt4914) [reply app/src/main/res/values/strings.xml]: Actually this string was not getting used anywhere so removed it.

File: app/src/sharedTest/java/org/oppia/app/home/ContinuePlayingActivityTest.kt (hunk 22 above)
Comment (rt4914) [reply app/src/sharedTest/java/org/oppia/app/home/ContinuePlayingActivityTest.kt]: Removed TestModule.

File: app/src/main/res/values/strings.xml (hunk 21 above)
Comment (rt4914) [reply app/src/main/res/values/strings.xml]: Removed this unused strings

File: app/src/main/java/org/oppia/app/home/topiclist/PromotedStoryViewModel.kt (hunk 9 above)
Comment (rt4914) [reply app/src/main/java/org/oppia/app/home/topiclist/PromotedStoryViewModel.kt]: changed `var` to `val`

File: app/src/main/java/org/oppia/app/home/topiclist/TopicListAdapter.kt (hunk 10 above)
Comment (rt4914) [reply app/src/main/java/org/oppia/app/home/topiclist/TopicListAdapter.kt]: Made this change here and everywhere else in this PR

File: app/src/main/java/org/oppia/app/home/topiclist/TopicListAdapter.kt (hunk 11 above)
Comment (rt4914) [reply app/src/main/java/org/oppia/app/home/topiclist/TopicListAdapter.kt]: Done. And it makes sense.

File: app/src/main/java/org/oppia/app/home/topiclist/TopicListAdapter.kt (hunk 15 above)
Comment (rt4914) [reply app/src/main/java/org/oppia/app/home/topiclist/TopicListAdapter.kt]: Updated to bind all this and pass it to itemList similar to implementation in other Items of the list.

File: app/src/main/java/org/oppia/app/home/topiclist/TopicSummaryViewModel.kt (hunk 17 above)
Comment (rt4914) [reply app/src/main/java/org/oppia/app/home/topiclist/TopicSummaryViewModel.kt]: Done.

Comment (rt4914) [reply app/src/main/java/org/oppia/app/home/topiclist/TopicSummaryViewModel.kt]: Extending ViewModel now.

File: app/src/main/res/layout/home_fragment.xml (hunk 18 above)
Comment (rt4914) [reply app/src/main/res/layout/home_fragment.xml:31]: I kept this because it was getting used in other PRs too but I think almost all PRs are ready now and therefore we can remove this now. Also, this will lead to failure in test-cases but anyways we need to updated test-cases too.

Removed this button and its respective code.

File: app/src/sharedTest/java/org/oppia/app/home/HomeActivityTest.kt [hunk 25]
```diff
@@ -89,10 +99,185 @@ class HomeActivityTest {
...
+          0,
+          R.id.welcome_text_view
+        )
+      ).check(matches(withText(containsString("Welcome"))))
+    }
+  }
+
+  @Test
+  fun testHomeActivity_recyclerViewIndex0_configurationChange_displaysWelcomeMessageCorrectly() {
+    launch(HomeActivity::class.java).use {
```
Comment (nikitamarysolomanpvt) [inline app/src/sharedTest/java/org/oppia/app/home/HomeActivityTest.kt:118]: This code seems not working. Even while debugging not changing (not showing the change in configuration)the configuration.

File: app/src/main/java/org/oppia/app/home/topiclist/PromotedStoryViewModel.kt (hunk 7 above)
Comment (rt4914) [reply app/src/main/java/org/oppia/app/home/topiclist/PromotedStoryViewModel.kt]: Done. Removed Inject and now PromotedStoryViewModel is directly calling `TopicActivity` and `ContinuePlayingActivity`.

File: app/src/sharedTest/java/org/oppia/app/home/HomeActivityTest.kt [hunk 26]
```diff
@@ -89,10 +99,185 @@ class HomeActivityTest {
...
+        matches(
+          withText(containsString("Second Story"))
+        )
+      )
+    }
+  }
+
+  @Test
+  fun testHomeActivity_recyclerViewIndex1_configurationChange_promotedCard_storyNameIsCorrect() {
+    launch(HomeActivity::class.java).use {
```
Comment (nikitamarysolomanpvt) [inline app/src/sharedTest/java/org/oppia/app/home/HomeActivityTest.kt:188]: ditto: not working

File: app/src/main/java/org/oppia/app/home/topiclist/TopicListAdapter.kt (hunk 14 above)
Comment (rt4914) [reply app/src/main/java/org/oppia/app/home/topiclist/TopicListAdapter.kt]: Done. Here and everywhere else in this PR.

File: app/src/sharedTest/java/org/oppia/app/home/HomeActivityTest.kt [hunk 27]
```diff
@@ -89,10 +99,185 @@ class HomeActivityTest {
...
+        matches(
+          withText(containsString("1 Lesson"))
+        )
+      )
+    }
+  }
+
+  @Test
+  fun testHomeActivity_recyclerViewIndex3_topicSummary_configurationChange_lessonCountIsCorrect() {
+    launch(HomeActivity::class.java).use {
```
Comment (nikitamarysolomanpvt) [inline app/src/sharedTest/java/org/oppia/app/home/HomeActivityTest.kt:272]: ditto:

File: app/src/main/java/org/oppia/app/home/topiclist/TopicListAdapter.kt (hunk 16 above)
Comment (rt4914) [reply app/src/main/java/org/oppia/app/home/topiclist/TopicListAdapter.kt]: Introduced `HomeItemViewModel` and made all viewmodels extend `HomeItemViewModel`.

File: app/src/main/java/org/oppia/app/databinding/DrawableBindingAdapters.kt [hunk 28]
```diff
@@ -0,0 +1,15 @@
...
+import androidx.annotation.ColorInt
+import androidx.databinding.BindingAdapter
+import org.oppia.app.R
+
+/** Used to set a rounded-rect background drawable with a data-bound color. */
+@BindingAdapter("app:roundedRectDrawableWithColor")
+fun setBackgroundDrawable(view: View, @ColorInt colorRgb: Int) {
+  view.setBackgroundResource(R.drawable.rounded_rect_background)
+  // The input color needs to have alpha channel prepended to it.
+  (view.background as GradientDrawable).setColor((0xff000000 or colorRgb.toLong()).toInt())
```
Comment (nikitamarysolomanpvt) [inline app/src/main/java/org/oppia/app/databinding/DrawableBindingAdapters.kt:14]: Is't supposed to be added in resource file.

File: app/src/main/java/org/oppia/app/home/topiclist/TopicListAdapter.kt (hunk 13 above)
Comment (rt4914) [reply app/src/main/java/org/oppia/app/home/topiclist/TopicListAdapter.kt]: Done. Updated error message to:
`IllegalArgumentException("Invalid type of data $position with item ${itemList[position]}")`

File: app/src/main/java/org/oppia/app/home/topiclist/TopicListAdapter.kt (hunk 12 above)
Comment (rt4914) [reply app/src/main/java/org/oppia/app/home/topiclist/TopicListAdapter.kt]: Updated error to `IllegalArgumentException("Invalid view type: $viewType")`

File: app/src/sharedTest/java/org/oppia/app/home/HomeActivityTest.kt (hunk 24 above)
Comment (rt4914) [reply app/src/sharedTest/java/org/oppia/app/home/HomeActivityTest.kt:200]: Done. Added verification for topicId and storyId.

File: app/src/sharedTest/java/org/oppia/app/home/HomeActivityTest.kt (hunk 23 above)
Comment (rt4914) [reply app/src/sharedTest/java/org/oppia/app/home/HomeActivityTest.kt]: Done. I have made changes to the description in #135 and your approach makes much more sense to me.

**Review by nikitamarysolomanpvt — CHANGES_REQUESTED** [review]
PTAL

- step to follow while testing
1. Turn on the auto-rotate in the device
2. Keep your device in LANDSCAPE mode.
3. Now start playing test cases.
- Issue 
Seven test cases failed
- Expected result 
All test cases should be successful
small

- It seems the configuration changes in test cases are not working. 

-  PTAL on other Nit changes.

File: app/src/main/java/org/oppia/app/databinding/DrawableBindingAdapters.kt (hunk 28 above)
Comment (rt4914) [reply app/src/main/java/org/oppia/app/databinding/DrawableBindingAdapters.kt:14]: @BenHenning Can you address this given the case that I have used this from your code.

**Comment by rt4914** [comment]
> PTAL
> 
> * step to follow while testing
> 
> 1. Turn on the auto-rotate in the device
> 2. Keep your device in LANDSCAPE mode.
> 3. Now start playing test cases.
> 
> * Issue
>   Seven test cases failed
> * Expected result
>   All test cases should be successful
> 
> small
> 
> * It seems the configuration changes in test cases are not working.
> * PTAL on other Nit changes.

All tests were written assuming that device will be in portrait mode. Thanks for pointing this out.

Added `onView(withId(R.id.home_recycler_view)).perform(scrollToPosition<RecyclerView.ViewHolder>(3))` this and similar index based scrolling to resolve this issue.

File: app/src/sharedTest/java/org/oppia/app/home/HomeActivityTest.kt (hunk 25 above)
Comment (rt4914) [reply app/src/sharedTest/java/org/oppia/app/home/HomeActivityTest.kt:118]: Introduced new file `OrientationChangeAction` which helps to work with orientationchange along with visibility.
`onView(isRoot()).perform(orientationLandscape())`

@BenHenning Please check this new implementation for orientation change.

File: app/src/sharedTest/java/org/oppia/app/home/HomeActivityTest.kt (hunk 26 above)
Comment (rt4914) [reply app/src/sharedTest/java/org/oppia/app/home/HomeActivityTest.kt:188]: Replied above.

File: app/src/sharedTest/java/org/oppia/app/home/HomeActivityTest.kt (hunk 27 above)
Comment (rt4914) [reply app/src/sharedTest/java/org/oppia/app/home/HomeActivityTest.kt:272]: Replied above.

File: app/src/main/res/layout/promoted_story_card.xml (hunk 19 above)
Comment (rt4914) [reply app/src/main/res/layout/promoted_story_card.xml:1]: Sent an email.

File: app/src/sharedTest/java/org/oppia/app/utility/OrientationChangeAction.kt [hunk 29]
```diff
@@ -0,0 +1,51 @@
...
+import android.content.Context
+import android.content.ContextWrapper
+import android.view.ViewGroup
+
+// https://gist.github.com/nbarraille/03e8910dc1d415ed9740
+/** This class helps in managing orientation changes in test-cases which are visible on device too. */
+class OrientationChangeAction(private val orientation: Int) : ViewAction {
+
+  companion object {
+    fun orientationLandscape(): ViewAction = OrientationChangeAction(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE)
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/app/utility/OrientationChangeAction.kt:19]: Let's make these file-level functions instead of companion functions. Then we can make this action private to the file to make things a bit cleaner.

File: app/src/sharedTest/java/org/oppia/app/utility/OrientationChangeAction.kt [hunk 30]
```diff
@@ -0,0 +1,51 @@
...
+      var i = 0
+      while (i < c && activity == null) {
+        activity = getActivity(view.getChildAt(i).context)
+        ++i
+      }
+    }
+    activity!!.requestedOrientation = orientation
+  }
+
+  private fun getActivity(context: Context): Activity? {
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/app/utility/OrientationChangeAction.kt:41]: Nit: getFirstActivity since activities can inherit from other activities.

File: app/src/sharedTest/java/org/oppia/app/utility/OrientationChangeAction.kt [hunk 31]
```diff
@@ -0,0 +1,51 @@
...
+  override fun getConstraints(): Matcher<View> = isRoot()
+
+  override fun perform(uiController: UiController, view: View) {
+    uiController.loopMainThreadUntilIdle()
+    var activity = getActivity(view.context)
+    if (activity == null && view is ViewGroup) {
+      val c = view.childCount
+      var i = 0
+      while (i < c && activity == null) {
+        activity = getActivity(view.getChildAt(i).context)
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/app/utility/OrientationChangeAction.kt:34]: Why can't we just use the ViewGroup's context? This extra iteration is a bit confusing.

File: app/src/sharedTest/java/org/oppia/app/home/HomeActivityTest.kt (hunk 25 above)
Comment (BenHenning) [reply app/src/sharedTest/java/org/oppia/app/home/HomeActivityTest.kt:118]: Is this just for convenience? I'm trying to understand why it's needed versus ``scenario.onActivity { activity -> activity.requestedOrientation = ... }``

File: app/src/main/java/org/oppia/app/databinding/DrawableBindingAdapters.kt (hunk 28 above)
Comment (BenHenning) [reply app/src/main/java/org/oppia/app/databinding/DrawableBindingAdapters.kt:14]: What specifically should be added to a resource file? There's nothing here that's really shareable. The ``0xff000000`` isn't a color, it's an alpha filter so it wouldn't belong in a resource file. Is there another aspect of this that you think should be in a resource file?

**Comment by BenHenning** [comment]
@rt4914 I did not do another pass on this. Let me know if you'd like me to, or want to discuss the specific aspects that you mentioned me in above.

File: app/src/sharedTest/java/org/oppia/app/home/HomeActivityTest.kt (hunk 25 above)
Comment (rt4914) [reply app/src/sharedTest/java/org/oppia/app/home/HomeActivityTest.kt:118]: @BenHenning When we use 
`scenario.onActivity { activity -> activity.requestedOrientation = ... }`
the test cases pass but the orientation change is not visible on screen.
The `OrientationChangeAction` file makes sure that the orientation change is actually visible on device when we run these test cases.

File: app/src/sharedTest/java/org/oppia/app/utility/OrientationChangeAction.kt (hunk 30 above)
Comment (rt4914) [reply app/src/sharedTest/java/org/oppia/app/utility/OrientationChangeAction.kt:41]: Done.

File: app/src/sharedTest/java/org/oppia/app/utility/OrientationChangeAction.kt (hunk 31 above)
Comment (rt4914) [reply app/src/sharedTest/java/org/oppia/app/utility/OrientationChangeAction.kt:34]: I did try to use the viewgroup's context but that was leading to `NullPointerException` error and therefore keeping it as it is for now.

File: app/src/main/java/org/oppia/app/databinding/DrawableBindingAdapters.kt (hunk 28 above)
Comment (nikitamarysolomanpvt) [reply app/src/main/java/org/oppia/app/databinding/DrawableBindingAdapters.kt:14]: I mentioned about 0xff000000 only.
We may add color with alpha filter in resource files is't?.(Just to clarify)
Just for example like the below code.
[https://android.googlesource.com/platform/frameworks/base/+/master/core/res/res/values/colors.xml ](https://android.googlesource.com/platform/frameworks/base/+/master/core/res/res/values/colors.xml )

File: app/src/sharedTest/java/org/oppia/app/utility/OrientationChangeAction.kt (hunk 29 above)
Comment (rt4914) [reply app/src/sharedTest/java/org/oppia/app/utility/OrientationChangeAction.kt:19]: I am actually in favour of keeping this implementation because this makes the usage of these functions quite easy in test cases. 

sample:

`onView(isRoot()).perform(orientationLandscape())`

File: app/src/main/res/layout/home_fragment.xml [hunk 32]
```diff
@@ -1,37 +1,30 @@
...
-    android:layout_height="match_parent">
-    <TextView
-      android:id="@+id/welcome_text_view"
-      android:layout_width="wrap_content"
+    android:layout_height="match_parent"
+    android:background="@color/white"
+    android:orientation="vertical">
+
+    <androidx.recyclerview.widget.RecyclerView
+      android:id="@+id/home_recycler_view"
```
Comment (nikitamarysolomanpvt) [inline app/src/main/res/layout/home_fragment.xml:21]: Because of this change StateFragmentTest file is raising issue "play_exploration_button not found". Please do fix.

**Review by nikitamarysolomanpvt — APPROVED** [review]
LGTM .Please fix the comment mentioned

File: app/src/main/res/layout/home_fragment.xml (hunk 32 above)
Comment (rt4914) [reply app/src/main/res/layout/home_fragment.xml:21]: There was one dummy button in this file to traverse to ExplorationActivity,

@BenHenning suggested to remove that dummy button, but because this button was connected to tests also, the test cases which were written earlier were breaking, for now I am keeping this dummy button and we will need to remove this button once all Low-fi work is done.

**Comment by rt4914** [comment]
Merging this PR for now, there are some open comments which will be discussed once low-fi is finished but those comments are non-blocking.
