### PR TITLE
Fixes #4100 : Added tests for PolynomialSubject

### LINKED ISSUE #4100: Add tests for PolynomialSubject
#4050 introduces a new custom Truth test subject: PolynomialSubject. It would be advantageous to add thorough tests for this to ensure that:
- Each of the subject methods correctly allow users to test specific properties of the protos each subject helps verify
- Each of the subject methods are verified to fail when expected (i.e. when used with an incompatible proto property) with the correct failure reason being verified

See #4097 for a similar issue.

### PR DESCRIPTION
**Pull request by theayushyadav11**
Fix #4100
### New Tests for Polynomial Functionality:

* **Build Configuration Update:**
  * Added a new test target `PolynomialSubjectTest` to the `BUILD.bazel` file. This includes necessary dependencies and configurations for the new test.

* **New Test File:**
  * Created `PolynomialSubjectTest.kt` which contains various test cases to validate polynomial operations. This includes tests for checking invalid polynomials, constant polynomials, term counts, and polynomial evaluations.

#### Screenshot of the passing tests.
Screenshot from 2025-01-26 16-03-01

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).
This pull request introduces a new set of tests for polynomial-related functionality in the `oppia_android_test` project. The primary changes include the addition of a new test file and corresponding updates to the build configuration.

### CODE REVIEW

**Comment by theayushyadav11** [comment]
Hey @adhiamboperes PTAL, and suggest me any changes if needed.

File: scripts/assets/test_file_exemptions.textproto [hunk 1]
```diff
@@ -4107,7 +4107,7 @@ test_file_exemption {
   test_file_not_required: true
 }
 test_file_exemption {
-  exempted_file_path: "testing/src/main/java/org/oppia/android/testing/math/PolynomialSubject.kt"
+  exempted_file_path: "testing/src/main/java/org/oppia/android/testing/math/RealSubject.kt"
```
Comment (adhiamboperes) [inline scripts/assets/test_file_exemptions.textproto]: Why did you change this instead of removing it? AFAIK RealSubject already has an exemption in ln4142

File: testing/src/test/java/org/oppia/android/testing/math/PolynomialSubjectTest.kt [hunk 2]
```diff
@@ -0,0 +1,173 @@
...
+          .addVariable(Polynomial.Term.Variable.newBuilder().setName("x").setPower(1))
+      )
+      .build()
+    assertThrows(AssertionError::class.java) {
+      PolynomialSubject.assertThat(nonConstantPolynomial).isConstantThat()
+    }
+  }
+
+  @Test
+  fun testPolynomialSubject_withZeroTerms_hasTermCountThat() {
```
Comment (adhiamboperes) [inline testing/src/test/java/org/oppia/android/testing/math/PolynomialSubjectTest.kt]:
```suggestion
  fun testPolynomialSubject_withZeroTerms_hasTermCountThatIsEqualToZero() {
```

Explicitly names the expected outcome.

File: testing/src/test/java/org/oppia/android/testing/math/PolynomialSubjectTest.kt [hunk 3]
```diff
@@ -0,0 +1,173 @@
...
+      .addTerm(Polynomial.Term.newBuilder().setCoefficient(Real.newBuilder().setInteger(5)))
+      .build()
+    PolynomialSubject.assertThat(constantPolynomial)
+      .isConstantThat()
+      .isIntegerThat()
+      .isEqualTo(5)
+  }
+
+  @Test
+  fun testPolynomialSubject_withNonConstantPolynomial_isConstantThat_fails() {
```
Comment (adhiamboperes) [inline testing/src/test/java/org/oppia/android/testing/math/PolynomialSubjectTest.kt]:
```suggestion
  fun testPolynomialSubject_ testIsConstantThat _withNonConstantPolynomial_fails() {
```

File: testing/src/test/java/org/oppia/android/testing/math/PolynomialSubjectTest.kt [hunk 4]
```diff
@@ -0,0 +1,173 @@
...
+  @Test
+  fun testPolynomialSubject_withZeroTerms_hasTermCountThat() {
+    val emptyPolynomial = Polynomial.newBuilder().build()
+    PolynomialSubject.assertThat(emptyPolynomial)
+      .hasTermCountThat()
+      .isEqualTo(0)
+  }
+
+  @Test
+  fun testPolynomialSubject_withMultipleTerms_hasTermCountThat() {
```
Comment (adhiamboperes) [inline testing/src/test/java/org/oppia/android/testing/math/PolynomialSubjectTest.kt]:
```suggestion
  fun testPolynomialSubject_withTwoTerms_hasTermCountThatIsEqualToTwo() {
```

File: testing/src/test/java/org/oppia/android/testing/math/PolynomialSubjectTest.kt [hunk 5]
```diff
@@ -0,0 +1,173 @@
...
+          .addVariable(Polynomial.Term.Variable.newBuilder().setName("y").setPower(1))
+      )
+      .build()
+
+    PolynomialSubject.assertThat(polynomial)
+      .term(0)
+      .hasCoefficientThat()
+      .isIntegerThat()
+      .isEqualTo(5)
+
```
Comment (adhiamboperes) [inline testing/src/test/java/org/oppia/android/testing/math/PolynomialSubjectTest.kt:102]: Test name suggests we are asserting the availability of coefficient, so this looks like it does not belong here.

File: testing/src/test/java/org/oppia/android/testing/math/PolynomialSubjectTest.kt [hunk 6]
```diff
@@ -0,0 +1,173 @@
...
+  @Test
+  fun testPolynomialSubject_failsWithInvalidIndex() {
+    val polynomial = Polynomial.newBuilder().build()
+    assertThrows(IndexOutOfBoundsException::class.java) {
+      PolynomialSubject.assertThat(polynomial).term(0)
+    }
+  }
+
+  @Test
+  fun testPolynomialSubject_withConstantPolynomial_evaluatesToPlainTextThat() {
```
Comment (adhiamboperes) [inline testing/src/test/java/org/oppia/android/testing/math/PolynomialSubjectTest.kt]:
```suggestion
  fun testPolynomialSubject_withConstantPolynomial_evaluatesToPlainText() {
```

File: testing/src/test/java/org/oppia/android/testing/math/PolynomialSubjectTest.kt [hunk 7]
```diff
@@ -0,0 +1,173 @@
...
+    val constantPolynomial = Polynomial.newBuilder()
+      .addTerm(Polynomial.Term.newBuilder().setCoefficient(Real.newBuilder().setInteger(5)))
+      .build()
+    PolynomialSubject.assertThat(constantPolynomial)
+      .evaluatesToPlainTextThat()
+      .isEqualTo("5")
+  }
+
+  @Test
+  fun testPolynomialSubject_withComplexPolynomial_evaluatesToPlainTextThat() {
```
Comment (adhiamboperes) [inline testing/src/test/java/org/oppia/android/testing/math/PolynomialSubjectTest.kt]:
```suggestion
  fun testPolynomialSubject_withComplexPolynomial_evaluatesToPlainText() {
```

File: testing/src/test/java/org/oppia/android/testing/math/PolynomialSubjectTest.kt [hunk 8]
```diff
@@ -0,0 +1,173 @@
...
+      )
+      .addTerm(Polynomial.Term.newBuilder().setCoefficient(Real.newBuilder().setInteger(1)))
+      .build()
+    PolynomialSubject.assertThat(polynomial)
+      .evaluatesToPlainTextThat()
+      .isEqualTo("2x^2 + 3x + 1")
+  }
+
+  @Test
+  fun testPolynomialSubject_withTermHasVariableCount_that() {
```
Comment (adhiamboperes) [inline testing/src/test/java/org/oppia/android/testing/math/PolynomialSubjectTest.kt]:
```suggestion
  fun testPolynomialSubject_withTwoTerms_hasVariableCountThatIsEqualToTwo() {
```

File: testing/src/test/java/org/oppia/android/testing/math/PolynomialSubjectTest.kt [hunk 9]
```diff
@@ -0,0 +1,173 @@
...
+    val term = Polynomial.Term.newBuilder()
+      .setCoefficient(Real.newBuilder().setInteger(5))
+      .addVariable(Polynomial.Term.Variable.newBuilder().setName("x").setPower(2))
+      .addVariable(Polynomial.Term.Variable.newBuilder().setName("y").setPower(1))
+      .build()
+
+    PolynomialSubject.assertThat(Polynomial.newBuilder().addTerm(term).build())
```
Comment (adhiamboperes) [inline testing/src/test/java/org/oppia/android/testing/math/PolynomialSubjectTest.kt]: Why not move Polynomial building to a local variable to improve readability.

Comment (adhiamboperes) [reply testing/src/test/java/org/oppia/android/testing/math/PolynomialSubjectTest.kt]: Same to the test below.

File: testing/src/test/java/org/oppia/android/testing/math/PolynomialSubjectTest.kt [hunk 10]
```diff
@@ -0,0 +1,173 @@
...
+      .term(0)
+      .hasVariableCountThat()
+      .isEqualTo(2)
+  }
+
+  @Test
+  fun testPolynomialSubject_withTermVariableHasDetails_that() {
```
Comment (adhiamboperes) [inline testing/src/test/java/org/oppia/android/testing/math/PolynomialSubjectTest.kt]:
```suggestion
  fun testPolynomialSubject_polynomialTermVariable_hasExpectedDetails() {
```

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @theayushyadav11! PTAL at the suggested changes.

File: testing/src/test/java/org/oppia/android/testing/math/PolynomialSubjectTest.kt (hunk 9 above)
Comment (theayushyadav11) [reply testing/src/test/java/org/oppia/android/testing/math/PolynomialSubjectTest.kt]: I'll add helper functions for this which will improve readability.

**Comment by theayushyadav11** [comment]
Hey @adhiamboperes PTAL!!

File: testing/src/test/java/org/oppia/android/testing/math/PolynomialSubjectTest.kt [hunk 11]
```diff
@@ -11,85 +11,92 @@ import org.oppia.android.app.model.Real
 @RunWith(JUnit4::class)
 class PolynomialSubjectTest {
 
+  // Helper function to create a polynomial term
```
Comment (adhiamboperes) [inline testing/src/test/java/org/oppia/android/testing/math/PolynomialSubjectTest.kt]:
```suggestion
  /** Helper function to create a polynomial term. */
```
Here and below: KDoc is required for public functions as opposed to comments.

File: testing/src/test/java/org/oppia/android/testing/math/PolynomialSubjectTest.kt (hunk 5 above)
Comment (adhiamboperes) [reply testing/src/test/java/org/oppia/android/testing/math/PolynomialSubjectTest.kt:102]: Apologies @theayushyadav11, I actually thought that there was a truth subject that asserts for the presence of a constant in the polynomial, but I checked the class and there isn't. Your original implementation makes the most sense, since without it, the assertion is left kind of hangind as ` .hasCoefficientThat()`.

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @theayushyadav11! I have left some comments to clean up the PR. PTAL.

**Comment by theayushyadav11** [comment]
Thanks @adhiamboperes for the review, I have updated the code, PTAL.

**Review by adhiamboperes — APPROVED** [review]
Thanks @theayushyadav11! This LGTM.
