### PR TITLE
Fix #5785, #6210 : Handle Network transition during playback 

### LINKED ISSUE #5785: [BUG]: Mobile data message is not shown when the Wifi is turned off while play audio
### Describe the bug

When the Learner is playing a Lesson with the audio and the Wifi is turned off, the Learner should be get a prompt on trying to play audio on cellular data, but it is not happen. 
The "currently on cellular data " message is shown only if the Learner starts playing the audio using celular data since from the beginning, if the Learner starts playing audio with Wifi and this turned off, the audio continues playing even when the Learner goes to the next page. 

### Steps To Reproduce

With Wifi conection

1. Go to Place Values
2. Go to What are the Place Values?
3. Play the audio
4. Turn off the Wifi
5. Keep the audio playing
6. Click on the continue button
7. The audio continue playing and the mobile data message is not shown

****

### Expected Behavior

it is expected to see a cellular data message when the Wifi is turned off while play audio.

### Screenshots/Videos

When the Wifi conection is turned off

https://github.com/user-attachments/assets/748db77b-8e10-4c8c-a13b-8f992c33723a

With mobile data ( it is working!) this is the message that I expected to see if the wifi conection is cut for some reason. 

https://github.com/user-attachments/assets/e816b2a7-e55b-4200-b85f-eadb318c76da

### What device/emulator are you using?

OPPO A79 5G

### Which Android version is your device/emulator running?

Android 14

### Which version of the Oppia Android app are you using?

0.15-beta-9404ea41d9

### Additional Context
_No response_

------
### Context

When Wi-Fi is turned off during audio playback, the app keeps playing on cellular data without showing the warning dialog. The dialog only appears if playback starts on mobile data.

**Note:** Fixing this issue will also resolve #5956 . #5956 can be addressed first to prevent crashes.

**Files to check:**

- [AudioFragmentPresenter](https://github.com/oppia/oppia-android/blob/fcb87dc79074450f90a658c9dddb186a12ab75f3/app/src/main/java/org/oppia/android/app/player/audio/AudioFragmentPresenter.kt#L42) -> funs: `handleAudioClick()`, `showCellularDataDialogFragment()`, showOfflineDialog()
- [NetworkConnectionUtil](https://github.com/oppia/oppia-android/blob/fcb87dc79074450f90a658c9dddb186a12ab75f3/utility/src/main/java/org/oppia/android/util/networking/NetworkConnectionUtil.kt#L4)

### LINKED ISSUE #6210: [BUG]: Audio gets stuck in infinite loading when network is switched
### Describe the bug

When playing audio in the Oppia Android app, switching the network (e.g., from Wi-Fi or mobile data to no network) causes the audio player to enter an infinite loading state.

### Steps To Reproduce

1. Connect to wi-fi or cellular data
2.  open a lesson/Fraction
2. Play the audio
3. Off the wifi while playing audio
4. Let it be complete 
5. Click on Continue to move to next card
6. The audio keeps loading infinitely

### Expected Behavior

A “No network” dialog should be displayed, and the loading state should stop

### Screenshots/Videos

https://github.com/user-attachments/assets/208aa7e1-6606-4850-9ee0-b02909e06c66

### What device/emulator are you using?

Galaxy A23 5G

### Which Android version is your device/emulator running?

Android 14

### Which version of the Oppia Android app are you using?

0.18-dev-bafece474e

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by itsadityaaaaa**
## Explanation

Fixes #5785 
Fixes #6210 
 This PR improving audio playback behavior when the network connection changes during playback, ensuring the user receives appropriate warnings while audio continues playing.
 
- Changes -
1. Added Robolectric regression tests for network transitions (Wi-Fi → cellular, Wi-Fi → offline) during audio playback.
2. Updated AudioFragmentPresenter to track the last known network state and show dialogs conditionally during content reloads.
3. Added a function to avoid infinite loading during no connection.

Failed Test Demonstrating they can catch the issue (Test are Failing without fixes)
Screenshot from 2026-04-09 14-45-41

## Essential Checklist

- [x] The PR title starts with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The explanation section above starts with "Fixes #bugnum: " (If this PR fixes part of an issue, use instead: "Fixes part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- For PRs introducing new UI elements or color changes, both light and dark mode screenshots must be included
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing
- 

https://github.com/user-attachments/assets/a7892921-e7b8-4d77-904e-e5c38a6859e7

https://github.com/user-attachments/assets/702da4f9-5e30-4d24-8f4b-271f59f57bfd

### CODE REVIEW

File: app/src/main/java/org/oppia/android/app/player/audio/AudioFragmentPresenter.kt [hunk 1]
```diff
@@ -354,6 +389,19 @@ class AudioFragmentPresenter @Inject constructor(
...
+      .setTitle(resourceHandler.getStringInLocale(R.string.cellular_data_alert_dialog_title))
+      .setMessage(
+        resourceHandler.getStringInLocale(R.string.cellular_data_alert_dialog_description)
+      )
+      .setPositiveButton(
+        resourceHandler.getStringInLocale(R.string.cellular_data_alert_dialog_okay_button)
+      ) { dialog, _ ->
+        dialog.dismiss()
+      }.create().show()
+  }
```
[the remark this answers is not in the document]
Comment (itsadityaaaaa) [reply app/src/main/java/org/oppia/android/app/player/audio/AudioFragmentPresenter.kt]: done

File: app/src/main/java/org/oppia/android/app/player/audio/AudioFragmentPresenter.kt [hunk 2]
```diff
@@ -222,7 +223,41 @@ class AudioFragmentPresenter @Inject constructor(
     audioViewModel.setStateAndExplorationId(newState, explorationId)
 
   fun loadMainContentAudio(allowAutoPlay: Boolean, reloadingContent: Boolean) =
+    maybeLoadMainContentAudio(allowAutoPlay, reloadingContent)
+
+  private fun maybeLoadMainContentAudio(allowAutoPlay: Boolean, reloadingContent: Boolean) {
+    val currentConnectionStatus =
+      networkConnectionUtil.getCurrentConnectionStatus()
+        as? NetworkConnectionUtil.ProdConnectionStatus
+        ?: NetworkConnectionUtil.ProdConnectionStatus.NONE
```
[the remark this answers is not in the document]
Comment (itsadityaaaaa) [reply app/src/main/java/org/oppia/android/app/player/audio/AudioFragmentPresenter.kt]: done

File: app/src/main/java/org/oppia/android/app/player/audio/AudioFragmentPresenter.kt [hunk 3]
```diff
@@ -222,7 +223,41 @@ class AudioFragmentPresenter @Inject constructor(
     audioViewModel.setStateAndExplorationId(newState, explorationId)
 
   fun loadMainContentAudio(allowAutoPlay: Boolean, reloadingContent: Boolean) =
+    maybeLoadMainContentAudio(allowAutoPlay, reloadingContent)
```
[the remark this answers is not in the document]
Comment (itsadityaaaaa) [reply app/src/main/java/org/oppia/android/app/player/audio/AudioFragmentPresenter.kt:226]: done

**Comment by itsadityaaaaa** [comment]
Hi @adhiamboperes Please take a look on my approach and let me know if any changes are required.

File: app/src/main/java/org/oppia/android/app/player/audio/AudioFragmentPresenter.kt [hunk 4]
```diff
@@ -222,7 +223,50 @@ class AudioFragmentPresenter @Inject constructor(
...
+      else -> null
+    }
+  }
+
+  private fun maybeLoadMainContentAudio(allowAutoPlay: Boolean, reloadingContent: Boolean) {
+    val currentConnectionStatus = getCurrentProdConnectionStatusOrNull()
+      ?: run {
+        audioViewModel.loadMainContentAudio(allowAutoPlay, reloadingContent)
+        return
+      }
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/player/audio/AudioFragmentPresenter.kt:241]: Should `lastKnownConnectionStatus` be updated in this branch too?

File: app/src/main/java/org/oppia/android/app/player/audio/AudioFragmentPresenter.kt [hunk 5]
```diff
@@ -222,7 +223,50 @@ class AudioFragmentPresenter @Inject constructor(
...
+        NetworkConnectionUtil.ProdConnectionStatus.CELLULAR -> {
+          if (
+            hasConnectionStatusChanged &&
+            previousConnectionStatus == NetworkConnectionUtil.ProdConnectionStatus.LOCAL
+          ) {
+            showCellularDataDialogFragment()
+          }
+        }
+        NetworkConnectionUtil.ProdConnectionStatus.LOCAL -> {
+        }
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/player/audio/AudioFragmentPresenter.kt:267]:
```suggestion
        NetworkConnectionUtil.ProdConnectionStatus.LOCAL -> {} // no-op
```

Lets developers know that the branch is intentionally empty.

File: app/src/main/java/org/oppia/android/app/player/audio/AudioFragmentPresenter.kt [hunk 6]
```diff
@@ -222,7 +223,50 @@ class AudioFragmentPresenter @Inject constructor(
...
+          }
+          lastKnownConnectionStatus = currentConnectionStatus
+          return
+        }
+        NetworkConnectionUtil.ProdConnectionStatus.CELLULAR -> {
+          if (
+            hasConnectionStatusChanged &&
+            previousConnectionStatus == NetworkConnectionUtil.ProdConnectionStatus.LOCAL
+          ) {
+            showCellularDataDialogFragment()
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/player/audio/AudioFragmentPresenter.kt:261]: After showing the dialog, execution continues and loads audio anyway. 

https://github.com/oppia/oppia-android/blob/0e297f7f87a4890d076541736a470aafdfe6fadb/app/src/main/java/org/oppia/android/app/player/audio/CellularAudioDialogFragment.kt#L34-L55 

is designed to gate behavior based on user choice:

```kotlin
cellularDataInterface.enableAudioWhileOnCellular(checkBox.isChecked)
cellularDataInterface.disableAudioWhileOnCellular(checkBox.isChecked)
```

But the audio is already being loaded before the user decides anything, effectively user consent is bypassed.

We should pause execution until the user makes a choice, which can be done by adding a `return` to this block.

File: domain/src/main/java/org/oppia/android/domain/audio/AudioPlayerController.kt [hunk 7]
```diff
@@ -275,6 +275,19 @@ class AudioPlayerController @Inject constructor(
     }
   }
 
+  /** Aborts any in-flight load and moves playback to a failure state. */
+  fun abortPendingLoad() {
```
Comment (adhiamboperes) [inline domain/src/main/java/org/oppia/android/domain/audio/AudioPlayerController.kt:279]: Public APIs must be tested.

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @itsadityaaaaa! PTAL at my feedback.

File: app/src/main/java/org/oppia/android/app/player/audio/AudioFragmentPresenter.kt (hunk 5 above)
Comment (itsadityaaaaa) [reply app/src/main/java/org/oppia/android/app/player/audio/AudioFragmentPresenter.kt:267]: added comment for this

File: domain/src/main/java/org/oppia/android/domain/audio/AudioPlayerController.kt (hunk 7 above)
Comment (itsadityaaaaa) [reply domain/src/main/java/org/oppia/android/domain/audio/AudioPlayerController.kt:279]: added tests for this

File: app/src/main/java/org/oppia/android/app/player/audio/AudioFragmentPresenter.kt (hunk 6 above)
Comment (itsadityaaaaa) [reply app/src/main/java/org/oppia/android/app/player/audio/AudioFragmentPresenter.kt:261]: done

File: app/src/main/java/org/oppia/android/app/player/audio/AudioFragmentPresenter.kt (hunk 4 above)
Comment (itsadityaaaaa) [reply app/src/main/java/org/oppia/android/app/player/audio/AudioFragmentPresenter.kt:241]: updated to null

**Comment by itsadityaaaaa** [comment]
Hi @adhiamboperes I have applied the suggestions, please take a look I have added tests for api and on further testing i have found some regression so some small fix in logic is also applied take a look on it also.

File: app/src/main/java/org/oppia/android/app/player/audio/AudioFragmentPresenter.kt (hunk 4 above)
Comment (adhiamboperes) [reply app/src/main/java/org/oppia/android/app/player/audio/AudioFragmentPresenter.kt:241]: I think the premise of using null is incorrect.  `enum ProdConnectionStatus` has a `NONE` field, which should be used in case of no connection, and not null. I believe that should be the default value of `lastKnownConnectionStatus`

File: domain/src/test/java/org/oppia/android/domain/audio/AudioPlayerControllerTest.kt [hunk 8]
```diff
@@ -504,6 +504,43 @@ class AudioPlayerControllerTest {
...
+  fun testController_preparePlayer_abortPendingLoad_multipleTimes_doesNotThrow() {
+    setUpMediaReadyApplication()
+    arrangeMediaPlayer()
+
+    assertNoExceptionIsThrown {
+      audioPlayerController.abortPendingLoad()
+      audioPlayerController.abortPendingLoad()
+    }
+  }
+
```
Comment (adhiamboperes) [inline domain/src/test/java/org/oppia/android/domain/audio/AudioPlayerControllerTest.kt:548]: I am wondering if we need another test to check that the failure is caught when `abortPendingLoad` is called multiple times?

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @itsadityaaaaa! I had a couple of followups, PTAL.

File: domain/src/test/java/org/oppia/android/domain/audio/AudioPlayerControllerTest.kt (hunk 8 above)
Comment (itsadityaaaaa) [reply domain/src/test/java/org/oppia/android/domain/audio/AudioPlayerControllerTest.kt:548]: Hi @adhiamboperes I have fixed the test to also caught the failure also and change the null to ```NONE``` . Please take a look.

**Comment by itsadityaaaaa** [comment]
Hey @adhiamboperes, Please re-run the workflow as the failing tests are due to network dependency.

**Review by adhiamboperes — APPROVED** [review]
Thanks @itsadityaaaaa, This LGTM.

Also restarted the failing tests.
