### PR TITLE
Fix #1592 And #5657: Previous responses header collapsed state not retained across landscape changes

### LINKED ISSUE #1592: Previous responses header collapsed state not retained across landscape changes
**Describe the bug**
If the previous responses header is in expanded state in `Exploration/Question` player, on configuration change, it changes back to collapsed state.

**To Reproduce**
1. Open any exploration / question player
2. Mark 2-3 incorrect answers
3. Click on `Previous Responses` so that it is now in expanded state
4. Change configuration to landscape
5. The `Previous Responses` header is now in collapsed state.

**Expected behavior**
Configuration change should persist the state of `Previous Responses` header.

Additional context: Please refer to PRs https://github.com/oppia/oppia-android/pull/5458 and https://github.com/oppia/oppia-android/pull/5478 for hints on how to resolve this.

### PR DESCRIPTION
**Pull request by TanishMoral11**
## Explanation  
Fix #1592 #5657 
This PR introduces the functionality to save and restore the expanded state of the previous responses view. The changes include:

- Added methods `saveExpandedState` and `restoreExpandedState` in `StateFragmentPresenter` and `StatePlayerRecyclerViewAssembler` to handle saving and restoring state.
- Updated `StateFragment` to call `restoreExpandedState` during `onViewCreated`.

These changes ensure that the expanded state of the view is preserved across configuration changes.

## Essential Checklist  
- [x] The PR title and explanation each start with "Fix part of #1592: ".
- [ ] Any changes to scripts/assets files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers.

After Changes : 

https://github.com/user-attachments/assets/c9834b1d-cc6f-4c3b-98d8-ca410d1917e2

### CODE REVIEW

**Comment by TanishMoral11** [comment]
Hey @adhiamboperes , PTAL !!

Also , I’m a bit unsure about how to write the tests to verify these changes. 
I am thinking first I’ll store the previous response header as Expanded, then change its orientation and check if the state is still Expanded, so yay! :)
Could you please guide me on the best approach for writing the tests for these modifications?

Thanks .

**Comment by TanishMoral11** [comment]
Hey @adhiamboperes , PTAL !!
This PR is ready for review.
Thanks.

File: app/src/main/java/org/oppia/android/app/player/state/StateFragment.kt [hunk 1]
```diff
@@ -170,5 +170,11 @@ class StateFragment :
       STATE_FRAGMENT_STATE_KEY,
       stateFragmentPresenter.getUserAnswerState()
     )
+    stateFragmentPresenter.saveExpandedState(outState)
+  }
+
+  override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
+    super.onViewCreated(view, savedInstanceState)
+    stateFragmentPresenter.restoreExpandedState(savedInstanceState)
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/player/state/StateFragment.kt]: What's the benefit of using `onViewCreated` over the  existing `onCreateView` to restore state?

File: app/src/main/java/org/oppia/android/app/player/state/StateFragmentPresenter.kt [hunk 2]
```diff
@@ -617,4 +618,12 @@ class StateFragmentPresenter @Inject constructor(
       SurveyQuestionName.NPS
     )
   }
+
+  fun saveExpandedState(outState: Bundle) {
+    recyclerViewAssembler.saveExpandedState(outState)
+  }
+
+  fun restoreExpandedState(savedInstanceState: Bundle?) {
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/player/state/StateFragmentPresenter.kt]: As public functions, these should have KDocs.

File: app/src/main/java/org/oppia/android/app/player/state/StatePlayerRecyclerViewAssembler.kt [hunk 3]
```diff
@@ -1506,4 +1507,15 @@ class StatePlayerRecyclerViewAssembler private constructor(
       }
     }
   }
+
+  /** Saves the expanded state to a Bundle. */
+  fun saveExpandedState(outState: Bundle) {
+    outState.putBoolean("hasPreviousResponsesExpanded", hasPreviousResponsesExpanded)
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/player/state/StatePlayerRecyclerViewAssembler.kt]: Here and below: name constants are usually preferred, or use patterns already established in this class. Additionally, we use protos for Bundles. Please see https://github.com/oppia/oppia-android/pull/5458 for example.

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @TanishMoral11!! I have left some comments, and when addressing them, please also brainstorm how to test these changes.

File: app/src/main/java/org/oppia/android/app/player/state/StateFragment.kt (hunk 1 above)
Comment (TanishMoral11) [reply app/src/main/java/org/oppia/android/app/player/state/StateFragment.kt]: Thanks @adhiamboperes !!
So Basically `onViewCreated` is a more suitable lifecycle method for restoring the state of UI elements

because it is called after the view hierarchy has been fully created and initialized. This ensures that the state restoration logic is applied to fully initialized views, which reducing the risk of encountering issues related to incomplete view initialization.

File: app/src/main/java/org/oppia/android/app/player/state/StateFragmentPresenter.kt (hunk 2 above)
Comment (TanishMoral11) [reply app/src/main/java/org/oppia/android/app/player/state/StateFragmentPresenter.kt]: Thanks @adhiamboperes, for the suggestion.

File: app/src/main/java/org/oppia/android/app/player/state/StatePlayerRecyclerViewAssembler.kt (hunk 3 above)
Comment (TanishMoral11) [reply app/src/main/java/org/oppia/android/app/player/state/StatePlayerRecyclerViewAssembler.kt]: Sure...

**Comment by TanishMoral11** [comment]
Hi @adhiamboperes  , PTAL

After Added Test : 

Image

**Comment by adhiamboperes** [comment]
@TanishMoral11, Thanks for making the changes. There is one open comment, and in addition, is the screen recording meant to demonstrate that the responses list remains expanded accross config change? How about a demo of the coollapsed state?

**Comment by TanishMoral11** [comment]
Thank you for your review @adhiamboperes . In the video, I’ve demonstrated that the responses list remains expanded across the configuration change. Additionally, the collapsed state functions as expected, with the previous header/list staying collapsed.

I’ve also attached a video that showcases both scenarios—whether the list is expanded or collapsed—so you can review both cases.


https://github.com/user-attachments/assets/0488fc89-1712-415d-b78c-37441a545fa8

File: app/src/test/java/org/oppia/android/app/player/state/StateFragmentLocalTest.kt [hunk 4]
```diff
@@ -1455,6 +1455,32 @@ class StateFragmentLocalTest {
     }
   }
 
+  @Test
+  fun testStateFragment_previousResponsesExpanded_retainedOnRotation() {
```
Comment (adhiamboperes) [inline app/src/test/java/org/oppia/android/app/player/state/StateFragmentLocalTest.kt:1459]: Create a duplicate test for the collapsed state.

File: app/src/main/java/org/oppia/android/app/player/state/StatePlayerRecyclerViewAssembler.kt [hunk 5]
```diff
@@ -1548,4 +1550,15 @@ class StatePlayerRecyclerViewAssembler private constructor(
...
+  /** Saves the expanded state to a Bundle. */
+  fun saveExpandedState(outState: Bundle) {
+    outState.putBoolean(HAS_PREVIOUS_RESPONSES_EXPANDED_KEY, hasPreviousResponsesExpanded)
+  }
+
+  /** Restores the expanded state from a Bundle. */
+  fun restoreExpandedState(savedInstanceState: Bundle?) {
+    hasPreviousResponsesExpanded =
+      savedInstanceState?.getBoolean(HAS_PREVIOUS_RESPONSES_EXPANDED_KEY, false) ?: false
+  }
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/player/state/StatePlayerRecyclerViewAssembler.kt]: We have moved to using protos only for arguments.(We refactored all usages of getInt, Boolean, String etc). PTAL at https://github.com/oppia/oppia-android/blob/6e349bc9f21a685861214c6164adbc1af78f30fa/app/src/main/java/org/oppia/android/app/topic/lessons/TopicLessonsFragment.kt#L78-L89 for reference. The protos are created in `arguments.proto`.

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
PTAL, thanks @TanishMoral11! 

Latest video looks good to me.

File: app/src/test/java/org/oppia/android/app/player/state/StateFragmentLocalTest.kt (hunk 4 above)
Comment (TanishMoral11) [reply app/src/test/java/org/oppia/android/app/player/state/StateFragmentLocalTest.kt:1459]: Done.

**Comment by TanishMoral11** [comment]
Hi @adhiamboperes , PTAL 
I moved the code to use protocol buffers for better state management.

Thanks !

**Comment by TanishMoral11** [comment]
Hi @adhiamboperes , PTAL.
Thanks !!

**Review by adhiamboperes — APPROVED** [review]
LGTM, thanks @TanishMoral11!
