### PR TITLE
Fixes #1220 : Added IsEqualToOrderingWithOneItemIncorrect Classifier Rule 

### LINKED ISSUE #1220: Add classifiers isEqualToOrderingWithOneItemAtIncorrectPosition
Add new classifier rule `isEqualToOrderingWithOneItemAtIncorrectPositionAdd classifiers isEqualToOrderingWithOneItemAtIncorrectPosition`

**Target PR date**: 23 May 2020
**Target completion date**: 25 May 2020

### PR DESCRIPTION
**Pull request by aggarwalpulkit596**
## Explanation

Fixes #1220 

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

File: domain/src/main/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemAtIncorrectPositionClassifierProvider.kt [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+      expectedObjectType = InteractionObject.ObjectTypeCase.LIST_OF_SETS_OF_HTML_STRING,
+      inputParameterName = "x",
+      matcher = this
+    )
+  }
+
+  override fun matches(answer: ListOfSetsOfHtmlStrings, input: ListOfSetsOfHtmlStrings): Boolean {
+    val answerStringSets = answer.setOfHtmlStringsList
+    val inputStringSets = input.setOfHtmlStringsList
+    return (answerStringSets zip inputStringSets).map { (first, second) ->
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemAtIncorrectPositionClassifierProvider.kt]: You might be able to keep this a bit closer to the original algorithm by counting the number of differences, e.g.:

```kotlin
  return (answerStringSets zip inputStringSets).map { (first, second) ->
    return ((first union second) subtract (first intersect second)).size
  }.reduce(Int::plus) == 1
```

File: domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemAtIncorrectPositionClassifierProviderTest.kt [hunk 2]
```diff
@@ -0,0 +1,160 @@
...
+      isEqualToOrderingWithOneItemAtIncorrectPositionClassifier.matches(
+        answer = LIST_OF_SETS_123,
+        inputs = inputs
+      )
+
+    assertThat(matches).isFalse()
+  }
+
+  @Test
+  fun testAnswer_testLisOfSetsOfHtmlString_differByOneElement_bothValuesDoNotMatch() {
```
Comment (BenHenning) [inline domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemAtIncorrectPositionClassifierProviderTest.kt]: Suggest also adding a test with more than 1 difference to show it doesn't match. Also, maybe another test where there's one difference in one of the sets, but the order is wrong (so the overall result should be not matching).

File: domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemAtIncorrectPositionClassifierProviderTest.kt [hunk 3]
```diff
@@ -0,0 +1,160 @@
...
+class DragDropSortInputIsEqualToOrderingWithOneItemAtIncorrectPositionClassifierProviderTest {
+  private val NON_NEGATIVE_VALUE_0 = createNonNegativeInt(value = 0)
+  private val ITEM_SET_1_AB = listOf("item a", "item b")
+  private val ITEM_SET_1_A = listOf("item a")
+  private val ITEM_SET_2_ITEM_2 = listOf("item 2")
+  private val ITEM_SET_3_ITEM_3 = listOf("item 3")
+  private val ITEM_SET_4_INVALID_AB = listOf("item invalid a", "item invalid b")
+  private val LIST_OF_SETS_123 =
+    createListOfSetsOfHtmlStrings(ITEM_SET_1_AB, ITEM_SET_2_ITEM_2, ITEM_SET_3_ITEM_3)
+  private val LIST_OF_SETS_132 =
```
Comment (BenHenning) [inline domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemAtIncorrectPositionClassifierProviderTest.kt]: I suggest naming these to more specifically represent what they contain, or inline the values. As it stands, these current names may require the reader to look at their values in order to understand what the test body is doing & verify that it's correct at a glance.

Perhaps:

```kotlin
SET_LIST_ITEMS_AB_ITEM_3_ITEM_2
SET_LIST_ITEM_A_ITEM_2_ITEM_3
```

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @aggarwalpulkit596! Had a few specific requested changes for the tests, but the PR overall LGTM.

File: domain/src/main/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemAtIncorrectPositionClassifierProvider.kt [hunk 4]
```diff
@@ -0,0 +1,41 @@
...
+import org.oppia.domain.classify.rules.GenericRuleClassifier
+import org.oppia.domain.classify.rules.RuleClassifierProvider
+
+/**
+ * Provider for a classifier that determines whether two objects of [ListOfSetsOfHtmlStrings] differ by
+ * exactly ordering of one item in the list.
+ *
+ * https://github.com/oppia/oppia/blob/132b9d8f059253548ea1efadf1ff76416dfa2832/extensions/interactions/DragAndDropSortInput/directives/drag-and-drop-sort-input-rules.service.ts#L72
+ */
+internal class DragDropSortInputIsEqualToOrderingWithOneItemAtIncorrectPositionClassifierProvider @Inject constructor(
```
Comment (vinitamurthi) [inline domain/src/main/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemAtIncorrectPositionClassifierProvider.kt]: I think these lines are exceeding 100 characters (You can add a line limit at 100 characters on your Android Studio UI to verify and wrap the lines!)

**Review by vinitamurthi — APPROVED** [review]
Just a nit, otherwise LGTM (after addressing Ben's comments)

File: domain/src/main/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemAtIncorrectPositionClassifierProvider.kt (hunk 4 above)
Comment (aggarwalpulkit596) [reply domain/src/main/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemAtIncorrectPositionClassifierProvider.kt]: okay will do that but keeping 100 characters is a bit difficult with these long names

Comment (aggarwalpulkit596) [reply domain/src/main/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemAtIncorrectPositionClassifierProvider.kt]: @anandwana001 for this case I have to add a comment below and above this function right?

Comment (anandwana001) [reply domain/src/main/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemAtIncorrectPositionClassifierProvider.kt]: > @anandwana001 for this case I have to add a comment below and above this function right?

it's `/* ktlint-disable max-line-length */` above that line and `/* ktlint-enable max-line-length */` below the line. The line which is exceeding that grey line. This should be applied only where we don't have any possible chance to put things on new line.

File: domain/src/main/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemAtIncorrectPositionClassifierProvider.kt (hunk 1 above)
Comment (aggarwalpulkit596) [reply domain/src/main/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemAtIncorrectPositionClassifierProvider.kt]: done

File: domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemAtIncorrectPositionClassifierProviderTest.kt (hunk 3 above)
Comment (aggarwalpulkit596) [reply domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemAtIncorrectPositionClassifierProviderTest.kt]: done

File: domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemAtIncorrectPositionClassifierProviderTest.kt (hunk 2 above)
Comment (aggarwalpulkit596) [reply domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemAtIncorrectPositionClassifierProviderTest.kt]: done

File: domain/src/main/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProvider.kt [hunk 5]
```diff
@@ -31,11 +31,15 @@ internal class DragDropSortInputIsEqualToOrderingWithOneItemAtIncorrectPositionC
...
   }
 
-  private fun areSetsOfHtmlStringsEqual(first: StringList, second: StringList): Boolean {
-    return HashSet(first.htmlList) == HashSet(second.htmlList)
+  private fun unionOfSetsOfHtmlStrings(first: StringList, second: StringList): Set<String> {
+    return HashSet(first.htmlList) union HashSet(second.htmlList)
+  }
+
+  private fun intersectOfSetsOfHtmlStrings(first: StringList, second: StringList): Set<String> {
+    return HashSet(first.htmlList) intersect  HashSet(second.htmlList)
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProvider.kt]: Spacing is off here--please fix.

File: domain/src/main/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProvider.kt [hunk 6]
```diff
@@ -31,11 +31,15 @@ internal class DragDropSortInputIsEqualToOrderingWithOneItemAtIncorrectPositionC
     val answerStringSets = answer.setOfHtmlStringsList
     val inputStringSets = input.setOfHtmlStringsList
     return (answerStringSets zip inputStringSets).map { (first, second) ->
-      areSetsOfHtmlStringsEqual(first, second)
-    }.count { !it } == 1
+       (unionOfSetsOfHtmlStrings(first, second) subtract intersectOfSetsOfHtmlStrings(first, second)).size
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProvider.kt]: Suggest moving this operation to a helper since to provide some context on what the operation is doing.

File: domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTest.kt [hunk 7]
```diff
@@ -81,24 +84,50 @@ class DragDropSortInputIsEqualToOrderingWithOneItemAtIncorrectPositionClassifier
...
+      isEqualToOrderingWithOneItemIncorrectClassifier.matches(
+        answer = SET_LIST_ITEM_A_ITEM_2_ITEM_3,
+        inputs = inputs
+      )
+
+    assertThat(matches).isFalse()
+  }
+
+  @Test
+  fun testAnswer_testLisOfSetsOfHtmlString_differByTwoElement_bothValuesDoNot_failsCorrectly() {
```
Comment (BenHenning) [inline domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTest.kt]: ``differByTwoElements``

And what does ``doNot`` correspond to? Please make the method name more specific.

**Review by BenHenning — APPROVED** [review]
Thanks @aggarwalpulkit596! Just had some nits.

File: domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTest.kt (hunk 7 above)
Comment (aggarwalpulkit596) [reply domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTest.kt]: It has been to be doesNotMatches i missed it

File: domain/src/main/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProvider.kt [hunk 8]
```diff
@@ -0,0 +1,45 @@
...
+import org.oppia.domain.classify.rules.RuleClassifierProvider
+
+/**
+ * Provider for a classifier that determines whether two objects of [ListOfSetsOfHtmlStrings] differ by
+ * exactly ordering of one item in the list.
+ *
+ * https://github.com/oppia/oppia/blob/132b9d8f059253548ea1efadf1ff76416dfa2832/extensions/interactions/DragAndDropSortInput/directives/drag-and-drop-sort-input-rules.service.ts#L72
+ */
+internal class DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProvider @Inject constructor(
+  private val classifierFactory: GenericRuleClassifier.Factory
```
Comment (anandwana001) [inline domain/src/main/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProvider.kt:19]: Could you please run `reformat code` and `optimise imports` and ktlint commands to check if it is passing?
Ktlint details in [wiki](https://github.com/oppia/oppia-android/wiki/Ktlint-Guide)

File: domain/src/main/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputModule.kt [hunk 9]
```diff
@@ -33,5 +33,12 @@ class DragDropSortInputModule{
   internal fun provideDragDropSortInputHasElementXBeforeElementYRuleClassifier(
     classifierProvider: DragDropSortInputHasElementXBeforeElementYClassifierProvider
   ): RuleClassifier = classifierProvider.createRuleClassifier()
-}
 
+  @Provides
```
Comment (anandwana001) [inline domain/src/main/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputModule.kt:37]: Same here.

File: domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTest.kt [hunk 10]
```diff
@@ -0,0 +1,189 @@
...
+    val exception = assertThrows(IllegalStateException::class) {
+      isEqualToOrderingWithOneItemIncorrectClassifier.matches(
+        answer = SET_LIST_ITEMS_AB_ITEM_2_ITEM_3,
+        inputs = inputs
+      )
+    }
+
+    assertThat(exception)
+      .hasMessageThat()
+      .contains("Expected input value to be of type LIST_OF_SETS_OF_HTML_STRING not NON_NEGATIVE_INT")
```
Comment (anandwana001) [inline domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTest.kt]: Same here. ktlint issue - `Exceeded max line length (100)`

**Review by anandwana001 — CHANGES_REQUESTED** [review]

File: domain/src/main/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProvider.kt (hunk 5 above)
Comment (aggarwalpulkit596) [reply domain/src/main/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProvider.kt]: done

File: domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTest.kt (hunk 7 above)
Comment (aggarwalpulkit596) [reply domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTest.kt]: done

File: domain/src/main/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProvider.kt (hunk 8 above)
Comment (aggarwalpulkit596) [reply domain/src/main/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProvider.kt:19]: done

File: domain/src/main/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputModule.kt (hunk 9 above)
Comment (aggarwalpulkit596) [reply domain/src/main/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputModule.kt:37]: done

File: domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTest.kt (hunk 10 above)
Comment (aggarwalpulkit596) [reply domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTest.kt]: done

File: domain/src/main/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProvider.kt (hunk 6 above)
Comment (aggarwalpulkit596) [reply domain/src/main/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProvider.kt]: done

File: domain/src/main/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProvider.kt (hunk 8 above)
Comment (anandwana001) [reply domain/src/main/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProvider.kt:19]: perfect

File: domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTest.kt [hunk 11]
```diff
@@ -96,7 +98,9 @@ class DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTe
   }
 
   @Test
+    /* ktlint-disable max-line-length */
```
Comment (anandwana001) [inline domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTest.kt]: Here you can use a single line comment for disabling ktlint check of 100 char thing at the end of the line which you want to disable.
`// ktlint-disable max-line-length`
Check here [Ktlint wiki page](https://github.com/oppia/oppia-android/wiki/Ktlint-Guide)

Here current issue `Unexpected indentation (4) (should be 2)` but using one line comment solve this too.

File: domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTest.kt [hunk 12]
```diff
@@ -109,7 +113,7 @@ class DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTe
   }
 
   @Test
-  fun testAnswer_testLisOfSetsOfHtmlString_differByTwoElement_bothValuesDoNot_failsCorrectly() {
+  fun testAnswer_testLisOfSetsOfHtmlString_differByTwoElements_bothValuesDoNotMatch_failsCorrectly() {
```
Comment (anandwana001) [inline domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTest.kt]: 100 char issue

File: domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTest.kt [hunk 13]
```diff
@@ -154,8 +158,10 @@ class DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTe
   }
 
   private fun setUpTestApplicationComponent() {
+    /* ktlint-disable max-line-length */
```
Comment (anandwana001) [inline domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTest.kt]: Ditto. Try single line thing as mentioned in other comment.

**Review by anandwana001 — CHANGES_REQUESTED** [review]

File: domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTest.kt (hunk 13 above)
Comment (aggarwalpulkit596) [reply domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTest.kt]: okay thanks

File: domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTest.kt (hunk 12 above)
Comment (aggarwalpulkit596) [reply domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTest.kt]: done

File: domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTest.kt [hunk 14]
```diff
@@ -98,9 +98,7 @@ class DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTe
   }
 
   @Test
-    /* ktlint-disable max-line-length */
-  fun testAnswer_testLisOfSetsOfHtmlString_differByOneElement_differentOrder_bothValuesDoNotMatch_failsCorrectly() {
-    /* ktlint-enable max-line-length */
+  fun testAnswer_testLisOfSetsOfHtmlString_differByOneElement_differentOrder_bothValuesDoNotMatch_failsCorrectly() {  /* ktlint-disable max-line-length */
```
Comment (anandwana001) [inline domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTest.kt]: Ktlint does not take it as a one-line comment, it's like disabling starts from the line below it till where you mention about enable. Use `// ktlint-disable max-line-length` as mentioned earlier. Also not put extra space before the comment, only one space else the ktlint will fail. 
I suggest please go through the [wiki page](https://github.com/oppia/oppia-android/wiki/Ktlint-Guide) once.

File: domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTest.kt [hunk 15]
```diff
@@ -113,7 +111,7 @@ class DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTe
   }
 
   @Test
-  fun testAnswer_testLisOfSetsOfHtmlString_differByTwoElements_bothValuesDoNotMatch_failsCorrectly() {
+  fun testAnswer_testLisOfSetsOfHtmlString_differByTwoElements_bothValuesDoNotMatch_failsCorrectly() {  /* ktlint-disable max-line-length */
```
Comment (anandwana001) [inline domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTest.kt]: ditto

File: domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTest.kt [hunk 16]
```diff
@@ -158,10 +156,8 @@ class DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTe
   }
 
   private fun setUpTestApplicationComponent() {
-    /* ktlint-disable max-line-length */
-    DaggerDragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTest_TestApplicationComponent.builder()
+    DaggerDragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTest_TestApplicationComponent.builder() /* ktlint-disable max-line-length */
```
Comment (anandwana001) [inline domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTest.kt]: ditto

**Review by anandwana001 — CHANGES_REQUESTED** [review]

File: domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTest.kt (hunk 14 above)
Comment (aggarwalpulkit596) [reply domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTest.kt]: okay got it thanks for the clarification 👍

File: domain/src/main/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemAtIncorrectPositionClassifierProvider.kt (hunk 4 above)
Comment (anandwana001) [reply domain/src/main/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemAtIncorrectPositionClassifierProvider.kt]: We going for single line comment because in an earlier version of ktlint, single comment thing not supposed to work but as we are going for a specific version of ktlint, we are good to go to use single line comment thing.

File: domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTest.kt (hunk 14 above)
Comment (BenHenning) [reply domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTest.kt]: Shouldn't we be using a single-line comment here since we're just exempting a single line, not a block of code? (per the wiki recommendations)

File: domain/src/main/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProvider.kt [hunk 17]
```diff
@@ -31,15 +32,25 @@ internal class DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierP
     val answerStringSets = answer.setOfHtmlStringsList
     val inputStringSets = input.setOfHtmlStringsList
     return (answerStringSets zip inputStringSets).map { (first, second) ->
-       (unionOfSetsOfHtmlStrings(first, second) subtract intersectOfSetsOfHtmlStrings(first, second)).size
+      checkEqualityWithIncorrectPositions(first, second).size
     }.reduce(Int::plus) == 1
   }
 
+  private fun checkEqualityWithIncorrectPositions(
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProvider.kt]: This isn't really checking something, it's performing a symmetric difference operation. Suggest: ``computeSymmetricDifference``.

File: domain/src/main/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProvider.kt [hunk 18]
```diff
@@ -31,15 +32,25 @@ internal class DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierP
...
+    first: StringList,
+    second: StringList
+  ): Set<String> {
+    return (unionOfSetsOfHtmlStrings(first, second) subtract intersectOfSetsOfHtmlStrings(
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProvider.kt]: I suggest moving the union & intersection to separate variables to make the line wrapping a bit cleaner.

**Review by BenHenning — APPROVED** [review]
Thanks @aggarwalpulkit596! Just a few minor nits.

File: domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTest.kt (hunk 7 above)
Comment (BenHenning) [reply domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTest.kt]: Did you mean ``doNotMatch``?

Comment (aggarwalpulkit596) [reply domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTest.kt]: yes and I have updated it.

File: domain/src/main/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProvider.kt (hunk 18 above)
Comment (aggarwalpulkit596) [reply domain/src/main/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProvider.kt]: done

File: domain/src/main/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProvider.kt (hunk 17 above)
Comment (aggarwalpulkit596) [reply domain/src/main/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProvider.kt]: done

File: domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTest.kt (hunk 15 above)
Comment (aggarwalpulkit596) [reply domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTest.kt]: done

File: domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTest.kt [hunk 19]
```diff
@@ -0,0 +1,191 @@
...
+      isEqualToOrderingWithOneItemIncorrectClassifier.matches(
+        answer = SET_LIST_ITEM_A_ITEM_2_ITEM_3,
+        inputs = inputs
+      )
+
+    assertThat(matches).isTrue()
+  }
+
+  @Test
+  fun testAnswer_testLisOfSetsOfHtmlString_differByOneElement_differentOrder_bothValuesDoNotMatch_failsCorrectly() {/* ktlint-disable max-line-length */
```
Comment (anandwana001) [inline domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTest.kt]: Use single line comment else ktlint will fail.

File: domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTest.kt [hunk 20]
```diff
@@ -0,0 +1,191 @@
...
+  private fun createHtmlStringList(items: List<String>): StringList {
+    return StringList.newBuilder().addAllHtml(items).build()
+  }
+
+  private fun createNonNegativeInt(value: Int): InteractionObject {
+    return InteractionObject.newBuilder().setNonNegativeInt(value).build()
+  }
+
+  private fun setUpTestApplicationComponent() {
+    DaggerDragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTest_TestApplicationComponent.builder()/* ktlint-disable max-line-length */
```
Comment (anandwana001) [inline domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTest.kt]: here too, and other places in this file.

**Review by anandwana001 — CHANGES_REQUESTED** [review]

File: domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTest.kt (hunk 19 above)
Comment (aggarwalpulkit596) [reply domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTest.kt]: Oh really but it doesn't fail locally ? Can i test this thing locally as well

Comment (anandwana001) [reply domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTest.kt]: yes, you can check locally in terminal 
`ktlint --android "path/of/your/kotlin/file.kt"`

File: domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTest.kt (hunk 20 above)
Comment (aggarwalpulkit596) [reply domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTest.kt]: done

File: domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTest.kt (hunk 19 above)
Comment (aggarwalpulkit596) [reply domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTest.kt]: thanks

**Review by anandwana001 — APPROVED** [review]
LGTM

File: domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTest.kt (hunk 14 above)
Comment (anandwana001) [reply domain/src/test/java/org/oppia/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemIncorrectClassifierProviderTest.kt]: Seems it is done.
