### PR TITLE
[RunAllTests] Fix part of #2787: Add support for proto lesson loading from local assets

### LINKED ISSUE #2787: Update app to support newest lesson structures
The app needs to be updated to support the latest exploration structures, and re-tested to ensure it properly supports:
- Place values
- Multiplication
- Fractions
- Ratios

### PR DESCRIPTION
**Pull request by BenHenning**
Fix part of #2787

This adds initial support for loading the new lessons needed for alpha. In particular, to better prepare the codebase for post-alpha beta work, this PR is introducing support for directly loading proto assets rather than JSON (bypassing the entire JSON loading pipeline). This requires punching a few holes into various retrievers/controllers (gated by a new qualified boolean: LoadLessonProtosFromAssets) to load proto rather than JSON. The resulting proto code is a bit simpler than the JSON versions since typing becomes much simpler.

In order to ensure the new pathways are (mostly) working in tests, this PR enables proto caching in some tests. However doing this isn't straightforward: we don't want to check actual binary proto files into the codebase since they are binary files and will  unnecessarily bloat our repository. Textproto is a more reasonable alternative since it's plaintext (and actually a bit more compact than JSON), but complicated to use: proto lite does not support loading via TextFormat. Rather than introducing a dependency on JsonFormat (to avoid JSON altogether), I decided instead to introduce a custom Starlark rule in Bazel to, at build time, convert textproto files to binary files & include those at build time. This works quite well: for both the apk itself & tests we can load binary pb files as though we're including them directly. Also, for this reason is why the PR includes textproto conversions of our development assets.

However, the above approach only works for Bazel. To mitigate this, the few test suites that were updated to verify the fixes conditionally enable proto loading based on whether the environment is Bazel. This is a bit hacky, but it seems like the best solution in the interim until we can entirely move off of Gradle per #59.

Other considerations for this PR:
- This removes dependence on test story 1 entirely because it includes structural elements that are incompatible with the pipeline used to convert to text/binary proto. This seems fine since we don't actually need these interactions for testing or development.
- This removes support for confirmed unclassified answers since they aren't used at all, and probably won't be in Android.
- This PR does not introduce support for the up-to-date interactions that will be shipped with the alpha. That will happen in a later PR (mainly #2985).
- The textproto files introduced in this PR were generated using an in-progress script that's also being used to download the assets that will be used for alpha. Follow up with me if you want to see the script.
- Enabling proto caching & running the APK locally will yield to images not loading. This is partly due to #2979 (in that they can't load without that fix), but mostly due to the fact that all of our dev assets short-circuit thumbnails (which is why we never discovered #2940 until working on alpha)

### CODE REVIEW

File: domain/src/main/java/org/oppia/android/domain/topic/TopicController.kt [hunk 1]
```diff
@@ -396,12 +426,25 @@ class TopicController @Inject constructor(
...
-      .setDiskSizeBytes(computeTopicSizeBytes(getAssetFileNameList(topicId)))
+      .setDiskSizeBytes(computeTopicSizeBytes(getJsonAssetFileNameList(topicId)).toLong())
       .addAllSubtopic(subtopicList)
       .setTopicPlayAvailability(topicPlayAvailability)
       .build()
   }
 
+  private fun loadSubtopic(topicId: String, subtopicId: Int): Subtopic {
+    val subtopicRecord = assetRepository.loadProtoFromLocalAssets(
+      assetName = "${topicId}_$subtopicId",
```
Comment (vinitamurthi) [inline domain/src/main/java/org/oppia/android/domain/topic/TopicController.kt:437]: I'm wondering if there's a better way to sent this request rather than the assetname which is a slightly vague variable name since it looks like it's picking up assets for different ids. Maybe asset type (as an enum), asset Id (which is called asset name here) , and base message?

File: domain/src/main/java/org/oppia/android/domain/topic/TopicListController.kt [hunk 2]
```diff
@@ -123,6 +130,23 @@ class TopicListController @Inject constructor(
   }
 
   private fun createTopicList(): TopicList {
+    return if (loadLessonProtosFromAssets) {
+      val topicIdList =
+        assetRepository.loadProtoFromLocalAssets(
+          assetName = "topics",
```
Comment (vinitamurthi) [inline domain/src/main/java/org/oppia/android/domain/topic/TopicListController.kt:135]: Here this kind of breaks the paradigm for assetName compared to the fields that are being used above, so I think it may be better to keep assetType, assetId, and baseMessage

**Review by vinitamurthi — CHANGES_REQUESTED** [review]

File: domain/src/main/java/org/oppia/android/domain/topic/TopicController.kt (hunk 1 above)
Comment (BenHenning) [reply domain/src/main/java/org/oppia/android/domain/topic/TopicController.kt:437]: Not sure I follow--what advantage does an enum give us here? The main typing mechanism is the base message type, and introducing an enum may require us to keep the types & enum in-sync which will add complexity.

File: domain/src/main/java/org/oppia/android/domain/topic/TopicListController.kt (hunk 2 above)
Comment (BenHenning) [reply domain/src/main/java/org/oppia/android/domain/topic/TopicListController.kt:135]: It's not a type though, it's the actual file name checked into the APK. Calling it 'assetType' would be misleading. Perhaps 'assetBaseFIilename' would be the most clear, but it's a bit lengthy. I also don't understand how you're distinguishing between 'type' and 'ID'. This is the topic list so it doesn't have an ID.

It could be named better but I'm following existing filenames to keep things a bit simpler. We'll be removing all of this code in coming months, anyway, in favor of downloading & caching completely dynamically.

**Comment by BenHenning** [comment]
NB: I will change this & downstream PRs to use '[RunAllTests]' to force test runs since these PRs appear to have issues triggering the 'compute affected tests' flow (probably because of changing BUILD files--that sometimes causes the script to hang and I haven't yet figured out why).

**Comment by BenHenning** [comment]
Thanks @vinitamurthi. FYI that this is ready for full review--PTAL.

@anandwana001 & @rt4914 PTAL as codeowners.

**Review by rt4914 — APPROVED** [review]
LGTM for code-owner files.

File: domain/src/main/java/org/oppia/android/domain/topic/TopicController.kt (hunk 1 above)
Comment (vinitamurthi) [reply domain/src/main/java/org/oppia/android/domain/topic/TopicController.kt:437]: My suggestion was because we are setting the asset name to be of a different format based on the asset types (i.e. subtopics have a different format of asset name (being topicId_subtopicID) , where as other assets have a different format for their asset names. But it looks like this is because of the way the file names are created, and given that this code may be unnecessary in a few months I guess its okay.

File: domain/src/main/java/org/oppia/android/domain/topic/TopicListController.kt (hunk 2 above)
Comment (vinitamurthi) [reply domain/src/main/java/org/oppia/android/domain/topic/TopicListController.kt:135]: Same comment as above..given that this code will be dead soon I think its okay

**Review by vinitamurthi — APPROVED** [review]

File: domain/domain_assets.bzl [hunk 3]
```diff
@@ -0,0 +1,213 @@
+"""
+Macros for preparing & creating assets to include in the domain module.
+"""
+
+load("@rules_proto//proto:defs.bzl", "ProtoInfo")
+
+def _extract_proto_sources(deps):
+    """
+    Returns the list of proto source files that make up the specified list of proto dependencies.
```
Comment (anandwana001) [inline domain/domain_assets.bzl:9]: we can use the `#` for comments, nit fix, not blocking

**Review by anandwana001 — APPROVED** [review]
LGTM, nit change but can be ignored

File: domain/domain_assets.bzl (hunk 3 above)
Comment (BenHenning) [reply domain/domain_assets.bzl:9]: @anandwana001 I don't think we should be. See https://skydoc.bazel.build/docs/writing.html for examples on writing Skydocs. They use multi-line strings, not ``#``. I think we should be treating ``#`` as line comments and ``"""`` as documentation (which also matches Oppia web).

I did notice I'm not formatting on the correct line, but we can fix that in a later PR by making all documentation consistent.

**Comment by BenHenning** [comment]
ClassroomService Bazel failure will be fixed by #2916.

File: domain/src/main/java/org/oppia/android/domain/topic/TopicController.kt (hunk 1 above)
Comment (BenHenning) [reply domain/src/main/java/org/oppia/android/domain/topic/TopicController.kt:437]: Yeah--I don't think we should over-index on this since the long-term solution should utilize more of a database-type structure for managing files. Thanks for bringing this up, though!

File: domain/src/main/java/org/oppia/android/domain/topic/TopicListController.kt (hunk 2 above)
Comment (BenHenning) [reply domain/src/main/java/org/oppia/android/domain/topic/TopicListController.kt:135]: Ack, thanks.

**Comment by BenHenning** [comment]
Thanks all for the review! Merging this now to keep the PR chain moving forward.
