### PR TITLE
Fix part of #28,#29,#33: Hi-fi input interaction views

### LINKED ISSUE #28: Full UI: TextInputInteractionView [Blocked: #15, #150]
This is tracking implementing the fully polished UI version of the text input interaction.

See the web frontend for details on how the text input interaction works. This is the first interaction that will be implemented, so it includes designing the general interaction architecture that will be leveraged by other interactions.

Mock: https://xd.adobe.com/spec/e2239cf4-9cde-4c08-5296-25316c1f0a14-9412/screen/40d6cf5f-f673-42c8-af15-035f711ef6b9/PM-IN-Introduction-

## Checklist
- [ ] TextInput
Screenshot 2019-11-08 at 3 50 56 PM

- [ ] Final touch up with padding, margin, animations and Accessibility Scanner test

### PR DESCRIPTION
**Pull request by nikitamarysolomanpvt**
## Explanation

Mock: https://xd.adobe.com/spec/e2239cf4-9cde-4c08-5296-25316c1f0a14-9412/screen/40d6cf5f-f673-42c8-af15-035f711ef6b9/PM-IN-Introduction-

## Checklist
- [x] TextInput (similar to the mock)

- [x] Final touch up with padding, margin and Accessibility Scanner test

- [x] Numeric Text Input (similar to the mock)

- [x] Final touch up with padding, margin and Accessibility Scanner test

- [x] FractionInput (similar to the mock)

- [x] Final touch up with padding, margin and Accessibility Scanner test

## Reference Mocks
https://xd.adobe.com/spec/e2239cf4-9cde-4c08-5296-25316c1f0a14-9412/screen/4d4e4bd8-3755-41fc-bf83-3dcff5d5eee1/Lesson-1-a-ii-Exploration-Player-Text-Input-No-Ans
https://xd.adobe.com/spec/e2239cf4-9cde-4c08-5296-25316c1f0a14-9412/screen/eeed0f6c-54ca-4371-ab23-5199abd87f28/Lesson-1-a-ii-Exploration-Player-Text-Input-Keyboa
https://xd.adobe.com/spec/e2239cf4-9cde-4c08-5296-25316c1f0a14-9412/screen/d66097bf-8421-41d8-bfda-2450d6e98dea/Lesson-1-a-i-Exploration-Player-Fraction-Input-No-
https://xd.adobe.com/spec/e2239cf4-9cde-4c08-5296-25316c1f0a14-9412/screen/249c3349-605b-4569-bbe9-1a017ab90101/Lesson-1-a-i-Exploration-Player-Fraction-Input-No-
https://xd.adobe.com/spec/e2239cf4-9cde-4c08-5296-25316c1f0a14-9412/screen/c4b0dfb3-53b4-491e-a759-818e096183fd/Lesson-1-a-v-Exploration-Player-Numeric-Input-No-A

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by nikitamarysolomanpvt** [comment]
@mschanteltc 
1.Please suggest on focus of edit text iam I supposed to clear hint(place holder text) ?
on Accessibility Scanner test it is giving suggestions as no label found.

`Item label
org.oppia.app:id/fraction_input_interaction_view
This item may not have a label readable by screen readers.
`
screenshot_Oppia_2019-11-11-22_45_09

2.The color of hint/text is not matching required contrast ratio.
Text contrast
`
org.oppia.app:id/fraction_input_interaction_view
The item's text contrast ratio is 1.61. This ratio is based on an estimated foreground color of #CCCCCC and an estimated background color of #FFFFFF. Consider increasing this item's text contrast ratio to 3.00 or greater.
`
screenshot_Oppia_2019-11-11-22_11_35

@mschanteltc 
3.Text contrast
org.oppia.app:id/fraction_input_interaction_view
The item's text contrast ratio is 1.80. This ratio is based on an estimated foreground color of #ABC2EC and an estimated background color of #FFFFFF. Consider increasing this item's text contrast ratio to 3.00 or greater.

screenshot_Oppia_2019-11-12-10_09_21

**Comment by mschanteltc** [comment]
Hi Nikita,

1. Although there are some drawbacks of removing the placeholder text, it should still disappear from the text input because it is more commonplace than keeping it there. If the input is still empty and the user taps out of the text field, then the placeholder text should reappear.  

2. Because it is placeholder text, we can assume that this is not "normal" text and that it does not adhere to the [WCAG 2.0 guidelines](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html).

**Comment by nikitamarysolomanpvt** [comment]
> Hi Nikita,
> 
> 1. Although there are some drawbacks of removing the placeholder text, it should still disappear from the text input because it is more commonplace than keeping it there. If the input is still empty and the user taps out of the text field, then the placeholder text should reappear.
> 2. Because it is placeholder text, we can assume that this is not "normal" text and that it does not adhere to the [WCAG 2.0 guidelines](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html).

Ok thank you. please reply on the below and also review this PR.

3.Text contrast
org.oppia.app:id/fraction_input_interaction_view
The item's text contrast ratio is 1.80. This ratio is based on an estimated foreground color of #ABC2EC and an estimated background color of #FFFFFF. Consider increasing this item's text contrast ratio to 3.00 or greater.

screenshot_Oppia_2019-11-12-10_09_21
4. Please suggest if you want any changes in the padding , margin or any other specifications.

**Comment by veena14cs** [comment]
Please update your code with latest develop.

File: app/src/main/java/org/oppia/app/customview/interaction/FractionInputInteractionView.kt [hunk 1]
```diff
@@ -16,4 +18,19 @@ class FractionInputInteractionView @JvmOverloads constructor(
   context: Context,
   attrs: AttributeSet? = null,
   defStyle: Int = android.R.attr.editTextStyle
-) : EditText(context, attrs, defStyle)
+) : EditText(context, attrs, defStyle), View.OnFocusChangeListener {
+  val hintText: String
```
Comment (veena14cs) [inline app/src/main/java/org/oppia/app/customview/interaction/FractionInputInteractionView.kt]: You can make this as private.

File: app/src/main/java/org/oppia/app/customview/interaction/NumericInputInteractionView.kt [hunk 2]
```diff
@@ -16,4 +18,19 @@ class NumericInputInteractionView @JvmOverloads constructor(
   context: Context,
   attrs: AttributeSet? = null,
   defStyle: Int = android.R.attr.editTextStyle
-) : EditText(context, attrs, defStyle)
+) : EditText(context, attrs, defStyle), View.OnFocusChangeListener {
+  val hintText: String
```
Comment (veena14cs) [inline app/src/main/java/org/oppia/app/customview/interaction/NumericInputInteractionView.kt]: Ditto here.

File: app/src/main/java/org/oppia/app/customview/interaction/TextInputInteractionView.kt [hunk 3]
```diff
@@ -15,4 +17,19 @@ class TextInputInteractionView @JvmOverloads constructor(
   context: Context,
   attrs: AttributeSet? = null,
   defStyle: Int = android.R.attr.editTextStyle
-) : EditText(context, attrs, defStyle)
+) : EditText(context, attrs, defStyle), View.OnFocusChangeListener {
+  val hintText: String
```
Comment (veena14cs) [inline app/src/main/java/org/oppia/app/customview/interaction/TextInputInteractionView.kt]: ditto here

File: app/src/main/res/drawable/edit_text_background_shadow.xml [hunk 4]
```diff
@@ -2,7 +2,18 @@
 <layer-list xmlns:android="http://schemas.android.com/apk/res/android">
   <item>
     <shape>
-      <corners android:radius="5dp"></corners>
+      <corners android:radius="10dp"></corners>
```
Comment (veena14cs) [inline app/src/main/res/drawable/edit_text_background_shadow.xml]: You could close `<corner ... />` tags instead of having empty body.

File: app/src/main/res/layout/fraction_interaction_item.xml [hunk 5]
```diff
@@ -35,10 +34,16 @@
         android:hint="@string/fractions_hint_text"
         android:inputType="text"
         android:longClickable="false"
+        android:textSize="16sp"
         android:maxLength="200"
-        android:padding="8dp"
+        android:minHeight="48dp"
+        android:paddingStart="16dp"
+        android:paddingLeft="16dp"
```
Comment (veena14cs) [inline app/src/main/res/layout/fraction_interaction_item.xml]: You haven't defined end padding over here.

File: app/src/main/res/layout/numeric_input_interaction_item.xml [hunk 6]
```diff
@@ -23,14 +22,19 @@
...
+      android:enabled="@{!viewModel.isReadOnly}"
       android:focusable="true"
       android:hint="@string/number_input_hint_text"
       android:inputType="numberDecimal"
       android:longClickable="false"
       android:maxLength="200"
-      android:padding="8dp"
+      android:minHeight="48dp"
+      android:paddingStart="16dp"
+      android:paddingLeft="16dp"
```
Comment (veena14cs) [inline app/src/main/res/layout/numeric_input_interaction_item.xml]: Define end padding too.

File: app/src/main/res/layout/numeric_input_interaction_item.xml [hunk 7]
```diff
@@ -23,14 +22,19 @@
...
+      android:paddingBottom="8dp"
       android:singleLine="true"
       android:text="@={viewModel.answerText}"
-      android:enabled="@{!viewModel.isReadOnly}" />
+      android:textColorHint="@color/edit_text_hint"
+      android:textStyle="italic" />
```
Comment (veena14cs) [inline app/src/main/res/layout/numeric_input_interaction_item.xml:42]: Please define font family to this view.

File: app/src/main/res/layout/text_input_interaction_item.xml [hunk 8]
```diff
@@ -12,24 +12,28 @@
...
+      android:enabled="@{!viewModel.isReadOnly}"
       android:focusable="true"
       android:hint="@string/text_input_hint_text"
       android:inputType="text"
       android:longClickable="false"
       android:maxLength="200"
-      android:padding="8dp"
+      android:minHeight="48dp"
+      android:paddingStart="16dp"
+      android:paddingLeft="16dp"
```
Comment (veena14cs) [inline app/src/main/res/layout/text_input_interaction_item.xml]: Define end padding.

File: app/src/main/res/layout/text_input_interaction_item.xml [hunk 9]
```diff
@@ -12,24 +12,28 @@
...
+      android:paddingBottom="8dp"
       android:singleLine="true"
       android:text="@={viewModel.answerText}"
-      android:enabled="@{!viewModel.isReadOnly}" />
+      android:textColorHint="@color/edit_text_hint"
+      android:textStyle="italic" />
```
Comment (veena14cs) [inline app/src/main/res/layout/text_input_interaction_item.xml:41]: Please give font size and fontfamily here and wherever it is missing.

**Review by veena14cs — CHANGES_REQUESTED** [review]
Please do the changes and assign me back.

File: app/src/main/java/org/oppia/app/customview/interaction/FractionInputInteractionView.kt (hunk 1 above)
Comment (nikitamarysolomanpvt) [reply app/src/main/java/org/oppia/app/customview/interaction/FractionInputInteractionView.kt]: Done

File: app/src/main/res/layout/fraction_interaction_item.xml (hunk 5 above)
Comment (nikitamarysolomanpvt) [reply app/src/main/res/layout/fraction_interaction_item.xml]: done

File: app/src/main/res/layout/numeric_input_interaction_item.xml (hunk 6 above)
Comment (nikitamarysolomanpvt) [reply app/src/main/res/layout/numeric_input_interaction_item.xml]: Done

File: app/src/main/res/layout/numeric_input_interaction_item.xml (hunk 7 above)
Comment (nikitamarysolomanpvt) [reply app/src/main/res/layout/numeric_input_interaction_item.xml:42]: Done

File: app/src/main/res/layout/text_input_interaction_item.xml (hunk 8 above)
Comment (nikitamarysolomanpvt) [reply app/src/main/res/layout/text_input_interaction_item.xml]: Done

File: app/src/main/res/layout/text_input_interaction_item.xml (hunk 9 above)
Comment (nikitamarysolomanpvt) [reply app/src/main/res/layout/text_input_interaction_item.xml:41]: Done

File: app/src/main/java/org/oppia/app/customview/interaction/NumericInputInteractionView.kt (hunk 2 above)
Comment (nikitamarysolomanpvt) [reply app/src/main/java/org/oppia/app/customview/interaction/NumericInputInteractionView.kt]: Done

File: app/src/main/java/org/oppia/app/customview/interaction/TextInputInteractionView.kt (hunk 3 above)
Comment (nikitamarysolomanpvt) [reply app/src/main/java/org/oppia/app/customview/interaction/TextInputInteractionView.kt]: Done

File: app/src/main/res/drawable/edit_text_background_shadow.xml (hunk 4 above)
Comment (nikitamarysolomanpvt) [reply app/src/main/res/drawable/edit_text_background_shadow.xml]: Done

File: app/src/main/res/layout/fraction_interaction_item.xml (hunk 5 above)
Comment (nikitamarysolomanpvt) [reply app/src/main/res/layout/fraction_interaction_item.xml]: Done

**Comment by mschanteltc** [comment]
> > Hi Nikita,
> > 
> > 1. Although there are some drawbacks of removing the placeholder text, it should still disappear from the text input because it is more commonplace than keeping it there. If the input is still empty and the user taps out of the text field, then the placeholder text should reappear.
> > 2. Because it is placeholder text, we can assume that this is not "normal" text and that it does not adhere to the [WCAG 2.0 guidelines](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html).
> 
> Ok thank you. please reply on the below and also review this PR.
> 
> 3.Text contrast
> org.oppia.app:id/fraction_input_interaction_view
> The item's text contrast ratio is 1.80. This ratio is based on an estimated foreground color of #ABC2EC and an estimated background color of #FFFFFF. Consider increasing this item's text contrast ratio to 3.00 or greater.
> 
> screenshot_Oppia_2019-11-12-10_09_21
> 4. Please suggest if you want any changes in the padding , margin or any other specifications.

In regards to the text input, the input box itself should have a border with hex value #395FD0 and opacity 100%. 

The text "1/2" should be #666666 at 100% opacity against a #FFFFFF background, so the contrast ratio should pass the accessibility checker. 

Theme colors have been changed from to #019489 to #00645C so most objects are able to pass the accessibility checker.

For the back button, this design may need further discussing. We have had the arrow by itself, without a box. Making the arrow white with a background color provides it as much significance as a "Submit" button, but should not be used frequently. It seems that there will be drawbacks regardless of the design we choose, but for now, let's stick with the current one that we have. I believe adding shadow elevates the back button to make it stand out to the user.

**Comment by nikitamarysolomanpvt** [comment]
Seems there are some changes in the focus of the input view ,noticed after merging with develop(expected as the change in lowfi explorations functionality).So the issue of requesting focus and showing keyboard is not handled in this PR. For this a new branch hi-fi-input-interaction-views-issue-fix is created.Need to discuss about the same with Ben.

**Review by rt4914 — CHANGES_REQUESTED** [review]
The cursor color in edittext is not correct: it should be `#2D4A9D` and currently it is pink.

**Comment by rt4914** [comment]
@nikitamarysolomanpvt Suggestions: Change background of the StateFragment to `#E0F2F1` to fix the contrast issue.

File: app/src/main/res/layout/fraction_interaction_item.xml [hunk 10]
```diff
@@ -17,9 +17,8 @@
       android:layout_width="match_parent"
       android:layout_height="wrap_content"
       android:layout_margin="8dp"
-      android:background="@color/white"
+      android:background="@color/oppiaLightGreen"
```
Comment (veena14cs) [inline app/src/main/res/layout/fraction_interaction_item.xml:20]: Please add input type.

File: app/src/main/res/layout/fraction_interaction_item.xml [hunk 11]
```diff
@@ -32,13 +31,20 @@
...
         android:enabled="@{!viewModel.isReadOnly}"
         android:focusable="true"
+        android:fontFamily="sans-serif"
         android:hint="@string/fractions_hint_text"
         android:inputType="text"
         android:longClickable="false"
         android:maxLength="200"
-        android:padding="8dp"
+        android:minHeight="48dp"
+        android:paddingLeft="16dp"
```
Comment (veena14cs) [inline app/src/main/res/layout/fraction_interaction_item.xml]: I suggest adding paddingStart and paddingEnd to support RTL

**Review by veena14cs — CHANGES_REQUESTED** [review]
Please do the changes and assign.

**Comment by nikitamarysolomanpvt** [comment]
> @nikitamarysolomanpvt Suggestions: Change background of the StateFragment to `#E0F2F1` to fix the contrast issue.

 Found this is not the reason of the suggestion in Accessibility Scanner test.

**Comment by nikitamarysolomanpvt** [comment]
> The cursor color in edittext is not correct: it should be `#2D4A9D` and currently it is pink.

Done

File: app/src/main/res/layout/fraction_interaction_item.xml (hunk 11 above)
Comment (nikitamarysolomanpvt) [reply app/src/main/res/layout/fraction_interaction_item.xml]: Done

File: app/src/main/res/layout/fraction_interaction_item.xml (hunk 10 above)
Comment (nikitamarysolomanpvt) [reply app/src/main/res/layout/fraction_interaction_item.xml:20]: Done

Comment (nikitamarysolomanpvt) [reply app/src/main/res/layout/fraction_interaction_item.xml:20]: Done

**Comment by nikitamarysolomanpvt** [comment]
> > > Hi Nikita,
> > > 
> > > 1. Although there are some drawbacks of removing the placeholder text, it should still disappear from the text input because it is more commonplace than keeping it there. If the input is still empty and the user taps out of the text field, then the placeholder text should reappear.
> > > 2. Because it is placeholder text, we can assume that this is not "normal" text and that it does not adhere to the [WCAG 2.0 guidelines](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html).
> > 
> > 
> > Ok thank you. please reply on the below and also review this PR.
> > 3.Text contrast
> > org.oppia.app:id/fraction_input_interaction_view
> > The item's text contrast ratio is 1.80. This ratio is based on an estimated foreground color of #ABC2EC and an estimated background color of #FFFFFF. Consider increasing this item's text contrast ratio to 3.00 or greater.
> > screenshot_Oppia_2019-11-12-10_09_21
> > 4. Please suggest if you want any changes in the padding , margin or any other specifications.
> 
> In regards to the text input, the input box itself should have a border with hex value #395FD0 and opacity 100%.
> 
> The text "1/2" should be #666666 at 100% opacity against a #FFFFFF background, so the contrast ratio should pass the accessibility checker.
> 
> Theme colors have been changed from to #019489 to #00645C so most objects are able to pass the accessibility checker.
> 
> For the back button, this design may need further discussing. We have had the arrow by itself, without a box. Making the arrow white with a background color provides it as much significance as a "Submit" button, but should not be used frequently. It seems that there will be drawbacks regardless of the design we choose, but for now, let's stick with the current one that we have. I believe adding shadow elevates the back button to make it stand out to the user.

Thank you. This PR is only for input views.

**Review by rt4914 — APPROVED** [review]
LGTM and nice work with Date input type.

File: app/src/main/res/layout/fraction_interaction_item.xml [hunk 12]
```diff
@@ -32,14 +31,22 @@
         android:digits="0123456789/- "
         android:enabled="@{!viewModel.isReadOnly}"
         android:focusable="true"
+        android:fontFamily="sans-serif"
         android:hint="@string/fractions_hint_text"
-        android:inputType="text"
-        android:longClickable="false"
         android:imeOptions="actionDone"
+        android:inputType="date"
```
Comment (veena14cs) [inline app/src/main/res/layout/fraction_interaction_item.xml:37]: One problem with this date input type. It allows user to add `-` and if this is submitted it will crash.

**Review by veena14cs — CHANGES_REQUESTED** [review]
Please resolve one comment and assign it back to me.

File: app/src/main/res/layout/fraction_interaction_item.xml (hunk 12 above)
Comment (nikitamarysolomanpvt) [reply app/src/main/res/layout/fraction_interaction_item.xml:37]: Fraction can be negative. If its is getting crashed need to find the issue in parsing which is updated by ben.

Comment (veena14cs) [reply app/src/main/res/layout/fraction_interaction_item.xml:37]: Okay just make a note of it, that we need to resolve this. Beside this looks good to me.

**Comment by nikitamarysolomanpvt** [comment]
> Please resolve one comment and assign it back to me.

OK

**Review by veena14cs — APPROVED** [review]
