### PR TITLE
Fix part of #1868: Fix few Topic Tests and Migrate to ViewPager2

### LINKED ISSUE #2149: [RTL] Highfi Topic tabs & toolbar
`Topic-Tabs and Toolbar` needs RTL support as shown in below screen.
TP (Practice, Unchecked)

NOTE: Just focus on tabs and toolbar and not the content below.

Make sure that this works correctly in mobile (landscape + portrait) and tablet (landscape + portrait).

## References
Mobile Portrait: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/grid/
Mobile Landscape: https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/grid/
Tablet: https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/grid/
Wiki: https://github.com/oppia/oppia-android/wiki/Working-on-UI

### LINKED ISSUE #2194: Onboarding Fragment needs to be updated to ViewPager2
In `OnboardingFragment` we are currently using `ViewPager` because of which it does not support RTL automatically, instead we should use `ViewPager2` and make it RTL compatible.

### PR DESCRIPTION
**Pull request by anandwana001**
## Explanation

Fix part of #1868 - `TopicPracticeFragmentTest`

Fix part of #632 - Converting `ChapterSummaryAdapter` to use generic adapter

Fix #2149 RTL Support to ViewPager

Fix #2194 Migrating to ViewPager2 

Fix test cases from `TopicFragmentTest`
Fix few test cases from `TopicInfoFragmentTest`
Fix test cases from `TopicLessonsFragmentTest`
Fix test cases from `TopicRevisionFragmentTest`

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by anandwana001** [comment]
Causing a bug in app:
1. Open app
2. Open any card (Fraction)
3. Expand the list
4. No item is visible
5. Re creating the activity will display the list of chapters

This is because of DataBinding. Fixed using `executePendingBindings()`, after items of Story list binds.

**Review by rt4914 — APPROVED** [review]
LGTM. Let's not merge this and wait for Ben as this was suggested by Ben.

**Comment by BenHenning** [comment]
Will need to take a look at this tomorrow. Sorry for the delay.

**Comment by BenHenning** [comment]
@anandwana001 Is there any other issue with this other than the explicit binding requirement? I'm wondering if we move the chapter list recycler view over to using our own data-binding recycler view adapter if that would avoid the need for explicitly calling ``executePendingBindings``.

Also, does this fix the underlying tests? I wasn't sure if ViewPager2 would work, it was an idea after looking at semi-related issues that people ran into with the standard ViewPager.

**Comment by anandwana001** [comment]
> @anandwana001 Is there any other issue with this other than the explicit binding requirement? I'm wondering if we move the chapter list recycler view over to using our own data-binding recycler view adapter if that would avoid the need for explicitly calling `executePendingBindings`.
> 
> Also, does this fix the underlying tests? I wasn't sure if ViewPager2 would work, it was an idea after looking at semi-related issues that people ran into with the standard ViewPager.

For the tests, yes it does fix a lot of test cases after migrating to ViewPager2

**Comment by anandwana001** [comment]
> @anandwana001 Is there any other issue with this other than the explicit binding requirement? I'm wondering if we move the chapter list recycler view over to using our own data-binding recycler view adapter if that would avoid the need for explicitly calling `executePendingBindings`.
> 
> Also, does this fix the underlying tests? I wasn't sure if ViewPager2 would work, it was an idea after looking at semi-related issues that people ran into with the standard ViewPager.

@BenHenning We cannot use `BindableAdapter` here as we need to access every position to show the chapter number. 
[`binding.index = position`](https://github.com/oppia/oppia-android/blob/develop/app/src/main/java/org/oppia/android/app/topic/lessons/ChapterSummaryAdapter.kt#L42)

**Comment by BenHenning** [comment]
I'm not sure I followed @anandwana001. Can't we bind the chapter number as part of the model so that we can display it?

**Comment by anandwana001** [comment]
> I'm not sure I followed @anandwana001. Can't we bind the chapter number as part of the model so that we can display it?

@BenHenning Let me check if we can get this [index](https://github.com/oppia/oppia-android/blob/develop/app/src/main/res/layout/lessons_chapter_view.xml#L11) from another route so that we can go for `BindableAdapter`

**Comment by BenHenning** [comment]
Thanks @anandwana001. In that case, unassigning for now until this is resolved.

**Comment by anandwana001** [comment]
> Thanks @anandwana001. In that case, unassigning for now until this is resolved.

@BenHenning  it's resolved now. You can review, I had used the BindableAdapter for chapter.

File: app/src/main/java/org/oppia/android/app/topic/TopicFragmentPresenter.kt [hunk 1]
```diff
@@ -52,7 +54,7 @@ class TopicFragmentPresenter @Inject constructor(
     )
     binding.lifecycleOwner = fragment
     this.storyId = storyId
-    viewPager = binding.root.findViewById(R.id.topic_tabs_viewpager) as ViewPager
+    viewPager2 = binding.root.findViewById(R.id.topic_tabs_viewpager) as ViewPager2
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/topic/TopicFragmentPresenter.kt]: Can we just keep the variable as 'viewPager'? The type is confusing as '2', but the variable makes it seem like there are two view pagers.

File: app/src/main/java/org/oppia/android/app/topic/TopicFragmentPresenter.kt [hunk 2]
```diff
@@ -70,24 +72,39 @@ class TopicFragmentPresenter @Inject constructor(
...
-    tabLayout.getTabAt(1)!!.setText(fragment.getString(R.string.lessons)).setIcon(tabIcons[1])
-    tabLayout.getTabAt(2)!!.setText(fragment.getString(R.string.practice)).setIcon(tabIcons[2])
-    tabLayout.getTabAt(3)!!.setText(fragment.getString(R.string.revision)).setIcon(tabIcons[3])
+      ViewPagerAdapter(fragment, internalProfileId, topicId, storyId)
+    viewPager2.adapter = adapter
+    TabLayoutMediator(tabLayout, viewPager2) { tab, position ->
+      when (position) {
+        0 -> {
+          tab.text = fragment.getString(R.string.info)
+          tab.icon = ContextCompat.getDrawable(fragment.context!!, tabIcons[0])
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/topic/TopicFragmentPresenter.kt]: Here & below: you can just use the activity as the context instead of ``fragment.context!!``

File: app/src/main/java/org/oppia/android/app/topic/lessons/StorySummaryAdapter.kt [hunk 3]
```diff
@@ -148,5 +148,30 @@ class StorySummaryAdapter(
...
+            ).root
+          },
+          bindView = { view, chapterSummary ->
+            val binding = DataBindingUtil.findBinding<LessonsChapterViewBinding>(view)!!
+            binding.chapterSummary = chapterSummary
+            binding.index = chapterList.indexOf(chapterSummary)
+            binding.chapterContainer.setOnClickListener {
+              chapterSummarySelector.selectChapterSummary(storyId, chapterSummary)
+            }
+          }
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/topic/lessons/StorySummaryAdapter.kt]: Prefer creating a view model class (non-injectable, non-Android view model) that contains the summary, index, and a bound listener callback for chapter selection. Then, you can use that view model as the type instead of ChapterSummary & bind everything through data-binding. That also trivializes bindView & the registration since you can use the databinding inflate/bind functions, instead, such as we do here:

https://github.com/oppia/oppia-android/blob/74db288b9ac25fb942a8feb35e918bcd7e94e55c/app/src/main/java/org/oppia/android/app/help/HelpFragmentPresenter.kt#L46

File: app/src/main/java/org/oppia/android/app/topic/lessons/StorySummaryAdapter.kt [hunk 4]
```diff
@@ -148,5 +148,30 @@ class StorySummaryAdapter(
         }
       }
     }
+
+    private fun createRecyclerViewAdapter(
+      storyId: String,
+      chapterList: MutableList<ChapterSummary>
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/topic/lessons/StorySummaryAdapter.kt]: This can just be a List<> (prefer not passing around mutable lists since it makes harder to reason about the state of data at any given point since mutable types can be changed).

File: app/src/sharedTest/java/org/oppia/android/app/topic/lessons/TopicLessonsFragmentTest.kt [hunk 5]
```diff
@@ -287,29 +277,23 @@ class TopicLessonsFragmentTest {
...
-  // TODO(@973): Fix TopicLessonsFragmentTest
-  @Ignore
   fun testLessonsPlayFragment_loadRatiosTopic_chapterListIsNotVisible() {
     launch<TopicActivity>(createTopicActivityIntent(internalProfileId, RATIOS_TOPIC_ID)).use {
-      onView(
-        atPositionOnView(R.id.story_summary_recycler_view, 1, R.id.chapter_recycler_view)
-      ).check(
-        matches(not(isDisplayed()))
-      )
+      onView(withId(R.id.chapter_recycler_view)).check(doesNotExist())
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/topic/lessons/TopicLessonsFragmentTest.kt:190]: This is a nice improvement: it seems like the new view pager is more memory efficient than the old one if the views aren't even in the hierarchy.

File: app/src/main/java/org/oppia/android/app/topic/lessons/StorySummaryAdapter.kt [hunk 6]
```diff
@@ -148,5 +148,30 @@ class StorySummaryAdapter(
...
+        .registerViewBinder(
+          inflateView = { parent ->
+            LessonsChapterViewBinding.inflate(
+              LayoutInflater.from(parent.context),
+              parent,
+              /* attachToParent= */ false
+            ).root
+          },
+          bindView = { view, chapterSummary ->
+            val binding = DataBindingUtil.findBinding<LessonsChapterViewBinding>(view)!!
```
Comment (rt4914) [inline app/src/main/java/org/oppia/android/app/topic/lessons/StorySummaryAdapter.kt]: Suggest not using `!!`

File: app/src/sharedTest/java/org/oppia/android/app/topic/lessons/TopicLessonsFragmentTest.kt [hunk 7]
```diff
@@ -434,9 +418,7 @@ class TopicLessonsFragmentTest {
         )
       ).perform(click())
       onView(withId(R.id.story_summary_recycler_view)).perform(
-        scrollToPosition<RecyclerView.ViewHolder>(
-          2
-        )
+        actionOnItemAtPosition<RecyclerView.ViewHolder>(2, scrollTo())
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/topic/lessons/TopicLessonsFragmentTest.kt:275]: Why not use ``scrollToPosition`` instead? Is this what you meant in our meeting today that ``scrollToPosition`` isn't working? What is it that you're observing?

File: app/src/sharedTest/java/org/oppia/android/app/topic/lessons/TopicLessonsFragmentTest.kt [hunk 8]
```diff
@@ -544,97 +526,6 @@ class TopicLessonsFragmentTest {
...
-  //  use a test executor service with a counting idle resource, but right now Gradle mixes dependencies such that both
-  //  the test and production blocking executors are being used. The latter cannot be updated to notify Espresso of any
-  //  active coroutines, so the test attempts to assert state before it's ready. This artificial delay in the Espresso
-  //  thread helps to counter that.
-
-  /**
-   * Perform action of waiting for a specific matcher to finish. Adapted from:
-   * https://stackoverflow.com/a/22563297/3689782.
-   */
-  private fun waitForMatch(viewMatcher: Matcher<View>, millis: Long): ViewAction {
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/topic/lessons/TopicLessonsFragmentTest.kt:562]: It's awesome to see this be deleted! :D

File: app/src/sharedTest/java/org/oppia/android/app/topic/revision/TopicRevisionFragmentTest.kt [hunk 9]
```diff
@@ -234,28 +231,6 @@ class TopicRevisionFragmentTest {
     }
   }
 
-  @Test
-  // TODO(#973): Fix TopicRevisionFragmentTest
-  @Ignore
-  fun testTopicRevisionFragment_loadFragment_configurationChange_checkSpanCount_isThree() {
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/topic/revision/TopicRevisionFragmentTest.kt:240]: Why was this removed?

File: app/src/sharedTest/java/org/oppia/android/app/topic/practice/TopicPracticeFragmentTest.kt [hunk 10]
```diff
@@ -90,322 +90,403 @@ class TopicPracticeFragmentTest {
...
         )
       ).perform(click())
-      onView(withId(R.id.master_skills_text_view))
-        .check(
-          matches(
-            withText(
-              R.string.topic_practice_master_these_skills
-            )
+      testCoroutineDispatchers.runCurrent()
+      onView(
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/topic/practice/TopicPracticeFragmentTest.kt:118]: For here & tests below: can we move these clicks/matches into specific helper functions to simplify the test bodies? Look at StateFragmentTest for inspiration on how helpers can provide semantic context to make tests smaller, much more readable, and make helper function code highly reusable.

File: app/src/sharedTest/java/org/oppia/android/app/topic/practice/TopicPracticeFragmentTest.kt [hunk 11]
```diff
@@ -90,322 +90,403 @@ class TopicPracticeFragmentTest {
...
   fun testTopicPracticeFragment_loadFragment_displaySubtopics_startButtonIsInactive() {
     launchTopicActivityIntent(internalProfileId, FRACTIONS_TOPIC_ID).use {
+      testCoroutineDispatchers.runCurrent()
       onView(
         allOf(
           withText(TopicTab.getTabForPosition(2).name),
           isDescendantOfA(withId(R.id.topic_tabs_container))
         )
       ).perform(click())
-      onView(withId(R.id.master_skills_text_view))
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/topic/practice/TopicPracticeFragmentTest.kt:123]: Here & below: can you provide some brief background on why these changes were needed?

File: app/src/sharedTest/java/org/oppia/android/app/topic/practice/TopicPracticeFragmentTest.kt [hunk 12]
```diff
@@ -90,322 +90,403 @@ class TopicPracticeFragmentTest {
...
         allOf(
           withText(TopicTab.getTabForPosition(2).name),
           isDescendantOfA(withId(R.id.topic_tabs_container))
         )
       ).perform(click())
+      testCoroutineDispatchers.runCurrent()
       onView(
         atPositionOnView(
           R.id.topic_practice_skill_list,
-          1, R.id.subtopic_check_box
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/topic/practice/TopicPracticeFragmentTest.kt:185]: Interesting--do you know why ktlint didn't catch this?

File: app/src/sharedTest/java/org/oppia/android/app/topic/practice/TopicPracticeFragmentTest.kt [hunk 13]
```diff
@@ -90,322 +90,403 @@ class TopicPracticeFragmentTest {
...
+          R.id.topic_practice_start_button
+        )
+      ).check(matches(isClickable()))
     }
   }
 
   @Test
-  // TODO(#973): Fix TopicPracticeFragmentTest
-  @Ignore
   fun testTopicPracticeFragment_loadFragment_selectSubtopics_deselectSubtopics_isSuccessful() {
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/topic/practice/TopicPracticeFragmentTest.kt]:
```suggestion
  fun testTopicPracticeFragment_loadFragment_selectSubtopics_thenDeselect_selectsCorrectTopic() {
```

This is maybe slightly clearer & better matches your changes.

File: app/src/sharedTest/java/org/oppia/android/app/topic/practice/TopicPracticeFragmentTest.kt [hunk 14]
```diff
@@ -90,322 +90,403 @@ class TopicPracticeFragmentTest {
...
           R.id.topic_practice_skill_list,
           1, R.id.subtopic_check_box
         )
-      ).perform(
-        click()
-      )
+      ).perform(click())
       onView(withId(R.id.topic_practice_skill_list)).perform(
         scrollToPosition<RecyclerView.ViewHolder>(
-          10
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/topic/practice/TopicPracticeFragmentTest.kt:258]: Why did the index change? Is this a screen size thing? Will this be flaky across different screen sizes?

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @anandwana001! Did a full pass--overall, this looks good. The test & functional improvements seem quite good. Most of my comments were nits, requests for clarification, and some suggestions to improve readability.

One high-level question that I have: can you please confirm that all the changed tests here still pass when run via Espresso and when run locally in Robolectric via Bazel?

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

File: app/src/main/java/org/oppia/android/app/topic/lessons/StorySummaryAdapter.kt (hunk 6 above)
Comment (rt4914) [reply app/src/main/java/org/oppia/android/app/topic/lessons/StorySummaryAdapter.kt]: @anandwana001 You can resolve this on your own with proper comment.

File: app/src/sharedTest/java/org/oppia/android/app/topic/lessons/TopicLessonsFragmentTest.kt (hunk 7 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/topic/lessons/TopicLessonsFragmentTest.kt:275]: Yes. 
While using `scrollToPosition `, the recyclerview item is not `CompletlyDisplayed` after scrolling, and because of which robolectric is not able to perform and ViewAction. But using ViewActions.scrollTo, it seems working and `CompletlyDisplayed` too.

File: app/src/sharedTest/java/org/oppia/android/app/topic/revision/TopicRevisionFragmentTest.kt (hunk 9 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/topic/revision/TopicRevisionFragmentTest.kt:240]: Shifted to `ProfileChooserSpanTest` as all the test related to span is there.

File: app/src/sharedTest/java/org/oppia/android/app/topic/practice/TopicPracticeFragmentTest.kt (hunk 11 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/topic/practice/TopicPracticeFragmentTest.kt:123]: `master_skills_text_view ` is not a direct text view, it's an item in the first position of RecyclerView, so to match the text with the 0th index of an item in the RecyclerView this change is needed.

File: app/src/sharedTest/java/org/oppia/android/app/topic/practice/TopicPracticeFragmentTest.kt (hunk 12 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/topic/practice/TopicPracticeFragmentTest.kt:185]: We are using `0.37.0` and this catch is something on newer version on experimental phase. 
reference 
 - https://github.com/pinterest/ktlint/issues/926
 - https://github.com/pinterest/ktlint#experimental-rules
 - https://github.com/pinterest/ktlint/issues/620

File: app/src/sharedTest/java/org/oppia/android/app/topic/practice/TopicPracticeFragmentTest.kt (hunk 14 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/topic/practice/TopicPracticeFragmentTest.kt:258]: 10 is wrong previously because it's not the real index of the last item in the recyclerview.

File: app/src/main/java/org/oppia/android/app/topic/TopicFragmentPresenter.kt (hunk 1 above)
Comment (anandwana001) [reply app/src/main/java/org/oppia/android/app/topic/TopicFragmentPresenter.kt]: done

File: app/src/main/java/org/oppia/android/app/topic/TopicFragmentPresenter.kt (hunk 2 above)
Comment (anandwana001) [reply app/src/main/java/org/oppia/android/app/topic/TopicFragmentPresenter.kt]: done

File: app/src/main/java/org/oppia/android/app/topic/lessons/StorySummaryAdapter.kt (hunk 4 above)
Comment (anandwana001) [reply app/src/main/java/org/oppia/android/app/topic/lessons/StorySummaryAdapter.kt]: done

File: app/src/sharedTest/java/org/oppia/android/app/topic/practice/TopicPracticeFragmentTest.kt (hunk 13 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/topic/practice/TopicPracticeFragmentTest.kt]: done

File: app/src/main/java/org/oppia/android/app/topic/lessons/StorySummaryAdapter.kt (hunk 6 above)
Comment (anandwana001) [reply app/src/main/java/org/oppia/android/app/topic/lessons/StorySummaryAdapter.kt]: Shifted to viewmodel

File: app/src/main/java/org/oppia/android/app/topic/lessons/StorySummaryAdapter.kt (hunk 3 above)
Comment (anandwana001) [reply app/src/main/java/org/oppia/android/app/topic/lessons/StorySummaryAdapter.kt]: done

File: app/src/sharedTest/java/org/oppia/android/app/topic/practice/TopicPracticeFragmentTest.kt (hunk 10 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/topic/practice/TopicPracticeFragmentTest.kt:118]: done

**Comment by anandwana001** [comment]
> Thanks @anandwana001! Did a full pass--overall, this looks good. The test & functional improvements seem quite good. Most of my comments were nits, requests for clarification, and some suggestions to improve readability.
> 
> One high-level question that I have: can you please confirm that all the changed tests here still pass when run via Espresso and when run locally in Robolectric via Bazel?

All tests are passing on espresso and robolectric. 

### 1
Need to run bazel tests, as of now I need to re-setup the bazel as I am getting timed out error. ` no such package '@maven//': Error while fetching artifact with coursier: Timed out`

### 2
**Build apk on bazel without extra param leads to error**

```console
ERROR: app/BUILD.bazel:554:19: output 'app/databinding/view_models_base/bin-files/org.oppia.android.app.view.models-org.oppia.android.app.view.models-setter_store.bin' was not created
ERROR: app/BUILD.bazel:554:19: output 'app/databinding/view_models_base/bin-files/org.oppia.android.app.view.models-org.oppia.android.app.view.models-layoutinfo.bin' was not created
ERROR: app/BUILD.bazel:554:19: output 'app/databinding/view_models_base/bin-files/org.oppia.android.app.view.models-org.oppia.android.app.view.models-br.bin' was not created
ERROR: app/BUILD.bazel:554:19: not all outputs were created or valid
Target //:oppia failed to build
```

**build apk successfully on local, using our data binding version of `bazel` not the regular one.**
```console
bazel build //oppia --android_databinding_use_v3_4_args --experimental_android_databinding_v2 --java_header_compilation=false --noincremental_dexing --define=android_standalone_dexing_tool=d8_compat_dx
```

### 3

```console
bazel test //app:TopicLessonsFragmentTest --android_databinding_use_v3_4_args --experimental_android_databinding_v2 --java_header_compilation=false --noincremental_dexing --define=android_standalone_dexing_tool=d8_compat_dx
```
Screenshot 2020-11-27 at 10 53 08
Screenshot 2020-11-27 at 10 56 35
Screenshot 2020-11-27 at 10 59 10
Screenshot 2020-11-27 at 11 00 38
Screenshot 2020-11-27 at 11 02 17

Adding @rt4914 for future reference regarding bazel tests running.

File: app/src/main/java/org/oppia/android/app/topic/lessons/StorySummaryViewModel.kt [hunk 15]
```diff
@@ -6,8 +6,30 @@ import org.oppia.android.app.model.StorySummary
...
+          explorationId = chapterSummary.explorationId,
+          chapterName = chapterSummary.name,
+          storyId = storySummary.storyId,
+          index = index,
+          chapterSummarySelector = chapterSummarySelector
+        )
+      )
+    }
+    return arrayList
+  }
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/topic/lessons/StorySummaryViewModel.kt]:
```suggestion
  private fun getRecyclerViewItemList(): List<ChapterSummaryViewModel> {
    return storySummary.chapterList.mapIndexed { index, chapterSummary ->
      ChapterSummaryViewModel(
        chapterPlayState = chapterSummary.chapterPlayState,
        explorationId = chapterSummary.explorationId,
        chapterName = chapterSummary.name,
        storyId = storySummary.storyId,
        index = index,
        chapterSummarySelector = chapterSummarySelector
      )
    }
  }
```

1. Prefer avoiding ArrayList (MutableList is the Kotlin idiomatic way to have modifiable lists)
2. Prefer to pass around List (since it's read-only and improves code robustness in the same way preferring val over var does)
3. Prefer to transform the list & compute a new one

File: app/src/main/java/org/oppia/android/app/topic/lessons/StorySummaryViewModel.kt [hunk 16]
```diff
@@ -6,8 +6,30 @@ import org.oppia.android.app.model.StorySummary
...
+  private val storySummarySelector: StorySummarySelector,
+  private val chapterSummarySelector: ChapterSummarySelector
 ) : TopicLessonsItemViewModel() {
+  private val arrayList = ArrayList<ChapterSummaryViewModel>()
+
+  val chapterSummaryItemList: List<ChapterSummaryViewModel> by lazy {
+    getRecyclerViewItemList()
+  }
+
+  private fun getRecyclerViewItemList(): ArrayList<ChapterSummaryViewModel> {
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/topic/lessons/StorySummaryViewModel.kt]: Perhaps instead: ``computeChapterSummaryItemList`` (prefer to be specific vs. 'recycler view item list' and prefer 'compute' since this isn't a trivial getter).

File: app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt [hunk 17]
```diff
@@ -202,181 +186,88 @@ class TopicFragmentTest {
...
-          withText(TopicTab.getTabForPosition(0).name),
-          isDescendantOfA(withId(R.id.topic_tabs_container))
-        )
-      ).perform(click())
-      onView(withId(R.id.topic_tabs_container)).check(
-        matches(
-          matchCurrentTabTitle(TopicTab.getTabForPosition(0).name)
-        )
-      )
+      clickTabAtPosition(position = 3)
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt]: One suggestion: maybe create a few top-level test constants to represent the positions for each tab, e.g.:

```kotlin
private const val INFO_TAB_POSITION = 0
...
private const val REVIEW_TAB_POSITION = 3
```

Then you can do something like ``clickTabAtPosition(REVIEW_TAB_POSITION)`` which will further help with readability. I'm not sure the position is actually needed in the context of the test in this case, so I think we can abstract it away without losing information.

File: app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt [hunk 18]
```diff
@@ -544,6 +364,48 @@ class TopicFragmentTest {
...
+        matchCurrentTabTitle(
+          TopicTab.getTabForPosition(position).name
+        )
+      )
+    )
+  }
+
+  private fun matchStringOnListItem(
+    recyclerView: Int,
+    position: Int,
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt]: Perhaps: ``itemPosition`` would be clearer.

File: app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt [hunk 19]
```diff
@@ -480,31 +322,15 @@ class TopicFragmentTest {
...
-              "What is a Fraction?"
-            )
-          )
-        )
+      matchTabTitleAtPosition(position = 3)
+      matchStringOnListItem(
+        recyclerView = R.id.revision_recycler_view,
+        position = 0,
+        targetViewId = R.id.subtopic_title,
+        stringToMatch = "What is a Fraction?"
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt]: Optional, but you could further specialize this for certain recycler views (e.g. new helpers that use this helper), such as:

```kotlin
verifySubtopicTitleIsPresent(subtopicPosition = 0, subtopicTitle = "What is a Fraction?")
```

Ditto for the other recycler views.

File: app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt [hunk 20]
```diff
@@ -544,6 +364,48 @@ class TopicFragmentTest {
     return launch(createTopicActivityIntent(internalProfileId, topicId))
   }
 
+  private fun clickTabAtPosition(position: Int) {
+    onView(
+      Matchers.allOf(
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt]: Prefer directly importing allOf() for consistency.

File: app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt [hunk 21]
```diff
@@ -544,6 +364,48 @@ class TopicFragmentTest {
...
+        withText(TopicTab.getTabForPosition(position).name),
+        isDescendantOfA(withId(R.id.topic_tabs_container))
+      )
+    ).perform(click())
+  }
+
+  private fun matchTabTitleAtPosition(position: Int) {
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt]: Here & below: suggest phrasing this in terms of making assertions. For example: ``verifyTabTitleAtPosition`` ('verify' is stronger language than just 'match' since it implies we need it to be a certain state).

File: app/src/sharedTest/java/org/oppia/android/app/topic/info/TopicInfoFragmentTest.kt [hunk 22]
```diff
@@ -190,8 +196,7 @@ class TopicInfoFragmentTest {
   }
 
   @Test
-  // TODO(#973): Fix TopicInfoFragmentTest
-  @Ignore
+  @RunOn(TestPlatform.ESPRESSO) // TODO(#1612): Enable for Robolectric.
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/topic/info/TopicInfoFragmentTest.kt]: This doesn't seem like the correct issue number. Should this be referring to #2057 instead? Ditto below.

File: app/src/sharedTest/java/org/oppia/android/app/topic/lessons/TopicLessonsFragmentTest.kt (hunk 7 above)
Comment (BenHenning) [reply app/src/sharedTest/java/org/oppia/android/app/topic/lessons/TopicLessonsFragmentTest.kt:275]: Strange. What's the difference between the two?

File: app/src/sharedTest/java/org/oppia/android/app/topic/lessons/TopicLessonsFragmentTest.kt [hunk 23]
```diff
@@ -526,6 +322,52 @@ class TopicLessonsFragmentTest {
...
+  }
+
+  private fun clickStoryItem(position: Int, targetViewId: Int) {
+    onView(
+      atPositionOnView(
+        R.id.story_summary_recycler_view,
+        position,
+        targetViewId
+      )
+    ).perform(click())
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/topic/lessons/TopicLessonsFragmentTest.kt:351]: Suggest adding another runCurrent() after this to help guard against stabilization issues (you may not notice them, but they can crop up for other people).

File: app/src/sharedTest/java/org/oppia/android/app/topic/lessons/TopicLessonsFragmentTest.kt [hunk 24]
```diff
@@ -526,6 +322,52 @@ class TopicLessonsFragmentTest {
...
+  }
+
+  private fun scrollToPosition(position: Int) {
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/topic/lessons/TopicLessonsFragmentTest.kt:355]: Should we still be using this per your earlier comment? I'm concerned about having 2 different scrolling solutions in Oppia Android--we ought to consolidate to a single one.

File: app/src/sharedTest/java/org/oppia/android/app/topic/lessons/TopicLessonsFragmentTest.kt [hunk 25]
```diff
@@ -526,6 +322,52 @@ class TopicLessonsFragmentTest {
...
+    onView(withId(R.id.story_summary_recycler_view)).perform(
+      scrollToPosition<RecyclerView.ViewHolder>(
+        position
+      )
+    )
+  }
+
+  private fun matchStringOnStorySummaryListItem(position: Int, stringToMatch: String) {
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/topic/lessons/TopicLessonsFragmentTest.kt]: Ditto here per my comment in the other test file (prefer something like 'verify*...').

File: app/src/sharedTest/java/org/oppia/android/app/topic/practice/TopicPracticeFragmentTest.kt [hunk 26]
```diff
@@ -239,66 +188,28 @@ class TopicPracticeFragmentTest {
...
-          R.id.topic_practice_skill_list,
-          1, R.id.subtopic_check_box
-        )
       ).check(matches(not(isChecked())))
     }
   }
 
   @Test
-  fun testTopicPracticeFragment_loadFragment_selectSubtopics_deselectsubtopics_startButtonIsInactive() { // ktlint-disable max-line-length
+  fun testTopicPracticeFragment_loadFragment_selectSubtopics_deselectSubtopics_startButtonIsInactive() { // ktlint-disable max-line-length
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/topic/practice/TopicPracticeFragmentTest.kt]: Can we remove the max-line disable directive now?

File: app/src/sharedTest/java/org/oppia/android/app/topic/practice/TopicPracticeFragmentTest.kt [hunk 27]
```diff
@@ -503,6 +339,35 @@ class TopicPracticeFragmentTest {
...
+  }
+
+  private fun clickPracticeItem(position: Int, targetViewId: Int) {
+    onView(
+      atPositionOnView(
+        R.id.topic_practice_skill_list,
+        position,
+        targetViewId
+      )
+    ).perform(click())
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/topic/practice/TopicPracticeFragmentTest.kt:369]: For this & the previous helper: suggest adding runCurrent() calls here and above, too, to preemptively address potential stability issues.

File: app/src/sharedTest/java/org/oppia/android/app/topic/revision/TopicRevisionFragmentTest.kt [hunk 28]
```diff
@@ -174,36 +151,12 @@ class TopicRevisionFragmentTest {
     }
   }
 
-  @Test
-  fun testTopicRevisionFragment_loadFragment_checkSpanCoun_isTwo() {
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/topic/revision/TopicRevisionFragmentTest.kt:181]: Why is this test being removed?

File: app/src/sharedTest/java/org/oppia/android/app/topic/revision/TopicRevisionFragmentTest.kt [hunk 29]
```diff
@@ -244,6 +191,24 @@ class TopicRevisionFragmentTest {
...
+    ).perform(click())
+    testCoroutineDispatchers.runCurrent()
+  }
+
+  private fun scrollToPosition(position: Int) {
+    onView(withId(R.id.revision_recycler_view)).perform(
+      scrollToPosition<RecyclerView.ViewHolder>(
+        position
+      )
+    )
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/topic/revision/TopicRevisionFragmentTest.kt:209]: Ditto here (suggest adding a runCurrent()).

File: app/src/sharedTest/java/org/oppia/android/app/topic/practice/TopicPracticeFragmentTest.kt (hunk 12 above)
Comment (BenHenning) [reply app/src/sharedTest/java/org/oppia/android/app/topic/practice/TopicPracticeFragmentTest.kt:185]: Ah, thanks for the context. That's unfortunate that it's still experimental.

File: app/src/sharedTest/java/org/oppia/android/app/topic/revision/TopicRevisionFragmentTest.kt (hunk 9 above)
Comment (BenHenning) [reply app/src/sharedTest/java/org/oppia/android/app/topic/revision/TopicRevisionFragmentTest.kt:240]: ``ProfileChooserSpanTest`` is testing profile span wrapping, not the number of spans for the revision card. Don't we still need this? E.g. the profile span functionality might change--that won't affect how we handle the revision card columns.

File: app/src/sharedTest/java/org/oppia/android/app/topic/practice/TopicPracticeFragmentTest.kt (hunk 11 above)
Comment (BenHenning) [reply app/src/sharedTest/java/org/oppia/android/app/topic/practice/TopicPracticeFragmentTest.kt:123]: Ah, weird that it was written in this way originally then. That makes sense--thanks!

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @anandwana001! I think the test simplifications are great! Just have a bunch of nits to address, then I think the PR will LGTM.

**Comment by BenHenning** [comment]
@anandwana001 what specific issues did you run into with Bazel and how did you work around them? That wasn't entirely clear to me from your comment (& in general, please try to be clear about what you tried that didn't work, and what you tried that did to help others who might run into the same issue in the future).

File: app/src/sharedTest/java/org/oppia/android/app/topic/revision/TopicRevisionFragmentTest.kt (hunk 28 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/topic/revision/TopicRevisionFragmentTest.kt:181]: This is shifted to its related *spanTest file.

File: app/src/sharedTest/java/org/oppia/android/app/topic/revision/TopicRevisionFragmentTest.kt (hunk 9 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/topic/revision/TopicRevisionFragmentTest.kt:240]: ah, my bad, I am sorry here, this test is shifted to `TopicRevisionSpanTest`

**Comment by anandwana001** [comment]
> @anandwana001 what specific issues did you run into with Bazel and how did you work around them? That wasn't entirely clear to me from your comment (& in general, please try to be clear about what you tried that didn't work, and what you tried that did to help others who might run into the same issue in the future).

I did mention, let me just format it a bit.

File: app/src/main/java/org/oppia/android/app/topic/lessons/StorySummaryViewModel.kt (hunk 15 above)
Comment (anandwana001) [reply app/src/main/java/org/oppia/android/app/topic/lessons/StorySummaryViewModel.kt]: done

File: app/src/main/java/org/oppia/android/app/topic/lessons/StorySummaryViewModel.kt (hunk 16 above)
Comment (anandwana001) [reply app/src/main/java/org/oppia/android/app/topic/lessons/StorySummaryViewModel.kt]: done

File: app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt (hunk 17 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt]: Done

File: app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt (hunk 18 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt]: done

File: app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt (hunk 19 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt]: as this is something optional, I will create a good-first-issue for this as the footfall of contributors is increasing a lot.

File: app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt (hunk 20 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt]: ah, missed it. Done

File: app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt (hunk 21 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt]: Sounds good, Done

File: app/src/sharedTest/java/org/oppia/android/app/topic/info/TopicInfoFragmentTest.kt (hunk 22 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/topic/info/TopicInfoFragmentTest.kt]: done

File: app/src/sharedTest/java/org/oppia/android/app/topic/lessons/TopicLessonsFragmentTest.kt (hunk 25 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/topic/lessons/TopicLessonsFragmentTest.kt]: done

File: app/src/sharedTest/java/org/oppia/android/app/topic/practice/TopicPracticeFragmentTest.kt (hunk 26 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/topic/practice/TopicPracticeFragmentTest.kt]: done

File: app/src/sharedTest/java/org/oppia/android/app/topic/practice/TopicPracticeFragmentTest.kt (hunk 27 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/topic/practice/TopicPracticeFragmentTest.kt:369]: done

File: app/src/sharedTest/java/org/oppia/android/app/topic/revision/TopicRevisionFragmentTest.kt (hunk 28 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/topic/revision/TopicRevisionFragmentTest.kt:181]: `TopicRevisionSpanTest`

File: app/src/sharedTest/java/org/oppia/android/app/topic/revision/TopicRevisionFragmentTest.kt (hunk 29 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/topic/revision/TopicRevisionFragmentTest.kt:209]: done

File: app/src/sharedTest/java/org/oppia/android/app/topic/lessons/TopicLessonsFragmentTest.kt (hunk 23 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/topic/lessons/TopicLessonsFragmentTest.kt:351]: done

File: app/src/sharedTest/java/org/oppia/android/app/topic/lessons/TopicLessonsFragmentTest.kt (hunk 24 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/topic/lessons/TopicLessonsFragmentTest.kt:355]: So the flow is:
 - the clicking of a drop-down icon which expands the story card and shows chapter. 
 - We had already expand the first item
 - Now, when we try to scroll over the second item and perform a click, the click doesn't happen because the view is not visible completely **(The reason I think here is maybe the regular scrolling is not scrolling the item on a completely visible state on the screen. )**
 - Using `ViewActions.scrollTo()` does the hack here. 

`ViewActions.scrollTo()` work on the basis of View, which works on visible bounds under the hood - `view.getDrawingRect(rect);`
whereas
`RecyclerViewActions.scrollToPosition` works on the basis of item position.

Also, under the hood, `RecyclerViewActions` using `import android.support.v7.widget.RecyclerView;`.

Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/topic/lessons/TopicLessonsFragmentTest.kt:355]: Adding @rt4914 for future reference

File: app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt [hunk 30]
```diff
@@ -145,7 +150,7 @@ class TopicFragmentTest {
     launchTopicActivityIntent(internalProfileId, FRACTIONS_TOPIC_ID).use {
       onView(withId(R.id.topic_tabs_viewpager)).check(matches(isDisplayed()))
       onView(withId(R.id.topic_tabs_viewpager)).perform(swipeLeft())
-      matchTabTitleAtPosition(position = 1)
+      verifyTabTitleAtPosition(position = 1)
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt]: Shouldn't this be ``position = LESSON_TAB_POSITION``? Ditto elsewhere for tab positions.

File: app/src/sharedTest/java/org/oppia/android/app/topic/lessons/TopicLessonsFragmentTest.kt (hunk 24 above)
Comment (BenHenning) [reply app/src/sharedTest/java/org/oppia/android/app/topic/lessons/TopicLessonsFragmentTest.kt:355]: Ah, in that case can you:
1. Introduce a new testing module file that provides scrolling actions
2. Wrap both of the two solutions behind two methods in the new class
3. Add documentation capturing the context above (the goal here is to provide sufficient context for developers to be able to decide between using one versus the other)
4. Update the references in this PR to use the new utilities
5. File a starter issue to update all other references in the codebase with the new utilities

Given how complex this is, I think we need to centrally manage scrolling so that we can be really deliberate about when to use option A or B. Long-term we can work to consolidate these, but we should avoid hiding context that requires esoteric knowledge (otherwise someone's just going to get confused in the future when they ask the same question & try digging into it).

File: app/src/sharedTest/java/org/oppia/android/app/topic/revision/TopicRevisionFragmentTest.kt (hunk 9 above)
Comment (BenHenning) [reply app/src/sharedTest/java/org/oppia/android/app/topic/revision/TopicRevisionFragmentTest.kt:240]: Aha, thanks for clarifying. Got it.

File: app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt (hunk 19 above)
Comment (BenHenning) [reply app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt]: Sounds good. Please mention the issue here once it exists (and add TODOs in code pointing to the issue where things need to change).

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @anandwana001! PR in its current form looks good, but let's try to consolidate the complexity around scrolling to avoid future developers running into similar pitfalls when working on test stability.

File: app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt (hunk 19 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt]: #2208

File: app/src/sharedTest/java/org/oppia/android/app/topic/lessons/TopicLessonsFragmentTest.kt (hunk 24 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/topic/lessons/TopicLessonsFragmentTest.kt:355]: https://github.com/oppia/oppia-android/issues/2209
Split this work into another issue and will continue this on parallel side.

File: app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt (hunk 30 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt]: ah, done

File: app/src/sharedTest/java/org/oppia/android/app/topic/lessons/TopicLessonsFragmentTest.kt (hunk 24 above)
Comment (BenHenning) [reply app/src/sharedTest/java/org/oppia/android/app/topic/lessons/TopicLessonsFragmentTest.kt:355]: Sg, thanks.

File: app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt (hunk 19 above)
Comment (BenHenning) [reply app/src/sharedTest/java/org/oppia/android/app/topic/TopicFragmentTest.kt]: Left a reply on the issue, but otherwise lgtm.

**Review by BenHenning — APPROVED** [review]
Thanks @anandwana001. LGTM!
