### PR TITLE
Fix #5232: ConsoleLogger overwrites local log file for each line write

### LINKED ISSUE #5232: [BUG]: ConsoleLogger overwrites local log file for each line write
### Describe the bug

``ConsoleLogger`` has support for logging output lines to a local log (rather than just logcat). However, it seems that this is currently configured such that each line will completely overwrite the original log file.

### Steps To Reproduce

- Build & install a developer version of Oppia Android.
- Play around in the app for a bit to generate logs.
- Pull logs from logcat (e.g. either in Android Studio or via ``adb logcat | grep org.oppia.android``).
- Pull the logs file: ``$ANDROID_HOME/platform-tools/adb pull /data/data/org.oppia.android/files/oppia_app.log ~/opensource/oppia_app.log``
- Compare these logs. Notice that the last entry in oppia_app.log is just the last log written in the logcat log.

### Expected Behavior

All lines should be kept, not just the most recent.

### Screenshots/Videos

_No response_

### What device/emulator are you using?

Pixel 6a emulator

### Which Android version is your device/emulator running?

SDK 33

### Which version of the Oppia Android app are you using?

0.11-dev-80a9a09723

### Additional Context

From the logic in ``ConsoleLogger``:

https://github.com/oppia/oppia-android/blob/6006277f33af2e981964fc4ab58e366c7f39e21a/utility/src/main/java/org/oppia/android/util/logging/ConsoleLogger.kt#L108

I suspect this is caused by the open ``FileWriter`` just always, by default, overwriting the file. We should, instead, open the writer in append mode & add tests to verify that this functionality now works.

Also, it's probably a good idea to keep a long-lived ``PrintStream`` open for the log file rather than reopening it for each line (which is going to be less performant). We _should_ overwrite the file in this case (to avoid indefinitely using more disk space for debug logs). This includes adding tests for verifying that multiple ``ConsoleLogger`` instances _do_ overwrite the file from the previous logger.

### PR DESCRIPTION
**Pull request by manas-yu**
## Explanation
Fix #5232
This PR updates the `ConsoleLogger` class to improve logging functionality. The key changes include:

- **Append Mode for Logs**: The `FileWriter` is now opened in append mode, ensuring that new log entries are added to the existing log file instead of overwriting it.
- **Long-lived PrintWriter**: A long-lived `PrintWriter` instance has been implemented to enhance performance by reducing the overhead of opening and closing the log file multiple times.
- **Close Log File**: A `closeLogFile()` method has been added to properly close the `PrintWriter`, preventing resource leaks after logging is complete.

These changes address the issue of logs being overwritten and enhance performance while ensuring proper resource management. 

## Essential Checklist
- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

### CODE REVIEW

**Comment by manas-yu** [comment]
@adhiamboperes, PTAL.

**Comment by manas-yu** [comment]
@adhiamboperes should i add tests in the ConsoleLoggerTest.kt for the Append mode and the Print Writer?

**Comment by adhiamboperes** [comment]
@manas-yu, yes, we do require tests for all changes.

**Comment by manas-yu** [comment]
@adhiamboperes, PTAL i have added tests for the ConsoleLogger

File: utility/src/main/java/org/oppia/android/util/logging/ConsoleLogger.kt [hunk 1]
```diff
@@ -33,6 +35,9 @@ class ConsoleLogger @Inject constructor(
    */
   val logErrorMessagesFlow: SharedFlow<ConsoleLoggerContext> = _logErrorMessagesFlow
 
+  /** Long-lived PrintWriter to improve performance by not reopening the file every time */
```
Comment (adhiamboperes) [inline utility/src/main/java/org/oppia/android/util/logging/ConsoleLogger.kt]: We do not require documentation for private fields and functions, unless very necessary. In this case, it is safe to remove the KDoc.

File: utility/src/main/java/org/oppia/android/util/logging/ConsoleLogger.kt [hunk 2]
```diff
@@ -124,10 +129,23 @@ class ConsoleLogger @Inject constructor(
...
-   * thread. A blocking dispatcher is used to ensure messages are written in order.
+   * Writes the specified text line to file in a background thread to ensure that saving messages
+   * doesn't block the main thread. A blocking dispatcher is used to ensure messages are written
+   * in order.
    */
   private fun logToFileInBackground(text: String) {
-    blockingScope.launch { logDirectory.printWriter().use { out -> out.println(text) } }
+    blockingScope.launch {
+      if (printWriter == null) {
+        printWriter = PrintWriter(FileWriter(logDirectory, true)) // Open in append mode
```
Comment (adhiamboperes) [inline utility/src/main/java/org/oppia/android/util/logging/ConsoleLogger.kt]:
```suggestion
        printWriter = PrintWriter(FileWriter(logDirectory, true)) // Open in append mode.
```

File: utility/src/main/java/org/oppia/android/util/logging/ConsoleLogger.kt [hunk 3]
```diff
@@ -124,10 +129,23 @@ class ConsoleLogger @Inject constructor(
...
+      }
+      printWriter?.println(text)
+      printWriter?.flush()
+    }
+  }
+
+  /** Close the log file when logging is finished. */
+  fun closeLogFile() {
```
Comment (adhiamboperes) [inline utility/src/main/java/org/oppia/android/util/logging/ConsoleLogger.kt]: Shouldn't this be private?

File: utility/src/test/java/org/oppia/android/util/logging/ConsoleLoggerTest.kt [hunk 4]
```diff
@@ -54,9 +55,13 @@ class ConsoleLoggerTest {
   @field:[Inject BackgroundTestDispatcher]
   lateinit var backgroundTestDispatcher: TestCoroutineDispatcher
 
+  private lateinit var logFile: File
+
   @Before
   fun setUp() {
     setUpTestApplicationComponent()
+    logFile = File(context.filesDir, "oppia_app.log")
+    logFile.delete() // Ensure we start with a clean log file
```
Comment (adhiamboperes) [inline utility/src/test/java/org/oppia/android/util/logging/ConsoleLoggerTest.kt]:
```suggestion
    logFile.delete() // Ensure we start with a clean log file.
```

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @manas-yu! PTAL at my comments.

**Comment by manas-yu** [comment]
@adhiamboperes,PTAL i have made the specified changes.

File: utility/src/main/java/org/oppia/android/util/logging/ConsoleLogger.kt [hunk 5]
```diff
@@ -124,10 +128,23 @@ class ConsoleLogger @Inject constructor(
...
+      }
+      printWriter?.println(text)
+      printWriter?.flush()
+    }
+  }
+
+  /** Close the log file when logging is finished. */
+  private fun closeLogFile() {
+    printWriter?.close()
+    printWriter = null
```
Comment (adhiamboperes) [inline utility/src/main/java/org/oppia/android/util/logging/ConsoleLogger.kt]: Follow up -- seems this was only used in tests before but it is nolonger needed. Please confirm and remove.

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thannks @manasyu! I just had one follow up comment. PTAL.

Also, it is the responsibility of the reviewer to resolve comments so that they can veerify that it was correctly addressed. But you can reply to the comments and say that you have addressed it.

File: utility/src/main/java/org/oppia/android/util/logging/ConsoleLogger.kt (hunk 5 above)
Comment (manas-yu) [reply utility/src/main/java/org/oppia/android/util/logging/ConsoleLogger.kt]: consoleLogFile removed.

**Comment by manas-yu** [comment]
@adhiamboperes is there anything else that needs to be done?

**Comment by adhiamboperes** [comment]
@manas-yu, PTAL at failing test:

```
org.oppia.android.util.logging.ConsoleLoggerTest > testConsoleLogger_closeAndReopen_continuesToAppend FAILED
    java.io.FileNotFoundException: /tmp/robolectric-Method_testConsoleLogger_closeAndReopen_continuesToAppend1146850382645191789/org.oppia.android.util.test-dataDir/files/oppia_app.log (No such file or directory)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:196)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:139)
        at kotlin.io.FilesKt__FileReadWriteKt.readText(FileReadWrite.kt:125)
        at kotlin.io.FilesKt__FileReadWriteKt.readText$default(FileReadWrite.kt:125)
        at  
```

**Comment by manas-yu** [comment]
@adhiamboperes the testConsoleLogger_closeAndReopen_continuesToAppend test was running fine locally but i have still added a check to ensure that the logfile exists.

**Comment by manas-yu** [comment]
@adhiamboperes sorry for the inconveniences, the tests were passing locally so i had some issues. But i have added LogFilePath dependency and improved the logger.

**Comment by manas-yu** [comment]
@adhiamboperes PTAL, the tests should pass now.

File: utility/src/test/java/org/oppia/android/util/logging/ConsoleLoggerTest.kt [hunk 6]
```diff
@@ -54,26 +54,60 @@ class ConsoleLoggerTest {
...
+  private fun logTestMessage(message: String) {
+    when (testLogLevel) {
+      LogLevel.VERBOSE -> consoleLogger.v(testTag, message)
+      LogLevel.DEBUG -> consoleLogger.d(testTag, message)
+      LogLevel.INFO -> consoleLogger.i(testTag, message)
+      LogLevel.WARNING -> consoleLogger.w(testTag, message)
+      LogLevel.ERROR -> consoleLogger.e(testTag, message)
+    }
+    testCoroutineDispatchers.advanceUntilIdle()
+  }
```
Comment (adhiamboperes) [inline utility/src/test/java/org/oppia/android/util/logging/ConsoleLoggerTest.kt]: I don't see a reason for this function, please remove, since the `testLogLevel` value never changes in any of the tests. You could just use `consoleLogger.e(testTag, message)` directly as needed in the tests. `e` because the test file configures global log level to error.

**Comment by manas-yu** [comment]
Hey @adhiamboperes, is there anything else that needs to be done?

File: utility/src/test/java/org/oppia/android/util/logging/ConsoleLoggerTest.kt [hunk 7]
```diff
@@ -54,26 +54,60 @@ class ConsoleLoggerTest {
   @field:[Inject BackgroundTestDispatcher]
   lateinit var backgroundTestDispatcher: TestCoroutineDispatcher
 
+  private lateinit var logFile: File
+
   @Before
   fun setUp() {
     setUpTestApplicationComponent()
+    // Initialize logFile and ensure parent directories exist
```
Comment (adhiamboperes) [inline utility/src/test/java/org/oppia/android/util/logging/ConsoleLoggerTest.kt]: Remove unneccessary comment

File: utility/src/test/java/org/oppia/android/util/logging/ConsoleLoggerTest.kt [hunk 8]
```diff
@@ -54,26 +54,60 @@ class ConsoleLoggerTest {
...
+    logFile = File(context.filesDir, "oppia_app.log")
+    logFile.parentFile?.mkdirs()
```
Comment (adhiamboperes) [inline utility/src/test/java/org/oppia/android/util/logging/ConsoleLoggerTest.kt]:
```suggestion

```
The previous line creates the file in the test home directory, so this line is not needed.

File: utility/src/test/java/org/oppia/android/util/logging/ConsoleLoggerTest.kt [hunk 9]
```diff
@@ -54,26 +54,60 @@ class ConsoleLoggerTest {
...
+      LogLevel.ERROR -> consoleLogger.e(testTag, message)
+    }
+    testCoroutineDispatchers.advanceUntilIdle()
+  }
+
+  @Test
+  fun testConsoleLogger_multipleLogCalls_appendsToFile() {
+    logTestMessage(testMessage)
+    logTestMessage("$testMessage 2")
+
```
Comment (adhiamboperes) [inline utility/src/test/java/org/oppia/android/util/logging/ConsoleLoggerTest.kt]:
```suggestion
    consoleLogger.e(testTag, testMessage)
    consoleLogger.e(testTag, "$testMessage 2")

    testCoroutineDispatchers.advanceUntilIdle()
```

File: utility/src/test/java/org/oppia/android/util/logging/ConsoleLoggerTest.kt [hunk 10]
```diff
@@ -54,26 +54,60 @@ class ConsoleLoggerTest {
...
+    assertThat(logContent.indexOf(testMessage)).isLessThan(logContent.indexOf("$testMessage 2"))
   }
 
   @Test
   @OptIn(ExperimentalCoroutinesApi::class)
-  fun testConsoleLogger_logError_withMessage_logsMessage() {
-    val firstErrorContextsDeferred = CoroutineScope(backgroundTestDispatcher).async {
-      consoleLogger.logErrorMessagesFlow.take(1).toList()
-    }
+  fun testConsoleLogger_closeAndReopen_continuesToAppend() = runTest {
```
Comment (adhiamboperes) [inline utility/src/test/java/org/oppia/android/util/logging/ConsoleLoggerTest.kt]: I think the original test that used to be here should be returned, because it tests a totally different thing (code coverage will fail).

Move the new test to be a seperate test. Additionally, we don't use `runTest` in tests. we have various testCoroutineDispatchers to manage syncronization in tests. Suggest using:

```kotlin
@Test
  fun testConsoleLogger_closeAndReopen_continuesToAppend() {
    consoleLogger.e(testTag, "first $testMessage")

    testCoroutineDispatchers.advanceUntilIdle()

    // Force close the PrintWriter to simulate app restart
    val printWriterField = ConsoleLogger::class.java.getDeclaredField("printWriter")
    printWriterField.isAccessible = true
    (printWriterField.get(consoleLogger) as? PrintWriter)?.close()
    printWriterField.set(consoleLogger, null)

    consoleLogger.e(testTag, "first $testMessage")

    consoleLogger.e(testTag, "second $testMessage")
    testCoroutineDispatchers.advanceUntilIdle()

    val logContent = logFile.readText()
    assertThat(logContent).contains("first $testMessage")
    assertThat(logContent).contains("second $testMessage")
  }
```

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @manas-yu!

Could we focus on getting this PR merged before working on the other 2? Having your first PR merged will allow your CI checks to run automatically, which should speed up your development.

**Comment by manas-yu** [comment]
@adhiamboperes PTAL, i have made the requested changes.

**Review by adhiamboperes — APPROVED** [review]
Thanks @manas-yu! This look s great. If the CI passes it should be ready to merge.
