### PR TITLE
Fix #5195: Fix RestrictedApi Errors

### LINKED ISSUE #5195: InvalidPackage + NewApi +  FragmentLiveDataObserve + RestrictedApi
## Description
We would like to fix all the remaining lint issues on Oppia Android. There are currently 195 errors and 1009 warnings. Also, 38 checks are currently disabled.

This issue tracks fixing all "InvalidPackage + NewApi + FragmentLiveDataObserve + RestrictedApi"

## Steps To Reproduce
Run the following command from a terminal in a checked-out Oppia Android repo:

./gradlew :app:lint

## Expected Behavior
Running the command above should not show any errors in this category

### PR DESCRIPTION
**Pull request by XichengSpencer**
## Explanation

Fixes #5195 In the Android/Lint errors, all I can see are just NewApi Errors, which related methods are only available on API 26 and our current min API is 19. 
Correct me if I am wrong, as discussed with Ben in a meeting, most errors test-related file can be fixed by adding require api annotation, and for all the changed files I think they are test related so I added annotation. I did some investigation java.util.Time replacement method and it requires to install third-party dependency, which I think adds too much complexity so I proceed with the annotation way. And for the color matcher one, I cannot find the replacement method.

## Essential Checklist

- [z] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- For PRs introducing new UI elements or color changes, both light and dark mode screenshots must be included
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

Screenshot 2024-02-21 092439

### CODE REVIEW

File: testing/src/main/java/org/oppia/android/testing/junit/OppiaParameterizedTestRunner.kt [hunk 1]
```diff
@@ -85,16 +88,24 @@ class OppiaParameterizedTestRunner(private val testClass: Class<*>) : Suite(test
...
+          methodName,
+          iterationName
         )
       }
     } + ProxyParameterizedTestRunner(
-      selectedRunnerClass, testClass, parameterizedMethods, methodName = null
+      selectedRunnerClass,
+      testClass,
+      parameterizedMethods,
+      methodName = null
```
Comment (adhiamboperes) [inline testing/src/main/java/org/oppia/android/testing/junit/OppiaParameterizedTestRunner.kt]: Revert this formatting only change.

File: testing/src/main/java/org/oppia/android/testing/junit/OppiaParameterizedTestRunner.kt [hunk 2]
```diff
@@ -300,7 +316,10 @@ class OppiaParameterizedTestRunner(private val testClass: Class<*>) : Suite(test
     private fun constructDelegate(): Any {
       val constructor =
         runnerClass.getConstructor(
-          Class::class.java, Map::class.java, String::class.java, String::class.java
+          Class::class.java,
+          Map::class.java,
+          String::class.java,
+          String::class.java
```
Comment (adhiamboperes) [inline testing/src/main/java/org/oppia/android/testing/junit/OppiaParameterizedTestRunner.kt]: Revert this formatting only change.

File: testing/src/main/java/org/oppia/android/testing/junit/OppiaParameterizedTestRunner.kt [hunk 3]
```diff
@@ -239,15 +253,17 @@ class OppiaParameterizedTestRunner(private val testClass: Class<*>) : Suite(test
...
 
   /**
    * Specifies that a method in a test that uses a [OppiaParameterizedTestRunner] runner should be
    * run multiple times for each [Iteration] specified in the [value] iterations list.
    *
    * See the KDoc for the runner for example code.
    */
-  @Target(AnnotationTarget.FUNCTION) annotation class RunParameterized(vararg val value: Iteration)
+  @Target(AnnotationTarget.FUNCTION)
+  annotation class RunParameterized(vararg val value: Iteration)
```
Comment (adhiamboperes) [inline testing/src/main/java/org/oppia/android/testing/junit/OppiaParameterizedTestRunner.kt]: Revert these formatting only changes.

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @XichengSpencer! Please revert the unneeded changes an re-assign.

**Comment by adhiamboperes** [comment]
@XichengSpencer, please reassign if this is ready for a review.

**Review by adhiamboperes — APPROVED** [review]
Thanks @XichengSpencer! This LGTM.
