### PR TITLE
Fix #5112: Rendering Inline SVGs

### LINKED ISSUE #5112: [BUG]: The Meaning of “Equal Parts” under Fractions
### Describe the bug

I got stuck because of this mistake - "and ___ of it gets eaten". This happened while playing the lesson: The Meaning of “Equal Parts” under Fractions.

There's no image and the fraction is missing. I have attached a screenshot of this card.

### Steps To Reproduce

1. Go to the Topic page for Fractions 
2. Click on “The Meaning of Equal Parts”
3. This is the 13th card (if you get all answers correctly).
4. 

### Expected Behavior

I expect to see the fraction being referred to in the card to enable me solve the problem. 

### Screenshots/Videos

IMG_0705

### What device/emulator are you using?

Samsung A13

### Which Android version is your device/emulator running?

_No response_

### Which version of the Oppia Android app are you using?

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by adhiamboperes**
## Explanation
Fixes #5112 

We discovered that `mathImg_` dimesions are in **ex**, and not **px**, and this unit is not natively rendered on android.  

This PR introduces a method that will convert ex to px and use the resulting dimesions to compute the rendering size of a math image to be rendered inline. The formula is based on the [androidSvg library](https://github.com/oppia/androidsvg/blob/5bc9c7553e94c3476e8ea32baea3c77567228fcd/androidsvg/src/main/java/com/caverock/androidsvg/androidrendering/SVGAndroidRenderer.java#L5018) that is also based on CSS3 specs.

To preserve the size computation of block SVGs, we have created a seperate method that handles the calculation of rendering dimensions for inline SVGs.

We have only tested these changes through visual observation, and confirming that the images scale correctly when reading text size is changed.

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only
|Before|After|
|--|--|
|IMG_0705|Screenshot_1698283405|
|Screenshot_1698284125|Screenshot_1698283411|
|Screenshot_1697714168|Screenshot_1698284519|
|Screenshot_1697745323|Screenshot_1698284666|
|Screenshot_1697714820|Screenshot_1698284933|

Images scaled to Largest text and display size, and dark mode
||||
|--|--|--|
|image|image|image|
|image|image|image|

### CODE REVIEW

File: WORKSPACE [hunk 1]
```diff
@@ -125,7 +125,7 @@ git_repository(
 # to correctly size in-line SVGs (such as those needed for LaTeX-based math expressions).
 git_repository(
     name = "androidsvg",
-    commit = "1265eb1087056cf3fc2e10442e5545bc65c109ce",
+    commit = "5bc9c7553e94c3476e8ea32baea3c77567228fcd",
```
Comment (BenHenning) [inline WORKSPACE:128]: Ah, we didn't ever update this for the release?

File: WORKSPACE [hunk 2]
```diff
@@ -125,7 +125,7 @@ git_repository(
...
     remote = "https://github.com/oppia/androidsvg",
     shallow_since = "1686302944 -0700",
```
Comment (BenHenning) [inline WORKSPACE]: Please update this, too (per the warning that should show up when building //:oppia_dev).

File: utility/src/main/java/org/oppia/android/util/parser/svg/SvgPictureDrawable.kt [hunk 3]
```diff
@@ -100,11 +100,17 @@ abstract class SvgPictureDrawable(
...
    */
   protected fun reinitialize(textPaint: TextPaint?) {
-    picture = textPaint?.let {
-      scalableVectorGraphic.renderToTextPicture(it)
-    } ?: scalableVectorGraphic.renderToBlockPicture()
+    val newPicture = if (textPaint != null) {
+      intrinsicSize = scalableVectorGraphic.computeSizeSpecsForTextPicture(textPaint)
+      scalableVectorGraphic.renderToTextPicture(textPaint)
+    } else {
+      intrinsicSize = scalableVectorGraphic.computeSizeSpecs(null)
```
Comment (BenHenning) [inline utility/src/main/java/org/oppia/android/util/parser/svg/SvgPictureDrawable.kt]: Does computeSizeSpecs still need to include this argument if it's not ever passed anymore?

Alternatively, might it be possible to consolidate the changes in the new function to be part of computeSizeSpecs? It would simplify this code (it wouldn't need to change) while also making computeSizeSpecs correct for the case when textPaint is provided.

**Review by BenHenning — COMMENTED** [review]
Thanks @adhiamboperes! Left a couple thoughts--PTAL.

File: utility/src/main/java/org/oppia/android/util/parser/svg/SvgPictureDrawable.kt (hunk 3 above)
Comment (adhiamboperes) [reply utility/src/main/java/org/oppia/android/util/parser/svg/SvgPictureDrawable.kt]: The new function is necessary because the alternative looks like this: 
```
 return if (textPaint != null) SvgSizeSpecs(
      adjustedWidth,
      adjustedHeight,
      renderedWidth = adjustedWidth,
      renderedHeight = adjustedHeight,
      verticalAlignment
    ) else SvgSizeSpecs(
      intrinsicWidth,
      intrinsicHeight,
      renderedWidth = imageFileNameWidth ?: intrinsicWidth,
      renderedHeight = imageFileNameHeight ?: intrinsicHeight,
      verticalAlignment = 0f
    )
```

Besides, there are addtional computations in `computeSizeSpecsForTextPicture` that would increase the size of the `computeSizeSpecs` function.

File: WORKSPACE (hunk 1 above)
Comment (adhiamboperes) [reply WORKSPACE:128]: No we didn't.

File: utility/src/main/java/org/oppia/android/util/parser/svg/SvgPictureDrawable.kt (hunk 3 above)
Comment (adhiamboperes) [reply utility/src/main/java/org/oppia/android/util/parser/svg/SvgPictureDrawable.kt]: I've removed the textPaint argument from computeSizeSpecs so it is not called where textpaint needs to be passed. I have also updated the KDocs.

File: WORKSPACE (hunk 2 above)
Comment (adhiamboperes) [reply WORKSPACE]: Done

**Review by BenHenning — APPROVED** [review]
Thanks @adhiamboperes. The latest changes LGTM!
