### PR TITLE
Fix #2637: [A11y] Marquee Toolbar Fix for Revision Card and Story Activity

### LINKED ISSUE #2637: [A11y] Revision Card
## Current Output
https://user-images.githubusercontent.com/9396084/107035557-587e3980-67de-11eb-92de-57b503f78d18.mp4

## Issues Identified
- [x] The talkback reads this screen as **Oppia** at start, instead it should be **Skill page**. Also please add test for the same. (Assigned to @jonathanalvares9009)
- [ ] After back arrow, overflow menu is selected and "What is a Fraction?" is never selected. Order should be: back-arrow, "Title" and overflow menu. (Assigned to @rt4914)

Note: To understand the above issue(s) completely, it is recommended that you setup Talkback and play with the app keeping it on and that will give you better context.

**Accessibility Guide**: https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide

### PR DESCRIPTION
**Pull request by rt4914**
## Explanation

Fix #2637: [A11y] Marquee Toolbar Fix for Revision Card and Story Activity

Before video is available in issue.

NOTE: The `Story Toolbar` issue has not been filed anywhere because currently we do not have a story name which goes out of toolbar size but considering that the implementation is exactly same as `Revision Card` I have fixed it for `Story Activity` too.

## After Video

https://user-images.githubusercontent.com/9396084/119278368-6c8d6000-bc42-11eb-9c53-da97fae7caf1.mp4

https://user-images.githubusercontent.com/9396084/119278373-73b46e00-bc42-11eb-9893-1b2f83fe66ea.mp4

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

File: app/src/main/java/org/oppia/android/app/story/StoryFragmentPresenter.kt [hunk 1]
```diff
@@ -76,7 +76,7 @@ class StoryFragmentPresenter @Inject constructor(
       (activity as StoryActivity).finish()
     }
 
-    binding.storyToolbar.setOnClickListener {
+    binding.storyToolbarTitle.setOnClickListener {
```
Comment (anandwana001) [inline app/src/main/java/org/oppia/android/app/story/StoryFragmentPresenter.kt:79]: any test case to update for this?

**Review by anandwana001 — APPROVED** [review]

File: app/src/main/java/org/oppia/android/app/story/StoryFragmentPresenter.kt (hunk 1 above)
Comment (rt4914) [reply app/src/main/java/org/oppia/android/app/story/StoryFragmentPresenter.kt:79]: No.
Screenshot 2021-05-24 at 4 14 29 AM
