### PR TITLE
Fix #171: Introduce support for diffing subsets of data in generic RecyclerView adapter

### LINKED ISSUE #171: Introduce support for diffing subsets of data in generic RecyclerView adapter
The initial implementation of the generic RecyclerView BindableAdapter notifies that the whole data set is changed for each re-bind, which is sometimes wrong (the data may be the same) and highly inefficient (1 element might have changed out of hundreds). Diffing logic should be introduced to only notify that a subset of the data has changed, which also enables support for RecyclerView animations.

Later update for much more context on approaching this issue:

We've tried two attempts at fixing this:
- #1359 that was actually merged, but then reverted in #1627 due to causing #1625 and #1626. As far as I know, we never looked into the specifics of what caused the performance issues here but I have some suspicions (see below)
- #2666 there were a bunch of test failures that weren't fixed, and more manual testing was needed. It also wasn't quite implemented correctly as we want to use more granular controls than just ``notifyDataSetChanged``.

To illustrate the current state and desired outcome (for added context):
- Today, ``BindableAdapter`` has a single ``setData`` method that replaces the entire list of data: https://github.com/oppia/oppia-android/blob/4f5aec630c8b4826cd94fe63bc2ab99f0cb35ad7/app/src/main/java/org/oppia/android/app/recyclerview/BindableAdapter.kt#L42-L48 This is actually very convenient because it ties directly into databinding. However, it is very inefficient: calling [``notifyDataSetChanged``](https://developer.android.com/reference/androidx/recyclerview/widget/RecyclerView.Adapter#notifyDataSetChanged()) which is a bit of a sledgehammer solution since it basically forces the recycler view to reset its views (which causes issues like #4839 plus other annoyances like view flashing and prevents clean automatic built-in recycler view animations).
- Ideally, we would actually use the more granular adapter functions for notifying changes: ``notifyItemChanged``, ``notifyItemInserted``, and ``notifyItemRemoved`` (possibly also ``notifyItemRangeChanged``, ``notifyItemRangeInserted``, and ``notifyItemRangeRemoved`` though these are less important and probably harder to do) so that ``RecyclerView`` knows how to manage incoming data changes correctly.
- Since we can't easily add new ``set*()`` methods in ``BindableAdapter`` for this purpose, we need to rely on diffing to understand the difference between the current set of data bound to the recycler view and the new list that's incoming. ``DiffUtil`` performs this computation. It has a benchmark listed that we could try to beat, but I'm not sure that it's necessary. I think we should try to use ``DiffUtil`` first, but correctly.
- #1359 attempted to use ``DiffUtil`` by directly comparing bound elements rather than doing anything specific to the data itself. The hope was that this would be a reasonable stop-gap. It turns out it wasn't and led to worse performance issues.
- I strongly suspect that #170 will be a prerequisite here. The idea of introducing [stable IDs](https://developer.android.com/reference/androidx/recyclerview/widget/RecyclerView.Adapter#hasStableIds()) is technically more for the purpose of animating, but I think it also adds internal performance benefits for recycler view. More to the point: stable IDs makes it much easier for us to perform correct diffing when implementing ``DiffUtil.Callback``. I suspect that #1359 had performance issues because it was causing ``areContentsTheSame`` to be called far too often, and in a way that probably has roughly O(n^2) complexity.

Introducing the necessary functionality for a correct ``DiffUtil.Callback`` requires establishing a strict API requirement for data bound to ``BindableAdapter``. I think that's fine, but it will involve a potentially large scale refactor in the codebase (and isn't easy to stage). That would require changing ``BindableAdapter`` to extend a new ``BindableItemViewModel`` class instead of ``Any``, and updating all uses of ``BindableAdapter`` in the codebase to adhere to this new class (which is hopefully as simple as implementing the interface in a bunch of new places). I think this interface could look like the following (as a concept):

```kotlin
/** Represents a single item in a bindable recycler view. */
interface BindableItemViewModel<T: BindableItemViewModel<T>> {
  /**
   * The unique content ID for this item. Note that content IDs are expected to be unique
   * even for view models of the same type, and should never be reused for a new view model.
   * Note that objects used as IDs must be able to be checked correctly for equivalence using
   * ``equals``.
   */
  val contentId: Any

  /**
   * Returns whether the [other] version of this view model has different contents to this version of it. This is used for data diffing analysis and should only compare fields that are relevant to rendering the view model.
   *
   * Note that data subclasses can probably just use an equals check for this so long as all of their contents are also data classes or have correct equals overrides (and it makes sense to check all fields).
   */
  fun hasChanges(other: T): Boolean
}
```

We could, alternatively, update ``BindableAdapter``'s builders to provide per-item ID and comparison methods (similar to what we do today for typing), but that seems a bit unwieldy. It may also be worth considering refactoring those builders to move the type information here, but I don't know how involved that will be since the single vs. multi typing is fairly complex in the adapter.

If we implemented the above, the ``DiffUtil.Callback`` becomes relatively trivial:

```kotlin
class BindableAdapterDiffUtilHandler<T: BindableItemViewModel>(
  private val oldList: List<T>,
  private val newList: List<T>
): DiffUtil.Callback {
  override fun getOldListSize() = oldList.size
  override fun getNewListSize() = newList.size
  override fun areItemsTheSame(oldItemPosition: Int, newItemPosition: Int) =
    oldList[oldItemPosition].contentId == newList[newItemPosition].contentId
  override fun areContentsTheSame(oldItemPosition: Int, newItemPosition: Int) =
    oldList[oldItemPosition].hasChanges(newList[newItemPosition])
}
```

This could even be extended in the future to introduce sub-item diffing (e.g. for item animation) by extending the contract of ``hasChanges`` to perform a sub-item diff and then hooking it up to ``getChangePayload`` in the custom diff util callback above. I didn't include that here because of it being unclear how to generalize the item animation side of it (even we would even want to do that).

Now the main part comes: how do we implement unique content IDs and ``hasChanges`` across all of the possible view models? Well:
- ``hasChanges`` is actually straightforward. We only need to cross-compare fields that are directly relevant to internal state and/or aspects of the view model that are displayed. This is likely most or all of the data in the view model (though injectable objects should be ignored). This should never be a direct equals check except for specific kinds of data classes.
- I suspect we will need to introduce custom ID classes on a per recycler view basis--see my example below.

An example of an adapter instance-specific ID would be as follows for the exploration player (not complete, just a basic example):

```kotlin
sealed class StateItemId {
  data class Content(val contentId: String): StateItemId()
  data class Feedback(val feedbackId: String): StateItemId()
  object PreviousNavigationButton: StateItemId() // Only one of these can ever exist.
  ... // See StateItemViewModel.ViewType for other types.
}
```

(Note that subclasses are data classes and are able to be checked for equivalence).

(Note for refactoring: if we represented this sealed class as a proto ``oneof`` then we could use the corresponding proto enum generated to also replace ``StateItemViewModel.ViewType`` which would probably be a nice way to combine the two concepts together).

Finally, I want to note a few things on approaching this project:
1. We should establish the high-level patterns of the mechanisms needed _and_ implement them in a very simple adapter case in the same PR to demonstrate it working. One way to do this would be updating ``BindableAdapter`` to have a temporary new ``setData`` method that checks the actual data types for subclassing ``BindableItemViewModel`` without updating the adapter's generic type. This allows us to introduce a small runtime cost to demonstrate that the functionality works with a single adapter without needing to implement it everywhere.
2. We should ensure that the new diffing functionality is gated by a feature flag so that if it causes performance or stability regressions that these aren't seen by users until we have time to test it thoroughly.
3. We should implement support for all other adapters one-by-one (which will likely be multiple PRs since some of the adapter uses are fairly complex).
4. Once all adapters are updated to use the new view model, then we can remove the temporary function and ``setData`` method.
5. We need to manually test with the feature on to make sure it works well. After manual testing, we may do additional testing through our alpha release channel if it's warranted (but, in the least, we'll also do additional QA testing since it's likely this will cause unforeseen issues particularly in the exploration player).
6. We need to think through automated testing and ensure that it's done well both for the new adapter support (i.e. that diffing correctly notifies on a per-item basis as we expect--note that this is essentially testing ``DiffUtil`` but that's ideal since if the utility isn't doing what we want, we'll need to introduce our own diffing logic) and for each view model that uses it. The latter is actually much more complex as this new logic may be able to result in item updates being ignored. This probably involves auditing existing tests for each adapter use case to ensure that the tests correctly verify scenarios where the corresponding recycler view's data changes in a way that would trigger each of the different diff util scenarios we care about (specifically item added, item removed, and item changed).

### PR DESCRIPTION
**Pull request by anandwana001**
## Explanation

Fix #171 
Introduced a diffing logic using `DiffUtil`. 
Added test cases which passed with `diffutil` implementation. 

### How to test
Check all possible screens where RecyclerView is used. 

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

File: app/src/main/java/org/oppia/app/recyclerview/RecyclerDataDiffCallback.kt [hunk 1]
```diff
@@ -0,0 +1,16 @@
...
+
+class RecyclerDataDiffCallback<T> : DiffUtil.ItemCallback<T>() {
+
+  override fun areItemsTheSame(oldItem: T, newItem: T): Boolean {
+    return oldItem == newItem
+  }
+
+  @SuppressLint("DiffUtilEquals")
+  override fun areContentsTheSame(oldItem: T, newItem: T): Boolean {
+    return oldItem == newItem
```
Comment (aggarwalpulkit596) [inline app/src/main/java/org/oppia/app/recyclerview/RecyclerDataDiffCallback.kt]:
```suggestion
    return oldItem.sameAndEqual(newItem)
```
with the help of extension function
```
inline fun <T : Any, K : Any> T.sameAndEqual(n: K): Boolean = ((this.javaClass == n.javaClass) && (this == n))
```

Comment (aggarwalpulkit596) [reply app/src/main/java/org/oppia/app/recyclerview/RecyclerDataDiffCallback.kt]: @BenHenning adding to conversation for suggestion

**Comment by BenHenning** [comment]
Aha, this is very interesting. :) I want to take a closer look at this, but I probably won't be able to until early next week.

In the meantime, @anandwana001 could you add tests for the diffing logic? I think we should try to encapsulate what the desired API of the adapter is via tests, even if we choose a different implementation.

**Comment by anandwana001** [comment]
Sure

File: app/src/main/java/org/oppia/app/recyclerview/RecyclerDataDiffCallback.kt (hunk 1 above)
Comment (BenHenning) [reply app/src/main/java/org/oppia/app/recyclerview/RecyclerDataDiffCallback.kt]: Wouldn't standard equality be sufficient? It would also provide nullness checking, wouldn't it?

File: app/src/main/java/org/oppia/app/recyclerview/RecyclerDataDiffCallback.kt [hunk 2]
```diff
@@ -0,0 +1,23 @@
+package org.oppia.app.recyclerview
+
+import androidx.recyclerview.widget.DiffUtil
+
+class RecyclerDataDiffCallback<T>(var oldList: List<T>, var newList: List<T>) :
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/app/recyclerview/RecyclerDataDiffCallback.kt]: Could we make the adapter itself be a ``DiffUtil.Callback``?

File: app/src/main/java/org/oppia/app/recyclerview/RecyclerDataDiffCallback.kt [hunk 3]
```diff
@@ -0,0 +1,23 @@
...
+  DiffUtil.Callback() {
+
+  override fun areItemsTheSame(oldItemPosition: Int, newItemPosition: Int): Boolean {
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/app/recyclerview/RecyclerDataDiffCallback.kt:10]: Could we check the item types here instead of contents? We don't have another way to quickly check equivalence, but as I understand it we want areItemsTheSame() to be fast, whereas areContentsTheSame can be a bit more expensive.

File: app/src/main/java/org/oppia/app/recyclerview/BindableAdapter.kt [hunk 4]
```diff
@@ -32,17 +33,17 @@ class BindableAdapter<T : Any> internal constructor(
   private val viewHolderFactoryMap: Map<Int, ViewHolderFactory<T>>,
   private val dataClassType: KClass<T>
 ) : RecyclerView.Adapter<BindableAdapter.BindableViewHolder<T>>() {
-  private val dataList: MutableList<T> = ArrayList()
+  private var dataList: MutableList<T> = ArrayList()
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/app/recyclerview/BindableAdapter.kt]: Could we do a shallow copy of the list & diff that, instead? Prefer minimizing mutability.

File: app/src/main/java/org/oppia/app/recyclerview/BindableAdapter.kt [hunk 5]
```diff
@@ -64,7 +65,7 @@ class BindableAdapter<T : Any> internal constructor(
           "expected adapter class type: $dataClassType."
       }
     }
-    @Suppress("UNCHECKED_CAST") // This is safe. See the above check.
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/app/recyclerview/BindableAdapter.kt]: Why remove this comment?

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @anandwana001! This looks really good. Left a few comments, otherwise waiting for tests.

**Comment by anandwana001** [comment]
> Thanks @anandwana001! This looks really good. Left a few comments, otherwise waiting for tests.

Could you give some hints, like what all cases we can cover with test?

File: app/src/main/java/org/oppia/app/recyclerview/RecyclerDataDiffCallback.kt (hunk 3 above)
Comment (anandwana001) [reply app/src/main/java/org/oppia/app/recyclerview/RecyclerDataDiffCallback.kt:10]: Ok, `areContentTheSame` only called for those items whose `areItemsTheSame` gives true.

File: app/src/main/java/org/oppia/app/recyclerview/RecyclerDataDiffCallback.kt (hunk 2 above)
Comment (anandwana001) [reply app/src/main/java/org/oppia/app/recyclerview/RecyclerDataDiffCallback.kt]: Kotlin doesn't support multiple inheritances that's why I created a separate file, also we can use this `RecyclerDataDiffCallback` as an inner class to our adapter until we have only one adapter in our whole codebase. In future, if we grow to 2 or more adapters we might need `RecyclerDataDiffCallback` for all the adapters.

File: app/src/main/java/org/oppia/app/recyclerview/BindableAdapter.kt (hunk 5 above)
Comment (anandwana001) [reply app/src/main/java/org/oppia/app/recyclerview/BindableAdapter.kt]: Oh, this is my mistake. Will put it again in next commit.

File: app/src/main/java/org/oppia/app/recyclerview/RecyclerDataDiffCallback.kt (hunk 3 above)
Comment (anandwana001) [reply app/src/main/java/org/oppia/app/recyclerview/RecyclerDataDiffCallback.kt:10]: **Could we check the item types here instead of contents?** This is amazing.

File: app/src/main/java/org/oppia/app/recyclerview/BindableAdapter.kt [hunk 6]
```diff
@@ -33,17 +33,19 @@ class BindableAdapter<T : Any> internal constructor(
...
 
   // TODO(#170): Introduce support for stable IDs.
 
   /** Sets the data of this adapter. This is expected to be called by Android via data-binding. */
   private fun setData(newDataList: List<T>) {
-    val result = DiffUtil.calculateDiff(RecyclerDataDiffCallback(dataList, newDataList), false)
-    dataList = newDataList.toMutableList()
+    val result = DiffUtil.calculateDiff(
+      RecyclerDataDiffCallback(dataList, newDataList),
+      false
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/app/recyclerview/BindableAdapter.kt]: Please add an argument comment for this value (e.g. ``/* paramName= */ false``) to help provide context for readers.

File: app/src/main/java/org/oppia/app/recyclerview/RecyclerDataDiffCallback.kt (hunk 3 above)
Comment (BenHenning) [reply app/src/main/java/org/oppia/app/recyclerview/RecyclerDataDiffCallback.kt:10]: Great, if this works it should provide a small performance improvement. Longer-term we should utilize stable IDs for this purpose (e.g. as part of #170), but this should work in the interim.

Small formatting suggestion:

```kotlin
return oldList[oldItemPosition]::class == newList[newItemPosition]::class
```

File: app/src/sharedTest/java/org/oppia/app/recyclerview/BindableAdapterTest.kt [hunk 7]
```diff
@@ -199,16 +215,83 @@ class BindableAdapterTest {
...
+        )
+      ).check(matches(withSubstring(INT_VALUE_1.intValue.toString())))
     }
   }
 
+  @Test
+  fun testRecyclerDataDiffCallback_getOldListSize_correctListSize() {
+    val oldList = listOf(STR_VALUE_1, STR_VALUE_0, STR_VALUE_2).toMutableList()
+    val newList = listOf(STR_VALUE_1, STR_VALUE_0).toMutableList()
+    val diffObj = RecyclerDataDiffCallback(oldList, newList)
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/app/recyclerview/BindableAdapterTest.kt]: When testing the new behaviors that DiffUtil introduces for the adapter, we shouldn't be testing diff util itself (it's actually an implementation detail). Can you update these tests to test the new behaviors that become available but only by interacting with BindableAdapter? Consider that in the future we could switch out our implementation away from DiffUtil to something else entirely. These tests ought to still pass with the new implementation without requiring changes if they are properly testing the public API of the system under test and not its implementation.

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @anandwana001! Left some more comments, mostly regarding the new tests.

File: app/src/main/java/org/oppia/app/recyclerview/RecyclerDataDiffCallback.kt (hunk 2 above)
Comment (anandwana001) [reply app/src/main/java/org/oppia/app/recyclerview/RecyclerDataDiffCallback.kt]: Resolving this on behalf of ben

File: app/src/main/java/org/oppia/app/recyclerview/BindableAdapter.kt (hunk 4 above)
Comment (anandwana001) [reply app/src/main/java/org/oppia/app/recyclerview/BindableAdapter.kt]: Resolving this on behalf of ben

File: app/src/main/java/org/oppia/app/recyclerview/BindableAdapter.kt (hunk 5 above)
Comment (anandwana001) [reply app/src/main/java/org/oppia/app/recyclerview/BindableAdapter.kt]: Resolving this on behalf of ben

File: app/src/sharedTest/java/org/oppia/app/recyclerview/BindableAdapterTest.kt (hunk 7 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/app/recyclerview/BindableAdapterTest.kt]: I added test cases for testing `diffUtil` itself because I am comparing class types here and this is our side implementation which is different from the original behaviour of `diffUtil` itself. Though, I should add some test cases only by interacting with BindableAdapter.

File: app/src/main/java/org/oppia/app/recyclerview/BindableAdapter.kt (hunk 6 above)
Comment (anandwana001) [reply app/src/main/java/org/oppia/app/recyclerview/BindableAdapter.kt]: Done

File: app/src/main/java/org/oppia/app/recyclerview/RecyclerDataDiffCallback.kt (hunk 3 above)
Comment (anandwana001) [reply app/src/main/java/org/oppia/app/recyclerview/RecyclerDataDiffCallback.kt:10]: Done

File: app/src/sharedTest/java/org/oppia/app/recyclerview/BindableAdapterTest.kt (hunk 7 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/app/recyclerview/BindableAdapterTest.kt]: Added a test case, which checks the BindableAdapter weather the list updated with the new data or not. 
As per the future point you said, with this test case no matter whatever the implementation/logic which use to update the list, this test case will tell us the data is going to update or not.

File: app/src/main/java/org/oppia/app/recyclerview/BindableAdapter.kt [hunk 8]
```diff
@@ -41,13 +42,16 @@ class BindableAdapter<T : Any> internal constructor(
   private fun setData(newDataList: List<T>) {
     val result = DiffUtil.calculateDiff(
       RecyclerDataDiffCallback(dataList, newDataList),
-      false
+      /* detectMoves*/ false
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/app/recyclerview/BindableAdapter.kt]: For formatted argument comments, follow:

```kotlin
/* detectMoves= */
```

File: app/src/sharedTest/java/org/oppia/app/recyclerview/BindableAdapterTest.kt [hunk 9]
```diff
@@ -381,28 +399,20 @@ class BindableAdapterTest {
     textView.text = "Value: " + data.intValue
   }
 
-  private fun getRecyclerViewListLiveData(
-    activity: BindableAdapterTestActivity
-  ): MutableLiveData<List<TestModel>> {
+  private fun getRecyclerViewListLiveData(activity: BindableAdapterTestActivity): MutableLiveData<List<TestModel>> { // ktlint-disable max-line-length
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/app/recyclerview/BindableAdapterTest.kt]: Why not keep this method wrapped? We should only disable the line length check in exceptional cases (e.g. when we can't wrap/shorten something), and in this case it seems like we can properly avoid the situation just by wrapping the method declarations.

File: app/src/main/java/org/oppia/app/recyclerview/BindableAdapter.kt [hunk 10]
```diff
@@ -41,13 +42,16 @@ class BindableAdapter<T : Any> internal constructor(
...
     )
     dataList.clear()
     dataList += newDataList.toMutableList()
     result.dispatchUpdatesTo(this)
   }
 
+  @VisibleForTesting(otherwise = VisibleForTesting.NONE)
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/app/recyclerview/BindableAdapter.kt]: Prefer not exposing a public API for the purposes of testing. Could we instead bind a test recycler view using the adapter & verify that the expected elements are bound by using Espresso matchers?

File: app/src/sharedTest/java/org/oppia/app/recyclerview/BindableAdapterTest.kt [hunk 11]
```diff
@@ -307,6 +307,24 @@ class BindableAdapterTest {
     assertThat(diffObj.areContentsTheSame(0, 0)).isEqualTo(false)
   }
 
+  @Test
+  fun testBindableAdapter_incomingNewData_correctUpdateListLogic() {
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/app/recyclerview/BindableAdapterTest.kt]: I'm not quite sure what this is testing that other existing tests don't already cover.

I think that what we want here are tests that only fail if we remove the DiffUtils part of the implementation. Can we somehow listen for changes to the recycler view itself and observe that the implementation is more optimal than "replace everything for each element change"? Those are the kinds of tests that I'm expecting.

File: app/src/sharedTest/java/org/oppia/app/recyclerview/BindableAdapterTest.kt (hunk 7 above)
Comment (BenHenning) [reply app/src/sharedTest/java/org/oppia/app/recyclerview/BindableAdapterTest.kt]: I left another comment in this review pass, but what I think we want are converting the tests you wrote earlier to be based on the actual recycler view object rather than testing the data diff callback. Is it possible for us to observe update notifications to the recycler view & assert based on those?

**Review by BenHenning — COMMENTED** [review]
Thanks @anandwana001 --I took another pass on this.

File: app/src/sharedTest/java/org/oppia/app/recyclerview/BindableAdapterTest.kt (hunk 9 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/app/recyclerview/BindableAdapterTest.kt]: Yes, I am thinking to fix such issues in files related to this pr in the last commit before meger, after final approval.

**Comment by anandwana001** [comment]
@BenHenning @rt4914 Added one test where I am checking if reminding is happening or not if in future we move to their implementation this test will fail as DiffUtil support no binding of the same data. 
I should look into other approaches like inserting, deleting or moving of items in the list. 
If you could add some feedback on this commit, this will help me in the other approaches for inserting, deleting or moving of items in the list.

**Comment by rt4914** [comment]
> @BenHenning @rt4914 Added one test where I am checking if reminding is happening or not if in future we move to their implementation this test will fail as DiffUtil support no binding of the same data.
> I should look into other approaches like inserting, deleting or moving of items in the list.
> If you could add some feedback on this commit, this will help me in the other approaches for inserting, deleting or moving of items in the list.

@anandwana001 Actually I will defer with Ben on the test case approach because I am not confident about the correct approach in this case.

**Comment by BenHenning** [comment]
Apologies for the delay, but I will need to take a pass on this PR tomorrow. I ran out of time to do so today.

File: app/src/sharedTest/java/org/oppia/app/recyclerview/BindableAdapterTest.kt [hunk 12]
```diff
@@ -251,6 +251,62 @@ class BindableAdapterTest {
     }
   }
 
+  @Test
+  fun testBindableAdapter_incomingSameData_noRebindingShouldHappen() {
+
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/app/recyclerview/BindableAdapterTest.kt]: Nit: remove empty line for consistency with other tests.

File: app/src/sharedTest/java/org/oppia/app/recyclerview/BindableAdapterTest.kt [hunk 13]
```diff
@@ -251,6 +251,62 @@ class BindableAdapterTest {
     }
   }
 
+  @Test
+  fun testBindableAdapter_incomingSameData_noRebindingShouldHappen() {
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/app/recyclerview/BindableAdapterTest.kt:259]: This test is definitely on the right track, but it only tests a single behavior (when setting the same data, no rebinding happens). It's also useful to test the other benefits that we get from the diff, such as:
- Inserting a new item triggers an insertion rather than rebinding the whole list
- Removing an item just changes that one item
- Moving an item has two simple operations instead of recreating the whole list
- Change the content of an item but not the item's identifier causes just that item to specify that it's changed

Can you add tests for each of these? Consider how to reuse the existing functionality in this test via helpers to keep the tests narrowly focused on illustrating the behavior being tested.

File: app/src/sharedTest/java/org/oppia/app/recyclerview/BindableAdapterTest.kt [hunk 14]
```diff
@@ -251,6 +251,62 @@ class BindableAdapterTest {
...
+    ActivityScenario.launch(BindableAdapterTestActivity::class.java).use { scenario ->
+
+      scenario.onActivity { activity ->
+        dataObserver = object : RecyclerView.AdapterDataObserver() {
+          override fun onChanged() {
+            doesRebind = true
+          }
+
+          override fun onItemRangeInserted(positionStart: Int, itemCount: Int) {
+            assertThat(positionStart).isEqualTo(0)
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/app/recyclerview/BindableAdapterTest.kt]: Can we extract this state & assert in the test body, instead? Prefer keeping tests with the structure: arrange, act, assert. We can collect data during the 'act' step to use in 'assert', but we should keep these two things separate.

File: app/src/sharedTest/java/org/oppia/app/recyclerview/BindableAdapterTest.kt [hunk 15]
```diff
@@ -251,6 +251,62 @@ class BindableAdapterTest {
...
+    lateinit var dataObserver: RecyclerView.AdapterDataObserver
+    var doesRebind = false
+
+    val oldList = listOf(STR_VALUE_1, STR_VALUE_1, INT_VALUE_1).toMutableList()
+    val newList = listOf(STR_VALUE_1, STR_VALUE_1, INT_VALUE_1).toMutableList()
+
+    ActivityScenario.launch(BindableAdapterTestActivity::class.java).use { scenario ->
+
+      scenario.onActivity { activity ->
+        dataObserver = object : RecyclerView.AdapterDataObserver() {
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/app/recyclerview/BindableAdapterTest.kt]: Consider making this either a fake class or a mock to make it more readily reusable, and easier to verify as correct.

File: app/src/sharedTest/java/org/oppia/app/recyclerview/BindableAdapterTest.kt [hunk 16]
```diff
@@ -251,6 +251,62 @@ class BindableAdapterTest {
...
+          }
+        }
+        adapter.registerAdapterDataObserver(dataObserver)
+      }
+
+      scenario.onActivity { activity ->
+        val liveData = getRecyclerViewListLiveData(activity)
+        liveData.value = oldList
+      }
+      safelyWaitUntilIdle()
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/app/recyclerview/BindableAdapterTest.kt]: Suggest moving this up to onActivity to a helper method to simplfiy this & the next line.

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @anandwana001! The test seems like a great start. I left some comments to help generalize it to multiple behaviors.

File: app/src/sharedTest/java/org/oppia/app/recyclerview/BindableAdapterTest.kt (hunk 12 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/app/recyclerview/BindableAdapterTest.kt]: Done

File: app/src/sharedTest/java/org/oppia/app/recyclerview/BindableAdapterTest.kt (hunk 13 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/app/recyclerview/BindableAdapterTest.kt:259]: Done, 
I added test cases which are passing and failing with and without DiffUtil implementation. 
Only thing I see here is, It is passing on Robolectric only, not espresso.

File: app/src/sharedTest/java/org/oppia/app/recyclerview/BindableAdapterTest.kt (hunk 14 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/app/recyclerview/BindableAdapterTest.kt]: updated test case

File: app/src/sharedTest/java/org/oppia/app/recyclerview/BindableAdapterTest.kt (hunk 15 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/app/recyclerview/BindableAdapterTest.kt]: Using mock now

File: app/src/sharedTest/java/org/oppia/app/recyclerview/BindableAdapterTest.kt [hunk 17]
```diff
@@ -253,56 +257,117 @@ class BindableAdapterTest {
...
+    ActivityScenario.launch(BindableAdapterTestActivity::class.java).use { scenario ->
       scenario.onActivity { activity ->
-        assertThat(doesRebind).isEqualTo(false)
-        adapter.unregisterAdapterDataObserver(dataObserver)
+        adapter.registerAdapterDataObserver(fakeObserver)
+        val liveData = getRecyclerViewListLiveData(activity)
+        liveData.value = oldList
+        val liveDataNew = getRecyclerViewListLiveData(activity)
+        liveDataNew.value = newList
+        verify(fakeObserver, times(1)).onItemRangeChanged(1, 1, null)
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/app/recyclerview/BindableAdapterTest.kt]: Here and elsewhere: please add argument comments with parameter names for the literal value arguments to provide context.

**Review by BenHenning — APPROVED** [review]
Thanks @anandwana001! This looks good to me. Please address my last comment—either @rt4914 or I can verify it’s correct.

File: app/src/sharedTest/java/org/oppia/app/recyclerview/BindableAdapterTest.kt (hunk 7 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/app/recyclerview/BindableAdapterTest.kt]: Done

File: app/src/main/java/org/oppia/app/recyclerview/BindableAdapter.kt (hunk 8 above)
Comment (anandwana001) [reply app/src/main/java/org/oppia/app/recyclerview/BindableAdapter.kt]: Done

File: app/src/main/java/org/oppia/app/recyclerview/BindableAdapter.kt (hunk 10 above)
Comment (anandwana001) [reply app/src/main/java/org/oppia/app/recyclerview/BindableAdapter.kt]: Sure

File: app/src/sharedTest/java/org/oppia/app/recyclerview/BindableAdapterTest.kt (hunk 11 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/app/recyclerview/BindableAdapterTest.kt]: Done

File: app/src/sharedTest/java/org/oppia/app/recyclerview/BindableAdapterTest.kt (hunk 17 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/app/recyclerview/BindableAdapterTest.kt]: Sure, Thanks

File: app/src/main/java/org/oppia/app/recyclerview/RecyclerDataDiffCallback.kt (hunk 1 above)
Comment (rt4914) [reply app/src/main/java/org/oppia/app/recyclerview/RecyclerDataDiffCallback.kt]: Resolving this now. Also considering that this is a minor thing here.

File: app/src/main/java/org/oppia/app/recyclerview/BindableAdapter.kt (hunk 6 above)
Comment (rt4914) [reply app/src/main/java/org/oppia/app/recyclerview/BindableAdapter.kt]: Resolving this now on behalf of @BenHenning

File: app/src/sharedTest/java/org/oppia/app/recyclerview/BindableAdapterTest.kt (hunk 7 above)
Comment (rt4914) [reply app/src/sharedTest/java/org/oppia/app/recyclerview/BindableAdapterTest.kt]: Resolving this now on behalf of @BenHenning

File: app/src/sharedTest/java/org/oppia/app/recyclerview/BindableAdapterTest.kt (hunk 9 above)
Comment (rt4914) [reply app/src/sharedTest/java/org/oppia/app/recyclerview/BindableAdapterTest.kt]: Resolving this now on behalf of @BenHenning

File: app/src/main/java/org/oppia/app/recyclerview/BindableAdapter.kt (hunk 8 above)
Comment (rt4914) [reply app/src/main/java/org/oppia/app/recyclerview/BindableAdapter.kt]: Resolving this now on behalf of @BenHenning

File: app/src/main/java/org/oppia/app/recyclerview/BindableAdapter.kt (hunk 10 above)
Comment (rt4914) [reply app/src/main/java/org/oppia/app/recyclerview/BindableAdapter.kt]: Resolving this now on behalf of @BenHenning

File: app/src/sharedTest/java/org/oppia/app/recyclerview/BindableAdapterTest.kt (hunk 11 above)
Comment (rt4914) [reply app/src/sharedTest/java/org/oppia/app/recyclerview/BindableAdapterTest.kt]: Resolving this now on behalf of @BenHenning

File: app/src/sharedTest/java/org/oppia/app/recyclerview/BindableAdapterTest.kt (hunk 17 above)
Comment (rt4914) [reply app/src/sharedTest/java/org/oppia/app/recyclerview/BindableAdapterTest.kt]: Resolving this on behalf of @BenHenning

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Comment by rt4914** [comment]
This PR also solves #508

**Comment by BenHenning** [comment]
@anandwana001 did you verify that the exploration player & all interactions still work? It seems this caused some regressions: #1625 and #1626.
