### PR TITLE
Fix part of #3602: Added label for MyDownloadsActivity

### LINKED ISSUE #3602: [A11y] Add label for all non-test activities
[A11y] Add label for all non-test activities

[Reference](https://github.com/oppia/oppia-android/pull/3352/files/9c944564734be9aa46bf029cf14e6789ced95a7c#r672844473)

- [x] HomeActivity (Assigned to @vrajdesai78)
- [x] MyDownloadsActivity (Assigned to @bhaktideshmukh) 
- [x] ProfilePictureActivity
- [x] ProfileEditActivity(open)
- [x] SplashActivity (Assigned to @bkaur-bkj )
- [x] WalkthroughActivity (Assigned to @priyatanu)

Example PR: https://github.com/oppia/oppia-android/pull/3227/files

### PR DESCRIPTION
**Pull request by bhaktideshmukh**
## Explanation
Fixes  #3602 : Added label for MyDownloadsActivity

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### CODE REVIEW

**Comment by yash10019coder** [comment]
Hi @bhaktideshmukh if you are aksing for a review for a PR always add then in the assingee section of the PR , this is how we get to know that we have to review a PR thanks and @rt4914 can you please approve the workflow thanks

File: app/src/sharedTest/java/org/oppia/android/app/mydownloads/MyDownloadsActivityTest.kt [hunk 1]
```diff
@@ -0,0 +1,159 @@
...
+  }
+
+  @Inject
+  lateinit var context: Context
+
+  @Test
+  fun testMyDownloadsActivity_hasCorrectActivityLabel() {
+    ActivityScenario.launch(MyDownloadsActivity::class.java).use { scenario ->
+      scenario.onActivity { activity ->
+        Truth.assertThat(activity.title).isEqualTo(
```
Comment (yash10019coder) [inline app/src/sharedTest/java/org/oppia/android/app/mydownloads/MyDownloadsActivityTest.kt]: We can add a import resource profile here for assertThat

**Review by yash10019coder — CHANGES_REQUESTED** [review]
@bhaktideshmukh add Fixes #4103 in the PR description and @rt4914 please approve the workflow thanks.

File: app/src/sharedTest/java/org/oppia/android/app/mydownloads/MyDownloadsActivityTest.kt (hunk 1 above)
Comment (bhaktideshmukh) [reply app/src/sharedTest/java/org/oppia/android/app/mydownloads/MyDownloadsActivityTest.kt]: @yash10019coder Can you please clarify what exactly am I suppose to do regarding adding import?

Comment (rt4914) [reply app/src/sharedTest/java/org/oppia/android/app/mydownloads/MyDownloadsActivityTest.kt]: It should be written as ` assertThat(activity.title).isEqualTo(` instead of ` Truth.assertThat(activity.title).isEqualTo(`

Comment (bhaktideshmukh) [reply app/src/sharedTest/java/org/oppia/android/app/mydownloads/MyDownloadsActivityTest.kt]: @rt4914 Done!

**Comment by bhaktideshmukh** [comment]
PTAL @rt4914 @yash10019coder 
Thanks.

File: app/src/sharedTest/java/org/oppia/android/app/mydownloads/MyDownloadsActivityTest.kt [hunk 2]
```diff
@@ -0,0 +1,159 @@
...
+  application = MyDownloadsActivityTest.TestApplication::class,
+  qualifiers = "port-xxhdpi"
+)
+class MyDownloadsActivityTest {
+
+  @get:Rule
+  val initializeDefaultLocaleRule = InitializeDefaultLocaleRule()
+
+  @get:Rule
+  val accessibilityTestRule = AccessibilityTestRule()
```
Comment (rt4914) [inline app/src/sharedTest/java/org/oppia/android/app/mydownloads/MyDownloadsActivityTest.kt]: Please merge this latest develop as this file does not exist anymore. Instead use `OppiaTestRule` here.

**Review by rt4914 — CHANGES_REQUESTED** [review]
@bhaktideshmukh PTAL thanks.

File: app/src/sharedTest/java/org/oppia/android/app/mydownloads/MyDownloadsActivityTest.kt (hunk 2 above)
Comment (bhaktideshmukh) [reply app/src/sharedTest/java/org/oppia/android/app/mydownloads/MyDownloadsActivityTest.kt]: Done

**Comment by bhaktideshmukh** [comment]
PTAL @rt4914 Thanks.

**Review by yash10019coder — APPROVED** [review]
LGTM @bhaktideshmukh thanks

File: app/src/main/res/values/strings.xml [hunk 3]
```diff
@@ -288,7 +288,7 @@
   <!-- ResetPinDialogFragment -->
   <string name="reset_pin_enter">Enter a New Pin</string>
   <!-- MyDownloadsActivity -->
-  <string name="my_downloads">My Downloads</string>
+  <string name="my_downloads_activity_title">My Downloads</string>
```
Comment (BenHenning) [inline app/src/main/res/values/strings.xml:291]: Can you please also rename the corresponding strings in our translated strings.xml files, too?

File: app/src/sharedTest/java/org/oppia/android/app/mydownloads/MyDownloadsActivityTest.kt [hunk 4]
```diff
@@ -0,0 +1,159 @@
...
+  fun testMyDownloadsActivity_hasCorrectActivityLabel() {
+    ActivityScenario.launch(MyDownloadsActivity::class.java).use { scenario ->
+      scenario.onActivity { activity ->
+        assertThat(activity.title).isEqualTo(
+          context.getString(R.string.my_downloads_activity_title)
+        )
+      }
+    }
+  }
+  @Singleton
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/mydownloads/MyDownloadsActivityTest.kt:112]: Nit: newline above this to separate the class members.

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @bhaktideshmukh! Just had a couple of comments--PTAL.

**Comment by bhaktideshmukh** [comment]
PTAL @BenHenning 
Thanks.

**Review by BenHenning — APPROVED** [review]
Thanks @bhaktideshmukh! LGTM for codeowners.

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.
