### PR TITLE
Fix #3031 : Glide loading small image

### LINKED ISSUE #3031: Glide loading small image
**Describe the bug**
Earlier, we use to load drawable using `setImageResource`. Shifting to Glide, causes a bug of smaller image size in Topic Revision Screen only

**To Reproduce**
1. Click on Fractions card on Home Screen
2. Go to Revision Tab

**Expected behavior**
| Currently | What it should be |
| -- | -- |
|  |  |

Look into `LessonThumbnailImageView` on how to load a drawable. 

https://github.com/oppia/oppia-android/blob/1be8ccde14c25d763c10dd8902ec7f5a2fa6f99e/app/src/main/java/org/oppia/android/app/customview/LessonThumbnailImageView.kt#L86

**Additional context**
The commit which cause this bug - https://github.com/oppia/oppia-android/commit/2bcd5114eb614e06f590ec759fde4b6bf28149ce#diff-a37faf8490754f9ab5367852640b3631eea31a197d74a0d5b8dbc8a0ad5e1c6e

**How to send a Pull Request**
1. Run `TopicRevisionFragmentTest` test on Espresso
2. Add a screenshot in Pull Request description showing all the tests are passing

### PR DESCRIPTION
**Pull request by anandwana001**
## Explanation

Fixes #3031 

TODO
Write test case for scaleType. 
Need to create a custom mather by passing imageView item and test match the scaleType. 

### Screenshot
<p>

</p>

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Review by rt4914 — COMMENTED** [review]
LGTM waiting for test case.

**Comment by anandwana001** [comment]
@rt4914 Added 2 test case, could we have good first issues for this making this as a base PR or do we require all the test in this PR only?

File: app/src/sharedTest/java/org/oppia/android/app/topic/revision/TopicRevisionFragmentTest.kt [hunk 1]
```diff
@@ -236,7 +256,12 @@ class TopicRevisionFragmentTest {
   private fun clickRevisionTab() {
     onView(
       allOf(
-        withText(TopicTab.getTabForPosition(position = 3, enablePracticeTab).name),
+        withText(
+          TopicTab.getTabForPosition(
+            position = 3,
+            enablePracticeTab = enablePracticeTab
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/topic/revision/TopicRevisionFragmentTest.kt:262]: added named argument, without it, it showing red marked error, nothing crashing or stopping app from working, but I think it's good to fix rather than keeping the red mark

File: testing/src/main/java/org/oppia/android/testing/espresso/ImageViewMatcher.kt [hunk 2]
```diff
@@ -0,0 +1,32 @@
+package org.oppia.android.testing.espresso
+
+import android.view.View
+import android.widget.ImageView
+import org.hamcrest.Description
+import org.hamcrest.TypeSafeMatcher
+
+/** A custom class that provides matching for ImageView. */
+class ImageViewMatcher {
```
Comment (anandwana001) [inline testing/src/main/java/org/oppia/android/testing/espresso/ImageViewMatcher.kt:9]: Created a specific matcher file for imageview.

Comment (rt4914) [reply testing/src/main/java/org/oppia/android/testing/espresso/ImageViewMatcher.kt:9]: Ack.

**Review by rt4914 — APPROVED** [review]
LGTM.

Normally we prefer tests in the PR itself but for this PR actually creating good-first-issues is good considering the tests are straightforward and across multiple files.

File: app/src/sharedTest/java/org/oppia/android/app/topic/revision/TopicRevisionFragmentTest.kt (hunk 1 above)
Comment (rt4914) [reply app/src/sharedTest/java/org/oppia/android/app/topic/revision/TopicRevisionFragmentTest.kt:262]: Ack.
