### PR TITLE
Fix #3843 Split Concatenated TextView

### LINKED ISSUE #3843: Completed/ongoing story strings should be separate text views rather than a combined string
After #3795, NavigationDrawerHeaderViewModel combines two strings (for ongoing & completed stories) into a single one. String concatenation should never be used for display purposes since it can be wrong in LTR/RTL situations. Instead, there should be separate text views or a single string to represent the text.

### PR DESCRIPTION
**Pull request by XichengSpencer**
## Explanation
Fix #3843 Instead of using 1 textview to display a concatenated string, now have 1 textview for story progress, 1 for bar separator, and 1 for topic progress.

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

|LTR|RTL|
|---|---|
|Screenshot_20230913_170309|Screenshot_20230913_170148|
|Screenshot_20230913_165312|Screenshot_20230913_170218|

## Tests
Screenshot 2023-09-15 101749

### CODE REVIEW

**Comment by adhiamboperes** [comment]
@XichengSpencer did you mean to put this up for review? Have you checked on the failing CI checks?

**Review by adhiamboperes — APPROVED** [review]
Thanks @XichengSpencer, this is fantastic. 

Please add some text to your PR title to describe the PR.

File: app/src/main/java/org/oppia/android/app/drawer/NavigationDrawerHeaderViewModel.kt [hunk 1]
```diff
@@ -22,33 +22,41 @@ class NavigationDrawerHeaderViewModel @Inject constructor(
...
 
   fun setCompletedStoryProgress(completedStoryCount: Int) {
     this.completedStoryCount = completedStoryCount
-    profileProgressText.set(computeProfileProgressText())
+    profileStoryProgressText.set(computeProfileStoryProgressText())
   }
 
-  private fun computeProfileProgressText(): String {
+  private fun computeProfileStoryProgressText(): String {
     // TODO(#3843): Either combine these strings into one or use separate views to display them.
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/drawer/NavigationDrawerHeaderViewModel.kt]: Please remove this TODO since it will cause a TODO check failure once the corresponding issue is closed

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Just one thing about the TODO. See in-line.

**Comment by adhiamboperes** [comment]
Is this ready for a review? Please assign it to me if so.

**Review by adhiamboperes — APPROVED** [review]
Thanks @XichengSpencer. This LGTM.
