### PR TITLE
Fix #6019: Resolve TopicController crash and CheckBox recycling issues

### LINKED ISSUE #6019: [BUG]: On the Developer Build, Marking Multiple Chapters as Completed Can Put a Topic Into a Broken State
### Describe the bug

It is possible to mark a chapter as completed without actually marking its prerequisite as completed, especially if marking chapters in different topics on a subsequent visit to that screen. 

This leads to a `java.lang.IndexOutOfBoundsException` when the `TopicController` is attempting to compute the chapter play state, because the prerequisite chapter index cannot be found in the `chapterProgressMap`.

### Steps To Reproduce

1. In the drawer menu, select developer options > Mark Chapters Completed
2. Select multiple chapters in different topics, but leave some topics untouched
3. Click "Mark Completed" then navigate away from the screen.
4. Revisit the "Mark Chapters Completed" screen, and select some more chapters, scrolling down the page. 
5. Scroll back up, and notice some chapters that were not manually selected, appear checked. Take note of the topic that was not manually marked, e.g. Division
6.  Click "Mark Completed" then navigate away from the screen.
7. Revisit the "Mark Chapters Completed" screen, and notice that it is blank.
8. Go to the home screen and select the topic from **Step 5**. Notice that the topic page is blank
9. The logcat will show the following stacktrace:

```php
Failed to retrieve storyList
org.oppia.android.util.data.AsyncResult$ChainedFailureException: org.oppia.android.util.data.AsyncResult$ChainedFailureException: java.lang.IndexOutOfBoundsException: Index:-1, Size:8
at org.oppia.android.util.data.AsyncResult.transformWithResult(AsyncResult.kt:158)
at org.oppia.android.util.data.AsyncResult.transform(AsyncResult.kt:95)
at org.oppia.android.util.data.DataProviders$Companion$transform$1.retrieveData(DataProviders.kt:55)
at org.oppia.android.util.data.DataProviders$Companion$transform$1$retrieveData$1.invokeSuspend(Unknown Source:14)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:923)
Caused by: org.oppia.android.util.data.AsyncResult$ChainedFailureException: java.lang.IndexOutOfBoundsException: Index:-1, Size:8
at org.oppia.android.util.data.AsyncResult.transformWithResult(AsyncResult.kt:158)
at org.oppia.android.util.data.AsyncResult.combineWith(AsyncResult.kt:130)
at org.oppia.android.util.data.DataProviders$Companion$combineWith$1.retrieveData(DataProviders.kt:129)
at org.oppia.android.util.data.DataProviders$Companion$combineWith$1$retrieveData$1.invokeSuspend(Unknown Source:14)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.IndexOutOfBoundsException: Index:-1, Size:8
at com.google.protobuf.ProtobufArrayList.ensureIndexInRange(ProtobufArrayList.java:168)
at com.google.protobuf.ProtobufArrayList.get(ProtobufArrayList.java:125)
at org.oppia.android.app.model.StorySummary.getChapter(StorySummary.java:383)
at org.oppia.android.app.model.StorySummary$Builder.getChapter(StorySummary.java:951)
at org.oppia.android.domain.topic.TopicController.combineStorySummaryAndStoryProgress(TopicController.kt:451)
at org.oppia.android.domain.topic.TopicController.combineTopicAndTopicProgress(TopicController.kt:415)
at org.oppia.android.domain.topic.TopicController.combineTopicsAndTopicsProgress(TopicController.kt:436)
at org.oppia.android.domain.topic.TopicController.access$combineTopicsAndTopicsProgress(TopicController.kt:100)
at org.oppia.android.domain.topic.TopicController$getTopics$topicsCombinedProvider$1.invoke(TopicController.kt:156)
at org.oppia.android.domain.topic.TopicController$getTopics$topicsCombinedProvider$1.invoke(TopicController.kt:156)
at org.oppia.android.util.data.AsyncResult$combineWith$1$1.invoke(AsyncResult.kt:131)
at org.oppia.android.util.data.AsyncResult$combineWith$1$1.invoke(AsyncResult.kt:131)
at org.oppia.android.util.data.AsyncResult.transformWithResult(AsyncResult.kt:157)
at org.oppia.android.util.data.AsyncResult.access$transformWithResult(AsyncResult.kt:49)
at org.oppia.android.util.data.AsyncResult$combineWith$1.invoke(AsyncResult.kt:131)
at org.oppia.android.util.data.AsyncResult$combineWith$1.invoke(AsyncResult.kt:130)
at org.oppia.android.util.data.AsyncResult.transformWithResult(AsyncResult.kt:157)
at org.oppia.android.util.data.AsyncResult.combineWith(AsyncResult.kt:130)
at org.oppia.android.util.data.DataProviders$Companion$combineWith$1.retrieveData(DataProviders.kt:129)
at org.oppia.android.util.data.DataProviders$Companion$combineWith$1$retrieveData$1.invokeSuspend(Unknown Source:14)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:923)

```

### Expected Behavior

1. It should not be possible to select a topic if the pre-requisite has not been selected.
2. Items that have not been manually selected, should not appear selected on scrolling the list.
3. The "Mark Chapters Completed" screen should not appear blank.

### Screenshots/Videos

|||
|---|---|
| https://github.com/user-attachments/assets/badf7d82-1820-4a69-ac6f-cfe46ca85d5b | https://github.com/user-attachments/assets/2a17e332-1a8d-4a4a-8e7e-aace1830739e|

### What device/emulator are you using?

Redmi Note 9S

### Which Android version is your device/emulator running?

Android 11

### Which version of the Oppia Android app are you using?

0.16-dev-7a993aa4b0

### Additional Context

This could be an issue with the recyclerview recycling views when scrolled, marking some items as selected when they were actually not.

### PR DESCRIPTION
**Pull request by harshsomankar123-tech**
Fixes #6019

This PR resolves two issues: a crash in `TopicController` and a UI bug in the "Mark Chapters Completed" developer option.

**1. Fix for IndexOutOfBoundsException in TopicController**
* **Issue:** When combining story summary and progress, the code attempts to check the completion status of the previous chapter. For the first chapter (`chapterIndex == 0`), this resulted in accessing index `-1`, causing an `IndexOutOfBoundsException` and a blank topic screen.
* **Fix:** Added a guard clause for `chapterIndex == 0`. If the first chapter has no recorded progress, it is now explicitly treated as `NOT_STARTED`, safely bypassing the invalid predecessor check.

**2. Fix for Phantom Checkbox Selections**
* **Issue:** In the "Mark Chapters Completed" list, `RecyclerView` recycling caused `OnCheckedChangeListener`s from previous bindings to persist. When `isChecked` was set programmatically during a new binding, the stale listener would fire, incorrectly updating the model.
* **Fix:** The `OnCheckedChangeListener` is now cleared (`null`) before setting the checkbox state, ensuring that programmatic updates do not trigger user-interaction listeners.

## Test Evidence
All tests pass locally:
* `TopicControllerTest` passed.
* `MarkChaptersCompletedFragmentTest` passed.

## Essential Checklist
- [x] The PR title starts with "Fix #bugnum: " or "Fix part of #bugnum: ...".
- [x] The PR explanation includes the words "Fixes #bugnum".
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not decrease the existing test coverage.
- [x] The PR is made from a branch that's not called "develop" and is up-to-date with "develop".
- [x] The PR is assigned to the appropriate reviewer(s).

### CODE REVIEW

**Comment by harshsomankar123-tech** [comment]
@adhiamboperes PTAL

File: domain/src/main/java/org/oppia/android/domain/topic/TopicController.kt [hunk 1]
```diff
@@ -448,12 +448,18 @@ class TopicController @Inject constructor(
...
-            chapterBuilder.chapterPlayState = ChapterPlayState.NOT_PLAYABLE_MISSING_PREREQUISITES
-            chapterBuilder.missingPrerequisiteChapter = prerequisiteChapter
+            val prerequisiteChapter = storyBuilder.getChapter(chapterIndex - 1)
+            if (prerequisiteChapter.chapterPlayState == ChapterPlayState.COMPLETED) {
+              chapterBuilder.chapterPlayState = ChapterPlayState.NOT_STARTED
+            } else {
+              chapterBuilder.chapterPlayState =
+                ChapterPlayState.NOT_PLAYABLE_MISSING_PREREQUISITES
+              chapterBuilder.missingPrerequisiteChapter = prerequisiteChapter
+            }
```
Comment (adhiamboperes) [inline domain/src/main/java/org/oppia/android/domain/topic/TopicController.kt:468]: Could you please add a test in `TopicControllerTest.kt` that verifies this condition?

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @harshsomankar123-tech! Please add a test for the domain changes.

**Comment by harshsomankar123-tech** [comment]
@adhiamboperes Thank you for the guidance. I have resolved the requested changes.

**Comment by harshsomankar123-tech** [comment]
@adhiamboperes PTAL

File: app/src/main/java/org/oppia/android/app/devoptions/markchapterscompleted/MarkChaptersCompletedFragmentPresenter.kt [hunk 2]
```diff
@@ -149,6 +149,8 @@ class MarkChaptersCompletedFragmentPresenter @Inject constructor(
     if (notCompletedChapterCount == 0) {
       this.binding.isAllChecked = true
     }
+    // Clear any previous listener to prevent stale callbacks during RecyclerView recycling.
+    binding.markChaptersCompletedChapterCheckBox.setOnCheckedChangeListener(null)
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/devoptions/markchapterscompleted/MarkChaptersCompletedFragmentPresenter.kt:154]: Please add a new line before and after this code and commentbecause it is not grouped together with the if check below or the one above.

File: domain/src/test/java/org/oppia/android/domain/topic/TopicControllerTest.kt [hunk 3]
```diff
@@ -76,6 +76,7 @@ class TopicControllerTest {
   @Inject lateinit var context: Context
   @Inject lateinit var storyProgressTestHelper: StoryProgressTestHelper
   @Inject lateinit var topicController: TopicController
+  @Inject lateinit var storyProgressController: StoryProgressController
```
Comment (adhiamboperes) [inline domain/src/test/java/org/oppia/android/domain/topic/TopicControllerTest.kt:79]: There is no need to inject the controller, we have a storyProgressTestHelper which is already widely used in this test suite.

File: domain/src/test/java/org/oppia/android/domain/topic/TopicControllerTest.kt [hunk 4]
```diff
@@ -1123,6 +1138,17 @@ class TopicControllerTest {
...
+  private fun markOnlyFractionsStory0Chapter1AsInProgressSaved() {
+    val resultProvider = storyProgressController.recordChapterAsInProgressSaved(
+      profileId1,
+      FRACTIONS_TOPIC_ID,
+      FRACTIONS_STORY_ID_0,
+      FRACTIONS_EXPLORATION_ID_1,
+      lastPlayedTimestamp = 0
+    )
+    monitorFactory.waitForNextSuccessfulResult(resultProvider)
+  }
```
Comment (adhiamboperes) [inline domain/src/test/java/org/oppia/android/domain/topic/TopicControllerTest.kt]: `markInProgressSavedFractionsStory0Exp1` is already defined inside the  `StoryProgressTestHelper`

File: domain/src/test/java/org/oppia/android/domain/topic/TopicControllerTest.kt [hunk 5]
```diff
@@ -772,6 +773,20 @@ class TopicControllerTest {
       .isEqualTo(ChapterPlayState.NOT_STARTED)
   }
 
+  @Test
+  fun testGetTopic_recordProgressForSecondChapterOnly_firstChapterIsNotStarted() {
```
Comment (adhiamboperes) [inline domain/src/test/java/org/oppia/android/domain/topic/TopicControllerTest.kt]:
```suggestion
  fun testRetrieveTopic_recordProgressForSecondChapterOnly_firstChapterIsNotStarted() {
```

Comment (adhiamboperes) [reply domain/src/test/java/org/oppia/android/domain/topic/TopicControllerTest.kt]: I have other suggestions for this test:
1. Please move it up in the file so that it is grouped togethr with the other testRetrieveTopic tests.
2. Can you run the test without your fix in the controller and verify whether the IOE is thrown by the test? Please attacha a screenshot.

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @harshsomankar123-tech, 

I have left some comments, but I am also discussing with the team what the full expected fix to this issue is.

**Comment by harshsomankar123-tech** [comment]
@adhiamboperes PTAL

File: domain/src/test/java/org/oppia/android/domain/topic/TopicControllerTest.kt (hunk 5 above)
Comment (adhiamboperes) [reply domain/src/test/java/org/oppia/android/domain/topic/TopicControllerTest.kt]: Hi @harshsomankar123-tech, I verified your changes. I am however wondering if question 2 was addressed because you did not upload a screenshot as requested.

Comment (harshsomankar123-tech) [reply domain/src/test/java/org/oppia/android/domain/topic/TopicControllerTest.kt]: Hi @adhiamboperes, sorry for the delay and thanks for the suggestion!

I tried to verify this using the existing TopicController tests, both with and without my fix, and all tests passed in both cases.

The crash that this PR addresses occurs when chapterIndex == 0 and the code attempts to access chapterIndex - 1. However, the current test setup does not trigger this specific path, which is why the IndexOutOfBoundsException is not observed during test execution.

My fix adds a guard for chapterIndex == 0 to prevent this invalid access and handle the first chapter safely.

If you'd like, I can also add a dedicated test case that explicitly reproduces this failure scenario (i.e., fails before the fix and passes after applying it).

Please let me know how you'd like me to proceed.

Comment (adhiamboperes) [reply domain/src/test/java/org/oppia/android/domain/topic/TopicControllerTest.kt]: Hi @harshsomankar123-tech, I have given this some thought. 

1. If the test is passing both before and after, then it is not correctly testing against regressions.
2.  I believe that you are correct in that the test setup doesn't fix the condition. The correct action here is to create a version of the `markInProgressSavedFractionsStory0Exp1` test helper, that does not have a step for completing the previous chapters first, i.e, does not have ` markCompletedFractionsStory0Exp0(profileId, timestampOlderThanOneWeek)`. This is likely to fail when tested without the fix. This helper can live  as a private function inside the TopicControllerTest test suite and not the StoryProgressTestHelper, because it will only be used in this one place.

File: domain/src/main/java/org/oppia/android/domain/topic/TopicController.kt (hunk 1 above)
Comment (adhiamboperes) [reply domain/src/main/java/org/oppia/android/domain/topic/TopicController.kt:468]: In future, please avoid resolving reviewers' comments, since we need to verify that they have been properly addressed.

**Comment by harshsomankar123-tech** [comment]
@adhiamboperes PTAL

**Comment by adhiamboperes** [comment]
@harshsomankar123-tech, please run this command on your terminal to fix your ktlin issue:

```
java -jar /home/runner/oppia-android-tools/ktlint -F --android domain/src/**/*.kt utility/src/**/*.kt data/src/**/*.kt app/src/**/*.kt testing/src/**/*.kt scripts/src/**/*.kt  instrumentation/src/**/*.kt 
```

Secondly, run this other command so that klint checks will always run before pushing:
```bash
bash scripts/setup.sh
```

**Comment by adhiamboperes** [comment]
PR looks good to me, but I will approve it after the checks pass.

**Comment by harshsomankar123-tech** [comment]
Thanks! @adhiamboperes PTAL. Lint passes locally.

**Review by adhiamboperes — APPROVED** [review]
Approved, thanks!
