### PR TITLE
Fix part #361:  HTML formatting throughout app

### LINKED ISSUE #361: Fix HTML formatting throughout app
There are a few issues we've noticed with HTML formatting:
1. Images that are too large get cut off--we should resize these to take up the maximum space they have available without requiring scrolling, but maintain aspect ratio.
2. Bullet list items need to have proper spacing.
3. Newlines shouldn't be rendered as <br>s.
4. Generally, we need the HTML result to look really clean.

### PR DESCRIPTION
**Pull request by veena14cs**
## Explanation
This PR fixes Html Formatting in the following cases.

- [x] Images that are too large get cut off--we should resize these to take up the maximum space they have available without requiring scrolling, but maintain aspect ratio.
- [x] Newlines shouldn't be rendered.

### CODE REVIEW

File: utility/src/main/java/org/oppia/util/parser/HtmlParser.kt [hunk 1]
```diff
@@ -47,4 +48,24 @@ class HtmlParser private constructor(
...
   }
+
+  private fun trimSpannable(spannable: SpannableStringBuilder): SpannableStringBuilder {
+    checkNotNull(spannable)
+    var trimStart = 0
+    var trimEnd = 0
+
+    var text = spannable.toString()
+
+    while (text.length > 0 && text.startsWith("\n")) {
```
Comment (rt4914) [inline utility/src/main/java/org/oppia/util/parser/HtmlParser.kt]: Nit update: `text.isNotEmpty()`

File: utility/src/main/java/org/oppia/util/parser/UrlImageParser.kt [hunk 2]
```diff
@@ -11,6 +11,9 @@ import android.widget.TextView
 import com.bumptech.glide.request.target.CustomTarget
 import com.bumptech.glide.request.transition.Transition
 import javax.inject.Inject
+import android.opengl.ETC1.getWidth
+
+
```
Comment (rt4914) [inline utility/src/main/java/org/oppia/util/parser/UrlImageParser.kt]: Remove these extra lines and unused imports.

**Review by rt4914 — APPROVED** [review]
LGTM, just nit changes.

File: utility/src/main/java/org/oppia/util/parser/HtmlParser.kt (hunk 1 above)
Comment (veena14cs) [reply utility/src/main/java/org/oppia/util/parser/HtmlParser.kt]: Done.

File: utility/src/main/java/org/oppia/util/parser/UrlImageParser.kt (hunk 2 above)
Comment (veena14cs) [reply utility/src/main/java/org/oppia/util/parser/UrlImageParser.kt]: done.

File: utility/src/main/java/org/oppia/util/parser/UrlImageParser.kt [hunk 3]
```diff
@@ -52,7 +52,17 @@ class UrlImageParser private constructor(
...
         val drawableWidth = drawable.intrinsicWidth
-        val rect = Rect(0, 0, drawableWidth, drawableHeight)
+        val width : Int
+        val height : Int
+        if (htmlContentTextView.getWidth() >= drawableWidth) {
+          width = drawableWidth
+          height = drawableHeight
+        } else {
+          width = htmlContentTextView.getWidth()
+          height = (drawableHeight / (1.0 * drawableWidth / width)).toInt()
```
Comment (BenHenning) [inline utility/src/main/java/org/oppia/util/parser/UrlImageParser.kt]: Small simplification (that also avoids the need to cast to/from double):

```height = (drawableHeight * width) / drawableWidth```

This probably is fine since it's unlikely to overflow.

File: utility/src/main/java/org/oppia/util/parser/UrlImageParser.kt [hunk 4]
```diff
@@ -52,7 +52,17 @@ class UrlImageParser private constructor(
       htmlContentTextView.post {
         val drawableHeight = drawable.intrinsicHeight
         val drawableWidth = drawable.intrinsicWidth
-        val rect = Rect(0, 0, drawableWidth, drawableHeight)
+        val width : Int
+        val height : Int
+        if (htmlContentTextView.getWidth() >= drawableWidth) {
```
Comment (BenHenning) [inline utility/src/main/java/org/oppia/util/parser/UrlImageParser.kt]: Suggest adding a comment explaining this logic so that it's clear to others.

File: utility/src/main/java/org/oppia/util/parser/HtmlParser.kt [hunk 5]
```diff
@@ -47,4 +48,24 @@ class HtmlParser private constructor(
       return HtmlParser(urlImageParserFactory, entityType, entityId)
     }
   }
+
+  private fun trimSpannable(spannable: SpannableStringBuilder): SpannableStringBuilder {
+    checkNotNull(spannable)
```
Comment (BenHenning) [inline utility/src/main/java/org/oppia/util/parser/HtmlParser.kt]: Isn't this tautological? ``spannable`` is a non-null type, so it should never be nullable per Kotlin.

File: utility/src/main/java/org/oppia/util/parser/HtmlParser.kt [hunk 6]
```diff
@@ -47,4 +48,24 @@ class HtmlParser private constructor(
       return HtmlParser(urlImageParserFactory, entityType, entityId)
     }
   }
+
+  private fun trimSpannable(spannable: SpannableStringBuilder): SpannableStringBuilder {
```
Comment (BenHenning) [inline utility/src/main/java/org/oppia/util/parser/HtmlParser.kt:61]: I'm slightly confused by this method--are we deleting whole lines? Does this handle newlines in the middle of the HTML?

Could we maybe instead do something like:

```kotlin
Html.fromHtmk(htmlContent.replace("\n", ""), imageGetter, ...)
```

Or does that not work?

**Review by BenHenning — CHANGES_REQUESTED** [review]
Can you please add tests for this new logic?

I'm also looking for some more context on this trimming behavior that's being added. It's not exactly clear to me how to solves the problem (in fact, adding tests could help clarify that since they should run the code through the usual/expected happy paths).

File: utility/src/main/java/org/oppia/util/parser/HtmlParser.kt (hunk 6 above)
Comment (veena14cs) [reply utility/src/main/java/org/oppia/util/parser/HtmlParser.kt:61]: I tried this. It doesn't work.

File: utility/src/main/java/org/oppia/util/parser/HtmlParser.kt (hunk 5 above)
Comment (veena14cs) [reply utility/src/main/java/org/oppia/util/parser/HtmlParser.kt]: Removed this null check.

File: utility/src/main/java/org/oppia/util/parser/HtmlParser.kt (hunk 6 above)
Comment (veena14cs) [reply utility/src/main/java/org/oppia/util/parser/HtmlParser.kt:61]: > I'm slightly confused by this method--are we deleting whole lines? Does this handle newlines in the middle of the HTML?
> 

It only removes last line.

File: utility/src/main/java/org/oppia/util/parser/UrlImageParser.kt (hunk 4 above)
Comment (veena14cs) [reply utility/src/main/java/org/oppia/util/parser/UrlImageParser.kt]: added comment.

File: utility/src/main/java/org/oppia/util/parser/UrlImageParser.kt (hunk 3 above)
Comment (veena14cs) [reply utility/src/main/java/org/oppia/util/parser/UrlImageParser.kt]: Simplified.

**Comment by nikitamarysolomanpvt** [comment]
Iam unassigning me once the changes are implemented please assign me again.

File: app/src/sharedTest/java/org/oppia/app/parser/HtmlParserTest.kt [hunk 7]
```diff
@@ -79,8 +116,116 @@ class HtmlParserTest {
...
   }
 
+  @Test
+  fun testHtmlContent_calculateImageWidth() {
+    val htmlContentTextView = activityTestRule.activity.findViewById(R.id.test_html_content_text_view) as TextView
+    val imageGetter = urlImageParserFactory.create(htmlContentTextView, "exploration", "DIWZiVgs0km-", true)
+    val result1 = imageGetter.calculateInitialMargin(100)
+    assertWithMessage("Width = " + result1)
+    val result2 = imageGetter.calculateInitialMargin(400)
+    assertWithMessage("Width = " + result2)
```
Comment (rt4914) [inline app/src/sharedTest/java/org/oppia/app/parser/HtmlParserTest.kt]: Nit:`assertWithMessage("Width = $result1")`

File: app/src/sharedTest/java/org/oppia/app/parser/HtmlParserTest.kt [hunk 8]
```diff
@@ -79,8 +116,116 @@ class HtmlParserTest {
...
+
```
Comment (rt4914) [inline app/src/sharedTest/java/org/oppia/app/parser/HtmlParserTest.kt]: Remove this extra line

**Review by rt4914 — APPROVED** [review]
LGTM.

File: app/src/sharedTest/java/org/oppia/app/parser/HtmlParserTest.kt (hunk 7 above)
Comment (veena14cs) [reply app/src/sharedTest/java/org/oppia/app/parser/HtmlParserTest.kt]: Done.

File: app/src/sharedTest/java/org/oppia/app/parser/HtmlParserTest.kt (hunk 8 above)
Comment (veena14cs) [reply app/src/sharedTest/java/org/oppia/app/parser/HtmlParserTest.kt]: Done.

File: app/src/sharedTest/java/org/oppia/app/parser/HtmlParserTest.kt [hunk 9]
```diff
@@ -79,8 +116,115 @@ class HtmlParserTest {
     onView(withId(R.id.test_html_content_text_view)).check(matches(not(textView.text.toString())))
   }
 
+  @Test
+  fun testHtmlContent_calculateImageWidth() {
+    val htmlContentTextView = activityTestRule.activity.findViewById(R.id.test_html_content_text_view) as TextView
+    val imageGetter = urlImageParserFactory.create(htmlContentTextView, "exploration", "DIWZiVgs0km-", true)
+    val result1 = imageGetter.calculateInitialMargin(100)
+    assertWithMessage("Width = $result1")
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/app/parser/HtmlParserTest.kt]: This isn't actually asserting anything. We need to chain it with additional statements (see https://truth.dev/faq#java8, but I don't think this is what you want to do here).

I suggest you verify that image's bounds are computed correctly for a test image, though I suspect that may not be possible since we can't swap out Glide. If that's the case, please file an issue to track properly testing the bounds computing logic.

Also--this test seems out of place for this PR.

File: utility/src/main/java/org/oppia/util/parser/UrlImageParser.kt [hunk 10]
```diff
@@ -78,7 +78,7 @@ class UrlImageParser private constructor(
     }
   }
 
-  private fun calculateInitialMargin(drawableWidth: Int): Int {
+  public fun calculateInitialMargin(drawableWidth: Int): Int {
```
Comment (BenHenning) [inline utility/src/main/java/org/oppia/util/parser/UrlImageParser.kt]: We shouldn't make internal methods public for testing purposes. Instead, we should test through the public API.

In this case, could we verify the drawable's bounds in the test to make sure it's calculated correctly?

File: utility/src/main/java/org/oppia/util/parser/HtmlParser.kt (hunk 6 above)
Comment (BenHenning) [reply utility/src/main/java/org/oppia/util/parser/HtmlParser.kt:61]: Ah I see--this is intentionally only removing the first or last newlines if they exist.

Now that #454 is checked in, do we still need the ``while`` loops?

**Review by BenHenning — CHANGES_REQUESTED** [review]

File: utility/src/main/java/org/oppia/util/parser/HtmlParser.kt (hunk 6 above)
Comment (veena14cs) [reply utility/src/main/java/org/oppia/util/parser/HtmlParser.kt:61]: #454 I checked this PR but it shows new line at the last of the content. Its not removing new line because of which it shows lot of padding at the bottom of content.

Comment (veena14cs) [reply utility/src/main/java/org/oppia/util/parser/HtmlParser.kt]: We can handle bullets using UlTagHandler.

File: app/src/sharedTest/java/org/oppia/app/parser/HtmlParserTest.kt (hunk 9 above)
Comment (veena14cs) [reply app/src/sharedTest/java/org/oppia/app/parser/HtmlParserTest.kt]: There is already issue filed in #277 .

File: utility/src/main/java/org/oppia/util/parser/UrlImageParser.kt (hunk 10 above)
Comment (veena14cs) [reply utility/src/main/java/org/oppia/util/parser/UrlImageParser.kt]: We need to have testing image to get drawable bounds. So I was testing with default values. We can have it tested in #277 .

File: app/src/sharedTest/java/org/oppia/app/parser/HtmlParserTest.kt [hunk 11]
```diff
@@ -83,4 +119,101 @@ class HtmlParserTest {
...
+  @Module
+  abstract class ImageTestModule {
+    @Binds
+    abstract fun provideGlideImageLoader(impl: GlideImageLoader): ImageLoader
+  }
+
+  @Singleton
+  @Component(
+    modules = [TestModule::class
+      , ImageTestModule::class]
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/app/parser/HtmlParserTest.kt]: Please fix formatting:

```kotlin
@Component(modules = [TestModule::class, ImageTestModule::class])
```

File: utility/src/main/java/org/oppia/util/parser/UrlImageParser.kt [hunk 12]
```diff
@@ -78,7 +78,7 @@ class UrlImageParser private constructor(
     }
   }
 
-  private fun calculateInitialMargin(drawableWidth: Int): Int {
+   fun calculateInitialMargin(drawableWidth: Int): Int {
```
Comment (BenHenning) [inline utility/src/main/java/org/oppia/util/parser/UrlImageParser.kt]: Please make this private again since it doesn't appear to need to be accessed outside of this class.

File: utility/src/main/java/org/oppia/util/parser/HtmlParser.kt (hunk 6 above)
Comment (BenHenning) [reply utility/src/main/java/org/oppia/util/parser/HtmlParser.kt:61]: Right, but it prevents there from being more than one newline in the front or back of the string. For that reason, I believe we no longer need the ``while`` loop here.

File: utility/src/main/java/org/oppia/util/parser/HtmlParser.kt [hunk 13]
```diff
@@ -43,9 +44,9 @@ class HtmlParser private constructor(
 
     val imageGetter = urlImageParserFactory.create(htmlContentTextView, entityType, entityId, imageCenterAlign)
     return if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.N) {
-      Html.fromHtml(htmlContent, Html.FROM_HTML_MODE_LEGACY, imageGetter, /* tagHandler= */ null) as Spannable
+      trimSpannable(Html.fromHtml(htmlContent, Html.FROM_HTML_MODE_LEGACY, imageGetter, /* tagHandler= */ null) as SpannableStringBuilder)
     } else {
-      Html.fromHtml(htmlContent, imageGetter, /* tagHandler= */ null) as Spannable
+      trimSpannable(Html.fromHtml(htmlContent, imageGetter, /* tagHandler= */ null)as SpannableStringBuilder)
```
Comment (BenHenning) [inline utility/src/main/java/org/oppia/util/parser/HtmlParser.kt]: Please fix spacing: `` as `` (one space on either side)

**Review by BenHenning — CHANGES_REQUESTED** [review]

File: utility/src/main/java/org/oppia/util/parser/UrlImageParser.kt (hunk 12 above)
Comment (veena14cs) [reply utility/src/main/java/org/oppia/util/parser/UrlImageParser.kt]: okay done.

File: app/src/sharedTest/java/org/oppia/app/parser/HtmlParserTest.kt (hunk 11 above)
Comment (veena14cs) [reply app/src/sharedTest/java/org/oppia/app/parser/HtmlParserTest.kt]: Done.

**Review by BenHenning — APPROVED** [review]
As discussed via chat, please remove the loops such that we’re only removing the first or last newline, rather than all first or last newlines. We can avoid the loops by updating the newline replace pattern added in #454 with one that replaces all variable newlines with one, eg: “\n{2,}” to solve the case of “\n\n\n” becoming “\n”.

File: utility/src/main/java/org/oppia/util/parser/HtmlParser.kt (hunk 6 above)
Comment (veena14cs) [reply utility/src/main/java/org/oppia/util/parser/HtmlParser.kt:61]: Replaced while loop with if statement.

File: utility/src/main/java/org/oppia/util/parser/HtmlParser.kt (hunk 13 above)
Comment (veena14cs) [reply utility/src/main/java/org/oppia/util/parser/HtmlParser.kt]: done.

File: utility/src/main/java/org/oppia/util/parser/HtmlParser.kt [hunk 14]
```diff
@@ -43,10 +45,36 @@ class HtmlParser private constructor(
...
+    var text = spannable.toString()
+
+    if (text.startsWith("\n")) {
+      text = text.substring(1)
+      trimStart += 1
     }
+
+    if (text.endsWith("\n")) {
+      text = text.substring(0, text.length - 1)
+      trimEnd += 2
```
Comment (veena14cs) [inline utility/src/main/java/org/oppia/util/parser/HtmlParser.kt:74]: Workaround.

**Comment by veena14cs** [comment]
> “\n{2,}”

Changed loop to if statement in trimSpannable() method. I tried replacing “\n{2,}” it didnt workout for me I tried workaround on [this](https://github.com/oppia/oppia-android/pull/404/files#r350143730)

**Comment by veena14cs** [comment]
Fix part of #361.
