### PR TITLE
Fix #4362, #1491: When reading text size is extra large, resume lesson page and revision tabs content is seen in normal size

### LINKED ISSUE #1491: Story Text Size in other learner screens.
Currently the story text size change in settings is getting reflected in exploration / `StateFragment` only. But I think it should get reflected in Concept Card as well as Hints & Solution because from user perspective they are also part of exploration only.

## Checklist
- [x] Implement in Hints & Solution
- [x] Implement in Concept Card
- [x] Implement in Question Player
- [x] Revision Card
- [x] Check that it is working on Hints & Solution of Question Player

### LINKED ISSUE #4362: When reading text size is extra large, resume lesson page and revision tabs content is seen in normal size
**Describe the bug**
When reading text size is extra large, resume lesson page and revision tabs content is seen in normal size

**To Reproduce**
1. Go to 'Navigation menu'
2. Click on 'Options'- Change Reading text size to Extra large
3. Open any exploration which is in progress
4. The Resume page will be seen in normal text size

**Expected behavior**
Resume lesson page should also be in Extra large size
In the Revision tab, click on any tile the content is displayed in normal text size

Environment:
Device name: One plus Nord2 5G
Android version : Android 11
App version: 0.7-alpha-6c08d882d3

### PR DESCRIPTION
**Pull request by Vishwajith-Shettigar**
## Explanation
Fixes #4362 
Fixes #1491

Support resizable reading text in resume lesson, question player and revision card.

| Before| After|
|--------|--------|
|[before.webm](https://github.com/oppia/oppia-android/assets/76042077/aa58a643-727f-421d-8b3a-a4799718113e)|[device-2024-01-02-150914.webm](https://github.com/oppia/oppia-android/assets/76042077/aa46b657-87cf-4c4f-b512-0c1b67dd351d)|
|[tablet_before.webm](https://github.com/oppia/oppia-android/assets/76042077/b9fd6b96-2f28-4a4f-8db5-1106219054f1)|[tablet_after.webm](https://github.com/oppia/oppia-android/assets/76042077/c9a105db-9062-47c4-982b-dd7f35a1f14c)|

Question Player

[questionPLayer.webm](https://github.com/oppia/oppia-android/assets/76042077/6b321c57-35ed-44e6-8220-3b9d52c089cc)

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- For PRs introducing new UI elements or color changes, both light and dark mode screenshots must be included
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### CODE REVIEW

**Comment by Vishwajith-Shettigar** [comment]
@adhiamboperes, PTAL.

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @Vishwajith-Shettigar!!

Please update the PR description and add before/after screenshots for mobile and tablets so that I can verify that the solution works.

**Comment by Vishwajith-Shettigar** [comment]
@adhiamboperes PTAL, PR description has been updated.

**Comment by Vishwajith-Shettigar** [comment]
@adhiamboperes, PTAL.

File: app/src/main/java/org/oppia/android/app/resumelesson/ResumeLessonActivity.kt [hunk 1]
```diff
@@ -100,4 +103,14 @@ class ResumeLessonActivity :
...
   }
+
+  override fun onDefaultFontSizeLoaded(readingTextSize: ReadingTextSize) {
+    resumeLessonActivityPresenter.loadResumeLessonFragment(readingTextSize)
+  }
+
+  override fun onBackPressed() {
+    super.onBackPressed()
+    resumeLessonActivityPresenter.onBackPressed()
+    finish()
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/resumelesson/ResumeLessonActivity.kt]: Why do we need this?

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @Vishwajith-Shettigar! This is an intyeresting solution. 

I have some thoughts:
- When thinking about possible User journey, it seems less likely that a user may want to change the text size on the resume lesson page, and more that they would expect it to show the same as the text size they selected the last time they were in a lesson.
- As such, we would want to not add the option  to change the text sie in the toolbar, but to retrieve the saved exploration reading text size, and apply it to this activity as well.

Please let me know if you have questions on how to go about this.

File: app/src/main/java/org/oppia/android/app/resumelesson/ResumeLessonActivity.kt (hunk 1 above)
Comment (Vishwajith-Shettigar) [reply app/src/main/java/org/oppia/android/app/resumelesson/ResumeLessonActivity.kt]: When user press back, app text size is set to medium.

**Comment by Vishwajith-Shettigar** [comment]
> Thanks @Vishwajith-Shettigar! This is an interesting solution.
> 
> I have some thoughts:
> 
> * When thinking about possible User journey, it seems less likely that a user may want to change the text size on the resume lesson page, and more that they would expect it to show the same as the text size they selected the last time they were in a lesson.
> * As such, we would want to not add the option  to change the text sie in the toolbar, but to retrieve the saved exploration reading text size, and apply it to this activity as well.
> 
> Please let me know if you have questions on how to go about this.


Changing reading text size would change size of all pages(resume lessson, exploration, and revison), its not targeting any single page.

[readingsize.webm](https://github.com/oppia/oppia-android/assets/76042077/8412d894-a6d6-4f1b-aea2-0fe971df8a70)


Fixed Tool bar title issue

[Toolbartextdoentchange.webm](https://github.com/oppia/oppia-android/assets/76042077/86857342-19e5-42e5-b21e-64890728371a)

**Comment by Vishwajith-Shettigar** [comment]
> Thanks @Vishwajith-Shettigar! This is an intyeresting solution.
> 
> I have some thoughts:
> 
> * When thinking about possible User journey, it seems less likely that a user may want to change the text size on the resume lesson page, and more that they would expect it to show the same as the text size they selected the last time they were in a lesson.
> * As such, we would want to not add the option  to change the text sie in the toolbar, but to retrieve the saved exploration reading text size, and apply it to this activity as well.
> 
> Please let me know if you have questions on how to go about this.

Changing reading text size would change size of all pages(resume lessson, exploration, and revison), its not targeting any single page.

File: app/src/main/java/org/oppia/android/app/resumelesson/ResumeLessonActivityPresenter.kt [hunk 2]
```diff
@@ -53,11 +93,44 @@ class ResumeLessonActivityPresenter @Inject constructor(
...
+    )
+  }
+
+  private fun processReadingTextSizeResult(
+    readingTextSizeResult: AsyncResult<Profile>
+  ): ReadingTextSize {
+    return when (readingTextSizeResult) {
+      is AsyncResult.Failure -> {
+
+        Profile.getDefaultInstance()
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/resumelesson/ResumeLessonActivityPresenter.kt:128]: You should log an error here instead, so that we know what happened(i.e could not fetch profile)

File: app/src/main/java/org/oppia/android/app/resumelesson/ResumeLessonActivityPresenter.kt [hunk 3]
```diff
@@ -53,11 +93,44 @@ class ResumeLessonActivityPresenter @Inject constructor(
...
 
+  private fun retrieveReadingTextSize(): LiveData<ReadingTextSize> {
+    return Transformations.map(
+      profileManagementController.getProfile(profileId).toLiveData(),
+      ::processReadingTextSizeResult
+    )
+  }
+
+  private fun processReadingTextSizeResult(
+    readingTextSizeResult: AsyncResult<Profile>
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/resumelesson/ResumeLessonActivityPresenter.kt]: Isn't this more accurately the **profileResult**?

File: app/src/main/java/org/oppia/android/app/resumelesson/ResumeLessonActivityPresenter.kt [hunk 4]
```diff
@@ -53,11 +93,44 @@ class ResumeLessonActivityPresenter @Inject constructor(
...
+  ): ReadingTextSize {
+    return when (readingTextSizeResult) {
+      is AsyncResult.Failure -> {
+
+        Profile.getDefaultInstance()
+      }
+      is AsyncResult.Pending -> Profile.getDefaultInstance()
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/resumelesson/ResumeLessonActivityPresenter.kt]: This can be a no- op branch, i.e do nothhing, or log an information to console that the result is prending or still being fetched.

File: app/src/main/java/org/oppia/android/app/resumelesson/ResumeLessonActivityPresenter.kt [hunk 5]
```diff
@@ -53,11 +93,44 @@ class ResumeLessonActivityPresenter @Inject constructor(
...
+
   private fun getResumeLessonFragment(): ResumeLessonFragment? {
     return activity
       .supportFragmentManager
       .findFragmentById(
         R.id.resume_lesson_fragment_placeholder
       ) as ResumeLessonFragment?
   }
+
+  /** Handles onBacKPressed. */
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/resumelesson/ResumeLessonActivityPresenter.kt]:
```suggestion
  /** Changes the reading text size to normal onBacKPressed. */
```

File: app/src/main/java/org/oppia/android/app/player/exploration/ExplorationActivity.kt [hunk 6]
```diff
@@ -44,7 +44,8 @@ class ExplorationActivity :
   BottomSheetOptionsMenuItemClickListener,
   RequestVoiceOverIconSpotlightListener {
 
-  @Inject lateinit var explorationActivityPresenter: ExplorationActivityPresenter
+  @Inject
+  lateinit var explorationActivityPresenter: ExplorationActivityPresenter
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/player/exploration/ExplorationActivity.kt]: Unneeded format only change

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @Vishwajith-Shettigar!

PTAL at my comments inline.

File: app/src/main/java/org/oppia/android/app/resumelesson/ResumeLessonActivityPresenter.kt (hunk 2 above)
Comment (Vishwajith-Shettigar) [reply app/src/main/java/org/oppia/android/app/resumelesson/ResumeLessonActivityPresenter.kt:128]: OKay.

File: app/src/main/java/org/oppia/android/app/resumelesson/ResumeLessonActivityPresenter.kt (hunk 3 above)
Comment (Vishwajith-Shettigar) [reply app/src/main/java/org/oppia/android/app/resumelesson/ResumeLessonActivityPresenter.kt:104]: I don't think so, we just retrieving textsize only.

Comment (Vishwajith-Shettigar) [reply app/src/main/java/org/oppia/android/app/resumelesson/ResumeLessonActivityPresenter.kt]: Yes, profileResult sounds more accurate.

File: app/src/main/java/org/oppia/android/app/resumelesson/ResumeLessonActivityPresenter.kt (hunk 5 above)
Comment (Vishwajith-Shettigar) [reply app/src/main/java/org/oppia/android/app/resumelesson/ResumeLessonActivityPresenter.kt]: Noted, thank you.

File: app/src/main/java/org/oppia/android/app/resumelesson/ResumeLessonActivityPresenter.kt (hunk 4 above)
Comment (Vishwajith-Shettigar) [reply app/src/main/java/org/oppia/android/app/resumelesson/ResumeLessonActivityPresenter.kt]: Will add log.

File: app/src/main/java/org/oppia/android/app/player/exploration/ExplorationActivity.kt (hunk 6 above)
Comment (Vishwajith-Shettigar) [reply app/src/main/java/org/oppia/android/app/player/exploration/ExplorationActivity.kt]: I'll fix.

**Comment by Vishwajith-Shettigar** [comment]
@adhiamboperes, PTAL.

**Review by adhiamboperes — COMMENTED** [review]
Thanks @Vishwajith-Shettigar! 

You can go ahead and add tests in the respective fragment or activity test  classes.

**Comment by Vishwajith-Shettigar** [comment]
@adhiamboperes, PTAL.

File: app/src/main/res/values/dimens.xml [hunk 7]
```diff
@@ -34,6 +34,18 @@
...
+  <dimen name="resume_lesson_fragment_font_scale_content_small_text_size">12.8dp</dimen>
+  <dimen name="resume_lesson_fragment_font_scale_content_medium_text_size">16dp</dimen>
+  <dimen name="resume_lesson_fragment_font_scale_content_large_text_size">19.2dp</dimen>
+  <dimen name="resume_lesson_fragment_font_scale_content_extra_large_text_size">22.4dp</dimen>
+
+  <!-- Revision Card Fragment Fragment Font Scale -->
+  <dimen name="revision_card_fragment_font_scale_content_small_text_size">12.8dp</dimen>
+  <dimen name="revision_card_fragment_font_scale_content_medium_text_size">16dp</dimen>
+  <dimen name="revision_card_fragment_font_scale_content_large_text_size">19.2dp</dimen>
+  <dimen name="revision_card_fragment_font_scale_content_extra_large_text_size">22.4dp</dimen>
```
Comment (adhiamboperes) [inline app/src/main/res/values/dimens.xml]: A few thoughts:
1. Font is measured in sp not dp.
2. In the dimens file, we already have the font scale size definitions, which you should use for your tests. Search for `<!-- Font Scale -->`.
3. It is not part of our conventions to use decimals in our dimensions.

File: app/src/sharedTest/java/org/oppia/android/app/resumelesson/ResumeLessonFragmentTest.kt [hunk 8]
```diff
@@ -293,6 +296,85 @@ class ResumeLessonFragmentTest {
...
+  @Test
+  fun testResumeLessonFragment_extraLargeTextSize_hasCorrectDimension() {
+    launch<ResumeLessonActivity>(createResumeLessonActivityIntent()).use {
+      it.onActivity { activity ->
+        activity.resumeLessonActivityPresenter
+          .loadResumeLessonFragment(ReadingTextSize.EXTRA_LARGE_TEXT_SIZE)
+      }
+      onView(withId(R.id.resume_lesson_chapter_description_text_view)).check(
+        matches(
+          FontSizeMatcher.withFontSize(
```
Comment (adhiamboperes) [inline app/src/sharedTest/java/org/oppia/android/app/resumelesson/ResumeLessonFragmentTest.kt]: Directly import `FontSizeMatcher.`

File: app/src/sharedTest/java/org/oppia/android/app/resumelesson/ResumeLessonFragmentTest.kt [hunk 9]
```diff
@@ -293,6 +296,85 @@ class ResumeLessonFragmentTest {
...
+      it.onActivity { activity ->
+        activity.resumeLessonActivityPresenter
+          .loadResumeLessonFragment(ReadingTextSize.LARGE_TEXT_SIZE)
+      }
+      onView(withId(R.id.resume_lesson_chapter_description_text_view)).check(
+        matches(
+          FontSizeMatcher.withFontSize(
+            round(
+              context.resources
+                .getDimension(R.dimen.resume_lesson_fragment_font_scale_content_large_text_size)
```
Comment (adhiamboperes) [inline app/src/sharedTest/java/org/oppia/android/app/resumelesson/ResumeLessonFragmentTest.kt]: After using the dimensions I have recommended above, I don't think it will be necessary to use round in these tests. Please refer to app/src/sharedTest/java/org/oppia/android/app/testing/TestFontScaleConfigurationUtilActivityTest.kt for sample tests.

File: app/src/sharedTest/java/org/oppia/android/app/topic/revisioncard/RevisionCardFragmentTest.kt [hunk 10]
```diff
@@ -229,6 +232,119 @@ class RevisionCardFragmentTest {
...
+      it.onActivity { activity ->
+        activity.revisionCardActivityPresenter
+          .loadRevisionCardFragment(ReadingTextSize.EXTRA_LARGE_TEXT_SIZE)
+      }
+      onView(withId(R.id.revision_card_explanation_text)).check(
+        matches(
+          FontSizeMatcher.withFontSize(
+            round(
+              context.resources.getDimension(
+                R.dimen.revision_card_fragment_font_scale_content_extra_large_text_size
```
Comment (adhiamboperes) [inline app/src/sharedTest/java/org/oppia/android/app/topic/revisioncard/RevisionCardFragmentTest.kt]: Please direct import `FontSizeMatcher` here too, and update to use font scale sp dimensions without the round function. Ditto other tests in file.

File: app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardActivityPresenter.kt [hunk 11]
```diff
@@ -30,16 +36,20 @@ class RevisionCardActivityPresenter @Inject constructor(
...
   private val analyticsController: AnalyticsController,
   private val topicController: TopicController,
-  private val translationController: TranslationController
+  private val translationController: TranslationController,
+  private val profileManagementController: ProfileManagementController,
+  private val fontScaleConfigurationUtil: FontScaleConfigurationUtil,
 ) {
-  @Inject lateinit var accessibilityService: AccessibilityService
+  @Inject
+  lateinit var accessibilityService: AccessibilityService
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardActivityPresenter.kt]: Revert to single line

File: app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardFragmentPresenter.kt [hunk 12]
```diff
@@ -98,4 +133,20 @@ class RevisionCardFragmentPresenter @Inject constructor(
...
+
+  private fun retrieveReadingTextSize(): ReadingTextSize {
+    return fragment.requireArguments()
+      .getSerializable(READING_TEXT_SIZE_ARGUMENT_KEY) as ReadingTextSize
+  }
+
+  private fun selectNewReadingTextSize(readingTextSize: ReadingTextSize) {
+    updateArguments(
+      readingTextSize
+    )
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardFragmentPresenter.kt]: Can be on one line.

File: app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardFragmentPresenter.kt [hunk 13]
```diff
@@ -83,6 +98,26 @@ class RevisionCardFragmentPresenter @Inject constructor(
     return binding.root
   }
 
+  /** Handles the [Fragment.onCreateView] portion of [RevisionCardFragment]'s lifecycle. */
+  fun handleViewCreated() {
+
+    val profileDataProvider = profileManagementController.getProfile(profileId)
+    profileDataProvider.toLiveData().observe(
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardFragmentPresenter.kt]: Instead of reading the textsize from cache, why not use the one from the ` fun retrieveReadingTextSize()` below? it seems as if it is unused anywhere in this file.

File: app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardFragmentPresenter.kt (hunk 12 above)
Comment (adhiamboperes) [reply app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardFragmentPresenter.kt]: Overall, I'm not sure why this function is needed here.

File: app/src/main/java/org/oppia/android/app/resumelesson/ResumeLessonActivityPresenter.kt (hunk 2 above)
Comment (adhiamboperes) [reply app/src/main/java/org/oppia/android/app/resumelesson/ResumeLessonActivityPresenter.kt:128]: Look's like I commented under the pending branch instead of the failure branch which I intended. While a result is pending, we typically log with .d() because it is a debug not error meesage.

File: app/src/main/java/org/oppia/android/app/resumelesson/ResumeLessonActivityPresenter.kt [hunk 14]
```diff
@@ -60,4 +135,17 @@ class ResumeLessonActivityPresenter @Inject constructor(
         R.id.resume_lesson_fragment_placeholder
       ) as ResumeLessonFragment?
   }
+
+  /** Changes the reading text size to normal onBacKPressed. */
+  fun onBackPressed() {
+    setReadingTextSizeNormal()
+  }
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/resumelesson/ResumeLessonActivityPresenter.kt]: Just directly call this `setReadingTextSizeNormal()` in the activity since it is already public and wrapping it in another function is redundant.

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @Vishwajith-Shettigar! I took a full pass on this PR. PTAL at the changes I have suggested.

File: app/src/main/res/values/dimens.xml (hunk 7 above)
Comment (Vishwajith-Shettigar) [reply app/src/main/res/values/dimens.xml]: 1. font scale size which already exists are in dp.
Screenshot 2024-03-19 204920

2. I defined new font size scale because existing font scale are not working with the textview I'm targeting because of different text size and same for 3rd point.

File: app/src/sharedTest/java/org/oppia/android/app/resumelesson/ResumeLessonFragmentTest.kt (hunk 8 above)
Comment (Vishwajith-Shettigar) [reply app/src/sharedTest/java/org/oppia/android/app/resumelesson/ResumeLessonFragmentTest.kt]: okay, ill fix them.

File: app/src/sharedTest/java/org/oppia/android/app/topic/revisioncard/RevisionCardFragmentTest.kt (hunk 10 above)
Comment (Vishwajith-Shettigar) [reply app/src/sharedTest/java/org/oppia/android/app/topic/revisioncard/RevisionCardFragmentTest.kt]: okay.

File: app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardActivityPresenter.kt (hunk 11 above)
Comment (Vishwajith-Shettigar) [reply app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardActivityPresenter.kt]: Done.

File: app/src/main/res/values/dimens.xml (hunk 7 above)
Comment (adhiamboperes) [reply app/src/main/res/values/dimens.xml]: I suspect that the tests will fail if you use a device with a different screen size, therefore point (3) still stands. We don't use decimals in dimensions.

I also think that it is okay to modify the existing font scale to sp, even though it may result in changing some other font scale utility tests. You need to verify that the UI still scales the way it should, but I don't foresee any problems with that.

File: app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardFragmentPresenter.kt (hunk 13 above)
Comment (Vishwajith-Shettigar) [reply app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardFragmentPresenter.kt]: When the fragment is initially loaded, we use retrieveReadingTextSize(). Subsequently, we monitor the profileDataProvider for any updates. Users have the ability to adjust the text size dynamically while reading the revision card content.

File: app/src/main/java/org/oppia/android/app/resumelesson/ResumeLessonActivityPresenter.kt (hunk 14 above)
Comment (Vishwajith-Shettigar) [reply app/src/main/java/org/oppia/android/app/resumelesson/ResumeLessonActivityPresenter.kt]: Okay.

File: app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardFragmentPresenter.kt (hunk 12 above)
Comment (Vishwajith-Shettigar) [reply app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardFragmentPresenter.kt]: Made some changes, and removed this method.

File: app/src/main/res/values/dimens.xml (hunk 7 above)
Comment (Vishwajith-Shettigar) [reply app/src/main/res/values/dimens.xml]: I don't think the test will fail even with a different screen size, because I have tried running the test on multiple devices.

**Comment by Vishwajith-Shettigar** [comment]
@adhiamboperes, PTAL. Thank you.

File: app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardActivityPresenter.kt [hunk 15]
```diff
@@ -79,17 +98,41 @@ class RevisionCardActivityPresenter @Inject constructor(
...
+        )
+        Profile.getDefaultInstance()
+      }
+      is AsyncResult.Success -> profileResult.value
+    }.readingTextSize
   }
 
   /** Action for onOptionsItemSelected. */
   fun handleOnOptionsItemSelected(itemId: Int): Boolean {
+    setReadingTextSizeMedium()
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardActivityPresenter.kt:135]: I think this should remain the same as the current selected font size, for consistency purposes.

File: app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardActivity.kt [hunk 16]
```diff
@@ -98,6 +101,11 @@ class RevisionCardActivity :
   }
 
   override fun onBackPressed() {
+    revisionCardActivityPresenter.setReadingTextSizeMedium()
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardActivity.kt:121]: I think it would be best to keep the current reading text size instead of resetting it, because resetting it gives the user extra work of selecting the preferred size again next time, which is not great UX(they may be frustrated trying to figure out why the font size keeps changing)

File: app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardActivityPresenter.kt [hunk 17]
```diff
@@ -172,4 +215,25 @@ class RevisionCardActivityPresenter @Inject constructor(
...
+        topicId,
+        subtopicId,
+        profileId,
+        subtopicListSize,
+        readingTextSize
+      )
+    ).commitNow()
+  }
+
+  fun setReadingTextSizeMedium() {
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardActivityPresenter.kt:236]: This function will become unused.

File: app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardActivityPresenter.kt [hunk 18]
```diff
@@ -54,18 +63,28 @@ class RevisionCardActivityPresenter @Inject constructor(
...
+    )
+
     revisionCardToolbar = binding.revisionCardToolbar
     revisionCardToolbarTitle = binding.revisionCardToolbarTitle
     activity.setSupportActionBar(revisionCardToolbar)
     activity.supportActionBar?.setDisplayShowTitleEnabled(false)
 
     binding.revisionCardToolbar.setNavigationOnClickListener {
       (activity as ReturnToTopicClickListener).onReturnToTopicRequested()
+      fontScaleConfigurationUtil.adjustFontScale(activity, ReadingTextSize.MEDIUM_TEXT_SIZE)
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardActivityPresenter.kt:85]: Same comment on not resetting the reading text size on back press.

File: app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardFragment.kt [hunk 19]
```diff
@@ -62,11 +72,17 @@ class RevisionCardFragment : InjectableDialogFragment() {
...
     return revisionCardFragmentPresenter.handleCreateView(
       inflater, container, topicId, subtopicId, profileId, subtopicListSize
     )
   }
 
+  override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
+    super.onViewCreated(view, savedInstanceState)
+    revisionCardFragmentPresenter.handleViewCreated()
+  }
+
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardFragment.kt]: We already have the ` override fun onCreateView()`.

Retrieve the text size from the fragment's arguments there and pass it as an argument for the `revisionCardFragmentPresenter.handleCreateView()` so you don't need to fetch it from profile during initial fragment creation.

File: app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardFragmentPresenter.kt (hunk 13 above)
Comment (adhiamboperes) [reply app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardFragmentPresenter.kt]: I have tested the code without this bit, and it still works. Reason being that we call "handleAttach" every time the fragment is recreated, which happens when we load the activity or change the font size via the options menu. The `profileDataProvider` is already being observed in the `RevisionCardActivityPresenter` and the result is being passed down to the fragment via the args, making this monitoring redundant.

File: app/src/main/java/org/oppia/android/app/resumelesson/ResumeLessonActivity.kt [hunk 20]
```diff
@@ -100,4 +104,13 @@ class ResumeLessonActivity :
...
   }
+
+  override fun onDefaultFontSizeLoaded(readingTextSize: ReadingTextSize) {
+    resumeLessonActivityPresenter.loadResumeLessonFragment(readingTextSize)
+  }
+
+  override fun onBackPressed() {
+    resumeLessonActivityPresenter.setReadingTextSizeNormal()
+    finish()
+  }
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/resumelesson/ResumeLessonActivity.kt:120]: This change is not needed either.

File: app/src/main/java/org/oppia/android/app/resumelesson/ResumeLessonActivity.kt [hunk 21]
```diff
@@ -87,6 +90,7 @@ class ResumeLessonActivity :
     parentScreen: ExplorationActivityParams.ParentScreen,
     isCheckpointingEnabled: Boolean
   ) {
+    resumeLessonActivityPresenter.setReadingTextSizeNormal()
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/resumelesson/ResumeLessonActivity.kt:97]: I believe there is no need to reset the size here.

File: app/src/main/java/org/oppia/android/app/resumelesson/ResumeLessonActivityPresenter.kt [hunk 22]
```diff
@@ -29,28 +50,82 @@ class ResumeLessonActivityPresenter @Inject constructor(
...
+        (activity as DefaultFontSizeStateListener).onDefaultFontSizeLoaded(result)
+      }
+    )
+
     resumeLessonToolbar.setNavigationOnClickListener {
+      fontScaleConfigurationUtil.adjustFontScale(
+        context = activity,
+        ReadingTextSize.MEDIUM_TEXT_SIZE
+      )
+
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/resumelesson/ResumeLessonActivityPresenter.kt]: Only activities that have implemented `DefaultFontSizeStateListener` are affected by font size changes. So by default, closing this screen without resetting won't affect the topic screen, making this call redundant.

File: app/src/main/java/org/oppia/android/app/resumelesson/ResumeLessonActivityPresenter.kt [hunk 23]
```diff
@@ -60,4 +135,12 @@ class ResumeLessonActivityPresenter @Inject constructor(
...
       ) as ResumeLessonFragment?
   }
+
+  /** Set reading text size normal. */
+  fun setReadingTextSizeNormal() {
+    fontScaleConfigurationUtil.adjustFontScale(
+      context = activity,
+      ReadingTextSize.MEDIUM_TEXT_SIZE
+    )
+  }
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/resumelesson/ResumeLessonActivityPresenter.kt:148]: This function is not being called anywhere so you should remove it.

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @Vishwajith-Shettigar!

I have taken another full pass at this and left some comments. Most of them revolve around removing changes that do not contribute to the feature.

File: app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardActivityPresenter.kt (hunk 15 above)
Comment (Vishwajith-Shettigar) [reply app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardActivityPresenter.kt:135]: We are only scaling content of the app, i don't think scaling option or help activity is necessary.
Would like to hear your opinion.

File: app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardActivity.kt (hunk 16 above)
Comment (Vishwajith-Shettigar) [reply app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardActivity.kt:121]: Even setting text to Medium doesn't affect user selected size when user return to revision card next time, because its just hardcoding the size in activity, not updating the reading size in profile.

File: app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardActivityPresenter.kt (hunk 17 above)
Comment (Vishwajith-Shettigar) [reply app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardActivityPresenter.kt:236]: Blocked on [comment](https://github.com/oppia/oppia-android/pull/5290#discussion_r1569018960)

File: app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardActivity.kt (hunk 16 above)
Comment (Vishwajith-Shettigar) [reply app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardActivity.kt:104]: If we don't set to medium this happens, i have attached screen recording PTAL.

[readingTextsize.webm](https://github.com/oppia/oppia-android/assets/76042077/3fc19fcc-9c5d-4ca5-8bcc-77c1b365d767)

Comment (Vishwajith-Shettigar) [reply app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardActivity.kt:121]: If we don't set to medium this happens, i have attached screen recording PTAL.

[readingTextsize.webm](https://github.com/oppia/oppia-android/assets/76042077/3fc19fcc-9c5d-4ca5-8bcc-77c1b365d767)

File: app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardActivityPresenter.kt (hunk 18 above)
Comment (Vishwajith-Shettigar) [reply app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardActivityPresenter.kt:85]: Same [comment](https://github.com/oppia/oppia-android/pull/5290#discussion_r1576450630)

File: app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardFragmentPresenter.kt (hunk 13 above)
Comment (Vishwajith-Shettigar) [reply app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardFragmentPresenter.kt]: This actually recreates the activity, i observed, if i remove this, and when i change size, tool bar title size remains same.

Comment (Vishwajith-Shettigar) [reply app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardFragmentPresenter.kt]: This is only monitoring to recreate the activity.

File: app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardActivity.kt (hunk 16 above)
Comment (adhiamboperes) [reply app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardActivity.kt:121]: Okay, noted.

File: app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardActivityPresenter.kt (hunk 15 above)
Comment (adhiamboperes) [reply app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardActivityPresenter.kt:135]: I don't really understand your comment in response to mine.

File: app/src/sharedTest/java/org/oppia/android/app/topic/revisioncard/RevisionCardFragmentTest.kt [hunk 24]
```diff
@@ -229,6 +232,119 @@ class RevisionCardFragmentTest {
...
+              )
+            )
+          )
+        )
+      )
+    }
+  }
```
Comment (adhiamboperes) [inline app/src/sharedTest/java/org/oppia/android/app/topic/revisioncard/RevisionCardFragmentTest.kt]: In our discussion we had agreed to hardcode the values, e.g below. 
```suggestion
        onView(withId(R.id.revision_card_explanation_text)).check(
        matches(
          withFontSize(
            62.0F
          )
        )
      )
```

I came up with 62F by logging the calculated value in the `FontSizeMatcher.kt` util class and checking logcat:
```
class FontSizeMatcher(private val expectedSize: Float) :
  TypeSafeMatcher<View?>(View::class.java) {
  override fun matchesSafely(target: View?): Boolean {
    if (target !is TextView) {
      return false
    }
    println("Textsize ${target.textSize}")
    return target.textSize.equals(expectedSize)
  }
```

You'll be able to find the appropriate values for other scale sizes too. Hope this helps.

**Review by adhiamboperes — COMMENTED** [review]
I resolved some comments after verifying, and left some that I believe are still valid. PTAL.

File: app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardActivityPresenter.kt (hunk 15 above)
Comment (Vishwajith-Shettigar) [reply app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardActivityPresenter.kt:135]: If we remove  `setReadingTextSizeMedium()` from `line no 135`, option activity and help activity font size will also scale.
Below i have attached screen recording, PTAL.

[OptionActivity.webm](https://github.com/oppia/oppia-android/assets/76042077/c5f6b0f6-f716-4f5f-a68f-5edd640f3942)

File: app/src/sharedTest/java/org/oppia/android/app/topic/revisioncard/RevisionCardFragmentTest.kt (hunk 24 above)
Comment (Vishwajith-Shettigar) [reply app/src/sharedTest/java/org/oppia/android/app/topic/revisioncard/RevisionCardFragmentTest.kt]: Thank you.

File: app/src/main/java/org/oppia/android/app/resumelesson/ResumeLessonActivity.kt (hunk 21 above)
Comment (Vishwajith-Shettigar) [reply app/src/main/java/org/oppia/android/app/resumelesson/ResumeLessonActivity.kt:97]: If we don't set text size medium it will affect the exploration tool bar title text size.

[Resume.webm](https://github.com/oppia/oppia-android/assets/76042077/1615b7e0-fdfb-4235-8f43-46c91c22fb11)

**Comment by Vishwajith-Shettigar** [comment]
@adhiamboperes, Some robolectric tests are failing in CI, but passed locally on espresso.

**Comment by adhiamboperes** [comment]
@Vishwajith-Shettigar, I have looked into these test failures and found that they are not related to size. For example, running:
`testQuestionPlayer_extraLargeTextSize_hasCorrectDimension` fails with the following error:

<details>

<summary>Expand to see full trace</summary>

```
org.oppia.android.app.topic.questionplayer.QuestionPlayerActivityTest > testQuestionPlayer_extraLargeTextSize_hasCorrectDimension FAILED
    androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with id is <org.oppia.android:id/question_recycler_view>

    View Hierarchy:
    +>DecorView{id=-1, visibility=VISIBLE, width=960, height=1410, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params={(0,0)(fillxfill) ty=BASE_APPLICATION wanim=0x7f120005
      fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
      pfl=FORCE_DRAW_STATUS_BAR_BACKGROUND FIT_INSETS_CONTROLLED
      fitSides=}, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1} 
    |
    +->LinearLayout{id=-1, visibility=VISIBLE, width=960, height=1410, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@1517de9e, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2} 
    |
    +-->ViewStub{id=16908719, res-name=action_mode_bar_stub, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@7f1aaec6, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0} 
    |
    +-->FrameLayout{id=-1, visibility=VISIBLE, width=960, height=1410, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@2aa4df4a, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1} 
    |
    +--->FitWindowsLinearLayout{id=2131296310, res-name=action_bar_root, visibility=VISIBLE, width=960, height=1410, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@45adc44f, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2} 
    |
    +---->ViewStubCompat{id=2131296324, res-name=action_mode_bar_stub, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@497f1d3f, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0} 
    |
    +---->ContentFrameLayout{id=16908290, res-name=content, visibility=VISIBLE, width=960, height=1410, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@54379e36, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1} 
    |
    +----->LinearLayout{id=-1, visibility=VISIBLE, width=960, height=1410, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@1fbc610e, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2} 
    |
    +------>AppBarLayout{id=2131297171, res-name=question_player_app_bar_layout, visibility=VISIBLE, width=960, height=168, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@15d982ef, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1} 
    |
    +------->Toolbar{id=2131297173, res-name=question_player_toolbar, visibility=VISIBLE, width=960, height=168, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=com.google.android.material.appbar.AppBarLayout$LayoutParams@3b27291a, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=3} 
    |
    +-------->AppCompatTextView{id=-1, visibility=VISIBLE, width=13, height=41, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.appcompat.widget.Toolbar$LayoutParams@319689ce, tag=null, root-is-layout-requested=false, has-input-connection=false, x=216.0, y=63.0, text=Practice Mode, input-type=0, ime-target=false, has-links=false} 
    |
    +-------->AppCompatImageButton{id=-1, desc=Navigate up, visibility=VISIBLE, width=168, height=168, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=true, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.appcompat.widget.Toolbar$LayoutParams@2032f72, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0} 
    |
    +-------->ActionMenuView{id=-1, visibility=VISIBLE, width=0, height=168, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.appcompat.widget.Toolbar$LayoutParams@605bcc22, tag=null, root-is-layout-requested=false, has-input-connection=false, x=960.0, y=0.0, child-count=0} 
    |
    +------>FrameLayout{id=-1, visibility=VISIBLE, width=960, height=1242, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@676b6bab, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=168.0, child-count=2} 
    |
    +------->FrameLayout{id=2131297172, res-name=question_player_fragment_placeholder, visibility=VISIBLE, width=960, height=1242, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@7c08a08b, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=0} 
    |
    +------->View{id=2131297174, res-name=question_player_toolbar_shadow_view, visibility=VISIBLE, width=960, height=18, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@420c49f4, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0} 
```

</details>


You can see that the main error is the `org.oppia.android:id/question_recycler_view` was not found, and this is what contains the text that is to be tested.  What this tells me is that the assertion happens before the activity loads fully, which means you need to bring the test to a reasonable idle state first before performing any assertions first. `testCoroutineDispatchers.runCurrent()` will give the activity time to load.

Secondly, by restricting the run to robolectric, the `@Config` with device dimensions is not needed.

Lastly, the values you have added as fontsize are most likely correct, and should pass. PTAL.

**Comment by Vishwajith-Shettigar** [comment]
> @Vishwajith-Shettigar, I have looked into these test failures and found that they are not related to size. For example, running: `testQuestionPlayer_extraLargeTextSize_hasCorrectDimension` fails with the following error:
> 
> Expand to see full trace
> You can see that the main error is the `org.oppia.android:id/question_recycler_view` was not found, and this is what contains the text that is to be tested. What this tells me is that the assertion happens before the activity loads fully, which means you need to bring the test to a reasonable idle state first before performing any assertions first. `testCoroutineDispatchers.runCurrent()` will give the activity time to load.
> 
> Secondly, by restricting the run to robolectric, the `@Config` with device dimensions is not needed.
> 
> Lastly, the values you have added as fontsize are most likely correct, and should pass. PTAL.

That's right, but I'm wondering why you mentioned not to configure tests with device dimensions, since we have decided to hard code text sizes for tests and run them on Robolectric with matching configurations.

**Comment by Vishwajith-Shettigar** [comment]
@adhiamboperes PTAL.

File: app/src/sharedTest/java/org/oppia/android/app/topic/revisioncard/RevisionCardFragmentTest.kt [hunk 25]
```diff
@@ -229,6 +231,96 @@ class RevisionCardFragmentTest {
     }
   }
 
+  @Test @Config(qualifiers = "w360dp-h640dp-xxhdpi")
```
Comment (adhiamboperes) [inline app/src/sharedTest/java/org/oppia/android/app/topic/revisioncard/RevisionCardFragmentTest.kt]: Please update the tests in this file as well

File: app/src/sharedTest/java/org/oppia/android/app/topic/questionplayer/QuestionPlayerActivityTest.kt [hunk 26]
```diff
@@ -556,6 +558,77 @@ class QuestionPlayerActivityTest {
     }
   }
 
+  @Test
+  @Config(qualifiers = "w360dp-h640dp-xxhdpi")
```
Comment (adhiamboperes) [inline app/src/sharedTest/java/org/oppia/android/app/topic/questionplayer/QuestionPlayerActivityTest.kt]: Please update these tests too.

File: app/src/sharedTest/java/org/oppia/android/app/resumelesson/ResumeLessonFragmentTest.kt [hunk 27]
```diff
@@ -295,6 +299,62 @@ class ResumeLessonFragmentTest {
     )
   }
 
+  @Test @Config(qualifiers = "w360dp-h640dp-xxhdpi")
```
Comment (adhiamboperes) [inline app/src/sharedTest/java/org/oppia/android/app/resumelesson/ResumeLessonFragmentTest.kt]: Robolectric defines it's own device dimensions if none is provided, and those are consistent for both local and CI runs.

File: app/src/main/java/org/oppia/android/app/resumelesson/ResumeLessonActivity.kt [hunk 28]
```diff
@@ -110,7 +110,6 @@ class ResumeLessonActivity :
   }
 
   override fun onBackPressed() {
-    super.onBackPressed()
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/resumelesson/ResumeLessonActivity.kt]: Why remove this? It is required for the lifycycle method

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
@Vishwajith-Shettigar, PTAL. Also answered your questiion inline.

**Comment by Vishwajith-Shettigar** [comment]
@adhiamboperes, PTAL.

File: model/src/main/proto/arguments.proto [hunk 29]
```diff
@@ -831,6 +843,9 @@ message RevisionCardFragmentArguments {
 
   // The sub topic list size.
   int32 subtopic_list_size = 3;
+
+  // The text size at which content in the resume lesson should be rendered.
```
Comment (adhiamboperes) [inline model/src/main/proto/arguments.proto]:
```suggestion
  // The text size at which content in the revision card should be rendered.
```

File: app/src/main/java/org/oppia/android/app/resumelesson/ResumeLessonFragment.kt [hunk 30]
```diff
@@ -18,7 +19,9 @@ import javax.inject.Inject
 /** Fragment that allows the user to resume a saved exploration. */
 class ResumeLessonFragment : InjectableFragment() {
   companion object {
-    private const val ARGUMENTS_KEY = "ResumeExplorationFragment.arguments"
+
+    /** Arguments key for [ResumeLessonFragment]. */
+    const val ARGUMENTS_KEY = "ResumeExplorationFragment.arguments"
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/resumelesson/ResumeLessonFragment.kt]:
```suggestion
    const val RESUME_LESSON_FRAGMENT_ARGUMENTS_KEY = "ResumeLessonFragment.arguments"
```

There are multiple instances of `ARGUMENTS_KEY` in the codebase, and an incorrect import could lead to errors.

File: app/src/main/java/org/oppia/android/app/topic/questionplayer/QuestionPlayerActivityPresenter.kt [hunk 31]
```diff
@@ -221,4 +281,12 @@ class QuestionPlayerActivityPresenter @Inject constructor(
       TAG_HINTS_AND_SOLUTION_DIALOG
     ) as? HintsAndSolutionDialogFragment
   }
+
+  /** Set reading text size normal. */
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/topic/questionplayer/QuestionPlayerActivityPresenter.kt]:
```suggestion
  /** Set reading text size to normal, which is the default. */
```

This is more clear, as I rember having clarity issues in one of my initial review passes.

File: app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardActivity.kt [hunk 32]
```diff
@@ -112,7 +115,13 @@ class RevisionCardActivity :
     revisionCardActivityPresenter.dismissConceptCard()
   }
 
+  @Deprecated("Deprecated in Java")
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardActivity.kt:119]: Could you please add the TODO with the issue number tracking this?

File: app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardActivityPresenter.kt [hunk 33]
```diff
@@ -24,13 +30,16 @@ import org.oppia.android.util.data.DataProviders.Companion.toLiveData
 import javax.inject.Inject
 
 /** The presenter for [RevisionCardActivity]. */
+@Suppress("DEPRECATION")
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardActivityPresenter.kt]: Please remove this. If a specific function is deprecated, annotate it explicitly and make sure there is a matching TODO to fix it.

File: app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardFragmentPresenter.kt [hunk 34]
```diff
@@ -83,6 +100,23 @@ class RevisionCardFragmentPresenter @Inject constructor(
     return binding.root
   }
 
+  /** Handles the [Fragment.onCreateView] portion of [RevisionCardFragment]'s lifecycle. */
+  fun handleViewCreated() {
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/topic/revisioncard/RevisionCardFragmentPresenter.kt]: Is there a specific reason this cannot be done in `handleCreateView` above?

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @Vishwajith-Shettigar1 I took a full pass and left some cleanup comments.

**Comment by Vishwajith-Shettigar** [comment]
@adhiamboperes, PTAL.

**Review by adhiamboperes — APPROVED** [review]
Thanks @Vishwajith-Shettigar! This looks good to me.

In future, please respond to all reviewer comments.
