### PR TITLE
Fix #2403: Resolve ktlint max line in player test package

### LINKED ISSUE #2403: Resolve ktlint max line in player test package
**Describe the bug**
We are preventing the 100 char length at some places like test case fun name. 
`// ktlint-disable max-line-length`

**Expected behavior**
We need to remove this prevention and fix the function name under 100 char length. 

Where to start?
https://github.com/oppia/oppia-android/blob/d2d55013605d318965594932b9224578cbc9a586/app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt#L291

### PR DESCRIPTION
**Pull request by pravesh00**
## Explanation

Fixes #2403 : Resolve ktlint max line in player test package

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by pravesh00** [comment]
@rt4914 I have tried to reduce the names of fun as much logical with the max limit as I could PTAL and tell me if I can make it better.

File: app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt [hunk 1]
```diff
@@ -352,7 +352,7 @@ class ExplorationActivityTest {
   }
 
   @Test
-  fun testAudioWithNoVoiceover_openPrototypeExploration_checkAudioButtonIsHidden() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt]: No need to change this as this doesn't have 100 char length issue.

File: app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt [hunk 2]
```diff
@@ -367,9 +367,8 @@ class ExplorationActivityTest {
     explorationDataController.stopPlayingExploration()
   }
 
-  // TODO (#1855): Resolve ktlint max line in app module test
   @Test
-  fun testAudioWithNoVoiceover_openPrototypeExploration_configurationChange_checkAudioButtonIsHidden() { // ktlint-disable max-line-length
+  fun testAudioWithNoVoiceover_prototypeExploration_configChange_checkAudioBtnIsHidden() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt]:
```suggestion
  fun testAudioWithNoVoiceover_prototypeExploration_configChange_checkAudioButtonIsHidden() {
```

File: app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt [hunk 3]
```diff
@@ -386,7 +385,7 @@ class ExplorationActivityTest {
   }
 
   @Test
-  fun testAudioWithNoConnection_openRatioExploration_clickAudioIcon_checkOpensNoConnectionDialog() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt]: no change needed

File: app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt [hunk 4]
```diff
@@ -408,7 +407,7 @@ class ExplorationActivityTest {
   }
 
   @Test
-  fun testAudioWithCellular_openRatioExploration_clickAudioIcon_checkOpensCellularAudioDialog() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt]: no change needed

File: app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt [hunk 5]
```diff
@@ -429,9 +428,8 @@ class ExplorationActivityTest {
     explorationDataController.stopPlayingExploration()
   }
 
-  // TODO (#1855): Resolve ktlint max line in app module test
   @Test
-  fun testAudioWithCellular_openRatioExploration_clickAudioIcon_changeConfiguration_checkOpensCellularAudioDialog() { // ktlint-disable max-line-length
+  fun testAudioCell_ratioExploration_audioIcon_changeConfig_opensCellularAudioDialog() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt]:
```suggestion
  fun testAudioCell_ratioExploration_audioIcon_configChange_opensCellularAudioDialog() {
```

File: app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt [hunk 6]
```diff
@@ -453,9 +451,8 @@ class ExplorationActivityTest {
     explorationDataController.stopPlayingExploration()
   }
 
-  // TODO (#1855): Resolve ktlint max line in app module test
   @Test
-  fun testAudioWithCellular_openRatioExploration_clickAudioIcon_clickNegative_checkAudioFragmentIsHidden() { // ktlint-disable max-line-length
+  fun testAudioCell_ratioExploration_audioIcon_clickNegative_checkAudioFragmentIsHidden() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt]:
```suggestion
  fun testAudioCell_ratioExploration_audioIcon_clickNegative_audioFragmentIsHidden() {
```

File: app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt [hunk 7]
```diff
@@ -639,9 +632,8 @@ class ExplorationActivityTest {
     explorationDataController.stopPlayingExploration()
   }
 
-  // TODO (#1855): Resolve ktlint max line in app module test
   @Test
-  fun testAudioWithWifi_openFractionsExploration_changeLanguage_clickNext_checkLanguageIsHinglish() { // ktlint-disable max-line-length
+  fun testAudioWithWifi_fractionsExploration_changeLang_next_langIsHinglish() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt]: we can short the `Exploration` to `Exp` everywhere

File: app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt [hunk 8]
```diff
@@ -730,7 +720,7 @@ class ExplorationActivityTest {
   }
 
   @Test
-  fun testExplorationActivity_loadExplorationFragment_hasDummyString() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt]: no change needed

File: app/src/sharedTest/java/org/oppia/android/app/player/state/StateFragmentTest.kt [hunk 9]
```diff
@@ -247,7 +247,7 @@ class StateFragmentTest {
   }
 
   @Test
-  fun testStateFragment_loadExp_explorationLoads_changeConfiguration_buttonIsNotVisible() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/player/state/StateFragmentTest.kt]: no change needed in this file

**Review by anandwana001 — CHANGES_REQUESTED** [review]
Thanks @pravesh00 

Left suggestions

File: app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt (hunk 7 above)
Comment (pravesh00) [reply app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt]: @anandwana001 Do I need to change this in the fun which doesn't cross the 100 letter limit also to keep consistency?

Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt]: I think it will be good to short only those where we are crossing 100 char limit, else where keep them as it is

**Comment by pravesh00** [comment]
@anandwana001 PTAL

**Comment by anandwana001** [comment]
@pravesh00 Could you please comment on my suggestions with `done` if completed or some comments if any of my comment is not clear.

File: app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt (hunk 1 above)
Comment (pravesh00) [reply app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt]: Done

File: app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt (hunk 3 above)
Comment (pravesh00) [reply app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt]: Done

File: app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt (hunk 4 above)
Comment (pravesh00) [reply app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt]: Done

File: app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt (hunk 5 above)
Comment (pravesh00) [reply app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt]: Done

File: app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt (hunk 6 above)
Comment (pravesh00) [reply app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt]: Done

File: app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt (hunk 7 above)
Comment (pravesh00) [reply app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt]: Done

File: app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt (hunk 8 above)
Comment (pravesh00) [reply app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt]: Done

File: app/src/sharedTest/java/org/oppia/android/app/player/state/StateFragmentTest.kt (hunk 9 above)
Comment (pravesh00) [reply app/src/sharedTest/java/org/oppia/android/app/player/state/StateFragmentTest.kt]: Done

File: app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt [hunk 10]
```diff
@@ -694,12 +686,10 @@ class ExplorationActivityTest {
     explorationDataController.stopPlayingExploration()
   }
 
-  // TODO (#1855): Resolve ktlint max line in app module test
   // TODO(#89): The ExplorationActivity takes time to finish. This test case is failing currently.
   @Test
   @Ignore("The ExplorationActivity takes time to finish, needs to fixed in #89.")
-  fun testAudioWithWifi_openRatioExploration_continueToInteraction_clickAudioButton_submitAnswer_checkFeedbackAudioPlays() { // ktlint-disable max-line-length
-    getApplicationDependencies(RATIOS_EXPLORATION_ID_0)
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt:702]: Why are we removing this line? This is something test required, we should not remove this. 

`getApplicationDependencies(RATIOS_EXPLORATION_ID_0)`

**Review by anandwana001 — CHANGES_REQUESTED** [review]

File: app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt (hunk 10 above)
Comment (pravesh00) [reply app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt:702]: Done

**Comment by pravesh00** [comment]
@anandwana001 PTAL

File: app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt [hunk 11]
```diff
@@ -429,9 +428,8 @@ class ExplorationActivityTest {
     explorationDataController.stopPlayingExploration()
   }
 
-  // TODO (#1855): Resolve ktlint max line in app module test
   @Test
-  fun testAudioWithCellular_openRatioExploration_clickAudioIcon_changeConfiguration_checkOpensCellularAudioDialog() { // ktlint-disable max-line-length
+  fun testAudioCell_ratioExploration_audioIcon_configChange_opensCellularAudioDialog() {
```
Comment (rt4914) [inline app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt]: Suggestion:
Instead of `Cell` use `Cellular` and as an adjustment we can use `ratioExp`.
`testAudioCellular_ratioExp_audioIcon_configChange_opensCellularAudioDialog `

File: app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt [hunk 12]
```diff
@@ -453,9 +451,8 @@ class ExplorationActivityTest {
     explorationDataController.stopPlayingExploration()
   }
 
-  // TODO (#1855): Resolve ktlint max line in app module test
   @Test
-  fun testAudioWithCellular_openRatioExploration_clickAudioIcon_clickNegative_checkAudioFragmentIsHidden() { // ktlint-disable max-line-length
+  fun testAudioCell_ratioExploration_audioIcon_clickNegative_audioFragmentIsHidden() {
```
Comment (rt4914) [inline app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt]: Ditto change

File: app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt [hunk 13]
```diff
@@ -486,9 +483,8 @@ class ExplorationActivityTest {
     explorationDataController.stopPlayingExploration()
   }
 
-  // TODO (#1855): Resolve ktlint max line in app module test
   @Test
-  fun testAudioWithCellular_openRatioExploration_clickAudioIcon_clickPositive_checkAudioFragmentIsVisible() { // ktlint-disable max-line-length
+  fun testAudioCell_ratioExp_audioIcon_clickPositive_checkAudioFragmentIsVisible() {
```
Comment (rt4914) [inline app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt]: Ditto change

File: app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt [hunk 14]
```diff
@@ -528,9 +524,8 @@ class ExplorationActivityTest {
     explorationDataController.stopPlayingExploration()
   }
 
-  // TODO (#1855): Resolve ktlint max line in app module test
   @Test
-  fun testAudioWithCellular_openRatioExploration_clickCheckboxAndNegative_clickAudioIcon_checkAudioFragmentIsHiddenAndDialogIsNotDisplayed() { // ktlint-disable max-line-length
+  fun testAudioCell_ratioExp_check_negative_audioIcon_audioFragHiddenDialogNotDisplay() {
```
Comment (rt4914) [inline app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt]: Ditto change

File: app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt [hunk 15]
```diff
@@ -565,9 +560,8 @@ class ExplorationActivityTest {
     explorationDataController.stopPlayingExploration()
   }
 
-  // TODO (#1855): Resolve ktlint max line in app module test
   @Test
-  fun testAudioWithCellular_openRatioExploration_clickCheckboxAndPositive_clickAudioIconTwice_checkAudioFragmentIsVisibleAndDialogIsNotDisplayed() { // ktlint-disable max-line-length
+  fun testAudioCell_ratioExp_checkPositive_audioIconTwice_audioFragVisDialogNotDisplay() {
```
Comment (rt4914) [inline app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt]: Ditto change.

**Review by rt4914 — CHANGES_REQUESTED** [review]
@pravesh00 Suggested changes.

File: app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt (hunk 11 above)
Comment (pravesh00) [reply app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt]: Done

File: app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt (hunk 12 above)
Comment (pravesh00) [reply app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt]: Done

File: app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt (hunk 13 above)
Comment (pravesh00) [reply app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt]: Done

File: app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt (hunk 14 above)
Comment (pravesh00) [reply app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt]: Done

File: app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt (hunk 15 above)
Comment (pravesh00) [reply app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt]: Done

**Comment by pravesh00** [comment]
@rt4914 PTAL

**Review by rt4914 — APPROVED** [review]
LGTM

**Review by anandwana001 — APPROVED** [review]
LGTM
