### PR TITLE
Fix #1287: Fix lint issues in app module in the kotlin files #1287

### LINKED ISSUE #1287: Fix lint issues in app module in the kotlin files
Fix lint issues in kotlin files in the app module. Take the feature with its respective test folder and create sub pr for them.  

- [x] activity

- [x] administratorcontrols

- [x] application

- [x] completedstorylist

- [x] customview

- [x] databinding

- [x] drawer

- [x] fragment

- [x] help

- [x] home **(blocked)**

- [x] mydownloads

- [x] onboarding

- [x] ongoingtopiclist

- [x] options

- [x] parser 

- [x] player **(blocked)**

- [x] profile

- [x] profileprogress

- [x] recyclerview

- [x] settings/profile

- [x] splash

- [x] story

- [x] testing

- [x] topic 
    - [x] conceptcard, info, questionplayer
    - [x]  lessons, practice
    - [x] revision, revisioncard, outside files

- [x] topic shared test 

- [x] utility

- [x] view

- [x] viewmodel

- [x] walkthrough

### PR DESCRIPTION
**Pull request by anandwana001**
## Explanation

Fix #1287 

## Checklist

- [ ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [ ] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [ ] The PR is made from a branch that's **not** called "develop".
- [ ] The PR is made from a branch that is up-to-date with "develop".
- [ ] The PR's branch is based on "develop" and not on any other branch.
- [ ] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

File: app/src/main/java/org/oppia/app/hintsandsolution/HintsAndSolutionAdapter.kt [hunk 1]
```diff
@@ -132,7 +135,9 @@ class HintsAndSolutionAdapter(
               position
             }
           expandedHintListIndexListener.onExpandListIconClicked(currentExpandedHintListIndex)
-          if (previousIndex != null && currentExpandedHintListIndex != null && previousIndex == currentExpandedHintListIndex) {
+          if (previousIndex != null && currentExpandedHintListIndex != null &&
+            previousIndex == currentExpandedHintListIndex
```
Comment (rt4914) [inline app/src/main/java/org/oppia/app/hintsandsolution/HintsAndSolutionAdapter.kt:140]: Nit here and below:
```
          if (previousIndex != null 
            && currentExpandedHintListIndex != null 
            && previousIndex == currentExpandedHintListIndex
```

File: app/src/main/java/org/oppia/app/hintsandsolution/HintsAndSolutionAdapter.kt [hunk 2]
```diff
@@ -188,7 +193,9 @@ class HintsAndSolutionAdapter(
...
```
Comment (rt4914) [inline app/src/main/java/org/oppia/app/hintsandsolution/HintsAndSolutionAdapter.kt:199]: Ditto

File: app/src/main/java/org/oppia/app/home/recentlyplayed/RecentlyPlayedFragmentPresenter.kt [hunk 3]
```diff
@@ -149,20 +158,29 @@ class RecentlyPlayedFragmentPresenter @Inject constructor(
...
+            result.getErrorOrNull()!!
+          )
+          else -> {
+            logger.d("RecentlyPlayedFragment", "Successfully loaded exploration")
+            routeToExplorationListener.routeToExploration(
+              internalProfileId,
+              topicId,
+              storyId,
+              explorationId, /* backflowScreen = */
+              null
```
Comment (rt4914) [inline app/src/main/java/org/oppia/app/home/recentlyplayed/RecentlyPlayedFragmentPresenter.kt]: Nit:
`/* backflowScreen = */ null`

**Review by rt4914 — CHANGES_REQUESTED** [review]
Great work @anandwana001 . Suggested some nit changes.

File: app/src/main/java/org/oppia/app/hintsandsolution/HintsAndSolutionAdapter.kt (hunk 1 above)
Comment (anandwana001) [reply app/src/main/java/org/oppia/app/hintsandsolution/HintsAndSolutionAdapter.kt:140]: ktlint says line cannot start with `&&`
`Line must not begin with "&&"`

File: app/src/main/java/org/oppia/app/hintsandsolution/HintsAndSolutionAdapter.kt (hunk 2 above)
Comment (anandwana001) [reply app/src/main/java/org/oppia/app/hintsandsolution/HintsAndSolutionAdapter.kt:199]: ktlint says line cannot start with `&&`
`Line must not begin with "&&"`

File: app/src/main/java/org/oppia/app/home/recentlyplayed/RecentlyPlayedFragmentPresenter.kt (hunk 3 above)
Comment (anandwana001) [reply app/src/main/java/org/oppia/app/home/recentlyplayed/RecentlyPlayedFragmentPresenter.kt]: Done

File: app/src/main/java/org/oppia/app/hintsandsolution/HintsAndSolutionAdapter.kt (hunk 1 above)
Comment (rt4914) [reply app/src/main/java/org/oppia/app/hintsandsolution/HintsAndSolutionAdapter.kt:140]: Then it should be:
```
          if (previousIndex != null &&
            currentExpandedHintListIndex != null &&
            previousIndex == currentExpandedHintListIndex
```

Comment (vinitamurthi) [reply app/src/main/java/org/oppia/app/hintsandsolution/HintsAndSolutionAdapter.kt:140]: You can put the && at the end of the line instead then
i.e.  
```
if (previousIndex != null &&
    currentExpandedHintListIndex != null && 
    previousIndex == currentExpandedHintListIndex
```

File: app/src/main/java/org/oppia/app/hintsandsolution/HintsAndSolutionAdapter.kt (hunk 2 above)
Comment (vinitamurthi) [reply app/src/main/java/org/oppia/app/hintsandsolution/HintsAndSolutionAdapter.kt:199]: Same comment as above

File: app/src/main/java/org/oppia/app/home/recentlyplayed/OngoingListAdapter.kt [hunk 4]
```diff
@@ -78,7 +77,8 @@ class OngoingListAdapter(
               (activity as Context).resources.getDimensionPixelSize(R.dimen.margin_28)
             }
           } else {
-            (activity as Context).resources.getDimensionPixelSize(R.dimen.margin_28)//this will be updated in next PR
+            // this will be updated in next PR
```
Comment (vinitamurthi) [inline app/src/main/java/org/oppia/app/home/recentlyplayed/OngoingListAdapter.kt]: Not entirely related to your PR but since you are changing this, can you create an issue for this if this is not fixed already. Or if it is fixed then we can remove this comment. Generally we shouldn't write such comments. If something needs to be done in the future we should create an issue for it and write it as `// TODO(issueNum):...`

File: app/src/main/java/org/oppia/app/player/exploration/ExplorationActivity.kt [hunk 5]
```diff
@@ -22,9 +22,13 @@ private const val TAG_STOP_EXPLORATION_DIALOG = "STOP_EXPLORATION_DIALOG"
 const val TAG_HINTS_AND_SOLUTION_DIALOG = "HINTS_AND_SOLUTION_DIALOG"
 
 /** The starting point for exploration. */
-class ExplorationActivity : InjectableAppCompatActivity(), StopStatePlayingSessionListener,
+class ExplorationActivity :
+  InjectableAppCompatActivity(),
+  StopStatePlayingSessionListener,
```
Comment (vinitamurthi) [inline app/src/main/java/org/oppia/app/player/exploration/ExplorationActivity.kt:27]: Does ktlint catch these? I am guessing it doesn't because I dont recall whether it does. If it doesn't , maybe let's consider adding a custom check for this (i.e. parameters in new lines for params that span multiple lines) Can you create an issue for this?

File: app/src/sharedTest/java/org/oppia/app/parser/HtmlParserTest.kt [hunk 6]
```diff
@@ -99,36 +99,54 @@ class HtmlParserTest {
...
-          "fraction of the cake has big red cherries in the pineapple slices?\u003c/p\u003e",
+      "\u003cp\u003e\"Let's try one last question,\" said Mr. Baker. \"Here's a " +
+        "pineapple cake cut into pieces.\"\u003c/p\u003e\u003coppia-noninteractive-image " +
+        "alt-with-value=\"\u0026amp;quot;Pineapple" +
+        " cake with 7/9 having cherries.\u0026amp;quot;\" caption-with-value=\"\u0026amp;quot;" +
+        "\u0026amp;quot;\" filepath-with-value=\"\u0026amp;quot;" +
+        "pineapple_cake_height_479_width_480.png\u0026amp;quot;\"\u003e\u003c/" +
+        "oppia-noninteractive-image\u003e\u003cp\u003e\u00a0\u003c/p\u003e\u003cp" +
+        "\u003e\u003cstrong\u003eQuestion 6\u003c/strong\u003e: What " +
+        "fraction of the cake has big red cherries in the pineapple slices?\u003c/p\u003e",
```
Comment (vinitamurthi) [inline app/src/sharedTest/java/org/oppia/app/parser/HtmlParserTest.kt:120]: Thank you for doing this :)

**Review by vinitamurthi — APPROVED** [review]
Small things here and there but overall this is great. Thank you so much @anandwana001, this basically unblocks linting completely and is a great milestone for code quality in the project!

File: app/src/main/java/org/oppia/app/home/recentlyplayed/OngoingListAdapter.kt (hunk 4 above)
Comment (anandwana001) [reply app/src/main/java/org/oppia/app/home/recentlyplayed/OngoingListAdapter.kt]: For this, I guess I had to confirm with the team like who has put this and take action accordingly.

Comment (vinitamurthi) [reply app/src/main/java/org/oppia/app/home/recentlyplayed/OngoingListAdapter.kt]: Yeah just check with whoever wrote this piece of code and add an issue instead of this comment (You can do this in another PR because its not related to linting at all)

File: app/src/main/java/org/oppia/app/hintsandsolution/HintsAndSolutionAdapter.kt (hunk 1 above)
Comment (anandwana001) [reply app/src/main/java/org/oppia/app/hintsandsolution/HintsAndSolutionAdapter.kt:140]: Sounds good

Comment (anandwana001) [reply app/src/main/java/org/oppia/app/hintsandsolution/HintsAndSolutionAdapter.kt:140]: Done

File: app/src/main/java/org/oppia/app/hintsandsolution/HintsAndSolutionAdapter.kt (hunk 2 above)
Comment (anandwana001) [reply app/src/main/java/org/oppia/app/hintsandsolution/HintsAndSolutionAdapter.kt:199]: Done

File: app/src/main/java/org/oppia/app/home/recentlyplayed/OngoingListAdapter.kt (hunk 4 above)
Comment (anandwana001) [reply app/src/main/java/org/oppia/app/home/recentlyplayed/OngoingListAdapter.kt]: Discussed with Rajat and removed this line

File: app/src/main/java/org/oppia/app/player/exploration/ExplorationActivity.kt (hunk 5 above)
Comment (anandwana001) [reply app/src/main/java/org/oppia/app/player/exploration/ExplorationActivity.kt:27]: Is it like if there are multiple things separated by `,` it should be all in new line?

File: app/src/sharedTest/java/org/oppia/app/parser/HtmlParserTest.kt (hunk 6 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/app/parser/HtmlParserTest.kt:120]: You're Welcome :)

**Review by rt4914 — APPROVED** [review]

File: app/src/sharedTest/java/org/oppia/app/parser/HtmlParserTest.kt (hunk 6 above)
Comment (rt4914) [reply app/src/sharedTest/java/org/oppia/app/parser/HtmlParserTest.kt:120]: Resolving this on behalf of @vinitamurthi

File: app/src/main/java/org/oppia/app/home/recentlyplayed/OngoingListAdapter.kt (hunk 4 above)
Comment (rt4914) [reply app/src/main/java/org/oppia/app/home/recentlyplayed/OngoingListAdapter.kt]: Resolving this on behalf of @vinitamurthi

File: app/src/main/java/org/oppia/app/player/exploration/ExplorationActivity.kt (hunk 5 above)
Comment (vinitamurthi) [reply app/src/main/java/org/oppia/app/player/exploration/ExplorationActivity.kt:27]: No it's more that if a function call is spread across multiple lines then each param should be in a single line
