### PR TITLE
Fixes #4132: Added tests for MathParsingErrorSubject.

### LINKED ISSUE #4132: Add tests for MathParsingErrorSubject
#4052 introduces a new custom Truth test subject: MathParsingErrorSubject. It would be advantageous to add thorough tests for this to ensure that:
- Each of the subject methods correctly allow users to test specific properties
- Each of the subject methods are verified to fail when expected with the correct failure reason being verified

See #4097 for a similar issue.

### PR DESCRIPTION
**Pull request by theayushyadav11**
Fixes #4132:
This pull request focuses on adding comprehensive tests for the `MathParsingErrorSubject` class and making necessary adjustments to the related files. The most important changes include the removal of an exemption for `MathParsingErrorSubject.kt`, the addition of a new test file for `MathParsingErrorSubject`, and the creation of a corresponding Bazel test target.

### Test Enhancements:

* [`testing/src/main/java/org/oppia/android/testing/math/MathParsingErrorSubject.kt`](diffhunk://#diff-c53693be09949f0e5f37517762c04d2ac4f8eb09049987bfcfcaca1243d51d3aL46-L47): Removed the TODO comment indicating the need for tests.
* [`testing/src/test/java/org/oppia/android/testing/math/MathParsingErrorSubjectTest.kt`](diffhunk://#diff-1110331e8184259d41c97f5541a1ab1b71ec94e2942f49e0b6c7df0533bd049eR1-R293): Added a new test file containing various unit tests for the `MathParsingErrorSubject` class.

### Configuration Updates:

* [`testing/src/test/java/org/oppia/android/testing/math/BUILD.bazel`](diffhunk://#diff-8a86bceb0e654069d42dcb4e76a52f65aeea3bc7d76a9cdff53f5e4bdde93f08R70-R85): Added a new Bazel test target for `MathParsingErrorSubjectTest`.

### Cleanup:

* [`scripts/assets/test_file_exemptions.textproto`](diffhunk://#diff-6ed782dd71126d847e7bac39eca30f830be55b72aa10b7e944612f2463003e24L4105-L4108): Removed the test file exemption for `MathParsingErrorSubject.kt`.

#### Screenshot of the pasing tests:
Screenshot from 2025-02-01 19-58-33

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

### CODE REVIEW

**Comment by theayushyadav11** [comment]
Hi @adhiamboperes PTAL!, and please suggest any changes which are to be made.

**Comment by theayushyadav11** [comment]
Hi @adhiamboperes , this PR is ready for review PTAL.

File: testing/src/test/java/org/oppia/android/testing/math/MathParsingErrorSubjectTest.kt [hunk 1]
```diff
@@ -0,0 +1,293 @@
...
+  @Test
+  fun testMathParsingErrorSubject_hasUnbalancedParenthesesError_fails() {
+    val error = SpacesBetweenNumbersError
+    assertThrows(AssertionError::class.java) {
+      MathParsingErrorSubject.assertThat(error).isUnbalancedParentheses()
+    }
+  }
+
+  @Test
+  fun testMathParsingErrorSubject_hasSingleRedundantParentheses() {
```
Comment (adhiamboperes) [inline testing/src/test/java/org/oppia/android/testing/math/MathParsingErrorSubjectTest.kt]:
```suggestion
  fun testMathParsingErrorSubject_hasSingleRedundantParenthesesWitDetails() {
```

File: testing/src/test/java/org/oppia/android/testing/math/MathParsingErrorSubjectTest.kt [hunk 2]
```diff
@@ -0,0 +1,293 @@
...
+      .setConstant(constant)
+      .build()
+    val group = MathExpression.newBuilder()
+      .setGroup(expression)
+      .build()
+    val error = SingleRedundantParenthesesError("(5)", group)
+    val subject = MathParsingErrorSubject.assertThat(error).isSingleRedundantParenthesesThat()
+    subject.hasExpressionThat().evaluatesToIntegerThat().isEqualTo(5)
+    subject.hasRawExpressionThat().isEqualTo("(5)")
+  }
```
Comment (adhiamboperes) [inline testing/src/test/java/org/oppia/android/testing/math/MathParsingErrorSubjectTest.kt]: This and the test below can be better structure following the example usage set in https://github.com/oppia/oppia-android/blob/38419bf486fa487be19f08e668c58911413ec6cb/utility/src/test/java/org/oppia/android/util/math/MathExpressionParserTest.kt#L201

File: testing/src/test/java/org/oppia/android/testing/math/MathParsingErrorSubjectTest.kt [hunk 3]
```diff
@@ -0,0 +1,293 @@
...
+
+  @Test
+  fun testMathParsingErrorSubject_isNumberAfterVariableError() {
+    val number = Real.newBuilder().setInteger(5).build()
+    val error = NumberAfterVariableError(number, "x")
+    val subject = MathParsingErrorSubject.assertThat(error).isNumberAfterVariableThat()
+    subject.hasNumberThat().isIntegerThat().isEqualTo(5)
+    subject.hasVariableThat().isEqualTo("x")
+  }
```
Comment (adhiamboperes) [inline testing/src/test/java/org/oppia/android/testing/math/MathParsingErrorSubjectTest.kt]: Here and all tests below: It is not clear why you are creating the `subject` variable since it is not being used. Assertions are independent expressions and should not be assigned to a variable.

```suggestion
    val subject = MathParsingErrorSubject.assertThat(error).isNumberAfterVariableThat().apply {
    hasNumberThat().isIntegerThat().isEqualTo(5)
    hasVariableThat().isEqualTo("x")
    }
  }
```

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @theayushyadav11! PTAL at the requested changes.

**Comment by theayushyadav11** [comment]
Hi @adhiamboperes,  
Thank you for your review! I have addressed all your comments and updated the code accordingly. 
PTAL!

**Review by adhiamboperes — APPROVED** [review]
LGTM, thanks @theayushyadav11!
