### PR TITLE
Fix #2592 : Rectify open navigation drawer from exploration

### LINKED ISSUE #2592: Open Navigation Drawer from Exploration
**Describe the bug**

**To Reproduce**
1. Go to 'exploration'
2. Click on 'option button' in top right of screen
3. Select 'Options' or 'Help'
4. Slide on screen to right ( so you can open Navigation Drawer)

**Expected behavior**
Navigation Drawer should not be operated from Exploration Activity because on Opening Navigation Drawer we can go to Home and which leads to the app-crash
**Screenshots**
https://user-images.githubusercontent.com/44704035/106388962-d8835880-6406-11eb-8008-c47a3a6078b8.mp4

### PR DESCRIPTION
**Pull request by chrk2205**
Fixes #2592  

## Explanation
Implemented the idea mentioned in the issue conversation

The options and help fragment has navigation drawer which can be accessed on swiping right also.
these both fragments can be opened from exploration too, when it is opened not from Navigation drawer, the navigation drawer should not be accessable. 
So to remove the navigation drawer,  I created duplicate XML files without drawer and used it at the particular instance.

OptionsFragmentTest
image
image

HelpFragmentTest
image
image

## Checklist

- [ ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by rt4914** [comment]
@chrk2205 Will review it tomorrow. Thanks.

File: app/src/main/java/org/oppia/android/app/options/OptionsActivityPresenter.kt [hunk 1]
```diff
@@ -25,7 +25,11 @@ class OptionsActivityPresenter @Inject constructor(
     isFirstOpen: Boolean,
     selectedFragment: String
   ) {
-    activity.setContentView(R.layout.option_activity)
+    if (isFromNavigationDrawer) {
```
Comment (rt4914) [inline app/src/main/java/org/oppia/android/app/options/OptionsActivityPresenter.kt:28]: This code should be merged with the `if` condition in line `39`

File: app/src/main/java/org/oppia/android/app/help/HelpActivityPresenter.kt [hunk 2]
```diff
@@ -16,11 +16,13 @@ class HelpActivityPresenter @Inject constructor(private val activity: AppCompatA
...
   fun handleOnCreate(isFromNavigationDrawer: Boolean) {
-    activity.setContentView(R.layout.help_activity)
-    setUpToolbar()
     if (isFromNavigationDrawer) {
+      activity.setContentView(R.layout.help_activity)
+      setUpToolbar()
       setUpNavigationDrawer()
     } else {
+      activity.setContentView(R.layout.help_without_drawer_activity)
+      setUpToolbar()
```
Comment (rt4914) [inline app/src/main/java/org/oppia/android/app/help/HelpActivityPresenter.kt:25]: `setUpToolbar` function is comment and therefore can be pulled out.

**Review by rt4914 — CHANGES_REQUESTED** [review]
@chrk2205 Suggested nit change.

File: app/src/main/java/org/oppia/android/app/help/HelpActivityPresenter.kt (hunk 2 above)
Comment (chrk2205) [reply app/src/main/java/org/oppia/android/app/help/HelpActivityPresenter.kt:25]: @rt4914 
we cannot pull it up because without  `setContentView` we cannot call `setupToolbar` as this function uses the view attribute.
without setting the content view we cannot call it.

and also we cannot pull It down because the following up functions cannot be called before `setuptollbar` function.

File: app/src/main/java/org/oppia/android/app/options/OptionsActivityPresenter.kt (hunk 1 above)
Comment (chrk2205) [reply app/src/main/java/org/oppia/android/app/options/OptionsActivityPresenter.kt:28]: @rt4914 
it will look like this similar to `helppresenter`
` if (isFromNavigationDrawer) {
      activity.setContentView(R.layout.option_activity)
      setUpToolbar()
      setUpNavigationDrawer()
    } else {
      setUpToolbar()
      activity.setContentView(R.layout.options_without_drawer_activity)
      activity.supportActionBar!!.setDisplayHomeAsUpEnabled(true)
      toolbar.setNavigationOnClickListener {
        activity.finish()
      }
    }`

**Comment by chrk2205** [comment]
@rt4914 
how should I write the test cases for this issue??
about the slide to open nav drawer.?

File: app/src/main/java/org/oppia/android/app/options/OptionsActivityPresenter.kt (hunk 1 above)
Comment (rt4914) [reply app/src/main/java/org/oppia/android/app/options/OptionsActivityPresenter.kt:28]: @chrk2205 The above comment is not that readable. Can you answer my suggestion is doable or not?

File: app/src/main/java/org/oppia/android/app/help/HelpActivityPresenter.kt (hunk 2 above)
Comment (rt4914) [reply app/src/main/java/org/oppia/android/app/help/HelpActivityPresenter.kt:25]: Yes I understand that but can't we take this outside but below the `if-else` condition?

**Comment by rt4914** [comment]
> @rt4914
> how should I write the test cases for this issue??
> about the slide to open nav drawer.?

@chrk2205 That would actually be nice. But I am not sure how can you write test case for sliding action. Adding @anandwana001 for assistance.

@anandwana001 : Check the issue in this PR. To write a test case for this bug we will need to do open a navigation drawer by `swipe` gesture . How can that be done?

File: app/src/main/java/org/oppia/android/app/options/OptionsActivityPresenter.kt (hunk 1 above)
Comment (chrk2205) [reply app/src/main/java/org/oppia/android/app/options/OptionsActivityPresenter.kt:28]: it is doable 
it looks similar to in `helpActivityPresenter` ( above changed file ).

File: app/src/main/java/org/oppia/android/app/help/HelpActivityPresenter.kt (hunk 2 above)
Comment (chrk2205) [reply app/src/main/java/org/oppia/android/app/help/HelpActivityPresenter.kt:25]: @rt4914 
no, we cannot take it outside as `setupNaviagtionDrawer`  ( line 22 ) cannot be called before `setupToolbar`.

**Comment by anandwana001** [comment]
@chrk2205 

for swiping we need to use 
```kotlin
import androidx.test.espresso.action.ViewActions.swipeLeft
or
import androidx.test.espresso.action.ViewActions.swipeRight
```

The above one might act as a first step, but we need a custom function to have a long swipe action to open the drawer. 
```kotlin
private fun ActivityScenario<NavigationDrawerTestActivity>.swipeOpenNavigationDrawer() {
    onView(withContentDescription(R.string.drawer_open_content_description))
      .check(matches(isCompletelyDisplayed()))
      .perform(swipeRight())

    // Force the drawer animation to start. See https://github.com/oppia/oppia-android/pull/2204 for
    // background context.
    onActivity { activity ->
      val drawerLayout =
        activity.findViewById<DrawerLayout>(R.id.home_activity_drawer_layout)
      // Note that this only initiates a single computeScroll() in Robolectric. Normally, Android
      // will compute several of these across multiple draw calls, but one seems sufficient for
      // Robolectric. Note that Robolectric is also *supposed* to handle the animation loop one call
      // to this method initiates in the view choreographer class, but it seems to not actually
      // flush the choreographer per observation. In Espresso, this method is automatically called
      // during draw (and a few other situations), but it's fine to call it directly once to kick it
      // off (to avoid disparity between Espresso/Robolectric runs of the tests).
      // NOTE TO DEVELOPERS: if this ever flakes, we can probably put this in a loop with fake time
      // adjustments to simulate the render loop.
      drawerLayout.computeScroll()
    }

    // Wait for the drawer to fully open (mostly for Espresso since Robolectric should synchronously
    // stabilize the drawer layout after the previous logic completes).
    testCoroutineDispatchers.runCurrent()
  }

// need to update this custom to have a long swipe from left to right by calculating view coordinates and passing at 2nd adn 3rd parameter
  fun swipeRight(): ViewAction? {
    return ViewActions.actionWithAssertions(
      GeneralSwipeAction(
        Swipe.SLOW, // Swipe.FAST,
        GeneralLocation.CENTER_LEFT,
        GeneralLocation.CENTER_RIGHT,
        Press.FINGER
      )
    )
```

**Comment by chrk2205** [comment]
@rt4914 
As we are removing the whole navigation drawer fragment we can simply check if that fragment exists or not instead of swipe left.
Is this okay?

**Comment by anandwana001** [comment]
Sounds good to me. 
    
It's simply checking if a view is present in the view hierarchy or not, so we can use `check(doesNotExist())`

**Comment by rt4914** [comment]
> @rt4914
> As we are removing the whole navigation drawer fragment we can simply check if that fragment exists or not instead of swipe left.
> Is this okay?

@chrk2205 Sounds good to me.

File: app/src/main/java/org/oppia/android/app/help/HelpActivityPresenter.kt (hunk 2 above)
Comment (rt4914) [reply app/src/main/java/org/oppia/android/app/help/HelpActivityPresenter.kt:25]: Ack.

File: app/src/main/java/org/oppia/android/app/options/OptionsActivityPresenter.kt (hunk 1 above)
Comment (rt4914) [reply app/src/main/java/org/oppia/android/app/options/OptionsActivityPresenter.kt:28]: Thanks.

**Comment by chrk2205** [comment]
@anandwana001 
check(doesNotExist()) 
Is not working. I mean the test case is getting failed .

**Comment by anandwana001** [comment]
Did you tried not displayed or anything else?

File: app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt [hunk 3]
```diff
@@ -16,6 +16,7 @@ import androidx.test.espresso.assertion.ViewAssertions.doesNotExist
 import androidx.test.espresso.assertion.ViewAssertions.matches
 import androidx.test.espresso.intent.Intents
 import androidx.test.espresso.matcher.ViewMatchers.isCompletelyDisplayed
+import androidx.test.espresso.matcher.ViewMatchers.isDisplayed
```
Comment (chrk2205) [inline app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt]: this should be removed

File: app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt [hunk 4]
```diff
@@ -30,6 +31,7 @@ import org.junit.Before
 import org.junit.Rule
 import org.junit.Test
 import org.junit.runner.RunWith
+import org.mockito.AdditionalMatchers.not
```
Comment (chrk2205) [inline app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt]: this one should be removed

**Comment by chrk2205** [comment]
@rt4914 
@anandwana001 
`doesNotExist()` worked. thankyou.
PTAL.

**Comment by anandwana001** [comment]
@chrk2205 

1. Could you please take the latest pull from the latest develop branch and complete the installation steps, especially the script running part? - https://github.com/oppia/oppia-android/wiki#installation
2. Why the `doesNotExist()` is not working earlier and what changes had been done to make it work now? This will be helpful to understand what sort of things are breaking the usage of `doesNotExist()`.

**Comment by chrk2205** [comment]
> @chrk2205
> 
> 1. Could you please take the latest pull from the latest develop branch and complete the installation steps, especially the script running part? - https://github.com/oppia/oppia-android/wiki#installation
> 2. Why the `doesNotExist()` is not working earlier and what changes had been done to make it work now? This will be helpful to understand what sort of things are breaking the usage of `doesNotExist()`.

I updated the branch and pushed after Klint checks
sorry about that 
@anandwana001 
`doesNotExist()` was working 
what happened was the activity was crashing because of a commented line.

**Comment by chrk2205** [comment]
@anandwana001 
PTAL

**Comment by anandwana001** [comment]
@chrk2205 Could you give bit of details on questions here, helps me to give more context. 
https://github.com/oppia/oppia-android/pull/2789#issuecomment-793745367

**Comment by chrk2205** [comment]
@anandwana001 

2. When the tests were running there was a commented line in the original fragment. because of it the application was crashing and also it was the reason of failed test case. When the code was cleared out then all the test cases passed.

**Comment by rt4914** [comment]
Assigning to @anandwana001 for test case part. Once it is approved please assign it back to me.

**Comment by anandwana001** [comment]
> @anandwana001
> 
> 1. When the tests were running there was a commented line in the original fragment. because of it the application was crashing and also it was the reason of failed test case. When the code was cleared out then all the test cases passed.

Could you mention which lines are these.

File: app/src/main/java/org/oppia/android/app/help/HelpActivityPresenter.kt [hunk 5]
```diff
@@ -16,11 +16,13 @@ class HelpActivityPresenter @Inject constructor(private val activity: AppCompatA
...
 
   fun handleOnCreate(isFromNavigationDrawer: Boolean) {
-    activity.setContentView(R.layout.help_activity)
-    setUpToolbar()
     if (isFromNavigationDrawer) {
+      activity.setContentView(R.layout.help_activity)
+      setUpToolbar()
       setUpNavigationDrawer()
     } else {
+      activity.setContentView(R.layout.help_without_drawer_activity)
```
Comment (chrk2205) [inline app/src/main/java/org/oppia/android/app/help/HelpActivityPresenter.kt:24]: @anandwana001 this is the line that was commented while testing
as there was no layout set the `doesnotexist()`  was not working ( null returned while testing).

**Comment by anandwana001** [comment]
I will take a look at this today later.

**Comment by chrk2205** [comment]
@anandwana001 
PTAL

File: app/src/sharedTest/java/org/oppia/android/app/help/HelpFragmentTest.kt [hunk 6]
```diff
@@ -126,6 +126,14 @@ class HelpFragmentTest {
     }
   }
 
+  @Test
+  fun testHelpFragment_notFromNavigationDrawer_navigationDrawerIsNotPresent() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/help/HelpFragmentTest.kt:130]: Also add one more test for this 

```kotlin
fun testHelpFragment_notFromNavigationDrawer_configChange_navigationDrawerIsNotPresent()
```

File: app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt [hunk 7]
```diff
@@ -151,6 +151,14 @@ class OptionsFragmentTest {
     }
   }
 
+  @Test
+  fun testOptionFragment_notFromNavigationDrawer_navigationDrawerIsNotPresent() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt:157]: Also, add one more test for this.

```kotlin
fun testOptionFragment_notFromNavigationDrawer_configChange_navigationDrawerIsNotPresent()
```

**Review by anandwana001 — CHANGES_REQUESTED** [review]
Thanks, @chrk2205  
LGTM, tests are passing on both espresso and robolectric for me. Nit update added.  
Also, please fix the PR title.  

re-running checks now.

File: app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt (hunk 7 above)
Comment (chrk2205) [reply app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt:157]: I will update it tommorow.

**Comment by chrk2205** [comment]
PTAL @anandwana001

**Comment by anandwana001** [comment]
@chrk2205 please don't resolve the conversation, the conversation should only be resolved by the one who has started it.

**Comment by anandwana001** [comment]
Also, please fix the PR title.

```
The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
```

File: app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt [hunk 8]
```diff
@@ -41,6 +42,7 @@ import org.oppia.android.app.application.ApplicationStartupListenerModule
 import org.oppia.android.app.player.state.hintsandsolution.HintsAndSolutionConfigModule
 import org.oppia.android.app.recyclerview.RecyclerViewMatcher.Companion.atPositionOnView
 import org.oppia.android.app.shim.ViewBindingShimModule
+import org.oppia.android.app.utility.OrientationChangeAction
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt]:
```suggestion
import org.oppia.android.app.utility.OrientationChangeAction.Companion.orientationLandscape
```

File: app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt [hunk 9]
```diff
@@ -151,6 +153,23 @@ class OptionsFragmentTest {
...
+    launch<OptionsActivity>(createOptionActivityIntent(0, false)).use {
+      onView(withId(R.id.options_activity_fragment_navigation_drawer))
+        .check(doesNotExist())
+    }
+  }
+
+  @Test
+  fun testOptionFragment_notFromNavigationDrawer_configChange_navigationDrawerIsNotPresent() {
+    launch<OptionsActivity>(createOptionActivityIntent(0, false)).use {
+      onView(isRoot()).perform(OrientationChangeAction.orientationLandscape())
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt]:
```suggestion
      onView(isRoot()).perform(orientationLandscape())
```

**Review by anandwana001 — CHANGES_REQUESTED** [review]
Nit changes @chrk2205 

Also, please add the espresso test result screenshot in pr description too.

**Comment by chrk2205** [comment]
@anandwana001 sorry about that I didn't knew.

**Comment by anandwana001** [comment]
You can simply reply to the conversation with done or something and assign the reviewer back.

**Comment by rt4914** [comment]
@anandwana001 Will defer to you for this PR.

File: app/src/sharedTest/java/org/oppia/android/app/help/HelpFragmentTest.kt (hunk 6 above)
Comment (chrk2205) [reply app/src/sharedTest/java/org/oppia/android/app/help/HelpFragmentTest.kt:130]: done.

File: app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt (hunk 7 above)
Comment (chrk2205) [reply app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt:157]: done.

File: app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt (hunk 9 above)
Comment (chrk2205) [reply app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt]: done.

File: app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt (hunk 8 above)
Comment (chrk2205) [reply app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt]: done.

**Comment by chrk2205** [comment]
@anandwana001 
added test results in description.

File: app/src/sharedTest/java/org/oppia/android/app/help/HelpFragmentTest.kt [hunk 10]
```diff
@@ -126,6 +126,23 @@ class HelpFragmentTest {
...
+    launch<HelpActivity>(createHelpActivityIntent(0, false)).use {
+      onView(withId(R.id.help_activity_fragment_navigation_drawer))
+        .check(doesNotExist())
+    }
+  }
+
+  @Test
+  fun testHelpFragment_notFromNavigationDrawer_configChange_navigationDrawerIsNotPresent() {
+    launch<HelpActivity>(createHelpActivityIntent(0, false)).use {
+      orientationLandscape()
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/help/HelpFragmentTest.kt]: `onView(isRoot()).perform(orientationLandscape())`

**Review by anandwana001 — CHANGES_REQUESTED** [review]

**Comment by anandwana001** [comment]
@chrk2205 Could you please fix the PR title?

`The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)`

**Comment by chrk2205** [comment]
do the PR title looks good now?
if not, can you specify what exactly should i change??
thankyou
@anandwana001

File: app/src/sharedTest/java/org/oppia/android/app/help/HelpFragmentTest.kt (hunk 10 above)
Comment (chrk2205) [reply app/src/sharedTest/java/org/oppia/android/app/help/HelpFragmentTest.kt]: done

**Comment by anandwana001** [comment]
It's good now. Thanks for the update.

**Review by anandwana001 — APPROVED** [review]
LGTM

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.
