### PR TITLE
Fix #1873: Fix OnboardingFragmentTest test cases on Robolectric

### LINKED ISSUE #1873: Fix OnboardingFragmentTest for Robolectric
Currently, the tests in OnboardingFragmentTest are passing on Espresso but they should also pass on Robolectric. Fix this file to make sure that the tests pass on Robolectric.

You can run robolectric tests by following these steps: https://github.com/oppia/oppia-android/wiki/Oppia-Android-Testing#running-roboelectric-tests

Fixing test cases will need to introduce TextApplicationComponent. This can be seen [here](https://github.com/oppia/oppia-android/pull/1680/commits/4729d551b86282ce617e1d53f2762416758785a1).

### LINKED ISSUE #2194: Onboarding Fragment needs to be updated to ViewPager2
In `OnboardingFragment` we are currently using `ViewPager` because of which it does not support RTL automatically, instead we should use `ViewPager2` and make it RTL compatible.

### PR DESCRIPTION
**Pull request by prayutsu**
## Explanation
FIxes #1873, fixes #2194,  fixes part of #2417 
Migrated from ViewPager to ViewPager2
Fixed test cases on robolectric

Testing Video to ensure that new implementation of ViewPager2 does not bring any new regressions - 

https://user-images.githubusercontent.com/54636525/104735359-7f10fd80-5767-11eb-87a7-cca6fc47524f.mp4

All test cases passing on Robolectric -
Screenshot from 2021-01-30 03-19-00

All test cases passing on Espresso -
Screenshot from 2021-01-30 03-18-05

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

File: app/src/sharedTest/java/org/oppia/android/app/onboarding/OnboardingFragmentTest.kt [hunk 1]
```diff
@@ -419,15 +433,18 @@ class OnboardingFragmentTest {
   @Test
   fun testOnboardingFragment_checkSlide2_getStartedButtonIsNotVisible() {
     launch(OnboardingActivity::class.java).use {
-      onView(withId(R.id.onboarding_slide_view_pager)).perform(scrollToPage(2))
+      onView(withId(R.id.onboarding_slide_view_pager)).perform(swipeLeft())
+      onView(withId(R.id.onboarding_slide_view_pager)).perform(swipeLeft())
       onView(withId(R.id.get_started_button)).check(matches(not(isDisplayed())))
     }
```
Comment (prayutsu) [inline app/src/sharedTest/java/org/oppia/android/app/onboarding/OnboardingFragmentTest.kt:439]: This test case is failing. I suspect that it isn't correct because the error thrown is - 
```
androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with id: org.oppia.android:id/get_started_button
```
which makes sense. Because there is no `Get Started` button on the 2nd slide. I think we should instead check for the correct exception thrown.

**Comment by prayutsu** [comment]
Note - I'll add the screenshots of the passing tests once we discuss the single failing test case.

**Comment by prayutsu** [comment]
All the tests are passing on Robolectric smoothly but 11 test cases are have become flaky in espresso -
Screenshot from 2021-01-15 23-35-27
Screenshot from 2021-01-15 23-28-54

**Comment by prayutsu** [comment]
The reason for the failure is -
```
androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: (with id: org.oppia.android:id/slide_description_text_view and at least 100 percent of the view's area is displayed to the user.)
```

I tried fixing them by using `testCoroutineDispatchers.runCurrent()` and `testCoroutineDispatchers.advancedUntilIdle()`
But they were still flaky.

I tried replacing `isCompletelyDisplayed()` with `isDisplayed()` but then they were flaking giving the error - 
`Multiple views match in the View hierarchy`

**Comment by BenHenning** [comment]
@prayutsu it may help to run the test specifically in isolation. Can you watch one flaky test running with Espresso when it flakes and see if it actually gets to the correct state (visually) before the failure occurs? We need to understand if the failure is due to the assertion itself failing for some reason (e.g. the screen is correct, it's just failing to realize that) or if it's failing to get to the destination state before checking, etc.

FYI that advanceUntilIdle & runCurrent are the same on Espresso. I also would expect those calls to help stabilize ViewPager2 since it uses a RecyclerView under the surface, so waiting for the main thread to idle should let it stabilize its animations correctly. You may also want to try to disable animations in your emulator if you haven't already to see if that fixes the flake. I suspect we'll probably run all of our emulator tests in CI with animations disabled for this reason.

Other than that, unrelated question: do we support dark/night mode? Don't remember night versions of the onboarding flow.

**Comment by prayutsu** [comment]
@BenHenning 
I tried running tests in isolation and clearly, they are reaching the correct state visually. I have also disabled animations but still they are failing.
A reference screenshot - 
Screenshot from 2021-01-16 13-25-35

You can see in the screenshot that the text we want to check is -
**Enjoy your learning adventures with our free, effective lessons.**

And in the emulator, it correctly shows the description (that means it successfully reached the correct state)

**Comment by prayutsu** [comment]
And I have enabled the dark mode in my phone's settings, so it kind of forces the apps to be in dark mode.
I have noticed that if the Material theme is used (even if it is a light theme) it displays in the dark mode if it is enabled in the phone settings.

File: app/src/sharedTest/java/org/oppia/android/app/onboarding/OnboardingFragmentTest.kt [hunk 2]
```diff
@@ -172,15 +178,15 @@ class OnboardingFragmentTest {
...
   fun testOnboardingFragment_checkDefaultSlide_clickSkipButton_shiftsToLastSlide() {
     launch(OnboardingActivity::class.java).use {
+      testCoroutineDispatchers.runCurrent()
       onView(withId(R.id.skip_text_view)).perform(click())
+      testCoroutineDispatchers.runCurrent()
       onView(
         allOf(
           withId(R.id.slide_title_text_view),
-          isCompletelyDisplayed()
+          isDisplayed()
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/onboarding/OnboardingFragmentTest.kt]: isDisplayed() will pass the test even if the view is not visible to us but it's the ui-tree, so we use isCompletelyDisplayed() to check the view should be 100% visible on the screen.

File: app/src/main/java/org/oppia/android/app/onboarding/OnboardingFragmentPresenter.kt [hunk 3]
```diff
@@ -50,18 +45,11 @@ class OnboardingFragmentPresenter @Inject constructor(
   }
 
   private fun setUpViewPager() {
-    onboardingPagerAdapter =
+    val adapter =
       OnboardingPagerAdapter(fragment.requireContext(), getOnboardingSlideFinalViewModel())
-    binding.onboardingSlideViewPager.adapter = onboardingPagerAdapter
-    // TODO (#2194 ): Remove this once the implementation is updated to ViewPager2
-    val isRTL = TextUtilsCompat
```
Comment (anandwana001) [inline app/src/main/java/org/oppia/android/app/onboarding/OnboardingFragmentPresenter.kt:57]: is it working correctly for RTL?

**Review by anandwana001 — CHANGES_REQUESTED** [review]
Screenshot 2021-01-18 at 11 25 06

@prayutsu PTAL, these tests are failing on espresso at Pixel XL

**Comment by prayutsu** [comment]
> Screenshot 2021-01-18 at 11 25 06
> 
> @prayutsu PTAL, these tests are failing on espresso at Pixel XL

Yes, I know, I also added the screenshot of failing test cases but they are reaching the correct stage visually in the emulator, also some of them are flaking. I also tried fixing them by adding delay but still some of them would pass some would again fail.
Do you have something that could help us here?

File: app/src/main/java/org/oppia/android/app/onboarding/OnboardingFragmentPresenter.kt (hunk 3 above)
Comment (prayutsu) [reply app/src/main/java/org/oppia/android/app/onboarding/OnboardingFragmentPresenter.kt:57]: I guess there's some problem with the back button - 


https://user-images.githubusercontent.com/54636525/104893546-91727d80-5999-11eb-8e11-b87c20abc892.mp4

File: app/src/sharedTest/java/org/oppia/android/app/onboarding/OnboardingFragmentTest.kt (hunk 2 above)
Comment (prayutsu) [reply app/src/sharedTest/java/org/oppia/android/app/onboarding/OnboardingFragmentTest.kt]: Done

File: app/src/main/java/org/oppia/android/app/onboarding/OnboardingFragmentPresenter.kt (hunk 3 above)
Comment (anandwana001) [reply app/src/main/java/org/oppia/android/app/onboarding/OnboardingFragmentPresenter.kt:57]: @FareesHussain mentioning you here to help with RTL stuff.

**Comment by prayutsu** [comment]
Surprisingly one test case is failing from `ExplorationActivityTest` - 
`org.oppia.android.app.player.exploration.ExplorationActivityTest > testAudioWithWifi_openFractionsExploration_changeLanguage_clickNext_checkLanguageIsHinglish FAILED
    androidx.test.espresso.PerformException: Error performing 'single click' on view 'with id: org.oppia.android:id/continue_button'.`

Is it flaky?

**Comment by anandwana001** [comment]
Looks like, trying re-run, Does it fail locally?

File: app/src/main/java/org/oppia/android/app/onboarding/OnboardingFragmentPresenter.kt (hunk 3 above)
Comment (FareesHussain) [reply app/src/main/java/org/oppia/android/app/onboarding/OnboardingFragmentPresenter.kt:57]: video looks fine
@prayutsu have a look at the todos in the `OnboardingFragmentPresenter` and `OnboardingPagerAdapter` and revert them
and then check if RTL works fine

**Comment by prayutsu** [comment]
> Looks like, trying re-run, Does it fail locally?

They are passing locally
Screenshot from 2021-01-18 15-20-48

File: app/src/main/java/org/oppia/android/app/onboarding/OnboardingFragmentPresenter.kt (hunk 3 above)
Comment (prayutsu) [reply app/src/main/java/org/oppia/android/app/onboarding/OnboardingFragmentPresenter.kt:57]: I checked it on the `develop` branch, and it looks ditto same as in this video.
Is it correct?

Comment (FareesHussain) [reply app/src/main/java/org/oppia/android/app/onboarding/OnboardingFragmentPresenter.kt:57]: Yes

**Comment by anandwana001** [comment]
Also, @prayutsu Could you compare this PR with the older one so that we can understand why we are getting the issue earlier where we get small image swiping.

**Comment by prayutsu** [comment]
> Also, @prayutsu Could you compare this PR with the older one so that we can understand why we are getting the issue earlier where we get small image swiping.

I changed the `layout_width` from `0dp` to `match_parent` for landscape layouts because it is basically the outermost layout in landscape layouts.

File: app/src/sharedTest/java/org/oppia/android/app/onboarding/OnboardingFragmentTest.kt [hunk 4]
```diff
@@ -209,7 +215,7 @@ class OnboardingFragmentTest {
   @Test
   fun testOnboardingFragment_checkSlide1Title_isCorrect() {
     launch(OnboardingActivity::class.java).use {
-      onView(withId(R.id.onboarding_slide_view_pager)).perform(scrollToPage(1))
+      onView(withId(R.id.onboarding_slide_view_pager)).perform(swipeLeft())
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/onboarding/OnboardingFragmentTest.kt]: Create helper functions 

```kotlin
private fun swipeToSlide1() {
  onView(withId(R.id.onboarding_slide_view_pager)).perform(swipeLeft())
  testCoroutineDispatchers.runCurrent()
}

private fun swipeToSlide2() {
  swipeToSlide1()
  swipeToSlide1()
}

private fun swipeToSlide3() {
  swipeToSlide2()
  swipeToSlide1()
}
```

Let me know if you have any better suggestion on this.

File: app/src/sharedTest/java/org/oppia/android/app/onboarding/OnboardingFragmentTest.kt [hunk 5]
```diff
@@ -279,18 +285,19 @@ class OnboardingFragmentTest {
...
     }
   }
 
   @Test
-  // TODO(#973): Fix OnboardingFragmentTest
-  @Ignore
   fun testOnboardingFragment_checkSlide1_clickSkipButton_shiftsToLastSlide() {
     launch(OnboardingActivity::class.java).use {
-      onView(withId(R.id.onboarding_slide_view_pager)).perform(scrollToPage(1))
+      testCoroutineDispatchers.runCurrent()
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/onboarding/OnboardingFragmentTest.kt]: please check on the consistency. 
Sometimes we are using `testCoroutineDispatchers.runCurrent()` at beginning of test, sometimes not. 
I also see the usage of `testCoroutineDispatchers.advanceUntilIdle()`, please check why this is a need in only one test and not others if the test case is something different put a comment on the line above that why we are using `testCoroutineDispatchers.advanceUntilIdle()`.

**Review by anandwana001 — CHANGES_REQUESTED** [review]
Thanks, @prayutsu for meeting our timeline and sending this PR. 

Left a few thoughts. Also, adding a reference for checking view item in nth position of viewPager. This way we might solve the issue for espresso failure, not sure, need to test. 

Reference 1 - https://stackoverflow.com/questions/29836405/testing-viewpager-with-espresso-how-perfom-action-to-a-button-of-an-item

Reference 2 - https://stackoverflow.com/questions/24748303/selecting-child-view-at-index-using-espresso/24933287#24933287

File: app/src/sharedTest/java/org/oppia/android/app/onboarding/OnboardingFragmentTest.kt (hunk 4 above)
Comment (prayutsu) [reply app/src/sharedTest/java/org/oppia/android/app/onboarding/OnboardingFragmentTest.kt]: Done

File: app/src/sharedTest/java/org/oppia/android/app/onboarding/OnboardingFragmentTest.kt (hunk 5 above)
Comment (prayutsu) [reply app/src/sharedTest/java/org/oppia/android/app/onboarding/OnboardingFragmentTest.kt]: It isn't rrequired to use `testCoroutineDispatchers.runCurrent()` in the beginning of the test, hence I removed it.
Also, I was checking if the test case may pass by using `advanceUntilIdle()` but it didn't.
So I have removed it.

**Comment by BenHenning** [comment]
@prayutsu it looks like from your screenshot that the test is hanging after reaching the desired state, unless you paused it or added a debug break? I'm actually slightly stumped here--I would need to dig into this a bit more myself to actually get an idea of why it's ending at that page & failing to match. My first guess is it's not reaching an idle state, but your failure doesn't seem to match that.

**Comment by prayutsu** [comment]
> @prayutsu it looks like from your screenshot that the test is hanging after reaching the desired state, unless you paused it or added a debug break? I'm actually slightly stumped here--I would need to dig into this a bit more myself to actually get an idea of why it's ending at that page & failing to match. My first guess is it's not reaching an idle state, but your failure doesn't seem to match that.

Actually, the test isn't hanging, I took 4-5 screenshots so that I can capture that it is reaching the correct state.

**Review by FareesHussain — APPROVED** [review]
RTL part LGTM

**Comment by BenHenning** [comment]
I don't think I'm going to be able to look into this this week--I'm particularly busy this week. If there's time during the meeting tomorrow, we can try to dig into it, otherwise I suggest adding breakpoints while running the test & start digging into what the specific failure is (e.g. if it's failing to assert the correct state, what is the correct state at the time of assertion? if it's failing to perform an action, what step in the action itself do things start to fail? etc.). The more you can dig into this @prayutsu the easier it will be for me & others to help provide guidance.

**Comment by prayutsu** [comment]
@BenHenning Let's consider one single test case - `testOnboardingFragment_checkSlide1Title_isCorrect()` (line number 215)

When I ran this test in isolation, it passed -
Screenshot from 2021-01-21 10-00-38

I ran it again, it failed - 
Screenshot from 2021-01-21 10-01-03

That's why I suspect that these test cases are flaking and not failing exactly.
All the test cases flaking are - 
```
testOnboardingFragment_checkSlide1Description_isCorrect
testOnboardingFragment_checkSlide2Description_isCorrect
testOnboardingFragment_checkSlide3Description_isCorrect

testOnboardingFragment_checkSlide1Image_isCorrect
testOnboardingFragment_checkSlide2Image_isCorrect
testOnboardingFragment_checkSlide3Image_isCorrect

testOnboardingFragment_checkSlide1Title_isCorrect
testOnboardingFragment_checkSlide2Title_isCorrect
testOnboardingFragment_checkSlide3Title_isCorrect

testOnboardingFragment_swipeLeftThenSwipeRight_isWorking()
testOnboardingFragment_checkSlide3_clickGetStartedButton_opensProfileActivity
```

**Comment by prayutsu** [comment]
Some important observations  -

Flaking test cases -
1. All these test cases first have scrolling involved and after scrolling, the assertion is related to `onboarding_slide.xml` and `onboarding_final_slide.xml`.

Passing test cases -
1. Test cases that first involve scrolling and after that their assertion is related to `onboarding_fragment.xml` are passing.
2. Test cases that involve the use of the `Skip` button and after that, their assertion is related to `onboarding_slide.xml` and `onboarding_final_slide.xml` are passing.
3. Test cases that involve scrolling followed by orientation change or use of skip button and after that their assertion is related to `onboarding_slide.xml` or `onboarding_slide.xml` or `onboarding_fragment` are passing.

So the only case failing involves only `scrolling` followed by an assertion based on `onboarding_slide.xml` or `onboarding_final_slide.xml`. If there's an extra intermediate step between scrolling and assertion (like configuration change or use of skip button) then it makes the test cases pass successfully without any flaky behavior.
Also note that `testOnboardingFragment_checkSlide3_getStartedButtonIsVisible` is not flaking.
All these observations conclude that the test cases involving views that are common to all the onboarding slides are creating the issue.


> I(e.g. if it's failing to assert the correct state, what is the correct state at the time of assertion? if it's failing to perform an action, what step in the action itself do things start to fail? etc.)

@BenHenning I suspect that it is failing to assert the correct state, all the actions are being performed correctly.

File: app/src/sharedTest/java/org/oppia/android/app/onboarding/OnboardingFragmentTest.kt [hunk 6]
```diff
@@ -222,7 +230,9 @@ class OnboardingFragmentTest {
   @Test
   fun testOnboardingFragment_checkSlide1Description_isCorrect() {
     launch(OnboardingActivity::class.java).use {
-      onView(withId(R.id.onboarding_slide_view_pager)).perform(scrollToPage(1))
+      onView(withId(R.id.onboarding_slide_view_pager)).perform(swipeLeft())
+      onView(isRoot()).perform(orientationLandscape())
+      onView(isRoot()).perform(orientationPortrait())
       onView(
```
Comment (prayutsu) [inline app/src/sharedTest/java/org/oppia/android/app/onboarding/OnboardingFragmentTest.kt:226]: I just wanted to check if this could work keeping the above-mentioned points in mind.
After scrolling action, changing the orientation to landscape, again changing back to portrait, and then checking the assertion.
This worked but one test case is still falling - 
Screenshot from 2021-01-21 12-22-50

File: app/src/sharedTest/java/org/oppia/android/app/onboarding/OnboardingFragmentTest.kt [hunk 7]
```diff
@@ -466,34 +493,38 @@ class OnboardingFragmentTest {
...
-      onView(withId(R.id.onboarding_slide_view_pager)).perform(scrollToPage(3))
-      onView(withId(R.id.get_started_button)).perform(click())
+      onView(withId(R.id.onboarding_slide_view_pager)).perform(swipeLeft())
+      onView(withId(R.id.onboarding_slide_view_pager)).perform(swipeLeft())
+      onView(withId(R.id.onboarding_slide_view_pager)).perform(swipeLeft())
+      onView(withId(R.id.get_started_button)).perform(scrollTo(), click())
+      testCoroutineDispatchers.runCurrent()
+      onView(isRoot()).perform(orientationLandscape())
+      onView(isRoot()).perform(orientationPortrait())
+      testCoroutineDispatchers.runCurrent()
```
Comment (prayutsu) [inline app/src/sharedTest/java/org/oppia/android/app/onboarding/OnboardingFragmentTest.kt:458]: This test case is failing.

**Review by prayutsu — COMMENTED** [review]
I will revert these changes after the reviewers take a look.
@BenHenning @anandwana001 PTAL

File: app/src/sharedTest/java/org/oppia/android/app/onboarding/OnboardingFragmentTest.kt (hunk 6 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/onboarding/OnboardingFragmentTest.kt:226]: I don't think we should do this just to pass the pass. 

All the steps in the test we perform are something we can think of that a user will also perform and based on that the test is passing or not. After a swipe, a user will change orientation two times as this is not a default way. 

To check what's going wrong with the test, we need to look at how the lifecycle is working when the test is getting performed. 

Other point, as mentioned earlier, if the view is in all the pages then we need to first test that the view on the specific page is completely visible or not, and then we can match the text or image.

Comment (prayutsu) [reply app/src/sharedTest/java/org/oppia/android/app/onboarding/OnboardingFragmentTest.kt:226]: @anandwana001 Yes, as mentioned in [this](https://github.com/oppia/oppia-android/pull/2482#pullrequestreview-573033619) comment, I'll revert these changes. 
@BenHenning suggested that I should investigate more on this, so I just wanted to share the results after my investigation.

**Comment by prayutsu** [comment]
Please again note that this is not the right way to fix the test cases, I pushed the changes to just show the output and so that you can also verify the same.
I just wanted to share everything that I discovered during the investigation.

**Comment by rt4914** [comment]
@prayutsu Can you please update the branch wit develop. It is assigned to me as code-owner. But I think Akshay will a be a code-owner too considering the test file.

**Comment by prayutsu** [comment]
> @prayutsu Can you please update the branch wit develop. It is assigned to me as code-owner. But I think Akshay will a be a code-owner too considering the test file.

Done, but he's still not appearing as the codeowner.

**Comment by BenHenning** [comment]
Note that Akshay might not appear as a code owner since this is changing app module stuff (he defaults to test code owner if another owner isn't defined for those files).

**Comment by BenHenning** [comment]
Thanks @prayutsu that helps narrow it down a bit. To summarize, it seems like the assertions only fail if we immediately performed a slide action before that. Strange.

I want to dig into this, too, but won't be able to at least until tomorrow.

**Comment by prayutsu** [comment]
> Thanks @prayutsu that helps narrow it down a bit. To summarize, it seems like the assertions only fail if we immediately performed a slide action before that. Strange.
> 
> I want to dig into this, too, but won't be able to at least until tomorrow.

@BenHenning As the main part of the issue has been completed successfully, we can wait for sure for some time to find the exact reason for this behavior.

**Comment by BenHenning** [comment]
Don't think I can dig into this today, but will try to next week. I do encourage you to continue digging into it if you can, though. You might find a solution before I get a chance to look into it further. :)

**Comment by prayutsu** [comment]
> Don't think I can dig into this today, but will try to next week. I do encourage you to continue digging into it if you can, though. You might find a solution before I get a chance to look into it further. :)

Sure, I am definitely digging deep into it. Thanks!

**Comment by BenHenning** [comment]
As discussed during the meeting today, @prayutsu I suggest trying to build a custom matcher that checks the children of a specific page rather than using allOf() since that results in inconsistencies where RecyclerView might sometimes & sometimes not recycle the old views when swiping to a new page.

File: app/src/sharedTest/java/org/oppia/android/app/onboarding/OnboardingFragmentTest.kt [hunk 8]
```diff
@@ -480,21 +489,52 @@ class OnboardingFragmentTest {
...
+      override fun matchesSafely(view: View?): Boolean {
+        if (view?.parent !is ViewGroup) {
+          return parentMatcher.matches(view?.parent)
+        }
+        val group = view.parent as ViewGroup
+        return parentMatcher.matches(view.parent) && group.getChildAt(childPosition) == view
+      }
+    }
+  }
+
```
Comment (prayutsu) [inline app/src/sharedTest/java/org/oppia/android/app/onboarding/OnboardingFragmentTest.kt]: @BenHenning I tried implementing a custom ViewMatcher, but I couldn't get rid of `allOf`.

**Comment by prayutsu** [comment]
> As discussed during the meeting today, @prayutsu I suggest trying to build a custom matcher that checks the children of a specific page rather than using allOf() since that results in inconsistencies where RecyclerView might sometimes & sometimes not recycle the old views when swiping to a new page.

I couldn't find some way so to directly access the pages of viewpager2, because if it is possible then we can easily match with the children of the page.

File: app/src/sharedTest/java/org/oppia/android/app/onboarding/OnboardingFragmentTest.kt [hunk 9]
```diff
@@ -480,21 +509,37 @@ class OnboardingFragmentTest {
...
+      override fun getConstraints(): Matcher<View> {
+        return isAssignableFrom(ViewPager2::class.java)
+      }
+
+      override fun perform(uiController: UiController?, view: View?) {
+        (view as ViewPager2).setCurrentItem(position, false)
+      }
+    }
+  }
```
Comment (prayutsu) [inline app/src/sharedTest/java/org/oppia/android/app/onboarding/OnboardingFragmentTest.kt]: I couldn't find a way to remove `allOf` so tried replacing swiping by implementing a custom ViewAction that does the scrolling. But even after using this, the tests were failing, then after trying different things, I disabled smooth scrolling, and the test cases passed.

**Comment by prayutsu** [comment]
Updated the PR description with the latest screenshots

**Comment by prayutsu** [comment]
Adding screenshots of passing test cases here-
Screenshot from 2021-01-30 03-19-00
Screenshot from 2021-01-30 03-18-05

File: app/src/sharedTest/java/org/oppia/android/app/onboarding/OnboardingFragmentTest.kt (hunk 9 above)
Comment (BenHenning) [reply app/src/sharedTest/java/org/oppia/android/app/onboarding/OnboardingFragmentTest.kt]: Ah nice find. We've had issues with smooth scrolling in the past, too (this is what prompted me to suggest using RecyclerView in the first place). I'd expect Espresso to properly stabilize against smooth scrolling. Does this mean we simply cannot use swipe for navigation & have to force the page directly?

File: app/src/sharedTest/java/org/oppia/android/app/onboarding/OnboardingFragmentTest.kt [hunk 10]
```diff
@@ -480,21 +504,36 @@ class OnboardingFragmentTest {
...
+      override fun getDescription(): String {
+        return "Scroll ViewPager2 to position: $position"
+      }
+
+      override fun getConstraints(): Matcher<View> {
+        return isAssignableFrom(ViewPager2::class.java)
+      }
+
+      override fun perform(uiController: UiController?, view: View?) {
+        (view as ViewPager2).setCurrentItem(position, false)
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/onboarding/OnboardingFragmentTest.kt]: Please add an argument comment for the ``false`` that includes the argument name, e.g. ``/* argName= */ false`` to provide context as to what the literal value corresponds to.

Comment (prayutsu) [reply app/src/sharedTest/java/org/oppia/android/app/onboarding/OnboardingFragmentTest.kt]: Done

File: app/src/sharedTest/java/org/oppia/android/app/onboarding/OnboardingFragmentTest.kt (hunk 9 above)
Comment (prayutsu) [reply app/src/sharedTest/java/org/oppia/android/app/onboarding/OnboardingFragmentTest.kt]: > Ah nice find. We've had issues with smooth scrolling in the past, too (this is what prompted me to suggest using RecyclerView in the first place). I'd expect Espresso to properly stabilize against smooth scrolling. Does this mean we simply cannot use swipe for navigation & have to force the page directly?

@BenHenning Yes, it seems like we have to force the page directly, because in this case maybe, views are not getting recycled the way they get while swiping.

**Comment by prayutsu** [comment]
@BenHenning @anandwana001 @rt4914 PTAL, the PR is ready for full review.

File: app/src/main/java/org/oppia/android/app/onboarding/OnboardingPagerAdapter.kt [hunk 11]
```diff
@@ -2,65 +2,81 @@ package org.oppia.android.app.onboarding
...
+import androidx.recyclerview.widget.RecyclerView
 import org.oppia.android.databinding.OnboardingSlideBinding
 import org.oppia.android.databinding.OnboardingSlideFinalBinding
-import java.util.Locale
 
-/** Adapter to control the slide details in onboarding flow. */
+private const val VIEW_TYPE_TITLE_TEXT = 1
+private const val VIEW_TYPE_STORY_ITEM = 2
+
 class OnboardingPagerAdapter(
```
Comment (anandwana001) [inline app/src/main/java/org/oppia/android/app/onboarding/OnboardingPagerAdapter.kt:13]: Are we going to use the Bindale Adapter and remove this Adapter in this PR only or we are keeping this as a separate issue? @rt4914

**Review by anandwana001 — APPROVED** [review]
LGTM, Thank @prayutsu

File: app/src/sharedTest/java/org/oppia/android/app/onboarding/OnboardingFragmentTest.kt [hunk 12]
```diff
@@ -529,7 +529,7 @@ class OnboardingFragmentTest {
       }
 
       override fun perform(uiController: UiController?, view: View?) {
-        (view as ViewPager2).setCurrentItem(position, false)
+        (view as ViewPager2).setCurrentItem(position, /* smoothScroll= */false)
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/onboarding/OnboardingFragmentTest.kt]:
```suggestion
        (view as ViewPager2).setCurrentItem(position, /* smoothScroll= */ false)
```

File: app/src/main/java/org/oppia/android/app/onboarding/OnboardingPagerAdapter.kt (hunk 11 above)
Comment (BenHenning) [reply app/src/main/java/org/oppia/android/app/onboarding/OnboardingPagerAdapter.kt:13]: That seems like a larger & unrelated change--I suggest splitting it off of this task.

Comment (BenHenning) [reply app/src/main/java/org/oppia/android/app/onboarding/OnboardingPagerAdapter.kt:13]: Actually, given that so much of the adapter has changed anyway, maybe it is worth trying to migrate to BindableAdapter.

**Review by BenHenning — COMMENTED** [review]
Overall, I think the new action is reasonable. I agree with @anandwana001's suggestion to move this to BindableAdapter.

Otherwise I have nothing else to add. Feel free to re-add me if you'd like my review, otherwise I'm happy to defer to codeowners for review.

File: app/src/main/java/org/oppia/android/app/onboarding/OnboardingPagerAdapter.kt (hunk 11 above)
Comment (prayutsu) [reply app/src/main/java/org/oppia/android/app/onboarding/OnboardingPagerAdapter.kt:13]: @BenHenning So, should I replace it with a bindable Adapter in this PR only?

Comment (prayutsu) [reply app/src/main/java/org/oppia/android/app/onboarding/OnboardingPagerAdapter.kt:13]: Oh, I guess you are suggesting to track it via a new issue.

**Comment by prayutsu** [comment]
> Overall, I think the new action is reasonable. I agree with @anandwana001's suggestion to move this to BindableAdapter.
> 
> Otherwise I have nothing else to add. Feel free to re-add me if you'd like my review, otherwise I'm happy to defer to codeowners for review.

@BenHenning Thanks for your review, if everything looks good, then can you please approve the changes?

**Comment by prayutsu** [comment]
@rt4914 We Will also need your review, PTAL.

File: app/src/sharedTest/java/org/oppia/android/app/onboarding/OnboardingFragmentTest.kt (hunk 12 above)
Comment (prayutsu) [reply app/src/sharedTest/java/org/oppia/android/app/onboarding/OnboardingFragmentTest.kt]: Done

**Comment by prayutsu** [comment]
File #2600 for Bindable Adapter Implementation

**Comment by prayutsu** [comment]
Filed #2600 for Bindable Adapter Implementation

**Comment by BenHenning** [comment]
@prayutsu I didn't actually review this in detail (and don't need to since I'm not a codeowner). In general, I don't fully review PRs that don't require my review unless the author specifically asks for it.

If you want me to review, I'm happy to, but I might need to prioritize it lower than other reviews that require my approval.

File: app/src/sharedTest/java/org/oppia/android/app/onboarding/OnboardingFragmentTest.kt [hunk 13]
```diff
@@ -480,21 +504,36 @@ class OnboardingFragmentTest {
...
         allOf(
           withId(R.id.slide_title_text_view),
-          isDisplayed()
+          isCompletelyDisplayed()
         )
       ).check(matches(withText(R.string.onboarding_slide_3_title)))
     }
   }
 
+  private fun scrollToPage(position: Int): ViewAction {
```
Comment (rt4914) [inline app/src/sharedTest/java/org/oppia/android/app/onboarding/OnboardingFragmentTest.kt]: Rename this to `scrollToPosition`

Also, if you have referenced this code from somewhere please add that reference just above the functions in comments.

Also where-ever you are using this function use it like this:
`scrollToPosition(position = 1)`

File: app/src/main/java/org/oppia/android/app/onboarding/OnboardingPagerAdapter.kt (hunk 11 above)
Comment (rt4914) [reply app/src/main/java/org/oppia/android/app/onboarding/OnboardingPagerAdapter.kt:13]: Given the case that @prayutsu has already worked a lot on this issue, let him decide what he wants to do:
(a.) File an issue, mention it this PR and later on either @prayutsu solves it or the community.
(b.) Use `BindableAdapter` in this PR itself.

**Review by rt4914 — CHANGES_REQUESTED** [review]
@prayutsu Overall this PR has turned out to be really good. Suggested few changes.

File: app/src/sharedTest/java/org/oppia/android/app/onboarding/OnboardingFragmentTest.kt (hunk 13 above)
Comment (prayutsu) [reply app/src/sharedTest/java/org/oppia/android/app/onboarding/OnboardingFragmentTest.kt]: Done

**Comment by prayutsu** [comment]
@rt4914 I have filed issue #2600 for migration to the bindable adapter, but I am thinking to close that issue and migrate to Bindable Adapter in this PR only. What do you suggest?

File: app/src/sharedTest/java/org/oppia/android/app/onboarding/OnboardingFragmentTest.kt (hunk 13 above)
Comment (prayutsu) [reply app/src/sharedTest/java/org/oppia/android/app/onboarding/OnboardingFragmentTest.kt]: @rt4914 Actually, I didn't find any reference for it, so I tried creating it myself and it worked.

Comment (rt4914) [reply app/src/sharedTest/java/org/oppia/android/app/onboarding/OnboardingFragmentTest.kt]: That really nice.

**Comment by rt4914** [comment]
> @rt4914 I have filed issue #2600 for migration to the bindable adapter, but I am thinking to close that issue and migrate to Bindable Adapter in this PR only. What do you suggest?

@prayutsu I would suggest you do it in a separate PR.

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.
