### PR TITLE
Fix #3734, #669: Gate language options behind feature flag, add more patterns, and other miscellaneous alpha MR3 fixes

### LINKED ISSUE #669: Adding translations for App and Audio Language selection.
Fetch language list from backend and add translations to track the language selection.

### LINKED ISSUE #3734: Disable in-lesson language picker

### PR DESCRIPTION
**Pull request by BenHenning**
Fix #3734
Fix #669

## Explanation

This PR:
- Gates language selection behind a new feature flag (#52 is tracking introducing a comprehensive UI for language selection; some UX & product considerations are needed before we can build this UI)
- Adds 4 new regex patterns for various locale-related things that shouldn't be allowed anymore
- Introduces miscellaneous fixes that were found as needed prior to building the version of MR3 that was tested last week (see below)

### New Regex checks
The new checks added prohibit:
- Using java.util.Calendar
- Using java.util.Date
- Using java.util.Locale
- Using anything from java.text

These packages/components all perform or are used to perform locale-sensitive operations, and their corresponding functionality is now available in a locale-consistent & safe way using MachineLocale and DisplayLocale. The exemptions are either components that must reference these in order to provide their underlying functionality, tests where it's easier to not use OppiaLocale, or cases that didn't need to be migrated now (for these, TODOs were added with newly filed issues: #3791, #3792).

### Miscellaneous fixes
- #669 was marked as fixed since the goal is to not fetch supported languages from the backend (the app needs to know its exact language set for compatibility). This is now handled through the textproto configuration files & related infrastructure that depends on it.
- Glide broke when loading images with a Proguard-optimized build on older versions of Android due to older versions of Android depending on reflection within its implementation of java.lang.Enum (so an additional dontoptimize exemption was needed for certain aspects of enums)
- The version code was updated to encapsulate test releases on the Play Store (we can only use a version code once, and they need to be increasing, so we'll be updating this version code a lot moving forward). Longer-term, we'll leverage automation to manage this version code so that a human doesn't need to do it.
- The platform parameter module needed to be reworked so that the singleton implementation wasn't provided along with the app's parameters so that certain tests (such as the two OptionsFragmentTest suites updated in this PR) can override feature parameter values. This is the main contributor to the PR's length both in LOC and files affected.

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

Screenshots (language options now missing):

Portrait:
image

Landscape:
image

Note: tablet screenshots not included since this UI change a trivial removal of behavior. Similarly, RTL & Talkback behaviors aren't included since this is just removing an item from the options menu.

Espresso results: OptionsFragmentTest is passing:

OptionsFragmentTest_passing_espresso

### CODE REVIEW

**Comment by BenHenning** [comment]
@vinitamurthi @rt4914 @anandwana001 PTAL for codeowners.

**Review by vinitamurthi — APPROVED** [review]

File: app/src/test/java/org/oppia/android/app/testing/options/OptionsFragmentTest.kt [hunk 1]
```diff
@@ -90,6 +103,7 @@ class OptionsFragmentTest {
 
   @Before
   fun setUp() {
+    TestModule.forceEnableLanguageSelectionUi = true
```
Comment (anandwana001) [inline app/src/test/java/org/oppia/android/app/testing/options/OptionsFragmentTest.kt:106]: should we shift this initialization to each test as some require true some false?

**Review by anandwana001 — APPROVED** [review]
One nit query, else all LGTM

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

File: app/src/test/java/org/oppia/android/app/testing/options/OptionsFragmentTest.kt (hunk 1 above)
Comment (BenHenning) [reply app/src/test/java/org/oppia/android/app/testing/options/OptionsFragmentTest.kt:106]: I sort of lean toward defaulting since it might be easy to miss in future tests. Ideally, we would use annotations to toggle features on/off, but we don't have that support yet so enabling the feature becomes a bit hidden like this.

**Comment by BenHenning** [comment]
Merging this as-is. @anandwana001 please let me know if you feel strongly about your comment (happy to follow up with a change if needed).
