### PR TITLE
Fix #2408 : Resolved ktlint max line in topic test package

### LINKED ISSUE #2408: Resolve ktlint max line in topic test package
**Describe the bug**
We are preventing the 100 char length at some places like test case fun name. 
`// ktlint-disable max-line-length`

**Expected behavior**
We need to remove this prevention and fix the function name under 100 char length.

### PR DESCRIPTION
**Pull request by varunvjha**
## Explanation

Fixes #2408 : Removed ' // ktlint-disable max-line-length ' and fixed the functions name under 100 char length.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

File: app/src/sharedTest/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragmentTest.kt [hunk 1]
```diff
@@ -158,7 +158,7 @@ class ConceptCardFragmentTest {
   }
 
   @Test
-  fun testConceptCardFragment_openDialogFragment0_checkSkillAndExplanationAreDisplayedWithoutRichText() { // ktlint-disable max-line-length
+  fun testCCFragment_openDialogFragment0_checkSkillAndExplanationDisplayedWithoutRichText() {
```
Comment (rt4914) [inline app/src/sharedTest/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragmentTest.kt]: Alternate suggestion which works just by removing `Fragment`

`fun testConceptCard_openDialog0_checkSkillAndExplanationAreDisplayedWithoutRichText() {`

Comment (rt4914) [reply app/src/sharedTest/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragmentTest.kt]: Same things applies for this entire file?

File: app/src/sharedTest/java/org/oppia/android/app/topic/lessons/TopicLessonsFragmentTest.kt [hunk 2]
```diff
@@ -276,7 +276,7 @@ class TopicLessonsFragmentTest {
   }
 
   @Test
-  fun testLessonsPlayFragment_loadRatiosTopic_clickExpandListIconIndex1_clickExpandListIconIndex2_chapterListForIndex1IsNotDisplayed() { // ktlint-disable max-line-length
+  fun testLessonsPlayFragment_clickExpandListIconIndex1then2_chapterListForIndex1NotDisplayed() {
```
Comment (rt4914) [inline app/src/sharedTest/java/org/oppia/android/app/topic/lessons/TopicLessonsFragmentTest.kt]: Its nice but the `T` should be capital in `1then2`.

`testLessonsPlayFragment_clickExpandListIconIndex1Then2_chapterListForIndex1NotDisplayed `

Comment (rt4914) [reply app/src/sharedTest/java/org/oppia/android/app/topic/lessons/TopicLessonsFragmentTest.kt]: Ditto at other places.

File: app/src/sharedTest/java/org/oppia/android/app/topic/revisioncard/RevisionCardFragmentTest.kt [hunk 3]
```diff
@@ -38,7 +38,7 @@ import org.oppia.android.app.parser.RichTextViewMatcher.Companion.containsRichTe
 import org.oppia.android.app.player.exploration.ExplorationActivity
 import org.oppia.android.app.player.state.hintsandsolution.HintsAndSolutionConfigModule
 import org.oppia.android.app.shim.ViewBindingShimModule
-import org.oppia.android.app.topic.revisioncard.RevisionCardActivity.Companion.createRevisionCardActivityIntent // ktlint-disable max-line-length
+import org.oppia.android.app.topic.revisioncard.RevisionCardActivity.Companion.createRevisionCardActivityIntent
```
Comment (rt4914) [inline app/src/sharedTest/java/org/oppia/android/app/topic/revisioncard/RevisionCardFragmentTest.kt]: This change won't work. You can fix this by removing the import and using
`RevisionCardActivity.createRevisionCardActivityIntent(` everywhere to fix the error.

File: app/src/sharedTest/java/org/oppia/android/app/topic/revisioncard/RevisionCardFragmentTest.kt [hunk 4]
```diff
@@ -269,7 +269,7 @@ class RevisionCardFragmentTest {
   }
 
   @Test
-  fun testRevisionCardTestActivity_configurationChange_fractionSubtopicId1_checkReturnToTopicButtonIsDisplayedSuccessfully() { // ktlint-disable max-line-length
+  fun testRevCardTestActivity_fractionSubtopicId1_checkReturnToTopicButtonDispSuccessfully() {
```
Comment (rt4914) [inline app/src/sharedTest/java/org/oppia/android/app/topic/revisioncard/RevisionCardFragmentTest.kt:271]: Instead of `testRevisionCardTestActivity` use `testRevisionCard` to fix this.

**Review by rt4914 — CHANGES_REQUESTED** [review]
Great work. Suggested few changes.

**Comment by varunvjha** [comment]
@rt4914 Made the requested changes. PTAL.

File: app/src/sharedTest/java/org/oppia/android/app/topic/revisioncard/RevisionCardFragmentTest.kt (hunk 4 above)
Comment (rt4914) [reply app/src/sharedTest/java/org/oppia/android/app/topic/revisioncard/RevisionCardFragmentTest.kt:271]: @varunvjha Always reply to these comments.

File: app/src/sharedTest/java/org/oppia/android/app/topic/revisioncard/RevisionCardFragmentTest.kt (hunk 3 above)
Comment (rt4914) [reply app/src/sharedTest/java/org/oppia/android/app/topic/revisioncard/RevisionCardFragmentTest.kt]: @varunvjha Always reply to these comments.

File: app/src/sharedTest/java/org/oppia/android/app/topic/lessons/TopicLessonsFragmentTest.kt (hunk 2 above)
Comment (rt4914) [reply app/src/sharedTest/java/org/oppia/android/app/topic/lessons/TopicLessonsFragmentTest.kt]: @varunvjha Always reply to these comments.

File: app/src/sharedTest/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragmentTest.kt (hunk 1 above)
Comment (rt4914) [reply app/src/sharedTest/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragmentTest.kt]: @varunvjha Always reply to these comments.

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Comment by anandwana001** [comment]
There are some issues with this PR. @MaskedCarrot will be solving them in his pr https://github.com/oppia/oppia-android/pull/2411

**Comment by anandwana001** [comment]
@rt4914 could you please revert this pr as there many changes which need to reopen these issues.
