### PR TITLE
Fix #5631: Fix thumbnail loading for multiple classrooms

### LINKED ISSUE #5631: [BUG]: Multiple classrooms do not load thumbnails from protos correctly
### Describe the bug

When using production assets with thumbnail information, the thumbnails aren't loaded as expected when multiple classrooms is enabled (see screenshot below).

### Steps To Reproduce

This requires production assets in order to repro.

### Expected Behavior

Thumbnails should load (see screenshot below).

### Screenshots/Videos

Thumbnails missing:

image

Thumbnails present (same build and assets but with multiple classrooms disabled):

image

### What device/emulator are you using?

Nexus 5X

### Which Android version is your device/emulator running?

27

### Which version of the Oppia Android app are you using?

0.14-dev-17f2ef3044

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by theMr17**
## Explanation

Fixes #5631

This PR introduces a new `ThumbnailImage` composable that integrates the `LessonThumbnailImageView` within a Compose layout. The changes include:

- Adding the basic structure for `ThumbnailImage` composable.
- Updating various UI components to use the new `ThumbnailImage` composable.
- Adding classroom thumbnail drawables to `LessonThumbnailImageView`.

Note: Initial attempts were made to use the Glide Compose library, but was found to be incompatible with other dependencies https://github.com/oppia/oppia-android/issues/5631#issuecomment-2570261190.

## Screenshots

|Light Mode|Dark Mode|
|--|--|
|image|image|
|image|image|

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- For PRs introducing new UI elements or color changes, both light and dark mode screenshots must be included
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### CODE REVIEW

**Comment by theMr17** [comment]
Hey @BenHenning, as discussed in chat, we can use this PR to test again with the production assets. PTAL.

File: app/src/main/java/org/oppia/android/app/classroom/ClassroomListViewModel.kt [hunk 1]
```diff
@@ -57,6 +58,7 @@ class ClassroomListViewModel(
   private val profileManagementController: ProfileManagementController,
   private val topicListController: TopicListController,
   private val classroomController: ClassroomController,
+  @ClassroomHtmlParserEntityType private val classroomEntityType: String,
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/classroom/ClassroomListViewModel.kt]: This & the following 2 fields don't need the qualifiers since this isn't an inject constructor.

File: app/src/main/java/org/oppia/android/app/classroom/ThumbnailImage.kt [hunk 2]
```diff
@@ -0,0 +1,46 @@
...
+ *
+ * This function integrates the [LessonThumbnailImageView] within a Compose layout, allowing it
+ * to render a lesson thumbnail image based on the provided parameters. The implementation
+ * currently relies on a traditional Android View approach due to compatibility issues with the
+ * Glide Compose library.
+ *
+ * @param entityId The unique identifier for the entity associated with the thumbnail.
+ * @param entityType The type of the entity (e.g., classroom, topic, story).
+ * @param lessonThumbnail The [LessonThumbnail] containing metadata required to load the image.
+ * @param modifier The [Modifier] to be applied to the layout, defaulting to [Modifier].
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/classroom/ThumbnailImage.kt]:
```suggestion
 * @param entityId the unique identifier for the entity associated with the thumbnail
 * @param entityType the type of the entity (e.g., classroom, topic, story)
 * @param lessonThumbnail the [LessonThumbnail] containing metadata required to load the image
 * @param modifier the [Modifier] to be applied to the layout, defaulting to [Modifier]
```

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @theMr17! Can you please attach screenshots to the main comment showing that this works with multiple classrooms enabled at least for test data locally? I think you may need to check out an earlier version of develop (before Gradle was removed) and merge this in to verify (since thumbnails don't currently load for Bazel builds--which is something we will need to fix eventually).

Otherwise, the changes seem quite sensible! Only had a few comments--PTAL.

File: app/src/main/java/org/oppia/android/app/classroom/ThumbnailImage.kt (hunk 2 above)
Comment (theMr17) [reply app/src/main/java/org/oppia/android/app/classroom/ThumbnailImage.kt]: Updated the kdoc.

File: app/src/main/java/org/oppia/android/app/classroom/ClassroomListViewModel.kt (hunk 1 above)
Comment (theMr17) [reply app/src/main/java/org/oppia/android/app/classroom/ClassroomListViewModel.kt]: Removed the qualifiers.

**Comment by theMr17** [comment]
Hey @BenHenning, thanks for the review! I've addressed your comments and added screenshots to the PR description, PTAL. I didn't need to check out older commits for the Gradle build; image loading works fine for me with Bazel builds as well.

Regarding the classroom thumbnails, they already have a background. The production assets should have the correct background color set for them to display properly.

**Review by BenHenning — APPROVED** [review]
Thanks @theMr17! I'm actually surprised to hear that the Bazel build actually has working thumbnails. Perhaps it's because the JSON assets are still being loaded.

This otherwise LGTM--really happy to see this get in quickly as it will allow us to test multiple classrooms in alpha. :)

**Comment by BenHenning** [comment]
Merging with the latest develop & enabling auto-merge.
