### PR TITLE
Fix #1105: Addition for OppiaUncaughtExceptionHandler

### LINKED ISSUE #1105: Offline handler for Crashes [GSoC'20][Milestone 3]
Addition of a UncaughtExceptionHandler (and tests) to the Oppia-Android codebase. This will allow us to handle offline storage of crashes in case of no network connectivity and smooth upload of them to the Firebase console in the presence of network connectivity.

### PR DESCRIPTION
**Pull request by Sarthak2601**
## Explanation

Fix #1105 
- Addition of an uncaught exception handler for handling the fatal exceptions. 

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

File: app/src/main/java/org/oppia/app/application/OppiaApplication.kt [hunk 1]
```diff
@@ -4,17 +4,39 @@ import android.app.Application
...
+import javax.inject.Inject
 
 /** The root [Application] of the Oppia app. */
 class OppiaApplication : MultiDexApplication(), ActivityComponentFactory {
   /** The root [ApplicationComponent]. */
+
+  @Inject
+  lateinit var exceptionsController: ExceptionsController
+  @Inject
+  lateinit var oppiaClock: OppiaClock
```
Comment (vinitamurthi) [inline app/src/main/java/org/oppia/app/application/OppiaApplication.kt]: Can we not inject OppiaUncaughtExceptionHandler directly instead of injecting its dependencies and creating it below?

File: app/src/main/java/org/oppia/app/application/OppiaApplication.kt [hunk 2]
```diff
@@ -4,17 +4,39 @@ import android.app.Application
...
+    setOppiaUncaughtExceptionHandler()
     return component.getActivityComponentBuilderProvider().get().setActivity(activity).build()
   }
+
+  /** Sets the uncaughtExceptionHandler of the current thread to [OppiaUncaughtExceptionHandler]. */
+  private fun setOppiaUncaughtExceptionHandler() {
+    try {
+      Thread.currentThread().uncaughtExceptionHandler =
+        OppiaUncaughtExceptionHandler(exceptionsController, oppiaClock)
+    } catch (exception: Exception) {
```
Comment (vinitamurthi) [inline app/src/main/java/org/oppia/app/application/OppiaApplication.kt]: Log this exception with the console log

File: domain/src/main/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandler.kt [hunk 3]
```diff
@@ -0,0 +1,19 @@
+package org.oppia.domain.oppialogger.exceptions
```
Comment (vinitamurthi) [inline domain/src/main/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandler.kt]: Can we add tests for this class?

File: app/src/main/java/org/oppia/app/application/OppiaApplication.kt [hunk 4]
```diff
@@ -4,17 +4,39 @@ import android.app.Application
...
+    } finally {
+      Thread.currentThread().uncaughtExceptionHandler = Thread.getDefaultUncaughtExceptionHandler()
```
Comment (vinitamurthi) [inline app/src/main/java/org/oppia/app/application/OppiaApplication.kt]: Have you verified that this properly redirects the exception to the default handler (i.e. crashlytics in our case?)

File: domain/src/main/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandler.kt [hunk 5]
```diff
@@ -0,0 +1,19 @@
...
+import javax.inject.Inject
+
+/** Handler for catching fatal exceptions before the defaultUncaughtExceptionHandler. */
+class OppiaUncaughtExceptionHandler @Inject constructor(
+  private var exceptionsController: ExceptionsController,
+  private var oppiaClock: OppiaClock
+) : Thread.UncaughtExceptionHandler {
+
+  /** Logs an uncaught exception to the [exceptionsController]. */
+  override fun uncaughtException(thread: Thread?, throwable: Throwable?) {
```
Comment (vinitamurthi) [inline domain/src/main/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandler.kt]: Dont we need to throw an exception here too? Since the caller is catching it?

**Review by vinitamurthi — CHANGES_REQUESTED** [review]

File: app/src/main/java/org/oppia/app/application/OppiaApplication.kt (hunk 1 above)
Comment (Sarthak2601) [reply app/src/main/java/org/oppia/app/application/OppiaApplication.kt]: Done.

File: app/src/main/java/org/oppia/app/application/OppiaApplication.kt (hunk 2 above)
Comment (Sarthak2601) [reply app/src/main/java/org/oppia/app/application/OppiaApplication.kt]: Would printing stack trace work ? Otherwise we'd have to inject console logger as well.

File: domain/src/main/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandler.kt (hunk 3 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandler.kt]: Done.

File: domain/src/main/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandler.kt (hunk 5 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandler.kt]: No, I don't think so. This function is called whenever the exception handler is invoked so I think the throwable will go forward. But yes, please correct me if I am wrong about this.

File: app/src/main/java/org/oppia/app/application/OppiaApplication.kt (hunk 4 above)
Comment (Sarthak2601) [reply app/src/main/java/org/oppia/app/application/OppiaApplication.kt]: Yes, verified. It redirects to crashlytics.

File: domain/src/test/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandlerTest.kt [hunk 6]
```diff
@@ -0,0 +1,174 @@
...
+      .onChanged(oppiaExceptionLogsResultCaptor.capture())
+
+    val exceptionLog = oppiaExceptionLogsResultCaptor.value.getOrThrow().getExceptionLog(0)
+    val exception = exceptionLog.toException()
+
+    assertThat(exception.message).matches("java.lang.Exception: TEST")
+  }
+
+  @Test
+  fun testHandler_throwException_verifyLogToRemoteService() {
```
Comment (vinitamurthi) [inline domain/src/test/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandlerTest.kt]: testHandler_throwException_withNetwork_verifyLogToRemoteService

File: domain/src/main/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandler.kt (hunk 5 above)
Comment (vinitamurthi) [reply domain/src/main/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandler.kt]: Can we do the try {} catch logic in the OppiaApplication here instead? That way if we want to register the handler anywhere else it would have all the try catch logic set up.

File: domain/src/test/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandlerTest.kt [hunk 7]
```diff
@@ -0,0 +1,174 @@
...
+    val exceptionThrown = Exception("TEST")
+    oppiaUncaughtExceptionHandler.uncaughtException(Thread.currentThread(), exceptionThrown)
+
+    val exceptionCaught = fakeExceptionLogger.getMostRecentException()
+    assertThat(exceptionCaught).hasMessageThat().matches("java.lang.Exception: TEST")
+    assertThat(exceptionCaught.cause).isEqualTo(Exception(exceptionThrown).cause)
+  }
```
Comment (vinitamurthi) [inline domain/src/test/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandlerTest.kt]: Once you move the try catch logic here, also add a test to verify that the default handler is also invoked (You can create a fake default handler and verify that it was called with the correct data)

**Review by vinitamurthi — CHANGES_REQUESTED** [review]

File: domain/src/main/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandler.kt (hunk 5 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandler.kt]: Yes, done.

File: domain/src/test/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandlerTest.kt (hunk 7 above)
Comment (Sarthak2601) [reply domain/src/test/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandlerTest.kt]: Done.

File: domain/src/test/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandlerTest.kt (hunk 6 above)
Comment (Sarthak2601) [reply domain/src/test/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandlerTest.kt]: Done.

File: domain/src/main/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandler.kt [hunk 8]
```diff
@@ -0,0 +1,25 @@
...
+    try {
+      exceptionsController.logFatalException(
+        Exception(throwable),
+        oppiaClock.getCurrentCalendar().timeInMillis
+      )
+    } catch (e: Exception) {
+      e.printStackTrace()
```
Comment (vinitamurthi) [inline domain/src/main/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandler.kt]: Should we be logging this to the console?

File: domain/src/test/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandlerTest.kt [hunk 9]
```diff
@@ -0,0 +1,203 @@
...
+): Thread.UncaughtExceptionHandler{
+
+  private val exceptionList = mutableListOf<Exception>()
+
+  override fun uncaughtException(p0: Thread?, p1: Throwable?) {
+    exceptionList.add(Exception(p1))
+  }
+
+  fun getMostRecentException() = exceptionList.last()
+}
```
Comment (vinitamurthi) [inline domain/src/test/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandlerTest.kt]: Add new line at EOF

File: domain/src/test/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandlerTest.kt [hunk 10]
```diff
@@ -0,0 +1,203 @@
...
+  }
+
+  @Test
+  fun testHandler_throwException_verifyLogToDefaultHandler(){
+    val exceptionThrown = Exception("TEST")
+    oppiaUncaughtExceptionHandler.uncaughtException(Thread.currentThread(), exceptionThrown)
+
+    val exceptionCaught = fakeDefaultExceptionHandler.getMostRecentException()
+    assertThat(exceptionCaught).hasMessageThat().matches("java.lang.Exception: TEST")
+    assertThat(exceptionCaught.cause).isEqualTo(Exception(exceptionThrown).cause)
```
Comment (vinitamurthi) [inline domain/src/test/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandlerTest.kt]: Why do we need to do Exception(exceptionThrown) here? Can we not just do exceptionThrown.cause?

**Review by vinitamurthi — COMMENTED** [review]
General approach looks good to me now! I am a bit unsure about the dagger injection bit, going to defer to @BenHenning here to verify if that's okay. Just a couple of comments otherwise

File: domain/src/test/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandlerTest.kt (hunk 10 above)
Comment (Sarthak2601) [reply domain/src/test/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandlerTest.kt]: We need to do Exception(exceptionThrown) because we're doing Exception(throwable) in our handler while logging to our controller. Our controller needs an exception, so we transform the throwable into an exception.

File: domain/src/main/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandler.kt (hunk 8 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandler.kt]: Done.

File: domain/src/test/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandlerTest.kt (hunk 9 above)
Comment (Sarthak2601) [reply domain/src/test/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandlerTest.kt]: Done.

File: app/src/main/java/org/oppia/app/application/OppiaApplication.kt (hunk 2 above)
Comment (vinitamurthi) [reply app/src/main/java/org/oppia/app/application/OppiaApplication.kt]: Is there any issue injecting the console logger?

**Review by vinitamurthi — APPROVED** [review]
I am still a bit unsure about the dagger injection. But I will approve to unblock and defer to Ben for that

File: domain/src/main/java/org/oppia/domain/oppialogger/exceptions/OppiaExceptionHandlerModule.kt [hunk 11]
```diff
@@ -0,0 +1,14 @@
+package org.oppia.domain.oppialogger.exceptions
+
+import dagger.Module
+import dagger.Provides
+
+@Module
+class OppiaExceptionHandlerModule {
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/domain/oppialogger/exceptions/OppiaExceptionHandlerModule.kt]: Please add a KDoc.

File: domain/src/main/java/org/oppia/domain/oppialogger/exceptions/OppiaExceptionHandlerModule.kt [hunk 12]
```diff
@@ -0,0 +1,14 @@
...
+  @Provides
+  fun provideHandler(
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/domain/oppialogger/exceptions/OppiaExceptionHandlerModule.kt]: You can use Binds, instead:

```kotlin
@Binds 
fun bindUncaughtExceptionHandler(impl: OppiaUncaughtExceptionHandler): Thread.UncaughtExceptionHandler
```

Requires also making the module an interface.

File: domain/src/main/java/org/oppia/domain/oppialogger/exceptions/OppiaExceptionHandlerModule.kt [hunk 13]
```diff
@@ -0,0 +1,14 @@
...
+    oppiaUncaughtExceptionHandler: OppiaUncaughtExceptionHandler
+  ): Thread.UncaughtExceptionHandler {
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/domain/oppialogger/exceptions/OppiaExceptionHandlerModule.kt]: Suggest qualifying this, or retrieving OppiaUncaughtExceptionHandler directly in the component to avoid binding a value for a type outside the codebase.

File: domain/src/main/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandler.kt [hunk 14]
```diff
@@ -0,0 +1,27 @@
+package org.oppia.domain.oppialogger.exceptions
+
+import org.oppia.util.logging.ConsoleLogger
+import org.oppia.util.system.OppiaClock
+import javax.inject.Inject
+
+/** Handler for catching fatal exceptions before the defaultUncaughtExceptionHandler. */
+class OppiaUncaughtExceptionHandler @Inject constructor(
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandler.kt]: Prefer naming this for what it’s doing, not ‘Oppia’

File: domain/src/main/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandler.kt [hunk 15]
```diff
@@ -0,0 +1,27 @@
...
+  override fun uncaughtException(thread: Thread?, throwable: Throwable?) {
+    try {
+      exceptionsController.logFatalException(
+        Exception(throwable),
+        oppiaClock.getCurrentCalendar().timeInMillis
+      )
+    } catch (e: Exception) {
+      consoleLogger.e("OPPIA_EXCEPTION_HANDLER", "Problem in logging exception", e)
+    } finally {
+      Thread.getDefaultUncaughtExceptionHandler().uncaughtException(thread, throwable)
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandler.kt]: This isn’t correct. You need to pass in the original uncaught exception handler that you’re replacing and call that.

It’s partly this reason why I suggested that you instead bind a new ApplicationCreationListener set whose onCreate calls are called in OppiaApplication, then have this handler self register itself.

File: domain/src/test/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandlerTest.kt [hunk 16]
```diff
@@ -0,0 +1,203 @@
...
+      fun setApplication(application: Application): Builder
+      fun build(): TestApplicationComponent
+    }
+
+    fun inject(oppiaUncaughtExceptionHandlerTest: OppiaUncaughtExceptionHandlerTest)
+  }
+}
+
+class FakeDefaultExceptionHandler @Inject constructor(
+  private val fakeExceptionLogger: ExceptionLogger
```
Comment (BenHenning) [inline domain/src/test/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandlerTest.kt]: Is this field being used for anything?

File: domain/src/test/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandlerTest.kt [hunk 17]
```diff
@@ -0,0 +1,203 @@
...
+  lateinit var oppiaExceptionLogsResultCaptor: ArgumentCaptor<AsyncResult<OppiaExceptionLogs>>
+
+  @Before
+  fun setUp() {
+    networkConnectionUtil = NetworkConnectionUtil(ApplicationProvider.getApplicationContext())
+    setUpTestApplicationComponent()
+    Thread.setDefaultUncaughtExceptionHandler(fakeDefaultExceptionHandler)
+  }
+
+  @ExperimentalCoroutinesApi
```
Comment (BenHenning) [inline domain/src/test/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandlerTest.kt]: This and next annotations are no longer needed. Please remove.

File: domain/src/test/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandlerTest.kt [hunk 18]
```diff
@@ -0,0 +1,203 @@
...
+  }
+
+  private fun setUpTestApplicationComponent() {
+    DaggerOppiaUncaughtExceptionHandlerTest_TestApplicationComponent.builder()
+      .setApplication(ApplicationProvider.getApplicationContext())
+      .build()
+      .inject(this)
+  }
+
+  @Test
```
Comment (BenHenning) [inline domain/src/test/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandlerTest.kt]: Move this up. Test methods should be consecutively next to each other before helpers.

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @Sarthak2601! Left some thoughts.

File: domain/src/test/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandlerTest.kt (hunk 18 above)
Comment (Sarthak2601) [reply domain/src/test/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandlerTest.kt]: Done.

File: domain/src/test/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandlerTest.kt (hunk 17 above)
Comment (Sarthak2601) [reply domain/src/test/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandlerTest.kt]: Done.

File: domain/src/test/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandlerTest.kt (hunk 16 above)
Comment (Sarthak2601) [reply domain/src/test/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandlerTest.kt]: Removed.

File: domain/src/main/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandler.kt (hunk 14 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandler.kt]: Actually I named it the way Crashlytics names its custom exception handler. Do you have something better in mind ? I think the name's alright since it's our custom uncaught exception handler.

File: domain/src/main/java/org/oppia/domain/oppialogger/exceptions/OppiaExceptionHandlerModule.kt (hunk 12 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/exceptions/OppiaExceptionHandlerModule.kt]: I modified this file to return `OppiaUncaughtExceptionHandler` instead. So i think we have to use `@Provides` here. PTAL.

File: domain/src/main/java/org/oppia/domain/oppialogger/exceptions/OppiaExceptionHandlerModule.kt (hunk 11 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/exceptions/OppiaExceptionHandlerModule.kt]: Done.

File: domain/src/main/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandler.kt (hunk 15 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandler.kt]: Modified, PTAL.

File: domain/src/main/java/org/oppia/domain/oppialogger/exceptions/OppiaExceptionHandlerModule.kt (hunk 13 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/exceptions/OppiaExceptionHandlerModule.kt]: Modified, PTAL.

File: domain/src/main/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandler.kt [hunk 19]
```diff
@@ -11,6 +11,8 @@ class OppiaUncaughtExceptionHandler @Inject constructor(
   private val consoleLogger: ConsoleLogger
 ) : Thread.UncaughtExceptionHandler {
 
+  private lateinit var existingUncaughtExceptionHandler: Thread.UncaughtExceptionHandler
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandler.kt]: This seems like a misuse of lateinit var. From what I understand, lateinit var is meant to only be used when we guarantee initialization, just after construction of the class. In this case, you want to use a sentinel value to represent presence on whether the handler was correctly initialized by the calling API. Nullability is probably a better fit for this:

```kotlin
private var chainedUncaughtExceptionHandler: Thread.UncaughtExceptionHandler? = null
```

File: app/src/main/java/org/oppia/app/application/OppiaApplication.kt [hunk 20]
```diff
@@ -10,22 +10,24 @@ import org.oppia.domain.oppialogger.exceptions.OppiaUncaughtExceptionHandler
...
-
-  lateinit var oppiaUncaughtExceptionHandler: OppiaUncaughtExceptionHandler
-
   private val component: ApplicationComponent by lazy {
     DaggerApplicationComponent.builder()
       .setApplication(this)
       .build()
   }
 
+  private lateinit var oppiaUncaughtExceptionHandler: OppiaUncaughtExceptionHandler
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/app/application/OppiaApplication.kt]: I'm still not keen on changing the OppiaApplication class, especially since it's going to make later migrations (such as the one to Dagger Hilt) more difficult. The current solution also won't correctly integrate with test applications which will make testing in the app module more difficult. See this gist for an idea on how to solve this using Dagger listeners as I suggested earlier:

https://gist.github.com/BenHenning/93efec191657b72667a476c456a0de5f

File: domain/src/main/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandler.kt (hunk 14 above)
Comment (BenHenning) [reply domain/src/main/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandler.kt]: We should generally try to avoid classes having generic names. What if we wanted to add more functionality to the uncaught exception handler chain? We could either have an omni OppiaUncaughtExceptionHandler that does lots of things, or a compositional approach where we have multiple exception handlers with specific responsibilities. The latter tends to be more flexible & has other maintenance benefits. Naming this class specific helps move toward that pattern. See the gist in my latest comment for a suggested alternate name.

**Review by BenHenning — CHANGES_REQUESTED** [review]
Left a Gist example on how we can use a multibound set to make this cleaner. I think the code I provided is almost plug-and-play with a few modifications, so please let me know if you run into any issues.

File: domain/src/main/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandler.kt (hunk 19 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandler.kt]: Got it. Done.

File: app/src/main/java/org/oppia/app/application/OppiaApplication.kt (hunk 20 above)
Comment (Sarthak2601) [reply app/src/main/java/org/oppia/app/application/OppiaApplication.kt]: Okay, I got your point and upon thinking I also feel that it'll be a lot better if we do things this way. Thanks a lot for the gist. It really helped me understand the setup.

File: domain/src/main/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandler.kt (hunk 14 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/exceptions/OppiaUncaughtExceptionHandler.kt]: Okay, got it. Name changed to the one suggested.

File: domain/src/main/java/org/oppia/domain/oppialogger/ApplicationStartupListenerModule.kt [hunk 21]
```diff
@@ -0,0 +1,12 @@
+package org.oppia.domain.oppialogger
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/domain/oppialogger/ApplicationStartupListenerModule.kt]: This should be in org.oppia.app.application since it's part of the application component setup.

File: domain/src/main/java/org/oppia/domain/oppialogger/exceptions/UncaughtExceptionLoggerModule.kt [hunk 22]
```diff
@@ -0,0 +1,17 @@
+package org.oppia.domain.oppialogger.exceptions
+
+import dagger.Binds
+import dagger.Module
+import dagger.multibindings.IntoSet
+import org.oppia.domain.oppialogger.ApplicationStartupListener
+
+/** Returns an [ApplicationStartupListener] after binding [UncaughtExceptionLoggerStartupListener] into it. */
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/domain/oppialogger/exceptions/UncaughtExceptionLoggerModule.kt]:
```suggestion
/** Binds [UncaughtExceptionLoggerStartupListener] as an [ApplicationStartupListener]. */
```

This is slightly more correct: module classes bind & provide things, not return them.

**Review by BenHenning — APPROVED** [review]
Thanks @Sarthak2601, LGTM! I defer to @vinitamurthi to verify that my 2 remaining comments are addressed after you have a chance to address them.

File: domain/src/main/java/org/oppia/domain/oppialogger/ApplicationStartupListenerModule.kt (hunk 21 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/ApplicationStartupListenerModule.kt]: Done.

File: domain/src/main/java/org/oppia/domain/oppialogger/exceptions/UncaughtExceptionLoggerModule.kt (hunk 22 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/exceptions/UncaughtExceptionLoggerModule.kt]: Done.

Comment (vinitamurthi) [reply domain/src/main/java/org/oppia/domain/oppialogger/exceptions/UncaughtExceptionLoggerModule.kt]: Verified that this has been done, resolving the comment

File: domain/src/main/java/org/oppia/domain/oppialogger/ApplicationStartupListenerModule.kt (hunk 21 above)
Comment (vinitamurthi) [reply domain/src/main/java/org/oppia/domain/oppialogger/ApplicationStartupListenerModule.kt]: Verified that this file has been moved. Resolving the comment

**Comment by vinitamurthi** [comment]
@Sarthak2601 the lint checks are failing, please resolve them and then you can merge the PR

**Comment by vinitamurthi** [comment]
@Sarthak2601 the lint tests are failing. Please resolve them and then you can merge this PR!

**Comment by Sarthak2601** [comment]
Checks passed, comments resolved and approvals done. Merging now !
