### PR TITLE
Fix #3821: Ensure Portuguese can be a default audio language

### LINKED ISSUE #3821: Text voiceovers in English for Portuguese language
**Describe the bug**
The text voiceovers appear in English even after changing the  device language to Portuguese. 

**To Reproduce**
1. Change the device language to Portuguese
2. Go to Oppia app 
3. Go to a lesson
4. Select and play voiceovers

**Expected behavior**
Portuguese voiceovers should appear if the device language is selected as Portuguese.

**Screenshots**
NA

**Device**
- Device/emulator being used - TBD
- SDK version - TBD

**Additional context**
NA

### PR DESCRIPTION
**Pull request by BenHenning**
## Explanation
Fixes #3821

This PR introduces the following end-user visible changes:
- It adds Brazilian Portuguese as an option when selecting a default audio language.
- It removes the 'No Audio' option from the list since it's confusing and presently defaults to 'English' when playing audio voiceovers, anyway.
- It changes the display names of the default audio languages to be localized to their own locale to make the languages easier to read by native speakers.
- It fixes a bug in the tablet version of OptionsActivity wherein switching between audio & reading text would result in fragment stacking (i.e. you could see the bottom of the longer fragment when on the shorter one). This entailed changing fragment 'adds' to 'replaces' for the options fragment transactions.

Technical details:
- This PR migrates the audio language pattern from using a string over to using the AudioLanguage proto enum, similar to the recent change for ReadingTextSize. This was preferred since changing everywhere to support a localized name of each language seemed non-ideal.
- A few models & listeners needed to be split between app & audio languages due to the previous approaching having a lot of codesharing between the two that's no longer applicable with strong types.

Exemptions:
- AppLanguageResourceHandler is now allowed to use ``Locale`` directly so that it can produce localized display names for each audio language. In the future, this could be moved to MachineLocale maybe.
- AppLanguageResourceHandlerTest is now allowed to use parameterized tests. The new parameterized tests that were added are technically violating the principle of now parameterizing the expected output of the test, but these are medium-term tests that will go away when the new language selector is added.
- The test file exemptions aren't technically "new" in the sense that they're just preserving the existing exemptions except that the exemptions are now split in the same way as the new app/audio versions of the classes.

## Essential Checklist
- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only
This section will be filled in post-merge (#4567 is tracking ensuring that the description is finished later).

### CODE REVIEW

File: app/src/main/java/org/oppia/android/app/translation/AppLanguageResourceHandler.kt [hunk 1]
```diff
@@ -133,6 +135,31 @@ class AppLanguageResourceHandler @Inject constructor(
   fun getLayoutDirection(): Int = getDisplayLocale().getLayoutDirection()
 
   /** Returns the current [OppiaLocale.DisplayLocale] used for resource processing. */
-  fun getDisplayLocale(): OppiaLocale.DisplayLocale =
-    appLanguageLocaleHandler.getDisplayLocale()
+  fun getDisplayLocale(): OppiaLocale.DisplayLocale = appLanguageLocaleHandler.getDisplayLocale()
+
+  // TODO: Add tests?
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/translation/AppLanguageResourceHandler.kt]:
```suggestion
```

Should be deleted.

Comment (BenHenning) [reply app/src/main/java/org/oppia/android/app/translation/AppLanguageResourceHandler.kt]: Done.

**Comment by BenHenning** [comment]
I've self-reviewed the code and haven't found any major points of concern.

**Comment by BenHenning** [comment]
Since this PR is part of broader urgent work for the Beta MR1 release, I'm force-merging this without review. I've self-reviewed it and found no major issues. Furthermore, https://github.com/oppia/oppia-android/issues/4567 is tracking ensuring that this does get reviewed by someone else later after it's been merged.
