### PR TITLE
Fix #2035: Update file formatting under dragAndDropSortInput package

### LINKED ISSUE #2035: Fix file formatting under dragAndDropSortInput package
**Describe the bug**
All the files, under the package `domain/src/test/java/org/oppia/android/domain/classify/rules/dragAndDropSortInput` are not in the correct format. 

**Expected behavior**
File format should be follow from this file - [TextInputEqualsRuleClassifierProviderTest](https://github.com/oppia/oppia-android/blob/develop/domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputEqualsRuleClassifierProviderTest.kt
)

**Correct Order**
Constant values
Dagger injection
Local variables
Test Before setup
Tests
Dagger Setup

### PR DESCRIPTION
**Pull request by ShridharGoel**
## Explanation
Fixes #2035 

Updated the files under dragAndDropSortInput package to use methods from `InteractionObjectTestBuilder` instead of creating those methods inside the tests.

## Checklist
- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [ ] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

## Screenshots
Screenshot 1
Screenshot 2
Screenshot 3
Screenshot 4

### CODE REVIEW

File: domain/src/test/java/org/oppia/android/domain/classify/rules/dragAndDropSortInput/DragDropSortInputHasElementXAtPositionYRuleClassifierProviderTest.kt [hunk 1]
```diff
@@ -26,11 +24,23 @@ import kotlin.test.fail
 @LooperMode(LooperMode.Mode.PAUSED)
 @Config(manifest = Config.NONE)
 class DragDropSortInputHasElementXAtPositionYRuleClassifierProviderTest {
-  private val NON_NEGATIVE_VALUE_0 = createNonNegativeInt(value = 1)
-  private val NON_NEGATIVE_VALUE_1 = createNonNegativeInt(value = 2)
-  private val STRING_VALUE_2 = createString(value = "test item 2")
-  private val STRING_VALUE_3 = createString(value = "test item invalid")
-  private val LIST_OF_SETS_OF_HTML_STRING_VALUE = createListOfSetsOfHtmlStrings()
+  private val NON_NEGATIVE_VALUE_0 =
```
Comment (anandwana001) [inline domain/src/test/java/org/oppia/android/domain/classify/rules/dragAndDropSortInput/DragDropSortInputHasElementXAtPositionYRuleClassifierProviderTest.kt:28]: leave a single line above. 
Ditto for all

File: domain/src/test/java/org/oppia/android/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemAtIncorrectPositionClassifierProviderTest.kt [hunk 2]
```diff
@@ -26,20 +24,34 @@ import kotlin.test.fail
...
+      listOf(ITEM_SET_2_ITEM_2, ITEM_SET_3_ITEM_3, ITEM_SET_1_AB)
+    )
   private val SET_LIST_ITEM_A_ITEM_2_ITEM_3 =
-    createListOfSetsOfHtmlStrings(ITEM_SET_1_A, ITEM_SET_2_ITEM_2, ITEM_SET_3_ITEM_3)
+    InteractionObjectTestBuilder.createListOfSetsOfHtmlStrings(
+      listOf(ITEM_SET_1_A, ITEM_SET_2_ITEM_2, ITEM_SET_3_ITEM_3)
+    )
 
   @Inject
   internal lateinit var dragDropSortInputIsEqualToOrderingWithOneItemAtIncorrectPositionClassifierProvider: // ktlint-disable max-line-length
```
Comment (anandwana001) [inline domain/src/test/java/org/oppia/android/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemAtIncorrectPositionClassifierProviderTest.kt]:
```kotlin
 @Inject
  internal lateinit var
    dragDropSortInputIsEqualToOrderingWithOneItemAtIncorrectPositionClassifierProvider:
    DragDropSortInputIsEqualToOrderingWithOneItemAtIncorrectPositionClassifierProvider

  private val isEqualToOrderingWithOneItemIncorrectClassifier: RuleClassifier by lazy {
    dragDropSortInputIsEqualToOrderingWithOneItemAtIncorrectPositionClassifierProvider
      .createRuleClassifier()
  }
```

Can we do this to avoid ktlint disable?

**Review by anandwana001 — CHANGES_REQUESTED** [review]
Thanks @ShridharGoel 
nit changes added

File: domain/src/test/java/org/oppia/android/domain/classify/rules/dragAndDropSortInput/DragDropSortInputHasElementXAtPositionYRuleClassifierProviderTest.kt (hunk 1 above)
Comment (ShridharGoel) [reply domain/src/test/java/org/oppia/android/domain/classify/rules/dragAndDropSortInput/DragDropSortInputHasElementXAtPositionYRuleClassifierProviderTest.kt:28]: Updated.

File: domain/src/test/java/org/oppia/android/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemAtIncorrectPositionClassifierProviderTest.kt (hunk 2 above)
Comment (ShridharGoel) [reply domain/src/test/java/org/oppia/android/domain/classify/rules/dragAndDropSortInput/DragDropSortInputIsEqualToOrderingWithOneItemAtIncorrectPositionClassifierProviderTest.kt]: Done.

**Comment by anandwana001** [comment]
@ShridharGoel Please don't resolve the suggested commits, else the reviewer might lose the suggested changes are done or not. We are following a way where Reviewer resolves the suggested changes.

**Comment by ShridharGoel** [comment]
@anandwana001 Okay.

**Review by anandwana001 — APPROVED** [review]
LGTM, Thanks @ShridharGoel 
Defer to @rt4914 for merge

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.
