### PR TITLE
Fix #135:Topic issues fixes part 2

### LINKED ISSUE #135: UI Structure: Topic activity/fragment
This is tracking introducing the UI structure for the topic page, including constituent tabs: train, play, overview, and review. This does not track introducing the UIs for each tab. See later in this issue for issues blocking this (4 of them should be the corresponding structure issues for each tab).

See #23 for the issue corresponding to the high-fidelity topic page work.

- [ ] Basic implementation of TopicActivity (@nikitamarysolomanpvt )
- [ ] Click on `PromotedStory` in `Home` should open `TopicPlayFragment` and scroll to a specific story item.

### PR DESCRIPTION
**Pull request by nikitamarysolomanpvt**
Duplicate of #279
## Explanation

- Removed dummy button on HomeFragment

- Introduced TopicTestActivity to load TopicFragment for a specific TOPIC_ID which will be used to test-code.

- Introduced TopicTestActivityForStory to load TopicFragment for a specific STORY_ID which will be used to test-code.

- When user clicks the promoted story item in HomeFragment the story id will be passed to TopicActivity.If the TOPIC_ID and STORY_ID is present in TopicActivity then the UI should traverse to a TopicPlay tab to show TopicPlayFragment, scroll to the specific item and then expands it.

## Mock
https://xd.adobe.com/spec/e2239cf4-9cde-4c08-5296-25316c1f0a14-9412/screen/0fad68f5-5ca4-4947-b8db-b4cf07235fd7/Topic-w-o-Play-19

To test TopicFragmentTest, follow these steps:
1. In `AndroidManifest` file make `TopicTestActivity` as launcher activity for testing TopicFragmentTest.
To test TopicTestActivityForStory, follow these steps:
1. In `AndroidManifest` file make `TopicTestActivityForStory` as launcher activity for testing TopicTestActivityForStoryTest.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is **assigned** to an appropriate reviewer.

### CODE REVIEW

File: domain/src/main/java/org/oppia/domain/topic/TopicController.kt [hunk 1]
```diff
@@ -283,8 +283,14 @@ class TopicController @Inject constructor(
       .setName("First Test Topic")
       .setDescription("A topic investigating the interesting aspects of the Oppia Android app.")
       .addStory(createTestTopic0Story0())
-      .addStory(createTestTopic0Story1())
+      .addStory(createTestTopic0Story0())
```
Comment (nikitamarysolomanpvt) [inline domain/src/main/java/org/oppia/domain/topic/TopicController.kt:286]: Added for testing purpose.

File: app/src/main/res/layout/home_fragment.xml [hunk 2]
```diff
@@ -16,32 +16,6 @@
...
     android:orientation="vertical">
 
-    <LinearLayout
-      android:layout_width="match_parent"
-      android:layout_height="wrap_content"
-      android:background="@color/white"
-      android:gravity="center"
-      android:orientation="vertical">
-
-      <Button
```
Comment (nikitamarysolomanpvt) [inline app/src/main/res/layout/home_fragment.xml:26]: If i am supposed to show exploration button please comment.

File: app/src/main/java/org/oppia/app/home/HomeFragmentPresenter.kt [hunk 3]
```diff
@@ -97,11 +95,6 @@ class HomeFragmentPresenter @Inject constructor(
     })
   }
```
Comment (nikitamarysolomanpvt) [inline app/src/main/java/org/oppia/app/home/HomeFragmentPresenter.kt:96]: playExplorationButton is unused. Please Let me know what to do with this.

File: app/src/main/java/org/oppia/app/topic/play/TopicPlayFragmentPresenter.kt [hunk 4]
```diff
@@ -79,6 +92,9 @@ class TopicPlayFragmentPresenter @Inject constructor(
       binding.storySummaryRecyclerView.apply {
         adapter = storySummaryAdapter
       }
+      if (!storyId.isEmpty())
+      binding.storySummaryRecyclerView.layoutManager!!.scrollToPosition(currentExpandedChapterListIndex!!)
```
Comment (jamesxu0) [inline app/src/main/java/org/oppia/app/topic/play/TopicPlayFragmentPresenter.kt]: Nit: Indent please.

File: app/src/main/java/org/oppia/app/topic/play/TopicPlayFragmentPresenter.kt [hunk 5]
```diff
@@ -50,7 +53,11 @@ class TopicPlayFragmentPresenter @Inject constructor(
     topicId = checkNotNull(fragment.arguments?.getString(TOPIC_ID_ARGUMENT_KEY)) {
       "Expected topic ID to be included in arguments for TopicPlayFragment."
     }
-    this.currentExpandedChapterListIndex = currentExpandedChapterListIndex
+    storyId = checkNotNull(fragment.arguments?.getString(STORY_ID_ARGUMENT_KEY) ?: "") {
+      "Expected topic ID to be included in arguments for TopicPlayFragment."
+    }
```
Comment (jamesxu0) [inline app/src/main/java/org/oppia/app/topic/play/TopicPlayFragmentPresenter.kt]: The checkNotNull will never fail. I suggest removing the elvis operator.

File: app/src/main/AndroidManifest.xml [hunk 6]
```diff
@@ -22,7 +22,7 @@
     <activity android:name=".profile.ProfileActivity" />
     <activity
       android:name=".splash.SplashActivity"
-      android:theme="@style/SplashScreenTheme">
+      android:theme="@style/SplashScreenTheme" >
```
Comment (rt4914) [inline app/src/main/AndroidManifest.xml]: Nit: There should no space before `>`

File: app/src/main/java/org/oppia/app/home/HomeFragmentPresenter.kt (hunk 3 above)
Comment (rt4914) [reply app/src/main/java/org/oppia/app/home/HomeFragmentPresenter.kt:96]: Keep it for now, otherwise it will start giving error in test cases that are using that button, which make it hard to run test cases in other files too.

File: app/src/main/java/org/oppia/app/topic/TopicActivity.kt [hunk 7]
```diff
@@ -30,7 +29,7 @@ class TopicActivity : InjectableAppCompatActivity(), RouteToQuestionPlayerListen
       "Expected topic ID to be included in intent for TopicActivity."
     }
     storyId = intent?.getStringExtra(TOPIC_ACTIVITY_STORY_ID_ARGUMENT_KEY) ?: ""
-    topicActivityPresenter.handleOnCreate(topicId)
+    topicActivityPresenter.handleOnCreate(topicId,storyId)
```
Comment (rt4914) [inline app/src/main/java/org/oppia/app/topic/TopicActivity.kt]: Nit: Space after `,`

File: app/src/main/java/org/oppia/app/topic/TopicFragmentPresenter.kt [hunk 8]
```diff
@@ -59,13 +61,15 @@ class TopicFragmentPresenter @Inject constructor(
...
   private fun setUpViewPager(viewPager: ViewPager, topicId: String?) {
-    val adapter = ViewPagerAdapter(fragment.fragmentManager!!, topicId!!)
+    val adapter = ViewPagerAdapter(fragment.fragmentManager!!, topicId!!, storyId)
     viewPager.adapter = adapter
     tabLayout.setupWithViewPager(viewPager)
     tabLayout.getTabAt(0)!!.setText(fragment.getString(R.string.overview)).setIcon(tabIcons[0])
     tabLayout.getTabAt(1)!!.setText(fragment.getString(R.string.play)).setIcon(tabIcons[1])
     tabLayout.getTabAt(2)!!.setText(fragment.getString(R.string.train)).setIcon(tabIcons[2])
     tabLayout.getTabAt(3)!!.setText(fragment.getString(R.string.review)).setIcon(tabIcons[3])
+    if (!topicId.isEmpty() && !storyId.isEmpty())
```
Comment (rt4914) [inline app/src/main/java/org/oppia/app/topic/TopicFragmentPresenter.kt]: Update this to: `if (topicId.isNotEmpty() && storyId.isNotEmpty())`

File: app/src/main/java/org/oppia/app/topic/ViewPagerAdapter.kt [hunk 9]
```diff
@@ -24,6 +28,8 @@ class ViewPagerAdapter(fragmentManager: FragmentManager, private val topicId: St
       }
       TopicTab.PLAY -> {
         val topicPlayTab = TopicPlayFragment()
+        if(!storyId.isEmpty())
```
Comment (rt4914) [inline app/src/main/java/org/oppia/app/topic/ViewPagerAdapter.kt]: Update: `if (storyId.isNotEmpty())`

File: app/src/main/java/org/oppia/app/topic/play/TopicPlayFragmentPresenter.kt [hunk 10]
```diff
@@ -15,6 +15,8 @@ import org.oppia.app.model.ChapterSummary
 import org.oppia.app.model.StorySummary
 import org.oppia.app.model.Topic
 import org.oppia.app.topic.RouteToStoryListener
+import org.oppia.app.topic.STORY_ID_ARGUMENT_KEY
+import org.oppia.app.topic.TOPIC_ACTIVITY_TOPIC_ID_ARGUMENT_KEY
```
Comment (rt4914) [inline app/src/main/java/org/oppia/app/topic/play/TopicPlayFragmentPresenter.kt]: Remove this unused key

File: app/src/main/java/org/oppia/app/topic/play/TopicPlayFragmentPresenter.kt [hunk 11]
```diff
@@ -50,7 +53,11 @@ class TopicPlayFragmentPresenter @Inject constructor(
     topicId = checkNotNull(fragment.arguments?.getString(TOPIC_ID_ARGUMENT_KEY)) {
       "Expected topic ID to be included in arguments for TopicPlayFragment."
     }
-    this.currentExpandedChapterListIndex = currentExpandedChapterListIndex
+    storyId = checkNotNull(fragment.arguments?.getString(STORY_ID_ARGUMENT_KEY) ?: "") {
+      "Expected topic ID to be included in arguments for TopicPlayFragment."
+    }
+    if (!storyId.isEmpty())
```
Comment (rt4914) [inline app/src/main/java/org/oppia/app/topic/play/TopicPlayFragmentPresenter.kt]: Update: `if (storySummary.storyId == storyId) {`

File: app/src/main/java/org/oppia/app/topic/play/TopicPlayFragmentPresenter.kt [hunk 12]
```diff
@@ -68,6 +75,12 @@ class TopicPlayFragmentPresenter @Inject constructor(
 
   private fun subscribeToTopicLiveData() {
     topicLiveData.observe(fragment, Observer<Topic> {
+      it.storyList!!.forEach { storySummary ->
+        if (storySummary.storyId.equals(storyId)) {
+          val index = it.storyList.indexOf(storySummary)
+          currentExpandedChapterListIndex=index
```
Comment (rt4914) [inline app/src/main/java/org/oppia/app/topic/play/TopicPlayFragmentPresenter.kt]: Spacing issue: `currentExpandedChapterListIndex = index`

File: app/src/main/java/org/oppia/app/testing/TopicTestActivityForStory.kt [hunk 13]
```diff
@@ -0,0 +1,65 @@
...
+/** The test activity for [TopicFragment] to test displaying story by storyId. */
+class TopicTestActivityForStory : InjectableAppCompatActivity(), RouteToQuestionPlayerListener, RouteToConceptCardListener,
+  RouteToTopicPlayListener, RouteToStoryListener, RouteToExplorationListener {
+  @Inject
+  lateinit var topicActivityPresenter: TopicActivityPresenter
+
+  override fun onCreate(savedInstanceState: Bundle?) {
+    super.onCreate(savedInstanceState)
+    activityComponent.inject(this)
+    topicActivityPresenter.handleOnCreate(topicId=TEST_TOPIC_ID_0,storyId= TEST_STORY_ID_1)
```
Comment (rt4914) [inline app/src/main/java/org/oppia/app/testing/TopicTestActivityForStory.kt]: Nit: `topicActivityPresenter.handleOnCreate(topicId = TEST_TOPIC_ID_0, storyId = TEST_STORY_ID_1)`

File: app/src/main/java/org/oppia/app/testing/TopicTestActivity.kt [hunk 14]
```diff
@@ -0,0 +1,64 @@
...
+/** The activity for testing [TopicFragment]. */
+class TopicTestActivity : InjectableAppCompatActivity(), RouteToQuestionPlayerListener, RouteToConceptCardListener,
+  RouteToTopicPlayListener, RouteToStoryListener, RouteToExplorationListener {
+  @Inject
+  lateinit var topicActivityPresenter: TopicActivityPresenter
+
+  override fun onCreate(savedInstanceState: Bundle?) {
+    super.onCreate(savedInstanceState)
+    activityComponent.inject(this)
+    topicActivityPresenter.handleOnCreate(topicId=TEST_TOPIC_ID_0,storyId= "")
```
Comment (rt4914) [inline app/src/main/java/org/oppia/app/testing/TopicTestActivity.kt]: Nit: `topicActivityPresenter.handleOnCreate(topicId = TEST_TOPIC_ID_0, storyId = "")`

File: app/src/sharedTest/java/org/oppia/app/topic/TopicFragmentTest.kt [hunk 15]
```diff
@@ -304,7 +305,7 @@ class TopicFragmentTest {
   }
   @Test
```
Comment (rt4914) [inline app/src/sharedTest/java/org/oppia/app/topic/TopicFragmentTest.kt:332]: Add blank line above this

**Review by rt4914 — CHANGES_REQUESTED** [review]
@nikitamarysolomanpvt Test cases are failing.

I know they were passing earlier but they are failing now because of those extra items added in domain layer. So you will need to update the test-cases accordingly.

File: `TopicFragmentTest`
3 fail and 15 pass

Screenshot 2019-11-08 at 9 24 44 AM

File: app/src/main/res/layout/home_fragment.xml (hunk 2 above)
Comment (rt4914) [reply app/src/main/res/layout/home_fragment.xml:26]: I suggest you keep this button for now, otherwise developer's wont be able to run test cases in any file.

File: app/src/main/AndroidManifest.xml [hunk 16]
```diff
@@ -38,6 +38,12 @@
     <activity android:name=".testing.ContentCardTestActivity" />
     <activity android:name=".testing.HtmlParserTestActivity" />
     <activity android:name=".testing.InputInteractionViewTestActivity" />
+    <activity
+      android:name=".testing.TopicTestActivity"
+      android:theme="@style/OppiaThemeWithoutActionBar" />
+    <activity
+      android:name=".testing.TopicTestActivityForStory"
+      android:theme="@style/OppiaThemeWithoutActionBar"/>
```
Comment (veena14cs) [inline app/src/main/AndroidManifest.xml]: nit change: add space before `/>`

File: app/src/main/java/org/oppia/app/activity/ActivityComponent.kt [hunk 17]
```diff
@@ -49,5 +51,7 @@ interface ActivityComponent {
   fun inject(stateFragmentTestActivity: StateFragmentTestActivity)
   fun inject(storyActivity: StoryActivity)
   fun inject(topicActivity: TopicActivity)
+  fun inject(topicTestActivity: TopicTestActivity)
+  fun inject(topicTestActivity: TopicTestActivityForStory)
```
Comment (veena14cs) [inline app/src/main/java/org/oppia/app/activity/ActivityComponent.kt]: Please rename it to `topicTestActvityForStory` both are having same names.

File: app/src/main/res/layout/home_fragment.xml (hunk 2 above)
Comment (nikitamarysolomanpvt) [reply app/src/main/res/layout/home_fragment.xml:26]: Ok done

File: app/src/main/java/org/oppia/app/home/HomeFragmentPresenter.kt (hunk 3 above)
Comment (nikitamarysolomanpvt) [reply app/src/main/java/org/oppia/app/home/HomeFragmentPresenter.kt:96]: Ok

File: app/src/main/AndroidManifest.xml (hunk 6 above)
Comment (nikitamarysolomanpvt) [reply app/src/main/AndroidManifest.xml]: Done

File: app/src/main/java/org/oppia/app/testing/TopicTestActivity.kt (hunk 14 above)
Comment (nikitamarysolomanpvt) [reply app/src/main/java/org/oppia/app/testing/TopicTestActivity.kt]: Done

File: app/src/main/java/org/oppia/app/testing/TopicTestActivityForStory.kt (hunk 13 above)
Comment (nikitamarysolomanpvt) [reply app/src/main/java/org/oppia/app/testing/TopicTestActivityForStory.kt]: Done

File: app/src/main/java/org/oppia/app/topic/TopicActivity.kt (hunk 7 above)
Comment (nikitamarysolomanpvt) [reply app/src/main/java/org/oppia/app/topic/TopicActivity.kt]: Done

File: app/src/main/java/org/oppia/app/topic/TopicActivityPresenter.kt [hunk 18]
```diff
@@ -8,16 +8,20 @@ import javax.inject.Inject
...
 class TopicActivityPresenter @Inject constructor(private val activity: AppCompatActivity) {
-  fun handleOnCreate(topicId: String) {
+
+  fun handleOnCreate(topicId: String, storyId: String) {
     activity.setContentView(R.layout.topic_activity)
     if (getTopicFragment() == null) {
       val topicFragment = TopicFragment()
       val args = Bundle()
       args.putString(TOPIC_ID_ARGUMENT_KEY, topicId)
+      if (!topicId.isEmpty() && !storyId.isEmpty())
```
Comment (veena14cs) [inline app/src/main/java/org/oppia/app/topic/TopicActivityPresenter.kt]: Update this to: `if (topicId.isNotEmpty() && storyId.isNotEmpty())`

File: app/src/main/java/org/oppia/app/topic/TopicFragmentPresenter.kt (hunk 8 above)
Comment (nikitamarysolomanpvt) [reply app/src/main/java/org/oppia/app/topic/TopicFragmentPresenter.kt]: Done

File: app/src/main/java/org/oppia/app/topic/ViewPagerAdapter.kt (hunk 9 above)
Comment (nikitamarysolomanpvt) [reply app/src/main/java/org/oppia/app/topic/ViewPagerAdapter.kt]: Done

File: app/src/main/java/org/oppia/app/topic/play/TopicPlayFragmentPresenter.kt (hunk 10 above)
Comment (nikitamarysolomanpvt) [reply app/src/main/java/org/oppia/app/topic/play/TopicPlayFragmentPresenter.kt]: Done

File: app/src/main/res/layout/home_fragment.xml (hunk 2 above)
Comment (veena14cs) [reply app/src/main/res/layout/home_fragment.xml:26]: +1

File: app/src/main/java/org/oppia/app/topic/play/TopicPlayFragmentPresenter.kt (hunk 5 above)
Comment (nikitamarysolomanpvt) [reply app/src/main/java/org/oppia/app/topic/play/TopicPlayFragmentPresenter.kt]: Done

File: app/src/sharedTest/java/org/oppia/app/testing/TopicTestActivityForStoryTest.kt [hunk 19]
```diff
@@ -0,0 +1,68 @@
...
+          EspressoTestsMatchers.matchCurrentTabTitle(
+            TopicTab.getTabForPosition(1).name
+          )
+        )
+      )
+    }
+  }
+
+  @Test
+  fun testTopicTestActivityForStory_showsTopicPlayFragment() {
```
Comment (veena14cs) [inline app/src/sharedTest/java/org/oppia/app/testing/TopicTestActivityForStoryTest.kt]: Can you rename this to `testTopicTestActivityForStory_showsTopicPlay`

File: app/src/main/java/org/oppia/app/topic/play/TopicPlayFragmentPresenter.kt (hunk 11 above)
Comment (nikitamarysolomanpvt) [reply app/src/main/java/org/oppia/app/topic/play/TopicPlayFragmentPresenter.kt]: Removed

File: app/src/main/java/org/oppia/app/topic/play/TopicPlayFragmentPresenter.kt (hunk 12 above)
Comment (nikitamarysolomanpvt) [reply app/src/main/java/org/oppia/app/topic/play/TopicPlayFragmentPresenter.kt]: Done

File: app/src/main/java/org/oppia/app/topic/play/TopicPlayFragmentPresenter.kt (hunk 4 above)
Comment (nikitamarysolomanpvt) [reply app/src/main/java/org/oppia/app/topic/play/TopicPlayFragmentPresenter.kt]: Done

**Review by veena14cs — CHANGES_REQUESTED** [review]

**Comment by veena14cs** [comment]
> @nikitamarysolomanpvt Test cases are failing.
> 
> I know they were passing earlier but they are failing now because of those extra items added in domain layer. So you will need to update the test-cases accordingly.
> 
> File: `TopicFragmentTest`
> 3 fail and 15 pass
> 
> Screenshot 2019-11-08 at 9 24 44 AM

+1

File: app/src/sharedTest/java/org/oppia/app/topic/TopicFragmentTest.kt (hunk 15 above)
Comment (nikitamarysolomanpvt) [reply app/src/sharedTest/java/org/oppia/app/topic/TopicFragmentTest.kt:332]: Done

**Comment by nikitamarysolomanpvt** [comment]
> @nikitamarysolomanpvt Test cases are failing.
> 
> I know they were passing earlier but they are failing now because of those extra items added in domain layer. So you will need to update the test-cases accordingly.
> 
> File: `TopicFragmentTest`
> 3 fail and 15 pass
> 
> Screenshot 2019-11-08 at 9 24 44 AM

Resolved

File: app/src/main/java/org/oppia/app/activity/ActivityComponent.kt (hunk 17 above)
Comment (nikitamarysolomanpvt) [reply app/src/main/java/org/oppia/app/activity/ActivityComponent.kt]: Done

File: app/src/sharedTest/java/org/oppia/app/testing/TopicTestActivityForStoryTest.kt (hunk 19 above)
Comment (nikitamarysolomanpvt) [reply app/src/sharedTest/java/org/oppia/app/testing/TopicTestActivityForStoryTest.kt]: Done

File: app/src/main/AndroidManifest.xml (hunk 16 above)
Comment (nikitamarysolomanpvt) [reply app/src/main/AndroidManifest.xml]: Resolved

File: app/src/main/java/org/oppia/app/topic/TopicActivityPresenter.kt (hunk 18 above)
Comment (nikitamarysolomanpvt) [reply app/src/main/java/org/oppia/app/topic/TopicActivityPresenter.kt]: Done

**Comment by rt4914** [comment]
@nikitamarysolomanpvt given that #285 has been merged can you change the base branch for this PR to `develop`?

File: app/src/main/java/org/oppia/app/topic/ViewPagerAdapter.kt [hunk 20]
```diff
@@ -24,6 +28,8 @@ class ViewPagerAdapter(fragmentManager: FragmentManager, private val topicId: St
       }
       TopicTab.PLAY -> {
         val topicPlayTab = TopicPlayFragment()
+        if(storyId.isNotEmpty())
```
Comment (rt4914) [inline app/src/main/java/org/oppia/app/topic/ViewPagerAdapter.kt]: Nit: `if (storyId.isNotEmpty())`

**Review by rt4914 — APPROVED** [review]
LGTM. Test cases are passing now.

File: app/src/sharedTest/java/org/oppia/app/testing/TopicTestActivityForStoryTest.kt [hunk 21]
```diff
@@ -0,0 +1,68 @@
...
+/** Tests for [TopicTestActivityForStory]. */
+@RunWith(AndroidJUnit4::class)
+class TopicTestActivityForStoryTest {
+
+  @Test
+  fun testTopicTestActivityForStory_defaultTabIsPlay_isSuccessful() {
+    launch(TopicTestActivityForStory::class.java).use {
+      onView(withId(R.id.topic_tabs_container)).check(
+        matches(
+          EspressoTestsMatchers.matchCurrentTabTitle(
```
Comment (veena14cs) [inline app/src/sharedTest/java/org/oppia/app/testing/TopicTestActivityForStoryTest.kt]: Remove `EspressoTestsMatchers` and use `matchCurrentTabTitle` from import.

**Review by veena14cs — APPROVED** [review]
Resolve 1 nit change and you can proceed.

File: app/src/main/java/org/oppia/app/topic/ViewPagerAdapter.kt (hunk 20 above)
Comment (nikitamarysolomanpvt) [reply app/src/main/java/org/oppia/app/topic/ViewPagerAdapter.kt]: Done

File: app/src/sharedTest/java/org/oppia/app/testing/TopicTestActivityForStoryTest.kt (hunk 21 above)
Comment (nikitamarysolomanpvt) [reply app/src/sharedTest/java/org/oppia/app/testing/TopicTestActivityForStoryTest.kt]: Done
