### PR TITLE
Fix #2450: Fix test testRecentlyPlayedTestActivity_clickOnToolbarNavigationButton_closeActivity [Testing]

### LINKED ISSUE #2450: Fix test testRecentlyPlayedTestActivity_clickOnToolbarNavigationButton_closeActivity [Testing]
**Describe the bug**
The test `testRecentlyPlayedTestActivity_clickOnToolbarNavigationButton_closeActivity` is only performing action.
Find this test in `RecentlyPlayedFragmentTest` app module.

**Expected behavior**
3 components of Espresso test 
1. ViewMatchers
2. ViewActions
3. ViewAssertions

There are no ViewAssertions in this test case, which means this test is checking nothing. As per the test name, we need to test the activity is closing or not.

### PR DESCRIPTION
**Pull request by viktoriias**
## Explanation

Fixes #2450
I added assertion in test testRecentlyPlayedTestActivity_clickOnToolbarNavigationButton_closeActivity.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by anandwana001** [comment]
Could you please add a screenshot showing test is passing on both espresso and robolectric?

**Comment by viktoriias** [comment]
> Could you please add a screenshot showing test is passing on both espresso and robolectric?

Screen Shot 2021-02-28 at 9 40 59 PM

**Comment by viktoriias** [comment]
ktlint passes locally:

Screen Shot 2021-02-28 at 10 04 29 PM

File: app/src/sharedTest/java/org/oppia/android/app/home/RecentlyPlayedFragmentTest.kt [hunk 1]
```diff
@@ -18,17 +18,23 @@ import androidx.test.espresso.intent.matcher.IntentMatchers.hasComponent
...
+import androidx.test.espresso.matcher.ViewMatchers.withContentDescription
 import androidx.test.espresso.matcher.ViewMatchers.withId
 import androidx.test.espresso.matcher.ViewMatchers.withParent
 import androidx.test.espresso.matcher.ViewMatchers.withText
 import androidx.test.ext.junit.runners.AndroidJUnit4
+import androidx.test.rule.ActivityTestRule
+import com.google.common.truth.Truth.assertThat
 import dagger.Component
+import javax.inject.Inject
+import javax.inject.Singleton
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/home/RecentlyPlayedFragmentTest.kt]: This is causing the ktlint failure, also I think this change is not required in this PR as it is just a replacing of line. Could you try fixing this and push again.

**Review by anandwana001 — CHANGES_REQUESTED** [review]

File: app/src/sharedTest/java/org/oppia/android/app/home/RecentlyPlayedFragmentTest.kt (hunk 1 above)
Comment (viktoriias) [reply app/src/sharedTest/java/org/oppia/android/app/home/RecentlyPlayedFragmentTest.kt]: Removing these causing errors

File: app/src/sharedTest/java/org/oppia/android/app/home/RecentlyPlayedFragmentTest.kt [hunk 2]
```diff
@@ -98,6 +102,11 @@ import javax.inject.Singleton
 )
 class RecentlyPlayedFragmentTest {
 
+  @get:Rule
+  var activityTestRule: ActivityTestRule<RecentlyPlayedActivity> = ActivityTestRule(
```
Comment (rt4914) [inline app/src/sharedTest/java/org/oppia/android/app/home/RecentlyPlayedFragmentTest.kt]: Change `var` to `val`

**Review by rt4914 — CHANGES_REQUESTED** [review]
@viktoriias Suggested nit change.

File: app/src/sharedTest/java/org/oppia/android/app/home/RecentlyPlayedFragmentTest.kt (hunk 1 above)
Comment (rt4914) [reply app/src/sharedTest/java/org/oppia/android/app/home/RecentlyPlayedFragmentTest.kt]: @viktoriias Actually @anandwana001 is mentioning that this PR changes the order of the imports. We do need all these imports. But the order is incorrect. All `javax` related imports should come in last and in alphabetical order.

File: app/src/sharedTest/java/org/oppia/android/app/home/RecentlyPlayedFragmentTest.kt (hunk 2 above)
Comment (viktoriias) [reply app/src/sharedTest/java/org/oppia/android/app/home/RecentlyPlayedFragmentTest.kt]: Done.

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

File: app/src/sharedTest/java/org/oppia/android/app/home/RecentlyPlayedFragmentTest.kt (hunk 1 above)
Comment (viktoriias) [reply app/src/sharedTest/java/org/oppia/android/app/home/RecentlyPlayedFragmentTest.kt]: Done thanks, I moved `javax` down. Although, Android studio keeps trying to move it back because `javax` comes before `org` alphabeticaly.

**Comment by anandwana001** [comment]
> > Could you please add a screenshot showing test is passing on both espresso and robolectric?
> 
> Screen Shot 2021-02-28 at 9 40 59 PM

Is it passing on Espresso too?

**Comment by viktoriias** [comment]
> > > Could you please add a screenshot showing test is passing on both espresso and robolectric?
> > 
> > 
> > Screen Shot 2021-02-28 at 9 40 59 PM
> 
> Is it passing on Espresso too?

Yes, finally got it to work: 
Screen Shot 2021-03-01 at 10 17 02 PM

**Review by anandwana001 — APPROVED** [review]
LGTM, Thanks @viktoriias
