### PR TITLE
Fix #5736, Fix #5721, Fix 5954, Fix 5636 and Fix part of #5800: 0.16 beta bug fixes

### LINKED ISSUE #5636: [BUG]: Developer Options Fails to Reopen After Back Navigation in Developer Build
### Describe the bug
When users select either **Developer Options** or **Administrator Controls** from the navigation drawer and subsequently press the back button to return, attempting to reopen these same options from the navigation drawer fails. The corresponding activities do not launch upon subsequent attempts, creating a broken user experience.

### Steps to Reproduce
1. Build and launch the app in a developer environment
2. Open the navigation drawer
3. Click on "Developer Options" (works correctly on initial launch)
4. Press the device's back button
5. Open the navigation drawer again
6. Click on "Developer Options" (fails to reopen)

The same issue occurs with "Administrator Controls."

### Expected Behavior
The selected activity (Developer Options or Administrator Controls) should reopen consistently when selected from the navigation drawer, regardless of previous navigation.

### Actual Behavior
The activities fail to reopen after being dismissed via the back button.

### Screenshots/Video
[Video Demonstration](https://github.com/user-attachments/assets/0fdca793-7e08-4e90-8e0b-a2987bfb1b65)

### Root Cause
The issue is caused by how the `NavigationDrawerFragmentPresenter` manages "selected state" for the footer items (`isDeveloperOptionsSelected` and `isAdministratorControlsSelected`).  

When a user first opens Developer Options or Administrator Controls, the code explicitly sets the corresponding state flag:  
```kotlin
footerViewModel.isDeveloperOptionsSelected.set(true)
footerViewModel.isAdministratorControlsSelected.set(true)
```
Later, when the drawer item is clicked again, the click listener checks:
```kotlin
if (footerViewModel.isDeveloperOptionsSelected.get() == true) {
  drawerLayout.closeDrawers()
  return@setOnClickListener
}
```
This means the drawer assumes the item is already selected and does nothing, even though the activity was closed when the user pressed the back button. The "selected" state is never reset, leaving the drawer in a stuck state.

#### Code Changes
Navigate to [`NavigationDrawerFragmentPresenter.kt`](https://github.com/oppia/oppia-android/blob/96af5e5f11dbf856eef5be9f0ccf264fde4491d6/app/src/main/java/org/oppia/android/app/drawer/NavigationDrawerFragmentPresenter.kt) and remove the following lines:

1. **Line 110**: `footerViewModel.isDeveloperOptionsSelected.set(true)`
2. **Line 145**: `footerViewModel.isAdministratorControlsSelected.set(true)`

By removing the explicit state-setting lines the drawer no longer marks these items as “selected.” As a result:
Each time the user taps Developer Options or Administrator Controls, the click listener executes and launches the activity.

There is no stale state preventing re-entry after the user presses back.

This aligns with the intended navigation behavior: always launch the requested activity when tapped.
#### Expected Behavior After Fix
After applying these changes, the navigation drawer items should consistently reopen their respective activities:

https://github.com/user-attachments/assets/968426f6-2ad5-4374-b0e8-a2308bf25561

### Testing
Add verification tests in [`NavigationDrawerActivityDebugTest.kt`](https://github.com/oppia/oppia-android/blob/86b79136628212e38b2d2f570375a941cb8459fd/app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerActivityDebugTest.kt#L136) to ensure the fixed behavior works correctly.

### What device/emulator are you using?

OPPO Reno2 F

### Which Android version is your device/emulator running?

Android 11

### Which version of the Oppia Android app are you using?

0.14-oppia-2fcc3b5653

### LINKED ISSUE #5721: [BUG]: Multiplying by powers of 10: the content of the page is not showing completly in the text box
### Describe the bug

In the Multiplying by powers of 10 lesson there is a page where its content is not being displayed completly in the text box The last letters do not appear in the text box.  

This happens in English and Portuguese language.

### Steps To Reproduce

Steps:

1. Go to Multiplication
2. Go to Multiplying by powers of 10
3. Playthrough the lesson
4. See a text box that the content is not shown completly 

### Expected Behavior

It expected to see the content fully 

### Screenshots/Videos

Image

### What device/emulator are you using?

OPPPO A79 5G

### Which Android version is your device/emulator running?

Android 14

### Which version of the Oppia Android app are you using?

0.14-beta-17f2ef3044

### Additional Context

_No response_

### LINKED ISSUE #5736: What multiplication means:  The factor 4 is missing in the expression 74x4
In an explanation about the Commutative property of multiplication the there is an expression that the factor is missing.
3x4 = 4x3
6x1 = 1x6
4x74 = 74 x ---

Steps:

1. Change to Portuguese language
2. Go to Multiplication
3. Go to What Multiplication means
4. Playthrough the chapter until the explanation about commutative property
5. See the factor 4 missing in the expression  4x74 = 74 x 

Image

------
## Issue Breakdown
This issue occurs only on the last bullet point where last character is cut off due to incorrect trimming.

### Steps to Reproduce
- Open the "First Test Topic".
- Click "STUDY"
- Open "Test Subtopic"
- Scroll down to the last and notice that the last letter "D" is cut off.

### Screenshot
See the attached screenshot for reference.
<td align="center">
      Light
    </td>

### Cause
The issue happens because `HtmlCompat.fromHtml() `outputs two trailing `\n `for normal paragraphs but only one trailing `\n` for list items (`<li>`). Since the existing trimming logic always removed 2, it not only removed the newline from `<li>` but also trimmed the last character of the text, causing the cutoff in the last bullet point.

### Proposed Solution
Update the trimming logic in [HtmlParser.kt](https://github.com/oppia/oppia-android/blob/86b79136628212e38b2d2f570375a941cb8459fd/utility/src/main/java/org/oppia/android/util/parser/html/HtmlParser.kt#L179) to remove only trailing `\n` characters without trimming the final text character

**Existing Logic:**
 https://github.com/oppia/oppia-android/blob/86b79136628212e38b2d2f570375a941cb8459fd/utility/src/main/java/org/oppia/android/util/parser/html/HtmlParser.kt#L182

**Testing:** 

- Use the "[Test Subtopic](https://github.com/oppia/oppia-android/blob/86b79136628212e38b2d2f570375a941cb8459fd/domain/src/main/assets/test_topic_id_0_1.textproto#L1)" for testing and verification.

### LINKED ISSUE #5954: [BUG]: Exploration does not exit and user stuck in the middle of exploration after cancelling survey
### Describe the bug

After encountering the survey dialog and selecting "Maybe Later", the exploration does not exit. The user becomes stuck in the exploration where submitting answers or navigating to previous cards no longer works, leaving the learner in a broken state.

### Steps To Reproduce

- Install the app (use a fresh install to ensure the survey dialog appears).
- Open "First Test Topic".
- Start "Prototype Exploration".
- Progress to any question (e.g., _"Which bird can sustain flight..."_).
- Wait at least 5 minutes (to fulfill the survey dialog condition).
- Tap the "X" button in the top-left corner — the survey dialog appears.
- In the survey dialog, click "Maybe Later".
- See submit button and previous state navigation button is not working.

### Expected Behavior

The user should be navigated away from the ExplorationActivity if they decline the survey or cancel an in-progress survey.

### Screenshots/Videos

https://github.com/user-attachments/assets/25910ed3-1e83-4a2a-9bf8-33baec6a96b7

 **Stacktrace**
```php

            java.lang.IllegalStateException: Session isn't initialized yet.
            	at org.oppia.android.domain.exploration.ExplorationProgressController.sendCommandForOperation(ExplorationProgressController.kt:612)
            	at org.oppia.android.domain.exploration.ExplorationProgressController.submitAnswer(ExplorationProgressController.kt:268)
            	at org.oppia.android.app.player.state.StateFragmentPresenter.handleSubmitAnswer(StateFragmentPresenter.kt:449)
            	at org.oppia.android.app.player.state.StateFragmentPresenter.onSubmitButtonClicked(StateFragmentPresenter.kt:218)
            	at org.oppia.android.app.player.state.StateFragment.onSubmitButtonClicked(StateFragment.kt:135)
            	at org.oppia.android.app.databinding.databinding.SubmitButtonItemBindingImpl._internalCallbackOnClick(SubmitButtonItemBindingImpl.java:300)
            	at org.oppia.android.app.databinding.generated.callback.OnClickListener.onClick(OnClickListener.java:11)
            	at android.view.View.performClick(View.java:7575)
            	at android.view.View.performClickInternal(View.java:7531)
            	at android.view.View.access$3900(View.java:842)
            	at android.view.View$PerformClick.run(View.java:28866)
            	at android.os.Handler.handleCallback(Handler.java:938)
            	at android.os.Handler.dispatchMessage(Handler.java:99)
            	at android.os.Looper.loop(Looper.java:264)
            	at android.app.ActivityThread.main(ActivityThread.java:8312)
            	at java.lang.reflect.Method.invoke(Native Method)
            	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
            	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

```

### What device/emulator are you using?

Oppo reno 2f

### Which Android version is your device/emulator running?

_No response_

### Which version of the Oppia Android app are you using?

_No response_

### Additional Context
This issue occurs because the exploration session is stopped before the survey dialog is shown. When the user cancels the survey by clicking "Maybe Later", they are returned to the same exploration screen, but the underlying session has already been destroyed. As a result, the user cannot submit answers or navigate between cards, leaving the exploration in a broken state.

**Files to check:**

- [survey_welcome_dialog_fragment.xml](https://github.com/oppia/oppia-android/blob/fcb87dc79074450f90a658c9dddb186a12ab75f3/app/src/main/res/layout/survey_welcome_dialog_fragment.xml#L58)
- [SurveyWelcomeDialogFragmentPresenter](https://github.com/oppia/oppia-android/blob/fcb87dc79074450f90a658c9dddb186a12ab75f3/app/src/main/java/org/oppia/android/app/survey/SurveyWelcomeDialogFragmentPresenter.kt#L53)
- [ExplorationActivityPresenter](https://github.com/oppia/oppia-android/blob/fcb87dc79074450f90a658c9dddb186a12ab75f3/app/src/main/java/org/oppia/android/app/player/exploration/ExplorationActivityPresenter.kt#L56) → functions: `stopExploration()`, `maybeShowSurveyDialog()`

### PR DESCRIPTION
**Pull request by adhiamboperes**
## Explanation

Fix #5736: The last character in the list is truncated because
https://github.com/oppia/oppia-android/blob/cda4f44e36222fae5fc8672c774cc8c281f97156/utility/src/main/java/org/oppia/android/util/parser/html/HtmlParser.kt#L179 
deletes 2 characters from the end if the text ends with a single `\n`, which is too aggressive. This means it deletes the last character (4) and the \n, when it should only delete the \n.

The safest solution is to trim all leading and trailing `\n` characters, not just one. That way, whether there’s 1, 2, or 10 newlines at the edges, they’ll be removed without touching non-\n characters.

|Before|After|
|--|--|
|Image|image|

Fix https://github.com/oppia/oppia-android/issues/5721:

Per @subhajitxyz's proposed solution in https://github.com/oppia/oppia-android/issues/5721#issuecomment-2854101478,  We need to calculate the width of the text outside of `drawLeadingMargin()`, so that `getLeadingMargin()` can return the correct computedLeadingMargin independently. We do this by passing a reference of the TextView  to the tag handler so that we can use it to construct a matching `TextPaint` object and dynamically calculate the prefix width (e.g., "1.", "10.") using its font, text size, and other styling. This will allow us to decouple `getLeadingMargin()` from `drawLeadingMargin()` and compute the margin correctly during layout. 

|||
|--|--|
|Image| Screenshot_2025-09-04-23-43-44-057_org oppia android|
|Image|Screenshot_2025-09-04-23-40-19-274_org oppia android|

Fix #5636

The developer options and admin controls menu item faailed to reopen because of respective variables in `NavigationDrawerFragmentPresenter` being set to true to indicate that they are already open, as well as forcing the drawer to close.

Unfortunately, tests for repeated opening are blocked by known issue: https://github.com/oppia/oppia-android/issues/2535.

Fix #5954

This bug is caused by the survey being shown AFTER the exploration has been stopped, so attempting to play the exploration results into the frozen state. The user is still able to exit the exploration normally by clicking the close or return to topic buttons again, but this creates an inconsistent UX.

The bug is fixed by navigating the user away from the ExplorationActivity if they decline the survey.

Some minor changes have been made to the survey code to remove some redundancies.

|Before|After|
|--|--|
|https://github.com/user-attachments/assets/5bed7d7b-6d78-427a-a105-86fc0f15fd08|https://github.com/user-attachments/assets/cb6f042f-3e2c-4ae7-b972-75cf08a2f137|

Fix part of #5800

The survey gets dismissed due to the gating provider updating as a result of the combined profile DataProvider updates. Immediately the survey popup is shown, the `surveyLastShownTimestampMs` field of a profile gets update, and this updates downstream providers that are subscribed to the profile provider. This has been fixed by removing the observer to the gating provider once it has returned the first time. This happened only on clicking "return to question".

This was not possible to test in `StateFragmentTest` because of issues with dragAndDrop on robolectric, preventing playing through and exploration. I spent a considerable amount of time trying to set up the test using the Ratios exploration, but experienced difficulty with item selection in state 19 -- the images are large and scrolling is needed to see and click all the options, but I was not able to make this work at this time. So keeping the issue open to track adding tests either by fixing the ratios playthrough, or the drag and drop issue.

|Before|After|
|--|--|
|. |https://github.com/user-attachments/assets/cb6f042f-3e2c-4ae7-b972-75cf08a2f137|

The PR also bumps versions for the release.

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

### CODE REVIEW

**Comment by adhiamboperes** [comment]
@BenHenning and @manas-yu, please take a look at a couple of these release blocking issues.

File: utility/src/main/java/org/oppia/android/util/parser/html/HtmlParser.kt [hunk 1]
```diff
@@ -178,9 +179,21 @@ class HtmlParser private constructor(
 
   private fun trimSpannable(spannable: SpannableStringBuilder): SpannableStringBuilder {
```
Comment (manas-yu) [inline utility/src/main/java/org/oppia/android/util/parser/html/HtmlParser.kt:180]: Slight improvement.

```suggestion
  private fun trimSpannable(spannable: SpannableStringBuilder): SpannableStringBuilder {
  val text = spannable.toString()
  val start = text.indexOfFirst { it != '\n' }.coerceAtLeast(0)
  val end = text.indexOfLast { it != '\n' }.takeIf { it >= 0 }?.plus(1) ?: start
  return SpannableStringBuilder(spannable.subSequence(start, end))
}
```

File: utility/src/main/java/org/oppia/android/util/parser/html/LiTagHandler.kt [hunk 2]
```diff
@@ -32,6 +33,13 @@ class LiTagHandler(
   private val latestPendingList: ListTag<*, *>?
     get() = pendingLists.lastOrNull()
 
+  private var currentTextView: TextView? = null
+
+  /** Sets the TextView reference for calculating text measurements. */
+  fun setTextView(textView: TextView) {
```
Comment (manas-yu) [inline utility/src/main/java/org/oppia/android/util/parser/html/LiTagHandler.kt:39]: This seems a better approach than in #5840. Thanks!

**Review by manas-yu — CHANGES_REQUESTED** [review]
Hi @adhiamboperes There are CI fails right now but just few comments for now.

File: utility/src/main/java/org/oppia/android/util/parser/html/HtmlParser.kt (hunk 1 above)
Comment (adhiamboperes) [reply utility/src/main/java/org/oppia/android/util/parser/html/HtmlParser.kt:180]: Thanks for this suggestion @manas-yu! I have however decided not to go with it because while it is a much more consise solution, it is a bit harder to read especially for contributors with low farmiliarity with Kotlin functions. Using loops are simpler, while at the same time have similar peformance and thoroughness as your suggestion.

Comment (manas-yu) [reply utility/src/main/java/org/oppia/android/util/parser/html/HtmlParser.kt:180]: Mahes sense, thanks!

**Comment by adhiamboperes** [comment]
@manas-yu, could you please tajke a second look? There are new chnages since the review last week.

**Review by manas-yu — APPROVED** [review]
Thanks @adhiamboperes changes looks good to me.

File: scripts/assets/test_file_exemptions.textproto [hunk 3]
```diff
@@ -2337,6 +2337,9 @@ test_file_exemption {
   test_file_not_required: true
 }
 test_file_exemption {
+  exempted_file_path: "app/src/main/java/org/oppia/android/app/survey/DismissSurveyListener.kt"
+  test_file_not_required: true
+}test_file_exemption {
```
Comment (BenHenning) [inline scripts/assets/test_file_exemptions.textproto:2342]:
```suggestion
}
test_file_exemption {
```

**Review by BenHenning — APPROVED** [review]
Had one comment--let's defer it to a different PR to unblock this. Thanks @adhiamboperes!

File: scripts/assets/test_file_exemptions.textproto (hunk 3 above)
Comment (BenHenning) [reply scripts/assets/test_file_exemptions.textproto:2342]: @adhiamboperes took note of this to do it in a later PR. Resolving to unblock the PR for the 0.16 release.
