### PR TITLE
Fix #4735 Text unit is set in dp instead of sp

### LINKED ISSUE #4735: Text unit is set in dp instead of sp
**Describe the bug**

The text unit is dp instead sp which results in an accessibility error.

**To Reproduce**
1. On profiles page, click on add user profile option
2. Toolbar text has accessibility issue

**Suggested Solution**:
If you notice code of https://github.com/oppia/oppia-android/blob/da80fab4a78997cb8ab190292f0676117f2722fc/app/src/main/res/layout/admin_pin_activity.xml
 we are not using any `Toolbar in this xml file`. Instead we are setting the title from https://github.com/oppia/oppia-android/blob/da80fab4a78997cb8ab190292f0676117f2722fc/app/src/main/java/org/oppia/android/app/profile/AdminAuthActivityPresenter.kt#L119
 What we can do is that instead of using the toolbar/action-bar of activity we can introduce our own `Toolbar` in xml file and can use it in activity & its presenter to set the text. This way we can easily control sp vs dp metric. 
[Similar Implementation](https://github.com/oppia/oppia-android/blob/da80fab4a78997cb8ab190292f0676117f2722fc/app/src/main/res/layout/add_profile_activity.xml)

**Environment**
- Device/emulator being used: <Vivo V25 pro>
- Android or SDK version (e.g. Android 5 or SDK 21): Android 12
- App version (you can get this through system app settings or via the admin controls menu in-app): 0.10-beta-5e64fae55e

### PR DESCRIPTION
**Pull request by Vishwajith-Shettigar**
## Explanation
Fix  #4735 , Added toolbar in admin_pin_activity xml file inorder to control the title size using sp.

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

Before fix
Admin pin activity
| Light mode| 
|--------|
|before light | 

After fix
|Light mode| Dark mode|
|-----------|--------------|
| afterlightmode | afterdarkmode |

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### CODE REVIEW

**Comment by Vishwajith-Shettigar** [comment]
**Here is screenshot for accessability**

Screenshot_20230814_134830
Screenshot_20230814_134904

File: app/src/main/java/org/oppia/android/app/profile/AdminPinActivityPresenter.kt [hunk 1]
```diff
@@ -45,11 +45,15 @@ class AdminPinActivityPresenter @Inject constructor(
     val binding =
       DataBindingUtil.setContentView<AdminPinActivityBinding>(activity, R.layout.admin_pin_activity)
 
+
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/profile/AdminPinActivityPresenter.kt]: Only one whitespace is allowed between lines of code

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
I think that this is definitely a good approach.

The screenshots that you have shared don't seem to be from the accessibility scanner. Please refer to our wiki section on accessibility if you need help with that.

**Comment by Vishwajith-Shettigar** [comment]
> I think that this is definitely a good approach.
> 
> The screenshots that you have shared don't seem to be from the accessibility scanner. Please refer to our wiki section on accessibility if you need help with that.

Here is accessability scanner screenshot. 

Android version 10
When I scanned, I have got no suggestions, please guide me if something is wrong here.
WhatsApp Image 2023-08-15 at 9 02 57 PM

**Comment by Vishwajith-Shettigar** [comment]
Hey please tell is this issue android 12 specific, I haven't tried accessability Scanner with 12
Edit: Attached 12 also

**Comment by Vishwajith-Shettigar** [comment]
Android 12 
Accessability scanner screenshot

onemore

**Comment by adhiamboperes** [comment]
> Here is accessability scanner screenshot.
> 
> Android version 10 When I scanned, I have got no suggestions, please guide me if something is wrong here. 

Basically;
1. You need to be able to verify that you can reproduce the issue. You can do this by switching to a branch like develop, deploying your app on that branch, then running the accessibility scanner for this screen. You should see the warnings same as in the issue description. (Save the screenshot, because you need to add it it to the description of this PR)
2.  Next, switch back to your branch(that contains your fix), and deploy the app, test it with the accessibility scanner. essentially, if your fix works, all the warnings should be gone(no suggestions). You will also add this screenshot to the  PR description for before/after proof.

**Comment by adhiamboperes** [comment]
Your changes have led to some failing tests, [here](https://github.com/oppia/oppia-android/wiki/Interpreting-CI-Results) is information on how to find what is broken, so you can update the code or tests as appropriate.

**Comment by Vishwajith-Shettigar** [comment]
> > Here is accessability scanner screenshot.
> > Android version 10 When I scanned, I have got no suggestions, please guide me if something is wrong here.
> 
> Basically;
> 
> 1. You need to be able to verify that you can reproduce the issue. You can do this by switching to a branch like develop, deploying your app on that branch, then running the accessibility scanner for this screen. You should see the warnings same as in the issue description. (Save the screenshot, because you need to add it it to the description of this PR)
> 2. Next, switch back to your branch(that contains your fix), and deploy the app, test it with the accessibility scanner. essentially, if your fix works, all the warnings should be gone(no suggestions). You will also add this screenshot to the  PR description for before/after proof.

Here is before fix 
befforetoolbar

After fix

onemore

**Comment by adhiamboperes** [comment]
The screenshots look good. Thanks!

**Comment by adhiamboperes** [comment]
Hi @Vishwajith-Shettigar, once you are done making changes, please do the following:

- [ ] Go to the PR description and make sure you have done all the items on the Essential Checklist, and check them off
- [ ]  Assign the PR to Ben Henning by mentioning him with ["@(Ben Henning), PTAL"](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#step-3-address-review-comments-until-all-reviewers-give-lgtm).

**Comment by Vishwajith-Shettigar** [comment]
> Hi @Vishwajith-Shettigar, once you are done making changes, please do the following:
> 
> * [x]  Go to the PR description and make sure you have done all the items on the Essential Checklist, and check them off
> * [x]   Assign the PR to Ben Henning by mentioning him with ["@(Ben Henning), PTAL"](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#step-3-address-review-comments-until-all-reviewers-give-lgtm).

hey actually I'm not able to understand why my checks are failing, can you give some idea about this please, that would be very helpful. @BenHenning

**Comment by Vishwajith-Shettigar** [comment]
Can you guide me why some checks are failing please ?

**Comment by MohitGupta121** [comment]
@Vishwajith-Shettigar you this particular Robolectric [test](https://github.com/oppia/oppia-android/blob/d74576dae6ec2e6a8d14226ae47ab2f87ef6c881/app/src/sharedTest/java/org/oppia/android/app/profile/AdminPinActivityTest.kt#L570) is failing becasue the content description of the new toolbar you introdue is not matching with the exact close icon. Test unable to find particular view. See the [log](https://github.com/oppia/oppia-android/actions/runs/5898974480/job/16026978670?pr=5134#step:17:570).


For more details go through this [wiki](https://github.com/oppia/oppia-android/wiki/Interpreting-CI-Results#how-to-find-error-message-for-failing-ci-checks)

**Comment by Vishwajith-Shettigar** [comment]
> @Vishwajith-Shettigar you this particular Robolectric [test](https://github.com/oppia/oppia-android/blob/d74576dae6ec2e6a8d14226ae47ab2f87ef6c881/app/src/sharedTest/java/org/oppia/android/app/profile/AdminPinActivityTest.kt#L570) is failing becasue the content description of the new toolbar you introdue is not matching with the exact close icon. Test unable to find particular view. See the [log](https://github.com/oppia/oppia-android/actions/runs/5898974480/job/16026978670?pr=5134#step:17:570).
> 
> For more details go through this [wiki](https://github.com/oppia/oppia-android/wiki/Interpreting-CI-Results#how-to-find-error-message-for-failing-ci-checks)

okay, thank you.

**Comment by Vishwajith-Shettigar** [comment]
@BenHenning ,PTAL

**Comment by Vishwajith-Shettigar** [comment]
somebody please take a look!

**Comment by Vishwajith-Shettigar** [comment]
@adhiamboperes  can you guide me about further steps please.

**Comment by MohitGupta121** [comment]
@Vishwajith-Shettigar if you have done with requested changes by Adhiambo, then wait for review or you can pick another issue for now if this is your 1st PR. Thanks!

**Comment by Vishwajith-Shettigar** [comment]
> @Vishwajith-Shettigar if you have done with requested changes by Adhiambo, then wait for review or you can pick another issue for now if this is your 1st PR. Thanks!

Thank you got it.

File: app/src/main/java/org/oppia/android/app/profile/AdminPinActivityPresenter.kt (hunk 1 above)
Comment (Vishwajith-Shettigar) [reply app/src/main/java/org/oppia/android/app/profile/AdminPinActivityPresenter.kt]: resolved

File: app/src/main/AndroidManifest.xml [hunk 2]
```diff
@@ -138,6 +138,7 @@
     <activity
       android:name=".app.profile.AdminPinActivity"
       android:label="@string/admin_pin_activity_title"
+    android:theme="@style/OppiaThemeWithoutActionBar"
```
Comment (adhiamboperes) [inline app/src/main/AndroidManifest.xml]: nit: this looks like it is not properly formatted. can you do `cmd+alt+L` to format your code?

**Comment by Vishwajith-Shettigar** [comment]
@adhiamboperes so what should I do now, here its showing  address Changes requested. 
Thank you.

**Review by adhiamboperes — APPROVED** [review]
Hi @Vishwajith-Shettigar, thanks for your PR. This LGTM!

**Comment by adhiamboperes** [comment]
I have left one nit comment - and for complete approval please update your PR description to include the following:

- [ ] An explanation of the changes that you have made
- [ ] Before(build using develop branch) and after screenshots(build app using your branch) of accessibility scanner showing that the warning is shown before your fix and gone after the fix. You can look at table formatting in markdown to organize your screenshots. Please see [this](https://github.com/oppia/oppia-android/pull/5104#issue-1819659150) for example.

File: app/src/main/AndroidManifest.xml (hunk 2 above)
Comment (Vishwajith-Shettigar) [reply app/src/main/AndroidManifest.xml:141]: can i just edit it here !? or need to make commit through local.

Comment (adhiamboperes) [reply app/src/main/AndroidManifest.xml]: It's best to make your commits locally and push.

**Comment by Vishwajith-Shettigar** [comment]
> 

I have made some changes PTAL, thank you.

**Review by adhiamboperes — APPROVED** [review]

**Comment by adhiamboperes** [comment]
> > 
> 
> I have made some changes PTAL, thank you.


Thanks. Do you know why the lightmode screenshot of the "after" fix is showing new suggestions?

**Comment by Vishwajith-Shettigar** [comment]
> > > 
> > 
> > 
> > I have made some changes PTAL, thank you.
> 
> Thanks. Do you know why the lightmode screenshot of the "after" fix is showing new suggestions?

no, I dont have any idea about that.

**Comment by adhiamboperes** [comment]
> > > > 
> > > 
> > > 
> > > I have made some changes PTAL, thank you.
> > 
> > 
> > Thanks. Do you know why the lightmode screenshot of the "after" fix is showing new suggestions?
> 
> no, I dont have any idea about that.

Well, could you please share the suggestions?

**Comment by Vishwajith-Shettigar** [comment]
> > > > > 
> > > > 
> > > > 
> > > > I have made some changes PTAL, thank you.
> > > 
> > > 
> > > Thanks. Do you know why the lightmode screenshot of the "after" fix is showing new suggestions?
> > 
> > 
> > no, I dont have any idea about that.
> 
> Well, could you please share the suggestions?

seems like its about background and foreground contrast ratio.

sug1

sug2

**Comment by Vishwajith-Shettigar** [comment]
I switched to develop branch,now it shows same with light mode (api 31)
beforelightedittext

**Review by seanlip — APPROVED** [review]
LGTM for 1 codeowner file

**Comment by adhiamboperes** [comment]
> I switched to develop branch,now it shows same with light mode (api 31) 

I checked this and the issue appears on the beta version as well. I don't think that should block this PR since the toolbar issue is fixed.

@Vishwajith-Shettigar, do you mind creating a bug report for the contrast issue?

@BenHenning, PTAL.

**Comment by Vishwajith-Shettigar** [comment]
> > I switched to develop branch,now it shows same with light mode (api 31)
> 
> I checked this and the issue appears on the beta version as well. I don't think that should block this PR since the toolbar issue is fixed.
> 
> @Vishwajith-Shettigar, do you mind creating a bug report for the contrast issue?
> 
> @BenHenning, PTAL.

@adhiamboperes Sure, thank you.

**Review by adhiamboperes — APPROVED** [review]

**Comment by adhiamboperes** [comment]
Merging this since a seperate issue #5142  has been created for the edit text contrasts.
