### PR TITLE
Fix #2192: Fixes delete profile in tablet

### LINKED ISSUE #2192: Profile Deletion in Tablet opens a different layout
**Describe the bug**
Profile Deletion Opens a list of profiles without toolbar

**To Reproduce**
1. Go to 'Administrator Controls'
2. Within 'Edit profiles' select a profile and delete the profile
3. Opens a list of profiles and onBack press shows a empty profile info as given below

**Expected behavior**
Go back to Edit Profiles section in Adminstrator Controls

**Screenshots**
Edit Profile | Selected Profile | Deleting profile | List of profiles without toolbar | Empty Profile Info 
--- | --- | --- | --- | ---
Screenshot_1606578255 | Screenshot_1606578255 | Screenshot_1606578259 | Screenshot_1606578264 | Screenshot_1606578268

**Device**
- Device/emulator being used - Nexus 7
- SDK version - 29

**Additional context**
 for more than one profile

### PR DESCRIPTION
**Pull request by FareesHussain**
## Explanation

Fixes #2192 
- Fixed with minimum changes possible.
 - Added tests which pass for both Espresso and Robolectric and fails without my implementation
 - Changed the intent from ProfileListActivity to AdministratorControlsActivity
 - Changing to intent to AdministratorControlsActivity take to ProfileListActivity with Administrator Control displayed

image

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by FareesHussain** [comment]
@anandwana001 please check

File: app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt [hunk 1]
```diff
@@ -313,7 +314,12 @@ class ProfileEditActivityTest {
         .inRoot(isDialog())
         .perform(click())
       testCoroutineDispatchers.runCurrent()
-      intended(hasComponent(ProfileListActivity::class.java.name))
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt:316]: is this test case failing before this implementation?

File: app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt [hunk 2]
```diff
@@ -313,7 +314,12 @@ class ProfileEditActivityTest {
...
+      val isTablet = context.resources.configuration.smallestScreenWidthDp >= 600
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt]: I don't think this will be a correct way to access whether its a tablet or not, we have few test cases where we do isTablet conditionally, you can find in some test classes.

**Review by anandwana001 — CHANGES_REQUESTED** [review]
@FareesHussain Did a pass on test file. PTAL

File: app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt (hunk 1 above)
Comment (FareesHussain) [reply app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt:316]: no it does'nt fail but we can't get the required screen

File: app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt (hunk 2 above)
Comment (FareesHussain) [reply app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt]: Ok I'll check

Comment (FareesHussain) [reply app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt]: Done, please check

File: app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt (hunk 1 above)
Comment (FareesHussain) [reply app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt:316]: Expected Screen after deleting profile | What we get 
--- | --- 
Screenshot_1606578255 | Screenshot_1606578255

File: app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt (hunk 2 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt]: ` val isTablet = context.resources.configuration.smallestScreenWidthDp >= 600` any use of it?

File: app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt (hunk 1 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt:316]: is it working correctly without RTL?

File: app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt (hunk 2 above)
Comment (FareesHussain) [reply app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt]: no i'll remove it

File: app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt (hunk 1 above)
Comment (FareesHussain) [reply app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt:316]: @anandwana001 I don't get it, I ran it without RTL

File: app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt [hunk 3]
```diff
@@ -313,7 +314,11 @@ class ProfileEditActivityTest {
         .inRoot(isDialog())
         .perform(click())
       testCoroutineDispatchers.runCurrent()
-      intended(hasComponent(ProfileListActivity::class.java.name))
+      if (context.resources.getBoolean(R.bool.isTablet)) {
+        intended(hasComponent(AdministratorControlsActivity::class.java.name))
+      } else {
+        intended(hasComponent(ProfileListActivity::class.java.name))
+      }
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt:321]: Update test name to `testProfileEdit_deleteProfile_checkReturnsToProfileListOnTabletOrAdminControlOnPhone`

File: app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt [hunk 4]
```diff
@@ -313,7 +314,11 @@ class ProfileEditActivityTest {
...
     }
   }
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt:323]: Also update the other test case `testProfileEdit_configChange_startWithUserProfile_deleteProfile_checkReturnsToProfileList`

File: app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt (hunk 1 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt:316]: ah, I checked, it's working correctly with RTL too.

**Review by anandwana001 — CHANGES_REQUESTED** [review]
Thanks @FareesHussain 
Few updates, PTAL

File: app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt (hunk 3 above)
Comment (FareesHussain) [reply app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt:321]: It might be a small mistake i'm changing it to `testProfileEdit_deleteProfile_checkReturnsToProfileListOnPhoneOrAdminControlOnTablet`

Comment (FareesHussain) [reply app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt:321]: Done

File: app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt (hunk 4 above)
Comment (FareesHussain) [reply app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt:323]: Done

Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt:323]: We can skip the startWithProfile to avoid ktlint disable.

Comment (FareesHussain) [reply app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt:323]: image

Comment (FareesHussain) [reply app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt:323]: it exceeds even after removing startWithUserProfile

Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt:323]: `testProfileEdit_configChange_deleteProfile_checkReturnsProfileListOnTabletAdminControlOnPhone` could you check this one!!

Comment (FareesHussain) [reply app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt:323]: @anandwana001 it's Close but still exceeds
image

Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt:323]: ah, could you suggest anything better, we are trying to avoid such ktlint disabling.

Comment (FareesHussain) [reply app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt:323]: testProfileEdit_landscape_deleteProfile_checkReturnsProfileListOnTabletAdminControlOnPhone this works

Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt:323]: sounds good.

Comment (FareesHussain) [reply app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt:323]: Done

**Review by anandwana001 — APPROVED** [review]
LGTM, Thanks @FareesHussain 
Defer to @rt4914 for further merge

**Comment by FareesHussain** [comment]
@rt4914 please check

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Comment by rt4914** [comment]
@FareesHussain Thanks a lot for finding this issues, filing this issue and solving this issue. Much appreciated.
