### PR TITLE
Fix #4632, #3779: Add support for checkpoint upgrading

### LINKED ISSUE #3779: Failed to retrieve oldest saved checkpoint details.
**Describe the bug**
Getting error log when opening exploration for the first time. 

**To Reproduce**
1. Go to lesson tab
2. Start any explortaion
3. Check logcat

**Expected behavior**
Investigate what the error is about and what is the suitable solution. 

**Device**
- Emulator being used - Pixel XL 
- SDK version 19 and 28

**Additional context**
```
09-13 10:10:48.272 E/ExplorationActivity: Failed to retrieve oldest saved checkpoint details.
    org.oppia.android.domain.exploration.lightweightcheckpointing.ExplorationCheckpointController$ExplorationCheckpointNotFoundException: No saved checkpoints in exploration_checkpoint_database for profileId 0.
        at org.oppia.android.domain.exploration.lightweightcheckpointing.ExplorationCheckpointController$retrieveOldestSavedExplorationCheckpointDetails$1.invokeSuspend(ExplorationCheckpointController.kt:207)
        at org.oppia.android.domain.exploration.lightweightcheckpointing.ExplorationCheckpointController$retrieveOldestSavedExplorationCheckpointDetails$1.invoke(ExplorationCheckpointController.kt)
        at org.oppia.android.util.data.AsyncResult$transformAsync$2.invokeSuspend(AsyncResult.kt:90)
        at org.oppia.android.util.data.AsyncResult$transformAsync$2.invoke(AsyncResult.kt)
        at org.oppia.android.util.data.AsyncResult.transformWithResultAsync(AsyncResult.kt:147)
        at org.oppia.android.util.data.AsyncResult.transformAsync(AsyncResult.kt:89)
        at org.oppia.android.util.data.DataProviders$Companion$transformAsync$1.retrieveData(DataProviders.kt:73)
        at org.oppia.android.util.data.DataProviders$Companion$transformAsync$1$retrieveData$1.invokeSuspend(DataProviders.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)
```

### LINKED ISSUE #4632: App learning progress reset when app moved from alpha to beta
**Describe the bug**
The learning progress - Story/Lesson completion - was lost when the app moved from alpha to beta channel.
I received a notification that I've been upgraded and then taken to the home/landing screen with profile selection options.
Once the profile is chosen it shows the Learning Home Screen.
Generally when I go to a topic/Lesson I have a "continue" option but it went back to the starter screen.

question: I would expect the app not to lose progress whenever there is an update to the app.

**To Reproduce**
Can't reproduce the behavior anymore since it's a one-time thing.
**Expected behavior**
I would expect the app not to lose progress whenever there is an update to the app.

**Demonstration**
N.A.

**Environment**
- Device/emulator being used: Pixel 5
- Android or SDK version (e.g. Android 5 or SDK 21): Android 13
- App version (you can get this through system app settings or via the admin controls menu in-app): 0.9-beta-3f935261e0

**Additional context**

### PR DESCRIPTION
**Pull request by BenHenning**
## Explanation
Fixes #4632
Fixes #3779

Adds support for upgrading checkpoints to support the latest versions of explorations if the checkpoint was saved for an older version, in cases where it's very likely reasonable to upgrade the checkpoints. The methodology applied is to simulate "replaying" the full lesson using the past answers that were submitted in the checkpointing, and verifying that the same outcome would more or less be achieved by ensuring:
- The content IDs for received feedback haven't changed (but the HTML might, e.g. for typos).
- The destination of a state hasn't changed.
- The pending & all completed states still exist.

The cases that currently can't be handled (but may be reasonable to in the future):
- State renaming (these are treated as failures).
- Reconstituting a compatible hint/solution state (the state is just reset for now so the user can re-trigger the hints if they get stuck after returning to the lesson).

As part of testing this:
- A bunch of new assets were introduced to directly demonstrate upgrading flows that lead to both compatibilities and incompatibilities (these were generated).
- A fake ``ExplorationRetriever`` needed to be introduced in order to support proxying exploration loading (so that newer versions can be force-loaded). This required splitting the existing ExplorationRetriever into an interface & implementation.
- ``ExplorationStorageModule`` has been moved one package up for better organization (which led to a bunch of other files being changed).
- Test-only checkpoint database storage sizes have been 150 bytes in all related tests, so this has been made as the test-specific constant in the new ExplorationStorageTestModule.

Separately, ExplorationRetriever was updated to mostly force background thread interaction by using a suspend method for actual exploration loading (which led to some small test changes).

#3779 was also fixed (since I was changing this code, anyway) by returning a default details object instead of failing whenever a checkpoint can't be found for a given exploration. Note that no test was added for this solution since doing so would be a bit painful (as it requires loading and verifying an exploration at the activity level where a bunch of the lower-level tools from StateFragment{Local}Test aren't available), and the failure case here is something that will definitely be caught by e2e tests so the risk is low for a serious regression.

## Essential Checklist
- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only
While this PR does affect UI flows for checkpoints, I'm opting to not include a walkthrough since it's difficult and time consuming to simulate the local upgrade flow. We'll be testing this specially during manual QA testing for this release to ensure it works as expected.

Similarly, app module tests haven't changed in a major way so I'm skipping showing Espresso results here. The Robolectric tests results ought to be a sufficiently good proxy for correctness.

### CODE REVIEW

**Comment by BenHenning** [comment]
@seanlip PTAL. As an FYI I have also self-reviewed the whole PR.

File: domain/src/main/java/org/oppia/android/domain/exploration/lightweightcheckpointing/ExplorationCheckpointController.kt [hunk 1]
```diff
@@ -299,6 +297,125 @@ class ExplorationCheckpointController @Inject constructor(
     return cacheStore
   }
 
+  /**
+   * Attempts to "reply" the specified checkpoint for the corresponding specified exploration,
```
Comment (seanlip) [inline domain/src/main/java/org/oppia/android/domain/exploration/lightweightcheckpointing/ExplorationCheckpointController.kt]: reply --> replay ?

**Review by seanlip — APPROVED** [review]
LGTM, but with the disclaimer that I've only been able to take a cursory look and didn't see anything obviously wrong (but I can't certify correctness). Thanks!

File: domain/src/main/java/org/oppia/android/domain/exploration/lightweightcheckpointing/ExplorationCheckpointController.kt (hunk 1 above)
Comment (BenHenning) [reply domain/src/main/java/org/oppia/android/domain/exploration/lightweightcheckpointing/ExplorationCheckpointController.kt]: Ah, nice catch! Fixed.

(Also marking this as resolved since you've approved the PR).

**Comment by BenHenning** [comment]
Merging this without @rt4914's approval since it's release blocking.
