### PR TITLE
Fix #5697: concept card close button

### LINKED ISSUE #5697: [BUG]: The close button is not working for concept cards
### Describe the bug

In "What is Addition" and "Basics of Addition" Chapters, when I open the concept card showing in the first page, I cannot close it using the "X" button. 

### Steps To Reproduce

1. Go to Addition and Subtraction Lesson
2. Go to what is Addition Chapter 
3. Or go to Basics of Addition Chapter 
4. Open the concept card in the first page
5. Try to close it using the "X" button
6. See the bug

### Expected Behavior

It is expected to close the concept card using the close button "X" 

### Screenshots/Videos

https://github.com/user-attachments/assets/5a7fa887-fd90-4562-9db7-a522f860bf46

### What device/emulator are you using?

OPPPO A79 %G

### Which Android version is your device/emulator running?

Android 14

### Which version of the Oppia Android app are you using?

0.14-beta-17f2ef3044

### Additional Context

I'm testing in Portuguese Language

### LINKED ISSUE #5787: [BUG]: The Learner is not able to close Concept Card
### Describe the bug

"As a learner I should be able to close Concept Card using close button” The learner is able to close Concept Card using close button, but is not able to close concept card, because there is close button not working.

### Steps To Reproduce

1. Go to Place Values
2. Go to What are the Place Values?
3. Go to Question Numer 6 
4. After the wrong answer have a concept card
5. Open concept card
6. See there is not working close button on Concept Card

### Expected Behavior

"As a learner I should be able to close Concept Card using close button”  it is expected to be able to close the Concept Card.

### Screenshots/Videos

Image

### What device/emulator are you using?

_No response_

### Which Android version is your device/emulator running?

_No response_

### Which version of the Oppia Android app are you using?

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by subhajitxyz**
## Explanation
Fixes #5787, #5697
This PR includes fixing close button functionality of concept card.

### Root Cause & Fix
This issue is a regression stemming from an incorrect fragment manager being used when calling dismissAll() in ConceptCardFragment.

In PR #5509 the dismiss functionality was implemented specifically for the case when the concept card is shown from **HintAndSolutionFragment**, where the correct fragment manager was passed. However, the dismiss functionality for concept cards shown directly from **StateFragment** was removed, leading to a missing dismissal behavior in that scenario.

As a result, when a user closed the concept card that was launched by **StateFragment**, the dismiss operation failed because there was no proper handling or fragment manager provided for that case.

### Fixes

```
override fun dismissConceptCard() {
    getHintsAndSolution()?.dismissConceptCard()
        ?: explorationActivityPresenter.dismissConceptCard()
}
```
This fix first tries to delegate the dismissal to **HintAndSolutionFragment**, ensuring the correct fragment manager is used. If **HintAndSolutionFragment** is not present, it falls back to the **ExplorationActivity's** presenter, which handles the case for concept cards shown by **StateFragment**. This ensures that **dismissAll**() is always called with the correct fragment manager, resolving the issue for both cases.

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [ ] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [ ] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

Closing concept card on StateFragment

https://github.com/user-attachments/assets/082b3d56-66c5-4f74-8c6e-e3e8af9fd462

Closing concept card on HintsAndSolutionDialogFragment

https://github.com/user-attachments/assets/70c3210b-0b0a-437a-a886-ec838f42aa4f

### CODE REVIEW

**Comment by subhajitxyz** [comment]
@adhiamboperes , PTAL.

**Review by adhiamboperes — COMMENTED** [review]
Thanks @subhajitxyz! This looks great.

Since this is a regression(we have tried to solve this issue twice before), could you please do a comprehensive write up in the PR description on the root of the issue, and why this PR fixes it?

**Comment by subhajitxyz** [comment]
@adhiamboperes , I have updated PR description.

**Comment by subhajitxyz** [comment]
@adhiamboperes , PTAL.

File: app/src/main/java/org/oppia/android/app/player/state/StateFragment.kt [hunk 1]
```diff
@@ -165,6 +165,12 @@ class StateFragment :
     stateFragmentPresenter.viewSolution()
   }
 
+  /**
+   * Delegates the removal of all [ConceptCardFragment] instances
+   * to the [stateFragmentPresenter].
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/player/state/StateFragment.kt]:
```suggestion
   * to the [StateFragmentPresenter].
```

File: app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt [hunk 2]
```diff
@@ -1869,7 +1869,7 @@ class ExplorationActivityTest {
 
   @Test
   @RunOn(TestPlatform.ROBOLECTRIC) // TODO(#3858): Enable for Espresso.
-  fun testExpActivity_openConceptCard_selectNavigationUp_conceptCardCloses() {
+  fun testExpActivity_openConceptCard_onHintsAndSolutionDialog_selectNavigationUp_conceptCardCloses() { // ktlint-disable max-line-length
```
Comment (adhiamboperes) [inline app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt]:
```suggestion
  fun testActivity_openConceptCard_onHintsAndSolutionDialog_selectNavigationUp_conceptCardCloses() {
```

File: app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt [hunk 3]
```diff
@@ -1905,6 +1905,45 @@ class ExplorationActivityTest {
     explorationDataController.stopPlayingExploration(isCompletion = false)
   }
 
+  @Test
+  @RunOn(TestPlatform.ROBOLECTRIC)
+  fun testExpActivity_openConceptCard_onStateFragment_selectNavigationUp_conceptCardCloses() {
```
Comment (adhiamboperes) [inline app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt]:
```suggestion
  fun testExpActivity_openConceptCard_fromStateFragment_selectNavigationUp_conceptCardCloses() {
```

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @subhajitxyz! Could you please check the following:'
1. Similar tests have been added to the StateFragmentTest or LocalTest
2. There is test for closing the concept card that is being opened from another concept card in the HintsDialog.

**Comment by subhajitxyz** [comment]
> Thanks @subhajitxyz! Could you please check the following:'
> 
> 1. Similar tests have been added to the StateFragmentTest or LocalTest
> 2. There is test for closing the concept card that is being opened from another concept card in the HintsDialog.


1. Hi @adhiamboperes , I have checked StateFragmentTest an StateFragmentLocalTest. There is tests only for opening Concecpt card. There is no test for closing concept card because StateFragmentTestAcitivity does not contain functionality for closing concept card.

Should i introduce functionality for closing concept card on StateFragmentTestActivity?

2. Yes , we can add a test for closing the concept card that is being opened from another concept card in the HintsDialog.

**Comment by adhiamboperes** [comment]
> 1. Hi @adhiamboperes , I have checked StateFragmentTest an StateFragmentLocalTest. There is tests only for opening Concecpt card. There is no test for closing concept card because StateFragmentTestAcitivity does not contain functionality for closing concept card.

> Should i introduce functionality for closing concept card on StateFragmentTestActivity?

I checked `StateFragmentTestAcitivity` but I didn't see the functionality you are referring to. Could you provide a link to the github code for clarity? 

> 2. Yes , we can add a test for closing the concept card that is being opened from another concept card in the HintsDialog.

You can go ahead and add the tests, for both your question (1) and (2)

File: app/src/main/java/org/oppia/android/app/player/state/StateFragment.kt (hunk 1 above)
Comment (subhajitxyz) [reply app/src/main/java/org/oppia/android/app/player/state/StateFragment.kt]: Done

File: app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt (hunk 2 above)
Comment (subhajitxyz) [reply app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt]: Done

File: app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt (hunk 3 above)
Comment (subhajitxyz) [reply app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt]: Done

**Comment by subhajitxyz** [comment]
PTAL @adhiamboperes .

**Review by adhiamboperes — APPROVED** [review]
Thanks @subhajitxyz! This LGTM!
