### PR TITLE
Fixes #3906: Incorrect output for rich text in hints and solution

### LINKED ISSUE #3906: [A11Y] Incorrect output for rich-text in Hints and Solution
Incorrect output for rich-text in Hints and Solution.

### PR DESCRIPTION
**Pull request by vrajdesai78**
## Explanation
Fixes #3906: Fixed the overall accessibility of Hints and Solution as follows:
- Parse HTML to normal string for content description
- Improved flow of screen reader by removing repetitive content description.
- Changed content description of expand_list_icon and also improve the flow by making expand_list_icon clickable and not clickable based on talkback reader. 

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

### Video for Hints

https://user-images.githubusercontent.com/43074241/198126083-88b1ea29-3726-43e5-895e-de64166a6515.mp4

### Video for Solution

https://user-images.githubusercontent.com/43074241/198126121-59b56e5c-4003-4047-a6c9-4595430f3a8b.mp4

### CODE REVIEW

**Comment by vrajdesai78** [comment]
@BenHenning @rt4914 CI checks are failing due to some flaky tests. Can you re-run it.

File: app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt [hunk 1]
```diff
@@ -1617,6 +1617,48 @@ class ExplorationActivityTest {
     explorationDataController.stopPlayingExploration(isCompletion = false)
   }
 
+  @Test
+  @RunOn(TestPlatform.ROBOLECTRIC) // TODO(#3858): Enable for Espresso.
+  fun testExpActivity_showHintAndSolution_hasCorrectContentDescription() {
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt]: Just to confirm, does this fail without the fix?

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @vrajdesai78. Just had one follow-up comment--PTAL.

File: app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt (hunk 1 above)
Comment (vrajdesai78) [reply app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt]: Yes @BenHenning, test case is failing without parsing HTML. 
image

**Comment by vrajdesai78** [comment]
> Thanks @vrajdesai78. Just had one follow-up comment--PTAL.

@BenHenning replied to your comment, also can you please re-run CI checks. Thanks

File: app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt (hunk 1 above)
Comment (BenHenning) [reply app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt]: Thanks for checking!

**Review by BenHenning — APPROVED** [review]
Thanks @vrajdesai78! This LGTM. Just waiting on CI.

**Comment by BenHenning** [comment]
CI is looking good, so I have no other concerns here. I think you just need @rt4914's approval at this point.

**Review by rt4914 — CHANGES_REQUESTED** [review]
Currently the hint-content and "Hint 1", `show/hide` all these are getting read-at-once.

Instead the hint-content, ie., `Remember ....` should be entirely separate from other things like `Hint 1` and `show/hide`

**Comment by vrajdesai78** [comment]
> Currently the hint-content and "Hint 1", `show/hide` all these are getting read-at-once.
> 
> Instead the hint-content, ie., `Remember ....` should be entirely separate from other things like `Hint 1` and `show/hide`

Thanks @rt4914, I have updated code according to your suggestion. Also, updated video in the description.

File: app/src/main/res/layout/hints_summary.xml [hunk 2]
```diff
@@ -94,7 +95,7 @@
             android:layout_marginTop="8dp"
             android:layout_marginEnd="8dp"
             android:layout_marginBottom="4dp"
-            android:contentDescription="@{viewModel.computeHintListDropDownIconContentDescription()}"
```
Comment (rt4914) [inline app/src/main/res/layout/hints_summary.xml:97]: One more suggestion, 

use `ImageButton` instead of `ImageView`, so that the talkback will correctly read the output for button instead of `Image`

Also, why was the content description should be optimised, i.e.,
- if list is expanded, 'Hide hint'
- if list is not-expanded, 'Show hint', 

**Also, note, I think similar changes needs to be done for `Solution-summary` too, please check that too..**

**Review by rt4914 — CHANGES_REQUESTED** [review]
@vrajdesai78 Suggested some more changes based on the current output.

File: app/src/main/res/layout/hints_summary.xml (hunk 2 above)
Comment (vrajdesai78) [reply app/src/main/res/layout/hints_summary.xml:97]: I have made required changes for Solution-summary. Updated changes and video in PR's description. Thanks

**Review by rt4914 — APPROVED** [review]
LGTM, Thanks.
