### PR TITLE
Fix part of #4391: Fix failing build on m1 macs

### LINKED ISSUE #4391: Bazel 4.0 not building project correctly on macOs Monterrey version 12.4
**Describe the bug**
Building project with bazel using macOs Monterrey version 12.4 on terminal fails see logs below for context

` Generating JavaLite proto_library //model/src/main/proto:event_logger_proto failed: (Segmentation fault): protoc failed: error executing command bazel-out/darwin-opt-exec-2B5CBBC6/bin/external/com_google_protobuf/protoc '--proto_path=bazel-out/android-armeabi-v7a-fastbuild/bin/model/src/main/proto/_virtual_imports/math_proto' ... (remaining 22 argument(s) skipped)
`

**To Reproduce**
1. Setup Oppia Android project on macOs Monterrey version 12.4 as per the docs
2. Run command `bazel build //:oppia ` on terminal
3. See error

**Expected behavior**
I expect Bazel to build project successfully and be able to generate required artifacts.

**Demonstration**
Screenshot 2022-06-10 at 11 17 46

**Environment**
- macOs Monterrey version 12.4
- Android or SDK version 30
- App version 1.0
- Bazel Version 4.0

**Additional context**
Issue with similar specs on Bazel repository
https://github.com/bazelbuild/bazel/issues/14469

### PR DESCRIPTION
**Pull request by kkmurerwa**
Fix part of #4391 : Fix failing build on M1 Macs
## Explanation

Some M1 Macs fail to build the Oppia app because of unused imports in some of the proto files in the project. This PR attempts to fix this issue by removing unused imports in proto files. Files affected by this fix are;
- profile.proto
- deprecation.proto

This is a temporary fix and more investigation will need to be done to properly understand why this behavior is erratic and why it only happens in some instances and not in others. More checks are also needed to ensure that proto files only have imports that are used in the proto file before they are merged.

Besides build fixes, this PR also;
- Includes a fix for the `buildifier_download.sh` which previously did not work for MacOS users.
- Introduces a `static_checks.sh` file to allow contributors to run all static checks locally before pushing the code to Git.
- Adds a wiki entry in the Static-Analysis-Checks wiki. The entry contains instructions on how to run static checks locally with the static_checks.sh file.

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

### CODE REVIEW

File: scripts/static_checks.sh
Comment (adhiamboperes) [inline scripts/static_checks.sh:1]: This is a really nice addition. Thanks!

**Review by adhiamboperes — APPROVED** [review]
Thanks @kkmurerwa! This PR LGTM. Just one thing: could you change both the title and description to "Fix Part of"? Otherwise the issue will be closed, yet it is not fully resolved.

**Comment by adhiamboperes** [comment]
One more thing, please refer to https://github.com/oppia/oppia-android/pull/5108#issuecomment-1655063018 on how to fix your failing TODO check.

File: scripts/static_checks.sh [hunk 1]
```diff
@@ -0,0 +1,111 @@
...
+
+# Run Kotlin lint check
+bash scripts/ktlint_lint_check.sh
+echo ""
+
+# Run protobuf lint checks
+bash scripts/buf_lint_check.sh
+echo ""
+
+# Download Buildifier in oppia-andoid-tools folder (pre-requisite for buildifier checks)
```
Comment (seanlip) [inline scripts/static_checks.sh]: andoid --> android

File: scripts/static_checks.sh [hunk 2]
```diff
@@ -0,0 +1,111 @@
+#!/bin/bash
```
Comment (seanlip) [inline scripts/static_checks.sh:1]: Thanks @kkmurerwa! Just wondering, how long does this script take to run (typically)? Might be worth mentioning that in the wiki so that devs know what to expect.

**Review by seanlip — CHANGES_REQUESTED** [review]

File: scripts/static_checks.sh
Comment (kkmurerwa) [reply scripts/static_checks.sh:1]: I have fixed the issue number reference and title. And thank you.

File: scripts/static_checks.sh (hunk 2 above)
Comment (kkmurerwa) [reply scripts/static_checks.sh:1]: I tried to be a bit scientific about this. I made three runs without running bazel clean and three while running bazel clean. Without bazel clean, the average runtime was 1 and a half minutes. Running bazel clean each time, the average time was 5 and a half minutes. Bearing in mind I'm using a quite powerful M1 chip, I would say it should be around 6-10 minutes for a clean run and around 2-5 minutes for a subsequent run. I will update the Wiki with these estimates.

File: scripts/static_checks.sh (hunk 1 above)
Comment (kkmurerwa) [reply scripts/static_checks.sh]: Thanks for spotting this.

**Comment by kkmurerwa** [comment]
Hi @seanlip. This is PR ready for another pass.

**Review by seanlip — APPROVED** [review]
Looks great. Thanks @kkmurerwa!

**Review by adhiamboperes — APPROVED** [review]
Thanks @kkmurerwa, this LGTM
