### PR TITLE
Fix #5032 Images in Arabic (RTL) lessons are right-aligned rather than center-aligned.

### LINKED ISSUE #5032: [BUG]: Images in Arabic (RTL) lessons are right-aligned rather than center-aligned.
**Describe the bug**
Images that display in the Arabic (right-to-left) versions of the lessons are right-aligned rather than center-aligned. This makes the experience for Arabic learners a bit odd and it would be good to fix it.

**To Reproduce**
1. Download the 0.11-beta release.
2. Set the language of the app to Arabic.
3. Play the first 2 cards of Fractions 1. The second card has an image of a bakery that is right-aligned. 

**Expected behavior**
The image of the bakery should be center-aligned.

**Demonstration**
| Arabic cards  | English cards  |
|---|---|
| Screenshot_20230608-191504  |   Screenshot_20230608-191826  | 

**Environment**
- Device/emulator being used: Moto device
- Android or SDK version (e.g. Android 5 or SDK 21): Android 8
- App version (you can get this through system app settings or via the admin controls menu in-app): 0.11-beta-8c81c98d8b

### PR DESCRIPTION
**Pull request by Vishwajith-Shettigar**
## Explanation
Fixes  #5032,  To make the image center-aligned, we are adding styling to the HTML content image and removing  the left margin by setting drawableLeft bound to 0 in RTL. 

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

### Before
LTR Potrait

beforeLTRpotrait

LTR Landscape

LTRlandscape

RTL Potrait

beforeRTLpotrait

RTL Landscape 

RTLlandscape

### After

RTL Potrait

Potrait_after

RTL Landscape

landscapeafter

LTR Potrait

LTRpotraitafter

LTR Landscape

LTRLandscape

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- For PRs introducing new UI elements or color changes, both light and dark mode screenshots must be included
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### CODE REVIEW

**Comment by Vishwajith-Shettigar** [comment]
@adhiamboperes, PTAL

File: utility/src/main/java/org/oppia/android/util/parser/image/UrlImageParser.kt [hunk 1]
```diff
@@ -304,11 +305,18 @@ class UrlImageParser private constructor(
             drawableWidth *= multipleFactor
           }
         }
-        val drawableLeft = if (imageCenterAlign) {
+
+        fun isRTLMode(): Boolean {
+          return ViewCompat.getLayoutDirection(htmlContentTextView) == ViewCompat
+            .LAYOUT_DIRECTION_RTL
+        }
```
Comment (adhiamboperes) [inline utility/src/main/java/org/oppia/android/util/parser/image/UrlImageParser.kt]: Could you move this function outside of computeBounds(), but  keep it still within the BlockImageTarget class? The function could also be private to the class.

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @Vishwajith-Shettigar! This is a really interesting solution. 

Please add a PR description explaining your solution.

File: utility/src/main/java/org/oppia/android/util/parser/image/UrlImageParser.kt (hunk 1 above)
Comment (Vishwajith-Shettigar) [reply utility/src/main/java/org/oppia/android/util/parser/image/UrlImageParser.kt]: I made changes, PTAL.
Thank you

**Review by adhiamboperes — APPROVED** [review]
Thanks @Vishwajith-Shettigar! This LGTM.
