### PR TITLE
Fix #1104: Offline Exception Logging

### LINKED ISSUE #1104: Offline Exception Logging [GSoC'20][Milestone 3]
- Addition of proto definition which will be useful for storing relevant Crashlytics data when the user is offline and retrieving the same for reporting to Firebase when the user is back online.
- Using the Proto definition and saving crash reports to the cache store in absence of network connectivity.

### PR DESCRIPTION
**Pull request by Sarthak2601**
## Explanation

Fixes #1104 
Fixes part of #1105 
- Adds the proto structure for exception logs 
- Adds exception controller for storing/uploading of exception logs on the basis of network connectivity. 

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

File: domain/src/main/java/org/oppia/domain/oppialogger/crashlytics/ExceptionsController.kt [hunk 1]
```diff
@@ -0,0 +1,174 @@
...
+  private val networkConnectionUtil: NetworkConnectionUtil,
+  private val oppiaClock: OppiaClock,
+  @ExceptionLogStorageCacheSize private val exceptionLogStorageCacheSize: Int
+) {
+  private val exceptionLogStore =
+    cacheStoreFactory.create("exception_logs", OppiaExceptionLogs.getDefaultInstance())
+
+  lateinit var exceptionCause: Throwable
+
+  fun logException(exception: Exception, timestamp: Long) {
```
Comment (vinitamurthi) [inline domain/src/main/java/org/oppia/domain/oppialogger/crashlytics/ExceptionsController.kt]: Add a KDoc for this function

File: domain/src/main/java/org/oppia/domain/oppialogger/crashlytics/ExceptionsController.kt [hunk 2]
```diff
@@ -0,0 +1,174 @@
...
+  private fun uploadOrCacheExceptionLog(exception: Exception, timestamp: Long) {
+    when (networkConnectionUtil.getCurrentConnectionStatus()) {
+      NetworkConnectionUtil.ConnectionStatus.NONE ->
+        cacheExceptionLog(exceptionToExceptionLog(exception, timestamp))
+      else -> exceptionLogger.logException(exception)
+    }
+  }
+
+  /** Returns an [ExceptionLog] from an [exception]. */
+  private fun exceptionToExceptionLog(exception: Exception, timestamp: Long): ExceptionLog {
```
Comment (vinitamurthi) [inline domain/src/main/java/org/oppia/domain/oppialogger/crashlytics/ExceptionsController.kt]: Let's rename this a bit. Maybe parseExceptionToExceptionLog or something?

File: domain/src/main/java/org/oppia/domain/oppialogger/crashlytics/ExceptionsController.kt [hunk 3]
```diff
@@ -0,0 +1,174 @@
...
+    val causeStackTraceSize = exception.cause?.stackTrace?.size
+    if (causeStackTraceSize != null) {
+      buildStackTraceElement(causeStackTraceSize, exceptionLogCauseBuilder, exception)
+    }
+    exceptionLogBuilder.cause = exceptionLogCauseBuilder.build()
+    return exceptionLogBuilder.build()
+  }
+
+  /** Returns an [Exception] from an [exceptionLog]. */
+  private fun exceptionLogToException(exceptionLog: ExceptionLog): Exception {
```
Comment (vinitamurthi) [inline domain/src/main/java/org/oppia/domain/oppialogger/crashlytics/ExceptionsController.kt]: As discussed, do we need this right now? If not, let's remove it.

File: domain/src/main/java/org/oppia/domain/oppialogger/crashlytics/ExceptionsController.kt [hunk 4]
```diff
@@ -0,0 +1,174 @@
...
+            .addExceptionLog(exceptionLog)
+            .build()
+        } else {
+          // TODO (#1433): Refactoring for logging exceptions to both console and exception loggers.
+          val exception =
+            NullPointerException(
+              "Least Recent Exception index absent -- ExceptionLogCacheStoreSize is 0"
+            )
+          consoleLogger.e("Exceptions Controller", exception.toString())
+          logException(exception, oppiaClock.getCurrentCalendar().timeInMillis)
```
Comment (vinitamurthi) [inline domain/src/main/java/org/oppia/domain/oppialogger/crashlytics/ExceptionsController.kt]: I'm wondering if it makes sense to log an exception here if the problem lies in logging exceptions

File: domain/src/main/java/org/oppia/domain/oppialogger/crashlytics/ExceptionsController.kt [hunk 5]
```diff
@@ -0,0 +1,174 @@
+package org.oppia.domain.oppialogger.crashlytics
+
```
Comment (vinitamurthi) [inline domain/src/main/java/org/oppia/domain/oppialogger/crashlytics/ExceptionsController.kt]: Please add tests for this file

**Review by vinitamurthi — CHANGES_REQUESTED** [review]
One more structure question. I wonder if it makes more sense to keep the exception serialization and deserialization (i.e. exceptionToExceptionLog() and exceptionLogtoException) in a separate class considering that multiple codepaths will be deserializing these exceptions @BenHenning thoughts?

File: domain/src/main/java/org/oppia/domain/oppialogger/crashlytics/ExceptionsController.kt [hunk 6]
```diff
@@ -0,0 +1,174 @@
...
+import org.oppia.domain.oppialogger.ExceptionLogStorageCacheSize
+import org.oppia.util.data.AsyncResult
+import org.oppia.util.data.DataProviders
+import org.oppia.util.logging.ConsoleLogger
+import org.oppia.util.logging.ExceptionLogger
+import org.oppia.util.networking.NetworkConnectionUtil
+import org.oppia.util.system.OppiaClock
+import javax.inject.Inject
+
+class ExceptionsController @Inject constructor(
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/domain/oppialogger/crashlytics/ExceptionsController.kt]: Please ensure all new classes & public API methods have KDocs.

File: domain/src/main/java/org/oppia/domain/oppialogger/crashlytics/ExceptionsController.kt (hunk 1 above)
Comment (BenHenning) [inline domain/src/main/java/org/oppia/domain/oppialogger/crashlytics/ExceptionsController.kt]: Why not always log this from within our ``Logger``class? I don't think callsites should be deciding whether to care about caching/uploading exception logs. Instead, callsites just care about noting to developers that something went wrong, and after that it's up to the logging system to decide what to do with the exception.

File: model/src/main/proto/oppia_logger.proto [hunk 7]
```diff
@@ -120,7 +120,47 @@ message EventLog {
   }
 }
 
-// Structure for a container that contains an event log report.
+// Structure for an exception log.
+message ExceptionLog {
+  // The timestamp of the exception.
+  int64 timestamp = 1;
```
Comment (BenHenning) [inline model/src/main/proto/oppia_logger.proto]: Is this timestamp's unit millis? Prefer being specific in the name.

File: model/src/main/proto/oppia_logger.proto [hunk 8]
```diff
@@ -120,7 +120,47 @@ message EventLog {
...
+  // The stacktrace of the exception explaining what went wrong
+  repeated StackTraceElement stacktrace = 2;
```
Comment (BenHenning) [inline model/src/main/proto/oppia_logger.proto]: Prefer: ``stack_trace_element`` to be consistent, and produce slightly more readable generated code (e.g. we'll now have ``addStackTraceElement`` rather than ``addStacktrace``).

File: model/src/main/proto/oppia_logger.proto [hunk 9]
```diff
@@ -120,7 +120,47 @@ message EventLog {
...
+  // The message explaining what failed at the site the exception was thrown.
+  string message = 3;
+  // The cause of the exception which in itself is a throwable.
+  ExceptionLog cause = 4;
+  // The type of exception indicating how that exception affected the application.
+  ExceptionType exception_type = 5;
+
+  enum ExceptionType {
+    // The undefined exception type.
+    CRASH_TYPE_UNSPECIFIED = 0;
```
Comment (BenHenning) [inline model/src/main/proto/oppia_logger.proto]: Should this be ``EXCEPTION_TYPE_UNSPECIFIED`` per Buf?

File: domain/src/main/java/org/oppia/domain/oppialogger/crashlytics/ExceptionsController.kt (hunk 6 above)
Comment (BenHenning) [inline domain/src/main/java/org/oppia/domain/oppialogger/crashlytics/ExceptionsController.kt]: Please add tests for this class.

File: domain/src/main/java/org/oppia/domain/oppialogger/crashlytics/ExceptionsController.kt (hunk 2 above)
Comment (BenHenning) [reply domain/src/main/java/org/oppia/domain/oppialogger/crashlytics/ExceptionsController.kt]: It seems to be a conversion function, perhaps: ``convertExceptionToExceptionLog``, ``createExceptionLog``, or ``createLogFromException``.

File: domain/src/main/java/org/oppia/domain/oppialogger/crashlytics/ExceptionsController.kt [hunk 10]
```diff
@@ -0,0 +1,174 @@
...
+      NetworkConnectionUtil.ConnectionStatus.NONE ->
+        cacheExceptionLog(exceptionToExceptionLog(exception, timestamp))
+      else -> exceptionLogger.logException(exception)
+    }
+  }
+
+  /** Returns an [ExceptionLog] from an [exception]. */
+  private fun exceptionToExceptionLog(exception: Exception, timestamp: Long): ExceptionLog {
+    val exceptionLogBuilder = ExceptionLog.newBuilder()
+    val exceptionLogCauseBuilder = ExceptionLog.newBuilder()
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/domain/oppialogger/crashlytics/ExceptionsController.kt]: Why not recurse a call to the same function, instead? E.g.

```kotlin
exception.cause?.let {
  exceptionLogBuilder.cause = exceptionToExceptionLog(it, timestamp)
}
```

It seems like that would reduce a lot of the construction that's needed here.

File: domain/src/main/java/org/oppia/domain/oppialogger/crashlytics/ExceptionsController.kt (hunk 4 above)
Comment (BenHenning) [reply domain/src/main/java/org/oppia/domain/oppialogger/crashlytics/ExceptionsController.kt]: This might cause a crash/fail loop, so we probably shouldn't try this and instead fail in the console logger.

File: domain/src/main/java/org/oppia/domain/oppialogger/crashlytics/ExceptionsController.kt [hunk 11]
```diff
@@ -0,0 +1,174 @@
...
+      Throwable()
+    }
+    exceptionCause.stackTrace = createErrorStackTrace(exceptionLog.cause)
+    val exception = Exception(exceptionMessage, exceptionCause)
+    exception.stackTrace = createErrorStackTrace(exceptionLog)
+    return exception
+  }
+
+  /** Builds the [ExceptionLog.StackTraceElement] for an [exception] with relevant data and adds it to the [exceptionLogBuilder]. */
+  private fun buildStackTraceElement(
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/domain/oppialogger/crashlytics/ExceptionsController.kt]: You might be able to simplify the stack trace construction slightly:

```kotlin
exceptionLogBuilder.addAllStackTraceElement(exception.stackTrace.map(this::convertStackTraceElementToLog))

...

fun convertStackTraceElementToLog(stackTraceElement: StackTraceElement): ExceptionLog.StackTraceElement {
  return ExceptionLog.StackTraceElement.newBuilder()
      .setFileName(stackTraceElement.fileName)
      .setMethodName(stackTraceElement.methodName)
      .setLineNumber(stackTraceElement.lineNumber)
      .setDeclaringClass(stackTraceElement.className)
      .build()
}
```

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @Sarthak2601--did a first pass.

File: domain/src/main/java/org/oppia/domain/oppialogger/crashlytics/ExceptionsController.kt (hunk 1 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/crashlytics/ExceptionsController.kt]: I think this will be done during restructuring as the `oppiaLogger` will become the call site for the developers. Please correct me if I am wrong @vinitamurthi.

File: domain/src/main/java/org/oppia/domain/oppialogger/crashlytics/ExceptionsController.kt (hunk 11 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/crashlytics/ExceptionsController.kt]: Yes, it helped. Thanks :)

File: domain/src/main/java/org/oppia/domain/oppialogger/crashlytics/ExceptionsController.kt (hunk 10 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/crashlytics/ExceptionsController.kt]: Yep, done.

File: domain/src/main/java/org/oppia/domain/oppialogger/crashlytics/ExceptionsController.kt (hunk 6 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/crashlytics/ExceptionsController.kt]: Added, PTAL.

File: model/src/main/proto/oppia_logger.proto (hunk 9 above)
Comment (Sarthak2601) [reply model/src/main/proto/oppia_logger.proto]: Not sure. @vinitamurthi thoughts ?

File: model/src/main/proto/oppia_logger.proto (hunk 8 above)
Comment (Sarthak2601) [reply model/src/main/proto/oppia_logger.proto]: Yes, done.

File: model/src/main/proto/oppia_logger.proto (hunk 7 above)
Comment (Sarthak2601) [reply model/src/main/proto/oppia_logger.proto]: Done.

File: domain/src/main/java/org/oppia/domain/oppialogger/crashlytics/ExceptionsController.kt (hunk 6 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/crashlytics/ExceptionsController.kt]: Done.

File: domain/src/main/java/org/oppia/domain/oppialogger/crashlytics/ExceptionsController.kt (hunk 5 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/crashlytics/ExceptionsController.kt]: Done.

File: domain/src/main/java/org/oppia/domain/oppialogger/crashlytics/ExceptionsController.kt (hunk 4 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/crashlytics/ExceptionsController.kt]: Removed.

File: domain/src/main/java/org/oppia/domain/oppialogger/crashlytics/ExceptionsController.kt (hunk 3 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/crashlytics/ExceptionsController.kt]: Removed.

File: domain/src/main/java/org/oppia/domain/oppialogger/crashlytics/ExceptionsController.kt (hunk 2 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/crashlytics/ExceptionsController.kt]: Changed to `convertExceptionToExceptionLog`.

File: domain/src/main/java/org/oppia/domain/oppialogger/crashlytics/ExceptionsController.kt (hunk 1 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/crashlytics/ExceptionsController.kt]: Modified, PTAL :)

File: domain/src/main/java/org/oppia/domain/oppialogger/exceptions/ExceptionsController.kt [hunk 12]
```diff
@@ -0,0 +1,150 @@
...
+  private val consoleLogger: ConsoleLogger,
+  private val networkConnectionUtil: NetworkConnectionUtil,
+  @ExceptionLogStorageCacheSize private val exceptionLogStorageCacheSize: Int
+) {
+  private val exceptionLogStore =
+    cacheStoreFactory.create("exception_logs", OppiaExceptionLogs.getDefaultInstance())
+
+  /** Logs a NON-FATAL exception. */
+  fun logNonFatalException(exception: Exception, timestamp: Long) {
+    uploadOrCacheExceptionLog(exception, timestamp, ExceptionLog.ExceptionType.NON_FATAL)
```
Comment (vinitamurthi) [inline domain/src/main/java/org/oppia/domain/oppialogger/exceptions/ExceptionsController.kt]: Can we import ExceptionLog.ExceptionType and directly use ExceptionType.NON_FATAL/FATAL

File: domain/src/main/java/org/oppia/domain/oppialogger/exceptions/ExceptionsController.kt [hunk 13]
```diff
@@ -0,0 +1,150 @@
...
+            .removeExceptionLog(exceptionLogRemovalIndex)
+            .addExceptionLog(exceptionLog)
+            .build()
+        } else {
+          // TODO (#1433): Refactoring for logging exceptions to both console and exception loggers.
+          val exception =
+            NullPointerException(
+              "Least Recent Exception index absent -- ExceptionLogCacheStoreSize is 0"
+            )
+          consoleLogger.e("Exceptions Controller", exception.toString())
```
Comment (vinitamurthi) [inline domain/src/main/java/org/oppia/domain/oppialogger/exceptions/ExceptionsController.kt]: Can we put this into a constant and use it in the file?

File: model/src/main/proto/oppia_logger.proto (hunk 9 above)
Comment (vinitamurthi) [reply model/src/main/proto/oppia_logger.proto]: Yep It should be EXCEPTION_TYPE_UNSPECIFIED

**Review by vinitamurthi — APPROVED** [review]
Overall LGTM, just a few comments!

File: domain/src/main/java/org/oppia/domain/oppialogger/crashlytics/ExceptionsController.kt (hunk 2 above)
Comment (vinitamurthi) [reply domain/src/main/java/org/oppia/domain/oppialogger/crashlytics/ExceptionsController.kt]: Resolving this

File: domain/src/main/java/org/oppia/domain/oppialogger/crashlytics/ExceptionsController.kt (hunk 1 above)
Comment (vinitamurthi) [reply domain/src/main/java/org/oppia/domain/oppialogger/crashlytics/ExceptionsController.kt]: Yeah we will do this in the OppiaLogger

File: domain/src/main/java/org/oppia/domain/oppialogger/exceptions/ExceptionsController.kt (hunk 12 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/exceptions/ExceptionsController.kt]: Done.

File: domain/src/main/java/org/oppia/domain/oppialogger/exceptions/ExceptionsController.kt (hunk 13 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/exceptions/ExceptionsController.kt]: Done.

File: model/src/main/proto/oppia_logger.proto (hunk 9 above)
Comment (Sarthak2601) [reply model/src/main/proto/oppia_logger.proto]: Done.

File: domain/src/main/java/org/oppia/domain/exploration/ExplorationProgressController.kt [hunk 14]
```diff
@@ -408,7 +408,8 @@ class ExplorationProgressController @Inject constructor(
             finishLoadExploration(exploration!!, explorationProgress)
             AsyncResult.success(explorationProgress.stateDeck.getCurrentEphemeralState())
           } catch (e: Exception) {
-            exceptionsController.logException(e, oppiaClock.getCurrentCalendar().timeInMillis)
+            exceptionsController
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/domain/exploration/ExplorationProgressController.kt]: I'd expect the line break to happen at the ``(`` first except when chaining multiple method calls together.

Feel free to resolve this comment after addressing it.

File: domain/src/main/java/org/oppia/domain/oppialogger/exceptions/ExceptionsController.kt [hunk 15]
```diff
@@ -10,103 +10,81 @@ import org.oppia.util.data.DataProviders
 import org.oppia.util.logging.ConsoleLogger
 import org.oppia.util.logging.ExceptionLogger
 import org.oppia.util.networking.NetworkConnectionUtil
-import org.oppia.util.system.OppiaClock
 import javax.inject.Inject
 
+const val EXCEPTIONS_CONTROLLER = "Exceptions Controller"
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/domain/oppialogger/exceptions/ExceptionsController.kt]: Prefer to make this ``private`` if it isn't being accessed outside of this class.

File: domain/src/main/java/org/oppia/domain/oppialogger/exceptions/ExceptionsController.kt (hunk 12 above)
Comment (BenHenning) [reply domain/src/main/java/org/oppia/domain/oppialogger/exceptions/ExceptionsController.kt]: Doesn't appear done--this still looks like ``ExceptionLog.ExceptionType.NON_FATAL``.

File: domain/src/main/java/org/oppia/domain/oppialogger/exceptions/ExceptionsController.kt [hunk 16]
```diff
@@ -10,103 +10,81 @@ import org.oppia.util.data.DataProviders
...
   private val consoleLogger: ConsoleLogger,
   private val networkConnectionUtil: NetworkConnectionUtil,
-  private val oppiaClock: OppiaClock,
   @ExceptionLogStorageCacheSize private val exceptionLogStorageCacheSize: Int
 ) {
   private val exceptionLogStore =
     cacheStoreFactory.create("exception_logs", OppiaExceptionLogs.getDefaultInstance())
 
-  lateinit var exceptionCause: Throwable
+  /** Logs a NON-FATAL exception. */
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/domain/oppialogger/exceptions/ExceptionsController.kt]: How is the timestamp used? That detail seems missing in this & the next method's KDoc. Please update.

File: domain/src/main/java/org/oppia/domain/oppialogger/exceptions/ExceptionsController.kt [hunk 17]
```diff
@@ -10,103 +10,81 @@ import org.oppia.util.data.DataProviders
...
       NetworkConnectionUtil.ConnectionStatus.NONE ->
-        cacheExceptionLog(exceptionToExceptionLog(exception, timestamp))
+        cacheExceptionLog(convertExceptionToExceptionLog(exception, timestamp, exceptionType))
       else -> exceptionLogger.logException(exception)
     }
   }
 
-  /** Returns an [ExceptionLog] from an [exception]. */
-  private fun exceptionToExceptionLog(exception: Exception, timestamp: Long): ExceptionLog {
+  /** Returns an [ExceptionLog] from an [throwable]. */
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/domain/oppialogger/exceptions/ExceptionsController.kt]: Nit: ``from a [throwable].``

File: domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt [hunk 18]
```diff
@@ -0,0 +1,350 @@
...
+import org.oppia.util.logging.EnableFileLog
+import org.oppia.util.logging.GlobalLogLevel
+import org.oppia.util.logging.LogLevel
+import org.oppia.util.networking.NetworkConnectionUtil
+import org.robolectric.annotation.Config
+import javax.inject.Inject
+import javax.inject.Qualifier
+import javax.inject.Singleton
+
+const val TEST_TIMESTAMP = 1556094120000
```
Comment (BenHenning) [inline domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt]: Prefer ``private`` if it's not accessed outside of this class. That's generally true for all members & classes.

File: domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt [hunk 19]
```diff
@@ -0,0 +1,350 @@
...
+  lateinit var oppiaExceptionLogsResultCaptor: ArgumentCaptor<AsyncResult<OppiaExceptionLogs>>
+
+  @Before
+  fun setUp() {
+    networkConnectionUtil = NetworkConnectionUtil(ApplicationProvider.getApplicationContext())
+    setUpTestApplicationComponent()
+  }
+
+  @Test
+  fun testController_logException_NonFatal_logsToRemoteService() {
```
Comment (BenHenning) [inline domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt]: Nit: ``testController_logException_nonFatal_logsToRemoteService``

The subsequent words in the test name should consistently follow lowerCamelCase. Ditto for all other test names in this class.

File: domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt [hunk 20]
```diff
@@ -0,0 +1,350 @@
...
+
+  @ExperimentalCoroutinesApi
+  @InternalCoroutinesApi
+  @Test
+  fun testController_logException_NonFatal_withNoNetwork_logsToCacheStore() {
+    networkConnectionUtil.setCurrentConnectionStatus(NetworkConnectionUtil.ConnectionStatus.NONE)
+    val exceptionThrown = Exception("TEST MESSAGE", Throwable("TEST CAUSE"))
+    exceptionsController.logNonFatalException(exceptionThrown, TEST_TIMESTAMP)
+
+    val cachedExceptions = exceptionsController.getExceptionLogs()
```
Comment (BenHenning) [inline domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt]: Out of curiosity, will ``getExceptionLogs`` be used by anything other than tests?

File: domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt [hunk 21]
```diff
@@ -0,0 +1,350 @@
...
+
+    verify(mockOppiaExceptionLogsObserver, atLeastOnce())
+      .onChanged(oppiaExceptionLogsResultCaptor.capture())
+
+    val exceptionOne = oppiaExceptionLogsResultCaptor.value.getOrThrow().getExceptionLog(0)
+    val exceptionTwo = oppiaExceptionLogsResultCaptor.value.getOrThrow().getExceptionLog(1)
+    val cacheStoreSize = oppiaExceptionLogsResultCaptor.value.getOrThrow().exceptionLogList.size
+
+    assertThat(cacheStoreSize).isEqualTo(2)
+    // In this case, 3 FATAL and 1 NON-FATAL exception was logged. So while pruning, none of the retained logs should have NON-FATAL exception type.
```
Comment (BenHenning) [inline domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt]: Nit: ``3 fatal and 1 non-fatal exceptions were logged.``

Comment (BenHenning) [inline domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt]: Here & everywhere else in this PR: please refer to 'fatal' and 'non-fatal' as standard words rather than specifically capitalizing them. We don't do this for any other terms in the codebase, and it's throwing me a bit off.

Comment (BenHenning) [inline domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt]: Also regarding the actual eviction strategy, shouldn't we prune non-fatal logs in favor of keeping fatal ones? Those seem more important to log to me.

File: domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt [hunk 22]
```diff
@@ -0,0 +1,350 @@
...
+    assertThat(exceptionOne.exceptionType).isNotEqualTo(ExceptionType.NON_FATAL)
+    assertThat(exceptionTwo.exceptionType).isNotEqualTo(ExceptionType.NON_FATAL)
+    // If we analyse the order of logging of exceptions, we can see that record pruning will begin from the logging of the third record.
+    // At first, the second exception log will be removed as it has NON-FATAL exception type and the exception logged at the third place will become the exception record at the second place in the store.
+    // When the forth exception gets logged then the pruning will be purely based on timestamp of the exception as both exception logs have FATAL exception type.
+    // As the third exceptions's timestamp was lesser than that of the first event, it will be pruned from the store and the forth exception will become the second exception in the store.
+    assertThat(exceptionOne.timestampInMillis).isEqualTo(1556094120000)
```
Comment (BenHenning) [inline domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt]: Please save these & other timestamps to distinct constants to help provide quick cross-reference checking for methods like this.

File: domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt [hunk 23]
```diff
@@ -0,0 +1,350 @@
...
+    verify(mockOppiaExceptionLogsObserver, atLeastOnce())
+      .onChanged(oppiaExceptionLogsResultCaptor.capture())
+
+    val exceptionOne = oppiaExceptionLogsResultCaptor.value.getOrThrow().getExceptionLog(0)
+    val exceptionTwo = oppiaExceptionLogsResultCaptor.value.getOrThrow().getExceptionLog(1)
+    val cacheStoreSize = oppiaExceptionLogsResultCaptor.value.getOrThrow().exceptionLogList.size
+
+    assertThat(cacheStoreSize).isEqualTo(2)
+    // In this case, 3 FATAL and 1 NON-FATAL exception was logged. So while pruning, none of the retained logs should have NON-FATAL exception type.
+    assertThat(exceptionOne.exceptionType).isNotEqualTo(ExceptionType.NON_FATAL)
```
Comment (BenHenning) [inline domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt:199]: Can we also check the cause messages against TEST1/2/3/4 to verify the correct ones were logged?

File: domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt [hunk 24]
```diff
@@ -0,0 +1,350 @@
...
+    // When the forth exception gets logged then the pruning will be purely based on timestamp of the exception as both exception logs have FATAL exception type.
+    // As the third exceptions's timestamp was lesser than that of the first event, it will be pruned from the store and the forth exception will become the second exception in the store.
+    assertThat(exceptionOne.timestampInMillis).isEqualTo(1556094120000)
+    assertThat(exceptionTwo.timestampInMillis).isEqualTo(1556094000000)
+  }
+
+  @ExperimentalCoroutinesApi
+  @InternalCoroutinesApi
+  @Test
+  fun testController_logExceptions_exceedLimit_checkSizeOfCache() {
```
Comment (BenHenning) [inline domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt]: ``checkSizeOfCache``is not an expected outcome. Might this be: cacheSizeDoesNotExceedLimit or similar?

Also, isn't this tested in the test above? I suggest keeping this test & removing the size check in the test above to keep the different behaviors clearly distinct between the two tests.

File: domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt [hunk 25]
```diff
@@ -0,0 +1,350 @@
...
+      .onChanged(oppiaExceptionLogsResultCaptor.capture())
+    val cacheStoreSize = oppiaExceptionLogsResultCaptor.value.getOrThrow().exceptionLogList.size
+
+    assertThat(cacheStoreSize).isEqualTo(2)
+  }
+
+  @ExperimentalCoroutinesApi
+  @InternalCoroutinesApi
+  @Test
+  fun testController_logException_switchToNoNetwork_logException_checkManagement() {
```
Comment (BenHenning) [inline domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt]: Here & below: what is the actual desired outcome? ``checkManagement`` and ``checkOrderInCache`` describe what the test is doing, not what we expect it to verify. Please update both test names.

File: domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt [hunk 26]
```diff
@@ -0,0 +1,350 @@
...
+  }
+
+  private fun setUpTestApplicationComponent() {
+    DaggerExceptionsControllerTest_TestApplicationComponent.builder()
+      .setApplication(ApplicationProvider.getApplicationContext())
+      .build()
+      .inject(this)
+  }
+
+  private fun exceptionLogToException(exceptionLog: ExceptionLog): Exception {
```
Comment (BenHenning) [inline domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt]: This & below: these are a bit too much logic for a test. Could we maybe have a few assertion helpers that verify a few aspects of the exception rather than trying to do an exact comparison between the two? Or, factor out the prod conversion code into a helper that both the controller & its test can use, and have a few dedicated tests for that helper utility to verify it's correct.

The latter is probably the cleaner solution, but it's up to you which approach you want to go with.

File: domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt [hunk 27]
```diff
@@ -0,0 +1,350 @@
...
+import org.robolectric.annotation.Config
+import javax.inject.Inject
+import javax.inject.Qualifier
+import javax.inject.Singleton
+
+const val TEST_TIMESTAMP = 1556094120000
+
+@RunWith(AndroidJUnit4::class)
+@Config(manifest = Config.NONE)
+class ExceptionsControllerTest {
```
Comment (BenHenning) [inline domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt:53]: What about a test verifying that network reconnection triggers an upload of all past cached exceptions?

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @Sarthak2601! Overall, the approach looks good and your tests are quite nice. I did a full review, and would like to do one more pass before approving (though I defer to @vinitamurthi on verifying my comments and approving in my place if this is time sensitive).

**Review by BenHenning — COMMENTED** [review]
Changing status to 'comment' to avoid blocking the PR.

File: domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt (hunk 27 above)
Comment (Sarthak2601) [reply domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt:53]: All tests related to the uploading of event/exception reports will be written when we implement the final upload functionality via Work Manager. So, I will add all the tests related to upload in that PR.

File: domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt (hunk 20 above)
Comment (Sarthak2601) [reply domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt]: Yes, when we implement the uploading functionality.

File: domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt (hunk 21 above)
Comment (Sarthak2601) [reply domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt]: Yes, that is what's happening. We prune non-fatal exceptions in favour of the fatal ones.

File: domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt (hunk 25 above)
Comment (Sarthak2601) [reply domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt]: Done.

File: domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt (hunk 24 above)
Comment (Sarthak2601) [reply domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt]: Done.

File: domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt (hunk 23 above)
Comment (Sarthak2601) [reply domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt:199]: Done.

File: domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt (hunk 22 above)
Comment (Sarthak2601) [reply domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt]: I kept them as numbers because it would've been easier to cross-verify pruning. Changed to constants now.

File: domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt (hunk 21 above)
Comment (Sarthak2601) [reply domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt]: Done.

Comment (Sarthak2601) [reply domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt]: Done.

File: domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt (hunk 19 above)
Comment (Sarthak2601) [reply domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt]: Done.

File: domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt (hunk 18 above)
Comment (Sarthak2601) [reply domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt]: Done.

File: domain/src/main/java/org/oppia/domain/oppialogger/exceptions/ExceptionsController.kt (hunk 17 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/exceptions/ExceptionsController.kt]: Done.

File: domain/src/main/java/org/oppia/domain/oppialogger/exceptions/ExceptionsController.kt (hunk 16 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/exceptions/ExceptionsController.kt]: Done.

File: domain/src/main/java/org/oppia/domain/oppialogger/exceptions/ExceptionsController.kt (hunk 15 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/exceptions/ExceptionsController.kt]: Done.

File: domain/src/main/java/org/oppia/domain/exploration/ExplorationProgressController.kt (hunk 14 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/exploration/ExplorationProgressController.kt]: Done.

File: domain/src/main/java/org/oppia/domain/oppialogger/exceptions/ExceptionsController.kt (hunk 12 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/exceptions/ExceptionsController.kt]: Oh my bad, I did it in the test file. Done now.

File: domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt (hunk 26 above)
Comment (Sarthak2601) [reply domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt]: Working on it.

Comment (Sarthak2601) [reply domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt]: Done.

File: domain/src/main/java/org/oppia/domain/oppialogger/exceptions/ExceptionsController.kt (hunk 13 above)
Comment (vinitamurthi) [reply domain/src/main/java/org/oppia/domain/oppialogger/exceptions/ExceptionsController.kt]: Hmm I am not able to see this change

Comment (vinitamurthi) [reply domain/src/main/java/org/oppia/domain/oppialogger/exceptions/ExceptionsController.kt]: I think you have done it below but not here

File: utility/src/main/java/org/oppia/util/logging/ExceptionsHelper.kt [hunk 28]
```diff
@@ -0,0 +1,47 @@
+package org.oppia.util.logging
+
+import org.oppia.app.model.ExceptionLog
+
+/** Helper class for conversion of exceptionLog proto object to an Exception. */
+class ExceptionsHelper {
```
Comment (vinitamurthi) [inline utility/src/main/java/org/oppia/util/logging/ExceptionsHelper.kt]: Maybe ExceptionParsingUtil or something on those lines ? ExceptionsHelper sounds a bit vague (But I am bad with names !)

File: domain/src/main/java/org/oppia/domain/oppialogger/exceptions/ExceptionsController.kt [hunk 29]
```diff
@@ -26,14 +27,20 @@ class ExceptionsController @Inject constructor(
   private val exceptionLogStore =
     cacheStoreFactory.create("exception_logs", OppiaExceptionLogs.getDefaultInstance())
 
-  /** Logs a NON-FATAL exception. */
+  /**
+   * Logs a non-fatal [exception].
+   * The [timestamp], along with [ExceptionType] facilitate effective pruning records when [exceptionLogStorageCacheSize] is exceeded.
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/domain/oppialogger/exceptions/ExceptionsController.kt]: This is a bit obscure. Maybe something like the following would be clearer:

```kotlin
/**
 * Logs a non-fatal [exception]. Note that exceptions may not actually be logged depending on the network status of the device. Older exceptions will be pruned to make room for newer exceptions.
 *
 * @param timestamp the time, in milliseconds, when the exception occurred
 *
```

Ditto elsewhere, and the suggestion above may require line wrapping.

File: domain/src/main/java/org/oppia/domain/oppialogger/exceptions/ExceptionsController.kt [hunk 30]
```diff
@@ -26,14 +27,20 @@ class ExceptionsController @Inject constructor(
...
+   */
   fun logNonFatalException(exception: Exception, timestamp: Long) {
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/domain/oppialogger/exceptions/ExceptionsController.kt]: Missed this the first time, but all times should always be qualified based on their time unit (e.g. ``timestampMillis``).

File: domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt [hunk 31]
```diff
@@ -42,7 +42,10 @@ import javax.inject.Inject
 import javax.inject.Qualifier
 import javax.inject.Singleton
 
-const val TEST_TIMESTAMP = 1556094120000
+private const val TEST_TIMESTAMP_ONE = 1556094120000
```
Comment (BenHenning) [inline domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt]: Ditto here & everywhere else (please qualify times based on their units).

File: domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt (hunk 20 above)
Comment (BenHenning) [reply domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt]: Makes sense, but will that actually be using LiveData? How will uploading functionality utilize this function?

File: utility/src/main/java/org/oppia/util/logging/ExceptionsHelper.kt [hunk 32]
```diff
@@ -0,0 +1,47 @@
+package org.oppia.util.logging
+
+import org.oppia.app.model.ExceptionLog
+
+/** Helper class for conversion of exceptionLog proto object to an Exception. */
```
Comment (BenHenning) [inline utility/src/main/java/org/oppia/util/logging/ExceptionsHelper.kt]:
```suggestion
/** Helper class for conversion of [ExceptionLog] object to an [Exception]. */
```

File: utility/src/main/java/org/oppia/util/logging/ExceptionsHelper.kt [hunk 33]
```diff
@@ -0,0 +1,47 @@
...
+class ExceptionsHelper {
+
+  /** Converts the [exceptionLog] into an appropriate exception. */
+  fun convertExceptionLogToException(exceptionLog: ExceptionLog): Exception {
+    val exceptionMessage = if (exceptionLog.message != "") {
+      exceptionLog.message
+    } else {
+      null
+    }
```
Comment (vinitamurthi) [inline utility/src/main/java/org/oppia/util/logging/ExceptionsHelper.kt]: I think you can reduce this into a single line like this:
`val exceptionMessage = if (exceptionLog.message.isEmpty()) null else exceptionLog.message`

File: utility/src/main/java/org/oppia/util/logging/ExceptionsHelper.kt [hunk 34]
```diff
@@ -0,0 +1,47 @@
...
+    val exceptionCause: Throwable? =
+      if (exceptionLog.cause.message == "" && exceptionLog.cause.stacktraceElementCount == 0) {
+        null
+      } else if (
+        exceptionLog.cause.message == "" && exceptionLog.cause.stacktraceElementCount != 0
+      ) {
+        Throwable()
+      } else {
+        Throwable(exceptionLog.cause.message)
+      }
```
Comment (vinitamurthi) [inline utility/src/main/java/org/oppia/util/logging/ExceptionsHelper.kt]: Can we extract this into a separate function and call it here like 
`val exceptionCause: Throwable? = extractExceptionCause(exception)` to make it more readable?

File: utility/src/test/java/org/oppia/util/logging/ExceptionsHelperTest.kt [hunk 35]
```diff
@@ -0,0 +1,69 @@
...
+class ExceptionsHelperTest {
+
+  private val exceptionLog = ExceptionLog.newBuilder().setMessage("TEST").build()
+
+  @Before
+  fun setUp() {
+    setUpTestApplicationComponent()
+  }
+
+  @Test
```
Comment (vinitamurthi) [inline utility/src/test/java/org/oppia/util/logging/ExceptionsHelperTest.kt]: Can you add tests for the different if conditions you have written above? 
e.g.
* When cause is empty and stack trace is 0
* When cause is empty and stark trace is > 0
* When exception message is null

**Review by vinitamurthi — CHANGES_REQUESTED** [review]

File: utility/src/main/java/org/oppia/util/logging/ExceptionsHelper.kt [hunk 36]
```diff
@@ -0,0 +1,47 @@
...
+    exceptionCause?.let {
+      it.stackTrace = createErrorStackTrace(exceptionLog.cause)
+    }
```
Comment (BenHenning) [inline utility/src/main/java/org/oppia/util/logging/ExceptionsHelper.kt]:
```suggestion
    val exceptionCause: Throwable? =
      if (exceptionLog.hasCause()) convertExceptionLogToException(exceptionLog.cause)
      else null
```

This seems simplifiable.

File: utility/src/main/java/org/oppia/util/logging/ExceptionsHelper.kt (hunk 28 above)
Comment (BenHenning) [inline utility/src/main/java/org/oppia/util/logging/ExceptionsHelper.kt]: Could we create an extension function on ``ExceptionLog``, instead? E.g. ``ExceptionLog.toException``? That might be cleaner than having a generic helper/utility for random exception things.

**Review by BenHenning — COMMENTED** [review]
Thanks @Sarthak2601! Some more thoughts.

File: domain/src/main/java/org/oppia/domain/oppialogger/exceptions/ExceptionsController.kt (hunk 13 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/exceptions/ExceptionsController.kt]: Done.

File: utility/src/main/java/org/oppia/util/logging/ExceptionsHelper.kt (hunk 28 above)
Comment (Sarthak2601) [reply utility/src/main/java/org/oppia/util/logging/ExceptionsHelper.kt]: File removed.

File: utility/src/main/java/org/oppia/util/logging/ExceptionsHelper.kt (hunk 33 above)
Comment (Sarthak2601) [reply utility/src/main/java/org/oppia/util/logging/ExceptionsHelper.kt]: It worked but file removed due to addition of extension function in the controller itself.

File: utility/src/main/java/org/oppia/util/logging/ExceptionsHelper.kt (hunk 34 above)
Comment (Sarthak2601) [reply utility/src/main/java/org/oppia/util/logging/ExceptionsHelper.kt]: Yes, it would've been more readable but Ben's suggestion below simplified all of this. So modified accordingly.

File: utility/src/test/java/org/oppia/util/logging/ExceptionsHelperTest.kt (hunk 35 above)
Comment (Sarthak2601) [reply utility/src/test/java/org/oppia/util/logging/ExceptionsHelperTest.kt]: File removed.

File: domain/src/main/java/org/oppia/domain/oppialogger/exceptions/ExceptionsController.kt (hunk 29 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/exceptions/ExceptionsController.kt]: Done.

File: domain/src/main/java/org/oppia/domain/oppialogger/exceptions/ExceptionsController.kt (hunk 30 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/exceptions/ExceptionsController.kt]: Done.

File: domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt (hunk 31 above)
Comment (Sarthak2601) [reply domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt]: Done.

File: utility/src/main/java/org/oppia/util/logging/ExceptionsHelper.kt (hunk 32 above)
Comment (Sarthak2601) [reply utility/src/main/java/org/oppia/util/logging/ExceptionsHelper.kt]: File removed.

File: utility/src/main/java/org/oppia/util/logging/ExceptionsHelper.kt (hunk 36 above)
Comment (Sarthak2601) [reply utility/src/main/java/org/oppia/util/logging/ExceptionsHelper.kt]: Yes, done.

File: utility/src/main/java/org/oppia/util/logging/ExceptionsHelper.kt (hunk 28 above)
Comment (Sarthak2601) [reply utility/src/main/java/org/oppia/util/logging/ExceptionsHelper.kt]: Yes, it's a lot cleaner now. Thanks !

**Comment by Sarthak2601** [comment]
@BenHenning @vinitamurthi Just to be clear, I didn't add test cases for the extension function because its functionality gets tested in all the tests that use it. In my opinion, if I write test cases for it then they will be very similar to the ones we already have. Does this make sense or should I add test cases for it anyway ?

File: domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt (hunk 20 above)
Comment (Sarthak2601) [reply domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt]: So my basic motive of using this method was to get the logs without going into threading. Data Providers does that but it's usage around the codebase for retrieval of cache was typically using LiveData only. You're right that the work manager (uploading functionality) won't be using any of the LiveData things. It would simply like to read from the store and upload.

Comment (BenHenning) [reply domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt]: Every place that requires background or async processing goes through DataProviders. We convert DataProviders to LiveData only for when we want to observe the DataProvider from a UI. If this needs to be a DataProvider, instead, you can still test it by adding listeners to it (see DataProvidersTest fro an example).

File: domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt (hunk 27 above)
Comment (BenHenning) [reply domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt:53]: Thanks for additional context.

File: domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt (hunk 21 above)
Comment (BenHenning) [reply domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt]: The test suggests otherwise though. Isn’t it showing that an older fatal exception is being pruned in favor of a newer non fatal exception?

Comment (Sarthak2601) [reply domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt]: No, the order of logging is fatal->non-fatal->fatal->fatal. So it prunes the non-fatal exception when it adds the third log (which is fatal). I've updated the comment to make it clearer.

File: domain/src/main/java/org/oppia/domain/oppialogger/exceptions/ExceptionsController.kt [hunk 37]
```diff
@@ -0,0 +1,199 @@
...
+            timestampInMillis,
+            exceptionType
+          )
+        )
+      else -> exceptionLogger.logException(exception)
+    }
+  }
+
+  /** Returns an [ExceptionLog] from a [throwable]. */
+  private fun convertExceptionToExceptionLog(
```
Comment (vinitamurthi) [inline domain/src/main/java/org/oppia/domain/oppialogger/exceptions/ExceptionsController.kt]: Is it worth making this an extension function as well?

**Review by vinitamurthi — COMMENTED** [review]
Umm are we testing all the edge cases of the extension function ? (i.e. when cause is null and all) If so then we do not need to create a separate test for the extension function. But in general I prefer to keep tests for each function as much as possible to keep it readable and to ensure we catch every case the extension function could run into

File: domain/src/main/java/org/oppia/domain/oppialogger/exceptions/ExceptionsController.kt (hunk 37 above)
Comment (Sarthak2601) [reply domain/src/main/java/org/oppia/domain/oppialogger/exceptions/ExceptionsController.kt]: We'd still have to pass two arguments but yes it looks better. Done.

**Comment by Sarthak2601** [comment]
> Umm are we testing all the edge cases of the extension function ? (i.e. when cause is null and all) If so then we do not need to create a separate test for the extension function. But in general I prefer to keep tests for each function as much as possible to keep it readable and to ensure we catch every case the extension function could run into

Added tests for the edge cases.

File: domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt (hunk 20 above)
Comment (Sarthak2601) [reply domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt]: PTAL

File: domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt [hunk 38]
```diff
@@ -293,6 +357,14 @@ class ExceptionsControllerTest {
       return application
     }
 
+    @ExperimentalCoroutinesApi
+    @Singleton
+    @Provides
+    @TestDispatcher
+    fun provideTestDispatcher(): CoroutineDispatcher {
```
Comment (BenHenning) [inline domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt]: Please don’t do this. You should include the test dispatcher module, instead.

File: domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt (hunk 21 above)
Comment (BenHenning) [reply domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt]: Sorry, I think I’m confused. The test is verifying that one of the pending exceptions is non-fatal—how does that correspond to the exception being pruned? How exactly is this test verifying the pruning strategy?

**Review by BenHenning — COMMENTED** [review]
Few more comments.

File: domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt (hunk 21 above)
Comment (Sarthak2601) [reply domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt]: The test is verifying that the exception type of any of the stored exception logs is not equal to non-fatal. It verifies the pruning strategy as - 
- Non-fatal exceptions are pruned in favour of the fatal ones. 
- The least recent exception gets pruned in favour of the most recent one.

File: domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt (hunk 38 above)
Comment (Sarthak2601) [reply domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt]: Done.

File: domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt (hunk 21 above)
Comment (vinitamurthi) [reply domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt]: The test is verifying that both the exceptions that were retained are not non-fatal (see the isNotEqualTo checks) . If I understand correctly, there were 4 total exceptions - 3 fatal, and one non-fatal.
What this test is doing is verifying that the non-fatal exception was pruned and the least recent fatal exception was pruned. Correct me if I'm wrong @Sarthak2601 ;

Comment (BenHenning) [reply domain/src/test/java/org/oppia/domain/oppialogger/exceptions/ExceptionsControllerTest.kt]: Ah, I see where my confusion was. I actually kept reading ``isEqualTo``--thanks for the additional clarification!

**Review by BenHenning — APPROVED** [review]
Thanks, LGTM @Sarthak2601!

**Review by vinitamurthi — APPROVED** [review]

**Comment by vinitamurthi** [comment]
Please merge develop to this branch!
