### PR TITLE
Fix #1468: Retain Drag and Drop state after an incorrect answer

### LINKED ISSUE #1468: Drag & drop drag state resets after an incorrect answer
**Describe the bug**
When using the drag & drop interaction, an incorrect answer results in the same drag state being shown.

**To Reproduce**
1. Start the Prototype Exploration on a dev build of the app
2. Play through it until the first drag & drop state
3. Drag the items to produce an incorrect answer
4. Submit the answer
5. Observe that the drag & drop order resets back to the original state

**Expected behavior**
The drag & drop order should stay the same after the incorrect answer.

**Screenshot**
oppia_drag_drop_not_retaining_state

**Device**
- Device: Pixel XL
- SDK: 29

## Additional Information

Comment https://github.com/oppia/oppia-android/issues/1468#issuecomment-669301671 was addressed in https://github.com/oppia/oppia-android/pull/5478.

### PR DESCRIPTION
**Pull request by Rd4dev**
## Explanation

Fix #1468 

### This PR includes

- Utilized `explorationProgressController` to retrieve the **'wrongAnswerList'** from ephemeralState's pendingState and use it to populate the `DragDropInteractionContentViewModel` list.
- When `wrongAnswerList` is available, corresponding content IDs and HTML values are applied. If not, the original `contentIdHtmlMap` and `SubtitledHtml` values are used as a fallback.
- The `choiceItems` are set up as LiveData to ensure the UI can react to changes.
- The `_choiceItems` are copied to `_originalChoiceItems ` for detecting arrangement box errors during submission when the answer has not changed.
- Retains linked-merged / unlinked states based on the `wrongAnswerList` data

### Re-order Retain State

https://github.com/user-attachments/assets/f4c3fd72-d96d-4ee8-b82e-af134ea06a2b

### Group / Unlink Retain

https://github.com/user-attachments/assets/c90a5fc2-ccf9-4e21-a7cd-31f9ec1bd6c0

### Espresso Tests

image

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

### CODE REVIEW

**Comment by Rd4dev** [comment]
@BenHenning, @adhiamboperes, could you PTAL and confirm if this could effectively retain the drag-and-drop states? 
I'm uncertain if using `runBlocking` is the right approach here. 

```
runBlocking {
  when (val result = explorationProgressController.getCurrentState().retrieveData()) { ...}
}
```

#

I'll rework this (possibly by finding a way to update the adapter) since it's blocking the current thread and causing test timeouts.

**Comment by Rd4dev** [comment]
@adhiamboperes, utilized LiveData to retain the states and added corresponding Robolectric tests. However, I haven't been able to add or verify the Espresso tests with issues, as mentioned in #5435. Is there anything I missed or any workaround to resolve this? Could you PTAL.

**Comment by Vishwajith-Shettigar** [comment]
> @adhiamboperes, utilized LiveData to retain the states and added corresponding Robolectric tests. However, I haven't been able to add or verify the Espresso tests with issues, as mentioned in #5435. Is there anything I missed or any workaround to resolve this? Could you PTAL.

The workaround would be to comment out the Oppia test rule in that test class.

**Comment by Rd4dev** [comment]
> The workaround would be to comment out the Oppia test rule in that test class.

@Vishwajith-Shettigar -- thanks for helping out, I commented the Oppia Test Rule, but it led to the `MockitoException` shared in the additional context #5435. After bumping Mockito to version 3.11.1, the tests started working with Espresso!

_Yet to approve the version bump._

**Comment by Vishwajith-Shettigar** [comment]
> > The workaround would be to comment out the Oppia test rule in that test class.
> 
> @Vishwajith-Shettigar -- thanks for helping out, I commented the Oppia Test Rule, but it led to the `MockitoException` shared in the additional context #5435. After bumping Mockito to version 3.11.1, the tests started working with Espresso!
> 
> _Yet to approve the version bump._

I usually bump to version 2.27.0 as a workaround, but version 2.22.0 >= may also work well with Java 11.

**Comment by Rd4dev** [comment]
> I usually bump to version 2.27.0 as a workaround, but version 2.22.0 >= may also work well with Java 11.

Thanks, @Vishwajith-Shettigar, would try that. It was also mentioned during the meeting that PR #5467 would be revived sometime soon and that would resolve this more thoroughly.

File: app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/DragAndDropSortInteractionViewModel.kt [hunk 1]
```diff
@@ -49,11 +56,14 @@ class DragAndDropSortInteractionViewModel private constructor(
   private val writtenTranslationContext: WrittenTranslationContext,
   private val resourceHandler: AppLanguageResourceHandler,
   private val translationController: TranslationController,
-  userAnswerState: UserAnswerState
+  userAnswerState: UserAnswerState,
+  private val fragment: Fragment,
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/DragAndDropSortInteractionViewModel.kt]: We typically dont pass fragments or contexts to the viewmodel as this could lead to memory leaks.

File: app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/DragAndDropSortInteractionViewModel.kt [hunk 2]
```diff
@@ -324,25 +341,70 @@ class DragAndDropSortInteractionViewModel private constructor(
...
+        dragAndDropSortInteractionViewModel,
+        resourceHandler
+      )
+      _choiceItemsLiveData.value = _choiceItems
+      _originalChoiceItems = _choiceItems.toMutableList()
+    }
+
+    return _choiceItems.takeIf { it.isNotEmpty() }
+      ?: _originalChoiceItems.toMutableList()
+  }
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/DragAndDropSortInteractionViewModel.kt]: Instead of observing livedata, you can use `Transformations`. this eliminates the need for the fragment instance.
```suggestion
    val ephemeralStateLiveData: LiveData<MutableList<DragDropInteractionContentViewModel>> by lazy {
      Transformations.map(explorationProgressController.getCurrentState().toLiveData()){result->
        return@map when(result){
          is AsyncResult.Failure -> _originalChoiceItems.toMutableList()
          is AsyncResult.Pending -> _originalChoiceItems.toMutableList()
          is AsyncResult.Success -> {
            val state = result.value
            val wrongAnswerList = state.pendingState.wrongAnswerList

            if (wrongAnswerList.isNotEmpty()) {
              val latestWrongAnswerContentIdList = wrongAnswerList.last()
                .userAnswer
                .answer
                .listOfSetsOfTranslatableHtmlContentIds
                .contentIdListsList

              latestWrongAnswerContentIdList.mapIndexed { index, setOfTranslatableHtmlContentIds ->
                DragDropInteractionContentViewModel(
                  contentIdHtmlMap = contentIdHtmlMap,
                  htmlContent = SetOfTranslatableHtmlContentIds.newBuilder().apply {
                    for (contentIds in setOfTranslatableHtmlContentIds.contentIdsList) {
                      addContentIds(
                        TranslatableHtmlContentId.newBuilder().apply {
                          contentId = contentIds.contentId
                        }
                      )
                    }
                  }.build(),
                  itemIndex = index,
                  listSize = latestWrongAnswerContentIdList.size,
                  dragAndDropSortInteractionViewModel = dragAndDropSortInteractionViewModel,
                  resourceHandler = resourceHandler
                )
              }.toMutableList()
            } else {
              _originalChoiceItems.toMutableList()
            }
          }
        }
      }
    }
```

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thank you @Rd4dev! I have left some suggestions, PTAL.

File: app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/DragAndDropSortInteractionViewModel.kt (hunk 1 above)
Comment (Rd4dev) [reply app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/DragAndDropSortInteractionViewModel.kt]: Got it, updated it with `Transformations` as suggested.

File: app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/DragAndDropSortInteractionViewModel.kt (hunk 2 above)
Comment (Rd4dev) [reply app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/DragAndDropSortInteractionViewModel.kt]: Thanks for the suggestion, updated it accordingly.

**Comment by Rd4dev** [comment]
@adhiamboperes, thanks for the review and the helpful direction. 
I've applied the changes, incorporating some adjustments -- PTAL.

**Review by adhiamboperes — APPROVED** [review]
Thanks @Rd4dev! This fix LGTM.

Just a note, however, that the video demos seem to be broken. Could you please re-upload them?

**Comment by Rd4dev** [comment]
Thanks @adhiamboperes for the review. I've updated the video demos in the description. Could you please check if they're functioning properly now?

**Comment by adhiamboperes** [comment]
Thanks @Rd4dev, the recordings play now.
