### PR TITLE
Fix part of #660: Lowfi admin controls part 4 Edit Profiles and Download Permissions

### LINKED ISSUE #660: Lowfi Admin Controls (Part 4): Edit Profiles
Mock: https://xd.adobe.com/view/0687f00c-695b-437a-79a6-688e7f4f7552-70b6/screen/71345025-f19e-4cac-a63f-e94442540e8f/Settings-6

https://xd.adobe.com/view/0687f00c-695b-437a-79a6-688e7f4f7552-70b6/screen/ddc3dadf-10e4-45f6-aeea-eb8a330e00ff/Settings-1-Profile-1

## Checklist
- [ ] Complete Edit Profiles Functionalities
- [ ] Test cases

### PR DESCRIPTION
**Pull request by Luffy18346**
## Explanation
Fix #660 Lowfi Admin Controls part 4: Edit Profiles and Download Permissions 

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by Luffy18346** [comment]
@rt4914 Edit Profiles UI and testing both are done. I am facing some issues in download permissions - the permissions are updated but not reflected when u open the `AdministratorControlsActivity` again.

File: app/src/main/java/org/oppia/app/administratorcontrols/AdministratorControlsViewModel.kt [hunk 1]
```diff
@@ -9,22 +11,36 @@ import org.oppia.app.administratorcontrols.administratorcontrolsitemviewmodel.Ad
...
 import javax.inject.Inject
 
 /** [ViewModel] for [AdministratorControlsFragment]. */
 @FragmentScope
-class AdministratorControlsViewModel @Inject constructor() : ObservableViewModel() {
+class AdministratorControlsViewModel @Inject constructor(
+  private val activity: AppCompatActivity,
+  private val fragment: Fragment,
+  private val logger: Logger,
+  private val profileManagementController: ProfileManagementController
```
Comment (rt4914) [inline app/src/main/java/org/oppia/app/administratorcontrols/AdministratorControlsViewModel.kt:29]: Your implementation is not working because all these parameters are never getting set in your viewmodel.
To make it correct check the implementation of `StoryChapterSummaryViewModel` inside `StoryViewModel` and how `StoryChapterSummaryViewModel` takes care of the rest. Meaning that your `AdministratorControlsViewModel` will contain the live data process everything and then create a `AdministratorControlsDownloadPermissionsViewModel` which will have all the final things which are required in xml file.

**Review by rt4914 — CHANGES_REQUESTED** [review]
Implementation Change.

File: app/src/main/java/org/oppia/app/administratorcontrols/AdministratorControlsViewModel.kt (hunk 1 above)
Comment (Luffy18346) [reply app/src/main/java/org/oppia/app/administratorcontrols/AdministratorControlsViewModel.kt:29]: Done. Thanks for the suggestion. Download Permissions are working and test-cases are passing as well.

File: app/src/main/java/org/oppia/app/administratorcontrols/AdministratorControlsViewModel.kt [hunk 2]
```diff
@@ -9,22 +12,55 @@ import org.oppia.app.administratorcontrols.administratorcontrolsitemviewmodel.Ad
...
+    Transformations.map(profileManagementController.getDeviceSettings(), ::processGetDeviceSettingsResult)
+  }
+
+  val administratorControlsLiveData: LiveData<List<AdministratorControlsItemViewModel>> by lazy {
+    Transformations.map(deviceSettingsLiveData, ::processAdministratorControlsList)
+  }
+
+  private fun processGetDeviceSettingsResult(deviceSettingsResult: AsyncResult<DeviceSettings>): DeviceSettings {
+    if (deviceSettingsResult.isFailure()) {
+      logger.e("AdministratorControlsFragmentPresenter", "Failed to retrieve profile", deviceSettingsResult.getErrorOrNull()!!)
```
Comment (rt4914) [inline app/src/main/java/org/oppia/app/administratorcontrols/AdministratorControlsViewModel.kt]: Replace `AdministratorControlsFragmentPresenter` with `AdministratorControlsFragment` we keep fragment/activity name only in TAG.

File: app/src/main/java/org/oppia/app/administratorcontrols/AdministratorControlsViewModel.kt [hunk 3]
```diff
@@ -9,22 +12,55 @@ import org.oppia.app.administratorcontrols.administratorcontrolsitemviewmodel.Ad
...
+    }
+    return deviceSettingsResult.getOrDefault(DeviceSettings.getDefaultInstance())
+  }
+
+  fun processAdministratorControlsList(deviceSettings: DeviceSettings): List<AdministratorControlsItemViewModel>{
```
Comment (rt4914) [inline app/src/main/java/org/oppia/app/administratorcontrols/AdministratorControlsViewModel.kt]: This can be private.

File: app/src/main/java/org/oppia/app/administratorcontrols/administratorcontrolsitemviewmodel/AdministratorControlsDownloadPermissionsViewModel.kt [hunk 4]
```diff
@@ -1,4 +1,38 @@
...
+import org.oppia.util.logging.Logger
+
 /** [ViewModel] for the recycler view in [AdministratorControlsFragment]. */
-class AdministratorControlsDownloadPermissionsViewModel : AdministratorControlsItemViewModel()
+class AdministratorControlsDownloadPermissionsViewModel(
+  private val fragment: Fragment,
+  private val logger: Logger,
+  private val profileManagementController: ProfileManagementController,
+  private val userProfileId: ProfileId,
+  private val deviceSettings: DeviceSettings
```
Comment (rt4914) [inline app/src/main/java/org/oppia/app/administratorcontrols/administratorcontrolsitemviewmodel/AdministratorControlsDownloadPermissionsViewModel.kt]: Nit:
`deviceSettings: DeviceSettings`

File: app/src/main/java/org/oppia/app/administratorcontrols/administratorcontrolsitemviewmodel/AdministratorControlsDownloadPermissionsViewModel.kt [hunk 5]
```diff
@@ -1,4 +1,38 @@
...
+      if (it.isFailure()) {
+        logger.e("AdministratorControlsDownloadPermissionsViewModel", "Failed to update topic update on wifi permission", it.getErrorOrNull()!!)
+      }
+    })
+  }
+
+  fun onTopicAutoUpdatePermissionChanged(checked: Boolean) {
+    profileManagementController.updateTopicAutomaticallyPermissionDeviceSettings(userProfileId, checked).observe(fragment, Observer {
+      if (it.isFailure()) {
+        logger.e("AdministratorControlsDownloadPermissionsViewModel", "Failed to update topic auto update permission", it.getErrorOrNull()!!)
```
Comment (rt4914) [inline app/src/main/java/org/oppia/app/administratorcontrols/administratorcontrolsitemviewmodel/AdministratorControlsDownloadPermissionsViewModel.kt]: Keep fragment name in place of TAG here and above.

File: app/src/main/java/org/oppia/app/administratorcontrols/administratorcontrolsitemviewmodel/AdministratorControlsProfileViewModel.kt [hunk 6]
```diff
@@ -1,4 +1,12 @@
 package org.oppia.app.administratorcontrols.administratorcontrolsitemviewmodel
 
+import org.oppia.app.administratorcontrols.RouteToProfileListListener
+
 /** [ViewModel] for the recycler view in [AdministratorControlsFragment]. */
-class AdministratorControlsProfileViewModel : AdministratorControlsItemViewModel()
+class AdministratorControlsProfileViewModel(
+  private val routeToProfileListListener: RouteToProfileListListener) : AdministratorControlsItemViewModel() {
```
Comment (rt4914) [inline app/src/main/java/org/oppia/app/administratorcontrols/administratorcontrolsitemviewmodel/AdministratorControlsProfileViewModel.kt]:
```
class AdministratorControlsProfileViewModel(
  private val routeToProfileListListener: RouteToProfileListListener
) : AdministratorControlsItemViewModel() {
```

File: app/src/sharedTest/java/org/oppia/app/administratorcontrols/AdministratorControlsActivityTest.kt [hunk 7]
```diff
@@ -180,13 +182,46 @@ class AdministratorControlsActivityTest {
       )
       onView(withId(R.id.administrator_controls_list)).perform(scrollToPosition<RecyclerView.ViewHolder>(2))
       onView(atPositionOnView(R.id.administrator_controls_list, 2, R.id.auto_update_topic_switch)).check(
+        matches(
```
Comment (rt4914) [inline app/src/sharedTest/java/org/oppia/app/administratorcontrols/AdministratorControlsActivityTest.kt:188]: `@Inject lateinit var profileTestHelper: ProfileTestHelper` is not needed. Remove this.

File: app/src/main/java/org/oppia/app/administratorcontrols/AdministratorControlsActivity.kt [hunk 8]
```diff
@@ -36,4 +37,9 @@ class AdministratorControlsActivity : InjectableAppCompatActivity() {
       return KEY_NAVIGATION_PROFILE_ID
     }
   }
+
+  override fun routeToProfileList() {
+    val intent = Intent(this, ProfileListActivity::class.java)
```
Comment (rt4914) [inline app/src/main/java/org/oppia/app/administratorcontrols/AdministratorControlsActivity.kt]: Instead of creating an intent here. We should create a companion object inside `ProfileListActivity` which will be called from here. Checkout the implementation of such intent transfers in various other activities.

**Review by rt4914 — CHANGES_REQUESTED** [review]
Looks good. Some final nit changes.

File: app/src/main/java/org/oppia/app/administratorcontrols/AdministratorControlsViewModel.kt (hunk 2 above)
Comment (Luffy18346) [reply app/src/main/java/org/oppia/app/administratorcontrols/AdministratorControlsViewModel.kt]: Done

File: app/src/main/java/org/oppia/app/administratorcontrols/AdministratorControlsViewModel.kt (hunk 3 above)
Comment (Luffy18346) [reply app/src/main/java/org/oppia/app/administratorcontrols/AdministratorControlsViewModel.kt]: Done

Comment (Luffy18346) [reply app/src/main/java/org/oppia/app/administratorcontrols/AdministratorControlsViewModel.kt]: Done

File: app/src/main/java/org/oppia/app/administratorcontrols/administratorcontrolsitemviewmodel/AdministratorControlsDownloadPermissionsViewModel.kt (hunk 4 above)
Comment (Luffy18346) [reply app/src/main/java/org/oppia/app/administratorcontrols/administratorcontrolsitemviewmodel/AdministratorControlsDownloadPermissionsViewModel.kt]: Done

File: app/src/main/java/org/oppia/app/administratorcontrols/administratorcontrolsitemviewmodel/AdministratorControlsProfileViewModel.kt (hunk 6 above)
Comment (Luffy18346) [reply app/src/main/java/org/oppia/app/administratorcontrols/administratorcontrolsitemviewmodel/AdministratorControlsProfileViewModel.kt]: Done

File: app/src/main/java/org/oppia/app/administratorcontrols/administratorcontrolsitemviewmodel/AdministratorControlsDownloadPermissionsViewModel.kt (hunk 5 above)
Comment (Luffy18346) [reply app/src/main/java/org/oppia/app/administratorcontrols/administratorcontrolsitemviewmodel/AdministratorControlsDownloadPermissionsViewModel.kt]: Done

Comment (Luffy18346) [reply app/src/main/java/org/oppia/app/administratorcontrols/administratorcontrolsitemviewmodel/AdministratorControlsDownloadPermissionsViewModel.kt]: Done

File: app/src/sharedTest/java/org/oppia/app/administratorcontrols/AdministratorControlsActivityTest.kt (hunk 7 above)
Comment (Luffy18346) [reply app/src/sharedTest/java/org/oppia/app/administratorcontrols/AdministratorControlsActivityTest.kt:188]: ProfileTestHelper is needed here to initialize profiles because some test-cases will fail if the profiles are not initialized before they run.

File: app/src/main/java/org/oppia/app/administratorcontrols/AdministratorControlsActivity.kt (hunk 8 above)
Comment (Luffy18346) [reply app/src/main/java/org/oppia/app/administratorcontrols/AdministratorControlsActivity.kt]: Done. I thought about this but as it was not created before, I thought it should be kept as it is.

File: app/src/sharedTest/java/org/oppia/app/administratorcontrols/AdministratorControlsActivityTest.kt (hunk 7 above)
Comment (Luffy18346) [reply app/src/sharedTest/java/org/oppia/app/administratorcontrols/AdministratorControlsActivityTest.kt:188]: ProfileHelper is needed here to initialize profiles before the test-cases run as there are some test-cases which are dependent on profiles.

File: app/src/main/java/org/oppia/app/settings/profile/ProfileListActivity.kt [hunk 9]
```diff
@@ -18,4 +20,11 @@ class ProfileListActivity : InjectableAppCompatActivity() {
     finish()
     return false
   }
+
+  companion object {
+    /** Returns a new [Intent] to route to [ProfileListActivity] for a specified story. */
```
Comment (rt4914) [inline app/src/main/java/org/oppia/app/settings/profile/ProfileListActivity.kt]: Remove `for a specified story` from the comment.

**Review by rt4914 — APPROVED** [review]
LGTM, one nit change regarding the KDoc

**Comment by rt4914** [comment]
@Luffy18346 Resolve merge conflicts in this PR.

File: app/src/main/java/org/oppia/app/administratorcontrols/AdministratorControlsActivity.kt [hunk 10]
```diff
@@ -41,4 +42,8 @@ class AdministratorControlsActivity : InjectableAppCompatActivity(), RouteToAppV
       return KEY_NAVIGATION_PROFILE_ID
     }
   }
+
```
Comment (rt4914) [inline app/src/main/java/org/oppia/app/administratorcontrols/AdministratorControlsActivity.kt]: The ordering in this is incorrect. Either keep companion on the top or at the bottom of the class

**Review by rt4914 — APPROVED** [review]
One nit change for better code clarity.

File: app/src/main/java/org/oppia/app/administratorcontrols/AdministratorControlsActivity.kt (hunk 10 above)
Comment (Luffy18346) [reply app/src/main/java/org/oppia/app/administratorcontrols/AdministratorControlsActivity.kt]: Done
