### PR TITLE
Fix #5932 and Fix part of #5732: Remove flashback confirmation dialog and update design of Explanation box (4/5)

### LINKED ISSUE #5932: Changes request for Flashback flow in M1 work based on review feedback
This issue tracks the design changes requested during the review of this PR #5910 .

During the review of that PR, the following [feedback](https://github.com/oppia/oppia-android/pull/5910#pullrequestreview-3080868148) was provided:

> Hi @subhajitxyz, leaving a product review as requested:
> 
> - Could you please confirm the text "This doesn't seem right. Let's go back and look at the previous question and answer to understand better." with the UXW team? Ditto for the text in the popup. (I think these might need revision -- one thing to clarify when talking to UXW is that the question being shown may not be the immediately-previous question, so the use of "the" in "the previous question" might be misleading as it implies that there's only one.)
> - In the flashback, could you separate out the explanation section more? Maybe bold the "Explanation" header and leave a bit of space below it.
> - Why is there a "1/2" learner's answer on the bottom right of the flashback, just above "Return to question"? That should not be there.
> - On returning to the original question, the text is wrong (the previous thing should be collapsed and the "Need help?" text should instead be "Now that you have ..." . See last mock here: https://github.com/oppia/design-team/issues/179#issue-2874247813 . This text should also be confirmed with UXW (but I think it looks generally OK). The previous answer/flashback-button should also be hidden.
> - Do not offer the same flashback twice for a question. In general, there should only ever be one flashback experience for a particular question.
> 
> Please fix the above and let me know if you have any questions. Thanks!
> 
> Also, one question -- how are you selecting the question to flashback to?
> 
> _Originally posted by @seanlip in https://github.com/oppia/oppia-android/pull/5910#pullrequestreview-3080868148_
>    

**Requested Design Changes:**

- Remove the Flashback confirmation dialog.
- Thicken the border of the submitted answer box in the Flashback screen.
- Update the design of the Explanation box
- Move the Explanation box below the submitted answer.
- Remove the kebab menu (three dots) in the Flashback screen.
- Change the header of the Flashback screen to: "Example".
- Update the first feedback message on the Flashback screen to: “Let’s review the solution to a previous question:”

**Why this issue was filed:**
To track and implement the requested changes from product/design review feedback ([see review comment](https://github.com/oppia/oppia-android/pull/5910#pullrequestreview-3080868148))

### PR DESCRIPTION
**Pull request by subhajitxyz**
## Explanation
Fixes part of #5732 
Fix #5932 
This PR fixes the M2 work as per this [feedback](https://github.com/oppia/oppia-android/pull/5910#pullrequestreview-3080868148)

Fixes:
- Remove Flahback confirmation dialog
- Thicken the broader of submitted ans box in flashback screen.
- Update design of Explanation Box.
- Move this Explanation box under the submitted answer.
- Remove kebab menu (Three dot) in flashback screen.
- Change header of flashback screen to "Example"
- Change first feedback of flashback screen to “Let’s review the solution to a previous question.” 

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

https://github.com/user-attachments/assets/cf45170e-7b41-472a-a222-68b5c1a55d54

<table align="center">
  <tr>
    <th align="center">Flashback screen</th>
    <th align="center">Normal solution screen</th>
  </tr>
  <tr>
    <td align="center">
      Light
    </td>
    <td align="center">
      Rotate
    </td>
  </tr>
</table>

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- For PRs introducing new UI elements or color changes, both light and dark mode screenshots must be included
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### CODE REVIEW

**Comment by subhajitxyz** [comment]
@adhiamboperes PTAL

**Comment by adhiamboperes** [comment]
@subhajitxyz, please resolve the merge conflicts here.

**Comment by subhajitxyz** [comment]
@adhiamboperes ,PTAL.

File: app/src/main/java/org/oppia/android/app/hintsandsolution/SolutionViewModel.kt [hunk 1]
```diff
@@ -74,6 +76,14 @@ class SolutionViewModel private constructor(
...
   }
 
+  /** Stroke width for the solution box border. */
+  val solutionBoxStrokeWidth by lazy {
+    activity.resources.getDimensionPixelSize(
+      if (isFlashback) R.dimen.flashback_explanation_box_stroke_width
+      else R.dimen.state_solution_box_stroke_width
+    )
+  }
+
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/hintsandsolution/SolutionViewModel.kt]: It is bad practice to pass a context object like an activity to the viewmodel. This binding could have been done inside the presenter instead.

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
This is a great cleanup job @subhajitxyz!

In addition to the inline comment, the issue numbers are not linked correctly so https://github.com/oppia/oppia-android/issues/5932 won't be closed when the PR is merged. pTAL.

File: app/src/main/java/org/oppia/android/app/hintsandsolution/SolutionViewModel.kt (hunk 1 above)
Comment (subhajitxyz) [reply app/src/main/java/org/oppia/android/app/hintsandsolution/SolutionViewModel.kt]: Thanks for the suggestion. I have fixed it and added update Screenshots.

**Comment by subhajitxyz** [comment]
> This is a great cleanup job @subhajitxyz!
> 
> In addition to the inline comment, the issue numbers are not linked correctly so #5932 won't be closed when the PR is merged. pTAL.

Updated it.

**Comment by subhajitxyz** [comment]
Hi @manas-yu , sharing the lint issue here. As per our discussion on chat, I am trying by removing it from the Enum and also from the issueIdMapping in the exemption proto.
```
 Redundant Exemptions: 1
Total Issues: 1

If you need additional help to resolve an issue, see https://googlesamples.github.io/android-custom-lint-rules/checks/severity.md.html

================================================================================
FILE: scripts/assets/android_lint_exemptions.textproto (1 issue)
================================================================================

Issue 1 of 1: REDUNDANT_EXEMPTION
  Severity: Redundant Exemption
  Line: 1886
  Error Line: lint_issue_id: UNKNOWN_ID_IN_LAYOUT
  Message: Redundant exemption found. Please remove it from the file.
  Explanation:
Exception in thread "main" java.lang.IllegalStateException: ANDROID LINT CHECK FAILED
	at org.oppia.android.scripts.lint.LintAnalysisReporter.printFinalResult(LintAnalysisReporter.kt:768)
    In app/src/main/res/layout/solution_summary.xml the
    UNKNOWN_ID_IN_LAYOUT exemption is redundant and can be removed
    since there are no corresponding lint issues.

============================================================
UNUSED ENUM MAPPINGS DETECTED:
The following issue IDs are defined in issueIdMapping but no corresponding lint issues were found.
Please remove them from the LintIssueId enum and issueIdMapping:

  - UnknownIdInLayout -> UNKNOWN_ID_IN_LAYOUT

	at org.oppia.android.scripts.lint.LintAnalysisReporter.printLintReport(LintAnalysisReporter.kt:488)
	at org.oppia.android.scripts.lint.AndroidLintRunner.reportLintIssues(AndroidLintRunner.kt:258)
	at org.oppia.android.scripts.lint.AndroidLintRunner.runLint(AndroidLintRunner.kt:203)
	at org.oppia.android.scripts.lint.AndroidLintAnalyzer.runAnalysis(AndroidLintRunner.kt:130)
	at org.oppia.android.scripts.lint.AndroidLintRunnerKt.main(AndroidLintRunner.kt:80)
Error: Process completed with exit code 1.
```

**Comment by manas-yu** [comment]
Hi @subhajitxyz the CI seems to pass. Let me know if there is anything else. Thanks.

**Comment by subhajitxyz** [comment]
@adhiamboperes , PTAL.

**Review by adhiamboperes — APPROVED** [review]
LGTM, thanks @subhajitxyz.
