### PR TITLE
Fix #1252: When navigating to an earlier state, hints & solutions unexpectedly show up

### LINKED ISSUE #1252: When navigating to an earlier state, hints & solutions unexpectedly show up
Repro:

1) Navigate to a state
2) Wait for a hint bulb to appear (e.g. wait 60 seconds)
3) Navigate to a previous state

Expected: the bulb should disappear OR show the previous state's hints, if any

Actual: the bulb still has an indicator for a new hint, and when pressing it opens an empty hints & solutions list. Navigating back to the latest state causes the correct hints to show up.

### PR DESCRIPTION
**Pull request by anandwana001**
## Explanation

Fix #1252 

### Test case failed without fix
Screenshot 2020-08-20 at 20 45 19

### Test case pass with fix
Screenshot 2020-08-20 at 20 07 33

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Review by rt4914 — APPROVED** [review]
LGTM, thanks

**Comment by anandwana001** [comment]
> LGTM, thanks

Thanks for review :)

File: app/src/main/java/org/oppia/app/player/state/StateFragmentPresenter.kt [hunk 1]
```diff
@@ -151,9 +152,20 @@ class StateFragmentPresenter @Inject constructor(
     moveToNextState()
   }
 
-  fun onNextButtonClicked() = moveToNextState()
+  fun onNextButtonClicked() {
+    val item = hintBulbVibisilityStack.lastOrNull()
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/app/player/state/StateFragmentPresenter.kt]: Please add tests to verify the new functionality is correct (specifically that the test fails without the fix & passes with it).

File: app/src/main/java/org/oppia/app/player/state/StateFragmentPresenter.kt [hunk 2]
```diff
@@ -74,6 +74,7 @@ class StateFragmentPresenter @Inject constructor(
   private lateinit var currentStateName: String
   private lateinit var binding: StateFragmentBinding
   private lateinit var recyclerViewAdapter: RecyclerView.Adapter<*>
+  private val hintBulbVibisilityStack: MutableList<Boolean> = mutableListOf()
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/app/player/state/StateFragmentPresenter.kt]: I wonder if we can simplify this. Do we ever need to show hints or a solution for previous states? If not, rather than tracking each state's hint visibility status, all we need to do is only track the current state's.

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @anandwana001. Left some thoughts.

File: app/src/main/java/org/oppia/app/player/state/StateFragmentPresenter.kt (hunk 2 above)
Comment (anandwana001) [reply app/src/main/java/org/oppia/app/player/state/StateFragmentPresenter.kt]: Done

File: app/src/main/java/org/oppia/app/player/state/StateFragmentPresenter.kt (hunk 1 above)
Comment (anandwana001) [reply app/src/main/java/org/oppia/app/player/state/StateFragmentPresenter.kt]: Done

File: app/src/test/java/org/oppia/app/player/state/StateFragmentLocalTest.kt [hunk 3]
```diff
@@ -280,6 +287,34 @@ class StateFragmentLocalTest {
...
+    launchForExploration(FRACTIONS_EXPLORATION_ID_1).use {
+      startPlayingExploration()
+      playThroughState1()
+      submitTwoWrongAnswers()
+      onView(withId(R.id.previous_state_navigation_button)).perform(click())
+      testCoroutineDispatchers.runCurrent()
+      onView(withId(R.id.state_recycler_view)).perform(scrollToViewType(NEXT_NAVIGATION_BUTTON))
+      onView(withId(R.id.next_state_navigation_button)).perform(click())
+      testCoroutineDispatchers.runCurrent()
+      onView(withId(R.id.hint_bulb)).check(matches(isDisplayed()))
```
Comment (BenHenning) [inline app/src/test/java/org/oppia/app/player/state/StateFragmentLocalTest.kt]: This doesn’t seem right. Why is the hint visible in the next state? Nothing has been done by the user to trigger that.

File: app/src/test/java/org/oppia/app/player/state/StateFragmentLocalTest.kt [hunk 4]
```diff
@@ -280,6 +287,34 @@ class StateFragmentLocalTest {
     }
   }
 
+  @Test
+  fun testStateFragment_submitTwoWrongAnswers_hintAvailable_prevState_hintNotAvailable() {
```
Comment (BenHenning) [inline app/src/test/java/org/oppia/app/player/state/StateFragmentLocalTest.kt:356]: Does this fail without the fix? Also, is this the right case? I thought we needed a case when a previous state can show the hint bulb, then we navigate back to it. It shouldn’t show the hint bulb again. Can you add a test case for that, too?

File: app/src/main/java/org/oppia/app/player/state/StateFragmentPresenter.kt [hunk 5]
```diff
@@ -191,10 +190,12 @@ class StateFragmentPresenter @Inject constructor(
           helpIndex.indexTypeCase == HelpIndex.IndexTypeCase.SHOW_SOLUTION
         viewModel.setHintOpenedAndUnRevealedVisibility(true)
         viewModel.setHintBulbVisibility(true)
+        currentStateNameOfVisibleHint = currentStateName
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/app/player/state/StateFragmentPresenter.kt]: Is it possible to solve this in the assembler? Otherwise this needs to be duplicated for both states and questions.

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks Akshay. This seems much simpler. I’m wondering if it works in all relevant cases though (see my comments on the tests). Also, we should do this in the assembler so that it’s fixed for both questions and explorations.

File: app/src/test/java/org/oppia/app/player/state/StateFragmentLocalTest.kt (hunk 3 above)
Comment (anandwana001) [reply app/src/test/java/org/oppia/app/player/state/StateFragmentLocalTest.kt]: What this test is doing is:
1. The user submits 2 wrong answer
2. Hint bulb is visible
3. A user going to prev state - where hint bulb is not visible (tested on second test cases in this or already)
4. Coming back to current state where user submit two wrong answer - so hint bulb should be visible again.

File: app/src/test/java/org/oppia/app/player/state/StateFragmentLocalTest.kt (hunk 4 above)
Comment (anandwana001) [reply app/src/test/java/org/oppia/app/player/state/StateFragmentLocalTest.kt:356]: The use case we have is:
1. The user submit wrong answers
2. Hint bulb visible
3. Going to prev state
4. Hint bulb should not visible
5. Back to the current state
6. Hint bulb should visible again

File: app/src/main/java/org/oppia/app/player/state/StateFragmentPresenter.kt (hunk 5 above)
Comment (anandwana001) [reply app/src/main/java/org/oppia/app/player/state/StateFragmentPresenter.kt]: Yes, I tried this approach too. What I am finding difficulty here is when I am in a current state, the bulb is visible, now I move to the previous state and come back to the current state, it's a bit hard to just make the build visible. 
When coming back to the current state where prev the bulb is visible, I had to manage the last showed hint state and also start the new state like scheduling for next hints. 

Also, in question player, we don't have next or previous button so we don't need this hiding/showing facility of a bulb.

**Comment by anandwana001** [comment]
A major thing to handle is:
1. Hint bulb visible
2. Go to the previous state which is a completed state (hide hint bulb)
3. Come back to the previous state which was the last state where hint bulb is visible 
4. **Make hint bulb visible again** (as per the Hint Handler the bulb icon while be shown after schedule completes or two wrong answers submitted)

### Approaches

1. Use a new function in `ShowHintAvailabilityListener` to manage the visibility of the bulb while transitioning between completed and pending states. Always hide the bulb when moving to a completed state. 

If in future we add more features like Question/State, we just have to override this method and set visibility in ViewModel, all other points will be taken care of by Assembler itself.

Without introducing a new function in the listener, I get blocked on how to make a hint bulb visible again when a user comes back again to the current state (current state -> hint bulb visible -> prev state -> current state -> show hint bulb again).

File: app/src/test/java/org/oppia/app/player/state/StateFragmentLocalTest.kt (hunk 3 above)
Comment (BenHenning) [reply app/src/test/java/org/oppia/app/player/state/StateFragmentLocalTest.kt]: I must have read this & the previous test incorrectly. This does look correct--thanks!

File: app/src/test/java/org/oppia/app/player/state/StateFragmentLocalTest.kt (hunk 4 above)
Comment (BenHenning) [reply app/src/test/java/org/oppia/app/player/state/StateFragmentLocalTest.kt:356]: Thanks--this does look correct.

File: app/src/main/java/org/oppia/app/player/state/StatePlayerRecyclerViewAssembler.kt [hunk 6]
```diff
@@ -1212,6 +1213,7 @@ class StatePlayerRecyclerViewAssembler private constructor(
     private var trackedWrongAnswerCount = 0
     private var previousHelpIndex: HelpIndex = HelpIndex.getDefaultInstance()
     private var hintSequenceNumber = 0
+    private var ishintVisibile = false
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/app/player/state/StatePlayerRecyclerViewAssembler.kt]: ``isHintVisible``

File: app/src/main/java/org/oppia/app/player/state/StatePlayerRecyclerViewAssembler.kt [hunk 7]
```diff
@@ -1221,6 +1223,13 @@ class StatePlayerRecyclerViewAssembler private constructor(
       // reset to 0 to ensure that all previous hint tasks are cancelled, and new tasks can be
       // scheduled without overlapping with past sequence numbers.
       hintSequenceNumber++
+      ishintVisibile = false
+    }
+
+    fun hideHint() {
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/app/player/state/StatePlayerRecyclerViewAssembler.kt:1230]: Add KDoc since this is part of the API of this helper class.

File: app/src/main/java/org/oppia/app/player/state/StatePlayerRecyclerViewAssembler.kt [hunk 8]
```diff
@@ -1221,6 +1223,13 @@ class StatePlayerRecyclerViewAssembler private constructor(
...
+      (fragment as ShowHintAvailabilityListener).hintVisibilityBetweenState(
+        /* hintVisibility= */ false
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/app/player/state/StatePlayerRecyclerViewAssembler.kt]:
```suggestion
        hintVisibility = false
```

Ditto below.

File: app/src/main/java/org/oppia/app/player/state/StatePlayerRecyclerViewAssembler.kt [hunk 9]
```diff
@@ -1325,6 +1340,7 @@ class StatePlayerRecyclerViewAssembler private constructor(
           // becomes null such as in the case of the solution becoming available).
           (fragment as ShowHintAvailabilityListener).onHintAvailable(helpIndexToShow)
           previousHelpIndex = helpIndexToShow
+          ishintVisibile = true
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/app/player/state/StatePlayerRecyclerViewAssembler.kt]: I think mechanically this solution looks good, but could we possibly leverage the existing ``ShowHintAvailabilityListener``? I think calling ``onHintAvailable`` with a default instance of ``HelpIndex`` will lead to the bulb being hidden. Unless I'm mistaken, it might simplify the current solution quite a bit.

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @anandwana001 --mechanically this LGTM, but I think it can  be simplified further. PTAL.

File: app/src/main/java/org/oppia/app/player/state/StateFragmentPresenter.kt (hunk 5 above)
Comment (BenHenning) [reply app/src/main/java/org/oppia/app/player/state/StateFragmentPresenter.kt]: Good point re: questions.

Are you still running into issues or is the current solution working?

**Comment by BenHenning** [comment]
@anandwana001 is this solution complete? It wasn't clear to me from your comment above.

File: app/src/main/java/org/oppia/app/player/state/StatePlayerRecyclerViewAssembler.kt (hunk 9 above)
Comment (anandwana001) [reply app/src/main/java/org/oppia/app/player/state/StatePlayerRecyclerViewAssembler.kt]: Yes, the default instance of `HelpIndex` does hide the bulb icon, but we need to show it again if a user comes back to the current state where the bulb was previously visible. 

1. Hint bulb visible either by submitting 2 wrong answers or after a period of time
2. Go to the previous state which is a completed state (hide hint bulb)
3. Come back to the previous state which was the last state where hint bulb is visible
4. Make hint bulb visible again

Comment (anandwana001) [reply app/src/main/java/org/oppia/app/player/state/StatePlayerRecyclerViewAssembler.kt]: In order to make it visible again, we have to trigger bulb visibility which statefragment and questionplayer view model are handling.

Comment (BenHenning) [reply app/src/main/java/org/oppia/app/player/state/StatePlayerRecyclerViewAssembler.kt]: Can we call maybeScheduleShowHint in the assembler when switching from a completed to a pending state?

Comment (anandwana001) [reply app/src/main/java/org/oppia/app/player/state/StatePlayerRecyclerViewAssembler.kt]: Yes, it is already calling and that's where I am doing the checking if the bulb icon was previously visible or not. 

```
 if (ishintVisibile) {
        (fragment as ShowHintAvailabilityListener).hintVisibilityBetweenState(
          /* hintVisibility= */ true
        )
      }
```

File: app/src/main/java/org/oppia/app/player/state/StatePlayerRecyclerViewAssembler.kt (hunk 6 above)
Comment (anandwana001) [reply app/src/main/java/org/oppia/app/player/state/StatePlayerRecyclerViewAssembler.kt]: Done

File: app/src/main/java/org/oppia/app/player/state/StatePlayerRecyclerViewAssembler.kt (hunk 7 above)
Comment (anandwana001) [reply app/src/main/java/org/oppia/app/player/state/StatePlayerRecyclerViewAssembler.kt:1230]: Done

File: app/src/main/java/org/oppia/app/player/state/StatePlayerRecyclerViewAssembler.kt (hunk 8 above)
Comment (anandwana001) [reply app/src/main/java/org/oppia/app/player/state/StatePlayerRecyclerViewAssembler.kt]: Done

File: app/src/main/java/org/oppia/app/player/state/StatePlayerRecyclerViewAssembler.kt (hunk 9 above)
Comment (anandwana001) [reply app/src/main/java/org/oppia/app/player/state/StatePlayerRecyclerViewAssembler.kt]: Done

File: app/src/main/java/org/oppia/app/player/state/StatePlayerRecyclerViewAssembler.kt [hunk 10]
```diff
@@ -1221,6 +1223,14 @@ class StatePlayerRecyclerViewAssembler private constructor(
       // reset to 0 to ensure that all previous hint tasks are cancelled, and new tasks can be
       // scheduled without overlapping with past sequence numbers.
       hintSequenceNumber++
+      isHintVisible = false
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/app/player/state/StatePlayerRecyclerViewAssembler.kt]: Perhaps: ``isHintVisibleInLatestState`` to be super explicit about this.

File: app/src/main/java/org/oppia/app/player/state/StatePlayerRecyclerViewAssembler.kt [hunk 11]
```diff
@@ -1233,6 +1243,18 @@ class StatePlayerRecyclerViewAssembler private constructor(
         return
       }
 
+      if (isHintVisible) {
+        if (state.interaction.hintList[previousHelpIndex.hintIndex].hintIsRevealed) {
+          (fragment as ShowHintAvailabilityListener).onHintAvailable(
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/app/player/state/StatePlayerRecyclerViewAssembler.kt:1253]: This doesn't seem quite right--what if the previous help index is 0 but there are 3 hints & a solution? We don't want to show everything again.

Why isn't ``onHintAvailable(previousHelpIndex)`` sufficient?

File: app/src/test/java/org/oppia/app/player/state/StateFragmentLocalTest.kt [hunk 12]
```diff
@@ -50,6 +50,7 @@ import org.oppia.app.player.state.itemviewmodel.StateItemViewModel
 import org.oppia.app.player.state.itemviewmodel.StateItemViewModel.ViewType.CONTINUE_NAVIGATION_BUTTON
 import org.oppia.app.player.state.itemviewmodel.StateItemViewModel.ViewType.FRACTION_INPUT_INTERACTION
 import org.oppia.app.player.state.itemviewmodel.StateItemViewModel.ViewType.NEXT_NAVIGATION_BUTTON
+import org.oppia.app.player.state.itemviewmodel.StateItemViewModel.ViewType.PREVIOUS_RESPONSES_HEADER
```
Comment (BenHenning) [inline app/src/test/java/org/oppia/app/player/state/StateFragmentLocalTest.kt:54]: Why is this needed now?

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @anandwana001. Forgot to submit my comments earlier today, PTAL.

File: app/src/main/java/org/oppia/app/player/state/StatePlayerRecyclerViewAssembler.kt (hunk 11 above)
Comment (anandwana001) [reply app/src/main/java/org/oppia/app/player/state/StatePlayerRecyclerViewAssembler.kt:1253]: with `onHintAvailable(previousHelpIndex)` we cannot manage if user has revealed the hint or not and do we have to show dot icon or not. If we use `previousHelpIndex` and user click on hint reveal and if user transit between states and coming back to current state will show the dot icon again as the `previousHelpIndex` has an index of `HINT_INDEX` which will make the dot icon visible as per the onHintAvailable implementation.

File: app/src/test/java/org/oppia/app/player/state/StateFragmentLocalTest.kt (hunk 12 above)
Comment (anandwana001) [reply app/src/test/java/org/oppia/app/player/state/StateFragmentLocalTest.kt:54]: We need `NEXT_NAVIGATION_BUTTON` for test `testStateFragment_submitTwoWrongAnswers_prevState_nextState_hintAvailable`.
`PREVIOUS_RESPONSES_HEADER` is used by other functions not related to this PR.

Comment (anandwana001) [reply app/src/test/java/org/oppia/app/player/state/StateFragmentLocalTest.kt:54]: This `testStateFragment_submitTwoWrongAnswers_prevState_nextState_hintAvailable ` test is basically

1. submitTwoWrongAnswers
2. Go to the previous state
3. scroll to `NEXT_NAVIGATION_BUTTON `
4. click on next
5. check if bulb icon is visible or not

File: app/src/main/java/org/oppia/app/player/state/StatePlayerRecyclerViewAssembler.kt (hunk 10 above)
Comment (anandwana001) [reply app/src/main/java/org/oppia/app/player/state/StatePlayerRecyclerViewAssembler.kt]: Done

File: app/src/test/java/org/oppia/app/player/state/StateFragmentLocalTest.kt (hunk 12 above)
Comment (BenHenning) [reply app/src/test/java/org/oppia/app/player/state/StateFragmentLocalTest.kt:54]: Ah, sorry. This sometimes happens since I view diffs between reviews. That can include changes from develop that are unrelated, like this.

File: app/src/main/java/org/oppia/app/player/state/StatePlayerRecyclerViewAssembler.kt (hunk 11 above)
Comment (BenHenning) [reply app/src/main/java/org/oppia/app/player/state/StatePlayerRecyclerViewAssembler.kt:1253]: Sorry, I don't quite see how that relates to my question. Per the current implementation, it seems like navigating back to the current state will end up revealing all hints, not just the ones previously hint. We do know if the user revealed the hint--that's what hintIsRevealed in EphemeralState represents. We also know the latest index shared with the user--all of that information is available to this class.

I think the user experience should be: previous states, never show hints again even if they were previously shown. Current state: do not change which hints were revealed or the badge status if navigating to/from the current state.

**Review by BenHenning — CHANGES_REQUESTED** [review]

**Comment by BenHenning** [comment]
Also @anandwana001 please don't forget to assign the PR if you need follow-up input on it, otherwise it's easy to lose track of.

**Comment by anandwana001** [comment]
> Also @anandwana001 please don't forget to assign the PR if you need follow-up input on it, otherwise it's easy to lose track of.

I was thinking to take this on today's meeting agenda so only put the comments.

File: app/src/main/java/org/oppia/app/player/state/StatePlayerRecyclerViewAssembler.kt (hunk 11 above)
Comment (anandwana001) [reply app/src/main/java/org/oppia/app/player/state/StatePlayerRecyclerViewAssembler.kt:1253]: Ah, I think we are misunderstanding the function setEverythingRevealed to true. 
This function is just helping us with the dot icon visibility. 

After running this implementation with states like where there is only 1 hint and where there are 4 hints and 1 solution, it works fine and also I did double check with rajat to run this implementation. 

I will demo it in meeting and see if we can have some other edge cases which cam fail this implementation.

Comment (BenHenning) [reply app/src/main/java/org/oppia/app/player/state/StatePlayerRecyclerViewAssembler.kt:1253]: Thanks for explaining this in more depth.

Two thoughts:
1. Please add a set of line comments above this whole if block explaining the logic in more depth
2. Please make sure there are tests for each of the if conditions possible here (I count at least 3 scenarios)

**Review by BenHenning — CHANGES_REQUESTED** [review]

**Comment by anandwana001** [comment]
Add below test after merging #1748 

```
@Test
fun testStateFragment_revealFirstHint_prevState_currentState_checkFirstHintRevealed() {
  launchForExploration(FRACTIONS_EXPLORATION_ID_1).use {
    startPlayingExploration()
    playThroughState1()

    produceAndViewFirstHint()

   moveToPreviousAndBackToCurrentState()

    openHintsAndSolutionsDialog()
    onView(withId(R.id.hints_and_solution_recycler_view))
      .inRoot(isDialog())
      .perform(scrollToPosition<ViewHolder>(0))
    onView(
      RecyclerViewMatcher.atPositionOnView(
        R.id.hints_and_solution_recycler_view, 0, R.id.hint_summary_container
      )
    ).perform(click())
    testCoroutineDispatchers.runCurrent()
    onView(withText("In a fraction, the pieces representing the denominator must be equal"))
      .inRoot(isDialog()).check(matches(isDisplayed()))
  }
}
```

File: app/src/main/java/org/oppia/app/player/state/StatePlayerRecyclerViewAssembler.kt (hunk 11 above)
Comment (anandwana001) [reply app/src/main/java/org/oppia/app/player/state/StatePlayerRecyclerViewAssembler.kt:1253]: Done

**Review by BenHenning — APPROVED** [review]
Thanks @anandwana001!
