### PR TITLE
Fixes part of #4272: Added Tests for EventLogSubject.

### LINKED ISSUE #4272: Add tests for EventLogSubject
#4267 introduces a new custom Truth test subject: EventLogSubject. It would be advantageous to add thorough tests for this to ensure that:
- Each of the subject & comparator methods correctly allow users to test specific properties of the protos each subject helps verify
- Each of the subject & comparator methods are verified to fail when expected (i.e. when used with an incompatible proto property) with the correct failure reason being verified

See #4097 for a similar issue.

## Pending testcases:

For context tests, we should test for 4 outcomes:
1. The context being present and matching
 `testEventLog_whenContextIsInfoTab_passes` using `EventLogSubject.assertThat(eventLog).hasOpenInfoTabContext()`

2. Subject has context with ceratin properties
`_returnsTopicContextSubject`  

```kotlin
 val eventLog = EventLog.newBuilder()
    .setContext(
      EventLog.Context.newBuilder()
        .setOpenInfoTab(
          TopicContext.newBuilder().setTopicId("info_tab_topic")
        )
    )
    .build()

  val subject = EventLogSubject.assertThat(eventLog)
    .hasOpenInfoTabContextThat()

subject.hasTopicIdThat().isEqualTo("info_tab_topic")
```

3. Subject has context with ceratin properties, and executes a block.
`_executesBlockWithCorrectSubject`

  ```kotlin
val eventLog = EventLog.newBuilder()
    .setContext(
      EventLog.Context.newBuilder()
        .setOpenInfoTab(TopicContext.newBuilder().setTopicId("test_topic"))
    )
    .build()

  EventLogSubject.assertThat(eventLog)
    .hasOpenInfoTabContextThat {
      hasTopicIdThat().isEqualTo("test_topic")
    }
```
4. A failure case when  the subject under test does not match the input.

These are necessary because every context subject has these 3 functions, and this will increase the code coverage of the class. 

(1) and (4) have already been covered in #5678

### PR DESCRIPTION
**Pull request by theayushyadav11**
Fixes part of #4272: 

This pull request introduces new tests for the `EventLogSubject` class in the `Oppia` Android project. The main changes include the addition of the `EventLogSubjectTest` class and the corresponding build configuration updates.

### New Tests for `EventLogSubject`:

* [`testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt`](diffhunk://#diff-346c08638dcbe5a2f3c1911f47813e71dcd5de2c528f19bdb326555aa9767712R1-R298): Added a comprehensive set of tests for the `EventLogSubject` class, covering various scenarios such as timestamp matching, priority checks, profile ID validation, and language selection verification.

### Build Configuration Updates:

* [`testing/src/test/java/org/oppia/android/testing/logging/BUILD.bazel`](diffhunk://#diff-c0153ba759e957520c4c5d5eb6221aab875f577074f14fe0f670cda8761a8f34R60-R79): Added a new build target for `EventLogSubjectTest`, including necessary dependencies for running the tests.

### Code Cleanup:

* [`testing/src/main/java/org/oppia/android/testing/logging/EventLogSubject.kt`](diffhunk://#diff-38666dc35e58390379b0604e36be3ee798c70f4d4d2070623a602a6023fec12aL73-L74): Removed outdated TODO comments related to adding tests for the `EventLogSubject` class.

All tests has been added succesfully.

#### Screenshot of all the passing tests:
image

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

### CODE REVIEW

**Comment by theayushyadav11** [comment]
Hi @adhiamboperes PTAL, as mentioned in the PR description these tests are not complete , once reviewed I would further add the remaining tests as `EventLogSubject` has the extensive scope.

File: testing/src/main/java/org/oppia/android/testing/logging/EventLogSubject.kt
Comment (adhiamboperes) [inline testing/src/main/java/org/oppia/android/testing/logging/EventLogSubject.kt:1]: Please remove this file from `test_file_exemptions.textproto` so code coverage analysis can run.

File: testing/src/main/java/org/oppia/android/testing/logging/EventLogSubject.kt [hunk 1]
```diff
@@ -70,8 +70,6 @@ import org.oppia.android.app.model.UserTypeAnswer
 import org.oppia.android.app.model.WrittenTranslationLanguageSelection
 import org.oppia.android.testing.logging.EventLogSubject.Companion.assertThat
 
-// TODO(#4272): Add tests for this class.
```
Comment (adhiamboperes) [inline testing/src/main/java/org/oppia/android/testing/logging/EventLogSubject.kt:73]: Please do a global search and remove any other occurrances of this `TODO(#4272)`.

File: testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt [hunk 2]
```diff
@@ -0,0 +1,298 @@
...
+import org.oppia.android.app.model.EventLog.ExplorationContext
+import org.oppia.android.app.model.EventLog.TopicContext
+import org.oppia.android.app.model.OppiaLanguage
+import org.oppia.android.app.model.ProfileId
+import org.oppia.android.app.model.WrittenTranslationLanguageSelection
+
+@RunWith(JUnit4::class)
+class EventLogSubjectTest {
+  @Test
+  fun testHasTimeStamp_withTimeStamp_matchesTimeStamp() {
```
Comment (adhiamboperes) [inline testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt]: All the tests in this class needs to be renamed to follow our preferred format: https://github.com/oppia/oppia-android/wiki/Oppia-Android-Testing#guidelines-for-testing, e.g. `testEventLogSubject_matchesCorrectTimestamp`
`testEventLogSubject_failsOnUnmatchingTimestamp`

File: testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt [hunk 3]
```diff
@@ -0,0 +1,298 @@
...
+  @Test(expected = AssertionError::class)
+  fun testHasTimeStamp_withDifferentTimeStamp_fails() {
+    val eventLog = EventLog.newBuilder()
+      .setTimestamp(123456789)
+      .build()
+
+    EventLogSubject.assertThat(eventLog)
+      .hasTimestampThat()
+      .isEqualTo(987654321)
+  }
```
Comment (adhiamboperes) [inline testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt]: We don't use this pattern when testing. Prefer something likee:
```suggestion
  @Test
  fun testEventLogSubject_failsOnUnmatchingTimestamp() {
    val eventLog = EventLog.newBuilder()
      .setTimestamp(123456789)
      .build()

 assertThrows<AssertionError>() {
      EventLogSubject.assertThat(eventLog)
      .hasTimestampThat()
      .isEqualTo(987654321)
    }   
  }
```

File: testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt [hunk 4]
```diff
@@ -0,0 +1,298 @@
...
+    val eventLog = EventLog.newBuilder()
+      .setPriority(EventLog.Priority.ESSENTIAL)
+      .build()
+
+    EventLogSubject.assertThat(eventLog)
+      .isEssentialPriority()
+  }
+
+  @Test(expected = AssertionError::class)
+  fun testIsEssentialPriority_withDifferentPriority_fails() {
```
Comment (adhiamboperes) [inline testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt]:
```suggestion
  fun testEventLogSubject_matchEssentialPriorityWithDifferentPriority_fails() {
```

File: testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt [hunk 5]
```diff
@@ -0,0 +1,298 @@
...
+    val eventLog = EventLog.newBuilder()
+      .setPriority(EventLog.Priority.ESSENTIAL)
+      .build()
+
+    EventLogSubject.assertThat(eventLog)
+      .isOptionalPriority()
+  }
+
+  @Test
+  fun testHasNoProfileId_withNoProfileId() {
```
Comment (adhiamboperes) [inline testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt]:
```suggestion
  fun testEventLogSubject_eventWithNoProfileId_returnsNoProfileId() {
```
Ditto test below

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @theayushyadav11!

My main suggestion is to change how the tests are named to reflect `classUnderTest_condition1BeingTested_condition2ifApplicable_expectedOutcome()`

Please rename these tests before adding more so that you can get a good grasp of the pattern.

File: testing/src/test/java/org/oppia/android/testing/logging/BUILD.bazel [hunk 6]
```diff
@@ -57,3 +57,21 @@ oppia_android_test(
...
+
+oppia_android_test(
+    name = "EventLogSubjectTest",
+    srcs = ["EventLogSubjectTest.kt"],
+    custom_package = "org.oppia.android.testing.logging",
+    test_class = "org.oppia.android.testing.logging.EventLogSubjectTest",
+    test_manifest = "//testing:test_manifest",
+    deps = [
+        "//:dagger",
+        "//testing",
```
Comment (adhiamboperes) [inline testing/src/test/java/org/oppia/android/testing/logging/BUILD.bazel]: Are these two deps really required here?

**Comment by theayushyadav11** [comment]
Thanks @adhiamboperes for the review, I'll implement the changes as required.

**Comment by theayushyadav11** [comment]
Hi @adhiamboperes, PTAL! Let me know if I should continue writing tests for other methods or if you have any other suggestions. Thanks!

File: testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt [hunk 7]
```diff
@@ -123,14 +130,15 @@ class EventLogSubjectTest {
...
+    assertThrows(AssertionError::class.java) {
+      EventLogSubject.assertThat(eventLog)
+        .hasProfileIdThat()
+        .isEqualTo(differentProfileId)
+    }
   }
 
   @Test
-  fun testHasAppLanguageSelectionThat_withAppLanguageSelection_matchesAppLanguageSelection() {
+  fun testEventLogSubject_hasSameAppLanguageSelection() {
```
Comment (adhiamboperes) [inline testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt]:
```suggestion
  fun testEventLogSubject_matchesAppLanguageSelection() {
```

File: testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt [hunk 8]
```diff
@@ -216,14 +226,15 @@ class EventLogSubjectTest {
...
+    assertThrows(AssertionError::class.java) {
+      EventLogSubject.assertThat(eventLog)
+        .hasAudioTranslationLanguageSelectionThat()
+        .isEqualTo(differentSelection)
+    }
   }
 
   @Test
-  fun testHasOpenExplorationActivityContext_withMatchingContext_passes() {
+  fun testEventLogSubject_hasOpenExplorationActivityContextPresent() {
```
Comment (adhiamboperes) [inline testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt]: For this and below, remove redundant verb.
```suggestion
  fun testEventLogSubject_hasOpenExplorationActivityContext() {
```

File: testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt [hunk 9]
```diff
@@ -235,17 +246,18 @@ class EventLogSubjectTest {
       .hasOpenExplorationActivityContext()
   }
 
-  @Test(expected = AssertionError::class)
-  fun testHasOpenExplorationActivityContext_withDifferentContext_fails() {
+  @Test
+  fun testEventLogSubject_openExplorationActivityContextAbsent_fails() {
```
Comment (adhiamboperes) [inline testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt]: For this and below, rename:
```suggestion
  fun testEventLogSubject_missingExplorationActivityContext_fails() {
```

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
@theayushyadav11, I have left a few corrections but please feel free to continue adding tests.

**Comment by theayushyadav11** [comment]
Hi @adhiamboperes, I have added all the tests for the `EventLogSubject`  PTAL  and please tell me if any more changes are needed. Thanks!

**Comment by theayushyadav11** [comment]
Hi @adhiamboperes , this PR is ready for review PTAL and please suggest the needed changes in the code.
Thanks!

**Comment by theayushyadav11** [comment]
Hi @adhiamboperes , this PR is ready for review PTAL and please suggest the needed changes in the code.
Thanks!

File: testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt [hunk 10]
```diff
@@ -0,0 +1,3939 @@
...
+
+    assertThrows(AssertionError::class.java) {
+      EventLogSubject.assertThat(eventLog)
+        .hasTimestampThat()
+        .isEqualTo(987654321)
+    }
+  }
+
+  @Test
+  fun testEventLogSubject_matchesPriorityEssential() {
```
Comment (adhiamboperes) [inline testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt]:
```suggestion
  fun testEventLogSubject_withPriorityEssential_passes() {
```

File: testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt [hunk 11]
```diff
@@ -0,0 +1,3939 @@
...
+      .setPriority(EventLog.Priority.OPTIONAL)
+      .build()
+    assertThrows(AssertionError::class.java) {
+      EventLogSubject.assertThat(eventLog)
+        .isEssentialPriority()
+    }
+  }
+
+  @Test
+  fun testEventLogSubject_matchesPriorityOptional() {
```
Comment (adhiamboperes) [inline testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt]:
```suggestion
  fun testEventLogSubject_withPriorityOptional_passes() {
```

File: testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt [hunk 12]
```diff
@@ -0,0 +1,3939 @@
...
+      .setProfileId(profileId)
+      .build()
+    assertThrows(AssertionError::class.java) {
+      EventLogSubject.assertThat(eventLog)
+        .hasNoProfileId()
+    }
+  }
+
+  @Test
+  fun testEventLogSubject_matchesProfileIdPresent() {
```
Comment (adhiamboperes) [inline testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt]:
```suggestion
  fun testHasProfileIdThat_eventWithProfileId_returnsProfileIdSubject {
```

File: testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt [hunk 13]
```diff
@@ -0,0 +1,3939 @@
...
+      .build()
+    assertThrows(AssertionError::class.java) {
+      EventLogSubject.assertThat(eventLog)
+        .hasProfileIdThat()
+        .isEqualTo(differentProfileId)
+    }
+  }
+
+  @Test
+  fun testEventLogSubject_matchesAppLanguageSelection() {
```
Comment (adhiamboperes) [inline testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt]:
```suggestion
  fun testEventLogSubject_eventWithAppLanguageSelection_returnsAppLanguageSelectionSubject() {
```

File: testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt [hunk 14]
```diff
@@ -0,0 +1,3939 @@
...
+      .build()
+    assertThrows(AssertionError::class.java) {
+      EventLogSubject.assertThat(eventLog)
+        .hasAppLanguageSelectionThat()
+        .isEqualTo(differentAppLanguageSelection)
+    }
+  }
+
+  @Test
+  fun testEventLogSubject_matchesWrittenTranslationLanguageSelection() {
```
Comment (adhiamboperes) [inline testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt]:
```suggestion
  fun testHasWrittenTranslationLanguageSelectionThat_eventWithWrittenTranslationLanguageSelection_returnsWrittenTranslationLanguageSelectionSubject() {
```

File: testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt [hunk 15]
```diff
@@ -0,0 +1,3939 @@
...
+      .build()
+    assertThrows(AssertionError::class.java) {
+      EventLogSubject.assertThat(eventLog)
+        .hasWrittenTranslationLanguageSelectionThat()
+        .isEqualTo(differentLanguageSelection)
+    }
+  }
+
+  @Test
+  fun testEventLogSubject_matchesAudioTranslationLanguageSelection() {
```
Comment (adhiamboperes) [inline testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt]:
```suggestion
  fun testHasAudioTranslationLanguageSelectionThat_eventWithAudioTranslationLanguageSelection_returnsAudioTranslationLanguageSelectionSubject() {
```

File: testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt [hunk 16]
```diff
@@ -0,0 +1,3939 @@
...
+      .build()
+    assertThrows(AssertionError::class.java) {
+      EventLogSubject.assertThat(eventLog)
+        .hasAudioTranslationLanguageSelectionThat()
+        .isEqualTo(differentSelection)
+    }
+  }
+
+  @Test
+  fun testEventLogSubject_hasOpenExplorationActivityContext() {
```
Comment (adhiamboperes) [inline testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt]:
```suggestion
  fun testEventLogSubject_hasOpenExplorationActivityContext_passes() {
```

Comment (adhiamboperes) [reply testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt]: Add tests for:

1. `testHasOpenExplorationActivityContextThat_contextIsExploration_returnsExplorationContextSubject`
2. `testHasOpenExplorationActivityContextThat_blockIsProvided_executesWithCorrectSubject`

File: testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt [hunk 17]
```diff
@@ -0,0 +1,3939 @@
...
+    val eventLog = EventLog.newBuilder()
+      .build()
+    assertThrows(AssertionError::class.java) {
+      EventLogSubject.assertThat(eventLog)
+        .hasOpenExplorationActivityContext()
+    }
+  }
+
+  @Test
+  fun testEventLogSubject_hasOpenInfoTabContext() {
```
Comment (adhiamboperes) [inline testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt]: Like with the exploration context test above, we should test for 3 outcomes, in addition to the failure case:
1. `_whenContextIsInfoTab_passes` ==  EventLogSubject.assertThat(eventLog)
      .hasOpenInfoTabContext()

2. `_returnsTopicContextSubject`  

```kotlin
 val eventLog = EventLog.newBuilder()
    .setContext(
      EventLog.Context.newBuilder()
        .setOpenInfoTab(
          TopicContext.newBuilder().setTopicId("info_tab_topic")
        )
    )
    .build()

  val subject = EventLogSubject.assertThat(eventLog)
    .hasOpenInfoTabContextThat()

subject.hasTopicIdThat().isEqualTo("info_tab_topic")
```

3. `_executesBlockWithCorrectSubject`

  ```kotlin
val eventLog = EventLog.newBuilder()
    .setContext(
      EventLog.Context.newBuilder()
        .setOpenInfoTab(TopicContext.newBuilder().setTopicId("test_topic"))
    )
    .build()

  EventLogSubject.assertThat(eventLog)
    .hasOpenInfoTabContextThat {
      hasTopicIdThat().isEqualTo("test_topic")
    }
```

This is because every contxt subject has these 3 functions, and this will increase the code coverage of the class. Ditto to the remaining contexts in the class.

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @theayushyadav11, for setting up tests for this extremely large class! 

Primarily, the test setup is good, and the coverage is great. I have some naming pattern suggestions and I have identified some missing test coverage for contexts. To clarify:

Contexts tyocally have 3 subject functions, `fun hasSomeContext()`, `fun hasSomeContextThat()`, and `hasSomeContextThat(block: TopicContextSubject.() -> Unit)`.

This PR adequatel covers the `fun hasSomeContext()`, functions, although I would prefer them renamed to `testEventLogSubject_hasSomeContext_passes`, to follow the `functionUnderTest_condition_expectedBehavior` pattern.

As for the 2 that are not covered, I am fine with those going in a follow up PR, to avoid adding a significant amount of work to this PR. This means changing the PR title to "Fix Part of". 

I am happy to merge this PR with only the test name updates, since it passes the required code coverage threshold.

File: testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt (hunk 13 above)
Comment (theayushyadav11) [reply testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt]: It crosses the word limit per line.

File: testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt (hunk 14 above)
Comment (theayushyadav11) [reply testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt]: Ditto

File: testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt (hunk 15 above)
Comment (theayushyadav11) [reply testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt]: Ditto

**Comment by theayushyadav11** [comment]
Hi  @adhiamboperes, I only have to change the test names in this pr as suggested (some are exceeding 100 letters) to make this pr merged and will raise a new pr for the other two types of functions which are not covered in coverage and will be looking at the `html` file and add the tests for those...please clarify so that I wrap up this asap.

File: testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt (hunk 13 above)
Comment (adhiamboperes) [reply testing/src/test/java/org/oppia/android/testing/logging/EventLogSubjectTest.kt]: Please see the edited suggestion.

**Comment by adhiamboperes** [comment]
@theayushyadav11,  tecgnically, yes. You need to address all comments except the ones for adding new tests for `hasSomeContextThat(),` and `hasSomeContextThat(block: TopicContextSubject.() -> Unit)`. You can edit the long tests names as per my latest suggestion.

>  will be looking at the `html` file and add the tests for those...please clarify so that I wrap up this asap.

Which **html** file are you referring to?

**Comment by theayushyadav11** [comment]
> Which **html** file are you referring to?

The file which generates after running code coverage locally.

**Comment by theayushyadav11** [comment]
PTAL @adhiamboperes.

**Review by adhiamboperes — APPROVED** [review]
Thanks @theayushyadav11! This LGTM.

**Comment by adhiamboperes** [comment]
Would like add a reminder: Always respond to reviewrs comments, even if it is with, "Done.". This lets us know that you have addressed the comment, and we can verify and resolve the comment.

**Comment by theayushyadav11** [comment]
> Would like add a reminder: Always respond to reviewrs comments, even if it is with, "Done.". This lets us know that you have addressed the comment, and we can verify and resolve the comment.


Apologies! I’ll make sure to take care of this from next time, as it will definitely make the review process easier.
