### PR TITLE
Fix #2427: Create LogoutDialogFragment

### LINKED ISSUE #2427: Logout Dialog disappears on orientation change
**Describe the bug**
In `Adminstrator Controls` screen logout dialog on orientation change disappears 

**To Reproduce**
1. Go to 'Administrator Controls'
2. Click on 'Log Out'
3. Rotate to Landscape
4. Dialog disappears

**Expected behavior**
Alert dialog should persist on orientation change. Also add test for the same in respective file.

**Video**

### PR DESCRIPTION
**Pull request by ArpitShukIa**
## Explanation
Fixes #2427: I created a new DialogFragment replacing the old AlertDialog in AdministratorControlsAccountActionsViewModel and removed the IntentFactoryShim dependency as it is no longer being used. Also added test for the fix.

### Test Results:
Robolectric:
image

Expresso:
image

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by ArpitShukIa** [comment]
@rt4914 PTAL.

**Comment by ArpitShukIa** [comment]
The bazel checks are failing. Probably because LogoutDialogFragment is not visible to AdministratorControlsAccountActionsViewModel.
How to fix this?

**Comment by rt4914** [comment]
Will review it once it gets review by @prayutsu or @FareesHussain

File: app/src/main/java/org/oppia/android/app/administratorcontrols/administratorcontrolsitemviewmodel/AdministratorControlsAccountActionsViewModel.kt [hunk 1]
```diff
@@ -1,29 +1,21 @@
...
-      }
-      .setPositiveButton(R.string.log_out_dialog_okay_button) { _, _ ->
-        // TODO(#762): Replace [ProfileChooserActivity] to [LoginActivity] once it is added.
-        val intent = intentFactoryShim.createProfileChooserActivityIntent(fragment.activity!!)
-        intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP)
-        fragment.activity!!.startActivity(intent)
-        fragment.activity!!.finish()
-      }.create().show()
+    LogoutDialogFragment().showNow(
+      fragment.requireActivity().supportFragmentManager,
```
Comment (prayutsu) [inline app/src/main/java/org/oppia/android/app/administratorcontrols/administratorcontrolsitemviewmodel/AdministratorControlsAccountActionsViewModel.kt]: In the future, we may probably want to add other logic with LogoutDialogFragment, so suggest making a method to provide the LogOutDialogFragment instance inside a Companion Object. You can see other DialogFragment for reference.

File: app/src/main/java/org/oppia/android/app/administratorcontrols/LogoutDialogFragment.kt [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+import android.app.Dialog
+import android.os.Bundle
+import androidx.appcompat.app.AlertDialog
+import androidx.fragment.app.DialogFragment
+import org.oppia.android.R
+import org.oppia.android.app.profile.ProfileChooserActivity
+
+/** [DialogFragment] that gives option to either cancel or logout from current profile. */
+class LogoutDialogFragment : DialogFragment() {
+
```
Comment (prayutsu) [inline app/src/main/java/org/oppia/android/app/administratorcontrols/LogoutDialogFragment.kt:12]: Not sure, but shouldn't the letter 'o' be uppercase?

@rt4914 @ArpitShukIa WDYT?

**Review by prayutsu — CHANGES_REQUESTED** [review]
Left some comments. PTAL @ArpitShukIa

File: app/src/main/java/org/oppia/android/app/administratorcontrols/administratorcontrolsitemviewmodel/AdministratorControlsAccountActionsViewModel.kt (hunk 1 above)
Comment (ArpitShukIa) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/administratorcontrolsitemviewmodel/AdministratorControlsAccountActionsViewModel.kt]: Done

File: app/src/main/java/org/oppia/android/app/administratorcontrols/LogoutDialogFragment.kt (hunk 2 above)
Comment (ArpitShukIa) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/LogoutDialogFragment.kt:12]: Which 'o'?
Do you mean "LogOutDialogFragment"?

File: app/src/main/java/org/oppia/android/app/administratorcontrols/administratorcontrolsitemviewmodel/AdministratorControlsAccountActionsViewModel.kt [hunk 3]
```diff
@@ -1,29 +1,21 @@
 package org.oppia.android.app.administratorcontrols.administratorcontrolsitemviewmodel
 
-import android.content.Intent
-import androidx.appcompat.app.AlertDialog
 import androidx.fragment.app.Fragment
-import org.oppia.android.R
-import org.oppia.android.app.shim.IntentFactoryShim
+import androidx.lifecycle.ViewModel
+import org.oppia.android.app.administratorcontrols.AdministratorControlsFragment
```
Comment (FareesHussain) [inline app/src/main/java/org/oppia/android/app/administratorcontrols/administratorcontrolsitemviewmodel/AdministratorControlsAccountActionsViewModel.kt]: It looks like a unused import (ktlint might have ignored it as it is used in the KDoc)

**Review by FareesHussain — CHANGES_REQUESTED** [review]
@ArpitShukIa Implementation LGTM,

PTAL there is a bazel build error.

As `AdministratorControlsAccountActionsViewModel` no longer imports the resources move it from [VIEW_MODELS_WITH_RESOURCE_IMPORTS](https://github.com/oppia/oppia-android/blob/develop/app/BUILD.bazel#L128) to [VIEW_MODELS](https://github.com/oppia/oppia-android/blob/develop/app/BUILD.bazel#L157) source set to optimize the build but this doesn't solve the bazel error, as we don't have Activities or Fragments in the viewmodels so far there is no `dep` added to the [view_models](https://github.com/oppia/oppia-android/blob/develop/app/BUILD.bazel#L554) target. 

To fix this we need to add the `:app` dep to the `:view_models` but this is definitely not a  good practice.

I suggest creating a new Listner and use the LogoutDialogFragment within the AdministratorControlsActivity or AdministratorControlsFragment

@BenHenning WDYT?

File: app/src/main/java/org/oppia/android/app/administratorcontrols/administratorcontrolsitemviewmodel/AdministratorControlsAccountActionsViewModel.kt (hunk 3 above)
Comment (ArpitShukIa) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/administratorcontrolsitemviewmodel/AdministratorControlsAccountActionsViewModel.kt:5]: What's to be done here?

Comment (ArpitShukIa) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/administratorcontrolsitemviewmodel/AdministratorControlsAccountActionsViewModel.kt]: Removed them

Comment (FareesHussain) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/administratorcontrolsitemviewmodel/AdministratorControlsAccountActionsViewModel.kt]: Thanks, you can resolve this now

**Review by FareesHussain — APPROVED** [review]
LGTM, Thanks

File: app/src/main/java/org/oppia/android/app/administratorcontrols/LogoutDialogFragment.kt (hunk 2 above)
Comment (prayutsu) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/LogoutDialogFragment.kt:12]: Yes, I meant LogOutDialogFragment but I am not really sure if we want to change it or not.

**Review by prayutsu — APPROVED** [review]
LGTM, Thanks @ArpitShukIa

File: app/src/main/java/org/oppia/android/app/administratorcontrols/administratorcontrolsitemviewmodel/AdministratorControlsAccountActionsViewModel.kt (hunk 1 above)
Comment (prayutsu) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/administratorcontrolsitemviewmodel/AdministratorControlsAccountActionsViewModel.kt]: This can be resolved now :)

**Comment by BenHenning** [comment]
Sorry, I think I'll need to take a pass on this tomorrow, but I can follow up to the comment above now.

File: app/src/main/java/org/oppia/android/app/administratorcontrols/LogoutDialogFragment.kt (hunk 2 above)
Comment (BenHenning) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/LogoutDialogFragment.kt:12]: The noun form is correct here (i.e. this is the dialog where logouts occur). The documentation should say 'log out' since the verb form is the action the user is taking. Another way to check: methods almost certainly should be logOut since they are verb phrases, and classes will usually be logout since they are noun phrases.

**Comment by BenHenning** [comment]
> @ArpitShukIa Implementation LGTM,
> 
> PTAL there is a bazel build error.
> 
> As `AdministratorControlsAccountActionsViewModel` no longer imports the resources move it from [VIEW_MODELS_WITH_RESOURCE_IMPORTS](https://github.com/oppia/oppia-android/blob/develop/app/BUILD.bazel#L128) to [VIEW_MODELS](https://github.com/oppia/oppia-android/blob/develop/app/BUILD.bazel#L157) source set to optimize the build but this doesn't solve the bazel error, as we don't have Activities or Fragments in the viewmodels so far there is no `dep` added to the [view_models](https://github.com/oppia/oppia-android/blob/develop/app/BUILD.bazel#L554) target.
> 
> To fix this we need to add the `:app` dep to the `:view_models` but this is definitely not a good practice.
> 
> I suggest creating a new Listner and use the LogoutDialogFragment within the AdministratorControlsActivity or AdministratorControlsFragment
> 
> @BenHenning WDYT?

I agree with moving this out of the resources view model list if R is no longer needed. Regarding the dependency, I'm fairly certain you can't add :app to :view_models since that will likely result in a circular dependency.

I'm not sure I'm following what the need for the listener is. What specific problem do you see here @FareesHussain?

**Comment by FareesHussain** [comment]
> I'm not sure I'm following what the need for the listener is. What specific problem do you see here @FareesHussain?

https://github.com/oppia/oppia-android/runs/2445936672

Before using the listener. the `AdministratorControlsAccountActionsViewModel` imports the LogoutDialogFragment. I had a look into the error and found that the LogoutDialogFragment comes under the `:app` target, I noticed none of the other viewmodels have imported from the `:app` target so to fix the Bazel error, I suggested adding a listener inorder to call the `showLogoutDialog` function. I'm not sure if there is any other way to fix it.

File: app/src/main/java/org/oppia/android/app/administratorcontrols/LogoutDialogFragment.kt (hunk 2 above)
Comment (prayutsu) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/LogoutDialogFragment.kt:12]: Sounds good, thanks for the clarification @BenHenning.
This can be resolved now.

Comment (ArpitShukIa) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/LogoutDialogFragment.kt:12]: > The documentation should say 'log out' since the verb form is the action the user is taking

Fixed it.

**Comment by BenHenning** [comment]
Ah I see, thanks for clarifying @FareesHussain. Yes, that seems like the correct way to solve this since the interface provides indirection (plus it's a bit cleaner not to directly interact with the activity/fragment lifecycles except at in that activity or fragment implementation class).

**Comment by BenHenning** [comment]
I'm actually going to take a pass on just my codeowners here (presumably Bazel) after @rt4914 has a chance to review it in case there are any big changes.

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt [hunk 4]
```diff
@@ -16,14 +16,16 @@ const val SELECTED_CONTROLS_TITLE_SAVED_KEY =
 const val LAST_LOADED_FRAGMENT_KEY = "LAST_LOADED_FRAGMENT_KEY"
 const val PROFILE_LIST_FRAGMENT = "PROFILE_LIST_FRAGMENT"
 const val APP_VERSION_FRAGMENT = "APP_VERSION_FRAGMENT"
+const val LOGOUT_DIALOG_FRAGMENT = "LOGOUT_DIALOG_FRAGMENT"
```
Comment (rt4914) [inline app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt]: This tag should be shifted to `LogoutDialogFragment` companion object and then it should be used wherever requried.

File: app/src/main/java/org/oppia/android/app/administratorcontrols/LogoutDialogFragment.kt [hunk 5]
```diff
@@ -0,0 +1,31 @@
...
+  }
+
+  override fun onCreateDialog(savedInstanceState: Bundle?): Dialog {
+    return AlertDialog.Builder(requireContext(), R.style.AlertDialogTheme)
+      .setMessage(R.string.log_out_dialog_message)
+      .setNegativeButton(R.string.log_out_dialog_cancel_button) { dialog, _ ->
+        dialog.dismiss()
+      }
+      .setPositiveButton(R.string.log_out_dialog_okay_button) { _, _ ->
+        // TODO(#762): Replace [ProfileChooserActivity] to [LoginActivity] once it is added.
```
Comment (rt4914) [inline app/src/main/java/org/oppia/android/app/administratorcontrols/LogoutDialogFragment.kt]: This TODO is not needed here. You can remove this.

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt (hunk 4 above)
Comment (ArpitShukIa) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt]: Done

File: app/src/main/java/org/oppia/android/app/administratorcontrols/LogoutDialogFragment.kt (hunk 5 above)
Comment (ArpitShukIa) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/LogoutDialogFragment.kt]: Done

File: app/src/main/java/org/oppia/android/app/administratorcontrols/ShowLogoutDialogListener.kt [hunk 6]
```diff
@@ -0,0 +1,6 @@
+package org.oppia.android.app.administratorcontrols
+
+/** Listener for when an activity should show [LogoutDialogFragment]. */
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/administratorcontrols/ShowLogoutDialogListener.kt]: Suggest: ``Listener for when the logout dialog should be shown.``

File: app/src/main/java/org/oppia/android/app/administratorcontrols/ShowLogoutDialogListener.kt [hunk 7]
```diff
@@ -0,0 +1,6 @@
...
+interface ShowLogoutDialogListener {
+  fun showLogoutDialog()
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/administratorcontrols/ShowLogoutDialogListener.kt:7]: This should have a KDoc, too, such as: ``Shows the logout dialog. This cannot be called at times when there's an ongoing fragment transaction.`` (the latter providing some context on when it's valid to call this).

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @ArpitShukIa! Generally LGTM for Bazel changes, but had 2 nit comments to address before approving.

File: app/src/main/java/org/oppia/android/app/administratorcontrols/ShowLogoutDialogListener.kt (hunk 6 above)
Comment (ArpitShukIa) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/ShowLogoutDialogListener.kt]: Done

File: app/src/main/java/org/oppia/android/app/administratorcontrols/ShowLogoutDialogListener.kt (hunk 7 above)
Comment (ArpitShukIa) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/ShowLogoutDialogListener.kt:7]: Done

**Comment by ArpitShukIa** [comment]
@BenHenning I have committed the requested changes. PTAL.

**Review by BenHenning — APPROVED** [review]
Thanks @ArpitShukIa. LGTM for codeowners.

**Comment by BenHenning** [comment]
The Bazel issues are existing problems and are unrelated to this PR, so merging this as-is.
