### PR TITLE
Fix #2040: Reformating files under TextInput Package

### LINKED ISSUE #2040: Fix file formatting under textinput package
**Describe the bug**
All the files, under the package `domain/src/test/java/org/oppia/android/domain/classify/rules/textinput` are not in the correct format. 

**Expected behavior**
File format should be follow from this file - [TextInputEqualsRuleClassifierProviderTest](https://github.com/oppia/oppia-android/blob/develop/domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputEqualsRuleClassifierProviderTest.kt
)

**Correct Order**
Constant values
Dagger injection
Local variables
Test Before setup
Tests
Dagger Setup

### PR DESCRIPTION
**Pull request by Arjupta**
## Explanation
Fixes #2040 : Reformated fies under TextInput Package according to this [file](https://github.com/oppia/oppia-android/blob/develop/domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputEqualsRuleClassifierProviderTest.kt)

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by anandwana001** [comment]
@ARJUPTA 
Follow the below points before review:
1. `The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)`
2. Branch naming - https://github.com/oppia/oppia-android/wiki#instructions-for-making-a-code-change

**Comment by Arjupta** [comment]
> @ARJUPTA
> Follow the below points before review:
> 
> 1. `The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)`
> 2. Branch naming - https://github.com/oppia/oppia-android/wiki#instructions-for-making-a-code-change

Pardon me, I will use descriptive branch names for further PRs. @anandwana001 PTAL

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt [hunk 1]
```diff
@@ -24,6 +24,27 @@ import kotlin.test.fail
 @Config(manifest = Config.NONE)
 class TextInputContainsRuleClassifierProviderTest {
 
+  private val STRING_VALUE_WILL_BREAK =
```
Comment (anandwana001) [inline domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt]: Can we have some more understandable naming here? 
As per from the other file, we have naming like `STRING_VALUE_TEST_UPPERCASE ` which says, this will be testing an uppercase string value.

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputFuzzyEqualsRuleClassifierProviderTest.kt [hunk 2]
```diff
@@ -22,6 +22,30 @@ import kotlin.test.fail
 @LooperMode(LooperMode.Mode.PAUSED)
 @Config(manifest = Config.NONE)
 class TextInputFuzzyEqualsRuleClassifierProviderTest {
+
+  private val STRING_ANSWER_UPPERCASE =
```
Comment (anandwana001) [inline domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputFuzzyEqualsRuleClassifierProviderTest.kt]: Let's update these naming also, like `STRING_ANSWER_TEST_UPPERCASE `.
applies to all other in this file.

**Review by anandwana001 — CHANGES_REQUESTED** [review]
Thanks @ARJUPTA Left few comments.
Also, put a screenshot in the PR description showing all the test cases are passing.

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt (hunk 1 above)
Comment (Arjupta) [reply domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt]: Should I name it `STRING_VALUE_THIS_IS_A_TEST_I_WILL_BREAK` **OR** `STRING_VALUE_WILL_BREAK_MESSAGE`

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputFuzzyEqualsRuleClassifierProviderTest.kt (hunk 2 above)
Comment (Arjupta) [reply domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputFuzzyEqualsRuleClassifierProviderTest.kt]: On It..

**Comment by Arjupta** [comment]
> Thanks @ARJUPTA Left few comments.
> Also, put a screenshot in the PR description showing all the test cases are passing.

@anandwana001 Can you direct me on how to run the test of another module?

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt (hunk 1 above)
Comment (anandwana001) [reply domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt:27]: > > Thanks @ARJUPTA Left few comments.
> > Also, put a screenshot in the PR description showing all the test cases are passing.
> 
> @anandwana001 Can you direct me on how to run the test of another module?

Head over to our wiki page for testing - https://github.com/oppia/oppia-android/wiki/Oppia-Android-Testing

**Comment by anandwana001** [comment]
> > Thanks @ARJUPTA Left few comments.
> > Also, put a screenshot in the PR description showing all the test cases are passing.
> 
> @anandwana001 Can you direct me on how to run the test of another module?

Head over to our wiki page for testing - https://github.com/oppia/oppia-android/wiki/Oppia-Android-Testing

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt (hunk 1 above)
Comment (anandwana001) [reply domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt]: Let's see what the test is trying to do, and name it accordingly. 
I don't think there is something related to break, although we have 'break' word in our string, that doesn't relate to anything breaking. 
I think this is related to the different values to test value match or not, check another test file in the package on a similar test what's the naming there.

Comment (Arjupta) [reply domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt]: Unfortunately, there is no String in TextInput package with the same value

Comment (anandwana001) [reply domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt:27]: Check `TextInputFuzzyEqualsRuleClassifierProviderTest.kt`

Comment (anandwana001) [reply domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt]: check `TextInputFuzzyEqualsRuleClassifierProviderTest.kt`

Comment (Arjupta) [reply domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt]: ### **The string values there are -**
  private val STRING_ANSWER_UPPERCASE = createString(value = "TEST")
  private val STRING_INPUT_UPPERCASE = createString(value = "TEST")
  private val STRING_INPUT_LOWERCASE = createString(value = "test")
  private val STRING_ANSWER_LOWERCASE = createString(value = "test")
  private val STRING_ANSWER_DIFF_LOWERCASE = createString(value = "diff")
  private val STRING_INPUT_DIFF_LOWERCASE = createString(value = "diff")
  private val STRING_INPUT_DIFF_UPPERCASE = createString(value = "DIFF")
  private val STRING_FUZZY_INPUT = createString(value = "This Is a TesT")
  private val STRING_ANSWER = createString(value = "this is a test")
  private val STRING_WITH_WHITESPACE = createString(value = "  test   ")
**What are you suggesting to follow**

**Comment by Arjupta** [comment]
> > > Thanks @ARJUPTA Left few comments.
> > > Also, put a screenshot in the PR description showing all the test cases are passing.
> > 
> > 
> > @anandwana001 Can you direct me on how to run the test of another module?
> 
> Head over to our wiki page for testing - https://github.com/oppia/oppia-android/wiki/Oppia-Android-Testing

@anandwana001 Adding the screensnips for individual tests

Screenshot 2020-11-03 112816

Screenshot 2020-11-03 112643

Screenshot 2020-11-03 112458

Screenshot 2020-11-03 111551

Screenshot 2020-11-03 112128

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt [hunk 3]
```diff
@@ -24,6 +24,27 @@ import kotlin.test.fail
 @Config(manifest = Config.NONE)
 class TextInputContainsRuleClassifierProviderTest {
 
+  private val STRING_VALUE_CONTAINS_ANSWER_TEXT =
```
Comment (anandwana001) [inline domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt]: You had done the correct naming in file `domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputFuzzyEqualsRuleClassifierProviderTest.kt` 
We should do the same here.

**Review by anandwana001 — CHANGES_REQUESTED** [review]
Thanks @ARJUPTA left a comment

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt (hunk 3 above)
Comment (Arjupta) [reply domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt]: Done

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt [hunk 4]
```diff
@@ -24,6 +24,29 @@ import kotlin.test.fail
 @Config(manifest = Config.NONE)
 class TextInputContainsRuleClassifierProviderTest {
 
+  private val STRING_INPUT_CONTAINS_ANSWER =
```
Comment (anandwana001) [inline domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt]: Other two files contain the correct variable naming like `STRING_ANSWER_TEST_UPPERCASE`. 
Let's use the same here. 

`STRING_VALUE_TEST_CONTAINS_ANSWER `

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt [hunk 5]
```diff
@@ -24,6 +24,29 @@ import kotlin.test.fail
...
+    InteractionObjectTestBuilder.createString(value = "this is a test i will break")
+  private val STRING_INPUT_AN_ANSWER =
```
Comment (anandwana001) [inline domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt]: `STRING_VALUE_TEST_AN_ANSWER `

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt [hunk 6]
```diff
@@ -24,6 +24,29 @@ import kotlin.test.fail
...
+    InteractionObjectTestBuilder.createString(value = "an answer")
+  private val STRING_INPUT_A_TEST =
```
Comment (anandwana001) [inline domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt]: `STRING_VALUE_TEST_A_TEST `

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt [hunk 7]
```diff
@@ -24,6 +24,29 @@ import kotlin.test.fail
...
+    InteractionObjectTestBuilder.createString(value = "a test")
+  private val STRING_INPUT_IS_A =
```
Comment (anandwana001) [inline domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt]: `STRING_VALUE_TEST_IS_A `

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt [hunk 8]
```diff
@@ -24,6 +24,29 @@ import kotlin.test.fail
...
+    InteractionObjectTestBuilder.createString(value = "is a")
+  private val STRING_INPUT_THIS_IS =
```
Comment (anandwana001) [inline domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt]: `STRING_VALUE_TEST_THIS_IS `

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt [hunk 9]
```diff
@@ -24,6 +24,29 @@ import kotlin.test.fail
...
+    InteractionObjectTestBuilder.createString(value = "this is")
+  private val STRING_INPUT_NULL =
```
Comment (anandwana001) [inline domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt]: `STRING_VALUE_TEST_NULL `

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt [hunk 10]
```diff
@@ -24,6 +24,29 @@ import kotlin.test.fail
...
+    InteractionObjectTestBuilder.createString(value = "")
+  private val STRING_ANSWER_NULL =
```
Comment (anandwana001) [inline domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt]: `STRING_VALUE_TEST_ANSWER_NULL`

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt [hunk 11]
```diff
@@ -24,6 +24,29 @@ import kotlin.test.fail
...
+    InteractionObjectTestBuilder.createString(value = "")
+  private val STRING_ANSWER =
```
Comment (anandwana001) [inline domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt]: `STRING_VALUE_TEST_ANSWER`

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt [hunk 12]
```diff
@@ -24,6 +24,29 @@ import kotlin.test.fail
...
+    InteractionObjectTestBuilder.createString(value = "this is a test")
+  private val STRING_ANSWER_EXTRA_SPACE =
```
Comment (anandwana001) [inline domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt]: `STRING_VALUE_TEST_EXTRA_SPACE `

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt [hunk 13]
```diff
@@ -24,6 +24,29 @@ import kotlin.test.fail
...
+    InteractionObjectTestBuilder.createString(value = " this   is  a  test ")
+  private val STRING_ANSWER_NO_SPACE =
```
Comment (anandwana001) [inline domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt]: `STRING_VALUE_TEST_NO_SPACE `

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputFuzzyEqualsRuleClassifierProviderTest.kt [hunk 14]
```diff
@@ -22,6 +22,30 @@ import kotlin.test.fail
 @LooperMode(LooperMode.Mode.PAUSED)
 @Config(manifest = Config.NONE)
 class TextInputFuzzyEqualsRuleClassifierProviderTest {
+
+  private val STRING_ANSWER_TEST_UPPERCASE =
```
Comment (anandwana001) [inline domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputFuzzyEqualsRuleClassifierProviderTest.kt]: `STRING_VALUE_TEST_UPPERCASE`

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputFuzzyEqualsRuleClassifierProviderTest.kt [hunk 15]
```diff
@@ -22,6 +22,30 @@ import kotlin.test.fail
...
+    InteractionObjectTestBuilder.createString(value = "TEST")
+  private val STRING_INPUT_TEST_UPPERCASE =
```
Comment (anandwana001) [inline domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputFuzzyEqualsRuleClassifierProviderTest.kt]: `STRING_VALUE_TEST_UPPERCASE `

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputFuzzyEqualsRuleClassifierProviderTest.kt [hunk 16]
```diff
@@ -22,6 +22,30 @@ import kotlin.test.fail
...
+    InteractionObjectTestBuilder.createString(value = "TEST")
+  private val STRING_INPUT_TEST_LOWERCASE =
```
Comment (anandwana001) [inline domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputFuzzyEqualsRuleClassifierProviderTest.kt]: `STRING_VALUE_TEST_LOWERCASE`

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputFuzzyEqualsRuleClassifierProviderTest.kt [hunk 17]
```diff
@@ -22,6 +22,30 @@ import kotlin.test.fail
...
+    InteractionObjectTestBuilder.createString(value = "test")
+  private val STRING_ANSWER_TEST_LOWERCASE =
```
Comment (anandwana001) [inline domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputFuzzyEqualsRuleClassifierProviderTest.kt]: `STRING_VALUE_TEST_ANSWER_LOWERCASE `

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputFuzzyEqualsRuleClassifierProviderTest.kt [hunk 18]
```diff
@@ -22,6 +22,30 @@ import kotlin.test.fail
...
+    InteractionObjectTestBuilder.createString(value = "test")
+  private val STRING_ANSWER_DIFF_LOWERCASE =
```
Comment (anandwana001) [inline domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputFuzzyEqualsRuleClassifierProviderTest.kt]: `STRING_VALUE_TEST_ANSWER_DIFF_LOWERCASE`

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputFuzzyEqualsRuleClassifierProviderTest.kt [hunk 19]
```diff
@@ -22,6 +22,30 @@ import kotlin.test.fail
...
+    InteractionObjectTestBuilder.createString(value = "diff")
+  private val STRING_INPUT_DIFF_LOWERCASE =
```
Comment (anandwana001) [inline domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputFuzzyEqualsRuleClassifierProviderTest.kt]: `STRING_VALUE_TEST_DIFF_LOWERCASE `

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputFuzzyEqualsRuleClassifierProviderTest.kt [hunk 20]
```diff
@@ -22,6 +22,30 @@ import kotlin.test.fail
...
+    InteractionObjectTestBuilder.createString(value = "diff")
+  private val STRING_INPUT_DIFF_UPPERCASE =
```
Comment (anandwana001) [inline domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputFuzzyEqualsRuleClassifierProviderTest.kt]: `STRING_VALUE_TEST_DIFF_UPPERCASE`

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputFuzzyEqualsRuleClassifierProviderTest.kt [hunk 21]
```diff
@@ -22,6 +22,30 @@ import kotlin.test.fail
...
+    InteractionObjectTestBuilder.createString(value = "DIFF")
+  private val STRING_FUZZY_INPUT =
```
Comment (anandwana001) [inline domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputFuzzyEqualsRuleClassifierProviderTest.kt]: `STRING_VALUE_TEST_FUZZY_INPUT `

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputFuzzyEqualsRuleClassifierProviderTest.kt [hunk 22]
```diff
@@ -22,6 +22,30 @@ import kotlin.test.fail
...
+    InteractionObjectTestBuilder.createString(value = "This Is a TesT")
+  private val STRING_ANSWER =
```
Comment (anandwana001) [inline domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputFuzzyEqualsRuleClassifierProviderTest.kt]: `STRING_VALUE_TEST_ANSWER `

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputFuzzyEqualsRuleClassifierProviderTest.kt [hunk 23]
```diff
@@ -22,6 +22,30 @@ import kotlin.test.fail
...
+    InteractionObjectTestBuilder.createString(value = "this is a test")
+  private val STRING_WITH_WHITESPACE =
```
Comment (anandwana001) [inline domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputFuzzyEqualsRuleClassifierProviderTest.kt]: `STRING_VALUE_TEST_WITH_WHITESPACE `

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputCaseSensitiveEqualsRuleClassifierProviderTest.kt [hunk 24]
```diff
@@ -23,9 +23,13 @@ import kotlin.test.fail
...
 class TextInputCaseSensitiveEqualsRuleClassifierProviderTest {
-  private val STRING_VALUE_TEST_UPPERCASE = createString(value = "TEST")
-  private val STRING_VALUE_TEST_LOWERCASE = createString(value = "test")
-  private val STRING_VALUE_RANDOM = createString(value = "random")
+
+  private val STRING_VALUE_TEST_UPPERCASE =
+    InteractionObjectTestBuilder.createString(value = "TEST")
+  private val STRING_VALUE_TEST_LOWERCASE =
+    InteractionObjectTestBuilder.createString(value = "test")
+  private val STRING_VALUE_RANDOM =
```
Comment (anandwana001) [inline domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputCaseSensitiveEqualsRuleClassifierProviderTest.kt]: `STRING_VALUE_TEST_RANDOM `

**Review by anandwana001 — CHANGES_REQUESTED** [review]
nit changes. Else good to go.

**Comment by anandwana001** [comment]
@ARJUPTA please comment on comments above for further review.

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputStartsWithRuleClassifierProviderTest.kt [hunk 25]
```diff
@@ -38,9 +38,9 @@ class TextInputStartsWithRuleClassifierProviderTest {
     InteractionObjectTestBuilder.createString("TESTSTRING")
   private val STRING_VALUE_TEST_UPPERCASE =
     InteractionObjectTestBuilder.createString("TEST")
-  private val EMPTY_STRING =
+  private val STRING_VALUE_TEST_NULL =
```
Comment (anandwana001) [inline domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputStartsWithRuleClassifierProviderTest.kt:41]: the above two variables are not correct, you update them, please. 

```kotlin
STRING_VALUE_TEST_STRING_LOWERCASE
STRING_VALUE_TEST_STRING_LOWERCASE_EXTRA_SPACES
```

**Review by anandwana001 — CHANGES_REQUESTED** [review]
nit change. @ARJUPTA

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt (hunk 4 above)
Comment (Arjupta) [reply domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt]: Done

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt (hunk 5 above)
Comment (Arjupta) [reply domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt]: Done

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt (hunk 6 above)
Comment (Arjupta) [reply domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt]: Done

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt (hunk 7 above)
Comment (Arjupta) [reply domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt]: Done

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt (hunk 8 above)
Comment (Arjupta) [reply domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt]: Done

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt (hunk 9 above)
Comment (Arjupta) [reply domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt]: Done

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt (hunk 10 above)
Comment (Arjupta) [reply domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt]: Done

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt (hunk 11 above)
Comment (Arjupta) [reply domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt]: Done

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt (hunk 12 above)
Comment (Arjupta) [reply domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt]: Done

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt (hunk 13 above)
Comment (Arjupta) [reply domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputContainsRuleClassifierProviderTest.kt]: Done

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputFuzzyEqualsRuleClassifierProviderTest.kt (hunk 14 above)
Comment (Arjupta) [reply domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputFuzzyEqualsRuleClassifierProviderTest.kt]: Done

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputFuzzyEqualsRuleClassifierProviderTest.kt (hunk 15 above)
Comment (Arjupta) [reply domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputFuzzyEqualsRuleClassifierProviderTest.kt]: Done

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputFuzzyEqualsRuleClassifierProviderTest.kt (hunk 16 above)
Comment (Arjupta) [reply domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputFuzzyEqualsRuleClassifierProviderTest.kt]: Done

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputFuzzyEqualsRuleClassifierProviderTest.kt (hunk 17 above)
Comment (Arjupta) [reply domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputFuzzyEqualsRuleClassifierProviderTest.kt]: Done

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputFuzzyEqualsRuleClassifierProviderTest.kt (hunk 18 above)
Comment (Arjupta) [reply domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputFuzzyEqualsRuleClassifierProviderTest.kt]: Done

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputFuzzyEqualsRuleClassifierProviderTest.kt (hunk 19 above)
Comment (Arjupta) [reply domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputFuzzyEqualsRuleClassifierProviderTest.kt]: Done

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputFuzzyEqualsRuleClassifierProviderTest.kt (hunk 20 above)
Comment (Arjupta) [reply domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputFuzzyEqualsRuleClassifierProviderTest.kt]: Done

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputFuzzyEqualsRuleClassifierProviderTest.kt (hunk 21 above)
Comment (Arjupta) [reply domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputFuzzyEqualsRuleClassifierProviderTest.kt]: Done

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputFuzzyEqualsRuleClassifierProviderTest.kt (hunk 22 above)
Comment (Arjupta) [reply domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputFuzzyEqualsRuleClassifierProviderTest.kt]: Done

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputFuzzyEqualsRuleClassifierProviderTest.kt (hunk 23 above)
Comment (Arjupta) [reply domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputFuzzyEqualsRuleClassifierProviderTest.kt]: Done

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputCaseSensitiveEqualsRuleClassifierProviderTest.kt (hunk 24 above)
Comment (Arjupta) [reply domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputCaseSensitiveEqualsRuleClassifierProviderTest.kt]: Done

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputStartsWithRuleClassifierProviderTest.kt (hunk 25 above)
Comment (Arjupta) [reply domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputStartsWithRuleClassifierProviderTest.kt:41]: Done

**Review by anandwana001 — APPROVED** [review]
LGTM, Thanks @ARJUPTA 

Just for the future reference, please move the screenshot in the PR description, it should not be in the comment.

**Comment by Arjupta** [comment]
> LGTM, Thanks @ARJUPTA 
> 
> Just for the future reference, please move the screenshot in the PR description, it should not be in the comment. 

Okay 👍

**Comment by anandwana001** [comment]
@rt4914 deferring to you for further merge.

**Comment by rt4914** [comment]
@aggarwalpulkit596 Please add points.

**Comment by aggarwalpulkit596** [comment]
give @ARJUPTA 5 points
