### PR TITLE
Fix #3309 and #3311: Implement Force Network Type Feature

### LINKED ISSUE #3309: Introduce UI for Force Network Type
Introduce UI for Force Network Type screen.
**Mock link:** https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/8ae1a60e-7f6d-4b7b-b741-469bb80007b9/

**Target PR date:** 2021-07-19
**Target completion date:** 2021-07-27

### LINKED ISSUE #3311: Implement logic to Force Network Type
Implement logic to Force Network Type of the android application.

**Target PR date:** 2021-07-25
**Target completion date:** 2021-08-02

### LINKED ISSUE #3379: Arrange the list of fragments in alphabetical order in FragmentComponent
**Describe the bug**
The list of fragments are not arranged in alphabetical order.

**To Reproduce**
1. Go to `FragmentComponent.kt`
2. See that at several instances the list is not in alphabetical order.

**Expected behavior**
The list of fragments should be arranged in alphabetical order.

**Additional context**
File Reference:
https://github.com/oppia/oppia-android/blob/090f7b192cfd71d6dd51572767eb5f28dba3d811/app/src/main/java/org/oppia/android/app/fragment/FragmentComponent.kt#L75-L118

### PR DESCRIPTION
**Pull request by yashraj-01**
## Explanation

Fixes #3309. Introduced UI for Force Network Type screen.
Fixes #3311. Implemented logic to force network type.
This PR also fixes #3379. cc: @rt4914

**Mock link:** https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/8ae1a60e-7f6d-4b7b-b741-469bb80007b9/specs/

**Screenshots**

- UI
  

- Espresso tests passing for `DeveloperOptionsFragmentTest`
Screenshot from 2021-07-31 20-04-10

- Espresso tests passing for `ForceNetworkTypeActivityTest`
Screenshot from 2021-07-31 21-16-47

- Espresso tests passing for `ForceNetworkTypeFragmentTest`
Screenshot from 2021-07-31 22-10-29

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by yashraj-01** [comment]
I have marked this PR as draft as I have not written the tests as of now. I'm waiting on the approval on PR #3471 and then will follow the same approach to write tests here. Also, the UI needs updates as I have to implement the logic for the selection of network types. That might depend on issue #3310. Thanks.

**Comment by yashraj-01** [comment]
> I have marked this PR as draft as I have not written the tests as of now. I'm waiting on the approval on PR #3471 and then will follow the same approach to write tests here. Also, the UI needs updates as I have to implement the logic for the selection of network types. That might depend on issue #3310. Thanks.

The tests are now there according to the comments on #3471. The UI is also updated and the logic for the feature is also included as part of this PR only. In short, the PR is now ready for review. PTAL. Thanks,

File: app/src/sharedTest/java/org/oppia/android/app/devoptions/ForceNetworkTypeActivityTest.kt [hunk 1]
```diff
@@ -0,0 +1,190 @@
...
+    val title = activityTestRule.activity.title
+
+    // Verify that the activity label is correct as a proxy to verify TalkBack will announce the
+    // correct string when it's read out.
+    assertThat(title).isEqualTo(context.getString(R.string.force_network_type_activity_title))
+  }
+
+  @Test
+  fun testForceNetworkTypeActivity_forceNetworkTypeFragmentIsDisplayed() {
+    launch(ForceNetworkTypeActivity::class.java).use {
```
Comment (Sarthak2601) [inline app/src/sharedTest/java/org/oppia/android/app/devoptions/ForceNetworkTypeActivityTest.kt]: This launch command is different from the usually used one in all other test files (eg: MarkTopicsCompletedFragmentTest), any particular reason for this change?

**Review by Sarthak2601 — COMMENTED** [review]
Thanks @yashraj-01. This almost LGTM, just wanted to understand the change in activity launching approach.

File: app/src/sharedTest/java/org/oppia/android/app/devoptions/ForceNetworkTypeActivityTest.kt (hunk 1 above)
Comment (yashraj-01) [reply app/src/sharedTest/java/org/oppia/android/app/devoptions/ForceNetworkTypeActivityTest.kt]: Yes. Since the `ForceNetworkTypeActivity` doesn't take any arguments while creating the intent for the activity, we have used the class approach to launch the activity. This was suggested by @anandwana001 in one of my previous PRs.

**Review by Sarthak2601 — APPROVED** [review]
Good work @yashraj-01, LGTM!

File: app/src/main/res/values/strings.xml [hunk 2]
```diff
@@ -480,4 +481,5 @@
   <string name="developer_options_force_crash">Force crash</string>
   <string name="all">All</string>
   <string name="mark_completed_uppercase">MARK COMPLETED</string>
+  <string name="network_selected">Network is Selected</string>
```
Comment (rt4914) [inline app/src/main/res/values/strings.xml]: Nit
`   <string name="network_selected">Network is selected</string>`

**Review by rt4914 — APPROVED** [review]
Nice work @yashraj-01

**Comment by BenHenning** [comment]
Apologies, will need to look at this a bit later today (my time).

File: app/src/main/res/values/strings.xml (hunk 2 above)
Comment (yashraj-01) [reply app/src/main/res/values/strings.xml]: Done.

Comment (yashraj-01) [reply app/src/main/res/values/strings.xml]: Resolving comment as the nit is fixed.

File: app/src/main/java/org/oppia/android/app/devoptions/forcenetworktype/ForceNetworkTypeViewModel.kt [hunk 3]
```diff
@@ -0,0 +1,31 @@
+package org.oppia.android.app.devoptions.forcenetworktype
+
+import org.oppia.android.app.fragment.FragmentScope
+import org.oppia.android.app.viewmodel.ObservableViewModel
+import org.oppia.android.util.networking.NetworkConnectionUtil
+import javax.inject.Inject
+
+/**
+ * [ViewModel] for [ForceNetworkTypeFragment]. It populates the recyclerview with a list of
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/devoptions/forcenetworktype/ForceNetworkTypeViewModel.kt]: I suggest either

```suggestion
 * [ViewModel] for [ForceNetworkTypeFragment]. It populates the RecyclerView with a list of
```

or

```suggestion
 * [ViewModel] for [ForceNetworkTypeFragment]. It populates the recycler view with a list of
```

("recyclerview" isn't a word, but "RecyclerView" is a proper noun versus "recycler view" which spells it out).

Ditto everywhere else.

File: app/src/main/java/org/oppia/android/app/devoptions/forcenetworktype/NetworkTypeItemViewModel.kt [hunk 4]
```diff
@@ -0,0 +1,14 @@
...
+import org.oppia.android.util.networking.NetworkConnectionUtil
+import javax.inject.Inject
+
+/** [ViewModel] for displaying a network type for the recyclerview in [ForceNetworkTypeFragment]. */
+class NetworkTypeItemViewModel @Inject constructor(
+  val networkType: NetworkConnectionUtil.ConnectionStatus
+) : ObservableViewModel() {
+
+  /** Returns the network type in a human readable format. */
+  fun formatNetworkTypeString(): String = networkType.name.toLowerCase().capitalize()
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/devoptions/forcenetworktype/NetworkTypeItemViewModel.kt]: If this is being displayed to the user it ought to use strings instead of formatting the enum constant (to facilitate things like translations & to avoid refactors/enum renames changing the UI).

File: app/src/main/java/org/oppia/android/app/devoptions/forcenetworktype/ForceNetworkTypeActivity.kt [hunk 5]
```diff
@@ -0,0 +1,28 @@
+package org.oppia.android.app.devoptions.forcenetworktype
+
+import android.content.Context
+import android.content.Intent
+import android.os.Bundle
+import org.oppia.android.R
+import org.oppia.android.app.activity.InjectableAppCompatActivity
+import javax.inject.Inject
+
+/** Activity for Force Network Type. */
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/devoptions/forcenetworktype/ForceNetworkTypeActivity.kt]:
```suggestion
/** Activity for forcing the network mode for the app. */
```

Prefer being more detailed (& to be judicious about capitalizing words). Ditto for other KDocs in this PR.

File: app/src/main/res/values/strings.xml [hunk 6]
```diff
@@ -468,6 +468,7 @@
   <string name="mark_stories_completed_activity_title">Mark Stories Completed</string>
   <string name="mark_topics_completed_activity_title">Mark Topics Completed</string>
   <string name="view_event_logs_activity_title">View Event Logs</string>
+  <string name="force_network_type_activity_title">Force Network Type</string>
```
Comment (BenHenning) [inline app/src/main/res/values/strings.xml:473]: I wonder if this should be 'Mode' instead of 'Type' since that might be a bit clearer, but I'm not sure.

@rt4914 any thoughts?

File: app/src/main/res/values/strings.xml [hunk 7]
```diff
@@ -480,4 +481,5 @@
   <string name="developer_options_force_crash">Force crash</string>
   <string name="all">All</string>
   <string name="mark_completed_uppercase">MARK COMPLETED</string>
+  <string name="network_selected">Network is selected</string>
```
Comment (BenHenning) [inline app/src/main/res/values/strings.xml]: This string name is too generic (keep in mind that these names are globals for the entire app). Can you please update this to be more specific to where the string is being used?

Further, the name should not reflect its exact English contents but rather its semantic meaning (consider "all" vs. "developer_options_modify_lesson_progress_label"; the latter is more specific to the context than the actual contents of the string).

File: app/src/sharedTest/java/org/oppia/android/app/devoptions/ForceNetworkTypeFragmentTest.kt [hunk 8]
```diff
@@ -0,0 +1,405 @@
+package org.oppia.android.app.devoptions
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/devoptions/ForceNetworkTypeFragmentTest.kt]: This test should be in the same corresponding package as the component that it's testing. Ditto for all tests in this & future PRs.

File: app/src/main/java/org/oppia/android/app/devoptions/forcenetworktype/ForceNetworkTypeFragment.kt [hunk 9]
```diff
@@ -0,0 +1,33 @@
...
+
+import android.content.Context
+import android.os.Bundle
+import android.view.LayoutInflater
+import android.view.View
+import android.view.ViewGroup
+import org.oppia.android.app.fragment.InjectableFragment
+import javax.inject.Inject
+
+/** Fragment to provide functionality to force network type of the app. */
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/devoptions/forcenetworktype/ForceNetworkTypeFragment.kt]:
```suggestion
/** Fragment to provide functionality to force the network type of the app. */
```

Small nit on grammar.

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @yashraj-01. Took a pass for my codeowners files (& the ones that they are including changes for).

File: app/src/main/java/org/oppia/android/app/devoptions/forcenetworktype/ForceNetworkTypeViewModel.kt (hunk 3 above)
Comment (yashraj-01) [reply app/src/main/java/org/oppia/android/app/devoptions/forcenetworktype/ForceNetworkTypeViewModel.kt]: Done. Followed the below one. Thanks.

File: app/src/main/java/org/oppia/android/app/devoptions/forcenetworktype/ForceNetworkTypeActivity.kt (hunk 5 above)
Comment (yashraj-01) [reply app/src/main/java/org/oppia/android/app/devoptions/forcenetworktype/ForceNetworkTypeActivity.kt]: Done.

File: app/src/sharedTest/java/org/oppia/android/app/devoptions/ForceNetworkTypeFragmentTest.kt (hunk 8 above)
Comment (yashraj-01) [reply app/src/sharedTest/java/org/oppia/android/app/devoptions/ForceNetworkTypeFragmentTest.kt]: Refactored. PTAL. Thanks.

File: app/src/main/java/org/oppia/android/app/devoptions/forcenetworktype/ForceNetworkTypeFragment.kt (hunk 9 above)
Comment (yashraj-01) [reply app/src/main/java/org/oppia/android/app/devoptions/forcenetworktype/ForceNetworkTypeFragment.kt]: Done.

File: app/src/main/res/values/strings.xml (hunk 7 above)
Comment (yashraj-01) [reply app/src/main/res/values/strings.xml]: Done. PTAL. Thanks.

File: app/src/main/java/org/oppia/android/app/devoptions/forcenetworktype/NetworkTypeItemViewModel.kt (hunk 4 above)
Comment (yashraj-01) [reply app/src/main/java/org/oppia/android/app/devoptions/forcenetworktype/NetworkTypeItemViewModel.kt]: I have modified the approach to use strings instead of enum names. PTAL. Thanks.

**Comment by BenHenning** [comment]
Hi. Will need to look at this tomorrow.

File: app/src/main/java/org/oppia/android/app/devoptions/forcenetworktype/NetworkTypeItemViewModel.kt (hunk 4 above)
Comment (BenHenning) [reply app/src/main/java/org/oppia/android/app/devoptions/forcenetworktype/NetworkTypeItemViewModel.kt]: This looks much better--thanks!

File: app/src/main/res/values/strings.xml (hunk 6 above)
Comment (BenHenning) [reply app/src/main/res/values/strings.xml:473]: I don't have a strong opinion here; resolving to unblock the PR.

File: app/src/main/res/values/strings.xml (hunk 7 above)
Comment (BenHenning) [reply app/src/main/res/values/strings.xml]: Much better, thanks!

**Review by BenHenning — COMMENTED** [review]
Thanks @yashraj-01. LGTM, but holding off on approving until the base PR is merged.

Also, @yashraj-01 could you please fix the corresponding static analysis & CI checks after merging the base PR and before assigning this back?

**Comment by yashraj-01** [comment]
> Thanks @yashraj-01. LGTM, but holding off on approving until the base PR is merged.
> 
> Also, @yashraj-01 could you please fix the corresponding static analysis & CI checks after merging the base PR and before assigning this back?

I have updated the PR with the base PR and also fixed the static checks. PTAL. Thanks.

File: app/src/main/java/org/oppia/android/app/devoptions/forcenetworktype/ForceNetworkTypeFragmentPresenter.kt [hunk 10]
```diff
@@ -73,11 +75,15 @@ class ForceNetworkTypeFragmentPresenter @Inject constructor(
     model: NetworkTypeItemViewModel
   ) {
     binding.viewModel = model
-    binding.isNetworkSelected =
-      networkConnectionUtil.getForcedConnectionStatus() == model.networkType
-    binding.networkTypeLayout.setOnClickListener {
-      networkConnectionUtil.setCurrentConnectionStatus(model.networkType)
-      bindingAdapter.notifyDataSetChanged()
+    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/devoptions/forcenetworktype/ForceNetworkTypeFragmentPresenter.kt]: This won't work on older versions of Android, and I'm not sure if this is covered under desugaring support. Suggest using the imperative if-check using ``isPresent()`` instead.

**Review by BenHenning — COMMENTED** [review]
Thanks @yashraj-01. Just had one follow-up comment. Otherwise, the passing CI checks LGTM. Please reassign once the last comment is resolved & #3512 is merged in and this PR updated.

File: app/src/main/java/org/oppia/android/app/devoptions/forcenetworktype/ForceNetworkTypeFragmentPresenter.kt (hunk 10 above)
Comment (yashraj-01) [reply app/src/main/java/org/oppia/android/app/devoptions/forcenetworktype/ForceNetworkTypeFragmentPresenter.kt]: I think Optional is covered under desugaring support [reference](https://developer.android.com/studio/write/java8-support#library-desugaring). But I think it requires building the app with Gradle plugin version 4.0.0+ and the current version is 3.6.1. And I'm not sure what are its requirements for Bazel. Also, Optional is introduced in API level 24 so all its methods are accessible in version > N only (even the get method), so we can't use an if statement here (correct me if I'm wrong). I have already had a TODO for it which I have added here.

Comment (BenHenning) [reply app/src/main/java/org/oppia/android/app/devoptions/forcenetworktype/ForceNetworkTypeFragmentPresenter.kt]: Let's use Guava's Optional, instead. That should let us avoid the issue.

**Review by BenHenning — COMMENTED** [review]
Thanks @yashraj-01. Had one follow-up.

File: app/src/main/java/org/oppia/android/app/devoptions/forcenetworktype/ForceNetworkTypeFragmentPresenter.kt (hunk 10 above)
Comment (yashraj-01) [reply app/src/main/java/org/oppia/android/app/devoptions/forcenetworktype/ForceNetworkTypeFragmentPresenter.kt]: Thanks @BenHenning. This solved the issue. Updated the PR to use Guava's Optional instead of Java8.

**Review by BenHenning — APPROVED** [review]
Thanks @yashraj-01. This LGTM!

**Review by anandwana001 — APPROVED** [review]
LGTM for code owner files.
