### PR TITLE
Fix #2213: TopicListControllerTest has failing tests on CI and Fix and Format few other tests

### LINKED ISSUE #2213: TopicListControllerTest has failing tests on CI
TopicListControllerTest has two tests that are currently disabled since they were failing on CI:
- testRetrieveOngoingStoryList_markRecentlyPlayedFracStory0Exp0_ongoingStoryListIsCorrect
- testRetrieveOngoingStoryList_markAllChaptersCompletedInFractions_ongoingStoryListIsCorrect

We should look into reenabling this on CI. Either they are now passing, or changes are needed to fix them.

### PR DESCRIPTION
**Pull request by anandwana001**
## Explanation

Fix #2213 

1. `AdministratorControlsActivityTest.kt` - remove unused testRule and nit fix
2. `HomeActivityTest.kt ` - CI Ignored test fix
3. `ProfileProgressFragmentTest.kt ` - remove `waitForTheView ` and nit fix
4. `TopicListControllerTest.kt` - Fix "Failing on Circle CI." and nit fix

Need to file a separate issue for this point and removing from this PR. 
5. `ExplorationActivityTest.kt ` - remove `waitForTheView `, nit fix
      1 test is only passing on Robolectric as for Espresso we need to check the pause button is visible, but the pause button is visible only in the idle state.
     1 test is ignored, with the same reason above and also not passing on robolectric.  

Screenshot 2020-12-18 at 12 26 48
Screenshot 2020-12-18 at 12 25 28
Screenshot 2020-12-18 at 12 24 20
Screenshot 2020-12-18 at 12 20 43
Screenshot 2020-12-18 at 12 16 14
Screenshot 2020-12-18 at 12 14 13
Screenshot 2020-12-18 at 12 05 47

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

File: app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt [hunk 1]
```diff
@@ -521,11 +492,10 @@ class ExplorationActivityTest {
 
   // TODO (#1855): Resolve ktlint max line in app module test
   // TODO(#89): The ExplorationActivity takes time to finish. This test case is failing currently.
+  @RunOn(TestPlatform.ROBOLECTRIC)
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt]: @BenHenning The test case here needs to check the visibility of the pause button, but the button is only visible when the audio plays and it's an idle state. 

How should we do this? 
or it seems like a robolectric test only?

Comment (BenHenning) [reply app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt]: We need a way to reasonably fake audio on Espresso. Is it possible to simulate different audio states through the fake audio library? E.g. could we tell the fake audio library to provide a playing state when the play button is clicked for both Robolectric & Espresso?

Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt]: https://github.com/oppia/oppia-android/issues/2255

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityTest.kt [hunk 2]
```diff
@@ -428,18 +311,11 @@ class AdministratorControlsActivityTest {
...
-      )
+      scrollToPosition(position = 4)
       onView(withId(R.id.log_out_text_view)).perform(click())
-      onView(withText(R.string.log_out_dialog_message)).inRoot(isDialog())
-        .check(matches(isDisplayed()))
-      onView(withText(R.string.log_out_dialog_okay_button)).inRoot(isDialog())
-        .check(matches(isDisplayed()))
-      onView(withText(R.string.log_out_dialog_cancel_button)).inRoot(isDialog())
-        .check(matches(isDisplayed()))
+      verifyTextInDialog(textInDialog = context.getString(R.string.log_out_dialog_message))
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityTest.kt]: If we only pass in a string, you could also change verifyTextInDialog to take a ``@StringRes`` string resource ID and retrieve the string from the context in the helper.

File: app/src/sharedTest/java/org/oppia/android/app/profileprogress/ProfileProgressFragmentTest.kt [hunk 3]
```diff
@@ -726,51 +628,37 @@ class ProfileProgressFragmentTest {
...
-
-        // Couldn't match in time.
-        throw PerformException.Builder()
-          .withActionDescription(description)
-          .withViewDescription(HumanReadables.describe(view))
-          .withCause(TimeoutException())
-          .build()
-      }
-    }
+  // TODO(#2208): Create helper function in Test for RecyclerView
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/profileprogress/ProfileProgressFragmentTest.kt]: Could we just go ahead and implement the verify version of this rather than implementing a solution that we want to change, anyway?

File: domain/src/test/java/org/oppia/android/domain/topic/TopicListControllerTest.kt [hunk 4]
```diff
@@ -238,7 +214,7 @@ class TopicListControllerTest {
   }
 
   @Test
-  @Ignore("Failing on Circle CI.")
+
```
Comment (BenHenning) [inline domain/src/test/java/org/oppia/android/domain/topic/TopicListControllerTest.kt]: Remove empty newline.

File: domain/src/test/java/org/oppia/android/domain/topic/TopicListControllerTest.kt [hunk 5]
```diff
@@ -616,6 +591,10 @@ class TopicListControllerTest {
     return Date().time - NINE_DAYS_IN_MS
   }
 
+  private fun retrieveTopicSummaryFromTopicList(index: Int): TopicSummary {
+    return topicListController.getTopicList().value!!.getOrThrow().getTopicSummary(index)
```
Comment (BenHenning) [inline domain/src/test/java/org/oppia/android/domain/topic/TopicListControllerTest.kt]: Hmm maybe wait until #2253 is merged, first, since it will largely change your approach here.

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @anandwana001! Given that the audio stuff isn't relevant here anymore, the other changes largely LGTM. Just a few nits.

File: domain/src/test/java/org/oppia/android/domain/topic/TopicListControllerTest.kt (hunk 4 above)
Comment (anandwana001) [reply domain/src/test/java/org/oppia/android/domain/topic/TopicListControllerTest.kt]: Done

File: domain/src/test/java/org/oppia/android/domain/topic/TopicListControllerTest.kt (hunk 5 above)
Comment (anandwana001) [reply domain/src/test/java/org/oppia/android/domain/topic/TopicListControllerTest.kt]: Done

File: app/src/sharedTest/java/org/oppia/android/app/profileprogress/ProfileProgressFragmentTest.kt (hunk 3 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/profileprogress/ProfileProgressFragmentTest.kt]: done

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityTest.kt (hunk 2 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityTest.kt]: done

**Comment by BenHenning** [comment]
Hi--sorry will need to look at this tomorrow.

File: domain/src/test/java/org/oppia/android/domain/topic/TopicListControllerTest.kt [hunk 6]
```diff
@@ -604,8 +619,11 @@ class TopicListControllerTest {
     return Date().time - NINE_DAYS_IN_MS
   }
 
-  private fun retrieveTopicSummaryFromTopicList(index: Int): TopicSummary {
-    return topicListController.getTopicList().value!!.getOrThrow().getTopicSummary(index)
+  private fun verifyObserverOfTopicListLiveData() {
```
Comment (BenHenning) [inline domain/src/test/java/org/oppia/android/domain/topic/TopicListControllerTest.kt]: The name isn't really describing what's being verified. What might be a cleaner approach could be something like:

```kotlin
fun retrieveTopicList(): TopicList {
  val topicListLiveData = ...
  ...
}
```

Then, tests would use the return result rather than resulting on the captor. This is a bit cleaner since it assumes success and abstracts away unrelated details (such as the LiveData mechanism). That being said, you should add a verify to ensure it's successful.

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @anandwana001! Generally LGTM--just have one comment.

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Review by BenHenning — APPROVED** [review]
Thanks @anandwana001!

**Comment by BenHenning** [comment]
Also heads up that there appear to be conflicts.
