### PR TITLE
Fix #4532: Prevent multiple concept card fragments

### LINKED ISSUE #4532: Multiple tabs are opening on clicking the concept cards link thrice
**Describe the bug**
Multiple tabs are opening on clicking the concept cards link thrice

**To Reproduce**
1. Go to 'Percentages' - Revision
2. Click on 'Converting Percentages to Decimals'
3. Scroll down to click on equicalent fraction link multiple times
4. See the no.of tabs opened

**Expected behavior**
Since the same link is clicked multiple times, single tab must be opened instead of multiple tabs

**Demonstration**
https://user-images.githubusercontent.com/101634267/186579350-9d2f05b5-d408-40f0-aaa2-2afeb82b0d4b.mp4

**Environment**
Device name: One plus Nord2 5G
Android version : Android 11
App version : 0.8-alpha-091b45a188

### PR DESCRIPTION
**Pull request by masclot**
## Explanation

Fix #4532: only allow one concept card open at a time. If the new new concept card has the same skill id as an existing one, do not open and instead reuse the existing one. 

I modified a couple of concept card data for dev so that they link to each other. This change is not necessary for this PR to work, but it allows manually testing the scenario where a concept car links to another.

Current behavior:
[multiple concept cards allowed, even with same skill id.webm](https://user-images.githubusercontent.com/103062089/232325925-d9ce7ad2-a260-46a8-a23a-075d0152f48e.webm)

New behavior:
[ConceptCard deduplication demo.webm](https://user-images.githubusercontent.com/103062089/232325566-96c74599-a5b8-4201-9feb-37f71c34649c.webm)

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### CODE REVIEW

**Comment by BenHenning** [comment]
@masclot is this ready for review or did you open the draft so that people can help with specific parts? Just wanted to make sure that we aren't inadvertently ignoring this. :)

**Comment by masclot** [comment]
> @masclot is this ready for review or did you open the draft so that people can help with specific parts? Just wanted to make sure that we aren't inadvertently ignoring this. :)

It is not ready. Since the change is not trivial, I just wanted to show what my idea is, so that I get early comments. @adhiamboperes already commented on chat.

**Comment by masclot** [comment]
@adhiamboperes PTAL

**Comment by masclot** [comment]
@BenHenning PTAL

**Comment by masclot** [comment]
The error in the checks seems to be temporal:

\# A fatal error has been detected by the Java Runtime Environment:
\#
\#  SIGSEGV (0xb) at pc=0x00007f02ba37d3e0, pid=2671, tid=2685

Could anybody rerun them?

**Comment by adhiamboperes** [comment]
Thanks @masclot! I took a first pass, and I'll be able to provide more specific feedback in the next pass.

-  Since you've made changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files , please have their rationale included in the PR explanation.
- There are some unrelated commits/changes, please remove them.

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @masclot! I took a first pass, and I'll be able to provide more specific feedback in the next pass.

-  Since you've made changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files , please have their rationale included in the PR explanation.
- There are some unrelated commits/changes, please remove them.

**Comment by BenHenning** [comment]
Hi @masclot. Apologies, will need to take a look at this tomorrow.

Also updating this to the latest develop branch.

File: app/src/main/java/org/oppia/android/app/testing/ConceptCardFragmentTestActivity.kt [hunk 1]
```diff
@@ -31,15 +31,15 @@ class ConceptCardFragmentTestActivity : InjectableAppCompatActivity(), ConceptCa
   }
 
   private fun getConceptCardFragment(): ConceptCardFragment? {
-    return supportFragmentManager.findFragmentByTag(TAG_CONCEPT_CARD_DIALOG) as ConceptCardFragment?
+    return supportFragmentManager.fragments.singleOrNull { fragment ->
+      fragment is ConceptCardFragment
+    } as ConceptCardFragment?
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/testing/ConceptCardFragmentTestActivity.kt]:
```suggestion
    return supportFragmentManager.fragments.filterIsInstance<ConceptCardFragment>().single()
```

Bit more robust and equivalent.

File: app/src/main/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragment.kt [hunk 2]
```diff
@@ -22,23 +23,74 @@ class ConceptCardFragment : InjectableDialogFragment() {
...
+
+    /**
+     * Removes any [ConceptCardFragment] in the given FragmentManager that is not of the given
+     * skill Id. If no [ConceptCardFragment] remains, creates a new fragment to show a concept card
+     * for the given skill id.
+     *
+     * @param skillId the skill ID for which a concept card should be loaded.
+     * @param profileId the profile in which the concept card will be shown.
+     * @param fragmentManager the [FragmentManager] where to show the concept card.
+     * @return the fragment created or null if none.
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragment.kt]:
```suggestion
     * @param skillId the skill ID for which a concept card should be loaded
     * @param profileId the profile in which the concept card will be shown
     * @param fragmentManager the [FragmentManager] where to show the concept card
     * @return the fragment created or null if none
```

Small nit on punctuation consistency for KDoc params.

File: app/src/main/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragment.kt [hunk 3]
```diff
@@ -22,23 +23,74 @@ class ConceptCardFragment : InjectableDialogFragment() {
...
+     */
+    fun bringToFrontOrCreateIfNew(
+      skillId: String,
+      profileId: ProfileId,
+      fragmentManager: FragmentManager
+    ): ConceptCardFragment? {
+      // The UI is recreated when changing profile ids, so no need to include it in the tag name.
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragment.kt]: This comment seems a bit out-of-band--perhaps add more context to explain the potential issue & why this means it isn't a problem?

File: app/src/main/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragment.kt [hunk 4]
```diff
@@ -75,4 +127,6 @@ class ConceptCardFragment : InjectableDialogFragment() {
     super.onStart()
     dialog?.window?.setWindowAnimations(R.style.FullScreenDialogStyle)
   }
+
+  private fun skillId(): String? = arguments?.getStringFromBundle(SKILL_ID_ARGUMENT_KEY)
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragment.kt]: nit: ``getSkillId`` per codebase consistency.

File: app/src/main/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragment.kt [hunk 5]
```diff
@@ -22,23 +23,74 @@ class ConceptCardFragment : InjectableDialogFragment() {
...
+        val transaction = fragmentManager.beginTransaction()
+        for (toRemove in conceptCardsWithDifferentSkillId) {
+          transaction.remove(toRemove)
+        }
+        transaction.commitNow()
+      }
+      if (!found) {
+        return showNewInstance(skillId, profileId, fragmentManager)
+      }
+      return null
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragment.kt]:
```suggestion
      return if (allConceptCards.size <= conceptCardsWithDifferentSkillId.size) {
        showNewInstance(skillId, profileId, fragmentManager)
      } else null
```

Some minor simplifications.

File: app/src/sharedTest/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragmentTest.kt [hunk 6]
```diff
@@ -363,6 +370,112 @@ class ConceptCardFragmentTest {
     }
   }
 
+  @Test
+  fun testConceptCardFragment_launchSeveralConceptCardsWithSameSkill_onlyTheFirstOne() {
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragmentTest.kt]:
```suggestion
  fun testConceptCardFragment_launchSeveralConceptCardsWithSameSkill_onlyTheFirstShows() {
```

File: app/src/sharedTest/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragmentTest.kt [hunk 7]
```diff
@@ -363,6 +370,112 @@ class ConceptCardFragmentTest {
...
+        Assert.assertNotNull(fragment)
+        Assert.assertNull(
+          ConceptCardFragment.bringToFrontOrCreateIfNew(
+            TEST_SKILL_ID_0,
+            ProfileId.getDefaultInstance(),
+            activity.supportFragmentManager
+          )
+        )
+        Assert.assertEquals(1, activity.supportFragmentManager.fragments.size)
+        Assert.assertEquals(fragment, activity.supportFragmentManager.fragments[0])
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragmentTest.kt]: Prefer using Truth assertions over JUnit's (and statically import them). Ditto for the other tests.

File: app/src/main/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragment.kt [hunk 8]
```diff
@@ -22,23 +23,74 @@ class ConceptCardFragment : InjectableDialogFragment() {
...
+     * @param skillId the skill ID for which a concept card should be loaded.
+     * @param profileId the profile in which the concept card will be shown.
+     * @param fragmentManager the [FragmentManager] where to show the concept card.
+     * @return the fragment created or null if none.
+     */
+    fun bringToFrontOrCreateIfNew(
+      skillId: String,
+      profileId: ProfileId,
+      fragmentManager: FragmentManager
+    ): ConceptCardFragment? {
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragment.kt]: Is the return actually useful? It seems like none of the callsites use it (unless I missed one of them).

File: app/src/sharedTest/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragmentTest.kt [hunk 9]
```diff
@@ -363,6 +370,112 @@ class ConceptCardFragmentTest {
...
+        fragmentSkill0!!.showNow(activity.supportFragmentManager, fragmentSkill0.tag)
+        Assert.assertEquals(2, activity.supportFragmentManager.fragments.size)
+        ConceptCardFragment.dismissAll(activity.supportFragmentManager)
+        Assert.assertEquals(0, activity.supportFragmentManager.fragments.size)
+      }
+    }
+  }
+
+  @Test
+  fun testConceptCardFragment_severalConceptCards_dismissAll() {
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragmentTest.kt]: Perhaps add a test for dismissAll when there are no cards?

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @masclot! Apologies for the delayed review.

I think this solution is fantastic. It's much more elegant and UI-isolated than I was originally thinking, so I'm quite happy with what you've come up with here. Mostly had style nits--PTAL.

File: app/src/main/java/org/oppia/android/app/testing/ConceptCardFragmentTestActivity.kt (hunk 1 above)
Comment (masclot) [reply app/src/main/java/org/oppia/android/app/testing/ConceptCardFragmentTestActivity.kt]: Done, but kept singleOrNull() instead of single() to keep the original method signature.

File: app/src/main/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragment.kt (hunk 2 above)
Comment (masclot) [reply app/src/main/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragment.kt]: Done

File: app/src/main/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragment.kt (hunk 8 above)
Comment (masclot) [reply app/src/main/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragment.kt]: I use the return in tests.

File: app/src/main/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragment.kt (hunk 3 above)
Comment (masclot) [reply app/src/main/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragment.kt]: Expanded the comment. I could also complicate the code so that the comment is not necessary.

File: app/src/main/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragment.kt (hunk 4 above)
Comment (masclot) [reply app/src/main/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragment.kt]: Done

File: app/src/sharedTest/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragmentTest.kt (hunk 6 above)
Comment (masclot) [reply app/src/sharedTest/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragmentTest.kt]: Done

File: app/src/sharedTest/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragmentTest.kt (hunk 7 above)
Comment (masclot) [reply app/src/sharedTest/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragmentTest.kt]: Done

File: app/src/sharedTest/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragmentTest.kt (hunk 9 above)
Comment (masclot) [reply app/src/sharedTest/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragmentTest.kt]: Done

File: app/src/main/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragment.kt (hunk 5 above)
Comment (masclot) [reply app/src/main/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragment.kt]: Done

**Comment by masclot** [comment]
> Thanks @masclot! I took a first pass, and I'll be able to provide more specific feedback in the next pass.
> 
> * Since you've made changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files , please have their rationale included in the PR explanation.
> * There are some unrelated commits/changes, please remove them.

@adhiamboperes 
I added a comment about the asset changes  to the PR description.
I couldn't find unrelated commits/changes. Could you point me to them?

**Comment by masclot** [comment]
@BenHenning 
@adhiamboperes 
PTAL

**Review by adhiamboperes — APPROVED** [review]
I've looked over your changes and they look really good!

File: app/src/main/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragment.kt (hunk 8 above)
Comment (BenHenning) [reply app/src/main/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragment.kt]: Having an API specifically for tests isn't generally preferred unless that API may be used by non-tests in the future, or is test-only (since it sort of skews the expected usage of the API between production and test contexts).

If the goal here is just to verify that the correct outcome happens, could we instead inspect the activity's fragment manager to see if the correct fragment has been created/not created rather than depending on the return value of this function? I think that will result in both more robust tests and a cleaner API.

File: app/src/sharedTest/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragmentTest.kt [hunk 10]
```diff
@@ -371,24 +371,24 @@ class ConceptCardFragmentTest {
...
           ConceptCardFragment.bringToFrontOrCreateIfNew(
             TEST_SKILL_ID_0,
             ProfileId.getDefaultInstance(),
             activity.supportFragmentManager
           )
-        )
-        Assert.assertEquals(1, activity.supportFragmentManager.fragments.size)
-        Assert.assertEquals(fragment, activity.supportFragmentManager.fragments[0])
+        ).isNull()
+        assertThat(activity.supportFragmentManager.fragments.size).isEqualTo(1)
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragmentTest.kt]:
```suggestion
        assertThat(activity.supportFragmentManager.fragments).hasSize(1)
```

More Truth-idiomatic version. Ditto elsewhere.

File: app/src/main/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragment.kt (hunk 3 above)
Comment (BenHenning) [reply app/src/main/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragment.kt]: I think the new comment is much clearer now--thanks!

File: app/src/main/java/org/oppia/android/app/testing/ConceptCardFragmentTestActivity.kt (hunk 1 above)
Comment (BenHenning) [reply app/src/main/java/org/oppia/android/app/testing/ConceptCardFragmentTestActivity.kt]: Ah, I think I meant ``singleOrNull`` originally (per your existing code)--good catch.

**Review by BenHenning — COMMENTED** [review]
Thanks @masclot! Just had a few follow-ups--PTAL.

File: app/src/sharedTest/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragmentTest.kt (hunk 10 above)
Comment (masclot) [reply app/src/sharedTest/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragmentTest.kt]: Done

File: app/src/main/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragment.kt (hunk 8 above)
Comment (masclot) [reply app/src/main/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragment.kt]: Done

**Comment by masclot** [comment]
Addressed the last two conversations.
@BenHenning PTAL

File: app/src/sharedTest/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragmentTest.kt [hunk 11]
```diff
@@ -420,23 +422,25 @@ class ConceptCardFragmentTest {
...
-        assertThat(fragmentSkill1).isNotNull()
-        fragmentSkill0!!.showNow(activity.supportFragmentManager, fragmentSkill0.tag)
-        assertThat(activity.supportFragmentManager.fragments.size).isEqualTo(2)
+          activity.supportFragmentManager.fragments.filterIsInstance<ConceptCardFragment>().single()
+        assertThat(fragmentSkill1).isNotEqualTo(fragmentSkill0)
+        fragmentSkill0.showNow(activity.supportFragmentManager, fragmentSkill0.tag)
+        assertThat(activity.supportFragmentManager.fragments).hasSize(2)
         ConceptCardFragment.dismissAll(activity.supportFragmentManager)
-        assertThat(activity.supportFragmentManager.fragments.size).isEqualTo(0)
+        assertThat(activity.supportFragmentManager.fragments).hasSize(0)
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragmentTest.kt]:
```suggestion
        assertThat(activity.supportFragmentManager.fragments).isEmpty()
```

Small nit: ``isEmpty()`` is the more idiomatic method for this case.

**Review by BenHenning — COMMENTED** [review]
Thanks @masclot! Really sorry for the delayed review here.

The PR LGTM, but had 1 nit left and I think the branch needs to be brought up-to-date with the latest develop changes. Please assign back once both are done and I'll go ahead and kick-off the merge.

File: app/src/sharedTest/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragmentTest.kt (hunk 11 above)
Comment (masclot) [reply app/src/sharedTest/java/org/oppia/android/app/topic/conceptcard/ConceptCardFragmentTest.kt]: Done

**Comment by masclot** [comment]
> Thanks @masclot! Really sorry for the delayed review here.
> 
> The PR LGTM, but had 1 nit left and I think the branch needs to be brought up-to-date with the latest develop changes. Please assign back once both are done and I'll go ahead and kick-off the merge.

I addressed the comment. Regarding "bringing the branch up-to-date with the latest develop changes", I'm not sure I'm doing it right. In Android Studio, I checked out my develop branch and clicked "Update" on it. I then checked-out the branch for this change and also clicked "Update". Would that be enough?

**Comment by masclot** [comment]
I don't think Android Studio -> \<branch-name\> -> Update does a merge.  This menu is what oppia documentation says we should do in Android Studio to update our repository: https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#making-a-local-code-change-using-android-studios-ui-based-github-workflow

Instead I did the following in Android Studio:
- checkout develop
- fetch
- merge upsteam/develop
- checkout \<my-branch\>
- fetch
- merge develop

I hope these steps are good. Please let me know otherwise.

**Review by BenHenning — APPROVED** [review]
Thanks @masclot! Re: updating the branch, I think we have instructions in the wiki for this but I can't find them off hand at the moment (@MohitGupta121 might you know?). We generally recommend doing this via Git CLI since it's easier to "debug" when something goes wrong, and I'm less familiar with the Android Studio Git interface.

PR LGTM!

**Comment by BenHenning** [comment]
Updating to latest develop & enabling auto-merge.
