### PR TITLE
Fix #1871: Fix ProfileChooserFragmentTest for Robolectric 

### LINKED ISSUE #1871: Fix ProfileChooserFragmentTest for Robolectric
Currently, the app module test cases in ProfileChooserFragmentTest are passing on Espresso but they should also pass on Robolectric. Fix these below mentioned files to make sure that the tests pass on Robolectric.

You can run robolectric tests by following these steps: https://github.com/oppia/oppia-android/wiki/Oppia-Android-Testing#running-roboelectric-tests

Fixing test cases will need to introduce TextApplicationComponent. This can be seen [here](https://github.com/oppia/oppia-android/pull/1680/commits/4729d551b86282ce617e1d53f2762416758785a1).

### PR DESCRIPTION
**Pull request by anandwana001**
## Explanation

Fix #1871 

## For Reviewers
Please check the comment below.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

File: app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt [hunk 1]
```diff
@@ -207,6 +212,7 @@ class ProfileChooserFragmentTest {
   fun testProfileChooserFragment_initializeProfiles_checkProfilesLastVisitedTimeIsShown() {
     profileTestHelper.initializeProfiles()
     launch<ProfileChooserActivity>(createProfileChooserActivityIntent()).use {
+      testCoroutineDispatchers.runCurrent()
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt:165]: @BenHenning  There are 4 Ignore test cases like this one, which performs the opening of next activity which actually not supported by Robolectric. Am I missing something here or should we this test espresso-only?

This test case is something which cannot be broken down into pieces to test things separately as this is a collective step to test which require hopping between different screens.

File: app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt [hunk 2]
```diff
@@ -560,36 +564,35 @@ class ProfileChooserFragmentTest {
...
       onView(isRoot()).perform(orientationLandscape())
       it.onActivity { activity ->
         val profileRecyclerView = activity.findViewById<RecyclerView>(
           R.id.profile_recycler_view
         )
         val layoutManager = profileRecyclerView.layoutManager as GridLayoutManager
         if (!activity.resources.getBoolean(R.bool.isTablet)) {
-          assertThat(layoutManager.spanCount).isEqualTo(2)
+          assertThat(layoutManager.spanCount).isEqualTo(1)
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt]: @rt4914 Could you please confirm the span count here? This is related to UI between port and land in mobile and Tablet.

Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt]: with 2, getting an error of 
```
expected: 2
but was : 1
```
Before checking into the test, just to confirm the UI logic are correct.

File: app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt (hunk 1 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt:165]: Workaround -  https://github.com/libon/RobolectricMultipleActivityTestIssue/pull/1/files
This is something we discussed earlier. But, from what I tried till now I feel we cannot achieve such e2e test with testCoroutineDispatchers.

Comment (BenHenning) [reply app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt:165]: How do the test coroutine dispatchers impact this? As I understand it, this is a Robolectric limitation since Robolectric isn't designed to switch between activities.

I'm also not sure I buy that this can't be broken up. This particular test can be split into several:
- testProfileChooserFragment_initialProfiles_clickFirst_opensPinPasswordActivity
- testPinPasswordActivity_inputCorrectPin_opensHomeActivity
- testHomeActivity_validatedProfile_pressBack_closesActivity
- testProfileChooserFragment_afterVisitingHomeActivity_showsJustNowText

Each of these are verifying a single activity, and verify boundaries by:
1. Using an intent matcher to check if a particular activity _would_ be open
2. Ensuring the state for the test is set up equivalently to if you did visit a previous activity (such as in the case of the last test above)

Note that this is generally better testing: it keeps things isolated, and it's verifying a single behavior at one time. Not all of the tests above belong in this suite either--they should be in each corresponding activity's test suite.

You could make the argument that this isn't as thorough since we aren't testing integration boundaries--that's true. We get very *close* to correct with this approach, but this does not replace proper integration/e2e tests. That's fine; we'll be implementing e2e tests in the future. Espresso should be used for unit tests based on our current team practices.

Does this help?

**Comment by BenHenning** [comment]
@anandwana001 left a comment. Please let me know if you want to discuss further.

File: app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt (hunk 2 above)
Comment (rt4914) [reply app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt]: I am confused here.
1. At the top we have mentioned `port-xxhdpi`, will that qualifier work strictly, meaning we cannot rotate? or it will allow landscape?
2. I think this test relates top below mentioned UI and in which case the span should be 2.
Screenshot_1603807239

Comment (rt4914) [reply app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt]: @anandwana001 PTAL

Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt]: shifting to ProfileChooserSpanTest

File: app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt (hunk 1 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt:165]: yes, divided the test cases. Done.

File: app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt [hunk 3]
```diff
@@ -582,99 +335,82 @@ class ProfileChooserFragmentTest {
...
-    return ApplicationProvider.getApplicationContext<Context>().resources
+  private fun scrollToPosition(position: Int) {
+    onView(withId(R.id.profile_recycler_view)).perform(
+      scrollToPosition<RecyclerView.ViewHolder>(
+        position
+      )
+    )
+  }
+
+  private fun matchStringOnProfileListItem(position: Int, targetView: Int, stringToMatch: String) {
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt]: Suggest verify*... here as well.

File: app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt [hunk 4]
```diff
@@ -131,399 +115,170 @@ class ProfileChooserFragmentTest {
...
-          withText(
-            String.format(
-              getResources().getString(R.string.profile_last_used) + " just now"
-            )
-          )
-        )
-      )
+      it.onActivity {
+        data.observeForever { }
+      }
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt]: This is a bit obscure. Suggest putting it behind a helper method, e.g. ``waitForOperationToComplete()`` that takes a live data, calls runCurrent(), then removes the observer. Then, update all methods that need this to call the new helper.

Please make sure the helper clearly documents _why_ the observeForever is needed & why it works. Also, please update the documentation for all the helpers in ProfileTestHelper that could result in this issue with instructions on how to make sure the operations finish (e.g. by adding an observer & calling runCurrent()).

File: app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt [hunk 5]
```diff
@@ -131,399 +115,170 @@ class ProfileChooserFragmentTest {
...
-        atPositionOnView(
-          R.id.profile_recycler_view,
-          0, R.id.profile_last_visited
-        )
-      ).check(
-        matches(
-          isDisplayed()
-        )
-      )
+      it.onActivity {
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt:162]: I think we really need a comment here to specify that doing this observer is simulating visiting the home activity, and how.

File: app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt [hunk 6]
```diff
@@ -131,399 +115,170 @@ class ProfileChooserFragmentTest {
...
-      ).check(
-        matches(
-          withText(
-            String.format(
-              getResources().getString(R.string.profile_last_used) + " just now"
-            )
-          )
-        )
-      )
+      it.onActivity {
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt:187]: Ditto here (copy comment that you add above to provide context here about how this is simulating home activity).

File: app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt [hunk 7]
```diff
@@ -131,399 +115,170 @@ class ProfileChooserFragmentTest {
...
+      testCoroutineDispatchers.runCurrent()
       onView(atPosition(R.id.profile_recycler_view, 0)).perform(click())
       intended(hasComponent(PinPasswordActivity::class.java.name))
     }
   }
 
   @Test
-  // TODO(#973): Fix ProfileChooserFragmentTest
-  @Ignore
-  fun testProfileChooserFragment_clickAddProfile_checkOpensAdminAuthActivity_onBackButton_opensProfileChooserFragment() { // ktlint-disable max-line-length
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt:477]: For this & next test: we shouldn't just be deleting them. Even though we can't test multi-intent flows in Robolectric, we should still be testing the navigation flows. Please re-add as needed and/or link to other tests for parts that are covered in other suites.

File: app/src/main/res/layout-sw600dp-port/profile_chooser_fragment.xml [hunk 8]
```diff
@@ -78,14 +78,15 @@
           android:paddingBottom="@{hasProfileEverBeenAddedValue ? @dimen/profile_chooser_padding_bottom_profile_already_added : @dimen/bottom_white_space}"
           android:requiresFadingEdge="vertical"
           android:scrollbars="none"
+          android:tag="profile_recycler_view"
```
Comment (BenHenning) [inline app/src/main/res/layout-sw600dp-port/profile_chooser_fragment.xml:81]: Why is this needed?

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @anandwana001! Just a few comments.

File: app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt (hunk 3 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt]: Adding in https://github.com/oppia/oppia-android/issues/2208

File: app/src/main/res/layout-sw600dp-port/profile_chooser_fragment.xml (hunk 8 above)
Comment (anandwana001) [reply app/src/main/res/layout-sw600dp-port/profile_chooser_fragment.xml:81]: We are using Tag in the `ProfileChooserSpanTest` to get the RecyclerView and use the span in the GridLayoutManager. 
https://github.com/oppia/oppia-android/blob/8e4b43938a5f07e51124fefdec4e39385922ac47/app/src/test/java/org/oppia/android/app/testing/ProfileChooserSpanTest.kt#L323

File: app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt (hunk 7 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt:477]: Done

File: app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt (hunk 5 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt:162]: Done

File: app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt (hunk 6 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt:187]: Done

File: app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt (hunk 4 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt]: Done

**Comment by BenHenning** [comment]
@anandwana001 is this ready for another review?

**Comment by anandwana001** [comment]
> @anandwana001 is this ready for another review?

Yes, missed assigning last night.

File: app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt [hunk 9]
```diff
@@ -156,8 +157,9 @@ class ProfileChooserFragmentTest {
   fun testProfileChooserFragment_afterVisitingHomeActivity_showsJustNowText() {
     val data = profileTestHelper.initializeProfiles()
     launch<ProfileChooserActivity>(createProfileChooserActivityIntent()).use {
+      // Waiting for the simulation that HomeActivity is visited once.
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt]:
```suggestion
      // Note that this wait is needed to simulate HomeActivity being visited by ensuring a profile was previously logged in.
```

(may require line wrapping). Please copy elsewhere (as needed).

File: app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt [hunk 10]
```diff
@@ -168,19 +170,24 @@ class ProfileChooserFragmentTest {
...
       ).check(matches(isDisplayed()))
       matchStringOnProfileListItem(
-        position = 0,
+        itemPosition = 0,
         targetView = R.id.profile_last_visited,
         stringToMatch = "${context.getString(R.string.profile_last_used)} just now"
       )
+      // Forcing to remove the LiveData Observer.
+      it.onActivity {
+        profileTestHelper.forceToCompleteOperation(data)
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt]: Why does this need to be done again? Ditto elsewhere?

File: app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt [hunk 11]
```diff
@@ -403,11 +436,16 @@ class ProfileChooserFragmentTest {
     )
   }
 
-  private fun matchStringOnProfileListItem(position: Int, targetView: Int, stringToMatch: String) {
+  // TODO(#2208): Create helper function in Test for RecyclerView
+  private fun matchStringOnProfileListItem(
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt]: Prefer: verify*

File: app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt [hunk 12]
```diff
@@ -390,6 +401,28 @@ class ProfileChooserFragmentTest {
     }
   }
 
+  @Test
+  fun testProfileChooserFragment_clickAdminControls_checkOpensAdminAuthActivity() {
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt]:
```suggestion
  fun testProfileChooserFragment_clickAdminControls_opensAdminAuthActivity() {
```

File: app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt [hunk 13]
```diff
@@ -390,6 +401,28 @@ class ProfileChooserFragmentTest {
...
+    launch<ProfileChooserActivity>(createProfileChooserActivityIntent()).use {
+      testCoroutineDispatchers.runCurrent()
+      onView(withId(R.id.administrator_controls_linear_layout)).perform(click())
+      intended(hasComponent(AdminAuthActivity::class.java.name))
+      intended(hasExtra(AdminAuthActivity.getIntentKey(), 0))
+    }
+  }
+
+  @Test
+  fun testProfileChooserFragment_clickAddProfile_checkOpensAdminAuthActivity() {
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt]:
```suggestion
  fun testProfileChooserFragment_clickAddProfile_opensAdminAuthActivity() {
```

File: testing/src/main/java/org/oppia/android/testing/profile/ProfileTestHelper.kt [hunk 14]
```diff
@@ -13,7 +14,13 @@ class ProfileTestHelper @Inject constructor(
   private val profileManagementController: ProfileManagementController,
   private val testCoroutineDispatchers: TestCoroutineDispatchers
 ) {
-  /** Creates one admin profile and one user profile. Logs in to admin profile. */
+
+  private val observer = Observer<AsyncResult<Any?>> { }
+
+  /** Creates one admin profile and one user profile. Logs in to admin profile.
```
Comment (BenHenning) [inline testing/src/main/java/org/oppia/android/testing/profile/ProfileTestHelper.kt]: Please fix KDoc formatting to follow style guide & be consistent with other KDocs in the codebase (there are multiple formatting issues here). Ditto below.

File: testing/src/main/java/org/oppia/android/testing/profile/ProfileTestHelper.kt [hunk 15]
```diff
@@ -13,7 +14,13 @@ class ProfileTestHelper @Inject constructor(
...
+   *
+   * The return type is LiveData and it requires a observer to observe it forever.
```
Comment (BenHenning) [inline testing/src/main/java/org/oppia/android/testing/profile/ProfileTestHelper.kt]:
```suggestion
   * @returns a [LiveData] that indicates when the login is complete. Note that this if is not observed, the login will not be performed.
```

(may need line wrapping). Please update other KDocs to match the wording/concepts/formatting.

File: testing/src/main/java/org/oppia/android/testing/profile/ProfileTestHelper.kt [hunk 16]
```diff
@@ -92,4 +102,17 @@ class ProfileTestHelper @Inject constructor(
     testCoroutineDispatchers.runCurrent()
     return result
   }
+
+  /** ObserveForever is needed in order to complete the Action which returns the LiveData.
```
Comment (BenHenning) [inline testing/src/main/java/org/oppia/android/testing/profile/ProfileTestHelper.kt]: This should describe what the helper does, then why it's needed. The 'observeForever' is irrelevant--that's an implementation detail. All callers care about is when & why they should call this, so we should answer that.

File: testing/src/main/java/org/oppia/android/testing/profile/ProfileTestHelper.kt [hunk 17]
```diff
@@ -92,4 +102,17 @@ class ProfileTestHelper @Inject constructor(
...
+   * Any Action which responds with the LiveData must need to observe it, to update the data
+   * on screen while running espresso test cases.
+   * */
+  fun waitForOperationToComplete(data: LiveData<AsyncResult<Any?>>) {
+    data.observeForever(observer)
+  }
+
+  /** Need to remove the observer as it is observing forever. */
+  fun forceToCompleteOperation(data: LiveData<AsyncResult<Any?>>) {
```
Comment (BenHenning) [inline testing/src/main/java/org/oppia/android/testing/profile/ProfileTestHelper.kt]: I wasn't thinking about using a helper, but since you are I suggest just omitting the remove observer. It's fine for testing purposes just to keep the observer registered.

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @anandwana001. Left a few more comments. PTAL.

File: app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt (hunk 10 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt]: We cannot remove the observer before testing the actual thing, so the flow is like
add observer, test, remove observer, else the test will freeze and nothing get observed.

File: testing/src/main/java/org/oppia/android/testing/profile/ProfileTestHelper.kt (hunk 17 above)
Comment (anandwana001) [reply testing/src/main/java/org/oppia/android/testing/profile/ProfileTestHelper.kt]: done

File: testing/src/main/java/org/oppia/android/testing/profile/ProfileTestHelper.kt (hunk 15 above)
Comment (anandwana001) [reply testing/src/main/java/org/oppia/android/testing/profile/ProfileTestHelper.kt]: done

File: app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt (hunk 13 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt]: done

File: app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt (hunk 12 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt]: done

File: app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt (hunk 11 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt]: done

File: app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt (hunk 9 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt]: done

File: testing/src/main/java/org/oppia/android/testing/profile/ProfileTestHelper.kt (hunk 14 above)
Comment (anandwana001) [reply testing/src/main/java/org/oppia/android/testing/profile/ProfileTestHelper.kt]: got it, done. https://kotlinlang.org/docs/reference/kotlin-doc.html

File: testing/src/main/java/org/oppia/android/testing/profile/ProfileTestHelper.kt (hunk 16 above)
Comment (anandwana001) [reply testing/src/main/java/org/oppia/android/testing/profile/ProfileTestHelper.kt]: Done, let me know if it is correct. 

```kdocs
  /**
   * While performing any action based on the LiveData, this helper function should be used.
   * Without this helper function the LiveData cannot be accessed.
   *
   * @param data is the LiveData which needs to accessed while performing action.
   */
```

File: testing/src/main/java/org/oppia/android/testing/profile/ProfileTestHelper.kt [hunk 18]
```diff
@@ -103,16 +107,13 @@ class ProfileTestHelper @Inject constructor(
...
 
-  /** ObserveForever is needed in order to complete the Action which returns the LiveData.
-   * Any Action which responds with the LiveData must need to observe it, to update the data
-   * on screen while running espresso test cases.
-   * */
+  /**
+   * While performing any action based on the LiveData, this helper function should be used.
+   * Without this helper function the LiveData cannot be accessed.
+   *
+   * @param data is the LiveData which needs to accessed while performing action.
```
Comment (BenHenning) [inline testing/src/main/java/org/oppia/android/testing/profile/ProfileTestHelper.kt]:
```suggestion
   * While performing any action based on the LiveData (see other methods above), this helper function should be used to ensure the operation corresponding to the LiveData properly completes.
   *
   * @param data is the LiveData which needs to accessed while performing action
```

Some suggested rewording (may require line-wrapping).

File: testing/src/main/java/org/oppia/android/testing/profile/ProfileTestHelper.kt (hunk 16 above)
Comment (BenHenning) [reply testing/src/main/java/org/oppia/android/testing/profile/ProfileTestHelper.kt]: Left a comment regarding this directly. Thanks!

**Review by BenHenning — APPROVED** [review]
Thanks @anandwana001! Just one comment--PR overall LGTM. Please feel free to resolve my comment & merge after addressing it.

File: testing/src/main/java/org/oppia/android/testing/profile/ProfileTestHelper.kt (hunk 18 above)
Comment (anandwana001) [reply testing/src/main/java/org/oppia/android/testing/profile/ProfileTestHelper.kt]: Done

File: app/src/main/res/layout-sw600dp-port/profile_chooser_fragment.xml (hunk 8 above)
Comment (anandwana001) [reply app/src/main/res/layout-sw600dp-port/profile_chooser_fragment.xml:81]: Resolving on behalf of Ben

File: app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt (hunk 7 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt:477]: Resolving on behalf of Ben

File: app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt (hunk 4 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt]: Resolving on behalf of Ben

File: app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt (hunk 3 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt]: Resolving on behalf of Ben
