### PR TITLE
Fixes part of #935: Optimised test cases for HDPI devices ( Packages A-H)

### LINKED ISSUE #935: Optimise app module test cases
Currently all `app` module test cases pass for high-end devices like Pixel but we need to optimise these test cases to make sure that they pass on HDPI devices also, preferably `Nexus S - emulator`.

Except `player` package in test cases all test cases should pass on `HDPI` device.

When you create a new emulator device make sure that these three animations are turned off in developer options:
Screenshot 2020-04-02 at 11 38 17 AM

### PR DESCRIPTION
**Pull request by NullByte08**
## Explanation
Partially fixes #935 
Tests made compatible for `HDPI` devices for packages `administratorcontrols` to `home`. All the tests pass successfully.

## Checklist

- [ ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

File: app/src/sharedTest/java/org/oppia/app/administratorcontrols/AdministratorControlsActivityTest.kt [hunk 1]
```diff
@@ -261,6 +271,69 @@ class AdministratorControlsActivityTest {
     )
   }
 
+  fun nestedScrollTo(): ViewAction {
```
Comment (rt4914) [inline app/src/sharedTest/java/org/oppia/app/administratorcontrols/AdministratorControlsActivityTest.kt]: Nit update on these functions:

Also, at the top of function add a comment in which you can mention the URL from which you have taken this code snippet.

```
  private fun nestedScrollTo(): ViewAction {
    return object : ViewAction {
      override fun getDescription(): String {
        return "View is not NestedScrollView"
      }

      override fun getConstraints(): org.hamcrest.Matcher<View> {
        return Matchers.allOf(
          ViewMatchers.isDescendantOfA(ViewMatchers.isAssignableFrom(NestedScrollView::class.java))
        )
      }

      override fun perform(uiController: UiController, view: View) {
        try {
          val nestedScrollView =
            findFirstParentLayoutOfClass(view, NestedScrollView::class.java!!) as NestedScrollView
          nestedScrollView.scrollTo(0, view.top)
        } catch (e: Exception) {
          throw PerformException.Builder()
            .withActionDescription(this.description)
            .withViewDescription(HumanReadables.describe(view))
            .withCause(e)
            .build()
        }
        uiController.loopMainThreadUntilIdle()
      }
    }
  }

  private fun findFirstParentLayoutOfClass(view: View, parentClass: Class<out View>): View {
    var parent: ViewParent = FrameLayout(view.context)
    lateinit var incrementView: ViewParent
    var i = 0
    while (!(parent.javaClass === parentClass)) {
      parent = if (i == 0) {
        findParent(view)
      } else {
        findParent(incrementView)
      }
      incrementView = parent
      i++
    }
    return parent as View
  }
```

File: app/src/sharedTest/java/org/oppia/app/home/HomeActivityTest.kt [hunk 2]
```diff
@@ -603,4 +607,4 @@ class HomeActivityTest {
       )
     }
   }
-}
+}
```
Comment (rt4914) [inline app/src/sharedTest/java/org/oppia/app/home/HomeActivityTest.kt]: EOF is missing, add one blank line at the end.

**Review by rt4914 — CHANGES_REQUESTED** [review]
LGTM, nit changes suggested.

File: app/src/sharedTest/java/org/oppia/app/administratorcontrols/AdministratorControlsActivityTest.kt (hunk 1 above)
Comment (NullByte08) [reply app/src/sharedTest/java/org/oppia/app/administratorcontrols/AdministratorControlsActivityTest.kt]: I made the change. It is not showing up here. You can see the change in "Files Changed".

**Comment by NullByte08** [comment]
@rt4914 Please review. Thanks.

File: app/src/sharedTest/java/org/oppia/app/administratorcontrols/AdministratorControlsActivityTest.kt (hunk 1 above)
Comment (rt4914) [reply app/src/sharedTest/java/org/oppia/app/administratorcontrols/AdministratorControlsActivityTest.kt]: There are still a lot of pending suggestions. Like usage of kotlin code instead of java code, one blank line between functions, make the functions private. You can use this below code (basically all possible warnings/suggestions should be fixed):

```
  /** Functions nestedScrollTo() and findFirstParentLayoutOfClass() taken from: https://stackoverflow.com/a/46037284/8860848 */
  private fun nestedScrollTo(): ViewAction {
    return object : ViewAction {
      override fun getDescription(): String {
        return "View is not NestedScrollView"
      }

      override fun getConstraints(): org.hamcrest.Matcher<View> {
        return allOf(
          isDescendantOfA(isAssignableFrom(NestedScrollView::class.java))
        )
      }

      override fun perform(uiController: UiController, view: View) {
        try {
          val nestedScrollView =
            findFirstParentLayoutOfClass(view, NestedScrollView::class.java) as NestedScrollView
          nestedScrollView.scrollTo(0, view.top)
        } catch (e: Exception) {
          throw PerformException.Builder()
            .withActionDescription(this.description)
            .withViewDescription(HumanReadables.describe(view))
            .withCause(e)
            .build()
        }
        uiController.loopMainThreadUntilIdle()
      }
    }
  }

  private fun findFirstParentLayoutOfClass(view: View, parentClass: Class<out View>): View {
    var parent: ViewParent = FrameLayout(view.context)
    lateinit var incrementView: ViewParent
    var i = 0
    while (!(parent.javaClass === parentClass)) {
      parent = if (i == 0) {
        findParent(view)
      } else {
        findParent(incrementView)
      }
      incrementView = parent
      i++
    }
    return parent as View
  }

  private fun findParent(view: View): ViewParent {
    return view.parent
  }

  private fun findParent(view: ViewParent): ViewParent {
    return view.parent
  }
```

**Review by rt4914 — APPROVED** [review]
Suggested change for the Admin functions.

**Comment by NullByte08** [comment]
@rt4914 Changes done.

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.
