### PR TITLE
Fix #2092: Make dialog survive config change

### LINKED ISSUE #2092: Dialog disappears on orientation change
**Describe the bug**
In `ProfileEdit` screen on orientation change if the dialog is already shown, it will disappear.

**To Reproduce**
1. Go to ProfileChooser screen and create atleast 2 profiles.
2. In `ProfileChooser` screen click on `Administrator Controls`
3. Enter your pin and go to `AdministratorControlsActivity`
4. Click `Edit Profiles`
5. Select `non-admin` profile.
6. Scroll and click on `Profile Deletion`
7. Once the alert dialog appears, change the orientation to landscape.
8. Notice that the alert dialog disappears.

**Expected behavior**
Alert dialog should persist on orientation change. Also add test for the same in respective file.

### PR DESCRIPTION
**Pull request by ArpitShukIa**
## Explanation
Fixes #2092: I simply saved whether the dialog was visible or not in the saveInstanceState bundle and recreated the dialog in onCreate() if it was open before.

Screenshot of test result:
image

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by ArpitShukIa** [comment]
@rt4914 PTAL.

File: app/src/main/java/org/oppia/android/app/settings/profile/ProfileEditActivityPresenter.kt [hunk 1]
```diff
@@ -26,7 +27,9 @@ class ProfileEditActivityPresenter @Inject constructor(
   @Inject
   lateinit var profileEditViewModel: ProfileEditViewModel
 
-  fun handleOnCreate() {
+  private var dialog: AlertDialog? = null
```
Comment (rt4914) [inline app/src/main/java/org/oppia/android/app/settings/profile/ProfileEditActivityPresenter.kt]: You can use `lateinit` like this:
`private lateinit var dialog: AlertDialog`

Also, this will bring one more change
```
  fun handleOnSaveInstanceState(outState: Bundle) {
    if (::dialog.isInitialized) {
      outState.putBoolean(IS_PROFILE_DELETION_DIALOG_VISIBLE_KEY, dialog.isShowing)
    } else {
      outState.putBoolean(IS_PROFILE_DELETION_DIALOG_VISIBLE_KEY, false)
    }
  }
```

**Review by rt4914 — CHANGES_REQUESTED** [review]
@ArpitShukIa PTAL

**Comment by ArpitShukIa** [comment]
@rt4914 I have updated the code as per the requested changes. PTAL.

**Comment by ArpitShukIa** [comment]
@rt4914 PTAL

File: app/src/main/java/org/oppia/android/app/settings/profile/ProfileEditActivityPresenter.kt [hunk 2]
```diff
@@ -121,6 +126,12 @@ class ProfileEditActivityPresenter @Inject constructor(
               }
             }
           )
-      }.create().show()
+      }.create()
+    dialog.show()
+  }
```
Comment (FareesHussain) [inline app/src/main/java/org/oppia/android/app/settings/profile/ProfileEditActivityPresenter.kt:131]: can you use scope function [apply](https://kotlinlang.org/docs/scope-functions.html#apply) here

**Review by FareesHussain — CHANGES_REQUESTED** [review]
@ArpitShukIa NIT change, rest LGTM

File: app/src/main/java/org/oppia/android/app/settings/profile/ProfileEditActivityPresenter.kt (hunk 2 above)
Comment (ArpitShukIa) [reply app/src/main/java/org/oppia/android/app/settings/profile/ProfileEditActivityPresenter.kt:131]: @FareesHussain We can,  but do we need to?
I think, with apply, code will be something like:
```
AlertDialog.Builder(..)
    .apply {
        dialog = create()
        dialog.show()
    }
```

Comment (FareesHussain) [reply app/src/main/java/org/oppia/android/app/settings/profile/ProfileEditActivityPresenter.kt:131]: image
This is what I meant here
or you can just change it to `.create().show()` instead of `dialog.show()`

Comment (ArpitShukIa) [reply app/src/main/java/org/oppia/android/app/settings/profile/ProfileEditActivityPresenter.kt:131]: @FareesHussain If I am not wrong, in the code snippet you shared, you used the apply function on AlertDialog.Builder and so `dialog` will be initialized to an AlertDialog.Builder instead of an AlertDialog after performing all the below operations on it.

Comment (FareesHussain) [reply app/src/main/java/org/oppia/android/app/settings/profile/ProfileEditActivityPresenter.kt:131]: Ah, I was a little confused. Yes, you are right.

You can resolve this conversation now.

Comment (ArpitShukIa) [reply app/src/main/java/org/oppia/android/app/settings/profile/ProfileEditActivityPresenter.kt:131]: Okay

**Review by FareesHussain — APPROVED** [review]
LGTM, thanks. 
Also, update the pr description by adding the screenshot of the passing Espresso tests.

**Comment by ArpitShukIa** [comment]
Done.

File: app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt [hunk 3]
```diff
@@ -303,6 +303,27 @@ class ProfileEditActivityTest {
...
+      )
+    ).use {
+      onView(withId(R.id.profile_delete_button)).perform(click())
+      onView(isRoot()).perform(orientationLandscape())
+      testCoroutineDispatchers.runCurrent()
+      onView(withText(R.string.profile_edit_delete_dialog_message))
+        .inRoot(isDialog())
+        .check(
+          matches(
+            isDisplayed()
```
Comment (prayutsu) [inline app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt]: We should use `isCompletelyDisplayed()` here to assure that the dialog is displayed completely.

**Review by prayutsu — COMMENTED** [review]
Left some comments, PTAL @ArpitShukIa

File: app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt [hunk 4]
```diff
@@ -303,6 +303,27 @@ class ProfileEditActivityTest {
...
 
+  @Test
+  fun testProfileEdit_startWithUserProfile_clickDelete_configChange_checkDeletionDialogIsVisible() {
+    launch<ProfileEditActivity>(
+      ProfileEditActivity.createProfileEditActivity(
+        context,
+        profileId = 1
+      )
+    ).use {
+      onView(withId(R.id.profile_delete_button)).perform(click())
```
Comment (prayutsu) [inline app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt]: Test may sometimes fail on the small screen devices if we don't perform `scrollTo()` before `click()`

File: app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt (hunk 3 above)
Comment (ArpitShukIa) [reply app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt]: Done.

File: app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt (hunk 4 above)
Comment (ArpitShukIa) [reply app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditActivityTest.kt]: Done. Updated the test screenshot as well

**Review by prayutsu — APPROVED** [review]
LGTM, Thanks @ArpitShukIa

File: app/src/main/java/org/oppia/android/app/settings/profile/ProfileEditActivity.kt [hunk 5]
```diff
@@ -8,6 +8,8 @@ import javax.inject.Inject
 
 const val PROFILE_EDIT_PROFILE_ID_EXTRA_KEY = "ProfileEditActivity.profile_edit_profile_id"
 const val IS_MULTIPANE_EXTRA_KEY = "ProfileEditActivity.is_multipane"
+const val IS_PROFILE_DELETION_DIALOG_VISIBLE_KEY =
+  "ProfileEditActivity.is_profile_deletion_dialog_visible"
```
Comment (prayutsu) [inline app/src/main/java/org/oppia/android/app/settings/profile/ProfileEditActivity.kt:12]: @rt4914 Just want to confirm if it is the best way of using const keys or we should file an issue to replace this.
I believe that they should be declared like this -
```kotlin
const val KEY_NAME = "KEY_NAME"
```

**Comment by prayutsu** [comment]
@ArpitShukIa You can now resolve the comments that I added before the LGTM.

**Review by MaskedCarrot — APPROVED** [review]
LGTM, Thanks

File: app/src/main/java/org/oppia/android/app/settings/profile/ProfileEditActivity.kt (hunk 5 above)
Comment (rt4914) [reply app/src/main/java/org/oppia/android/app/settings/profile/ProfileEditActivity.kt:12]: Actually this is the correct way.

**Review by rt4914 — APPROVED** [review]
LGTM. Thanks.
