### PR TITLE
Fix part of #41: Hifi-StoryChapterList (FULL)

### LINKED ISSUE #41: Full UI: StoryFragment/Activity
The story page should show the user their current progress through the story, and provide links to the corresponding explorations that they can play.

Mock: https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/5abb0ace-19ee-48b8-8154-919154f924d2/TP-CL-Chapter-List-/

https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/screen/cce938d6-e079-4761-bac0-8bde22ac6348/TP-CL-Auto-Scroll-Button-

### PR DESCRIPTION
**Pull request by rt4914**
## Explanation

Check issue #41 for entire checklist.

Mock: https://xd.adobe.com/spec/e2239cf4-9cde-4c08-5296-25316c1f0a14-9412/screen/5abb0ace-19ee-48b8-8154-919154f924d2/TP-CL-Chapter-List-/

- [x] Finished entire mock.
- [x] Automatic scroll to next chapter.
- [x] Tested with Accessibility Scanner.

story_list_1

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by rt4914** [comment]
@mschanteltc @seanlip @BenHenning 

Accessibility scanner is  giving these suggestions to make foreground and background more contrasting but I think this is correct given the case that we want to indicate that this chapter is currently not playable. What's your suggestion?

Also, in mocks there was `blur` effect on top of this item, @BenHenning are we implementing blur effect? For demo purposes, I have not used blur and tried to change colors to match best with the mocks.

screenshot_Oppia_2019-11-09-01_40_59

**Comment by mschanteltc** [comment]
> @mschanteltc @seanlip @BenHenning
> 
> Accessibility scanner is giving these suggestions to make foreground and background more contrasting but I think this is correct given the case that we want to indicate that this chapter is currently not playable. What's your suggestion?
> 
> Also, in mocks there was `blur` effect on top of this item, @BenHenning are we implementing blur effect? For demo purposes, I have not used blur and tried to change colors to match best with the mocks.
> 
> screenshot_Oppia_2019-11-09-01_40_59

The contrast accessibility checker should apply to every object that is active. Since the Chapter card is not accessible, it is [not required](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html) to pass the accessibility checker based on WCAG 2.1 guidelines.

**Comment by rt4914** [comment]
> > @mschanteltc @seanlip @BenHenning
> > Accessibility scanner is giving these suggestions to make foreground and background more contrasting but I think this is correct given the case that we want to indicate that this chapter is currently not playable. What's your suggestion?
> > Also, in mocks there was `blur` effect on top of this item, @BenHenning are we implementing blur effect? For demo purposes, I have not used blur and tried to change colors to match best with the mocks.
> > screenshot_Oppia_2019-11-09-01_40_59
> 
> The contrast accessibility checker should apply to every object that is active. Since the Chapter card is not accessible, it is [not required](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html) to pass the accessibility checker based on WCAG 2.1 guidelines.

Thanks. Sounds good.

File: app/src/main/java/org/oppia/app/story/StoryFragmentPresenter.kt [hunk 1]
```diff
@@ -52,6 +65,8 @@ class StoryFragmentPresenter @Inject constructor(
   }
 
   private fun createRecyclerViewAdapter(): BindableAdapter<StoryItemViewModel> {
+    smoothScrollToPosition(2)
```
Comment (veena14cs) [inline app/src/main/java/org/oppia/app/story/StoryFragmentPresenter.kt]: This is hardcoded please update it to be dynamic.

**Review by veena14cs — APPROVED** [review]
Make one change otherwise LGTM.

File: app/src/main/java/org/oppia/app/story/StoryFragmentPresenter.kt (hunk 1 above)
Comment (rt4914) [reply app/src/main/java/org/oppia/app/story/StoryFragmentPresenter.kt]: This was written for dummy testing and has been removed as it was not needed anymore.

**Comment by nikitamarysolomanpvt** [comment]
Please include updated mock links with finalised specifications.

File: app/src/main/res/layout/story_chapter_view.xml [hunk 2]
```diff
@@ -4,57 +4,121 @@
...
-      android:textSize="12sp"
-      app:layout_constraintStart_toStartOf="parent"
-      app:layout_constraintTop_toBottomOf="@id/chapter_title" />
-  </androidx.constraintlayout.widget.ConstraintLayout>
+      android:layout_margin="16dp"
+      android:clickable="@{viewModel.chapterSummary.chapterPlayState != ChapterPlayState.NOT_PLAYABLE_MISSING_PREREQUISITES}"
+      android:onClick="@{viewModel.onExplorationClicked}"
+      app:cardCornerRadius="4dp"
+      app:cardElevation="@{viewModel.chapterSummary.chapterPlayState != ChapterPlayState.NOT_PLAYABLE_MISSING_PREREQUISITES ? @dimen/elevation_4dp : @dimen/elevation_0dp}"
+      app:strokeColor="@{viewModel.chapterSummary.chapterPlayState != ChapterPlayState.NOT_PLAYABLE_MISSING_PREREQUISITES ? @color/chapterCardGreenBorder : @color/chapterCardGreyBorder}"
```
Comment (nikitamarysolomanpvt) [inline app/src/main/res/layout/story_chapter_view.xml]: Color doesn’t seems matching with the mock.

Comment (nikitamarysolomanpvt) [inline app/src/main/res/layout/story_chapter_view.xml:28]: Color doesn’t seems matching with the mock.

File: app/src/main/res/layout/story_chapter_view.xml [hunk 3]
```diff
@@ -4,57 +4,121 @@
...
-    android:contentDescription="@{viewModel.name}"
-    app:roundedRectDrawableWithColor="@{viewModel.chapterThumbnail.backgroundColorRgb}">
-
-    <ImageView
-      android:id="@+id/chapter_thumbnail"
+  <FrameLayout
+    android:layout_width="match_parent"
+    android:layout_height="wrap_content">
+
+    <com.google.android.material.card.MaterialCardView
```
Comment (nikitamarysolomanpvt) [inline app/src/main/res/layout/story_chapter_view.xml:20]: If you check in detail the corners of the card you would find a white space on both top corners, and white card corner below the stroke corner borders of bottom rounded corners.

**Review by nikitamarysolomanpvt — CHANGES_REQUESTED** [review]
App was crashing on click of story name in first topic PTAL, Also the cards corners and other comment.

**Comment by rt4914** [comment]
> Please include updated mock links with finalised specifications.

Waiting for @mschanteltc reply on my email for this.

File: app/src/main/res/layout/story_chapter_view.xml (hunk 2 above)
Comment (rt4914) [reply app/src/main/res/layout/story_chapter_view.xml:28]: This again relates to the comment earlier, the mocks that you are checking are v7_draft and and the mocks on which this UI has been made is v6_final and because of that there is confusion. Waiting for @mschanteltc for correct v6_spec link

Comment (rt4914) [reply app/src/main/res/layout/story_chapter_view.xml:28]: This has been resolved again. The mocks were updated when you were checking the PR, now they are back to original. So this does not need any change.

File: app/src/main/res/layout/story_chapter_view.xml (hunk 3 above)
Comment (rt4914) [reply app/src/main/res/layout/story_chapter_view.xml:20]: I am not able to find a proper solution for this as of now, I have mentioned this in the issues checklist, so it would nice if we can merge this PR and fix that issue later on.

**Review by nikitamarysolomanpvt — APPROVED** [review]
LGTM
