### PR TITLE
Fixes #4708: Don't submit answer if it's invalid according to the input

### LINKED ISSUE #4708: Fragment returns null view on config change in submit time error
**Describe the bug**
Whenever we compute submit time error, rotates screen and again submits answer [without error] the app crashes and in log it shows that fragment is returning null view. 

**To Reproduce**
1. Go to 'MathInputInteraction'
2. Submit answer with error
3. Rotate screen
4. Remove '?' from fragment.view? in hideKeyboard method in StateFragmentPresenter.kt 
5. Submit answer without error.
6. Observe error log 

**Expected behavior**
App should not return null view, it should return a non-null view when we submits answer without error. 

**Screen Recording**

https://user-images.githubusercontent.com/43074241/201446130-19fcfa6f-48e8-408d-844b-0416065e142e.mp4

**Environment**
- Device/emulator being used: Realme GT Master Edition
- Android or SDK version (e.g. Android 5 or SDK 21): Android 12
- App version (you can get this through system app settings or via the admin controls menu in-app): 1.0

### PR DESCRIPTION
**Pull request by Bontrey**
## Explanation
Fixes #4708: Don't submit answer if it's invalid according to the input
or else after submitting the recycler view will not restore items on configuration change. See #4708 for more details

Video demo:
[before](https://drive.google.com/file/d/1bLgo-AYro0UbffR6X8nWo8Xv7oUuNJFa/view?usp=sharing)
[after](https://drive.google.com/file/d/1Oek7j6dgjJmgasyyd9FHtQo4E7zTvEBd/view?usp=sharing)

Continuation of PR #5202 since that one's no longer viable due to being force pushed in a repo sync through GitHub UI.

## Essential Checklist
- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only
If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- For PRs introducing new UI elements or color changes, both light and dark mode screenshots must be included
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

Change unrelated to concerns like dark mode, RTL, accessibility. PR #5202 had passing test checks for these changes, so that'll be my demonstration of tests passing.

### CODE REVIEW

**Comment by Bontrey** [comment]
@adhiamboperes PTAL and approve pending workflows. Also see my [response](https://github.com/oppia/oppia-android/pull/5202#discussion_r1369986740) about handling null. The other suggested changes were incorporated. Thanks

File: app/src/main/java/org/oppia/android/app/player/state/StateViewModel.kt [hunk 1]
```diff
@@ -101,12 +101,12 @@ class StateViewModel @Inject constructor(
...
   fun getPendingAnswer(
     retrieveAnswerHandler: (List<StateItemViewModel>) -> InteractionAnswerHandler?
-  ): UserAnswer {
+  ): UserAnswer? {
     return getPendingAnswerWithoutError(
       retrieveAnswerHandler(
         getAnswerItemList()
       )
-    ) ?: UserAnswer.getDefaultInstance()
+    )
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/player/state/StateViewModel.kt:109]: Here, you're invoking the retrieveAnswerHandler lambda with the result of getAnswerItemList(). However, if getAnswerItemList() returns null, it will result in a NullPointerException when invoking the lambda.

To avoid this potential issue, you should add a null-check to ensure that the result of getAnswerItemList() is not null before invoking the lambda.

```
fun getPendingAnswer(
    retrieveAnswerHandler: (List<StateItemViewModel>) -> InteractionAnswerHandler?
): UserAnswer? {
    val answerItemList = getAnswerItemList()
    return if (answerItemList != null) {
        retrieveAnswerHandler(answerItemList)
    } else {
        null
    }
}
```

File: app/src/sharedTest/java/org/oppia/android/app/player/state/StateFragmentTest.kt [hunk 2]
```diff
@@ -442,6 +442,24 @@ class StateFragmentTest {
     }
   }
 
+  @Test
+  @RunOn(TestPlatform.ESPRESSO) // Robolectric tests don't rotate like this to recreate activity
+  fun testStateFragment_loadExp_secondState_invalidAnswer_changeConfiguration_submitButtonIsEnabled() { // ktlint-disable max-line-length
```
Comment (adhiamboperes) [inline app/src/sharedTest/java/org/oppia/android/app/player/state/StateFragmentTest.kt]: Can you think of a way to potentially reduce the length of this name, rather than disabling ktlint?

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @Bontrey. Please see changes inline.

File: app/src/sharedTest/java/org/oppia/android/app/player/state/StateFragmentTest.kt (hunk 2 above)
Comment (adhiamboperes) [reply app/src/sharedTest/java/org/oppia/android/app/player/state/StateFragmentTest.kt]: E.g "configChange" in place of "changeConfiguration"

Comment (Bontrey) [reply app/src/sharedTest/java/org/oppia/android/app/player/state/StateFragmentTest.kt]: Updated name. The fact that it's the second state isn't really relevant to the test, so I removed that part.

Chose not to shorten 'changeConfiguration' since that appears elsewhere in the test (and 'Config' is more ambiguous than the fully word 'Configuration' in the context of Android).

Also changed 'Enabled' back to 'Displayed', since I really just care about the button existing. When the disabled state is reset is a separate matter. If future changes are made to keep the disabled state, the test would still rightly pass without needing modifications.

File: app/src/main/java/org/oppia/android/app/player/state/StateViewModel.kt (hunk 1 above)
Comment (Bontrey) [reply app/src/main/java/org/oppia/android/app/player/state/StateViewModel.kt:109]: `getAnswerItemList` doesn't return nullable

**Comment by Bontrey** [comment]
Hmm maybe I have to use the bot instead of clicking 're-request review'

@adhiamboperes Addressed/replied to comments. PTAL

**Review by adhiamboperes — APPROVED** [review]
Thanks @Bontrey. LGTM.
