### PR TITLE
Fix #735: Updated test cases for RecentlyPlayed

### LINKED ISSUE #735: Reenable Test cases in RecentlyPlayedFragmentTest [Blocked on #683]
RecentlyPlayedFragmentTest test cases are not working correctly because of changes in domain layer code. Fix these test cases once the OngoingStoryList is fetched correctly.

### PR DESCRIPTION
**Pull request by rt4914**
## Explanation

Fixes: #735 

This PR enables test cases in `RecentlyPlayedFragment`

Also, there was one dummy test activity which was needed earlier but it is no longer needed, so removed that implementation.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

File: app/src/sharedTest/java/org/oppia/app/home/RecentlyPlayedFragmentTest.kt [hunk 1]
```diff
@@ -209,70 +261,43 @@ class RecentlyPlayedFragmentTest {
...
+  fun testRecentlyPlayedTestActivity_recyclerViewItem2_showsLastMonthSectionTitle() {
+    ActivityScenario.launch<RecentlyPlayedActivity>(createRecentlyPlayedActivityIntent(internalProfileId)).use {
+      onView(withId(R.id.ongoing_story_recycler_view)).perform(scrollToPosition<RecyclerView.ViewHolder>(2))
       onView(
         atPositionOnView(
           R.id.ongoing_story_recycler_view,
-          3,
+          2,
           R.id.section_title_text_view
         )
```
Comment (Luffy18346) [inline app/src/sharedTest/java/org/oppia/app/home/RecentlyPlayedFragmentTest.kt]: Here also Indentation is incorrect. `atPositionOnView` method can be written in single line. Please correct it here and also at other similar places in this file.

File: app/src/sharedTest/java/org/oppia/app/home/RecentlyPlayedFragmentTest.kt [hunk 2]
```diff
@@ -66,9 +120,13 @@ class RecentlyPlayedFragmentTest {
   }
 
   @Test
-  @Ignore("Reenable once OngoingStoryList in domain layer is updated.") // TODO(#735): Reenable once OngoingStoryList is fetched correctly.
   fun testRecentlyPlayedTestActivity_recyclerViewItem0_doesNotShowSectionDivider() {
-    ActivityScenario.launch(RecentlyPlayedFragmentTestActivity::class.java).use {
+    ActivityScenario.launch<RecentlyPlayedActivity>(createRecentlyPlayedActivityIntent(internalProfileId)).use {
+      onView(withId(R.id.ongoing_story_recycler_view)).perform(
+        scrollToPosition<RecyclerView.ViewHolder>(
```
Comment (Luffy18346) [inline app/src/sharedTest/java/org/oppia/app/home/RecentlyPlayedFragmentTest.kt]: Indentation is incorrect. `ScrollToPosition `method can be written in single line. Please correct it here and also at other similar places in this file.

File: app/src/sharedTest/java/org/oppia/app/home/RecentlyPlayedFragmentTest.kt [hunk 3]
```diff
@@ -118,16 +174,15 @@ class RecentlyPlayedFragmentTest {
         )
       ).check(
         matches(
-          withText(containsString("The Meaning of Equal Parts"))
+          withText(containsString("What is a Fraction?"))
```
Comment (Luffy18346) [inline app/src/sharedTest/java/org/oppia/app/home/RecentlyPlayedFragmentTest.kt]: Please use the reference of this text from string.xml resource file instead of hard-coding the text..

File: app/src/sharedTest/java/org/oppia/app/home/RecentlyPlayedFragmentTest.kt [hunk 4]
```diff
@@ -66,9 +120,13 @@ class RecentlyPlayedFragmentTest {
   }
 
   @Test
-  @Ignore("Reenable once OngoingStoryList in domain layer is updated.") // TODO(#735): Reenable once OngoingStoryList is fetched correctly.
   fun testRecentlyPlayedTestActivity_recyclerViewItem0_doesNotShowSectionDivider() {
-    ActivityScenario.launch(RecentlyPlayedFragmentTestActivity::class.java).use {
+    ActivityScenario.launch<RecentlyPlayedActivity>(createRecentlyPlayedActivityIntent(internalProfileId)).use {
+      onView(withId(R.id.ongoing_story_recycler_view)).perform(
+        scrollToPosition<RecyclerView.ViewHolder>(
+          1
```
Comment (Luffy18346) [inline app/src/sharedTest/java/org/oppia/app/home/RecentlyPlayedFragmentTest.kt]: scrollToPosition - 1 does not match with the method name which says `recyclerViewItem0`. Please either correct the method's name or write the functionality as the method name suggested.

**Review by Luffy18346 — CHANGES_REQUESTED** [review]
LGTM thanks. I have suggested few changes.

File: app/src/sharedTest/java/org/oppia/app/home/RecentlyPlayedFragmentTest.kt (hunk 1 above)
Comment (rt4914) [reply app/src/sharedTest/java/org/oppia/app/home/RecentlyPlayedFragmentTest.kt]: Indentation is something which we cannot confirm that it should follow  one single pattern because of android studio. The only thing that we can make sure is that the indentation in one single file is consistent. I have done that. Thanks.

File: app/src/sharedTest/java/org/oppia/app/home/RecentlyPlayedFragmentTest.kt (hunk 2 above)
Comment (rt4914) [reply app/src/sharedTest/java/org/oppia/app/home/RecentlyPlayedFragmentTest.kt]: Indentation is something which we cannot confirm that it should follow  one single pattern because of android studio. The only thing that we can make sure is that the indentation in one single file is consistent. I have done that. Thanks.

File: app/src/sharedTest/java/org/oppia/app/home/RecentlyPlayedFragmentTest.kt (hunk 3 above)
Comment (rt4914) [reply app/src/sharedTest/java/org/oppia/app/home/RecentlyPlayedFragmentTest.kt]: Actually we do use `Hard-coded` strings in tests. This is how it works:
1. If there is a string which in `strings.xml` then we should use that string and do not use a hard-coded string.
2. If the string is not present in `strings.xml` then hardcode it but do not introduce that in `strings.xml` file as we do not want that string to be used in `app` module.

File: app/src/sharedTest/java/org/oppia/app/home/RecentlyPlayedFragmentTest.kt (hunk 4 above)
Comment (rt4914) [reply app/src/sharedTest/java/org/oppia/app/home/RecentlyPlayedFragmentTest.kt]: Resolved.

**Comment by rt4914** [comment]
@Luffy18346 I have made test cases more solid by introducing `waitForView` function. You can run the test file twice and it there are any failures, do let me know.

File: app/src/sharedTest/java/org/oppia/app/home/RecentlyPlayedFragmentTest.kt (hunk 3 above)
Comment (Luffy18346) [reply app/src/sharedTest/java/org/oppia/app/home/RecentlyPlayedFragmentTest.kt]: Ok

**Comment by Luffy18346** [comment]
> @Luffy18346 I have made test cases more solid by introducing `waitForView` function. You can run the test file twice and it there are any failures, do let me know.

LGTM. Thanks
I ran the test-cases twice and both times one test-case fails.
`testRecentlyPlayedTestActivity_changeConfiguration_recyclerViewItem1_lessonThumbnailIsCorrect`

Gives Error: 
`androidx.test.espresso.PerformException: Error performing 'wait for a specific view with matcher <with text: is "FRACTIONS"> during 30000 millis.' on view 'Animations or transitions are enabled on the target device.`

I searched about it. It seems to me that it is emulator problem but i didnt find anything significant.

**Review by Luffy18346 — APPROVED** [review]
LGTM. Thanks
All test-cases are passing.
