### PR TITLE
Fix #1804: Resolved storyfragment toolbar failed testcase

### LINKED ISSUE #1804: Fix StoryFragmentTest.testStoryFragment_clickOnToolbarNavigationButton_closeActivity
This test was recently ignored because we realized it wasn't asserting anything, and adding the assertion triggered a failure so the test isn't actually set up correctly.

### PR DESCRIPTION
**Pull request by alokbharti**
## Explanation
This PR fixes #1804 
- To test working for toolbar back button, instead of choosing entire toolbar id, only the id of navigation back button on toolbar
is used.
- Using ActivityScenario.onActivity after navigation back button clicked will lead to NullPointerException as activity has already been destroyed, So instead, we can use ActivityScenario.getState() method to see the state of current acitivity lifecycle

Here is the screenshot of the successful test result.
Screenshot 2020-09-30 233113

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by alokbharti** [comment]
@rt4914 PTAL

**Comment by aggarwalpulkit596** [comment]
@alokbharti let's wait till the test case have been passed.

File: app/src/sharedTest/java/org/oppia/android/app/story/StoryFragmentTest.kt [hunk 1]
```diff
@@ -142,15 +143,14 @@ class StoryFragmentTest {
...
   fun testStoryFragment_clickOnToolbarNavigationButton_closeActivity() {
     launch<StoryActivity>(createStoryActivityIntent()).use {
       testCoroutineDispatchers.runCurrent()
 
-      onView(withId(R.id.story_toolbar)).perform(click())
+      onView(withContentDescription(R.string.go_to_previous_page)).perform(click())
       testCoroutineDispatchers.runCurrent()
 
-      it.onActivity { activity -> assertThat(activity.isFinishing).isTrue() }
+      assertThat(it.state == Lifecycle.State.DESTROYED)
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/story/StoryFragmentTest.kt]: I think we don't need this change. Running the test with this change makes the test slow. 
it's good to use the earlier one 
`it.onActivity { activity -> assertThat(activity.isFinishing).isTrue() }`

changing the id to content description resolves this issue.

**Review by anandwana001 — CHANGES_REQUESTED** [review]
Thanks @alokbharti 
Looks good to me, just added a point. 
Also, please add the screenshot in the PR description showing the test is passing on both espresso and robolectric.

File: app/src/sharedTest/java/org/oppia/android/app/story/StoryFragmentTest.kt (hunk 1 above)
Comment (alokbharti) [reply app/src/sharedTest/java/org/oppia/android/app/story/StoryFragmentTest.kt]: Actually, I tried with the previous one and it leads to NullPointerException. Clicking on back button will destroy the activity and since activity is already destroyed, it make sense not to use `it.onActivity`.

Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/story/StoryFragmentTest.kt]: Could you add a screenshot for that, because it is passing for me?

Comment (alokbharti) [reply app/src/sharedTest/java/org/oppia/android/app/story/StoryFragmentTest.kt]: Hi @anandwana001 , I did some thing wrong that was causing NullPointerException. I committed with the earlier one.

**Review by anandwana001 — APPROVED** [review]
LGTM, Thanks @alokbharti

**Comment by rt4914** [comment]
@alokbharti Can you just update this branch with latest develop, so that we can merge it?

**Comment by alokbharti** [comment]
> @alokbharti Can you just update this branch with latest develop, so that we can merge it?

yeah sure

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.
