### PR TITLE
Fix #2407: Resolve ktlint max line in testing test package

### LINKED ISSUE #2407: Resolve ktlint max line in testing test package
**Describe the bug**
We are preventing the 100 char length at some places like test case fun name. 
`// ktlint-disable max-line-length`

**Expected behavior**
We need to remove this prevention and fix the function name under 100 char length.

### PR DESCRIPTION
**Pull request by etigoel**
## Explanation
Fix #2407:
We are preventing the 100 char length at some places like test case fun name.
// ktlint-disable max-line-length

Expected behavior
We need to remove this prevention and fix the function name under 100 char length.

@anandwana001 anandwana001 added 

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

File: app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt [hunk 1]
```diff
@@ -118,7 +118,7 @@ class InputInteractionViewTestActivityTest {
   }
 
   @Test
-  fun testFractionInputInteractionView_withInputtedNegativeWholeNumberText_hasCorrectPendingAnswer() { // ktlint-disable max-line-length
+  fun testFractionInputUnder100CharLengthInteractionView_withInputtedNegativeWholeNumberText_hasCorrectPendingAnswer() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt]:
```kotlin
fun testFractionInputInteractionView_withNegativeNumber_hasCorrectPendingAnswer()
```

File: app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt [hunk 2]
```diff
@@ -224,7 +224,7 @@ class InputInteractionViewTestActivityTest {
   }
 
   @Test
-  fun testFractionInputInteractionView_withInputtedNegativeWholeNumberValue_hasCorrectPendingAnswer() { // ktlint-disable max-line-length
+  fun testFractionInputUnder100CharLengthInteractionView_withInputtedNegativeWholeNumberValue_hasCorrectPendingAnswer() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt]:
```kotlin
fun testFractionInputInteractionView_withNegativeMixedNumber_hasCorrectPendingAnswer()
```

File: app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt (hunk 1 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt]: We need a correction, there is nothing negative whole number because mathematically whole numbers are 0,1,2,3, which are never negative.

Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt]: Also, we don't need `Under100CharLength`, test case name should be something which helps un understand what the test function is doing.

**Review by anandwana001 — CHANGES_REQUESTED** [review]
@etigoel PTAL

**Comment by anandwana001** [comment]
currently, what changes you had made have characters more than 100 in a single line which is causing the ktlint failure.

File: app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt (hunk 1 above)
Comment (etigoel) [reply app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt]: Done

File: app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt (hunk 2 above)
Comment (etigoel) [reply app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt]: Done

**Comment by etigoel** [comment]
> currently, what changes you had made have characters more than 100 in a single line which is causing the ktlint failure.

Changed the function names. Klint tests are passing now.

File: app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt (hunk 1 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt]:
```diff
- fun testFractionInputInteractionView_inputtedNegativeNumberText_hasCorrectPendingAnswer()
+ fun testFractionInputInteractionView_withNegativeNumber_hasCorrectPendingAnswer()
```

Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt]: we don't need `inputted` anywhere as it doesn't make any sense.

File: app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt [hunk 3]
```diff
@@ -249,7 +249,7 @@ class InputInteractionViewTestActivityTest {
 
   @Test
   @Ignore("Landscape not properly supported") // TODO(#56): Reenable once landscape is supported.
-  fun testFractionInputInteractionView_withInputtedText_onConfigurationChange_hasCorrectPendingAnswer() { // ktlint-disable max-line-length
+  fun testFractionInputInteractionView_inputText_onConfigurationChange_hasCorrectPendingAnswer() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt]: testFractionInputInteractionView_withFractionInput_onConfigChange_hasCorrectPendingAnswer

File: app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt [hunk 4]
```diff
@@ -355,7 +355,7 @@ class InputInteractionViewTestActivityTest {
   }
 
   @Test
-  fun testFractionInputInteractionView_withInputtedPartialValue_clickSubmitButton_numberFormatErrorIsDisplayed() { // ktlint-disable max-line-length
+  fun testFractionInputInteractionView_inputPartialValue_onSubmit_numberFormatErrorIsDisplayed() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt]: testFractionInputInteractionView_withPartialValue_onSubmit_numberFormatErrorIsDisplayed

File: app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt [hunk 5]
```diff
@@ -376,7 +376,7 @@ class InputInteractionViewTestActivityTest {
   }
 
   @Test
-  fun testFractionInputInteractionView_withInputtedValidValue_clickSubmitButton_noErrorIsDisplayed() { // ktlint-disable max-line-length
+  fun testFractionInputInteractionView_inputtedValidValue_clickSubmitButton_noErrorIsDisplayed() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt]: testFractionInputInteractionView_withMixedFractionNumber_clickSubmitButton_noErrorIsDisplayed

**Review by anandwana001 — CHANGES_REQUESTED** [review]
`with` can replace `inputted` as inputted sounds like the value isalready inputted

File: app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt (hunk 5 above)
Comment (etigoel) [reply app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt]: Done

File: app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt (hunk 4 above)
Comment (etigoel) [reply app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt]: Done

File: app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt (hunk 3 above)
Comment (etigoel) [reply app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt]: Done

**Comment by etigoel** [comment]
> `with` can replace `inputted` as inputted sounds like the value isalready inputted

Done.

File: app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt [hunk 6]
```diff
@@ -518,7 +518,7 @@ class InputInteractionViewTestActivityTest {
   }
 
   @Test
-  fun testNumericInputInteractionView_withInputtedNegativeDecimal_hasCorrectPendingAnswerWithDecimalValues() { // ktlint-disable max-line-length
+  fun testNumericInputInteractionView_withNegDecimal_hasCorrectPendingAnswerWithDecimalValues() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt]: testNumericInputInteractionView_withNegativeDecimal_hasCorrectPendingAnswer

File: app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt [hunk 7]
```diff
@@ -596,7 +596,7 @@ class InputInteractionViewTestActivityTest {
   }
 
   @Test
-  fun testNumericInputInteractionView_withInputtedLongNonDecimalNumber_clickSubmitButton_numberTooLongErrorIsDisplayed() { // ktlint-disable max-line-length
+  fun testNumericInputInteractionView_withLongNonDecimalNum_onSubmit_numTooLongErrorIsDisplayed() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt]: testNumericInputInteractionView_withLongNumber_onSubmit_numberTooLongErrorIsDisplayed

we need consistency, as we are writing `number` everywhere.

File: app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt [hunk 8]
```diff
@@ -673,7 +673,7 @@ class InputInteractionViewTestActivityTest {
   }
 
   @Test
-  fun testNumericInputInteractionView_withInputtedFloatingPointMoreThanOnce_numberFormatErrorIsDisplayed() { // ktlint-disable max-line-length
+  fun testNumericInputInteractionView_withFloatingPointMoreThanOnce_numFormatErrorIsDisplayed() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt]: testNumericInputInteractionView_withFloatingPointMoreThanOnce_numberFormatErrorIsDisplayed

File: app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt [hunk 9]
```diff
@@ -692,7 +692,7 @@ class InputInteractionViewTestActivityTest {
   }
 
   @Test
-  fun testNumericInputInteractionView_withInputtedFloatingPointAtStart_numberStartingWithFloatingPointErrorIsDisplayed() { // ktlint-disable max-line-length
+  fun testNumericInputInteractionView_withDecimalAtStart_numStartingWithFloatingPointError() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt]: testNumericInputInteractionView_withDecimalAtStart_numberStartingWithFloatingPointError

**Review by anandwana001 — CHANGES_REQUESTED** [review]
nit changes

File: app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt (hunk 7 above)
Comment (etigoel) [reply app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt]: Done

File: app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt (hunk 8 above)
Comment (etigoel) [reply app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt]: Done

File: app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt (hunk 9 above)
Comment (etigoel) [reply app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt]: Done

**Review by anandwana001 — CHANGES_REQUESTED** [review]
```diff
- testFractionInputInteractionView_withInputtedWholeNumberText_hasCorrectPendingAnswer
+ testFractionInputInteractionView_withWholeNumberText_hasCorrectPendingAnswer

- testFractionInputInteractionView_withInputtedFractionText_hasCorrectPendingAnswer
+ testFractionInputInteractionView_withFractionText_hasCorrectPendingAnswer

- testFractionInputInteractionView_withInputtedNegativeValue_hasCorrectPendingAnswer
+ testFractionInputInteractionView_withNegativeFractionText_hasCorrectPendingAnswer

- testFractionInputInteractionView_withInputtedWholeNumberValue_hasCorrectPendingAnswer
+ testFractionInputInteractionView_withFractionWholeNumberValue_hasCorrectPendingAnswer

- testFractionInputInteractionView_withInputtedDividerAtStart_numberFormatErrorIsDisplayed
+ testFractionInputInteractionView_withDividerAtStart_numberFormatErrorIsDisplayed

- testFractionInputInteractionView_withInputtedPartialValue_numberFormatErrorIsNotDisplayed
+ testFractionInputInteractionView_withPartialValue_numberFormatErrorIsNotDisplayed

- testFractionInputInteractionView_withInputtedDivideByZero_errorIsNotDisplayed
+ testFractionInputInteractionView_withDivideByZero_errorIsNotDisplayed

- testNumericInputInteractionView_withInputtedText_hasCorrectPendingAnswer
+ testNumericInputInteractionView_withRealNumberText_hasCorrectPendingAnswer

- testNumericInputInteractionView_withInputtedText_hasCorrectPendingAnswerWithDecimalValues
+ testNumericInputInteractionView_withRationalNumber_hasCorrectPendingAnswer

- testTextInputInteractionView_withInputtedText_hasCorrectPendingAnswer
+ testTextInputInteractionView_withCharText_hasCorrectPendingAnswer

- testRatioInputInteractionView_withInputtedText_hasCorrectPendingAnswer
+ testRatioInputInteractionView_withRatioOfNumberText_hasCorrectPendingAnswer

- testRatioInputView_withInputtedText_onConfigurationChange_hasCorrectPendingAnswer
+ testRatioInputInteractionView_withRatioText_configChange_hasCorrectPendingAnswer

- testRatioInputView_withInputtedTwoColonsTogether_colonsTogetherFormatErrorIsDisplayed
+ testRatioInputInteractionView_withTwoColonsTogether_colonsTogetherFormatErrorIsDisplayed

- testRatioInputInteractionView_withInputtedNegativeRatio_numberFormatErrorIsDisplayed
+ testRatioInputInteractionView_withNegativeRatioOfNumberText_numberFormatErrorIsDisplayed

- testRatioInputView_withZeroRatio_clickSubmitButton_numberWithZerosErrorIsDisplayed
+ testRatioInputInteractionView_withZeroRatio_submit_numberWithZerosErrorIsDisplayed

- testRatioInputView_withInvalidRatioFormat_clickSubmitButton_numberFormatErrorIsDisplayed
+ testRatioInputInteractionView_withInvalidRatioFormat_submit_numberFormatErrorIsDisplayed

- testRatioInputView_withRatioHaving4Terms_clickSubmitButton_invalidSizeErrorIsDisplayed
+ testRatioInputInteractionView_with4RatioOfNumberText_submit_invalidSizeErrorIsDisplayed

- testRatioInputView_withRatioHaving2Terms_clickSubmitButton_invalidSizeErrorIsDisplayed
+ testRatioInputInteractionView_with2RatioOfNumberText_submit_invalidSizeErrorIsDisplayed

- testRatioInputView_withRatioHaving3Terms_clickSubmitButton_noErrorIsDisplayed
+ testRatioInputInteractionView_with3RatioOfNumberText_submit_noErrorIsDisplayed 
```

**Comment by etigoel** [comment]
> ```diff
> - testFractionInputInteractionView_withInputtedWholeNumberText_hasCorrectPendingAnswer
> + testFractionInputInteractionView_withWholeNumberText_hasCorrectPendingAnswer
> 
> - testFractionInputInteractionView_withInputtedFractionText_hasCorrectPendingAnswer
> + testFractionInputInteractionView_withFractionText_hasCorrectPendingAnswer
> 
> - testFractionInputInteractionView_withInputtedNegativeValue_hasCorrectPendingAnswer
> + testFractionInputInteractionView_withNegativeFractionText_hasCorrectPendingAnswer
> 
> - testFractionInputInteractionView_withInputtedWholeNumberValue_hasCorrectPendingAnswer
> + testFractionInputInteractionView_withFractionWholeNumberValue_hasCorrectPendingAnswer
> 
> - testFractionInputInteractionView_withInputtedDividerAtStart_numberFormatErrorIsDisplayed
> + testFractionInputInteractionView_withDividerAtStart_numberFormatErrorIsDisplayed
> 
> - testFractionInputInteractionView_withInputtedPartialValue_numberFormatErrorIsNotDisplayed
> + testFractionInputInteractionView_withPartialValue_numberFormatErrorIsNotDisplayed
> 
> - testFractionInputInteractionView_withInputtedDivideByZero_errorIsNotDisplayed
> + testFractionInputInteractionView_withDivideByZero_errorIsNotDisplayed
> 
> - testNumericInputInteractionView_withInputtedText_hasCorrectPendingAnswer
> + testNumericInputInteractionView_withRealNumberText_hasCorrectPendingAnswer
> 
> - testNumericInputInteractionView_withInputtedText_hasCorrectPendingAnswerWithDecimalValues
> + testNumericInputInteractionView_withRationalNumber_hasCorrectPendingAnswer
> 
> - testTextInputInteractionView_withInputtedText_hasCorrectPendingAnswer
> + testTextInputInteractionView_withCharText_hasCorrectPendingAnswer
> 
> - testRatioInputInteractionView_withInputtedText_hasCorrectPendingAnswer
> + testRatioInputInteractionView_withRatioOfNumberText_hasCorrectPendingAnswer
> 
> - testRatioInputView_withInputtedText_onConfigurationChange_hasCorrectPendingAnswer
> + testRatioInputInteractionView_withRatioText_configChange_hasCorrectPendingAnswer
> 
> - testRatioInputView_withInputtedTwoColonsTogether_colonsTogetherFormatErrorIsDisplayed
> + testRatioInputInteractionView_withTwoColonsTogether_colonsTogetherFormatErrorIsDisplayed
> 
> - testRatioInputInteractionView_withInputtedNegativeRatio_numberFormatErrorIsDisplayed
> + testRatioInputInteractionView_withNegativeRatioOfNumberText_numberFormatErrorIsDisplayed
> 
> - testRatioInputView_withZeroRatio_clickSubmitButton_numberWithZerosErrorIsDisplayed
> + testRatioInputInteractionView_withZeroRatio_submit_numberWithZerosErrorIsDisplayed
> 
> - testRatioInputView_withInvalidRatioFormat_clickSubmitButton_numberFormatErrorIsDisplayed
> + testRatioInputInteractionView_withInvalidRatioFormat_submit_numberFormatErrorIsDisplayed
> 
> - testRatioInputView_withRatioHaving4Terms_clickSubmitButton_invalidSizeErrorIsDisplayed
> + testRatioInputInteractionView_with4RatioOfNumberText_submit_invalidSizeErrorIsDisplayed
> 
> - testRatioInputView_withRatioHaving2Terms_clickSubmitButton_invalidSizeErrorIsDisplayed
> + testRatioInputInteractionView_with2RatioOfNumberText_submit_invalidSizeErrorIsDisplayed
> 
> - testRatioInputView_withRatioHaving3Terms_clickSubmitButton_noErrorIsDisplayed
> + testRatioInputInteractionView_with3RatioOfNumberText_submit_noErrorIsDisplayed 
> ```

Done

File: app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt [hunk 10]
```diff
@@ -249,7 +249,7 @@ class InputInteractionViewTestActivityTest {
 
   @Test
   @Ignore("Landscape not properly supported") // TODO(#56): Reenable once landscape is supported.
-  fun testFractionInputInteractionView_withInputtedText_onConfigurationChange_hasCorrectPendingAnswer() { // ktlint-disable max-line-length
+  fun testFractionInputInteractionView_withFractionInput_onConfigChange_hasCorrectPendingAnswer() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt]: testFractionInputInteractionView_withFractionInput_configChange_hasCorrectPendingAnswer

File: app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt [hunk 11]
```diff
@@ -355,7 +355,7 @@ class InputInteractionViewTestActivityTest {
   }
 
   @Test
-  fun testFractionInputInteractionView_withInputtedPartialValue_clickSubmitButton_numberFormatErrorIsDisplayed() { // ktlint-disable max-line-length
+  fun testFractionInputInteractionView_withPartialValue_onSubmit_numberFormatErrorIsDisplayed() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt]: testFractionInputInteractionView_withPartialValue_submit_numberFormatErrorIsDisplayed

File: app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt [hunk 12]
```diff
@@ -376,7 +376,7 @@ class InputInteractionViewTestActivityTest {
   }
 
   @Test
-  fun testFractionInputInteractionView_withInputtedValidValue_clickSubmitButton_noErrorIsDisplayed() { // ktlint-disable max-line-length
+  fun testFractionInputInteractionView_withMixedFractionNumber_onSubmit_noErrorIsDisplayed() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt]: testFractionInputInteractionView_withMixedFractionNumber_submit_noErrorIsDisplayed

File: app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt [hunk 13]
```diff
@@ -402,7 +402,7 @@ class InputInteractionViewTestActivityTest {
   }
 
   @Test
-  fun testFractionInputInteractionView_withInputtedDivideByZero_clickSubmitButton_divideByZeroErrorIsDisplayed() { // ktlint-disable max-line-length
+  fun testFractionInputInteractionView_withDivideByZero_onSubmit_divideByZeroErrorIsDisplayed() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt]: testFractionInputInteractionView_withDivideByZero_submit_divideByZeroErrorIsDisplayed

File: app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt [hunk 14]
```diff
@@ -443,7 +443,7 @@ class InputInteractionViewTestActivityTest {
   }
 
   @Test
-  fun testFractionInputInteractionView_withInputtedLongNumber_clickSubmitButton_numberTooLongErrorIsDisplayed() { // ktlint-disable max-line-length
+  fun testFractionInputInteractionView_withLongNumber_onSubmit_numberTooLongErrorIsDisplayed() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt]: testFractionInputInteractionView_withLongNumber_submit_numberTooLongErrorIsDisplayed

File: app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt [hunk 15]
```diff
@@ -540,7 +540,7 @@ class InputInteractionViewTestActivityTest {
 
   @Test
   @Ignore("Landscape not properly supported") // TODO(#56): Reenable once landscape is supported.
-  fun testNumberInputInteractionView_withInputtedText_onConfigurationChange_hasCorrectPendingAnswer() { // ktlint-disable max-line-length
+  fun testNumberInputInteractionView_withText_onConfigurationChange_hasCorrectPendingAnswer() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt]: testNumberInputInteractionView_withText_configChange_hasCorrectPendingAnswer

File: app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt [hunk 16]
```diff
@@ -574,7 +574,7 @@ class InputInteractionViewTestActivityTest {
   }
 
   @Test
-  fun testNumericInputInteractionView_withInputtedLongNumber_clickSubmitButton_numberTooLongErrorIsDisplayed() { // ktlint-disable max-line-length
+  fun testNumericInputInteractionView_withLongNumber_onSubmit_numberTooLongErrorIsDisplayed() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt]: testNumericInputInteractionView_withLongNumber_submit_numberTooLongErrorIsDisplayed

File: app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt [hunk 17]
```diff
@@ -596,7 +596,7 @@ class InputInteractionViewTestActivityTest {
   }
 
   @Test
-  fun testNumericInputInteractionView_withInputtedLongNonDecimalNumber_clickSubmitButton_numberTooLongErrorIsDisplayed() { // ktlint-disable max-line-length
+  fun testNumericInputInteractionView_withLongInteger_onSubmit_numberTooLongErrorIsDisplayed() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt]: testNumericInputInteractionView_withLongInteger_submit_numberTooLongErrorIsDisplayed

File: app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt [hunk 18]
```diff
@@ -618,7 +618,7 @@ class InputInteractionViewTestActivityTest {
   }
 
   @Test
-  fun testNumericInputInteractionView_withInputtedMinusSymbol_clickSubmitButton_numberFormatErrorIsDisplayed() { // ktlint-disable max-line-length
+  fun testNumericInputInteractionView_withMinusSymbol_onSubmit_numberFormatErrorIsDisplayed() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt]: testNumericInputInteractionView_withMinusSymbol_submit_numberFormatErrorIsDisplayed

File: app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt [hunk 19]
```diff
@@ -741,7 +741,7 @@ class InputInteractionViewTestActivityTest {
 
   @Test
   @Ignore("Landscape not properly supported") // TODO(#56): Reenable once landscape is supported.
-  fun testTextInputInteractionView_withInputtedText_onConfigurationChange_hasCorrectPendingAnswer() { // ktlint-disable max-line-length
+  fun testTextInputInteractionView_withText_onConfigurationChange_hasCorrectPendingAnswer() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt]: testTextInputInteractionView_withCharText_configChange_hasCorrectPendingAnswer

**Review by anandwana001 — CHANGES_REQUESTED** [review]
please keep the consistency in `configChange`, `submit`

File: app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt (hunk 10 above)
Comment (etigoel) [reply app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt]: Done

File: app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt (hunk 11 above)
Comment (etigoel) [reply app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt]: Done

File: app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt (hunk 12 above)
Comment (etigoel) [reply app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt]: Done

File: app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt (hunk 13 above)
Comment (etigoel) [reply app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt]: Done

File: app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt (hunk 14 above)
Comment (etigoel) [reply app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt]: Done

File: app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt (hunk 15 above)
Comment (etigoel) [reply app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt]: Done

File: app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt (hunk 16 above)
Comment (etigoel) [reply app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt]: Done

File: app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt (hunk 17 above)
Comment (etigoel) [reply app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt]: Done

File: app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt (hunk 19 above)
Comment (etigoel) [reply app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt]: Done

File: app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt (hunk 18 above)
Comment (etigoel) [reply app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt]: Done

**Review by anandwana001 — CHANGES_REQUESTED** [review]
```diff
- testFractionInputInteractionView_withInputtedNegativeValue_hasCorrectPendingAnswer
+ testFractionInputInteractionView_withNegativeFractionText_hasCorrectPendingAnswer

- testFractionInputInteractionView_withInputtedPartialValue_numberFormatErrorIsNotDisplayed
+ testFractionInputInteractionView_withPartialValue_numberFormatErrorIsNotDisplayed

- testNumericInputInteractionView_withInputtedText_hasCorrectPendingAnswerWithDecimalValues
+ testNumericInputInteractionView_withRealNumber_hasCorrectPendingAnswer

- testRatioInputView_withInputtedText_configChange_hasCorrectPendingAnswer
+ testRatioInputView_withRatio_configChange_hasCorrectPendingAnswer

- testRatioInputView_withInputtedTwoColonsTogether_colonsTogetherFormatErrorIsDisplayed
+ testRatioInputView_withTwoColonsTogether_colonsTogetherFormatErrorIsDisplayed
```

please add `@Test` at function `testNumericInputInteractionView_withNegativeSymbolNotAt0_numberFormatErrorIsDisplayed`

Also, please confirm before sending for review as the earlier suggested changes are not yet completed.

**Comment by anandwana001** [comment]
Updated all the names here and fixed test annotation thing

https://gist.github.com/anandwana001/73509b40bf37e3af55b265bb1599bf57

**Comment by etigoel** [comment]
> ```diff
> - testFractionInputInteractionView_withInputtedNegativeValue_hasCorrectPendingAnswer
> + testFractionInputInteractionView_withNegativeFractionText_hasCorrectPendingAnswer
> 
> - testFractionInputInteractionView_withInputtedPartialValue_numberFormatErrorIsNotDisplayed
> + testFractionInputInteractionView_withPartialValue_numberFormatErrorIsNotDisplayed
> 
> - testNumericInputInteractionView_withInputtedText_hasCorrectPendingAnswerWithDecimalValues
> + testNumericInputInteractionView_withRealNumber_hasCorrectPendingAnswer
> 
> - testRatioInputView_withInputtedText_configChange_hasCorrectPendingAnswer
> + testRatioInputView_withRatio_configChange_hasCorrectPendingAnswer
> 
> - testRatioInputView_withInputtedTwoColonsTogether_colonsTogetherFormatErrorIsDisplayed
> + testRatioInputView_withTwoColonsTogether_colonsTogetherFormatErrorIsDisplayed
> ```
> 
> please add `@Test` at function `testNumericInputInteractionView_withNegativeSymbolNotAt0_numberFormatErrorIsDisplayed`
> 
> Also, please confirm before sending for review as the earlier suggested changes are not yet completed.

Done

**Comment by rt4914** [comment]
@etigoel Please keep the `Assignees` section up-to-date so that we can know when to review a PRs.
Reference: https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section

**Review by anandwana001 — CHANGES_REQUESTED** [review]
Thanks, @etigoel Looks good so far to me. 
As it seems like we are using `testRatioInput_` rather than `testRatioInputInteractionView`, how about updating others as well. 

1. `testRatioInput_` <- `testRatioInputInteractionView`
2. `testFractionInput_` <- `testFractionInputInteractionView`
3. `testNumericInput_` <- `testNumericInputInteractionView`
4. `testTextInput_` <- `testTextInputInteractionView_`

File: app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt [hunk 20]
```diff
@@ -794,7 +795,7 @@ class InputInteractionViewTestActivityTest {
 
   @Test
   @Ignore("Landscape not properly supported") // TODO(#56): Reenable once landscape is supported.
-  fun testRatioInputView_withInputtedText_onConfigurationChange_hasCorrectPendingAnswer() {
+  fun testRatioInputView_withRatio_configChange_hasCorrectPendingAnswer() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt]: testRatioInput_

File: app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt [hunk 21]
```diff
@@ -812,7 +813,7 @@ class InputInteractionViewTestActivityTest {
   }
 
   @Test
-  fun testRatioInputView_withInputtedTwoColonsTogether_colonsTogetherFormatErrorIsDisplayed() {
+  fun testRatioInputView_withTwoColonsTogether_colonsTogetherFormatErrorIsDisplayed() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt]: testRatioInput_

ditto for others

**Review by anandwana001 — CHANGES_REQUESTED** [review]

File: app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt (hunk 21 above)
Comment (etigoel) [reply app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt]: Done

File: app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt (hunk 20 above)
Comment (etigoel) [reply app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt]: Done

**Review by anandwana001 — APPROVED** [review]
LGTM, Thanks @etigoel

**Comment by etigoel** [comment]
> @etigoel Please keep the `Assignees` section up-to-date so that we can know when to review a PRs.
> Reference: https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section

@rt4914 I do not have access to add/change assignees.

**Comment by rt4914** [comment]
> > @etigoel Please keep the `Assignees` section up-to-date so that we can know when to review a PRs.
> > Reference: https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section
> 
> @rt4914 I do not have access to add/change assignees.

@etigoel My mistake. You will receive an email soon after which you can access assignees section.
