### PR TITLE
Fix #3141: Moved tests from OptionsFragmentTest.kt unit test file to Instrumentation test file

### LINKED ISSUE #3141: Shift Instrumentation test written in Unit Test directory for OptionsFragmentTest
**Describe the bug**
There are some test cases written in `src/test/java/org/oppia/android/app/testing/options/OptionsFragmentTest.kt` which are instrumentation test but the file exist in unit test folder. 

**Expected behavior**
Look for the instrumentation tests in this file and shift them to the instrumentation test directory. 

**Additional context**
[How to test on Espresso?](https://developer.android.com/codelabs/advanced-android-kotlin-training-testing-basics#4)

**How to send a Pull Request for this Issue**
Add screenshot showing shifted tests are passing on Espresso.

### PR DESCRIPTION
**Pull request by Arnold2381**
## Explanation
Fixes #3141 
Screenshot of all the instruments tests passing.
image

Screenshot of the unit test passing after removing init() and release()
image

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by Arnold2381** [comment]
PTAL @anandwana001

**Review by anandwana001 — CHANGES_REQUESTED** [review]
Could you confirm if we need `Intents.init()` and `Intents.release()` anymore in `app/src/test/java/org/oppia/android/app/testing/options/OptionsFragmentTest.kt`?

**Comment by Arnold2381** [comment]
I think we can do that because it starts recording the intents for instrumentation tests, I will try and make the changes.

**Comment by rt4914** [comment]
@Arnold2381 Please update this PR by merging with latest develop.

File: app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt [hunk 1]
```diff
@@ -440,6 +445,67 @@ class OptionsFragmentTest {
...
+        )
+      ).perform(
+        click()
+      )
+      intended(hasComponent(AudioLanguageActivity::class.java.name))
+      intended(hasExtra(KEY_AUDIO_LANGUAGE_PREFERENCE_TITLE, AUDIO_LANGUAGE))
+    }
+  }
+
+  private fun createReadingTextSizeActivityIntent(summaryValue: String): Intent {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt]: are we using this method in this file anywhere?

**Review by anandwana001 — CHANGES_REQUESTED** [review]
It looks like there are duplicate tests after moving. 

like `testOptionsFragment_clickReadingTextSize_checkSendingTheCorrectIntent` and `openOptionsActivity_clickReadingTextSize_opensReadingTextSizeActivity`

@Arnold2381 Could you confirm and check if we need or we are good to remove these test cases?

File: app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt (hunk 1 above)
Comment (Arnold2381) [reply app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt]: I checked it. We aren't using it anywhere, I will remove it.

**Comment by anandwana001** [comment]
@Arnold2381 PTAL https://github.com/oppia/oppia-android/pull/3162#pullrequestreview-656305824

**Comment by Arnold2381** [comment]
@anandwana001 Sorry! I missed that. Yes they are duplicates both are doing the same checks. Will remove that too.

**Review by anandwana001 — CHANGES_REQUESTED** [review]
I think we are just removeing the test from the `app/src/test/java/org/oppia/android/app/testing/options/OptionsFragmentTest.kt` and no changes in the `sharedTest` side, as there are already same test cases are written.

**Comment by anandwana001** [comment]
Also, could you confirm if the older test are passing on espresso?

1. `openOptionsActivity_clickReadingTextSize_opensReadingTextSizeActivity`
2. `openOptionsActivity_configChange_clickTextSize_opensReadingTextSizeActivity`
3. `openOptionsActivity_clickAppLanguage_opensAppLanguageActivity`
4. `openOptionsActivity_configChange_clickAppLanguage_opensAppLanguageActivity`
5. `openOptionsActivity_clickAudioLanguage_opensAudioLanguageActivity`
6. `openOptionsActivity_configChange_clickAudioLanguage_opensAudioLanguageActivity`

Let me know if you find any differences in these above mentioned test and tests which are in the `src/test/java/org/oppia/android/app/testing/options/OptionsFragmentTest.kt`

**Comment by Arnold2381** [comment]
@anandwana001 all the tests were passing on espresso, I tested it before only and then made the commit.
Also, I checked the tests in the `src/test/java/org/oppia/android/app/testing/options/OptionsFragmentTest.kt` , they are doing nothing different from the espresso tests. So should I remove them?

**Review by anandwana001 — CHANGES_REQUESTED** [review]
Most probably, we are going to keep `app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt` unchanged and  remove unnecessary tests from `src/test/java/org/oppia/android/app/testing/options/OptionsFragmentTest.kt`.


Before that, I see here that `sharedTest` file is only testing the pref values (`VALUE_EXTRA_KEY`) for readingTextSize fragment, app language, and audio fragment, but the `test dir file is only testing the pref keys (`TITLE_EXTRA_KEY`). 

So, what we can do here is to update tests in `sharedTest` so that a single test can test both pref values and keys, and remove them from the `test` directory. 

For example
```kt
@Test
  fun openOptionsActivity_clickAppLanguage_opensAppLanguageActivity() {
    launch<OptionsActivity>(
      createOptionActivityIntent(
        internalProfileId = 0,
        isFromNavigationDrawer = true
      )
    ).use {
      testCoroutineDispatchers.runCurrent()
      onView(
        atPositionOnView(
          recyclerViewId = R.id.options_recyclerview,
          position = 1,
          targetViewId = R.id.app_language_text_view
        )
      ).perform(click())
      intended(
        allOf(
          hasExtra(AppLanguageActivity.APP_LANGUAGE_PREFERENCE_TITLE_EXTRA_KEY, APP_LANGUAGE),
          hasExtra(
            AppLanguageActivity.APP_LANGUAGE_PREFERENCE_SUMMARY_VALUE_EXTRA_KEY,
            "English"
          ),
          hasComponent(AppLanguageActivity::class.java.name)
        )
      )
    }
  }
```

**Comment by Arnold2381** [comment]
@anandwana001 I made the changes in readingTextSize fragment, app language, and audio fragment, and as the unit test file only contains tests that seem duplicates after changes, I removed the entire file, though I am not sure about this. Waiting for your comments on this.
PTAL.

File: app/src/test/java/org/oppia/android/app/testing/options/OptionsFragmentTest.kt [hunk 2]
```diff
@@ -1,298 +0,0 @@
...
-          activity.supportFragmentManager.findFragmentById(R.id.multipane_options_container)
-        assertThat(loadedFragment is ReadingTextSizeFragment).isTrue()
-      }
-    }
-  }
-
-  @Test
-  @Config(qualifiers = "sw600dp")
-  @LooperMode(LooperMode.Mode.PAUSED)
-  fun testOptionsFragment_clickAppLanguage_checkLoadingTheCorrectFragment() {
```
Comment (anandwana001) [inline app/src/test/java/org/oppia/android/app/testing/options/OptionsFragmentTest.kt]: These test case should be in this file only. They are no UI test, what we are testing in this test case is the fragment context.

File: app/src/test/java/org/oppia/android/app/testing/options/OptionsFragmentTest.kt [hunk 3]
```diff
@@ -1,298 +0,0 @@
...
-          activity.supportFragmentManager.findFragmentById(R.id.multipane_options_container)
-        assertThat(loadedFragment is AppLanguageFragment).isTrue()
-      }
-    }
-  }
-
-  @Test
-  @Config(qualifiers = "sw600dp")
-  @LooperMode(LooperMode.Mode.PAUSED)
-  fun testOptionsFragment_clickDefaultAudio_checkLoadingTheCorrectFragment() {
```
Comment (anandwana001) [inline app/src/test/java/org/oppia/android/app/testing/options/OptionsFragmentTest.kt]: ditto

File: app/src/test/java/org/oppia/android/app/testing/options/OptionsFragmentTest.kt [hunk 4]
```diff
@@ -1,298 +0,0 @@
...
-      )
-      intended(hasComponent(AudioLanguageActivity::class.java.name))
-      intended(hasExtra(KEY_AUDIO_LANGUAGE_PREFERENCE_TITLE, AUDIO_LANGUAGE))
-    }
-  }
-
-  @Test
-  @Config(qualifiers = "sw600dp")
-  @LooperMode(LooperMode.Mode.PAUSED)
-  fun testOptionsFragment_checkInitiallyLoadedFragmentIsReadingTextSizeFragment() {
```
Comment (anandwana001) [inline app/src/test/java/org/oppia/android/app/testing/options/OptionsFragmentTest.kt]: ditto

File: app/src/test/java/org/oppia/android/app/testing/options/OptionsFragmentTest.kt [hunk 5]
```diff
@@ -1,298 +0,0 @@
...
-          activity.supportFragmentManager.findFragmentById(R.id.multipane_options_container)
-        assertThat(loadedFragment is ReadingTextSizeFragment).isTrue()
-      }
-    }
-  }
-
-  @Test
-  @Config(qualifiers = "sw600dp")
-  @LooperMode(LooperMode.Mode.PAUSED)
-  fun testOptionsFragment_clickReadingTextSize_checkLoadingTheCorrectFragment() {
```
Comment (anandwana001) [inline app/src/test/java/org/oppia/android/app/testing/options/OptionsFragmentTest.kt]: ditto

File: app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt [hunk 6]
```diff
@@ -356,14 +361,14 @@ class OptionsFragmentTest {
   }
 
   @Test
-  fun openOptionsActivity_clickReadingTextSize_opensReadingTextSizeActivity() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt]: We need this test as well because  `openOptionsActivity_configChange_clickTextSize_opensReadingTextSizeActivity` is testing whether the ReadingTextSizeActivity open after config change. 
And `openOptionsActivity_clickReadingTextSize_opensReadingTextSizeActivity` test whether ReadingTextSizeActivity open in portrait mode. 
So we need both of these test cases

File: app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt [hunk 7]
```diff
@@ -384,51 +393,81 @@ class OptionsFragmentTest {
   }
 
   @Test
-  fun openOptionsActivity_configChange_clickTextSize_opensReadingTextSizeActivity() {
+  fun openOptionsActivity_clickAppLanguage_opensAppLanguageActivity() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt]: I suggest keeping `openOptionsActivity_configChange_clickAppLanguage_opensAppLanguageActivity` under  `openOptionsActivity_clickAppLanguage_opensAppLanguageActivity` this test.

File: app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt [hunk 8]
```diff
@@ -384,51 +393,81 @@ class OptionsFragmentTest {
...
+            "English"
+          ),
+          hasComponent(AppLanguageActivity::class.java.name)
+        )
+      )
+    }
+  }
+
+  @Test
+  fun testOptionsFragment_clickReadingTextSize_checkSendingTheCorrectIntent() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt]: remove this test case

File: app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt [hunk 9]
```diff
@@ -384,51 +393,81 @@ class OptionsFragmentTest {
...
 
   @Test
-  fun openOptionsActivity_clickAppLanguage_opensAppLanguageActivity() {
-    launch<OptionsActivity>(
-      createOptionActivityIntent(
-        internalProfileId = 0,
-        isFromNavigationDrawer = true
-      )
-    ).use {
+  fun testOptionsFragment_clickAppLanguage_checkSendingTheCorrectIntent() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt]: remove this test case

File: app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt [hunk 10]
```diff
@@ -440,6 +479,23 @@ class OptionsFragmentTest {
   }
 
   @Test
+  fun testOptionsFragment_clickDefaultAudioLanguage_checkSendingTheCorrectIntent() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt]: remove this test

File: app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt [hunk 11]
```diff
@@ -485,6 +545,10 @@ class OptionsFragmentTest {
       ).perform(click())
       intended(
         allOf(
+          hasExtra(
+            AudioLanguageActivity.KEY_AUDIO_LANGUAGE_PREFERENCE_TITLE,
+            AUDIO_LANGUAGE
+          ),
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt:503]: Add the below check in `openOptionsActivity_configChange_clickAudioLanguage_opensAudioLanguageActivity` test as well
```kt
hasExtra(
            AudioLanguageActivity.KEY_AUDIO_LANGUAGE_PREFERENCE_TITLE,
            AUDIO_LANGUAGE
          ),
```

**Review by anandwana001 — CHANGES_REQUESTED** [review]
Left few changes.

**Comment by anandwana001** [comment]
@Arnold2381 Please reply to my suggested comments if they are done or if there is any issues related to them, and assign me back.

File: app/src/test/java/org/oppia/android/app/testing/options/OptionsFragmentTest.kt (hunk 2 above)
Comment (Arnold2381) [reply app/src/test/java/org/oppia/android/app/testing/options/OptionsFragmentTest.kt]: I added this test back.

File: app/src/test/java/org/oppia/android/app/testing/options/OptionsFragmentTest.kt (hunk 3 above)
Comment (Arnold2381) [reply app/src/test/java/org/oppia/android/app/testing/options/OptionsFragmentTest.kt]: I added this test back.

File: app/src/test/java/org/oppia/android/app/testing/options/OptionsFragmentTest.kt (hunk 4 above)
Comment (Arnold2381) [reply app/src/test/java/org/oppia/android/app/testing/options/OptionsFragmentTest.kt]: I added this test back.

File: app/src/test/java/org/oppia/android/app/testing/options/OptionsFragmentTest.kt (hunk 5 above)
Comment (Arnold2381) [reply app/src/test/java/org/oppia/android/app/testing/options/OptionsFragmentTest.kt]: I added this test back.

File: app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt (hunk 6 above)
Comment (Arnold2381) [reply app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt]: Ok. I added this test back.

File: app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt (hunk 7 above)
Comment (Arnold2381) [reply app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt]: Done!

File: app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt (hunk 8 above)
Comment (Arnold2381) [reply app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt]: Removed!

File: app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt (hunk 9 above)
Comment (Arnold2381) [reply app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt]: Removed!

File: app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt (hunk 10 above)
Comment (Arnold2381) [reply app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt]: Removed!

File: app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt (hunk 11 above)
Comment (Arnold2381) [reply app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt:503]: Yea, I added it.

**Comment by Arnold2381** [comment]
@anandwana001 Done!

**Review by anandwana001 — APPROVED** [review]
LGTM, re-running checks currently, 2 cases are failing.

**Comment by anandwana001** [comment]
@FareesHussain Do you remember we face a similar error about this companion object access in Bazel, Could you please check the failure of this action here.

**Comment by FareesHussain** [comment]
@Arnold2381 can you try to import these intent key constants.

**Review by rt4914 — CHANGES_REQUESTED** [review]
Blocking for bazel tests.

**Comment by Arnold2381** [comment]
@rt4914 PTAL.

File: app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt [hunk 12]
```diff
@@ -85,6 +85,17 @@ import org.robolectric.annotation.LooperMode
...
+private const val KEY_READING_TEXT_SIZE_PREFERENCE_TITLE = "READING_TEXT_SIZE_PREFERENCE"
+private const val APP_LANGUAGE_PREFERENCE_TITLE_EXTRA_KEY =
+  "AppLanguageActivity.app_language_preference_title"
+private const val KEY_AUDIO_LANGUAGE_PREFERENCE_TITLE = "AUDIO_LANGUAGE_PREFERENCE"
+private const val KEY_READING_TEXT_SIZE_PREFERENCE_SUMMARY_VALUE =
+  "READING_TEXT_SIZE_PREFERENCE_SUMMARY_VALUE"
+private const val APP_LANGUAGE_PREFERENCE_SUMMARY_VALUE_EXTRA_KEY =
+  "AppLanguageActivity.app_language_preference_summary_value"
+private const val KEY_AUDIO_LANGUAGE_PREFERENCE_SUMMARY_VALUE =
+  "AUDIO_LANGUAGE_PREFERENCE_SUMMARY_VALUE"
```
Comment (rt4914) [inline app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt]: @anandwana001 and @Arnold2381 This passes the tests but thats no the correct way to write tests. In future if we change these constants in production files then these tests will again start failing and we will need to fix that too. 

@anandwana001 WDYT?

**Review by rt4914 — CHANGES_REQUESTED** [review]
PTAL

File: app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt (hunk 12 above)
Comment (Arnold2381) [reply app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt]: @rt4914 I tried importing the constants but the bazel tests are failing.

Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt]: @rt4914 currently, we don't directly import the variables, but we use the get function from the test file to get the original key in the production file.  

Reference - https://github.com/oppia/oppia-android/blob/82d8ee4c3cd4c3a6b90703c805b48e8bdd99db38/app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt#L66

Comment (rt4914) [reply app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt]: Actually we need to make all of these keys consistent by defining them in `companion object` and then using it wherever needed.

Comment (rt4914) [reply app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt]: For this PR we can use any solution but the main point is to use same const in production and in test file.

Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt]: yeah, that's why we can use the get function. 
Bazel doesn't support importing.

Comment (rt4914) [reply app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt]: Okay then we will need to use `function` for all intent values. Sure, let's do it for this PR and then discuss this idea with Jan and Ben too.

Comment (Arnold2381) [reply app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt]: @rt4914 is it okay now? PTAL

File: app/src/main/java/org/oppia/android/app/options/AppLanguageActivity.kt [hunk 13]
```diff
@@ -43,6 +43,13 @@ class AppLanguageActivity : InjectableAppCompatActivity() {
       intent.putExtra(APP_LANGUAGE_PREFERENCE_SUMMARY_VALUE_EXTRA_KEY, summaryValue)
       return intent
     }
+
+    fun getIntentKey(): Array<String> {
```
Comment (anandwana001) [inline app/src/main/java/org/oppia/android/app/options/AppLanguageActivity.kt]: this is not what exactly we are looking for. 

Create separate functions for both the items and name the functions accordingly with that function return.

**Review by anandwana001 — CHANGES_REQUESTED** [review]

File: app/src/main/java/org/oppia/android/app/options/AppLanguageActivity.kt (hunk 13 above)
Comment (Arnold2381) [reply app/src/main/java/org/oppia/android/app/options/AppLanguageActivity.kt]: @anandwana001 is it not better if we have just one function and return the array of strings? In the future, if suppose some other key is added then we need to create one more function?

Comment (anandwana001) [reply app/src/main/java/org/oppia/android/app/options/AppLanguageActivity.kt]: Separate function sounds good. Passing by array is something we need one param, but getting a everything and then extracting out one.

Comment (Arnold2381) [reply app/src/main/java/org/oppia/android/app/options/AppLanguageActivity.kt]: @anandwana001 Is this okay? I did the changes.

File: app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt [hunk 14]
```diff
@@ -374,7 +387,7 @@ class OptionsFragmentTest {
       intended(
         allOf(
           hasExtra(
-            ReadingTextSizeActivity.KEY_READING_TEXT_SIZE_PREFERENCE_SUMMARY_VALUE,
+            KEY_READING_TEXT_SIZE_PREFERENCE_SUMMARY_VALUE,
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt]: Let's use the value directly.
```suggestion
            ReadingTextSizeActivity.getKeyReadingTextSizePreferenceSummaryValue(),
```

Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/options/OptionsFragmentTest.kt]: ditto for all

**Review by anandwana001 — CHANGES_REQUESTED** [review]
nit suggestion else LGTM

**Review by anandwana001 — APPROVED** [review]
LGTM, let's wait for all the checks to pass and will merge.

**Comment by Arnold2381** [comment]
> LGTM, let's wait for all the checks to pass and will merge.

Yea it passed.

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.
