### PR TITLE
Fix #5784: Standardize audio and app language list ordering

### LINKED ISSUE #5784: [BUG]: The list of languages in the App Language and Preferred Audio Language is not the same order
### Describe the bug

The list of languages in the App Language is not the same order than Preferred Audio Language. To have a better a stetic and user experience, the order of available languages should be the same, begining for English in first position. 

### Steps To Reproduce

1. Go to Optioon menu
2. Click on App Language
3. See the order of available languages
4. Click on Preferred Audio Language
5. See the order of available languages
6. Compare the order of languages

### Expected Behavior

It is expected to see the list of languages in the App Language in the same order as Preferred Audio Language

### Screenshots/Videos

Image

### What device/emulator are you using?

OPPO A79 5G

### Which Android version is your device/emulator running?

Android 14

### Which version of the Oppia Android app are you using?

0.15-beta-9404ea41d9

### Additional Context

_No response_

-------
### Context

Currently, the list of languages shown in **App Language** list and **Preferred Audio Language** list are not ordered the same way. This causes inconsistency in the UI and results in a suboptimal user experience.

This two lists are not required to contain the same set of languages—for example, some languages may only be available as app languages but not audio and vice versa—but they should still follow the same ordering logic.

👉 **The intended ordering rule (per team decision):**

- Store written and audio languages separately (since we may offer a written language but not an audio language if voiceovers aren't complete for that language).
- Always show English first, followed by the other languages alphabetically ordered by their English name (to match Android OS convention).

### Files to Investigate

**For the Preferred Audio Language list:**
 
- [audio_language_fragment](https://github.com/oppia/oppia-android/blob/86b79136628212e38b2d2f570375a941cb8459fd/app/src/main/res/layout/audio_language_fragment.xml#L16)
- [AudioLanguageSelectionViewModel](https://github.com/oppia/oppia-android/blob/86b79136628212e38b2d2f570375a941cb8459fd/app/src/main/java/org/oppia/android/app/options/AudioLanguageSelectionViewModel.kt#L61)
- enum [AudioLanguage](https://github.com/oppia/oppia-android/blob/86b79136628212e38b2d2f570375a941cb8459fd/model/src/main/proto/profile.proto#L159)

**For the App Language list:**

- [app_language_fragment](https://github.com/oppia/oppia-android/blob/86b79136628212e38b2d2f570375a941cb8459fd/app/src/main/res/layout/app_language_fragment.xml#L13)
- [AppLanguageSelectionViewModel](https://github.com/oppia/oppia-android/blob/86b79136628212e38b2d2f570375a941cb8459fd/app/src/main/java/org/oppia/android/app/options/AppLanguageSelectionViewModel.kt#L30)
- [TranslationController](https://github.com/oppia/oppia-android/blob/86b79136628212e38b2d2f570375a941cb8459fd/domain/src/main/java/org/oppia/android/domain/translation/TranslationController.kt#L114)
- enum [OppiaLanguage](https://github.com/oppia/oppia-android/blob/86b79136628212e38b2d2f570375a941cb8459fd/model/src/main/proto/languages.proto#L9)

**For testing:**

The test should verify that the **ordering rule** is followed for each list independently. It should not check whether both lists have the same set of languages (since the available languages may differ between app and audio).

- [AudioLanguageFragmentTest](https://github.com/oppia/oppia-android/blob/86b79136628212e38b2d2f570375a941cb8459fd/app/src/sharedTest/java/org/oppia/android/app/options/AudioLanguageFragmentTest.kt#L128)
- [AppLanguageFragmentTest](https://github.com/oppia/oppia-android/blob/86b79136628212e38b2d2f570375a941cb8459fd/app/src/sharedTest/java/org/oppia/android/app/options/AppLanguageFragmentTest.kt#L110)

### PR DESCRIPTION
**Pull request by EngDann**
## Explanation
Fix #5784 

Before, the list of text and audio languages was bad sorted, so, as was proposed, I sorted the languages in alphabetic form, excluding the English from that sort and applying that as the first language.

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [ ] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [ ] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

| Before (Inconsistent Sort) | After (Standardized Sort) |
| :--- | :--- |
| [Video](https://github.com/user-attachments/assets/1f9704cc-40f1-47f5-aa65-65dc36bc53fe) | [Video](https://github.com/user-attachments/assets/3b8d0539-cda9-4fcd-9387-9092a8123115) |

### CODE REVIEW

**Comment by manas-yu** [comment]
Hi @EngDann PTAL at the failing unit tests in CI and assign back, also make sure to write tests for the code changes as well. Thanks!

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks for this great solution, @EngDann!

As @manas-yu mentioned, please look at [this wiki page](https://github.com/oppia/oppia-android/wiki/Interpreting-CI-Results) to see how to locate failing tests in the CI report. An easy method I use is to click on the failing shard, then in the search bar, I type "failures", and I can easily navigate to the errors.

For information on how to run the tests locally on your machine, please see [here](https://github.com/oppia/oppia-android/wiki/Installing-Oppia-Android#set-up-and-run-tests).

Ps: Coverage related failures will automatically fix themselves once the tests pass.

**Comment by adhiamboperes** [comment]
Please let us know if you need any support with the fixes.

**Comment by EngDann** [comment]
Hi @adhiamboperes and @manas-yu, thanks for the detailed feedback and the helpful links!

I'll aim to have the necessary test cases written and the PR updated by the end of this week. I don't need any support right now, but I'll definitely reach out if I hit a blocker. Thanks!

File: app/src/sharedTest/java/org/oppia/android/app/options/AudioLanguageFragmentTest.kt [hunk 1]
```diff
@@ -247,6 +247,36 @@ class AudioLanguageFragmentTest {
     }
   }
 
+  @Test
+  fun testAudioLanguage_englishIsFirstThenAlphabetical() {
+    topicController.getTopic(
+      ProfileId.newBuilder().setInternalId(0).build(),
+      TEST_TOPIC_ID_0
+    ).observeForever(mockTopicLiveDataObserver)
+    testCoroutineDispatchers.runCurrent()
```
Comment (adhiamboperes) [inline app/src/sharedTest/java/org/oppia/android/app/options/AudioLanguageFragmentTest.kt]: This seems completely out of place. I don't think this test will compile at all. Did you run it locally?

File: app/src/sharedTest/java/org/oppia/android/app/options/AudioLanguageFragmentTest.kt [hunk 2]
```diff
@@ -247,6 +247,36 @@ class AudioLanguageFragmentTest {
...
+
+    launch<OptionsActivity>(
```
Comment (adhiamboperes) [inline app/src/sharedTest/java/org/oppia/android/app/options/AudioLanguageFragmentTest.kt]: The activity under test is `AudioLanguageActivity`, not `OptionsActivity`, so this test will fail with build errors.


I suggest looking at other tests in this class to see how they are written, and using an identical set up for this new test.

File: app/src/sharedTest/java/org/oppia/android/app/options/AudioLanguageFragmentTest.kt [hunk 3]
```diff
@@ -247,6 +247,36 @@ class AudioLanguageFragmentTest {
...
+      onView(withId(R.id.language_recycler_view))
+        .perform(
+          scrollToPosition<RecyclerView.ViewHolder>(0)
+        ).check(
+          matches(
+            atPositionOnView(
+              0,
+              withText("English"),
+              R.id.language_radio_button
+            )
```
Comment (adhiamboperes) [inline app/src/sharedTest/java/org/oppia/android/app/options/AudioLanguageFragmentTest.kt]: This assertion only verifies that English is in the first position, but it does not verify the remaining languages. The name of the test is `testAudioLanguage_englishIsFirstThenAlphabetical`, which means we expect to see the `onView....matches(atPositionOnView..)` for all the languages in the list.

File: app/src/sharedTest/java/org/oppia/android/app/options/AppLanguageFragmentTest.kt [hunk 4]
```diff
@@ -239,6 +239,30 @@ class AppLanguageFragmentTest {
     }
   }
 
+  @Test
+  fun testAppLanguage_englishIsFirstThenAlphabetical() {
+    launch(OptionsActivity::class.java).use {
```
Comment (adhiamboperes) [inline app/src/sharedTest/java/org/oppia/android/app/options/AppLanguageFragmentTest.kt]: The activity under test is`AppLanguageActivity`, not `OptionsActivity`, so this test will fail with build errors.

Please look at how the other tests in this class are written, and use the same format.

File: app/src/sharedTest/java/org/oppia/android/app/options/AppLanguageFragmentTest.kt [hunk 5]
```diff
@@ -239,6 +239,30 @@ class AppLanguageFragmentTest {
...
+        ).check(
+          matches(
+            atPositionOnView(
+              0,
+              withText("English"),
+              R.id.language_radio_button
+            )
+          )
+        )
+    }
```
Comment (adhiamboperes) [inline app/src/sharedTest/java/org/oppia/android/app/options/AppLanguageFragmentTest.kt:309]: This assertion only verifies that English is in the first position, but it does not verify the remaining languages. The name of the test is `testAudioLanguage_englishIsFirstThenAlphabetical`, which means we expect to see the `onView....matches(atPositionOnView..)` for all the languages in the list.

File: app/src/sharedTest/java/org/oppia/android/app/options/AppLanguageFragmentTest.kt [hunk 6]
```diff
@@ -239,6 +239,30 @@ class AppLanguageFragmentTest {
...
   }
 
+  @Test
+  fun testAppLanguage_englishIsFirstThenAlphabetical() {
+    launch(OptionsActivity::class.java).use {
+      it.onActivity { activity ->
+        val fragment = activity.supportFragmentManager
+          .findFragmentByTag(TAG_APP_LANGUAGE_FRAGMENT) as AppLanguageFragment
+        testCoroutineDispatchers.runCurrent()
+        fragment.requireView().requestLayout()
```
Comment (adhiamboperes) [inline app/src/sharedTest/java/org/oppia/android/app/options/AppLanguageFragmentTest.kt]: This will not be necessary if you launch `isAppLanguageActivity` directly.

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @EngDann for adding tests. 

However, the tests have not been correctly written, and I have left some comments inline explaining that.

Also, I have noticed that you have not fixed the existing tests that are failing in the CI. In my previous comment, I left some links for you to look at, pointing towards the WIki pages about our CI. Please take a look and let me know if I can explain some things further.

**Comment by EngDann** [comment]
@adhiamboperes, thank you so much for the feedback! 

I'm still learning how to write tests effectively for this project, and it has been a challenge for me, so your comments were very helpful. I will update the tests with all of your suggestions.

Regarding the other failing CI checks, I had some trouble accessing the logs last time as they had expired. I see they are available now, so I will investigate those failures and work on fixing them.

Thanks again for your help and patience!

**Comment by EngDann** [comment]
Hey @adhiamboperes!

I've pushed updates for all the feedback you gave me. I fixed the tests to launch the correct activities and check all the languages, like you pointed out.

Could you please take another look when you get a chance? Thanks!

Screenshot from 2025-10-23 16-16-50
Screenshot from 2025-10-23 16-17-48

**Review by adhiamboperes — COMMENTED** [review]
Thanks @EngDann! These tests look good! Will take another look once CI passes.

**Review by adhiamboperes — APPROVED** [review]
This LGTM @EngDann! Thanks for your work on it!

**Comment by adhiamboperes** [comment]
@EngDann, please let us know if you need any help picking your next issue

**Comment by EngDann** [comment]
> @EngDann, please let us know if you need any help picking your next issue

Yes, I'd like help to choose my next issue
