### PR TITLE
Fix #4803 Failed to add Admin (or non-admin) Profile Picture.

### LINKED ISSUE #4803: Failed to add Admin (or non-admin) Profile Picture.
**Describe the bug**
Whenever I try to change admin profile picture or basically setup, I get redirected to gallery but after selecting approximate picture I go back to the previous section (profile progress activity) but the profile picture is not set.

**To Reproduce**
1. Go to app drawer.
2. Click on Admin Profile Picture
3. Then again click on the profile picture and then click 'Choose From Gallery' option.
4. Select any image from gallery.
5. See the error: Admin Profile Picture is not.

**Demonstration**
https://user-images.githubusercontent.com/99060332/209429780-72e28ad6-7de1-4dd5-9f2a-5dda875cfe9f.mp4
**Environment**
- Device being used: Redmi Note pro
- Android version: Android 11
- App version: 0.10-beta

### PR DESCRIPTION
**Pull request by ShubhadeepKarmakar**
## Explanation

- Fix #4803 
 val galleryIntent = Intent(Intent.ACTION_PICK, MediaStore.Images.Media.EXTERNAL_CONTENT_URI)
The above code (previous) is the explicit way to get images from gallery but is not working here. But the updated code below is less explicit but works fine,
val galleryIntent = Intent(Intent.ACTION_GET_CONTENT).apply { type = "image/*" }

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## Screen Recording

https://github.com/oppia/oppia-android/assets/99060332/b6379a06-e3e6-41eb-9bed-de6271dcd346

### CODE REVIEW

**Comment by adhiamboperes** [comment]
Thanks @ShubhadeepKarmakar! 

Hi @kkmurerwa, could you give this a pass and assign it to me once any initial concerns have been addressed?

File: app/src/main/java/org/oppia/android/app/profileprogress/ProfileProgressActivityPresenter.kt [hunk 1]
```diff
@@ -52,7 +52,8 @@ class ProfileProgressActivityPresenter @Inject constructor(
   }
 
   fun openGalleryIntent() {
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/profileprogress/ProfileProgressActivityPresenter.kt:53]: Could you please update the corresponding tests `testProfileProgressFragment_imageSelectAvatar_checkGalleryIntent` and `testProfileProgressFragment_imageSelectAvatar_configChange_checkGalleryIntent`

So that they pass?

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @ShubhadeepKarmakar!

In addition to the tests, please update the following so that we can merge your PR:

1. Your PR title should either describe the problem being solved, or make it the same as the issue title. 
2. Instead of saying "Added two lines to the codebase and resolved.", please explain the change you have made in terms of why the old code didn't work, and why your change fixes the bug. This is helpful for future developers reading the code.

**Comment by adhiamboperes** [comment]
Additionally, here is a [link](https://github.com/oppia/oppia-android/wiki/Interpreting-CI-Results) to the wiki to help you identify the cause of your failing CI checks, and another [link](https://github.com/oppia/oppia-android/wiki/Static-Analysis-Checks) to fixing static analysis check failures.

**Comment by kkmurerwa** [comment]
Hi @adhiamboperes. I see that you have already done a review of this PR. I don't think I have any further comments. @ShubhadeepKarmakar if you get stuck, feel free to reach out to me.

**Comment by ShubhadeepKarmakar** [comment]
> Hi @adhiamboperes. I see that you have already done a review of this PR. I don't think I have any further comments. @ShubhadeepKarmakar if you get stuck, feel free to reach out to me.

**Comment by ShubhadeepKarmakar** [comment]
@kkmurerwa I am facing this problem at the time of updating the test cases
error

**Comment by kkmurerwa** [comment]
> @kkmurerwa I am facing this problem at the time of updating the test cases error

Hi @ShubhadeepKarmakar. The problem could be the Android Studio version that you are using. Please check that you are using Android Studio Bumblebee.

**Comment by ShubhadeepKarmakar** [comment]
> > @kkmurerwa I am facing this problem at the time of updating the test cases error
> 
> Hi @ShubhadeepKarmakar. The problem could be the Android Studio version that you are using. Please check that you are using Android Studio Bumblebee.

I'm currently using Android Studio Electric Eel, 
Oky, lets see what happen after dropping the version.

**Comment by ShubhadeepKarmakar** [comment]
I'm facing an installation error while running the test testProfileProgressFragment_imageSelectAvatar_configChange_checkGalleryIntent

error2

**Comment by adhiamboperes** [comment]
> I'm facing an installation error while running the test testProfileProgressFragment_imageSelectAvatar_configChange_checkGalleryIntent
> 
> error2


My experience with Xiaomi devices is that you need to accept the install permission request. It's best to use the "remember my choice" option.

An alternative is to setup an Android emulator. Preferably pixel 3a sdk 29.

 Could you also take another look at the wiki set up instructions for additional information?

File: app/src/main/java/org/oppia/android/app/profileprogress/ProfileProgressActivityPresenter.kt (hunk 1 above)
Comment (ShubhadeepKarmakar) [reply app/src/main/java/org/oppia/android/app/profileprogress/ProfileProgressActivityPresenter.kt:53]: Successfully updated and passed two mentioned tests. @adhiamboperes you can check the updates.

File: app/src/sharedTest/java/org/oppia/android/app/profileprogress/ProfileProgressFragmentTest.kt [hunk 2]
```diff
@@ -360,25 +359,19 @@ class ProfileProgressFragmentTest {
...
       onView(withText(R.string.profile_picture_edit_alert_dialog_choose_from_library))
         .perform(click())
-      testCoroutineDispatchers.runCurrent()
       intended(expectedIntent)
-      onView(isRoot()).perform(orientationLandscape())
-      testCoroutineDispatchers.runCurrent()
-      intended(expectedIntent)
-      clickProfileProgressItem(itemPosition = 0, targetViewId = R.id.profile_edit_image)
-      // The dialog should still be open after a configuration change.
-      verifyTextInDialog(context.getString(R.string.profile_progress_edit_dialog_title))
```
Comment (adhiamboperes) [inline app/src/sharedTest/java/org/oppia/android/app/profileprogress/ProfileProgressFragmentTest.kt]: You have a good point in refactoring this test, but I think some of the removed assertions are still needed. I'd like to propose spiltting this into 2 seperate tests instead.

1. `testProfileProgressFragment_imageSelectAvatar_configChange_checkGalleryIntent`
This is the same as your current changes, testing that the gallery intent is still available in landscape.

2. Add new test `testFragment_imageSelectAvatar_configChange_profilePictureDialogIsVisible()`
This test should contain the lines of code that you have removed, to verify that
- user clicked on the profile avatar
- the edit profile picture dialog is visible
- user changed orientation to landscape
- the edit profile picture dialog is still visible

You can try out these steps manually in order to better understand the behaviour I am describing.

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks! 

I just had one more comment, but otherwise your changes look good so far.

File: app/src/sharedTest/java/org/oppia/android/app/profileprogress/ProfileProgressFragmentTest.kt (hunk 2 above)
Comment (ShubhadeepKarmakar) [reply app/src/sharedTest/java/org/oppia/android/app/profileprogress/ProfileProgressFragmentTest.kt]: Are you trying to say that someone opens the profile picture dialog and instead of dismissing the dialog simply rotates the screen and this time the dialog should remain visible to the user?

Comment (adhiamboperes) [reply app/src/sharedTest/java/org/oppia/android/app/profileprogress/ProfileProgressFragmentTest.kt]: Yes, see:
[device-2023-08-09-142348.webm](https://github.com/oppia/oppia-android/assets/59600948/3b8ecd53-2083-42b5-87c6-31e4383ca084)

Comment (ShubhadeepKarmakar) [reply app/src/sharedTest/java/org/oppia/android/app/profileprogress/ProfileProgressFragmentTest.kt]: I'm also trying to recording my screen to show you the same thing, lol. 
I understood.

Comment (ShubhadeepKarmakar) [reply app/src/sharedTest/java/org/oppia/android/app/profileprogress/ProfileProgressFragmentTest.kt]: @adhiamboperes check the commit.

**Review by adhiamboperes — APPROVED** [review]
Thanks @ShubhadeepKarmakar!

Congratulations on getting your first PR approveed! Your changes LGTM.
