### PR TITLE
Consolidate timing with a new fake oppia clock

### LINKED ISSUE #2599: TopicListControllerTest is flaky
After #2272 was checked in, TopicListControllerTest became flaky: https://github.com/oppia/oppia-android/runs/1809924511. testRetrievePromotedActivityList_markAllChapDoneInAllTopics_comingSoonTopicListIsCorrect seems to intermittently fail.

Due to #2272 being quite large, I don't want to revert it but we do need to figure out where this is coming from.

### PR DESCRIPTION
**Pull request by BenHenning**
Potentially fixes #2599.

This PR does a lot of things. At its core, it's introducing a new FakeOppiaClock that allows us to easily configure different time arrangements depending on the needs of tests. In particular:
- Three time modes are being introduced: fixed time, uptime milliseconds, and wall clock time
- Fixed time: this allows for a custom timestamp to be set (useful for the home screen greeting)
- Wall clock time: this is the default that matches current behavior; use the real wall clock time in both Robolectric & Espresso
- Uptime millis: use SystemClock.uptimeMillis(). This one is particularly noteworthy since in Robolectric this method returns a fixed time that's coordinated with TestCoroutineDispatchers. This is especially useful since it lets us use the coroutine dispatchers to affect the time returned by the clock (useful when trying to make sure subsequent operations can happen at different times--see below).

Beyond the above, this PR also makes substantial changes to StoryProgressTestHelper & corresponding classes that use it. These changes started as ensuring tests were able to leverage the benefits of FakeOppiaClock but this eventually turned into a broader cleanup/refactor. Specific details:
- StoryProgressTestHelper was moved to the testing package
- StoryProgressTestHelper now uses automatic time progression for chapter completion/recently played operations to ensure that the timestamp recorded for each operation is actually roughly reflective of the order in which they happen (to match production behavior)
- As a result of the above, StoryProgressTestHelper now requires tests to set FakeOppiaClock to MODE_UPTIME_MILLIS_TIME
- All other uses of StoryProgressController were migrated to StoryProgressTestHelper to consolidate the API & reduce test error
- This PR reimplements most of StoryProgressTestHelper's API such that:
  - The documentation is now clearer & easier to maintain
  - The API is well-ordered & comprehensive (e.g. there are no longer missing gaps)
  - Method names are consistent
  - Unused methods were removed (though new ones were added to ensure a comprehensive API was being introduced)
- StoryProgressTestHelperTest was rewritten from scratch to focus on verifying exactly the state the helper is supposed to create. This is a simplification over the current test suite, and it seemed necessary since the current tests were heavily encroaching on TopicControllerListTest to the point where it wasn't clear why we even had tests for the helper.

Other minor details:
- All tests were updated to mostly match their existing clock behaviors
- All references to ``Date().time`` were replaced with references to the clock (many of these were at worst incorrect, and at best potentially misleading)
- All other references to time were consolidated to OppiaClock
- OppiaClock itself was largely simplified (it only required exposing 2 methods & introducing a trivial implementation)
- HomeActivityTest is one of the more complicated tests due to it requiring the clock to operate in several different modes across the suite
- I didn't added tests for OppiaClockImpl since there weren't any for it initially, and the PR is already quite large
- I verified all UI tests directly affected by the clock changes (e.g. not refactors) are passing on Espresso, and all tests across the project on Robolectric (though I didn't re-run for a bit so I'm relying on CI for the initial run)
- Bazel might be broken, but I suspect it won't be straightforward to fix without #1904 so I'm going to defer updating Bazel tests to that PR to avoid further bloating this PR
- I ran tests from #2601 with these fixes >100 times each and saw no flakes

### CODE REVIEW

**Comment by BenHenning** [comment]
@rt4914 @anandwana001 @vinitamurthi PTAL when you get a chance. I *highly* suggest focusing just on your codeowners files, and potentially OppiaClock, FakeOppiaClock, StoryProgressTestHelper, and their corresponding tests to get an idea of the core changes. Mostly everything else is refactoring, and given the size of the project it bloated up the PR a bit. The majority of code is new stuff, and hopefully it's relatively straightforward to review.

**Comment by veena14cs** [comment]
> /cc @veena14cs you may want to see if this helps address your flakes elsewhere. I'm also not sure how much of your PR will be needed after this.

Thanks Ben! I will address this once it is in develop.

**Comment by veena14cs** [comment]
> > /cc @veena14cs you may want to see if this helps address your flakes elsewhere. I'm also not sure how much of your PR will be needed after this.
> 
> Thanks Ben! I will address this once it is in develop.

I have looked into `TopicListControllerTest` and `StroyProgressTestHelper`. All tests are passing, I made it run several times, there are no more flakes. My #2601 PR is no longer need as this PR fixes the issue #2599. Hence, I will be closing my PR.

My App layer PR #2320 is blocked on this. Once this is merged in develop I can update my testcases with FakeOppiaClock.

File: testing/src/main/java/org/oppia/android/testing/story/StoryProgressTestHelper.kt [hunk 1]
```diff
@@ -0,0 +1,774 @@
...
+   * Marks the first chapter of test topic 0 story 0 as completed.
+   *
+   * Note that this function will advance the clock & synchronize all background execution to ensure
+   * that any operations needed to achieve the requested state are completed and successful.
+   *
+   * @param profileId the profile we are setting partial progress of the fraction story for
+   * @param timestampOlderThanOneWeek if the timestamp for this topic progress is more than one week
+   *     ago
+   */
+  fun markCompletedTestTopic0Story0Exp2(profileId: ProfileId, timestampOlderThanOneWeek: Boolean) {
```
Comment (rt4914) [inline testing/src/main/java/org/oppia/android/testing/story/StoryProgressTestHelper.kt:81]: @BenHenning Here you are following the convention of id names which can make it confusing to use this function at other places. 
Considering these functions will be used in other files I think the name should be `markCompletedTestTopic0Story0Exp0` so that it looks less confusing in other files and in future we should update the `ids` too to match these. WDYT?

**Review by rt4914 — APPROVED** [review]
Looks good. The only suggestion is related to naming of functions in `StoryProgressTestHelper`

**Review by anandwana001 — APPROVED** [review]
LGTM

File: testing/src/main/java/org/oppia/android/testing/story/StoryProgressTestHelper.kt (hunk 1 above)
Comment (BenHenning) [reply testing/src/main/java/org/oppia/android/testing/story/StoryProgressTestHelper.kt:81]: I was on the fence about this since the opposite situation could easily happen (e.g. assuming that TEST_EXPLORATION_ID_0 is marked as completed in this case). Given both situations seem relatively equal, I don't think I have a strong stance.

@vinitamurthi / @anandwana001 / @Srikanth-Kb do any of you have thoughts here?

**Comment by BenHenning** [comment]
@vinitamurthi PTAL for codeowners when you get a chance. Thanks!

File: testing/src/main/java/org/oppia/android/testing/story/StoryProgressTestHelper.kt (hunk 1 above)
Comment (rt4914) [reply testing/src/main/java/org/oppia/android/testing/story/StoryProgressTestHelper.kt:81]: In my experience `markCompletedTestTopic0Story0Exp0` function or other helper functions are generally getting more used as compared to topic ids in app layer and therefore I am particularly in favour of `markCompletedTestTopic0Story0Exp0`

**Review by vinitamurthi — APPROVED** [review]

**Comment by vinitamurthi** [comment]
Merging this as all comments have been addressed

File: testing/src/main/java/org/oppia/android/testing/story/StoryProgressTestHelper.kt (hunk 1 above)
Comment (BenHenning) [reply testing/src/main/java/org/oppia/android/testing/story/StoryProgressTestHelper.kt:81]: Hmm I think this was merged before we could address this. I'll follow up with another PR to fix this @rt4914.

Comment (BenHenning) [reply testing/src/main/java/org/oppia/android/testing/story/StoryProgressTestHelper.kt:81]: Opened: #2695.
