### PR TITLE
Fix #3134: Admin Settings shows error message for null pin entries.

### LINKED ISSUE #3134: AdminSettingDialogFragment doesn’t show error message when the input is empty
**Describe the bug**
Submit button doesn't show error message when the text in the AdminSettingDialogFragment is empty

**To Reproduce**
1. Go to a 'User profile' with pin
2. Click on 'I FORGOT MY PIN'
3. Click submit
4. No error message displayed

**Expected behavior**
Show error message describing that the input is empty

**Video**

https://user-images.githubusercontent.com/54740946/116250573-762ebf80-a78b-11eb-89b9-fc43858bd9f6.mp4

### PR DESCRIPTION
**Pull request by Arnold2381**
## Explanation
Fixes #3134 

https://user-images.githubusercontent.com/46752548/117769644-96fa1900-b251-11eb-86f0-9363c7067383.mp4

Screenshot of all the tests passing on espresso
image

image

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by anandwana001** [comment]
Write test case too. 

https://github.com/oppia/oppia-android/wiki/Oppia-Android-Testing

**Comment by Arnold2381** [comment]
@anandwana001 I have a question, in the Administrator Controls, the submit button only gets activated when the user enters a pin of length 5 but in this PR in the video if you see when a user is going to Administrator controls even if the submit button isn't activated, he can use his keyboard submit button and if he does that with an incorrect pin of whatever length less than 5 an error is shown, so I did the same for null string but this cant be tested. So is it okay if I don't include tests for this?

**Comment by anandwana001** [comment]
@Arnold2381 Can we disable the keyboard from submitting?  this makes out the keyboard in sync with the submit button state.

**Comment by Arnold2381** [comment]
> @Arnold2381 Can we disable the keyboard from submitting? this makes out the keyboard in sync with the submit button state.

I did figure out a way to test it. But yes we can remove it, and if I do that, I will be removing the tests for that.

**Comment by Arnold2381** [comment]
@anandwana001 Also PTAL in this one.

File: app/src/main/java/org/oppia/android/app/profile/AdminAuthActivityPresenter.kt [hunk 1]
```diff
@@ -58,8 +57,7 @@ class AdminAuthActivityPresenter @Inject constructor(
     }
 
     binding.adminAuthInputPinEditText.setOnEditorActionListener { _, actionId, event ->
-      if (actionId == EditorInfo.IME_ACTION_DONE ||
-        (event != null && (event.keyCode == KeyEvent.KEYCODE_ENTER))
+      if (event != null && (event.keyCode == KeyEvent.KEYCODE_ENTER)
```
Comment (anandwana001) [inline app/src/main/java/org/oppia/android/app/profile/AdminAuthActivityPresenter.kt]: Are we able to use the keyboard action done,  if we input the correct pin in the input field? or Do we have to only use the submit button?

File: app/src/main/res/values/strings.xml [hunk 2]
```diff
@@ -201,6 +201,7 @@
   <string name="admin_auth_admin_controls_sub">Enter the Administrator PIN in order to access Administrator Controls.</string>
   <string name="admin_auth_pin">Administrator\'s PIN</string>
   <string name="admin_auth_incorrect">Incorrect Administrator PIN. Please try again.</string>
+  <string name="admin_auth_null">This field can\'t be empty.</string>
```
Comment (anandwana001) [inline app/src/main/res/values/strings.xml]: @rt4914 Do we need to confirm this message with Chantel or does it sounds good?

File: app/src/sharedTest/java/org/oppia/android/app/profile/AdminAuthActivityTest.kt [hunk 3]
```diff
@@ -216,30 +191,6 @@ class AdminAuthActivityTest {
     }
   }
 
-  @Test
-  fun testAdminAuthActivity_inputCorrectPassword_imeAction_opensAdminControlsActivity() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/profile/AdminAuthActivityTest.kt]: I don't think it's an appropriate solution to solve this issue, we do need the keyboard action done feature so that users can submit input using the keyboard also, not dependent on the submit button.

**Review by anandwana001 — CHANGES_REQUESTED** [review]
Thanks @Arnold2381 

left a few thoughts, will check test file in next iteration.

File: app/src/main/res/values/strings.xml (hunk 2 above)
Comment (rt4914) [reply app/src/main/res/values/strings.xml]: @mschanteltc If you check the video in the issue: https://github.com/oppia/oppia-android/issues/3134 you will see that if the learner clicks on `Submit` button if there is no text then there is no error message. Unfortunately we cannot `disable` the `Submit` button here so we will have to show error message only. 
So does `This field can't be empty` makes sense to me?
To me `Please enter Administrator Pin` makes more sense meaning something precise as an error.
WDYT?

**Comment by Arnold2381** [comment]
@anandwana001 Sorry for the late reply, I was busy with my college exams and everything.
I have made the keyboard button in sync with the submit button. And also user can use the keyboard submit button only when he enters a pin of length equal to the admin pin. And also because we are removing the functionality of not allowing the user to press the submit button before the admin pin's length, I don't think we need the tests for that so I removed the two tests for the same.
PTAL

File: app/src/main/res/values/strings.xml (hunk 2 above)
Comment (mschanteltc) [reply app/src/main/res/values/strings.xml]: I agree that the latter choice `Please enter Administrator PIN` works better.

**Comment by anandwana001** [comment]
@Arnold2381 Please follow up on all my earlier comments.
Also, Chantel has confirm the string here - https://github.com/oppia/oppia-android/pull/3181#discussion_r640158432

File: app/src/sharedTest/java/org/oppia/android/app/profile/AdminAuthActivityTest.kt (hunk 3 above)
Comment (Arnold2381) [reply app/src/sharedTest/java/org/oppia/android/app/profile/AdminAuthActivityTest.kt]: Yes, I have changed it now. 
The keyboard button can be used to submit but only when the length of the pin entered is the same as the adminPin's length.

File: app/src/main/java/org/oppia/android/app/profile/AdminAuthActivityPresenter.kt (hunk 1 above)
Comment (Arnold2381) [reply app/src/main/java/org/oppia/android/app/profile/AdminAuthActivityPresenter.kt]: Yes, we can use the keyboard button. It same as the submit button now.
Until and unless the length of the pin entered is less than the adminPin's length the keyboard submit can be clicked but would have no action.

Comment (anandwana001) [reply app/src/main/java/org/oppia/android/app/profile/AdminAuthActivityPresenter.kt]: > but would have no action.

Will this show any error message or nothing will happen?

File: app/src/sharedTest/java/org/oppia/android/app/profile/AdminAuthActivityTest.kt (hunk 3 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/profile/AdminAuthActivityTest.kt]: Do we need to test in `app/src/sharedTest/java/org/oppia/android/app/profile/AdminAuthActivityTest.kt` as well? 
As we are removing the test from here, I think we should update the test as per the button/keyboard thing rather than removing the test.

File: app/src/main/java/org/oppia/android/app/profile/AdminAuthActivityPresenter.kt (hunk 1 above)
Comment (Arnold2381) [reply app/src/main/java/org/oppia/android/app/profile/AdminAuthActivityPresenter.kt]: No, it won't show. It will act as ditto as the submit button, so nothing will happen.

File: app/src/sharedTest/java/org/oppia/android/app/profile/AdminAuthActivityTest.kt (hunk 3 above)
Comment (Arnold2381) [reply app/src/sharedTest/java/org/oppia/android/app/profile/AdminAuthActivityTest.kt]: I made some change now, and I don't think we need those tests, the two tests I removed are testing cases which won't occur now. A pin less than the length of the admin pin will have no action when the keyboard submit button is pressed. So I don't think they are needed.
Your views?

**Comment by anandwana001** [comment]
Hi @Arnold2381 

Looks like we lost track of this PR, are you still working on this, and could you update on where are we on this PR. Also, whenever you need a review of any member, please comment the persons' GitHub handle and add `PTAL`, our Oppiabot will assign that person to the assignee section so that the PR doesn't go off the track.

**Comment by Arnold2381** [comment]
Hello @anandwana001 
Sorry! I thought replying to your reviews would notify you, next time I would do the same. .

Yea so our discussion was on the tests I removed. I suggest there is no need of the tests and I removed it because the cases its testing for will never arise.  As you will see when will enter a pin less then the length of the adminPin the button doesn't gets activated so I don't think it will ever show an error. The tests were required before because the keyboard submit button was allowing the user to press the submit button before the length of the admin pin entered but now, the keyboard submit button will have no action until and unless the pin length is same as admin and once same it acts same as the normal submit button.
So i think whatever is done till now is working.

**Comment by Arnold2381** [comment]
@anandwana001 PTAL

**Comment by rt4914** [comment]
@anandwana001 PTAL at this PR.

**Comment by anandwana001** [comment]
I will take a look at this tonight.

File: app/src/sharedTest/java/org/oppia/android/app/profile/AdminAuthActivityTest.kt [hunk 4]
```diff
@@ -291,75 +291,6 @@ class AdminAuthActivityTest {
     }
   }
 
-  @Test
-  fun testAdminAuthActivity_inputIncorrectPassword_inputAgain_errorIsGone() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/profile/AdminAuthActivityTest.kt:302]: why are we removing this test?

File: app/src/sharedTest/java/org/oppia/android/app/profile/AdminAuthActivityTest.kt [hunk 5]
```diff
@@ -291,75 +291,6 @@ class AdminAuthActivityTest {
...
-        editTextInputAction.appendText("4"),
-        closeSoftKeyboard()
-      )
-      onView(withId(R.id.admin_auth_input_pin))
-        .check(matches(hasNoErrorText()))
-    }
-  }
-
-  @Test
-  fun testAdminAuthActivity_inputIncorrectPassword_correct_imeAction_errorIsGone() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/profile/AdminAuthActivityTest.kt:337]: why are we removing this test?

File: app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt [hunk 6]
```diff
@@ -673,6 +673,73 @@ class PinPasswordActivityTest {
     }
   }
 
+  @Test
+  fun testPinPassword_withUser_forgot_inputAdminPinAndNullPin_errorIsDisplayed() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt:683]: Also, add a configChange version on this test and separately test it.

File: app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt [hunk 7]
```diff
@@ -673,6 +673,73 @@ class PinPasswordActivityTest {
...
+        .perform(editTextInputAction.appendText(""), closeSoftKeyboard())
+      onView(withId(R.id.forgot_pin)).perform(click())
+      onView(
+        allOf(
+          withId(R.id.admin_settings_input_pin_edit_text),
+          isDescendantOfA(withId(R.id.admin_settings_input_pin))
+        )
+      ).inRoot(isDialog())
+        .perform(editTextInputAction.appendText(""), closeSoftKeyboard())
+      onView(withText(context.getString(R.string.admin_settings_submit)))
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt:701]: Add a test case where click on the action done in softKeyboard, rather than `admin_settings_submit`.

**Review by anandwana001 — CHANGES_REQUESTED** [review]
Tested it, seems working for me. 

Nit queries regarding test cases, else LGTM.

File: app/src/sharedTest/java/org/oppia/android/app/profile/AdminAuthActivityTest.kt (hunk 4 above)
Comment (Arnold2381) [reply app/src/sharedTest/java/org/oppia/android/app/profile/AdminAuthActivityTest.kt:302]: When soft keyboard didn't function as same as the submit button we needed this test. because that time even if the length of the pin was less then the length of the admin pin the soft keyboard submit was working but now as I have already added the functionality that soft keyboard submit button will only work when the length is same for both entered pin and admin pin there is no use of this.

File: app/src/sharedTest/java/org/oppia/android/app/profile/AdminAuthActivityTest.kt (hunk 5 above)
Comment (Arnold2381) [reply app/src/sharedTest/java/org/oppia/android/app/profile/AdminAuthActivityTest.kt:337]: same.

File: app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt (hunk 6 above)
Comment (Arnold2381) [reply app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt:683]: Done and updated the sc of passed tests.

File: app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt (hunk 7 above)
Comment (Arnold2381) [reply app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt:701]: ditto.

**Comment by Arnold2381** [comment]
@anandwana001 PTAL.

File: app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt [hunk 8]
```diff
@@ -673,6 +674,147 @@ class PinPasswordActivityTest {
...
+        )
+      ).inRoot(isDialog())
+        .perform(editTextInputAction.appendText(""), ViewActions.pressImeActionButton())
+      onView(withId(R.id.admin_settings_input_pin))
+        .check(matches(hasErrorText(R.string.admin_auth_null)))
+    }
+  }
+
+  @Test
+  fun testPinPassword_User_forgot_adminPinAndNullPin_configChange_imeAction_errorIsDisplayed() {
```
Comment (rt4914) [inline app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt]: Rename to `testPinPassword_user_forgot_adminPinAndNullPin_configChange_imeAction_errorIsDisplayed`

File: app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt [hunk 9]
```diff
@@ -673,6 +674,147 @@ class PinPasswordActivityTest {
...
+      onView(withId(R.id.input_pin))
+        .perform(editTextInputAction.appendText(""), closeSoftKeyboard())
+      onView(withId(R.id.forgot_pin)).perform(click())
+      onView(
+        allOf(
+          withId(R.id.admin_settings_input_pin_edit_text),
+          isDescendantOfA(withId(R.id.admin_settings_input_pin))
+        )
+      ).inRoot(isDialog())
+        .perform(editTextInputAction.appendText(""), ViewActions.pressImeActionButton())
```
Comment (rt4914) [inline app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt]: Use direct imports
`.perform(editTextInputAction.appendText(""), pressImeActionButton())`

File: app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt [hunk 10]
```diff
@@ -673,6 +674,147 @@ class PinPasswordActivityTest {
...
```
Comment (rt4914) [inline app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt]: Ditto

**Review by rt4914 — APPROVED** [review]
Nit changes suggested. Else looks good. 

Merge with latest develop and wait for @anandwana001 approval.

**Comment by Arnold2381** [comment]
@rt4914 done!

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Review by anandwana001 — APPROVED** [review]
LGTM
