### PR TITLE
Fix #4581: Privacy policy hyperlink in Terms of Service

### LINKED ISSUE #4581: Privacy policy hyperlink is not opening in Terms of Service
**Describe the bug**
Privacy policy hyperlink is not opening in Terms of Service

**To Reproduce**
1. Install Oppia and Open it
2. Click on Next to get to the last page where Terms of Service link is present
3. Click on Terms of Service
4. Scroll down and click on Privacy policy link

**Expected behavior**
On clicking Privacy policy link it should open the privacy policy

**Demonstration**

https://user-images.githubusercontent.com/101634267/189470966-82a2fa66-9f53-4417-b041-e6226e845edb.mp4

**Environment**
Mobile: One Plus Nord2 5G
Android Version: 11
App Version: 0.9-beta-3f935261e0

### PR DESCRIPTION
**Pull request by veena14cs**
## Explanation
Fixes #4581 . This PR fixes the privacy policy hyperlink in Terms of service page.

**Before and after video**

https://user-images.githubusercontent.com/16301028/191303416-fb26934b-f0ec-4eb5-9d32-d73869886e48.mp4 
  
https://user-images.githubusercontent.com/16301028/191303721-53f8b25f-01aa-4b23-bf1a-2de8212c07b0.mp4

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

### CODE REVIEW

File: app/src/main/java/org/oppia/android/app/policies/PoliciesActivity.kt [hunk 1]
```diff
@@ -45,4 +47,8 @@ class PoliciesActivity : InjectableAppCompatActivity() {
       }
     }
   }
+
+  override fun onRouteToPolicies(policyPage: PolicyPage) {
+    startActivity(createPoliciesActivityIntent(this, policyPage))
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/policies/PoliciesActivity.kt:55]: Please add tests to verify that this activity can correctly route to each type of activity.

File: app/src/main/java/org/oppia/android/app/policies/PoliciesFragmentPresenter.kt [hunk 2]
```diff
@@ -80,4 +79,13 @@ class PoliciesFragmentPresenter @Inject constructor(
       supportsConceptCards = false
     )
   }
+
+  override fun onPolicyPageLinkClicked(policyType: PolicyType) {
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/policies/PoliciesFragmentPresenter.kt:83]: Please include tests to verify that the host activity is called as a listener for each policy type.

File: app/src/main/res/values/terms_of_service.xml [hunk 3]
```diff
@@ -38,10 +38,7 @@
     <p>
       For more information about how we use your personal information and what
       types of information we collect and why, please refer to our
-      <a href="/privacy-policy"
-         [routerLink]="'/' + PAGES_REGISTERED_WITH_FRONTEND.PRIVACY.ROUTE">
-         Privacy Policy
-      </a>.
+      <oppia-noninteractive-policy link=\"privacy\">Privacy Policy</oppia-noninteractive-policy>.
```
Comment (BenHenning) [inline app/src/main/res/values/terms_of_service.xml:41]: Please include a test to verify this link, specifically, does the right thing when clicked on.

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @veena14cs! Had just a few comments, but otherwise the solution LGTM (I think we're mainly missing tests).

Could you please also include before & after videos showing the fix?

**Comment by BenHenning** [comment]
@rt4914 I think you can take a look at the XML change, or the broader PR if you're so inclined.

**Review by rt4914 — APPROVED** [review]
Other than tests, things work good. Approving and relying on Ben's review for tests.

File: app/src/main/java/org/oppia/android/app/policies/PoliciesActivity.kt (hunk 1 above)
Comment (veena14cs) [reply app/src/main/java/org/oppia/android/app/policies/PoliciesActivity.kt:55]: Added test to verify this.

File: app/src/main/java/org/oppia/android/app/policies/PoliciesFragmentPresenter.kt (hunk 2 above)
Comment (veena14cs) [reply app/src/main/java/org/oppia/android/app/policies/PoliciesFragmentPresenter.kt:83]: Done.

File: app/src/main/res/values/terms_of_service.xml (hunk 3 above)
Comment (veena14cs) [reply app/src/main/res/values/terms_of_service.xml:41]: Done.

**Comment by BenHenning** [comment]
Hi @veena14cs I sent this on chat, but also sending it here:

I think there are two different behaviors that need to be verified here, and at different levels:
- Clicking the hyperlink calls the activity's listener callback. This is verified in the fragment test, and should be verified like we do for the beta notice fragment: https://github.com/oppia/oppia-android/blob/18814f57b00ec8d3e25536a5c6b6633138ac677c/app/src/main/java/org/oppia/android/app/notice/testing/BetaNoticeDialogFragmentTestActivity.kt#L16 (where we use a mock assigned in the test and verified there).
- Clicking the hyperlink opens the correct activity (this should be verified in an activity test since it's verifying the activity's behavior, not the fragment's).

At the moment, I think your test is conflating testing an activity behavior at the fragment level, and this is resulting in actually testing the test activity which isn't what we want

File: app/src/main/java/org/oppia/android/app/testing/PoliciesFragmentTestActivity.kt [hunk 4]
```diff
@@ -46,4 +47,8 @@ class PoliciesFragmentTestActivity : InjectableAppCompatActivity() {
       }
     }
   }
+
+  override fun onRouteToPolicies(policyPage: PolicyPage) {
+    startActivity(createPoliciesFragmentTestActivity(this, policyPage))
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/testing/PoliciesFragmentTestActivity.kt]: Per https://github.com/oppia/oppia-android/pull/4595#issuecomment-1276766636 this should be calling forward to a test-set mock to verify the callback (to ensure that we're testing as little of the test activity as possible).

File: app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesActivityTest.kt [hunk 5]
```diff
@@ -96,14 +122,43 @@ class PoliciesActivityTest {
...
+    Intents.init()
     setUpTestApplicationComponent()
+    testCoroutineDispatchers.registerIdlingResource()
   }
 
+  @After
+  fun tearDown() {
+    Intents.release()
+    testCoroutineDispatchers.unregisterIdlingResource()
+  }
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesActivityTest.kt:147]: Nit: add newline after this bracket for consistency.

File: app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesActivityTest.kt [hunk 6]
```diff
@@ -149,6 +204,63 @@ class PoliciesActivityTest {
       }
     }
   }
+  @Test
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesActivityTest.kt]: Newline before this test for consistency.

File: app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesActivityTest.kt [hunk 7]
```diff
@@ -149,6 +204,63 @@ class PoliciesActivityTest {
...
+  fun testPoliciesFragment_forTermsOfService_opensPrivacyPolicyPage() {
+    launch<PoliciesActivity>(
+      PoliciesActivity.createPoliciesActivityIntent(
+        ApplicationProvider.getApplicationContext(),
+        PolicyPage.TERMS_OF_SERVICE
+      )
+    ).use { activityScenario ->
+      activityScenario.onActivity { activity ->
+
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesActivityTest.kt]: No newline here for consistency.

File: app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesActivityTest.kt [hunk 8]
```diff
@@ -149,6 +204,63 @@ class PoliciesActivityTest {
       }
     }
   }
+  @Test
+  fun testPoliciesFragment_forTermsOfService_opensPrivacyPolicyPage() {
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesActivityTest.kt]: What's actually being tested here? The test name is missing the action being done.

File: app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesActivityTest.kt [hunk 9]
```diff
@@ -149,6 +204,63 @@ class PoliciesActivityTest {
...
+
+        testCoroutineDispatchers.runCurrent()
+        val htmlParser = htmlParserFactory.create(
+          policyOppiaTagActionListener = mockPolicyOppiaTagActionListener,
+          displayLocale = appLanguageLocaleHandler.getDisplayLocale()
+        )
+        val textView: TextView =
+          activity.findViewById(R.id.policy_description_text_view)
+
+        val htmlResult: Spannable = htmlParser.parseOppiaHtml(
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesActivityTest.kt]: Doesn't the fragment already do this part--why do we need to parse it again?

File: app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesFragmentTest.kt [hunk 10]
```diff
@@ -246,6 +276,58 @@ class PoliciesFragmentTest {
...
+          supportsConceptCards = false
+        )
+        textView.text = htmlResult
+        // Verify the displayed text is correct & has a clickable span.
+        val clickableSpans = htmlResult.getSpansFromWholeString(ClickableSpan::class)
+        assertThat(clickableSpans).isNotEmpty()
+        // Call each of the spans.
+        clickableSpans[0].onClick(textView)
+        // Verify that the tag listener is called.
+        verify(mockPolicyOppiaTagActionListener).onPolicyPageLinkClicked(
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesFragmentTest.kt]: Only this should be needed--the intent verification below isn't needed if we're only verifying the mock.

File: app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesFragmentTest.kt [hunk 11]
```diff
@@ -246,6 +276,58 @@ class PoliciesFragmentTest {
...
+
+        testCoroutineDispatchers.runCurrent()
+        val htmlParser = htmlParserFactory.create(
+          policyOppiaTagActionListener = mockPolicyOppiaTagActionListener,
+          displayLocale = appLanguageLocaleHandler.getDisplayLocale()
+        )
+        val textView: TextView =
+          activity.findViewById(R.id.policy_description_text_view)
+
+        val htmlResult: Spannable = htmlParser.parseOppiaHtml(
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesFragmentTest.kt]: Ditto here--this shouldn't be needed per the code being tested.

File: app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesFragmentTest.kt [hunk 12]
```diff
@@ -246,6 +276,58 @@ class PoliciesFragmentTest {
...
+  @Test
+  fun testPoliciesFragment_forTermsOfService_opensPrivacyPolicyPage() {
+    launch<PoliciesFragmentTestActivity>(
+      createPoliciesFragmentTestActivity(
+        getApplicationContext(),
+        PolicyPage.TERMS_OF_SERVICE
+      )
+    ).use { activityScenario ->
+      activityScenario.onActivity { activity ->
+
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesFragmentTest.kt]: Ditto here.

File: app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesFragmentTest.kt [hunk 13]
```diff
@@ -246,6 +276,58 @@ class PoliciesFragmentTest {
     }
   }
 
+  @Test
+  fun testPoliciesFragment_forTermsOfService_opensPrivacyPolicyPage() {
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesFragmentTest.kt]: Ditto here.

File: app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesFragmentTest.kt [hunk 14]
```diff
@@ -246,6 +276,58 @@ class PoliciesFragmentTest {
...
+      createPoliciesFragmentTestActivity(
+        getApplicationContext(),
+        PolicyPage.TERMS_OF_SERVICE
+      )
+    ).use { activityScenario ->
+      activityScenario.onActivity { activity ->
+
+        testCoroutineDispatchers.runCurrent()
+        val htmlParser = htmlParserFactory.create(
+          policyOppiaTagActionListener = mockPolicyOppiaTagActionListener,
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesFragmentTest.kt]: The mock should be called via the test activity callback, not HtmlParser (otherwise, you aren't testing the fragment).

File: app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesActivityTest.kt [hunk 15]
```diff
@@ -149,6 +204,63 @@ class PoliciesActivityTest {
...
+          supportsConceptCards = false
+        )
+        textView.text = htmlResult
+        // Verify the displayed text is correct & has a clickable span.
+        val clickableSpans = htmlResult.getSpansFromWholeString(ClickableSpan::class)
+        assertThat(clickableSpans).isNotEmpty()
+        // Call each of the spans.
+        clickableSpans[0].onClick(textView)
+        // Verify that the tag listener is called.
+        verify(mockPolicyOppiaTagActionListener).onPolicyPageLinkClicked(
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesActivityTest.kt]: The mock isn't needed here since we're testing the activity's behavior (which is that the correct intent is sent to start the corresponding activity).

**Review by BenHenning — COMMENTED** [review]
Thanks @veena14cs; I took another pass. I don't think my last comment was fully addressed, so I've left additional comments to hopefully provide more context on how to address the comment.

Please send back once the comments are addressed, and after CI checks are passing.

File: app/src/main/java/org/oppia/android/app/testing/PoliciesFragmentTestActivity.kt (hunk 4 above)
Comment (veena14cs) [reply app/src/main/java/org/oppia/android/app/testing/PoliciesFragmentTestActivity.kt]: Done.

File: app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesActivityTest.kt (hunk 5 above)
Comment (veena14cs) [reply app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesActivityTest.kt:147]: Done.

File: app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesActivityTest.kt (hunk 6 above)
Comment (veena14cs) [reply app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesActivityTest.kt]: Done.

File: app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesFragmentTest.kt (hunk 11 above)
Comment (veena14cs) [reply app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesFragmentTest.kt]: removed.

File: app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesFragmentTest.kt (hunk 12 above)
Comment (veena14cs) [reply app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesFragmentTest.kt]: done.

File: app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesFragmentTest.kt (hunk 13 above)
Comment (veena14cs) [reply app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesFragmentTest.kt]: done.

File: app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesFragmentTest.kt (hunk 14 above)
Comment (veena14cs) [reply app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesFragmentTest.kt]: I have added callback. I am getting below error.
Screenshot (89)

File: app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesActivityTest.kt (hunk 9 above)
Comment (veena14cs) [reply app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesActivityTest.kt]: To perform click on the link I used html parser here. I have removed it as per https://github.com/oppia/oppia-android/pull/4595#issuecomment-1276766636

File: app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesActivityTest.kt (hunk 8 above)
Comment (veena14cs) [reply app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesActivityTest.kt]: I have removed this test.

File: app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesActivityTest.kt (hunk 7 above)
Comment (veena14cs) [reply app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesActivityTest.kt]: Removed.

File: app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesFragmentTest.kt (hunk 10 above)
Comment (veena14cs) [reply app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesFragmentTest.kt]: Removed.

File: app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesActivityTest.kt (hunk 15 above)
Comment (veena14cs) [reply app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesActivityTest.kt]: Removed it.

File: app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesFragmentTest.kt [hunk 16]
```diff
@@ -246,6 +272,28 @@ class PoliciesFragmentTest {
     }
   }
 
+  @Test
+  fun testPoliciesFragment_inTermsOfServicePage_clickOnPrivacyLink_opensPrivacyPolicyPage() {
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesFragmentTest.kt]:
```suggestion
  fun testPoliciesFragment_inTermsOfServicePage_clickOnPrivacyLink_callsRouteToPrivacyPolicy() {
```

File: app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesActivityTest.kt [hunk 17]
```diff
@@ -204,63 +176,6 @@ class PoliciesActivityTest {
       }
     }
   }
-  @Test
-  fun testPoliciesFragment_forTermsOfService_opensPrivacyPolicyPage() {
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesActivityTest.kt]: We still want to test the intent part, just not the mock part (the mock is used for testing the fragment, and intents are used for testing the activity).

File: app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesActivityTest.kt (hunk 8 above)
Comment (BenHenning) [reply app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesActivityTest.kt]: To be clear, I didn't mean for the test to be removed just that its name needs to be clearer. I left a new comment to track this, though.

File: app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesFragmentTest.kt [hunk 18]
```diff
@@ -246,6 +272,28 @@ class PoliciesFragmentTest {
...
+        PolicyPage.TERMS_OF_SERVICE
+      )
+    ).use { scenario ->
+      scenario.onActivity {
+        it.mockCallbackListener = mockRouteToPoliciesListener
+        onView(withId(R.id.policy_description_text_view))
+          .check(matches(isDisplayed()))
+        onView(withId(R.id.policy_description_text_view))
+          .check(matches(withText(containsString("Privacy Policy"))))
+          .perform(click())
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesFragmentTest.kt]: Is this actually performing the click? I wonder if we still need to retrieve the spans from the text (not parsing, but just retrieving the ones that should already be there) in order to perform the click.

File: app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesFragmentTest.kt (hunk 14 above)
Comment (BenHenning) [reply app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesFragmentTest.kt]: Left a follow-up comment on code that I think might be causing your issue, but otherwise per my comment in chat this is something that will need to be debugged.

**Review by BenHenning — COMMENTED** [review]
Thanks @veena14cs. Took another pass--PTAL.

File: app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesActivityTest.kt (hunk 17 above)
Comment (veena14cs) [reply app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesActivityTest.kt]: Ah. I fixed it. Thanks.

File: app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesFragmentTest.kt (hunk 18 above)
Comment (veena14cs) [reply app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesFragmentTest.kt]: No this was the issue. I added clickable spans and now the mock works.

**Comment by veena14cs** [comment]
> Thanks @veena14cs. Took another pass--PTAL.

Thanks. I have fixed the issue. PTAL.

File: app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesActivityTest.kt [hunk 19]
```diff
@@ -132,6 +172,46 @@ class PoliciesActivityTest {
...
+        testCoroutineDispatchers.runCurrent()
+
+        val policiesArguments =
+          PoliciesActivityParams
+            .newBuilder()
+            .setPolicyPage(PolicyPage.PRIVACY_POLICY)
+            .build()
+        Intents.intended(
+          IntentMatchers.hasComponent(
+            ComponentNameMatchers.hasClassName(
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesActivityTest.kt]: Please directly import these & fit this to one line as we do elsewhere.

Ditto for hasExtras below.

File: app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesActivityTest.kt [hunk 20]
```diff
@@ -132,6 +172,46 @@ class PoliciesActivityTest {
...
+  fun testPoliciesActivity_inTermsOfServicePage_clickOnPrivacyLink_callsRouteToPrivacyPolicy() {
+    launch<PoliciesActivity>(
+      PoliciesActivity.createPoliciesActivityIntent(
+        ApplicationProvider.getApplicationContext(),
+        PolicyPage.TERMS_OF_SERVICE
+      )
+    ).use { scenario ->
+      scenario.onActivity {
+        onView(withId(R.id.policy_description_text_view))
+          .check(matches(isDisplayed()))
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesActivityTest.kt]: Nit: can fit on one line.

File: app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesActivityTest.kt [hunk 21]
```diff
@@ -132,6 +172,46 @@ class PoliciesActivityTest {
     }
   }
 
+  @Test
+  fun testPoliciesActivity_inTermsOfServicePage_clickOnPrivacyLink_callsRouteToPrivacyPolicy() {
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesActivityTest.kt]:
```suggestion
  fun testPoliciesActivity_inTermsOfServicePage_clickOnPrivacyLink_routesToPrivacyPolicy() {
```

File: app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesFragmentTest.kt [hunk 22]
```diff
@@ -246,6 +266,30 @@ class PoliciesFragmentTest {
...
+    launch<PoliciesFragmentTestActivity>(
+      createPoliciesFragmentTestActivity(
+        getApplicationContext(),
+        PolicyPage.TERMS_OF_SERVICE
+      )
+    ).use { scenario ->
+      scenario.onActivity {
+        it.mockCallbackListener = mockRouteToPoliciesListener
+        onView(withId(R.id.policy_description_text_view))
+          .check(matches(isDisplayed()))
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesFragmentTest.kt]: Nit: can fit on one line.

File: app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesFragmentTest.kt (hunk 14 above)
Comment (BenHenning) [reply app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesFragmentTest.kt]: Resolved in the latest iteration.

**Review by BenHenning — COMMENTED** [review]
Thanks @veena14cs! Just a few nits left, otherwise this LGTM.

File: app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesActivityTest.kt (hunk 19 above)
Comment (veena14cs) [reply app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesActivityTest.kt]: Done.

File: app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesFragmentTest.kt (hunk 22 above)
Comment (veena14cs) [reply app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesFragmentTest.kt]: Done.

File: app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesActivityTest.kt (hunk 20 above)
Comment (veena14cs) [reply app/src/sharedTest/java/org/oppia/android/app/policies/PoliciesActivityTest.kt]: Done.

**Comment by veena14cs** [comment]
> Thanks @veena14cs! Just a few nits left, otherwise this LGTM.

Thanks @BenHenning I have fixed nits. PTAL.

**Review by BenHenning — APPROVED** [review]
Thanks @veena14cs! This LGTM.
