### PR TITLE
Fix #2036: Fix file formatting under fractioninput package

### LINKED ISSUE #2036: Fix file formatting under fractioninput package
**Describe the bug**
All the files, under the package `domain/src/test/java/org/oppia/android/domain/classify/rules/fractioninput` are not in the correct format. 

**Expected behavior**
File format should be follow from this file - [TextInputEqualsRuleClassifierProviderTest](https://github.com/oppia/oppia-android/blob/develop/domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputEqualsRuleClassifierProviderTest.kt
)

**Correct Order**
Constant values
Dagger injection
Local variables
Test Before setup
Tests
Dagger Setup

### PR DESCRIPTION
**Pull request by MaskedCarrot**
## Explanation
Fixes #2036
Reformated code in files under fraction input package.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by anandwana001** [comment]
@MaskedCarrot Fix the PR title.

File: domain/src/test/java/org/oppia/android/domain/classify/rules/fractioninput/FractionInputHasNumeratorEqualToRuleClassifierProviderTest.kt [hunk 1]
```diff
@@ -30,9 +32,9 @@ class FractionInputHasNumeratorEqualToRuleClassifierProviderTest {
   private val FRACTION_2_OVER_4 = createFraction(isNegative = false, numerator = 2, denominator = 4)
   private val FRACTION_NEGATIVE_2_OVER_4 =
     createFraction(isNegative = true, numerator = -2, denominator = 4)
-  private val SIGNED_INT_1 = createSignedInt(1)
-  private val SIGNED_INT_2 = createSignedInt(2)
-  private val SIGNED_INT_NEGATIVE_2 = createSignedInt(-2)
+  private val SIGNED_INT_1 = createSignedInt(value = 1)
```
Comment (anandwana001) [inline domain/src/test/java/org/oppia/android/domain/classify/rules/fractioninput/FractionInputHasNumeratorEqualToRuleClassifierProviderTest.kt]: leave a empty line after `class FractionInputHasNumeratorEqualToRuleClassifierProviderTest {`

File: domain/src/test/java/org/oppia/android/domain/classify/rules/fractioninput/FractionInputHasDenominatorEqualToRuleClassifierProviderTest.kt [hunk 2]
```diff
@@ -25,11 +26,17 @@ import kotlin.test.fail
...
 @Config(manifest = Config.NONE)
 class FractionInputHasDenominatorEqualToRuleClassifierProviderTest {
-  private val WHOLE_NUMBER_123 = createWholeNumber(isNegative = false, value = 123)
-  private val FRACTION_1_OVER_2 = createFraction(isNegative = false, numerator = 1, denominator = 2)
-  private val FRACTION_2_OVER_4 = createFraction(isNegative = false, numerator = 2, denominator = 4)
-  private val NON_NEGATIVE_VALUE_1 = createNonNegativeInt(value = 1)
-  private val NON_NEGATIVE_VALUE_2 = createNonNegativeInt(value = 2)
+
+  private val WHOLE_NUMBER_123 =
+    createWholeNumber(isNegative = false, value = 123)
```
Comment (anandwana001) [inline domain/src/test/java/org/oppia/android/domain/classify/rules/fractioninput/FractionInputHasDenominatorEqualToRuleClassifierProviderTest.kt]: For the consistency let's access methods using the object, not importing directly. 
`InteractionObjectTestBuilder`. 

@aggarwalpulkit596 any suggestion on this? Either we should import directly or using object, which could be a good practice?

File: domain/src/test/java/org/oppia/android/domain/classify/rules/fractioninput/FractionInputHasDenominatorEqualToRuleClassifierProviderTest.kt [hunk 3]
```diff
@@ -25,11 +26,17 @@ import kotlin.test.fail
...
+  private val FRACTION_1_OVER_2 =
+    createFraction(isNegative = false, numerator = 1, denominator = 2)
+  private val FRACTION_2_OVER_4 =
```
Comment (anandwana001) [inline domain/src/test/java/org/oppia/android/domain/classify/rules/fractioninput/FractionInputHasDenominatorEqualToRuleClassifierProviderTest.kt]: check the naming of variables in the reference file. 
example - `STRING_VALUE_TEST_UPPERCASE`

this could be `FRACTION_VALUE_TEST_1_OVER_2 `
`<type>_value_test_<what_to_test>`

**Review by anandwana001 — CHANGES_REQUESTED** [review]
Thanks @MaskedCarrot 
took the first pass on this pr and suggested few updates.

File: domain/src/test/java/org/oppia/android/domain/classify/rules/fractioninput/FractionInputHasDenominatorEqualToRuleClassifierProviderTest.kt (hunk 2 above)
Comment (MaskedCarrot) [reply domain/src/test/java/org/oppia/android/domain/classify/rules/fractioninput/FractionInputHasDenominatorEqualToRuleClassifierProviderTest.kt]: if we write `InteractionObjectTestBuilser.createMixedNumber(isNegative = false, wholeNumber = 123, numerator = 1, denominator = 2)` then the length of this line goes over 100 words. Should I remove `isNegative` and other such values ?

Comment (anandwana001) [reply domain/src/test/java/org/oppia/android/domain/classify/rules/fractioninput/FractionInputHasDenominatorEqualToRuleClassifierProviderTest.kt]: the line can be broken down easily, but keep the consistency. 

```kotlin
= InteractionObjectTestBuilser.createMixedNumber(
    isNegative = false,
    wholeNumber = 123,
    numerator = 1,
    denominator = 2
  )
```

**Comment by anandwana001** [comment]
@MaskedCarrot  Correct the PR description as well. Check the second point of the checklist.

File: domain/src/test/java/org/oppia/android/domain/classify/rules/fractioninput/FractionInputHasDenominatorEqualToRuleClassifierProviderTest.kt (hunk 3 above)
Comment (MaskedCarrot) [reply domain/src/test/java/org/oppia/android/domain/classify/rules/fractioninput/FractionInputHasDenominatorEqualToRuleClassifierProviderTest.kt]: done

File: domain/src/test/java/org/oppia/android/domain/classify/rules/fractioninput/FractionInputHasDenominatorEqualToRuleClassifierProviderTest.kt (hunk 2 above)
Comment (MaskedCarrot) [reply domain/src/test/java/org/oppia/android/domain/classify/rules/fractioninput/FractionInputHasDenominatorEqualToRuleClassifierProviderTest.kt]: done

File: domain/src/test/java/org/oppia/android/domain/classify/rules/fractioninput/FractionInputHasNumeratorEqualToRuleClassifierProviderTest.kt (hunk 1 above)
Comment (MaskedCarrot) [reply domain/src/test/java/org/oppia/android/domain/classify/rules/fractioninput/FractionInputHasNumeratorEqualToRuleClassifierProviderTest.kt]: done

**Comment by rt4914** [comment]
@anandwana001 Once you approve this, assign it to me for full pass. Thanks.

**Review by anandwana001 — APPROVED** [review]
LGTM, Thanks @MaskedCarrot

**Comment by MaskedCarrot** [comment]
I accidentally deleted this branch from my repo so reopening it.

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.
