### PR TITLE
Fix #4845: Dark mode support to Equations Text

### LINKED ISSUE #4845: Add dark mode support to Equations Text
**Describe the bug**

Equations Color in dark mode is still black need to change to white so that it visible in dark mode.

**To Reproduce**
1. Turn on your emulator dark-mode
2. Go to 'Fractions Card'
3. Click on 'Revision' in top menu
4. Click on 'What is Fraction Card'
5. See error

image

### PR DESCRIPTION
**Pull request by MohitGupta121**
## Explanation

Fix #4845 : Dark mode support to Equations Text

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

### Equation Text Screen Recording

https://user-images.githubusercontent.com/76530270/216761782-027744b7-a0df-41ca-8547-2e7f52eaea0c.mp4

#### Day Mode Test

image

#### Night Mode Test

image

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### CODE REVIEW

**Review by MohitGupta121 — COMMENTED** [review]
@rt4914 PTAL on the darkmode of equation-text if there is any changes.

@BenHenning I updated the Colors as we discuss in last meeting. Only now I left with [kotlitex](https://github.com/oppia/kotlitex) PR.

**Comment by MohitGupta121** [comment]
The workflow Tests are failing as the library is not updated as per my changes but I raised PR for that changes directly into [kotlitex](https://github.com/oppia/kotlitex) library. 
So please ignore the test failing for now.

**Comment by MohitGupta121** [comment]
@BenHenning I make PR for Kotlitex Library Please first review and merge that to avoid build and workflow tests failures https://github.com/oppia/kotlitex/pull/1

File: utility/src/main/java/org/oppia/android/util/parser/html/MathTagHandler.kt [hunk 1]
```diff
@@ -65,7 +69,15 @@ class MathTagHandler(
...
           MathExpressionSpan(
-            content.rawLatex, lineHeight, assetManager, isMathMode = !useInlineRendering
+            content.rawLatex,
+            lineHeight,
+            assetManager,
+            isMathMode = !useInlineRendering,
+            ResourcesCompat.getColor(
+              application.resources,
+              R.color.component_color_shared_equation_color,
+              null
```
Comment (BenHenning) [inline utility/src/main/java/org/oppia/android/util/parser/html/MathTagHandler.kt]: This should have an argument comment to explain what it's representing.

File: utility/src/main/java/org/oppia/android/util/parser/math/MathBitmapModelLoader.kt [hunk 2]
```diff
@@ -109,7 +111,15 @@ class MathBitmapModelLoader private constructor(
...
           MathExpressionSpan(
-            model.rawLatex, model.lineHeight, application.assets, !model.useInlineRendering
+            model.rawLatex,
+            model.lineHeight,
+            application.assets,
+            !model.useInlineRendering,
+            ResourcesCompat.getColor(
+              application.resources,
+              R.color.component_color_shared_equation_color,
+              null
```
Comment (BenHenning) [inline utility/src/main/java/org/oppia/android/util/parser/math/MathBitmapModelLoader.kt]: Ditto here.

File: utility/src/main/java/org/oppia/android/util/parser/html/HtmlParser.kt [hunk 3]
```diff
@@ -134,7 +135,8 @@ class HtmlParser private constructor(
         consoleLogger,
         context.assets,
         htmlContentTextView.lineHeight.toFloat(),
-        cacheLatexRendering
+        cacheLatexRendering,
+        context as? Application ?: context.applicationContext as Application
```
Comment (BenHenning) [inline utility/src/main/java/org/oppia/android/util/parser/html/HtmlParser.kt:139]: Can you expand on why this is needed? I'd expect context to be the application context in this case based on how we set up the Dagger graph, but perhaps I'm missing something.

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @MohitGupta121. https://github.com/oppia/kotlitex/pull/1 is now merged, so this PR can be updated to point to the new latest commit to the fork.

Beyond that, is there also a way to add tests to verify that the correct color is being passed to the span for day/night modes? I think we can set this in Robolectric tests via config.

File: utility/src/main/java/org/oppia/android/util/parser/html/MathTagHandler.kt (hunk 1 above)
Comment (MohitGupta121) [reply utility/src/main/java/org/oppia/android/util/parser/html/MathTagHandler.kt]: Actually the problem is here is that Kotlitex needs color code in Interger format but if we directly pass color R.color. then it not geting the exact color that we are passing. I attach the screenshots for that reference. It's getting Blue color.

File: utility/src/main/java/org/oppia/android/util/parser/math/MathBitmapModelLoader.kt (hunk 2 above)
Comment (MohitGupta121) [reply utility/src/main/java/org/oppia/android/util/parser/math/MathBitmapModelLoader.kt]: Explain in above comment.

File: utility/src/main/java/org/oppia/android/util/parser/html/HtmlParser.kt (hunk 3 above)
Comment (MohitGupta121) [reply utility/src/main/java/org/oppia/android/util/parser/html/HtmlParser.kt:139]: Explain in above comment, as we need context so there is way to pass the context.

File: utility/src/main/java/org/oppia/android/util/parser/html/MathTagHandler.kt (hunk 1 above)
Comment (BenHenning) [reply utility/src/main/java/org/oppia/android/util/parser/html/MathTagHandler.kt]: Ah to clarify my original comment, what I mean is that the ``null`` needs to have an argument comment, e.g. ``/* paramName= */ null`` to provide context to the reader.

File: utility/src/main/java/org/oppia/android/util/parser/html/HtmlParser.kt (hunk 3 above)
Comment (BenHenning) [reply utility/src/main/java/org/oppia/android/util/parser/html/HtmlParser.kt:139]: Sorry, I'm not sure if the other explanation actually answers my question. Why can't ``context`` be used instead of the extra casting work to ``Application`` that's happening here?

File: utility/src/main/java/org/oppia/android/util/parser/html/MathTagHandler.kt (hunk 1 above)
Comment (MohitGupta121) [reply utility/src/main/java/org/oppia/android/util/parser/html/MathTagHandler.kt]: Actually the `null` specify the `Theme` but we not have specific theme in utility package and this argument is required to pass that's why I passing here `null`

For reader  e.g. `/* paramName= */ null` Done in my latest commit. Thanks

File: utility/src/main/java/org/oppia/android/util/parser/html/HtmlParser.kt (hunk 3 above)
Comment (MohitGupta121) [reply utility/src/main/java/org/oppia/android/util/parser/html/HtmlParser.kt:139]: Actually here we need the `Application Context` to access the `application.resources` in `ResourcesCompat.getColor` That's why I using `Application` as with only `Context` these resources is not accessible.

**Comment by MohitGupta121** [comment]
> Beyond that, is there also a way to add tests to verify that the correct color is being passed to the span for day/night modes? I think we can set this in Robolectric tests via config.

About the tests we need to done that in this PR itself, I think tests will blocking this issue to clear. Just a suggestion.
What you think?

**Comment by BenHenning** [comment]
> > Beyond that, is there also a way to add tests to verify that the correct color is being passed to the span for day/night modes? I think we can set this in Robolectric tests via config.
> 
> About the tests we need to done that in this PR itself, I think tests will blocking this issue to clear. Just a suggestion. What you think?

Sorry I'm not sure that I'm following--what exactly is blocking adding tests?

**Comment by MohitGupta121** [comment]
> Sorry I'm not sure that I'm following--what exactly is blocking adding tests?

Okay sure, I'll add tests for that also. Only blocking is that I have not have clear idea about that tests but I try in this so that it helps me in future issues also.

**Comment by MohitGupta121** [comment]
@BenHenning I not understand why this https://github.com/oppia/oppia-android/actions/runs/4110540436/jobs/7093464931#step:13:1542 tests is failing as in my local `R` is getting from utility and it's working fine.

**Comment by BenHenning** [comment]
> @BenHenning I not understand why this https://github.com/oppia/oppia-android/actions/runs/4110540436/jobs/7093464931#step:13:1542 tests is failing as in my local `R` is getting from utility and it's working fine.

You added utility resources in the deps for MathBitmapModelLoader but not MathTagHandler which also needs access to the utility module's R class. However, I can't be certain this is the only issue since there are multiple failing runs (the one you linked to suggested MathBitmapModelLoader was the issue, but we discussed this during the meeting so it may not be up-to-date) and the latest failure is due to a visibility problem in the Bazel changes.

**Comment by MohitGupta121** [comment]
@BenHenning yes the latest failure is due to visibility issue, I add visibility conditions but it still showing errors. I ping you for that same in google chat.

**Comment by MohitGupta121** [comment]
@BenHenning still getting the same visibility issue after making it public also https://github.com/oppia/oppia-android/actions/runs/4129992792/jobs/7136213790#step:13:101

**Comment by MohitGupta121** [comment]
@BenHenning still getting the same visibility [error](https://github.com/oppia/oppia-android/actions/runs/4130050688/jobs/7136333450#step:13:133) after making it public also in this [file](https://github.com/oppia/oppia-android/blob/66087bd1e1360c8126c9bfc2ec10bfa573238f03/utility/src/main/java/org/oppia/android/util/parser/math/BUILD.bazel#L26)

**Review by MohitGupta121 — COMMENTED** [review]
@BenHenning PTAL, test is also added for equation color.
https://user-images.githubusercontent.com/76530270/222052888-18ccbfb5-1649-4007-8a71-c76ef2921326.png

**Comment by MohitGupta121** [comment]
@BenHenning Actually the one Bazel Test is failing (https://github.com/oppia/oppia-android/actions/runs/4300376404/jobs/7496592994#step:15:5275) saying unresolved color.

So what we need to change here? Or I directly use Hex value of night color in comparable?

**Comment by MohitGupta121** [comment]
@BenHenning I run `MathTagHandlerTest` test in Bazel in my local machine and getting the same error in Develop as well as in my this PR branch :

And in this PR CI check workflow getting this error https://github.com/oppia/oppia-android/pull/4866#issuecomment-1449436658

Screenshot 2023-03-01 at 6 16 29 PM

**Comment by BenHenning** [comment]
> @BenHenning Actually the one Bazel Test is failing (https://github.com/oppia/oppia-android/actions/runs/4300376404/jobs/7496592994#step:15:5275) saying unresolved color.
> 
> So what we need to change here? Or I directly use Hex value of night color in comparable?

@MohitGupta121 this is caused by a discrepancy that exists between Gradle & Bazel builds wherein we need to change references to resource files at compile-time in Bazel builds to match where Gradle expects them to be (otherwise the code wouldn't compile on both build platforms). This is set up per file that needs it, and we don't seem to have a BUILD.bazel yet for the package that MathTagHandlerTest is part of. Because of that, I think the easiest way to resolve this will probably just be to hardcode the color being checked in tests. If the resource file is ever updated, the test should fail and require updating, which is totally fine here.

**Comment by MohitGupta121** [comment]
Okay thanks @BenHenning , means I can hardcode the hex color in Test comparison. 
If we do this then we don't need  @Config(qualifiers = "night") in that test?

**Comment by MohitGupta121** [comment]
@BenHenning PTAL, Updated the Latex Test separately for Day and Night mode.
Thanks.

#### Day Mode 

https://user-images.githubusercontent.com/76530270/222653431-05f7e726-c8f0-4677-a48e-8ca37c5ea8e4.png

#### Night Mode 

https://user-images.githubusercontent.com/76530270/222653513-458e25ce-9508-480e-bdfc-a4ede5e8a0ed.png

File: utility/src/main/java/org/oppia/android/util/parser/math/BUILD.bazel [hunk 4]
```diff
@@ -23,11 +23,12 @@ kt_android_library(
     srcs = [
         "MathBitmapModelLoader.kt",
     ],
-    visibility = ["//utility/src/main/java/org/oppia/android/util/parser/image:__pkg__"],
+    visibility = ["//visibility:public"],
```
Comment (BenHenning) [inline utility/src/main/java/org/oppia/android/util/parser/math/BUILD.bazel]: Why does this visibility need to change?

File: utility/src/main/java/org/oppia/android/util/parser/html/MathTagHandler.kt [hunk 5]
```diff
@@ -65,7 +69,15 @@ class MathTagHandler(
...
           MathExpressionSpan(
-            content.rawLatex, lineHeight, assetManager, isMathMode = !useInlineRendering
+            content.rawLatex,
+            lineHeight,
+            assetManager,
+            isMathMode = !useInlineRendering,
+            ResourcesCompat.getColor(
+              application.resources,
+              R.color.component_color_shared_equation_color,
+              /* paramName= theme */ null
```
Comment (BenHenning) [inline utility/src/main/java/org/oppia/android/util/parser/html/MathTagHandler.kt]: The formatting of this argument name seems off--please fix.

File: utility/src/main/java/org/oppia/android/util/parser/math/MathBitmapModelLoader.kt [hunk 6]
```diff
@@ -109,7 +111,15 @@ class MathBitmapModelLoader private constructor(
...
           MathExpressionSpan(
-            model.rawLatex, model.lineHeight, application.assets, !model.useInlineRendering
+            model.rawLatex,
+            model.lineHeight,
+            application.assets,
+            !model.useInlineRendering,
+            ResourcesCompat.getColor(
+              application.resources,
+              R.color.component_color_shared_equation_color,
+              /* paramName= theme */null
```
Comment (BenHenning) [inline utility/src/main/java/org/oppia/android/util/parser/math/MathBitmapModelLoader.kt]: Ditto here.

File: utility/src/test/java/org/oppia/android/util/parser/html/MathTagHandlerTest.kt [hunk 7]
```diff
@@ -80,13 +82,23 @@ class MathTagHandlerTest {
   @JvmField
   val mockitoRule: MockitoRule = MockitoJUnit.rule()
 
-  @Mock lateinit var mockImageRetriever: FakeImageRetriever
-  @Captor lateinit var stringCaptor: ArgumentCaptor<String>
-  @Captor lateinit var retrieverTypeCaptor: ArgumentCaptor<ImageRetriever.Type>
-  @Captor lateinit var floatCaptor: ArgumentCaptor<Float>
+  @Mock
+  lateinit var mockImageRetriever: FakeImageRetriever
```
Comment (BenHenning) [inline utility/src/test/java/org/oppia/android/util/parser/html/MathTagHandlerTest.kt]: Nit: please revert this & the other captor/inject lines to use the compact styling (Android Studio reverts this sometimes unfortunately).

File: utility/src/test/java/org/oppia/android/util/parser/html/MathTagHandlerTest.kt [hunk 8]
```diff
@@ -246,6 +258,33 @@ class MathTagHandlerTest {
...
+  fun testParseHtmlDayColor_withMathMarkup_cachingOff_getEquationDayColor() {
+    val parsedHtml =
+      CustomHtmlContentHandler.fromHtml(
+        html = MATH_WITHOUT_FILENAME_MARKUP,
+        imageRetriever = mockImageRetriever,
+        customTagHandlers = tagHandlersWithUncachedMathSupport
+      )
+
+    val equationColor = parsedHtml.getSpansFromWholeString(MathExpressionSpan::class)
+    assertThat(/* Color from Equation Text */ equationColor[0].equationColor).isEqualTo(Color.BLACK)
```
Comment (BenHenning) [inline utility/src/test/java/org/oppia/android/util/parser/html/MathTagHandlerTest.kt]: Is this comment needed for this & the next test? The code seems pretty self-explanatory as-is.

Otherwise, you could always move the value to a variable that has a clearer name, instead.

File: utility/src/main/java/org/oppia/android/util/parser/math/MathBitmapModelLoader.kt [hunk 9]
```diff
@@ -109,7 +111,15 @@ class MathBitmapModelLoader private constructor(
         // creation can still happen in parallel, and those are the more expensive steps.
         val span = withContext(CoroutineScope(blockingDispatcher).coroutineContext) {
           MathExpressionSpan(
-            model.rawLatex, model.lineHeight, application.assets, !model.useInlineRendering
+            model.rawLatex,
+            model.lineHeight,
+            application.assets,
+            !model.useInlineRendering,
+            ResourcesCompat.getColor(
```
Comment (BenHenning) [inline utility/src/main/java/org/oppia/android/util/parser/math/MathBitmapModelLoader.kt:119]: Is this change also being tested? It seems like only MathTagHandler's change is verified in tests.

**Review by BenHenning — COMMENTED** [review]
Thanks @MohitGupta121! Took another pass--PTAL.

File: utility/src/main/java/org/oppia/android/util/parser/html/MathTagHandler.kt (hunk 5 above)
Comment (MohitGupta121) [reply utility/src/main/java/org/oppia/android/util/parser/html/MathTagHandler.kt]: `/* theme = */` is this fine?  what you suggest this is actually Theme

File: utility/src/main/java/org/oppia/android/util/parser/math/MathBitmapModelLoader.kt (hunk 9 above)
Comment (MohitGupta121) [reply utility/src/main/java/org/oppia/android/util/parser/math/MathBitmapModelLoader.kt:119]: We already testing the MathExpressionSpan color parameter in MathTagHandlerTest, So this also Tested.
I not understand exact what you are approaching?

File: utility/src/main/java/org/oppia/android/util/parser/math/BUILD.bazel (hunk 4 above)
Comment (MohitGupta121) [reply utility/src/main/java/org/oppia/android/util/parser/math/BUILD.bazel]: This is needed to access the resources in the utility, If we did not do the visibility public then Bazel is unable to access the Resources(Color) and throws a Bazel build error. As we discuss earlier.

File: utility/src/test/java/org/oppia/android/util/parser/html/MathTagHandlerTest.kt (hunk 8 above)
Comment (MohitGupta121) [reply utility/src/test/java/org/oppia/android/util/parser/html/MathTagHandlerTest.kt]: Done.

File: utility/src/test/java/org/oppia/android/util/parser/html/MathTagHandlerTest.kt (hunk 7 above)
Comment (MohitGupta121) [reply utility/src/test/java/org/oppia/android/util/parser/html/MathTagHandlerTest.kt]: Done.

**Review by rt4914 — APPROVED** [review]
For codeowner files.

File: utility/src/main/java/org/oppia/android/util/parser/math/BUILD.bazel (hunk 4 above)
Comment (MohitGupta121) [reply utility/src/main/java/org/oppia/android/util/parser/math/BUILD.bazel]: Done.

File: utility/src/main/java/org/oppia/android/util/parser/html/MathTagHandler.kt (hunk 5 above)
Comment (MohitGupta121) [reply utility/src/main/java/org/oppia/android/util/parser/html/MathTagHandler.kt]: Done.

File: utility/src/main/java/org/oppia/android/util/parser/math/MathBitmapModelLoader.kt (hunk 6 above)
Comment (MohitGupta121) [reply utility/src/main/java/org/oppia/android/util/parser/math/MathBitmapModelLoader.kt]: Done.

File: utility/src/main/java/org/oppia/android/util/parser/math/MathBitmapModelLoader.kt (hunk 9 above)
Comment (MohitGupta121) [reply utility/src/main/java/org/oppia/android/util/parser/math/MathBitmapModelLoader.kt:119]: Done.

**Review by MohitGupta121 — COMMENTED** [review]
@BenHenning PTAL, I make all changes as per review.

**Review by BenHenning — APPROVED** [review]
Thanks @MohitGupta121. This LGTM!

**Comment by BenHenning** [comment]
Updating from develop & enabling auto-merge.

**Comment by BenHenning** [comment]
Also @MohitGupta121 please note the edits I made to your PR title & description for the correct verb tenses to use when referring to the issues being fixed. Part of this is to make sure GitHub closes the issues being fixed correctly, and the other is for consistency with other PRs (which is ultimately based on a Git best practice when referring to issues being fixed).

**Comment by MohitGupta121** [comment]
@BenHenning Yes Thanks, noted the changes that you made. Yes the issue is also closed now.
