### PR TITLE
Fix #1792: Show same keyboard on toggling show/hide while entering pin

### LINKED ISSUE #1792: Toggling show/hide changes soft keyboard
**Describe the bug**
When we are on the screen where we have to input admin pin, we have a show and hide button, toggling which changes the soft keyboard 

**To Reproduce**
Steps to reproduce the behaviour:
1. Install app -> click on the admin profile
2. click on the show -> hide -> soft keyboard changes 

**Expected behaviour**
The soft keyboard should not change

**Video**
https://lh3.googleusercontent.com/2ACs5tLuu3JmS1V248M2flkFCL35GeI4ZaHaj2yXu-AIaXExQFbWXVDkkyeS8vCXBKIyU5RRxhQeJ08=m37

**Device**
- Redmi Note 5 Pro

### PR DESCRIPTION
**Pull request by yk1ax**
## Explanation

Fixes #1792 
As mentioned in the issue's thread it required an update to the version 1.4.4 and minor changes in the corresponding xml file. So I did that and checked that it is infact working properly.
## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.
## GIF of change
| Before  | After |
| :-: | :-: |
|  |  |

### CODE REVIEW

**Comment by anandwana001** [comment]
@yk1ax 
1. Please check the second point in the PR description. 
2. We also need to update the version in the BUILD file in the app module which is a Bazel file. 
3. We also need to write a test case which checks the soft keyboard is same while the password is hidden or not, that's the issue we are fixing here.

**Comment by yk1ax** [comment]
@anandwana001 I've updated the version in BUILD file. But I am not much familiar with writing tests so can you provide some guidance specifically on that ? Like there are so many files in testing section. So firstly I'm confused on where to write the test.

**Comment by anandwana001** [comment]
> @anandwana001 I've updated the version in BUILD file. But I am not much familiar with writing tests so can you provide some guidance specifically on that ? Like there are so many files in testing section. So firstly I'm confused on where to write the test.

1. The build file you had update is a Gradle file, you need to update the version in BUILD.bazel file. 
https://github.com/oppia/oppia-android/blob/71935a00580a1e5975c3a9263be32a2915544f21/app/BUILD.bazel#L500

2. For testing, please start with our wiki guide - https://github.com/oppia/oppia-android/wiki/Oppia-Android-Testing
As we are fixing things for `PinPasswordActivity`, I suggest checking `PinPasswordActivity`, `PinPasswordActivityPresenter` first to check how the flow works. Then for writing test cases go to `PinPasswordActivityTest` where all the test are written related to the `PinPasswordActivity` flow. 
For this PR, You need to write an espresso test where you have check the value of `setPasswordHidden` is true or false according to your action. Also, We need to do some searching here on how we can test the type of visible soft keyboard so we can identify that the soft keyboard is same on both the action. 
The test cases should pass with your fix and fail without your fix on espresso and robolectric.

**Comment by anandwana001** [comment]
@yk1ax Any update on this?

**Comment by yk1ax** [comment]
> @yk1ax Any update on this?

My exams were going on. They have ended now so I'll continue working on this today.

**Comment by yk1ax** [comment]
@anandwana001 I'm having problems even in running the PinPasswordActivityTest.kt file. It's freezing at this screen and then failing the tests. I also tried a uninstalling and then running the tests with a fresh install.

And in the logcat the last statement is ```I/ViewInteraction: Performing 'appendText(12345)' action on view (with id: org.oppia.android:id/input and is descendant of a: with id: org.oppia.android:id/input_pin)```

**Comment by anandwana001** [comment]
@yk1ax Could you please add the screenshot of the test result and which test is freezing here?

**Comment by yk1ax** [comment]
> @yk1ax Could you please add the screenshot of the test result and which test is freezing here?

@anandwana001 It just freezes on the test 'testPinPasswordActivityWithUser_clickForgot_inputAdminPin_clickSubmit_inputNewPin_changeConfiguration_clickSubmit_pinChangeIsSuccessful'. The device pops up the message that it is unresponsive after a long time and then if I end the app the test shows failed and if I don't end it, it just stays frozen.

Screenshot (8)

**Comment by anandwana001** [comment]
@yk1ax This seems a bit weird as all the tests are working correctly [before](https://github.com/oppia/oppia-android/pull/1854). 

As for now, It looks like the issue in Espresso is, the EditText is not getting focuses to type the text in it, also the`EditTextInputAction` doesn't seems to work for the test case. 

We are looking forward migrating to the `TextInputLayout`which removes the part where we want to check the focus and appending of data. Let's skip this freezing thing for now and see if you can write you test cases as your test cases not involve setting any text to the input.

**Comment by yk1ax** [comment]
> @yk1ax This seems a bit weird as all the tests are working correctly [before](https://github.com/oppia/oppia-android/pull/1854). 
> 
> As for now, It looks like the issue in Espresso is, the EditText is not getting focuses to type the text in it, also the`EditTextInputAction` doesn't seems to work for the test case. 
> 
> We are looking forward migrating to the `TextInputLayout`which removes the part where we want to check the focus and appending of data. Let's skip this freezing thing for now and see if you can write you test cases as your test cases not involve setting any text to the input. 
> 

Okay sure, now I'll simply write the test solely for the modified functionality. Because of this problem I've become a bit more familiar with testing. But I just wasn't writing the test because I thought maybe there has been some problem while setting up the project in my system. Now I'll get done with it 👍

**Comment by yk1ax** [comment]
@anandwana001 I am trying something like this.
```
@Test
  fun testPinPassworkActivityWithAdmin_checkKeyboardTypeConsistency_clickShowHidePassword_keyboardTypeIsSame() {
    ActivityScenario.launch<PinPasswordActivity>(
      PinPasswordActivity.createPinPasswordActivityIntent(
        context,
        adminPin,
        adminId
      )
    ).use {
      testCoroutineDispatchers.runCurrent()
      val imm = context.getSystemService(
        Context.INPUT_METHOD_SERVICE
      ) as InputMethodManager

//      val firstInputType = /* get the input type */
      onView(withId(R.id.show_pin)).perform(click())
//      val lastInputType = /* get the input type*/

//      Check if both the input types are the same
    }
  }
```

**Comment by anandwana001** [comment]
@yk1ax Looks in the right direction. Getting the input type of view in both the cases and comparing if both input types are the same or not.

**Comment by yk1ax** [comment]
@anandwana001 I have implemented the test in a different way than what I previously proposed.

```
      onView(withId(R.id.input_pin)).check(
        matches(
          withInputType(
            InputType.TYPE_CLASS_NUMBER
          )
        )
      )
      onView(withId(R.id.show_pin)).perform(click())
      onView(withId(R.id.input_pin)).check(
        matches(
          withInputType(
            InputType.TYPE_CLASS_NUMBER
          )
        )
      )
```

Here I am checking if the inputType of the pinView in both the cases equals to the definite value of InputType.TYPE_CLASS_NUMBER instead of directly checking both of them for equality. Is this also fine ? Actually I did this because I wasn't able to find any method to extract the input type of the view under espresso which I needed for storing into the two variables. Kindly tell me whether I should try something else or make a commit.

**Comment by anandwana001** [comment]
Is this test is passing on both espresso and robolectric?

**Comment by yk1ax** [comment]
> Is this test is passing on both espresso and robolectric?

I just ran this single test. It failed on 'develop' branch and it ran successfully on this PR's branch.

Can you tell me from where should I run espresso and robolectric ? I am a beginner with testing in android. I just used the run button that appears next to the function name.

**Comment by anandwana001** [comment]
Check our wiki guide for running robolectric test - https://github.com/oppia/oppia-android/wiki/Oppia-Android-Testing#running-robolectric-tests

Also, push the tests to PR for review.

**Comment by yk1ax** [comment]
In the latest commit I failed the klint test because of the max line limit. Will it be resolved simply by putting ``` // klint-disable max-line-length ``` at the end of that line ? 

And there is a big issue with the bazel test. Following error is occurring ``` ERROR: Cannot find a setter for <com.chaos.view.PinView android:setPasswordHidden> that accepts parameter type 'boolean' ``` but using this parameter seems to be the suggested way of using the show/hide password functionality as mentioned [here](https://github.com/ChaosLeung/PinView/issues/55)

**Comment by yk1ax** [comment]
> Check our wiki guide for running robolectric test - https://github.com/oppia/oppia-android/wiki/Oppia-Android-Testing#running-robolectric-tests
> 
> Also, push the tests to PR for review.

I was trying to run robolectric tests as mentioned in that section but I was getting the following error
Annotation 2020-12-17 084209

I checked there was a field named "Shorten command line" in the edit configurations window and it was set to default as shown in the running robolectric tests section

**Comment by anandwana001** [comment]
> In the latest commit I failed the klint test because of the max line limit. Will it be resolved simply by putting `// klint-disable max-line-length` at the end of that line ?
> 
> And there is a big issue with the bazel test. Following error is occurring `ERROR: Cannot find a setter for <com.chaos.view.PinView android:setPasswordHidden> that accepts parameter type 'boolean'` but using this parameter seems to be the suggested way of using the show/hide password functionality as mentioned [here](https://github.com/ChaosLeung/PinView/issues/55)

Try to prevent the use of ktlint disable if we can break the lines. Reformat code/Rearrange code might helps.

**Comment by yk1ax** [comment]
> > In the latest commit I failed the klint test because of the max line limit. Will it be resolved simply by putting `// klint-disable max-line-length` at the end of that line ?
> > 
> > And there is a big issue with the bazel test. Following error is occurring `ERROR: Cannot find a setter for <com.chaos.view.PinView android:setPasswordHidden> that accepts parameter type 'boolean'` but using this parameter seems to be the suggested way of using the show/hide password functionality as mentioned [here](https://github.com/ChaosLeung/PinView/issues/55)
> 
> Try to prevent the use of ktlint disable if we can break the lines. Reformat code/Rearrange code might helps.

Actually the line exceeding the limit is the one with test name.

The bigger issue is that using the setPasswordHidden parameter is giving error.

@anandwana001 I was using setPasswordHidden attribute in xml to do the show/hide toggle with the help of databinding as there was a variable showPassword in viewModel and this is causing some error in databinding. So should not use the setPasswordHidden programmatically through a click listener ?

**Comment by yk1ax** [comment]
@anandwana001 I got help from the gitter channel and I was able to run the Robolectric test. The test I wrote is passing on my branch and failing on develop branch so it seems to be doing its work. But I am failing one test - "testPinPasswordActivityWithUser_clickForgot_inputAdminPin_clickSubmit_inputNewPin_changeConfiguration_clickSubmit_pinChangeIsSuccessful()". Unfortunately his test is also failing on the develop branch.

I was trying to understand what the error might be, I saw multiple lines citing Firebase originating at this error ``` at org.oppia.android.app.profile.PinPasswordActivityTest.setUp(PinPasswordActivityTest.kt:121) ``` and that line was ``` FirebaseApp.initializeApp(context) ```

**Comment by yk1ax** [comment]
I'm also setting up bazel so that I can run the bazel test offline as the 'setPasswordHidden' attribute is causing problem during databinding and that still needs to be resolved.

**Comment by ShridharGoel** [comment]
@yk1ax 

As mentioned by @anandwana001, you need to update the version in `BUILD.bazel` file in the app module as well.

Also, since the ktlint issue is because of the long test name, you can add the comment there to disable it.

**Comment by ShridharGoel** [comment]
> @anandwana001 I got help from the gitter channel and I was able to run the Robolectric test. The test I wrote is passing on my branch and failing on develop branch so it seems to be doing its work. But I am failing one test - "testPinPasswordActivityWithUser_clickForgot_inputAdminPin_clickSubmit_inputNewPin_changeConfiguration_clickSubmit_pinChangeIsSuccessful()". Unfortunately his test is also failing on the develop branch.
> 
> I was trying to understand what the error might be, I saw multiple lines citing Firebase originating at this error `at org.oppia.android.app.profile.PinPasswordActivityTest.setUp(PinPasswordActivityTest.kt:121)` and that line was `FirebaseApp.initializeApp(context)`

Since it is failing on `develop` branch as well, we can open another issue for this.

**Comment by anandwana001** [comment]
> I s

We are solving this issue separately here - https://github.com/oppia/oppia-android/pull/2220#issuecomment-744492054

**Comment by yk1ax** [comment]
@anandwana001 Now it's failing only the bazel test, showing the same error as the last time.

```
fastbuild/bin/app/_javac/databinding_resources/libdatabinding_resources_sourcegenfiles/org/oppia/android/app/databinding/DataBinderMapperImpl.java:189: error: cannot find symbol
import org.oppia.android.app.databinding.databinding.PinPasswordActivityBindingImpl;
                                                    ^
  symbol:   class PinPasswordActivityBindingImpl
  location: package org.oppia.android.app.databinding.databinding
java.lang.RuntimeException: android.databinding.tool.util.LoggedErrorException: Found data binding error(s):

ERROR: Cannot find a setter for <com.chaos.view.PinView android:setPasswordHidden> that accepts parameter type 'boolean'

If a binding adapter provides the setter, check that the adapter is annotated correctly and that the parameter type matches.
```

I have a way to resolve this. I was going through the [README](https://github.com/ChaosLeung/PinView/blob/master/README.md) of pinView and I observed that 'setPasswordHidden' is not mentioned under XML as an attribute (although the functionality was working by this method on my physical device) but it is mentioned under JAVA section. So what I can do instead is that I can write a binding adapter for pinView and from there I can hide the password by calling the setPasswordHidden method. Should I do that ?

**Comment by anandwana001** [comment]
> @anandwana001 Now it's failing only the bazel test, showing the same error as the last time.
> 
> ```
> fastbuild/bin/app/_javac/databinding_resources/libdatabinding_resources_sourcegenfiles/org/oppia/android/app/databinding/DataBinderMapperImpl.java:189: error: cannot find symbol
> import org.oppia.android.app.databinding.databinding.PinPasswordActivityBindingImpl;
>                                                     ^
>   symbol:   class PinPasswordActivityBindingImpl
>   location: package org.oppia.android.app.databinding.databinding
> java.lang.RuntimeException: android.databinding.tool.util.LoggedErrorException: Found data binding error(s):
> 
> ERROR: Cannot find a setter for <com.chaos.view.PinView android:setPasswordHidden> that accepts parameter type 'boolean'
> 
> If a binding adapter provides the setter, check that the adapter is annotated correctly and that the parameter type matches.
> ```
> 
> I have a way to resolve this. I was going through the [README](https://github.com/ChaosLeung/PinView/blob/master/README.md) of pinView and I observed that 'setPasswordHidden' is not mentioned under XML as an attribute (although the functionality was working by this method on my physical device) but it is mentioned under JAVA section. So what I can do instead is that I can write a binding adapter for pinView and from there I can hide the password by calling the setPasswordHidden method. Should I do that ?

@yk1ax Sounds correct to me. Let's commit the new changes and will review.

File: app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt [hunk 1]
```diff
@@ -681,6 +683,35 @@ class PinPasswordActivityTest {
     }
   }
 
+  @Test
+  fun testPinPasswordActivityWithAdmin_checkKeyboardTypeConsistency_clickShowHidePassword_keyboardTypeIsSame() { // ktlint-disable max-line-length
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt]: prevent using `// ktlint-disable max-line-length` with a short the function name.

**Review by anandwana001 — CHANGES_REQUESTED** [review]
nit change @yk1ax

File: app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt (hunk 1 above)
Comment (yk1ax) [reply app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt]: Can I use this name instead "testPinPasswordActivity_checkKeyboardType_clickShowHidePassword_keyboardTypeIsSame()"
I removed that with admin because I just realised that this keyboard change is for the other users as well and I also removed the word 'Consistency'

Comment (yk1ax) [reply app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt]: Meanwhile I also found that there is a file called WORKSPACE related to bazel. So I updated the PinView version in that file as well from '1.4.3' to '1.4.4'.

**Comment by yk1ax** [comment]
@anandwana001 it is again failing bazel build test. This time with the following error. 

```
bazel-out/android-armeabi-v7a-fastbuild/bin/app/src/main/java/org/oppia/android/app/databinding/PinViewBindingAdapters_updated.java:4: error: package com.chaos.view does not exist
import com.chaos.view.PinView;
                     ^
bazel-out/android-armeabi-v7a-fastbuild/bin/app/src/main/java/org/oppia/android/app/databinding/PinViewBindingAdapters_updated.java:12: error: cannot find symbol
  public static void setPasswordVisibility(@NotNull PinView pinView, boolean isPasswordShown) {
                                                    ^
  symbol:   class PinView
  location: class PinViewBindingAdapters_updated
```

Also what is the command to run bazel build test on my local system. There doesn't seem to be any info on that in the wiki page.

**Comment by yk1ax** [comment]
@anandwana001 While going through the BUILD.bazel file I found this part

```
# Library for all custom data-binding adapters under org/oppia/android/app/databinding.
android_library(
    name = "binding_adapters",
    srcs = BINDING_ADAPTERS,
    custom_package = "org.oppia.android.app.databinding.adapters",
    enable_data_binding = True,
    manifest = "src/main/DatabindingAdaptersManifest.xml",
    visibility = ["//visibility:private"],
    deps = [
        ":dagger",
        ":resources",
        ":view_models",
        "//model",
        "//utility",
        "@circularimageview//circularimageview:circular_image_view",
        artifact("androidx.annotation:annotation"),
        artifact("androidx.constraintlayout:constraintlayout:1.1.3"),
        artifact("androidx.lifecycle:lifecycle-livedata-core:jar:2.0.0-alpha1"),
        artifact("androidx.lifecycle:lifecycle-livedata-ktx"),
    ],
)
```

Do I have to add ``` artifact("com.chaos.view.PinView"), ``` in the above code ?

**UPD :** Doing this also didn't work. It again failed the bazel build test (and another test failed this time when I added the line), it seems like some configuration needs to be done somewhere while adding another artifact. Kindly guide me with what to do next.

File: app/BUILD.bazel [hunk 2]
```diff
@@ -591,6 +592,7 @@ android_library(
         artifact("androidx.constraintlayout:constraintlayout:1.1.3"),
         artifact("androidx.lifecycle:lifecycle-livedata-core:jar:2.0.0-alpha1"),
         artifact("androidx.lifecycle:lifecycle-livedata-ktx"),
+        artifact("com.chaos.view.PinView"),
```
Comment (BenHenning) [inline app/BUILD.bazel]: This should match the other artifact: ``com.chaos.view:pinview:1.4.4``.

Comment (yk1ax) [reply app/BUILD.bazel]: Made the change. I hope the tests run correctly this time.

**Comment by yk1ax** [comment]
@BenHenning my last commit has passed all checks. You can review it for any further changes.

**Comment by BenHenning** [comment]
@yk1ax can you include in the main PR comment a Gif of the current behavior, too? That will better help visualize the before-and-after behavior.

**Comment by yk1ax** [comment]
> @yk1ax can you include in the main PR comment a Gif of the current behavior, too? That will better help visualize the before-and-after behavior.

@BenHenning Done.

File: app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt [hunk 3]
```diff
@@ -681,6 +683,35 @@ class PinPasswordActivityTest {
     }
   }
 
+  @Test
+  fun testPinPasswordActivity_checkKeyboardType_clickShowHidePassword_keyboardTypeIsSame() {
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt]: Can you confirm that this fails without your fix in place?

**Review by BenHenning — APPROVED** [review]
Thanks @yk1ax! I think the solution overall looks quite good. I just had one comment, but going ahead and approving this. Deferring to @anandwana001 to confirm the last remaining comment.

**Comment by yk1ax** [comment]
I just made a slight change in the last commit. Previously I was matching the input type before and after clicking the password show/hide toggle by comparing the inputType both times with the absolute value of InputType.TYPE_CLASS_NUMBER whereas now I've declared a constant with value InputType.TYPE_CLASS_NUMBER which is being used for comparison

**Comment by anandwana001** [comment]
@yk1ax Continuing Ben's comment, could you also add a screenshot showing test case is passing on both espresso and robolectric.

**Comment by yk1ax** [comment]
> @yk1ax Continuing Ben's comment, could you also add a screenshot showing test case is passing on both espresso and robolectric.

@anandwana001 
**For Robolectric :**
Screenshot from 2020-12-23 17-30-40

**For Espresso:**
Tests are freezing so I can't run espresso test on PinPasswordActivityTest.kt as also mentioned over [here](https://github.com/oppia/oppia-android/issues/2299). I can upload the screenshot for that after #2300 gets merged.
**UPD:**
Since the PR #2300 got merged I made a copy of the branch linked with this PR and merged the develop branch onto that and now the Espresso test ran to completion.
Screenshot from 2020-12-25 15-05-02

**Comment by yk1ax** [comment]
@anandwana001 it had some merge conflict. I resolved it, so you can have a look at it.

File: app/src/main/res/layout/pin_password_activity.xml [hunk 4]
```diff
@@ -68,7 +68,8 @@
       android:layout_marginTop="8dp"
       android:cursorVisible="true"
       android:fontFamily="sans-serif"
-      android:inputType="@{viewModel.showPassword ? InputType.TYPE_CLASS_NUMBER : (InputType.TYPE_CLASS_NUMBER | InputType.TYPE_NUMBER_VARIATION_PASSWORD)}"
+      android:inputType="number"
```
Comment (anandwana001) [inline app/src/main/res/layout/pin_password_activity.xml]: update other versions of this file
src/main/res/layout-sw600dp-land/pin_password_activity.xml
src/main/res/layout-sw600dp-port/pin_password_activity.xml
src/main/res/layout-land/pin_password_activity.xml

File: app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt [hunk 5]
```diff
@@ -689,6 +691,36 @@ class PinPasswordActivityTest {
...
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt]: rename to `testPinPasswordActivity_checkInputType_clickShowHidePassword_inputTypeIsSame` as in the core we are matching the input type

File: app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt [hunk 6]
```diff
@@ -689,6 +691,36 @@ class PinPasswordActivityTest {
...
+    ActivityScenario.launch<PinPasswordActivity>(
+      PinPasswordActivity.createPinPasswordActivityIntent(
+        context,
+        adminPin,
+        adminId
+      )
+    ).use {
+      testCoroutineDispatchers.runCurrent()
+
+      val inputType = InputType.TYPE_CLASS_NUMBER
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt]: let's not check the type here explicitly. We can try accessing the input type directly from Ui

```kotlin
  @Test
  fun testPinPasswordActivity_checkInputType_clickShowHidePassword_inputTypeIsSame() {
    ActivityScenario.launch<PinPasswordActivity>(
      PinPasswordActivity.createPinPasswordActivityIntent(
        context,
        adminPin,
        adminId
      )
    ).use {
      testCoroutineDispatchers.runCurrent()

      var inputType: Int = 0
      it.onActivity {
        inputType = it.findViewById<PinView>(R.id.input_pin).inputType
      }
      onView(withId(R.id.input_pin))
        .check(matches(withInputType(inputType)))
      onView(withId(R.id.show_pin)).perform(click())
      onView(withId(R.id.input_pin))
        .check(matches(withInputType(inputType)))
    }
  }
```

File: app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt [hunk 7]
```diff
@@ -689,6 +691,36 @@ class PinPasswordActivityTest {
...
+      onView(withId(R.id.input_pin)).check(
+        matches(
+          withInputType(
+            inputType
+          )
+        )
+      )
+    }
+  }
+
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt]: Also, could you please remove `waitUntilActivityVisible`. It will be helpful as the function has no use.

File: app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt (hunk 6 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt]: let me know if this test case is passing on robolectric too, then we can go with this.

**Review by anandwana001 — CHANGES_REQUESTED** [review]
Thanks, @yk1ax 

Could you run this PR on Pixel or try in few other devices if the keyboard is the same and what we need. I tried on pixel Xl, the keyboard is the same for both passwords hidden and visible but in both cases, the keyboard has extra buttons. 

WDYT? @rt4914 Is it good to go with a few extra buttons in the soft keyboard, as I think this is something default. Removing them is a bit complicated stuff. Although, this PR solves the issue where we need consistency in the keyboard in both hidden and visible passwords. 

Screenshot_1609391626

**Comment by yk1ax** [comment]
@anandwana001 thanks for noticing. I made a mistake and used number instead of numberPassword as inputType. I hope it's as expected now.

**Comment by anandwana001** [comment]
I don't think it will work the same way with the pixel device. Let's wait for the Rajat's comment and see if we can go with the way mentioned in my previous comment.

**Comment by yk1ax** [comment]
> I don't think it will work the same way with the pixel device. Let's wait for the Rajat's comment and see if we can go with the way mentioned in my previous comment.

Okay meanwhile I'll make the other changes needed.

File: app/src/main/res/layout/pin_password_activity.xml (hunk 4 above)
Comment (yk1ax) [reply app/src/main/res/layout/pin_password_activity.xml]: Done

File: app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt (hunk 5 above)
Comment (yk1ax) [reply app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt]: Done

File: app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt (hunk 7 above)
Comment (yk1ax) [reply app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt]: Done

File: app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt (hunk 6 above)
Comment (yk1ax) [reply app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt]: Doing it this way makes more sense. Actually I'm not that familiar with ActivityScenario so I wasn't able to find a way to extract the inputType at runtime from ActivityScenario.

Comment (yk1ax) [reply app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt]: This test passes on robolectric

File: app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt (hunk 3 above)
Comment (yk1ax) [reply app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt]: Yes

**Comment by anandwana001** [comment]
@yk1ax For future reference, the reviewer needs to resolve the conversation as it confirms the suggested changes are done as needed. Good to go for this PR.

File: app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt (hunk 3 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt]: Resolving on behalf of Ben

File: app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt [hunk 8]
```diff
@@ -710,18 +735,6 @@ class PinPasswordActivityTest {
     return visibleActivityName == T::class.java.name
   }
 
-  private inline fun <reified T : Activity> waitUntilActivityVisible() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt:713]: Looks like there are few unused methods which were previously used by this method. Need to remove.

**Review by anandwana001 — CHANGES_REQUESTED** [review]
Nit change

**Comment by yk1ax** [comment]
> @yk1ax For future reference, the reviewer needs to resolve the conversation as it confirms the suggested changes are done as needed. Good to go for this PR.

@anandwana001 thanks I will make sure from the next time.

File: app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt (hunk 8 above)
Comment (yk1ax) [reply app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt:713]: I found 2 such methods 'isVisible' and 'getCurrentActivity' and removed them which resulted in many unused imports so I removed those as well. I just had a confusion, two unused imports are also left
```
private const val TIMEOUT = 1000L
private const val CONDITION_CHECK_INTERVAL = 100L
```
Should I remove these two as well ?

Comment (yk1ax) [reply app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt:713]: @anandwana001 I found 2 such methods 'isVisible' and 'getCurrentActivity' and removed them which resulted in many unused imports so I removed those as well. I just had a confusion, two unused constants are also left
```
private const val TIMEOUT = 1000L
private const val CONDITION_CHECK_INTERVAL = 100L
```
Should I remove these two as well ?

Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt:713]: yes, as these are of no use we can remove this.

Comment (yk1ax) [reply app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt:713]: Okay

Comment (yk1ax) [reply app/src/sharedTest/java/org/oppia/android/app/profile/PinPasswordActivityTest.kt:713]: Done

**Review by rt4914 — APPROVED** [review]
LGTM. Nice work @yk1ax

**Comment by yk1ax** [comment]
> LGTM. Nice work @yk1ax

Thanks @rt4914

**Review by anandwana001 — APPROVED** [review]
LGTM, Thanks @yk1ax
