### PR TITLE
Fix #4859: Images in List Items Are Rendered as Block Elements

### LINKED ISSUE #4859: Images in 'li' tags display in inline rather than block mode.
**Describe the bug**

Images in 'li' tags display in inline mode, which is incorrect, and results in such images being cut off. 

Instead, such images should be displayed in block mode and centered.

**To Reproduce**

In the production version of the app, go to Multiplication > Revision card > Techniques of multiplication. Then scroll down the page.

Screenshot_20230125-172145

**Expected behavior**
The image should appear on its own line, and be centered.

**Environment**
- App version: 0.10-alpha_kenya

### PR DESCRIPTION
**Pull request by manas-yu**
## Explanation

Fix #4859
This PR adds `formatImageSpans` to `LiTagHandler` to properly format images that appear within `<li>` tags. The new formatImageSpans function ensures that ImageSpan elements are rendered as block images by inserting line breaks before and after them if they are not already surrounded by `\n`.

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- For PRs introducing new UI elements or color changes, both light and dark mode screenshots must be included
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### CODE REVIEW

**Comment by manas-yu** [comment]
Hi @adhiamboperes, PTAL.  

I tried multiple approaches to append line breaks around the `ImageSpan` or the control character (`'\uFFFC'`) in ImageTagHander, but it wasn't working. It seems to interfere with how Android's `SpannableStringBuilder` processes the control character (`'\uFFFC'`), which is necessary for image rendering. When adding line breaks, the image failed to render correctly.  

As a workaround, I modified the LiTagHandler to achieve the desired result. Let me know if this implementation is acceptable. Also, is there a way to access the images used in the original issue? That would help me make the screenshots more relevant. That way, I could also test for #4530. Thanks!

**Review by adhiamboperes — APPROVED** [review]
Thanks @manas-yu! This LGTM.

**Comment by adhiamboperes** [comment]
@manas-yu, in your screenshots, how come the images are not center aligned? In the current implementation, they are usually placed at the center. Additionally, the sentence, what is a. Seems incomplete.

**Comment by adhiamboperes** [comment]
Re: assets, @Vishwajith-Shettigar had images in https://github.com/oppia/oppia-android/pull/5286. I think they were production assets but they are no longer usable. Please confirm @Vishwajith-Shettigar

**Comment by manas-yu** [comment]
Hi @adhiamboperes, PTAL at the following updates:

- For the incorrect center alignment, the margin spacing was being applied to the images, which disrupted the center alignment. This has now been corrected in the latest changes.
- The sentence "what is a." was intentionally included to highlight the issue with inline rendering.

I'll update the screenshots(if needed) and test for #4530 after the [confirmation](https://github.com/oppia/oppia-android/pull/5687#issuecomment-2637098196)

You can refer to the screenshots below to verify the fixed center alignment.
image
image

File: utility/src/main/java/org/oppia/android/util/parser/html/LiTagHandler.kt [hunk 1]
```diff
@@ -57,6 +61,76 @@ class LiTagHandler(
...
+  private fun formatImageSpans(output: Editable) {
+    val imageSpans = output.getSpans(0, output.length, ImageSpan::class.java)
+
+    imageSpans.sortedByDescending { output.getSpanStart(it) }.forEach { span ->
+      val startIndex = output.getSpanStart(span)
+      val endIndex = output.getSpanEnd(span)
+
+      if (startIndex >= 0 && endIndex <= output.length) {
+        if (endIndex < output.length && output[endIndex] != '\n') {
+          output.insert(endIndex, "\n")
```
Comment (adhiamboperes) [inline utility/src/main/java/org/oppia/android/util/parser/html/LiTagHandler.kt:77]: There is an `appendNewLine()` function below, could you please check if it is applicable in this instance?

**Review by adhiamboperes — COMMENTED** [review]
Thanks @manas-yu! 

I have looked at this again. LGTM except for one comment.

Re: screenshots, do please update the one in content description. 

Re: https://github.com/oppia/oppia-android/issues/4530, we can test for that post merge once we are able to get a hold of the production assets.

File: utility/src/main/java/org/oppia/android/util/parser/html/LiTagHandler.kt (hunk 1 above)
Comment (manas-yu) [reply utility/src/main/java/org/oppia/android/util/parser/html/LiTagHandler.kt:77]: The `formatImageSpans()` method must **insert** newlines at specific positions in the text—both before and after each image span. While an `insertNewLineAt()` helper method could be created for this purpose, it seems unnecessary since it's only used within `formatImageSpans()`. However, if it improves readability or maintainability, adding it would be reasonable. Let me know if you'd like me to refine this further.

Comment (adhiamboperes) [reply utility/src/main/java/org/oppia/android/util/parser/html/LiTagHandler.kt:77]: There's no need to create a new helper at this time.
