### PR TITLE
Fix #2017: Format TextInputEqualsRuleClassifierProviderTest 

### LINKED ISSUE #2017: Format TextInputEqualsRuleClassifierProviderTest
**Describe the bug**
Correct format of `TextInputEqualsRuleClassifierProviderTest` file

**Expected behavior**
Formatting should be correct and in order

### PR DESCRIPTION
**Pull request by anandwana001**
## Explanation

Fix #2017 

### Order
1. constants
2. inject
3. local variable
4. before test setup
5. test cases
6. any utility or private method whichever require
7. dagger setup

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by rt4914** [comment]
@anandwana001 Suggest waiting for the helper class to merge and use it in this file so that we can file issues in much better way.

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputEqualsRuleClassifierProviderTest.kt [hunk 1]
```diff
@@ -23,18 +23,42 @@ import kotlin.test.fail
...
-  private val NON_NEGATIVE_VALUE = createNonNegativeInt(value = 1)
 
   @Inject
   internal lateinit var textInputEqualsRuleClassifierProvider:
     TextInputEqualsRuleClassifierProvider
 
+  @Inject
+  internal lateinit var interactionObjectTestBuilder: InteractionObjectTestBuilder
+
+  private val STRING_VALUE_TEST_UPPERCASE by lazy {
```
Comment (rt4914) [inline domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputEqualsRuleClassifierProviderTest.kt]: As disucssed earlier, we should keep constants at the top, then the inject values, then other variables, followed by setUp function.

Comment (rt4914) [reply domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputEqualsRuleClassifierProviderTest.kt]: But I am not sure because now you are using lazy because of which it looks nice to be kept above other variables. 

@Sarthak2601 @BenHenning Any opinion.

**Review by rt4914 — CHANGES_REQUESTED** [review]
@anandwana001 Actually I am a bit confused and therefore added sarthak and ben. 

Can you add a bit more detailed description to give context to ben about what we are trying to solve here.

File: domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputEqualsRuleClassifierProviderTest.kt (hunk 1 above)
Comment (BenHenning) [reply domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputEqualsRuleClassifierProviderTest.kt]: Hmm. I'm not sure I have a strong opinion here, actually, or see specific value in changing this. Out of curiosity, why use ``by lazy``? Generally, we use that to avoid creating expensive objects or having side effects that should happen later. Neither cases seem relevant to constants, especially in a test.

Comment (BenHenning) [reply domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputEqualsRuleClassifierProviderTest.kt]: Ah, I just realized the ``by lazy`` is needed since it's relying on an injected value. That sort of makes them non-constants now. I think we should either:
1. Treat them as non-constants and rename them accordingly
2. Make ``InterationObjectTestBuilder`` a non-injected class and have companion functions to assemble constants in which case ``by lazy`` won't be needed anymore

Comment (rt4914) [reply domain/src/test/java/org/oppia/android/domain/classify/rules/textinput/TextInputEqualsRuleClassifierProviderTest.kt]: @anandwana001 I am in favour of second option.

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Comment by rt4914** [comment]
@anandwana001 We can merge this now as you have done the step which is mentioned by @BenHenning .

**Comment by anandwana001** [comment]
> @anandwana001 We can merge this now as you have done the step which is mentioned by @BenHenning .

Cool, we can merge this, all check pass. @rt4914
