### PR TITLE
Fix #4878: Add NPS Survey Events

### LINKED ISSUE #4878: Configure Firebase, Firestore and BigQuery on the Development Environment
## Set Up Requirements

- [x] Upgrading the project plan to Blaze. This is necessary to be able to stream data to BigQuery in realtime, and to install the extension that supports this.

### Enable Firestore for the Project
- [x] Owner role, or Editor role with Firebase Role: Develop Admin.
- Navigate to the Cloud Firestore section of the [Firebase console](https://console.firebase.google.com/project/_/firestore).
- You'll be prompted to create a database. Follow the database creation workflow.
   - Under _secure rules for Cloud Firestore_, select **Start in production mode**. This prevents external reads and writes.
   - For _Set Cloud Firestore location_, select region as **US**, which is the same as the existing Firebase configuration for analytics and crashlytics.
   - Click **enable**.

### Add Security Rules
- Once in the Cloud Firestore Console, navigate to the **Rules** tab.
- Change the rules to:

```
rules_version = '2';
// Scopes the rules to the firestore product
service cloud.firestore {
  // Specifies that rules should match any Cloud Firestore database
 match /databases/{database}/documents {
   // Specifies that the rule applies to any document in the nps_survey_open_feedback collection
   // As a result, they also deny access to documents in all other collections, which would have to be granted explicitly.
  match /nps_survey_open_feedback/{document} {
    allow read, write: if request.auth != null;
  	}
    }
}
```
- Click publish.

## Stream Collections to BigQuery Integration
- In the Cloud Firestore Console, navigate to the **Extensions** tab.
- Click **Install** on the **Stream Collections to BigQuery** extension.
- [x] The project billing has already been set, so click on **Next**.
- [x] Review APIs enabled and resources created and enable **Cloud Functions** and **Artifact Registry** which are required for this extension to function properly.
- [x] Review access granted to this extension. No action is required.
- [x] Configure extension
       - Cloud Functions location, which is the same as the Cloud Firestore location above
       - BigQuery Dataset location: `United States(multi-regional)`
       - Project Id: `oppia-android-dev`. In production this will correspond to the prod project id.
       - Collection path: `nps_survey_open_feedback`. This is the name our collection will have on Firestore.
       - Dataset ID: `nps_survey_open_feedback_export`
       - Table ID: `nps_survey_open_feedback`.  This is what our collection will be called once exported to BigQuery. We need this since we haven't actually created the collection in Firestore, but the extension will create it in BigQuery. 
       -  We don't need to configure any of the optionals. 
       - Click to **Install Extension**
       
Extension Documentation: [Stream Collections to BigQuery](https://extensions.dev/extensions/firebase/firestore-bigquery-export?authuser=0&hl=en)

**Note** - in production, we will also configure our data retention time to live per our retention policy. Ref #4904 

### Enable Anonymous Auth
In the Firebase console, Open the **Build/Authentication** menu.

- [x] On the **Sign-in Methods** page, enable the **Anonymous** sign-in method.

### PR DESCRIPTION
**Pull request by adhiamboperes**
## Explanation
Fixes #4878.

This is PR 4 of 6 planned PRs.

It adds eventlogs that are used to describe the survey, including submitting the responses to the compulsory questions of the survey.

The data that needs to be recorded is tracked [here](https://docs.google.com/spreadsheets/d/1oLP9vd8Lfd_wTUyhSFk0K6d5zhL-pVJEZJpRR-cvfXI/edit?resourcekey=0-Por1i0feHg0jff9Sps__Gw#gid=216732748):
- market_fit: MarketFit Answer
- nps_q1: NPS Score
- nps_user: UserType answer
- nps_served: Survey Popup Shown Event
- nps_abandoned: Abandon Survey Event
- language: App language is automatically added to events by the EventBundleCreator
- region_locale: Country information is automatically added to events by the EventBundleCreator
- app_version:  automatically added to events by the EventBundleCreator
- time_exposed/time_submitted: event timestamps are automatically added to events by the AnalyticsController
- lesson_chapter: we're logging both topic and exploration IDs
- user_identifier: This PR adds profileId, although it is not unique. This should be replaced by a unique ID from Core Metrics in a fast-follow item.

The remaining data from this spreadsheet are calculated fields that will be derived from the above parameters.

The nps_q2/ Feedback question is to be uploaded to Firestore on our new Firestore infrastructure in PR #5098.

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

### Event Logs from Developer Menu
|   |  |   
|---|---|
| Screenshot_1688920566| Screenshot_1688758093|   

### Event Logs from Firebase Debug View
|   |  |   
|---|---|
|Screenshot 2023-07-09 at 21 13 20|Screenshot 2023-07-09 at 21 14 04|
|Screenshot 2023-07-09 at 21 17 08|Screenshot 2023-07-09 at 21 18 25|
|Screenshot 2023-07-09 at 22 25 27| Screenshot 2023-07-09 at 22 26 17|

### CODE REVIEW

File: app/src/main/java/org/oppia/android/app/survey/ExitSurveyConfirmationDialogFragmentPresenter.kt [hunk 1]
```diff
@@ -57,7 +55,7 @@ class ExitSurveyConfirmationDialogFragmentPresenter @Inject constructor(
   }
 
   private fun endSurveyWithCallback(callback: () -> Unit) {
-    surveyController.stopSurveySession().toLiveData().observe(
+    surveyController.stopSurveySession(isCompletion = false).toLiveData().observe(
```
Comment (seanlip) [inline app/src/main/java/org/oppia/android/app/survey/ExitSurveyConfirmationDialogFragmentPresenter.kt]: Perhaps isCompletion --> surveyIsComplete or surveyCompleted

(again, trying to avoid starting booleans with a verb since such names are interpretable as functions)

File: domain/src/main/java/org/oppia/android/domain/survey/SurveyProgressController.kt [hunk 2]
```diff
@@ -457,6 +473,63 @@ class SurveyProgressController @Inject constructor(
...
+      isCompletion -> {
+        surveyLogger.logMandatoryResponses(
+          surveyId,
+          profileId,
+          getStoredResponse(SurveyQuestionName.USER_TYPE)!!,
+          getStoredResponse(SurveyQuestionName.MARKET_FIT)!!,
+          getStoredResponse(SurveyQuestionName.NPS)!!
+        )
+
+        // TODO(#5001): Optional responses are uploaded to Firestore, which is out of scope for this PR
```
Comment (seanlip) [inline domain/src/main/java/org/oppia/android/domain/survey/SurveyProgressController.kt]: TODOs should state the action that should be taken to resolve the TODO. 

It is not useful to say "this PR" in it, because, when this PR gets merged into the codebase, developers won't know which PR is being referred to. Comments about scope can go in the PR description or a GitHub comment on the PR.

File: domain/src/main/java/org/oppia/android/domain/survey/SurveyQuestionDeck.kt [hunk 3]
```diff
@@ -91,4 +93,14 @@ class SurveyQuestionDeck constructor(
...
     return isTopOfDeckTerminalChecker(pendingTopQuestion)
   }
+
+  /** Stores a list of all the questions that have been answered in the survey. */
+  fun trackAnsweredQuestions(questionName: SurveyQuestionName) {
+    answeredQuestions.add(questionName)
+  }
+
+  /** Returns whether the survey progress has reached the threshold for partial completion. */
+  fun hasReachedPartialCompletionThreshold(): Boolean {
```
Comment (seanlip) [inline domain/src/main/java/org/oppia/android/domain/survey/SurveyQuestionDeck.kt]: Is "partially completed" (up to the threshold) a subset of "completed" (i.e. would a survey reaching that threshold be also considered complete in a similar manner to isCompletion above), or is it a distinct category?

It's a bit ambiguous, so I would suggest something like hasCompletedAllMandatoryQuestions or something that actually includes the definition of "partial completion" (so that you don't need to use that jargon).

**Review by seanlip — CHANGES_REQUESTED** [review]
Thanks @adhiamboperes! I don't have many comments, just a few suggestions.

File: domain/src/main/java/org/oppia/android/domain/survey/SurveyQuestionDeck.kt (hunk 3 above)
Comment (adhiamboperes) [reply domain/src/main/java/org/oppia/android/domain/survey/SurveyQuestionDeck.kt]: > Is "partially completed" (up to the threshold) a subset of "completed" (i.e. would a survey reaching that threshold be also considered complete in a similar manner to isCompletion above), or is it a distinct category?

Your question is not very clear, but I'll try to answer it:
The survey can have 3 completion states: Fully completed, partially completed or not completed.
It is only fully completed iff all the mandatory questions have been answered and the optional question has been answered as well. It is Partially complete if the mandatory questions have been answered but the optional question has not. If the Mandatory question threshhold hasn't been reached, we consider the survey abandoned.

isCompletion(updated name) is only ever true if the optional question has been answered.

> It's a bit ambiguous, so I would suggest something like hasCompletedAllMandatoryQuestions or something that actually includes the definition of "partial completion" (so that you don't need to use that jargon).

I have updated the function name to `hasAnsweredAllMandatoryQuestions`

File: domain/src/main/java/org/oppia/android/domain/survey/SurveyProgressController.kt (hunk 2 above)
Comment (adhiamboperes) [reply domain/src/main/java/org/oppia/android/domain/survey/SurveyProgressController.kt]: Thanks, I have updated this. I have the comment in the description.

File: app/src/main/java/org/oppia/android/app/survey/ExitSurveyConfirmationDialogFragmentPresenter.kt (hunk 1 above)
Comment (adhiamboperes) [reply app/src/main/java/org/oppia/android/app/survey/ExitSurveyConfirmationDialogFragmentPresenter.kt]: Noted, thanks. I have used both suggestions where I thought they would read more naturally.

**Comment by adhiamboperes** [comment]
> Thanks @adhiamboperes! I don't have many comments, just a few suggestions.

Thanks @seanlip, I have made changes per your suggestions, PTAL.

**Review by seanlip — APPROVED** [review]
Thanks @adhiamboperes. I think this all looks fine in general. My only remaining concern is that there are still some `isCompletion` variables in the PR, and you might want to rename them as discussed previously so that they aren't mistaken for functions.

File: app/src/main/java/org/oppia/android/app/survey/ExitSurveyConfirmationDialogFragmentPresenter.kt (hunk 1 above)
Comment (seanlip) [reply app/src/main/java/org/oppia/android/app/survey/ExitSurveyConfirmationDialogFragmentPresenter.kt]: There are still some more instances of isCompletion in the PR, it might be worth fixing them too.

**Comment by adhiamboperes** [comment]
> Thanks @adhiamboperes. I think this all looks fine in general. My only remaining concern is that there are still some `isCompletion` variables in the PR, and you might want to rename them as discussed previously so that they aren't mistaken for functions.

I have updated all occurences.

**Comment by adhiamboperes** [comment]
Hey @kkmurerwa, please assign back to me once you are through with your review.

File: app/src/main/java/org/oppia/android/app/survey/ExitSurveyConfirmationDialogFragmentPresenter.kt (hunk 1 above)
Comment (adhiamboperes) [reply app/src/main/java/org/oppia/android/app/survey/ExitSurveyConfirmationDialogFragmentPresenter.kt]: Updated

**Review by kkmurerwa — APPROVED** [review]
Hi @adhiamboperes. This PR LGTM.

**Comment by adhiamboperes** [comment]
Thanks @kkmurerwa!
