### PR TITLE
Fix #1968: Fix NavigationDrawerTestActivityTest for Robolectric

### LINKED ISSUE #1968: Fix NavigationDrawerTestActivityTest for Robolectric
Currently, NavigationDrawerTestActivityTest are passing on Espresso but they should also pass on Robolectric. Fix these below mentioned files to make sure that the tests pass on Robolectric.

You can run robolectric tests by following these steps: https://github.com/oppia/oppia-android/wiki/Oppia-Android-Testing#running-roboelectric-tests

Fixing test cases will need to introduce TextApplicationComponent. This can be seen [here](https://github.com/oppia/oppia-android/pull/1680/commits/4729d551b86282ce617e1d53f2762416758785a1).

### PR DESCRIPTION
**Pull request by anandwana001**
## Explanation

Fix #1968 

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

**Comment by BenHenning** [comment]
So I've been investigating this. When digging into why click() is failing (e.g. due to the 'Admin' text not being at least 90% visible), I found something interesting. The internal check to Espresso uses something called view.getGlobalVisibleRect() to get the visible rect of the child. That function, internally, relies heavily on its parent to determine if it's visible (e.g. by calling ViewGroup.getChildVisibleRect()). If you follow this up to the DrawerLayout starting at the admin text, all views underneath that layout are visible until you reach that point of the hierarchy. The child in question is NavigationView and it has an mLeft value of -768 (meaning the menu is completely offscreen when Robolectric is trying to interact with it).

Not sure why Robolectric isn't waiting for the drawer to open--trying to figure that part out now.

**Comment by BenHenning** [comment]
I have a decent idea why this is happening now, but don't yet have a workaround. Clicking to open the navigation drawer is piping through ActionBarDrawerToggle & into DrawerLayout.openDrawer() as expected. However, it starts going downhill from there: openDrawer() uses a utility class called ViewDragHelper + an override to computeScroll() to scroll the drawer open after being told to open. The initiation of this process is working, but unsurprisingly Robolectric doesn't call into computeScroll() correctly (we've run into this problem in past tests, too). Looking for a way to force the scrolling.

**Comment by BenHenning** [comment]
Aha, it seems that computeScroll() is only called during the View's drawing step, and Robolectric skips view rendering. It's a bit bad that Android has a rendering process with side effects imo, but that's something that we need to live with for certain animations it seems.

**Comment by BenHenning** [comment]
Hmm. Apparently just calling computeScroll() opens the drawer enough to fix the test. I'm not sure why it works with just one call (real Android calls it 3-4 times with an emulator & debugger attached)--maybe it has something to do with the fake time. We may need to tweak this if we see flakes in the future, but it's easily isolatable. Will post fixed version of the test suite soon.

**Comment by BenHenning** [comment]
Here's my partially working implementation: https://gist.github.com/BenHenning/e0c3c6d729409d74bcb2e213a6557db6/revisions. Some tests are passing, and I think the mechanism being introduced here is correct. Some additional changes that I think will be needed:
1. I don't think we can use open() for the drawer--we should probably use the mechanism I introduced here (which may need to be generalized to support different screens besides home)
2. A lot of these tests are performing multi-activity tests--they need to split apart since Robolectric doesn't support actually changing activities

All of the tests are passing on Espresso, and a bit less than half are passing on Robolectric. The other failures *seem* mainly tied to testing multiple activities, so I'm deferring to you @anandwana001 to finish up those pieces.

**Comment by BenHenning** [comment]
(Reassigning since I don't think I have anything left to do here since I found a workaround for the core issue).

File: app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerTestActivityTest.kt [hunk 1]
```diff
@@ -276,93 +249,74 @@ class NavigationDrawerTestActivityTest {
...
   }
 
   @Test
+  @Ignore("Navigation Drawer is not closing")
   fun testNavigationDrawerTestActivity_openNavigationDrawerAndClose_closingOfNavigationDrawerIsVerifiedSuccessfully() { // ktlint-disable max-line-length
     launch(NavigationDrawerTestActivity::class.java).use {
       testCoroutineDispatchers.runCurrent()
-      onView(withContentDescription(R.string.drawer_open_content_description)).perform(click())
+      it.openNavigationDrawer()
       onView(withId(R.id.home_activity_drawer_layout)).perform(close())
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerTestActivityTest.kt]: @BenHenning Tried a similar mechanism with few tweaks to close the Drawer but not working. 

 1. `drawer_close_content_description`, not worked with computeScroll too
 2. `swipeLeft()` - not worked with computeScroll too
 3.  `DrawerActions.close()` - not worked
 4. Tried custom ViewAction - not worked

File: app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerTestActivityTest.kt [hunk 2]
```diff
@@ -374,6 +374,23 @@ class NavigationDrawerTestActivityTest {
...
+      it.openNavigationDrawer()
+      onView(withText(R.string.menu_switch_profile)).perform(click())
+      onView(withText(R.string.home_activity_back_dialog_message))
+        .inRoot(isDialog())
+        .check(matches(isDisplayed()))
+      onView(withText(R.string.home_activity_back_dialog_cancel))
+        .inRoot(isDialog())
+        .perform(click())
+      testCoroutineDispatchers.runCurrent()
+      onView(withId(R.id.home_activity_drawer_layout)).check(matches(isClosed()))
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerTestActivityTest.kt:385]: Out of curiosity, does this fail when you use it in the beginning of the test before the drawer is even opened?

File: app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerTestActivityTest.kt (hunk 1 above)
Comment (BenHenning) [reply app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerTestActivityTest.kt]: Hmm closing is tricky. Can we avoid testing these cases? To some extent this is just testing that the drawer itself works, and I think we can assume that it does. Worst case, maybe add 1 close test that's Espresso-only (it's not unreasonable to have a few Espresso-specific tests when it's too hard to test something on Robolectric).

File: app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerTestActivityTest.kt (hunk 2 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerTestActivityTest.kt:385]: No, Initially this test case is never ignored and it always passes as the opening and closing has no effect and as result, the `home_activity_drawer_layout` is always in the closed state.

File: app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerTestActivityTest.kt (hunk 1 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerTestActivityTest.kt]: Done

**Comment by BenHenning** [comment]
Ack thanks @anandwana001. Will do a review pass later today my time.

File: app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerTestActivityTest.kt [hunk 3]
```diff
@@ -276,93 +255,63 @@ class NavigationDrawerTestActivityTest {
...
     launch(NavigationDrawerTestActivity::class.java).use {
-      onView(withContentDescription(R.string.drawer_open_content_description)).perform(click())
+      it.openNavigationDrawer()
       onView(isRoot()).perform(orientationLandscape())
       onView(withId(R.id.home_activity_drawer_layout)).check(matches(isOpen()))
     }
   }
 
   @Test
-  fun testNavigationDrawerTestActivity_openNavigationDrawerAndClose_closingOfNavigationDrawerIsVerifiedSuccessfully() { // ktlint-disable max-line-length
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerTestActivityTest.kt:325]: Per discussion, let's keep this as an Espresso-only test with an explanation of why (e.g. that it's hard to test verifying drawer closing on Robolectric & in general this is mostly testing drawer-specific behavior).

File: app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerTestActivityTest.kt [hunk 4]
```diff
@@ -371,39 +320,15 @@ class NavigationDrawerTestActivityTest {
...
-            )
-          )
-        )
-    }
-  }
-
-  @Test
-  // TODO(#973): Fix NavigationDrawerTestActivityTest
-  @Ignore
-  fun testNavigationDrawerTestActivity_openNavigationDrawer_selectHelpMenuInNavigationDrawer_showsHelpFragmentSuccessfully() { // ktlint-disable max-line-length
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerTestActivityTest.kt:397]: Just to check--was this removed because testNavigationDrawerTestActivity_openNavDrawer_selectHelpMenu_opensHelpActivity effectively tests this flow by verifying HelpActivity navigation?

File: app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerTestActivityTest.kt (hunk 2 above)
Comment (BenHenning) [reply app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerTestActivityTest.kt:385]: That's what I was wondering. Keeping this as Espresso-specific to verify it fails correctly sgtm.

File: app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerTestActivityTest.kt [hunk 5]
```diff
@@ -412,160 +337,102 @@ class NavigationDrawerTestActivityTest {
...
       onView(isRoot()).perform(orientationLandscape())
       onView(withText(R.string.home_activity_back_dialog_message)).check(matches(isDisplayed()))
     }
   }
 
   @Test
-  // TODO(#973): Fix NavigationDrawerTestActivityTest
-  @Ignore
-  fun testNavigationDrawerTestActivity_openNavigationDrawer_selectHelpMenuInNavigationDrawer_clickNavigationDrawerHamburger_navigationDrawerIsOpenedAndVerifiedSuccessfully() { // ktlint-disable max-line-length
+  fun testNavigationDrawerTestActivity_openNavDrawer_selectHelpMenu_opensHelpActivity() { // ktlint-disable max-line-length
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerTestActivityTest.kt]: Can we remove the ktlint disabled directive now? Prefer removing all of them in this file while the suite is already being changed so much.

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @anandwana001! Overall, this LGTM (and I'm really happy to see all of the disables removed here--these were quite tricky!). Just a few comments before I'll approve.

File: app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerTestActivityTest.kt (hunk 4 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerTestActivityTest.kt:397]: yes

File: app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerTestActivityTest.kt (hunk 3 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerTestActivityTest.kt:325]: okay, I thought we can have only one closing test as it is testing in the clicking on cancel in the switch profile. 
Will add this test back too.

File: app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerTestActivityTest.kt (hunk 5 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerTestActivityTest.kt]: Done

File: app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerTestActivityTest.kt [hunk 6]
```diff
@@ -255,7 +254,7 @@ class NavigationDrawerTestActivityTest {
   }
 
   @Test
-  fun testNavigationDrawerTestActivity_openNavDrawer_navigationDrawerIsOpenedSuccessfully() {
+  fun testNavigationDrawerTestActivity_openNavDrawer_navigationDrawerIsOpened() {
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerTestActivityTest.kt]: The order seems a bit weird here--maybe move this to the top of the tests since it seems like the first thing we should check before verifying various properties about the drawer itself.

File: app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerTestActivityTest.kt [hunk 7]
```diff
@@ -283,7 +272,7 @@ class NavigationDrawerTestActivityTest {
   }
 
   @Test
-  fun testNavigationDrawerTestActivity_withAdminProfile_openNavigationDrawer_checkAdministratorControlsDisplayed() { // ktlint-disable max-line-length
+  fun testNavigationDrawerTestActivity_openNavDrawer_adminControlsIsDisplayed() {
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerTestActivityTest.kt]: Here & above: suggest differentiating between an admin profile and user profile (I don't think it's obvious that the default profile state is admin).

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @anandwana001! Just a few more comments.

File: app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerTestActivityTest.kt (hunk 3 above)
Comment (BenHenning) [reply app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerTestActivityTest.kt:325]: Making sure we test different cases of it closing is also important, so I think it's good to add it back. Thanks!

File: app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerTestActivityTest.kt (hunk 6 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerTestActivityTest.kt]: Done

File: app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerTestActivityTest.kt (hunk 7 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerTestActivityTest.kt]: done. 
Did some fixes due to char length ktlint issue
Thinking to create a starter issue to rename these files 

`NavigationDrawerTestActivity` -> `NavigationDrawerActivity`
`NavigationDrawerTestActivityTest` -> `NavigationDrawerActivityTest`

If it sounds good to you, I will create the issue.

File: app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerTestActivityTest.kt [hunk 8]
```diff
@@ -309,7 +309,7 @@ class NavigationDrawerTestActivityTest {
   }
 
   @Test
-  fun testNavigationDrawerTestActivity_withUserProfile_openNavDrawer_adminControlsIsNotDisplayed() {
+  fun testNavigationDrawerTestActivity_withUserProfile_adminControlsIsNotDisplayed() {
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerTestActivityTest.kt]:
```suggestion
  fun testNavigationDrawerTestActivity_withUserProfile_adminControlsAreNotDisplayed() {
```

File: app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerTestActivityTest.kt (hunk 7 above)
Comment (BenHenning) [reply app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerTestActivityTest.kt]: Test rename sounds good, but the activity doesn't seem right--this is a test activity (we would never open it in the production app, for example). The reason the test name isn't quite right is because this isn't testing that the drawer test activity is correct, it's testing that the drawer integration itself is correct. I think a simple test rename is sufficient, but that's not really worth filing an issue over imo--can we just do it quickly?

Also, we should consider rethinking the test strategy for the drawer as a whole (the current tests depend on HomeActivity behavior--that's not ideal). I suggest filing a backlog issue for this, though it won't be suitable for starters.

**Review by BenHenning — APPROVED** [review]
Thanks @anandwana001! Besides the comment for filing an issue, just had one other comment. Feel free to merge once both comments are addressed.

File: app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerTestActivityTest.kt (hunk 8 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerTestActivityTest.kt]: Done

File: app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerTestActivityTest.kt (hunk 7 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerTestActivityTest.kt]: https://github.com/oppia/oppia-android/issues/2249
