### PR TITLE
Fix #1300: Profile & set up profiles tap targets are way too big #1300

### LINKED ISSUE #1300: Profile & set up profiles tap targets are way too big
**Describe the bug**
Tapping well outside both an existing profile and the 'set up multiple profiles' buttons triggers those buttons to be activated.

**To Reproduce**
1. Start with a fresh install of the app (no existing profiles)
2. Open the app and observe the 'Select your profile' screen
3. Either tap below the default 'Sean' profile, or above the 'Set up Multiple Profiles' button
4. Observed: either Sean's profile is selected, or a new profile creation flow is started

**Expected behavior**
Tapping outside of these areas shouldn't trigger them to be clicked (see the attached gifs).

**Screenshots**
large_new_profile_touch_target
_When tapping near the 'set up multiple profiles' button_

large_select_profile_touch_target
_When tapping near the item for selecting an existing profile_

**Device**
- Device/emulator being used: Pixel XL
- SDK version: 29

### PR DESCRIPTION
**Pull request by anandwana001**
## Explanation

Fix #1300
Change the click target to just the content not the complete item. 
 
profile-chooser-click-target

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [ ] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

File: app/src/main/java/org/oppia/app/profile/ProfileChooserFragmentPresenter.kt [hunk 1]
```diff
@@ -168,7 +168,7 @@ class ProfileChooserFragmentPresenter @Inject constructor(
   ) {
     binding.viewModel = model
     binding.presenter = this
-    binding.root.setOnClickListener {
+    binding.root.profile_item.setOnClickListener {
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/app/profile/ProfileChooserFragmentPresenter.kt]: Prefer accessing the view directly instead of using the synthetic import, e.g. ``profileItem``

File: app/src/main/java/org/oppia/app/profile/ProfileChooserFragmentPresenter.kt [hunk 2]
```diff
@@ -201,7 +201,7 @@ class ProfileChooserFragmentPresenter @Inject constructor(
     @Suppress("UNUSED_PARAMETER") model: ProfileChooserUiModel
   ) {
     binding.presenter = this
-    binding.root.setOnClickListener {
+    binding.root.add_profile_item.setOnClickListener {
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/app/profile/ProfileChooserFragmentPresenter.kt]: Ditto here.

File: app/src/main/res/layout-sw600dp-land/profile_chooser_profile_view.xml [hunk 3]
```diff
@@ -30,6 +30,7 @@
     app:profileChooserMarginBottom="@{presenter.wasProfileEverBeenAddedValue ? @dimen/margin_0 : @dimen/margin_0}">
 
     <LinearLayout
+      android:id="@+id/profile_item"
```
Comment (BenHenning) [inline app/src/main/res/layout-sw600dp-land/profile_chooser_profile_view.xml]: Maybe: ``profile_chooser_item``

**Review by BenHenning — APPROVED** [review]
Thanks @anandwana001, this LGTM! Just had a few nits. Feel free to resolve them directly once the changes are implemented.

File: app/src/main/java/org/oppia/app/profile/ProfileChooserFragmentPresenter.kt (hunk 1 above)
Comment (anandwana001) [reply app/src/main/java/org/oppia/app/profile/ProfileChooserFragmentPresenter.kt]: Done, resolving on behalf of ben

File: app/src/main/java/org/oppia/app/profile/ProfileChooserFragmentPresenter.kt (hunk 2 above)
Comment (anandwana001) [reply app/src/main/java/org/oppia/app/profile/ProfileChooserFragmentPresenter.kt]: Done, resolving on behalf of ben

File: app/src/main/res/layout-sw600dp-land/profile_chooser_profile_view.xml (hunk 3 above)
Comment (anandwana001) [reply app/src/main/res/layout-sw600dp-land/profile_chooser_profile_view.xml]: Done, resolving on behalf of ben

**Review by rt4914 — APPROVED** [review]
