### PR TITLE
Fix #3345 Images are not fully displayed 

### LINKED ISSUE #3345: Images are not fully displayed
**Describe the bug**
Critical text in images is cut off. This makes it difficult for users to learn the math concepts. 

**To Reproduce**

In the place values lesson, there are multiple images are not fully displayed. 

**Expected behavior**
Images should be fully displayed. 

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.
Screenshot_20210526-055327_Oppia
Screenshot_20210526-055147_Oppia
Screenshot_20210526-054559_Oppia

**Device** samsung Galaxy s9+
- Android version 8 

**Additional context**

### PR DESCRIPTION
**Pull request by Vishwajith-Shettigar**
## Explanation
Fixes #3345, substracting drawableWidth from maxContentItemPadding only if drawableWidth >= (maxcontentWidth - 
 maxContentItemPadding) would solve the issue.

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

### Before

https://user-images.githubusercontent.com/82181327/122643554-54f1ac00-d108-11eb-906f-6748d2facf2f.jpg

https://user-images.githubusercontent.com/101634267/245153650-cd8335df-01ec-47e6-97b2-7f7244d95efb.jpg

https://user-images.githubusercontent.com/101634267/245153665-cb9506d2-6d0d-4231-8a42-5f8ab15cf4d4.jpg

### After

after_image_cut

after_imagecut

after_image_cut2

### After RTL

After_RTL

after_no_effect_RTL

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- For PRs introducing new UI elements or color changes, both light and dark mode screenshots must be included 
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### CODE REVIEW

**Comment by Vishwajith-Shettigar** [comment]
@adhiamboperes, PTAL

File: utility/src/main/java/org/oppia/android/util/parser/image/UrlImageParser.kt [hunk 1]
```diff
@@ -311,6 +312,8 @@ class UrlImageParser private constructor(
           }
         }
 
+        drawableWidth-=maxContentItemPadding
```
Comment (adhiamboperes) [inline utility/src/main/java/org/oppia/android/util/parser/image/UrlImageParser.kt]: Nit: Please format code.

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @Vishwajith-Shettigar. This is fantastic! 

Some general points:

- [ ] Can you please confirm that these two images display the same way in the before? Confirming some apparent distortion.

|||
|---|---|
|Screenshot_1700522031|Screenshot_1700522887|


- [ ] You can make it easier to do a side by side comparison of your before/after screenshots by using a markdown table like I have used here. See: https://www.tablesgenerator.com/markdown_tables.

- [ ] The last screenshot of the bakery in your screenshots does not seem related to this issue.

File: utility/src/main/java/org/oppia/android/util/parser/image/UrlImageParser.kt (hunk 1 above)
Comment (Vishwajith-Shettigar) [reply utility/src/main/java/org/oppia/android/util/parser/image/UrlImageParser.kt]: okay

**Comment by Vishwajith-Shettigar** [comment]
@adhiamboperes, 
The bakery screenshot is taken in RTL, referencing [this issue](https://github.com/oppia/oppia-android/issues/5032)

**Comment by Vishwajith-Shettigar** [comment]
| Before  | After  |  
|---|---|
| newbefore|newafter|
|new2before | new2after|


@adhiamboperes, PTAL. Did some changes!.

**Comment by Vishwajith-Shettigar** [comment]
> Before	After
> newbefore	newafter
> new2before	new2after

@adhiamboperes, PTAL.

**Review by adhiamboperes — APPROVED** [review]
Thanks @Vishwajith-Shettigar! I think the latest changes look good. 

I would suggest however updating the PR description to explain your solution, before we merge the PR.

**Comment by Vishwajith-Shettigar** [comment]
@adhiamboperes, PTAL, PR description updated.
