### PR TITLE
Fixes #2325: A11y + Highfi changes to audio player

### LINKED ISSUE #2325: Changes in Views related to Audio Player [A11y] [BLOCKED]
**Describe the bug**

Some Views related to Audio Player are not fully compatible with some users from the Accessibility point of view.

Issue 1 - The Audio Player Icon in the ToolBar of Exploration Activity does not have a content label 
Issue 2 - The checkbox inside cellular data dialog box has a height of 41dp which is less than the standard one (48dp)
Issue 3 - The SeekBar which shows the progress of Audio that is being played, does not have a content label

Probable Solution for -
Issue 1) The screen reader should say 'Audio, OFF, Double-tap to activate'
Isseu 3) Audio scrub, STATE (ex: Audio scrub, PAUSED)

**To Reproduce**
Steps to reproduce the behaviour:
1. Start the Accessibility Scanner App on your device
2. Open the Oppia Android App and start Fraction Exploration
3. Try to play the audio to encounter the dialog box and the audio icon
3. Scan the screenshots with the Accessibility Scanner
4. You will see the tests that are not passed by that screen
5. Repeat this for other screens

**Expected behaviour**
All the tests must be passed by scanning the screenshots for both Tablet and Mobile Devices in every orientation.

**Screenshots**
|Issue 1|Issue 2|Issue 3|
|:-:|:-:|:-:|
|Screenshot_2020-12-17-11-24-53-65_80a9469f53bfe75dbc6e8989be28e2f0|Screenshot_2020-12-17-11-25-18-23_80a9469f53bfe75dbc6e8989be28e2f0|Screenshot_2020-12-17-11-25-40-87_80a9469f53bfe75dbc6e8989be28e2f0|

**Device**
- Real Device - RealMe3
- SDK version - 29

**Additional context**
The Screenshots are descriptive enough for understanding the issues but still, if there is a need of clarification then you can comment here. Multiple Pull Requests can also be made for solving these issues.

Reference - [https://github.com/oppia/oppia-android/wiki/Working-on-UI#accessibility-scanner](https://github.com/oppia/oppia-android/wiki/Working-on-UI#accessibility-scanner)

### PR DESCRIPTION
**Pull request by rt4914**
## Explanation

Fixes #2325

Mocks: https://xd.adobe.com/view/dfe8ccd4-39eb-414d-a0b2-b5674357f966-8abb/screen/b73cb76c-3593-4a30-944a-ab240f00d0df/specs/

- As per the mocks the height of the audio player should be of 48dp. Now in previous implementation the height was more than 48dp because of incorrect calculations of height of the images. 
- This PR fixes the height of images by making changes to padding correctly. Also the bottom margin of root layout has been removed as it does not work across different layouts.
- Also the gap between the play/pause and seekbar start is also reduced.

## Note to reviewer
- To test this I suggest using `Galaxy Nexus` emulator as it almost resembles the mocks.
- If the below images look good to you than there is no need to check app for UI on device.
- This screen passes all A11y checks mentioned in #2325
- Talkback output has been added below.

## Before vs. After vs. Mock
Before  After  Mock 

## Talkback output

https://user-images.githubusercontent.com/9396084/116435639-36d6a080-a869-11eb-8992-994cace28b71.mp4

## Espresso Test Result
Screenshot 2021-04-30 at 10 14 20 AM

Filed an issue for the above test failures because they are failing on develop too. Will try to to solve in separate PR.

Screenshot 2021-04-30 at 10 33 35 AM

There was one more test failing in `AudioFragmentTest` which is no longer needed therefore removed it in my last commit.

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

File: app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt [hunk 1]
```diff
@@ -209,6 +210,48 @@ class ExplorationActivityTest {
...
+      networkConnectionUtil.setCurrentConnectionStatus(NetworkConnectionUtil.ConnectionStatus.LOCAL)
+      testCoroutineDispatchers.runCurrent()
+      onView(withId(R.id.action_audio_player))
+        .check(matches(withContentDescription(context.getString(R.string.audio_player_off))))
+    }
+    explorationDataController.stopPlayingExploration()
+  }
+
+  @Test
+  fun testExploration_clickAudioIcon_contentDescription_changesCorrectly() {
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt:234]: I suggest also adding a test for disabling again (to make sure it reverts back).

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @rt4914! I think the solution looks good. Just have two additional questions besides my other comment from this review:
1. Can you post an indication whether the affected tests still pass on Espresso?
2. Is item 2 from #2325 not addressable/not planned to be addressed in this PR?

File: app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt (hunk 1 above)
Comment (rt4914) [reply app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt:234]: Added test.

**Comment by rt4914** [comment]
> Thanks @rt4914! I think the solution looks good. Just have two additional questions besides my other comment from this review:
> 
> 1. Can you post an indication whether the affected tests still pass on Espresso?
> 2. Is item 2 from #2325 not addressable/not planned to be addressed in this PR?

1. I have added details in the description. Summary: Removed one test from AudioFragmentTest and filed #3145 as these tests are failing on develop.
2. It has been solved in #2519 by Arjun.

**Comment by rt4914** [comment]
> > Thanks @rt4914! I think the solution looks good. Just have two additional questions besides my other comment from this review:
> > 
> > 1. Can you post an indication whether the affected tests still pass on Espresso?
> > 2. Is item 2 from #2325 not addressable/not planned to be addressed in this PR?
> 
> 1. I have added details in the description. Summary: Removed one test from AudioFragmentTest and filed #3145 as these tests are failing on develop.
> 2. It has been solved in #2519 by Arjun.

@BenHenning The failing tests for `ExplorationActivityTest` have been fixed in https://github.com/oppia/oppia-android/pull/3147

File: app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt [hunk 2]
```diff
@@ -252,6 +252,30 @@ class ExplorationActivityTest {
...
+        FRACTIONS_EXPLORATION_ID_0
+      )
+    ).use {
+      explorationDataController.startPlayingExploration(FRACTIONS_EXPLORATION_ID_0)
+      networkConnectionUtil.setCurrentConnectionStatus(NetworkConnectionUtil.ConnectionStatus.LOCAL)
+      testCoroutineDispatchers.runCurrent()
+      onView(withId(R.id.action_audio_player))
+        .perform(click())
+      onView(withId(R.id.action_audio_player))
+        .perform(click())
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt]: Prefer these to be on the same lines since line wrapping isn't needed here.

File: app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt [hunk 3]
```diff
@@ -252,6 +252,30 @@ class ExplorationActivityTest {
     explorationDataController.stopPlayingExploration()
   }
 
+  @Test
+  fun testExploration_clickAudioIconTwice_contentDescription_changesToDefault() {
+    setupAudioForFraction()
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt]: Should be ``setUpAudioForFractionLesson`` ('setUp' being the main change). While not part of your PR, it'd be nice to fix this.

**Review by BenHenning — APPROVED** [review]
Thanks @rt4914. Just 2 nits, otherwise PR LGTM.

File: app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt (hunk 2 above)
Comment (rt4914) [reply app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt]: Done.

File: app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt (hunk 3 above)
Comment (rt4914) [reply app/src/sharedTest/java/org/oppia/android/app/player/exploration/ExplorationActivityTest.kt]: Done.

**Comment by rt4914** [comment]
@BenHenning I am unable to understand why the bazel checks are failing.

**Comment by BenHenning** [comment]
@rt4914 you probably already know this by now, but this is likely #3157.
