### PR TITLE
Fix #3446: Fixing PlatformParameterIntegrationTest for both Espresso and Robolectric [RunAllTests]

### LINKED ISSUE #3446: Robolectric failure for Toast message (Reference -PlatfromParameterIntegrationTest)
PR Reference - https://github.com/oppia/oppia-android/pull/3405 (Its replica is made [here](https://github.com/oppia/oppia-android/pull/3441) which is facing same error)

Description - https://github.com/oppia/oppia-android/pull/3405#issuecomment-876422402

### Issue
Cannot run a test on Robolectric but working on Espresso.

```
  There was 1 failure:
  1) testSplashTestActivity_updateEmptyDatabase_readDatabaseValues_checkWelcomeMsgIsVisible(org.oppia.android.app.testing.PlatformParameterIntegrationTest)
  androidx.test.espresso.NoMatchingRootException: Matcher 'is toast' did not match any of the following roots: [Root{application-window-token=android.view.ViewRootImpl$W@65ea45a0, window-token=android.view.ViewRootImpl$W@65ea45a0, has-window-focus=true, layout-params-type=1, layout-params-string={(0,0)(fillxfill) ty=BASE_APPLICATION wanim=0x10302f8
    fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
    pfl=FORCE_DRAW_STATUS_BAR_BACKGROUND}, decor-view-string=DecorView{id=-1, visibility=VISIBLE, width=960, height=1410, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params={(0,0)(fillxfill) ty=BASE_APPLICATION wanim=0x10302f8
    fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
    pfl=FORCE_DRAW_STATUS_BAR_BACKGROUND}, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1}}]
	  at java.base/java.lang.Thread.getStackTrace(Thread.java:1654)
	  at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:96)
	  at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:59)
	  at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:322)
	  at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:306)
	  at org.oppia.android.app.testing.PlatformParameterIntegrationTest.testSplashTestActivity_updateEmptyDatabase_readDatabaseValues_checkWelcomeMsgIsVisible(PlatformParameterIntegrationTest_updated.kt:132)
	  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	  at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	  at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	  at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	  at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	  at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	  at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	  at org.oppia.android.testing.OppiaTestRule$apply$1.evaluate(OppiaTestRule.kt:18)
	  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	  at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:575)
	  at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:263)
	  at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	  at java.base/java.lang.Thread.run(Thread.java:844)
```

### PR DESCRIPTION
**Pull request by Arjupta**
## Explanation

Fixes #3446 
Added Robolectric dependency for androidTestImplementation in app module. This fixed the PlatformParameterTest to run on both Espresso and Robolectric

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

File: app/src/sharedTest/java/org/oppia/android/app/testing/PlatformParameterIntegrationTest.kt [hunk 1]
```diff
@@ -119,42 +105,20 @@ class PlatformParameterIntegrationTest {
...
-          if (windowToken === appToken) {
-            // Means this window isn't contained by any other windows.
-            return true
-          }
-        }
-        return false
-      }
+      testCoroutineDispatchers.runCurrent()
+      assertThat(ShadowToast.getLatestToast()).isNotNull()
+      assertThat(ShadowToast.getTextOfLatestToast()).isEqualTo(SplashTestActivity.WELCOME_MSG)
```
Comment (jcqli) [inline app/src/sharedTest/java/org/oppia/android/app/testing/PlatformParameterIntegrationTest.kt:118]: Is this the only way to verify the toast? If possible I'd also add a check that the toast view is fully visible.

**Review by jcqli — CHANGES_REQUESTED** [review]
This really simplified the code, looks good! Adding a blocking comment re: toast view but I'm not sure how it works with the ShadowToast.

**Review by anandwana001 — CHANGES_REQUESTED** [review]
Please add an espresso test result video. Also, we need to look into the other option than using Shadow.

**Comment by vinitamurthi** [comment]
Note I am removing myself from assignees since I will not be available this weekend, if my input is needed please feel free to add me back and mention me in the comment where its required and I will take a look on Monday!

File: app/src/sharedTest/java/org/oppia/android/app/testing/PlatformParameterIntegrationTest.kt (hunk 1 above)
Comment (Arjupta) [reply app/src/sharedTest/java/org/oppia/android/app/testing/PlatformParameterIntegrationTest.kt:118]: @anandwana001 do you have any suggestions on this?

Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/testing/PlatformParameterIntegrationTest.kt:118]: I need to check if decor view works with both espresso and robolectric or not.

**Comment by Arjupta** [comment]
> Please add an espresso test result video. Also, we need to look into the other option than using Shadow.

Espresso tests are failing with this error  - 
"Attempt to invoke interface method 'java.lang.Object org.robolectric.internal.bytecode.ShadowedObject.$$robo$getData()' on a null object reference"

**Comment by jcqli** [comment]
> > Please add an espresso test result video. Also, we need to look into the other option than using Shadow.
> 
> Espresso tests are failing with this error -
> "Attempt to invoke interface method 'java.lang.Object org.robolectric.internal.bytecode.ShadowedObject.$$robo$getData()' on a null object reference"

Is this a new failure? What changes were made?

**Comment by anandwana001** [comment]
Shadow doesn't work with espresso, it's a robolectric library

**Comment by Arjupta** [comment]
@anandwana001 as per @BenHenning 's suggestion I have moved this PlatformParameterIntegrationTest to "test" directory of app module. Does this looks good to you?

**Comment by Arjupta** [comment]
> > > Please add an espresso test result video. Also, we need to look into the other option than using Shadow.
> > 
> > 
> > Espresso tests are failing with this error -
> > "Attempt to invoke interface method 'java.lang.Object org.robolectric.internal.bytecode.ShadowedObject.$$robo$getData()' on a null object reference"
> 
> Is this a new failure? What changes were made?

There were no new changes, only ran these tests on Espresso. Earlier I was more focussed on resolving the failing tests on robolectric thatswhy I didn't ran them for Espresso.

File: app/src/sharedTest/java/org/oppia/android/app/testing/PlatformParameterIntegrationTest.kt (hunk 1 above)
Comment (jcqli) [reply app/src/sharedTest/java/org/oppia/android/app/testing/PlatformParameterIntegrationTest.kt:118]: From an offline conversation we learned that Shadows are not compatible with Espresso so we won't be verifying any UI elements with these tests. This comment is not applicable anymore.

**Review by jcqli — APPROVED** [review]
LGTM

**Comment by rt4914** [comment]
Un-assigning myself and will defer to @anandwana001 on this PR.

File: app/src/test/java/org/oppia/android/app/testing/PlatformParameterIntegrationTest.kt [hunk 2]
```diff
@@ -109,6 +91,7 @@ class PlatformParameterIntegrationTest {
   @Before
   fun setUp() {
     setUpTestApplicationComponent()
+    ShadowToast.reset()
```
Comment (anandwana001) [inline app/src/test/java/org/oppia/android/app/testing/PlatformParameterIntegrationTest.kt]: Why are we resetting at the start of the test? 

Reset method is called when we want to clear the recorded test, mostly after functions like `.showToast()` or after functions like where to count or read the toast text.

Comment (anandwana001) [reply app/src/test/java/org/oppia/android/app/testing/PlatformParameterIntegrationTest.kt]: Screenshot 2021-07-22 at 18 55 00

**Review by anandwana001 — CHANGES_REQUESTED** [review]

File: app/src/test/java/org/oppia/android/app/testing/PlatformParameterIntegrationTest.kt (hunk 2 above)
Comment (Arjupta) [reply app/src/test/java/org/oppia/android/app/testing/PlatformParameterIntegrationTest.kt]: I was doing it just to clear any previous state. But yeah if we can work without it thats not an issue. Commiting this change

Comment (ARJUPTA) [reply app/src/test/java/org/oppia/android/app/testing/PlatformParameterIntegrationTest.kt:94]: I was doing it just to clear any previous state. But yeah if we can work without it thats not an issue. Commiting this change

Comment (anandwana001) [reply app/src/test/java/org/oppia/android/app/testing/PlatformParameterIntegrationTest.kt]: I don't know removing will work or not, I just shifted it to after. Let's see if it works, though moving it to after works, because let's say in future if we add more test with more toast text, it might fail.

**Comment by Arjupta** [comment]
@anandwana001 PTAL, it can be merged now.
//cc @vinitamurthi @jcqli

**Comment by vinitamurthi** [comment]
Note the bazel tests are probably not running because no test targets were affected by this change

**Review by anandwana001 — APPROVED** [review]
LGTM
