### PR TITLE
Partially fix #89: Introduce test coroutine dispatchers (early testing utility)

### LINKED ISSUE #89: Properly handle background thread processing in AndroidX tests
tl;dr: The project needs a way to consistently test operations which require background processing in a way that's consistent with production environments,

UI-centric AndroidX tests can run on both Robolectric and Espresso. Both Robolectric and Espresso have their own ways to block on background tasks completing.

Robolectric running in legacy mode can deterministically advance the system clock and looper to execute pending tasks. This, combined with Kotlin's experimental [runBlockingTest](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-test/kotlinx.coroutines.test/run-blocking-test.html) provides a nice way to at least test background tasks that are blocking on coroutines. However, this isn't fool-proof, and has its own issues (e.g. best practice is to use [InstantTaskExecutorRule](https://developer.android.com/reference/android/arch/core/executor/testing/InstantTaskExecutorRule) which actually forces synchronous execution).

Espresso, on the other hand, has the choice of [idling resources](https://developer.android.com/training/testing/espresso/idling-resource). These allow the app to communicate to Espresso when a non-UI bound task has completed which pairs well with Espresso's internal idling mechanism. This helps improve test determinism for Espresso.

Having two solutions isn't viable for shared AndroidX tests, and Robolectric's approach results in synchronizing background processing which reduces the chance of discovering race conditions. Instead, Oppia Android should have a way to run background tasks similar to production (i.e. by not synchronizing them or forcing them to run on the main thread), and ensure both testing frameworks can consistently wait for completion (probably by using idling resource since Robolectric should support them, or using either idling resource or a Robolectric-specific solution). This should also be done in conjunction with running Robolectric in a [paused looper mode](http://robolectric.org/blog/2019/06/04/paused-looper/) to have better parity with Android and try to detect real timing regressions that could occur in production.

Edit: Jetpack Compose also needs to be considered (see comment below).

### PR DESCRIPTION
**Pull request by BenHenning**
Introduce a test coroutine dispatcher & coordination utility to guarantee determinism in Robolectric tests. This is not yet app module or Espresso compatible (that requires abstracting the main thread portion & leveraging IdlingResources, plus verifying the replacement mechanism for app module dependencies). #89 is tracking the additional work needed after this PR is submitted.

This also introduces a new testing module where test-only dependencies can live. We shouldn't over-user this yet (e.g. app test deps should stay in the app module), but this is a pattern we will make more use of in the future (especially after we move to Bazel in #59).

This solves one critical requirement for resolving #89: arranging thread execution so that it can be deterministically idled. This was used successfully in downstream tests (see #928). However, please note that this implementation is still incomplete. #89 includes additional details of what work is needed here, so integrations with this utility should be used cautiously until it has had time to be finalized.

This implementation is loosely based on Kotlin's experimental TestCoroutineDispatcher, except the implementation needed significant changes in order to work in this coordinated environment so it was effectively rewritten from the ground up using Kotlin's as a reference for how to actually continue suspended execution.

Finally, no tests were added yet since the implementation still may broadly change and certain aspects aren't trivially testable (like the fake system clock since it's not yet correctly coordinating system time in tests across all aspects of the simulated Android test environment).

### CODE REVIEW

File: testing/src/main/java/org/oppia/testing/TestCoroutineDispatchers.kt [hunk 1]
```diff
@@ -0,0 +1,116 @@
...
+    // TODO(#89): Ensure the check for pending UI thread tasks is actually correct.
+    return backgroundTestDispatcher.hasPendingTasks()
+        || blockingTestDispatcher.hasPendingTasks()
+        || !shadowUiLooper.isIdle
+  }
+
+  private fun hasPendingCompletableTasks(): Boolean {
+    return backgroundTestDispatcher.hasPendingCompletableTasks()
+        || blockingTestDispatcher.hasPendingCompletableTasks()
+        || !shadowUiLooper.isIdle
```
Comment (rt4914) [inline testing/src/main/java/org/oppia/testing/TestCoroutineDispatchers.kt]: Indentation Update:
```
  private fun hasPendingTasks(): Boolean {
    // TODO(#89): Ensure the check for pending UI thread tasks is actually correct.
    return backgroundTestDispatcher.hasPendingTasks()
      || blockingTestDispatcher.hasPendingTasks()
      || !shadowUiLooper.isIdle
  }

  private fun hasPendingCompletableTasks(): Boolean {
    return backgroundTestDispatcher.hasPendingCompletableTasks()
      || blockingTestDispatcher.hasPendingCompletableTasks()
      || !shadowUiLooper.isIdle
  }
```

Or are we keeping continuation indentation as `4 spaces` ?

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

File: testing/src/main/java/org/oppia/testing/TestCoroutineDispatchers.kt (hunk 1 above)
Comment (BenHenning) [reply testing/src/main/java/org/oppia/testing/TestCoroutineDispatchers.kt]: Looks like we're using 4 spaces for continuation, but I apparently incorrectly put ``||`` at the beginning of the line. I used ktlint to reformat the file as part of answering your question. I think we should follow the formatter in this case unless other folks have a strong opinion about it.

Comment (rt4914) [reply testing/src/main/java/org/oppia/testing/TestCoroutineDispatchers.kt]: Okay, now it looks more readable. I think we should use ktlint only to avoid any confusion.

File: testing/build.gradle [hunk 2]
```diff
@@ -0,0 +1,50 @@
+apply plugin: 'com.android.library'
+apply plugin: 'kotlin-android'
+apply plugin: 'kotlin-android-extensions'
+apply plugin: 'kotlin-kapt'
+
+android {
```
Comment (aggarwalpulkit596) [inline testing/build.gradle:6]: I don't see why this needs to be an android module?

Comment (BenHenning) [reply testing/build.gradle:6]: The classes included in this module depend on test-only libraries like Robolectric. We can't actually include those in the production builds of the app, and any source files included in the other modules are automatically included unless they're under the test folder. Since these utilities aren't actually tests, they shouldn't go under the test folder. It seems like having a dedicated, test-only module is the only way to solve this problem. Do you have another approach that might work?

Comment (vinitamurthi) [reply testing/build.gradle:6]: I'm curious, have we already specified in this PR (if so, can you tell me where?) that for release builds we shouldn't include this module?  Or is this something we would like to do in the future/something gradle does by default? I am wondering how to go about that in gradle builds

File: testing/src/main/java/org/oppia/testing/TestCoroutineDispatchers.kt [hunk 3]
```diff
@@ -0,0 +1,116 @@
...
+   */
+  @ExperimentalCoroutinesApi
+  fun advanceUntilIdle() {
+    do {
+      flushAllTasks()
+    } while (hasPendingTasks())
+  }
+
+  @ExperimentalCoroutinesApi
+  private fun flushNextTasks() {
```
Comment (vinitamurthi) [inline testing/src/main/java/org/oppia/testing/TestCoroutineDispatchers.kt:79]: This is more for my understanding: is flushNextTasks supposed to flush for every dispatcher that's available? I'm wondering if there's a way to flush only backgroundTestDispatcher or only blockingTestDispatcher for e.g.

**Review by vinitamurthi — APPROVED** [review]
LGTM, I just had some questions for my own understanding

File: testing/build.gradle (hunk 2 above)
Comment (BenHenning) [reply testing/build.gradle:6]: It's an implicit thing right now--the project isn't included for any non-test dependency lists for the other modules so it won't be included. With modules we have control over what dependencies are included, but not over what sources are included which is why we needed to make this split.

I *think* it might be possible to segment sources within a single module, but I'm expecting that to cause other issues since it's a rather non-typical thing to do with Gradle. This seemed like a more Gradle-idiomatic way to ensure certain source files aren't included.

Comment (BenHenning) [reply testing/build.gradle:6]: @aggarwalpulkit596 since you didn't follow up, I'm taking that to mean you're okay with the test-only module. Please follow up with me if you're not. Since this is blocking a lot of downstream work, I want to get this submitted.

File: testing/src/main/java/org/oppia/testing/TestCoroutineDispatchers.kt (hunk 3 above)
Comment (BenHenning) [reply testing/src/main/java/org/oppia/testing/TestCoroutineDispatchers.kt:79]: You can inject those test dispatchers directly and call their flush method. I did this in a downstream test while writing it, then went back to the flush-everything one. I think it's unlikely you'll want to flush a specific dispatcher since it doesn't properly solve the cross-thread cases, but the option is supported.

**Comment by BenHenning** [comment]
Thanks everyone!
