### PR TITLE
Fix part of #3861: Submit-time errors permanently break the answer submission flow

### LINKED ISSUE #3861: Submit-time errors permanently break the answer submission flow
**Describe the bug**
When a submit-time error is encountered, attempting to submit another answer (regardless of correctness) causes an error to be logged in logcat and the submit button stops working (the entire exploration experience goes into a bad state).

**To Reproduce**
1. Open the prototype exploration
2. Navigate to the fraction input state (second state)
3. Input "1/" and click submit
4. Observe the submit-time error
5. Now, try to input "1/2"
6. Observe that the submit button goes gray, no feedback is given, and the exploration is now broken (including back navigation)

Note that navigating away & back to the lesson (e.g. via checkpointing) fixes the issue & is probably a reasonable mitigation in the meantime.

**Expected behavior**
Submit-time errors should not break the lesson experience.

**Demonstration**
None--this is fairly easy to repro so no demo was added.

**Environment**
- Device/emulator being used: Nexus 5X
- Android or SDK version (e.g. Android 5 or SDK 21): SDK 27
- App version (you can get this through system app settings or via the admin controls menu in-app): 0.6-dev-7ff1b2bbd2

**Additional context**
This was found during alpha MR3 development, but it's not specifically tied to the MR3 release.

### PR DESCRIPTION
**Pull request by anandwana001**
## Explanation

Fix a part of #3861 

### My Observation while fixing this issue
1. In `FractionInteractionViewModel` using text watcher we keep track of real-time errors at function `checkPendingAnswerError`
2. On submit button click, we again come to `checkPendingAnswerError` with a submit-time check.
3. In function `getSubmitTimeError` when we call `parseFraction` using the input string `1/` it returns null.

### Cause
1. `parseFraction` returns null, which make `pendingAnswerError` null.
2. Now, when we try to get the pending answer it creates a new user instance for us, which only consists of `contentDescription`.
```proto
private UserAnswer() {
    contentDescription_ = "";
  }
```
3. Now, with this incomplete proto, we try to access `answer`, and `writtenTranslationContext` from our controller, which leads to falling under the `finally` case in try/catch handle where we use an uninitialized variable to access.
https://github.com/oppia/oppia-android/blob/dd024327d32d4c8edcbf12fe31d9df97f7f71a4f/domain/src/main/java/org/oppia/android/domain/exploration/ExplorationProgressController.kt#L180

### Fix
1. Add an additional check `normalized.endsWith("/") -> FractionParsingError.INVALID_FORMAT` to catch on real-time.
It should have caught on real-time so that submit button doesn't get active.
2. Do we need some updates in UserAnswer proto default creation?
3. Initialising the variable inside the try/catch will again lead to crashes in the future, need some better understanding here.
https://github.com/oppia/oppia-android/blob/dd024327d32d4c8edcbf12fe31d9df97f7f71a4f/domain/src/main/java/org/oppia/android/domain/exploration/ExplorationProgressController.kt#L174

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### CODE REVIEW

**Comment by anandwana001** [comment]
@BenHenning Assigned you to get your initial thoughts on this. Please check the PR description.

**Comment by BenHenning** [comment]
@anandwana001 I think this is sensible in terms of fixing a fractions specific issue, but I think to fix #3861 we also need to build in robustness such that these situations don't permanently break the answer submission flow.

I actually added a solution in #2173 when I noticed a similar problem when testing algebraic expressions (see changes to submitAnswer in ExplorationProgressController). Would those changes also fix the permanent broken state observed here, as well (separately from the fraction error fix)?

**Comment by anandwana001** [comment]
@BenHenning  I run your PR locally and below are the things that happened:
1. Input `1/`
2. submit button gets active
3. click submit
4. real-time error is shown and also there is an error in Logcat

```
org.oppia.android E/StateFragment: Failed to retrieve answer outcome
    java.lang.IllegalStateException: Failed when classifying answer # org.oppia.android.app.model.InteractionObject@7bc6f for interaction FractionInput
        at org.oppia.android.domain.classify.AnswerClassificationController.classifyAnswer(AnswerClassificationController.kt:82)
        at org.oppia.android.domain.classify.AnswerClassificationController.classify(AnswerClassificationController.kt:40)
        at org.oppia.android.domain.exploration.ExplorationProgressController.submitAnswer(ExplorationProgressController.kt:178)
        at org.oppia.android.app.player.state.StateFragmentPresenter.handleSubmitAnswer(StateFragmentPresenter.kt:403)
        at org.oppia.android.app.player.state.StateFragmentPresenter.onSubmitButtonClicked(StateFragmentPresenter.kt:193)
        at org.oppia.android.app.player.state.StateFragment.onSubmitButtonClicked(StateFragment.kt:105)
        at org.oppia.android.databinding.SubmitButtonItemBindingImpl._internalCallbackOnClick(SubmitButtonItemBindingImpl.java:322)
        at org.oppia.android.generated.callback.OnClickListener.onClick(OnClickListener.java:11)
Caused by: java.lang.IllegalStateException: Expected answer to be of type FRACTION not OBJECTTYPE_NOT_SET
        at org.oppia.android.domain.classify.rules.GenericRuleClassifier.matches(GenericRuleClassifier.kt:28)
        at org.oppia.android.domain.classify.AnswerClassificationController.classifyAnswer(AnswerClassificationController.kt:69)
```

5. Input another wrong answer ex - `5/6`
6. Submit button gets active and able to submit
7. We can move back/forth in exploration.

**Comment by anandwana001** [comment]
Ignore the test failure, it is a nit fix, will update once we finalize the above discussion.

**Comment by BenHenning** [comment]
> @BenHenning I run your PR locally and below are the things that happened:
> 
> 1. Input `1/`
> 2. submit button gets active
> 3. click submit
> 4. real-time error is shown and also there is an error in Logcat
> 
> ```
> org.oppia.android E/StateFragment: Failed to retrieve answer outcome
>     java.lang.IllegalStateException: Failed when classifying answer # org.oppia.android.app.model.InteractionObject@7bc6f for interaction FractionInput
>         at org.oppia.android.domain.classify.AnswerClassificationController.classifyAnswer(AnswerClassificationController.kt:82)
>         at org.oppia.android.domain.classify.AnswerClassificationController.classify(AnswerClassificationController.kt:40)
>         at org.oppia.android.domain.exploration.ExplorationProgressController.submitAnswer(ExplorationProgressController.kt:178)
>         at org.oppia.android.app.player.state.StateFragmentPresenter.handleSubmitAnswer(StateFragmentPresenter.kt:403)
>         at org.oppia.android.app.player.state.StateFragmentPresenter.onSubmitButtonClicked(StateFragmentPresenter.kt:193)
>         at org.oppia.android.app.player.state.StateFragment.onSubmitButtonClicked(StateFragment.kt:105)
>         at org.oppia.android.databinding.SubmitButtonItemBindingImpl._internalCallbackOnClick(SubmitButtonItemBindingImpl.java:322)
>         at org.oppia.android.generated.callback.OnClickListener.onClick(OnClickListener.java:11)
> Caused by: java.lang.IllegalStateException: Expected answer to be of type FRACTION not OBJECTTYPE_NOT_SET
>         at org.oppia.android.domain.classify.rules.GenericRuleClassifier.matches(GenericRuleClassifier.kt:28)
>         at org.oppia.android.domain.classify.AnswerClassificationController.classifyAnswer(AnswerClassificationController.kt:69)
> ```
> 
> 5. Input another wrong answer ex - `5/6`
> 6. Submit button gets active and able to submit
> 7. We can move back/forth in exploration.

Ah, in that case maybe this PR should be 'fix part of #3861' and I can add the 'Fix #3861' to my PR to finish it.

File: app/src/main/java/org/oppia/android/app/parser/StringToFractionParser.kt [hunk 1]
```diff
@@ -50,6 +50,7 @@ class StringToFractionParser {
     return when {
       !normalized.matches(invalidCharsRegex) -> FractionParsingError.INVALID_CHARS
       normalized.startsWith("/") -> FractionParsingError.INVALID_FORMAT
+      normalized.endsWith("/") -> FractionParsingError.INVALID_FORMAT
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/parser/StringToFractionParser.kt]: Please add a test for this case (e.g. in the parser's test suite). Also, it would be good to introduce a StateFragmentLocalTest test that triggers this permanent breakage scenario to verify that it's fixed.

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @anandwana001. One comment (but two main points)--PTAL.

File: app/src/main/java/org/oppia/android/app/parser/StringToFractionParser.kt (hunk 1 above)
Comment (anandwana001) [reply app/src/main/java/org/oppia/android/app/parser/StringToFractionParser.kt]: Added tests in the parser. 

For `StateFragmentLocalTest `, as per existing tests, all the tests related to real-time error text displayed or not, we add in `StateFragmentTest`.
For example - `testStateFragment_loadExp_secondState_submitInvalidAnswer_disablesSubmitAndShowsError`.
which already checks that the permanent breakage scenario is fixed.

Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/parser/StringToFractionParser.kt]: I'm actually thinking this should be a submit-time error (I didn't notice before this was added as a real-time error) since it will be a bit noisy (i.e. it'll always show up as you're typing a fraction, which isn't ideal).

**Review by BenHenning — COMMENTED** [review]
Thanks @anandwana001. Generally LGTM, but left one comment suggesting this be updated to be a submit-time error. PTAL.

File: app/src/main/java/org/oppia/android/app/parser/StringToFractionParser.kt (hunk 1 above)
Comment (anandwana001) [reply app/src/main/java/org/oppia/android/app/parser/StringToFractionParser.kt]: Updated

File: app/src/main/java/org/oppia/android/app/parser/StringToFractionParser.kt [hunk 2]
```diff
@@ -29,6 +29,8 @@ class StringToFractionParser {
   fun getSubmitTimeError(text: String): FractionParsingError {
     if (invalidCharsLengthRegex.find(text) != null)
       return FractionParsingError.NUMBER_TOO_LONG
+    if (text.endsWith("/"))
+      return FractionParsingError.INVALID_FORMAT
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/parser/StringToFractionParser.kt]: Should have braces per https://developer.android.com/kotlin/style-guide#braces. Ditto for other cases in this file that are wrong (while we're here, might as well fix them).

**Review by BenHenning — COMMENTED** [review]
Thanks @anandwana001. Just had one nit, otherwise the PR LGTM. PTAL.

File: app/src/main/java/org/oppia/android/app/parser/StringToFractionParser.kt (hunk 2 above)
Comment (anandwana001) [reply app/src/main/java/org/oppia/android/app/parser/StringToFractionParser.kt]: Done

**Comment by anandwana001** [comment]
Flake test failing.

**Review by BenHenning — APPROVED** [review]
Thanks @anandwana001. LGTM.
