### PR TITLE
Fix #4028: Hi fi profile tablet implement edit profile screen inside a fragment

### LINKED ISSUE #3242: Hi-Fi User Profile Tablet
Mobile - https://xd.adobe.com/view/0687f00c-695b-437a-79a6-688e7f4f7552-70b6/screen/1c3f250f-32e5-4299-8187-75d7c3dbe6b6/

Tablet - https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/screen/e277771d-14bf-48a2-9974-7d48f25d3f28/

**Follow this guide**: https://github.com/oppia/oppia-android/wiki/Working-on-UI

### LINKED ISSUE #4007: ProfileEditFragment Backstack loop error
**Describe the bug**
In tablet When we reset or rename the Profile by Administrator controls in ProfileEditFragment and then on Pressing the back button we get stuck in a loop
**To Reproduce**
1. Go to Administrator Controls and click on any profile and then reset the pin or rename the name 
2. Click on the BackButton
3. Again Click on the back button
4. You get stuck in a loop of ProfileEditFragment and ProfileListFragment

**Expected behavior**
You should go back to administrator controls activity after pressing back button

**Demonstration**
|   |    |   |
| - | - | - |
| Screenshot_20211122_210529 | Screenshot_20211122_210618 | Screenshot_20211122_210644 |
| Screenshot_20211122_210701 | Screenshot_20211122_210706 |

https://user-images.githubusercontent.com/76404817/142893869-2f33edc5-0c89-4267-a5ff-af8bfe17f3e4.mp4

**Environment**
- Device/emulator being used: <device version/emulator>
- Android or SDK version : Android 9 Oreo/ api 28
- App version : latest dev

### LINKED ISSUE #4028: Implement edit profile screen inside a fragment
issue #3241 

refer to this issue for the details and impletation for this issue
this issue basically resolves the hi-fi profile in administrator controls.

 Implementing edit profile screen inside a fragment

### PR DESCRIPTION
**Pull request by yash10019coder**
## Explanation

Fixes #4028 
Fixes #3242 
Fixes #4007 
## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:

## Mobile Screenshots
| Old | New |
| - | - |
| Screenshot_20220106_235314 |  Screenshot_20220106_232411 |
| Screenshot_20220106_235326 |  Screenshot_20220106_232440 |
| Screenshot_20220106_235337 |  Screenshot_20220106_232415 |
| Screenshot_20220106_235340 |  Screenshot_20220106_232652 |
| Screenshot_20220106_235349 |  Screenshot_20220106_232745 |
| Screenshot_20220106_235353 |  Screenshot_20220106_232752 |
| Screenshot_20220106_235358 |  Screenshot_20220106_232758 |
| Screenshot_20220106_235404 |  Screenshot_20220106_232802 |
| Screenshot_20220106_235407 |  Screenshot_20220106_232818 |

## Tablet Screenshots
| Old | New |
| - | - |
|Screenshot_20220106_234109 | New Tab Port |
| Screenshot_20220106_234119 |  New Tab Land |
| Screenshot_20220106_234127 |  New Tab Admin Port  |
|Screenshot_20220106_234137 |  New Tablet Admin Land |
| Screenshot_20220106_234145 |  New Tablet User Port |
| Screenshot_20220106_234149 |  New Tablet User Land |

## UI Workflow Mobile
https://user-images.githubusercontent.com/76404817/153045130-d98344f4-18b1-4093-8eb9-294285c84099.mp4

## UI Workflow Tablet
https://user-images.githubusercontent.com/76404817/153045402-80a317de-49d9-4975-8925-88b7b1645df5.mp4

## AdministratorControlsActivityTest and AdministratorControlsFragmentTest
image
image

### CODE REVIEW

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt [hunk 1]
```diff
@@ -90,6 +93,25 @@ class AdministratorControlsActivityPresenter @Inject constructor(
...
+          profileId,
+          isMultipane
+        )
+      )
+    } else {
+      lastLoadedFragment = PROFILE_EDIT_FRAGMENT
+      binding.administratorControlsMultipaneOptionsBackButton!!.visibility = View.VISIBLE
+      val fragment = ProfileEditFragment.newInstance(profileId, isMultipane)
+      activity.supportFragmentManager.beginTransaction()
+        .add(R.id.administrator_controls_fragment_multipane_placeholder, fragment)
```
Comment (yash10019coder) [inline app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt]: here I have implemnted so that ProfileEditFragment is pushed in the fragment back stack .

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt [hunk 2]
```diff
@@ -20,8 +24,9 @@ class AdministratorControlsActivityPresenter @Inject constructor(
   private lateinit var navigationDrawerFragment: NavigationDrawerFragment
   private var isMultipane = false
   private lateinit var lastLoadedFragment: String
-  private lateinit var binding: AdministratorControlsActivityBinding
+  private val ADMINISTRATOR_CONTROLS_BACKSTACK: String? = null // "ADMINISTRATOR_CONTROLS_BACKSTACK"
```
Comment (yash10019coder) [inline app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt]: tried to add a specific tag for the fragments which we are adding to back stack like ProfileListFragment and ProfileEditFragment so that we can push or pop fragments from the back stack instead of replacing fragments.

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt [hunk 3]
```diff
@@ -86,10 +93,48 @@ class AdministratorControlsActivityPresenter @Inject constructor(
...
+        ADMINISTRATOR_CONTROLS_BACKSTACK
+      ).commitNow()
+    }
+  }
+
+  val TAG = "tag"
+  fun handleOnBackPressed() {
+    var b = activity.supportFragmentManager.fragments.removeLast()
+    var c = activity.supportFragmentManager.fragments
+    Log.i(TAG, "handleOnBackPressed: $b\n$c")
```
Comment (yash10019coder) [inline app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt]: Logging the back stacks and also tired loggin the back stack count

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt [hunk 4]
```diff
@@ -86,10 +93,48 @@ class AdministratorControlsActivityPresenter @Inject constructor(
...
+  }
+
+  fun handleOnResume() {
+    activity.supportFragmentManager.addOnBackStackChangedListener {
+      Log.i(
+        TAG,
+        "handleOnResume:\n **** back stack changed\n *******"
```
Comment (yash10019coder) [inline app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt]: logging if there is any change in the back stack in the log all the fragments displayed are added to the back stack properly but this output never comes very strange.

**Review by yash10019coder — COMMENTED** [review]
Hi @BenHenning  I tried to implement a back stack management so that we can add fragments on the back stack and if back button is pushed then we can simply pop the fragment but this isn't working.
first I tired adding tags tags were properly displayed on the fragments list as I logged it but the backstack size was coming zero
this is the output below for my above run
`2021-12-10 14:48:14.134 9140-9140/org.oppia.android I/tag: handleOnBackPressed: ProfileEditFragment{e213891} (224a34e6-8455-4819-805b-bcd6b5be6ba7) id=0x7f090072 ADMINISTRATOR_CONTROLS_BACKSTACK}
    [NavigationDrawerFragment{48773f6} (fe0c3145-91f3-4383-bed9-d71069c05b9b) id=0x7f090070}, AdministratorControlsFragment{94583f7} (4de28ea0-b6e0-4576-b7c5-d7d3423e41a6) id=0x7f090073 ADMINISTRATOR_CONTROLS_BACKSTACK}, ProfileListFragment{8d8a264} (ba3d3f5a-c561-4f96-bb9f-355b9940abc3) id=0x7f090072 ADMINISTRATOR_CONTROLS_BACKSTACK}, SupportRequestManagerFragment{30fcccd} (9a4b0150-e5f1-4b4c-84dc-4e9555ffcd51) com.bumptech.glide.manager}{parent=null}, ProfileEditFragment{e213891} (224a34e6-8455-4819-805b-bcd6b5be6ba7) id=0x7f090072 ADMINISTRATOR_CONTROLS_BACKSTACK}]
    0`

**Comment by BenHenning** [comment]
> Hi @BenHenning I tried to implement a back stack management so that we can add fragments on the back stack and if back button is pushed then we can simply pop the fragment but this isn't working. first I tired adding tags tags were properly displayed on the fragments list as I logged it but the backstack size was coming zero this is the output below for my above run `2021-12-10 14:48:14.134 9140-9140/org.oppia.android I/tag: handleOnBackPressed: ProfileEditFragment{e213891} (224a34e6-8455-4819-805b-bcd6b5be6ba7) id=0x7f090072 ADMINISTRATOR_CONTROLS_BACKSTACK} [NavigationDrawerFragment{48773f6} (fe0c3145-91f3-4383-bed9-d71069c05b9b) id=0x7f090070}, AdministratorControlsFragment{94583f7} (4de28ea0-b6e0-4576-b7c5-d7d3423e41a6) id=0x7f090073 ADMINISTRATOR_CONTROLS_BACKSTACK}, ProfileListFragment{8d8a264} (ba3d3f5a-c561-4f96-bb9f-355b9940abc3) id=0x7f090072 ADMINISTRATOR_CONTROLS_BACKSTACK}, SupportRequestManagerFragment{30fcccd} (9a4b0150-e5f1-4b4c-84dc-4e9555ffcd51) com.bumptech.glide.manager}{parent=null}, ProfileEditFragment{e213891} (224a34e6-8455-4819-805b-bcd6b5be6ba7) id=0x7f090072 ADMINISTRATOR_CONTROLS_BACKSTACK}] 0`

@yash10019coder I can't be sure what's wrong without actually debugging it, but in principle I actually suggest trying to implement this without using the backstack, if possible. I generally recommend against using the fragment backstack because it can be difficult to get correct, and I've yet to run into a situation where it was actually needed. Generally, the alternatives end up being more predictable and easy to understand, too.

Can you provide a bit more context into what the exact user flow is that you're trying to model?

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt (hunk 2 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt]: this is working

File: app/src/main/java/org/oppia/android/app/settings/profile/ProfileListFragmentPresenter.kt [hunk 5]
```diff
@@ -65,13 +69,13 @@ class ProfileListFragmentPresenter @Inject constructor(
...
-          activity,
-          profile.id.internalId,
-          isMultipane
-        )
-      )
+      if (isMultipane) {
+        val profileEditListener = (activity as LoadProfileEditListener)
+        profileEditListener.loadProfileEdit(profile.id.internalId, profile.name)
+      } else {
+        val routeToProfileEditListener = (activity as RouteToProfileEditListener)
```
Comment (yash10019coder) [inline app/src/main/java/org/oppia/android/app/settings/profile/ProfileListFragmentPresenter.kt:72]: @BenHenning this line gives me a ClassCastException wheras the line 73 run completely fine. No idea here please help.

**Review by yash10019coder — COMMENTED** [review]
Hi @BenHenning now the ProfileEditFragment is opening correctly in tablet multipane but in mobile error occus left you a comment in the code PTAL thanks

File: app/src/main/java/org/oppia/android/app/settings/profile/ProfileListFragmentPresenter.kt (hunk 5 above)
Comment (BenHenning) [reply app/src/main/java/org/oppia/android/app/settings/profile/ProfileListFragmentPresenter.kt:72]: @yash10019coder have you tried debugging what the activity was at the time of the exception occurring? I'm wondering if this fragment is being hosted somewhere other than AdministratorControlsActivity (which I think it is), so other activities may also need to be wired up for routing to work correctly.

**Comment by BenHenning** [comment]
Hi. As of today, some main reviewers have taken time off for the next few weeks, so it may take a little while before we can look at this PR. We appreciate your patience while some of our team members recharge. We'll be fully returning on 4 January 2021.

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt [hunk 6]
```diff
@@ -0,0 +1,725 @@
...
+          targetViewId = R.id.auto_update_topic_switch
+        )
+      ).check(matches(Matchers.not(ViewMatchers.isChecked())))
+      onView(
+        atPositionOnView(
+          recyclerViewId = R.id.administrator_controls_list,
+          position = 2,
+          targetViewId = R.id.topic_update_on_wifi_constraint_layout
+        )
+      ).perform(click())
```
Comment (yash10019coder) [inline app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt]: @BenHenning @rt4914 this click isn't performed and therefore this test fails everything is correct but still it is not done.

**Review by yash10019coder — COMMENTED** [review]
@rt4914 PTAL thanks

File: app/src/main/java/org/oppia/android/app/settings/profile/ProfileListFragmentPresenter.kt (hunk 5 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/settings/profile/ProfileListFragmentPresenter.kt:72]: this is fixed .

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt (hunk 6 above)
Comment (yash10019coder) [reply app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt]: @rt4914 @BenHenning I have added a video below of a failing above test of the emulator.

https://user-images.githubusercontent.com/76404817/147857517-aecf3e22-c96b-4440-a332-5e2b3f7887ca.mp4

This is the code below for the above test case as we can see that we are not able to click the button it is in an infinite loop with a gap of 200ms in each iteration 
I don't know what is wrong with this code everything seems fine to me but still the outcome is very strange 
@rt4914 @BenHenning 
PTAL thanks
`
@Test
  fun testAdministratorControlsFragment_clickWifiContainer_configChange_wifiSwitchIsChecked() {
    launch<AdministratorControlsActivity>(
      createAdministratorControlsActivityIntent(
        profileId = internalProfileId
      )
    ).use {
      testCoroutineDispatchers.runCurrent()
      scrollToPosition(position = 2)
      onView(
        atPositionOnView(
          recyclerViewId = R.id.administrator_controls_list,
          position = 2,
          targetViewId = R.id.topic_update_on_wifi_switch
        )
      ).check(matches(not(isChecked())))
      onView(
        atPositionOnView(
          recyclerViewId = R.id.administrator_controls_list,
          position = 2,
          targetViewId = R.id.auto_update_topic_switch
        )
      ).check(matches(not(isChecked())))
      testCoroutineDispatchers.runCurrent()
      while (true) {
        onView(
          atPositionOnView(
            recyclerViewId = R.id.administrator_controls_list,
            position = 2,
            targetViewId = R.id.topic_update_on_wifi_constraint_layout
          )
        ).perform(click())
        Thread.sleep(200)
      }
      testCoroutineDispatchers.runCurrent()
      onView(isRoot()).perform(orientationLandscape())
      scrollToPosition(position = 2)
      onView(
        atPositionOnView(
          recyclerViewId = R.id.administrator_controls_list,
          position = 2,
          targetViewId = R.id.topic_update_on_wifi_switch
        )
      ).check(matches(isChecked()))
      onView(
        atPositionOnView(
          recyclerViewId = R.id.administrator_controls_list,
          position = 2,
          targetViewId = R.id.auto_update_topic_switch
        )
      ).check(matches(not(isChecked())))
      onView(isRoot()).perform(OrientationChangeAction.orientationPortrait())
      scrollToPosition(position = 2)
      onView(
        atPositionOnView(
          recyclerViewId = R.id.administrator_controls_list,
          position = 2,
          targetViewId = R.id.topic_update_on_wifi_switch
        )
      ).check(matches(isChecked()))
      onView(
        atPositionOnView(
          recyclerViewId = R.id.administrator_controls_list,
          position = 2,
          targetViewId = R.id.auto_update_topic_switch
        )
      ).check(matches(not(isChecked())))
    }
  }
`

Comment (yash10019coder) [reply app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt]: this is fixed

**Comment by yash10019coder** [comment]
Hi @BenHenning Sometimes CI gets stuck like in this case

**Review by yash10019coder — COMMENTED** [review]
Hi @rt4914 @BenHenning  PTAL thanks

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt [hunk 7]
```diff
@@ -86,6 +89,25 @@ class AdministratorControlsActivity :
...
 
+  override fun loadProfileEdit(profileId: Int, profileName: String) {
+    lastLoadedFragment = PROFILE_EDIT_FRAGMENT
+    administratorControlsActivityPresenter.setExtraControlsTitle(profileName)
+    administratorControlsActivityPresenter.loadProfileEdit(profileId)
+  }
+
+  companion object {
+
+    fun createAdministratorControlsActivityIntent(context: Context, profileId: Int?): Intent {
```
Comment (rt4914) [inline app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt]: Add Kdoc on public functions.

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt [hunk 8]
```diff
@@ -20,8 +22,9 @@ class AdministratorControlsActivityPresenter @Inject constructor(
   private lateinit var navigationDrawerFragment: NavigationDrawerFragment
   private var isMultipane = false
   private lateinit var lastLoadedFragment: String
-  private lateinit var binding: AdministratorControlsActivityBinding
+  private val ADMINISTRATOR_CONTROLS_BACKSTACK: String = "ADMINISTRATOR_CONTROLS_BACKSTACK"
```
Comment (rt4914) [inline app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt]: `  private const val ADMINISTRATOR_CONTROLS_BACKSTACK: String = "ADMINISTRATOR_CONTROLS_BACKSTACK"`

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt [hunk 9]
```diff
@@ -20,8 +22,9 @@ class AdministratorControlsActivityPresenter @Inject constructor(
...
 
+  private lateinit var binding: AdministratorControlsActivityBinding
   fun handleOnCreate(extraControlsTitle: String?, lastLoadedFragment: String) {
```
Comment (rt4914) [inline app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt]: Add a blank line above

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt [hunk 10]
```diff
@@ -86,10 +91,47 @@ class AdministratorControlsActivityPresenter @Inject constructor(
...
+  fun handleOnBackPressed() {
+    if (activity.supportFragmentManager.backStackEntryCount > 0)
+      activity.supportFragmentManager.popBackStackImmediate()
+  }
+
+  fun handleOnResume() {
+    activity.supportFragmentManager.addOnBackStackChangedListener {
+      if (activity.supportFragmentManager.backStackEntryCount == 0)
+        binding.administratorControlsMultipaneOptionsBackButton!!.visibility = View.GONE
+      val multipane_id = R.id.administrator_controls_fragment_multipane_placeholder
```
Comment (rt4914) [inline app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt]: `multipane_id ` -> `multipaneId `

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt [hunk 11]
```diff
@@ -86,10 +91,47 @@ class AdministratorControlsActivityPresenter @Inject constructor(
...
+      val multipane_fragment =
```
Comment (rt4914) [inline app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt]: `multipane_fragment ` -> `multipaneFragment `

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt [hunk 12]
```diff
@@ -86,10 +91,47 @@ class AdministratorControlsActivityPresenter @Inject constructor(
...
+        activity.supportFragmentManager.findFragmentById(multipane_id)
+      if (multipane_fragment is ProfileListFragment) {
+        setExtraControlsTitle("Edit profiles")
```
Comment (rt4914) [inline app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt]: This string should be defined in strings.xml file

File: app/src/main/java/org/oppia/android/app/help/HelpActivity.kt [hunk 13]
```diff
@@ -35,6 +35,9 @@ class HelpActivity :
   LoadThirdPartyDependencyListFragmentListener,
   LoadLicenseListFragmentListener,
   LoadLicenseTextViewerFragmentListener {
+  override fun onBackPressed() {
```
Comment (rt4914) [inline app/src/main/java/org/oppia/android/app/help/HelpActivity.kt]: Add blank line above

Comment (rt4914) [reply app/src/main/java/org/oppia/android/app/help/HelpActivity.kt]: Also I don't this function is needed as nothing is implemented here.

File: app/src/main/java/org/oppia/android/app/settings/profile/ProfileListFragmentPresenter.kt [hunk 14]
```diff
@@ -18,7 +19,7 @@ import javax.inject.Inject
 class ProfileListFragmentPresenter @Inject constructor(
   private val activity: AppCompatActivity,
   private val fragment: Fragment,
-  private val viewModelProvider: ViewModelProvider<ProfileListViewModel>
+  private val viewModelProvider: ViewModelProvider<ProfileListViewModel>,
```
Comment (rt4914) [inline app/src/main/java/org/oppia/android/app/settings/profile/ProfileListFragmentPresenter.kt]: Remove `,` at end

File: app/src/main/java/org/oppia/android/app/settings/profile/ProfileListActivity.kt [hunk 15]
```diff
@@ -23,6 +25,10 @@ class ProfileListActivity : InjectableAppCompatActivity() {
     return false
   }
 
+  override fun routeToProfileEditActivity(profileId: Int) {
+    startActivity(ProfileEditActivity.createProfileEditActivity(this, profileId, false))
```
Comment (rt4914) [inline app/src/main/java/org/oppia/android/app/settings/profile/ProfileListActivity.kt]: add inline comments so that it becomes more readable

**Review by rt4914 — CHANGES_REQUESTED** [review]
Nit changes suggested. Did initial pass only, functional is pending.

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt (hunk 7 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt]: shouldn't a kdoc test fail here?

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt [hunk 16]
```diff
@@ -86,10 +91,47 @@ class AdministratorControlsActivityPresenter @Inject constructor(
...
+    lastLoadedFragment = PROFILE_EDIT_FRAGMENT
+    binding.administratorControlsMultipaneOptionsBackButton!!.visibility = View.VISIBLE
+    val fragment = ProfileEditFragment.newInstance(profileId, isMultipane)
+    activity.supportFragmentManager.beginTransaction().add(
+      R.id.administrator_controls_fragment_multipane_placeholder,
+      fragment,
+      ADMINISTRATOR_CONTROLS_BACKSTACK
+    )
+      .addToBackStack(ADMINISTRATOR_CONTROLS_BACKSTACK)
+      .commit()
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt]: We should always use commitNow().

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt [hunk 17]
```diff
@@ -86,10 +91,47 @@ class AdministratorControlsActivityPresenter @Inject constructor(
...
+  }
+
+  fun handleOnBackPressed() {
+    if (activity.supportFragmentManager.backStackEntryCount > 0)
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt]: Needs braces per https://developer.android.com/kotlin/style-guide#braces.

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt [hunk 18]
```diff
@@ -86,10 +91,47 @@ class AdministratorControlsActivityPresenter @Inject constructor(
...
+      activity.supportFragmentManager.popBackStackImmediate()
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt]: Per my comment from earlier, what alternative approaches have you considered vs. using the backstack?

@rt4914 do you have any thoughts here?

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt [hunk 19]
```diff
@@ -86,10 +91,47 @@ class AdministratorControlsActivityPresenter @Inject constructor(
...
+  }
+
+  fun handleOnResume() {
+    activity.supportFragmentManager.addOnBackStackChangedListener {
+      if (activity.supportFragmentManager.backStackEntryCount == 0)
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt]: This feels potentially fragile if we change this UI in the future.

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @yash10019coder. The PR LGTM for codeowners, but I still have some concerns around the backstack mechanism. Also left one style comment--PTAL.

**Comment by yash10019coder** [comment]
@BenHenning @rt4914 Sometimes workflows are unable to run
image

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt (hunk 7 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt]: done

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt (hunk 8 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt]: unable to do this error comes it says that 
allowed only on top level declarations.

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt (hunk 9 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt]: done

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt (hunk 16 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt]: error comes if I use commitNow

2022-01-09 23:30:26.063 4994-4994/org.oppia.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.oppia.android, PID: 4994
    java.lang.IllegalStateException: This transaction is already being added to the back stack
        at androidx.fragment.app.FragmentTransaction.disallowAddToBackStack(FragmentTransaction.java:679)
        at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:296)
        at org.oppia.android.app.administratorcontrols.AdministratorControlsActivityPresenter.loadProfileEdit(AdministratorControlsActivityPresenter.kt:119)
        at org.oppia.android.app.administratorcontrols.AdministratorControlsActivity.loadProfileEdit(AdministratorControlsActivity.kt:104)
        at org.oppia.android.app.settings.profile.ProfileListFragmentPresenter$bindProfileView$1.onClick(ProfileListFragmentPresenter.kt:76)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt (hunk 17 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt]: done

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt (hunk 18 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt]: Other approaches are manually managing the back stack by storing which fragment is on Top which we usally do in oppia we have to store all the tags of the fragments.
But by using back stack we just have to check on the count of fragments which is better and we can add or pop the fragments from the backstack at ease
we can even store the state of the back stack like we do in instagram and with backstack we can also implement the back button much easier and a nicer way.

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt (hunk 19 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt]: Umm as we have one control in the Administrator controls so I done this. What can I improve on this

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt (hunk 12 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt]: done

File: app/src/main/java/org/oppia/android/app/help/HelpActivity.kt (hunk 13 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/help/HelpActivity.kt]: done

File: app/src/main/java/org/oppia/android/app/settings/profile/ProfileListActivity.kt (hunk 15 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/settings/profile/ProfileListActivity.kt]: I'm sorry I'm unable to understand this

File: app/src/main/java/org/oppia/android/app/settings/profile/ProfileListFragmentPresenter.kt (hunk 14 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/settings/profile/ProfileListFragmentPresenter.kt]: done

**Review by yash10019coder — COMMENTED** [review]
Hi @BenHenning @rt4914 made the requested changes PTAL 
Thanks

**Comment by BenHenning** [comment]
> @BenHenning @rt4914 Sometimes workflows are unable to run image

FYI that this isn't a failure, it's just indicating that Oppia has used up all of its free concurrent CI resources. The workflows will eventually run once runners free up.

> Other approaches are manually managing the back stack by storing which fragment is on Top which we usally do in oppia we have to store all the tags of the fragments. But by using back stack we just have to check on the count of fragments which is better and we can add or pop the fragments from the backstack at ease we can even store the state of the back stack like we do in instagram and with backstack we can also implement the back button much easier and a nicer way.

@yash10019coder the problem is that we don't necessarily know the order of the backstack, or what's currently on top without inspecting it. As UIs get more complex, the backstack can be a nightmare to manage because lots of different places may be trying to push/pop at the same time. https://jeroenmols.com/blog/2017/12/18/fragmentback/ covers once such example where seemingly simple backstack management code is subtly wrong.

I'm not opposed to the single-activity/fragment management approach to navigation, but we should then be leveraging Jetpack's navigation library to mange it for us so that we don't have to tweak the backstack manually. Given that we don't do that today, the main option left to us is to manually manage the fragments via tags & transactions (at least for now).

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt [hunk 20]
```diff
@@ -90,10 +102,50 @@ class AdministratorControlsActivityPresenter @Inject constructor(
...
+      fragment
+    ).commitNow()
+  }
+
+  /** Handles the back button according to the back stack of fragments. */
+  fun handleOnBackPressed() {
+    setBackButtonClickListener()
+  }
+
+  private fun setBackButtonClickListener() {
```
Comment (rt4914) [inline app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt:176]: This function is completely incorrect.
1. It is actually not handling the back button present on native android screen (outside of app and part of android os).
2. It is setting click listener to the `administratorControlsMultipaneOptionsBackButton` but is not considering what should be done if the back button is not visible.
3. If `AppVersionFragment` is visible, in that case there is no case which covers that part.

I do understand that you are stuck about how to close the fragments correctly but atleast to make it functional you can use `lastLoadedFragment` variable using which when back is pressed you can identify which fragment is visible currently and based on which you can define which fragment should be visible next.

**Review by rt4914 — CHANGES_REQUESTED** [review]
@yash10019coder Left one comment.

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt (hunk 20 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt:176]: done

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt [hunk 21]
```diff
@@ -0,0 +1,913 @@
...
+      testCoroutineDispatchers.runCurrent()
+      onView(atPositionOnView(R.id.profile_list_recycler_view, 0, R.id.profile_list_name)).check(
+        matches(withText("Admin"))
+      ).perform(click())
+      testCoroutineDispatchers.runCurrent()
+      onView(withId(R.id.extra_controls_title)).check(matches(withText("Admin")))
+      onView(withId(R.id.profile_edit_name)).check(matches(withText("Admin")))
+      onView(withId(R.id.administrator_controls_multipane_options_back_button)).perform(click())
+      testCoroutineDispatchers.runCurrent()
+      onView(atPositionOnView(R.id.profile_list_recycler_view, 1, R.id.profile_list_name)).check(
```
Comment (yash10019coder) [inline app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt]: this line is unable to execute therefore it is causing this test to fail.

**Review by yash10019coder — COMMENTED** [review]
Hi @rt4914 @BenHenning most of the things are done I have also added a comment and addressed all PTAL thanks.

**Comment by rt4914** [comment]
Will be able to review it tomorrow.

File: scripts/assets/kdoc_validity_exemptions.textproto [hunk 22]
```diff
@@ -1,11 +1,5 @@
 exempted_file_path: "app/src/main/java/org/oppia/android/app/activity/ActivityComponentImpl.kt"
-exempted_file_path: "app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt"
-exempted_file_path: "app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt"
-exempted_file_path: "app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragment.kt"
 exempted_file_path: "app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentPresenter.kt"
-exempted_file_path: "app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsViewModel.kt"
-exempted_file_path: "app/src/main/java/org/oppia/android/app/administratorcontrols/LoadAppVersionListener.kt"
-exempted_file_path: "app/src/main/java/org/oppia/android/app/administratorcontrols/LoadProfileListListener.kt"
```
Comment (BenHenning) [inline scripts/assets/kdoc_validity_exemptions.textproto:8]: It's nice to see these removed. :)

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt [hunk 23]
```diff
@@ -8,27 +8,45 @@ import org.oppia.android.app.activity.ActivityComponentImpl
...
   "AdministratorControlsActivity.selected_controls_title"
+
+/** Argument key for of selected profile for selected controls in [AdministratorControlsActivity]. */
+const val SELECTED_PROFILE_ID_SAVED_KEY =
+  "AdministratorControlsActivity.selected_profile_id"
+
+/** Argument key for last loaded fragment in [AdministratorControlsActivity]. */
 const val LAST_LOADED_FRAGMENT_EXTRA_KEY = "AdministratorControlsActivity.last_loaded_fragment"
+
+/** Argument key for [ProfileListFragment]. */
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt]: This doesn't really describe how this value should be used. Could you add some details to that effect? Ditto for the others below.

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt [hunk 24]
```diff
@@ -44,7 +62,13 @@ class AdministratorControlsActivity :
       // TODO(#661): Change the default fragment in the right hand side to be EditAccount fragment in the case of multipane controls.
       PROFILE_LIST_FRAGMENT
     }
-    administratorControlsActivityPresenter.handleOnCreate(extraControlsTitle, lastLoadedFragment)
+    val selectedProfileId =
+      savedInstanceState?.getInt(SELECTED_PROFILE_ID_SAVED_KEY)
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt]: Nit: can this fit on one line?

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt [hunk 25]
```diff
@@ -56,16 +80,16 @@ class AdministratorControlsActivity :
...
+  override fun onBackPressed() {
+    val fragment =
+      supportFragmentManager.findFragmentById(
+        R.id.administrator_controls_fragment_multipane_placeholder
+      )
 
-    fun getIntentKey(): String {
-      return NAVIGATION_PROFILE_ID_ARGUMENT_KEY
-    }
+    if (fragment is ProfileEditFragment)
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt]: This needs braces or reformatting per https://developer.android.com/kotlin/style-guide#braces.

Also, this would probably benefit from a line comment explaining this logic since it's not obvious at a glance why it's correct/needed.

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt [hunk 26]
```diff
@@ -86,6 +110,26 @@ class AdministratorControlsActivity :
...
+
+  companion object {
+    /** Returns an [Intent] to start this activity. */
+    fun createAdministratorControlsActivityIntent(context: Context, profileId: Int?): Intent {
+      val intent = Intent(context, AdministratorControlsActivity::class.java)
+      intent.putExtra(NAVIGATION_PROFILE_ID_ARGUMENT_KEY, profileId)
+      return intent
+    }
+
+    /** Returns an Argument key for internal ProfileId of User. */
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt]:
```suggestion
    /** Returns the argument key used to specify the user's internal profile ID. */
```

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt [hunk 27]
```diff
@@ -72,33 +94,89 @@ class AdministratorControlsActivityPresenter @Inject constructor(
       ) as AdministratorControlsFragment?
   }
 
+  /**
+   * Loads the profile list fragment as the [AdministratorControlsActivity] is
+   * started in multipane tablet mode.
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt]: Please ensure this fits as much space in the 100 character limit as it can.

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt [hunk 28]
```diff
@@ -72,33 +94,89 @@ class AdministratorControlsActivityPresenter @Inject constructor(
...
+  }
+
+  private fun backButtonLogic() {
+    val currentFragment =
+      activity.supportFragmentManager.findFragmentById(
+        R.id.administrator_controls_fragment_multipane_placeholder
+      )
+    if (currentFragment != null) {
+      when (currentFragment) {
+        is ProfileEditFragment -> {
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt]: This can just be an if-check, right?

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsViewModel.kt [hunk 29]
```diff
@@ -44,6 +46,7 @@ class AdministratorControlsViewModel @Inject constructor(
     )
   }
 
+  /** This partially stores the list of the controls in the [AdministratorControlsFragment] */
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsViewModel.kt]: Nit: end with punctuation.

Also, what does 'partially' mean?

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsViewModel.kt [hunk 30]
```diff
@@ -35,6 +35,8 @@ class AdministratorControlsViewModel @Inject constructor(
   private val loadProfileListListener = activity as LoadProfileListListener
   private val showLogoutDialogListener = activity as ShowLogoutDialogListener
   private lateinit var userProfileId: ProfileId
+
+  /** Sets the Index for the currently selected fragment. */
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsViewModel.kt]: ``index`` not ``Index``. Ditto elsewhere (please only capitalize types or proper nouns).

File: app/src/main/java/org/oppia/android/app/administratorcontrols/LoadProfileEditListener.kt [hunk 31]
```diff
@@ -0,0 +1,7 @@
+package org.oppia.android.app.administratorcontrols
+
+/** Listener for when an activity should load [ProfileEditFragment]. */
+interface LoadProfileEditListener {
+  /** This method is called when the fragment of [ProfileEditFragment] is inflated. */
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/administratorcontrols/LoadProfileEditListener.kt]: Method KDocs should describe what the method does, not when it's called (since that's tied just to the current implementation, and implementations change--it's generally more useful to describe what what and how of a method in its documentation so that people understand when and why to call it).

File: app/src/main/java/org/oppia/android/app/settings/profile/ProfileEditFragmentPresenter.kt [hunk 32]
```diff
@@ -76,7 +75,8 @@ class ProfileEditFragmentPresenter @Inject constructor(
     profileEditViewModel.profile.observe(
       fragment,
       Observer {
-        activity.title = it.name
+        if (activity is ProfileEditActivity)
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/settings/profile/ProfileEditFragmentPresenter.kt]: Ditto here (for braces). Also, could we use isMultipane as a proxy for this, instead? That gives information about how the fragment is hosted.

File: app/src/main/java/org/oppia/android/app/settings/profile/ProfileListActivity.kt (hunk 15 above)
Comment (BenHenning) [reply app/src/main/java/org/oppia/android/app/settings/profile/ProfileListActivity.kt]: I think Rajat might be referring to using either argument comments or named arguments (the latter being preferred if it's a Kotlin method), i.e.

``ProfileEditActivity.createProfileEditActivity(arg1 = this, profileId, arg2 = false)``

**Review by BenHenning — COMMENTED** [review]
Thanks @yash10019coder. File changes per my codeowners generally LGTM, but I had various style feedback--PTAL.

Note that I didn't look at the tests closely.

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt (hunk 21 above)
Comment (BenHenning) [reply app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt]: Can you be more specific on what 'unable to execute' means? What specifically are you observing?

Comment (yash10019coder) [reply app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt]: like at line 683 a click action is performed but it is actually not happening so the test fails as this action is required.

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt (hunk 23 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt]: done

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt (hunk 24 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt]: done

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt (hunk 25 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt]: done

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt (hunk 26 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt]: done

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt (hunk 27 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt]: done

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt (hunk 28 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt]: when I'm going to add more fragments like ProfileRenameFragment and ProfileResetPinFragment then we are going to need when so I'm using it.

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsViewModel.kt (hunk 30 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsViewModel.kt]: done

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsViewModel.kt (hunk 29 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsViewModel.kt]: done changed partially to temporarily

File: app/src/main/java/org/oppia/android/app/administratorcontrols/LoadProfileEditListener.kt (hunk 31 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/LoadProfileEditListener.kt]: done

File: app/src/main/java/org/oppia/android/app/settings/profile/ProfileEditFragmentPresenter.kt (hunk 32 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/settings/profile/ProfileEditFragmentPresenter.kt]: done

File: app/src/main/java/org/oppia/android/app/settings/profile/ProfileListActivity.kt (hunk 15 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/settings/profile/ProfileListActivity.kt]: done

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt (hunk 21 above)
Comment (yash10019coder) [reply app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt]: as this click is very dependent as it loads the ProfielEditFragment so the checks in furthur lines fails and therefore the test fails

File: scripts/assets/kdoc_validity_exemptions.textproto (hunk 22 above)
Comment (yash10019coder) [reply scripts/assets/kdoc_validity_exemptions.textproto:8]: :+1:

**Review by yash10019coder — COMMENTED** [review]
Hi @BenHenning mentioned all the comments PTAL thanks

**Comment by yash10019coder** [comment]
Also here's the failed test gist [link](https://gist.github.com/3c5886e62322959b3473c01b914f9596)

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt [hunk 33]
```diff
@@ -85,11 +84,17 @@ class AdministratorControlsActivity :
...
         R.id.administrator_controls_fragment_multipane_placeholder
       )
-
-    if (fragment is ProfileEditFragment)
+    /**
+     * when fragment is [ProfileEditFragment] then we should switch
+     * fragment to [ProfileListFragment] or else
+     * we just end the activity as then we are
+     * having [ProfileListFragment] on top.
+     */
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt]: This should either be a block comment (e.g. ``/* */``) or single-line comments (e.g. ``/``), not a KDoc.

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt [hunk 34]
```diff
@@ -26,13 +26,13 @@ const val SELECTED_PROFILE_ID_SAVED_KEY =
 /** Argument key for last loaded fragment in [AdministratorControlsActivity]. */
 const val LAST_LOADED_FRAGMENT_EXTRA_KEY = "AdministratorControlsActivity.last_loaded_fragment"
 
-/** Argument key for [ProfileListFragment]. */
+/** Argument key for identifying [ProfileListFragment] in the backstack. */
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt]: Could we just say it's used to identify the fragment?

Also, should this be called a TAG per convention? And, is this the correct constant style for such constants? /cc @rt4914 since he'd be more familiar with these conventions.

Ditto for the others.

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt [hunk 35]
```diff
@@ -94,10 +94,7 @@ class AdministratorControlsActivityPresenter @Inject constructor(
       ) as AdministratorControlsFragment?
   }
 
-  /**
-   * Loads the profile list fragment as the [AdministratorControlsActivity] is
-   * started in multipane tablet mode.
-   */
+  /** Loads the profile list fragment as the [AdministratorControlsActivity] is started in multipane tablet mode. */
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt:114]: This is going in the other direction. :) KDocs need to fit within the 100 character line limit, but they should take up as much space within that limit before wrapping.

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsViewModel.kt [hunk 36]
```diff
@@ -36,7 +36,7 @@ class AdministratorControlsViewModel @Inject constructor(
   private val showLogoutDialogListener = activity as ShowLogoutDialogListener
   private lateinit var userProfileId: ProfileId
 
-  /** Sets the Index for the currently selected fragment. */
+  /** Sets index for the currently selected fragment. */
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsViewModel.kt]:
```suggestion
  /** Sets the index for the currently selected fragment. */
```

That being said, this is still a bit confusing. What exactly is a fragment index?

File: app/src/main/java/org/oppia/android/app/administratorcontrols/LoadProfileEditListener.kt [hunk 37]
```diff
@@ -2,6 +2,6 @@ package org.oppia.android.app.administratorcontrols
 
 /** Listener for when an activity should load [ProfileEditFragment]. */
 interface LoadProfileEditListener {
-  /** This method is called when the fragment of [ProfileEditFragment] is inflated. */
+  /** Used for inflating [ProfileEditFragment] in a multipane fragment in tablet mode. */
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/administratorcontrols/LoadProfileEditListener.kt]:
```suggestion
  /** Inflates [ProfileEditFragment] as part of a tablet mode a multipane fragment. */
```

We should describe what the method does, not when it's called.

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt (hunk 28 above)
Comment (BenHenning) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt]: Is that going to be happening in a follow-up PR, or is it an eventuality that could happen?

Also, what about the 'else' case--what should the presenter do in those cases? If shouldn't happen, consider adding a warning log line to help with debugging if it leads to a broken user experience.

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt (hunk 33 above)
Comment (BenHenning) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt]: Also, we can't use ``[]`` for line comments (they're only valid for KDocs).

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt (hunk 19 above)
Comment (BenHenning) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt]: No longer relevant since you moved away from the backstack approach (though I've left a similar comment for the most recent implementation regarding asking what we should do if an unexpected fragment state is encountered).

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt (hunk 18 above)
Comment (BenHenning) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt]: Per the other discussion, the implementation was updated to no longer commit to the backstack manually.

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt (hunk 16 above)
Comment (BenHenning) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt]: No longer applies since we're now using the fragment approach used elsewhere in the app.

**Review by BenHenning — COMMENTED** [review]
Thanks @yash10019coder. Took another pass--PTAL.

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt [hunk 38]
```diff
@@ -115,6 +158,583 @@ class AdministratorControlsFragmentTest {
...
+        matches(withText("Admin"))
+      ).perform(click())
+      testCoroutineDispatchers.runCurrent()
+      onView(withId(R.id.extra_controls_title)).check(matches(withText("Admin")))
+      onView(withId(R.id.profile_edit_name)).check(matches(withText("Admin")))
+      onView(withId(R.id.administrator_controls_multipane_options_back_button)).perform(click())
+      testCoroutineDispatchers.runCurrent()
+      onView(atPositionOnView(R.id.profile_list_recycler_view, 1, R.id.profile_list_name))
+        .check(matches(withText("Ben")))
+      onView(atPositionOnView(R.id.profile_list_recycler_view, 1, R.id.profile_list_name))
```
Comment (yash10019coder) [inline app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt]: i have broken down the implementation

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt [hunk 39]
```diff
@@ -115,6 +158,583 @@ class AdministratorControlsFragmentTest {
...
+        matches(withText("Admin"))
+      ).perform(click())
+      testCoroutineDispatchers.runCurrent()
+      onView(withId(R.id.extra_controls_title)).check(matches(withText("Admin")))
+      onView(withId(R.id.profile_edit_name)).check(matches(withText("Admin")))
+      pressBack()
+      testCoroutineDispatchers.runCurrent()
+      onView(atPositionOnView(R.id.profile_list_recycler_view, 1, R.id.profile_list_name))
+        .check(matches(withText("Ben")))
+      onView(atPositionOnView(R.id.profile_list_recycler_view, 1, R.id.profile_list_name))
```
Comment (yash10019coder) [inline app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt]: same goes here

**Review by yash10019coder — COMMENTED** [review]
Hi @BenHenning  @rt4914 I have broken down the implementaion but it still seems to be not working here's the gist [link](https://gist.github.com/7ae887ee432779ddbc85f6e4fecc1147) for the error PTAL thanks

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt (hunk 34 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt]: done

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt (hunk 33 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt]: done

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt (hunk 35 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt:114]: trimmed it

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt (hunk 28 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt]: Yes there will be two follow up PR's after this PR 
removed the if as I think it is not required there will always be a fragment on the screen

**Review by yash10019coder — COMMENTED** [review]
Hi @BenHenning mentioned all the comments and made some nit fixes PTAL.

**Comment by rt4914** [comment]
@yash10019coder As per our discussion there is fragment overlapping because of which accessibility checks and test cases are failing.

**Comment by yash10019coder** [comment]
@rt4914 replacing the fragment transactions from add to replace worked now tests are passing yay :smiley:

**Comment by BenHenning** [comment]
(FYI since my comments are mostly surface-level, I'm going to deprioritize my review of this for until early next week--please let me know if this will cause any issues, i.e. if all other approvals are completed before then).

**Comment by yash10019coder** [comment]
Hi @rt4914 added all the workflows and also updated the tests PTAL thanks

File: app/src/main/java/org/oppia/android/app/settings/profile/ProfileEditFragmentPresenter.kt [hunk 40]
```diff
@@ -26,17 +26,16 @@ class ProfileEditFragmentPresenter @Inject constructor(
   private val activity: AppCompatActivity,
   private val fragment: Fragment,
   private val oppiaLogger: OppiaLogger,
+  private val profileEditViewModel: ProfileEditViewModel,
   private val profileManagementController: ProfileManagementController
 ) {
 
-  @Inject
-  lateinit var profileEditViewModel: ProfileEditViewModel
```
Comment (rt4914) [inline app/src/main/java/org/oppia/android/app/settings/profile/ProfileEditFragmentPresenter.kt:34]: Why is this change required?

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt [hunk 41]
```diff
@@ -79,29 +111,40 @@ import org.oppia.android.util.parser.html.HtmlParserEntityTypeModule
...
   application = AdministratorControlsFragmentTest.TestApplication::class,
   qualifiers = "port-xxhdpi"
 )
 class AdministratorControlsFragmentTest {
+
   @get:Rule
   val initializeDefaultLocaleRule = InitializeDefaultLocaleRule()
 
+  @get:Rule
+  val accessibilityTestRule = OppiaTestRule()
```
Comment (rt4914) [inline app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt]: `accessibilityTestRule ` to `oppiaTestRule`

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt [hunk 42]
```diff
@@ -115,6 +158,611 @@ class AdministratorControlsFragmentTest {
...
+        )
+      ).check(matches(isChecked()))
+      onView(
+        atPositionOnView(
+          recyclerViewId = R.id.administrator_controls_list,
+          position = 2,
+          targetViewId = R.id.auto_update_topic_switch
+        )
+      ).check(matches(not(isChecked())))
+      onView(isRoot()).perform(OrientationChangeAction.orientationPortrait())
```
Comment (rt4914) [inline app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt]: Use Direct Import
`onView(isRoot()).perform(orientationPortrait())`

**Review by rt4914 — CHANGES_REQUESTED** [review]
@yash10019coder Looks really good.

Couple of suggestions:
1. If you click on `Profile Deletion` and then rotate the screen the dialog disappears. This should be fixed and a test case should be added too.
2. Run all tests on Espresso to demonstrate that all tests pass on AccessibilityChecks too. If any test case fails, you can use `DisableAccessibilityChecks` as annotation for that particular test case.

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt [hunk 43]
```diff
@@ -94,12 +96,15 @@ class AdministratorControlsActivityPresenter @Inject constructor(
       ) as AdministratorControlsFragment?
   }
 
-  /** Loads the profile list fragment as the [AdministratorControlsActivity] is started in multipane tablet mode. */
+  /**
+   * Loads the profile list fragment as the [AdministratorControlsActivity]
+   * is started in multipane tablet mode.
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt]: This should be wrapped at 100 characters.

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt (hunk 38 above)
Comment (BenHenning) [reply app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt]: Now this test is verifying multiple behaviors--you should split it up such that each test has just one arrange/act/assert block (in that order). Multiple act/assert blocks in a single test indicates more than one behavior is being tested, and we should aim to verify only a single behavior for each test method.

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt [hunk 44]
```diff
@@ -727,12 +729,40 @@ class AdministratorControlsFragmentTest {
...
+      testCoroutineDispatchers.runCurrent()
+      onView(atPositionOnView(R.id.profile_list_recycler_view, 1, R.id.profile_list_name)).check(
+        matches(withText("Ben"))
+      ).perform(click())
+      onView(isRoot()).perform(orientationLandscape())
+      testCoroutineDispatchers.runCurrent()
+      onView(withId(R.id.profile_edit_name)).check(matches(withText("Ben")))
+      onView(withId(R.id.profile_edit_allow_download_heading)).check(matches((isDisplayed())))
+      onView(withId(R.id.profile_edit_allow_download_sub)).check(matches((isDisplayed())))
+      onView(withId(R.id.profile_edit_allow_download_switch)).check(matches((isDisplayed())))
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt]: Here & elsewhere: please remove the redundant parentheses.

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt [hunk 45]
```diff
@@ -84,11 +85,11 @@ class AdministratorControlsActivity :
...
-     * when fragment is [ProfileEditFragment] then we should switch
-     * fragment to [ProfileListFragment] or else
-     * we just end the activity as then we are
-     * having [ProfileListFragment] on top.
+    /*
+     when fragment is ProfileEditFragment then we should switch
+     fragment to ProfileListFragment or else
+     we just end the activity as then we are
+     having ProfileListFragment on top.
      */
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt]: You should keep the '*' at the start of the lines, and you should wrap them at the 100 character mark.

File: app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditFragmentTest.kt [hunk 46]
```diff
@@ -0,0 +1,591 @@
...
+    ).use {
+      testCoroutineDispatchers.runCurrent()
+      onView(withId(R.id.profile_edit_allow_download_container)).check(matches(isDisplayed()))
+    }
+  }
+
+  @Test
+  fun testProfileEdit_startWithUserDoesNotHaveDownloadAccess_switchContainerIsNotDisplayed() {
+    launch<ProfileEditActivity>(
+      ProfileEditActivity.createProfileEditActivity(
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditFragmentTest.kt]: If this suite aims to test ProfileEditFragment, it ought to test the fragment in isolation by wrapping it in a test activity (similar to how we do this for other fragments).

File: app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditFragmentTest.kt [hunk 47]
```diff
@@ -0,0 +1,591 @@
...
+import org.oppia.android.util.parser.image.ImageParsingModule
+import org.robolectric.annotation.Config
+import org.robolectric.annotation.LooperMode
+import javax.inject.Inject
+import javax.inject.Singleton
+
+@RunWith(AndroidJUnit4::class)
+@LooperMode(LooperMode.Mode.PAUSED)
+@Config(application = ProfileEditFragmentTest.TestApplication::class, qualifiers = "port-xxhdpi")
+class ProfileEditFragmentTest {
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditFragmentTest.kt:106]: Does this suite cover all of the behaviors for the tests you removed from AdministratorControlsActivityTest?

**Review by BenHenning — COMMENTED** [review]
Thanks @yash10019coder. Took another pass--PTAL.

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt (hunk 43 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt]: done

File: app/src/main/java/org/oppia/android/app/settings/profile/ProfileEditFragmentPresenter.kt (hunk 40 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/settings/profile/ProfileEditFragmentPresenter.kt:34]: I thought to include the dependency at compile time rather than runtime shall I revert this?

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt (hunk 42 above)
Comment (yash10019coder) [reply app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt]: done

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt (hunk 44 above)
Comment (yash10019coder) [reply app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt]: done

File: app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditFragmentTest.kt (hunk 47 above)
Comment (yash10019coder) [reply app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditFragmentTest.kt:106]: Actually I just shifted the tests related to fragment in AdministratorControlsFragment Test and same goes here.

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt (hunk 41 above)
Comment (yash10019coder) [reply app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt]: done

File: app/src/main/java/org/oppia/android/app/settings/profile/ProfileEditFragmentPresenter.kt (hunk 40 above)
Comment (rt4914) [reply app/src/main/java/org/oppia/android/app/settings/profile/ProfileEditFragmentPresenter.kt:34]: Yes please revert this here. If you think compile time is better suggest doing it in separate PR with explanation.

Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/settings/profile/ProfileEditFragmentPresenter.kt:34]: reverted it

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt (hunk 45 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt]: done

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt (hunk 38 above)
Comment (yash10019coder) [reply app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt]: actuallly these tests are big as I am navigating with the profiles and buttons I am not directly able to inflate ProfileEditFragment and then see things they are very closely coupled.

**Review by yash10019coder — COMMENTED** [review]
Hi @rt4914 mentioned all the comments PTAL thanks

**Comment by yash10019coder** [comment]
@rt4914 gradle roboelectric test is flaky so please ignore it , it happens often

**Comment by rt4914** [comment]
> @rt4914 gradle roboelectric test is flaky so please ignore it , it happens often

@yash10019coder Just file an issue for that so that either we can ignore it for now or fix it.

Also please keep the `Assignees` section up-to-date, so that we can know whether to review this PR or not.

**Comment by BenHenning** [comment]
Sorry, there were more changes than I expected in the latest version. I'll need to take a look tomorrow.

**Comment by BenHenning** [comment]
Will follow up on this tomorrow--sorry for the delay.

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt [hunk 48]
```diff
@@ -85,12 +94,8 @@ class AdministratorControlsActivity :
...
         R.id.administrator_controls_fragment_multipane_placeholder
       )
-    /*
-     when fragment is ProfileEditFragment then we should switch
-     fragment to ProfileListFragment or else
-     we just end the activity as then we are
-     having ProfileListFragment on top.
-     */
+    /* when fragment is ProfileEditFragment then we should switch fragment to ProfileListFragment or else
+       we just end the activity as then we are having ProfileListFragment on top. */
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt]: I'm having a slightly difficulty in understanding exactly what this is saying--can you please rephrase it to make it a bit clearer?

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt (hunk 7 above)
Comment (BenHenning) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt]: FYI that this class is currently allowlisted to not contain KDocs which is why the error didn't occur--we'll be working on removing all of those exceptions once we have KDoc formatting enforcement added to the CI checks.

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt [hunk 49]
```diff
@@ -64,6 +68,13 @@ class AdministratorControlsActivityPresenter @Inject constructor(
               profileId = it,
               profileName = extraControlsTitle
             )
+            if (isProfileDeletionDialogVisible == true && it != 0) {
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt]: Please name ``it`` to help provide context. That being said, it's a bit hacky to be checking for 0--we shouldn't be making assumptions about the internal profile ID. Why is this check necessary?

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt [hunk 50]
```diff
@@ -64,6 +68,13 @@ class AdministratorControlsActivityPresenter @Inject constructor(
...
+              val fragment = activity.supportFragmentManager.findFragmentById(
+                R.id.administrator_controls_fragment_multipane_placeholder
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt:75]: Prefer saving the fragment in a val above and using it here rather than needing to find the fragment via the manager.

File: app/src/main/java/org/oppia/android/app/settings/profile/LoadProfileEditDeletionDialogListener.kt [hunk 51]
```diff
@@ -0,0 +1,7 @@
+package org.oppia.android.app.settings.profile
+
+/** Listener for when the activity should inflate [ProfileEditDeletionDialogFragment]. */
+interface LoadProfileEditDeletionDialogListener {
+  /** Inflates [ProfileEditDeletionDialogFragment] for the configuration changes and saves the state of the dialog. */
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/settings/profile/LoadProfileEditDeletionDialogListener.kt]: What does 'for the configuration changes' mean? Could you please clarify this point in the doc comment?

File: app/src/main/java/org/oppia/android/app/settings/profile/ProfileEditFragmentPresenter.kt [hunk 52]
```diff
@@ -142,4 +150,9 @@ class ProfileEditFragmentPresenter @Inject constructor(
         }
       )
   }
+
+  /** This loads the dialog whenever requested by the listerner in [AdministratorControlsActivity]. */
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/settings/profile/ProfileEditFragmentPresenter.kt]:
```suggestion
  /** This loads the dialog whenever requested by the listener in [AdministratorControlsActivity]. */
```

File: app/src/main/java/org/oppia/android/app/settings/profile/ProfileEditFragmentPresenter.kt [hunk 53]
```diff
@@ -26,10 +27,14 @@ class ProfileEditFragmentPresenter @Inject constructor(
...
   private val fragment: Fragment,
   private val oppiaLogger: OppiaLogger,
-  private val profileEditViewModel: ProfileEditViewModel,
   private val profileManagementController: ProfileManagementController
 ) {
 
+  @Inject
+  lateinit var profileEditViewModel: ProfileEditViewModel
+
+  private var isMultipane: Boolean? = null
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/settings/profile/ProfileEditFragmentPresenter.kt:37]: Alternatively, the default could just be false for this, right? That might help simplify the pattern to avoid the nullable cases. Ditto elsewhere in the PR.

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt [hunk 54]
```diff
@@ -1,34 +1,51 @@
...
+  private val resourceHandler: AppLanguageResourceHandler
 ) {
   private lateinit var navigationDrawerFragment: NavigationDrawerFragment
   private var isMultipane = false
-  private lateinit var lastLoadedFragment: String
   private lateinit var binding: AdministratorControlsActivityBinding
 
-  fun handleOnCreate(extraControlsTitle: String?, lastLoadedFragment: String) {
+  private lateinit var lastLoadedFragment: String
+  private var selectedProfileId: Int? = null
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt]: You could default this to -1 since that's never a valid profile ID.

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt [hunk 55]
```diff
@@ -72,33 +107,94 @@ class AdministratorControlsActivityPresenter @Inject constructor(
...
+    ).commitNow()
+  }
+
+  /** Sets whether the user has clicked on the profile deletion [ProfileEditDeletionDialogFragment] in tablet mode. */
+  fun loadProfileDeletionDialog(profileDeletionDialogVisible: Boolean) {
+    isProfileDeletionDialogVisible = profileDeletionDialogVisible
+  }
+
+  private fun setMultipaneBackButtonVisibility(visibility: Int) {
+    binding.administratorControlsMultipaneOptionsBackButton!!.visibility = visibility
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt]: Could we use ``?.`` instead of ``!!``?

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt [hunk 56]
```diff
@@ -72,33 +107,94 @@ class AdministratorControlsActivityPresenter @Inject constructor(
...
+    }
+  }
+
+  private fun setBackButtonClickListener() {
+    binding.administratorControlsMultipaneOptionsBackButton!!.setOnClickListener {
+      backButtonLogic()
+    }
+  }
+
+  private fun backButtonLogic() {
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt]: Please name this as a verb phrase to describe what it's actually doing (rather than what it contains).

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt [hunk 57]
```diff
@@ -72,33 +107,94 @@ class AdministratorControlsActivityPresenter @Inject constructor(
...
+    val currentFragment =
+      activity.supportFragmentManager.findFragmentById(
+        R.id.administrator_controls_fragment_multipane_placeholder
+      )
+    when (currentFragment) {
+      is ProfileEditFragment -> {
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt:188]: Perhaps use an ``if``, instead? I'm not sure there's a benefit to ``when`` here when there's 1 case and no guarantee for it being comprehensive.

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt [hunk 58]
```diff
@@ -116,49 +156,776 @@ class AdministratorControlsFragmentTest {
   }
 
   @Test
-  fun testAdministratorControlsFragment_clickEditProfile_checkSendingTheCorrectIntent() {
+  fun testAdministratorControlsFragment_generalAndProfileManagementIsDisplayed() {
+    launch<AdministratorControlsActivity>(
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt]: Any tests that are testing routing should be part of the activity's test suite (since they need to verify the activity is set up correctly), but all other tests should stay here and utilize a test activity rather than use AdministratorControlsActivity (since it should be tested in isolation). There are a bunch of examples to reference to reference for how to do this.

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt [hunk 59]
```diff
@@ -116,49 +156,776 @@ class AdministratorControlsFragmentTest {
...
+      verifyTextOnAdministratorListItemAtPosition(
+        itemPosition = 4,
+        targetViewId = R.id.log_out_text_view,
+        stringIdToMatch = R.string.administrator_controls_log_out
+      )
+    }
+  }
+
+  @Test
+  fun testAdministratorControlsFragment_wifiSwitchIsUncheck_autoUpdateSwitchIsUncheck() {
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt]:
```suggestion
  fun testAdministratorControlsFragment_wifiSwitchIsUnchecked_autoUpdateSwitchIsUnchecked() {
```

Ditto elsewhere (where relevant).

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt [hunk 60]
```diff
@@ -116,49 +156,776 @@ class AdministratorControlsFragmentTest {
...
+          recyclerViewId = R.id.administrator_controls_list,
+          position = 2,
+          targetViewId = R.id.auto_update_topic_switch
+        )
+      ).check(matches(not(isChecked())))
+    }
+  }
+
+  @Test
+  fun testAdministratorControlsFragment_clickWifiContainer_configChange_wifiSwitchIsChecked() {
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt]: This test is doing a lot. I suggest splitting it up such that each test corresponds to a single behavior. A test should have 1 of each arrange, act, and assert blocks in that order. If you have multiple assertion blocks that usually indicates more than one behavior is being tested, and it's beneficial to keep tests behavior-specific.

Further, it may help shorten the tests and make them more readable by introducing helpers. I suggest looking at StateFragmentTest for inspiration on how some of the longer onView-type blocks can be generalized into nicer-to-use and much shorter test helpers that also help to improve test readability.

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt [hunk 61]
```diff
@@ -116,49 +156,776 @@ class AdministratorControlsFragmentTest {
...
+          position = 2,
+          targetViewId = R.id.auto_update_topic_switch
+        )
+      ).check(matches(isChecked()))
     }
   }
 
   @Test
-  fun testAdministratorControlsFragment_clickAppVersion_checkSendingTheCorrectIntent() {
+  fun testAdministratorControlsFragment_wifiSwitchIsNonClickable() {
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt]: This name is missing whatever condition is necessary for the switch to not be clickable--please update. Ditto for the next test.

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt [hunk 62]
```diff
@@ -116,49 +156,776 @@ class AdministratorControlsFragmentTest {
...
+          recyclerViewId = R.id.administrator_controls_list,
+          position = 2,
+          targetViewId = R.id.auto_update_topic_switch
+        )
+      ).check(matches(not(isClickable())))
+    }
+  }
+
+  @Test
+  fun testAdministratorControlsFragment_clickLogoutButton_logoutDialogIsDisplayed() {
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt]: Here & elsewhere: for these cases we should be testing that the callback is called from the fragment's perspective, and in the activity test suite we can verify that the correct thing actually happens (i.e. that the dialog opens).

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt [hunk 63]
```diff
@@ -116,49 +156,776 @@ class AdministratorControlsFragmentTest {
...
+      onView(withId(R.id.administrator_controls_linear_layout)).perform(nestedScrollTo())
+        .perform(click())
+      onView(withText(context.getString(R.string.administrator_controls_edit_account)))
+        .check(matches(isDisplayed()))
+    }
+  }
+
+  @Test
+  @Config(qualifiers = "sw600dp")
+  fun testAdministratorControls_defaultTabletConfig_multipaneBackButtonGone() {
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt]:
```suggestion
  fun testAdministratorControls_defaultTabletConfig_multiPaneBackButtonGone() {
```

Ditto elsewhere.

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt (hunk 38 above)
Comment (BenHenning) [reply app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt]: I'm not sure that I'm understanding what the issue is. I left a bit more detailed comment on this suggestion above, but the main thing we should avoid is performing multiple assertions that are unrelated since that indicates multiple behaviors being tested.

The tests themselves can be shortened by leveraging helper methods to consolidate common setup to simple-to-use methods.

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt [hunk 64]
```diff
@@ -116,49 +156,776 @@ class AdministratorControlsFragmentTest {
...
+      scrollToPosition(position = 4)
+      onView(withId(R.id.log_out_text_view)).perform(click())
+      verifyTextInDialog(textInDialogId = R.string.log_out_dialog_message)
+      onView(withText(R.string.log_out_dialog_cancel_button)).perform(click())
+      onView(withId(R.id.log_out_text_view)).check(matches(isDisplayed()))
     }
   }
 
+  @Test
+  fun testAdministratorControls_selectAdminNavItem_adminControlsIsDisplayed() {
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt]: This seems like an activity-level test since it's verifying the navigation drawer (which isn't set up by the fragment).

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @yash10019coder. Apologies for the delayed review--I took a full pass on the PR. Overall, I think the PR looks good. I mainly had style/readability feedback and a bunch of feedback on the testing--PTAL.

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt (hunk 48 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt]: done

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt (hunk 7 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt]: I think I have removed this file AdministratorControlsActivity form kdoc_validity_exemptions.

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt (hunk 54 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt]: ok

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt (hunk 49 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt]: Actually I have made it nullable, so it's necessary and also profile deletion dialog is not for admin so it's a necessary check.

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt (hunk 55 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt]: done but using ? wouldn't make it nullable?

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt (hunk 56 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt]: done

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt (hunk 57 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt:188]: I am going to add furthurmore cases here for the  ProfileRenameFragment and ProfileResetPinFragment they will be done in two seperate PR's.

File: app/src/main/java/org/oppia/android/app/settings/profile/LoadProfileEditDeletionDialogListener.kt (hunk 51 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/settings/profile/LoadProfileEditDeletionDialogListener.kt]: configuration change is like rotating phone or tablet from portrait to landscape.
done

File: app/src/main/java/org/oppia/android/app/settings/profile/ProfileEditFragmentPresenter.kt (hunk 53 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/settings/profile/ProfileEditFragmentPresenter.kt:37]: done

File: app/src/main/java/org/oppia/android/app/settings/profile/ProfileEditFragmentPresenter.kt (hunk 52 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/settings/profile/ProfileEditFragmentPresenter.kt]: done

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt (hunk 59 above)
Comment (yash10019coder) [reply app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt]: done

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt (hunk 50 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt:75]: do you mean declaring the fragment in global scope?

**Review by rt4914 — CHANGES_REQUESTED** [review]
Almost LGTM. Just let me know when test related changes are ready.

File: app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditFragmentTest.kt (hunk 47 above)
Comment (yash10019coder) [reply app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditFragmentTest.kt:106]: also wrapped the tests inside their own test activity

File: app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditFragmentTest.kt (hunk 46 above)
Comment (yash10019coder) [reply app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditFragmentTest.kt]: done

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt (hunk 58 above)
Comment (yash10019coder) [reply app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt]: still left to do

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt (hunk 60 above)
Comment (yash10019coder) [reply app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt]: shortened the test case

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt (hunk 61 above)
Comment (yash10019coder) [reply app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt]: actually we don't have to click anything here it's already on the screen we are checking the clickablity for Download and update only on wifi

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt (hunk 62 above)
Comment (yash10019coder) [reply app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt]: can you please elaborate this

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt (hunk 64 above)
Comment (yash10019coder) [reply app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt]: shifted it

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt (hunk 63 above)
Comment (yash10019coder) [reply app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt]: done

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt (hunk 38 above)
Comment (yash10019coder) [reply app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt]: made some helper functions to shorten the tests.

**Review by yash10019coder — COMMENTED** [review]
Hi @rt4914 @BenHenning made some changes PTAL thanks

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt [hunk 65]
```diff
@@ -94,8 +94,9 @@ class AdministratorControlsActivity :
       supportFragmentManager.findFragmentById(
         R.id.administrator_controls_fragment_multipane_placeholder
       )
-    /* when fragment is ProfileEditFragment then we should switch fragment to ProfileListFragment or else
-       we just end the activity as then we are having ProfileListFragment on top. */
+    /* If we have current fragment ProfileListFragment then we should end the activity on back press
+       but if we have ProfileEditFragment as current fragment then we should inflate profileListFragment
+       which is done by the handleOnBackPressed method. */
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt]:
```suggestion
    /*
     * If the current fragment is ProfileListFragment then the activity should end on back press.
     * If it's instead ProfileEditFragment then profileListFragment should be inflated via
     * handleOnBackPressed.
     */
```

Some reformatting and language changes. This might also need re-wrapping to more tightly fit the 100 character limit (I didn't check since it's a bit difficult to via a web text box).

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt (hunk 50 above)
Comment (BenHenning) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt:75]: No, I mean declaring it was a variable in handleOnCreate since it's created above and thus could be accessed here at zero-cost (rather than needing to fetch it via the manager).

File: app/src/main/java/org/oppia/android/app/settings/profile/LoadProfileEditDeletionDialogListener.kt [hunk 66]
```diff
@@ -2,6 +2,9 @@ package org.oppia.android.app.settings.profile
 
 /** Listener for when the activity should inflate [ProfileEditDeletionDialogFragment]. */
 interface LoadProfileEditDeletionDialogListener {
-  /** Inflates [ProfileEditDeletionDialogFragment] for the configuration changes and saves the state of the dialog. */
+  /**
+   * Inflates [ProfileEditDeletionDialogFragment] for the configuration changes, i.e. rotating the device
+   *  from landscape to portrait and saves the state of the dialog.
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/settings/profile/LoadProfileEditDeletionDialogListener.kt]:
```suggestion
   * from landscape to portrait, and saves the state of the dialog.
```

File: app/src/main/java/org/oppia/android/app/testing/ProfileEditFragmentTestActivity.kt [hunk 67]
```diff
@@ -0,0 +1,32 @@
...
+import android.os.Bundle
+import org.oppia.android.app.activity.ActivityComponentImpl
+import org.oppia.android.app.settings.profile.PROFILE_EDIT_PROFILE_ID_EXTRA_KEY
+import org.oppia.android.app.settings.profile.ProfileEditFragment
+import org.oppia.android.app.testing.activity.TestActivity
+import javax.inject.Inject
+
+/**
+ * Test Activity for testing [ProfileEditFragment] and it's view models.
+ */
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/testing/ProfileEditFragmentTestActivity.kt]: Nit: can fit on one line.

Also, please remove the extra newline below this.

File: app/src/main/java/org/oppia/android/app/testing/ProfileEditFragmentTestActivityPresenter.kt [hunk 68]
```diff
@@ -0,0 +1,31 @@
...
+class ProfileEditFragmentTestActivityPresenter @Inject constructor(
+  private val activity: AppCompatActivity
+) {
+  fun handleOnCreate() {
+    activity.setContentView(R.layout.profile_edit_activity)
+    val profileId = activity.intent.getIntExtra(PROFILE_EDIT_PROFILE_ID_EXTRA_KEY, 0)
+    if (getProfileEditFragment() == null) {
+      activity.supportFragmentManager.beginTransaction().replace(
+        R.id.profile_edit_fragment_placeholder,
+        ProfileEditFragment.newInstance(profileId, false)
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/testing/ProfileEditFragmentTestActivityPresenter.kt]: You should use a named argument for the boolean literal ``false`` to provide inline context on what the value corresponds to.

File: app/src/main/java/org/oppia/android/app/testing/ProfileEditFragmentTestActivityPresenter.kt [hunk 69]
```diff
@@ -0,0 +1,31 @@
...
+      ).commitNow()
+    }
+  }
+
+  private fun getProfileEditFragment(): ProfileEditFragment? {
+    return activity
+      .supportFragmentManager
+      .findFragmentById(R.id.profile_edit_fragment_placeholder) as ProfileEditFragment?
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/testing/ProfileEditFragmentTestActivityPresenter.kt]: Should be ``as? ProfileEditFragment`` since you want both the cast and null to result in null here.

File: scripts/assets/kdoc_validity_exemptions.textproto [hunk 70]
```diff
@@ -267,6 +267,8 @@ exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/ImageRegion
 exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/InputInteractionViewTestActivity.kt"
 exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/NavigationDrawerTestActivity.kt"
 exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/ProfileChooserFragmentTestActivity.kt"
+exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/ProfileEditFragmentTestActivity.kt"
+exempted_file_path: "app/src/main/java/org/oppia/android/app/testing/ProfileEditFragmentTestActivityPresenter.kt"
```
Comment (BenHenning) [inline scripts/assets/kdoc_validity_exemptions.textproto]: You should add the missing KDocs rather than exempting the file.

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityTest.kt [hunk 71]
```diff
@@ -175,399 +173,348 @@ class AdministratorControlsActivityTest {
...
-      scrollToPosition(position = 4)
-      onView(withId(R.id.log_out_text_view)).perform(click())
-      verifyTextInDialog(textInDialogId = R.string.log_out_dialog_message)
-      verifyTextInDialog(textInDialogId = R.string.log_out_dialog_okay_button)
-      verifyTextInDialog(textInDialogId = R.string.log_out_dialog_cancel_button)
+      clickAdminProfile()
+      testCoroutineDispatchers.runCurrent()
+      onView(withId(R.id.extra_controls_title)).check(matches(withText("Admin")))
+      onView(withId(R.id.profile_edit_name)).check(matches(withText("Admin")))
+      Espresso.pressBack()
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityTest.kt]: pressBack should be directly imported like other Espresso methods.

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityTest.kt [hunk 72]
```diff
@@ -175,399 +173,348 @@ class AdministratorControlsActivityTest {
...
     ).use {
+      onView(ViewMatchers.isRoot()).perform(OrientationChangeAction.orientationLandscape())
       testCoroutineDispatchers.runCurrent()
-      scrollToPosition(position = 3)
-      onView(withId(R.id.app_version_text_view)).perform(click())
-      intended(hasComponent(AppVersionActivity::class.java.name))
+      onView(atPositionOnView(R.id.profile_list_recycler_view, 1, R.id.profile_list_name)).check(
+        matches(withText("Ben"))
+      ).perform(click())
+      onView(withId(R.id.profile_delete_button)).perform(ViewActions.scrollTo()).perform(click())
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityTest.kt]: scrollTo and orientationLandscape and isRoot should also be directly imported. Ditto for all other similar methods used in this test suite, and others in the PR.

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityTest.kt [hunk 73]
```diff
@@ -175,399 +173,348 @@ class AdministratorControlsActivityTest {
...
+        .inRoot(isDialog())
+        .check(
+          matches(
+            isCompletelyDisplayed()
+          )
+        )
     }
   }
 
+  private fun isAdminProfileVisible() {
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityTest.kt]:
```suggestion
  private fun checkIsAdminProfileVisible() {
```

I think this is what you meant--the function should clearly describe what it's doing.

Ditto for isAdminTextVisibile.

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt (hunk 60 above)
Comment (BenHenning) [reply app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt]: It's still verifying more than one thing (i.e. it has multiple distinct 'assert' sections whereas it should only have one).

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt (hunk 62 above)
Comment (BenHenning) [reply app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt]: Sure. Since we should be testing the fragment in isolation (i.e. via a test activity), the verification here is to ensure the callback that leads to the activity opening the logout dialog is the thing that should be verified since without the actual activity it wouldn't be displayed.

I may be mistaken about the flow here, though. Is the dialog shown via the activity or the fragment?

File: app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditFragmentTest.kt [hunk 74]
```diff
@@ -0,0 +1,388 @@
...
+      onView(isRoot()).perform(orientationLandscape())
+      onView(withId(R.id.profile_delete_button)).perform(scrollTo()).perform(click())
+      testCoroutineDispatchers.runCurrent()
+      onView(withText(R.string.profile_edit_delete_dialog_message))
+        .inRoot(isDialog())
+        .check(
+          matches(
+            isDisplayed()
+          )
+        )
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditFragmentTest.kt]: This can be condensed to one line, I think (per the style guide).

Ditto for other similar cases in this test suite.

File: app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditFragmentTest.kt [hunk 75]
```diff
@@ -0,0 +1,388 @@
...
+      isAdmin = false
+    ).toLiveData()
+    launch<ProfileEditFragmentTestActivity>(
+      ProfileEditFragmentTestActivity.createProfileEditFragmentTestActivity(
+        context = context,
+        profileId = 4
+      )
+    ).use {
+      testCoroutineDispatchers.runCurrent()
+      onView(withId(R.id.profile_edit_allow_download_switch)).check(matches(not(isClickable())))
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditFragmentTest.kt:273]: I'm a bit confused. Isn't this test using the exact same profile setup as the previous one? Why is the switch clickable in that test but not this one?

File: app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditFragmentTest.kt [hunk 76]
```diff
@@ -0,0 +1,388 @@
...
+      onView(withId(R.id.profile_edit_allow_download_container)).check(matches(isDisplayed()))
+    }
+  }
+
+  @Test
+  fun testProfileEdit_startWithUserDoesNotHaveDownloadAccess_switchContainerIsNotDisplayed() {
+    launch<ProfileEditFragmentTestActivity>(
+      ProfileEditFragmentTestActivity.createProfileEditFragmentTestActivity(
+        context = context,
+        profileId = 0
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditFragmentTest.kt:324]: Does this correspond to a real profile?

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt (hunk 55 above)
Comment (BenHenning) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt]: When doing assignments like ``object?.property = value``, the ``?.`` operator will conditionally assign ``value`` to ``property`` iff ``object`` isn't null.

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt (hunk 61 above)
Comment (BenHenning) [reply app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt]: In that case, the condition is 'initialState' (and it's worth clarifying so that others don't make any assumptions about what state is necessary to produce the verified outcome).

**Review by BenHenning — COMMENTED** [review]
Thanks @yash10019coder! I took a mostly full pass on the PR (there are still some high-level test changes pending per past comments). Most of my feedback are nits at this point, I think, so the PR is starting to look close to done. PTAL at the latest comments.

**Comment by rt4914** [comment]
Un-assiging until the above changes are finished.

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt (hunk 50 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt:75]: Actually we need the ProfileEditFragment as fragment which is only possible by taking it this way inside I tried to decleare it outside but then it captures the instance of ProfileListFragment and then a illegal cast exception.

File: app/src/main/java/org/oppia/android/app/testing/ProfileEditFragmentTestActivity.kt (hunk 67 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/testing/ProfileEditFragmentTestActivity.kt]: done

File: app/src/main/java/org/oppia/android/app/testing/ProfileEditFragmentTestActivityPresenter.kt (hunk 68 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/testing/ProfileEditFragmentTestActivityPresenter.kt]: done

File: app/src/main/java/org/oppia/android/app/testing/ProfileEditFragmentTestActivityPresenter.kt (hunk 69 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/testing/ProfileEditFragmentTestActivityPresenter.kt]: done

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityTest.kt (hunk 71 above)
Comment (yash10019coder) [reply app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityTest.kt]: done

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityTest.kt (hunk 72 above)
Comment (yash10019coder) [reply app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityTest.kt]: done

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityTest.kt (hunk 73 above)
Comment (yash10019coder) [reply app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityTest.kt]: done

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt (hunk 60 above)
Comment (yash10019coder) [reply app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt]: But the thing we are trying to do here is that we are first checking if the button isn't clicked then as it is confirmed that it is not clicked we click it and then perform a orientation change and then check if the button is still click for checking the persistance of the data.
I think that checking the persistance has to be done in one go, so how can we split it?

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt (hunk 61 above)
Comment (yash10019coder) [reply app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt]: added more reasonable context.

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt (hunk 62 above)
Comment (yash10019coder) [reply app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt]: I think dialog is shown by fragment

File: app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditFragmentTest.kt (hunk 74 above)
Comment (yash10019coder) [reply app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditFragmentTest.kt]: done

File: app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditFragmentTest.kt (hunk 75 above)
Comment (yash10019coder) [reply app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditFragmentTest.kt:273]: Actually this is the unit test for ProfileEditFragment and the earlier one is of AdministratorControlsFragment.

File: app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditFragmentTest.kt (hunk 76 above)
Comment (yash10019coder) [reply app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditFragmentTest.kt:324]: yeah actually admin doesn't have any download access or thing as he's the admin he doesn't need any.

File: scripts/assets/kdoc_validity_exemptions.textproto (hunk 70 above)
Comment (yash10019coder) [reply scripts/assets/kdoc_validity_exemptions.textproto]: ack

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt (hunk 58 above)
Comment (yash10019coder) [reply app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt]: done

**Review by yash10019coder — COMMENTED** [review]
Hi @BenHenning @rt4914 mentioned all the comments PTAL 
I am also getting a error while running tests for AdministratorControlsFragment.kt [gist link](https://gist.github.com/32fab1e647bee5ffbe5a40f1b59ffb81) I have declared the activity in manifest bug still it is not recognizing the intent.

File: app/src/main/java/org/oppia/android/app/testing/AdministratorControlsFragmentTestActivity.kt [hunk 77]
```diff
@@ -0,0 +1,66 @@
...
+import org.oppia.android.app.administratorcontrols.RouteToProfileListListener
+import org.oppia.android.app.administratorcontrols.ShowLogoutDialogListener
+import org.oppia.android.app.administratorcontrols.appversion.AppVersionActivity
+import org.oppia.android.app.drawer.NAVIGATION_PROFILE_ID_ARGUMENT_KEY
+import org.oppia.android.app.settings.profile.ProfileListActivity
+import org.oppia.android.app.testing.activity.TestActivity
+import org.oppia.android.app.translation.AppLanguageResourceHandler
+import javax.inject.Inject
+
+/** Activity [AdministratorControlsFragmentTestActivity] that allows user to change admin controls. */
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/testing/AdministratorControlsFragmentTestActivity.kt]:
```suggestion
/** Test activity for ``AdministratorControlsFragmentTestActivity``. */
```

I suspect this might be a bit clearer.

File: app/src/main/java/org/oppia/android/app/testing/AdministratorControlsFragmentTestActivity.kt [hunk 78]
```diff
@@ -0,0 +1,66 @@
...
+      return intent
+    }
+
+    /** Returns the argument key used to specify the user's internal profile ID. */
+    fun getIntentKey(): String {
+      return NAVIGATION_PROFILE_ID_ARGUMENT_KEY
+    }
+  }
+
+  override fun showLogoutDialog() {
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/testing/AdministratorControlsFragmentTestActivity.kt]: So this is actually what I was referring to in the other comment--rather than showing the dialog, you could call a test-defined ShowLogoutDialogListener field to verify when the logout dialog should be opened.

File: app/src/main/java/org/oppia/android/app/testing/ProfileEditFragmentTestActivity.kt [hunk 79]
```diff
@@ -9,10 +9,7 @@ import org.oppia.android.app.settings.profile.ProfileEditFragment
 import org.oppia.android.app.testing.activity.TestActivity
 import javax.inject.Inject
 
-/**
- * Test Activity for testing [ProfileEditFragment] and it's view models.
- */
-
+/** Test Activity for testing [ProfileEditFragment] and it's view models. */
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/testing/ProfileEditFragmentTestActivity.kt]:
```suggestion
/** Test Activity for testing [ProfileEditFragment] and its view models. */
```

File: app/src/main/java/org/oppia/android/app/testing/ProfileEditFragmentTestActivity.kt [hunk 80]
```diff
@@ -23,6 +20,7 @@ class ProfileEditFragmentTestActivity : TestActivity() {
   }
 
   companion object {
+    /** Returns an [Intent] for opening the [ProfileEditFragmentTestActivitytivity]. */
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/testing/ProfileEditFragmentTestActivity.kt]: Typo in the class reference; please fix.

File: app/src/main/res/values/strings.xml [hunk 81]
```diff
@@ -507,4 +507,7 @@
...
   <string name="faq_answer_8"><![CDATA[<p>To download an Exploration:</p><p>1. From the Home Page, tap on a Topic or Exploration.</p><p>2. From that Topic Page, tap on the <strong>Info</strong> tab.</p><p>3. Tap on <strong>Download Topic</strong>. </p><p>4. Depending on your app settings, you may need Administrator approval or stable Wifi connection to complete your download. If needed, once these requirements are satisfied, the Topic has been downloaded onto the device and can be used offline by all profiles. <p>]]></string>
   <string name="faq_answer_9"><![CDATA[<p>If you cannot find your question or would like to report a bug, contact us at admin@oppia.org.</p>]]></string>
+  <string name="profile_edit_fragment_test_activity_label">ProfilEditFragmentTestActivity</string>
+  <string name="administrator_controls_fragment_test_activity_label">Administrator Controls Fragment Test Activity
```
Comment (BenHenning) [inline app/src/main/res/values/strings.xml]: While we don't usually have strings for test activity labels, please make sure that these two are consistent in their wording.

File: app/src/main/res/values/strings.xml [hunk 82]
```diff
@@ -507,4 +507,7 @@
...
+  </string>
```
Comment (BenHenning) [inline app/src/main/res/values/strings.xml]:
```suggestion
  <string name="administrator_controls_fragment_test_activity_label">Administrator Controls Fragment Test Activity</string>
```

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt (hunk 62 above)
Comment (BenHenning) [reply app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt]: Per the test activity you added, it appears to be the activity. I left a new comment to continue this discussion there--PTAL.

File: app/src/main/AndroidManifest.xml [hunk 83]
```diff
@@ -6,7 +6,7 @@
   <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
   <uses-permission android:name="android.permission.INTERNET" />
   <uses-permission android:name="android.permission.WAKE_LOCK" />
-  <!-- TODO(#56): Reenable landscape support. -->
```
Comment (BenHenning) [inline app/src/main/AndroidManifest.xml]: Why is this being removed?

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt (hunk 50 above)
Comment (BenHenning) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivityPresenter.kt:75]: Ah, I think I mixed up the multipane with non-multipane version. This makes more sense to me now.

File: app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditFragmentTest.kt (hunk 75 above)
Comment (BenHenning) [reply app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditFragmentTest.kt:273]: I'm not sure that I understand. Both this & the previous test are setting up ProfileEditFragmentTestActivity with exactly the same profile. Am I missing something?

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt (hunk 61 above)
Comment (BenHenning) [reply app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt]: Much clearer--can you also update the next test and others that aren't as clear?

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt (hunk 60 above)
Comment (BenHenning) [reply app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt]: I see three distinct tests here:

First:
```kotlin
    launch<AdministratorControlsFragmentTestActivity>(
      createAdministratorControlsFragmentTestActivityIntent(
        profileId = internalProfileId
      )
    ).use {
      testCoroutineDispatchers.runCurrent()

      scrollToPosition(position = 2)

      onView(
        atPositionOnView(
          recyclerViewId = R.id.administrator_controls_list,
          position = 2,
          targetViewId = R.id.topic_update_on_wifi_switch
        )
      ).check(matches(not(isChecked())))
    }
```

Second:
```kotlin
    launch<AdministratorControlsFragmentTestActivity>(
      createAdministratorControlsFragmentTestActivityIntent(
        profileId = internalProfileId
      )
    ).use {
      testCoroutineDispatchers.runCurrent()
      scrollToPosition(position = 2)
      onView(
        atPositionOnView(
          recyclerViewId = R.id.administrator_controls_list,
          position = 2,
          targetViewId = R.id.topic_update_on_wifi_constraint_layout
        )
      ).perform(click())
      testCoroutineDispatchers.runCurrent()

      onView(isRoot()).perform(orientationLandscape())

      scrollToPosition(position = 2)
      onView(
        atPositionOnView(
          recyclerViewId = R.id.administrator_controls_list,
          position = 2,
          targetViewId = R.id.topic_update_on_wifi_switch
        )
      ).check(matches(isChecked()))
    }
```

Third:
```kotlin
    launch<AdministratorControlsFragmentTestActivity>(
      createAdministratorControlsFragmentTestActivityIntent(
        profileId = internalProfileId
      )
    ).use {
      testCoroutineDispatchers.runCurrent()
      scrollToPosition(position = 2)
      onView(
        atPositionOnView(
          recyclerViewId = R.id.administrator_controls_list,
          position = 2,
          targetViewId = R.id.topic_update_on_wifi_constraint_layout
        )
      ).perform(click())
      testCoroutineDispatchers.runCurrent()

      onView(isRoot()).perform(orientationLandscape())
      onView(isRoot()).perform(orientationPortrait())

      scrollToPosition(position = 2)
      onView(
        atPositionOnView(
          recyclerViewId = R.id.administrator_controls_list,
          position = 2,
          targetViewId = R.id.topic_update_on_wifi_switch
        )
      ).check(matches(isChecked()))
    }
```

Notice how each has a single assertion block at the end rather than some in the middle. This can be further visually shortened by introducing helper methods to simplify specific parts of this & other tests, as well.

Does that help clarify?

**Review by BenHenning — COMMENTED** [review]
Thanks @yash10019coder. Just had a few comments--PTAL.

**Comment by yash10019coder** [comment]
@BenHenning can you please also look at the while running tests for AdministratorControlsFragment.kt [gist link](https://gist.github.com/32fab1e647bee5ffbe5a40f1b59ffb81) I have declared the activity in manifest bug still it is not recognizing the intent.

File: app/src/main/AndroidManifest.xml (hunk 83 above)
Comment (yash10019coder) [reply app/src/main/AndroidManifest.xml]: reverted removed by mistake.

File: app/src/main/java/org/oppia/android/app/testing/ProfileEditFragmentTestActivity.kt (hunk 80 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/testing/ProfileEditFragmentTestActivity.kt]: done

File: app/src/main/res/values/strings.xml (hunk 81 above)
Comment (yash10019coder) [reply app/src/main/res/values/strings.xml]: done

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt (hunk 60 above)
Comment (yash10019coder) [reply app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt]: ok I understand now fixed it.

File: app/src/main/java/org/oppia/android/app/testing/AdministratorControlsFragmentTestActivity.kt (hunk 78 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/testing/AdministratorControlsFragmentTestActivity.kt]: But it is already tested in both the activity and fragment

File: app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditFragmentTest.kt (hunk 75 above)
Comment (yash10019coder) [reply app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditFragmentTest.kt:273]: fixed it now this test profile has no download access.

**Review by yash10019coder — COMMENTED** [review]
Hi @BenHenning @rt4914 mentioned all the comments PTAL thanks

File: app/src/main/AndroidManifest.xml (hunk 83 above)
Comment (BenHenning) [reply app/src/main/AndroidManifest.xml]: Suggest also reverting the removed newline (I suspect it was originally intentional since these are logically separate blocks in the manifest).

File: app/src/main/java/org/oppia/android/app/testing/AdministratorControlsFragmentTestActivity.kt [hunk 84]
```diff
@@ -15,11 +18,14 @@ import org.oppia.android.app.testing.activity.TestActivity
 import org.oppia.android.app.translation.AppLanguageResourceHandler
 import javax.inject.Inject
 
-/** Activity [AdministratorControlsFragmentTestActivity] that allows user to change admin controls. */
+/** Test activity for ``AdministratorControlsFragmentTestActivity``. */
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/testing/AdministratorControlsFragmentTestActivity.kt]:
```suggestion
/** Test activity for ``AdministratorControlsFragmentTest``. */
```

I think this is what you meant, or no? The previous documentation didn't really make sense since it was tautological.

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt [hunk 85]
```diff
@@ -506,6 +449,96 @@ class AdministratorControlsFragmentTest {
...
+    ).check(matches(isChecked()))
+  }
+
+  private fun clickUpdateOnWifiSwitch() {
+    onView(
+      atPositionOnView(
+        recyclerViewId = R.id.administrator_controls_list,
+        position = 2,
+        targetViewId = R.id.topic_update_on_wifi_constraint_layout
+      )
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt]: You could probably move this bit to a helper, too, to simplify all of these helper methods (I think they'd fit on just one line at that point).

File: app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditFragmentTest.kt [hunk 86]
```diff
@@ -252,7 +252,7 @@ class ProfileEditFragmentTest {
       name = "James",
       pin = "123",
       avatarImagePath = null,
-      allowDownloadAccess = true,
+      allowDownloadAccess = false,
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditFragmentTest.kt:262]: Is this correct? It no longer matches the name of the test.

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt [hunk 87]
```diff
@@ -232,145 +232,112 @@ class AdministratorControlsFragmentTest {
   }
 
   @Test
-  fun testAdministratorControlsFragment_wifiSwitchIsUncheck_autoUpdateSwitchIsUnchecked() {
+  fun testAdministratorControlsFragment_wifiSwitchIsUnchecked() {
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt:243]: As a piece of feedback: these tests are **much** more readable--thanks for making the changes!

File: app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditFragmentTest.kt (hunk 75 above)
Comment (BenHenning) [reply app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditFragmentTest.kt:273]: I think I might still be confused, but I added a new conversation thread per the latest changes so resolving this to simplify discussions.

File: app/src/main/java/org/oppia/android/app/testing/AdministratorControlsFragmentTestActivity.kt (hunk 78 above)
Comment (BenHenning) [reply app/src/main/java/org/oppia/android/app/testing/AdministratorControlsFragmentTestActivity.kt]: Tests generally should be verifying the "public API" (i.e. observable behaviors) of their component under test.

For an activity, that's essentially the high-level user behaviors (especially those which go across fragments since individual fragment tests can't verify them). Showing the dialog is an example of this: the activity is responsible for showing the dialog under certain conditions. Since it's the activity's responsibility, we verify it in the activity's test suite.

The fragment, on the other hand, isn't responsible for _showing_ the dialog, but it _is_ responsible for notifying its host activity when it's time to show the dialog. Because this is an expected behavior of the fragment, we should test that. While verifying that the dialog also opens is technically verifying it by proxy, that's entirely contingent on the test activity behaving the same way as the production activity. My suggestion is to instead pass in a fake or mock ShowLogoutDialogListener that the test activity just calls here rather than doing anything, and then we can verify mor explicitly in the fragment's test suite that it calls the activity's ShowLogoutDialogListener when expected.

Does that help clarify?

**Review by BenHenning — COMMENTED** [review]
Thanks @yash10019coder! Just had a few comments left, but I think the PR is getting really close.

@rt4914 & @anandwana001 I think you could both review the PR for codeowners at this point since all of my remaining comments are nits or small suggestions.

File: app/src/main/AndroidManifest.xml (hunk 83 above)
Comment (yash10019coder) [reply app/src/main/AndroidManifest.xml]: done

File: app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditFragmentTest.kt (hunk 86 above)
Comment (yash10019coder) [reply app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditFragmentTest.kt:262]: fixed

**Review by rt4914 — APPROVED** [review]
Approved for functionality and code-owner files.

File: app/src/main/java/org/oppia/android/app/testing/AdministratorControlsFragmentTestActivity.kt (hunk 84 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/testing/AdministratorControlsFragmentTestActivity.kt]: yeah thanks ben

File: app/src/main/java/org/oppia/android/app/testing/AdministratorControlsFragmentTestActivity.kt (hunk 78 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/testing/AdministratorControlsFragmentTestActivity.kt]: thanks ben this clears the whole thing I have moved tests related to these to activity and also removed the implementation and just overridden the methods.

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt (hunk 87 above)
Comment (yash10019coder) [reply app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt:243]: thanks a lot for feedback

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt (hunk 85 above)
Comment (yash10019coder) [reply app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt]: I think they cannot be subdivided further as they are in a single view assertion and perform state?

**Review by yash10019coder — COMMENTED** [review]
Hi @BenHenning @anandwana001 mentioned all the comments PTAL thanks

File: app/src/main/java/org/oppia/android/app/testing/AdministratorControlsFragmentTestActivity.kt [hunk 88]
```diff
@@ -0,0 +1,74 @@
...
+import org.oppia.android.app.administratorcontrols.RouteToProfileListListener
+import org.oppia.android.app.administratorcontrols.ShowLogoutDialogListener
+import org.oppia.android.app.administratorcontrols.appversion.AppVersionActivity
+import org.oppia.android.app.drawer.NAVIGATION_PROFILE_ID_ARGUMENT_KEY
+import org.oppia.android.app.settings.profile.ProfileListActivity
+import org.oppia.android.app.testing.activity.TestActivity
+import org.oppia.android.app.translation.AppLanguageResourceHandler
+import javax.inject.Inject
+
+/** Test activity for ``AdministratorControlsFragmentTest``. */
```
Comment (anandwana001) [inline app/src/main/java/org/oppia/android/app/testing/AdministratorControlsFragmentTestActivity.kt]: Though we cannot jump to the test class, but the format should be

```suggestion
/** Test activity for [AdministratorControlsFragmentTest]. */
```

File: app/src/main/java/org/oppia/android/app/testing/AdministratorControlsFragmentTestActivity.kt [hunk 89]
```diff
@@ -0,0 +1,74 @@
...
+    ): Intent {
+      val intent = Intent(context, AdministratorControlsFragmentTestActivity::class.java)
+      intent.putExtra(NAVIGATION_PROFILE_ID_ARGUMENT_KEY, profileId)
+      return intent
+    }
+
+    /** Returns the argument key used to specify the user's internal profile ID. */
+    fun getIntentKey(): String {
+      return NAVIGATION_PROFILE_ID_ARGUMENT_KEY
+    }
```
Comment (anandwana001) [inline app/src/main/java/org/oppia/android/app/testing/AdministratorControlsFragmentTestActivity.kt]: Are we using this function somewhere? else we can remove it.

File: app/src/main/java/org/oppia/android/app/testing/AdministratorControlsFragmentTestActivityPresenter.kt [hunk 90]
```diff
@@ -0,0 +1,31 @@
...
+  }
+
+  /** Returns [AdministratorControlsFragment] instance. */
+  private fun getAdministratorControlsFragment(): AdministratorControlsFragment? {
+    return activity
+      .supportFragmentManager
+      .findFragmentById(
+        R.id.administrator_controls_fragment_test_activity_fragment_container
+      ) as? AdministratorControlsFragment
+  }
```
Comment (anandwana001) [inline app/src/main/java/org/oppia/android/app/testing/AdministratorControlsFragmentTestActivityPresenter.kt]: Is this function used anywhere?

File: app/src/main/java/org/oppia/android/app/testing/ProfileEditFragmentTestActivity.kt [hunk 91]
```diff
@@ -0,0 +1,30 @@
...
+  @Inject
+  lateinit var profileEditFragmentTestActivityPresenter: ProfileEditFragmentTestActivityPresenter
+  override fun onCreate(savedInstanceState: Bundle?) {
+    super.onCreate(savedInstanceState)
+    (activityComponent as ActivityComponentImpl).inject(this)
+    profileEditFragmentTestActivityPresenter.handleOnCreate()
+  }
+
+  companion object {
+    /** Returns an [Intent] for opening the [ProfileEditFragmentTestActivity]. */
```
Comment (anandwana001) [inline app/src/main/java/org/oppia/android/app/testing/ProfileEditFragmentTestActivity.kt]:
```suggestion
    /** Returns an [Intent] for opening [ProfileEditFragmentTestActivity]. */
```

**Review by anandwana001 — APPROVED** [review]
Nit suggestions on my codeowner files else LGTM

File: app/src/main/java/org/oppia/android/app/testing/AdministratorControlsFragmentTestActivity.kt (hunk 89 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/testing/AdministratorControlsFragmentTestActivity.kt]: removed unused code

File: app/src/main/java/org/oppia/android/app/testing/AdministratorControlsFragmentTestActivityPresenter.kt (hunk 90 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/testing/AdministratorControlsFragmentTestActivityPresenter.kt]: removed this unused method.

**Review by yash10019coder — COMMENTED** [review]
Hi @BenHenning mentioned all the comments and requested changes PTAL thanks

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt (hunk 85 above)
Comment (BenHenning) [reply app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt]: You could do something like:

```kotlin
private fun clickUpdateOnWifiSwitch() {
  onView(atAdminControlsItem(position = 2, R.id.topic_update_on_wifi_constraint_layout)).perform(click())
}

private fun atAdminControlsItem(position: Int, @ResId viewId: Int): Matcher<View> {
  return atPositionOnView(recyclerViewId = R.id.administrator_controls_list, position, viewId)
}
```

(As an example). It doesn't quite fit on one line for the first bit, but there are other ways you could simplify things if you'd want to. FWIW I think this is optional, but it can help with test readability.

File: app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditFragmentTest.kt [hunk 92]
```diff
@@ -0,0 +1,373 @@
...
+    ).use {
+      testCoroutineDispatchers.runCurrent()
+      onView(withId(R.id.profile_edit_allow_download_switch)).check(matches(isChecked()))
+      onView(withId(R.id.profile_edit_allow_download_container)).perform(click())
+      onView(withId(R.id.profile_edit_allow_download_switch)).check(matches(not(isChecked())))
+    }
+  }
+
+  @Test
+  fun testProfileEdit_startWithUserDoesNotHasDownloadAccess_switchIsNotClickable() {
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/settings/profile/ProfileEditFragmentTest.kt]:
```suggestion
  fun testProfileEdit_startWithUserDoesNotHaveDownloadAccess_switchIsNotClickable() {
```

**Review by BenHenning — COMMENTED** [review]
Sorry @yash10019coder I had an urgent issue to deal with for the last week. Took another pass--the PR mostly LGTM. Just had 1 nit and 1 follow-up on an optional comment--PTAL.

**Comment by yash10019coder** [comment]
gist of the error https://gist.github.com/yash10019coder/ceb2e1fc6ef5fbf61ad244d2f454e253

**Comment by BenHenning** [comment]
> gist of the error https://gist.github.com/yash10019coder/ceb2e1fc6ef5fbf61ad244d2f454e253

@yash10019coder there are new modules that need to be included in your tests. I think this has occurred since new modules were added since the PR was originally opened, so syncing to develop has caused the missing dependencies issue to crop up. I suggest taking a look at other UI fragments and their histories (which can be viewed via GitHub) to see which modules have been added in the last few weeks; you'll likely need to add similar ones (based on the specific Dagger missing binding errors that you're encountering).

File: app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt (hunk 85 above)
Comment (yash10019coder) [reply app/src/sharedTest/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentTest.kt]: done

**Review by yash10019coder — COMMENTED** [review]
Hi @BenHenning mentioned all the comments PTAL thanks.

**Comment by BenHenning** [comment]
Reopened since this was closed due to my late review.

File: app/BUILD.bazel [hunk 93]
```diff
@@ -673,8 +674,8 @@ kt_android_library(
         "//app/src/main/java/org/oppia/android/app/utility/datetime:date_time_util",
         "//app/src/main/java/org/oppia/android/app/utility/math:math_expression_accessibility_util",
         "//domain",
-        "//domain/src/main/java/org/oppia/android/domain/audio:audio_player_controller",
         "//domain/src/main/java/org/oppia/android/domain/clipboard:clipboard_controller",
+        "//domain/src/main/java/org/oppia/android/domain/audio:audio_player_controller",
```
Comment (BenHenning) [inline app/BUILD.bazel]: This should be on the line above per dependency sorting order.

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt [hunk 94]
```diff
@@ -93,16 +94,44 @@ class AdministratorControlsActivity :
...
       )
     /*
-     * If the current fragment is ProfileListFragment then the activity should end on back press.
-     * If it's instead ProfileEditFragment then profileListFragment should be inflated via
-     * handleOnBackPressed.
-     */
+      * If the current fragment is ProfileListFragment then the activity should end on back press.
+      * If it's instead ProfileEditFragment then profileListFragment should be inflated via
+      * handleOnBackPressed.
+      */
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt]: The previous version was correct--this should be moved to the left by 1 space.

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt [hunk 95]
```diff
@@ -64,18 +98,47 @@ class AdministratorControlsActivity :
     startActivity(ProfileAndDeviceIdActivity.createIntent(this))
   }
 
+  override fun loadProfileEdit(profileId: Int, profileName: String) {
+    lastLoadedFragment = PROFILE_EDIT_FRAGMENT
+    administratorControlsActivityPresenter.loadProfileEdit(profileId, profileName)
+  }
+
+  override fun loadBooleanProfileEditDeletionDialog(isProfileDeletionDialogVisible: Boolean) {
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt]: Why not just ``loadProfileDeletionDialog`` for parity with the methods & variables?

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentPresenter.kt [hunk 96]
```diff
@@ -178,8 +183,9 @@ class AdministratorControlsFragmentPresenter @Inject constructor(
   private fun getSelectedFragmentIndex(selectedFragment: String): Int {
     return when (selectedFragment) {
       PROFILE_LIST_FRAGMENT -> 1
-      PROFILE_AND_DEVICE_ID_FRAGMENT -> 2
-      APP_VERSION_FRAGMENT -> 4
+      PROFILE_EDIT_FRAGMENT -> 2
+      APP_VERSION_FRAGMENT -> 3
+      PROFILE_AND_DEVICE_ID_FRAGMENT -> 4
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentPresenter.kt]: Just confirming, do all of these highlight correctly on tablet?

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @yash10019coder. Sorry for the late review. Overall PR is LGTM, just had a few comments--PTAL.

**Review by rt4914 — APPROVED** [review]
LGTM, Thanks.

File: app/BUILD.bazel (hunk 93 above)
Comment (yash10019coder) [reply app/BUILD.bazel]: done, I don't know why was this missed I also later tried Ctrl Alt L but nothing happened had to do it manually.

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt (hunk 95 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt]: done

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt (hunk 94 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsActivity.kt]: done

File: app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentPresenter.kt (hunk 96 above)
Comment (yash10019coder) [reply app/src/main/java/org/oppia/android/app/administratorcontrols/AdministratorControlsFragmentPresenter.kt]: reverted it as no recycler view adapter is created for ProfileEditFragment.

**Review by yash10019coder — COMMENTED** [review]
Hi @BenHenning Made the requested changes PTAL thanks.

File: app/BUILD.bazel (hunk 93 above)
Comment (BenHenning) [reply app/BUILD.bazel]: If you're using Android Studio with Bazel, sometimes Buildifier doesn't run and requires an IDE restart. :(

**Review by BenHenning — APPROVED** [review]
Thanks @yash10019coder! This LGTM.
