### PR TITLE
Fixes #4098: Added tests for ComparableOperationSubjectTest

### LINKED ISSUE #4098: Add tests for ComparableOperationSubject
#4049 introduces a new custom Truth test subject: ComparableOperationSubject. It would be advantageous to add thorough tests for this to ensure that:
- Each of the subject & comparator methods correctly allow users to test specific properties of the protos each subject helps verify
- Each of the subject & comparator methods are verified to fail when expected (i.e. when used with an incompatible proto property) with the correct failure reason being verified

See #4097 for a similar issue.

### PR DESCRIPTION
**Pull request by theayushyadav11**
Fixes #4098:
This pull request includes changes to add tests for the `ComparableOperationSubject` class and update the build configuration to include these tests. The most important changes are:

### Test Additions:

* Added tests for `ComparableOperationSubject`

### Build Configuration:

* Added a new `oppia_android_test` target for `ComparableOperationSubjectTest` in the `BUILD.bazel` file to include the necessary dependencies and configuration for running the tests.
#### Screenshot of the passing tests.
image

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

### CODE REVIEW

**Comment by theayushyadav11** [comment]
Hi @adhiamboperes PTAL, and suggest me any changes if needed.

**Comment by theayushyadav11** [comment]
Hi @adhiamboperes , this PR is ready for review PTAL.

**Comment by theayushyadav11** [comment]
Hi @adhiamboperes , this PR is ready for review PTAL and please suggest the needed changes in the code.
Thanks!

File: testing/src/test/java/org/oppia/android/testing/math/ComparableOperationSubjectTest.kt [hunk 1]
```diff
@@ -0,0 +1,429 @@
...
+      .setIsInverted(true)
+      .build()
+
+    assertThat(operation).hasStructureThatMatches {
+      hasInvertedPropertyThat().isTrue()
+    }
+  }
+
+  @Test
+  fun testComparableOperationSubject_commutativeAccumulation_withValidSummation() {
```
Comment (adhiamboperes) [inline testing/src/test/java/org/oppia/android/testing/math/ComparableOperationSubjectTest.kt:105]:
```suggestion
  fun testComparableOperationSubject_commutativeAccumulation_withValidSummation_hasCorrectStructure() {
```

File: testing/src/test/java/org/oppia/android/testing/math/ComparableOperationSubjectTest.kt [hunk 2]
```diff
@@ -0,0 +1,429 @@
...
+          constantTerm {
+            withValueThat().isIntegerThat().isEqualTo(2)
+          }
+        }
+      }
+    }
+  }
+
+  @Test
+  fun testComparableOperationSubject_commutativeAccumulation_withEmptyAccumulation() {
```
Comment (adhiamboperes) [inline testing/src/test/java/org/oppia/android/testing/math/ComparableOperationSubjectTest.kt]:
```suggestion
  fun testComparableOperationSubject_commutativeAccumulation_withEmptyAccumulation_hasCorrectStructure() {
```

File: testing/src/test/java/org/oppia/android/testing/math/ComparableOperationSubjectTest.kt [hunk 3]
```diff
@@ -0,0 +1,429 @@
...
+        ComparableOperation.CommutativeAccumulation
+          .AccumulationType.SUMMATION
+      ) {
+        hasOperandCountThat().isEqualTo(0)
+      }
+    }
+  }
+
+  @Test
+  fun testComparableOperationSubject_commutativeAccumulationFailsWithInvalidType() {
```
Comment (adhiamboperes) [inline testing/src/test/java/org/oppia/android/testing/math/ComparableOperationSubjectTest.kt]:
```suggestion
  fun testComparableOperationSubject_commutativeAccumulation_failsWithInvalidType() {
```

File: testing/src/test/java/org/oppia/android/testing/math/ComparableOperationSubjectTest.kt [hunk 4]
```diff
@@ -0,0 +1,429 @@
...
+              withValueThat().isIntegerThat().isEqualTo(3)
+            }
+          }
+        }
+      }
+    }
+  }
+
+  @Test
+  fun testComparableOperationSubject_exponentiationFailsWithInvalidOperation() {
```
Comment (adhiamboperes) [inline testing/src/test/java/org/oppia/android/testing/math/ComparableOperationSubjectTest.kt]:
```suggestion
  fun testComparableOperationSubject_exponentiation_failsWithInvalidOperation() {
```

File: testing/src/test/java/org/oppia/android/testing/math/ComparableOperationSubjectTest.kt [hunk 5]
```diff
@@ -0,0 +1,429 @@
...
+      assertThat(operation).hasStructureThatMatches {
+        nonCommutativeOperation {
+          exponentiation { }
+        }
+      }
+    }
+  }
+
+  @Test
+  fun testComparableOperationSubject_squareRoot_withValidOperation() {
```
Comment (adhiamboperes) [inline testing/src/test/java/org/oppia/android/testing/math/ComparableOperationSubjectTest.kt]:
```suggestion
  fun testComparableOperationSubject_squareRoot_withValidOperation_hasCorrectStructure() {
```

File: testing/src/test/java/org/oppia/android/testing/math/ComparableOperationSubjectTest.kt [hunk 6]
```diff
@@ -0,0 +1,429 @@
...
+              }
+            }
+          }
+        }
+      }
+    }
+  }
+
+  @Test
+  fun testComparableOperationSubject_checksConstantTerm_withValidValue() {
```
Comment (adhiamboperes) [inline testing/src/test/java/org/oppia/android/testing/math/ComparableOperationSubjectTest.kt:323]:
```suggestion
  fun testComparableOperationSubject_checksConstantTerm_withValidValue_hasCorrectStructure() {
```

File: testing/src/test/java/org/oppia/android/testing/math/ComparableOperationSubjectTest.kt [hunk 7]
```diff
@@ -0,0 +1,429 @@
...
+      assertThat(operation).hasStructureThatMatches {
+        constantTerm {
+          withValueThat().isIntegerThat().isEqualTo(42)
+        }
+      }
+    }
+  }
+
+  @Test
+  fun testComparableOperationSubject_validatesVariableTerm() {
```
Comment (adhiamboperes) [inline testing/src/test/java/org/oppia/android/testing/math/ComparableOperationSubjectTest.kt]:
```suggestion
  fun testComparableOperationSubject_withVariableTerm_hasExpectedName() {
```

File: testing/src/test/java/org/oppia/android/testing/math/ComparableOperationSubjectTest.kt [hunk 8]
```diff
@@ -0,0 +1,429 @@
...
+    val operation = createVariableOperation("x")
+
+    assertThat(operation).hasStructureThatMatches {
+      variableTerm {
+        withNameThat().isEqualTo("x")
+      }
+    }
+  }
+
+  @Test(expected = AssertionError::class)
```
Comment (adhiamboperes) [inline testing/src/test/java/org/oppia/android/testing/math/ComparableOperationSubjectTest.kt]: Please refeactor per existing patterns.

File: testing/src/test/java/org/oppia/android/testing/math/ComparableOperationSubjectTest.kt [hunk 9]
```diff
@@ -0,0 +1,429 @@
...
+
+    assertThat(operation).hasStructureThatMatches {
+      variableTerm {
+        withNameThat().isEqualTo("x")
+      }
+    }
+  }
+
+  @Test
+  fun testComparableOperationSubject_complexExpression_withNestedOperations() {
```
Comment (adhiamboperes) [inline testing/src/test/java/org/oppia/android/testing/math/ComparableOperationSubjectTest.kt]:
```suggestion
  fun testComparableOperationSubject_complexExpression_withNestedOperations_hasCorrectStructure() {
```

File: testing/src/test/java/org/oppia/android/testing/math/ComparableOperationSubjectTest.kt [hunk 10]
```diff
@@ -0,0 +1,429 @@
...
+            .AccumulationType.SUMMATION
+        ) {
+          index(1) { }
+        }
+      }
+    }
+  }
+
+  @Test
+  fun testComparableOperationSubject_matchesWithValidOperation() {
```
Comment (adhiamboperes) [inline testing/src/test/java/org/oppia/android/testing/math/ComparableOperationSubjectTest.kt:182]:
```suggestion
  fun testComparableOperationSubject_nonCommutativeOperation_hasCorrectStructure() {
```

File: testing/src/test/java/org/oppia/android/testing/math/ComparableOperationSubjectTest.kt [hunk 11]
```diff
@@ -0,0 +1,429 @@
...
+  fun testComparableOperationSubject_hasInvertedProperty() {
+    val operation = ComparableOperation.newBuilder()
+      .setConstantTerm(Real.newBuilder().setInteger(42))
+      .setIsInverted(true)
+      .build()
+
+    assertThat(operation).hasStructureThatMatches {
+      hasInvertedPropertyThat().isTrue()
+    }
+  }
```
Comment (adhiamboperes) [inline testing/src/test/java/org/oppia/android/testing/math/ComparableOperationSubjectTest.kt]: For these 2 add in test name the condition for returning true and false.

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @theayushyadav11! PTAL.

**Comment by theayushyadav11** [comment]
Thanks @adhiamboperes for the review, I have updated the code PTAL and please suggest me any changes if required.

**Comment by theayushyadav11** [comment]
Hi @adhiamboperes , I have addressed all the comments, PTAL.

**Review by adhiamboperes — APPROVED** [review]
LGTM, Thanks!
