### PR TITLE
Fix #4135, Fix part of #5070: In FractionInteraction UI, leave submit button enabled when answer is empty.

### LINKED ISSUE #4135: Add tests for FractionInputInteractionView
FractionInputInteractionView should have dedicated tests to verify that it behaves correctly as an interaction. Today, it's tested through InputInteractionViewTestActivity, but these tests ought to be moved to a dedicated test suite for fraction input, and other fraction-specific tests should be added.

### PR DESCRIPTION
**Pull request by masclot**
Fix part of https://github.com/oppia/oppia-android/issues/5070: In FractionInteraction UI, leave submit button enabled when answer is empty. Show an error on submitting an empty answer. The error message already exists and is the same as in https://github.com/oppia/oppia/pull/18379.

Demo video: [leave_submit_button_enabled_on_empty_answer_v3.webm](https://github.com/oppia/oppia-android/assets/103062089/d072ae88-c462-455c-a324-57680d4a82c5)

The new error messages for empty inputs on submit are listed here: [oppia/design-team#71(comment)](https://github.com/oppia/design-team/issues/71#issuecomment-1581232000)

I added an accessibility-label exemption for FractionInputInteractionViewTestActivity as this activity is only used in tests.

Fix #4135: incidentaly, this change also fixes #4135, since I had to split the tests for FractionInputInteraction

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- For PRs introducing new UI elements or color changes, both light and dark mode screenshots must be included
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### CODE REVIEW

File: utility/src/main/java/org/oppia/android/util/math/FractionParser.kt [hunk 1]
```diff
@@ -130,6 +134,9 @@ class FractionParser {
      * Indicates that at least one of the numbers present in the string is too long to be
      * precisely represented in a fraction.
      */
-    NUMBER_TOO_LONG
+    NUMBER_TOO_LONG,
+
+    /** The input text was empty. */
```
Comment (adhiamboperes) [inline utility/src/main/java/org/oppia/android/util/math/FractionParser.kt]:
```suggestion
    /** Indicates that the input text was empty. */
```

File: app/src/test/java/org/oppia/android/app/parser/FractionParsingUiErrorTest.kt [hunk 2]
```diff
@@ -165,7 +165,7 @@ class FractionParsingUiErrorTest {
         .toUiError()
         .getErrorMessageFromStringRes(activity.appLanguageResourceHandler)
       assertThat(errorMessage)
-        .isEqualTo("Please enter a valid fraction (e.g., 5/3 or 1 2/3)")
+        .isEqualTo("Enter a fraction to continue")
```
Comment (adhiamboperes) [inline app/src/test/java/org/oppia/android/app/parser/FractionParsingUiErrorTest.kt]: In your demo video, it shows the original error text, not this one. Could you please confirm that?

File: app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/FractionInteractionViewModel.kt [hunk 3]
```diff
@@ -64,23 +69,25 @@ class FractionInteractionViewModel private constructor(
...
-        AnswerErrorCategory.REAL_TIME -> {
+    when (category) {
+      AnswerErrorCategory.REAL_TIME -> {
+        if (answerText.isNotEmpty()) {
           pendingAnswerError =
             FractionParsingUiError.createFromParsingError(
               fractionParser.getRealTimeAnswerError(answerText.toString())
             ).getErrorMessageFromStringRes(resourceHandler)
+        } else {
+          pendingAnswerError = null
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/FractionInteractionViewModel.kt:80]: Isn't this supposed to show an error too from the list of errors?

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Had some questions: Please see inline.

File: app/src/test/java/org/oppia/android/app/parser/FractionParsingUiErrorTest.kt (hunk 2 above)
Comment (masclot) [reply app/src/test/java/org/oppia/android/app/parser/FractionParsingUiErrorTest.kt]: I changed the message after I recorded the video. I can update the video if you want.

Comment (adhiamboperes) [reply app/src/test/java/org/oppia/android/app/parser/FractionParsingUiErrorTest.kt]: Your final solution should include the latest recording

File: app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/FractionInteractionViewModel.kt (hunk 3 above)
Comment (masclot) [reply app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/FractionInteractionViewModel.kt:80]: My understanding is that the message should show on submit only, not while the user is typing, or waiting to type,  the answer. Otherwise we would show an error message in the resting state, when the user did not input any answer, in which case we could keep the submit button disabled.

File: utility/src/main/java/org/oppia/android/util/math/FractionParser.kt (hunk 1 above)
Comment (masclot) [reply utility/src/main/java/org/oppia/android/util/math/FractionParser.kt]: Done

File: app/src/test/java/org/oppia/android/app/parser/FractionParsingUiErrorTest.kt (hunk 2 above)
Comment (masclot) [reply app/src/test/java/org/oppia/android/app/parser/FractionParsingUiErrorTest.kt]: Done

**Comment by masclot** [comment]
This PR should be complete now.
Please @adhiamboperes PTAL

File: utility/src/main/java/org/oppia/android/util/math/FractionParser.kt [hunk 4]
```diff
@@ -24,6 +25,9 @@ class FractionParser {
    * detection should be done using [getRealTimeAnswerError], instead.
    */
   fun getSubmitTimeError(text: String): FractionParsingError {
+    if (TextUtils.isEmpty(text)) {
```
Comment (adhiamboperes) [inline utility/src/main/java/org/oppia/android/util/math/FractionParser.kt]: Any reason you used this instead of Kotlin's `isEmpty()/isBlank()`?

File: app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt [hunk 5]
```diff
@@ -140,400 +140,6 @@ class InputInteractionViewTestActivityTest {
     ApplicationProvider.getApplicationContext<TestApplication>().inject(this)
   }
 
-  // TODO(#4135): Move fraction input tests to a dedicated test suite.
```
Comment (adhiamboperes) [inline app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt:143]: Now that this is done, this PR should also reference #4135 to close it.

File: app/src/sharedTest/java/org/oppia/android/app/testing/FractionInputInteractionViewTestActivityTest.kt [hunk 6]
```diff
@@ -0,0 +1,608 @@
...
+            )
+          )
+        )
+    }
+  }
+
+  @Test
+  @DisableAccessibilityChecks // Disabled, as FractionInputInteractionViewTestActivity is a test file and
+  // will not be used by user
+  fun testFractionInput_noInput_submit_errorIsDisplayed() {
```
Comment (adhiamboperes) [inline app/src/sharedTest/java/org/oppia/android/app/testing/FractionInputInteractionViewTestActivityTest.kt]: Nit: More descriptive.
```suggestion
  fun testFractionInput_emptyInput_submit_errorIsDisplayed() {
```

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @masclot, and apologies for the delay in review. I have left a few minor comments, but this approach looks good to me.

File: app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt (hunk 5 above)
Comment (masclot) [reply app/src/sharedTest/java/org/oppia/android/app/testing/InputInteractionViewTestActivityTest.kt:143]: I added "Fix #4135" to the PR description

File: utility/src/main/java/org/oppia/android/util/math/FractionParser.kt (hunk 4 above)
Comment (masclot) [reply utility/src/main/java/org/oppia/android/util/math/FractionParser.kt]: Not really. TextUtils also checks for nullness, so in the android-Java world it is safer to use, and I keep using it without thinking too much. I don't mind switching to kotlin's isEmpty if you think it is better.

File: app/src/sharedTest/java/org/oppia/android/app/testing/FractionInputInteractionViewTestActivityTest.kt (hunk 6 above)
Comment (masclot) [reply app/src/sharedTest/java/org/oppia/android/app/testing/FractionInputInteractionViewTestActivityTest.kt]: Done

**Comment by masclot** [comment]
@adhiamboperes PTAL. Should I also include @BenHenning as reviewer?

File: utility/src/main/java/org/oppia/android/util/math/FractionParser.kt (hunk 4 above)
Comment (adhiamboperes) [reply utility/src/main/java/org/oppia/android/util/math/FractionParser.kt]: In the project, we mainly use kotlin extension functions for things like these, even though the functionality is basically the same. It is up to you to change it.

If you want to consider a string with only whitespace characters as empty, use isBlank().

**Review by adhiamboperes — APPROVED** [review]
Thanks @masclot, this LGTM.

@BenHenning, I am happy with this solution, but could you take a high level pass to verify the approach?

File: app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/FractionInteractionViewModel.kt [hunk 7]
```diff
@@ -43,12 +43,17 @@ class FractionInteractionViewModel private constructor(
         override fun onPropertyChanged(sender: Observable, propertyId: Int) {
           errorOrAvailabilityCheckReceiver.onPendingAnswerErrorOrAvailabilityCheck(
             pendingAnswerError,
-            answerText.isNotEmpty()
+            true // Allow submit on empty answer
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/FractionInteractionViewModel.kt]:
```suggestion
            inputAnswerAvailable = true // Allow submit on empty answer.
```

File: app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/FractionInteractionViewModel.kt [hunk 8]
```diff
@@ -43,12 +43,17 @@ class FractionInteractionViewModel private constructor(
...
           )
         }
       }
     errorMessage.addOnPropertyChangedCallback(callback)
     isAnswerAvailable.addOnPropertyChangedCallback(callback)
+    // Apply defaults:
+    errorOrAvailabilityCheckReceiver.onPendingAnswerErrorOrAvailabilityCheck(
+      null,
+      true
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/FractionInteractionViewModel.kt]: Ditto here--please add the method argument names when passing literal values to help make the code more self-documenting.

File: app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/FractionInteractionViewModel.kt [hunk 9]
```diff
@@ -43,12 +43,17 @@ class FractionInteractionViewModel private constructor(
...
           errorOrAvailabilityCheckReceiver.onPendingAnswerErrorOrAvailabilityCheck(
             pendingAnswerError,
-            answerText.isNotEmpty()
+            true // Allow submit on empty answer
           )
         }
       }
     errorMessage.addOnPropertyChangedCallback(callback)
     isAnswerAvailable.addOnPropertyChangedCallback(callback)
+    // Apply defaults:
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/FractionInteractionViewModel.kt]: Could you expand in this comment on why the default call below is needed? It's not obvious to me as a reader, so I suspect it will also be unclear for future folks who come across this code in isolation (vs. in the context of the broader PR).

File: app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/MathExpressionInteractionsViewModel.kt [hunk 10]
```diff
@@ -73,6 +73,9 @@ class MathExpressionInteractionsViewModel private constructor(
    * bound to the corresponding edit text.
    */
   var answerText: CharSequence = ""
+    set(value) {
+      field = value.toString().trim()
+    }
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/MathExpressionInteractionsViewModel.kt:81]: Why is this change needed? Seems a bit complicated, so it'd be nice to better understand.

File: app/src/main/res/values/strings.xml [hunk 11]
```diff
@@ -166,6 +166,7 @@
   <string name="fraction_error_invalid_format">Please enter a valid fraction (e.g., 5/3 or 1 2/3)</string>
   <string name="fraction_error_divide_by_zero">Please do not put 0 in the denominator</string>
   <string name="fraction_error_larger_than_seven_digits">None of the numbers in the fraction should have more than 7 digits.</string>
+  <string name="fraction_error_empty_input">Enter a fraction to continue</string>
```
Comment (BenHenning) [inline app/src/main/res/values/strings.xml]:
```suggestion
  <string name="fraction_error_empty_input">Enter a fraction to continue.</string>
```

File: utility/src/main/java/org/oppia/android/util/math/FractionParser.kt (hunk 4 above)
Comment (BenHenning) [reply utility/src/main/java/org/oppia/android/util/math/FractionParser.kt]: Kotlin also has ``isNullOrBlank`` but the nullness check isn't necessary since we can statically guarantee non-nullness at this point.

I think I also lean toward not using TextUtils here. The more we depend on Android in the utility module the harder it will be to abstract away Android functionality in the future (so we should only depend on Android when absolutely necessary) in the event we want to support more than just Android with this codebase.

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @masclot! This looks really good. Just had a few comments--PTAL.

File: app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/MathExpressionInteractionsViewModel.kt (hunk 10 above)
Comment (masclot) [reply app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/MathExpressionInteractionsViewModel.kt:81]: This change was already done by the TextWatcher. This was a bug, because the binding would also set this field, but without applying the same modification. I added a comment. Let me know if it is clear enough.

File: app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/FractionInteractionViewModel.kt (hunk 9 above)
Comment (masclot) [reply app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/FractionInteractionViewModel.kt]: Updated the doc

File: app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/FractionInteractionViewModel.kt (hunk 7 above)
Comment (masclot) [reply app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/FractionInteractionViewModel.kt]: Done

File: app/src/main/res/values/strings.xml (hunk 11 above)
Comment (masclot) [reply app/src/main/res/values/strings.xml]: Done

File: utility/src/main/java/org/oppia/android/util/math/FractionParser.kt (hunk 4 above)
Comment (masclot) [reply utility/src/main/java/org/oppia/android/util/math/FractionParser.kt]: Changed to isNullOrBlank.

File: app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/FractionInteractionViewModel.kt (hunk 8 above)
Comment (masclot) [reply app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/FractionInteractionViewModel.kt]: Done

**Comment by masclot** [comment]
@BenHenning PTAL

File: app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/MathExpressionInteractionsViewModel.kt (hunk 10 above)
Comment (BenHenning) [reply app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/MathExpressionInteractionsViewModel.kt:81]: This helps--thanks.

**Review by BenHenning — APPROVED** [review]
Thanks @masclot! Really sorry for the delayed review. This LGTM.
