### PR TITLE
Fix #6004: Submit Button in Admin Auth not Working

### LINKED ISSUE #6004: [BUG]: No response upon clicking submit at add new profile screen.
### Describe the bug

In the developer mode of the app after setting up administrator's pin and adding profiles, if trying to add new profile entering administrator pin and clicking submit has no response.

### Steps To Reproduce

1. Setup app , administrator's pin, profiles after first time opening the app.
2. Restart app.
3. Go to add new profile screen and try to submit pin.

### Expected Behavior

Some kind of menu should be opening to let the user add new profiles by entering username, profile picture.

### Screenshots/Videos

Image

### What device/emulator are you using?

Samsung M13

### Which Android version is your device/emulator running?

Android 14

### Which version of the Oppia Android app are you using?

0.16-dev-be1ac4b29b

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by adhiamboperes**
## Explanation

Fix #6004:

#5955 introduced a change that requires the admin to be logged in before being able to add a profile. For reasons why this was needed, please see https://github.com/oppia/oppia-android/issues/5906. This change exposed a bug in the navigation logic for creating the `AdminAuthActivity` intent from the Profile Chooser. The profile Id provided was -1, an invalid profile, instead of the actual admin profile. This caused the login flow to fail, since no matching profile was found. 

This PR fixes the bug by passing in the admin's profile.

Tests have been modified to verify the value of the profileId passed. 

This fix can be made more robust by the implementation of https://github.com/oppia/oppia-android/issues/5440.

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- For PRs introducing new UI elements or color changes, both light and dark mode screenshots must be included
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### Proof of the tests failing before the fix
Screenshot 2025-11-24 at 01 23 25

### Videos
|Before|After|
|---|---|
|https://github.com/user-attachments/assets/0c7bacf1-e4b8-420e-8a1a-52de3a6213bb|https://github.com/user-attachments/assets/8badd9c2-cd78-4f93-95e4-1269728091b3|

### CODE REVIEW

**Review by adhiamboperes — COMMENTED** [review]
Self-reviewed. LGTM.

**Comment by adhiamboperes** [comment]
@manas-yu, @BenHenning, PTAL.

File: app/src/main/java/org/oppia/android/app/profile/AdminAuthActivityPresenter.kt [hunk 1]
```diff
@@ -30,6 +31,7 @@ class AdminAuthActivityPresenter @Inject constructor(
   private val profileManagementController: ProfileManagementController,
 ) {
   private lateinit var binding: AdminAuthActivityBinding
+  private var profileId = ProfileId.getDefaultInstance()
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/profile/AdminAuthActivityPresenter.kt]: Why does this need to be a field? Can't it be kept as a local?

It's definitely better to avoid defaulting to a default instance since that _can_ be a valid profile ID (and the reason why #5440 was filed actually).

**Review by BenHenning — APPROVED** [review]
Thanks @adhiamboperes! Approving since this is an urgent PR, but I do think you should rework the changes in the activity presenter to avoid using the default instance. I'm happy to do another review pass if needed, but otherwise feel free to resolve the comment and merge once addressed.

File: app/src/main/java/org/oppia/android/app/profile/AdminAuthActivityPresenter.kt (hunk 1 above)
Comment (adhiamboperes) [reply app/src/main/java/org/oppia/android/app/profile/AdminAuthActivityPresenter.kt]: I have made the variable local to`adminAuthSubmitButton.setOnClickListener` and removed the  default instance initialization, thanks!

Comment (adhiamboperes) [reply app/src/main/java/org/oppia/android/app/profile/AdminAuthActivityPresenter.kt]: Merging since it’s a straightforward change.
