### PR TITLE
Fix #2587: testHomeActivity_allTopicsCompleted_displaysAllTopicCards() test not working

### LINKED ISSUE #2587: Fix test testHomeActivity_allTopicsCompleted_displaysAllTopicCards
`testHomeActivity_allTopicsCompleted_displaysAllTopicCards()` in `HomeActivityTest` fails when running using Espresso in an Android emulator with a tablet image, because of the bigger screen size. (All tests pass in Robolectric.)

Other similar test methods covering "topics":
* Have 4 versions, split into portrait/landscape and mobile/tablet.
* Also assert the number of cards (topics).

Suggested fix:
* Similarly split test method into 4 versions, ensuring tablet tests pass for tablets, etc.
* Consider introducing another helper for the topic card count assertion.

_Originally posted by @yurilev in https://github.com/oppia/oppia-android/issues/2504#issuecomment-770044052_

### PR DESCRIPTION
**Pull request by deonwaju**
## Explanation

Fix for #2587: split test method into 4 versions, [mobilePortrait, mobileLandscape, tabletPortrait, tabletLandscape]

A. Mobile potrait test
mobile-port

B. Mobile Lanscape
mobile-landscape

C. Tablet Portrait
tablet-port

D. Tablet Landscape test.
tablet-land

## Essential Checklist

- [X] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [X] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [X] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [X] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [X] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [X] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

### CODE REVIEW

**Comment by deonwaju** [comment]
PTAL @adhiamboperes

File: app/src/sharedTest/java/org/oppia/android/app/home/HomeActivityTest.kt [hunk 1]
```diff
@@ -1333,8 +1333,9 @@ class HomeActivityTest {
     }
   }
 
+  @Config(qualifiers = "+port")
   @Test
-  fun testHomeActivity_allTopicsCompleted_displaysAllTopicCards() {
+  fun testHomeActivity_allTopicsCompleted_mobilePortraitDisplaysAllTopicCardsIn2Columns() {
```
Comment (adhiamboperes) [inline app/src/sharedTest/java/org/oppia/android/app/home/HomeActivityTest.kt]:
```suggestion
  fun testHomeActivity_allTopicsCompleted_mobilePortrait_displaysAllTopicCardsIn2Columns() {
```

Comment (adhiamboperes) [reply app/src/sharedTest/java/org/oppia/android/app/home/HomeActivityTest.kt]: In this test, since the test name specifies mobile landscape, there is no need for checking `if (context.resources.getBoolean(R.bool.isTablet))` as that is now a different test.

The same applies to the rest of the tests.

File: app/src/sharedTest/java/org/oppia/android/app/home/HomeActivityTest.kt [hunk 2]
```diff
@@ -1352,6 +1353,58 @@ class HomeActivityTest {
     }
   }
 
+  @Config(qualifiers = "+land")
+  @Test
+  fun testHomeActivity_allTopicsCompleted_mobileLandscapeDisplaysAllTopicCardsIn3Columns() {
```
Comment (adhiamboperes) [inline app/src/sharedTest/java/org/oppia/android/app/home/HomeActivityTest.kt]:
```suggestion
  fun testHomeActivity_allTopicsCompleted_mobileLandscape_displaysAllTopicCardsIn3Columns() {
```

File: app/src/sharedTest/java/org/oppia/android/app/home/HomeActivityTest.kt [hunk 3]
```diff
@@ -1352,6 +1353,58 @@ class HomeActivityTest {
...
+        verifyHomeRecyclerViewHasGridColumnCount(columnCount = 4)
+      } else {
+        verifyHomeRecyclerViewHasGridColumnCount(columnCount = 3)
+      }
+    }
+  }
+
+  @Config(qualifiers = "+sw600dp-port")
+  @Test
+  fun testHomeActivity_allTopicsCompleted_tabletPortraitDisplaysAllTopicCardsIn3Columns() {
```
Comment (adhiamboperes) [inline app/src/sharedTest/java/org/oppia/android/app/home/HomeActivityTest.kt]:
```suggestion
  fun testHomeActivity_allTopicsCompleted_tabletPortrait_displaysAllTopicCardsIn3Columns() {
```

File: app/src/sharedTest/java/org/oppia/android/app/home/HomeActivityTest.kt [hunk 4]
```diff
@@ -1352,6 +1353,58 @@ class HomeActivityTest {
...
+    launch<HomeActivity>(createHomeActivityIntent(internalProfileId)).use {
+      testCoroutineDispatchers.runCurrent()
+      scrollToPosition(position = 3)
+      verifyHomeRecyclerViewHasGridColumnCount(columnCount = 3)
+    }
+  }
+
+  @Config(qualifiers = "+sw600dp-land")
+  @Test
+  fun testHomeActivity_allTopicsCompleted_tabletLandscapeDisplaysAllTopicCardsIn4Columns() {
```
Comment (adhiamboperes) [inline app/src/sharedTest/java/org/oppia/android/app/home/HomeActivityTest.kt]:
```suggestion
  fun testHomeActivity_allTopicsCompleted_tabletLandscape_displaysAllTopicCardsIn4Columns() {
```

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @deonwaju!

In addition to my inline comments, can you please share a screenshot that shows you ran these tests on an emulator/device and they passed? The issues describes the tests failing in tablet so we need proof that they now pass in tablets.

One more thing, was the issue reproducible before you wrote the fix? I find it strange that the original test had no prior configurations that limited it to running on robolectric, or ignoring it yet we had no reported failures(It's great that this PR increases the test coverage, but I'd like to check).

**Comment by deonwaju** [comment]
> Thanks @deonwaju!
> 
> In addition to my inline comments, can you please share a screenshot that shows you ran these tests on an emulator/device and they passed? The issues describes the tests failing in tablet so we need proof that they now pass in tablets.
> 
> One more thing, was the issue reproducible before you wrote the fix? I find it strange that the original test had no prior configurations that limited it to running on robolectric, or ignoring it yet we had no reported failures(It's great that this PR increases the test coverage, but I'd like to check).

Ok got it, and yes the issue was reproducible, I took your advice to test on a larger tablet screen size, so used a 10" pixel C tablet, and I was able to reproduce the issue. Turns out that the test passes only when the tablet is in portrait mode, in landscape mode it fails. That was the issue

**Comment by deonwaju** [comment]
@adhiamboperes 
Please find attached the screenshots for each of the tests.

A. Mobile portrait test

mobile-potrait

B. Mobile landscape test

mobile-land

C. Tablet portrait test

tablet-portrait

D. Tablet landscape test

tablet-land

**Comment by adhiamboperes** [comment]
@deonwaju, the tests look good. Please complete the test name suggestions and resubmit for approval.

**Comment by deonwaju** [comment]
PTAL @adhiamboperes

**Review by adhiamboperes — APPROVED** [review]
Thanks @deonwaju! This LGTM.
