### PR TITLE
Fix #1762, #2704: Highlight Correct MenuItem after cancelling ExitProfileDialog

### LINKED ISSUE #1762: NavigationDrawer cancel switch profile always mark home
**Describe the bug**
After cancelling the exit profile dialog, home menu get's marked no matter on which menu I was on previously 

**To Reproduce**
Steps to reproduce the behaviour:
1. Open nav drawer
2. click option
3. open nav drawer
4. click switch profile
5. click cancel
6. home gets marked but we are on the options screen

**Expected behaviour**
Mark that menu Item which was on the screen before opening the switch dialog not home as always

### LINKED ISSUE #2704: Incorrect highlighting in Drawer items
**Describe the bug**

**To Reproduce**
1. Go to Home
2. Open Navigation Drawer
3. Click on `Admin Controls`
4. Click default back button
5. Open Navigation Drawer

Notice that both `Home` and `Admin Controls` are highlighted.

**Expected behavior**
Only `Home` screen should remain highlighted in this case.
The similar error occurs for other items too like `Options`, `Help`.

untitled

### PR DESCRIPTION
**Pull request by prayutsu**
## Explanation

Fixes #1762, and fixes #2704 -
Navigation Drawer now highlights the correct menu Item after canceling the ExitProfileDialog, and also after pressing the back button (when some activity is opened from the navigation drawer).

Manual testing video - 
https://user-images.githubusercontent.com/54636525/107812250-6ceda380-6d95-11eb-9d46-5dafb44838c2.mp4

Tests passing on ESPRESSO-
Screenshot from 2021-02-15 10-38-39

New test cases being ignored on Robolectric-
Screenshot from 2021-02-13 15-10-46

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

File: app/src/main/java/org/oppia/android/app/drawer/NavigationDrawerFragmentPresenter.kt [hunk 1]
```diff
@@ -264,13 +267,33 @@ class NavigationDrawerFragmentPresenter @Inject constructor(
   }
 
   fun markHomeMenuCloseDrawer() {
```
Comment (chrk2205) [inline app/src/main/java/org/oppia/android/app/drawer/NavigationDrawerFragmentPresenter.kt]: we can rename it as `markPreviousMenuItemCloseDrawer`
as done in `NavigationDrawerFragment`

File: app/src/main/java/org/oppia/android/app/drawer/NavigationDrawerFragment.kt [hunk 2]
```diff
@@ -40,7 +40,7 @@ class NavigationDrawerFragment :
     navigationDrawerFragmentPresenter.openProfileProgress(profileId)
   }
 
-  override fun markHomeMenuCloseDrawer() {
+  override fun restoreLastCheckedMenuItem() {
```
Comment (chrk2205) [inline app/src/main/java/org/oppia/android/app/drawer/NavigationDrawerFragment.kt]: instead of restore maybe we can go with 
`markPreviousMenuItemCloseDrawer`

**Review by chrk2205 — CHANGES_REQUESTED** [review]

**Comment by prayutsu** [comment]
https://user-images.githubusercontent.com/54636525/107389547-e0d14700-6b1c-11eb-8025-4efe17c7410b.mp4

Now we are facing only 1 bug-

1. Go to Administrator Controls
2. Open NavDrawer and click on Switch Profile
3. Change the configuration of the device
4. The `Switch Profile` Item gets unchecked and `Administrator Controls` gets checked.

File: app/src/main/java/org/oppia/android/app/drawer/NavigationDrawerFragmentPresenter.kt (hunk 1 above)
Comment (prayutsu) [reply app/src/main/java/org/oppia/android/app/drawer/NavigationDrawerFragmentPresenter.kt]: Deferring to @rt4914, since he owns this file.

File: app/src/main/java/org/oppia/android/app/drawer/NavigationDrawerFragment.kt (hunk 2 above)
Comment (prayutsu) [reply app/src/main/java/org/oppia/android/app/drawer/NavigationDrawerFragment.kt]: Deferring to @rt4914, since he owns this file.

Comment (prayutsu) [reply app/src/main/java/org/oppia/android/app/drawer/NavigationDrawerFragment.kt]: Maybe we want to append `CloseDrawer` in the name.

**Comment by BenHenning** [comment]
Honestly from a user perspective I think this looks quite solid @prayutsu. The scenario you described is quite an edge case, and I'm not even sure it can be considered a bug. It does have slight inconsistency with the other configuration change scenarios, but it still seems arguably 'correct' in the context in which it's observed (e.g. you're still in the admin controls page).

File: app/src/main/java/org/oppia/android/app/drawer/NavigationDrawerFragmentPresenter.kt [hunk 3]
```diff
@@ -263,14 +266,34 @@ class NavigationDrawerFragmentPresenter @Inject constructor(
...
+          false
+      } else {
+        binding.fragmentDrawerNavView.menu.getItem(
+          NavigationDrawerItem.valueFromNavId(
+            lastCheckedMenuItemValue
+          ).ordinal
+        ).isChecked =
+          true
+      }
+    }
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/drawer/NavigationDrawerFragmentPresenter.kt]:
```suggestion
    previousMenuItemId?.let { itemId ->
      if (itemId == 0) {
        getFooterViewModel().isAdministratorControlsSelected.set(true)
        uncheckAllMenuItemsWhenAdministratorControlsIsSelected()
        binding.fragmentDrawerNavView.menu.getItem(
          NavigationDrawerItem.SWITCH_PROFILE.ordinal
        ).isChecked =
          false
      } else {
        binding.fragmentDrawerNavView.menu.getItem(
          NavigationDrawerItem.valueFromNavId(itemId).ordinal
        ).isChecked = true
      }
    }
```

More Kotlin-idiomatic.

File: app/src/main/java/org/oppia/android/app/drawer/NavigationDrawerFragmentPresenter.kt [hunk 4]
```diff
@@ -263,14 +266,34 @@ class NavigationDrawerFragmentPresenter @Inject constructor(
...
+  fun restoreLastCheckedMenuItem() {
+    if (previousMenuItemId != null) {
+      val lastCheckedMenuItemValue: Int = previousMenuItemId!!
+      if (lastCheckedMenuItemValue == 0) {
+        getFooterViewModel().isAdministratorControlsSelected.set(true)
+        uncheckAllMenuItemsWhenAdministratorControlsIsSelected()
+        binding.fragmentDrawerNavView.menu.getItem(
+          NavigationDrawerItem.SWITCH_PROFILE.ordinal
+        ).isChecked =
+          false
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/drawer/NavigationDrawerFragmentPresenter.kt]: This seems a bit hacky to me. The navigation drawer in general should not specialize its behavior for how it's used outside of the drawer. Given that we have a separate call path for the exit dialog flow, could we use a different method to specifically handle this case via ExitProfileDialogFragment?

**Review by BenHenning — COMMENTED** [review]
Thanks @prayutsu. This is definitely moving toward the right solution. Just have a few specific thoughts on the exact mechanism being built into the navigation drawer presenter. PTAL.

File: app/src/main/java/org/oppia/android/app/drawer/NavigationDrawerFragmentPresenter.kt (hunk 3 above)
Comment (prayutsu) [reply app/src/main/java/org/oppia/android/app/drawer/NavigationDrawerFragmentPresenter.kt]: Done.

File: app/src/main/java/org/oppia/android/app/drawer/NavigationDrawerFragmentPresenter.kt (hunk 4 above)
Comment (prayutsu) [reply app/src/main/java/org/oppia/android/app/drawer/NavigationDrawerFragmentPresenter.kt]: Tried modifying it a bit.

Also, as per your comment in the previous PR, I am adding all the possibilities that we need to cover - 

1. When the dialog is created from the Nav drawer then we need to restore the menu item (it can be either `Administrator Controls`  or one of the 5 menuItems).
2. When the dialog is created by pressing the back button from the HomeActivity then we don't want to restore any of the items.

So, if we consider two variables `x` and `y` where `x` denotes the restoration of MenuItem and `y` denotes the restoration of Administrator Controls then either both of them are false or exactly one of them is true.

File: model/src/main/proto/arguments.proto [hunk 5]
```diff
@@ -0,0 +1,22 @@
...
+  oneof highlight_item {
+    // Whether any menu item needs to be highlighted or not.
+    bool highlight_none = 1;
+
+    // Whether some menuItem from the Navigation Drawer menu needs to be highlighted or not.
+    bool highlight_last_checked_menu_item = 2;
+
+    // Whether Administrator Controls item from the Navigation Drawer footer needs to be
+    // highlighted or not.
+    bool highlight_administrator_controls_item = 3;
```
Comment (prayutsu) [inline model/src/main/proto/arguments.proto]: I also had a second thought to create an enum in place of these two, it may look more cleaner because they both are mutually exclusive (but not exhaustive).

**Review by prayutsu — COMMENTED** [review]
Tried some modifications, PTAL @BenHenning.

File: app/src/main/java/org/oppia/android/app/drawer/ExitProfileDialogFragment.kt [hunk 6]
```diff
@@ -38,33 +42,47 @@ class ExitProfileDialogFragment : DialogFragment() {
...
-      false
+    val exitProfileDialogArguments = args.getProto(
+      EXIT_PROFILE_DIALOG_ARGUMENTS_PROTO,
+      ExitProfileDialogArguments.getDefaultInstance()
     )
 
-    if (isFromNavigationDrawer) {
+    val restoreLastCheckedItem = when (exitProfileDialogArguments.highlightItemCase) {
+      ExitProfileDialogArguments.HighlightItemCase.HIGHLIGHT_NONE -> false
+      else -> true
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/drawer/ExitProfileDialogFragment.kt]: I think you might want to invert this (e.g. only set it true for the cases where restoration should happen) since there are auto-generated constants being included in the 'else' (such as unspecified).

File: app/src/main/java/org/oppia/android/app/drawer/NavigationDrawerFragmentPresenter.kt (hunk 4 above)
Comment (BenHenning) [reply app/src/main/java/org/oppia/android/app/drawer/NavigationDrawerFragmentPresenter.kt]: The case you described (either both false or one is true) exactly what a proto oneof enforces (or a sealed class with an 'other' child). Given we're already trying to use proto to model this, I think your latest oneof is much closer to the ideal state.

I think the presenter is closer to the ideal state, too, but the part I still don't quite understand is why we need to specialize for administrator controls. Leaving another comment to focus on a potential alternative.

File: app/src/main/java/org/oppia/android/app/drawer/NavigationDrawerFragmentPresenter.kt [hunk 7]
```diff
@@ -244,8 +242,25 @@ class NavigationDrawerFragmentPresenter @Inject constructor(
           if (previousFragment != null) {
             fragment.childFragmentManager.beginTransaction().remove(previousFragment).commitNow()
           }
+          val exitProfileDialogArguments =
+            if (getFooterViewModel().isAdministratorControlsSelected.get() == true) {
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/drawer/NavigationDrawerFragmentPresenter.kt:247]: This is the part I'm still confused about. Why do we need to specialize the behavior for admin controls/why does it need to be treated differently than everything else? I think we can probably avoid this tight coupling, but I need to better understand why admin controls is special.

File: model/src/main/proto/arguments.proto (hunk 5 above)
Comment (vinitamurthi) [reply model/src/main/proto/arguments.proto]: I was going to ask the same thing, I think an enum seems to work better here

File: app/src/main/java/org/oppia/android/app/drawer/NavigationDrawerFragmentPresenter.kt (hunk 7 above)
Comment (prayutsu) [reply app/src/main/java/org/oppia/android/app/drawer/NavigationDrawerFragmentPresenter.kt:247]: This is really a good point, so I am adding what I understand 
1. `Administrator Controls` is not exactly a menuItem like Home, Options, etc.
2. If we navigate between the fragments/activities associated with the NavDrawer Menu Items (Home, Options, Switch Profile, Help, Downloads), then the `NavigationDrawerMenuItem` itself manages the highlighting/unhighlighting the corresponding menuItem (we just need to set `.isChecked = true` for one item and it will automatically unhighlight the previous item).
3. But as `Administrator Controls` item is not a part of the NavigationDrawer menu item, we can't apply `.ischecked` property on it (so we explicitly change the color of text "Administrator Controls" when `isAdministratorControlsSelected` is true) so it doesn't automatically unhighlight the color of the previous menu item. Now, suppose we are in Administrator Controls Frgament, we open the NavDrawer, click on `Switch Profile`, then both of the items `Switch Profile` and `Administrator Controls` will get highlighted (Note that this isn't observed for the other menu items).
4. So, I am explicitly setting `isAdministratorControlsSelected` to false when we click `Switch Profile` and its restoration after canceling the dialog also requires separate implementation.

File: model/src/main/proto/arguments.proto (hunk 5 above)
Comment (prayutsu) [reply model/src/main/proto/arguments.proto]: Please confirm if you are referring to the below model - 
```
oneof HighlightItem {
     bool highlight_none = 1;
     HighlightCorrespondingItem highlight_corresponding_menu_item = 2;
}

enum HighlightCorrespondingItem {
     HIGHLIGHT_LAST_CHECKED_MENU_ITEM_UNSPECIFIED  = 0;
     HIGHLIGHT_ADMINISTRATOR_CONTROLS_ITEM = 1;
}
```
If yes then can you please suggest some good variable names here? Like what should be a good alternative for `HighlightCorrespondingMenuItem`?

File: app/src/main/java/org/oppia/android/app/drawer/ExitProfileDialogFragment.kt (hunk 6 above)
Comment (prayutsu) [reply app/src/main/java/org/oppia/android/app/drawer/ExitProfileDialogFragment.kt]: Makes sense, done.

**Comment by anandwana001** [comment]
@prayutsu Could you check one more issue similar to this, if you could repro. 
1. Open nav drawer
2. Click options
3. press back - android UI
4. Home is not selected, but we are on the home screen

**Comment by prayutsu** [comment]
> @prayutsu Could you check one more issue similar to this, if you could repro.
> 
> 1. Open nav drawer
> 2. Click options
> 3. press back - android UI
> 4. Home is not selected, but we are on the home screen

Yes, I am able to repro the issue, it is also present in the current develop branch. So, should I file a new issue or this needs to be solved in the current PR itself?

File: model/src/main/proto/arguments.proto (hunk 5 above)
Comment (vinitamurthi) [reply model/src/main/proto/arguments.proto]: No I actually meant something like:
```
enum HighlightItem {
NONE = 0;
LAST_CHECKED_MENU = 1;
ADMINISTRATOR_CONTROLS = 2;
}
```

Something on those lines

File: model/BUILD.bazel [hunk 8]
```diff
@@ -38,6 +38,15 @@ load("@rules_java//java:defs.bzl", "java_lite_proto_library")
 #       ],
 #       ...
 #   )
+proto_library(
```
Comment (BenHenning) [inline model/BUILD.bazel:42]: Nit: please add empty newline above.

File: app/src/main/java/org/oppia/android/app/drawer/NavigationDrawerFragmentPresenter.kt (hunk 7 above)
Comment (BenHenning) [reply app/src/main/java/org/oppia/android/app/drawer/NavigationDrawerFragmentPresenter.kt:247]: Thanks for clarifying it. Given your explanation, I suspect this is probably the cleanest approach (at least I can't think of any way to further improve it). Thanks for the very thorough explanation!

**Review by BenHenning — COMMENTED** [review]
Thanks @prayutsu! Overall, I think this is quite clean. Just looking to see the last few proto improvements before approving.

File: model/BUILD.bazel (hunk 8 above)
Comment (prayutsu) [reply model/BUILD.bazel:42]: Done.

File: model/src/main/proto/arguments.proto (hunk 5 above)
Comment (prayutsu) [reply model/src/main/proto/arguments.proto]: Done.

File: model/src/main/proto/arguments.proto [hunk 9]
```diff
@@ -0,0 +1,18 @@
...
+option java_package = "org.oppia.android.app.model";
+option java_multiple_files = true;
+
+// The fragment arguments passed to instances of ExitProfileDialogFragment.
+message ExitProfileDialogArguments {
+  // Decides the correct menu item to be highlighted after canceling the ExitProfile dialog.
+  HighlightItem highlight_item = 1;
+}
+
+enum HighlightItem {
```
Comment (rt4914) [inline model/src/main/proto/arguments.proto:16]: Add a single line explanation for this too.

**Review by rt4914 — APPROVED** [review]
LGTM. I have found one more issue: https://github.com/oppia/oppia-android/issues/2704

Can this be solved in this too?

**Comment by prayutsu** [comment]
@rt4914 Actually we have some more problem in #2704, like it can also be reproduced for the Options, Help menuItems. So please tell me if I should fix that in the current PR or handle it in some other issue.

**Comment by rt4914** [comment]
> @rt4914 Actually we have some more problem in #2704, like it can also be reproduced for the Options, Help menuItems. So please tell me if I should fix that in the current PR or handle it in some other issue.

Considering that both errors are related to some feature it would be nice if we can solve both of these together.

File: model/src/main/proto/arguments.proto (hunk 9 above)
Comment (prayutsu) [reply model/src/main/proto/arguments.proto:16]: Please suggest one.

**Comment by prayutsu** [comment]
> > @rt4914 Actually we have some more problem in #2704, like it can also be reproduced for the Options, Help menuItems. So please tell me if I should fix that in the current PR or handle it in some other issue.
> 
> Considering that both errors are related to some feature it would be nice if we can solve both of these together.

Sure, will add the changes and the corresponding test cases.

File: model/src/main/proto/arguments.proto [hunk 10]
```diff
@@ -0,0 +1,18 @@
...
+  NONE_UNSPECIFIED = 0;
```
Comment (vinitamurthi) [inline model/src/main/proto/arguments.proto]: This is a bit confusing to me. Is NONE a separate option compared to UNSPECIFIED? They seem to be two different cases that should be handled separately
If thats the case you should have UNSPECIFIED/UNKNOWN as the 0th element, followed by NONE, LAST_CHECKED ....

Comment (prayutsu) [reply model/src/main/proto/arguments.proto]: Actually, I only intended to use NONE but protobuf says that the first item of an enum should end with `UNSPECIFIED`.

**Comment by prayutsu** [comment]
PR description updated with new screenshots.
The new manual testing video - 

https://user-images.githubusercontent.com/54636525/107812250-6ceda380-6d95-11eb-9d46-5dafb44838c2.mp4

File: model/src/main/proto/arguments.proto (hunk 10 above)
Comment (prayutsu) [reply model/src/main/proto/arguments.proto]: Should we omit this case and simply use the `UNSPECIFIED` case that we don't need to mention in the enum?
But I think that will not describe the correct behavior as per its usage.

File: model/src/main/proto/arguments.proto (hunk 9 above)
Comment (prayutsu) [reply model/src/main/proto/arguments.proto:16]: Added an explanation comment, please mention it again if requires nit changes.

File: model/src/main/proto/arguments.proto (hunk 10 above)
Comment (prayutsu) [reply model/src/main/proto/arguments.proto]: @vinitamurthi Took inspiration from other enums and refactored it as follows - 
```kotlin
enum HighlightItem {
  // Indicates that none of the items needs to be highlighted.
  ITEM_UNSPECIFIED = 0;

  // Indicates that one of the NavigationDrawerItem needs to be highlighted.
  LAST_CHECKED_MENU_ITEM = 1;

  // Indicates that the Administrator Controls item needs to be highlighted.
  ADMINISTRATOR_CONTROLS_ITEM = 2;
}
```

Please confirm if it looks good?

**Comment by prayutsu** [comment]
Re-requested reviews from all the codeOwners as the PR has some noticeable changes to fix the issue #2704.

**Review by BenHenning — APPROVED** [review]
Approval for my codeowners files. I think the broader changes are reasonable--deferring to others for verifying correctness & best practices for the app layer & corresponding tests.

File: app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerActivityTest.kt [hunk 11]
```diff
@@ -278,8 +284,249 @@ class NavigationDrawerActivityTest {
...
+      it.openNavigationDrawer()
+      onView(withId(R.id.fragment_drawer_nav_view))
+        .check(matches(checkNavigationViewItemStatus(NavigationDrawerItem.HOME)))
+    }
+  }
+
+  // TODO(#2535): Unable to open NavigationDrawer multiple times on Robolectric
+  @RunOn(TestPlatform.ESPRESSO)
+  @Test
+  fun testNavDrawer_openNavDrawer_admin_pressBack_homeIsSelected() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerActivityTest.kt:579]: this is helpful, can we have the tests for all the menu items? and it's configChange part too.

**Review by anandwana001 — CHANGES_REQUESTED** [review]

**Comment by prayutsu** [comment]
@anandwana001 Should I also add test cases for My downloads menu item and add @Ignore annotation to them. We can also add a TO-DO to be removed when we have Downloads implementation.
If yes, then please mention the issue number that should be added to the TO-DO.

File: app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerActivityTest.kt (hunk 11 above)
Comment (prayutsu) [reply app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerActivityTest.kt:579]: Added.

**Comment by prayutsu** [comment]
PR description updated with new screenshots.

File: model/src/main/proto/arguments.proto (hunk 10 above)
Comment (vinitamurthi) [reply model/src/main/proto/arguments.proto]: if NONE is a viable option, we should have something like 
```
enum HighlightItem {
  // Indicates that the highlight item was not set
  ITEM_UNSPECIFIED = 0;

  // Indicates that none of the items needs to be highlighted.
  NONE = 1;

  // Indicates that one of the NavigationDrawerItem needs to be highlighted.
  LAST_CHECKED_MENU_ITEM = 2;

  // Indicates that the Administrator Controls item needs to be highlighted.
  ADMINISTRATOR_CONTROLS_ITEM = 3;
}
```

Comment (prayutsu) [reply model/src/main/proto/arguments.proto]: Done.

File: app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerActivityTest.kt [hunk 12]
```diff
@@ -278,8 +284,400 @@ class NavigationDrawerActivityTest {
...
+      it.openNavigationDrawer()
+      onView(withId(R.id.fragment_drawer_nav_view))
+        .check(matches(checkNavigationViewItemStatus(NavigationDrawerItem.HOME)))
+    }
+  }
+
+  // TODO(#2535): Unable to open NavigationDrawer multiple times on Robolectric
+  @RunOn(TestPlatform.ESPRESSO)
+  @Test
+  fun testNavDrawer_openNavDrawer_switchProfile_pressBack_homeIsSelected() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerActivityTest.kt:563]: Isn't this test case failing?

The flow is:
1. Open nav drawer
2. click switch profile
3. Dialog appears
4. press back
5. dialog disappeared
6. nav is already open and switch profile is selected

This is the current flow:
What we need is, after 5th point, the menu item should get selected whose screen currently displayed, like if from the home I am selecting switch profile and pressing back, dialog disappeared, home get selected back. 
Same with other menus, Also, for this use case we need to add the test case for all menu items.

File: app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerActivityTest.kt [hunk 13]
```diff
@@ -278,8 +284,400 @@ class NavigationDrawerActivityTest {
...
+      onView(isRoot()).perform(orientationLandscape())
+      onView(withId(R.id.fragment_drawer_nav_view))
+        .check(matches(checkNavigationViewItemStatus(NavigationDrawerItem.HOME)))
+    }
+  }
+
+  // TODO(#2535): Unable to open NavigationDrawer multiple times on Robolectric
+  @RunOn(TestPlatform.ESPRESSO)
+  @Test
+  fun testNavDrawer_openNavDrawer_switchProfile_pressBack_configChange_homeIsSelected() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerActivityTest.kt:648]: Ditto here

File: app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerActivityTest.kt [hunk 14]
```diff
@@ -278,8 +284,400 @@ class NavigationDrawerActivityTest {
     }
   }
 
+  // TODO(#2535): Unable to open NavigationDrawer multiple times on Robolectric
+  @RunOn(TestPlatform.ESPRESSO)
+  @Test
+  fun testNavDrawer_openNavDrawer_switchProfile_cancel_homeIsSelected() {
```
Comment (anandwana001) [inline app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerActivityTest.kt:290]: The current flow is in the latest develop is:
1. Open nav drawer
2. click options
3. Open nav drawer
4. click switch profile
5. cancel - nav drawer gets closed and we are on the same options screen but,
6. open nav drawer
7. home gets selected (issue)

File: app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerActivityTest.kt (hunk 12 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerActivityTest.kt:563]: Press back vs cancel click getting different behaviour

**Review by anandwana001 — CHANGES_REQUESTED** [review]

File: app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerActivityTest.kt (hunk 12 above)
Comment (prayutsu) [reply app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerActivityTest.kt:563]: Actually, the test case is passing, and It is also behaving correctly. See video below-
Note that I have enabled gesture mode in my device so I have to swipe left instead of pressing the back button.

https://user-images.githubusercontent.com/54636525/107905897-d1675900-6f75-11eb-8be1-f13745301177.mp4

File: app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerActivityTest.kt (hunk 14 above)
Comment (prayutsu) [reply app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerActivityTest.kt:290]: Yes, we have test cases for this below.
This test case ensures that the right behavior is exhibited for home.

File: app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerActivityTest.kt (hunk 13 above)
Comment (prayutsu) [reply app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerActivityTest.kt:648]: It is also passing for me.

File: app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerActivityTest.kt (hunk 12 above)
Comment (anandwana001) [reply app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerActivityTest.kt:563]: Could you please confirm with the press back too? Might be helpful.

Comment (prayutsu) [reply app/src/sharedTest/java/org/oppia/android/app/testing/NavigationDrawerActivityTest.kt:563]: It's working, also see the PR description for the full testing video.
https://user-images.githubusercontent.com/54636525/107907904-daa6f480-6f7a-11eb-992a-9e6797f997d6.mp4

**Comment by prayutsu** [comment]
Updated PR description with latest screenshots of passing test cases on ESPRESSO.

**Review by vinitamurthi — APPROVED** [review]
LGTM, thanks @prayutsu !

File: model/src/main/proto/arguments.proto [hunk 15]
```diff
@@ -0,0 +1,28 @@
...
+option java_multiple_files = true;
+
+// The fragment arguments passed to instances of ExitProfileDialogFragment.
+message ExitProfileDialogArguments {
+  // Decides the correct menu item to be highlighted after canceling the ExitProfile dialog.
+  HighlightItem highlight_item = 1;
+}
+
+// Represents the type of item/menuItem that should be highlighted after canceling the
+// ExitProfile dialog.
```
Comment (rt4914) [inline model/src/main/proto/arguments.proto]: This format is incorrect for `ExitProfile dialog`.
Suggest writing this as `ExitProfileDialogFragment`

File: app/src/main/java/org/oppia/android/app/testing/NavigationDrawerTestActivity.kt [hunk 16]
```diff
@@ -32,6 +32,11 @@ class NavigationDrawerTestActivity : InjectableAppCompatActivity(), RouteToTopic
     title = getString(R.string.menu_home)
   }
 
+  override fun onRestart() {
+    super.onRestart()
+    homeActivityPresenter.handleOnReStart()
```
Comment (rt4914) [inline app/src/main/java/org/oppia/android/app/testing/NavigationDrawerTestActivity.kt]: Rename this function to `handleOnRestart `.
`Restart` is correct and `ReStart` is incorrect.

**Review by rt4914 — APPROVED** [review]
@prayutsu Just found another issue filing this and do not solve this in this PR. https://github.com/oppia/oppia-android/issues/2728

Thanks.

**Review by rt4914 — CHANGES_REQUESTED** [review]
Forgot about my suggestions because of issue filing. Blocking this PR for nit changes.

File: model/src/main/proto/arguments.proto (hunk 15 above)
Comment (prayutsu) [reply model/src/main/proto/arguments.proto]: Done.

File: app/src/main/java/org/oppia/android/app/testing/NavigationDrawerTestActivity.kt (hunk 16 above)
Comment (prayutsu) [reply app/src/main/java/org/oppia/android/app/testing/NavigationDrawerTestActivity.kt]: Done.

**Review by rt4914 — APPROVED** [review]
LGTM, thanks.

**Review by anandwana001 — APPROVED** [review]
LGTM

**Comment by prayutsu** [comment]
[If @chrk2205 do not have any suggestions, then @anandwana001 can merge this PR.

**Review by chrk2205 — APPROVED** [review]
LGTM

**Comment by prayutsu** [comment]
Thanks, everyone for reviewing the PR!!

**Comment by rt4914** [comment]
@BenHenning and @anandwana001 Some `Optional` tests are failing so should be merge in this case or not?

**Comment by BenHenning** [comment]
@rt4914 Optional tests can be partly ignored (which is why they're being kept optional). We don't need to block submission on them yet, but we should ensure new breakages are fixed in PRs where we can spot them. This isn't as perfect as requiring the tests yet, but we will need to wait a few weeks before we can mark them as required.

**Comment by BenHenning** [comment]
The failures seem like known flakes that are outside our codebase & need more investigating, plus one apparent issue with the compute affected targets PR process: https://github.com/oppia/oppia-android/pull/2671/checks?check_run_id=1908497857. Adding this to #2691.

**Comment by BenHenning** [comment]
Re-running with latest develop & enabling auto-merge.

**Comment by rt4914** [comment]
@BenHenning Thanks.
