### PR TITLE
Fix #4764: Spotlight overlays have some UI issues 

### LINKED ISSUE #4764: Spotlight overlays have some UI issues
According to some reports, the following problems should be addressed for the spotlights to have a green flag:

- Remove the initial "Next" spotlight from the onboarding screen.
- The spotlight message box is too wide. Please add a margin around it so that it's not bumping up against the edges of the window.
- The "Done" button is too far from the spotlight, and it's not intuitive that it needs to be clicked on to close the spotlight. (In some cases, it even drops off the bottom of the screen!) Please put the "Done" button close to the spotlight in all cases.
- Make the spotlight show up a bit faster, it's currently rather sluggish.
- Text change: "Tap on this button to try!" --> "Tap on this button to try it!
- Text change: "Tap to change the voiceover language."
- When the spotlight for changing the voiceover language triggers and is closed, the Android app crashes.

### PR DESCRIPTION
**Pull request by JishnuGoyal**
## Explanation

fixes #4764 
Updated video demo:

https://user-images.githubusercontent.com/64526117/206852213-f7a89815-3992-4aed-b8d1-38d0c22e6d4f.mp4

Updated screenshots:

WhatsApp Image 2022-11-26 at 5 07 26 PM (1)
WhatsApp Image 2022-11-26 at 5 07 26 PM
WhatsApp Image 2022-11-26 at 5 07 25 PM (1)
WhatsApp Image 2022-11-26 at 5 07 25 PM

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

Portrait

WhatsApp Image 2022-11-25 at 10 28 03 PM (1)
WhatsApp Image 2022-11-25 at 10 28 03 PM
WhatsApp Image 2022-11-25 at 10 28 04 PM (1)
WhatsApp Image 2022-11-25 at 10 28 04 PM (2)
WhatsApp Image 2022-11-25 at 10 28 04 PM
WhatsApp Image 2022-11-25 at 10 28 05 PM
WhatsApp Image 2022-11-25 at 10 31 51 PM

Land:

WhatsApp Image 2022-11-25 at 10 35 15 PM
WhatsApp Image 2022-11-25 at 10 35 16 PM (1)
WhatsApp Image 2022-11-25 at 10 35 16 PM (2)
WhatsApp Image 2022-11-25 at 10 35 16 PM
WhatsApp Image 2022-11-25 at 10 35 17 PM (1)
WhatsApp Image 2022-11-25 at 10 35 17 PM

mobile rtl:
WhatsApp Image 2022-11-25 at 10 44 58 PM
WhatsApp Image 2022-11-25 at 10 44 59 PM (1)
WhatsApp Image 2022-11-25 at 10 44 59 PM (2)
WhatsApp Image 2022-11-25 at 10 44 59 PM
WhatsApp Image 2022-11-25 at 10 45 00 PM (1)
WhatsApp Image 2022-11-25 at 10 45 00 PM (2)
WhatsApp Image 2022-11-25 at 10 45 00 PM

Tablet:
image
image
image
image
image
image

Video (spotlight experience):

https://user-images.githubusercontent.com/64526117/204033854-12f2f0ca-fb92-4ddc-8589-02e5b1e38c46.mp4

Video (Talkback):

https://user-images.githubusercontent.com/64526117/204034102-f420b8ef-972e-4517-a55d-dcd3d5fb5919.mp4

### CODE REVIEW

**Comment by JishnuGoyal** [comment]
Update: All done.

> tasks left: Add screenshots and videos demonstrating the behaviour and UI of the spotlights introduced.

File: app/src/main/java/org/oppia/android/app/spotlight/SpotlightFragment.kt [hunk 1]
```diff
@@ -137,7 +137,7 @@ class SpotlightFragment : InjectableFragment(), SpotlightNavigationListener, Spo
         }
 
         override fun onEnded() {
-          targetList.removeFirst()
+          if (targetList.isNotEmpty()) targetList.removeFirst()
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/spotlight/SpotlightFragment.kt:140]: Is there a test that produces the crash which we can use this to verify as passing?

File: model/src/main/proto/spotlight.proto [hunk 2]
```diff
@@ -10,29 +10,26 @@ option java_multiple_files = true;
 message Spotlight {
   // Determines the UI element being spotlit.
   oneof feature {
-    // Corresponds to the onboarding screen's next button.
-    SpotlightViewState onboarding_next_button = 1;
-
     // Corresponds to the topic fragment's lessons tab.
-    SpotlightViewState topic_lesson_tab = 2;
+    SpotlightViewState topic_lesson_tab = 1;
```
Comment (BenHenning) [inline model/src/main/proto/spotlight.proto]: Keep existing indexes and mark the old onboarding one as reserved with a comment.

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @JishnuGoyal! I think it looks much better! I have a few comments, but besides that the alignment of text looks a bit off, ditto for the new x button: can we keep the top of the x button aligned with the text? Also, the text top and bottom margins relative to the background should always be the same (sometimes it seems like one is larger than the other in your pictures).

**Review by rt4914 — APPROVED** [review]
Awesome work @JishnuGoyal Thanks.

File: model/src/main/proto/spotlight.proto (hunk 2 above)
Comment (JishnuGoyal) [reply model/src/main/proto/spotlight.proto]: Done - Reserved in spotlightstatedatabase proto. The one mentioned here is a oneOf, from where it was removed. PTAL

File: app/src/main/java/org/oppia/android/app/spotlight/SpotlightFragment.kt (hunk 1 above)
Comment (JishnuGoyal) [reply app/src/main/java/org/oppia/android/app/spotlight/SpotlightFragment.kt:140]: image

This tests mimics the behavior when the close spotlight button is tapped twice rapidly in a row. The test fails because the close button is not available, not because it is out of elements to pop. This essentially means that the functionality works as expected, but at the moment, more information is required how the crash reported in the email occurred. It might be possible that the crash was due to some unforeseen circumstance/state that was not caught by the error log such as too many apps being run parallelly on the device. In essence, the spotlight library itself has been designed in a way that this error should not occur. A test case cannot be written with the information we have today.

**Comment by JishnuGoyal** [comment]
Thanks! @rt4914 and @BenHenning. FYI i have updated the UI as requested and addressed the review comments. This PR is getting a bit time sensitive so i have updated everything to the best of my knowledge. PTAL.

File: model/src/main/proto/spotlight.proto (hunk 2 above)
Comment (rt4914) [reply model/src/main/proto/spotlight.proto]: I have checked this and this change does look good.

**Comment by rt4914** [comment]
https://github.com/oppia/oppia-android/pull/4763#discussion_r1032774542
-> Don't have much context about it so haven't been able to help to resolve the comment.

https://github.com/oppia/oppia-android/pull/4763#discussion_r1032689188
-> LGTM from my side.

File: model/src/main/proto/spotlight.proto [hunk 3]
```diff
@@ -10,9 +10,6 @@ option java_multiple_files = true;
 message Spotlight {
   // Determines the UI element being spotlit.
   oneof feature {
-    // Corresponds to the onboarding screen's next button.
-    SpotlightViewState onboarding_next_button = 1;
```
Comment (BenHenning) [inline model/src/main/proto/spotlight.proto:14]: Need reserved for this proto, too (it would go in Spotlight and not in the oneof).

File: app/src/main/java/org/oppia/android/app/spotlight/SpotlightFragment.kt (hunk 1 above)
Comment (BenHenning) [reply app/src/main/java/org/oppia/android/app/spotlight/SpotlightFragment.kt:140]: Hmm okay. We could try to find a situation that would cause the specific crash in question, but I'm actually not sure how it could occur, either, and I think the fix is a reasonable mitigation regardless. I think it's okay that we don't add a test for this.

File: app/src/main/res/values/strings.xml [hunk 4]
```diff
@@ -583,7 +583,6 @@
   <string name="profile_edit_fragment_test_activity_label">Profile Edit Fragment Test Activity</string>
   <string name="administrator_controls_fragment_test_activity_label">Administrator Controls Fragment Test Activity</string>
   <string name="revision_navigation_cards_header">Continue Studying</string>
-  <string name="onboarding_next_button_spotlight_hint">Next</string>
   <string name="state_fragment_hint_bar_forced_announcement_text">Go to the bottom of the screen for a hint.</string>
-  <string name="mark_spotlight_seen_button_text">Done</string>
+  <string name="mark_spotlight_seen_button_text">Close</string>
```
Comment (BenHenning) [inline app/src/main/res/values/strings.xml]: Is this still the seen button text or is it actually the content description for the new icon? Suggest either renaming or removing, based on that.

File: model/src/main/proto/spotlight.proto (hunk 2 above)
Comment (BenHenning) [reply model/src/main/proto/spotlight.proto]: I think part of it is missing, left one follow-up.

**Review by BenHenning — COMMENTED** [review]
Thanks @JishnuGoyal. Just two follow-ups--PTAL. Otherwise, the PR LGTM.

File: model/src/main/proto/spotlight.proto (hunk 3 above)
Comment (JishnuGoyal) [reply model/src/main/proto/spotlight.proto:14]: done

File: app/src/main/res/values/strings.xml (hunk 4 above)
Comment (JishnuGoyal) [reply app/src/main/res/values/strings.xml]: removing since spotlights themselves are suspended during talkback

**Review by BenHenning — APPROVED** [review]
Thanks, LGTM!
