### PR TITLE
Fix #4186: Uncheck all selection on developer options not working

### LINKED ISSUE #4186: Unselect All option in Developer Options not working
**Describe the bug**
The Developer options have three items, Mark Chapters, Mart Stories, and Mark Topic. Inside each item, there is an option to select all at once.
But, unselecting the all option didn't work correctly. 

**To Reproduce**
1. Go to admin profile
2. Swipe left from the Home screen and click on Developer options
3. Open any item of the three-item (Mark Chapters, Mart Stories, and Mark Topic) and select all
4. Click all again and it will not unselect

**Expected behavior**
It should unselect all items correctly.

**Demonstration**
Screenshot_20220214_163035

**Environment**
- Device/emulator being used: emulator
- Android or SDK version (e.g. Android 5 or SDK 21):  SDK 30
- App version (you can get this through system app settings or via the admin controls menu in-app): 1.0

**Additional context**
In PR please add test case showing that this has been fixed now.

### PR DESCRIPTION
**Pull request by KevinGitonga**
## Explanation
  Fix #4186
   This pr fixes :--
  User not able to unselect currently selected developer options using the "All Checkbox". I added more checks when the 
  checkbox is clicked to check scenario when the checkbox is already clicked, if clicked already initiate removal of all items that had been selected and uncheck the checkboxes. 

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-(A11y)-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing
## Before changes demo video
https://user-images.githubusercontent.com/20886444/172631796-bb490c36-3f1c-49d9-9cb1-b370be417680.mp4

## After Changes made demo video
https://user-images.githubusercontent.com/20886444/172336615-ad36af46-87de-490d-a2af-139a4fe3b3f0.mp4

## Screenshots of failing tests before fix
Screenshot 2022-07-07 at 17 22 11

Screenshot 2022-07-07 at 17 23 10

Screenshot 2022-07-07 at 17 24 01

## Espresso Test Results
MarkChaptersCompletedFragmentTest results
Screenshot 2022-07-14 at 14 12 47
MarkStoriesCompletedFragmentTest results
Screenshot 2022-07-14 at 14 14 11
MarkTopicsCompletedFragmentTest results
Screenshot 2022-07-14 at 14 17 50

### CODE REVIEW

File: app/src/main/java/org/oppia/android/app/devoptions/marktopicscompleted/MarkTopicsCompletedFragmentPresenter.kt [hunk 1]
```diff
@@ -64,15 +64,22 @@ class MarkTopicsCompletedFragmentPresenter @Inject constructor(
     }
 
     binding.markTopicsCompletedAllCheckBoxContainer.setOnClickListener {
-      if (binding.isAllChecked == null || binding.isAllChecked == false)
+      if (binding.isAllChecked == null || binding.isAllChecked == false) {
         binding.isAllChecked = true
+      } else if (binding.isAllChecked == true) {
+        binding.isAllChecked = false
+      }
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/devoptions/marktopicscompleted/MarkTopicsCompletedFragmentPresenter.kt]: Given that this covers all cases, this can probably be simplified to be more Kotlin idiomatic:

```kotlin
binding.isAllChecked = !(binding.isAllChecked ?: false)
```

Ditto above in the PR.

File: app/src/main/java/org/oppia/android/app/devoptions/markchapterscompleted/MarkChaptersCompletedFragmentPresenter.kt [hunk 2]
```diff
@@ -78,6 +78,17 @@ class MarkChaptersCompletedFragmentPresenter @Inject constructor(
               )
           }
         }
+      } else if (binding.isAllChecked == true) {
+        binding.isAllChecked = false
+        getMarkChaptersCompletedViewModel().getItemList().forEach { viewModel ->
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/devoptions/markchapterscompleted/MarkChaptersCompletedFragmentPresenter.kt]: Maybe factor this common bit out with the block above to have closer parity with the approach taken for stories and topics (this is a bit more duplicated).

File: app/src/main/java/org/oppia/android/app/devoptions/markchapterscompleted/MarkChaptersCompletedFragmentPresenter.kt [hunk 3]
```diff
@@ -78,6 +78,17 @@ class MarkChaptersCompletedFragmentPresenter @Inject constructor(
...
+          if (viewModel is ChapterSummaryViewModel) {
+            if (!viewModel.checkIfChapterIsCompleted())
+              chapterUnselected(
+                viewModel.chapterIndex,
+                viewModel.nextStoryIndex
+              )
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/devoptions/markchapterscompleted/MarkChaptersCompletedFragmentPresenter.kt]: Nit: I think this can fit within the 100 character limit, so it probably should be de-line wrapped so that it minimizes vertical space (for consistency with other code in the codebase).

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @KevinGitonga! I think the approach looks good. My main pieces of feedback aside from the in-line comments are:
- The title is missing a ':' after the issue number (see other PRs for reference)
- The explanation for the PR should include 'Fix' with the issue being fixed, along with a description explaining what's being fixed, how, and why this is the best approach (+ any other relevant considerations). I suggest taking a look at other PRs for reference, particularly some of the larger ones submitted over the past couple of months that have really clear explanation sections.
- The checklist should use ``[ ]`` for unchecked items and ``[x]`` for checked items (I think you have extra spaces in yours). If it's easier, you can actually click on the checkboxes once the PR description is saved so that you don't need to manually edit each one.
- The recorded video is really nice--thanks for adding that!
- Please also include the other videos/screenshots requested in the PR description template (particularly for accessibility since tablet & landscape aren't likely to be different in behavior per the nature of the fix).
- The Espresso test screenshot isn't actually showing the results of running any Espresso tests. See other PRs that have provided screenshots for an idea on what's helpful to include.
- Please add tests for each of the updated presenters (we generally always add tests for all behaviors that are added, removed, or changed in the codebase, unless there's a specific reason why the change can't be tested).

File: app/src/main/java/org/oppia/android/app/devoptions/markchapterscompleted/MarkChaptersCompletedFragmentPresenter.kt (hunk 2 above)
Comment (KevinGitonga) [reply app/src/main/java/org/oppia/android/app/devoptions/markchapterscompleted/MarkChaptersCompletedFragmentPresenter.kt]: Hey @BenHenning please tell me why it is more duplicated?

File: app/src/main/java/org/oppia/android/app/devoptions/markchapterscompleted/MarkChaptersCompletedFragmentPresenter.kt (hunk 3 above)
Comment (KevinGitonga) [reply app/src/main/java/org/oppia/android/app/devoptions/markchapterscompleted/MarkChaptersCompletedFragmentPresenter.kt]: Hi @BenHenning when i de-line wrap i am getting lint error while committing the changes.

File: app/src/main/java/org/oppia/android/app/devoptions/markchapterscompleted/MarkChaptersCompletedFragmentPresenter.kt [hunk 4]
```diff
@@ -72,12 +72,19 @@ class MarkChaptersCompletedFragmentPresenter @Inject constructor(
           if (viewModel is ChapterSummaryViewModel) {
             if (!viewModel.checkIfChapterIsCompleted())
               chapterSelected(
-                viewModel.chapterIndex,
-                viewModel.nextStoryIndex,
+                viewModel.chapterIndex, viewModel.nextStoryIndex,
```
Comment (rt4914) [inline app/src/main/java/org/oppia/android/app/devoptions/markchapterscompleted/MarkChaptersCompletedFragmentPresenter.kt]: Undo this change.
Each argument should be in its own line here.

**Review by rt4914 — CHANGES_REQUESTED** [review]
@KevinGitonga Please add tests for this functionality. Thanks.

File: app/src/main/java/org/oppia/android/app/devoptions/markchapterscompleted/MarkChaptersCompletedFragmentPresenter.kt (hunk 3 above)
Comment (BenHenning) [reply app/src/main/java/org/oppia/android/app/devoptions/markchapterscompleted/MarkChaptersCompletedFragmentPresenter.kt]: Are you de-wrapping it like this:

```kotlin
              chapterUnselected(viewModel.chapterIndex, viewModel.nextStoryIndex)
```

That shouldn't result in a lint error as it fits within 100 characters, so I'm curious what issue you're seeing if that's what you're trying.

File: app/src/main/java/org/oppia/android/app/devoptions/markchapterscompleted/MarkChaptersCompletedFragmentPresenter.kt (hunk 2 above)
Comment (BenHenning) [reply app/src/main/java/org/oppia/android/app/devoptions/markchapterscompleted/MarkChaptersCompletedFragmentPresenter.kt]: Ah, I was mainly thinking that the forEach bit could be consolidated with the if-check above (``      if (binding.isAllChecked == null || binding.isAllChecked == false) {``), but in retrospect I don't think that would actually reduce much. Please disregard. :)

File: app/src/main/java/org/oppia/android/app/devoptions/markchapterscompleted/MarkChaptersCompletedFragmentPresenter.kt (hunk 3 above)
Comment (BenHenning) [reply app/src/main/java/org/oppia/android/app/devoptions/markchapterscompleted/MarkChaptersCompletedFragmentPresenter.kt]: This appears resolved in the latest changes.

File: app/src/main/java/org/oppia/android/app/devoptions/marktopicscompleted/MarkTopicsCompletedFragmentPresenter.kt (hunk 1 above)
Comment (BenHenning) [reply app/src/main/java/org/oppia/android/app/devoptions/marktopicscompleted/MarkTopicsCompletedFragmentPresenter.kt]: This appears resolved in the latest changes.

**Review by BenHenning — COMMENTED** [review]
Ah, not sure if you intentionally re-assigned me @rt4914.

@KevinGitonga please make sure to address all points mentioned, and respond to all comments, before sending a PR back for review (I know you didn't send this back in this case, but I thought I'd mention this, anyway, so that you have this in mind when you send this PR back into review).

**Comment by BenHenning** [comment]
@KevinGitonga are you still actively working on this? We should avoid PRs becoming stale.

**Comment by KevinGitonga** [comment]
@BenHenning was blocked on tests for this patch. Will proceed as i can run tests on my Ubuntu now.

File: app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkChaptersCompletedFragmentTest.kt [hunk 5]
```diff
@@ -422,6 +423,58 @@ class MarkChaptersCompletedFragmentTest {
...
+      verifyItemUnCheckedOnRecyclerViewItemAtPosition(itemPosition = 8)
+      scrollToPosition(position = 10)
+      verifyItemUnCheckedOnRecyclerViewItemAtPosition(itemPosition = 10)
+      scrollToPosition(position = 11)
+      verifyItemUnCheckedOnRecyclerViewItemAtPosition(itemPosition = 11)
+      scrollToPosition(position = 13)
+      verifyItemUnCheckedOnRecyclerViewItemAtPosition(itemPosition = 13)
+      scrollToPosition(position = 14)
+      verifyItemUnCheckedOnRecyclerViewItemAtPosition(itemPosition = 14)
+      println("asserts completed")
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkChaptersCompletedFragmentTest.kt]: Did you mean to remove this?

File: app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkChaptersCompletedFragmentTest.kt [hunk 6]
```diff
@@ -422,6 +423,58 @@ class MarkChaptersCompletedFragmentTest {
...
   }
 
+  @Test
+  fun testMarkChaptersCompletedFragment_unSelectAll_unSelectsAllChapters() {
+    launch<MarkChaptersCompletedTestActivity>(
+      createMarkChaptersCompletedTestActivityIntent(internalProfileId)
+    ).use {
+      testCoroutineDispatchers.runCurrent()
+      onView(withId(R.id.mark_chapters_completed_all_check_box_container)).perform(click())
+      scrollToPosition(position = 1)
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkChaptersCompletedFragmentTest.kt]: Could we maybe include the scroll within the helper? It'd cut down a lot on the boilerplate required in the test.

File: app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkChaptersCompletedFragmentTest.kt [hunk 7]
```diff
@@ -422,6 +423,58 @@ class MarkChaptersCompletedFragmentTest {
...
+      verifyItemCheckedOnRecyclerViewItemAtPosition(itemPosition = 8)
+      scrollToPosition(position = 10)
+      verifyItemCheckedOnRecyclerViewItemAtPosition(itemPosition = 10)
+      scrollToPosition(position = 11)
+      verifyItemCheckedOnRecyclerViewItemAtPosition(itemPosition = 11)
+      scrollToPosition(position = 13)
+      verifyItemCheckedOnRecyclerViewItemAtPosition(itemPosition = 13)
+      scrollToPosition(position = 14)
+      verifyItemCheckedOnRecyclerViewItemAtPosition(itemPosition = 14)
+      onView(withId(R.id.mark_chapters_completed_all_check_box_container)).perform(click())
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkChaptersCompletedFragmentTest.kt:398]: It seems like this test is verifying multiple things. I suggest splitting it up to keep the tests focused:
- One test for verifying that clicking the 'check all' does, indeed, check all items
- One test for verifying that checking all, then unchecking them, does indeed uncheck all items

File: app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkChaptersCompletedFragmentTest.kt [hunk 8]
```diff
@@ -868,6 +921,16 @@ class MarkChaptersCompletedFragmentTest {
     ).check(matches(isChecked()))
   }
 
+  private fun verifyItemUnCheckedOnRecyclerViewItemAtPosition(itemPosition: Int) {
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkChaptersCompletedFragmentTest.kt]:
```suggestion
  private fun verifyItemUncheckedOnRecyclerViewItemAtPosition(itemPosition: Int) {
```

('unchecked' is one word).

File: app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkChaptersCompletedFragmentTest.kt [hunk 9]
```diff
@@ -422,6 +423,58 @@ class MarkChaptersCompletedFragmentTest {
     }
   }
 
+  @Test
+  fun testMarkChaptersCompletedFragment_unSelectAll_unSelectsAllChapters() {
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkChaptersCompletedFragmentTest.kt]:
```suggestion
  fun testMarkChaptersCompletedFragment_deselectAll_deselectsAllChapters() {
```

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @KevinGitonga! I think the tests look really solid. I left a few comments to ensure both test parity and maintainability. PTAL as my comments for MarkChaptersCompletedFragmentTest also apply to the other two test suites.

Once those are addressed, could you upload screenshots of running the test suite without the fix in place to show that the new tests fail as expected? This is really useful when fixing bugs as it demonstrates that the tests will properly catch the issue if it ever regresses in the future.

File: app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkChaptersCompletedFragmentTest.kt (hunk 5 above)
Comment (KevinGitonga) [reply app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkChaptersCompletedFragmentTest.kt]: Yeah removing it.

File: app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkChaptersCompletedFragmentTest.kt (hunk 7 above)
Comment (KevinGitonga) [reply app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkChaptersCompletedFragmentTest.kt:398]: Actually @BenHenning i am verifying if unchecking them does indeed uncheck and also the items as this is the issue at hand but at first i have to check the checkbox and all items i have added the check logic into a separate function in a separate function to avoid duplicating. PLMK if this works.

File: app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkChaptersCompletedFragmentTest.kt (hunk 6 above)
Comment (KevinGitonga) [reply app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkChaptersCompletedFragmentTest.kt]: Hi @BenHenning not sure what you mean. I understand that we should move it to StoryProgressTestHelper. How about the dependency on recyclerview id which is different on the different fragments.

File: app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkChaptersCompletedFragmentTest.kt (hunk 9 above)
Comment (KevinGitonga) [reply app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkChaptersCompletedFragmentTest.kt]: Update applied.

File: app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkChaptersCompletedFragmentTest.kt [hunk 10]
```diff
@@ -398,80 +398,62 @@ class MarkChaptersCompletedFragmentTest {
...
-      verifyItemCheckedOnRecyclerViewItemAtPosition(itemPosition = 11)
-      scrollToPosition(position = 13)
-      verifyItemCheckedOnRecyclerViewItemAtPosition(itemPosition = 13)
-      scrollToPosition(position = 14)
-      verifyItemCheckedOnRecyclerViewItemAtPosition(itemPosition = 14)
+      testMarkChaptersCompleted_selectAll_selectsAllTests()
     }
   }
 
+  private fun testMarkChaptersCompleted_selectAll_selectsAllTests() {
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkChaptersCompletedFragmentTest.kt]: This wasn't what I meant, actually. My earlier comment was suggesting to:
- Move the 'scrollToPosition' call to be inside of 'verifyItemCheckedOnRecyclerViewItemAtPosition' so that we only need 1 line of code in the test to perform _each_ item interaction (not all of them)
- It's an antipattern to move the behavior-specific steps of a test into a helper as it hides away the thing that's actually being tested (which can make the tests harder to understand at best, and difficult to maintain at worst in the case where the helper is used by multiple tests).

Please revert and make the mentioned adjustments above. If you're not sure, feel free to reach out.

**Review by BenHenning — COMMENTED** [review]
Hi @KevinGitonga. I had one follow-up comment--PTAL.

File: app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkChaptersCompletedFragmentTest.kt (hunk 10 above)
Comment (KevinGitonga) [reply app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkChaptersCompletedFragmentTest.kt]: Hey @BenHenning i have updated and moved 'scrollToPosition' also have reverted some changes.

File: app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkChaptersCompletedFragmentTest.kt (hunk 7 above)
Comment (BenHenning) [reply app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkChaptersCompletedFragmentTest.kt:398]: I'm not sure that the first verify step is needed, though. If there's already a test to verify that clicking the 'check all' box checks everything, then your test can start with that assumption by clicking the checkbox, then unclicking it and verifying that nothing is checked anymore (both tests together tell the whole story).

**Review by BenHenning — COMMENTED** [review]
Thanks @KevinGitonga. I think the test changes are coming along well. I've left one follow-up comment--PTAL.

File: app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkChaptersCompletedFragmentTest.kt (hunk 7 above)
Comment (KevinGitonga) [reply app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkChaptersCompletedFragmentTest.kt:398]: Have started with assumption and updated the tests accordingly.

File: app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkTopicsCompletedFragmentTest.kt [hunk 11]
```diff
@@ -327,31 +296,38 @@ class MarkTopicsCompletedFragmentTest {
...
       testCoroutineDispatchers.runCurrent()
-      scrollToPosition(position = 0)
       performItemCheckOnTopicSummaryListItem(itemPosition = 0)
-      scrollToPosition(position = 1)
       performItemCheckOnTopicSummaryListItem(itemPosition = 1)
-      scrollToPosition(position = 2)
       performItemCheckOnTopicSummaryListItem(itemPosition = 2)
-      scrollToPosition(position = 3)
       performItemCheckOnTopicSummaryListItem(itemPosition = 3)
       onView(withId(R.id.mark_topics_completed_all_check_box)).check(matches(isChecked()))
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkTopicsCompletedFragmentTest.kt:306]: For this & the other test suites--should we also be including this line at the end of the new tests but to verify that the 'complete all' checkbox is unselected?

File: app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkTopicsCompletedFragmentTest.kt [hunk 12]
```diff
@@ -327,31 +296,38 @@ class MarkTopicsCompletedFragmentTest {
...
   }
 
+  @Test
+  fun testMarkTopicsCompletedFragment_deselectAllTopics_deselectsAllTopics() {
+    launch<MarkTopicsCompletedTestActivity>(
+      createMarkTopicsCompletedTestActivityIntent(internalProfileId)
+    ).use {
+      testCoroutineDispatchers.runCurrent()
+      onView(withId(R.id.mark_topics_completed_all_check_box_container)).perform(click())
+      onView(withId(R.id.mark_topics_completed_all_check_box_container)).perform(click())
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkTopicsCompletedFragmentTest.kt]: For this & the other new tests: it would be nice to include a comment to make it clear that the two redundant lines are intentional. E.g. something like:

```suggestion
      // Click one to select all topics.
      onView(withId(R.id.mark_topics_completed_all_check_box_container)).perform(click())

      // Click a second time to unselect all topics.
      onView(withId(R.id.mark_topics_completed_all_check_box_container)).perform(click())

```

File: app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkChaptersCompletedFragmentTest.kt (hunk 6 above)
Comment (BenHenning) [reply app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkChaptersCompletedFragmentTest.kt]: This has been clarified in another comment, and the latest changes address my original comment here.

File: app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkChaptersCompletedFragmentTest.kt (hunk 8 above)
Comment (BenHenning) [reply app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkChaptersCompletedFragmentTest.kt]: This appears to have been addressed for chapters & stories, but seems to still be unresolved for MarkTopicsCompletedFragmentTest. Please fix.

File: app/src/main/java/org/oppia/android/app/devoptions/markchapterscompleted/MarkChaptersCompletedFragmentPresenter.kt [hunk 13]
```diff
@@ -78,6 +78,14 @@ class MarkChaptersCompletedFragmentPresenter @Inject constructor(
               )
           }
         }
+      } else if (binding.isAllChecked == true) {
+        binding.isAllChecked = false
+        getMarkChaptersCompletedViewModel().getItemList().forEach { viewModel ->
+          if (viewModel is ChapterSummaryViewModel) {
+            if (!viewModel.checkIfChapterIsCompleted())
+              chapterUnselected(viewModel.chapterIndex, viewModel.nextStoryIndex)
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/devoptions/markchapterscompleted/MarkChaptersCompletedFragmentPresenter.kt]: This should have braces per https://developer.android.com/kotlin/style-guide#formatting (we only omit braces if the entire if condition + conditioned statement can fit on one line).

File: app/src/main/java/org/oppia/android/app/devoptions/markchapterscompleted/MarkChaptersCompletedFragmentPresenter.kt (hunk 4 above)
Comment (BenHenning) [reply app/src/main/java/org/oppia/android/app/devoptions/markchapterscompleted/MarkChaptersCompletedFragmentPresenter.kt]: This appears to be resolved, or at least is no longer an issue in the latest changes.

**Review by BenHenning — COMMENTED** [review]
Thanks @KevinGitonga. I just had a few follow-up comments--PTAL. Otherwise, the PR is coming together really nicely and seems quite close to being completed.

**Comment by BenHenning** [comment]
Also, @KevinGitonga please make sure to include screenshots of the changed test suites passing with Epsresso in your PR description (per the PR template).

File: app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkTopicsCompletedFragmentTest.kt (hunk 11 above)
Comment (KevinGitonga) [reply app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkTopicsCompletedFragmentTest.kt:306]: Not sure i follow @BenHenning  which line exactly? I refactored scrollToPosition into performItemCheckOnTopicSummaryListItem.

File: app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkTopicsCompletedFragmentTest.kt (hunk 12 above)
Comment (KevinGitonga) [reply app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkTopicsCompletedFragmentTest.kt]: Yeah @BenHenning for sure this makes sense, myself i had a hard time to understand the logic.

File: app/src/main/java/org/oppia/android/app/devoptions/markchapterscompleted/MarkChaptersCompletedFragmentPresenter.kt (hunk 13 above)
Comment (KevinGitonga) [reply app/src/main/java/org/oppia/android/app/devoptions/markchapterscompleted/MarkChaptersCompletedFragmentPresenter.kt]: Noted updated the statements.

File: app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkChaptersCompletedFragmentTest.kt (hunk 8 above)
Comment (KevinGitonga) [reply app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkChaptersCompletedFragmentTest.kt]: Ohh don't know how i missed this, have applied a patch for this as well.

File: app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkTopicsCompletedFragmentTest.kt (hunk 11 above)
Comment (KevinGitonga) [reply app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkTopicsCompletedFragmentTest.kt:306]: @BenHenning i think i understand now but adding a check to assert if checkbox is unchecked is always failing for some reason.

Comment (BenHenning) [reply app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkTopicsCompletedFragmentTest.kt:306]: What issue are you running into @KevinGitonga, and what specific check are you trying? Sometimes Espresso checks can be unexpectedly finicky.

**Review by BenHenning — COMMENTED** [review]
Thanks @KevinGitonga! I think just one comment thread is yet to be addressed, and then the PR should be 'LGTM' from me.

File: app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkTopicsCompletedFragmentTest.kt (hunk 11 above)
Comment (KevinGitonga) [reply app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkTopicsCompletedFragmentTest.kt:306]: Actually @BenHenning i noticed this two lines are behaving differently, the second one is working as expected in my case. 
onView(withId(R.id.mark_chapters_completed_all_check_box)).check(matches(isNotChecked()))
onView(withId(R.id.mark_chapters_completed_all_check_box)).check(matches(not(isChecked())))

Comment (BenHenning) [reply app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkTopicsCompletedFragmentTest.kt:306]: How odd. I looked into this and I couldn't see any reason why they would be different.

Just for sanity, can you verify that the ``not(isChecked())`` version fails when expected?

**Review by BenHenning — COMMENTED** [review]
Thanks @KevinGitonga! The PR LGTM, but I just wanted to double check the failing behavior for the latest test updates.

**Comment by BenHenning** [comment]
@rt4914 I'm more or less 'LGTM' on this PR, so I think you can take a look now as a codeowner.

**Review by rt4914 — APPROVED** [review]
LGTM. Thanks @BenHenning for reviewing this PR

File: app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkTopicsCompletedFragmentTest.kt (hunk 11 above)
Comment (KevinGitonga) [reply app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkTopicsCompletedFragmentTest.kt:306]: @BenHenning very odd, i tried again and the first line is running as expected. I would say some checks have a tendency of behaving weirdly for some reason.

Comment (BenHenning) [reply app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkTopicsCompletedFragmentTest.kt:306]: Hmm. It may be prudent to run it a few times @KevinGitonga to be sure that it isn't flaky.

That being said, I think using ``isNotChecked`` is preferred for parity with ``isChecked``.

**Review by BenHenning — COMMENTED** [review]
Thanks @KevinGitonga. Followed up on the open comment thread.

File: app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkTopicsCompletedFragmentTest.kt (hunk 11 above)
Comment (KevinGitonga) [reply app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkTopicsCompletedFragmentTest.kt:306]: @BenHenning what i mean is that matches(not(isChecked() has been used while covering all the other similar checks in this particular class. I do not understand what you mean by saying that. isnotChecked has more parity with isChecked. Also i have noticed the same behavior it's like espresso will misbehave and fail when expected to pass on some instances, not all i have also noticed this behavior on other tests.

Comment (KevinGitonga) [reply app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkTopicsCompletedFragmentTest.kt:306]: Also after running i few times it may pass but on the next try fail. What i have noticed is that not(isChecked) has little tendency to fail compared to isNotChecked.

Comment (BenHenning) [reply app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkTopicsCompletedFragmentTest.kt:306]: I see. Does the ``not(isChecked())`` version ever fail @KevinGitonga? If not, I'm fine with going ahead with that.

Also, it help to add a ``testCoroutineDispatchers.runCurrent()`` right before the verification line--that might help avoid the flake.

Comment (KevinGitonga) [reply app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkTopicsCompletedFragmentTest.kt:306]: Okay @BenHenning i have added this line but i still notice that it is failing to on some instances on my machine, but on CI i think it is passing as expected. Based on results, not sure if CI run all tests even newly added ones.

Comment (KevinGitonga) [reply app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkTopicsCompletedFragmentTest.kt:306]: @BenHenning I have also noticed that this flake is affecting MarkStoriesCompletedFragmentTest the other updated classes seem to work fine.

Comment (BenHenning) [reply app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkTopicsCompletedFragmentTest.kt:306]: Hmm @KevinGitonga let's sync on next steps for this issue. We should dig into the flake to make sure we don't check in a flaky test, and there are good practices to follow for how to more easily do this.

**Comment by KevinGitonga** [comment]
@BenHenning I have been having an issue with this PR with one of the test case being flaky. It is not able to be merged PTAL and advise.

**Comment by BenHenning** [comment]
@KevinGitonga PTAL at https://github.com/KevinGitonga/oppia-android/pull/4 and assign back if it looks good & you can merge it.

I have a separate follow-up fix PR to send once that's merged.

**Comment by BenHenning** [comment]
@KevinGitonga PTAL at https://github.com/KevinGitonga/oppia-android/pull/3 and merge it if it looks good to you.

I think that'll fix at least the obvious CI failures (though there may be others that I'm unaware of).

Note that per that PR's description I tried running the tests a bunch of times and didn't see any flakes. After merging the PR, could you check again to see if you're still running into the flake issues that led to this being routed over to me for investigating?

**Comment by KevinGitonga** [comment]
@BenHenning have merged the changes will sync and run the test's on another device to check the status of this flake.

**Comment by KevinGitonga** [comment]
@BenHenning noticed i still have some flakes when i run test's on MarkChaptersCompletedFragmentTest on the develop branch too this is both on my Mac and ubuntu. The tests have a tendency to fail and sometimes pass completely. Please check image below for the test results.

# First run
Screenshot 2022-10-05 at 14 26 54

## Next run
Screenshot 2022-10-05 at 14 37 01

**Comment by BenHenning** [comment]
Just to confirm @KevinGitonga are those results from Robolectric or Espresso?

File: app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkTopicsCompletedFragmentTest.kt (hunk 11 above)
Comment (BenHenning) [reply app/src/sharedTest/java/org/oppia/android/app/devoptions/MarkTopicsCompletedFragmentTest.kt:306]: Resolving this as we're now discussing this on the main comment thread.

**Comment by KevinGitonga** [comment]
> Just to confirm @KevinGitonga are those results from Robolectric or Espresso?

@BenHenning this are from Espresso run from my Samsung device. Not sure what is causing this on espresso but since if ci is using robolectric and the same tests are passing and they are actually supposed to pass, my thinking is that the changes can merge to develop as the core issue is resolved. Thanks.

**Review by BenHenning — APPROVED** [review]
Agreed @KevinGitonga. Since the Espresso failures already exist on develop, approving & merging this. Thanks!
