### PR TITLE
Fix #4648: Fix topic lesson differentiation between locked, completed and in-progress lessons

### LINKED ISSUE #4648: No differentiation between completed lessons and locked lessons in topics tab
**Describe the bug**
In topic lessons tab, when we use screen reader there is not differentiation between completed lessons and locked lessons. Also, locked lessons are having content description as "lessons in progress" which should be locked lessons. 

**To Reproduce**
1. Go to Any Story
2. Click on Lessons Tab
3. Turn on talkback reader
4. Navigate to the list of lessons. 

**Expected behavior**
The content description for completed lessons, locked lessons and In Progress lesson should be appropriate to it's state. For example, for locked chapter content description should have locked chapter in the end. 

**Demonstrationtion**
https://user-images.githubusercontent.com/43074241/195417529-357236fe-1d37-45a1-888f-51158ea89822.mp4

**Environment**
- Device/emulator being used: Realme GT Master Edition
- Android or SDK version (e.g. Android 5 or SDK 21): Android 12
- App version (you can get this through system app settings or via the admin controls menu in-app): 1.0

### PR DESCRIPTION
**Pull request by kkmurerwa**
## Explanation

Fix #4648: When this PR is merged, it will fix the issue of locked, completed and in progress lessons not being differentiated by Talkback.

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### CODE REVIEW

File: app/src/main/java/org/oppia/android/app/topic/lessons/ChapterSummaryViewModel.kt [hunk 1]
```diff
@@ -23,14 +24,22 @@ class ChapterSummaryViewModel(
...
-      )
+    return when (chapterPlayState) {
+      ChapterPlayState.COMPLETED -> {
+        resourceHandler.getStringInLocaleWithWrapping(
+          R.string.chapter_completed, (index + 1).toString(), chapterTitle
+        )
+      }
+      ChapterPlayState.NOT_PLAYABLE_MISSING_PREREQUISITES -> {
+        resourceHandler.getStringInLocaleWithWrapping(
+          R.string.chapter_prerequisite_title_label, (index).toString(), previousChapterTitle
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/topic/lessons/ChapterSummaryViewModel.kt]:
```suggestion
          R.string.chapter_prerequisite_title_label, index.toString(), previousChapterTitle
```

File: app/src/main/java/org/oppia/android/app/topic/lessons/StorySummaryViewModel.kt [hunk 2]
```diff
@@ -77,6 +77,14 @@ class StorySummaryViewModel(
...
           ephemeralChapterSummary.writtenTranslationContext
         ),
+        previousChapterTitle = if (index > 0) {
+          translationController.extractString(
+            ephemeralStorySummary.chaptersList[index - 1].chapterSummary.title,
+            ephemeralStorySummary.chaptersList[index - 1].writtenTranslationContext
+          )
+        } else {
+          ""
+        },
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/topic/lessons/StorySummaryViewModel.kt]: Perhaps instead pass in null and add the null check to the 'when' condition for MISSING_PREREQUISITES? I think that will lead to a slightly cleaner & more robust implementation.

File: app/src/main/java/org/oppia/android/app/topic/lessons/ChapterSummaryViewModel.kt [hunk 3]
```diff
@@ -23,14 +24,22 @@ class ChapterSummaryViewModel(
...
-      resourceHandler.getStringInLocaleWithWrapping(
-        R.string.chapter_in_progress, (index + 1).toString(), chapterTitle
-      )
+    return when (chapterPlayState) {
+      ChapterPlayState.COMPLETED -> {
+        resourceHandler.getStringInLocaleWithWrapping(
+          R.string.chapter_completed, (index + 1).toString(), chapterTitle
+        )
+      }
+      ChapterPlayState.NOT_PLAYABLE_MISSING_PREREQUISITES -> {
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/topic/lessons/ChapterSummaryViewModel.kt:33]: Please add a test for this follow-up change & add two screenshots to the PR description: one showing the new test failing when your fix is temporarily commented out/removed, and a second showing it passing. This is generally good practice when fixing targeted issues like this.

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @kkmurerwa! This seems like a really sensible solution. Had a few follow-up suggestions--PTAL.

File: app/src/main/java/org/oppia/android/app/topic/lessons/StorySummaryViewModel.kt (hunk 2 above)
Comment (kkmurerwa) [reply app/src/main/java/org/oppia/android/app/topic/lessons/StorySummaryViewModel.kt]: I have added the else statement as suggested. It returns  a generic string that I also added to address the usecase where there is no previous chapter title.

File: app/src/main/java/org/oppia/android/app/topic/lessons/ChapterSummaryViewModel.kt (hunk 1 above)
Comment (kkmurerwa) [reply app/src/main/java/org/oppia/android/app/topic/lessons/ChapterSummaryViewModel.kt]: This has been modified with the latest changes.

File: app/src/main/java/org/oppia/android/app/topic/lessons/ChapterSummaryViewModel.kt (hunk 3 above)
Comment (kkmurerwa) [reply app/src/main/java/org/oppia/android/app/topic/lessons/ChapterSummaryViewModel.kt:33]: I have added a test for the ideal situation (where there is a previous chapter title). I haven't been able to add a test for the other condition since I am unable to replicate it in test.

**Comment by kkmurerwa** [comment]
Screenshot(s) of the  failing test when the new code block is commented out;
Screenshot from 2023-04-28 16-22-01
The log produced by the failure
Screenshot from 2023-04-28 16-22-45

Screenshot of the passing test with the new code block uncommented;
Screenshot from 2023-04-28 16-25-10

**Comment by kkmurerwa** [comment]
Hey @BenHenning. I have addressed your comments and added screenshots of the failing and passing test. You should be able to do another review. PTAL.

**Comment by kkmurerwa** [comment]
Hey @BenHenning. I have temporarily reassigned myself the issue. There are a few more changes I am working on to improve accessibility.

**Comment by kkmurerwa** [comment]
Hey @BenHenning. Here are a few changes I have made with commit ID [8d497a2](https://github.com/oppia/oppia-android/pull/4958/commits/8d497a2c2e4be269cc3eed9fbe50a551162067f3).
- I noticed that there are no existing tests to check for the computeChapterPlayStateIconContentDescription that is displayed on the chapter_play_state_icon. I added a test for this that tests in the content description for progress chapters is being displayed correctly.
- In the case of a completed chapter topic, there is no chapter play state icon displayed. I modified the chapter_index text view to display the string from computeChapterPlayStateIconContentDescription instead for better Talkback feedback to visually impaired users.
- I added a test for the computeChapterPlayStateIconContentDescription in the case of the completed chapter topic state.


Here is a screenshot of the failing tests when I return a dummy string.
Screenshot from 2023-05-02 18-31-56

Here is  a screenshot of the passing tests when the original logic is reinstated.
Screenshot from 2023-05-02 18-35-12

The tests on the CI failed for some reason but they all pass locallly. The failing test requires a rerun to pass.
Screenshot from 2023-05-02 18-45-16

**Comment by BenHenning** [comment]
Apologies @kkmurerwa will need to look at this tomorrow.

**Comment by kkmurerwa** [comment]
No problem at all Ben.

File: app/src/main/java/org/oppia/android/app/topic/lessons/StorySummaryViewModel.kt [hunk 4]
```diff
@@ -77,6 +77,14 @@ class StorySummaryViewModel(
...
           ephemeralChapterSummary.writtenTranslationContext
         ),
+        previousChapterTitle = if (index > 0) {
+          translationController.extractString(
+            ephemeralStorySummary.chaptersList[index - 1].chapterSummary.title,
+            ephemeralStorySummary.chaptersList[index - 1].writtenTranslationContext
+          )
+        } else {
+          null
+        },
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/topic/lessons/StorySummaryViewModel.kt]:
```suggestion
        } else null,
```

Small change to make it a bit more compact.

File: app/src/main/res/values/strings.xml [hunk 5]
```diff
@@ -91,6 +91,7 @@
   <string name="chapter_completed">Chapter %s with title %s is completed</string>
   <string name="chapter_in_progress">Chapter %s with title %s is in progress</string>
   <string name="chapter_prerequisite_title_label">Complete Chapter %s: %s to unlock this chapter.</string>
+  <string name="chapter_prerequisite_title_label_without_chapter_title">Complete the previous chapter to unlock this chapter</string>
```
Comment (BenHenning) [inline app/src/main/res/values/strings.xml]:
```suggestion
  <string name="chapter_prerequisite_title_label_without_chapter_title">Complete the previous chapter to unlock this chapter.</string>
```

For consistency with the other label.

File: app/src/main/java/org/oppia/android/app/topic/lessons/ChapterSummaryViewModel.kt (hunk 3 above)
Comment (BenHenning) [reply app/src/main/java/org/oppia/android/app/topic/lessons/ChapterSummaryViewModel.kt:33]: Thanks! The other case is, theoretically, impossible. There is a way to force it to happen in tests, but I think it makes sense just to ignore it. We might be able to eliminate the codepath entirely with future refactors of the domain structures, but I think it's fine to leave it as-is untested.

**Review by BenHenning — COMMENTED** [review]
Thanks @kkmurerwa! PR LGTM, just had small nits--PTAL. Also, the branch will need to be brought up-to-date with the latest develop so that we can merge it.

File: app/src/main/res/values/strings.xml (hunk 5 above)
Comment (kkmurerwa) [reply app/src/main/res/values/strings.xml]: I have made this change. It should reflect on the code now.

File: app/src/main/java/org/oppia/android/app/topic/lessons/StorySummaryViewModel.kt (hunk 4 above)
Comment (kkmurerwa) [reply app/src/main/java/org/oppia/android/app/topic/lessons/StorySummaryViewModel.kt]: This has been done too.

**Comment by kkmurerwa** [comment]
Hey @BenHenning. The issues mentioned have been resolved. The PR should now be ready for a merge unless there are some other issues.

**Review by BenHenning — APPROVED** [review]
Thanks @kkmurerwa! Apologies for the delayed review. This LGTM!
