### PR TITLE
Fix #5946: Language behavior in tablet devices

### LINKED ISSUE #5946: [BUG]: Unexpected behaviour on language selection in tablet devices
### Describe the bug

With the new onboarding flow, the app and audio language screens have been redesigned, intorducing new behaviour. Some of this behaviour is buggy.

- [x] On selecting an app language from the dropdow, the selected language in the options multi-pane panel sometimes does not update. Investigations show that this is due to the presenter originally relying on the result of ` translationController.updateAppLanguage(profileId, selection)` to update the UI,  but this is incorrect since this function's response payload is the _previous_selection.
- [x] In the Audio Language dropdown, Swahili is listed as as supported language when it shouldn't be. Selecting Kiswahili returns LANGUAGE_UNSPECIFIED, which leads to the options side panel becoming blank.

### Steps To Reproduce

1. Enable the `ONBOARDING_FLOW_V2` feature flag.
2. Log in to the app and navigate to the options -> preferred app language/preferred audio language screen.
3. Attempt to change either language options
4. See that the decribed bug is reproduced.

### Expected Behavior

1. The app language should be updated in the side panel as soon as it is updated in the language dropdown
2. Kiswahili should not show in the list of audio languages.

### Screenshots/Videos

https://github.com/user-attachments/assets/64f7f6e2-fed5-4fff-ab99-c2580d58dd7f

### What device/emulator are you using?

Pixel Tablet 10"

### Which Android version is your device/emulator running?

API 29

### Which version of the Oppia Android app are you using?

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by adhiamboperes**
## Explanation
Fix #5946
Weird app language update behaviour occured in the options screen, where the language in the side panel sometimes did not update when the app language selection was not changed. This is due to the presenter originally relying on the result of  `translationController.updateAppLanguage(profileId, selection)` to update the UI, but this is incorrect since this function's response payload is the _previous_  selection.

This is fixed by updating the language when the selection has changed in the viewmodel.

Additionally, it was observed that Kiswahili is in the list of audio languages, but it is not a supported audio language. This has been filtered out.

Tests have been added as well.

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only
|||
|--|--|
| [Swahili audio bug fix.webm](https://github.com/user-attachments/assets/465a8e75-9ff9-4af4-bc6e-9dd5686ea64c) | [2.1.2.3 app language overwritable and sticky.webm](https://github.com/user-attachments/assets/00223080-495c-4c76-b381-b352c7d3cc77) | 

More tablet video recordings : https://drive.google.com/drive/u/2/folders/1rkwYFPVLYN3wNMUgSGIzYZHf-fRK3olo

### CODE REVIEW

**Comment by adhiamboperes** [comment]
@BenHenning, please take a look at these bug fixes, they are very small changes.

**Comment by adhiamboperes** [comment]
@manas-yu, are you able to take a look at this PR?

File: app/src/main/java/org/oppia/android/app/options/AppLanguageFragmentPresenter.kt [hunk 1]
```diff
@@ -154,15 +153,12 @@ class AppLanguageFragmentPresenter @Inject constructor(
...
-          is AsyncResult.Success -> {
-            updateAppLanguage(result.value.selectedLanguage)
-          }
           is AsyncResult.Failure -> oppiaLogger.e(
             "AppLanguageFragment",
             "Failed to set AppLanguageSelection",
             result.error
           )
-          is AsyncResult.Pending -> {} // Do nothing.
+          else -> {} // Do nothing.
```
Comment (manas-yu) [inline app/src/main/java/org/oppia/android/app/options/AppLanguageFragmentPresenter.kt]: I think we can keep `is AsyncResult.Pending -> {}` to preserve exhaustiveness?

File: app/src/main/java/org/oppia/android/app/onboarding/AudioLanguageFragmentPresenter.kt [hunk 2]
```diff
@@ -141,6 +142,19 @@ class AudioLanguageFragmentPresenter @Inject constructor(
     return binding.root
   }
 
+  private fun List<OppiaLanguage>.filterUnsupportedAudioLanguages(): List<OppiaLanguage> {
```
Comment (manas-yu) [inline app/src/main/java/org/oppia/android/app/onboarding/AudioLanguageFragmentPresenter.kt:145]: Should we move this filter to domain in `TranslationController`?

**Review by manas-yu — CHANGES_REQUESTED** [review]
Thanks @adhiamboperes, I won't be active till the end of this month, just saw the PR was assigned, apologies for the delay. The changes look good, just minor comments.

File: app/src/main/java/org/oppia/android/app/onboarding/AudioLanguageFragmentPresenter.kt (hunk 2 above)
Comment (BenHenning) [reply app/src/main/java/org/oppia/android/app/onboarding/AudioLanguageFragmentPresenter.kt:145]: I think this is fine to go into this PR, but we should fix it properly in onboarding M2 by introducing a dedicated getSupportedAudioLanguages function in TranslationController, removing AudioLanguage proto since it's unnecessary, and updating getAudioTranslationContentLanguage to gracefully fall back when the user's save setting is not compatible with the supported languages in the current version of the app (e.g. using the new getSupportedAudioLanguages).

I'm also wondering if a similar fallback mechanism is needed for app language, too...

**Review by BenHenning — APPROVED** [review]

File: app/src/main/java/org/oppia/android/app/options/AppLanguageFragmentPresenter.kt (hunk 1 above)
Comment (adhiamboperes) [reply app/src/main/java/org/oppia/android/app/options/AppLanguageFragmentPresenter.kt]: I had earlier removed the success branch, which is why I changed to `else` initially. Reverting to `AsyncResult.Pending -> {} // Do nothing.` also means adding `AsyncResult.Success -> {} // Do nothing.`, which is redundant.

Removed the observer all together because we are not really interested in the outcome of the operation at this point.

**Comment by adhiamboperes** [comment]
Thanks for your reviews @BenHenning  and @manas-yu!

@manas-yu, PTAL at my revisions. Thanks!

**Comment by manas-yu** [comment]
Thanks @adhiamboperes, LGTM.

File: app/src/main/java/org/oppia/android/app/onboarding/AudioLanguageFragmentPresenter.kt (hunk 2 above)
Comment (manas-yu) [reply app/src/main/java/org/oppia/android/app/onboarding/AudioLanguageFragmentPresenter.kt:145]: Resolving to unblock but i agree with the points related to adding a dedicated `getSupportedAudioLanguages` function in `TranslationController`.

**Comment by adhiamboperes** [comment]
@manas-yu, The PR cannot be merged because of the changes requested status--please approve.

**Review by manas-yu — APPROVED** [review]
Approved changes.
