### PR TITLE
Fix #5592 : Enable submit button after linking items in Drag & Drop Sort Interaction

### LINKED ISSUE #5592: [BUG]: Submit Button Stays Disabled After Linking Items in Drag-and-Drop Input
### Describe the bug

In the Drag and Drop Sort Interaction when items are linked to represent equivalence (e.g., 0.6 and 3/5), the linked states are not recognized as different from the unlinked states, keeping the submit button disabled.

### Steps To Reproduce

1. Open the "Prototype Exploration".
2. Play through to the "Second Drag & Drop interaction".
3. Arrange the items in the order: 0.6, (unlinked) 3/5, 0.46, 0.35 and attempt to submit.
4. The app will indicate that the order is incorrect.
5. Click submit again with unchanged solution.
6. The Submit button will be disabled mentioning to arrange first.
7. Link 0.6 and 3/5, arranging them as 0.6, (linked) 3/5, 0.46, 0.35.
8. Despite the correct arrangement or change in the link states, the submit button will still remain disabled, preventing the successful submission of the answer.

### Expected Behavior

The submit button should enable immediately after there is a change in the link states.

### Screenshots/Videos

https://github.com/user-attachments/assets/191e8b52-7c74-4f9d-b721-7b967813c5e1

### What device/emulator are you using?

Pixel 2 [Emulator]

### Which Android version is your device/emulator running?

API 28

### Which version of the Oppia Android app are you using?

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by TanishMoral11**
## Explanation
Fixes #5592 , where the submit button did not become enabled after linking items in the Drag & Drop Sort Interaction. Previously, even when the items were correctly linked, the submit button remained disabled, preventing users from proceeding.

### **Changes Made**
- Updated logic to track linking and unlinking of items as a meaningful "state change."
- Ensured that the submit button becomes enabled as soon as items are linked or unlinked.
- Refactored the relevant functions to make sure the submit button reflects changes in real-time.

This change improves the overall UX, making it more intuitive for users to submit their answers after linking items. 
---

## Essential Checklist
- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix #5592 ".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

---
After Changes Video : 

https://github.com/user-attachments/assets/b6e3830c-e01c-4e70-933d-8d24cfee2a41

Screenshot of Passing Tests :
Screenshot 2024-12-13 232845

### CODE REVIEW

**Comment by TanishMoral11** [comment]
Hey @adhiamboperes , Could You PTAL !!

**Comment by TanishMoral11** [comment]
Hey @adhiamboperes , PTAL !! 
The PR is ready for review.

File: app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/DragAndDropSortInteractionViewModel.kt [hunk 1]
```diff
@@ -246,15 +250,24 @@ class DragAndDropSortInteractionViewModel private constructor(
       dragDropInteractionContentViewModel.itemIndex = index
       dragDropInteractionContentViewModel.listSize = _choiceItems.size
     }
-    // to update the list
+
+    // *Update the list*
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/DragAndDropSortInteractionViewModel.kt]: Here and below: please format comment correctly. Asterisks are only used in kdocs.

File: app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/DragAndDropSortInteractionViewModel.kt [hunk 2]
```diff
@@ -246,15 +250,24 @@ class DragAndDropSortInteractionViewModel private constructor(
...
     (adapter as BindableAdapter<*>).setDataUnchecked(_choiceItems)
+
+    // *Trigger pending answer check* to re-enable submit button
+    checkPendingAnswerError(AnswerErrorCategory.REAL_TIME)
   }
 
   private fun getSubmitTimeError(): DragAndDropSortInteractionError {
-    return if (_originalChoiceItems == _choiceItems) {
+    val hasItemsChanged = _originalChoiceItems.size != _choiceItems.size ||
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/DragAndDropSortInteractionViewModel.kt]:
```suggestion
    val haveItemsChanged = _originalChoiceItems.size != _choiceItems.size ||
```

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @TanishMoral11!

A UI test to verify the change in [StateFragmentTest.kt](https://github.com/oppia/oppia-android/pull/5323/files#diff-6cc8ab23c6444ea9c27014ead03753daf9fc4e240985de43775062dc314fe0ab) is required.

**Comment by TanishMoral11** [comment]
Hey @adhiamboperes PTAL !!

Before Changes :

https://github.com/user-attachments/assets/ed2f0dc1-432d-4b5b-833d-7438d9557f3c

After Changes :

https://github.com/user-attachments/assets/12e8d0b1-0f98-46d2-beae-600419fa4d6e

StateFragmentTest.kt Screen Shot :
Screenshot 2024-12-17 170906

File: app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/DragAndDropSortInteractionViewModel.kt (hunk 2 above)
Comment (TanishMoral11) [reply app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/DragAndDropSortInteractionViewModel.kt]: Done.

File: app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/DragAndDropSortInteractionViewModel.kt (hunk 1 above)
Comment (TanishMoral11) [reply app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/DragAndDropSortInteractionViewModel.kt]: Done.

**Comment by TanishMoral11** [comment]
Hey @adhiamboperes , PTAL !!
The PR Is Ready For Review.

StateFragmentTest.kt Screen Shot With Added New Test  :
image

**Review by adhiamboperes — APPROVED** [review]
Thanks @TanishMoral11! This LGTM.
