### PR TITLE
Fix #5981: Option Screen goes blank when user select the preferred audio language as Hindi

### LINKED ISSUE #5981: [BUG]: Option Screen goes blank when user select the preferred audio language as Hindi.
### Describe the bug

When learner selects the preferred audio language as Hindi, Options page is going blank.

### Steps To Reproduce

1. Launch the app with any profile 
2. Navigate to the Options either from left hamburger menu or in between any lesson.
3. select Preferred audio language as Hindi and
4.  Upon clicking (or touch )the back observe the Option screen/page goes blank.

### Expected Behavior

Preferred Audio language should set to Hindi and Learner should see the other Audio language options.

### Screenshots/Videos

Image

### What device/emulator are you using?

Pixel 8 Pro, Samsung Galaxy s8 

### Which Android version is your device/emulator running?

Android 16 , Android 9

### Which version of the Oppia Android app are you using?

0.16 Beta

### Additional Context

```php
2025-11-21 02:11:13.133  5807-5807  OptionControlViewModel  org.oppia.android  E  Failed to process results list (Ask Gemini)
org.oppia.android.util.data.AsyncResult$ChainedFailureException: org.oppia.android.util.data.AsyncResult$ChainedFailureException: org.oppia.android.util.data.AsyncResult$ChainedFailureException: org.oppia.android.util.data.AsyncResult$ChainedFailureException: java.lang.IllegalStateException: Language HINDI for usage AUDIO_TRANSLATIONS doesn't match supported language definitions
	at org.oppia.android.util.data.AsyncResult.transformWithResult(AsyncResult.kt:158)
	at org.oppia.android.util.data.AsyncResult.access$transformWithResult(AsyncResult.kt:49)
	at org.oppia.android.util.data.AsyncResult$combineWith$1.invoke(AsyncResult.kt:131)
	at org.oppia.android.util.data.AsyncResult$combineWith$1.invoke(AsyncResult.kt:130)
	at org.oppia.android.util.data.AsyncResult.transformWithResult(AsyncResult.kt:157)
	at org.oppia.android.util.data.AsyncResult.combineWith(AsyncResult.kt:130)
	at org.oppia.android.util.data.DataProviders$Companion$combineWith$1.retrieveData(DataProviders.kt:129)
	at org.oppia.android.util.data.DataProviders$Companion$combineWith$1$retrieveData$1.invokeSuspend(Unknown Source:14)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: org.oppia.android.util.data.AsyncResult$ChainedFailureException: org.oppia.android.util.data.AsyncResult$ChainedFailureException: org.oppia.android.util.data.AsyncResult$ChainedFailureException: java.lang.IllegalStateException: Language HINDI for usage AUDIO_TRANSLATIONS doesn't match supported language definitions
	at org.oppia.android.util.data.AsyncResult.transformWithResult(AsyncResult.kt:158)
	at org.oppia.android.util.data.AsyncResult.access$transformWithResult(AsyncResult.kt:49)
	at org.oppia.android.util.data.AsyncResult$combineWith$1.invoke(AsyncResult.kt:131)
	at org.oppia.android.util.data.AsyncResult$combineWith$1.invoke(AsyncResult.kt:130)
	at org.oppia.android.util.data.AsyncResult.transformWithResult(AsyncResult.kt:157)
	at org.oppia.android.util.data.AsyncResult.combineWith(AsyncResult.kt:130)
	at org.oppia.android.util.data.DataProviders$Companion$combineWith$1.retrieveData(DataProviders.kt:129)
	at org.oppia.android.util.data.DataProviders$Companion$combineWith$1$retrieveData$1.invokeSuspend(Unknown Source:14)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: org.oppia.android.util.data.AsyncResult$ChainedFailureException: org.oppia.android.util.data.AsyncResult$ChainedFailureException: java.lang.IllegalStateException: Language HINDI for usage AUDIO_TRANSLATIONS doesn't match supported language definitions
	at org.oppia.android.util.data.AsyncResult.transformWithResult(AsyncResult.kt:158)
	at org.oppia.android.util.data.AsyncResult.transform(AsyncResult.kt:95)
	at org.oppia.android.util.data.DataProviders$Companion$transform$1.retrieveData(DataProviders.kt:55)
	at org.oppia.android.util.data.DataProviders$Companion$transform$1$retrieveData$1.invokeSuspend(Unknown Source:14)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: org.oppia.android.util.data.AsyncResult$ChainedFailureException: java.lang.IllegalStateException: Language HINDI for usage AUDIO_TRANSLATIONS doesn't match supported language definitions
	at org.oppia.android.util.data.AsyncResult.transformWithResult(AsyncResult.kt:158)
	at org.oppia.android.util.data.AsyncResult.transform(AsyncResult.kt:95)
	at org.oppia.android.util.data.DataProviders$Companion$transform$1.retrieveData(DataProviders.kt:55)
	at org.oppia.android.util.data.DataProviders$Companion$transform$1$retrieveData$1.invokeSuspend(Unknown Source:14)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.IllegalStateException: Language HINDI for usage AUDIO_TRANSLATIONS doesn't match supported language definitions
	at org.oppia.android.domain.locale.LocaleController$retrieveAudioTranslationsLocale$1.invokeSuspend(LocaleController.kt:511)
	at org.oppia.android.domain.locale.LocaleController$retrieveAudioTranslationsLocale$1.invoke(Unknown Source:8)
	at org.oppia.android.domain.locale.LocaleController$retrieveAudioTranslationsLocale$1.invoke(Unknown Source:4)
	at org.oppia.android.util.data.AsyncResult$transformAsync$2.invokeSuspend(AsyncResult.kt:107)
	at org.oppia.android.util.data.AsyncResult$transformAsync$2.invoke(Unknown Source:8)
	at org.oppia.android.util.data.AsyncResult$transformAsync$2.invoke(Unknown Source:2)
	at org.oppia.android.util.data.AsyncResult.transformWithResultAsync(AsyncResult.kt:167)
	at org.oppia.android.util.data.AsyncResult.transformAsync(AsyncResult.kt:106)
	at org.oppia.android.util.data.DataProviders$Companion$transformAsync$1.retrieveData(DataProviders.kt:79)
	at org.oppia.android.domain.translation.TranslationController$getAudioTranslationContentLocale$1.invokeSuspend(TranslationController.kt:309)
	at org.oppia.android.domain.translation.TranslationController$getAudioTranslationContentLocale$1.invoke(Unknown Source:13)
```

### PR DESCRIPTION
**Pull request by adhiamboperes**
## Explanation
Fix #5981

The current implementation of the Audio Langauge Selection UI relies on the `AudioLanguage` enum to display a list of ausio langauges. This is problematic because some audio languages are not supported in prod.

This PR changes the supported audio languages list to be displayed to be derived from the supported `OppiaLanguage`s list. This means that the list will vary for dev or prod depending on the definitions in `supported_languages.textproto`.

An in-place migration has also been added in `TranslationController` to help users who had previously selected a language that is now unsupported due to configuration changes, recover gracefully.

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- For PRs introducing new UI elements or color changes, both light and dark mode screenshots must be included
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

|Before|After|
|---|---|
|https://github.com/user-attachments/assets/f69cb01b-2bf6-4b97-9990-97e0d3348b9b| https://github.com/user-attachments/assets/fce3e8d7-61d7-49d3-8ea2-2271bc5900c9|

### CODE REVIEW

**Comment by adhiamboperes** [comment]
PTAL @BenHenning

**Comment by BenHenning** [comment]
I think I took a rough pass on this over the meeting so sending back to you until the final changes are done.

**Comment by adhiamboperes** [comment]
@BenHenning, could you PTAL at the viewmodel in this PR -- I keep getting an empty list, so this means that the data is not being loaded from the controller. I am sure I am missing something, but I am not sure what.

File: app/src/main/java/org/oppia/android/app/options/AudioLanguageSelectionViewModel.kt [hunk 1]
```diff
@@ -91,6 +98,19 @@ class AudioLanguageSelectionViewModel @Inject constructor(
     this.profileId = profileId
   }
 
+  /** Maps an [OppiaLanguage] to an [AudioLanguage]. */
+  fun getAudioLanguageFromOppiaLanguage(oppiaLanguage: OppiaLanguage): AudioLanguage {
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/options/AudioLanguageSelectionViewModel.kt:101]: Nit: can & should be private. Also doesn't need a KDoc because of that.

File: app/src/main/java/org/oppia/android/app/options/AudioLanguageSelectionViewModel.kt [hunk 2]
```diff
@@ -52,17 +52,8 @@ class AudioLanguageSelectionViewModel @Inject constructor(
...
-    val sortedLanguages = languages.sortedWith(
-      compareBy<AudioLanguage> { it != AudioLanguage.ENGLISH_AUDIO_LANGUAGE }
-        .thenBy { appLanguageResourceHandler.computeLocalizedDisplayName(it) }
-    )
-    sortedLanguages.map(::createItemViewModel)
-  }
-
   /** Sets the list of audio languages supported by the app based on [OppiaLanguage]. */
+  // TODO(#6020): Replace getSupportedAppLanguages with an audio languages specific API.
   val supportedOppiaLanguagesLiveData: LiveData<List<OppiaLanguage>> by lazy {
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/options/AudioLanguageSelectionViewModel.kt]: Should be private now or replaced by the new list? We don't need two public fields as far as I can tell.

**Review by BenHenning — COMMENTED** [review]
Took a review pass. Need to actually debug per your request. Will follow up soon.

File: app/src/main/java/org/oppia/android/app/options/AudioLanguageSelectionViewModel.kt (hunk 2 above)
Comment (adhiamboperes) [reply app/src/main/java/org/oppia/android/app/options/AudioLanguageSelectionViewModel.kt]: This is shared by the v2 onboarding language UI, and used in https://github.com/oppia/oppia-android/blob/5d5d06610a913b210426661a6d6e1b61b8c5d32e/app/src/main/java/org/oppia/android/app/onboarding/AudioLanguageFragmentPresenter.kt#L109

**Review by BenHenning — APPROVED** [review]

File: app/src/main/java/org/oppia/android/app/options/AudioLanguageSelectionViewModel.kt (hunk 1 above)
Comment (BenHenning) [reply app/src/main/java/org/oppia/android/app/options/AudioLanguageSelectionViewModel.kt:101]: Presumably can't be because of the v1/v2 split.

Comment (adhiamboperes) [reply app/src/main/java/org/oppia/android/app/options/AudioLanguageSelectionViewModel.kt:101]: This is also used in `AudioLanguageFragmentPresenter` to replace https://github.com/oppia/oppia-android/blob/5d5d06610a913b210426661a6d6e1b61b8c5d32e/app/src/main/java/org/oppia/android/app/onboarding/AudioLanguageFragmentPresenter.kt#L202-L212
