### PR TITLE
Fix #4072 and Fix Part of #4938: Revised profile chooser UI

### LINKED ISSUE #4072: Creating multiple user not working with profile pic
**Describe the bug**l
While creating multiple users in the app, after adding a profile photo and name in respective fields I wasn't able to create new profile the "Done" button wasn't working or responding to clicks. 

P.S.  A new profile can be added w/o profile picture,and it works fine.

**To Reproduce**
1. Go to Switch Profile from the 
2. Click on 'add account'
3. Click on the Profile Picture icon and add a photo
4. Fill your username and click on done.

**Expected behavior**
This should create new profile, but it doesn't do anything when clicked on done.

**Demonstration**

https://user-images.githubusercontent.com/74976752/147110744-cf52acd5-aed7-4d9c-a5a0-15a2ef4a89ca.mp4

**Environment**
- Device/emulator being used: Xiaomi Redmi Note 10 Pro
- Android or SDK version: Android 11
- App version (you can get this through system app settings or via the admin controls menu in-app): 1.0

**Additional context**

### PR DESCRIPTION
**Pull request by adhiamboperes**
## Explanation

Fixes https://github.com/oppia/oppia-android/issues/4072.
The selected image uri created by `com.miui.gallery` app in Xiaomi devices has a different format from the android recommended uri, and is therefore not parsed correctly. Changing the name of the stored file, to be generated using a random UUID, fixes the issue. Please see https://github.com/oppia/oppia-android/issues/4072#issuecomment-2271713809 for more information. There have been no tests added for this bugfix because of issues setting up **ShadowContentResolver** to work with ProfileManagementController.

Fixes Part of https://github.com/oppia/oppia-android/issues/4938: Creates the new Profile chooser UI.
The portrait mode layout is a grid layout recylerview, while landscape mode utilizes a custom recyclerview to create a carousel. This design choice is kind of inconsistent, but more intuitive for users in landscape mode. `ProfileChooserFragmentPresenter` handles the data binding and UI interactions for both layouts. 

Care has been taken to ensure the existing profile behaviour e.g. random color selection and 10 profiles limit have been retained.

Additionally, a new `ParentScreen` enum has been created for the  onboarding IntroActivity to control  when to show the step count. Per PRD, the step count should not show for additional learners.

There have been minor bugfixes to ensure all the user pathways work as detailed in the TDD.

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes

### Phone
|LTR|RTL|
|--|--|
|Screenshot_1739971929|Screenshot_1740172190|
|Screenshot_1739971954|Screenshot_1740172286|
|Screenshot_1740176694|Screenshot_1740176834|
|Screenshot_1739972307|Screenshot_1740161079|
|Screenshot_1739972674|Screenshot_1740161000|
|Screenshot_1740160683|Screenshot_1739972780|

### Tablet
|Portrait|Landscape|
|--|--|
|Screenshot_1740179588|Screenshot_1740179297|
|Screenshot_1733945372|Screenshot_1733945392|

### CODE REVIEW

File: app/src/main/java/org/oppia/android/app/profile/ProfileItemViewModel.kt [hunk 1]
```diff
@@ -0,0 +1,6 @@
+package org.oppia.android.app.profile
+
+import org.oppia.android.app.model.Profile
+import org.oppia.android.app.viewmodel.ObservableViewModel
+
+class ProfileItemViewModel(val profile: Profile) : ObservableViewModel()
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/profile/ProfileItemViewModel.kt]: Add KDocs

File: scripts/assets/kdoc_validity_exemptions.textproto [hunk 2]
```diff
@@ -140,6 +140,7 @@ exempted_file_path: "app/src/main/java/org/oppia/android/app/player/stopplaying/
 exempted_file_path: "app/src/main/java/org/oppia/android/app/player/stopplaying/StopStatePlayingSessionListener.kt"
 exempted_file_path: "app/src/main/java/org/oppia/android/app/profile/AddProfileActivity.kt"
 exempted_file_path: "app/src/main/java/org/oppia/android/app/profile/AddProfileActivityPresenter.kt"
+exempted_file_path: "app/src/main/java/org/oppia/android/app/profile/AddProfileListener.kt"
```
Comment (adhiamboperes) [inline scripts/assets/kdoc_validity_exemptions.textproto]: Remove

File: scripts/assets/kdoc_validity_exemptions.textproto [hunk 3]
```diff
@@ -154,7 +155,7 @@ exempted_file_path: "app/src/main/java/org/oppia/android/app/profile/PinPassword
 exempted_file_path: "app/src/main/java/org/oppia/android/app/profile/PinPasswordViewModel.kt"
 exempted_file_path: "app/src/main/java/org/oppia/android/app/profile/ProfileChooserActivity.kt"
 exempted_file_path: "app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenter.kt"
-exempted_file_path: "app/src/main/java/org/oppia/android/app/profile/ProfileChooserViewModel.kt"
+exempted_file_path: "app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenterV1.kt"
```
Comment (adhiamboperes) [inline scripts/assets/kdoc_validity_exemptions.textproto:156]: Add KDocs and remove from here

File: app/src/main/res/layout/profile_selection_fragment.xml [hunk 4]
```diff
@@ -0,0 +1,138 @@
...
+  <androidx.constraintlayout.widget.ConstraintLayout
+    android:layout_width="match_parent"
+    android:background="@color/component_color_profile_selection_background_color"
+    android:layout_height="match_parent">
+
+    <androidx.core.widget.NestedScrollView
+      android:layout_width="match_parent"
+      android:layout_height="match_parent"
+      app:layout_constraintBottom_toTopOf="@id/profile_chooser_setting_icon"
+      android:layout_marginBottom="64dp"
```
Comment (adhiamboperes) [inline app/src/main/res/layout/profile_selection_fragment.xml]: Move all resources to respective files. Verify resources are properly named

**Review by adhiamboperes — COMMENTED** [review]
Self review pass 1

File: app/src/main/java/org/oppia/android/app/profile/ProfileListView.kt [hunk 5]
```diff
@@ -0,0 +1,89 @@
...
+            view,
+            viewModel
+          )
+        }
+      ).build()
+  }
+
+  /**
+   * Sets the list of profiles that this view shows.
+   * @param newDataList the new list of profiles to present
```
Comment (Vishwajith-Shettigar) [inline app/src/main/java/org/oppia/android/app/profile/ProfileListView.kt]: * @param newDataList the new list of profiles to present.
Add a period at the end of line.

File: app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenter.kt [hunk 6]
```diff
@@ -304,4 +321,34 @@ class ProfileChooserFragmentPresenter @Inject constructor(
       activity.startActivity(pinPasswordIntent)
     }
   }
+
+  /** Handles navigation to the [AdministratorControlsActivity]. */
```
Comment (Vishwajith-Shettigar) [inline app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenter.kt]: /** Handles navigation to either the [AdministratorControlsActivity] or [AdminAuthActivity]. */ 

The modified KDoc provides more clarity.

File: app/src/main/java/org/oppia/android/app/onboarding/IntroActivityPresenter.kt [hunk 7]
```diff
@@ -15,7 +16,7 @@ import javax.inject.Inject
 private const val TAG_LEARNER_INTRO_FRAGMENT = "TAG_INTRO_FRAGMENT"
 
 /** Argument key for bundling the profile nickname. */
-const val PROFILE_NICKNAME_ARGUMENT_KEY = "IntroFragment.Arguments"
+const val INTRO_FRAGMENT_ARGUMENT_KEY = "IntroFragment.Arguments"
```
Comment (Vishwajith-Shettigar) [inline app/src/main/java/org/oppia/android/app/onboarding/IntroActivityPresenter.kt]: Since you’ve touched this code, would it be possible to consider moving the IntroFragment creation and key into the IntroFragment itself?

**Comment by Vishwajith-Shettigar** [comment]
@adhiamboperes i have suggested some changes, PTAL. Thanks.

**Comment by BenHenning** [comment]
Will need to take a look at this next week.

@theMr17 might you have capacity to take a review pass on this PR?

File: gradle.properties [hunk 8]
```diff
@@ -23,4 +23,3 @@ android.enableJetifier=false
 kotlin.code.style=official
 # Needed to enable Android data binding.
 android.databinding.enableV2=true
-
```
Comment (theMr17) [inline gradle.properties:26]: Please revert this formatting change.

File: app/src/sharedTest/java/org/oppia/android/app/onboarding/IntroFragmentTest.kt [hunk 9]
```diff
@@ -233,6 +233,7 @@ class IntroFragmentTest {
     ActivityScenario<IntroActivity>? {
       val params = IntroActivityParams.newBuilder()
         .setProfileNickname(testProfileNickname)
+        .setParentScreen(IntroActivityParams.ParentScreen.CREATE_PROFILE_SCREEN)
```
Comment (theMr17) [inline app/src/sharedTest/java/org/oppia/android/app/onboarding/IntroFragmentTest.kt]: `testProfileNickname` is being indirectly tested by `testFragment_explanationText_isDisplayed`. Is there a way to verify the parent screen as well?

File: app/src/main/java/org/oppia/android/app/profile/ProfileChooserViewModel.kt [hunk 10]
```diff
@@ -16,7 +17,7 @@ import org.oppia.android.util.data.DataProviders.Companion.toLiveData
 import org.oppia.android.util.locale.OppiaLocale
 import javax.inject.Inject
 
-/** The ViewModel for [ProfileChooserFragment]. */
+/** The ViewModel for [ProfileActionChooserFragment]. */
```
Comment (theMr17) [inline app/src/main/java/org/oppia/android/app/profile/ProfileChooserViewModel.kt]: Is the `ProfileActionChooserFragment` going to be introduced in another PR? I couldn't find it.

File: app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenterV1.kt [hunk 11]
```diff
@@ -0,0 +1,274 @@
...
+                ClassroomListActivity.createClassroomListActivity(activity, profile.id)
+              )
+            } else {
+              activity.startActivity(
+                HomeActivity.createHomeActivity(activity, profile.id)
+              )
+            }
+          }
+        }
+      )
```
Comment (theMr17) [inline app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenterV1.kt]: The lambda argument can be moved out of the `observe` function. Ditto for other observers in the both the old and new presenters.

File: domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt [hunk 12]
```diff
@@ -857,7 +858,7 @@ class ProfileManagementController @Inject constructor(
     profileId: ProfileId,
     profileType: ProfileType,
     avatarImagePath: Uri?,
-    colorRgb: Int,
+    colorRgb: Int?,
```
Comment (theMr17) [inline domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt]: Under what circumstances could `colorRgb` be null?

File: app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenter.kt [hunk 13]
```diff
@@ -155,87 +218,40 @@ class ProfileChooserFragmentPresenter @Inject constructor(
...
+          AdminAuthEnum.PROFILE_ADD_PROFILE.value
         )
       )
     } else {
       activity.startActivity(
         AdminAuthActivity.createAdminAuthActivityIntent(
           activity,
           chooserViewModel.adminPin,
-          chooserViewModel.adminProfileId.internalId,
+          0,
```
Comment (theMr17) [inline app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenter.kt]:
```suggestion
          profileId = 0,
```
Nit.

File: app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenter.kt [hunk 14]
```diff
@@ -77,74 +77,137 @@ class ProfileChooserFragmentPresenter @Inject constructor(
...
       R.color.component_color_shared_profile_status_bar_color, activity, false
     )
-    binding = ProfileChooserFragmentBinding.inflate(
-      inflater,
-      container,
-      /* attachToRoot= */ false
-    )
-    binding.apply {
+
+    binding = ProfileSelectionFragmentBinding.inflate(inflater, container, false).apply {
```
Comment (theMr17) [inline app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenter.kt]:
```suggestion
    binding = ProfileSelectionFragmentBinding.inflate(inflater, container, /* attachToRoot= */ false).apply {
```
Nit.

File: app/src/main/res/layout-land/profile_item.xml
Comment (theMr17) [inline app/src/main/res/layout-land/profile_item.xml:1]: Do we need a separate landscape layout for this? It seems the primary difference lies only in the root layout.

File: app/src/main/res/layout/profile_selection_fragment.xml [hunk 15]
```diff
@@ -0,0 +1,130 @@
...
+          android:tag="profiles_list"
+          app:data="@{viewModel.profilesList}"
+          app:layout_constraintEnd_toEndOf="parent"
+          app:layout_constraintStart_toStartOf="parent"
+          app:layout_constraintTop_toBottomOf="@id/profile_selection_header" />
+      </androidx.constraintlayout.widget.ConstraintLayout>
+    </androidx.core.widget.NestedScrollView>
+
+    <ImageView
+      android:id="@+id/profile_chooser_setting_icon"
```
Comment (theMr17) [inline app/src/main/res/layout/profile_selection_fragment.xml]: From the screenshots, it seems we need to add some left margin to the icon on the portrait layout, perhaps the same amount as the bottom margin.

**Review by theMr17 — CHANGES_REQUESTED** [review]
Thanks @adhiamboperes, and apologies for the delayed review. I have left some comments, PTAL.

Additionally, I’m unsure why the _old_ presenter is named `v1`. Shouldn’t it be the other way around?

File: app/src/main/res/layout/profile_selection_fragment.xml (hunk 15 above)
Comment (adhiamboperes) [reply app/src/main/res/layout/profile_selection_fragment.xml]: Added a start margin.

File: app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenter.kt (hunk 14 above)
Comment (adhiamboperes) [reply app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenter.kt]: Added.

File: app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenter.kt (hunk 13 above)
Comment (adhiamboperes) [reply app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenter.kt]: Updated

File: domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt (hunk 12 above)
Comment (adhiamboperes) [reply domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt]: We usually provide a default in all cases. Updated to non-null.

File: gradle.properties (hunk 8 above)
Comment (adhiamboperes) [reply gradle.properties:26]: Done

File: app/src/sharedTest/java/org/oppia/android/app/onboarding/IntroFragmentTest.kt (hunk 9 above)
Comment (adhiamboperes) [reply app/src/sharedTest/java/org/oppia/android/app/onboarding/IntroFragmentTest.kt]: 1. I discovered that the simplest way to test intent parameters is by using the Fragment that initiates the intent. This ensures all necessary parameters are properly set. As a result, I created `CreateProfileFragmentTest.testFragment_landscape_continueButtonClicked_afterErrorShown_launchesLearnerIntroScreen`.
2. 
3. In `IntroFragmentTest`, the assumption is that all parameters are correctly provided during the test setup, as these are hardcoded in `launchOnboardingLearnerIntroActivity()`. Otherwise, we don’t have a public API available to access those parameters directly.

File: app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenterV1.kt (hunk 11 above)
Comment (adhiamboperes) [reply app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenterV1.kt]: Done

File: app/src/main/java/org/oppia/android/app/profile/ProfileChooserViewModel.kt (hunk 10 above)
Comment (adhiamboperes) [reply app/src/main/java/org/oppia/android/app/profile/ProfileChooserViewModel.kt]: No, I believe this was leftover from an earlier refactor. Removed all occurances.

File: app/src/main/java/org/oppia/android/app/onboarding/IntroActivityPresenter.kt (hunk 7 above)
Comment (adhiamboperes) [reply app/src/main/java/org/oppia/android/app/onboarding/IntroActivityPresenter.kt]: Done

File: app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenter.kt (hunk 6 above)
Comment (adhiamboperes) [reply app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenter.kt]: Updated.

File: app/src/main/java/org/oppia/android/app/profile/ProfileListView.kt (hunk 5 above)
Comment (adhiamboperes) [reply app/src/main/java/org/oppia/android/app/profile/ProfileListView.kt]: We typically only add a period to `@param` lines if they are multiline.

File: app/src/main/res/layout-land/profile_item.xml
Comment (adhiamboperes) [reply app/src/main/res/layout-land/profile_item.xml:1]: Yes, the individual views are constrained differently to the parent and to each other, in both landscape and portrait.

**Comment by adhiamboperes** [comment]
Thanks for your review @theMr17! I have addressed all your comments. Please let me know of any further questions or changes.
 
Re:

> Additionally, I’m unsure why the old presenter is named v1. Shouldn’t it be the other way around?

The new flow is v2, so we chose to rename the legacy flow with a v1 suffix, and when the feature is complete, we will remove all v1 classes and keep the new ones without a need to rename them.

**Comment by adhiamboperes** [comment]
Thanks for your review as well @Vishwajith-Shettigar! I have adressed all of your comments. PTAL and resolve.

File: app/src/main/java/org/oppia/android/app/profile/ProfileListView.kt (hunk 5 above)
Comment (Vishwajith-Shettigar) [reply app/src/main/java/org/oppia/android/app/profile/ProfileListView.kt]: Okay

**Review by Vishwajith-Shettigar — APPROVED** [review]
@adhiamboperes LGTM.

File: app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenter.kt (hunk 6 above)
Comment (Vishwajith-Shettigar) [reply app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenter.kt]: Okay.

**Comment by Vishwajith-Shettigar** [comment]
> Thanks for your review as well @Vishwajith-Shettigar! I have adressed all of your comments. PTAL and resolve.

I don't see the resolve button, so please feel free to resolve it yourself. Thank you.

File: app/src/main/java/org/oppia/android/app/onboarding/IntroFragment.kt [hunk 16]
```diff
@@ -46,7 +54,38 @@ class IntroFragment : InjectableFragment() {
...
+      parentScreen
     )
   }
+
+  companion object {
+    /** Argument key for bundling arguments into [IntroFragment] . */
+    const val INTRO_FRAGMENT_ARGUMENT_KEY = "IntroFragment.Arguments"
+
+    /**
+     * Creates a new instance of a IntroFragment.
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/onboarding/IntroFragment.kt]:
```suggestion
     * Creates a new instance of an [IntroFragment].
```

Slight doc rewording suggestion.

File: app/src/main/java/org/oppia/android/app/onboarding/IntroFragmentPresenter.kt [hunk 17]
```diff
@@ -43,6 +45,10 @@ class IntroFragmentPresenter @Inject constructor(
 
     profileManagementController.markProfileOnboardingStarted(profileId)
 
+    if (parentScreen == IntroActivityParams.ParentScreen.PROFILE_CHOOSER_SCREEN) {
+      binding.onboardingStepsCount?.visibility = View.GONE
+    }
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/onboarding/IntroFragmentPresenter.kt:50]: Are both possibilities of this conditional covered in intro fragment tests?

File: app/src/main/java/org/oppia/android/app/profile/ProfileListView.kt [hunk 18]
```diff
@@ -0,0 +1,89 @@
...
+   */
+
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/profile/ProfileListView.kt]: Please remove blank newline.

File: domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt [hunk 19]
```diff
@@ -887,7 +888,7 @@ class ProfileManagementController @Inject constructor(
           ProfileAvatar.newBuilder().setAvatarImageUri(imageUri).build()
       } else {
         updatedProfile.avatar =
-          ProfileAvatar.newBuilder().setAvatarColorRgb(colorRgb).build()
+          colorRgb.let { color -> ProfileAvatar.newBuilder().setAvatarColorRgb(color).build() }
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt]: Why this change? Using the scope function seems unnecessary here and may harm the code's readability.

File: domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt [hunk 20]
```diff
@@ -1225,7 +1226,7 @@ class ProfileManagementController @Inject constructor(
     // TODO(#3616): Migrate to the proper SDK 29+ APIs.
     @Suppress("DEPRECATION") // The code is correct for targeted versions of Android.
     val bitmap = MediaStore.Images.Media.getBitmap(context.contentResolver, avatarImagePath)
-    val fileName = avatarImagePath.pathSegments.last()
+    val fileName = UUID.randomUUID().toString()
```
Comment (BenHenning) [inline domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt:1228]: Since this is fixing a bug, is it possible for us to add a test to at least verify this functionality (even if it's a bit contrived)?

File: app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenter.kt [hunk 21]
```diff
@@ -77,74 +78,137 @@ class ProfileChooserFragmentPresenter @Inject constructor(
...
-    subscribeToWasProfileEverBeenAdded()
-    binding.profileRecyclerView.apply {
+
+    binding.addProfileButton.setOnClickListener { addProfileButtonClickListener() }
+    binding.addProfilePrompt.setOnClickListener { addProfileButtonClickListener() }
+
+    return binding.root
+  }
+
+  private fun ProfileSelectionFragmentBinding.setupPortraitMode() {
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenter.kt]: Nit here & below: the action form should be 'setUp' (as the noun is 'setup').

File: app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenter.kt [hunk 22]
```diff
@@ -77,74 +78,137 @@ class ProfileChooserFragmentPresenter @Inject constructor(
...
+    val targetView = snapHelper.findSnapView(layoutManager ?: newLayoutManager)
+    targetView?.let { recyclerView ->
+      val distance =
+        snapHelper.calculateDistanceToFinalSnap(layoutManager ?: newLayoutManager, recyclerView)
+      val scrollDistance = distance?.get(0) ?: 0
+      val scrollableWidth = binding.profilesListLandscape?.let {
+        it.width - (it.paddingStart + it.paddingEnd)
+      } ?: 0
+      val offset =
+        if (isLeft) scrollDistance - scrollableWidth else scrollableWidth - scrollDistance
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenter.kt]: Does this work correctly in RTL?

File: app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenter.kt [hunk 23]
```diff
@@ -155,87 +219,40 @@ class ProfileChooserFragmentPresenter @Inject constructor(
...
+          AdminAuthEnum.PROFILE_ADD_PROFILE.value
         )
       )
     } else {
       activity.startActivity(
         AdminAuthActivity.createAdminAuthActivityIntent(
           activity,
           chooserViewModel.adminPin,
-          chooserViewModel.adminProfileId.internalId,
+          profileId = 0,
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenter.kt]: Can we avoid hardcoding 0 here?

1. It makes it harder to move away from the default integer 0 being a valid profile ID (#5440).
2. It should eventually be possible for non-ID 0 profiles to become the primary administrator (or, at least, the code should be robust against such a scenario).

File: app/src/main/java/org/oppia/android/app/profile/ProfileChooserViewModel.kt [hunk 24]
```diff
@@ -26,16 +27,73 @@ class ProfileChooserViewModel @Inject constructor(
...
 
+  /** Livedata representing the list of profiles on the app, to be bound to the recyclerview. */
+  val profilesList: LiveData<List<ProfileItemViewModel>> by lazy {
+    Transformations.map(
+      profileManagementController.getProfiles().toLiveData(), ::retrieveProfiles
+    )
+  }
+
+  private fun retrieveProfiles(profilesResult: AsyncResult<List<Profile>>):
+    List<ProfileItemViewModel> {
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/profile/ProfileChooserViewModel.kt]:
```suggestion
  private fun retrieveProfiles(
    profilesResult: AsyncResult<List<Profile>>
  ): List<ProfileItemViewModel> {
```

Prefer this format, instead. We generally use this because it avoids needing to indent the entire method body one further indentation compared to all other same-level members in the class (which makes it stand out).

File: app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt [hunk 25]
```diff
@@ -591,38 +650,280 @@ class ProfileChooserFragmentTest {
...
+        itemPosition = 0,
+        targetView = R.id.profile_last_visited,
+        stringToMatch = "${context.getString(R.string.profile_last_used)} just now",
+        recyclerViewId = R.id.profiles_list_landscape,
+      )
+    }
+  }
+
+  @Test
+  fun testFragment_enableOnboardingV2_addManyProfiles_checkProfilesSortedAndNoAddProfile() {
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt]: Is the 'no add profile' bit actually being tested?

Also, I suggest moving that to its own test (so that verifying sorting & the add profile button absence are separate tests).

File: app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt [hunk 26]
```diff
@@ -591,38 +650,280 @@ class ProfileChooserFragmentTest {
...
       intended(hasComponent(ClassroomListActivity::class.java.name))
       hasExtraWithKey(PROFILE_ID_INTENT_DECORATOR)
     }
   }
 
-  private fun createProfileChooserActivityIntent(): Intent {
-    return ProfileChooserActivity
-      .createProfileChooserActivity(ApplicationProvider.getApplicationContext())
+  @Test
+  fun testFragment_enableOnboardingV2_checkAddProfileTextIsDisplayed() {
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt:661]: Have you verified that all key functionality from the v1 tests are being appropriately covered in v2 versions? I want to make sure since:

1. It can help ensure correctness as unit tests are good at catching super specific mistakes (e.g. from regressions that the previous implementation has had and fixed).
2. It's valuable to cover old tests since they'll likely be unconditionally deleted during the cleanup PR.

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @adhiamboperes! Took a full pass. Some top-level feedback:
- The 'add more profiles' and floating action button feel a bit crowded on portrait and would benefit from a bit more space (similar to the landscape version).
- How do the arrows and fling behaviors in landscape behave in RTL mode?
- As discussed during today's CLaM meeting, the landscape layout looks a bit off due to the solo learner bubble being so far left. I'm not quite sure that it should be centered, though, as landscape layouts are usually designed to have important elements easily reachable with one's thumbs. Perhaps placing it at the 1/4 or 1/3 portion of the screen from the left might be a bit cleaner? This seems even worse on tablet landscape mode--that's a lot of blank whitespace.
- As discussed during today's CLaM meeting, how does the new layout behave with Talkback?

File: app/src/main/java/org/oppia/android/app/onboarding/IntroFragment.kt (hunk 16 above)
Comment (adhiamboperes) [reply app/src/main/java/org/oppia/android/app/onboarding/IntroFragment.kt]: Updated.

File: app/src/main/java/org/oppia/android/app/onboarding/IntroFragmentPresenter.kt (hunk 17 above)
Comment (adhiamboperes) [reply app/src/main/java/org/oppia/android/app/onboarding/IntroFragmentPresenter.kt:50]: Added a test for the `PROFILE_CHOOSER_SCREEN` parent.

File: app/src/main/java/org/oppia/android/app/profile/ProfileListView.kt (hunk 18 above)
Comment (adhiamboperes) [reply app/src/main/java/org/oppia/android/app/profile/ProfileListView.kt]: Done

File: domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt (hunk 19 above)
Comment (adhiamboperes) [reply domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt]: In an earlier commit, I had set `colorRgb` to be nullabe, so this was meant for nullsafety. But I have since refactored the code so that `colorRgb` is not nullable, and I have also reverted this change.

File: app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenter.kt (hunk 21 above)
Comment (adhiamboperes) [reply app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenter.kt]: Refactored.

File: app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenter.kt (hunk 22 above)
Comment (adhiamboperes) [reply app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenter.kt]: With some modification to account for layout direction, it works correctly.
https://github.com/user-attachments/assets/5371b810-e068-48e0-8129-95dff2bee516

File: app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenter.kt (hunk 23 above)
Comment (adhiamboperes) [reply app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenter.kt]: Updated to use the `adminProfileId` variable available in the viewmodel.

File: app/src/main/java/org/oppia/android/app/profile/ProfileChooserViewModel.kt (hunk 24 above)
Comment (adhiamboperes) [reply app/src/main/java/org/oppia/android/app/profile/ProfileChooserViewModel.kt]: Updated, thanks.

File: app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt (hunk 26 above)
Comment (adhiamboperes) [reply app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt:661]: Yes, I audited the tests. Tests that should pass for both feature flag on/off are not gated behind the platform parameter. Tests that will be removed are gated ` TestPlatformParameterModule.forceEnableOnboardingFlowV2(false)` while tests that will be kept have ` TestPlatformParameterModule.forceEnableOnboardingFlowV2(true)`. This should be documented in the issue tracking cleanup.

File: app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt (hunk 25 above)
Comment (adhiamboperes) [reply app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt]: Split the test into 2 and added the assertion for the add profile button.

**Review by theMr17 — APPROVED** [review]
Apologies for the delayed review. Thanks @adhiamboperes, this LGTM!

**Comment by BenHenning** [comment]
@adhiamboperes I think you mentioned in our quick sync today that you'd like another review on this PR. Is that correct, and does that mean that this PR is ready for another pass? I'm asking since it's still assigned to you, so I wasn't sure. :)

**Comment by adhiamboperes** [comment]
@BenHenning, PTAL.

File: app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenter.kt [hunk 27]
```diff
@@ -170,8 +169,25 @@ class ProfileChooserFragmentPresenter @Inject constructor(
...
-        if (isLeft) scrollDistance - scrollableWidth else scrollableWidth - scrollDistance
+
+      // Check layout direction.
+      val isRtl = binding.profilesListLandscape?.let { ViewCompat.getLayoutDirection(it) } ==
+        ViewCompat.LAYOUT_DIRECTION_RTL
+
+      val scrollLeftInRtl = isRtl && isLeft
+      val scrollRightInRtl = isRtl && !isLeft
+      val scrollLeftInLtr = !isRtl && isLeft
+      val scrollRightInLtr = !isRtl && !isLeft
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenter.kt:199]: Are there tests for verifying this RTL/LTR and directional scrolling behaviors?

File: app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenter.kt (hunk 22 above)
Comment (BenHenning) [reply app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenter.kt]: This looks really nice! Just to check (since I couldn't quite determine from the video): does RTL mode start with being scrolled all the way to the right? I see that the profile list is correctly reversed (with admin starting at the right), so just wanted to check for initial scroll state.

File: domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt (hunk 20 above)
Comment (BenHenning) [reply domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt:1228]: Reminder on this comment since I don't think it was addressed yet.

**Review by BenHenning — CHANGES_REQUESTED** [review]
Thanks @adhiamboperes! Took another pass. I think most of my previous comments have been addressed, but a few haven't. Besides the open conversations, this includes:

> * The 'add more profiles' and floating action button feel a bit crowded on portrait and would benefit from a bit more space (similar to the landscape version).
> * As discussed during today's CLaM meeting, the landscape layout looks a bit off due to the solo learner bubble being so far left. I'm not quite sure that it should be centered, though, as landscape layouts are usually designed to have important elements easily reachable with one's thumbs. Perhaps placing it at the 1/4 or 1/3 portion of the screen from the left might be a bit cleaner? This seems even worse on tablet landscape mode--that's a lot of blank whitespace.
> * As discussed during today's CLaM meeting, how does the new layout behave with Talkback?

PTAL at the open comment threads and the above.

File: app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenter.kt (hunk 27 above)
Comment (adhiamboperes) [reply app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenter.kt:199]: I have added tests that verify both conditions when using the arrows. Swipe behaviour is covered by existing tests using "scrollTo()".

File: app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenter.kt (hunk 22 above)
Comment (adhiamboperes) [reply app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenter.kt]: The list is reversed in rtl, so it is not scrolled - users should not be able to see a flicker.

File: domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt (hunk 20 above)
Comment (adhiamboperes) [reply domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt:1228]: I haven't had much success working with shadowcontentresolver or shadowmediaplayer to resolve this, mainly because  `context.contentResolver.openInputStream(uri)!!` tis used within a private function, so I found it difficult to mock via the public API `updateProfileAvatar`

**Comment by adhiamboperes** [comment]
@BenHenning, PTAL.

I have addressed all pending comments, and update the screenshots in the main PR body. I should be able to upload talkback video tomorrow -- currently facing some physical device issues.

File: app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt [hunk 28]
```diff
@@ -712,6 +717,191 @@ class ProfileChooserFragmentTest {
...
+        )
+
+        testCoroutineDispatchers.runCurrent()
+      }
+    }
+  }
+
+  @Test
+  @Config(qualifiers = "land")
+  fun testFragment_enableOnboardingV2_rtl_checkRightArrowScrollBehaviourIscorrect() {
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt]: Are this & the one above actually verifying RTL? Only testFragment_enableOnboardingV2_rtl_checkListIsAlphabetical seems to be enabling RTL explicity.

File: app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt [hunk 29]
```diff
@@ -712,6 +717,191 @@ class ProfileChooserFragmentTest {
...
+  @Test
+  @Config(qualifiers = "land")
+  fun testFragment_enableOnboardingV2_rtl_checkListIsAlphabetical() {
+    TestPlatformParameterModule.forceEnableOnboardingFlowV2(true)
+    profileTestHelper.addOnlyAdminProfile()
+    profileTestHelper.addMoreProfiles(9)
+
+    launch(ProfileChooserActivity::class.java).use {
+      it.onActivity { activity ->
+        activity.window.decorView.layoutDirection = ViewCompat.LAYOUT_DIRECTION_RTL
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt]: Does this actually cause the activity to relayout into RTL?

An alternative that might work is switching the language to Arabic since that should force RTL as well, I think.

File: app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt [hunk 30]
```diff
@@ -712,6 +717,191 @@ class ProfileChooserFragmentTest {
...
+          )
+        )
+        testCoroutineDispatchers.runCurrent()
+      }
+    }
+  }
+
+  @Test
+  @Config(qualifiers = "land")
+  fun testFragment_enableOnboardingV2_rtl_checkLeftArrowScrollBehaviourIscorrect() {
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt]:
```suggestion
  fun testFragment_enableOnboardingV2_rtl_checkLeftArrowScrollBehaviourIsCorrect() {
```

Ditto above. Though perhaps we can be more specific than 'correct'?

File: app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt [hunk 31]
```diff
@@ -712,6 +717,191 @@ class ProfileChooserFragmentTest {
...
+        onView(
+          withViewAtPosition(
+            recyclerViewId = R.id.profiles_list_landscape,
+            position = 0,
+            targetViewId = R.id.profile_name_text,
+            itemMatcher = allOf(withText("Admin"), isDisplayed())
+          )
+        )
+
+        testCoroutineDispatchers.runCurrent()
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt]: Why is this needed? Can't the test just end?

Ditto below.

File: app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt [hunk 32]
```diff
@@ -712,6 +717,191 @@ class ProfileChooserFragmentTest {
...
+    launch(ProfileChooserActivity::class.java).use {
+      testCoroutineDispatchers.runCurrent()
+
+      it.onActivity {
+        onView(
+          withViewAtPosition(
+            recyclerViewId = R.id.profiles_list_landscape,
+            position = 0,
+            targetViewId = R.id.profile_name_text,
+            itemMatcher = allOf(withText("Admin"), isDisplayed())
```
Comment (BenHenning) [inline app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt]: This doesn't technically verify that it's alphabetical, just that admin is first. Do we already verify elsewhere the whole list is populated correctly?

File: app/src/main/res/layout/profile_selection_fragment.xml [hunk 33]
```diff
@@ -100,7 +100,8 @@
       android:layout_width="@dimen/profile_selection_fragment_icon_size"
       android:layout_height="@dimen/profile_selection_fragment_icon_size"
       android:layout_marginEnd="@dimen/profile_selection_fragment_add_profile_button_margin_end"
-      android:contentDescription="@string/profile_selection_profile_icon_description"
+      android:layout_marginBottom="@dimen/profile_selection_fragment_add_button_margin_bottom"
+        android:contentDescription="@string/profile_selection_profile_icon_description"
```
Comment (BenHenning) [inline app/src/main/res/layout/profile_selection_fragment.xml]: Nit: please remove extra indentation here.

File: app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenter.kt [hunk 34]
```diff
@@ -83,6 +84,16 @@ class ProfileChooserFragmentPresenter @Inject constructor(
 ) {
   private lateinit var binding: ProfileSelectionFragmentBinding
 
+  /**
+   * Used to retrieve the layout direction that should be used to mirror the direction of the
+   * list based on locale.
+   */
+  @Inject lateinit var resourceHandler: AppLanguageResourceHandler
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenter.kt]: Since this class is a presenter, this can be injected directly via the class's constructor.

File: domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt (hunk 20 above)
Comment (BenHenning) [reply domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt:1228]: Are you able to document what you've tried and what hasn't worked in a new issue that we could file to track this? While I'm fine with postponing adding a test for this now, it will eventually become a requirement as we work in the long-term toward 100% code coverage. It'd be nice to capture your efforts so that they don't need to be redone in the future.

File: app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenter.kt (hunk 22 above)
Comment (BenHenning) [reply app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenter.kt]: Sorry, I don't think that quite answers my question. The video seems to start with the list of profiles scrolled in the middle, so it's unclear which side of the list the user begins on. Is it the right or left when in RTL?

**Review by BenHenning — CHANGES_REQUESTED** [review]
> @BenHenning, PTAL.
> 
> I have addressed all pending comments, and update the screenshots in the main PR body. I should be able to upload talkback video tomorrow -- currently facing some physical device issues.

Thanks @adhiamboperes! Took a pass on the new code and left some comments. Just to check, did you address all of my 3 points in the main review message above (quoted from 2 reviews ago)? I did a scan on the images changed in the main PR post, but they don't seem different in any noticeable way and it seems like the original concerns may still be present (minus perhaps Talkback but I don't yet see a video for that to review).

File: app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt (hunk 30 above)
Comment (adhiamboperes) [reply app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt]: I updated name to `testFragment_enableOnboardingV2_rtl_checkLeftArrowScrollsListToTheRight`, ditto for similar tests.

File: app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt (hunk 29 above)
Comment (adhiamboperes) [reply app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt]: I refactored tests to use the Arabic locale, thanks for the suggestion!

File: app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt (hunk 28 above)
Comment (adhiamboperes) [reply app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt]: I refactored this test to use the Arabic locale.

File: app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt (hunk 31 above)
Comment (adhiamboperes) [reply app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt]: It is not required. I have removed it everywhere.

File: app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt (hunk 32 above)
Comment (adhiamboperes) [reply app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt]: I have refactored the test to verify the position of all the created profiles.

File: app/src/main/res/layout/profile_selection_fragment.xml (hunk 33 above)
Comment (adhiamboperes) [reply app/src/main/res/layout/profile_selection_fragment.xml]: Done

File: app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenter.kt (hunk 34 above)
Comment (adhiamboperes) [reply app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenter.kt]: Refactored.

**Comment by adhiamboperes** [comment]
> Thanks @adhiamboperes! Took a full pass. Some top-level feedback:
> 
> * The 'add more profiles' and floating action button feel a bit crowded on portrait and would benefit from a bit more space (similar to the landscape version).

I reduced the end margin to create more space between the recyclerview and the button. Also increased the spacing between the button and the prompt.
|Original Layout|Modified Layout|
|---|---|
|port_multiple|Screenshot_1740176689|

> * How do the arrows and fling behaviors in landscape behave in RTL mode?

https://github.com/user-attachments/assets/ace3154e-cff8-444d-9fde-ef3c4eecb623

> * As discussed during today's CLaM meeting, the landscape layout looks a bit off due to the solo learner bubble being so far left. I'm not quite sure that it should be centered, though, as landscape layouts are usually designed to have important elements easily reachable with one's thumbs. Perhaps placing it at the 1/4 or 1/3 portion of the screen from the left might be a bit cleaner? This seems even worse on tablet landscape mode--that's a lot of blank whitespace.

The single profile(or first few profiles), are now placed from the 1/3 part of the screen.
|Original Layout|Modified Layout|
|---|---|
|land_1|Screenshot_1739972307|
|tablet_1|Screenshot_1740179297|



> * As discussed during today's CLaM meeting, how does the new layout behave with Talkback?

The layout works as expected both with the arrows and with regular scrolling.
https://github.com/user-attachments/assets/86a954ee-1660-44d4-9718-8fb68862cc7a

File: domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt (hunk 20 above)
Comment (adhiamboperes) [reply domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt:1228]: I filed https://github.com/oppia/oppia-android/issues/5716 to track this(could benefit from a few more details in the solutions tried section)

**Comment by adhiamboperes** [comment]
@BenHenning, PTAL.

File: app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt (hunk 30 above)
Comment (BenHenning) [reply app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt]: Much clearer naming, thanks!

File: domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt (hunk 20 above)
Comment (BenHenning) [reply domain/src/main/java/org/oppia/android/domain/profile/ProfileManagementController.kt:1228]: Sounds good--thanks!

File: app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenter.kt (hunk 22 above)
Comment (BenHenning) [reply app/src/main/java/org/oppia/android/app/profile/ProfileChooserFragmentPresenter.kt]: Per the video that you shared, this does work correctly (there just might be a small graphical bit to fix yet--adding that directly elsewhere).

**Review by BenHenning — COMMENTED** [review]
Thanks @adhiamboperes! The new spacing looks fantastic, and the Talkback flow looks really good, too!

I think there is just one final thing to address, otherwise the PR LGTM. Specifically: per your excellent video on the RTL behavior, https://m2.material.io/design/usability/bidirectionality.html#localization suggests that the moving arrows need to be reversed (they feel incorrect right now, and I think this is the reason why).

**Comment by adhiamboperes** [comment]
In the latest commit, I have made some changes that include:

1. Creating dimensions specific to the profile list layout
2. Exporting string literals to the strings file.
3. Removing constraints and creating a dynamic margin decorator instead, using a binding adapter.

|||
|---|---|
|Screenshot_1742593191|Screenshot_1742850540|
|Screenshot_1742846355|Screenshot_1742850439|
|Screenshot_1742846530|Screenshot_1742849009|

**Comment by adhiamboperes** [comment]
@BenHenning, PTAL.

**Comment by adhiamboperes** [comment]
> Thanks @adhiamboperes! The new spacing looks fantastic, and the Talkback flow looks really good, too!
> 
> I think there is just one final thing to address, otherwise the PR LGTM. Specifically: per your excellent video on the RTL behavior, https://m2.material.io/design/usability/bidirectionality.html#localization suggests that the moving arrows need to be reversed (they feel incorrect right now, and I think this is the reason why).



I had set auto mirrored to be true in the vectors. That has changed now.

Screenshot_1742846668

File: app/src/main/java/org/oppia/android/app/recyclerview/DynamicMarginItemDecorator.kt [hunk 35]
```diff
@@ -0,0 +1,43 @@
...
+import android.graphics.Rect
+import android.view.View
+import androidx.recyclerview.widget.RecyclerView
+import org.oppia.android.app.R
+
+/**
+ * A decorator that assigns a dynamic margin to a recyclerview based on the number of items in the
+ * adapter.
+ */
+class DynamicMarginItemDecorator(
```
Comment (BenHenning) [inline app/src/main/java/org/oppia/android/app/recyclerview/DynamicMarginItemDecorator.kt]: I think either the decorator itself needs to be specific to profile selection, or the dimensions need to be generalized. The current general adapter + specific dimensions is a bit confusing.

Feel free to resolve this yourself once addressed.

**Review by BenHenning — APPROVED** [review]
Thanks @adhiamboperes! Just one comment, otherwise this LGTM!

File: app/src/main/java/org/oppia/android/app/recyclerview/DynamicMarginItemDecorator.kt (hunk 35 above)
Comment (adhiamboperes) [reply app/src/main/java/org/oppia/android/app/recyclerview/DynamicMarginItemDecorator.kt]: I have thought about this -- creating a generic decorator requires a lot more design, e.g. allowing the desired item count to be customizable, and passing in all the variations of margins desired as well as validating that the provided margins are for the desired boundary.

On the other hand, as is, the decorator supports the specific needs of the profile list. I have opted to rename the class and move the file to the profile package.
