### PR TITLE
Fix #1438 & #1761: Switch Profile Dialog lost in orientation change

### LINKED ISSUE #1438: Switch Profile Dialog lost in orientation change
**Describe the bug**
The Dialog box which asks for the confirmation before exiting the profile is getting lost when open and change screen orientation. It's not crashing but giving an error in logcat.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Oppia app
2. Open Navigation drawer
3. Click on Switch Profile -> Dialog will appear
4. Change screen orientation (portrait to landscape or vice versa)
5. Dialog will disappear
6. In navigation Drawer, "switch profile" will get marked
7. open/close nav drawer - "switch profile" remain marked

**Expected behaviour**
The dialog should remain on the screen or if we are planning to make it disappear from the screen, home should be marked in navigation drawer. 

**Screenshots**
ezgif com-video-to-gif

**Device**
- Device/emulator being used
- SDK version

**Error**
<pre>
2020-07-01 15:06:31.606 14368-14368/? E/WindowManager: android.view.WindowLeaked: Activity org.oppia.app.home.HomeActivity has leaked window DecorView@17d1b23[HomeActivity] that was originally added here
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:544)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:346)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
        at android.app.Dialog.show(Dialog.java:329)
        at <b>org.oppia.app.drawer.NavigationDrawerFragmentPresenter.openActivityByMenuItemId(NavigationDrawerFragmentPresenter.kt:253)</b>
        at <b>org.oppia.app.drawer.NavigationDrawerFragmentPresenter.onNavigationItemSelected(NavigationDrawerFragmentPresenter.kt:395)</b>
        at com.google.android.material.navigation.NavigationView$1.onMenuItemSelected(NavigationView.java:210)
        at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
        at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
        at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
        at com.google.android.material.internal.NavigationMenuPresenter$1.onClick(NavigationMenuPresenter.java:416)
        at android.view.View.performClick(View.java:6608)
        at android.view.View.performClickInternal(View.java:6585)
        at android.view.View.access$3100(View.java:785)
        at android.view.View$PerformClick.run(View.java:25921)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
</pre>

**Half Solution**
Dismiss the dialog when activity destroy. This resolves the window leaking problem but the dialog still lost. 
<pre>
override fun onDestroy() {
    navigationDrawerFragmentPresenter.dismissDialog()
    super.onDestroy()
  }
fun dismissDialog() {
    dialog.dismiss()
  }
</pre>

### LINKED ISSUE #1761: HomeActivity backpress dialog lost in orientation change
**Describe the bug**
The dialog which asks for exit current profile gets lost when an orientation change

**To Reproduce**
1. Open app at Home Screen
2. press back button on the android screen - dialog appears 
3. dialog lost

**Expected behavior**
Dialog should not lose

### PR DESCRIPTION
**Pull request by anandwana001**
## Explanation

Fix #1438 #1761

### How to test
1. open nav drawer
2. click on switch profile -> dialog appears
3. change orientation -> check if dialog visible or not

### How to review 
Check if the added test case works

## Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR is made from a branch that's **not** called "develop".
- [x] The PR is made from a branch that is up-to-date with "develop".
- [x] The PR's branch is based on "develop" and not on any other branch.
- [x] The PR is **assigned** to an appropriate reviewer in both the **Assignees** and the **Reviewers** sections.

### CODE REVIEW

File: app/src/main/java/org/oppia/app/drawer/NavigationDrawerSwitchProfileDialogFragment.kt [hunk 1]
```diff
@@ -0,0 +1,66 @@
...
+import androidx.appcompat.view.ContextThemeWrapper
+import androidx.drawerlayout.widget.DrawerLayout
+import androidx.fragment.app.DialogFragment
+import org.oppia.app.R
+import org.oppia.app.profile.ProfileChooserActivity
+
+/** [DialogFragment] that gives option to either cancel or exit current profile */
+class NavigationDrawerSwitchProfileDialogFragment : DialogFragment() {
+
+  private lateinit var menu: Menu
```
Comment (anandwana001) [inline app/src/main/java/org/oppia/app/drawer/NavigationDrawerSwitchProfileDialogFragment.kt]: One suggestion I am looking for here:
Another approach is where we can have an interface and rather than passing `menu` and `drawerLayout` object we can implement an interface in `NavigationDrawerFragment` and use it from there. 
The only thing we have to achieve with these objects is 
```
menu.getItem(
          NavigationDrawerItem.HOME.ordinal
        ).isChecked =
          true
        drawerLayout.closeDrawers()
```

Comment (rt4914) [reply app/src/main/java/org/oppia/app/drawer/NavigationDrawerSwitchProfileDialogFragment.kt]: This approach does sound correct. Please have a look at top level comment.

**Review by rt4914 — CHANGES_REQUESTED** [review]
This similar implementation is used in `HomeActivity` also, so I suggest applying this fragment there too.

Also, please update/rename `NavigationDrawerSwitchProfileDialogFragment ` so that its not just linked to NavigationDrawer.

Something like `ExitProfileDialogFragment`

Also, update test cases accordingly.

File: app/src/main/java/org/oppia/app/drawer/NavigationDrawerFragmentPresenter.kt [hunk 2]
```diff
@@ -273,6 +257,14 @@ class NavigationDrawerFragmentPresenter @Inject constructor(
     )
   }
 
+  fun markHomeMenuCloseDrawer() {
+    binding.fragmentDrawerNavView.menu.getItem(
+      NavigationDrawerItem.HOME.ordinal
```
Comment (anandwana001) [inline app/src/main/java/org/oppia/app/drawer/NavigationDrawerFragmentPresenter.kt:262]: home is not always an option, the user might click on switch profile from any menu screen like option or help, creating a different issue for this.

Comment (rt4914) [reply app/src/main/java/org/oppia/app/drawer/NavigationDrawerFragmentPresenter.kt:262]: @anandwana001 Please reference issue number here.

File: app/src/main/java/org/oppia/app/drawer/ExitProfileDialogFragment.kt [hunk 3]
```diff
@@ -0,0 +1,70 @@
...
+import android.content.Context
+import android.content.Intent
+import android.os.Bundle
+import androidx.appcompat.app.AlertDialog
+import androidx.appcompat.view.ContextThemeWrapper
+import androidx.fragment.app.DialogFragment
+import org.oppia.app.R
+import org.oppia.app.profile.ProfileChooserActivity
+
+/** [DialogFragment] that gives option to either cancel or exit current profile */
```
Comment (rt4914) [inline app/src/main/java/org/oppia/app/drawer/ExitProfileDialogFragment.kt]: Nit full stop: `/** [DialogFragment] that gives option to either cancel or exit current profile. */`

File: app/src/main/java/org/oppia/app/drawer/NavigationDrawerFragmentPresenter.kt (hunk 2 above)
Comment (rt4914) [reply app/src/main/java/org/oppia/app/drawer/NavigationDrawerFragmentPresenter.kt:262]: Also, if that is the case then shouldn't `markHomeMenuCloseDrawer ` be renamed to something else which does not include `Home`

**Review by rt4914 — CHANGES_REQUESTED** [review]
Few nits/questions before final approval.

File: app/src/main/java/org/oppia/app/drawer/NavigationDrawerFragmentPresenter.kt (hunk 2 above)
Comment (anandwana001) [reply app/src/main/java/org/oppia/app/drawer/NavigationDrawerFragmentPresenter.kt:262]: #1762 is the issue number and the name can be change in that issue as this complety solves there, changing name here might create confusion.

File: app/src/main/java/org/oppia/app/drawer/ExitProfileDialogFragment.kt (hunk 3 above)
Comment (anandwana001) [reply app/src/main/java/org/oppia/app/drawer/ExitProfileDialogFragment.kt]: Done

**Review by rt4914 — APPROVED** [review]
LGTM
