### PR TITLE
Fix part of #4470, Fix #4471, Fix 4474: Handle configuration change using onSavedInstance.

### LINKED ISSUE #4471: Handle configuration change for text input based interactions
Handle configuration change for following text input based interactions in exploration player and question player:
- FractionInputInteraction
- NumericInputInteraction
- TextInputInteraction
- MathExpressionInteraction
- RatioExpressionInteraction

**Steps to reproduce the bug**:

1. Open app and visit `Prototype Exploration`
2. Answer first question (or any question where you have enter value in an input-box)
3. In text-based interaction, enter the value (DO NOT SUBMIT THE ANSWER)
4. Now rotate your screen
5. Notice that the entered text value has been cleared.

**Expected behaviour**
The last entered text-value should persist during rotation, so that user can continue directly from there.

**Similar issues**
#4474
#4472
#4473

### LINKED ISSUE #4474: Handle configuration change for SelectionInputInteraction [Blocked on #4470]
Handle configuration change for SelectionInputInteraction such that when user rotates the device, last selected answer of user persists. 

**Steps to reproduce the bug**:

1. Open app and visit `Prototype Exploration`
2. Answer first question with 1/2
3. In multiple selection question, select any option (do not click SUBMIT)
4. Now rotate your screen
5. Notice that the selection has been cleared.

**Expected behaviour**
The last selected value should persist during rotation, so that user doesn't need to re-select the same values.

**Similar issues**
#4471
#4472
#4473

### PR DESCRIPTION
**Pull request by Vishwajith-Shettigar**
## Explanation
Fix part of #4470. 
Fixes #4471.
Fixes #4474

This PR enables the retention of input when the device configuration changes using onSavedInstance.

List of interactions covered in this PR:
1. FractionInputInteraction
2. NumericInputInteraction
3. TextInputInteraction
4. MathExpressionInteraction
5. RatioExpressionInteraction

List of interactions not covered in this PR (Covered here #5478):
1. Image Region selection interaction.
2. Drag and Drop interaction.

## Essential Checklist

- [x] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] Any changes to [scripts/assets](https://github.com/oppia/oppia-android/tree/develop/scripts/assets) files have their rationale included in the PR explanation.
- [x] The PR follows the [style guide](https://github.com/oppia/oppia-android/wiki/Coding-style-guide).
- [x] The PR does not contain any unnecessary code changes from Android Studio ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#undo-unnecessary-changes)).
- [x] The PR is made from a branch that's **not** called "develop" and is up-to-date with "develop".
- [x] The PR is **assigned** to the appropriate reviewers ([reference](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR#clarification-regarding-assignees-and-reviewers-section)).

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots for portrait/landscape for both a tablet & phone of the before & after UI changes
- For the screenshots above, include both English and pseudo-localized (RTL) screenshots (see [RTL guide](https://github.com/oppia/oppia-android/wiki/RTL-Guidelines))
- Add a video showing the full UX flow with a screen reader enabled (see [accessibility guide](https://github.com/oppia/oppia-android/wiki/Accessibility-A11y-Guide))
- For PRs introducing new UI elements or color changes, both light and dark mode screenshots must be included
- Add a screenshot demonstrating that you ran affected Espresso tests locally & that they're passing

### CODE REVIEW

**Comment by Vishwajith-Shettigar** [comment]
@adhiamboperes, take a pass.

**Comment by Vishwajith-Shettigar** [comment]
@adhiamboperes, PTAL.

File: app/src/main/java/org/oppia/android/app/player/state/StateFragment.kt [hunk 1]
```diff
@@ -86,6 +90,12 @@ class StateFragment :
   ): View? {
     val args =
       arguments?.getProto(STATE_FRAGMENT_ARGUMENTS_KEY, StateFragmentArguments.getDefaultInstance())
+
+    val userAnswerState = savedInstanceState?.getProto(
+      STATE_FRAGMENT_STATE_KEY,
+      UserAnswerState.getDefaultInstance()
+    ) ?: UserAnswerState.getDefaultInstance()
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/player/state/StateFragment.kt:97]: If you're already setting a default, you don't need to add an elvis operator. Instead, add a null check in the presenter. This means that `handleCreateView()` should expect a nullable `userAnswerState`.

File: app/src/main/java/org/oppia/android/app/player/state/StateFragmentPresenter.kt [hunk 2]
```diff
@@ -365,6 +367,9 @@ class StateFragmentPresenter @Inject constructor(
   private fun subscribeToAnswerOutcome(
     answerOutcomeResultLiveData: LiveData<AsyncResult<AnswerOutcome>>
   ) {
+    if (stateViewModel.getCanSubmitAnswer().get() == true) {
+      recyclerViewAssembler.resetUserAnswerState()
+    }
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/player/state/StateFragmentPresenter.kt]: I don't understand why this is required. Could you please add a comment to explain it?

File: app/src/main/java/org/oppia/android/app/player/state/answerhandling/InteractionAnswerHandler.kt [hunk 3]
```diff
@@ -26,6 +28,11 @@ interface InteractionAnswerHandler {
   fun getPendingAnswer(): UserAnswer? {
     return null
   }
+
+  /** Returns the current answer. */
```
Comment (adhiamboperes) [inline app/src/main/java/org/oppia/android/app/player/state/answerhandling/InteractionAnswerHandler.kt]: Is "current selected answer" more descriptive?

File: model/src/main/proto/exploration.proto [hunk 4]
```diff
@@ -420,3 +420,32 @@ enum CheckpointState {
...
+enum AnswerErrorCategory {
+  // Corresponds to the pending answer having no error.
+  NO_ERROR_UNSPECIFIED = 0;
+
+  // Corresponds to errors that may be found while the user is trying to input an answer.
+  REAL_TIME = 1;
+
+  // Corresponds to errors that may be found only when a user tries to submit an answer.
+  SUBMIT_TIME = 2;
+}
```
Comment (adhiamboperes) [inline model/src/main/proto/exploration.proto]:
```suggestion
enum AnswerErrorCategory {
   // The error is unknown or not specified.
 ERROR_UNSPECIFIED = 0;
  
  // Corresponds to the pending answer having no error.
  NO_ERROR = 1;

  // Corresponds to errors that may be found while the user is trying to input an answer.
  REAL_TIME = 2;

  // Corresponds to errors that may be found only when a user tries to submit an answer.
  SUBMIT_TIME = 3;
}
```
no_error, and the unspecified state do not mean the same thing in protobuf. unspecified is the default fallback for enums, and unrecognized enum is created by the compiler for a value that is out of bounds(-1), or unknown.

File: model/src/main/proto/exploration.proto [hunk 5]
```diff
@@ -420,3 +420,32 @@ enum CheckpointState {
...
+
+// Corresponds to a raw representation of the current answer entered by the user
+// which is used to retain state on configuration changes
+message UserAnswerState {
+  AnswerErrorCategory answer_error_category = 1;
+  oneof answer_input_type{
+    ItemSelectionAnswerState item_selection = 2;
+
+    // A raw answer entered by user in a text-based interactions.
+    string textual_answer = 3;
```
Comment (adhiamboperes) [inline model/src/main/proto/exploration.proto]: Maybe?
```suggestion
    string text_input_answer = 3;
```

File: model/src/main/proto/exploration.proto [hunk 6]
```diff
@@ -420,3 +420,32 @@ enum CheckpointState {
...
+message ItemSelectionAnswerState {
+  repeated int32 selected_indexes = 1;
+}
+
+// Corresponds to a raw representation of the current answer entered by the user
+// which is used to retain state on configuration changes
+message UserAnswerState {
+  AnswerErrorCategory answer_error_category = 1;
+  oneof answer_input_type{
+    ItemSelectionAnswerState item_selection = 2;
```
Comment (adhiamboperes) [inline model/src/main/proto/exploration.proto]: Don't forget to add docs for all the fields.

File: app/src/main/res/layout/item_selection_interaction_items.xml [hunk 7]
```diff
@@ -27,13 +27,13 @@
...
-      android:checked="@{viewModel.answerSelected}"
+      app:buttonTint="@{viewModel.isEnabled ? @color/component_color_shared_item_selection_interaction_enabled_color : @color/component_color_shared_item_selection_interaction_disabled_color}"
       android:clickable="false"
       android:enabled="@{viewModel.isEnabled}"
       android:focusable="false"
       android:labelFor="@id/item_selection_contents_text_view"
-      app:buttonTint="@{viewModel.isEnabled ? @color/component_color_shared_item_selection_interaction_enabled_color : @color/component_color_shared_item_selection_interaction_disabled_color}" />
-
+      android:checked="@{viewModel.answerSelected}"
+      />
```
Comment (adhiamboperes) [inline app/src/main/res/layout/item_selection_interaction_items.xml]: Is the formatting correct?

**Review by adhiamboperes — CHANGES_REQUESTED** [review]
Thanks @Vishwajith-Shettigar! I have looked at the implementation of the textinput answer state, and so far the approach looks like it is in the right direction. PTAL at some highlevel comments that I have.

File: app/src/main/java/org/oppia/android/app/player/state/StateFragment.kt (hunk 1 above)
Comment (Vishwajith-Shettigar) [reply app/src/main/java/org/oppia/android/app/player/state/StateFragment.kt:97]: Thanks for the feedback! Can you explain the benefits of handling nullability in the presenter instead of using the Elvis operator in the fragment? I'm curious about the impact.

File: app/src/main/java/org/oppia/android/app/player/state/answerhandling/InteractionAnswerHandler.kt (hunk 3 above)
Comment (Vishwajith-Shettigar) [reply app/src/main/java/org/oppia/android/app/player/state/answerhandling/InteractionAnswerHandler.kt]: `selected` term align with only selection type interactions. That's the reason i kept as above.

File: app/src/main/java/org/oppia/android/app/player/state/StateFragmentPresenter.kt (hunk 2 above)
Comment (Vishwajith-Shettigar) [reply app/src/main/java/org/oppia/android/app/player/state/StateFragmentPresenter.kt]: That's redundant check. Removed.

File: app/src/main/res/layout/item_selection_interaction_items.xml (hunk 7 above)
Comment (Vishwajith-Shettigar) [reply app/src/main/res/layout/item_selection_interaction_items.xml]: I intentionally did that because checkboxes weren't showing the checked state when the user rotated the device. After investigating for days, I found that it was because of the `buttontint `binding adapter. After changing the position of `checked `and `buttontint`, it works."

File: model/src/main/proto/exploration.proto (hunk 5 above)
Comment (Vishwajith-Shettigar) [reply model/src/main/proto/exploration.proto]: Done.

File: model/src/main/proto/exploration.proto (hunk 6 above)
Comment (Vishwajith-Shettigar) [reply model/src/main/proto/exploration.proto]: Okay.

File: model/src/main/proto/exploration.proto (hunk 4 above)
Comment (Vishwajith-Shettigar) [reply model/src/main/proto/exploration.proto]: Thanks.

File: model/src/main/proto/exploration.proto [hunk 8]
```diff
@@ -421,31 +421,37 @@ enum CheckpointState {
...
-// Corresponds to a item selection answer that user has selected.
+// Represents the state of item selection answers that the user has selected.
 message ItemSelectionAnswerState {
+  // List of selected item indexes
   repeated int32 selected_indexes = 1;
 }
 
-// Corresponds to a raw representation of the current answer entered by the user
-// which is used to retain state on configuration changes
+// Represents the user's answer state, retaining state across configuration changes.
```
Comment (adhiamboperes) [inline model/src/main/proto/exploration.proto]:
```suggestion
// Represents the user's answer state, retained across configuration changes.
```

File: model/src/main/proto/exploration.proto [hunk 9]
```diff
@@ -421,31 +421,37 @@ enum CheckpointState {
   CHECKPOINT_UNSAVED = 3;
 }
 
-// Corresponds to a item selection answer that user has selected.
+// Represents the state of item selection answers that the user has selected.
 message ItemSelectionAnswerState {
+  // List of selected item indexes
```
Comment (adhiamboperes) [inline model/src/main/proto/exploration.proto]: Nits:
```suggestion
  // List of selected item indices.
```

I think indices is the correct plural of index.

**Review by adhiamboperes — COMMENTED** [review]
Looks like you have enough to go on right now. Please reasign when PR is ready, or if stuck on something.

File: app/src/main/res/layout/item_selection_interaction_items.xml (hunk 7 above)
Comment (adhiamboperes) [reply app/src/main/res/layout/item_selection_interaction_items.xml]: That sounds good.

Re: formatting - isn't the closing tag `/>` supposed to be at the end of the previous line 35?

File: app/src/main/java/org/oppia/android/app/player/state/StateFragment.kt (hunk 1 above)
Comment (adhiamboperes) [reply app/src/main/java/org/oppia/android/app/player/state/StateFragment.kt:97]: I suggested it here for two reasons:
1. Returning `UserAnswerState.getDefaultInstance()` if the saved state arguments is null, is making a dangerous assumption that`UserAnswerState` is always available. Technically, on first screen open before any config change, it will always return the DefaultInstance.

I looked at the presenter, and I saw that you are directly using the passed UserAnswerState without first checking if it is default or not(can be safely ignored if default)

But with null check, you are forced to pay attention to the variable, and handle the situation where it is null. This way it is easier to catch errors, even in tests.

File: app/src/main/java/org/oppia/android/app/player/state/answerhandling/InteractionAnswerHandler.kt (hunk 3 above)
Comment (adhiamboperes) [reply app/src/main/java/org/oppia/android/app/player/state/answerhandling/InteractionAnswerHandler.kt]: Ah I see. Maybe use  "pending answer" to show that it is the input that has not been submitted.

File: model/src/main/proto/exploration.proto (hunk 9 above)
Comment (Vishwajith-Shettigar) [reply model/src/main/proto/exploration.proto]: Both are plural, but indices commonly used in technical contexts. Changed.

File: app/src/main/java/org/oppia/android/app/player/state/StateFragment.kt (hunk 1 above)
Comment (Vishwajith-Shettigar) [reply app/src/main/java/org/oppia/android/app/player/state/StateFragment.kt:97]: Default UserAnswerState would make no difference in any interactions, that's the reason i directly passed.

File: app/src/main/java/org/oppia/android/app/player/state/answerhandling/InteractionAnswerHandler.kt (hunk 3 above)
Comment (Vishwajith-Shettigar) [reply app/src/main/java/org/oppia/android/app/player/state/answerhandling/InteractionAnswerHandler.kt]: Okay.

File: app/src/main/res/layout/item_selection_interaction_items.xml (hunk 7 above)
Comment (Vishwajith-Shettigar) [reply app/src/main/res/layout/item_selection_interaction_items.xml]: Done.

File: model/src/main/proto/exploration.proto (hunk 8 above)
Comment (Vishwajith-Shettigar) [reply model/src/main/proto/exploration.proto]: Done.

**Comment by Vishwajith-Shettigar** [comment]
@adhiamboperes, PTAL.

**Review by adhiamboperes — APPROVED** [review]
Thanks @Vishwajith-Shettigar! LGTM.

**Comment by adhiamboperes** [comment]
@Vishwajith-Shettigar, which part of #4470 has not been completed in this PR?

Please also check that the PR title and explanation has all the issue numbers.

**Comment by Vishwajith-Shettigar** [comment]
> @Vishwajith-Shettigar, which part of #4470 has not been completed in this PR?
> 
> Please also check that the PR title and explanation has all the issue numbers.

Updated PR description and title. Thank you.
